### ISSUE TITLE
Improved Hunter's Mark is being overidden by unimproved Hunter's Mark

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#100]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
As the title says

**How to reproduce:**
Get two hunters, one with improved and one without, improved cast it > unimproved cast it
the latest cast one will apply over stronger ones

**How it should work:**
Strongest debuff should co exist with the weaker one, but only the strongest should apply with ability rank > talent rank 3 > 2 > 1 > 0 

**Database links:**
https://www.wowhead.com/wotlk/spell=19423/improved-hunters-mark#modifies

**Comment by Afgann** [comment]
fixed
