### ISSUE TITLE
[spell] Mind Flay

### ISSUE THREAD

**Issue by buza-me** [gamefreedomgit/Frostmourne#1001]
**Description:**
Mind Flay does two damage ticks instead of three in most cases.

**How to reproduce:**
Cast Mind Flay while shielded or when 100% pushback immune. I use combat log events to play sound on Mind Flay ticks.
[This WA](https://pastebin.com/bYCLKVFQ) can do it, currently water drop sound.

**How it should work:**
Mind Flay channeling should result in 3 damage instances.

**Database links:**
[Mind Flay](https://www.wowhead.com/wotlk/spell=48156/mind-flay)

**Comment by UltraNix** [comment]
@buza-me What's your haste rating? Are you using some haste talents/buffs?

**Comment by buza-me** [comment]
@UltraNix [gear and talents](https://eightyupgrades.com/set/96USXbBQ6dcErTRQA8jZuP). Not using any haste buffs.
  
I did not test Mind Sear but I have a feeling it probably is broken too just like Mind Flay and Penance.

**Comment by UltraNix** [comment]
Fixed.
