### ISSUE TITLE
Disenchanting Sunwell TW items does not give Abyss Crystals

### ISSUE THREAD

**Issue by saree32** [gamefreedomgit/Frostmourne#1004]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When you disenchant an epic item from Sunwell TW, you do not get anything.
When we made a ticket about this in game, we were told GMs could not help and to make a bug report. 

**How to reproduce:**
Go into Sunwell TW, kill a boss, loot, try disenchanting an item, watch it come up empty. 

**How it should work:**
Should give abyss crystals.

**Database links:**

**Comment by saree32** [comment]
UPDATE: You cannot disenchant Sunwell TW items inside Sunwell. You CAN disenchant them and get abyss crystals outside of Sunwell. Strange, but works okay

**Comment by Afgann** [comment]
fixed
