### ISSUE TITLE
[spell] Ferocious Bite

### ISSUE THREAD

**Issue by w3kur** [gamefreedomgit/Frostmourne#1005]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
ferocious bite takes 30 energy with clearcast proc (i think its just remove 35 energy cost to use fero but additional 30 energy for more dmg  takes (ferocious takes 65 energy for max damage))
https://streamable.com/atqmj7

**How to reproduce:**
just use it with clearcast proc

**How it should work:**
it should take 0 energy with clearcast proc 

**Database links:**
https://www.wowhead.com/wotlk/spell=48577/ferocious-bite

**Comment by Afgann** [comment]
fixed
