### ISSUE TITLE
Loop for farming infinite green item

### ISSUE THREAD

**Issue by paygoz** [gamefreedomgit/Frostmourne#1006]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
In Icecrown on right of aldurthar there are some moob who have a void as enslaved/minion, if you kill the minion and go away the minion respawn without a cd so you can farm infinite time green item each time.

**Database links:**
https://www.wowhead.com/wotlk/npc=32260/enslaved-minion

**Comment by UltraNix** [comment]
Fixed.
