### ISSUE TITLE
Naxxramas. Heigan the Unclean platform bug

### ISSUE THREAD

**Issue by wotlkenjoyer** [gamefreedomgit/Frostmourne#101]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
People can find a safe spot where they not getting  green posion damage and attack the boss ignoring the mechanic

**How to reproduce:**
[Screenshot](https://i.imgur.com/hC14SRK.png)

Place the boss at the bottom corner of the platform and stack everyone  in opposite corner, like on screenshot.  

**How it should work:**
Heigan debuff aura range should be much larger than now,  
[Spell Disruption](https://www.wowhead.com/wotlk/spell=29310/spell-disruptionl)

Spell Disruption aura should cover more than just platform,   so you can't place the boss and be safe from poison at the same time. 

[Example](https://i.imgur.com/3MMxraZ.png)

**Comment by Tednugg** [comment]
This is not a bug, it's just the most efficient strategy to kill the boss, it worked on original wrath and it also works on wotlk classic. https://youtu.be/qk0z3zCOVfg?si=fBzyp_cZlhqh_vlP&t=670 check this video for evidence.
