### ISSUE TITLE
Leave No One Behind

### ISSUE THREAD

**Issue by Paulioskinas** [gamefreedomgit/Frostmourne#1011]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk) https://www.wowhead.com/wotlk/quest=12512/leave-no-one-behind

**Description:**
Use bandage on 3 crusaders and escort them to Dr. Rogers 1 by 1.

**How to reproduce:**
Once crusader is bandaged, proceed to escort him > no partial completion registered.

**How it should work:**
Once 1 of 3 crusaders is escorted, partial completion should be registered.

**Database links:**
https://www.wowhead.com/wotlk/quest=12512/leave-no-one-behind

**Comment by ChronoWM** [comment]
Confirmed; after escorting any of the NPCs player does not get the credit for it.
Cannot be completed.

**Comment by PanJanuszek** [comment]
![image](https://github.com/user-attachments/assets/f57c3a49-200c-47f7-8bd2-424aa7692f04)
![image](https://github.com/user-attachments/assets/a59ab6e9-8312-4ff4-b44d-001c830dd69a)

 cannot reproduce, did it 1 by 1 and everytime npc is following player and i got credit when he reached "imp mark" - (not visible for players)

cannot reproduce
