### ISSUE TITLE
Terrorclaw does not grant reputation below 11,999 honored

### ISSUE THREAD

**Issue by erikpowa** [gamefreedomgit/Frostmourne#1013]
[Terrorclaw](https://www.wowhead.com/tbc/npc=20477/terrorclaw)

**Description:**
Terrorclaw should yield Cenarion Expedition honor

**How to reproduce:**
kill Terrorclaw at Honored (below 11999), 0 reputation gain

**How it should work:**
it should yield reputation

**Database links:**

**Comment by WhitemaneIsa** [comment]
![grafik](https://github.com/gamefreedomgit/Frostmourne/assets/164479303/c309f509-5432-45dd-9131-51fc54406b7d)

**Comment by erikpowa** [comment]
![](https://i.imgur.com/h6hqqHG.png)

**Comment by erikpowa** [comment]
![](https://i.imgur.com/vUz1Yf0.png)

**Comment by erikpowa** [comment]
forexample
11990 -> kill +7 -> 11997
11997 -> kill +7 -> 11999, only get +2 because rep gain stops at honored

**Comment by WhitemaneIsa** [comment]
What is your currrent rep?
