### ISSUE TITLE
[Quest][TBC] Fumping - does not work

### ISSUE THREAD

**Issue by erikpowa** [gamefreedomgit/Frostmourne#1014]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)
https://www.wowhead.com/quest=10929/fumping
https://www.wowhead.com/item=31810/fumper

**Description:**
whenever you're trying to use Fumper in Bone Wastes, quest mobs only appear for milisec then disappers, makes it impossible to complete it

**How to reproduce:**
try to do the quest

**How it should work:**

**Database links:**

**Comment by Enteroox** [comment]
Description:
The quest is about summoning worms from underground, then murdering them and taking their bones.
The quest item for this task may sometimes summon other creatures (Sand Gnomes, who'd know they exist!), other times this worm creature.

How to reproduce:
Go and pick up the quest, head to the designated area in Terrokar Forest, and use the said quest item. Upon doing so you'll either summon a Sand Gnome or the [Mature Bone Sifter](https://www.wowhead.com/wotlk/npc=22482/mature-bone-sifter). In the cases where you summon the [Mature Bone Sifter](https://www.wowhead.com/wotlk/npc=22482/mature-bone-sifter), it'd appear and then instantly disappear.
You briefly enter combat and as soon as it vanishes, leave combat.

Here's a minute-long video of me performing this quest. You'll notice at the end of the issue I am mentioning in my post here.
https://www.youtube.com/watch?v=HuPHunvvMQQ

How it should work:
The [Mature Bone Sifter](https://www.wowhead.com/wotlk/npc=22482/mature-bone-sifter) should not disappear, instead, it should remain and die in vain and drop [Mature Bone Sifter Carcass](https://www.wowhead.com/wotlk/item=31814/mature-bone-sifter-carcass), which we require for our quest's progression.

Database links:
Quest: [Fumping](https://www.wowhead.com/wotlk/quest=10929/fumping)
Quest item: [Fumper](https://www.wowhead.com/wotlk/item=31810/fumper)
Quest monster: [Mature Bone Sifter](https://www.wowhead.com/wotlk/npc=22482/mature-bone-sifter)
Quest item (loot) from the Mature Bone Sifter: [Mature Bone Sifter Carcass](https://www.wowhead.com/wotlk/item=31814/mature-bone-sifter-carcass)
