### ISSUE TITLE
DK Unholy talent "Ravenous Dead" bugged

### ISSUE THREAD

**Issue by Sylanha** [gamefreedomgit/Frostmourne#1015]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The talent "Ravenous Dead" which you can find in the Unholy Tree is bugged in the sense that it doesn't give the right amount of strength it is supposed to give.

**How to reproduce:**
What I did here is, that I took "Glyph of the Ghoul" (which works perfectly fine) giving an additional 40% of the DK's strength and stamina to the ghoul and looked at that amount of strength my ghoul has (1662 with my gear now) and compared it to when I put 2/3 points into Ravenous Dead (here my ghoul gets 40% of the DK's strength and stamina; in adition the DK's total strength gets raised by 2% so in the end this talent should even give the ghoul more strength than the Glyph).

The strength my ghoul has from "Glyph of the Ghoul": 1662 strength
The strength my ghoul has from 2/3 Ravenous Dead: 1541 strength
The strength my ghoul has without Glyph or Ravenous Dead: 1178 strength

**How it should work:**
The formula for the Glyph is: 
(Ghoul str) + (DK str) x 0,4 = x
with x being the Ghouls Str with the Glyph of the Ghoul (40% added DK's str to the Ghoul)

So basically the Glyph is doing it right. 
Take my DK's Base strength without any Talents or Glyph: 1210
and put it into the fomula
1178 + 1210 x 0,4 = 1662 strength

This outcome is how it works and should work
The same applies to stamina.
The talent Ravenous Dead is even fucking up more when applying to stamina. The source of the stamina it takes from here is even more scuffed, since it doesn't take the DK's stamina value, but it originates from the GHOULS additional stamina that he gains from external buffs.
Also the talents Ravenous Ghoul should apply on Army of the Dead as it says "ghouls" in the tooltip
Also the talent "Night of the Dead"'s 90% area of effect damage reduction should apply to Army of the Dead and not have them instantly die to Fire Nova or any other AoE damage.
Please have a look into it.

**Database links:**
https://youtu.be/EOa2Ak12RDw

**Comment by Afgann** [comment]
fixed
