### ISSUE TITLE
Haste cap of ghoul bugged

### ISSUE THREAD

**Issue by Sylanha** [gamefreedomgit/Frostmourne#1017]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Haste cap of ghoul bugged

**How to reproduce:**
Get yourself as much haste as possible (Meelehaste + Bloodlust + Unholy Presence + Potion of Speed + Ghoulfrenzy + etc).

**How it should work:**
The ghoul should not be hastecapped and the meeleswing timer should progressively be effected by additional haste. (Army had the same issue but got fixed)

**Database links:**
https://youtu.be/sjJnfCehSto

**Comment by Afgann** [comment]
fixed
