### ISSUE TITLE
Soul Preserver still doesnt work properly

### ISSUE THREAD

**Issue by Nihaobeachez** [gamefreedomgit/Frostmourne#1018]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** 
As title says, still doesnt work properly. It was already reported back in February https://github.com/gamefreedomgit/Frostmourne/issues/219
Its not 2% per cast, its 2% per Target hit, that includes the Gylph of Holy Light (6 targets), Wild Growth (max 6 Targets), Chain Heal (4 Target). For some Classes this Trinket is BiS throughout several Tiers. For Druids T7, for Shamans till T9 and for Paladins even till T10 if it would work correctly.
![image](https://github.com/gamefreedomgit/Frostmourne/assets/96308500/4958e57a-9d75-4804-9c4e-dd6cdc7c424d)
https://classic.warcraftlogs.com/reports/d7BMacXCTGhJzRtp#fight=2&type=auras&target=32&ability=60513
This log shows 12% Soul Preserver Proccrate as Hpal which adds up with Glyph of Holy Light proccing it (technically 11.4% but you get the idea)

**How to reproduce:** Create a Healer with a Spell/Gylph that hits multiple Targets.

**How it should work:** As above stated, proccrate should be for each target hit, not per cast. It should NOT procc on Hots. It also doesnt have any form of ICD

**Database links:** https://db.rising-gods.de/?item=37111

**Comment by Afgann** [comment]
fixed
