### ISSUE TITLE
Hunter Pet Dying in Twilight Portal in Obsidium Sanctum 3D

### ISSUE THREAD

**Issue by saree32** [gamefreedomgit/Frostmourne#1019]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
[Instance: OS 25 3D] Hunter pet dies to Twilight Torment as soon as you enter the twilight portal for Vesperon. It seems the pet takes full dmg from Twilight Torment and gets pretty much 2 shot by this mechanic. It also seems this is only happening to hunter pets - locks and other pet classes seem unaffected. 

**How to reproduce:**
Enter Vesperon's portal as a hunter and watch your pet die to Twilight Torment as you DPS the Vesperon add. :(

**How it should work:**
Pets should have a 90% avoidance to aoe spells. 

**Database links:**
Under "New Stat Scaling": https://www.wowhead.com/wotlk/guide/hunter-pets-taming-feeding-exotic

**Comment by UltraNix** [comment]
Fixed.
