### ISSUE TITLE
Naxxramas. Heigan the unclean  combat bug.

### ISSUE THREAD

**Issue by wotlkenjoyer** [gamefreedomgit/Frostmourne#102]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

This one is very simple,  if you wiped on Heigan, nobody can enter the raid because it says  combat is till going. Nobody inside, everyone released, but boss still doing something and dont want to reset, i saw it already before on other projects, we used to diband the group and get soft reset ( wait 30 minutes without a group) then rebuild.

**Comment by wotlkenjoyer** [comment]
failed 3 test runs in past 3 weeks because of that, with 3 different groups.  Basically if you wiped there thats over, group disband

**Comment by wotlkenjoyer** [comment]
@Afgann   need more information about this one?  any help i can provide?

**Comment by Afgann** [comment]
@wotlkenjoyer in what phase was the boss during wipe? or is it completely random?

**Comment by wotlkenjoyer** [comment]
> @wotlkenjoyer in what phase was the boss during wipe? or is it completely random?

it happens after the dance phase,    second phase, when he teleports to the platform and everyone have to run fast 

if you wiped there, you release and can't enter, encounter is still going, everyone released and etc. 

I saw the same bug on warmane frostmourne season 2 , but later they fixed that.

**Comment by wotlkenjoyer** [comment]
it seems like even if everyone dies, he still stand there and does something, dance event still going or something.

**Comment by wotlkenjoyer** [comment]
> @wotlkenjoyer in what phase was the boss during wipe? or is it completely random?

You can ask GM Tide,  he was doing  /kill command for us twice,  so we could proceed the raid during our testing.
