### ISSUE TITLE
Hunter's Explosive Trap on Sapphiron

### ISSUE THREAD

**Issue by parsafr0st** [gamefreedomgit/Frostmourne#1020]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Basiclly when u put ur Explosive trap under the boss it gets triggered but it just disappears, so there will be no debuff on the boss, its a pretty simple problem so i wont need to go into more details.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
Did it only happen on sapphiron?

**Comment by Nuy** [comment]
> Did it only happen on sapphiron?

I can confirm this happens on Sapphiron. Could be the same with Sartharion and Malygos (dragon bosses in general) but I'm not sure about them.

**Comment by Nuy** [comment]
We just did SWP, Malygos and OS in guilld and traps on Brutallus are also fked and his hitbox is really weird. It's the same with Malygos but on Sartharion it seems all fine.

**Comment by parsafr0st** [comment]
at that time that i submitted this issue i had only done Saph, but yes, the dragon bosses or the boss with big and wide hit boxes are like this, u have to put the trap almost exactly at the center of the boss in order for it to work.
so... the hit boxes are broken or bugged.

**Comment by parsafr0st** [comment]
to be more exact the big hit boxes trigger the traps but the traps are too far away from the bosses to be affected.

**Comment by Afgann** [comment]
fixed
