### ISSUE TITLE
Azjol-Nerub Hardonox loot issue

### ISSUE THREAD

**Issue by ChronoWM** [gamefreedomgit/Frostmourne#1021]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Players defeated Hardonox in RHC, received emblem of heroism but did not receive the dropped item.
Quoting from the players who had the issue:

> Disappearing loot in an Azjol-Nerub RHC run. The Hadronox tank trinket dropped but did not show up in the chat log at all - the icon for need/greed showed up, but after clicking it just disappeared and nothing about the item showed up in the chat log. Afterwards the boss' corpse was "empty" (it  read *skinnable* underneath), but nobody in the party got loot.
I'm attaching a link to the screenshots I took after: https://imgur.com/a/linM9L6

**Comment by WhitemaneIsa** [comment]
The screenshot doesn't exist.. Can you post a screenshot of the screenshot? 

I have seen/heard of this issue a few times, did someone potentially leave the group in the meantime or disconnect?
@ChronoWM

**Comment by ChronoWM** [comment]
Sadly i do not have the screenshot anymore, but it could show that players received the emblems in chat for that specific boss however, no other loot was there.

**Comment by WhitemaneIsa** [comment]
I'll close it until we get a proper report then.
