### ISSUE TITLE
Conflagrate is not working consistently.

### ISSUE THREAD

**Issue by bobeanudani** [gamefreedomgit/Frostmourne#1023]
The link for immolate:
https://www.wowhead.com/wotlk/spell=348/immolate

The link for conflagrate:
https://www.wowhead.com/wotlk/spell=17962/conflagrate

**Description:**

There's a problem with the warlock spell Conflagrate from the destruction spec. After you cast immolate, an instant damage spell not a projectile with travel time, you should be able to cast conflagrate straight away.
The problem is sometimes is available and sometimes you have to wait a second or 2 before it becomes available.
The main problem being that you can't guess when the spell will be available to use.

**How to reproduce:**
Cast immolate on a target and then try to cast conflagrate. There's like a 70% chance (from my experience) you can't cast conflagrate right away.

**How it should work:**
Conflagrate should be available to cast as soon as immolate is on the target.

**Comment by Galatoa** [comment]
I can confirm having exactly the same issue, you lose on average a GCD worth of spellcasting between Immolate and waiting for Conflagrate to become available.
On your average boss fight that's 15-30 GCDs worth of dps dropped, possibly even more depending on the boss and on the raid damage or you can reduce that by overlapping the last 1-2 secs of an Immolate with the next one which is not ideal either.

**Comment by Psychh** [comment]
bump

**Comment by Afgann** [comment]
fixed
