### ISSUE TITLE
Lagg and Delay in World/Bgs/Arenas

### ISSUE THREAD

**Issue by Chino6969** [gamefreedomgit/Frostmourne#1024]
There is a really big Delay in pvp on this Server even with a low ms!
-Players walking in stuns
-You cant hit players even if they near you
-Spells "arrive" 2 sec later on the target
- You can never Backstab or shred players from behind cuz of the delay.
literally impossible to play pvp!

Should get a prio 1 on fixing cuz its impossible to play pvp, otherwise u will lose all pvp players
greetings

**Comment by UltraNix** [comment]
Fixed.
