### ISSUE TITLE
Sartharion dead with 2 drakes (10m Ascended)

### ISSUE THREAD

**Issue by D4NTh** [gamefreedomgit/Frostmourne#1025]
**Description:**
We killed Sartharion on 10m Ascended with 2 drakes up, and didn't give us loot from 2drakes https://prnt.sc/lF-dZ5mHdqNv. (https://prnt.sc/i9kyGxNg0kcW this is the dps chart as proof that we killed Sartharion with 2 drakes up)

**How it should work:**
10m Ascended should drop loot from 25m version of the raid. In this case it should have dropped atleast one item from the 2 drakes list. 

**Database links:**
https://www.wowhead.com/wotlk/guide/raids/obsidian-sanctum/loot

**Comment by wotlkenjoyer** [comment]
Exactly same for our group, two weeks in a row we getting only Sartharion loot + x1 ascended 25man normal loot piece
**But we not getting 1d and 2d loot table pieces**

**Comment by Afgann** [comment]
fixed
