### ISSUE TITLE
Simple Living Bomb skill bug

### ISSUE THREAD

**Issue by realdanger** [gamefreedomgit/Frostmourne#1026]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When using the fire mage skill: Living Bomb, you cannot exit pvp combat

**How to reproduce:**
Use Living Bomb on an enemy player. Both stop fighting. Until the skill ends you cannot exit combat.

**How it should work:**
After 5 or 6 seconds you should exit combat, even if you use damage over time on a player target. 
After these 5-6 seconds it says:
<leaving combat>
<entering combat>
instantly.

And you need to wait again the 5-6 seconds and thus ending the total 12 seconds ability of Living Bomb.

This is a big problem in pvp when after 5-6 seconds you should be able to mount up or use food/water to regenerate.

**Database links:**
https://www.wowhead.com/classic/spell=400613/living-bomb

**Comment by realdanger** [comment]
I think it got fixed with restart, lmao

**Comment by realdanger** [comment]
Actually Ignite talent might be the one doing this , keeping you in combat...

**Comment by realdanger** [comment]
No answer? Just closed?

**Comment by WhitemaneIsa** [comment]
> No answer? Just closed?

@realdanger Did I misunderstand your comment? I thought you meant it's the talent keeping you in combat as it's a dot and dot's do keep you in combat...?

**Comment by realdanger** [comment]
Wrong. You can check this on warmane too. 
If you use dots and talents that do dots and you run away from your target and not direct fighting. You should exit combat. I just sit in ESG for 12-15 seconds after I use one skill without being able to use mount. That's not how the game should work. But whatever...

**Comment by WhitemaneIsa** [comment]
Can you provide a proper source for that? We don't use other private servers as reference.

**Comment by realdanger** [comment]
In PvP, a player will leave combat if they have not attacked or been attacked for 5 seconds, or all the enemy characters that have attacked you are killed.

On https://wowwiki-archive.fandom.com/wiki/Combat#google_vignette

[deleted]
•
3y ago
The combat timer is 6 seconds. Dots don’t keep you in combat, just the initial cast keeps you in combat

https://www.reddit.com/r/classicwow/comments/nyj3vl/how_exactly_does_leaving_combat_work_in_pvp_tbc/


---


If you played the game before maybe you'd know this too.
