### ISSUE TITLE
High Inquisitor Whitemane is unkillable

### ISSUE THREAD

**Issue by Aeradel** [gamefreedomgit/Frostmourne#1027]
https://www.wowhead.com/wotlk/npc=3977/high-inquisitor-whitemane

This NPC in the Scarlet Monastery has had a bug preventing her from dying. I am unaware of the full context of it, but I see no hidden aura on her that I am able to remove to resolve it.

**Comment by WhitemaneIsa** [comment]
No further complaints/Info, closing.
