### ISSUE TITLE
Frost Lord Ahune event encounter

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#1028]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The whole combat event is tuned for ~ ulduar/toc gear. Ahune mobs are doing too much damage and spawning too many as well

**Comment by WhitemaneIsa** [comment]
This was already readjusted. Should be better now.
