### ISSUE TITLE
Race change in BGs is bugged

### ISSUE THREAD

**Issue by havingtoreportbugsiscancer** [gamefreedomgit/Frostmourne#1029]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When i queue BGs and get faction changed i cant see my gear, i see level 1 gear and shoulders in all races except Belf 

**How to reproduce:**
Queue BGs

**How it should work:**
Full items visible

**Database links:**

**Comment by havingtoreportbugsiscancer** [comment]
this is dumb having to report it here since its only happening to me basicly atm but i cant fix it, new client doesnt fix it, patch doesnt fix it

**Comment by WhitemaneIsa** [comment]
Any addons?

**Comment by havingtoreportbugsiscancer** [comment]
no addons instaled

**Comment by havingtoreportbugsiscancer** [comment]
my addon folder is full with "blizzard" addons, thats normal right? 
![image](https://github.com/gamefreedomgit/Frostmourne/assets/173417012/636143c7-c089-4946-862f-a91890a78031)

**Comment by havingtoreportbugsiscancer** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/173417012/bc1781be-c860-4c79-b1ab-43e63ec2c268)
deleting folder contents doesnt work and this is what i see in BGS
![image](https://github.com/gamefreedomgit/Frostmourne/assets/173417012/b6c7b82c-2370-426b-8b88-7f23118a4d3e)

**Comment by WhitemaneIsa** [comment]
Are you sure they are not actually just wearing no or low gear? A lot of people enter BGs with no gear, sadly.

**Comment by WhitemaneIsa** [comment]
No further info/complaints, closing.
