### ISSUE TITLE
Can't group

### ISSUE THREAD

**Issue by nivractlc** [gamefreedomgit/Frostmourne#1030]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by nivractlc** [comment]
Can no longer invite players who the system considers " too high" or " too low" level. Before server restart my 67 was grouped with an 80 and after restart I left party to combined into another party and now can none of us can invite each other if not same level range.

**Comment by Afgann** [comment]
fixed
