### ISSUE TITLE
Facing PVE Bug (Backstab/Ambush)

### ISSUE THREAD

**Issue by DYuuren** [gamefreedomgit/Frostmourne#1031]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** 

A system error appears and says you're not facing from behind the enemy.
(If you're out of combat then the facing bug will not trigger).

**How to reproduce:** 

1. Into combat with any already pulled mob.
2. Using any rogue ability which requiere staying behind them.
3. Stun him using Kidney shot, Cheap shot or Gouge.
4.  Try to use Backstab/Ambush

**How it should work:** Never trigger the system error while trying to use those abilities from behind a stunned mob

**Database links:**

#776

_Edit: I saw there is a closed thread with the same issue from some weeks ago. Can you verify if it is really solved? Im already having the same problem since I started to play this week._

**Comment by WhitemaneIsa** [comment]
@UltraNix Since you closed the https://github.com/gamefreedomgit/Frostmourne/issues/776 as fixed - can you have another look please?

**Comment by UltraNix** [comment]
@DYuuren What mob exactly?

**Comment by UltraNix** [comment]
Fixed.
