### ISSUE TITLE
Death Comes from Above

### ISSUE THREAD

**Issue by 0xRenegade** [gamefreedomgit/Frostmourne#1032]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Death Comes from Above quest bugged. Eye cannot analyze the chapel.

**How to reproduce:**
make DK, get the quest, try to analyze chapel with eye.

**How it should work:**
Quest should mark Chapel as analyzed

**Database links:**

**Comment by WhitemaneIsa** [comment]
![grafik](https://github.com/gamefreedomgit/Frostmourne/assets/164479303/322fd3a9-f593-4dfb-98f5-1f18d0e0a60e)
You must have done it in the wrong spot or something. If you have issues completing the quest feel free to open a ticket ingame so we can assist you with it and make sure you are doing it correctly.
