### ISSUE TITLE
Moonkin form passive mana

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1033]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
as the moonkin form states, it should only be single target crits that proc the mana gain.
currently it is proccing from aoe crits also as tested with Hurricane.

**How to reproduce:**
**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
