### ISSUE TITLE
Plagueheart robes set bonus bug

### ISSUE THREAD

**Issue by mebroski** [gamefreedomgit/Frostmourne#1035]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Warlock's Plagueheart robes is not counting toward set bonus

**How to reproduce:**
Unsure, /reload, logout, exiting games does not add robes to the set bonus

**How it should work:**

**Database links:**
https://gyazo.com/dfd2698d86afab9a47e999468a8ae919

**Comment by Godmatik** [comment]
do you have transmog for it?
iirc its just visual bug if so

**Comment by mebroski** [comment]
It is mogged, in that case it's most likely a visual bug

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/858
