### ISSUE TITLE
Quest - Kaw the Mammoth Destroyer

### ISSUE THREAD

**Issue by WhitemaneIsa** [gamefreedomgit/Frostmourne#1037]
**Description:**
Mammoth Bulls aren't mountable.

**Database links:**](https://www.wowhead.com/wotlk/quest=11879/kaw-the-mammoth-destroyer)

**Comment by PanJanuszek** [comment]
![image](https://github.com/user-attachments/assets/0b463a01-449a-454e-ba69-8ae4a86db7cb)
![image](https://github.com/user-attachments/assets/d0c8ffca-fad6-42f0-b32b-26124ad70f98)
![image](https://github.com/user-attachments/assets/e793d002-fb40-4449-8495-9c3d20e4189f)

Cannot reproduce

**Comment by Greywolf59** [comment]
I encountered the same problem today. Toon: Lykfar, Arms Warrior Human lvl 80. Abandoning the quest, closing the game and opening it again and taking the quest again did not help. @PanJanuszek
