### ISSUE TITLE
Mind controlled targets and spell ranks

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#1038]
Someone gets mind controlled by an NPC (such as Kel'thuzad)

Any spell or ability they use while MCed - it will often not use their max rank. Looks like it is using only their level 60 max rank of the ability.

Should use the maximum rank of spell available to them at level 80.

**Comment by Riztazz** [comment]
Is this still valid? I've recently made some changes that should have fixed it
