### ISSUE TITLE
Sunwell - Emblems

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#1039]
Sunwell 25m (heroic) bosses drop Emblems of Heroism.

Should be Emblems of Valor?

**Comment by WhitemaneIsa** [comment]
@itsemmastone

**Comment by RadeghostWM** [comment]
This is intended to combat loot oversaturation

**Comment by Godmatik** [comment]
Wat? This explanation makes no sense - you are literally selling items on the shop.
