### ISSUE TITLE
[PALADIN] Seal of Command cleave not proccing if attack deals a Killing blow

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1040]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Title

**How to reproduce:**
Use attacks such as Auto or Crusader Strike to deal a killing blow to an enemy with another nearby and notice no Seal of Command proc

**How it should work:**
Seal of Command should be proccing on the attack, regardless if it deals a Killing blow

**Database links:**
https://www.wowhead.com/wotlk/spell=33127/seal-of-command

**Comment by Afgann** [comment]
fixed
