### ISSUE TITLE
Bear armor

### ISSUE THREAD

**Issue by holyshryt** [gamefreedomgit/Frostmourne#1042]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
![Screenshot 2024-06-21 005855](https://github.com/gamefreedomgit/Frostmourne/assets/120144120/84a00c4d-cb67-44b1-8a66-463479b0b510)
![Screenshot 2024-06-21 005907](https://github.com/gamefreedomgit/Frostmourne/assets/120144120/aa311882-684f-403a-9f0f-9164508edfc4)
![Screenshot 2024-06-20 184826](https://github.com/gamefreedomgit/Frostmourne/assets/120144120/210f8f1e-597b-4aa4-9eae-3db616e5c73f)
![Screenshot 2024-06-20 184842](https://github.com/gamefreedomgit/Frostmourne/assets/120144120/55c193a6-13af-4199-94d6-666716fa2c0f)

**How to reproduce:**
bonus armor on cloaks are not appying at all in bear form

**How it should work:**
base form armor scales with bear form then add the bonus armor 

**Database links:**
https://www.reddit.com/r/classicwow/comments/wovagd/wrath_beta_bear_form_armor_scaling_question/

**Comment by holyshryt** [comment]
![Screenshot 2024-06-21 005620](https://github.com/gamefreedomgit/Frostmourne/assets/120144120/6b452471-0314-4b1e-ae7b-f5358087b44b)
this is a picture with the cloak enchant

**Comment by holyshryt** [comment]
![Screenshot 2024-06-21 012243](https://github.com/gamefreedomgit/Frostmourne/assets/120144120/760bb03c-2984-428f-a66b-a1dcc9437664)
![Screenshot 2024-06-21 012255](https://github.com/gamefreedomgit/Frostmourne/assets/120144120/632915ce-1d89-4f69-851b-d83504e68ae2)
 I know this is becoming a mess but tree form seems to not be recieveing the 409+ armor in tree form correctly

**Comment by Godmatik** [comment]
![dfgdfgdf](https://github.com/gamefreedomgit/Frostmourne/assets/37913400/0423fae7-53a5-4b4a-870b-5b45718dec41)


Post from Blizzard back during Wrath - seems intended.

**Comment by yeagerca** [comment]
The "Green" armor from an items bonus armor, enchantments, necks, rings, trinkets, and weapons is not affected by bear form, thick hide, or other tank armor multipliers.

In the case of an item having bonus armor, the "white" armor value that is supposed to be multiplied will be the same as any other cloak of the same item level.

**Comment by yeagerca** [comment]
> I have the same problem, though im not entirely sure if the problem is with the "enhanced" armor of the Icebound Cloak, the scaling of bear form or something else entirely.
> Somehow using the Icebound Cloak evaluates to 50 less total armor.
This does look like a bug.
Icebound Cloak should have more "white" armor that does scale with buffs. It should not evaluate lower than an item of equal item level, especially one of lower quality.
The correct amount of white armor for a ilvl 200 epic cloak is 150 armor. See: https://www.wowhead.com/wotlk/items/armor/cloaks/min-level:200/max-level:200

**Comment by holyshryt** [comment]
> ![dfgdfgdf](https://private-user-images.githubusercontent.com/37913400/341942979-0423fae7-53a5-4b4a-870b-5b45718dec41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTg2OTgsIm5iZiI6MTcxOTI5ODM5OCwicGF0aCI6Ii8zNzkxMzQwMC8zNDE5NDI5NzktMDQyM2ZhZTctNTNhNS00YjRhLTg3MGItNWI0NTcxOGRlYzQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA2NTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0NTE2YzM4ZDg0MjQwZjQwZjg0NmMwNTJhNDA0NmFiYTZlNjI4OWZiOGY1MGZhYzYxN2I5YTEwYWVkMmUyMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DsCi5Z9D0RJp6Yf-Swzv_1GdVuyuYqT4pmoWAEKIYe8)
> 
> Post from Blizzard back during Wrath - seems intended.

This isn’t what I’m talking about. I know it’s not going to get the bear multiplier. But it’s just not adding the extra 409 armor.

**Comment by Piootrek** [comment]
@holyshryt Can you check if this issue still exists? From my tests bonus armor is applied correctly.

**Comment by yeagerca** [comment]
@Piootrek 
Bugs Summary:
As demonstrated in Test 1 and Test 2, armor calculations are correct for most items. However, there are two bugs which apply to the custom-scaled Midsummer event cloaks.
1. All Midsummer cloaks have an incorrect amount of white armor for their scaled item level. They should have 150, but most have 137. Citation: https://www.wowhead.com/wotlk/items/armor/cloaks#items;0-1-4+3+20;level=%3D200
2. "Icebound Cloak" has only 60 white armor for some reason. It should have 150 white armor (affected by Toughness, Thick Hide, etc). To maintain a total statline of 559 armor as displayed in the tooltip, it should have and 409 green armor (559-150=409).

Test 1, white armor custom, "The Frost Lord's Battle Shroud"
Armor from Agility: 110*2=220
Armor from Enchantment: 0
Armor from White (item level): 137
Armor from Green (bonus stats): 0
Armor from Toughness (+10% White): 137*0.1=13.7
Total Armor Calculated: 370.7
Total Armor Observed: 370
Calculated and Observed match (rounding error)!

Test 2, green armor stock, "Cloak of Armed Strife"
Armor from Agility: 87*2=174
Armor from Enchantment: 0
Armor from White (item level): 150
Armor from Green (bonus stats): 486-150=336
Armor from Toughness (+10% White): 150*0.1=15.0
Total Armor Calculated: 174+486+15=675
Total Armor Observed: 675
Calculated and Observed match!

Test 3, green armor custom, "Icebound Cloak"
Armor from Agility: 87*2=174
Armor from Enchantment: 225
Armor from White (item level): 137 (assumed)
Armor from Green (bonus stats): 559-137=422
Armor from Toughness (+10% White): 137*0.1=13.7
Total Armor Calculated: 174+225+559+13.7=971.7
Total Armor Observed: 964
Calculated and Observed do not match!
How much armor is actually granted by Toughness?: 964-174-225-559=6
How much white armor is being affected?: 6*100/10=60

**Comment by Piootrek** [comment]
In test 3 you used a wrong white armor, this cloak had 69 of it. 
Fixed this for all midsummer cloaks.
