### ISSUE TITLE
Lightwell doesn't disappear when consumed (Visual bug)

### ISSUE THREAD

**Issue by Furiianda** [gamefreedomgit/Frostmourne#1043]
**Description:**
After using all the charges of Lightwell,  it sometimes persists visually on-screen as a targetable object.
Note that it persists differently for different players, for instance in testing, I used 2 accounts and only the account that consumed the last charge could see the lightwell afterwards.

![lightwell_visual_bug](https://github.com/gamefreedomgit/Frostmourne/assets/6436416/84a306b1-8ed9-4717-a653-27122652df95)
(all 3 of the lightwells were cast by 1 priest in this image)

**How to reproduce:**
Summon a lightwell with at least 1 party member and use all the charges. The character who uses the final charge will have the lightwell object stuck on-screen for an indefinite amount of time, while the other character doesn't see anything.

**How it should work:**
Lightwell should disappear when expired, or when all charges are consumed. In addition, it also has a unique "shrinking" disappearing animation which does not play.

**Database links:**
https://www.wowhead.com/wotlk/spell=48087/lightwell

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
