### ISSUE TITLE
repsawn timer of Recipe: Elixir of Major Defense

### ISSUE THREAD

**Issue by OksenOi** [gamefreedomgit/Frostmourne#1044]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I've been standing by the vendor "Daga Ramba" for a couple of hours without any respawn of the recipe "Recipe: Elixir of Major Defense".

**How it should work:**
What i can read on wowhead people say many different things. some say it has about a 5 min respawn timer and some say hours. 
but mostly people say that recipe is the shortest timer from the recepies this vendor sells. with the Mana recipe being the longest (and that has respawned 3 times so far). 

**Database links:**
https://www.wowhead.com/wotlk/item=22909/recipe-elixir-of-major-defense#comments

**Comment by OksenOi** [comment]
i've now checked the allience vendor as well "Haalrun" and he also only had the "Recipe: Super Mana Potion". (ofc i could have randomly arrived after someone else bought it). 

i need the Recipe: Elixir of Major Defense to complete the questline for master of elixir as alchemist. would really like to have this before our guild raid on sunday.

**Comment by Afgann** [comment]
fixed
