### ISSUE TITLE
Mobs in K3 Northrend misposition/appearance

### ISSUE THREAD

**Issue by ChronoWM** [gamefreedomgit/Frostmourne#1048]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)
Several NPCs that seem to be an objective of the quest a delicate touch are right outside K3 village in Northrend.

**Description:**
NPCs [Snowblind Followers](https://www.wowhead.com/wotlk/npc=29618/snowblind-follower) and [Snowblind Followers](https://www.wowhead.com/wotlk/npc=29619/garm-invader) are in K3 in Northrend.

**How it should work:**
They are an objective of the quest A Delicate Touch, [A Delicate Touch](https://www.wowhead.com/wotlk/quest=12820/a-delicate-touch) and [Overstock](https://www.wowhead.com/wotlk/quest=12833/overstock) 
and are not meant to be standing there by default.

**Database links:**
[![image](https://github.com/gamefreedomgit/Frostmourne/assets/170808156/8826a898-e7fd-4e92-a907-95e5707b59be)](https://imgur.com/a/IsSQnTJ)

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/1047
