### ISSUE TITLE
[NPC] Enranged Stanley gives incorrect XP

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Frostmourne#105]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Enraged Stanley should give equivalent XP to a quest, he only gives normal mob XP.

**How to reproduce:**
.set xp 1
.quest add 502
Hand it in
Kill the dog that spawns, notice how you only get a 200 xp, you should get over 1000.

**How it should work:**
![image](https://github.com/gamefreedomgit/Frostmourne/assets/6482585/5045be5a-307d-4201-948a-69befaa86eb9)

**Database links:**
https://www.wowhead.com/wotlk/npc=2275/enraged-stanley#comments
https://www.wowhead.com/wotlk/quest=502/elixir-of-pain#comments

**Comment by Afgann** [comment]
fixed
