### ISSUE TITLE
[spell] Mind Flay

### ISSUE THREAD

**Issue by buza-me** [gamefreedomgit/Frostmourne#1050]
**Description:**
Mind Flay does two damage ticks instead of three in some cases.

**How to reproduce:**
Cast Mind Flay while shielded or when 100% pushback immune. I use combat log events to play sound on Mind Flay ticks.
[This WA](https://pastebin.com/bYCLKVFQ) can do it, currently water drop sound.

[Here is the video](https://www.youtube.com/watch?v=cpLfltVQI7c) with a timestamp that I made 10 minutes before I created this issue.
The issue is rather rare now, will probably happen 1-3 times during a boss fight depending on a boss fight length.

**How it should work:**
Mind Flay channeling should result in 3 damage instances.

**Database links:**
[Mind Flay](https://www.wowhead.com/wotlk/spell=48156/mind-flay)

**Comment by UltraNix** [comment]
Fixed.
