### ISSUE TITLE
Quest | Neutralizing the Plague Daily

### ISSUE THREAD

**Issue by danysilva** [gamefreedomgit/Frostmourne#1051]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The NPC "Pustulent Horror" does not drop "Flesh Giant Spine"

**How to reproduce:**
Chance drop 9% 
https://www.wowhead.com/wotlk/item=44009/flesh-giant-spine

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
