### ISSUE TITLE
Ebon plague and SSG bug

### ISSUE THREAD

**Issue by Thickskull** [gamefreedomgit/Frostmourne#1052]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
So i couple of days ago i made a post here reporting a bug on scourge strike glyph(SSG from now on ) having a conflict with Epidemic talent, which was fixed. Thanks a lot for that but now seems it created 2 new problems.

The first one is Ebon plague is now not being benefit from the +3 secs when you use SSG which previously was , the second bug is now scourge SSG can only be used 3 times, after that it doesnt work anymore. needing you to refresh your deseases again for it to work. Previously it was giving always +3 secs not only 3 times

The max duration of the deseases is 21 secs while using epidemic talent but its not the cap, the cap is 30 seconds, 21 base +9 from SSG  once you reach that 30 seconds cap, SSG should not give you  any more aditional seconds but if you are not at that cap it should always give you +3 seconds because it can give you up to 9 not only 9 its big diference
https://www.youtube.com/watch?v=r-uckNyqMpY
**How to reproduce:**
Create a dk, go to any training dummy apply your deseases, then use scourge strike with his glyph active and you will see the bug. Ebon plague is not being benefit from the extra 3 seconds from SSG

For the second bug do the same, apply your deseases use SS with his glyph active you will see that it only works 3 times and then no longer gives +3 seconds unless you reapply your deseases again

**How it should work:**
Ebon plague should  benefit alongside with frost fever and blood plague from SSG since all of them are deseases

SSG should always give +3 if you are not at the 30 seconds cap

**Database links:**
SSG doesnt say anywhere in the description that is limited to only 3 uses
SSG https://www.wowhead.com/wotlk/item=43551/glyph-of-scourge-strike#comments:id=856993 

These 3 are deseases and all of them should benefint from SSG
Ebon plague https://www.wowhead.com/wotlk/spell=51735/ebon-plague

Frost Fever https://www.wowhead.com/wotlk/spell=55095/frost-fever

Blood plague https://www.wowhead.com/wotlk/spell=55078/blood-plague#comments

**Comment by UltraNix** [comment]
Fixed.
