### ISSUE TITLE
[item] Frostscythe of Lord Ahune and enchanting scrolls

### ISSUE THREAD

**Issue by ShikannahtheIssueReporter** [gamefreedomgit/Frostmourne#1055]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Trying to enchant [Frostscythe of Lord Ahune](https://www.wowhead.com/wotlk/item=54806/frostscythe-of-lord-ahune) staff with a scroll results in "That item is not a valid target." message popping up.

**How to reproduce:**
https://youtu.be/aZTSqeFRdyE

**Comment by RadeghostWM** [comment]
you need whitemane patch

**Comment by Aeradel** [comment]
> you need whitemane patch

This doesn't really make sense because they would need the patch to even equip the weapon to begin with - unless there's something I'm forgetting.

Not the first time this has been reported, but I haven't gone through troubleshooting to try and replicate it yet.

**Comment by UltraNix** [comment]
To be more precise: 
You need whitemane client (wow.exe).
