### ISSUE TITLE
Culling of Stratholme - Wrong event order stops waves

### ISSUE THREAD

**Issue by yeagerca** [gamefreedomgit/Frostmourne#1056]
**Description:**
In Culling of Stratholme, starting the dialogue events in the wrong order can cause waves of enemies to stop spawning.

Starting the waves by skipping to the second dialogue, then finishing the plagued crates and starting the first dialogue will cause the waves to stop spawning. Following through with the second dialogue again will spawn only one wave.

**How to reproduce:**
Only works in Heroic because skips are disabled in Normal difficulty.
1. Player 1 uses Chromie to teleport.
2. Player 2 gets the item to reveal plagued crates.
3. Player 1 starts the second role play, waits for it to finish, and maybe kills some waves of mobs.
4. Player 2 reveals all plagued crates and starts the first role play.
5. Waves will immediately stop spawning.
6. Continue to the second dialogue again. See that waves stop spawning after the first.

**How it should work:**
The dialogue to start the first event should not be available after skipping and starting the second event,
or,
after triggering the second event again it should continue spawning more waves.

**Comment by UltraNix** [comment]
@yeagerca I can't reproduce the way you described.
After Player 1 uses Chromie to teleport, the Player 2 see only option to use the teleport- with no option to start crates events.
Can you record it or give some screenshots?

**Comment by yeagerca** [comment]
I didn't take any video or screenshots when it happened.
I think starting the quest for the first time triggers the plagued crates event much like the dialogue does, even if the dialogue isn't available. I do not have a fresh character available to test starting the quest as Player 2.

**Comment by UltraNix** [comment]
Fixed.
