### ISSUE TITLE
[Achievement] Master of Arms not granted due to automatic skill-ups

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1057]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Two achievement unobtainable since weapon skills are automatically skilled with your level.
[Master of Arms]
[Did Somebody Order a Knuckle Sandwich?]

**How to reproduce:**

**How it should work:**
Achievements should be granted upon reaching level 80 if skills are automatically granted.

**Database links:**
https://www.wowhead.com/wotlk/achievement=16/did-somebody-order-a-knuckle-sandwich
https://www.wowhead.com/wotlk/achievement=705/master-of-arms

**Comment by Chaos-within** [comment]
This was fixed but wasn't retroactively applied to people who hit 80 in the past. Thus new 80s get these achievements but old 80s are still unable to achieve.

**Comment by UltraNix** [comment]
Fixed.
