### ISSUE TITLE
Torch Juggler bug (current event)

### ISSUE THREAD

**Issue by Klakocik** [gamefreedomgit/Frostmourne#1058]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Juggling 40 torches doesn't award Torch Juggler

**How to reproduce:**
Throw torches on yourself. Tried yesterday and today.
https://youtu.be/Q3odjWQ4OVE

**How it should work:**
Torches juggled should go back to equipment, not just disappear.
Also juggling 40 torches in 15 seconds while being in Dalaran should award Achievemnt Torch Juggler

**Database links:**
https://www.wowhead.com/wotlk/achievement=272/torch-juggler
https://www.wowhead.com/wotlk/item=34599/juggling-torch

**Comment by UltraNix** [comment]
You need to complete https://www.wowhead.com/quest=11657/torch-catching/https://www.wowhead.com/quest=11923/torch-catching.
Also, it works only in Dalaran.
