### ISSUE TITLE
Guru's Elixir mislabelled in trainer

### ISSUE THREAD

**Issue by yeagerca** [gamefreedomgit/Frostmourne#1059]
**Description:**
In the trainer window Guru's Elixir is named Increased Spirit 34.

Database Links:
https://www.wowhead.com/wotlk/spell=53848/gurus-elixir
https://www.wowhead.com/wotlk/spell=14456/increased-spirit-34

![Guru's Elixir](https://github.com/gamefreedomgit/Frostmourne/assets/93017663/d69709c8-b86b-42f6-8565-879734a9fb14)

**Comment by RadeghostWM** [comment]
Fixed
