### ISSUE TITLE
Maexxna keeps her room shut after a wipe

### ISSUE THREAD

**Issue by Mixetaa** [gamefreedomgit/Frostmourne#106]
**Description:** Maexxna doesn't remove her web that she uses to close her chamber when you start the boss encounter, after a wipe.
![WoWScrnShot_020424_210308](https://github.com/gamefreedomgit/Frostmourne/assets/158359423/b805acba-80f0-4f71-a008-9a25b4800de5)

**How to reproduce:** Wipe on Maexxna

**How it should work:** When the boss encounter ends, either by killing the boss or by wiping, the webs should go away

**Comment by Afgann** [comment]
fixed
