### ISSUE TITLE
Razuvious in Naxx10 Ascended

### ISSUE THREAD

**Issue by ruivexamos** [gamefreedomgit/Frostmourne#1060]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
There are no mind control crystals in Naxx 10 man Ascended

**How to reproduce:**
Go play the raid

**How it should work:**
It should have the crystals

**Database links:**

**Comment by Afgann** [comment]
fixed
