### ISSUE TITLE
Charge/Intercept Bug

### ISSUE THREAD

**Issue by KeXyftw** [gamefreedomgit/Frostmourne#1061]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
While charging/intercepting as a warrior, I often experience this: Charge goes through, I rush to the enemy. Then I zoom back to my starting position only to reappear again next to the enemy a second later. 

I'm sorry I can't provide enough detail, but hope this helps as I've been experiencing this from the server start. It could be that it's an issue with some files on my side? If so I'll be grateful for any help with that.

**How to reproduce:**
Unfortunately I haven't figured out what exactly causes this. But It happens a lot in PvP.

**How it should work:**
The warrior should rush to the enemy and stay there.

**Database links:**
https://www.wowhead.com/wotlk/spell=11578/charge
https://www.wowhead.com/wotlk/spell=20252/intercept

**Comment by UltraNix** [comment]
@KeXyftw No stuns/roots/knockbacks during charging?

**Comment by KeXyftw** [comment]
> @KeXyftw No stuns/roots/knockbacks while charging?

It's possible that it's happening during frost novas/roots, but what happens is that I charge in, can even get an auto/spell in, then it very quickly just rebounds back. Not even necessarily to the starting position, and then back to the enemy again where I'm able to attack again. And it's definitely not a lag issue, game's smooth.

**Comment by UltraNix** [comment]
Do we have source if charge should be even stopped by roots/stuns?
