### ISSUE TITLE
Fly and Swift Fly Form (DRUID)

### ISSUE THREAD

**Issue by DusanJovanovic1991** [gamefreedomgit/Frostmourne#1062]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[[//]: # (https://www.wowhead.com/wotlk)](https://www.wowhead.com/wotlk/spell=40120/swift-flight-form)

**Description:**
druids doesnt need any training for flying which is a bug. For epic flying you just need to go to moonglade and train swift fly from from Logaanar npc. and there you go you have epic fly for druid without spending gold. And for slower bird you just train it from trainer also and you have it without spending gold.

**How to reproduce:**
Remove all druids that not trained flying skill and they should pay like everyone else for flying. 

**How it should work:**
Fly form and swift fly form should require flying skill trained. This is mayor bug so please fix ASAP.

**Database links:**
According to the 3.0.3 patch notes, the Druid swift flight form will be trainable at level 71. It will still require 300 flying skill and will require that you have previously learned the regular flying form.

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/591

**Comment by DusanJovanovic1991** [comment]
so i guess you guys dont know how to fix it

**Comment by DusanJovanovic1991** [comment]
Nice waste of time reporting it. Bye

**Comment by UltraNix** [comment]
Fixed.
