### ISSUE TITLE
Waterfall Height in Sholazar Basin

### ISSUE THREAD

**Issue by sth666** [gamefreedomgit/Frostmourne#1063]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

**Waterfall Height** in Sholazar Basin  - The Seabreach Flow.

**Coordinates : 37.43 61.38** ( used Mapster addon coordinates.

I waited for the "Breath" bar to end, at the end of the bar, the player **starts taking damage.**

![Breath issue](https://github.com/gamefreedomgit/Frostmourne/assets/45474717/14122343-d148-4b1d-907c-c7f6ea8eaaf0)
![Breath issue2](https://github.com/gamefreedomgit/Frostmourne/assets/45474717/51886b6f-895d-44f1-b21c-774b793d2e7a)

**Comment by UltraNix** [comment]
Fixed.
