### ISSUE TITLE
Midsummer Fire Festival

### ISSUE THREAD

**Issue by Matrwa** [gamefreedomgit/Frostmourne#1064]
**Description:** As low level character i cant complete Honor the Flame quest 

**How to reproduce:** make fresh char go nearest event spot and try to finish Honor the flame quest 

**How it should work:** any level should be able to have this q up to do

**Database links:**https://www.wowhead.com/quest=11834/honor-the-flame

**Comment by UltraNix** [comment]
@Matrwa What zone/area/level?

**Comment by Matrwa** [comment]
check 3 durotar, ashenvale, barens( crossroads ) checked on 80 level instant was in durotar did not check rest

**Comment by Godmatik** [comment]
These quests only appear to open up once you are level 30 or higher.

**Comment by Matrwa** [comment]
got it already
