### ISSUE TITLE
Armor penetration

### ISSUE THREAD

**Issue by Wzqpoiazep** [gamefreedomgit/Frostmourne#1065]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Hello i wanted to know why armor penetration doesnt apply on bleeds on feral druids that litteraly doesnt change a thing with armor pen procs 

**How to reproduce:**
i did many tries with and without trinket with and without armor penetration

**How it should work:**
armor penetration should increase the damage of bleeds tic on target by reducing his armor.

**Database links:**

**Comment by UltraNix** [comment]
https://wowpedia.fandom.com/wiki/Armor_penetration
`Armor penetration will increase non-bleed physical damage by a percentage significant for virtually every target, however, for lightly armored targets it is less effective in the damage it provides.`
