### ISSUE TITLE
Grobbulus have no slime in 10 ascended

### ISSUE THREAD

**Issue by iskense** [gamefreedomgit/Frostmourne#1066]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
In 10a Naxx, grobbulus doesnt spawn a slime after slime pray.

**How to reproduce:**
fight grobbulus in naxx 10a

**How it should work:**
[Slime Spray](https://wowclassicdb.com/wotlk/spell/28157) IconSlime Spray — This ability is a frontal cone cast by Grobbulus, causing heavy Nature damage to any players hit. In addition, a [Fallout Slime](https://wowclassicdb.com/wotlk/npc/16290) will be spawned for each player hit (a minimum of one, as the tank cannot avoid this ability).

**Database links:**

**Comment by Afgann** [comment]
fixed
