### ISSUE TITLE
Terokk's divine shield will not go away

### ISSUE THREAD

**Issue by frostydom** [gamefreedomgit/Frostmourne#1067]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
while killing Terrokk https://www.wowhead.com/wotlk/npc=21838/terokk both during the quest and summoning him multiple times he uses divine sheild to make him invulnerable and then the Sha'tari Skyguard npcs put down a purple flare then it turns to flames and it is supposed to remove the divine shield so you can kill him but it does not.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by WhitemaneChronus** [comment]
Confirmed issue, shield does not go away while Terokk is affected by the flare.

**Comment by Spacemuffin007** [comment]
Bump! Trying to farm my rep for mounts and cant finish this repeatable quest... Please fix.
