### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Murblet** [gamefreedomgit/Frostmourne#1068]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Murblet** [comment]
Lock and Load isn' working on my hunter , named " Murble" pls help

**Comment by WhitemaneIsa** [comment]
No further info/complaints, closing.
