### ISSUE TITLE
No blasted lands portal in Ogrimmar

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#107]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
There is no blasted lands portal in cleft of shadows area in Ogrimmar. There probably isn't any in other capitals as well.

**How to reproduce:**
-

**How it should work:**
BL portal in capitals

**Database links:**

**Comment by Inukk** [comment]
The portal to blasted lands on orgrimmar is located right next to the portal trainer on the valley of spirits. The one in cleft of shadows was added on cata iirc
