### ISSUE TITLE
Strength scaling of Army too high

### ISSUE THREAD

**Issue by Sylanha** [gamefreedomgit/Frostmourne#1070]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Recently the talent "Ravenous Dead" has been fixed. It is now working properly with Army, which is good, but the strength convertion of Army should not be 1:1 but instead x0.4.

**How it should work:**
 So if the DK has 1000str and has 3/3 points in Ravenous Dead then Army should be getting 240 (and not 600) strength from the talent (So 60% of the talent(Ravenous Dead is working fine )and then 40% of that).
Math explained:
-DK has for example 1000str
-3/3 Ravenous Dead gives Army of the Dead 600 strength
-the 600 strength should be multiplied with x0.4 (40%) again and not leave it as x1 (100%), since it would be too strong then.
      -> making that a total of 240 strength given to Army of the Dead

So army needs another multiplicator of x0.4 , or it is too strong.

**Comment by Godmatik** [comment]
Confirmed

**Comment by Afgann** [comment]
fixed
