### ISSUE TITLE
All Pets in general are not always attacking from the back

### ISSUE THREAD

**Issue by Sylanha** [gamefreedomgit/Frostmourne#1071]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
All pets, no matter if Hunter pet or DK pet, or even summoned pets like Spirit Wolves/FireElemental/Earth Elemental from Shamans (or Army of the Dead from DK's) are not focusing attacking from behind. Otherwise the pets are parryhasting the boss, which can lead to wipes due to random pet AI.

**How to reproduce:**
Take literally any pet and move to the front of a dummy and make it attack (/petattack). It will sometimes attack from the front, it is inconsistent, but it SHOULD ALWAYS attack from the back.

**How it should work:**
It should be moving behind the target and not stay in front of the target.

**Database links:**
https://youtu.be/8W2a4EGLQ-g

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/474
