### ISSUE TITLE
Issues with OS10/OS10 Ascended

### ISSUE THREAD

**Issue by josh23meyer** [gamefreedomgit/Frostmourne#1072]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Did not receive emblems from each dragon inside OS. Also did not receive 25m loot from 10m Ascended

**How to reproduce:**
Kill Sarth 10m Ascended

**How it should work:**
Each of the 3 drakes when killed seperately should provide an Emblem to everyone in the raid based off difficulty. When killing Sartharion in 10m ascended - you are supposed to receive at least one piece of 25m loot. 

**Database links:**

**Comment by Afgann** [comment]
You need to do at least 2D version to get 25m loot.

**Comment by wotlkenjoyer** [comment]
@Afgann  Hello, 2 weeks in a row were doing  10man Ascended 2 drakes,  yes it drops x1 25man loot, but there is no bonus drakes loot  in the loot table,  it never drops, we missing loot from 1d and from 2d.  It happens only  in Ascended version,  You getting only normal sartarion 10man loot + x1 random 25man, but no hard mode loot from Shadron and Tenebron.

**Comment by wotlkenjoyer** [comment]
But when we did it at week 1 it dropped, x1 25man  and bonus drake 10man loot, but  next week you guys changed something everywhere in ascended. in naxx too, after  you added emblems to each boss in naxx , with that server update we los bonus drake loot. Just did it  and still no loot

**Comment by Afgann** [comment]
fixed
