### ISSUE TITLE
Terokk's Downfall (TBC quest)

### ISSUE THREAD

**Issue by streamson1** [gamefreedomgit/Frostmourne#1073]
https://www.wowhead.com/quest=11073/terokks-downfall

When doing the quest, around 30% life left, he shields himself taking 0 damage from any source. You are suppose to drag him to the blue fire/bomb to disable his shield to continue the fight. But the issue is, the fire/bomb doesn't break/disable his shield.

Fix the shield so it breaks when the fire/bombs drops.

The blue flame/bomb is suppose to disable his shield when he is enraged.

https://www.wowhead.com/quest=11073/terokks-downfall#comments

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/1067
