### ISSUE TITLE
Pet becoming uncontrollable during Eyes of the Beast

### ISSUE THREAD

**Issue by Karsenity** [gamefreedomgit/Frostmourne#1076]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** 

Occasionally while using Eyes of the Beast, your pet AI will resume and override your own. You'll still be channeling Eyes of the Beast, however you won't be able to move the pet or use any their abilities for the duration.

**How to reproduce:**

One way that pretty consistently recreates it is if your pet is far away and running back to you when you finish casting. The pet will insist on running back to you before you gain control.

**How it should work:** Pet AI should be disabled while using eyes of the beast

**Database links:**

**Comment by Riztazz** [comment]
fixed, will close once it's live
