### ISSUE TITLE
Heroic: Judgment at the Eye of Eternity

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#1077]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
After killing Malygos 25m I forgot to loot the heart and exited the raid, when I realized I forgot to loot it I went back for it and the heart was unclickable

https://youtu.be/KWREEnseSz8

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/975
