### ISSUE TITLE
Pet macro's not working during Eyes of the Beast

### ISSUE THREAD

**Issue by Karsenity** [gamefreedomgit/Frostmourne#1078]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

During Eyes of the Beast, pet abilities bound to macros are only working if the ability is on the pet bar. I.e. if Bite is on the pet bar, a macro can be used to cast it during Eyes of the Beast. However if you remove it from the pet bar, the pet is no longer able to cast the ability during the spell.

**How to reproduce:** 

Create a macro reading "/cast bite" and use eyes of the beast, then use it. Remove Bite from the pet actionbar, recast eyes of the beast, and try again.

**How it should work:**

Macro should allow casting pet ability while in Eyes of the Beast

**Database links:**

**Comment by Karsenity** [comment]
So far this has happened with Bite, Last Stand, and Taunt

It's worked for Thunderstomp, growl, Charge, and pet-specific abilities

**Comment by Riztazz** [comment]
Not a bug sadly, client does not allow to run macros while under possess. You could try raising separate ticket for 3.5 client to enable this
