### ISSUE TITLE
Grommash Hold guards throwing rotten fruit to everyone

### ISSUE THREAD

**Issue by Galatoa** [gamefreedomgit/Frostmourne#1080]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Grommash Hold guards throwing rotten fruit to every character not just death knights during their quest arriving to Orgrimmar

**How to reproduce:**
So far it happened with my alts when I visit Grommash Hold. No further clue on why it's being triggered

**How it should work:**
Guards should only throw rotten fruit to death knights during the Warchief's Blessing quest and only before they meet with Thrall.

**Database links:**
https://www.wowhead.com/wotlk/quest=13189/warchiefs-blessing

**Comment by WhitemaneIsa** [comment]
I vote we never fix this, it's so fun. :D
