### ISSUE TITLE
Malygos issues

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1081]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Last 25M kill of malygos, after the air phase vortex ended his model remained flying even though he was walking on the platform.
He also used breath before while falling down to the floor, should only cast it a bit after finally landing on the floor similar to this [video](https://www.youtube.com/watch?v=CDZDZWiS-dw).
on this server the spark also seems to be absorbed by malygos using his hitbox rather than the center of his model.
in the same video you'll notice they death gripped right next to him, if done on frostmourne he would have absorbed it and gained the damage buff which limits its usage for melees.
https://www.youtube.com/watch?v=hPzjW3qAIls
another video where multiple sparks are in his hitbox but not absorbed since not passed through his center.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Godmatik** [comment]
Confirmed about spark, I recall this issue from another Wrath server.

He is absorbing at a much greater distance than he should.
