### ISSUE TITLE
[Enchanting] Disenchanting 105-164 epic never yields 2x [Void Crystal]

### ISSUE THREAD

**Issue by erikpowa** [gamefreedomgit/Frostmourne#1083]
**Description:**
Disenchanting 105-164 (105 - 159) epic tbc items should also have a chance to yield 2x void crystals instead of 1

**How to reproduce:**
```.additem 32942 50```
```.additem 34361 50```
disenchant them
notice only 1x void crystal

**How it should work:**
66.7% 2x
33.3% 1x

**Database links:**
https://wowpedia.fandom.com/wiki/Disenchanting_tables

**Comment by Afgann** [comment]
fixed
