### ISSUE TITLE
Stranglethorn Vale Fishing Extravaganza in Bootybay didnt work

### ISSUE THREAD

**Issue by zuldabad** [gamefreedomgit/Frostmourne#1084]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Stranglethorn Vale Fishing Extravaganza in Bootybay didnt work, its already 14pm+ at sever time and goblin [Riggle Bassbait](https://www.wowhead.com/classic/npc=15077/riggle-bassbait): dont have quest available. And there is no [Speckled Tastyfish](https://www.wowhead.com/classic/item=19807/speckled-tastyfish) swarms

**How to reproduce:**
Go to Booty bay at 2pm to 4pm and try to talk to Riggle Bassbait

**How it should work:**

at 2pm to 4pm at server time goblin Riggle Bassbait should start quest, he asks you to catch 40 Speckled Tastyfish
**Database links:**
https://www.wowhead.com/quest=44765/stranglethorn-fishing-extravaganza

**Comment by zuldabad** [comment]
If there is some other timings for that event, i would like to know when exactly it is

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/1084
