### ISSUE TITLE
Shadowform bug

### ISSUE THREAD

**Issue by VengyFmourn** [gamefreedomgit/Frostmourne#1086]
Shadowform getting bugged and uncastable with a gray button that is unclickable. 
The error messages I get are usually: 
- Spell not ready yet.
- You can't used that now.
When it happens: 
- Usually after casting healing spells but mostly Prayer of Mending. Sometimes you get lucky and it doesn't bug out.
- Ways to fix this currently is log out and log in, which is quite inconvenient in raid environment because you are constantly in combat.
- An alternative way is to just reload but that happens very rarely, so you must log out manually.

Realm - Frostmourne
Character name - Vengy
Cheers and thanks in advance!

**Comment by UltraNix** [comment]
@VengyFmourn So you are in ShadowForm and try to use healing spell?
Do you use any macro when casting such healing spell?

**Comment by minthes** [comment]
@UltraNix hey, this bug happened to me as well today. I didn't use a macro, just cancelled shadowform then healed, couldn't go back into shadowform.

**Comment by buza-me** [comment]
@UltraNix 
I had this bug twice. First time it happened when I tried to use Shadowform when in a vehicle, doing "Assault by air" quest in Icecrown.
Second time it happened on Sapphiron when I used Hymn of Hope in Shadowform, while hiding behind an ice tomb during the air phase. I could not really reproduce it.

**Comment by UltraNix** [comment]
Let me know if it's fixed.

**Comment by buza-me** [comment]
@UltraNix sometimes shadowform has no GCD or is clickable during a GCD. When such activation happens it bugs out. It happens to me at least once a day, usually when I throw a quick renew or POM on myself and press the shadowform key after.

**Comment by UltraNix** [comment]
@buza-me Any macros?

**Comment by buza-me** [comment]
Nope @UltraNix , no macros :( It usually happens after a heal and immediate shadowform recast in my cases.

**Comment by buza-me** [comment]
or actually it happened once when I fat fingered Holy Fire and then recasted shadowform. I guess it has more to do with a gcd window but idk.

**Comment by UltraNix** [comment]
@buza-me Let me if it's fixed now.

**Comment by UltraNix** [comment]
Fixed.
