### ISSUE TITLE
Bugged/glitchy pixelated graphics while using a nvidia rtx 2080 super

### ISSUE THREAD

**Issue by Fluffydrood** [gamefreedomgit/Frostmourne#1087]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Bugged graphics and textures

**How to reproduce:**
idk playing on frostmourne all of sudden has glitchy textures and shaders and lighting like it becomes pixelated 

**How it should work:**
clear crisp imagery 

**Database links:**

**Comment by WhitemaneIsa** [comment]
Try installing a fresh client and play around with your settings. This is very very unlikely a server bug.

**Comment by Fluffydrood** [comment]
well i have done just that and Frostmourne is the only server it does it with
