### ISSUE TITLE
Recipe jc bug

### ISSUE THREAD

**Issue by Drdalez** [gamefreedomgit/Frostmourne#1088]
I bought a jc recipe 5 minutes before the restart server, I even made a gem before the server went down for good, when it came back both the recipe and the tokens were no longer there, I have this print as proof, a gem made by me, I would like that at least my jc tokens would come back
![whiute](https://github.com/gamefreedomgit/Frostmourne/assets/173618657/c953b2ba-f067-4dd7-9045-c81cccee5f90)

**Comment by WhitemaneIsa** [comment]
Open a ticket ingame please
