### ISSUE TITLE
Cleanse type spells can remove buffs

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#1089]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Currently, cleanse type spells (cleansing totem, dispels) can remove beneficial effects on players (buffs) when they should only be able to affect debuffs. This happens when the buffs themselves have a negative type attached to them. Some situational/gimmick buffs can be classified as type - poison, curse.

Only tested with dragonbreath chili as it's the only one I can recall right that has type poison, but there may be other things like this. I think this should be addressed as a whole since cleanses should only be able to affect debuffs anyway. There may be other buffs with weird classification type affected by this.

**How to reproduce:**
Pop a https://wotlk.evowow.com/?item=12217
Use cleaning totem (or single target cleanse or any poison dispelling spell)
Watch it being removed on cleanse tick.

**How it should work:**
"This item produces a buff that is classified as a Poison effect. Normal friendly poison cleansing effects will not remove it, but the Dwarf 'Stone Form' racial, which grants temporary immunity to poisons, will."

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
