### ISSUE TITLE
Frostscythe of Lord Ahune and MC in DTK

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1091]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Draktheron keep's last boss Theronja mind control/shapeshift caused a caster in my party who is equipping the staff unable to use his melee ability prompting a warning message "you don't have a melee weapon equipped".
basically the button was blacked out and unable to be usable.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
@Manpower99 He has the whitemane patch and whitemane client?

**Comment by Manpower99** [comment]
> @Manpower99 He has the whitemane patch and whitemane client?
Just got a reply, yes he does

**Comment by UltraNix** [comment]
Just teted with whitemane patch and whitemane wow.exe - I see no error.
Tested with non-whitemane client - there is an error. So I guess he just don't have our client.

**Comment by Manpower99** [comment]
Since im using the client ill try to test it on live as soon as i can, with same class as him aka Mage. just gotta wait till i get the staff and will comment further after.
