### ISSUE TITLE
No 226 item dropped from 10A Kel'Thuzad

### ISSUE THREAD

**Issue by sorryjeb** [gamefreedomgit/Frostmourne#1092]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Killed KT
https://www.twitch.tv/videos/2179662269 - 2hrs39mins50seconds
**How to reproduce:**
Killed KT on 10A

**How it should work:**
KT should drop x1 226 item

**Database links:**

**Comment by sorryjeb** [comment]
Please message "hg" in game.

**Comment by WhitemaneIsa** [comment]
There is not supposed to drop a 226 item from 10A, only 25A.

**Comment by Afgann** [comment]
fixed
