### ISSUE TITLE
the mobs enter inside wall & mobs flee issue

### ISSUE THREAD

**Issue by ziniguebi** [gamefreedomgit/Frostmourne#1095]
when i am lvling in hardcore and  while i am killing a mob he just flee inside the wall well it doesnt pull the other adds but it still can hit hit through wall and i cannot take loot from it 
also there are some mobs that shouldnt flee like undead mobs in ghoslands( trolls in the cave and murlocs in the coast they flee but they shouldnt)

also the head droprate sometimes the mob doesnt drop his head and i should do the quest 2 times or even more

**Comment by UltraNix** [comment]
@ziniguebi What mobs in what area/zone?
About fleeing mobs - please give us their names at least (or links)

`also the head droprate sometimes the mob doesnt drop his head and i should do the quest 2 times or even more`
Again - more info please. What head and what quest?

**Comment by WhitemaneIsa** [comment]
No further complaints/Info, closing.
