### ISSUE TITLE
cant see emblems with gems at ally side " Murble"

### ISSUE THREAD

**Issue by Murblet** [gamefreedomgit/Frostmourne#1096]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by WhitemaneIsa** [comment]
Please provide more detail.

**Comment by Manpower99** [comment]
Already reported this

**Comment by WhitemaneIsa** [comment]
> Already reported this

is it this one? https://github.com/gamefreedomgit/Frostmourne/issues/762

**Comment by Manpower99** [comment]
> > Already reported this
> 
> is it this one? #762

Correct!
