### ISSUE TITLE
Transmog Issue (SUB is active)

### ISSUE THREAD

**Issue by olverius420067** [gamefreedomgit/Frostmourne#1097]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Transmog is not showing

**How to reproduce:**
Transmog on Character Selection is ON, Subscription is ON, in-game visuals are OFF!
account: olverius
character: Olverius, Horde, Undead, Paladin

**Proof:**
See the attachments!

**Links:**
![bug1](https://github.com/gamefreedomgit/Frostmourne/assets/121267984/2621e554-966d-4397-a6ed-14a5d740c645)
![bug2](https://github.com/gamefreedomgit/Frostmourne/assets/121267984/f8823bbb-2ee3-43c2-80b5-fb136d20894c)
![bug3](https://github.com/gamefreedomgit/Frostmourne/assets/121267984/43f15f34-e191-4add-bafe-fe8c65aa4917)

**Comment by UltraNix** [comment]
@olverius420067 You mean what transmog?

**Comment by olverius420067** [comment]
Shop Transmog [see the picture below]: **Merciless Gladiator Felweave Armor**
PS1: All characters have the same problem. I can't see any transmog in game.
PS2: I've tried your HD version for the game. Same issues.
PS3: Please contact me on discord - olverius_fisto#0001  

![image](https://github.com/gamefreedomgit/Frostmourne/assets/121267984/6880155b-a083-417f-9388-00fe56152215)
