### ISSUE TITLE
Cosmetic Pet Aura Spam on Paladin/Combat Log

### ISSUE THREAD

**Issue by jerj** [gamefreedomgit/Frostmourne#1098]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When a cosmetic pet is summoned on a Paladin, the Devotion Aura constantly drops and reapplies to the pet. This is likely spamming the server with unnecessary actions. Happens about every 5 seconds.

**How to reproduce:**
Have an Aura up on a Paladin. Summon a cosmetic pet. Watch combat log.

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
