### ISSUE TITLE
[Fishing] Patch of Elemental Water does not spawn

### ISSUE THREAD

**Issue by erikpowa** [gamefreedomgit/Frostmourne#1099]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Patch of Elemental Water nowhere to be found

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/classic/object=180753/patch-of-elemental-water

**Comment by yeagerca** [comment]
In my experience private servers use this node map with 1 hour respawns per pool.
https://wotlk.cavernoftime.com/object=180753
