### ISSUE TITLE
Glyphs stacking on PTR

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#110]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Glyphs from the presets are currently stacking indefinitely for as long as you don't disconnect from the server. Also, you keep the glyphs from the other presets, so you can stack glyphs from all 3 specs at the same time.

Currently you can stack damage % buffs, spell duration, stat buffs, etc.

**How to reproduce:**
1. Select a preset from sally whitemane
2. Delete the items from your bags to make room for another preset.
3. Repeat.

**Video demonstration after ~5 minutes of stacking arcane preset on a mage:**
https://youtu.be/bJcBswCRCpg?si=oKd2Fy0csWxnqLca

**Comment by Afgann** [comment]
fixed
