### ISSUE TITLE
Server failing to recognize players as level 80 and blocking whispers

### ISSUE THREAD

**Issue by WhitemaneIsa** [gamefreedomgit/Frostmourne#1100]
![grafik](https://github.com/gamefreedomgit/Frostmourne/assets/164479303/dc491fa2-a4b1-4530-bfbd-429b70768cfa)

The player was already level 80 when I checked him. I then set him to Level 1 and back to 80 which has fixed it for him.

![grafik](https://github.com/gamefreedomgit/Frostmourne/assets/164479303/ee1d1adb-8277-4cbf-8e09-e299375c25b9)

Sometimes a restart of the game fixes it, sometimes it doesn't. I hear of it ~5 times per day. Gaga mentioned something about memory issue.

**Comment by Afgann** [comment]
fixed
