### ISSUE TITLE
Scions of Eternity's hitboxes in EoE are bugged and causing unintended LoS issues

### ISSUE THREAD

**Issue by UltraSPArchitecture** [gamefreedomgit/Frostmourne#1103]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
In Eye of Eternity, during phase 2, the flying Scions of Eternity's hitbox is very wierd and often gives Line of Sight issues.
Melees especially have to keep spinning 360 degrees around the scions to even have a chance to be able to cast abilities

**How to reproduce:**
Go to EoE
Get to phase 2
Go on a disc on a melee class (casters have issues too)
try to hit the Scion of Eternity with your abilities
Notice also how your white melee damage isnt being dealt

**How it should work:**
The hitbox should just be a normal hitbox, and close proximity / line of sight of them should behave properly

**Database links:**

**Comment by Afgann** [comment]
fixed
