### ISSUE TITLE
Tank relic from Emblems of Heroism not working properly

### ISSUE THREAD

**Issue by Rippinz** [gamefreedomgit/Frostmourne#1105]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Relic named "Sigil of Unfaltering Knight" for Death Knight's is not working properly. It should increase defense rating by 53 every time it hits the target with Icy Touch but it's not 100% all the time it procs.

**How to reproduce:**

**How it should work:**
Every time Icy Touch hits the target, it should proc the sigil. Only time it shouldn't proc is if the spell is missed (Which requires spell hit).

**Database links:**
https://www.wowhead.com/wotlk/item=40714/sigil-of-the-unfaltering-knight#comments 
(Idk the database for private servers but on every one i played , it worked this way)

**Comment by Afgann** [comment]
fixed
