### ISSUE TITLE
[Naxxramas] Patchwerk - Pets

### ISSUE THREAD

**Issue by disruption01** [gamefreedomgit/Frostmourne#1106]
Hateful strike is one-shotting pets when there's no off-tank alive.

**Comment by Karsenity** [comment]
Isn't this how the mechanic is supposed to work? I can't find anything online referencing him ignoring pets.

**Comment by RadeghostWM** [comment]
Need some retail proof.

**Comment by disruption01** [comment]
I can try to find it though I played wotlk classic and the pets were never affected by these kind of abilities.

anyway
https://www.wowhead.com/wotlk/spell=59192/hateful-strike
https://www.wowhead.com/wotlk/spell=32233/avoidance

my pet took direct damage (not reduced) sadly logs doesn't exist for 3.3.5a otherwise it would be easier to prove it

anyway, look at what kind of spell hateful strike is in the actual database of spells the client provides you will see that it's considered an area effect spell

(I believe that in some cores the damage of hateful strike is directly calculated in the boss script, from personal experience)

anyway this is minor so if you guys don't wanna considered it's okayish

**Comment by Godmatik** [comment]
Avoidance works against aoe spells, not direct attacks.

**Comment by Godmatik** [comment]
Where in that link does it say hateful strike is an AoE ability?

**Comment by disruption01** [comment]
You didnt read all I wrote, in the actual Blizzard db of spells where you have all the details the spell is considered an area effect spell, the links don't have all the info about the spell, but thats the best I could get.

Anyway, I was just trying to help, disregard this if you doubt so much.

**Comment by Godmatik** [comment]
Not sure why you closed this over my comment, but ok
