### ISSUE TITLE
Quest The sum is greater that the parts

### ISSUE THREAD

**Issue by Thickskull** [gamefreedomgit/Frostmourne#1109]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Quest nor working properly, in order to do the quest you need to mount the construct to start the event and then complete the quest

**How to reproduce:**
Get the initial quest from The wich bone in  icecrown then try to complete the quest  you can see than you can mount the construc unable to start qhe quest

**How it should work:**
You should be able to mount the construct to start the event were more and more adds come until Dr terrible shows up

**Database links:**

https://www.youtube.com/watch?v=PKr2j4T38xI
https://www.wowhead.com/wotlk/quest=13043/the-sum-is-greater-than-the-parts

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/740
