### ISSUE TITLE
Orc racial blood fury 

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#111]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Tooltip is not updating for each level.
At 80 still says 6 ap increase
Effect seems fine

**How to reproduce:**
Make orc boost 80 
Check blood fury tooltip

**How it should work:**
Tooltip should indicate correct stat increase 

**Database links:**

https://www.wowhead.com/wotlk/spell=20572/blood-fury#comments

**Comment by Afgann** [comment]
fixed
