### ISSUE TITLE
Fingers of Frost

### ISSUE THREAD

**Issue by Paladizz** [gamefreedomgit/Frostmourne#1111]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Fingers of Frost consumed but does nothing 

**How to reproduce:**
Get FoF proc while a spell is on the way to the target for example, cast a frostbolt and then an ice lance. If the frostbolt procs Fingers of Frost, the ice lance will consume 1 stack of FoF but will not get the extra damage/ 50% crit from it.

**How it should work:**
If you have 1 stack of FoF you can use 2 spells at the same time and that stack will work on both of those spells, Plus if one of those spells procs the FoF they will not consume the new stacks. (Warmane does it well)

**Database links:**

https://github.com/gamefreedomgit/Frostmourne/assets/173791019/b056b538-df99-49e2-a986-f3dfaef12449

**Comment by UltraNix** [comment]
Fixed.
