### ISSUE TITLE
Glyph of Hunger for Blood//assa rogue

### ISSUE THREAD

**Issue by Looky13** [gamefreedomgit/Frostmourne#1112]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Glyph of Hunger for Blood gives additional 3% dmg to Hunger for Blood ability in spell description everything is okay it shows that dmg will increase by 8%, but when i cast the spell my buff shows only 5% dmg buff. Is it visual or its just bugged
![hunger2](https://github.com/gamefreedomgit/Frostmourne/assets/161340129/2fb3ae62-01ee-4aad-9b69-f1960eed7ddd)
![hunger](https://github.com/gamefreedomgit/Frostmourne/assets/161340129/c3827c67-e671-416c-a508-0969f312e36f)

**Comment by Manpower99** [comment]
Works as intended, the buff tooltip is simply misleading. this has been tested on ptr and live and if you open your character sheet and mouse over your melee's percentage damage modifier you'll notice 8% extra.
