### ISSUE TITLE
Sheddle glossgleam

### ISSUE THREAD

**Issue by eaglebloo** [gamefreedomgit/Frostmourne#1113]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
This npc in the threads of fate should offer shoe shine services but doesn't 

**How to reproduce:**
Sit in the shoe shine chair next to the npc

**How it should work:**
Sit next to npc, in shoe shine chair and they should offer a shoe shine service

**Database links:**

https://www.wowhead.com/wotlk/spell=62089/shiny-shoes

**Comment by Afgann** [comment]
fixed
