### ISSUE TITLE
Daily PvP Quest

### ISSUE THREAD

**Issue by Stylesxz** [gamefreedomgit/Frostmourne#1115]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
There should be a Daily PvP Quest given by the Alliance Brigadier General, it's called Call To Arms and whatever the BG is that day

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/wotlk/npc=15351/alliance-brigadier-general#starts

**Comment by roperoperope** [comment]
yo i think there is one bro, did u check near pvp vendors
i remember seeing one in sw like up the stairs

**Comment by Stylesxz** [comment]
yes we tried every version of the npc in the different locations, no quest

**Comment by vedude** [comment]
This is working as intentional. The daily pvp quest is active only from Friday-Monday every week and it is part of the call to arms rotation.

**Comment by PanJanuszek** [comment]
![image](https://github.com/user-attachments/assets/350729f4-e93f-41df-b977-20b803ac8957)
![image](https://github.com/user-attachments/assets/34324963-2f04-420a-a494-ee7efdca033b)

I have check both races, it gives 1 of 4 quests per day.
