### ISSUE TITLE
Svala Sorrowgrave issues

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1116]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
As observed in Classic Videos (there are plenty) and of course original wotlk videos ill post this one [here](https://www.youtube.com/watch?v=CgwBaZ4PCp4) , Svala sorrowgrave has two noticable issues regarding her Air phase
1. She is untargetable on whitemane, she should not be. 
2. on whitemane she currently goes down before the sword actually lands and explodes.
the sword should land 25seconds after the ritual starts and once that happens svala should fly down

https://www.youtube.com/watch?v=o5M0lTFTctI
Another video showcasing damage number while she flying that are taken by dots and she only comes down after the sword falls.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
