### ISSUE TITLE
Sparks in 25EoE causing Chilled to the Bone 

### ISSUE THREAD

**Issue by Aeradel** [gamefreedomgit/Frostmourne#1117]
I am unsure this is intended, but when players are fighting Malygos and stand in the Sparks, they receive the **Chilled to the Bone** debuff from the Sindragosa fight as well as the typical Power Spark (de)buff. 

https://www.wowhead.com/wotlk/spell=70107/permeating-chill
https://www.wowhead.com/wotlk/npc=28859/malygos#abilities;mode:n10
https://www.wowhead.com/npc=30084/power-spark

**Comment by RadeghostWM** [comment]
This is intended as a part of 25-man tuning.

**Comment by Zipica** [comment]
https://www.wowhead.com/wotlk/spell=70107/permeating-chill 
Permeating ChillInstant
Causes those who attack Sindragosa with physical attacks to be chilled to the bone, dealing 1000 Frost damage per 2 sec. for each application.*
so then casters should have Unchained Magic, clothers are getting destroyed by 1000dmg ticks...
or just tweek it a bit down on 500dmg per stack
