### ISSUE TITLE
Toggle PvP Announcements are not working

### ISSUE THREAD

**Issue by vedude** [gamefreedomgit/Frostmourne#1118]
**Description:**

Toggle PvP Announcement that are in the addon settings of the Whitemane client is not working. There are no announcements displayed when people que for any arena bracket.

**How to reproduce:**

You into arena and an announcement should show up.

**How it should work:**

When someone queues for solo or 2v2/3v3, there should be an announcement in your chatbox saying someone queued.

Now I don't know what kind of information it should show such as including rating or not but that is up to you guys to decide to fix.

Thank you.

**Comment by vedude** [comment]
Forgot to mention that I added this in "frostmourne-suggestions" and that it has been approved by Radeghost:

_Add that it's been approved and it should work with the PvP announcement option command._

**Comment by RadeghostWM** [comment]
Need to implement those like Maelstrom @UltraNix

**Comment by WhitemaneIsa** [comment]
I've seen them ingame now a few times @UltraNix - did you maybe forget to close?
