### ISSUE TITLE
Test of Lore 1160 quest

### ISSUE THREAD

**Issue by Jenga-fm** [gamefreedomgit/Frostmourne#1119]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The quest is impossible to complete right now. Once you reach the book's location, it has sparkles, but it's not clickable so you can't interact with the object and pick up the book.

**How to reproduce:**
Add quest Test of Lore (1160 since there are several quests of the same name) -> get to the book -> watch the shiny sparkles without the possibility to click. It doesn't affect everyone (so far I think hardcore flag doesn't do it, however the alliance faction due to the racial requirement makes this able to reproduce, however somehow this issue existed on a blood elf hardcore character who hasn't done any racial swap)

**How it should work:**
You should be able to click that book and loot it

**Database links:**
https://www.wowhead.com/wotlk/quest=1160/test-of-lore
https://www.wowhead.com/wotlk/object=20726/beginnings-of-the-undead-threat

**Comment by WhitemaneIsa** [comment]
After testing this again a couple of times, we couldn't reproduce it.

@Jenga-fm please add a comment and @ me if you end up finding out how it bugs.
