### ISSUE TITLE
[Warlock] Inferno not resetting after boss kill/wipe

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#112]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**How to reproduce:**
Summon inferno during combat then kill boss or wipe

**Database links:**
https://www.wowhead.com/wotlk/spell=1122/inferno

**Comment by Afgann** [comment]
fixed
