### ISSUE TITLE
Glyph of pain suppresion (priest)

### ISSUE THREAD

**Issue by debugger12313** [gamefreedomgit/Frostmourne#1121]
I am reporting a bug with the Glyph of Pain Suppression. The glyph should allow Pain Suppression to be cast while charmed, specifically during Seduce from a Warlock's pet. However, on this server, it does not function this way.

In the original Wrath of the Lich King, Classic Wrath, and on Warmane servers, the Glyph of Pain Suppression correctly allows Pain Suppression to be used while under the effect of Seduce. This indicates that the current implementation on this server is incorrect.

Please investigate and correct this issue to ensure the glyph functions as it should.

https://www.wowhead.com/wotlk/item=45760/glyph-of-pain-suppression

**Comment by WhitemaneIsa** [comment]
According to the comments you linked Warlock Seduction isn't listed from what I see?

**Comment by debugger12313** [comment]
https://www.wowhead.com/wotlk/spell=6358/seduction

this is the spell. I can use pain suppression through wyvern sting for example, which is not a stun. 

https://www.wowhead.com/wotlk/spell=24134/wyvern-sting

**Comment by debugger12313** [comment]
Im aware of what the glyph test is saying but it worked like this on both original and classic blizzard servers

**Comment by WhitemaneIsa** [comment]
Can you find an old arena video of it maybe?

**Comment by debugger12313** [comment]
That is going to be very hard to do unfortunately. The only realistic solution here is to ask priests that has played both original and classic wotlk

**Comment by alemae96** [comment]
I've never known the glyph to break through seduction, since charm would be similar to mind control.

**Comment by UltraNix** [comment]
Fixed.
