### ISSUE TITLE
[MAGE] Arcane Missles, talent Missile Barrage not working

### ISSUE THREAD

**Issue by CraigThompson-Dev** [gamefreedomgit/Frostmourne#1122]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Mage, lvl 54. Getting a proc for Missile Barrage, and it's not triggering at all. Jsut casting a normal arcane missiles and clearing the buff.

**How to reproduce:**
Get the proc, and re-cast arcane missiles while already channeling. 

**How it should work:**
Re-cast arcane missiles, faster with the buff. 

**Database links:**

**Comment by CraigThompson-Dev** [comment]
Just noticed too ,if you get the proc WHILE casting arcane missiles, you just lose the buff if you stop the cast to try and use the proc.

**Comment by CraigThompson-Dev** [comment]
This is using frostbolt to proc it.

**Comment by Riztazz** [comment]
Fixed, will close once it's live
