### ISSUE TITLE
Can't Queue for Wintergrasp during Battle

### ISSUE THREAD

**Issue by LezChap** [gamefreedomgit/Frostmourne#1123]
I can't seem to queue for Wintergrasp during the battle.

When you fly into the zone, it asks if you want to queue while the kick timer is going down,  IF you click accept, it puts you in the queue for a second or two before the kick/teleport out, at which point you're removed from the queue.

The NPC in Dalaran doesn't add you to the queue.

You should be able to queue so if there's space, you can get into the battle.  You also shouldn't be kicked from the queue when you're teleported out.

One fact that might be related:  I was queued from the beginning of the battle, but accidentally left queue.  Said I was eligible to enter, but clicking that never teleported me into the zone/raid.  I tried again and misclicked Leave Queue.  I've also (last night) been kicked from queue I entered at the start of the battle when flying around the WG zone Perimeter trying to do other activities waiting for it to pop, and accidently going too far into the zone and getting teleported out.

**Comment by Afgann** [comment]
fixed
