### ISSUE TITLE
Soulkiller Gorr randomly changing Display IDs

### ISSUE THREAD

**Issue by WhitemaneIsa** [gamefreedomgit/Frostmourne#1124]
16387 - Soulkiller Gorr is randomly changing displayIDs after every crash/restart into random human models in every starting area except for nightelves

![grafik](https://github.com/gamefreedomgit/Frostmourne/assets/164479303/7d471544-327d-438f-9c1e-d4df1b8227c6)

![grafik](https://github.com/gamefreedomgit/Frostmourne/assets/164479303/18b034ef-9422-4ebe-9ee7-dd5a9fe2727d)

**Comment by Afgann** [comment]
fixed
