### ISSUE TITLE
Invisible Enemy in Arena

### ISSUE THREAD

**Issue by Stylesxz** [gamefreedomgit/Frostmourne#1125]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
In arenas my partner sees only the red circle beneath the enemy and not his characters, it only happens against a DK

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by WhitemaneIsa** [comment]
We'll need more info and possibly screenshots or videos on this I'm afraid.

**Comment by WhitemaneIsa** [comment]
No further info/complaints, closing.
