### ISSUE TITLE
I have the rating for feet and waist but I still see them red. (desactivated all addons and reloged and reloaded)

### ISSUE THREAD

**Issue by rgslmx** [gamefreedomgit/Frostmourne#1126]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I have the rating for feet and waist but I still see them red. (desactivated all addons and reloged and reloaded)

**How to reproduce:**

**How it should work:**
I should be able to buy the feet and waist

**Database links:**
https://imgur.com/a/JV2ucgQ
https://imgur.com/a/xKI1hDs

**Comment by UltraNix** [comment]
@rgslmx Still valid?

**Comment by WhitemaneIsa** [comment]
No further info/complaints, closing.
