### ISSUE TITLE
Xevozz's Ethereal Sphere pathing issue (prolly general pathing issue)

### ISSUE THREAD

**Issue by LezChap** [gamefreedomgit/Frostmourne#1128]
Got Xevozz in a RHC.  He summoned the Ethereal Spheres and we kited him across the balcony as you do.  Unfortunately, the Spheres decided to path through the floor and straight to him instead of going up the stairs and around, nearly causing a wipe.  (We got him down, but only 1 person was alive and we barely got enough Rez's out to continue the dungeon before the next portal spawned).

The Spheres shouldn't go through the floor, their pathing should more or less follow where players can travel.

I've noticed similar (but less encounter-breaking) pathing issues where the NPCs run through walls in Nexus.  The clearest example I've replicated is the 4 trash mobs before Grand Magus Telestra, if you range pull them and try to LOS them around the wall outside the room (so no one accidentally starts the boss encounter early), 1-2 of the mobs will usually go through the transparent wall and over the void (because you can't hit them there) and start going after a healer or someone else in the party that caused buff-related aggro.

I think this is a general NPC pathing bug, but these are two examples in "end-game content", one of which broke the encounter.

**Comment by LezChap** [comment]
Another example in Drak'Tharon Keep HC today...the Darkweb Hatchlings went about 15-20 yards deep through the wall to bypass the tank/melee and go after the healer.  Looked like they came from wherever they spawn on the left side of the room straight back towards the healer standing to the right of the previous boss which we just killed, while the tank was working on the elites at the doorway.

**Comment by Riztazz** [comment]
Next time this happens please make some screenshots, i need spots to debug, i am running around the instance like crazy and they always path properly

**Comment by Riztazz** [comment]
I am gonna close this as some edge case, maybe fixed with something in-between. If something like that happens again and you have a video, or even a screenshot of where were you guys standing when it happened, please open another issue and post it there, it will help a ton
