### ISSUE TITLE
Not returning to Flight Form after BG/RDF

### ISSUE THREAD

**Issue by LezChap** [gamefreedomgit/Frostmourne#1129]
I'm flying around (actually in Swift Flight Form, if that matters) waiting on queues.  It pops, I do the thing (BG/RDF) and when I teleport out/leave BG, I'm not returned to Swift Flight Form and start falling to my death.

People on mounts are returned to their mount when leaving a BG or teleporting out of an RDF.  Flight Form is essentially a Druid's Flight Mount, and so we should return to that form automatically as well instead of falling and having to remember to reshift (and hope we don't lag on loading before hitting the ground).

**Comment by Afgann** [comment]
fixed
