### ISSUE TITLE
[DK] Nerves of Cold Steel

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#113]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Nerves of Cold Steel is giving you a flat hit % increase as opposed to only increasing your hit % with 1 handed weapons.

**How to reproduce:**
Equip a 2 handed weapon with 5% hit rating and 3/3 NoCS, your melee swings and ability strikes will never miss.

**How it should work:**
Should only increase your hit chance with 1 handed weapons.
"Increases your chance to hit with one-handed melee weapons by 3%"

**Database links:**
https://www.wowhead.com/wotlk/spell=50138/nerves-of-cold-steel

**Comment by Afgann** [comment]
fixed
