### ISSUE TITLE
Dk's Army cooldown reset

### ISSUE THREAD

**Issue by Deserthor** [gamefreedomgit/Frostmourne#1130]
Killing bosses no longer reset the dk's army cooldown after the last update.

**Comment by Dominik-Krzyzanowski** [comment]
There is a problem with Army of the Dead after last update. Today at 11:30 of server time i used spell before the Keleseth on Udgarde Keep, and after the boss, a spell will be still on cooldown.
![afterBoss](https://github.com/gamefreedomgit/Frostmourne/assets/119120022/c73dfc3b-e7b4-4a2a-b692-848794249171)
![beforeBoss](https://github.com/gamefreedomgit/Frostmourne/assets/119120022/dd8395dd-452b-4f84-bc65-3141d533df2e)

**Comment by WhitemaneIsa** [comment]
Apparently this change was decided as needed by Radeghost, so it is not a bug.
