### ISSUE TITLE
The Nexus - Anomalus -Chaotic Rift placement

### ISSUE THREAD

**Issue by yeagerca** [gamefreedomgit/Frostmourne#1131]
**Description:**
In the Nexus, Anomalus can spawn it's Chaotic Rifts below the platform where their model falls to the floor far below.
Remarkably, bounces from Hammer of Justice still hit the Chaotic Rift seen in the screenshot, so it its hit box may have been closer than the clickable model shows.
![WoWScrnShot_062624_001953](https://github.com/gamefreedomgit/Frostmourne/assets/93017663/7f3b3389-8d6a-4f45-aecf-8b722b90aadd)

**How to reproduce:**
Move Anomalus close to an edge of the platform (or the ramp, maybe).

**Database links:**
https://www.wowhead.com/wotlk/npc=26763/anomalus
https://www.wowhead.com/wotlk/spell=47743/create-rift
https://www.wowhead.com/wotlk/npc=26918/chaotic-rift

**Comment by Afgann** [comment]
fixed
