### ISSUE TITLE
RDF HC while server crash does not give emblem rewards

### ISSUE THREAD

**Issue by Cure-whitemane** [gamefreedomgit/Frostmourne#1132]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Yesterday, 25 June 2024 at about 10:55 AM CET we had a server crash. My team and I were running RDF HC while the crash. Once server was up we logged in and continued farming it. We reached and killed the boss, but we did not get rewards x2 Emblem of Valor.

**How to reproduce:**

1. Que RDF HC
2. Server crash
3. KIll last boss
4. No RDF HC rewards

**How it should work:**

It should still track properly even after the crash. We still should be awarded for RDF HC queue

**Database links:**

I do not have any

**Comment by yeagerca** [comment]
The Call to Arms reward satchel is also not retained through a server crash.

**Comment by UltraNix** [comment]
Fixed.
