### ISSUE TITLE
Possible bug for Omor's Hoof (Weaken the Ramparts quest)

### ISSUE THREAD

**Issue by GM-Aule** [gamefreedomgit/Frostmourne#1133]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
One of the items needed to complete the Weaken the ramparts quest, Omor's Hoof, is reported to not be dropping.

**How to reproduce:**
Clear the boss and try to loot the item.
I will try to replicate and update with further information.

**How it should work:**
The boss should drop the item so long as you are doing the Weaken the ramparts quest

**Database links:**
https://www.wowhead.com/wotlk/quest=9572/weaken-the-ramparts
https://www.wowhead.com/wotlk/item=23886/omors-hoof
https://www.wowhead.com/wotlk/npc=17308/omor-the-unscarred

**Comment by PanJanuszek** [comment]
Tested 25x iterations. Couldn't reproduce.

 If you catch it again... we need:

1. Any player could loot?
2. Did you try it on HC or Normal
