### ISSUE TITLE
Solo queue matches same teammates every match

### ISSUE THREAD

**Issue by vedude** [gamefreedomgit/Frostmourne#1135]
**Description:**

When you queue for solo you get the same teammates over and over. I think it may be due to their MMR being close to each other.

This causes heavy imbalance due to low-rated MMR people getting teamed up with higher ones. 

For example in my experience it was like this:

3x people in a team of 18-1900 MMR vs 3x being 1400 MMR.

**How to reproduce:**

The same people who keep queueing always match together in a team versus others.

**How it should work:**

The system should mix people together based on roles in a more randomly manner.

**Comment by UltraNix** [comment]
Teammates matchmaking is based on MMR rating, so you cannot have one player with 1400 MMR and second with 1900 MMR (in general)

**Comment by vedude** [comment]
That would normally be the case. However, in solo que the high rated MMR players will always get grouped vs low MMR players. It's 100% win for the high MMR players and farmable to climb the bracket.

The lower MMR players will suffer like this so I'm not sure if the same system would work out for the solo bracket. It's just my opinion.

**Comment by UltraNix** [comment]
It's because there are not many players at high rates and thus people wait long enough to get any match.
