### ISSUE TITLE
Water Elemental Snapshot

### ISSUE THREAD

**Issue by Paladizz** [gamefreedomgit/Frostmourne#1136]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Water Elemental should be able to be snapshotted

**How to reproduce:**
Proc all Spell Power procs like trinkets back enchant rings etc etc and maximize its damage output

**How it should work:**
Even tho It doesn't work like this in the retail, Warmane did change this so water elemental could be able to snapshot so why not change it here also since frost mage is meh
**Database links:**

**Comment by Manpower99** [comment]
Warmane did not lol. you can login to their blackrock realm and check for yourself..
Water ele without the glyph is a guardian and does snapshot stats, with the glyph is a pet and scales dynamically.
similarly to Raise Dead + Master of Ghouls talent.

**Comment by Paladizz** [comment]
It does snapshot in Icecrown since i've been playing frost mage in there for 2 years I know It does snapshot there

**Comment by Manpower99** [comment]
It snapshots without the glyph yes. thats the normal behavior when its not a permanent pet

**Comment by Paladizz** [comment]
![imagem](https://github.com/gamefreedomgit/Frostmourne/assets/173791019/cada9cf0-28ba-4a8a-b043-957475ce787e)
![imagem](https://github.com/gamefreedomgit/Frostmourne/assets/173791019/8127202c-8384-4748-992f-ff8b18077f67)
first image is without a single trinket proc
second image is with 1 trinket proc 
![imagem](https://github.com/gamefreedomgit/Frostmourne/assets/173791019/dad983ff-8704-416a-890f-5294359f6268)
third image is me having the glyph

**Comment by Paladizz** [comment]
Like i said it snapshots with the glyph in Icecrown

**Comment by Manpower99** [comment]
Then its a bug on icecrown, you probably should suggest this on their discord instead of reporting it s a bug since it isn't
