### ISSUE TITLE
"Call to arms" Bags

### ISSUE THREAD

**Issue by Rippinz** [gamefreedomgit/Frostmourne#1137]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Basically, it says i'm no longer eligible to receive it. It's really annyoing having to restart my game all the time i get that bug. For me personally it's happening every 2 dungeons or so... it's really annoying having to do it every time.

**How to reproduce:**

**How it should work:**

**Database links:**
![image](https://github.com/gamefreedomgit/Frostmourne/assets/86166113/8b60a848-ee08-4a07-bdde-ad449f11646f)

**Comment by UltraNix** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/1022
