### ISSUE TITLE
Being stuck after wipe on dungeon

### ISSUE THREAD

**Issue by Rippinz** [gamefreedomgit/Frostmourne#1138]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Unable to move unless i do /reload after a wipe on any dungeon. 

**How to reproduce:**

**How it should work:**
Should be able to move to dungeon freely

**Database links:**

**Comment by Cure-whitemane** [comment]
Happened to me today for the first time as well

**Comment by Cure-whitemane** [comment]
`/reload` helped tho

**Comment by WhitemaneIsa** [comment]
Did you really test this on *any* dungeon? We need more specific details. Which bosses did you wipe on?

**Comment by Rippinz** [comment]
Yeap did about 4 dungeons total, wipes were on trash packs mostly

**Comment by GM-Aule** [comment]
I can confirm multiple people getting stuck not being able to move in front of the Auchindoun spirit healer and the Azjol-Nerub one. At least a dozen people between both occurrences.

**Comment by LezChap** [comment]
Happened to my party several times last night on Skadi in Utgard.

**Comment by Furiianda** [comment]
Confirmed, happened to multiple members of my party in Heroic Nexus after a trash wipe.

**Comment by UltraNix** [comment]
Fixed.
