### ISSUE TITLE
Retrieving item information takes up to 3-5m after login

### ISSUE THREAD

**Issue by Cure-whitemane** [gamefreedomgit/Frostmourne#1139]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

After login it takes about 3m for the items to be retrieved:

- mail
- quest
- RDF HC queue

![image](https://github.com/gamefreedomgit/Frostmourne/assets/173875910/93adeda3-e8ea-4f1c-ab19-e8240639b0df)

**How to reproduce:**

Once login hower to quest/RDF HC items

**How it should work:**

Should be retrieved instantly

**Comment by WhitemaneIsa** [comment]
@Afgann I know you fixed this but it still happens :( Can you have a look again?

**Comment by Cure-whitemane** [comment]
@BalanCV yeah, good point. I completely missed professions. It even takes longers

**Comment by Cure-whitemane** [comment]
@Afgann @WhitemaneIsa https://discord.com/channels/1040715551531618365/1121481733435572335/1256175239214399508 do we have any update on this?

**Comment by RadeghostWM** [comment]
It will be fixed in the next game patch.
