### ISSUE TITLE
Not able to skip RP from CoS dungeon

### ISSUE THREAD

**Issue by Rippinz** [gamefreedomgit/Frostmourne#1140]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Basically what the title says, only see 1 option from the NPC after completing quest

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
All party members must have the quest completed.
