### ISSUE TITLE
DnD not consuming Cinderglacier rune buff

### ISSUE THREAD

**Issue by Jairocv** [gamefreedomgit/Frostmourne#1141]
DnD not consuming Cinderglacier rune buff

**Comment by WhitemaneIsa** [comment]
https://www.wowhead.com/cata/spell=53341/rune-of-cinderglacier#comments:id=1430042

I'm not sure if this change was added with 4.0 or was already a thing from the get go, but please provide more info/data on that it should be consuming it.

**Comment by Manpower99** [comment]
because it should not, as with og wotlk and classic both confirming it DnD benefits from the buff while the buff is still there but it does not consume it.
even plague strike does not consume it and blood plague still benefits these are all intended wotlk things and not a bug.

**Comment by WhitemaneIsa** [comment]
> because it should not, as with og wotlk and classic both confirming it DnD benefits from the buff while the buff is still there but it does not consume it. even plague strike does not consume it and blood plague still benefits these are all intended wotlk things and not a bug.

Thank you for confirming, that's what I figured too.
