### ISSUE TITLE
Potion Mastery lower than intended proc chance

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#1142]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
PTR tested 500 crafts of Potion of Speed resulting in:

500 crafts - > total 593 pots
x2 proc: 34  (+68 extra pots) 6.8% proc chance
x3 proc: 9 (+18 extra pots)  1.8% proc chance
x4 proc: 1 (+3 extra pots)   0.2% proc chance
x5 proc: 1 (+4 extra pots)   0.2% proc chance (probably lucky proc, should be a bit lower than x4 at around 0.1%)

Combined extra proc chance: 9%

This is half of what is expected and I believe simply doubling the proc chance should make it accurate as the distribution curve among procs seems accurate. Have not tested elixir and transmute mastery but they probably suffer from the same issue as chances are supposed to be same for all 3 specs.

**How to reproduce:**

**How it should work:**
The general consensus among blizzard players regarding this is that proc chance is a probability curve that approaches **20% combined proc** when adding all the possible proc chances.
https://www.reddit.com/r/woweconomy/comments/4dawnm/odds_of_getting_alchemy_procs/
https://www.reddit.com/r/classicwow/comments/10gf5eg/become_a_potions_master_they_said/

"Anyway I computed the following assuming a 1/6 (16.67%) proc chance and it seems reasonable with my experiences as a Potion Master:

P(x=1): 100%
P(x=2): 16.67%
P(x=3): 2.78%
P(x=4): 0.46%
P(x=5): 0.08%
SUM P: 119.98%"

**Database links:**

**Comment by Piootrek** [comment]
The Potion Mastery proc chance comes from Blizzard files and is correctly set to 16%. Closing.
