### ISSUE TITLE
Priest power word shield reflection stuck in combat

### ISSUE THREAD

**Issue by decorlan** [gamefreedomgit/Frostmourne#1143]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The priest talent for power word shield to reflect damage back keeps you in combat.

**How to reproduce:**
Cast power word shield
Take damage
Reflection dmg keeps attacker in combat

**How it should work:**
Should not be in combat when taking the reflect damage as the range is infinite. 

**Database links:**

**Comment by Piootrek** [comment]
Please provide some proof it shouldn't apply combat.
