### ISSUE TITLE
Ulduar - Hodir 25nm

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#1146]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

1. Starlight (gameobject?) hitbox is extremely small. You have to stand in the very middle of it to even have a chance to get the haste buff.

2. Even when standing in the very middle of it, the starlight buff (https://wotlk.evowow.com/?spell=62807) is not consistent. Sometimes you get it for a few seconds and disappears even if you did not move.

1+2 How it should work:
The hitbox of the starlight spell should be high enough that you benefit from the buff even if your character is outside but barely touches the spotlight animation.
The buff should be permanent on your character until you leave the zone described above, or it disappears due to the Npc casting it being frozen by Hodir.

Extra: There might be something that massively drops framerates in this fight. However, this might just be my poor setup during that PTR session. Will update on this with info from future sessions on a different device.

**Comment by Afgann** [comment]
fixed
