### ISSUE TITLE
Ulduar - Thorim 25nm

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#1147]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

1. Thorim should end the encounter at 2% HP not at 0%. When he reaches 2% he stops the fight and does an event speech. At the end of the speech the players can click on the loot chest. Currently he ends the fight when his hp reaches 1.
https://www.youtube.com/watch?v=B7KNPtJ_pHI

2. Dark Rune Champion is immune to disarm, but should not be. (at least on 25man nm)

**Comment by Manpower99** [comment]
His hitbox seems to be significantly smaller than it should be also, forcing melee players to be very close within echothers proximity and possibly killing eachother with chain lightning

**Comment by Afgann** [comment]
fixed
