### ISSUE TITLE
Ulduar - Freya 25nm

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#1148]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

1. Pulling Freya will aggro all the trash packs around the room. This should not happen.

2. Phase 2, When Freya casts Nature bombs there seems to be a delay and she does not cast all the bombs at once causing some bombs to go on the other side of the river (if players choose river zone separation strat)
Freya should cast a bomb per player towards the current position of that player, all at once, not in 2 waves.

**Comment by Dalvae** [comment]
Can confirm

**Comment by Godmatik** [comment]
You can use freedom on roots, should not be possible in pre-nerf

**Comment by Afgann** [comment]
fixed
