### ISSUE TITLE
[Quest] Playing along 

### ISSUE THREAD

**Issue by disruption01** [gamefreedomgit/Frostmourne#1149]
https://www.wowhead.com/wotlk/quest=12528/playing-along#comments

check first comment in wowhead, Tracker Gekgek (NPC id: 28095) should give you this quest after you kill Pitch, which doesn't happen, this way I can't start the Frenzyheart rep chain quest.

**Comment by UltraNix** [comment]
Do you have https://www.wowhead.com/wotlk/quest=12654/the-part-time-hunter?

**Comment by UltraNix** [comment]
Fixed.
