### ISSUE TITLE
[Quest] Supplies for the Crossroads

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#115]
**Description:**
Quest "Supplies for the Crossroads" is not available until you have first completed quest "Disrupt the Attacks". This is a common bug on this core.

**How it should work:**
This quest should be available immediately at level 9 - no other pre-req is required

**Database links:**
https://www.wowhead.com/classic/quest=5041/supplies-for-the-crossroads

**Comment by Afgann** [comment]
fixed
