### ISSUE TITLE
[Quest] Reconnaissance Flight

### ISSUE THREAD

**Issue by disruption01** [gamefreedomgit/Frostmourne#1150]
https://www.wowhead.com/wotlk/quest=12671/reconnaissance-flight#videos:id=972

As you can see in this video, after the helicopter reaches the mountains the engine blows up and the vehicle can be commanded, the issue here is that the vehicle is running by itself the only thing it's controllable it's the right and left directions and by this there is no way to land the helicopter to complete quest since I can't lower down the vehicle.

**Comment by disruption01** [comment]
also to note, the engine is very slow after being blown up and it's not in flames.

**Comment by PanJanuszek** [comment]
You have to click "Spacebar" or jump key. Then helicopter is under your control, client bug.

**Comment by disruption01** [comment]
Bugged, can't land

![image](https://github.com/user-attachments/assets/eace6c11-d5de-442a-8e0d-fec191ee927f)
