### ISSUE TITLE
Quest WG Alliance

### ISSUE THREAD

**Issue by uaresmashed** [gamefreedomgit/Frostmourne#1154]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Quest Toppling the Towers (Ali) impossible to pass

**How to reproduce:**
The quest, when completed, cannot be turned in while playing for an alliance; the quest description says that you need to turn it in to the Horde military leader; this is impossible to do while playing as an alliance.

**How it should work:**
The quest must be available for completion for both factions; you can take it, but you cannot turn it in

**Database links:**
https://www.wowhead.com/wotlk/quest=13539/toppling-the-towers
![WoWScrnShot_062724_121502](https://github.com/gamefreedomgit/Frostmourne/assets/173998894/9dde1b58-6507-4843-8df4-a64a95c3547e)
![WoWScrnShot_062724_121507](https://github.com/gamefreedomgit/Frostmourne/assets/173998894/d382139e-d4ee-425e-87c8-9276a260b339)
![WoWScrnShot_062724_121614](https://github.com/gamefreedomgit/Frostmourne/assets/173998894/702e4ff1-5975-4e70-9d11-d5886fb6e3aa)

**Comment by LezChap** [comment]
This could be a crossfaction bug.  Did you get the quest from it being shared while in a WG raid?

**Comment by uaresmashed** [comment]
> This could be a crossfaction bug. Did you get the quest from it being shared while in a WG raid?

No, I definitely got it from the quest giver
