### ISSUE TITLE
Malygos - Energy usage for drakes in P3

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#1158]
There is some odd issues with using energy for abilities on your drakes in P3, I recall this being a problem on the previous server also that was fixed, guess it was not brought over.

Basically, you need 10 more energy available to use an ability.

For example, if I want to cast the healing spell on the drake, and it costs 10 energy, it will not allow it unless you have 20 energy stocked up, even though it will only use up 10 energy.

This is an issue with all spells.

**Comment by UltraNix** [comment]
Fixed.
