### ISSUE TITLE
XP rates bugged and reset

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#116]
1. XP provided is currently double what it should be

So if you have 5x selected (Default), it is giving 10x instead.

2. If you change your XP rate with .xp set, and then relog, the rate will automatically go back to the default 5x rate (which is actually 10x), even though the displayed XP rate is whatever you set it to before logging out. You need to set it again to fix this.

**Comment by Iramtempuss** [comment]
FYI;
As this ticket also mentions it, the double xp has also been reported in issue 51. If this is fixed on this ticket then that ticket can also be closed.
