### ISSUE TITLE
[Storm Peaks] A Delicate Touch

### ISSUE THREAD

**Issue by disruption01** [gamefreedomgit/Frostmourne#1160]
As you can see in this picture mobs are coming from the wrong side, they should run from the left to the right (check pic) instead from the right to the left, this makes it impossible to complete the quest because the item to place the bomb only works on the left side (check pic) and then I can't trigger any explosion on them

https://wowhead.com/wotlk/quest=12820
![image](https://github.com/gamefreedomgit/Frostmourne/assets/44980177/6b8138e8-f544-421e-8c11-0e8ca8134a98)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/44980177/447137fb-6475-4e0b-a448-8074cca70f81)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/44980177/bb517981-7913-4256-8f2a-75bb7b6705b5)

**Comment by Aeradel** [comment]
After testing, this quest can still be completed by manually killing the creatures.

**Comment by disruption01** [comment]
> After testing, this quest can still be completed by manually killing the creatures.



> After testing, this quest can still be completed by manually killing the creatures.

doubt it, I couldnt .

**Comment by Aeradel** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/171863635/bed05536-4ed0-42ce-ac6c-5c20637f3efc)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/171863635/d5f3bbae-2d9b-48f6-9768-1620e43e4e5c)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/171863635/97490ef2-cbe3-413c-8fa2-c97f0441ad7c)

**Comment by disruption01** [comment]
idk then, I killed a few in the live realm and didn't count, will try again then

**Comment by disruption01** [comment]
Looks fixed on the live realm now, the mobs come from the correct side.
