### ISSUE TITLE
Transmog bug

### ISSUE THREAD

**Issue by Rarii15** [gamefreedomgit/Frostmourne#1161]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Whenever I swap my weapons with macro my transmog of enchants disappearing on both set of weapons(playing rogue) and then when I go to transmog NPC it shows that transmog of enchant is pending. 
![Zrzut ekranu (18)](https://github.com/gamefreedomgit/Frostmourne/assets/174046518/ecde8f77-e644-4d51-93d2-3d189e8580a8)

**How to reproduce:**

**How it should work:**

**Database links:**
![Zrzut ekranu (19)](https://github.com/gamefreedomgit/Frostmourne/assets/174046518/2e86758e-2adb-445e-85d3-428a5396a300)
![Zrzut ekranu (20)](https://github.com/gamefreedomgit/Frostmourne/assets/174046518/6a892044-aafd-442f-b262-174c0cdfb1e7)
![Zrzut ekranu (21)](https://github.com/gamefreedomgit/Frostmourne/assets/174046518/573422ca-a2f7-4ea7-a111-3df77f84379c)
![Zrzut ekranu (22)](https://github.com/gamefreedomgit/Frostmourne/assets/174046518/e13cc0a9-2460-40de-88af-ce12ec07c8eb)
![Zrzut ekranu (23)](https://github.com/gamefreedomgit/Frostmourne/assets/174046518/42b365a5-5e50-49ef-b2bb-c60776adc70c)

**Comment by UltraNix** [comment]
@Rarii15 Show us your macro.

**Comment by WhitemaneIsa** [comment]
No further info/complaints, closing.
