### ISSUE TITLE
Thaddius Aggro

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#1162]
I reported this a while ago as part of a large compilation of bugs, seems like it got fixed one raid ID but it's back again(?)

"When fight begins, Thaddius is already monitoring threat and will snipe a healer at ranged as soon as he is active. His threat table should not be working at all until he becomes active at start of Phase 2."

Happens in 10m and 25m.

**Comment by bandini9** [comment]
I can confirm this happens
