### ISSUE TITLE
Bugged Quest in Zul'Drak

### ISSUE THREAD

**Issue by Nelkel9023** [gamefreedomgit/Frostmourne#1165]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Can't complete the objetives of the quest "It Rolls Downhill"

**How to reproduce:**
Take the quest and try to order a geist to extract a blight crystal

**How it should work:**
 Needs make the Geist go to a crystal, take it and walk up to the Voltarus teleporter to gain credit for the quest

**Database links:**
https://www.wowhead.com/wotlk/quest=12673/it-rolls-downhill

**Comment by LezChap** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/760 Duplicate report.
