### ISSUE TITLE
Missing SPELL_CAST_SUCCESS for Malygos' Vortex

### ISSUE THREAD

**Issue by Nessy27** [gamefreedomgit/Frostmourne#1168]
**Description:**
Malygos isn't sending a SPELL_CAST_SUCCESS event when using his Vortex. This causes the DBM Vortex timer to stop since it uses this event to refresh the timer.

**How to reproduce:**

**How it should work:**
Malygos should send a SPELL_CAST_SUCCESS event when casting Vortex.
eg: SPELL_CAST_SUCCESS,0xF1300070BB000001,"Malygos",0x10a48,0x0000000000000000,nil,0x80000000,56105,"Vortex",0x1

**Database links:**

**Comment by Riztazz** [comment]
fixed, will close once it's live
