### ISSUE TITLE
Kil'jaedan issues (timewalking)

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#1169]
1. Kil'jaedan is meleeing in between his Soul Flay beams which is causing spiky tank damage - he should never melee
2. Mind controlled dragons are able to receive heals, this allows them to cast more than 2 shields per phase. The dragons should be immune to all healing (including their own breaths), each time shield is used it should drain 50% of their health, and thus 2 shields = dragon dead
3. Armageddons stop spawning for an extended period of time after KJ casts "darkness of a thousand souls". They should never stop spawning during phase 4 and phase 5 (except when he is casting Shadow Spikes in intermission)

**Comment by Godmatik** [comment]
Bump

**Comment by RadeghostWM** [comment]
@Afgann

**Comment by Riztazz** [comment]
Fixed, will close once it's live
