### ISSUE TITLE
Spell Queue window is non existent.

### ISSUE THREAD

**Issue by Robosterone** [gamefreedomgit/Frostmourne#117]
**Description:**
Whole functionality of Spell Queue is missing

**What is Spell Queue?:**
The Spell Queue Window is the time in milliseconds in which you're allowed to tell WoW's servers about the next spell you want to cast before your current cast is finished. This defaults to 400 milliseconds. Without this feature, you would experience a large delay (2x average latency) between spells. This also applies to instant-cast spells on the Global Cool-down (GCD). The Spell Queue Window benefits everyone, no matter how low your internet latency is.

When you queue a spell, the queue-system does not allow you to change that spell. For that reason, some find that lowering the Spell Queue Window value improves how spell-casting feels. Be careful not to set the value too low or spell-queueing will not work properly. The recommended delay is at least 100ms higher than your average latency.

**How to reproduce:**
Use any caster class and try to use a spell if time on current cast is lower than 0.4s, nothing will happen.

**How it should work:**
Default Spell Queue should be at 400ms, that means 0.4 seconds.

**Database links:**
Cannot really find anything, but on all others wotlk servers there is spell queue.

**Comment by Manpower99** [comment]
Would be great QoL to implement this. I believe it is called spell batching. Benefitial to server handling also.

**Comment by Robosterone** [comment]
https://web.archive.org/web/20100807214416/http://elitistjerks.com/f73/t88239-resto_pve_compendium_general_discussion Here's some info about spell queue in original wotlk (search for "queueing"). Proof that it was present.

**Comment by Afgann** [comment]
fixed
