### ISSUE TITLE
Prospecting Thorium

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1172]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Yesterday i prospected 400total thorium ores on live realm, 3/10 times the prospecting was giving me nothing basically empty which should not be the case ever.
did not test with other gems yet but will do to see if the loot table on prospecting is incorrect on every gem or not.

**How to reproduce:**
Prospect thorium a good amount of times.

**How it should work:**
Prospecting should guarantee atleast 1 common (green item) gem always, with rng and luck could be more.

**Database links:**

**Comment by WhitemaneChronus** [comment]
The issue is also reported for [mithril ore](https://www.wowhead.com/wotlk/item=3858/mithril-ore)

**Comment by UltraNix** [comment]
Fixed.
