### ISSUE TITLE
Tundra Traveler's mount unusable in Heroic dungeons

### ISSUE THREAD

**Issue by niama1618** [gamefreedomgit/Frostmourne#1173]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The vendors are hostile when in heroic dungeon. Assuming it has something to do with cross faction.

**How to reproduce:**
Mount up in a heroic dungeon with the Traveler's tundra mount

**How it should work:**
Vendor should be interactable for repairs and buying/selling

**Database links:**
Screenshot of the hostile vendors in a heroic dungeon
https://imgur.com/a/Ksazhtk

**Comment by niama1618** [comment]
Hi, more information, it doesn't work in raids too, at least in SWP.

https://imgur.com/a/ZKPorJL

**Comment by UltraNix** [comment]
Fixed.
