### ISSUE TITLE
Aetish shard drop rate is about 15% instead of 30%

### ISSUE THREAD

**Issue by Cure-whitemane** [gamefreedomgit/Frostmourne#1174]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Yesterday we had a nax25 run, for 15 bosses only 2 splinters (mage/priest/dudu) dropped, while war/pal/dk shard drops on Sunwell drop literally every boss. Could you please double-check the likelihood and confirm it works as expected?

Per wowhead its 30% drop rate, but if its 30% then it should 5 shards, but its just 2 meaning its about ~15% drop rate

**How to reproduce:**

Run nax25

**How it should work:**

30% drop rate, currently it seems like it has 15%

**Database links:**

https://www.wowhead.com/classic/item=22726/splinter-of-atiesh

**Comment by Cure-whitemane** [comment]
Please, get me right: in no way I'm demanding or requesting to change it. I'm just curious and ask to check whether it works as it supposed to.

If it does work properly, then thank you for your checks and feel free to close the ticket ❤️

**Comment by UltraNix** [comment]
It is 30%.
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/11ee4193-f9c9-4562-99f2-2881b310da16)
