### ISSUE TITLE
cant destroy / sell totem item

### ISSUE THREAD

**Issue by Matrwa** [gamefreedomgit/Frostmourne#1175]
**Description:** can't sell / destroy totem item

**How to reproduce:** try to sell / destroy totem item

**How it should work:** destroy / sell

**Database links:**
![Zrzut ekranu 2024-06-28 152657](https://github.com/gamefreedomgit/Frostmourne/assets/101882994/56f09690-410c-4082-a980-34e5a2644686)
![Zrzut ekranu 2024-06-28 152708](https://github.com/gamefreedomgit/Frostmourne/assets/101882994/f5b8006f-4bcd-4d3a-86da-31bba41a2a9e)
![Zrzut ekranu 2024-06-28 152838](https://github.com/gamefreedomgit/Frostmourne/assets/101882994/b407e89a-1f87-4d39-8761-37dcedb56082)

**Comment by UltraNix** [comment]
It's inteded.
https://github.com/gamefreedomgit/Frostmourne/issues/992

**Comment by Matrwa** [comment]
and get my 1 bag slot is intended?
