### ISSUE TITLE
Kalecgos - Curse

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#1177]
Some issues with curse on Kalecgos fight. Occasionally they go away.

When a curse goes out, it should NEVER go away until fight is over. If you dispel it, then it should jump to someone else. If it expires naturally, it should jump to someone else. If someone dies with it, it should jump to someone else. If someone takes a portal to shadow realm or gets ported back up to normal realm, the curse should stay on them and not be removed.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
