### ISSUE TITLE
[Item] Sun-Lute's transformation effect replacing others even after use ends

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1178]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Sun-Lute's transformation effect taking priority over any transformation even when not in use.

**How to reproduce:**
Use Sun-Lute's face melter. Afterwards use any transformation, such as Savory Deviate Delight or Iron Boot Flask.

**How it should work:**
Sun-Lute's face melter transformation should only be active during the buff.

**Database links:**

**Comment by RadeghostWM** [comment]
@Afgann - basically when you are under any effect of morph and you wield Sun-Lute, you are morphed into the belf guitarist. Repro: wear sun-lute and go to CoT:Stratholme

**Comment by Alim-ben** [comment]
Yeah i noticed this in ptr forgot to report it

**Comment by Chaos-within** [comment]
Any word on this? Would be nice if custom legendary didn't have VERY annoying morph bug

**Comment by RadeghostWM** [comment]
@UltraNix

**Comment by UltraNix** [comment]
Fixed.
