### ISSUE TITLE
Deathfrost enchant from Ahune bugged

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#1179]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Deathfrost enchant that drops from Ahune makes your weapon cast a composite spell with a damage component and a slow component.

The damage component: https://wotlk.evowow.com/?spell=46579

is supposed to also apply the slow component: https://wotlk.evowow.com/?spell=46629

but currently it does not apply the second part at all.

**How to reproduce:**
Attack a target with a weapon using the enchant, only 150 damage will proc, no other effect

**How it should work:**
Second component should apply to target as well

**Database links:**

**Comment by Riztazz** [comment]
![image](https://github.com/user-attachments/assets/b227ed63-1f8d-4c95-a264-708195a967a7)
Some monsters might be immune, especially bosses. Works as intended
