### ISSUE TITLE
Honor items not refundable

### ISSUE THREAD

**Issue by Withered-11** [gamefreedomgit/Frostmourne#1180]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
It happened on several characters: I bought items with honor, and when I tried to sell them for a refund (blue text was still there with the timer), the item wouldn't sell and there was no error text. No enchants were used. 

**How to reproduce:**
I don't know if it affects only some accounts, since I had a guildmate that said that the refund works for him. Also my client is up to date. Just try to sell the honor item with the timer to a honor vendor and see if the item sells.

**How it should work:**
Selling back the item should give the honor refund and maybe pop the confirmation box "do you really want to get refund for the item"? I don't know if it should appear.

**Database links:**

https://github.com/gamefreedomgit/Frostmourne/assets/174154851/60e8e68e-f459-479b-9cbb-052255845955

**Comment by UltraNix** [comment]
@Withered-11 Have you tried without addons?

**Comment by Withered-11** [comment]
> @Withered-11 Have you tried without addons?

Hey @UltraNix ! Thanks so much for the idea. This one fixed it. It was an addon called "Custom Item Icon Fix" which "Enables icons on custom items". I don't know what it is and where it comes from. Maybe it got in there from a random server when I copied all the addons into the Whitemane folder?
