### ISSUE TITLE
Fix Smelting to show to put on bars using Whitemaine Client

### ISSUE THREAD

**Issue by Toney10** [gamefreedomgit/Frostmourne#1182]
Hello found a bug.... can t see can t find the Smelting button... so i logged on a normal wotlk 3 3 5 client to put it on a bar... having or clicking that mining pick nothing happens... it don t open the thing learned like smelting. Please fix the patch or client.. here are some pictures.

![image](https://github.com/gamefreedomgit/Frostmourne/assets/174189501/70481fdc-69a1-4821-9fa8-98198707e6a6)

![image](https://github.com/gamefreedomgit/Frostmourne/assets/174189501/2c480b6e-a4d4-4168-87aa-9d724f90f6d2)

**Comment by WhitemaneIsa** [comment]
Is this HD or regular WM client or regular client + patch?

**Comment by Toney10** [comment]
It s the HD client already patched that i use

**Comment by UltraNix** [comment]
#706
