### ISSUE TITLE
Jesus mode - Walking on water for no apparent reason

### ISSUE THREAD

**Issue by scrublama** [gamefreedomgit/Frostmourne#1183]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
https://gyazo.com/96978af49b056520fd8c7438a86cef8b

**How to reproduce:**
I think it happend when ally dk gripped me in water but he was also lagging, like his path of frost got permanent up on me, persist thru death. But relog removed it

**How it should work:**

**Database links:**

**Comment by WhitemaneIsa** [comment]
@UltraNix what I dmed you about

**Comment by Manpower99** [comment]
Yup it just happened again, path of frosted while ppl are within my proximity as they left they still were able to walk on water

**Comment by UltraNix** [comment]
Fixed.
