### ISSUE TITLE
Culling of Stratholme Arthas Spawning adds

### ISSUE THREAD

**Issue by bandini9** [gamefreedomgit/Frostmourne#1186]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When you kill mobs on a flamey street before talking arthas and after talking with arthas everything respawns

**How to reproduce:**
Go down to street on flame, clear halfway through, go back to talk with arthas and everything respawns

**How it should work:**
things shouldnt respawn

**Database links:**

**Comment by yeagerca** [comment]
This is the street they are referring to.
![WorldMap-CoTStratholme1](https://github.com/gamefreedomgit/Frostmourne/assets/93017663/687286a2-ff6b-4d6a-bcb0-8672c5281639)
