### ISSUE TITLE
Gnomish/Goblin Engineering cannot be taken after dropping them.

### ISSUE THREAD

**Issue by anelectricrat** [gamefreedomgit/Frostmourne#1187]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

When you drop your Engineering Specialty (Gnomish/Goblin) with the book in Tanaris, after that you cannot take/start any of them again. 

**How to reproduce:**

Drop Gnomish/Goblin in Tanaris , try to take Gnomish/Goblin from Ratchet/Ironforge/etc. depending on what Faction you are.
**How it should work:**

Should be able to get any of the quests and start them from scratch, then complete with the mats the profession quest and then get the profession. Should be able to drop it anytime you want with this :
https://github.com/gamefreedomgit/Frostmourne/issues/792
and then get it again if you do all the steps.
**Database links:**
https://www.wowhead.com/wotlk/quest=3639/show-your-work
https://www.wowhead.com/wotlk/quest=3641/show-your-work

(Final quests to complete)

**Comment by UltraNix** [comment]
You don;t need to start again the quest chain - all you need to do is to use the book again.
