### ISSUE TITLE
Chek the resilience please!

### ISSUE THREAD

**Issue by emztoxe** [gamefreedomgit/Frostmourne#1191]
**Description:**
I would like the resilience of the server to be reviewed since with the little equipment that currently exists, it is not normal for a warrior or a rogue to hit 4k against a person who has 829 resilience. On no server in phase 1 have I seen that outrage hit me.

**How to reproduce:**

**How it should work:**

**Database links:**

![imagen_2024-06-30_194940477](https://github.com/gamefreedomgit/Frostmourne/assets/174270279/9882d54e-3051-4207-875c-2da4d598ee55)

**Comment by WhitemaneIsa** [comment]
No further info/complaints, closing.
