### ISSUE TITLE
 [Spirit of Redemption] 

### ISSUE THREAD

**Issue by Matrwa** [gamefreedomgit/Frostmourne#1192]
**Description:**  [Spirit of Redemption] when you die and get in angel form you can cast spell on yourself even heal like your healthbars 
raise

**How to reproduce:** die with  [Spirit of Redemption] talent cast spell on yourself 

**How it should work:**  [Spirit of Redemption] should not let you to heal you and use spell like guardian spirit 

**Database links:**https://www.wowhead.com/spell=20711/spirit-of-redemption

**Comment by Afgann** [comment]
fixed
