### ISSUE TITLE
Arcane mage Missiles bug

### ISSUE THREAD

**Issue by DescendPT** [gamefreedomgit/Frostmourne#1194]
Arcane missiles sometimes do not do the 5 ticks that it should be doing, just spammed arcane missiles non stop on a dummy and multiple times it only did 4 ticks instead of 5, and this bug happens more once paired with Missile barrage proc.
This is a huge bug for arcane mages. And no, I am not clipping arcane missiles, I'm letting it full cast before I use another skill, this also happens to another player that also tested it.

How to reproduce:
Just cast arcane missiles without proc and sometimes it will only do 4 ticks instead of 5,
With Missile barrage proc cast arcane blast until you have the proc and then cast arcane missiles multiple times does 4 ticks instead of 5.

How it should work:
It should always be 5 ticks of damage, and never 4.

Database links:
https://www.wowhead.com/wotlk/spell=8416/arcane-missiles

**Comment by DescendPT** [comment]
Especially noticeable when having a lot of haste buffs

**Comment by Manpower99** [comment]
seems to be an issue with many channeled abilities losing their ticks, possibly an issue due to spellqueue?

**Comment by DescendPT** [comment]
Maybe, I was on my disc priest on the other day, I casted penance and the last tick didn't go through, but this only occurred 1 time and never happened again, so I just assume I moved or did something.

**Comment by Nihaobeachez** [comment]
@Manpower99 Could be. Dont know bout classic, but warmane also had this issue and people just started to use nochanneling macros, which especially helped if you had a lot of haste. basically forces to game to ignore spellqueue and finish ur channeling ability completely. iirc it should look like this 

#showtooltip Arcane Blast
/cast [nochanneling:Arcane Missiles] Arcane Blast

so even if you spam arcane blast while channeling arcane missiles, it wont interrupt. ofc u can use it with any channeled ability/pair it with

**Comment by Manpower99** [comment]
> @Manpower99 Could be. Dont know bout classic, but warmane also had this issue and people just started to use nochanneling macros, which especially helped if you had a lot of haste. basically forces to game to ignore spellqueue and finish ur channeling ability completely. iirc it should look like this
> 
> #showtooltip Arcane Blast /cast [nochanneling:Arcane Missiles] Arcane Blast
> 
> so even if you spam arcane blast while channeling arcane missiles, it wont interrupt. ofc u can use it with any channeled ability/pair it with

I do use no channeling macros and while the difference is noticable, the issue still happens. warmane spellqueue is different anyway they have something called GCD munching, basically your gcd starts the moment the spell is actually queued rather than when it is casted. on this server the gcd starts when it is casted. i really do hope they find a solution to this

**Comment by UltraNix** [comment]
Fixed.
