### ISSUE TITLE
Sartharion dead with 2 drakes (10m Ascended) again

### ISSUE THREAD

**Issue by D4NTh** [gamefreedomgit/Frostmourne#1198]
We killed Sartharion on 10m Ascended with 2 drakes up, and didn't give us loot from 2drakes again. https://prnt.sc/vyCndzBbWq7p (https://prnt.sc/0HR_LpSrr2_t this is the loot table as proof that we killed Sartharion Ascended with 2 drakes up) Raid ID: 8571
Second time this happens, is there any way to get a compensation for this? 

How it should work:
10m Ascended should drop loot from 25m version of the raid. It also should drop 2xTier (we got 1) and we didn't get any 25m item.

**Database links:**
https://whitemane-server.fandom.com/wiki/Ascended_Raids#Obsidian_Sanctum

**Comment by D4NTh** [comment]
Some of us got also 0 H Obsidian Sanctum on raid-log https://prnt.sc/ZE9sFn3HwLeq
Maybe it's attached to the main bug?

**Comment by alemae96** [comment]
I believe you have to post unedited photos. You can't see the raid group, and you can't see anything that show's it's ascended

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/1025
