### ISSUE TITLE
Warlock infernal incorrect base weapon speed

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#1199]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Currently infernals seem to have a base weapon speed of ~2.6, blizzlike value should be 2.0, same as the felguard and felhunter.

**How to reproduce:**
Use the infernal against any training dummy, in its 60s duration and without any external melee haste buffs it will always hit 23-24 times, the correct amount of melee hits should be 30.

**Comment by UltraNix** [comment]
Not really.
Infernal melee tiemr is reduced by this spell:
https://www.wowhead.com/spell=1098/subjugate-demon
