### ISSUE TITLE
Cooldown Reset: raid, arena, duel

### ISSUE THREAD

**Issue by RadeghostWM** [gamefreedomgit/Frostmourne#12]
We already had this on Dueling, so it was patched to not include profession cooldowns. Basically, it should work like on retail: when you kill a boss, everyone that credited with the kill, has their cooldowns reset, and Bloodlust debuff taken off. 
In case of wipe, what happens is when you wipe and boss resets, your CDs are reset as well, but you MUST be in the raid while the boss resets. So if you release your spirit while boss kills leftovers of your raid, your CDs wont reset, but if you wait patiently until boss resets and combat stops, your CDs will be reset, so then everyone releases spirit and can approach boss as well.

+ add reset CD on duel while in Elwynn/Durotar and Dalaran Sewers; and CD reset after arena match ends (and need to make sure it won't be abused, so for example players cannot go into arenas when they're fighting a raid boss).

**Comment by RadeghostWM** [comment]
@Afgann could u put prio on this? :3

**Comment by Afgann** [comment]
fixed

**Comment by Shineslippers** [comment]
@Afgann Hi. can't find anything else related to this. What's the API event(s) for this? Want to use it in addon or WA.
