### ISSUE TITLE
Combat Rogue - Killing spree jumps bugged

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#120]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Currently the last "hop" of killing spree in a multiple target situation has a chance to put you behind a secondary target that isn't your main attack target. This shouldn't be the case as it leaves you not autoattacking as soon as u exit till u change target or run back to your main target.

**How to reproduce:**
GM isle 2 target dummies. start attacking the one on north then killing spree and the last hop might teleport you behind the one on the south instead of returning you back to your main target(north)

**How it should work:**
https://www.youtube.com/watch?v=ats4GrMUgVc

**Database links:**

**Comment by Manpower99** [comment]
Killing Spree has multiple issues rn, it randomly sometimes attacks from the front on bosses with no restrictions of movement,
it also as this report stated has a chance of putting your character after the final jump in position of secondary targets instead of primary target you casted on.

**Comment by Afgann** [comment]
fixed
