### ISSUE TITLE
Frost Mage Brainfreeze proc

### ISSUE THREAD

**Issue by Baldyshere** [gamefreedomgit/Frostmourne#1200]
When playing frost mage talents the brain freeze proc in the frost tree makes fireball/frostfire bolt instant cast when the proc comes up on screen its not called BrainFreeze. Spoke to GM advised to post on here to get fixed.

**Description:**
Brainfreeze proc when shown up on buffs with the mouse cursor is called "Fireball!" 

**How to reproduce:**

**How it should work:**
It should say Brain Freeze when hovering over the proc on screen.

**Database links:**

**Comment by UltraNix** [comment]
It's not a bug.

**Comment by Baldyshere** [comment]
The GM literally said it was and how's it not
