### ISSUE TITLE
Prospecting Saronite

### ISSUE THREAD

**Issue by Andrej-sv81** [gamefreedomgit/Frostmourne#1201]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The Prospecting skill from JC stopped working on saronite ore. It starts the cast and ends it immediately saying "There are no gems in this".  I dont know if there is a limit on gem possesion on a character but I have 70ish rare gems and quite a bit of uncommon gems in my bank.

**How to reproduce:**
Farmed 7 stacks of saronite. Used the skill on a stack in my inventory.

**How it should work:**
It should start casting and use up 5 ore to produce gems.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.

**Comment by kkacpero1** [comment]
Hey guys. the Prospecting dont work properly. I mean after the update there is chance taht prospecting drop for example 2x Blood stone + 2x bloodstone in one prospecting eariler was chance just for one of the small gems and one big gem for exmaple: 1x bloodstone + 1x scarlet ruby dont kno what was the % of drop each one but now its teribble like in Auctionhouse the price for 1 chalcedony decresse from 70g to 19 per one cuz of this "bug. Also there is a bug with titanium ore? i cant prospecting it its says same thing There no gems in this.

**Comment by UltraNix** [comment]
About saronite - #1220
About titanium - #937
