### ISSUE TITLE
Saronite Ore

### ISSUE THREAD

**Issue by kkacpero1** [gamefreedomgit/Frostmourne#1202]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I cant prospect SaroniteOre cuz i was in raid group when paid for C.O.D saronite ;))))))) (tryed everything like reload/restart client/send all of my saronite to other char then buy new still same shit ;) 
![image](https://github.com/gamefreedomgit/Frostmourne/assets/138106541/3225259c-1596-479d-b1f9-59fc477b5467)
**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/1201
