### ISSUE TITLE
Show Cast bars without targeting like in wotlk classic. or any other wow expansion !

### ISSUE THREAD

**Issue by Alim-ben** [gamefreedomgit/Frostmourne#1203]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Cant see casting bars of adds or players when not targeting, this feature cant be achieved by addons since its 3.3.5a client
Wolk Classic & Ru Hd  Client have this feature enabled.
Ru Hd client 3.3.5a achieved this by patching there wow.exe it even works on whitemane client but since whitemane have custum items & wm+ sub (& lego weapon)  they dont work on the ru Hd client !

**How to reproduce:**
dont target a player & tell him to cast y cant see what his casting !

**How it should work:**
dont target a player & tell him to cast , y can see what's his casting.

**Database links:**
This feature is crucial in pvp  wolk classic have it & all wow expansions after wolk have it !

**Comment by Manpower99** [comment]
Unlikely that they add it to regular wotlk client, but considering it already exists in the regular HD client we have from warmane this likely can be added to the Whitemane one also.
