### ISSUE TITLE
Ghostlands Ribbon Pole not working

### ISSUE THREAD

**Issue by GM-Aule** [gamefreedomgit/Frostmourne#1204]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The Ghostlands Ribbon Pole at Tranquillien does not work.
Once activated your character spins for a few seconds and then stops. There's no beam of light linking the character to the pole while it spins and no experience buff is awarded for spinning.

**How to reproduce:**
Right click the Ribbon Pole.

**How it should work:**
You should be able to keep spinning until you break away from the pole and you should be awarded with the Ribbon Dance experience buff.

**Database links:**
https://www.wowhead.com/wotlk/object=181605/ribbon-pole
https://www.wowhead.com/wotlk/spell=29175/ribbon-dance

**Comment by UltraNix** [comment]
Fixed.
