### ISSUE TITLE
DK Gargoyle spell range is too far

### ISSUE THREAD

**Issue by slicplaya** [gamefreedomgit/Frostmourne#1205]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Dueling a DK, I kite out of range of the Gargoyle, yet it was still casting on me outside of 41 yards. I couldn't even trap launch at 40 because it was so far away.

**How to reproduce:**
Let a DK cast Gargoyle on you, move out of range, and watch the casts continuously occur.

**How it should work:**
The Gargoyle should not be able to cast outside of 30 yards range. Outside of 30 yards range, the pet ai should attempt to move back into cast range and attempt to cast a spell again. Instead, it sits at extended ranges casting nonstop outside of the correct range.

**Database links:**

https://wotlk.evowow.com/?spell=49206

**Comment by Manpower99** [comment]
Every DB including wowhead's classic mention it being 40Y range. it does seem to be casting from much further

**Comment by UltraNix** [comment]
Fixed.
