### ISSUE TITLE
Spell and Melee Leeway does not seem to work

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#121]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Currently after testing with friends in PTR i have concluded that Leeway does not work atm
Leeway has existed in WoW since early in the beta and still exists in retail to this today unchanged and should be part of private servers also.

**How to reproduce:**
Queue Melee and move towards your target
Queue Melee and jump to reach a highground target
Move/jump while casting frost nova/arcane explosion/holy nova
Moving/Jumping while casting Death and decay
Cast whirlwind while moving/jumping
by this you get an idea of how it should work, more examples are traps ( which seems to be already implemented )
hunter autoshots and spells that get outranged by merely 2 yards
cone abilities such as cone of cold and shadowflame
Spells that get ouranged by about 2 yards
There are more that i could list if needed.

**How it should work:**
https://www.mmo-champion.com/threads/2572799-Leeway
video is included in the link.
this is a part of the game that existed from vanilla and still exists in retail.

**Database links:**

**Comment by Afgann** [comment]
fixed
