### ISSUE TITLE
Omen of Clarity and Consumables/Enchants

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1210]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
https://github.com/SunwellTracker/issues/issues/3459

Old sunwell bug that i dont believe was ever fixed. as confirmation with wotlk classic and ofcourse other private servers the mentioned consumables/spellprocs should not be able to proc it but currently do.

Flame Caps
Dragonbreath Chilli
Stormchops
Fiery Weapon
Possibly others too

Edit: it seems it can even proc from thorns and indirect healing from imp.leader of the pack, it shouldn't be. it should be in cat form 3.5PPM ( using 1.0 base attack speed from cat form) white hits only. 
in bear it is also 3.5PPM white hit only but uses base weapon speed as base attack speed for the calculation, with only one blizzlike exception being Maul, even tho its a yellow hit blizzard allowed it to proc OOC so bears in wotlk don't have the same issue as TBC OOC for bears.

**How to reproduce:**

**How it should work:**
Should not proc from those ever

**Database links:**

**Comment by Riztazz** [comment]
Is this still a thing? I've pushed a bunch of fixes some time ago to OOC

**Comment by Manpower99** [comment]
I don't know tbh, its been a very long time. ill close it and do a different bug report if i notice anything.
