### ISSUE TITLE
[Feral Druid] Cat Form and PPM normalization

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1211]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
PPM effects while in Cat Form should be using 1.0 as a basis instead of the equipped weapon's attack speed
Noticable here on Frostmourne Whitemane how cats Berserking weapon enchant procs more than it should because of it.

Due to the RNG nature of PPM and 1.0 Attack speed on cat you can see the proc chance on Algalon during classic for example [here ](https://media.discordapp.net/attachments/952320489320235100/1136205256229916782/image.png?ex=6685039a&is=6683b21a&hm=48feeb50f1a5e35450a4caee35bcbd4e6162bdbab35650c2351f9ebce18ba9cd&=&format=webp&quality=lossless)
One proc for a 2 minute fight.

Using a 5 minute fight algalon in Phase2 Classic you can see the proc in a better light [here ](https://classic.warcraftlogs.com/reports/qPmCz23LMf47RFbX#fight=53&type=auras&source=4&pins=0%24Separate%24%23244F4B%24auras-gained%240%240.0.0.Any%240.0.0.Any%24true%2439160493.0.0.Druid%24false%2459620)
this log shows in an over 5 min fight 8 total procs happened most of which were overlapping and refreshing before the proc even finished.

Using PPM Formula and since Berserking should be 1PPM = ( 1.0 * 1) / 60 = 1.67% (due to rounding up) 
of course this will be improved upon by Haste with Formula being : 1.67% * Attackspeed improvements.
This of course would be different if the druid is in humanoid form and is meleeing with a 3.6 weapon, because then the proc chance would be 6%.

Testing on PTR dummies is giving mixed result which led me to believe the enchant is properly scripted as 1PPM but it was proccing too often within a 1 minute dummy target with barely any melee haste improvement.
Using uwulogs for example [here ](https://uwu-logs.xyz/reports/24-06-30--20-02--Cure--Whitemane-Frostmourne/casts/Littlecigy/?boss=brutallus&mode=25N&s=786&f=964&attempt=0&target=006132)
you can see berserking is being refreshed before it even ends so often within this Brutallus Log who's mostly a stationary boss.
3 applications 
9 refreshes
2 removals 
looking at the results of this feral druid within a [3 minute bossfight](https://uwu-logs.xyz/reports/24-06-30--20-02--Cure--Whitemane-Frostmourne/spell/59620/?boss=brutallus&mode=25N&s=786&f=964&attempt=0&target=006132) leads me to the conclusion it is using the weapon's base attack speed not the cat form's.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Piootrek** [comment]
Fixed
