### ISSUE TITLE
Unique vanilla Food buffs

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1213]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Many food buffs who are not technically well fed buffs are stacking with eachother but should not be.
There should only be 1 Food buff active at a specific time
[Smoked Desert Dumplings](https://www.wowhead.com/classic/item=20452/smoked-desert-dumplings)
[Grilled Squid](https://www.wowhead.com/classic/item=13928/grilled-squid)
[Nightfin Soup](https://www.wowhead.com/classic/item=13931/nightfin-soup)
[Runn Tum Tuber Surprise](https://www.wowhead.com/classic/item=18254/runn-tum-tuber-surprise)
[Dirge's Kickin' Chimaerok Chops](https://www.wowhead.com/classic/item=21023/dirges-kickin-chimaerok-chops)
[Blessed Sunfruit Juice](https://www.wowhead.com/classic/item=13813/blessed-sunfruit-juice)
[Blessed Sunfruit](https://www.wowhead.com/classic/item=13810/blessed-sunfruit)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
I tested all - none of these are stacking.

**Comment by Manpower99** [comment]
> I tested all - none of these are stacking.

[Naked Level 80 tauren hunter](https://cdn.discordapp.com/attachments/1107303630702387300/1258214141823553596/Base_stats_of_a_tauren_80_hunter.png?ex=66873abb&is=6685e93b&hm=d0e37fe0f46c2679e2293ef12688c3b4b24ea782c904f7e21b5b0bd59d62765d&)

And this [One ](https://cdn.discordapp.com/attachments/1107303630702387300/1258215479433101383/image.png?ex=66873bfa&is=6685ea7a&hm=5dfb4a6ebe236eb461ffabd7a7e320fd9810bcf5c66d5f27f622d47ba85ba614&)is after using Dirge + Nightfin soup + smoked desert dumpling. 
all of them are considered food buff and should only have one active at a time

**Comment by UltraNix** [comment]
`This content is no longer available.`

**Comment by Manpower99** [comment]
@UltraNix 
yeah i apologize i will repost it here.
![image](https://github.com/gamefreedomgit/Frostmourne/assets/100322493/fd0592ff-5cec-4c6d-a53a-a3416979b44e)

**Comment by UltraNix** [comment]
Fixed.
