### ISSUE TITLE
Death and Decay

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1214]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Testing on PTR DnD while under frost presence seems to be generating no threat whatsoever.
while in blood presence it did while makes no sense.
using omen addon as a basis.

It also seems to never miss, it should be using the DK's spell hit rating + virulence and debuffs that increase spell hit chance.
and also spell crit rating instead of melee crit rating+ talents and buffs/debuffs that improve spell crit chance rather than melee chance.

**How to reproduce:**

**How it should work:**
Damage * 1.9 [Death and Decay Multiplier] * 2.0735 [Frost Presence Multiplier]

Cast 10+ of dnd on multiple target dummies and notice no misses.
**Database links:**

**Comment by Piootrek** [comment]
Hmm, for me it correctly generates aggro and misses for me. Can you test it on a live server?

**Comment by Manpower99** [comment]
> Hmm, for me it correctly generates aggro and misses for me. Can you test it on a live server?

The miss issue was incorrect, disregard it. as for the Threat issue it is not consistent. i will make sure to figure it out afterwards and get back at you if it happens again
