### ISSUE TITLE
Feral Spirits Enha Shaman

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1215]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Feral Spirits seems to have incorrect base attack speed tested with no haste gear or melee haste buffs.
**they should instead have 1.5** 
Going through all the classic logs 10man without bloodlust and only regular melee haste buffs are applied they do seem to be on a 1.5 base attack speed improved to barely 1.2/1.1.
https://www.mmo-champion.com/threads/696875-Haste-and-Feral-Spirit
this old MMO champion thread seems to confirm it from og wotlk also.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Riztazz** [comment]
They do have a speed of 1.5 though

**Comment by Manpower99** [comment]
> They do have a speed of 1.5 though

Ye i just forgot to close this, i apologize.
