### ISSUE TITLE
Gem swapping mid combat

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1217]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Probably a high prio fix considering how toxic it was when bugged in classic also.
Currently able to swap gems in the middle of combat.

**How to reproduce:**

**How it should work:**
attempting to swap a gem in middle of combat should give u a warning and prevent it from happening.

**Database links:**

**Comment by UltraNix** [comment]
Please - provide source.

**Comment by Manpower99** [comment]
Provide source for why it shouldn't work this way or proof that it works this way on warmane?

**Comment by UltraNix** [comment]
Proof the swapping gems in combat should be forbidden on wotlk 3.3.5

**Comment by Manpower99** [comment]
proof doesn't exist no longer, this is something that is lost to time as every classic wow player couldnt find proof also but it was changed anyway due to primarily toxicity of such a thing. automated weak auras exist nowadays which would make this common practice that will feed to a bigger problem.
i can provide 3.4 proof of it being fixed if you wish, otherwise i simply ask for it to be considered within your dev team.

**Comment by UltraNix** [comment]
Classic wow is not 3.3.5 - different cores, different clients, different games :P

**Comment by Manpower99** [comment]
I totally agree. but again this is something to be considered as this server is technically not even 3.3 due to custom changes etc.
other private servers did the same to prevent the issue that comes with this thats why im bringing it to your attention.

**Comment by UltraNix** [comment]
We don't care about other servers.

**Comment by WhitemaneIsa** [comment]
> I totally agree. but again this is something to be considered as this server is technically not even 3.3 due to custom changes etc. other private servers did the same to prevent the issue that comes with this thats why im bringing it to your attention.

I'm a little dumb here, what issues is this causing?

**Comment by Manpower99** [comment]
> > I totally agree. but again this is something to be considered as this server is technically not even 3.3 due to custom changes etc. other private servers did the same to prevent the issue that comes with this thats why im bringing it to your attention.
> 
> I'm a little dumb here, what issues is this causing?

Prior to the classic fix players were able to swap haste gems along with both tbc and wotlk thundering skyflare meta gem in order to maximize their haste for gargoyle. and since swapping gems do not have an ICD you can theoretically keep a 100% uptime on Thundering Skyflare meta gem for example.
players who wish to log their parses would then do this in order to maximize their potential damage on logs.

**Comment by BalanCV** [comment]
I agree, meta gem swapping mid combat is a very bad incentive for playstyle as you can just automate it with a weakaura. Incentivizing stacking bag with gems for parse doesn't seem like a good idea for any server. There isn't any skill involved with automation just plain sadness.

**Comment by WhitemaneIsa** [comment]
I think this is not a bug but rather a Game Design decision then. @RadeghostWM

**Comment by RadeghostWM** [comment]
While it was possible in earlier expansions, even in Wrath, this is certainly something that wasn’t intended. No healthy gameplay should force player to create macros to automatically swap gems left and right while in combat. 

While not „blizzlike”, as in this did happen in original Wrath, it should be made impossible to swap gems mid combat. It wasn’t a problem then, because people didn’t know much about the game, but after so many years, when players explored every possible option to maximize output, it starts to become a problem. It was just not really discovered then.

**Comment by UltraNix** [comment]
Fixed.
