### ISSUE TITLE
[Transmog] Foam Sword

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1219]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Foam Swords aren't being added to Transmog list after being added to appearance collection

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/wotlk/item=45061/foam-sword
https://www.wowhead.com/wotlk/item=45176/foam-sword
https://www.wowhead.com/wotlk/item=45177/foam-sword
https://www.wowhead.com/wotlk/item=45178/foam-sword
https://www.wowhead.com/wotlk/item=45179/foam-sword

**Comment by WhitemaneIsa** [comment]
Their appearance cannot be used for transmog.
