### ISSUE TITLE
Warrior Sword Spec Talent and Rogue's Hack and Slash proccing white hits instead of yellow

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#122]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Currently the procs are glancing and when i dual wielded they started missing which would imply it currently functions as pre tbc version

**How to reproduce:**
Currently when it procs its resetting swing timers since its a white hit
its also glancing and missing since we are dual wielding as rogues, i have tested it while dual wielding swords as arms warrior too and the result is the same.
https://imgur.com/1i3IPU2
https://imgur.com/W9kbTAc

**How it should work:**
They Shouldn't reset the swing timer.
they shouldn't glance.
nor miss while dual wielding.
easy fix is to do exactly as the patch notes which is turn them into yellow mainhand hits

https://imgur.com/Mge2Eie
https://imgur.com/nkwGRZL

**Database links:**
https://www.wowhead.com/wotlk/spell=12815/sword-specialization
https://www.wowhead.com/wotlk/spell=13964/hack-and-slash

**Comment by Afgann** [comment]
fixed
