### ISSUE TITLE
Judgement of Righteousness + Seal of Righteousness DMG Order

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1221]
https://www.wowhead.com/wotlk/spell=21084/seal-of-righteousness#comments
The Problem: Currently seal of righteousness when used with judgement deals dmg AFTER the judgement hit.

How it should work: Correct dmg order when using judgement is: SoR -> Judgement of Righteousness.

This bug is frustrating for 2 reasons:
1.) If the paladin judges a target that has an absorb effect, and the judgement dmg is less than said effect, but the Judgement + Seal dmg combined is more, that means the paladin should receive mana from judgements of the wise talent.

Currently this interaction doesn't happen.

2.) if the paladin judges a target, like a totem that has a small amount of HP, and the seal dmg is enough to kill the target, the judgement dmg shouldn't proc, so no mana should be restored.
Currently this is the exact reverse.

Let's not get into the details of the correct proc order for all the stuff that procs off of a judgement spell, this is the most game breaking bug.

How to reproduce: Cast judgement on any target with SoR buff.

https://www.warcraftmovies.com/movieview.php?id=165369

27:40 for instance

**Comment by haephaistoss** [comment]
In case you wanna fix the correct proc order I'll leave it here:

Player casts  https://www.wowhead.com/wotlk/spell=20271/judgement-of-light

That procs (if the judgement crit roll is a crit) - thus the judgement and seal proc benefit from the increase after this step
https://www.wowhead.com/wotlk/spell=20053/vengeance

Next proc is debuff application
https://www.wowhead.com/wotlk/spell=20185/judgement-of-light

Next is seal dmg

https://www.wowhead.com/wotlk/spell=25742/seal-of-righteousness

Next is the actual judgement dmg

https://www.wowhead.com/wotlk/spell=20187/judgement-of-righteousness

Then HotC is applied

https://www.wowhead.com/wotlk/spell=54499/heart-of-the-crusader

Then AoW

https://www.wowhead.com/wotlk/spell=59578/the-art-of-war

Then RV

https://www.wowhead.com/wotlk/spell=61840/righteous-vengeance

Same for all other judgements - except, that for some no extra seal dmg is applied, so that step is skipped, everything else is the same.

Fun fact if you pay attention to the combat log in this or other videos:

Heart of the Crusader is applied twice - once for the judgement of light application and another one for the judgement of rigteousness hit. I skipped this here, I saw no rason to waste time on it.

**Comment by UltraNix** [comment]
Fixed.
