### ISSUE TITLE
Winter's Chill Application Delay Missing

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1222]
https://www.wowhead.com/wotlk/spell=28593/winters-chill
The Problem: Winter's Chill's application is instant now.

How it should work: Winter's chill application should be roughly 200 ms later than the slow that applies it.
This should open up window for counterplay to spam magic removal spell and ALWAYS remove the slow first, if no other magic debuffs are present on the target.

How to reproduce: Cast any slow with winter's chill talent active on a mage onto any target.

https://www.warcraftmovies.com/movieview.php?id=164185

-49:57 -- around 0:56 in the video.

**Comment by UltraNix** [comment]
You were able to notice 200ms delay on that video? :)

**Comment by haephaistoss** [comment]
Ice Lance

It wasn't an exact 200 ms number on retail, it was tied to update cycles, but private servers mostly don't replicate that.

The mechanic however, is pretty important, as you can see in PvP - it guaranteed, that if cleanse or dispel magic was spammed in time it would **always** remove the slow, or frost nova, or similar effect first.

**Comment by haephaistoss** [comment]
https://youtu.be/-J55f0puu9A?t=284

Some update - look at the application of winter's chill - it's each and every time is delayed

**Comment by UltraNix** [comment]
Fixed.
