### ISSUE TITLE
[REQUEST] Class - specific BiS items to the PTR Vendor

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1223]
I'm requesting the addition of 2 items to the test server vendors, since I can't seem to find any other quick way of getting them:

https://www.wowhead.com/wotlk/item=30846/arcanum-of-the-outcast

https://www.wowhead.com/wotlk/item=33504/libram-of-divine-purpose

The latter needs some testing as it is BiS throughout wotlk - at least since the removal of Seal of Blood in 3.2

**Comment by WhitemaneIsa** [comment]
Added both to the Enchanting Vendor. .... I know the relic is not an enchant but I fat fingered and can't remove it. Should still be good enough.

**Comment by haephaistoss** [comment]
Thanks!

Is it possible to somehow add rep to power city too?

Without it the enchant can't be used.

Or remove the rep requirement?
