### ISSUE TITLE
Gretta the Arbiter [NPC id: 29796]

### ISSUE THREAD

**Issue by disruption01** [gamefreedomgit/Frostmourne#1227]
This NPC should offer a new daily everyday.
Sometimes it simply doesn't, today is an example of it.

**Comment by UltraNix** [comment]
@disruption01 I assume you've fulfilled all required prerequisites for these quests?

**Comment by disruption01** [comment]
Yes I did all the prerequesites. Been doing the dailies just sometimes theres none.

**Comment by UltraNix** [comment]
@disruption01 Random or maybe some specific quest does not appear?

**Comment by disruption01** [comment]
Hard to tell. I think I only did the ones where you duel and fight in the pit with the bear

**Comment by disruption01** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/44980177/6515891d-7b19-4e8e-8760-a66e53778ade)
right now, no daily.

**Comment by disruption01** [comment]
From all of the 3 I never saw this one

![image](https://github.com/gamefreedomgit/Frostmourne/assets/44980177/6834011d-5ee1-4509-9d55-55ee6a433bcd)

maybe thats the bug, this quest maybe missing

**Comment by UltraNix** [comment]
I've been testing this for a couple days now - everyday I have always one quest available there.

**Comment by disruption01** [comment]
I don't. Yesterday I didn't and I never got "Maintaining Discipline"

**Comment by disruption01** [comment]
> @disruption01 Poke me in Discord.

added as silverech0

**Comment by disruption01** [comment]
I never got back to do these quests since I got the polar bear. Maybe you can close if no evidence of being bugged
