### ISSUE TITLE
[PALADIN] Seals of the Pure

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1229]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Bonus DMG should be multiplicative, currenlty it is addittive - only in terms of Seal of RIght.

**How to reproduce:** With talented seals of the pure and Glyph of SoR the dmg is off by 1.5 % from the theoretical dmg -> so it must be handled incorrectly, client data suggests it should be addittive as it is with every other spell, but developers had no idea how to program this shit apparently.

**How it should work:** The 15 % dmg part from Seals of the Pure with SoR should stack multiplicatively with the rest of the multipliers.

**Database links:** https://www.wowhead.com/wotlk/spell=20332/seals-of-the-pure

**Comment by haephaistoss** [comment]
Edit: I linked the wrong spell - redid the test, and fixed the report.

**Comment by Afgann** [comment]
fixed
