### ISSUE TITLE
Divine Storm Normalized to 3.3 WS?

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1231]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** In my testing on the PTR Divine Storm spell seems to be normalized to 3.3 weapon speed like most melee abilities. Auto attacks are fine that's why I'm guessing normalization is the culprit.

**How to reproduce:** Hit the training dummy.

**How it should work:** It shouldn't be normalized to 3.3 weapon speed, the divine storm spell is an exception to this rule.

**Database links:** https://www.wowhead.com/wotlk/spell=53385/divine-storm

**Comment by Piootrek** [comment]
Please provide some proof.

**Comment by haephaistoss** [comment]
https://www.wowhead.com/wotlk/spell=53385/divine-storm

<img width="571" alt="image" src="https://github.com/user-attachments/assets/9aaaccba-111e-4eac-806a-3108dda0e7d8">


https://www.wowhead.com/wotlk/spell=1680/whirlwind

<img width="611" alt="image" src="https://github.com/user-attachments/assets/11407547-9dc9-418b-918d-e3422bc15425">


It is widely known to never have been normalized, common knowledge basically. Logs can also confirm this:

http://www.worldoflogs.com/reports/up5rno2y5w0lta6h/xe/?x=sourceName+%3D+%22Elovie%22+and+spellid+in+(35395%2C+53385%2C+42463)&page=2

**Comment by Piootrek** [comment]
Fixed
