### ISSUE TITLE
Druid and Celestial Steed not obtaining 310% flight speed when owning a 310% flying mount

### ISSUE THREAD

**Issue by Spacemuffin007** [gamefreedomgit/Frostmourne#1233]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Druid's swift flight form and celestial mount should both increase to 310% flying speed when you have obtained a 310% flying mount. 

**How to reproduce:**
Own Celestial Steed, Druid Swift Flight Form and own Ashes of Al'ar. Ashes of Al'ar is a 310% speed mount. Which then should prompt Celestial Steed and Druid Swift Flight Form to also increase to 310% speed. 

**Database links:**

https://wowwiki-archive.fandom.com/wiki/Patch_3.2.0#Druid
https://www.wowhead.com/wotlk/spell=75614/celestial-steed#comments
https://wowwiki-archive.fandom.com/wiki/Patch_3.2.0#Druid

**Comment by Riztazz** [comment]
They do, if you test with celestial steed - it properly updates the tooltip, sadly the same cannot be done for flight form and it might display 280% but under the hood you're flying at 310% speed. Given that you have access to some 310% flyer.
