### ISSUE TITLE
Army of the Dead taunting raid bosses (level ??)

### ISSUE THREAD

**Issue by Casandy** [gamefreedomgit/Frostmourne#1234]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Using army of the dead when fighting Grobbulus and now Malygos made the boss turned to us, even when the tank was 30k+ on threat and wipe us because of their respective tactics.

**How to reproduce:**
Use Army of the Dead and see the boss turning towards the raid where the army is.

**How it should work:**
Army of the Dead should not taunt the raid bosses.

**Database links:**
https://wowwiki-archive.fandom.com/wiki/Army_of_the_Dead

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/701
