### ISSUE TITLE
[25N Ulduar] PTR 03/07/23

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1236]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
these were all done in 25man normal with gear obtaintable only through T7 content ( including atiesh and sun lute but no thoridal ), with many players using "realistic bis" instead of full 226 bis.

**General Issue** : 
CDs are not resetting.
Bosses dropping Emblem of Heroism

**25N Flame Leviathan Normal Mode** :
1.The Vehicles were being dazed, this could either be a general issue with vehicles or them being affected by aspect of the pack but shouldnt be.
2.Barely any pyrite in the air

**25N XT  Normal Mode :**
1.the second time Heart normally would appear it did not, we still had to wait for the phase to be over to attack XT again as he is untargetable during Heart Phase of course but the Heart was not there. bug does not happen consistently 

**25N Kologarn :**
1.Focused Eyebeam got casted in melee range despite there are out of melee range/ranged targets available.

**25N Mimiron HM :**
1.Proximity Mines do not have a grace period and explode immiditely on impact if there is a player within the proximity, there should be a slight delay upon landing before they can explode for players to be able to react, on many videos the "arming" of the bomb even has a slight animation. [timestamped here you can see it](https://youtu.be/Uzr0VBcL27Y?si=GymD0kpnXmbzL5kM&t=24)
2.the facing of phase 2 VX-001 whenever he casts P3Wx2 Laser Barrage is shifting initially.
3.Phase 4 Laser Barrage should fix the boss in position in other words root him, boss should not move and turn during laser barrage.
4.Emergency Fire Bot either not extinguishing fire or the radius is too small, as observed in this [classic video](https://youtu.be/KCk7xMx0lT4?si=5fBtrjT4pTbL2DAL&t=346) the radius is quite noticable
5.Since this is normal 25man the Fire Emergency Bot shouldn't be using Deafening Siren Spell
6.[Mimiron Teleporter](https://wowpedia.fandom.com/wiki/Ulduar_Teleporter) Spark of Imagination was not available to us after engaging mimiron. the rest of the teleporters seem to work fine but we did not test all of them.

**25N Algalon :** 
~~1.The edges of the black hole spawned from the death of a Collapsing Star is able to go out of bounds which shouldn't happen. Videos from both retail and classic both showcase the movement patterns of the stars never go too close to the walls to begin with so this issue should never occur~~ seems this did occur sometimes on classic as i have found one vod of it happening.
2.An issue relating to the platform when it comes to summoning players/pets/summon stone sometimes falling through.
pets seem to also fall whenever they move but try and get back up.
3.His Swing timers seem very off based on [Death logs](https://cdn.discordapp.com/attachments/962061368901652490/1258164322539143279/image.png?ex=66870c56&is=6685bad6&hm=651de0d915bf107298be9f257052dc28d3e10d5ca441c42569c4cd8ca2914ec9&) of two t7 geared tanks. do keep in mind we have death knights applying a Attack Speed Reduction Debuff on the boss.
Here is a [log ](https://classic.warcraftlogs.com/reports/bXda38F2TgKf64jz#fight=35&type=damage-taken&source=2&target=202&ability=1&options=38)from wotlk classic algalon on 25 as a reference, the gaps are of course whenever the tank went in for big bang.

4._This one will need further testing_ it seems the Splash damage of cosmic smash has a higher proximity damage than it should be? players pretty far from it were taking substantial damage.
will try next PTR session to see if it ever targets pets for its initial location of cosmic smash, it shouldnt be a thing.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by disruption01** [comment]
"The edges of the black hole spawned from the death of a Collapsing Star is able to go out of bounds which shouldn't happen." wrong, on wotlk classic this happened.

**Comment by BalanCV** [comment]
Also i think mimiron suffers from #1020 as well

**Comment by Afgann** [comment]
fixed
