### ISSUE TITLE
[DK] Frost Fever and Blood Plague Snapshotting

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1237]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Currently the 2 aforementioned debuffs snapshot at the moment of application.

**How to reproduce:** Apply any of these DoTs to any target

**How it should work:** They shouldn't snapshot, instead before every tick they should recalculate the amount of dmg to deal.

**Database links:** https://www.wowhead.com/wotlk/spell=55095/frost-fever#comments 
https://www.wowhead.com/wotlk/spell=55078/blood-plague#comments

**Comment by haephaistoss** [comment]
Also they keep both the player and the target in combat, which shouldn't happen.

**Comment by Manpower99** [comment]
??
They should snapshot percentage damage increases, what they shouldn't snapshot is the attack power when casted and each tick should be dynamic.
this was tested in classic also using Cinderglacier enchant and that is how its intended. you can even keep them permanently rolling using Glyph of Disease/Pestillence.

**Comment by haephaistoss** [comment]
Yup that's what I meant.

Sry it's almost 3 am here, I just wanted to out this here so I can finish polishing tomorrow.

But yes, what I meant exactly.

Serpent sting works the same way too

**Comment by WhitemaneIsa** [comment]
... So if they should snapshot and they do, where is the bug?

**Comment by haephaistoss** [comment]
They snapshot AP curreny, which they shouldn't. Each tick should be dynamic.

**Comment by Sylanha** [comment]
They way it works right now is how it is supposed to work. Each tick should snapshot with the attackpower that the Player currently has while casted. For example if I have a 5000 AP buff and apply frost fever, it is supposed to do increased damage throughout the whole tick up until the point where the dot drops or I reapply it without 5000 AP.
It works the same with other classes that have dots, like Warlock, Shadow priest or Boomie. It is a normal wotlk mechanic

**Comment by Manpower99** [comment]
> The way it works right now is how it is supposed to work. Each tick should snapshot with the attackpower that the Player currently has while casted. For example if I have a 5000 AP buff and apply frost fever, it is supposed to do increased damage throughout the whole tick up until the point where the dot drops or I reapply it without 5000 AP. It works the same with other classes that have dots, like Warlock, Shadow priest or Boomie. It is a normal wotlk mechanic
Ye it snapshots %
and you're absolutely right on the disease's AP snapshot actually. ive checked warcraftlogs
https://classic.warcraftlogs.com/reports/pKHPhyTFkbtWNQmD#fight=53&type=damage-done&source=30&ability=-55095
you can see that up until the 2nd application the damage was the same

**Comment by haephaistoss** [comment]
I recall snapshot on this reacting to greatness procs somehow, but it may have been just cata prepatch then.

worldoflogs are gone forever sadly so this is the best we could dig up 🫡
