### ISSUE TITLE
Wintergrasp "join the battle" when on FP

### ISSUE THREAD

**Issue by LezChap** [gamefreedomgit/Frostmourne#1239]
If you're on a FP and it flies through Wintergrasp while a battle is taking place (and also probably the 15 minutes before a battle), it asks if you'd like to queue into the battle.

As far as I remember, people on Flights over Wintergrasp should not be getting these messages.  I didn't want to cancel/decline and risk getting TP'd off the FP, but I think that happened once weeks ago too.

**Comment by Afgann** [comment]
fixed
