### ISSUE TITLE
Living Bomb

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#124]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
On PTR right if you have living bomb on the target you cant reapply it to refresh duration which removes a layer of playing fire mage

**How to reproduce:**
Apply living bomb on target
try to apply it again > cant till it explodes

**How it should work:**
should be able to refresh it whenever you can if you feel like delaying the explosion or even by a missclick thats how the spell should work

**Database links:**
https://www.wowhead.com/wotlk/spell=44457/living-bomb

**Comment by Afgann** [comment]
fixed
