### ISSUE TITLE
Alliance "Trespassing" Zone in Dalaran extends into the street.

### ISSUE THREAD

**Issue by LezChap** [gamefreedomgit/Frostmourne#1240]
The "Alliance Only" area of Dalaran extends past the building and onto the common areas of the street, especially at the corner near the bank and behind the tree selling food in the center.  This causes Horde players who cut these corners too closely to be teleported and stunned for a couple seconds in Dalaran.

**Comment by Manpower99** [comment]
Very noticable whenever near the walls of the alliance zone but not actually trying to trespass.

**Comment by Afgann** [comment]
fixed
