### ISSUE TITLE
[HUNTER] Serpent Sting Keeping Combat

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1241]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Serpent Sting keeps both the player and target in combat. - From previous testing it seems like a global issue with DoTs, gonna look into it further.

**How to reproduce:** Cast serpent sting on a training dummy

**How it should work:** DoTs should NOT keep combat at all.

**Database links:** https://www.wowhead.com/wotlk/spell=49001/serpent-sting

**Comment by disruption01** [comment]
training dummies have a special script it's not like they're the best options to test these things. test on a normal mob

**Comment by haephaistoss** [comment]
Same result

**Comment by Piootrek** [comment]
@haephaistoss  How did you test in on normal mobs?

**Comment by haephaistoss** [comment]
> @haephaistoss How did you test in on normal mobs? Edit: Fixed it on training dummies, on normal mobs it's working correctly.

No, i was focused on pvp spells mostly, and I made these at the start of my reporting carreer, I thought these were global, but it later turned out they weren't

**Comment by oneadanut** [comment]
There is another issue related to target dummies. If 2 players attack a target dummy and one of them stops, he will be kept in combat until the other player stops attacking. The only way to remove combat is to run far away from target dummy or to wait for the other players to stop attacking the target dummy.

**Comment by Piootrek** [comment]
> There is another issue related to target dummies. If 2 players attack a target dummy and one of them stops, he will be kept in combat until the other player stops attacking. The only way to remove combat is to run far away from target dummy or to wait for the other players to stop attacking the target dummy.

Fixed too
