### ISSUE TITLE
[DK] Rune of the Fallen Crusader

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1244]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** PPM seems very high. It should be 1 PPM, now it's constantly applied...

**How to reproduce:** Equip the enchant and start hitting the dummy.

**How it should work:** It should equal roughly 2 PPM. 

**Database links:** https://www.wowhead.com/wotlk/spell=53344/rune-of-the-fallen-crusader#comments

**Comment by Manpower99** [comment]
it is very well known that it's 2 PPM same as original wotlk as classic
https://web.archive.org/web/20100912010601/http://elitistjerks.com/f72/t94207-dk_mechanics_discussion/

**Comment by haephaistoss** [comment]
True, I thought Ulduar wasn't live yet, my apologies. I'm only on the test server.

https://wowpedia.fandom.com/wiki/Rune_of_the_Fallen_Crusader?oldid=2290314
Can be seen here too.

Currently it's constantly on, even with simple auto attacks

**Comment by Manpower99** [comment]
No need for assumptions i posted one elitist jerks findings and can post atleast 3 more.
We are on 3.3.5a class balance regardless so it would be 2PPM from naxx to ICC.
even on cataclysm it remained 2PPM.
https://www.mmo-champion.com/threads/1345790-Rune-of-the-fallen-crusader-and-it-s-procs-uptime

**Comment by Manpower99** [comment]
https://classic.warcraftlogs.com/reports/TD7ZCJ8zNxjav9rL#fight=18&type=auras&source=6
every log on classic confirms it with over 80% uptime on frostdk and over 90% uptime on dual wield unholy.

**Comment by WhitemaneIsa** [comment]
@RadeghostWM opinion?

**Comment by haephaistoss** [comment]
Measured 18 applications in a 3 min testing window, with 100 % uptime.

That's too many even for 2 ppm currently.

**Comment by RadeghostWM** [comment]
We will check this. Despite being on 3.0 content we do use 3.3 balance, so it should be 2PPM. @Afgann

**Comment by Manpower99** [comment]
Out of curiosity @Afgann if possible what PPM was it on prior?

**Comment by Afgann** [comment]
@Manpower99 it was 4PPM before.

**Comment by Manpower99** [comment]
> @Manpower99 it was 4PPM before.

Thank you!

**Comment by Afgann** [comment]
fixed
