### ISSUE TITLE
[PALADIN] Seal of Corruption / Vengeance

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1245]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** DoT is not dynamic, it should recalculate dmg with every tick. Also keeps combat for both player and target. This shouldn't happen at all.

**How to reproduce:** Hit a dummy with the seal active.

**How it should work:** See above.

**Database links:** https://www.wowhead.com/wotlk/spell=53736/seal-of-corruption   https://www.wowhead.com/wotlk/spell=31801/seal-of-vengeance

**Comment by UltraNix** [comment]
#1247
