### ISSUE TITLE
[MAGE] Arcane missiles

### ISSUE THREAD

**Issue by Pixipu** [gamefreedomgit/Frostmourne#1246]
**Description:** Arcane missiles sometimes send out 4 missiles instead of 5, without taking damage, moving or casting another spell before the cast for arcane missiles finishes.

**How to reproduce:** Hit a dummy

**How it should work:** It should always send out 5 missiles if not you aren't hit, if you move or if you cast another spell before finishing the cast.

**Database link:** https://www.wowhead.com/wotlk/spell=8416/arcane-missiles

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/1194
