### ISSUE TITLE
[DK] Unholy Blight vs Absorb

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1249]
If the death cil dmg has been absorbed, UH Blight is still applied to the target.

This shouldn't happen.

Similar to Paladin Judgement -> mana restore, Warrior rend proc -> OP. (These work fine, jsut tested them)

https://www.warcraftmovies.com/movieview.php?id=157161

7:26 for instance

Game breaking because in the case of DC having been absorbed, the disease-dispel lock mechanic shouldn't apply - offering a counterplay against DKs, which is currently nonexistent.

**Comment by Afgann** [comment]
fixed

**Comment by haephaistoss** [comment]
@Afgann is it on live?

I started a DK, and lvled up using WSG, and I distinctly remember even took some screenshots of absorbed death coils applying UHB.

It was against a priest specifically

**Comment by haephaistoss** [comment]
just tested it, it still applies on the PTR too through absorb

**Comment by haephaistoss** [comment]
![image](https://github.com/user-attachments/assets/488388b7-81a7-477a-9deb-0cb0284b6898)
