### ISSUE TITLE
Trinket Eye of Gruul does not work :(

### ISSUE THREAD

**Issue by ftj-prog** [gamefreedomgit/Frostmourne#1250]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Trinket Eye of Gruul does not consume the buff

**How to reproduce:**

Equip the trinket and proc it - it will not consume the buff for the mana reduction.

**How it should work:**

It should consume the buff and provide a mana reduction

**Database links:**
https://www.wowhead.com/wotlk/item=28823/eye-of-gruul

**Comment by ItsPope** [comment]
Still does not work :(

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
