### ISSUE TITLE
[SUGGESTION] PVP - only toon as an option?

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1251]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** The idea came after having looked at the PvP discord channel, and some ppl complained about the PvP scene, which is quite often the case with wotlk realms - pvpers don't rly wanna sink time into lvling and doing dungeons to get their arena bis items etc...

I'm not sure if it is even possible, but if it doesn't eat up a ton of resources, maybe you could create the option to play pvp only characters on the main realm, like a test char on blizz nowadays, where the person gets a max lvl char with starting gear, and off ya go - with the limitation that they can't enter raids or dungeons for instance, or even use the AH to sell stuff, their only way of getting gold or any resource is through doing PvP.

Instead they could have a hidden aura that enables them too a set of vendors invisible to the 'normal' characters, that lets them access their PvE bis items for honor points - thus incentivizing BG-s.

Also rated duels could also be an option, even a separate arena q can be added with a ladder on the website. Some servers did it back in the day and it was a success, lots of ppl played it in their spare time.

I know a few friends who are looking for a place to play pvp only, with warmane blackrock being the only alternative, but their spell scripting is just the lowest quality shit on the market, and gets boring pretty fast.

I think maybe you could stand a chance to challenge their monopoly in the pvp space.

With the legendary idea you're doing rn (which I find actually fun) you can capitalize on this not only for the PvE crowd, but also the PvP too, and we shall meet at the crossroads anyway.

I've started to test how class spells work - and aside from a few minor hiccups I'm pleasantly surprised by the quality of spells and interactions, with some polishing you guys can actually be top notch.

Still raidlogging may be an issue later into contents.

I couldn't find a char boost to lvl 80 on the website, or a char AH on the website, so I have no idea how to get into the game without doing pve shit first - so me and a few pvpers are just gonna chill on the PTR and help you by reporting broken spells to make it truly top quality - you can decide what to do with the knowledge we share.

With your aggressive marketing strategy you could rly make this a home run without complicated X realm BGs and shit.

Just an idea *flies away*

Thanks for reading it and not banning me (hopefully) for this essay <3

**Comment by yeagerca** [comment]
"Path of War" will be available sometime during the tier 8 content schedule according to the "!timeline" discord command.

> ❄️ Frostmourne
Now: Tier 7, Timewalking: Sunwell Plateau and Arena Season 5 since Friday, June 14, 2024 1:00 PM
Next: Tier 8, Season 8 and Path of War in late August/early September.

https://whitemane.org/en/features/path-of-war
https://whitemane.org/en/realms/frostmourne
