### ISSUE TITLE
[DK] Glyph of Rune Tap OG wotlk bug?

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1252]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Glyph of Rune tap currently doesn't take the caster as part of the party for the purposes of the party heal 10 %.

**How to reproduce:** Equip the glyph and cast rune tap.

**How it should work:** It should? take the Dk into account as well. Pretty sure it wasn't intended behavior, and it wasn't replicated in Wotlk classic by blizz either - it was supposedly fixed with Cata 4.0, after this the DK was excluded from the party part.
it's up to you if you replicate it or not.

Also note that it seemed to get 'fixed' in 3.1 - or so, but by 3.3 LK it was 'wrong' again, people abused it for LK fights :D

In OG wotlk this glyph was rather fun to play with - read the siege machine part below...

Also it enabled builds like 'Resto DK' in PvP and so on...

**Database links:** https://www.wowhead.com/wotlk/spell=48982/rune-tap#comments

Some old sources:

https://www.mmo-champion.com/threads/736293-Rune-tap

"Even I designed a custom Build for LK HC for myself which takes Rune Tap + Imp. Rune Tap with Glyph to help with Infest Soaking and Spirit Soaking."

Reason:
I do think if it only gave 2% increase you wouldn't take this glyph for LK HC self sustain build.

https://www.mmo-champion.com/threads/625537-Rune-Tap-vs-Unbreakable-Armor

Well, hi Myzou, if you plan to tank Unbreakable Armor glyph is a must (talent also), if you don't get Rune Tap (Heal *whole* group 10% every minute is good, even siege machines).

I can't vouch for siege machines, I don't remember that part at all, but it seems that's how it worked. - up to you if you  wanna replicate this behavior as well. 

![image](https://github.com/gamefreedomgit/Frostmourne/assets/67190649/ffc9742b-ff99-4448-b649-f5c8b802bb7d)

![image](https://github.com/gamefreedomgit/Frostmourne/assets/67190649/f76990a5-cbde-4f6e-a1ce-e216019ae469)

**Comment by UltraNix** [comment]
As I can see, this glyph should not double heal the caster.
I think we can stay like it is now.
