### ISSUE TITLE
Zul'Farrak Zombie

### ISSUE THREAD

**Issue by enaeroe** [gamefreedomgit/Frostmourne#1253]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Hits like a fucking truck, can not do this dungeon at all on HC.

**How to reproduce:**
Try and kill it

**How it should work:**
Scale it the fuck down so it doesnt one shot people

**Database links:**

**Comment by Spacemuffin007** [comment]
To clarify it's the zombies that spawn from the mounds in ZF. They do hit almost 2000% harder than they should be.

**Comment by enaeroe** [comment]
I guess the devs just chilling now cashing in on a half ass made server, not focusing on the player experience. waste of fucking time playing hc.

**Comment by Afgann** [comment]
fixed
