### ISSUE TITLE
[WARLOCK] Backdraft + Rain of Fire

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1254]
Description: Backdraft should affect rain of fire channeling time

Current behaviour: Rain of Fire channeling time isn't affected by backdraft, only gcd.

Expected behaviour: Rain of Fire channeling time should be affected, not only the gcd. If only the gcd is affected still a stack should be consumed, because the gcd has been reduced, but that kinda sucks for warlocks. To my knowledge such as heroism and similar effects, RoF should also be affected.

**Comment by UltraNix** [comment]
The spell description is clear - it affects only gcd.
Base gcd of Rain of Fire is 1.5 sec.
Please - provide some source it's a bug.

**Comment by haephaistoss** [comment]
It does affect gcd, but no stack is consumed.

I doubt it should *do* something and not use a stack.

**Comment by UltraNix** [comment]
I just tested and right now Backdraft does not affect gcd on our server and thus no charge is consumed.
So it seems wowhead is right about it.

**Comment by UltraNix** [comment]
https://www.mmo-champion.com/threads/622382-haste-and-effects-on-channeling
https://www.mmo-champion.com/threads/634921-Backdraft-amp-Rain-of-Fire
https://us.forums.blizzard.com/en/wow/t/backdraft-haste-destruction-warlock/1380850/6
I think it can be closed.
