### ISSUE TITLE
[WARLOCK] Conflagrate  delay

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1255]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Conflagrate becomes castable ~ a 150 ms later than the immolate debuff is put on the target. 

**How to reproduce:** Cast immolate on any target.

**How it should work:** Conflagrate should be instantly castable the moment the target is affected by immolate debuff - without it anybody with a dispel can remove it, even if not played correctly - not saving gcd for it.

**Database links:** https://www.wowhead.com/wotlk/spell=17962/conflagrate

**Comment by haephaistoss** [comment]
Same with shadowflame

**Comment by haephaistoss** [comment]
Same effect as Swiftmend - and that doesn't have this weird delay.

**Comment by scrublama** [comment]
This report is invalid and not a bug.
confirmed from:
https://github.com/SunwellTracker/issues/issues/1826

**Comment by haephaistoss** [comment]
https://m.youtube.com/watch?v=5S0cqK0EDsg&pp=ygUMY29icmFrIHdvdGxr


Not once was there any delay on conflagrate litting up - this is from wotlk classic, as opposed to other update cycle related stuff like Winter's chill application.

There may have been a time in the client's history when this was present, but eith today's Computer and internet speed this kinda renders destro PvP totally fucked against anyone who can use dispel

**Comment by haephaistoss** [comment]
https://m.youtube.com/watch?v=5S0cqK0EDsg&pp=ygUMY29icmFrIHdvdGxr


Not once was there any delay on conflagrate litting up - this is from wotlk classic, as opposed to other update cycle related stuff like Winter's chill application.

There may have been a time in the client's history when this was present, but eith today's Computer and internet speed this kinda renders destro PvP totally fucked against anyone who can use dispel

**Comment by haephaistoss** [comment]
https://m.youtube.com/watch?v=UezbLZlbylI&t=48s&pp=ygUMY29icmFrIHdvdGxr


this one is from og wotlk around s6-s7, and even with those internet speeds, if there is a small delay it's way less than it is currently.

**Comment by Riztazz** [comment]
I think in the past people took that delay as some artifical delay for immolate and conf, but i think back then noone knew what spell queue really was/is.
In my opinion what was talked about in the past in reality was spell queue which we have here, and i think the artifical delay between immolate and conf should be removed, so @RadeghostWM your decision :D

**Comment by Riztazz** [comment]
Is this valid by the way?

**Comment by RadeghostWM** [comment]
Let's do it like WotLK Classic from one of videos above

**Comment by Riztazz** [comment]
It does some to work like that, at least on my local server, i cannot find the artificial delay anywhere anymore.
Can someone test please?

**Comment by haephaistoss** [comment]
delay isn't present anymore in my testing either.

I'll just close this then, it was solved randomly I guess :D
