### ISSUE TITLE
Halls of Stone[Heroic], Sjonnir the Ironshaper Lightning Shield bugged again

### ISSUE THREAD

**Issue by Nihaobeachez** [gamefreedomgit/Frostmourne#1256]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Lightning Shield is bugged again, was fixed 3 weeks ago. https://github.com/gamefreedomgit/Frostmourne/issues/737

**How to reproduce:**

**How it should work:**

**Database links:**
![image](https://github.com/gamefreedomgit/Frostmourne/assets/96308500/b4623997-7dfc-437e-8917-5433bc0794c5)

**Comment by WhitemaneIsa** [comment]
@Afgann

**Comment by Afgann** [comment]
fixed
