### ISSUE TITLE
Midsummer Fire Festival

### ISSUE THREAD

**Issue by Enteroox** [gamefreedomgit/Frostmourne#1259]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
According to the in-game calendar, the Midsummer Fire Festival ended last night, however, NPCs, along with all their "equipment" are still present throughout the universe.

According to WowHead's WOTLK-related database, the event ends on the 5th of July instead of the 4th, so our in-game calendar might be wrong and this may be working correctly.

**How to reproduce:**
Visit the capitals or other locations where their bonfires and such are present. You'll witness them.

**How it should work:**
They are supposed to be gone once 11:59 PM on the 4th of July passes.

**Database links:**
[Midsummer Fire Festival](https://www.wowhead.com/wotlk/event=341/midsummer-fire-festival)

**Comment by bandini9** [comment]
https://discord.com/channels/1040715551531618365/1043976197459152947/1253500659286937640

**Comment by WhitemaneIsa** [comment]
As stated, this isn't an accident or bug, I'll end it tonight.
