### ISSUE TITLE
Boss Kill Announcements + Raid Modes

### ISSUE THREAD

**Issue by RadeghostWM** [gamefreedomgit/Frostmourne#126]
Change it to this format:

\<bossname> (difficulty) has been slain by [\<GUILD NAME>/RaidLeaderName's group] in \<time>! (Previous record: \<time> by [\<GUILD NAME>/RaidLeaderName's group].

Using \<time> like "X minutes and XX.X second(s)", for example "1 minute and 32.1 second(s)"

Examples:

Malygos (25 Normal) has been slain by \<Cool Guild> in 2 minutes and 21.5 second(s). (Previous record: 2 minutes and 21.8 second(s) by Radeghost's group.)

Kel'Thuzad (10 Ascended) has been slain by \<GM Team> in 9 minutes and 59.9 seconds.

Sartharion (10 Ascended, 3 Drakes) has been slain by \<GM Team> in 9 minutes and 59.9 seconds. (Previous record: 7 minutes and 3.0 seconds by \<GM Team>.)

Sartharion (25 Normal, 2 Drakes) has been slain by \<GM Team> in 9 minutes and 59.9 seconds. (Previous record: 7 minutes and 3.0 seconds by \<GM Team>.)

Sartharion (10 Normal, 3 Drakes) has been slain by \<GM Team> in 9 minutes and 59.9 seconds. (Previous record: 7 minutes and 3.0 seconds by \<GM Team>.)

Sartharion (10 Ascended, 0 Drakes) has been slain by \<GM Team> in 9 minutes and 59.9 seconds. (Previous record: 7 minutes and 3.0 seconds by \<GM Team>.)

Patchwerk (10 Normal) has been slain by Radeghost's group in 7 minutes and 1.0 second(s). (Previous record: 7 minutes and 3.0 seconds by \<GM Team>.)

Hodir (10 Hard Mode Ascended) has been slain by \<GM Team> in 9 minutes and 59.9 seconds. (Previous record: 7 minutes and 3.0 seconds by \<GM Team>.)

Hodir (25 Normal) has been slain by \<GM Team> in 9 minutes and 59.9 seconds. (Previous record: 7 minutes and 3.0 seconds by \<GM Team>.)

Flame Leviathan (25 Hard Mode) has been slain by \<GM Team> in 9 minutes and 59.9 seconds. (Previous record: 7 minutes and 3.0 seconds by \<GM Team>.)

The Lich King (10 Heroic Ascended) has been slain by <GM Team> in 9 minutes and 59.9 seconds. (Previous record: 7 minutes and 3.0 seconds by \<GM Team>.)

The Lich King (10 Normal) has been slain by <GM Team> in 9 minutes and 59.9 seconds. (Previous record: 7 minutes and 3.0 seconds by \<GM Team>.)

The Lich King (25 Heroic) has been slain by <GM Team> in 9 minutes and 59.9 seconds. (Previous record: 7 minutes and 3.0 seconds by \<GM Team>.)

COLORS: Guild name/group name (so "/<GM TEAM>" or "Radeghost's group") should have the same color as "Whitemane" in .server info; and rest of the announcement should have the same color as the rest of .server info.

**Comment by Afgann** [comment]
fixed
