### ISSUE TITLE
daily quest "The way to his heart" not found

### ISSUE THREAD

**Issue by abderrahmen2001** [gamefreedomgit/Frostmourne#1260]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
  I can't find a daily quest named "The way to his heart" from an npc named "Anuniaq" and that quest helps me to increase my Kalu'ak reputation.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by yeagerca** [comment]
You must do all of the Kalu'ak quests in Howling Fjord to unlock it.
