### ISSUE TITLE
Muru - Sentinels

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#1262]
A warlock can use enslave demon on the Void Sentinels in the fight.

They should be immune.

**Comment by hamajaxd** [comment]
it worked like that in pre-patch wotlk , it was only immune in tbc

**Comment by WhitemaneIsa** [comment]
@RadeghostWM

**Comment by Godmatik** [comment]
> it worked like that in pre-patch wotlk , it was only immune in tbc

No - you never could enslave the sentinel

**Comment by RadeghostWM** [comment]
Need to fix this. @Afgann

**Comment by Riztazz** [comment]
https://www.warcrafttavern.com/tbc/guides/muru/

seems like intended

```
Additionally, your [Warlocks](https://www.warcrafttavern.com/tbc/guides/type/classes/warlock/) can use [Enslave Demon](https://wowclassicdb.com/tbc/spell/11726)Enslave Demon to enslave the Spawns, which makes having up to 6 of them amazing for this fight. Their [Shadow Bolt Volley](https://wowclassicdb.com/tbc/spell/46082)Shadow Bolt Volley has no cooldown, so your [Warlocks](https://www.warcrafttavern.com/tbc/guides/type/classes/warlock/) can even use macros (see the Abilities – Void Sentinel section for more information) in order to spam the Volley like no tomorrow, doing an absolutely crazy amount of AoE damage in the process.
```

**Comment by Godmatik** [comment]
Those are the spawns, not the sentinel

**Comment by Riztazz** [comment]
You are correct, the text was a bit misleading, i have further confirmed this and fixed the issue, will close once it's live. Thank you
