### ISSUE TITLE
Hunter viper sting 

### ISSUE THREAD

**Issue by Basedmikeftw** [gamefreedomgit/Frostmourne#1263]
**Description:**
Hunter viper sting doesn't really energize for what it should.
Used it on various mobs in borean tundra, it only regenerates 1% 

Some numbers that I observed when using this:
My mana pool 4137 (max drain 330)
Coldarra Spellweaver 72 lvl, mana pool 7332, drained 73, energized 73
Coldarra Spellweaver 72 lvl, mana pool 7500, drained 75, energized 75 
Magic-bound Ancient 72 lvl, mana pool 3309, drained 33, energized 33 
Coldarra Mage Slayer 68 lvl, mana pool 3080, drained 30, energized 30 

**How to reproduce:**
Test it on various mobs around the world

**How it should work:**
Ability description: Stings the target, draining 4% mana over 8 sec (up to a maximum of 8% of the caster's maximum mana), and energizing the Hunter equal to 300% of the amount drained. 

**Database links:**
https://www.wowhead.com/wotlk/spell=3034/viper-sting#comments
The first comment (highest rated sorting) has quite nice calculations on how much it should drain/energize

edit: dont ask drunk person to do mathz lol

**Comment by haephaistoss** [comment]
On players it seems to be correct.

![image](https://github.com/gamefreedomgit/Frostmourne/assets/67190649/534f8cc0-8654-48f5-bc27-88371460d8f2)

15 313 * 0.04 = 612.52
613 / 4 = 153 this is what we see in combat log 
153 * 3 = 459 this is too what we see in combat log as gained.

Done against 0 res target - so that shouldn't be taken into account.

**Comment by haephaistoss** [comment]
Tested on an NPC too and it seems to be in order.

![image](https://github.com/gamefreedomgit/Frostmourne/assets/67190649/8f92d1d7-bb82-4b59-9545-813b0e547597)


4 tick over 12 sec 1% mana each, 4 in total.

36 mana each tick, 3 times as much restored as you can see.

**Comment by slicplaya** [comment]
I just tested Viper sting, it's working 100% correctly. Mob had 3994 mana, rounded down that's 39 mana per tick(every 2 seconds), 4 ticks(8 second duration) is the 4% mana as the tool tip states. I was getting energized for 300% at 117. 177/3=49. The Chimera Shot of the viper sting also works correctly.
