### ISSUE TITLE
Hardcore mount does not get account shared

### ISSUE THREAD

**Issue by Shadethyst** [gamefreedomgit/Frostmourne#1265]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The mount "Black Qiraji Battle Tank" that you get as a reward for doing the hardcore challenge does not get shared to other characters on the account on use

**How to reproduce:**
Use the Black Qiraji Battle Tank to learn it

**How it should work:**
The mount "Black Qiraji Battle Tank" should be shared to all characters on the account that can use it

**Database links:**

**Comment by WhitemaneIsa** [comment]
@RadeghostWM ?

**Comment by Godmatik** [comment]
Is this mount 280% or 310%?

It says 280 but we were told it would be 310

**Comment by RadeghostWM** [comment]
It should be 310%. Its going to be updated with the 3.1 patch most likely.

**Comment by UltraNix** [comment]
Fixed.
