### ISSUE TITLE
Mount account-bound share issue

### ISSUE THREAD

**Issue by Bluecow941** [gamefreedomgit/Frostmourne#1267]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Mounts don't become account-bound anymore from recently. So far I tested this on PTR (whitemane client and whitemane patch) with full riding skills on hardcore mount, gnome striders (2nd character checked was also gnome), ashes of alar and amani bear.

**How to reproduce:**
Get some mount like ashes of alar on 1st character with full riding -> relog on another character on same account on 2nd character with full riding

**How it should work:**
Characters with legit riding skill should have account-shared mounts like hardcore wasp mount.

**Database links:**
none

**Comment by UltraNix** [comment]
Just tested with Ashes of Alar:
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/b0e29af1-7a8a-48bc-943f-99b26ce12805)

**Comment by WhitemaneIsa** [comment]
No further info or complaints, closing.
