### ISSUE TITLE
[PALADIN] Shield of Righteousness Hit / Crit Mishap

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1268]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Shield of Righteousness critical hits don't apply Art of War, nor does it proc on hit effects like judgement mana restore, or heal.

**How to reproduce:** Cast Shield of Righteousness on any target, and wait til it crits.

**How it should work:** Shield of Righteousness is similar to judgements in this regard, it is a holy school melee attack - thus should proc art of war on crits, and on hit effects like judgements.

**Database links:** https://www.wowhead.com/wotlk/spell=61411/shield-of-righteousness

**Comment by UltraNix** [comment]
Fixed.
