### ISSUE TITLE
Too many Truesilver spawning

### ISSUE THREAD

**Issue by Spacemuffin007** [gamefreedomgit/Frostmourne#1270]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Truesilver is supposed to be a RARE spawn of Mithril Veins. Not sure what happened but Truesilver is far from being rare. There are whole maps that are flooded with Truesilver veins. 

**How to reproduce:**
Go to Felwood and any other major mithril vein map and you will find 60%+ of all mithril veins are Truesilver Veins. 

**How it should work:**
Truesilver Veins should be 1/200 of a chance to spawn in place of a Mithril Vein. 

**Database links:**
https://www.wowhead.com/wotlk/object=2047/truesilver-deposit#comments

**Comment by Manpower99** [comment]
Yeah currently Mithril is the rare one instead lol

**Comment by Piootrek** [comment]
Fixed

**Comment by Spacemuffin007** [comment]
> Fixed

Spawn rate for Truesilver in Hinterlands is still too high. Felwood is looking 100% better though.

**Comment by Piootrek** [comment]
Will be fixed after server update too
