### ISSUE TITLE
[CORE] Battle Shout vs Blessing of Might - Buffs Overwriting Similar Buffs

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1272]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Similar Auras like Blessing of Might - Battle Shout, etc overwrite the other currently, removing the previous buff.

Similar effects:

untalented agility totem + Horn of Winter

**How to reproduce:** Cast any of the similar buffs after one another.

**How it should work:** These buffs shouldn't overwrite each other, they should be present at the same time, but only the aura with the most powerful effect should affect the players. - Unlike debuffs.

**Database links:**

**Comment by Piootrek** [comment]
Do you have any proof it should work that way? I watched a few videos from wotlk raids and never seen those buffs together.

**Comment by haephaistoss** [comment]
Obsolete, sry. I was referring to an earlier version of wrath buffs, aura stacking is the way to go, it's up to date:

https://github.com/gamefreedomgit/Frostmourne/issues/1498

I'm closing this one, as it's fixed already, and not up to date
