### ISSUE TITLE
Not receiving the tabard acquired from Loremaster of Northrend 

### ISSUE THREAD

**Issue by Solenyia** [gamefreedomgit/Frostmourne#1273]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
After completing Loremaster of Northrend achievement, I didnt receive the tabard (Loremaster's Colors)

**How to reproduce:**

**How it should work:**
Once the achievement is finished, it should be sent to mail of the character
![Screenshot 2024-07-06 121151](https://github.com/gamefreedomgit/Frostmourne/assets/174870473/afce9ec6-4fe8-4a68-9c13-89d8cebafdf2)
![WoWScrnShot_070624_121236](https://github.com/gamefreedomgit/Frostmourne/assets/174870473/28d8d4b2-f38b-436d-9ed3-36a9764f16d0)

**Database links:**

**Comment by Piootrek** [comment]
This tabard is from The Loremaster achievement, not Loremaster of Northrend
