### ISSUE TITLE
Healing stream not procing illustartion of the dragon soul

### ISSUE THREAD

**Issue by hamajaxd** [gamefreedomgit/Frostmourne#1274]
if u spam healing stream u should get procs from the trinkets but here it dosnt work like that and its making the trinket useless for shamans
https://www.wowhead.com/wotlk/item=40432/illustration-of-the-dragon-soul#comments

each healing stream totem should proc 1 as shown in the video below 

https://www.youtube.com/watch?v=624cDhI7RNs&t=2s

**Comment by karacsonyiz** [comment]
For warlocks, life tap doesn't stack Illustration of the Dragon Soul, but it should in order to stack it up before the fight.
Source : https://www.wowhead.com/wotlk/guide/classes/warlock/affliction/dps-bis-gear-pve-phase-1#trinkets

**Comment by Piootrek** [comment]
Fixed
