### ISSUE TITLE
Ley Guardian Eregos - Time Stop

### ISSUE THREAD

**Issue by MadeinNoxus** [gamefreedomgit/Frostmourne#1275]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
This boss for someone acts like a player when stunned too many times with the same effect, gets inmunity to time stop from the bronze drake in the dungeon The Oculus when you fight against the last boss: Ley-Guardian Eregos

**How to reproduce:**
Try to cast Time stop 3 or 4 times 

**How it should work:**
You should be able to use time stop without him getting inmunity.

**Database links:**
https://www.wowhead.com/wotlk/spell=23171/time-stop
https://www.wowhead.com/wotlk/npc=27656/ley-guardian-eregos#drops;mode:heroic

**Comment by MadeinNoxus** [comment]
Same issue as https://github.com/gamefreedomgit/Frostmourne/issues/723

**Comment by Manpower99** [comment]
It is an intended Diminishing return effect

**Comment by bandini9** [comment]
It's called diminishing return

**Comment by Godmatik** [comment]
Not a bug, intended, many private servers it does not exist.
