### ISSUE TITLE
Kalu'ak Fishing Derby not working as intended

### ISSUE THREAD

**Issue by Koharuwaifu** [gamefreedomgit/Frostmourne#1278]
Description:
The Kalu'ak fishing derby is not starting at 2PM ST, Elder Clearwater is not spawning between Saturday 14:00-15:00 ST. Intead, on past Saturdays, I've seen Elder Clearwater in the dalaran fountain, but at incorrect times, around 18:00ST or 20:00ST

How to reproduce:
Go to dalaran fountain on Saturday at 14:00ST

How it should work:
Elder Clearwater should spawn next to the fishing trainer in Dalaran and do a /yell message announcing the start of the fishing derby at 14:00ST on Saturdays, and that message should be seen all across northrend. Then you should be able to get a Blacktip Shark from any northrend fishing school and turn it in with Elder Clearwater

![imagen](https://github.com/gamefreedomgit/Frostmourne/assets/50305786/7181381e-6a92-4868-b9d9-4e29b6806bd5)

Database links: https://www.wowhead.com/wotlk/npc=38294/elder-clearwater

**Comment by Koharuwaifu** [comment]
i can confirm the NPC spawns at the wrong time, spawned just now, he didn't do the /yell message, it's 9PM ST

![imagen](https://github.com/gamefreedomgit/Frostmourne/assets/50305786/9c288b85-14cf-47b5-a1e5-67460c15eb40)

**Comment by UltraNix** [comment]
Fixed.
