### ISSUE TITLE
X-53 Touring Rocket Visual bug

### ISSUE THREAD

**Issue by Cloctar** [gamefreedomgit/Frostmourne#1279]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
X53 Touring rocket not showing other player when flying together. It shows on my friends screen who is the passenger

**How to reproduce:**
When my friend jump up on the mount he just stands still on the ground for me but for him he is on the mount.

**How it should work:**
I should be able to see him on my screen.

**Database links:**
https://www.youtube.com/watch?v=BRTwNsCpz6M

**Comment by Cloctar** [comment]
Okey I want a refund for my mount it still doesn't work

**Comment by Piootrek** [comment]
Fixed
