### ISSUE TITLE
Quest is missing 

### ISSUE THREAD

**Issue by qwerty4444444444444444444444444** [gamefreedomgit/Frostmourne#128]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Quest in Kharanos is missing from npc called Ragnar Thunderbrew

**How to reproduce:**
Visit NPC

**How it should work:**
NPC should have quest linked down
Add the following quest 
**Database links:**
https://wowpedia.fandom.com/wiki/Beer_Basted_Boar_Ribs_(quest)

**Comment by Afgann** [comment]
fixed
