### ISSUE TITLE
[PALADIN] Hammer of Wrath

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1280]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** HoW is currently handled as a RANGED attack, thus being parryable by deterrence, and causing to miss by Evasion.

It is not possible to BLOCK HoW currently - it should be.

**How to reproduce:** Cast HoW on any Hunter who's using deterrence, or on a Rogue who's using Evasion.

**How it should work:** Since HoW is a MELEE attack, that deals holy dmg, and cannot be parried, or dodged, only blocked - deterrence should have no effect on it. Similar to Overpower.

Since it is a MELEE attack, that cannot be dodged, parried - only blocked -> Evasion should have 0 effect on it.

It should be possible to BLOCK HoWever.

**Database links:** https://www.wowhead.com/wotlk/spell=48806/hammer-of-wrath#comments

**Comment by haephaistoss** [comment]
Similar to this mechanic:

https://youtu.be/0leWp4lIYv0

**Comment by UltraNix** [comment]
For Blizzard it's ranged spell in wotlk:
```
ID - 24275 Hammer of Wrath (Rank 1)
=================================================
Description: Hurls a hammer that strikes an enemy for ${$m1+0.15*$SPH+0.15*$AP} to ${$M1+0.15*$SPH+0.15*$AP} Holy damage.  Only usable on enemies that have 20% or less health.
Category = 1131, SpellIconID = 42, activeIconID = 0, SpellVisual = (7250,0), SpellPriority = 0
Family SPELLFAMILY_PALADIN, flag [0] 0x00000000 [1] 0x00000080 [2] 0x00000000

SpellSchoolMask = 2 (SPELL_SCHOOL_MASK_HOLY)
DamageClass = 3 (SPELL_DAMAGE_CLASS_RANGED)
PreventionType = 1 (SPELL_PREVENTION_TYPE_SILENCE)
```
`SPELL_DAMAGE_CLASS_RANGED`
They changed that on Cataclysm.

@haephaistoss Do you have any source or videos about these interactions?

**Comment by UltraNix** [comment]
https://wowpedia.fandom.com/wiki/Hammer_of_Wrath?oldid=2722412
`The attack is resolved as a ranged special-attack that does non-physical damage. It can miss, it can be blocked (if the target is facing you), and it does double damage on a crit.`

**Comment by UltraNix** [comment]
https://web.archive.org/web/20120304192119/www.wowhead.com/spell=24275#comments:id=881485
Might be an exception here for HoW.

**Comment by haephaistoss** [comment]
It has been an exception since wrath.  The wowhead comment section is one source that is available now:

Not sure why my comment was downrated since it was true. Maybe i worded it wrong.
"
I repeat Hammer of Wrath will go straight threw:

Cloak of Shadows
Deterrence
Spell Reflection

And a few other Magic Immunity/Resist effects which by all means should ignore/deflect magic. Make of this what you will, I'm simply stating this so other Pallies will know these effects have no effect on your Hammer of Wrath"


Also this is from wotlk classic patch, blizz themselves got it wrong at first

https://www.wowhead.com/wotlk/news/wrath-classic-hotfixes-hammer-of-wrath-soul-siphon-arena-point-cap-330003

Similar is shred, and abilities that require the player to be behind the enemy - nothing says they are unable to be parried - yet they are.

http://web.archive.org/web/20160327204914/http://www.arenajunkies.com/topic/119512-why-does-shred-go-through-deterrence/

Seems to me, based on what you just showed us, and blizz fucking it up in wotlk classic, that HoW wasn't created this way originally, and later got spaghetti fixed to behave like this.

**Comment by haephaistoss** [comment]
The correct term I'm looking for here is hit table.

It uses melee hit table - thus being unaffected by ranged stuff, Evasion, Cloak, Deterrence, Hand of Prot, and so on.

But it should be possible to block it.

It was changed most likely because paladins have no other ranged attack,so using ranged hit table and crit and etc would be kinda bs

**Comment by slicplaya** [comment]
It's not supposed to go through deterrence.

**Comment by haephaistoss** [comment]
Found this old rant about it:

https://www.wowhead.com/forums/topic/deterrence-77274

@slicplaya hit tables and casting stuff are totally different.

You can prevent a judgement from being cast by silencing, yet it still uses melee hit table, and deals holy dmg, can't be dodged, blocked, or parried. Think of it as an overpower - with 100 % armorpen all the time.

There are some abilities like this, game's way more complex than that.

**Comment by slicplaya** [comment]
Gotta love the game's absolute void wording and explanation on basically anything complex. Only certain skills actually word it in the tooltip. Other's don't. Good thing this is "fixed." Now the scripting hpal/warr comps can win even faster.

**Comment by slicplaya** [comment]
Maybe, but until they actually stop the scripters, It's gonna be a Rip-fest. you're doing work on bugs. hc

**Comment by UltraNix** [comment]
Fixed.
