### ISSUE TITLE
[PALADIN / HUNTER] Judgement vs Deterrence

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1281]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Judgements are melee attacks in terms of server side handling, that cannot be blocked, dodged, or parried. Currently Deterrence blocks Judgements from hitting. - Causes them to miss

Tested stealth abilities, and they go through deterrence as they should - so too use only while behind the target attacks, so Judgement is bugged in this regard.

**How to reproduce:** Cast Judgement on any Hunter with Deterrence

**How it should work:** Judgements shouldn't be affected by Deterrence at all. Like Overpower.

**Database links:** https://www.wowhead.com/wotlk/spell=19263/deterrence

**Comment by haephaistoss** [comment]
Similar to this one

https://youtu.be/0leWp4lIYv0

**Comment by slicplaya** [comment]
[Patch 3.2.0](https://wowpedia.fandom.com/wiki/Patch_3.2.0) (2009-08-04): This ability now allows the hunter to parry spells and attacks **from behind** as well as in front. Now has a new visual spell effect.

**Comment by UltraNix** [comment]
https://wowpedia.fandom.com/wiki/Patch_3.2.0
`[Judgments]: Some of these attacks were considered ranged and some melee. They are all now considered melee attacks that can't be dodged, parried or blocked.`

**Comment by UltraNix** [comment]
Fixed.
