### ISSUE TITLE
[CORE] Attunement for TBC HCs

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1285]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Attunement requirements for all heroics were removed in wotlk.

**How to reproduce:** Try to enter Terokkar Arena HCs

**How it should work:** Player should be able to enter old dungeons or raids withotu atunnement

**Database links:** Attunement quests remain in the game for fun, but are not necessary to access the raids or dungeons. I think some of the vanilla attunement quests are removed from the game though, like the molten core quests that give you the water item. Some vanilla raids will be removed from the game (Naxx straight away in pre-patch, I think you have a little longer to run Onyxia), and other more tedious mechanics are removed from older raids so its easier to run them without needing to get specific items or have specific class abilities. Zul'Aman also loses its conditional mount, and some quest chains lose certain rewards (like titles), but I don't know if you care about that or consider it 'content'.

https://www.reddit.com/r/classicwowtbc/comments/v07n0m/tbc_content_after_wotlk_release/

**Comment by Godmatik** [comment]
Attumenets for TBV raids were removed, but not heroic dungeons

**Comment by Manpower99** [comment]
I mean if you're referring to the Keys and Attunements required for heroic dungeons, those were removed in cata and not wotlk.
most of those raid attunements were removed in tbc itself 

https://wowpedia.fandom.com/wiki/Black_Temple_attunement
> As of Patch 2.4, this attunement will not be needed to gain access to the Black Temple.

https://wowpedia.fandom.com/wiki/Flamewrought_Key

> [Patch 4.2.0](https://wowpedia.fandom.com/wiki/Patch_4.2.0) (2011-06-28): Removed.

https://wowpedia.fandom.com/wiki/Flamewrought_Key

> Cataclysm [Patch 4.2.0](https://wowpedia.fandom.com/wiki/Patch_4.2.0) (2011-06-28): Removed.

**Comment by Manpower99** [comment]
https://wowpedia.fandom.com/wiki/Auchenai_Key

> Cataclysm [Patch 4.2.0](https://wowpedia.fandom.com/wiki/Patch_4.2.0) (2011-06-28): Removed.

https://wowpedia.fandom.com/wiki/Shadow_Labyrinth_Key

> Cataclysm [Patch 4.0.3a](https://wowpedia.fandom.com/wiki/Patch_4.0.3a) (2010-11-23): Removed.
