### ISSUE TITLE
[PALADIN] Seal and Judgement of Light and Wisdom PPM

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1287]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Seals and Judgements of Light and Wisdom should all have a PPM of 15. Currently their proc rate feels way too low.

**How to reproduce:**  Stand at a Dummy and auto

**How it should work:** With a weapon speed of 3.8 (Sword of Justice) the proc chance on each hit should be ~ 3.8 / 4 = 95 %
Hidden Strike procs seem to be missing as well. THere should be no ICD starting from 3.1 anymore.

**Database links:** 

https://www.wowhead.com/wotlk/spell=20271/judgement-of-light

https://www.wowhead.com/wotlk/spell=53408/judgement-of-wisdom

https://www.wowhead.com/wotlk/spell=20165/seal-of-light

https://www.wowhead.com/wotlk/spell=20166/seal-of-wisdom

**Comment by Afgann** [comment]
fixed
