### ISSUE TITLE
[ITEM] Tiny Abomination in a Jar

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1288]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Proc doesn't seem to be handled as a melee attack - doesn't proc Seal dmg on Paladin.

**How to reproduce:**

**How it should work:** it should proc everything as a separate melee attack with a 50 % modifier.

**Database links:** https://www.wowhead.com/wotlk/spell=71545/anger-capacitor

**Comment by Piootrek** [comment]
It works correctly. 8 seal procs, 7 from melee, 1 from trinket
![image](https://github.com/user-attachments/assets/c653cfe0-a388-4b37-8a76-3bac41999c23)
