### ISSUE TITLE
Druid Sifting In/Out of Form Does Not Remove Slows Maybe Snares

### ISSUE THREAD

**Issue by ConnectedByFate** [gamefreedomgit/Frostmourne#1290]
Druid Sifting In/Out of Form Does Not Remove Slows Maybe Snares

Title says it all. No matter what slow when I shift it isn't removed when I go in and out of form. Obviously a bug. Breaks and ruins the class fundamentally.

**Comment by scrublama** [comment]
ive ran from many dks shifting out of travelform when they chains of ice me, be more specific

**Comment by UltraNix** [comment]
Tested with mage's frostbolt, warrior's hamstring and rogue's crippling poison - all is good.
@ConnectedByFate Please - provide more info. What slows or snares have you tested?

**Comment by haephaistoss** [comment]
One notablenexception has to be judgement of justice - as it doesn't slow you, it only limits your max Movespeed to be 100%, and it shouldn't be removed by shape shifting, and it seems to work this way now.
