### ISSUE TITLE
Dueling Rogues

### ISSUE THREAD

**Issue by ruivexamos** [gamefreedomgit/Frostmourne#1292]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I was dueling my friend rogue and i can see him even when he is invisible

**How to reproduce:**
play the game

**How it should work:**
You should not be able to see the rogue

**Database links:**

**Comment by UltraNix** [comment]
You were in party with him? Happened only once? Maybe he was close at hand?

**Comment by WhitemaneIsa** [comment]
No further info/complaints, closing.
