### ISSUE TITLE
Dark Smash is not LOS-able

### ISSUE THREAD

**Issue by LezChap** [gamefreedomgit/Frostmourne#1293]
Utguard Keep, last boss, Ingvar the Plunderer's ability, Dark Smash, should be negated if you can LOS it with the pillars.  However, it currently doesn't respect LOS and will stun/damage the entire party regardless of LOS.

https://www.wowhead.com/wotlk/npc=23954/ingvar-the-plunderer
https://www.wowhead.com/wotlk/spell=42723/dark-smash (Normal Version Ability?)
https://www.wowhead.com/wotlk/spell=59709/dark-smash (Heroic Version?)

**Comment by Manpower99** [comment]
it shouldn't be LoSable you can see it in the flags of the spell
![image](https://github.com/gamefreedomgit/Frostmourne/assets/100322493/e0ddf2da-fc22-4b34-b043-08c20d502029)

**Comment by LezChap** [comment]
Many guides say you can negate it via LOS.  Maybe the guides are wrong.  Or maybe that flag says to finish the cast/ability even if the mob has lost LOS of the ability, not to apply the effect despite LOS?

**Comment by Manpower99** [comment]
https://www.wowhead.com/wotlk/spell=42729/dreadful-roar#used-by-npc
or perhaps they mix up two of his abilities, due to both of them being aoe abilities?
try to find a video if possible of a guy LoSing it.

**Comment by UltraNix** [comment]
Yep - both can hit targets not in los.
```
ID - 42723 Dark Smash
=================================================
Description: Deals $s1 Shadow damage to all enemies within a $a1 yard cone in front of the caster. In addition, deals $s3 Shadow damage to all enemies, knocking them down.
ToolTip: Stunned.
Category = 1152, SpellIconID = 277, activeIconID = 0, SpellVisual = (9626,0), SpellPriority = 0
Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000

SpellSchoolMask = 32 (SPELL_SCHOOL_MASK_SHADOW)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Attributes: 0x00040000 (SPELL_ATTR0_DONT_AFFECT_SHEATH_STATE)
AttributesEx2: 0x00000004 (SPELL_ATTR2_CAN_TARGET_NOT_IN_LOS)
AttributesEx5: 0x00080008 (SPELL_ATTR5_USABLE_WHILE_STUNNED, SPELL_ATTR5_DONT_TURN_DURING_CAST)
=================================================
```
But this attribute only affect 1. effect of the spell:
```
Effect 0: Id 2 (SPELL_EFFECT_SCHOOL_DAMAGE)
BasePoints = 8749 to 11250
Targets (24, 0) (TARGET_UNIT_CONE_ENEMY_24, NO_TARGET)
Radius (Id 13) 10,00
```
There two more effects of this spell:
```
Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 0
Targets (18, 16) (TARGET_DEST_CASTER, TARGET_UNIT_DEST_AREA_ENEMY)
Aura Id 12 (SPELL_AURA_MOD_STUN), value = 1, misc = 0 (0), miscB = 0, periodic = 0
Radius (Id 22) 200,00

Effect 2: Id 2 (SPELL_EFFECT_SCHOOL_DAMAGE)
BasePoints = 1749 to 2250
Targets (18, 16) (TARGET_DEST_CASTER, TARGET_UNIT_DEST_AREA_ENEMY)
Radius (Id 22) 200,00
```
These effects do not hit on targets not in los. So guides are not wrong about it. You can use the pillar to avoid stun. 
Just tested and works okay.

**Comment by Manpower99** [comment]
@LezChap seems you can LoS the stun 🍡
