### ISSUE TITLE
[Quest] Poisoned Water not being offered

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1295]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Quest is not being offered.

**How to reproduce:**

**How it should work:**
Should be able to accept quest [Poisoned Water] from Duke Hydraxis.

**Database links:**
https://www.wowhead.com/wotlk/quest=6804/poisoned-water
https://www.wowhead.com/wotlk/npc=13278/duke-hydraxis

**Comment by UltraNix** [comment]
Yep - removed in 3.0.8
