### ISSUE TITLE
[Shop Item] Tuskarr and Dragon Kites killable by opposite faction

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1296]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Tuskarr and Dragon Kites (non-combat companions) are currently PvP flagged in PvP zones, making them killable by the opposite faction (not attackable directly but through chain effects).
Frequency of their lightning effect is also low.

**How to reproduce:**

**How it should work:**
Should act as other non-combat companions.

**Database links:**

**Comment by Piootrek** [comment]
Can you confirm this bug still exists? Works correctly for me.
