### ISSUE TITLE
Malygos adds LOS/range problems 10man Ascended

### ISSUE THREAD

**Issue by wotlkenjoyer** [gamefreedomgit/Frostmourne#1297]
Malygos adds  when you on the disc still has LOS /range problems
On video you can see  im trying to use Icy touch (which is a range spell)  and Plague strike (which is a melee spell)  
Rarely you can find  position around the add where you can use something and this positing always change since the add moving
https://github.com/gamefreedomgit/Frostmourne/assets/158612010/75c09458-0b76-4f4c-9620-56e411a6ef44

**Comment by wotlkenjoyer** [comment]
@Afgann
![image](https://github.com/user-attachments/assets/c2f2fcd8-47b3-4ba8-8d11-c5c228c01908)

If this change is live  on the server right now, then it became even worse, currently when second phase starts, even the tank  can't make aggro on incoming  adds ( 4 adds that landing to the ground) because of LOS problems.

**Comment by Afgann** [comment]
fixed
