### ISSUE TITLE
Warlocks Infernal doing way less damage then intended

### ISSUE THREAD

**Issue by Steadydnt** [gamefreedomgit/Frostmourne#1299]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Yo i noticed that the 10 minute Cooldown for Warlocks "Summon Infenal" doing way too less damage with their melee attacks. I just tested and melee attacks are average doing 700 damage a hit. While on Classic Wotlk and also all other Wotlk private servers its about 2000damage a melee attack. This bug makes the 10minute Cooldown almost not viable since you still loose a 1,2 sec casts for a Pet that will do basically 10k damage then your normal Pet.

**How to reproduce:**

**How it should work:**
Melee attack damage done by Infenal should be buffed.

**Database links:**

**Comment by disruption01** [comment]
I can confirm this issue.

**Comment by Inukk** [comment]
can confirm, both the damage and attack speed are bugged

**Comment by UltraNix** [comment]
700 damage melee hit - against what?

**Comment by Inukk** [comment]
@UltraNix Here's the damage of an infernal in phase 1 of Classic
![image](https://github.com/gamefreedomgit/Frostmourne/assets/101921457/5ae32307-40a8-4095-bba6-f1ee1bd82f2e)

And here's the damage of an infernal in Frostmourne, this log is from the current rank 5 affli on patchwerk
![image](https://github.com/gamefreedomgit/Frostmourne/assets/101921457/5a7e88fa-e613-4221-b4cc-1821357e63a3)

The infernal in frostmourne is doing roughly half the damage it should be doing compared to classic, this along with the bugged attack speed makes it so the overall dps is something like 35% of what it should be.

I also ran it through 2010's SimCraft for 3.3.5 release using an affli profile with gear similar to the one from the rank 5 log, and again the results show ~50% more damage on melee hits compared to what can currently be observed in frostmourne, it's also consistent with what can be seen in classic logs.
![image](https://github.com/gamefreedomgit/Frostmourne/assets/101921457/90c0164d-d782-428e-9caa-437b0ab33c94)

**Comment by BalanCV** [comment]
From my testing on PTR its simply that melees are not scaling with owner's SP.
Immolation aura is scaling fine its just the melees.

From wowsims:
Base stats:
stats.Strength:  331,
stats.Agility:   113,
stats.Stamina:   361,
stats.Intellect: 65,
stats.Spirit:    109,
stats.Mana:      0,
stats.MeleeCrit: 3.192 * core.CritRatingPerCritChance,

stats.AttackPower:      ownerStats[stats.SpellPower] * 0.57,
stats.SpellPower:       ownerStats[stats.SpellPower] * 0.15,

// infernal is classified as a warrior class, so we assume it gets the
// same agi crit coefficient
infernal.AddStatDependency(stats.Agility, stats.MeleeCrit, core.CritRatingPerCritChance*1/62.5)
infernal.AddStatDependency(stats.Strength, stats.AttackPower, 2)

MainHand: core.Weapon{
			BaseDamageMin:  330,
			BaseDamageMax:  494.9,
			SwingSpeed:     2,
			CritMultiplier: 2,
		},
		
ALSO it mentions specifically that immolation is capped AOE. Not sure which type of cap so I assume the standard one.

**Comment by Manpower99** [comment]
> From my testing on PTR its simply that melees are not scaling with owner's SP. Immolation aura is scaling fine its just the melees.
> 
> From wowsims: Base stats: stats.Strength: 331, stats.Agility: 113, stats.Stamina: 361, stats.Intellect: 65, stats.Spirit: 109, stats.Mana: 0, stats.MeleeCrit: 3.192 * core.CritRatingPerCritChance,
> 
> stats.AttackPower: ownerStats[stats.SpellPower] * 0.57, stats.SpellPower: ownerStats[stats.SpellPower] * 0.15,
> 
> // infernal is classified as a warrior class, so we assume it gets the // same agi crit coefficient infernal.AddStatDependency(stats.Agility, stats.MeleeCrit, core.CritRatingPerCritChance*1/62.5) infernal.AddStatDependency(stats.Strength, stats.AttackPower, 2)
> 
> MainHand: core.Weapon{ BaseDamageMin: 330, BaseDamageMax: 494.9, SwingSpeed: 2, CritMultiplier: 2, },
> 
> ALSO it mentions specifically that immolation is capped AOE. Not sure which type of cap so I assume the standard one.

Can confirm that this is very accurate wotlkclassic info with screenshots if required.

**Comment by UltraNix** [comment]
The scaling is already okay.
I see the base stats are different.

**Comment by Gruonden** [comment]
Bump

**Comment by Steadydnt** [comment]
I want to bring this up again mainly because I see you bring Legendaries & small buffs for a bunch of classes and forget about the only Cooldown Affliction has is still working wrong. It feels very bad to see this as Affliction Player.

Its still doing like half the damage then it should normally do. The Immolation Aura scales correct and also the Inferno Effect scales correct. Also the Attackspeed was fixed. 
Infernal melee attacks are still calculated very badly. They are doing not even half the Damage then they should. The Calculation uptop sent by Manpower is probably correct i can just provide you screenshots again of how it should look like and how its looking here on Whitemane Private Wotlk.
This is Rank 1 affliction warlocks Infernal at KelThuzad in Wotlk Classic: 
![image](https://github.com/user-attachments/assets/d3425159-2eb1-4622-9835-60787f41d4b0)

You can see its swinging autoattacks for like average 2k Physical damage. When it Crits on it they hit for about 4.4k damage.

Here im posting from my Kelthuzad Fight here on Warmane the value:
![image](https://github.com/user-attachments/assets/8c8c288f-d35f-4a7d-9014-2c00decab0bd)

Its swinging 23x normal melee attacks for avg. 1073 damage. And when it critted 5x for avg. 2300 damage.

There is not much gear difference between my character on Whitemane and the character on classic. Its just exactly 50% less damage.

**Comment by Rowern96** [comment]
@UltraNix hey, since the base stats are clearly wrong and each strength difference translates in the attackpower being off by 2, isnt it possible to change the base stats and see how it effects the damage. its super annoying testing and gathering data on infernal while we already know one problem

**Comment by Manpower99** [comment]
I've already compiled good amount of resources to try and make an accurate bug report, it wont be long till i finalize my findings and report it and the rest is up to the devs to apply them or not. approximately a couple of days since im sadly very busy PTRing ulduar and raiding also. i will say however that the previous findings are not fully accurate either btw so no need to fully rely on them.
