### ISSUE TITLE
Gothik Bugged

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#130]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
After being done with waves, gothik randomly dies and no loot is dropped

**How to reproduce:**
clear all waves and watch as he just randomly dies

**How it should work:**
After waves, should teleport down fight resumes as intended and loot drops

**Database links:**

**Comment by Afgann** [comment]
fixed
