### ISSUE TITLE
Ulduar - Thorim extra add on The Hallway

### ISSUE THREAD

**Issue by Dalvae** [gamefreedomgit/Frostmourne#1300]
**Description:**
There is an extra add on top of the hallway next to the [Ancient Rune Giant](https://wowpedia.fandom.com/wiki/Ancient_Rune_Giant).

**How to reproduce:**
I think it appears after a wipe.

**How it should work:**
That add shouldn't be there.

**Links:**
[Video evidence](https://youtu.be/rO9eUukqwYk)

**Comment by Afgann** [comment]
fixed
