### ISSUE TITLE
Warlock infernal incorrect attack speed

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#1302]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Currently the attack speed of the infernal is being affected by Enslave Demon (which shouldn't be the case), increasing the interval between melee hits from 2.0s to 2.6s

Data from original WotLK such as 2010's SimulationCraft for 3.3.5 shows that the interval between melee hits without any haste buffs should be 2.0s, this also matches the attack speed in Classic WotLK and in popular sim websites such as WoWSims

![image](https://github.com/gamefreedomgit/Frostmourne/assets/101921457/3e890082-a2df-46a7-8fdc-8a5781bc79b1)
https://github.com/wowsims/wotlk/blob/master/sim/warlock/inferno.go

**Comment by UltraNix** [comment]
Fixed.
