### ISSUE TITLE
[Quest NPC] Ancient Shadowmoon Spirit is missing

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1304]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
While on the quest [Teron Gorefiend - Lore and Legend], NPC to turn in the quest is missing.
I'm guessing this may be related to:
https://github.com/gamefreedomgit/Frostmourne/issues/1235

**How to reproduce:**

**How it should work:**
NPC Should be at the Altar of Shadows and should be seen with or without [Spectrecles] provided by the quest, and in ghost form after dying.

**Database links:**
https://www.wowhead.com/tbc/npc=21797/ancient-shadowmoon-spirit
https://www.wowhead.com/tbc/quest=10633/teron-gorefiend-lore-and-legend
https://www.wowhead.com/tbc/quest=10644/teron-gorefiend-lore-and-legend

**Comment by PanJanuszek** [comment]
He is not missing. Due to TBC was without phase system, he was just killed by previous player who was doing last quest in chain. Respawn is 5min
