### ISSUE TITLE
BRD Boss Event - The Seven doesn't reset

### ISSUE THREAD

**Issue by LezChap** [gamefreedomgit/Frostmourne#1305]
I was in BRD farming for stuff, and did The Seven encounter.  Doom'rel killed a totem of mine, and I guess I wasn't on his threat table yet because he reset to his starting position, and then the others I'd killed reset to their positions and alive again, but Doom'rel's script didn't reset to restart the event, breaking getting past this encounter to finish the dungeon without resetting the instance.

https://www.wowhead.com/npc=9039/doomrel
https://wowpedia.fandom.com/wiki/The_Seven

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
