### ISSUE TITLE
Fear Visual Pathing Bug

### ISSUE THREAD

**Issue by Acurtis03** [gamefreedomgit/Frostmourne#1306]
**Description:**
Currently in the game (as confirmed by other players on discord) when someone gets feared (CC ability from warlock/warrior/priest) there is a visual bug that shows them running in a direction or standing in a place where they actually are not. In other words, in reality the person under fear effect runs LEFT for example, well the visual bug shows them running RIGHT or standing completely still. This interferes with PvP on many different levels that i won't go into detail over, its a bug plain and simple. 

**How to reproduce:**
Just go play arena, or get into a pvp scenario where a enemy target gets under the Fear effect, and try to cast spells at them or try to use melee abilities on them, it will say (target not in range) or something similar because in reality they are somewhere else, not where you see them to be. 

**How it should work:**
When an enemy target is suffering from the "Fear" effect, their location and pathing should be visible and accurate to their true position in the game-space to both enemies and friendly targets alike. There should be no difference between the visual location of a player, and their TRUE location.

**Comment by UltraNix** [comment]
@Acurtis03 Could you record it?

**Comment by rradman** [comment]
i can 100% confirm this is happening, people start teleporting when my teammate fears them

**Comment by UltraNix** [comment]
@rradman Maybe other CC forms (e.g. roots, poly or death grip) was active?

**Comment by rradman** [comment]
> @rradman Maybe other CC forms (e.g. roots, poly or death grip) were active?

can't remember in detail, a lot happens in arena/bg.

**Comment by haephaistoss** [comment]
I have encountred this too in wsg during lvling. Usually happens on most other private servers when the target is affected by fear during him being affected by another form of CC, like a stun, or during a movement animation like feral charge, and the 2 give birth to this unwordly visual bug.

We'Ll try to record it later

**Comment by UltraNix** [comment]
Still waiting for record to see what combination of CC effects might be here the problem.

**Comment by UltraNix** [comment]
Okay - stun + fear.

**Comment by debugger12313** [comment]
This is 100% real

**Comment by UltraNix** [comment]
Fixed.
