### ISSUE TITLE
kt 25 mind control 

### ISSUE THREAD

**Issue by draxan1** [gamefreedomgit/Frostmourne#1307]
Naxx 25 Kel'Thuzad

**Description:**
Naxx 25 Kel'Thuzad ability mind control is not working properly ,person in mc can actually move on his own
**How to reproduce:**
get nc on kt

**How it should work:**
can't use character for the time begin mc

**Database links:**
https://www.wowhead.com/wotlk/spell=28410/chains-of-kelthuzad

**Comment by Godmatik** [comment]
you can only move on your own when mind controlled  after you are CCed and the CC wears off

In addition, if you are MCed, you are not using your max rank spells, as I indicated here:

https://github.com/gamefreedomgit/Frostmourne/issues/1038

**Comment by Afgann** [comment]
fixed
