### ISSUE TITLE
naxx 10hm all party member max hp 20mil

### ISSUE THREAD

**Issue by draxan1** [gamefreedomgit/Frostmourne#1309]
**Description:**
Yesterday we do naxx 10hc and on heigan all party member got around 20 milions hp

**How to reproduce:**
idk

**How it should work:**
there is no 100000% hp buff

**Database links:**
![image](https://github.com/gamefreedomgit/Frostmourne/assets/175113484/77afd659-d55b-43a7-b3ff-5c468b33024d)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/175113484/d9ec01ed-2f77-42bf-afc2-9b58e063b3d0)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/175113484/11de5bad-b690-4db8-a6e7-dbbb936a4d22)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/175113484/b518f8d7-6a24-4c85-8c4b-78bff322b4b1)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/175113484/ab9cae23-c138-4994-b761-775648f043f6)

**Comment by Afgann** [comment]
fixed

**Comment by Manpower99** [comment]
> fixed

Disease in Heigan 10Ascended is still amplifying the Hp of the targets affected instead of reducing it.
