### ISSUE TITLE
Prospecting Saronite bug

### ISSUE THREAD

**Issue by rradman** [gamefreedomgit/Frostmourne#1311]
According to the WotLK Prospecting Table, Saronite Ore should on Average drop a rare gem in 20-25% of the cases.

When prospecting, that chance seems to be much lower (2 rare gems from 120 ore).

It think it was working fine before Monday (8th Jul).

**Comment by UltraNix** [comment]
Fixed.

**Comment by rradman** [comment]
@UltraNix is it deployed live?
