### ISSUE TITLE
Shadowstep positioning

### ISSUE THREAD

**Issue by rradman** [gamefreedomgit/Frostmourne#1312]
**Description:**
Rogue Shadowstep ability does not position the rogue correctly, it seems to "jump" like 5 meters behind the target that is moving.

**How to reproduce:**
Have an enemy running (or even better running on a mount), then try to Shadowstep + Cheapshot (or kidney) and it won't work because "**target is out of range**".

**How it should work:**
Should bring the rogue behind the target in melee range.

**Database links:**

**Comment by UltraNix** [comment]
Show me this macro

**Comment by rradman** [comment]
> Show me this macro

What macro? Simply spamming the 2 abilities should do the trick, no need for a macro.

**Comment by rradman** [comment]
@UltraNix is it deployed live?
