### ISSUE TITLE
[PTR ULDUAR 25N Mimiron] Emergency Fire Bot Water Spray range/width seems too small

### ISSUE THREAD

**Issue by gforghieri** [gamefreedomgit/Frostmourne#1313]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
[ULDUAR 25N Mimiron] Emergency Fire Bot Water Spray doenst douse fires correctly

**How to reproduce:**
Check Mimiron P3 and P4 Emergency Fire Bot Water Spray ability doesnt douse all fires within a 15y wide and long cone as it should.

It looks like the ability has a smaller range than intended, please check this.

**How it should work:**
![image](https://github.com/gamefreedomgit/Frostmourne/assets/23422651/895ba862-97e0-4151-b99c-6f762779e41e)

**Database links:**
https://www.wowhead.com/wotlk/spell=64619/water-spray

**Comment by Afgann** [comment]
fixed
