### ISSUE TITLE
Flame caps spawn in dungeons messed up by fix

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#1316]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The fix from #143 basically deleted all static spawns of Flame cap (which is fine open world) but also those in dungeons (slave pens, underbog, steamvaults)
Because in dungeon system the rest of the herbs are static it means you will only get ragveils inside which you need to pick up and wait 2hours for them to respawn(because dungeon timer) essentially making it useless to gather flame caps from dungeons since you can do the same with 5min respawn ragveils outside.

According to classic spawns:
https://imgur.com/a/SL5wqQr
https://www.youtube.com/watch?v=Nz-9sj0HWyg
There should be 1-2 flame caps spawning in slave pens so technically 100% chance to spawn at least one
And around 50-80% chance for it to be spawned in steamvaults and underbog

Now comes the tricky part:
**Fix potential 1** (proper fix, lot of work for a low level dungeon, not worth?)
Currently, when dungeon id is generated at first so are all static herbs inside, as such they will default to ragveil default spawn. Making all herbs inside these dungeons have a dynamic chance at ID generation to be their rare version will require some work.

**Fix potential 2** (ez fix mimicking expected drop rates from classic per dungeon)
Add 1 or 2 static flame cap spawns in random location on top of other herbs in the slave pens at dungeon id generation. Do the same for steam vaults and underbog but add 1 flame cap with 80% chance to exist on dungeon id generation.

**Comment by jonathansbb** [comment]
Bump!

**Comment by PanJanuszek** [comment]
so far disabled in instance
