### ISSUE TITLE
Auction house Error

### ISSUE THREAD

**Issue by GRamsaySWRP** [gamefreedomgit/Frostmourne#1317]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
If you bid on an item in the auction house, then buyout that item, it doesnt return your original bid amount. It only sends you the item.

**How to reproduce:**
Bid on an item
Then buy the item.

**How it should work:**
Bid on the Item
Buy the Item
Get both the original bid amount and the item.

**Database links:**

**Comment by UltraNix** [comment]
When you buyout, the amount of gold you really spent is already adjusted by your bid.
My starting gold:
![image](https://github.com/user-attachments/assets/74ba0863-ee3f-4740-8847-d685f2ec3c90)
100 gold.

Now bid - 99 left.
![image](https://github.com/user-attachments/assets/b581a31b-9c8a-4324-842c-44c367fe94f4)

Now buyout - 80 left (that 1 gold from bid already returned to you).
![image](https://github.com/user-attachments/assets/f691d232-f237-459e-a342-595a96c24ae4)

No bug here,
