### ISSUE TITLE
[Wintergrasp] Workshops owned upon battle beginning

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1318]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
If Alliance are defending, they start with 0/4 workshops captured. If Horde are defending, they start with 2/4 workshops captured.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by scrublama** [comment]
I call that great balance, horde sucks

**Comment by UltraNix** [comment]
https://wowpedia.fandom.com/wiki/Wintergrasp
`The internal balance system now only changes when a faction achieves 2 consecutive defenses after an initial capture of Wintergrasp, up from 1`
https://www.wowhead.com/news=145516/patch-3-3-3-upcoming-wintergrasp-balance-changes
The question is about the number of consecutive defenses. If Alliance defended 2 times in a row, then Horde starts with all 4 workshops. If Horde just captured Wintergrasp and it's 1st timer whne defending, then Alliance and Horde have 2 workshops per faction.

**Comment by Chaos-within** [comment]
@UltraNix 
You used https://www.wowhead.com/news/patch-3-3-3-upcoming-wintergrasp-balance-changes-145516 as a reference but the current system whitemane has implemented does not follow this moving scale and the corresponding advantages.

"if the scale is at 0 and the Alliance capture Wintergrasp fortress while attacking, the scale will not move. If the Alliance defend Wintergrasp twice in a row after this, the scale will move 100 points in favor of the Horde. Each consecutive defense by the Alliance after this will move the scale 100 points further in favor of the Horde each time, bringing the Horde to 400 points in their favor after one unsuccessful defense and five unsuccessful attacks, a total of six Horde losses in a row."

"400: Faction starts with the Sunken Ring Factory under their control."

Only 1 workshop captured at the beginning after losing six times in a row. Which never happens on Whitemane, it's either 2 or 4.

**Comment by UltraNix** [comment]
Tested that:
First battle after horde captured WG - both starts with 2.
![image](https://github.com/user-attachments/assets/62de8818-6fc1-4a0b-9867-29afac3e99c5)

2nd battle - still the same:
![image](https://github.com/user-attachments/assets/179e05f8-6687-4d10-96a1-f14b3cb281a7)

3rd battle - you can see now Sunken Ring is alliance
![image](https://github.com/user-attachments/assets/ea63596c-19ef-4c88-89b8-a2e75f010f71)

4th battle - all workshops are now alliance
![image](https://github.com/user-attachments/assets/a747add6-033c-429c-8462-188fa7eab556)

Now let's capture WG by alliance:
1.st battle after Alliance captured WG - all is reset:
![image](https://github.com/user-attachments/assets/e3339a84-7b9a-43d2-aa44-99d377d3c8f2)
So this might be the only bug here - it should not reset after capturing by opposing faction.

**Comment by Chaos-within** [comment]
@UltraNix Alliance haven't won WG for over a day straight and this is how the battleground is still beginning: 
![image](https://github.com/user-attachments/assets/7f1f3542-d810-4e66-9b8c-f7bd7461daff)
