### ISSUE TITLE
[Class] Debuffs not being removed when using Divine Shield

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1319]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Since last "update", debuffs are not being removed when using Divine Shield.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
@Chaos-within Like what debuf?

**Comment by yeagerca** [comment]
Divine Shield also no longer immunes the damage from Kel'Thuzad's Ice Tomb.

Debuffs not being removed was also observed with Ice Block.

Thirdly, Hand of Protection is being immuned when cast on someone in Ice Block.

**Comment by UltraNix** [comment]
Already fixed.
