### ISSUE TITLE
Patchwerk

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#1320]
**Description:**
The Patchwerk boss has an incorrect attack speed. The 1.2 sec modifier is installed on the server.
The second problem is that Patchwork must be immune to the effects of Taunt.

**How it should work:**
 In wotlk classic, the boss had a base value of 0.7 sec. Near the Threat Classic addon, there is a red stripe of boss swings in the center from below. 0.7 sec, influenced by debuff 20% = 0.84.
attack speed - https://youtu.be/fUh-dCZ1ZrA?t=2096 
Imun taunt - https://youtu.be/fUh-dCZ1ZrA?t=2142

**Database links:**
https://www.wowhead.com/wotlk/npc=16028/patchwerk

**Comment by AlucardHellsingChapel** [comment]
i would say 3.3.5 is not classic so if it was a classic change it should not be applied here

**Comment by wowclassic1234** [comment]
> i would say 3.3.5 is not classic so if it was a classic change it should not be applied here

The same thing happened in the original WOTLK game, here is an example, here you can clearly see how every second and more often the tank falls under the automatic attack of the boss.
https://www.youtube.com/watch?v=a-0IM9UwuT8

If you want to find the video yourself, you will see that in the original Wotlk the boss was invulnerable to ridicule. But, of course, you will not do this, it is easier for you to write a comment in the topic that will question the relevance of this problem.

**Comment by AlucardHellsingChapel** [comment]
> > i would say 3.3.5 is not classic so if it was a classic change it should not be applied here
> 
> The same thing happened in the original WOTLK game, here is an example, here you can clearly see how every second and more often the tank falls under the automatic attack of the boss. https://www.youtube.com/watch?v=a-0IM9UwuT8
> 
> If you want to find the video yourself, you will see that in the original Wotlk the boss was invulnerable to ridicule. But, of course, you will not do this, it is easier for you to write a comment in the topic that will question the relevance of this problem.

was talking about taunt immune it was immune while enraged but never heard of being immune to taunt in any other moment to taunt

**Comment by draxan1** [comment]
bro why ppl like can even time there , u guys should ad some iq test cus ppl cant even read ,
u sending some video from some bugged rusian server and from vanila wow where all boss was to hard to kill before pre nerf
also there was never taunt immune on patch and his attack speed look normal

**Comment by wowclassic1234** [comment]
Server flamegor official. 

Dude, I completely played all the WOTLK Classic, I have a bunch of videos with proofs of how everything should work. Please do a good deed, don't write nonsense to me in my reports. If you want to make a rebuttal, throw a video proof 15 years ago  2009. At least that way you won't look stupid in my eyes.

**Comment by draxan1** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/175113484/90729412-b1bc-4f7b-8cad-687f7aa8bd65)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/175113484/20c3303b-1cf2-4001-9255-ee7effd5f9ba)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/175113484/3ae135dd-2d6e-467b-8f85-5e8e42d320e8)
there is no information about u cant taunt patch , is only when he enrage

**Comment by draxan1** [comment]
also on retail u do so much more threat

**Comment by wowclassic1234** [comment]
You're so stupid. Where in your proof should I see that he had no immunity? You're showing me that he used taunt. What's next? I threw you a video with my gameplay on Wotlk classic, where the boss shows immunity to taunt. Okay, you turned on the idiot, I believed you had a negative IQ. Let me show you more, here's the first video I came across on behalf of a tank from YouTube in 2009 from the original WOTLK.  The paladin uses Taunt 2 times and in both cases the boss's immunity is triggered.

https://www.youtube.com/watch?v=dGmGFKzDWAk

**Comment by wowclassic1234** [comment]
> also on retail u do so much more threat

I have shown you 2 video proofs Official 2009 and official 2023. If you re-start writing your nonsense from your schizophrenic head in my topic, then I strongly recommend contacting a doctor and deleting your github account. With your brand, you mislead developers and other people. People like you shouldn't be here.

**Comment by draxan1** [comment]
idk maybe u right but ,if this really nessesary to change it ,now in good guild u need to have dps trinket on prot pals , im playing bdk and i can tell u threat spells are not correct some of them give more some less threat then in orginal wow ,do u want them to rewirte all threat spell cus your patch dont have immunity to taunt ?

**Comment by wowclassic1234** [comment]
If you think that some class has an incorrect Threat calculation formula, create a separate topic and provide evidence there, you do not need to write about it here. This is a completely different topic. I play as a tank warrior and I have no problems with  getting a high threat volume compared to other classes.

**Comment by alemae96** [comment]
You kept threat the entire time. Were you wanting to OT to taunt off during enrage? I'm confused. You hit Taunt twice during the encounter. If you're already tanking the boss, taunt will not work. Nowhere did I see it show immune and as far as attack speeds, they look normal to me.

**Comment by gforghieri** [comment]
Even though you are right, it ruins the fun for people because now they have to hold back the dps and cant parse as effectively...

So correcting things, but ruining the fun, is it worth it?

**Comment by UltraNix** [comment]
@gforghieri Watch once again the video that @wowclassic1234 provided - it's from 2009.
Also there are some forum topics from that time .e.g https://www.mmo-champion.com/threads/647073-OT-taunting

**Comment by gforghieri** [comment]
I know its correct, it doesnt mean anybody wants it, that was my point. @UltraNix

**Comment by gforghieri** [comment]
What this effectively does is people having to hold back on DPS and ruining the fun.

**Comment by wowclassic1234** [comment]
If you have a problem with the Threat On this boss, then what is the problem with using Misdirection and Tricks to properly distribute the threat in tanks? Or are the players on this server so incapable that they have to explain in the comments what they need to do?

**Comment by wowclassic1234** [comment]
> Я знаю, что это правильно, это не значит, что люди этого хотят, это была моя точка зрения. @UltraNix

If I want a loot chest of 1 bonus item per week, should the developers listen to me and do it? That's a great idea, of course.  That's what I want, that's why it's going to happen. Why don't you keep your opinion to yourself? And the developers themselves will make the game what it should be.

**Comment by Manpower99** [comment]
So is the taunt change removed or not? judging by the post and further evidence looked at thru WCL, patchwerk should indeed be taunt immune, just want clarification if possible ( since it was removed from discord changelog)

**Comment by Manpower99** [comment]
@UltraNix something to note here that currently does not work on whitemane which if the taunt change is being kept ( as it should) is the threat generation portion of hateful strike, you can see in the video the candidates (top3 threat) of hateful strike are generating massive amount of threat which is in line with the wowhead comment, which is copied from an elitistjerks thread.
https://www.wowhead.com/wotlk/npc=16028/patchwerk#comments:id=552113

**Comment by UltraNix** [comment]
@Manpower99 Could you make a new report about it (if it's bugged on our server)?

**Comment by Manpower99** [comment]
> @Manpower99 Could you make a new report about it (if it's bugged on our server)?

Will do, but is the taunt change being applied or not? it has been deleted from discord changelog.

**Comment by UltraNix** [comment]
Will be applied.

**Comment by UltraNix** [comment]
Fixed.
