### ISSUE TITLE
Arcanite Dragonling bugged

### ISSUE THREAD

**Issue by Sylanha** [gamefreedomgit/Frostmourne#1321]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Arcanite Dragonling trinket does not apply debuffs.

**How to reproduce:**
Summon the trinket and let the Summoned Dragon hit aggressive mobs lvl 60-80.

**How it should work:**
Summoned Dragonling has 2 abilities Flame Breath and Flame Buffet but it also has melee attacks. Flame Buffet has a 10% chance to cast everytime it melee attacks which applies a stacking debuff that increases fire damage taken by per stack (actually increases fire spellpower instead of flat damage taken so things that do not benefit from fire spellpower do not get affected but everything else does).
Flame breath is a casted spell that does roughly 500 damage in a cone. The summoned dragonling also scales with Engineering levels at 5:1 Ratio  that caps out at level 80.

**Database links:**
https://www.wowhead.com/wotlk/item=16022/arcanite-dragonling
https://www.wowhead.com/wotlk/spell=8873/flame-breath#comments
https://www.wowhead.com/wotlk/spell=9658/flame-buffet

**Comment by Afgann** [comment]
fixed
