### ISSUE TITLE
gnomish army knife doesnt work

### ISSUE THREAD

**Issue by Roswald1334** [gamefreedomgit/Frostmourne#1323]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
should ress your teammate,
tried it 10 times never workes.

**How to reproduce:**

**How it should work:**
very high chance of ressing a friend

**Database links:**

**Comment by draxan1** [comment]
working fine test it more then 3 times

**Comment by bandini9** [comment]
I disagree, it works as it's supposed to
