### ISSUE TITLE
shadowstep worked great yasterday, today i shadowstep infront of ppl. 

### ISSUE THREAD

**Issue by Roswald1334** [gamefreedomgit/Frostmourne#1325]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Roswald1334** [comment]
when they are walking or moving

**Comment by Afgann** [comment]
fixed
