### ISSUE TITLE
NPCs in Orebor Harborage turned to 'enemies'

### ISSUE THREAD

**Issue by Seren79** [gamefreedomgit/Frostmourne#1326]
**Description:**
Several of the Broken One NPCs in Orebor Harborage suddenly changed from friendly to enemy, meaning it's no longer possible to interact with them and some of them (Maktu and Puluu) no longer give their quests. Their names display in red and I can't click on them. The ! quest indicator over their heads comes and goes. After this happened, my character got stuck in place and I had to use the 'unstuck' tool. Some weird bug going on here!

**How to reproduce:**
Not sure tbh. Try going to Orebor Harborage and accepting quests from other NPCs. It happened to me after I accepted the Wanted: Chieftain Mummaki quest (I think - it happened so quickly), so not sure if that broke something.

**How it should work:**
The NPCs in Orebor Harborage should all be friendly to Alliance players and it should be possible to interact with them and view and accept all quests, as normal. Accepting quests should not break code and should not turn certain NPCs into 'enemies'.

**Database links:**
https://www.wowhead.com/tbc/quest=9905/maktus-revenge
https://www.wowhead.com/quest=9833/lines-of-communication
https://www.wowhead.com/quest=9830/stinger-venom

**Comment by Seren79** [comment]
Screenshots below:

![WoWScrnShot_071024_214321](https://github.com/gamefreedomgit/Frostmourne/assets/173203318/94253968-db50-4330-ab2e-6ba272fa0ee7)
![WoWScrnShot_071024_214336](https://github.com/gamefreedomgit/Frostmourne/assets/173203318/40f0050f-494b-4ac3-89da-c2a5026cdfa6)

**Comment by Godmatik** [comment]
You need neutral rep or higher
