### ISSUE TITLE
[Setting] AFK cleared upon moving

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1327]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
AFK is being cleared upon character movement even with the setting Auto Clear Away unchecked.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
