### ISSUE TITLE
Retrieving item information takes up to 3-5m after login [2]

### ISSUE THREAD

**Issue by Cure-whitemane** [gamefreedomgit/Frostmourne#1329]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

After login and reload it takes about 3m for the items to be retrieved:

- mail
- quest
- RDF HC queue

![image](https://github.com/gamefreedomgit/Frostmourne/assets/173875910/8ec1c462-b682-4282-8b0d-e7eb37e8e72e)

**How to reproduce:**

Once login hower to quest/RDF HC items

**How it should work:**

Should be retrieved instantly

I already opened such issue https://github.com/gamefreedomgit/Frostmourne/issues/1139

**Comment by Cure-whitemane** [comment]
The time it takes now is definitely more. It becomes worse :(

![image](https://github.com/gamefreedomgit/Frostmourne/assets/173875910/896f5487-7d22-4afe-8295-976bc1d5780d)

**Comment by Cure-whitemane** [comment]
After buying item on Auction House sometimes you need to wait like 3-4 minutes

**Comment by BalanCV** [comment]
This issue is present even without, but the whitemane custom client makes this worse like this reporter mentions 3-5mins of retrieving because it keeps deleting the cache on wow launch or doesn't utilize cache at all.
Using non-whitemane client you still get this bug either when freshly logging in or when swapping to different characters through logout. Doesn't last as long without whitemane client though. /reload sometimes fixes it, most times it doesn't.

**Comment by Cure-whitemane** [comment]
@WhitemaneIsa @RadeghostWM @UltraNix can we please help something about that? On the weekend it took 3m to retrieve mailbox and 5m to load professions

**Comment by UltraNix** [comment]
Clientside problem with our client. Will be fixed within the next patch.

**Comment by gingerdadman** [comment]
> Clientside problem with our client. Will be fixed within the next patch.

Was this intended to be fixed with v3.3? Same issue on the patch I installed today.

**Comment by RadeghostWM** [comment]
If gets fixed after cache successfully generates.

**Comment by Riztazz** [comment]
Leaving a note so it's not forgotten, it is possible to force client cache reset from server
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/worldserver/worldserver.conf.dist#L1199

**Comment by UltraNix** [comment]
No further info - closing.
