### ISSUE TITLE
[CORE] Racial  / Talent based negative hit chance

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1332]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** In Wotlk there were 2 classes of negative hit chance: provided by racial spell, and provided by talent. Racial based hit could be capped against with extra hit rating thus negating its effect, talent based however, couldn't.

**How to reproduce:** I'm not sure how to reproduce this in a timely manner with any reasonable validity of measurement on the PTR, so I'm just leaving it here for you to check the code, if it is working as intended.

**How it should work:** So for example: night elf racial should be OK to cap against with a crapton of HIT rating (1 %), Divine Purpose talent of Paladins however, the contrary.-> with 10000000000 % hit chance, it should still provide its 4 % chance to miss regardless.

Maybe a way to think of these is that racial based spells provide negative hit chance, and talent based ones provide a chance to miss, that isn't in any way related to hit or hit rating.

I'll gather the spell links if needed later, I'm not sure how it's handled in the code, maybe there is a flag for different types of spells that provide negative hit chance 

**Database links:**

**Comment by Piootrek** [comment]
Can you provide any proof that it should work this way?
