### ISSUE TITLE
BCB and Dual Wielding.

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1333]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Talent BCB seems to interact similarly to how Hack and Slash for rogue works.(offhand hit procs mainhand's damage)
it should not, It should use the respective damage range for the weapon that proced it and be appropriately reduced in damage from dual-wielding or in the case of two weapons being vastly different in their damage range, be reduced by both the dual-wielding damage penalty and the weapon range difference itself.

**How to reproduce:**
Equip a fast low level weapon on offhand and a Havoc Heroic in mh.
Hit dummy enough
Notice how each hit there is barely any variance at all.
Now do swap the weapons with the fast low level weapon being put into mainhand instead and observe.

**How it should work:**
BCB works in a simple way in wotlk
it has a fixed chance to proc dependant on how many talent points invested to do the damage it should, it should have no icd what so ever. it should hit for the appropriate amount depending on which weapon procced it.
[This is a old wotlk og video of a frost dk and you can see the damage variance in his scrolling battle text whenever BCB procs
](https://www.youtube.com/watch?v=vLJ3NljxdP8&t=8s)

Classic WotLk works exactly the way it is intended also :
![image](https://github.com/user-attachments/assets/f014450f-d291-4156-89c1-14786e09c276)

https://classic.warcraftlogs.com/reports/z17wmJNyfAaXq34G#fight=19&type=damage-done&source=14&ability=61895
Logs from classic are also indicating the damage variance. 

**Database links:**
https://www.wowhead.com/wotlk/spell=49628/blood-caked-blade

**Comment by Manpower99** [comment]
Looking at uwulogs on private servers where this functions correctly they have two db spell ids for Mainhand hits and Offhand Hits
[Offhand](https://wotlk.evowow.com/?spell=61895) and [Mainhand ](https://wotlk.evowow.com/?spell=50463)

This is a [Log ](https://uwu-logs.xyz/reports/23-03-09--18-59--Leex--Frostmourne3/player/Vezax/?boss=the-lich-king&mode=25H&s=8009&f=8624&attempt=0)from a different private server where the variance can be seen in the detailed damage on MH and OH hits.
and Here is a recent [Log ](https://uwu-logs.xyz/reports/24-07-11--19-05--Laurynhance--Whitemane-Frostmourne/player/Deekayxd/?boss=patchwerk&mode=25N&s=1438&f=1585&attempt=0)from Whitemane showing the lack of massive variance and only Mainhand version proccing.

**Comment by Karsenity** [comment]
Even though this isn't the original behavior, maybe this would be a good change to keep.

The dps increase is pretty minor, but it's enough that it disincentivizes unholy dk's from targeting tank weapons like Last Laugh since they'd gain more benefit from slow weapons in the MH. Considering that's been a big source of loot drama on the server, that sounds like a good tradeoff.

**Comment by Manpower99** [comment]
If they decide to keep the currently incorrect way of it working, then so be it. im only reporting how it should work.

**Comment by Riztazz** [comment]
The logs are from private server but the spells most definitely exist so to me this seems like an oversight which i'm going to fix, will close once it's live
