### ISSUE TITLE
Mount speed increases not working correctly

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1336]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Mount speed increases only adding to the base amount.

**How to reproduce:**
Can use an addon to view characters current movement speed, such as monkeyspeed.

**How it should work:**
https://www.wowhead.com/tbc/spell=32223/crusader-aura#comments:id=3369935
https://www.wowhead.com/tbc/spell=32223/crusader-aura#comments:id=3369873

**Database links:**

**Comment by Chaos-within** [comment]
https://wowpedia.fandom.com/wiki/Mount#Statistics

**Comment by haephaistoss** [comment]
/run print(GetUnitSpeed("target") / 7 * 100)
/script x=GetUnitSpeed("player") DEFAULT_CHAT_FRAME:AddMessage(format("Speed: %d yds/sec, %.1f kph, %.1f mph, %d%% normal run speed",x,x*3600/1093.6133,x*45/22,x/7*100))


you can test any target with this macro

**Comment by Chaos-within** [comment]
Bump?

**Comment by Piootrek** [comment]
It works correctly. From the macro above I got exactly same number as the guy in wowhead comments. Closing
