### ISSUE TITLE
Hunter pets and combat state

### ISSUE THREAD

**Issue by slicplaya** [gamefreedomgit/Frostmourne#1339]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Currently, attacking with a hunter pet doesn't put the hunter in combat. I've tested this with dk and warlock pets. It places the player in combat. It does not on hunter's currently.

**How to reproduce:**
PTR a hunter with a pet. Attack a target, watch combat state never happen.

**How it should work:**
As with all pets, the player should enter a state of combat when a pet attacks a target. This is extremely detrimental to PvP and dodging saps.

**Database links:**

**Comment by Riztazz** [comment]
Possibly fixed by https://github.com/gamefreedomgit/Frostmourne/issues/1385

Please check after the fix has been applied

**Comment by Piootrek** [comment]
Confirmed, https://github.com/gamefreedomgit/Frostmourne/issues/1385 fixed it.
