### ISSUE TITLE
Serpent Sting Snapshot with Chimera Shot

### ISSUE THREAD

**Issue by slicplaya** [gamefreedomgit/Frostmourne#1340]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Currently, Chimera Shot is not refreshing the current serpent sting on a target. It's reapplying a completely new sting and recalculating the hunter's current attack power.

**How to reproduce:**
Serpent sting a target, and chimera shot it with a high amount of attack power. On the next cool down, reduce the attack power of a hunter and cast it again, recognizing the massively lower Chimera shot and sting tick damage.

**How it should work:**
The first sting applied to the target should be "refreshed" as the tool tip states, and not reapplied and recalculated based on the current attack power of the hunter. Currently, when a sting is applied in aspect of the viper at 50% damage done, and later refreshed with a Chimera Shot with Aspect of the Dragonhawk on, the sting and chimera shot damage is still 50%, but it's recalculated and reapplied with higher attack power amounts. Something is definitely not working correctly.

**Database links:**

**Comment by haephaistoss** [comment]
Serpent sting refresh via chimera should recalculate AP, and keep % modifiers from the original cast, so it seems OK.

**Comment by UltraNix** [comment]
https://web.archive.org/web/20101206062019/http://www.warcrafthuntersunion.com/2009/12/chimera-shot-secrets-for-mm-hunters/ 
Not a bug.
Change about Chimera Shot not refreshing Serpent Sting will be reverted.
