### ISSUE TITLE
Warlock pet not casting Shadow Bite when available.

### ISSUE THREAD

**Issue by Eradicatepls** [gamefreedomgit/Frostmourne#1341]
**Description:**
Interaction with "/cast Shadow Bite" and autocast on.
When pet is within combat, if you chose to turn on autocasting on Shadow Bite, it's not using it when available.

**How to reproduce:**

Create a maccro with a "/pettattack" command and a "/cast Shadow Bite"
You can send pet on a dummy to see his spells are not queued After 1st Time using Shadow Bite.

**How it should work:**

Pet should cast Shadow Bite every 2 second when autocast is on, with talent in affli tree + in melee range + has mana. Ofc

**Database links:**

**Comment by WhitemaneChronus** [comment]
I managed to replicate the issue. 
While having shadow bite on auto cast, once its on cooldown, use /cast shadow bite or manually click on the pet spell. 
It bugs out and will stop auto casting it.

You can send your pet back and then to attack again to fix it.

Furthermore it's not specific to this pet or this spell, it happened with other pets / abilities as well, except imp firebolt cast which is 1 second cd. 
Same happened with hunters pets

**Comment by yeagerca** [comment]
Until it is fixed you can try adding to your macro to forcefully toggle it:
```
/cast Shadow Bite
/petautocastoff Shadow Bite
/petautocaston Shadow Bite
```
