### ISSUE TITLE
[Dungeon] [TBC] Shadow Labyrinth – Murmur

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#1342]
Links:
Boss: https://www.wow-mania.com/armory/?npc=18708
Murmur's Touch: https://tbc.wowhead.com/spell=33711/murmurs-touch
https://www.youtube.com/watch?v=l1M3NnUgSR4
Sonic Boom: https://tbc.wowhead.com/spell=33666/sonic-boom
Magnetic Pull: https://tbc.wowhead.com/spell=33689/magnetic-pull

ROOM: https://www.youtube.com/watch?v=ym9K83HWbhs (45:30 onward)

What is Happening:

1: Murmur's touch does not launch the person into the air upon detonation.
2: I am not sure if he is using Magnetic Pull or if he uses it right.
3: He does nothing when you enter the room. (as opposed to "ROOM" video)

What Should happen:

1: Person should go flying after the touch detonates
2: Magnetic Pull in the video looks like it is focused on a player, often the one who gets Murmur's Touch and it makes other players pulled to the the focused person
3: When you enter the Scream Room (iirc) or just boss room, Murmur should be fighting with the orcs as seen in video "ROOM"

**Comment by Piootrek** [comment]
1. Fixed
2. It works correctly right now
3. Can you reupload a video? I couldn't find any decent one that shows how it should work.

**Comment by Greywolf59** [comment]
I am on the vacation starting today at the moment but I dont think there is any more than those I posted. I can take another look when I get home in a few days.

**Comment by Piootrek** [comment]
The video you posted is not available for me.

**Comment by Greywolf59** [comment]
Yes, looks like it is gone now.
Here is one from tbc classic I guess. It looks very much the same as the old video from 1st tbc release
From about 5:45 here, just gotta slow it down
https://youtu.be/kXLuDZnJLc0?si=mwarwXagZfM_Ct4o

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by Greywolf59** [comment]
Now Murmur is not using any abilities on the player. Observed on heroic difficulty. Murmur keeps casting his spells on mobs in the room and just melees the player. That might change if the room would be cleared.
