### ISSUE TITLE
[Culling of Stratholme[] Can't skip chromie (again?)

### ISSUE THREAD

**Issue by bandini9** [gamefreedomgit/Frostmourne#1343]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
No idea what causes It, sometimes I can sometimes I can not. Probably about someone else in group.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
#1140
