### ISSUE TITLE
Kelthuzad - Frost blast

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#1344]
**Description:**
The problem is that the frost blast spell is affected by resistance, and due to this it does less damage than it should. Damage is also reduced due to talents and skills like Shield Wall and Defensive stance, which reduce damage by a percentage. None of this should reduce damage.

**How it should work:**
Frost blast Ability damage should not be resisted and should not be reduced by other spells.  It must deal damage equal to 26% of the player's total health. The second comment from wowhead of this ability confirms this. Here is another video that confirms this, the shaman loses 52% of his health in TWO ticks. This moment is very noticeable on raid frames.
https://youtu.be/0ooHg_YrXFI?t=5372

The third proof is that tanks with defensive skills should receive full damage from Frost Blast. A warrior receives 9,041 units of damage from freezing, which is exactly 26% of his HP from the total.
https://youtu.be/EhLKqxooTls?t=190

**Database links:**
https://www.wowhead.com/wotlk/npc=15990/kelthuzad
https://www.wowhead.com/wotlk/spell=27808/frost-blast

**Comment by Afgann** [comment]
fixed
