### ISSUE TITLE
Mail box items being deleted after 30 days instead of returned

### ISSUE THREAD

**Issue by Hades249** [gamefreedomgit/Frostmourne#1345]
Sent the greens i was saving to an alt where they were kept in the mail. When the time for the mails to be automatic returned passed they just disappeared and never returned.

**Comment by WhitemaneIsa** [comment]
@itsemmastone ?

**Comment by UltraNix** [comment]
@Hades249 Have you read these mails on your alt char and left items inside them?

**Comment by Hades249** [comment]
> @Hades249 Have you read these mails on your alt char and left items inside them?

I have read some mails and took some of the items, others weren´t even open. When the 30days passed i never got the items back to the character that i 1st sent them from and they just disappeared.

**Comment by UltraNix** [comment]
Any C.O.D inside?
Should be fixed anyway within the next server update.

**Comment by Hades249** [comment]
> Any C.O.D inside? Should be fixed anyway within the next server update.

No C.O.D i was just using the mail box as storage

**Comment by UltraNix** [comment]
Fixed.
