### ISSUE TITLE
Issue with pet taking way too high damage from aoe. Including Fire Elemental.

### ISSUE THREAD

**Issue by Eradicatepls** [gamefreedomgit/Frostmourne#1346]
**Description:**
Pet in wotlk should baseline benefit of a 90% damage reduction from all source of aoe and untargeted spells.

**How to reproduce:**
Damage from Heigan passive aoe are dealing raw damage. Same for Wall of fire in Sartha 2D.

**How it should work:**
https://wowwiki-archive.fandom.com/wiki/Avoidance_(passive)

**Database links:**

**Comment by UltraNix** [comment]
@Eradicatepls You mean Plague Cloud?

**Comment by Eradicatepls** [comment]
Yes and Eruption. 
Any sort of Aoe Damage seems to deal raw damage to pets in the server's core. Will link a details with logs of my raid tomorrow, but i think it's easy to notice on any pet class, pets are dying from nothing in raids.

**Comment by UltraNix** [comment]
In general it works. But there are some exceptions, so every each AoE spell must be reported.

**Comment by UltraNix** [comment]
Tested with warlock pet on Heigan:
![image](https://github.com/user-attachments/assets/dc8242f5-786d-4a6d-82dd-1ae78864275f)

The same boss - shaman Fire elemental:
![image](https://github.com/user-attachments/assets/0037b1b9-e175-4a45-8184-fe30de6cddfc)

**Comment by WhitemaneIsa** [comment]
No further info or complaints, closing.
