### ISSUE TITLE
Ghoul Explosion is cancelled if target dies

### ISSUE THREAD

**Issue by Karsenity** [gamefreedomgit/Frostmourne#1348]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** When using Corpse Explosion to command your pet to cast explosion, there is a bug where the ghoul will cancel the cast if its target dies during it. This leads to a problem in both PVE and PVP where the explosion cannot properly be utilized, as when this occurs corpse explosion still invokes the 4-second cooldown and doesn't refund the 40 runic power. 

It should be noted that the ghoul explosion is normally the second most damaging ability unholy dk's have access to in AOE, and is a crucial ability for their burst in pvp.

**How to reproduce:** Cast corpse explosion on your ghoul and kill the target before the cast finishes

**How it should work:** Ghoul continues to cast explode

**Database links:**

**Comment by Riztazz** [comment]
fixed, will close once it's live
