### ISSUE TITLE
Raise Dead cooldown only beginning after ghoul is dismissed

### ISSUE THREAD

**Issue by Karsenity** [gamefreedomgit/Frostmourne#1349]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Currently the cooldown for Raise Dead only begins ticking after the pet is dismissed. At least referring to Wotlk classic, the cooldown on Raise Dead ticks while the pet is summoned, rather than only starting after dismissal. You can see this demonstrated in this clip: https://youtube.com/clip/UgkxTJwRYi6_Xych4YGxgeZttuf8Wyncw3Kj?si=wsZczEljtiYNIG5c

**How to reproduce:** Summon a ghoul and dismiss it

**How it should work:** Cooldown should continue while ghoul is summoned in order to allow instant resummoning.

**Database links:**

**Comment by UltraNix** [comment]
https://www.youtube.com/watch?v=Cp3nIhf2tfk
I can see there the icon is greyed-out.
https://www.youtube.com/watch?v=sSO-QXUlvqs Same here.

**Comment by Karsenity** [comment]
> https://www.youtube.com/watch?v=Cp3nIhf2tfk I can see there the icon is greyed-out. https://www.youtube.com/watch?v=sSO-QXUlvqs Same here.

In the second video you sent, you can see that the cooldown is ticking while the ghoul is active. Even though the ability is still grayed out, the moment the ghoul dies the cooldown is already over halfway through.

**Comment by UltraNix** [comment]
Yep - you are right.
Still not sure about that change :)

**Comment by Karsenity** [comment]
Watcha mean by not sure :P As in concerns of impact?

**Comment by UltraNix** [comment]
E.g. First video.

**Comment by Karsenity** [comment]
Gotcha. The one thing with the first video is since he starts with the ghoul and never dismisses it, its hard to tell whether or not it was on cooldown.

**Comment by Karsenity** [comment]
Also from a personal standpoint, I'd imagine the intended behavior is the older video + how they implemented it in classic. It provides only minor/niche dps increases, i.e. letting you resummon after death pacting during a boss fight. The biggest use-case would honestly be less downtime from dismissing your pet to skip adds in dungeons.

**Comment by Karsenity** [comment]
Did more digging for the inconsistency:

[Patch 3.1.0](https://wowpedia.fandom.com/wiki/Patch_3.1.0) (2009-04-14): Duration lowered to 60 sec. and cooldown lowered to 3 min. The cooldown on this ability now begins when the pet dies rather than when it is summoned.

It looks like this change was made in patch 3.1, and then was reverted during wotlk classic. I'll leave it up to you which version you think is best. Have a good one <3

**Comment by UltraNix** [comment]
https://us.forums.blizzard.com/en/wow/t/bug-deathknight-raise-dead-goes-on-cooldown-when-pet-explodes-and-not-when-its-killed/1368142
There are many videos from wotlk also showing cooldown should start when pet is dead/gone.
I will leave it as it is now.
