### ISSUE TITLE
Hunter able to call PetDismiss() API, abandoning pet

### ISSUE THREAD

**Issue by Karsenity** [gamefreedomgit/Frostmourne#1350]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** The PetDismiss() API command is behaving unexpectedly for hunters. If used as the hunter, it will abandon your pet. Additionally, if used during Eyes of the Beast, it will instantly dismiss the pet, which opens the door for potential abuse in pvp (instantly recall pet to safety + instantly replenish its focus bar, as pets are always summoned at max focus).

**How to reproduce:** use /run PetDismiss() and try to call your pet

**How it should work:** Shouldn't work on hunter pets.

**Database links:**

**Comment by Afgann** [comment]
fixed
