### ISSUE TITLE
Sun-Lute Head transforming to Head of Atiesh

### ISSUE THREAD

**Issue by zYukou** [gamefreedomgit/Frostmourne#1351]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Good afternoon, when killing Kelthuzad, he gave the solar laud paladin item, but when picking it up, it transformed into the atiesh staff item, I need help because he gave me another item when picking it up. 
p/s: I used a translator xD   ...                                        thanks,  pj:  Yukou

**How to reproduce:**
![asd (1)](https://github.com/user-attachments/assets/78e90abd-f636-41b5-9cb3-836ee9b9e1df)
![asd (2)](https://github.com/user-attachments/assets/ddecd9de-0f0f-4c50-8a3e-076da99738e5)

**How it should work:**
I would have to give me the item laud solar, and not head staff of atiesh

**Database links:**

**Comment by zYukou** [comment]
I don't have the photo of the item, because it was direct for me, and when I received it he gave me the other item. They told me I had to put in a ticket anyway.
If it wasn't bugged like that, I would finally be continuing my mission as a paladin.

**Comment by WhitemaneIsa** [comment]
@RadeghostWM @itsemmastone

**Comment by UltraNix** [comment]
@zYukou It was master loot? You could pick it up by yourself or master looter gave it to you?

**Comment by MetalCrawler** [comment]
Hi, we had the same issue two days ago, Paladin ign: **Batizado** got Staff instead of Head even tho me (Master Loot of raid) gave him the HEAD.

Yes it was Master Loot I gave him via EPGP. Others have been reporting the same problem with MASTER LOOT.

**Comment by zYukou** [comment]
F

**Comment by zYukou** [comment]
@UltraNix 
Hello, today with my guild, we killed kt again, the item solar laud came out, and when assigned to me it transformed again into the atiesh staff, with me being the master looter...

![help (1)](https://github.com/user-attachments/assets/2df2cb20-ec48-4c23-8fed-1332b40142ac)
![help (2)](https://github.com/user-attachments/assets/e7feb6a2-1ca5-474e-81f5-5437707f0f60)

Please help, 8-9 days ago we already killed a keltu, and now we killed another, and I still have the item bug

**Comment by zYukou** [comment]
@itsemmastone hello, need help with item bug
today with my guild, we killed KT again, and it doesn't give me the item.  (images above) with me being the master looter...
