### ISSUE TITLE
Hyperspawning mobs ignoring their grace period

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1352]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When a mob spawns, there should be a few seconds before it engages in combat/reacts to those around them, unless attacked.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Godmatik** [comment]
Also - hyperspawning mobs do the 'level up' animation when respawning and should not.

**Comment by Afgann** [comment]
fixed
