### ISSUE TITLE
Loatheb

### ISSUE THREAD

**Issue by Vagos19** [gamefreedomgit/Frostmourne#1354]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Loatheb buff being kept even after finishing the boss.

**How to reproduce:**  Kill the boss the moment some people get the last spore.

**How it should work:** Buff wasn't meant to be kept alive after u were leaving the room of loatheb, let alone if you pull a boss. Right now there is even a log where people had the buff while killing sapphiron. That isn't meant to happen, compromising the logs.

**Database links:**
https://www.warcrafttavern.com/wotlk/news/wotlk-classic-hotfixes-november-8th-fungal-creep-nerfed-on-trash/

**Comment by bandini9** [comment]
1. This aint wotlk classic

2. wotlk classic logs and 3.3.5a pvp server logs never meant to be compare each other

**Comment by Manpower99** [comment]
It is indeed a wotlk classic change that was intended to nerf speedrunning and using it to kill sapphiron quicker if the devs decide on using it. but here it is :
![image](https://github.com/user-attachments/assets/d67dea20-efe4-4947-ad9a-e9efa95703f1)
