### ISSUE TITLE
Waterlogged Recipe

### ISSUE THREAD

**Issue by disruption01** [gamefreedomgit/Frostmourne#1355]
Waterlogged recipe seems to be missing from the Bag of Fishing Treasures

https://www.wowhead.com/wotlk/item=49667/waterlogged-recipe

Never go it in many days and spoke to a couple of people who also didn't get any.

In the AH never saw one so I suspect is not dropping at all.

**Comment by zuldabad** [comment]
Sup mate, I had it 1 time, doing fishing daily for 1 month roughly 
And it's soul bound, how it should be till some patch, can't remember what patch exactly

**Comment by zuldabad** [comment]
Seems like not so much luck on us bro, my daily loot is trash

**Comment by disruption01** [comment]
It shouldnt be soulbound at least in wotlk classic wasnt. But the drop rates must be wrong aswell

**Comment by zuldabad** [comment]
Well I did my research, and it has something around 1.7 - 2% drop rate, u must be atleast 300 at cooking to get it from fishing daily bag and seems like I was wrong saying that it is should be soulbound, but I can clearly remember, that a got it, then run to the AH, saw that there is no Waterlogged recipes, then trying to sell it but AH won't let me do that cos it says it soul bound

**Comment by zuldabad** [comment]
Anyway, no luck, or maybe something wrong with fishing part on that server, cos events work wrong aswell, wrong time, and no shark, and no tastyfish ponds kekw
On me there is around 40 daily quest, and no fishing rods, only 1 recipe, no any other fishing enhancements, just waterwalking pots, some oil, and tons of gray crap
Same with outland fishing daily, no beer recipe so far with same amount of daily done

**Comment by bandini9** [comment]
I did around 12-13 fishing daily so far and got 1

**Comment by yeagerca** [comment]
I got 2 Waterlogged Recipes early on in the server but haven't seen one since. Neither of them were soulbound, I sold both. I also got one Vial of Poison.
