### ISSUE TITLE
[Ulduar] Flame Lev Systems Shutdown not working when Turret are killed.

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1357]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Flame Lev 10 man System Shutdown not working when Turret are killed.

**How to reproduce:**
Kill turrets after being launched from a Demo

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
