### ISSUE TITLE
Problem for [Base of Atiesh] KJ

### ISSUE THREAD

**Issue by yixs1** [gamefreedomgit/Frostmourne#1358]
Hi, I killed KJ un raid 7308 while on Atiesh quest, no one else looted [Base of Atiesh] off KJ and I don't see the quest item on the corpse... but in his previous post is the following and I quote "Atiesh, Greatstaff of the Guardian: the staff of legends, obtainable by Druids, Priests, and Mages. This questline works exactly like it did in Classic WoW, with two exceptions: Warlocks cannot get it anymore, and [Head of Atiesh] drops from Kil'jaeden from Timewalking: Sunwell Plateau." I NEED HELP

Here is the image where it is said that KJ will give the item  [Base of Atiesh] -- date: 13/06/2024
https://files.fm/u/jued8zd57u
https://www.wowhead.com/classic/guide/wow-classic-atiesh-greatstaff-of-the-guardian-questchain 
**Database links:**
https://files.fm/u/vbvyymdvga

**Comment by WhitemaneIsa** [comment]
@RadeghostWM @itsemmastone

**Comment by WhitemaneChronus** [comment]
Checking the issue on PTR C'thun or KJ didnt drop the base

**Comment by UltraNix** [comment]
Fixed.
