### ISSUE TITLE
KJ (SWP) doesn't drop Base of Atiesh

### ISSUE THREAD

**Issue by Twawa8** [gamefreedomgit/Frostmourne#1359]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

In-game charactor name:  Twawa

**Description:**
Entire timeline describing the bug:

1.  On July 11th, 2024 - collect all 40 splinters  in raid ID 8339.  Combine all 40 splinters to the quest item, which opens the followup quest in Tanaris.
2.  Went to Tanaris received quest to kill KT in naxx for Head of Atiesh and KJ in swp for Base of Atiesh.
3.  In the same raid ID 8339 later, I killed KT and got the [Head of Atiesh]  https://www.wowhead.com/classic/item=22733/staff-head-of-atiesh
4.  Fastforward to today July 13th, in SWP raid ID 9935 I killed KJ but without [Base of Atiesh] appearing on KJ's corpse
https://www.wowhead.com/classic/item=22734/base-of-atiesh

References:
This is the screenshot evidence to show no Base of Atiesh on KJ's corpse
![image](https://github.com/user-attachments/assets/bd121e38-965f-40d4-836c-7fc197863541)
This is the recording of the kill shows no one else looted Base of Atiesh and no Base of Atiesh on KJ's corpse
https://youtu.be/kxsV2FDQINk?t=4337

**How to reproduce:**
Seeing others also reporting the same issue, I am taking their reporting as evidence of reproducing the issue.

**How it should work:**
KJ in swp should drop the Base of Atiesh as described in the quest description.
![image](https://github.com/user-attachments/assets/eb43de30-333c-49db-b15c-3ded43ea3431)

**Database links:**
https://www.wowhead.com/classic/item=22733/staff-head-of-atiesh
https://www.wowhead.com/classic/item=22734/base-of-atiesh

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/1358
