### ISSUE TITLE
Heroic Presence

### ISSUE THREAD

**Issue by Trollsmet** [gamefreedomgit/Frostmourne#136]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Heroic Presence does not give my party members + hit. Ive tried it with my friends being allys and being horde. Me myself is on a dranei.
I dont know if it is a visual bug or if they really aren't getting any + hit. I can see them getting the buff under their potrait when i target them. 
**How to reproduce:**
Make a Dranei and inv anyone to a party and check if it affects their Hit.

**How it should work:**
Should give my party + hit.

**Database links:**
https://www.wowhead.com/wotlk/spell=28878/heroic-presence

**Comment by Manpower99** [comment]
I have made a Draenei Warrior on PTR with pre set which has 7.11% Hit.
 this is a visual bug that should indeed be fixed to show the 1% Hit on character tab.
However in over 500melee swings and melee abilities as well i have not gotten a single miss.
I will update this later to confirm if it works for party members or not.

**Comment by Trollsmet** [comment]
Alright thanks for the response ☺️

**Comment by Afgann** [comment]
https://us.forums.blizzard.com/en/wow/t/draenei-hit-racial-heroic-presence/1609487
