### ISSUE TITLE
LOS not needed, cast through mostly anything!

### ISSUE THREAD

**Issue by 44aa44** [gamefreedomgit/Frostmourne#1361]
**Description:**
You can cast through, walls. bushes. some entire buildings, fences.

**How to reproduce:**
Go to the walls in Warsong Gultch, any tree or obstruction in Azeroth and cast you will 9/10 hit your oponnent.

**How it should work:**
Spells shouldn't penetrate 4 feet of wood.

** links:**
video link backup
https://files.catbox.moe/8avzmi.mp4
demonstration
https://github.com/user-attachments/assets/b77e36af-2feb-4613-9115-8114be74e09f

special thanks to Isa for putting all my issues in low priority.

**Comment by UltraNix** [comment]
Terrain does not prevent from casting spells.
Some objects (like rocks, trees etc) also can ignore LoS.
https://eu.forums.blizzard.com/en/wow/t/los-is-it-bugged/127000/10
https://eu.forums.blizzard.com/en/wow/t/los-is-it-bugged/127000/15
https://www.mmo-champion.com/threads/1193133-Is-line-of-sight-removed-or-bugged

**Comment by zebostplay** [comment]
> Terrain does not prevent from casting spells. Some objects (like rocks, trees etc) also can ignore LoS. https://eu.forums.blizzard.com/en/wow/t/los-is-it-bugged/127000/10 https://eu.forums.blizzard.com/en/wow/t/los-is-it-bugged/127000/15 https://www.mmo-champion.com/threads/1193133-Is-line-of-sight-removed-or-bugged

You're right about terrain and some small objects. But on Warsong Gulch? These chopped woods on whole map was always unable to cast through it. Without this, whole bg is unbalanced because each melee class is simply outplayed even by the worst casters. how can you say, that is normal? XD it isn't
