### ISSUE TITLE
[Spell] [Class] Mage's Spellsteal – Charged Skin and Botlhorn's Rune of Flame

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#1362]
When Mage Speallsteals [Botlhorn's Rune of Flame](https://www.wowhead.com/wotlk/spell=54965/bolthorns-rune-of-flame), it does no damage to the enemies. There is visual effect of having it and the rune hitting enemies but no damage is done. Same is true for [Charged Skin](https://www.wowhead.com/wotlk/spell=50718/charged-skin) and might be true for other/all spellstolen aura-damage buffs.

**Comment by Piootrek** [comment]
Fixed
