### ISSUE TITLE
Sunwell 25 normal wrong level requirement

### ISSUE THREAD

**Issue by yeagerca** [gamefreedomgit/Frostmourne#1364]
**Description:**
Characters lower than level 80 cannot enter Sunwell 25 normal.

**How to reproduce:**
Attempt to enter Sunwell 25 normal with a level 70-79 character.

**How it should work:**
Sunwell 25 normal should be accessible by characters level 70+ while Sunwell 25 heroic should be accessible only to level 80 characters.

**Comment by Afgann** [comment]
fixed
