### ISSUE TITLE
Anti-SPAM in /w and /p for hardcore(-HC) characters

### ISSUE THREAD

**Issue by Consealer** [gamefreedomgit/Frostmourne#1366]
When I try to send Recount info in /p or /w channel as hardcore character after second message I get muted and an error tells me:
The number of messages that can be sent is limited. Please wait to send another message.
Normal characters dont get muted on those channels. I checked it.
I contacted GM Nightmare about it. He said it should not be happening and told me to report it here.
![WoWScrnShot_071524_093601](https://github.com/user-attachments/assets/1aef8f68-94b4-4e1c-b3fc-7a21ac7f922f)

**Comment by UltraNix** [comment]
It's not about hardcore or not - it's about spamming with the message. The cooldown is 3 seconds and the limit depends on whether you have max leveled char or not.
