### ISSUE TITLE
[PRIEST] Mind FLay + Movement Impairing Cancel Effects

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1367]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** currently Mind Flay channel is interrupted if the target removes snares -  like Hand of Freedom, Druid shapeshifting, or even pvp trinket.

**How to reproduce:** Channel Mind Flay onto a target and have them use any of the aforementioned abilities.

**How it should work:** Mind Flay shouldn't stop channeling, but the slow component should be removed - or ignored.
It is basically one of the most important ability of a spec, it was hackfixed to not be useless in these scenarios

**Database links:** https://www.wowhead.com/wotlk/spell=48156/mind-flay

https://www.warcraftmovies.com/movieview.php?id=163587 ~ 15:17

https://www.youtube.com/watch?v=_uRiKBLD-C8&t=12s

**Comment by alemae96** [comment]
From the video I can see the warrior you are targeting had Hand of Freedom on him while you were still casting Mind Blast then Mind Flay. You can also see in the chat at the time no trinket was used, and you were targeting a warrior, so there was no druid shapshift.

**Comment by UltraNix** [comment]
I see something like this:
https://wowpedia.fandom.com/wiki/Mind_Flay?oldid=2572548
`When attacking a Druid with Mind Flay, shapeshifting cancels it.`
`Similarly, if the target uses a PvP trinket, it removes Mind Flay, due to the snare.`
So looks like that anything removing snare effects would cancel Mind Flay?

**Comment by haephaistoss** [comment]
Sometimes wowwiki isn't accurate source, that's why I linked actual wcm video. The mechanic of shapeshifting is the same as the clear effect from anything that clears movement impairment.

May be another case of blizz spaghetthi code during some times, but if Hand of Freedom didn't cancel it, which it didn't, no similar effects should.

I don't play priest, but I have never seen in my time on retail wotlk this sort of mechanic

**Comment by haephaistoss** [comment]
One question tho: in another report i was told wotlk classic was no basis for anything, yet in others when its beneficial for a class played by a lot of ppl, it seems like wotlk classic is taken as a basis. So the question is, is it og wotlk, or is it a per bug basis?

**Comment by haephaistoss** [comment]
> I see something like this: https://wowpedia.fandom.com/wiki/Mind_Flay?oldid=2572548 `When attacking a Druid with Mind Flay, shapeshifting cancels it.` `Similarly, if the target uses a PvP trinket, it removes Mind Flay, due to the snare.` So looks like that anything removing snare effects would cancel Mind Flay?
> 
> About that movie from warcraft movies - I can see that Hand of Freedom was applied exactly when Mind Flay was over?

if you play frame by frame, there is a teeny tiny overlap, the other video on ytb is way better quality and longer overlap.

**Comment by UltraNix** [comment]
> One question tho: in another report i was told wotlk classic was no basis for anything, yet in others when its beneficial for a class played by a lot of ppl, it seems like wotlk classic is taken as a basis. So the question is, is it og wotlk, or is it a per bug basis?

Link to me that report :)

**Comment by UltraNix** [comment]
I found something like these:
https://www.reddit.com/r/wow/comments/fgx6h/druid_shapeshifting_pvp/
`Shift out of slow. Shifting cancels mind flay too. You're fucked on a frost trap, just like everyone else.`

https://www.bluetracker.gg/wow/topic/us-en/12065381924-mind-flay-is-broken/#40 (it's tbc)
`Mind Flay also get canceled when the target uses a PvP trinket (or when druids shape shift, or various other abilities that remove snares), even when we have the glyph of mind flay. I know this is because of the snare effect`

**Comment by haephaistoss** [comment]
I'll try the interaction on cata classic tomorrow and see what I get, I don't recall this being the case with hand of freedom or pvp trinket at all.

Iirc, cata changed druids to remove only snares, roots are not removed anymore right?

**Comment by WhitemaneIsa** [comment]
No further info/complaints, closing.
