### ISSUE TITLE
Blade Barrier not popping out of combat

### ISSUE THREAD

**Issue by Sonataa101** [gamefreedomgit/Frostmourne#137]
[//]: # (http://wowhead.com/) https://www.wowhead.com/wotlk/spell=55226/blade-barrier

**Description:**
Whenever your Blood Runes are on cooldown, you gain the Blade Barrier effect, which decreases damage taken by 5% for the next 10 sec. however on Frostmourne PTR, Blade Barrier doesn't trigger when you're out of combat.

**How to reproduce:**
make a blood death knight and use any of your blood abilities twice (out of combat) then use them twice while in combat.

**How it should work:**

Blade Barrier should trigger whenever your Blood Runes are on cooldown, whether the Death knight is in/out of combat.

**Comment by Manpower99** [comment]
To add to this there are few issues on Blade Barrier :
1.vampiric blood + rune tap = u get blade barrier but other combination you don't which makes no sense but yeah.
2.while 2 blood runes are on cooldown you should get blade barrier refresh even by using horn of winter, yes its a very blizzlike thing aslong runes are on cooldown any spell you use will refresh it, but on this server it does not function this way.

**Comment by Afgann** [comment]
fixed
