### ISSUE TITLE
[WARRIOR] Spell Reflect + Spellsteal

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1370]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Spellsteal doesn't steal a buff for the warrior from the mage if reflected.

**How to reproduce:** cast spellsteal onto a warrior with spellreflect up.

**How it should work:** spell reflecting spellsteal should have the warrior steal a buff from the caster mage, if possible.

**Database links:** https://www.wowhead.com/spell=23920/spell-reflection#comments

I actually asked my friends to try this out :P Spellreflecting spellsteal actually steals one of the mage's buffs and gives it to the warrior (The warrior later joked about doing this to get molten armor, putting on caster-gear and shout "I´m a mage", not sure if he did though :P) As a rule of thumb when thinking about how spellreflect works, imagine that the warrior is casting the spell, but with the mage's stats, buffs and specc.

**Comment by Chaos-within** [comment]
Does not work like that.

**Comment by UltraNix** [comment]
@haephaistoss Provide some sources it's a bug.

**Comment by UltraNix** [comment]
Okay, got something:
https://www.wowhead.com/spell=23920/spell-reflection#comments:id=291275

**Comment by UltraNix** [comment]
Still not sure about what should happend with stolen buff? Should be applied on warrior or only dispeled?

**Comment by haephaistoss** [comment]
Afaik, it should be applied to the warr, as if he had cast the spell.

So basically the same as with every other reflected spell, only difference being that in this case no DMG is applied, because there is none

**Comment by UltraNix** [comment]
Okay - as I see on many comments it's just a dispel.

**Comment by UltraNix** [comment]
After reading many comments, I think it should be just a dispel.
Most noticable:
https://wow.allakhazam.com/forum.html?forum=243&mid=1249840925181138908&h=25&p=1#12

**Comment by haephaistoss** [comment]
i don't think it was changed in cata classic so we can hop onto PTR and test it :D

I remember it actually stealing a buff, but it may have been a period when it was bugged, or I recall completely wrong.

However, reading this one and the wowhead one - the wowhead one seems more certain, but at this point it's mostly grammatics

Tested it and... vs I Think

**Comment by UltraNix** [comment]
Fixed.
