### ISSUE TITLE
[Quest]  [Escape from Durnholde]10284

### ISSUE THREAD

**Issue by GM-Nightmaree** [gamefreedomgit/Frostmourne#1372]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
quest event isnt scripted , cant talk to thrall to start the event 
![image](https://github.com/user-attachments/assets/796bcab3-0071-415e-9666-47e55c1b3725)

**How to reproduce:**
get the quest and go to thrall you wont be able to talk to him to escort him and start the event

**How it should work:**
thrall should have an option to start the event

**Database links:**
https://www.wowhead.com/wotlk/quest=10284/escape-from-durnholde

**Comment by PanJanuszek** [comment]
![image](https://github.com/user-attachments/assets/fe0dc7f7-541b-4377-8036-e01afb5d7a70)
it works i have tried on hc version. When I finished setting 5 bombs in nearby houses, gossip appeared.
