### ISSUE TITLE
[Wintergrasp] Graveyard immunity lasting after workshop is captured

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1373]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Leads to people sitting at graveyards with everlasting immunities keeping the newest faction stuck in combat after they start ressing since it's become their graveyard.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
I tested that with Horde char ressing and stainding at Sunken Ring graveyard. After the workshop is captured, the Spiritual Immunity is gone.
@Chaos-within Some specific graveyard?

**Comment by UltraNix** [comment]
Okay - I see it's true at least for Broken Temple.

**Comment by Chaos-within** [comment]
Only encountered it at Broken Temple and thought it was same for all.

**Comment by UltraNix** [comment]
Fixed.
