### ISSUE TITLE
[Spell] Eagle Eye not showing enemy beyond a certain distance from character

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1374]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Likely caused from whitemanes reduction in character load in distance and not made to work with specific spells. Shaman's [Far Sight] is likely included in this.

**How to reproduce:**
Eagle Eye a fair distance, notice no enemies in area.

**How it should work:**
Should be able to Eagle Eye and see enemies even if multiple zones away.

**Database links:**

**Comment by yeagerca** [comment]
This would also apply to the engineering item, [Ornate Spyglass](https://www.wowhead.com/wotlk/item=5507/ornate-spyglass).
Haven't tested it myself, but I heard from friends that Priest's Mind Vision is correctly showing mobs at a distance.

**Comment by BalanCV** [comment]
I'm pretty sure this is intentional, changing load distances would probably cause the server to lag.

**Comment by Chaos-within** [comment]
There's no need to change load distance, just make load distance based off eagle eye location during spell channel.

**Comment by UltraNix** [comment]
Fixed.
