### ISSUE TITLE
[Transmog] Weapon swapping removes transmogged enchant

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1375]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Transmogged weapon enchant reverts to the original one on the weapon upon weapon swapping

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Piootrek** [comment]
Fixed
