### ISSUE TITLE
Pets spawned as aggressive bug

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#1376]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Pets that get spawned as aggresive either do 1 attack then get recalled as if the owner did /stopattack or they simply not attack the target until the owner does /petattack.
This is affecting pets with petbars such as: Shadow fiend, Druid Treants, Infernal, possibly others I forget.

**How to reproduce:**
Cast shadow fiend on a target you are either in or outside combat with. Watch pet either not attack target or do 1 attack and stop, coming back to owner until you order it to attack.

**How it should work:**
Pets spawned as aggressive should either stick to their target which they were casted on (in case of shadow fiend)
Or attack closes target that is in combat with owner in the place they were spawned (as treants and infernal being aoe summon)

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
