### ISSUE TITLE
Owner AOE vs Pets on defensive stance

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#1377]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Pets on defensive stance currently attack targets that the owner engages combat with when using single target spells. However, when owner uses AOE, the pets stay passive not engaging anything.

**How to reproduce:**
Use Rain of fire on a pack while your pet is out and on defensive stance and it simply stay by your side instead of starting attacks.

**How it should work:**
Pet should start attacking the closest target inside the aoe of the owner/those the owner is in combat with.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
