### ISSUE TITLE
Deep Wounds and Trauma

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1378]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Tested this on Ptr with no trinkets or procs.
When you get the talent Trauma (increases bleed damage taken by the target by 30%), warrior's Deep Wounds does 69% more instead of 30% more (x1,69 instead of x1,30). 
This could be because deep wounds takes 30% from the talent twice into the formula, which results in 69% total increase. This bug does not seem to affect other dots, like rend.
Every test is conducted on Heroic Training Dummy

**How to reproduce:**
Crit on Dummy once with a twohander with Deep wounds Talented.
in my test deepwounds tick for 113damage
Rend tick is 589

Crit on a Dummy with the same setup just add 1 points in Trauma
now each Deepwounds tick is 149 (a 31% increase from 113tick)
Rend tick is 677 ( a 14% Increase from 589tick)

Crit on a Dummy with the same setup just add 1 more point (total of 2 invested talent points)  in Trauma
now each deepwounds tick is 191 (  69% increase from 113tick)
Rend tick is 765 (a 29% increase from 589tick)

Perhaps it is double dipping if the Warrior is talenting the talent itself i cannot be certain but i have conducted this test multiple times and concluded it is doing way more damage than it should.
especially since this is a growing dot like ignite so the accumulative damage will grow too much.

After further digging this seems to be an old sunwell bug that was never fixed : https://youtu.be/wY2w9cgbcPg

**How it should work:**
Rank 1 Truma should increase Bleed Damage by 15%
Rank 2 Trauma Should increase Bleed Damage by 30%
Mangle Should increase Bleed Damage by 30%
Deep Wounds should only benefit once in the formula not twice.

Edit: it would seem Deepwounds simply takes into account any Bleed Increase Debuff Twice
As with the comments below, tested with both Trauma and Mangle, the formula likely just takes one of the two debuffs twice into account.
Should Be Trauma R2/Mangle>Trauma R1. and ony taking it into the formula once.

**Database links:**
https://www.wowhead.com/wotlk/spell=46855/trauma

**Comment by AlucardHellsingChapel** [comment]
Did you take blood frenzy into account ?

**Comment by Manpower99** [comment]
Blood Frenzy was not talented. also as i have written there was no trinkets or procs.

**Comment by Gruonden** [comment]
So I tested it as well. It seems that it’s more about Deep Wounds than Trauma itself. I also tested it with a feral cat. The Mangle debuff (30% more damage from bleeds) provides the same amount of damage increase as Trauma. However, only warriors benefit more from Deep Wounds than they should. For example, Rake benefits a 30% damage increase. Here are the results:

CAT: Rake: 470 hits without Mangle/Trauma vs. 611 hits with Mangle/Trauma.
        Rip:    559 hits without Mangle/Trauma vs. 726 hits with Mangle/Trauma.
WARRIOR: 122 hits without Mangle/Trauma vs. 206 hits with Mangle/Trauma (with only 1 stack of Deep Wounds).

The tests were performed without any procs (neither talent procs nor item procs)

**Comment by Manpower99** [comment]
> So I tested it as well. It seems that it’s more about Deep Wounds than Trauma itself. I also tested it with a feral cat. The Mangle debuff (30% more damage from bleeds) provides the same amount of damage increase as Trauma. However, only warriors benefit more from debuff than they should. For example, Rake and Rip benefits a 30% damage increase and Deep Wounds about 60%. Here are the results:
> 
> CAT: Rake: 470 ticks without Mangle/Trauma vs. 611 tics with Mangle/Trauma. Rip: 559 tics without Mangle/Trauma vs. 726 tics with Mangle/Trauma. WARRIOR: 122 tics without Mangle/Trauma vs. 206 tics with Mangle/Trauma (with only 1 stack of Deep Wounds).
> 
> The tests were performed without any procs (neither talent procs nor item procs)

Thank you for your tests, it is likely an issue within deep wounds's code itself benfitting from both the debuff and another multiplier if the warrior has talented it, further evidenced by that fury warrior's deep wounds does not seem to be benefitting twice.

**Comment by Gruonden** [comment]
@Manpower99 It seems that this also applies to Fury Warriors. You don’t need to invest any points in the Trauma talent to achieve over a 60% damage increase from the bleed debuff (Mangle).

As Fury Warrior: 118 ticks without debuff, 198 ticks with debuff active. That is not 30% increase but rather over 60%. 

Additionally, Deep Wounds is calculated based on the weapon with which you scored a crit strike, so if you crit with your off-hand weapon, your deep wounds will tick for lower amount of damage (73 without debuff, 123 with debuff - also over 60% increase). But honestly , I dont know if it suppose to work like that or not so I will just leave it here.

**Comment by Manpower99** [comment]
> @Manpower99 It seems that this also applies to Fury Warriors. You don’t need to invest any points in the Trauma talent to achieve over a 60% damage increase from the bleed debuff (Mangle).
> 
> As Fury Warrior: 118 ticks without debuff, 198 ticks with debuff active. That is not 30% increase but rather over 60%.
> 
> Additionally, Deep Wounds is calculated based on the weapon with which you scored a crit strike, so if you crit with your off-hand weapon, your deep wounds will tick for lower amount of damage (73 without debuff, 123 with debuff - also over 60% increase). But honestly , I dont know if it suppose to work like that or not so I will just leave it here.

Okay good find, then it seems the issue is entirely within deep wound's code regardless of it being talented or not

**Comment by yeagerca** [comment]
> Additionally, Deep Wounds is calculated based on the weapon with which you scored a crit strike, so if you crit with your off-hand weapon, your deep wounds will tick for lower amount of damage (73 without debuff, 123 with debuff - also over 60% increase). But honestly , I dont know if it suppose to work like that or not so I will just leave it here.

That is intended. Criticals that came from main-hand will use main-hand weapon damage, off-hand will use off-hand, and non-weapon spells will use main-hand.

**Comment by UltraNix** [comment]
Fixed.

**Comment by Manpower99** [comment]
Has been in fact reverted as of i'd assume 2 weeks ago perhaps longer. Uwulogs clearly indicate this, wether or not its intended i cannot confirm but evidence show that the revert is intended but there is no basis for why this bug should exist as it contradicts every finding from classic wotlk. not a single high end warrior in classic knew of such bug even on Fight Club Discord.

**Comment by RealDerpyDude** [comment]
https://youtu.be/hoF0KpGzzf4
