### ISSUE TITLE
[PTR] 25N Mimiron HM Fire Cap

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1379]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
This would affect all raid difficulties of Mimiron HM. ( 10n/25n/10hc/25hc) 
https://www.youtube.com/watch?v=Jee971qfSMQ
According to Tankspot, the fire's wont even spread if you reach fire cap at 4:20
This is further evidenced at 5:00 you can see the explosion that would normally summon more fires did not, since the room is in fact fire capped.
this was further confirmed in classic's pre nerf ulduar release where there was in fact a fire cap.
https://www.youtube.com/watch?v=IJpiB-q4FEs
at 4:25 as you can see no new fires spawned.

**How to reproduce:**
Do mimi hm>notice how fires are uncapped and can engulf the entire room.

**How it should work:**
After a certain amount of flames you should reach "fire cap", it means you have so many fires that the fires won't spread anymore and even if the timer is up, 3 new fires won't actually spawn.

**Database links:**

**Comment by Afgann** [comment]
fixed
