### ISSUE TITLE
Several issues with respawning mobs

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#138]
**Description:**
1. When a mob respawns, it aggros you immediately. There should be a 5 second or so grace period of them not detecting when they spawn
2. Respawn rate is currently set at 1 minute rather than the standard 5. While this may be helpful for dense zones with a lot of players, it also makes it incredibly difficult to accomplish some quests solo. The respawn rate should be handled dynamically.
3. Respawning mobs show the 'level up' animation when popping in - this is an old stock bug, there should be no such animation, they should simply appear.

**Comment by RadeghostWM** [comment]
1 and 2 yes, 3 is not stock bug, majority of mobs respawn without that (source: classic wow)

**Comment by Godmatik** [comment]
With 3 I am saying currently when a mob respawns on Frostmourne it shows the level up animation, on classic if does not, unless I misunderstanding you.

**Comment by Godmatik** [comment]
Some days on PTR, seems like the 1 min respawn is active, some days its set to standard 5 min respawn

**Comment by Godmatik** [comment]
Seems fixed
