### ISSUE TITLE
AotD Scaling findings 

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1381]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Many bugs have been fixed recently relating to AotD and its scaling but here are my findings and few remaining bugs that might need to be ironed out.

Things that seem to be working correctly:
Ghouls should be considered rogues and benefit from stats at the same rate as a rogue. 
this seems to be working accurately, if you buff a rogue with a Paladin Class Buffs a ghoul within the raid will get the same buff.
Claw should only be casted at 75+ Energy, this has been fixed recently.
MeleeHit and Expertise Scaling from Owner's Melee Hit seems to be working correctly.
no scaling from glyph of ghoul, orc racial(command) and ravenous dead.

**Things that don't seem to be working correctly:**
1.Ghouls are summoned with 0 Energy, they should summon with 100
2.Periodic Taunts seem to be causing ghouls to lose some attacks/swings, causing less total attacks.
3.Channeling AotD seems to be losing ticks at the end and thus summoning less ghouls, might be an issue due to spellqueue. similar issue has been reported for a couple of channeled abilities ([Mind Flay report](https://github.com/gamefreedomgit/Frostmourne/issues/1050))

Now regarding scaling ( most issues seem to be already fixed but here they are if required for a double check if required.)

AotD Ghoul's BaseDamageMin:     30 
AotD Ghoul's BaseDamageMax:     74
AotD Ghoul's Base Attack Speed:        2
AotD Ghoul's CritMultiplier:    2
AotD Ghoul's AttackPowerPerDPS: 17.5

AotD Ghoul's Base Stamina : 1.9875 Per Level or (x0.2 of Owner's Snapshotted Stamina at the time of summon) , seems it actually takes the base as a failsafe incase owner's snapshotted stamina falls below it, otherwise it is x0.2 always and doesn't take base.
AotD Ghoul's Base Agility:  (10.7 per level)
AotD Ghoul's Base Strength: (4.1375 per level)
AotD Ghoul AttackPower: -20
AotD Ghoul's Total AP : ( x1 of its own Agility ) + ( x1 of its own Strength ) + ( x0.065 of its Owner's Snapshotted AP at the time of summon ) -20.
AotD Ghoul's Crit : Same as a rogue
a Level80 Ghoul would benefit at the rate of 83.33 agility = 1% crit chance 
a Level80 AotD Ghoul would be (10.7x80) 856/83.33 = 10% Melee Crit Chance
AotD's Ghoul Melee Haste : x1 of its Owner's Melee Haste snapshotted at the time of summon.

With this we can try and calculate the white hits damage of a non crit/non glancing.
If Owner's AP is 5000 at the snapshot then 5000x0.065=325
So the Ghoul's AP would be 325+856(agi)+331(str) = 1512AP

Formula would then be
BaseDmg + ((BaseAttackSpeed)x(GhoulAP-20)) / 17.5
Min Damage = 30+((2)x(1512-20))/17.5 = 200.5142857143
Max Damage = 74+((2)x(1512-20))/17.5 = 244.5142857143
So this is the BEFORE ARMOR REDUCTION damage of a aotd ghoul that snapshotted 5000Owner'sAP x0.065

If we were to conduct this test on a boss with no armor reduction debuffs, the boss' armor should be 10643 (same as a heroic training dummy) we would end up with 
118.0396072417 minimum white hit nonglancing/noncrit
143.9417154139 maximum white hit nonglancing/noncrit

If we were to use wowsims with exactly 5000AP from owner and no trinkets or procs that increase ap, no raid buffs that increase AP or boss debuffs that decrease armor. 
we will end up with very similar results.
proving that the way it works as originally thought of is the same both wotlk classic and og wotlk, it has poor ap scaling and strong melee haste scaling.
![image](https://github.com/user-attachments/assets/1a93a947-24eb-437b-9cba-f936910dd5d4)
![image](https://github.com/user-attachments/assets/229ef135-fb18-4d02-842a-3824cb65c750)

Any further required info i will be happy to provide.

**How to reproduce:**

**How it should work:**

**Database links:**
http://web.archive.org/web/20100810004935/http://elitistjerks.com/f72/t42606-pet_discussion_garg_aotd_ghoul/p5/#post1144739

**Comment by Manpower99** [comment]
@Afgann i see you were the primary dev in charge of fixing AotD, that is why i'm tagging you.

**Comment by Manpower99** [comment]
Seems to have been completely broken after today's update, please take a look i will be happy to co-operate to fix this issue.

**Comment by Riztazz** [comment]
Last tick should be fixed by another commit now

**Comment by Manpower99** [comment]
> Last tick should be fixed by another commit now

I believe it has yeah.

**Comment by Riztazz** [comment]
I've seen @Afgann push something, could you test this issue once again? It seems to be fixed

**Comment by Manpower99** [comment]
> I've seen @Afgann push something a while ago, could you test this issue once again? It seems to be fixed

Yup works
