### ISSUE TITLE
[PALADIN] [OG Wolk Bug] Judgements of the Just Extra SoR Proc

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1382]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** There was a bug present from 3.2 - til the end of wrath, and was never fixed, but was acknowledged, so it's up to you if you wanna replicate it or not. It was clearly stated by blizz, that it was UNINTENDED behavior, but they never actually came to fix it.

With Judgements of the Just talent, Seal of RIghteousness proced to the JotJ debuff as well as to the Judgement of RIghteousness itself, resulting in 2 times seal dmg, instead of the intended 1.

**How to reproduce:** Cast any judgement with SoR and JotJ talented, and see the result.

**How it should work:** This is a tough one: if we're aiming for blizzlike, it should proc twice, if not, it shouldn't. Just putting it here, it's up to you if you want it to work or not.

**Database links:** https://www.wowhead.com/wotlk/spell=53696/judgements-of-the-just       

https://www.wowhead.com/wotlk/spell=20187/judgement-of-righteousness

https://www.wowhead.com/wotlk/spell=21084/seal-of-righteousness

https://web.archive.org/web/20100505023450/http://elitistjerks.com/f76/t68951-retribution_updated_3_3_a/#Seals

SoR judgements:
Judging SoR results in a double SoR proc, widely documented.
Hotfixed (stealth): Judging SoR triggers a single SoR proc as of 8/11. Still double procs with JotJ as prot.

Source: [http://elitistjerks.com/f76/t68951-retribution_updated_3_3_a/#Seals#ixzz0n1Uf0OVb](https://web.archive.org/web/20100505023450mp_/http://elitistjerks.com/f76/t68951-retribution_updated_3_3_a/#Seals#ixzz0n1Uf0OVb)

**Comment by Piootrek** [comment]
Hello. After internal discussion, we've decided that we won't implement this bug.

**Comment by haephaistoss** [comment]
It's better this way honestly, totally fair 🫡
