### ISSUE TITLE
Patchwerk patrol pattern

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1383]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Patchwerk currently does not pause his patrolling once he's at the destination right infront of the Froggers.
https://youtu.be/DH1-Qt-dLg0?si=CeygGWTuch-HvxAg&t=3672
Timestamped video you can see Patchwerk stays at that specific spot for a set amount of time before he continues to patrol, on Frostmourne-Whitemane he does not pause and constantly patrols causing pull timers to be rushed.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Godmatik** [comment]
Confirmed

**Comment by Manpower99** [comment]
@PanJanuszek Hey, thanks for the quick fix but i noticed that the Location where he "stops" is incorrect atm, he currently stops in the middle of the froggers, the timestamped video i linked show it to be different.
https://youtu.be/DH1-Qt-dLg0?si=CeygGWTuch-HvxAg&t=3672
