### ISSUE TITLE
Unable to resurrect cross faction after releasing spirit 

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1384]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
If a party member from the opposite faction dies and releases spirit, they cannot be resurrected by clicking on their corpse.
This issue is quite important in **arenas.** 

It seems to be working fine if they do not use release spirit button.

**How to reproduce:**
Group with a player of opposite factions, take classes with resurrection ability. 

**How it should work:**
Even if the player releases spirit, one should be able to cast resurrect and click on their corpse to revive them.

**Comment by UltraNix** [comment]
Fixed.
