### ISSUE TITLE
[Shaman] Spirit wolves do not put Shaman in combat

### ISSUE THREAD

**Issue by Brylezor** [gamefreedomgit/Frostmourne#1385]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Sending and dealing dmg with the spirit wolves will not put the shaman in combat state.

**How to reproduce:**
create a shaman with points in spirit wolves, summon them and make them attack any target, check combat state for shaman

**How it should work:**
as soon as the spirit wolves deal dmg to a target it should put the shaman in combat and keep him in combat until the wolves disappear or they do not hit the target for 8 seconds (or how ever the combat is meant to be dropped)

**Database links:**

**Comment by Piootrek** [comment]
Fixed
