### ISSUE TITLE
{shaman] Hexed targets still able to use some abilities

### ISSUE THREAD

**Issue by Brylezor** [gamefreedomgit/Frostmourne#1386]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Hexing a target such as another shaman will allow the shaman to keep dropping totems while in a hex state, this is equal to being able to put totems while in fear/polymorphed and should not happen.

**How to reproduce:**
have a shaman hex another shaman player, once becoming hexed the hexed shaman uses any totem he wants as if he is not in a cc.

**How it should work:**
While under Hex, the target can only use abilities that will free the user from the hex, such as ice block from mages, divine shield from pala, and pvp trinkets.

**Database links:**

**Comment by Chaos-within** [comment]
Casting totems while hexed is not a bug

**Comment by reminuz** [comment]
> Casting totems while hexed is not a bug
> 
> https://www.youtube.com/watch?v=xFQnTdWl0Qc&t=1566s


Same with divine sacrifice and trinkets.

**Comment by Chaos-within** [comment]
> Same with divine sacrifice and trinkets.

Depending on the trinket; [Patch 3.3.0] (2009-12-08): Players are no longer able to use Battlemaster trinkets while under the effects of this spell.

https://wowpedia.fandom.com/wiki/Hex

**Comment by UltraNix** [comment]
As above - not a bug.
