### ISSUE TITLE
Icy Prism Loot table

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1388]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Similarly to https://github.com/gamefreedomgit/Frostmourne/issues/1172
Opened two icy prisms in a row and got no gems.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
