### ISSUE TITLE
MasterLooter and Professions

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1389]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Being in group where master looter is enabled causes issues with looting things that normally shouldn't be.

Examples :
Disassembling and skinning won't let the engineer or skinner loot
Mining and Herbing wont let the Miner or herbalist loot the ores/herbs

The only players who should have access to these loots is the Herbalist/Skinner/Engineer/Miner, thus masterlooting shouldnt affect them.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by yeagerca** [comment]
Were you in a Master Loot group when the Icy Prism bug occurred too? #1388 
This bug could pertain to all objects or containers.

**Comment by Manpower99** [comment]
> Were you in a Master Loot group when the Icy Prism bug occurred too? #1388 This bug could pertain to all objects or containers.

No i actually was not in a group at all in the icy prism bug report.

**Comment by Nightw4re** [comment]
this is even worst, if you are in a group with master looter and you will open box of saronite bombs, you will lost box and nothing looted.

**Comment by Manpower99** [comment]
> this is even worst, if you are in a group with master looter and you will open box of saronite bombs, you will lost box and nothing looted.


@UltraNix  unsuspecting players are suffering out of this, it seems it is also affecting containers.

**Comment by Piootrek** [comment]
Fixed
