### ISSUE TITLE
Ulduar PTR - pre-Mimiron trash packs

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#1391]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
A couple of minions in the hallway that leads to Mimiron transport have incorrect stealth and invisibility detection.
This applies to both 10, 25man and all difficulties.

Names of mobs:
Trash : incorrectly has stealth & invis detection
Arachnopod Destroyer : incorrectly has stealth & invis detection
Boomer XP-500 : incorrectly has stealth & invis detection

Clockwork sapper is the only one who should have detection ( and he does as well)

**How to reproduce:**
stealth next to said mobs, observe eye detection animation above their head

**How it should work:**
https://www.youtube.com/watch?v=PZEONR7sqDU
video from classic showing how the mobs should behave and their lack of detections

**Database links:**

**Comment by Afgann** [comment]
fixed
