### ISSUE TITLE
Taunt diminishing

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#1392]
**Description:**
The raid mechanics of Taunt Diminishing does not work. You can use taunt indefinitely on all bosses.

In WotLK Classic, the following bosses were immune to provocation. Sapphiron, Patchwerk, Death Knight Understudy. The Non-diminishing category included bosses such as: Instructor Razuviy, Feugen, Stalagg, Four Horsemen, this was due to their mechanics of automatically changing targets or constantly maintaining the taunt effect on the boss, using the example of Instructor Razuviy. 

All other bosses in NAXX + OS + EYE fell into the diminishing category. In general, this is a global mechanic and it should be on most bosses including Ulduar, TOGC, ICC, RS. You can make a global fix, give a taunt with diminishing, and where there should be immunity, just add it to a certain boss. As a rule, there are very few such bosses (exceptions) in the game in the WOTLK content.

**How it should work:**
The evidence can be seen here on my videos, I specifically ran around testing Immunity to taunts, Taunt diminishing and its absence. 

Maexxna - Diminishing
https://youtu.be/fUh-dCZ1ZrA?t=880 

Loatheb - Diminishing
https://youtu.be/fUh-dCZ1ZrA?t=1680 

Grobbulus - Diminishing
https://youtu.be/fUh-dCZ1ZrA?t=2504 

Gluth - Diminishing
https://youtu.be/fUh-dCZ1ZrA?t=2650  

Thaddius - Diminishing 
https://youtu.be/fUh-dCZ1ZrA?t=3200

Death Knight Understudy -  Imun
https://youtu.be/fUh-dCZ1ZrA?t=3625

Gothik the Harvester - Diminishing
https://youtu.be/fUh-dCZ1ZrA?t=4088 

Sapphiron - Imun
https://youtu.be/fUh-dCZ1ZrA?t=4708

Kel'Thuzad - Diminishing 
https://youtu.be/fUh-dCZ1ZrA?t=6015 

Noth the Plaguebringer - Dimishing
![image (30)](https://github.com/user-attachments/assets/f8870dd9-78bc-45eb-9084-7345852fc80c)

Anub'Rekhan - Diminishing
![image (28)](https://github.com/user-attachments/assets/d9bac2ed-17d7-4782-aef8-2c944a361f14)

Grand Widow Faerlina - Diminishind
![image (29)](https://github.com/user-attachments/assets/3d3969c2-3618-4af0-ac8e-d06d8d9be6d8)

Heigan the Unclean - Dimishing, I remember testing it out in a separate video, but it was deleted.

Malygos - Diminishing
https://youtu.be/awhprNToKfQ?si=WwvSkd2SY6PITQRI

OS - Sarth + mini boss - Diminishing
https://youtu.be/lEA_F9xxd2Q?t=416
https://youtu.be/lEA_F9xxd2Q?t=733

**Database links:**
Link to the list of bosses in NAXX
https://www.wowhead.com/wotlk/zone=3456/naxxramas
https://www.wowhead.com/wotlk/npc=28860/sartharion
https://www.wowhead.com/wotlk/npc=30449/vesperon
https://www.wowhead.com/wotlk/npc=30452/tenebron
https://www.wowhead.com/wotlk/npc=30451/shadron
https://www.wowhead.com/wotlk/npc=28859/malygos

**Comment by Manpower99** [comment]
Thi is True, however do keep in mind that this server's custom debuffs that are being applied to some bosses such as sapphiron, are put in place for players to run a second tank and do a taunt swap.
Now obviously the custom debuffs are neither blizzlike nor is the vast majority of bosses having no DR on taunt, so you should consider removing the custom debuffs in order for the sapphiron bossfight to become blizzlike (excluding the boosted damage on the frost aura and melee damage taken), or keep sapphiron off the taunt immunity. by blizzlike standards he should be immune yes but if you do fix his taunt immunity then this debuff will simply destroy tanks in pugs.
Imo the debuff should just be removed since its neither enjoyable nor blizzlike and just make him taunt immune so we play Sapphiron Bossfight like its intended where a tank death is basically a wipe unless a second tank manages to build enough threat fast enough ( which is unlikely anyway ).

**Comment by Manpower99** [comment]
The custom debuff im mentioning is : 

> Stomp - 20k physical damage, also puts debuff for 10 sec decreasing target's armor by 50%. Casts every 10 seconds vs ~ This is additional ability in our boosted Naxxramas. 

Both Thaddius and Sapphiron are using these abilities.

**Comment by wowclassic1234** [comment]
> Both Thaddius and Sapphiron are using this ability.

Thaddeus is not dangerous, after receiving full diminishing, the tank can use def cooldown, and live on it without problems while debuff is active and diminishing is taking place. Unfortunately, it will not work on sapphiron. I was thinking about it when I wrote this topic.

**Comment by Manpower99** [comment]
> > Both Thaddius and Sapphiron are using this ability.
> 
> Thaddius is not dangerous, after receiving full diminishing, the tank can use def cooldown, and live on it without problems while debuff is active and diminishing is taking place. Unfortunately, it will not work on sapphiron. I was thinking about it when I wrote this topic.

Don't misunderstand im not disagreeing with your bug report, you are correct on the subject of taunts but the custom debuff was designed under the fact that sapphirons is (bugged tho )tauntable. if these get adressed so should sapphiron.

**Comment by wowclassic1234** [comment]
> Don't misunderstand im not disagreeing with your bug report, you are correct on the subject of taunts but the custom debuff was designed under the fact that sapphirons is (bugged tho )tauntable. if these get adressed so should sapphiron.

I didn't write anything about sapphiron, I just noticed that if you give a sapphire immunity to taunt. will complicate it too much, maybe it will make its passage impossible. I agree with you here and have nothing against it. 

I wrote about Thadius above, but I will write again.
If giving Thadius the mechanics of diminishing , will complicate the fight just a little bit, because I play for two tanks and I know that using Def cooldown you can ignore the custom Debuff. But in any case Game developers will check it themselves and do what they think is right.

**Comment by RadeghostWM** [comment]
In that case it should be disabled as it directly collides with the fix

**Comment by Riztazz** [comment]
@RadeghostWM what about Thaddius?:P

**Comment by Riztazz** [comment]
Fixed, will close once it's live

**Comment by RadeghostWM** [comment]
The same IMO, we can remove the mechanic if we can't adjust it

**Comment by LezChap** [comment]
Loatheb's damage and/or anti-healing debuff probably will need to be adjusted.  The server strat (I'm aware of) thus far has been to ping-pong him with taunts to minimize tank damage, because even mitigation tanks were having trouble not dying over the duration of the anti-healing debuff with the damage he did, especially on 10 Ascended.  With the Taunt DRs being re-implimented/fixed, the current strat to work around the massive damage will no longer work for Loatheb.

**Comment by Manpower99** [comment]
Is there a specific reason why this got reverted despite the ample proof of it being a thing?

> [Patch 3.3.0](https://wowpedia.fandom.com/wiki/Patch_3.3.0) (2009-12-08): Taunt Diminishing Returns: We've revised the system for diminishing returns on Taunt so that creatures do not become immune to Taunt until after 5 Taunts have landed. The duration of the Taunt effect will be reduced by 35% instead of 50% for each taunt landed. In addition, most creatures in the world will not be affected by Taunt diminishing returns at all. Creatures will only have Taunt diminishing returns if they have been specifically flagged for that behavior based on the design of a given encounter.
