### ISSUE TITLE
[Quest] Steamtank Surprise (Dragonblight)

### ISSUE THREAD

**Issue by Torises** [gamefreedomgit/Frostmourne#1393]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Use an Alliance Steam Tank to destroy 6 Plague Wagons and deliver the 7th legion elites.

**How to reproduce:**
Quest its undoable right now due to being dismount as soon you try to ride the tanks.

**How it should work:**
You should be able to use a tank all the time you're on the quest.

**Database links:**
https://www.wowhead.com/wotlk/quest=12326/steamtank-surprise

PROOF:

https://www.youtube.com/watch?v=qLYAKWdRt-Q

**Comment by PanJanuszek** [comment]
**cannot reproduce, works as should**

![image](https://github.com/user-attachments/assets/c5dff215-fcfe-44e4-86d6-c04c353b5bf5)
