### ISSUE TITLE
Patchwerk Hateful strike threat generation

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1394]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
https://www.wowhead.com/wotlk/npc=16028/patchwerk#comments:id=552113
comment in wowhead that references a elitistjerk thread explaining how hatefuls work, claim that the candidates get bonus threat generation.
if we were to look at some classic and og videos we could confirm this to be a thing. they are TOWERING over everyone in threat.
https://www.youtube.com/watch?v=a-0IM9UwuT8 (og)
https://www.youtube.com/watch?v=fUh-dCZ1ZrA&t=2142s (classic 1.5mil threat at end)
https://www.youtube.com/watch?v=08deqJvaB9c&t=517s (classic 2mil threat at end)

you can see the tank has alot of threat at the end of the fight, in a much shorter fight than this server due to classic having less hp so less lengthy boss fights. (about 02:35 sec)
while on this server the threat generated/boosted by it is either non existant or low. as pala tanks can barely get to 1mil threat by 2minute bossfight length. 
https://www.youtube.com/live/m0bcvNGQMg0?si=woct75_s4ugTFIIc&t=314
while it is expected that threat is improved by externals, proper spell usage and gear, the massive difference is noticable (about 50% more total threat at the end) and considering patchwerk has been properly fixed to be taunt immune now, this should be fixed also.

This is one of the reasons why on classic most speedrunners used 2 tanks in speedkills instead of 3, because the threat boost was sufficient that only the offtank would be taking hatefuls(due to him having way higher hp and threat than whichever melee dps is third on threat)
while if you were to check every log in whitemane its always 3 tanks and 2 offtanks being hateful soakers due to this mechanic not existing.

https://classic.warcraftlogs.com/reports/mPHgb43QaLkTdtRV#fight=12&type=damage-taken&ability=59192
https://classic.warcraftlogs.com/reports/PgZkMKwtbJLCQczT#fight=41&type=damage-taken&ability=59192

While i cannot confirm if it boosts their threat by damage done or just adds a flat amount/percentage, it is likely leaning towards just adding flat amount of threat everytime a hateful is used.
https://www.mmo-champion.com/threads/638077-Patchwerk-s-hateful?p=6093340&viewfull=1#post6093340
explanation of another elitistjerks thread referenced here. so far the best explanation of how hateful strike works

[The 40MAN version of patchwerk wowpedia ](https://wowpedia.fandom.com/wiki/Patchwerk_(Classic))page also claims this threat increase:

> Hateful Strike - Base damage is 22100-29900 physical damage, thankfully this is mitigated through high AC. The average hit is ~8000 damage on a fully buffed BWL/AQ40 geared Warrior in defensive stance. From Elitist Jerks' website: "There are only three viable targets for hateful strike, and these are the three people 2nd, 3rd, and 4th on his aggro list within melee range. Hateful strike will hit the highest HP person out of those 3. Additionally, hateful strike will add threat to the target it hits, which helps keep these tanks on that hateful strike list. This is the reason where if your 3 hateful tanks are low hp, Patchwerk would still hateful one of them and kill them, disregarding the fact that there were melee dps with higher HP. It is possible for the tanks to fall out of the top four if the melee dps push very large amounts of threat, which can lead to a melee dps taking hateful strike. Sinking your melee into the slime doesn't help anyone, it's just stupid and you should quit doing it."

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Manpower99** [comment]
@UltraNix as requested.

**Comment by UltraNix** [comment]
@Manpower99 I have a question about it:
Let's say - on 10 man we have main-tank and off-tank. Off-tank is not in melee range, but is 2nd on threat list. So we have two candidates: main tank and some melee DPS, right? And boss can hit with Hateful Strike even on DPS. And now what about threat generation? Main-tank and that DPS got threat increased or maybe off-tank instead of melee DPS?

**Comment by Manpower99** [comment]
@UltraNix Sorry it took long to answer i was trying to see whatever info i can gather on this.

Since some guides mention you'd have to be hit by Hateful Strike and some guides mention that its all the candidates of hateful strike get a threat boost and sadly the full elitistjerks thread does not seem to be archived we would have to rely on Vanilla/WotLK Classic videos to figure out how it actually works since it does work properly there.
Proof leans towards that if you were to be a candidate by hateful strike (top3 25man/top2 10man) you do get bonus flat amount of threat each time it is used, how much threat exactly is unclear but i will do some estimation.

https://www.youtube.com/watch?v=1SOOJ73c4CU This is a 25man Naxxramas video from retail which indicates the flat threat increase seems to be working still, the mage who isnt casting anything is getting a threat increase (on omen addon).
the amount of threat given isnt reliable since retail changed alot of values relating to hp/dmg taken/threat/avoidance etc.

When he uses it actually adds threat to everyone currently in the top 3 in 25M, 2 for 10M on the threat-list.
This is 100% confirmed now. Just watch threat meters during the fights.

As for your question regarding range, It should give it to the DPS since the Offtank is not within melee range and thus not a candidate for the time being, it would make no sense for it to be given to ranged/casters/healers when they will never be considered candidates for the hateful strike, unless they are within melee range.

My estimations on how it works in wotlk is like this :
15K threat divided equally among top three melee targets in the threat list everytime a hateful strike is cast in 25Man.
10K threat divided equally among top two melee targets in the threat list everytime a hateful strike is cast in 10Man.
the threat should be given regardless of it being avoided or not.

**Comment by UltraNix** [comment]
Thanks for the info.
These 10/15k are definitely too big numbers. I will try with something smaller.

**Comment by Manpower99** [comment]
Perhaps you're right they are mostly estimations from how many hatefuls were casted and how much total threat was at the end.
The minimum i can estimate is 3250 per target
3250x3 on 25man
3250x2 on 10Man
Considering on 2-3min bossfights tanks end up on 2.5+ million threat it doesnt seem so ridiculous, i'll get back at you after it gets applied to live and logs are available

**Comment by UltraNix** [comment]
@Manpower99 Let me know (once you fight again with Patchwerk) if current value is enough.

**Comment by Manpower99** [comment]
@UltraNix 
So far it is definitely sufficient to keep Tanks ahead in threat. i'm very glad it was added along with the taunt changes as it has already caught most guilds off-guard this lock-out reset lol.

Something to note though, i strongly believe that the "Aggro Affinity" mechanic is not working, noticed it during a patchwerk pull.
Its essentially a way for whoever initially had aggro to stay primary on aggro list or gain it back quickly.
I.e if you pulled the mob, and someone else takes aggro away from you, you only need to reach 100% of that person’s threat to steal it back (as opposed to the 110% for melee range and 130% for outside melee range).

**Comment by UltraNix** [comment]
@Manpower99 Yes please - a new report.
This one is resolved.
