### ISSUE TITLE
[NPC] Aludane Whitecloud is oversized

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1395]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Dalaran flight master Aludane Whitecloud is currently oversized (ruining immersion).

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by PanJanuszek** [comment]
compared with cata base, checked client files, looks good 

![image](https://github.com/user-attachments/assets/e65fb8e6-9078-4cf5-a5c9-80e2a3023a67)

Closing

**Comment by Chaos-within** [comment]
@PanJanuszek 
![image](https://github.com/user-attachments/assets/5e9a86b6-699a-4c56-b5ff-30f84996894c)

**Comment by Godmatik** [comment]
was done on purpose i assume
