### ISSUE TITLE
[NPC] Hand of the Deceivers incorrect classification

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1396]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The 3 summoners infront of timewalking KJ inside Sunwell are incorrectly classified as Humanoids instead of Demons.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Godmatik** [comment]
https://www.wowhead.com/tbc/npc=25588/hand-of-the-deceiver

Not a bug, they are indeed humanoids.

**Comment by Chaos-within** [comment]
https://www.wowhead.com/wotlk/npc=25588/hand-of-the-deceiver#comments:id=525413

**Comment by Godmatik** [comment]
That comment you linked said they are humanoids?
