### ISSUE TITLE
[25n Ulduar PTR] 17/07/24

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1399]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
**Trash:**
[Clockwork Sapper](https://wowpedia.fandom.com/wiki/Clockwork_Sapper) does not seem to be casting [explosion](https://wotlk.evowow.com/?spell=64873) upon death.
https://youtu.be/ZNug8WdjPds?si=voOKgkgcfKQ--Bsn&t=1469

https://github.com/gamefreedomgit/Frostmourne/issues/1391 the same issue reported here happened to us as well.

**25n Thorim**
 1. [Dark Rune Champion](https://wowpedia.fandom.com/wiki/Dark_Rune_Champion) Should not be disarm-immune on ANY mode.
If we were to use frosthold's [tuning post](https://archive.ph/6WwGI), then they should still be disarmable but it does not affect their whirlwind damage on 10hc/25hc.

 2. Thorim's Hitbox seems to be smaller than it should be, in this [video ](https://www.youtube.com/watch?v=EoYM-iI0paE)you can see they can hit him from further than his model
 
 3. Thorim should end the encounter at 2% HP not at 0%, then he does his Roleplay before dropping combat and giving loot. https://www.youtube.com/watch?v=Vr_1Si5zayU

**25n Hodir**

 1. Issue probably affects every mode, [Starlight ](https://www.wowhead.com/wotlk/spell=62807/starlight)radius is EXTREMELY small it should be 5 Yards from the moonlight gameobject

**25n Mimiron**

 1. I made this [bug report ](https://github.com/gamefreedomgit/Frostmourne/issues/1379)from a PTR run i did yesterday but the bug is unadressed so.

 3. Phase4 it seems our casters were hitting only the Head, however that same threat was snapping to the Bottom part also, which caused finicky aggro and eventually loss of aggro  to the casters themselves who are not even hitting the Bottom part.

 5. Rocket Strike on 25n should be post nerf thus take longer time to land( about a second longer).

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
