### ISSUE TITLE
Cloth drops - Mobs with two different sets of cloth in their drop table can drop them both

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#140]
Bug that has been around for a while in old private servers - mobs that have two different types of cloth in their drop table are able to drop both.

So for example Galak Scout can drop Wool Cloth or Silk Cloth. When killing one it can currently drop one of each. It should only be able to drop the Wool Cloth or Silk Cloth, but not both

**Comment by Afgann** [comment]
fixed
