### ISSUE TITLE
Gluth Decimate

### ISSUE THREAD

**Issue by query-wow** [gamefreedomgit/Frostmourne#1400]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Decimate kills you if you're below the threshold. The damage also stacks with the damage increase debuff of the Zombies
![image](https://github.com/user-attachments/assets/da327769-8886-4920-91e2-aca9f71f77f6)

**How to reproduce:**

**How it should work:**
It should only reduce you to 5% health, if you have less than that it doesn't affect you. Also doesn't stack with damage increase mods. It's a flat % damage taken buff

**Database links:**

**Comment by Afgann** [comment]
fixed
