### ISSUE TITLE
DE greens giving x2 of a blue enchanting material

### ISSUE THREAD

**Issue by niama1618** [gamefreedomgit/Frostmourne#1401]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Disenchanting greens should only give x1 of a dream shard with a small chance.

**How to reproduce:**
Disenchant green items

**How it should work:**
Disenchanting greens should only give x1 of a dream shard with a small chance.

**Database links:**
https://imgur.com/a/0uRRFbH
https://www.wowhead.com/wotlk/item=36036/condor-sandals#disenchanting

**Comment by Afgann** [comment]
fixed
