### ISSUE TITLE
Sigil swapping should give 1.5 second global cooldown and reset autoattack timer

### ISSUE THREAD

**Issue by danniellos94** [gamefreedomgit/Frostmourne#1402]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Currently I don't have any cooldown after swapping sigils. Also you should not be able to have 2 buffs from different sigils I remember trying to snapshot virulence sigil buff and hanged man on classic it was not possible the second buff was deleting the first.

**How to reproduce:**
Swap sigils.

**How it should work:**
Sigil swapping should give 1.5 second global cooldown and reset autoattack timer.

**Database links:**
for example https://www.mmo-champion.com/threads/666619-Swapping-sigils-mid-rotation but there are more proofs in the internet if you dig out

**Comment by Manpower99** [comment]
Sigil/Ranged weapon slot should indeed give a gcd and reset swing timers

**Comment by haephaistoss** [comment]
> Sigil/Ranged weapon slot should indeed give a gcd and reset swing timers

They should reset GCD - so if you use a macro like

/cast spell
/equip wep
/equip shield
/equip relic

It all has to happen in 1 GCD, beacuse spell cast triggers GCD, others are just refreshing it, but since it happens at the same time no extra GCD.

**Comment by Manpower99** [comment]
Not sure theres a difference to begin with consider they all happen simulatenously, but regardless it should be fixed.

**Comment by haephaistoss** [comment]
Title should be made more generic, not only sigil swapping should have this behavior but all wep slots

**Comment by BalanCV** [comment]
There is a difference.
If you cast a spell (gives 1.5 gcd) then you wait for that general gcd to reach 0.5sec and swap sigil it would remain 0.5sec not reset to 1.5
Swapping sigil should only trigger gcd fully 1.5 if any gcd was not already triggered before sigil swap happened.

**Comment by scrublama** [comment]
weapon swap and sigil swap is already giving gcd, in combat! 
obviously not in no combat if thats why you trying

**Comment by danniellos94** [comment]
They give gcd in combat but you can use spell and swap sigil in a macro and have 1 GCD. About swing timer I didn't check it to be honest.
"those macros would still trigger 2 gcds gcd so id be 3 secs per macro"

**Comment by haephaistoss** [comment]
> They give gcd in combat but you can use spell and swap sigil in a macro and have 1 GCD. About swing timer I didn't check it to be honest. "those macros would still trigger 2 gcds gcd so id be 3 secs per macro" "Just tested it. It triggers the GCD twice, HOWEVER it's not two full GCDs. The two actions happen in sequence, and you get about .5 seconds of GCD from the attack and 1.5 from the swap."

How they work currently is how they should work.

Spell + wep swap is how it has always worked... You can go and test it on Cata Classic or whichever version you want. 

TO Quote myself again:

But swapping weapon slots has to be possible regardless of GCD state, it merely restarts it.

They should reset GCD, not give one, big difference. - so if you use a macro like

/cast spell
/equip wep
/equip shield
/equip relic

It all has to happen in 1 GCD, beacuse spell cast triggers GCD, others are just refreshing it, but since it happens at the same time no extra GCD. - it still works like this on retail, classic, whichever.

And @Manpower99 this is the difference between restarting, and giving.

**Comment by danniellos94** [comment]
> > They give gcd in combat but you can use spell and swap sigil in a macro and have 1 GCD. About swing timer I didn't check it to be honest. "those macros would still trigger 2 gcds gcd so id be 3 secs per macro" "Just tested it. It triggers the GCD twice, HOWEVER it's not two full GCDs. The two actions happen in sequence, and you get about .5 seconds of GCD from the attack and 1.5 from the swap."
> 
> How they work currently is how they should work.
> 
> Spell + wep swap is how it has always worked... You can go and test it on Cata Classic or whichever version you want.
> 
> TO Quote myself again:
> 
> But swapping weapon slots has to be possible regardless of GCD state, it merely restarts it.
> 
> They should reset GCD, not give one, big difference. - so if you use a macro like
> 
> /cast spell /equip wep /equip shield /equip relic
> 
> It all has to happen in 1 GCD, beacuse spell cast triggers GCD, others are just refreshing it, but since it happens at the same time no extra GCD. - it still works like this on retail, classic, whichever.
> 
> Just tested it in Cata CLassic, Cata Classic PTR, Retail WoW, Retail PTR... Half of high lvl pvpers would be fucked if this was true, weapon dancing is the most important thing to master playing as certain classes
> 
> Also another case of a random forum post from 1 source is false information. MMO champion is like facebook comment section in terms of accuracy
> 
> And @Manpower99 this is the difference between restarting, and giving.

So I just tested it and it's definitely too fast on this server, on cata when I use spell + swap sigil there is an gcd and then gcd backs for about 0.5 sec and start again here it doesn't.
https://www.youtube.com/watch?v=LXEa7bzHFuc&feature=youtu.be cata classic
https://www.youtube.com/watch?v=ZIihQBRuD-I ptr whitemane

**Comment by haephaistoss** [comment]
that's BS, it should be instant and within 1 click, and gcd.

It all comes down to your latency to blizz servers

**Comment by haephaistoss** [comment]
you are manually equipping it, ofc you're slow 😅

It has to be in a macro to be instant

**Comment by danniellos94** [comment]
I did that the same way in classic than on whitemane and you can see visible difference.
