### ISSUE TITLE
Essence-Infused Moonstone dissappeared after first use

### ISSUE THREAD

**Issue by bl2x14** [gamefreedomgit/Frostmourne#1403]
Did the druid Swift Flight Form quest chain the other day, summoned Anzu right after.
Next day I was missing the Moonstone when tried to summon the boss, like it's a one time use item only, simply dissappeared.

**How it should work:**
It should stay on the keyring forever.

**Comment by PanJanuszek** [comment]
Don't you have this item in bag?
https://www.wowhead.com/item=32462

It may be there

**Comment by bl2x14** [comment]
Just as I said, I already summoned the boss once, meaning I opened that bag and got the Moonstone and Arthorn's Research (which I dropped because it has no use).

**Comment by WhitemaneChronus** [comment]
Player was missing the last quest on chain [Eternal Vigilance](https://www.wowhead.com/wotlk/quest=11011/eternal-vigilance)

remember that [Vanquish the Raven God](https://www.wowhead.com/wotlk/quest=11001/vanquish-the-raven-god) provides you with an one time use item and swift flight form but you need to finish [Eternal Vigilance](https://www.wowhead.com/wotlk/quest=11011/eternal-vigilance) to get [Essence-Infused Moonstone](https://www.wowhead.com/wotlk/item=32449/essence-infused-moonstone)

**Comment by bl2x14** [comment]
The boss is also bugged: while in "banished" form still casting Paralyzing Screech.
![WoWScrnShot_072024_133954](https://github.com/user-attachments/assets/3470753e-1a01-4be9-863e-6d4cb9df453f)
![WoWScrnShot_072024_134003](https://github.com/user-attachments/assets/290ce9fb-a9c4-4af1-83bc-6616c3fab41e)

**Comment by bl2x14** [comment]
The boss is casting 'Paralyzing Screech' again while banished as of 24/07/24.

![WoWScrnShot_072424_090324](https://github.com/user-attachments/assets/767464ad-fcbb-4797-84f5-c89fd2f57df9)

**Comment by PanJanuszek** [comment]
I think there was no update yet.
