### ISSUE TITLE
Staff Head of Atiesh displaying as a Sun-Lute Head

### ISSUE THREAD

**Issue by Dalvae** [gamefreedomgit/Frostmourne#1404]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** We went to a 10ascend and Kelthuzad drop a Sun Lute head, I already have the sun lute completed so there is no need for Kelthuzad to drop the head. We have on the raid a mage thats was on the questline, trying to get the staff but in the body we saw the sun lute head. And when the master looter saw that he give it to me, and it transform into a Staff head of Atiesh as you can see on the right uper corners of my bags

**How to reproduce:** Maybe is related to having a paladin or a warrior master looter or having two person one with the atiesh staff questline and another with the sun lute complete

**How it should work:**
It should display the Staff Head of Atiesh, and the Head of the staff is dropped from killjaedan not naxxramas

**Database links:**
![WoWScrnShot_071824_010731](https://github.com/user-attachments/assets/47b854b6-c3d6-4025-b01c-d7cb82fce4ed)

I do have to pointed out, the terrible support we recive of the gms. Its not our fault that this quest is bugged, and they try to say that they can turn my head staff into a sun lute head, when already did the quest, we just want to pass this item to the mage, so simple.

**Comment by UltraNix** [comment]
#1351
