### ISSUE TITLE
[QUEST] The Light of Dawn

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1405]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Multiple issues here:

1. During the battle Darion's buff isn't applied to players in a large enough vicinity, thus making them die constantly, and unable to fight.
2. During the cutscene at the end when Darion charges to Arthas, he has nothing in his hand - but does the animation. He should be having Corrupted Ashbringer.
3. After Darion tosses Corrupted Ashbringer to Darion, there is no model that is flying to him, and Tirion has Corrupted Ashbringer model on him during the rest of the cutscene. He should have cleansed CA-thus making it Ashbringer again - and the model on him should represent that.

https://youtu.be/e_oyXSSFAL0?t=200

**How to reproduce:** 

**How it should work:**

**Database links:** https://www.wowhead.com/wotlk/quest=12801/the-light-of-dawn

https://www.wowhead.com/wotlk/spell=58361/the-might-of-mograine

**Comment by PanJanuszek** [comment]
1. Has 150yrd range which is ok
2.  it has 

3. it is
![image](https://github.com/user-attachments/assets/9ed35ec1-fcb5-4214-83a0-edf65e389469)

fixed making Ashbringer without corruption

**Comment by PanJanuszek** [comment]
1. It's 150yrd so works as aura is designed. Even being 100yrd away is so far.
![image](https://github.com/user-attachments/assets/a22ffe1d-ce85-49e0-b7c7-6b0e4268bb55)
2. It has
![image](https://github.com/user-attachments/assets/cb012195-4870-4e8a-942c-6276ababacfc)
3. It is
![image](https://github.com/user-attachments/assets/2c40cef2-44ea-4646-bdf0-07c75128e323)
Fixed cleansing of Ashbringer
![image](https://github.com/user-attachments/assets/bd7251ae-bc07-49d3-afac-c0def52e1121)
