### ISSUE TITLE
SWD not breaking CC with pws up

### ISSUE THREAD

**Issue by debugger12313** [gamefreedomgit/Frostmourne#1407]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Shadow word: death should break CC that breaks on damage. But right now it doesnt if either divine aegis or power word: shield is up. This is not the way it should work because if u get hit during a CC with shield up it breaks

**How to reproduce:**
Try SWD before a blind with and without power word: shield (pws) up.

Then try to get blinded with and without power word: shield and see if it breaks or not.

**How it should work:**
SWD SHOULD BREAK BLIND WITH AND WITHOUT SHIELDS

**Database links:**
https://www.youtube.com/watch?v=QXbnix-kr4s&ab_channel=Hydramist

**Comment by haephaistoss** [comment]
It is possibly linked to "Friendly" dmg not breaking CC-s when absorbed - since the caster and the target here are the same. Similar to this one:

https://github.com/gamefreedomgit/Frostmourne/issues/1369

**Comment by debugger12313** [comment]
Ok but fix it. This is not how it has worked ever ever ever

**Comment by debugger12313** [comment]
Absorbed damage = damage. It should break the CC, no further questions needed.

**Comment by haephaistoss** [comment]
Not all the time, but in terms of CC-s taht break on dmg, yes, your statement holds.

**Comment by debugger12313** [comment]
Ok so when should it NOT break from damage then?

**Comment by Chaos-within** [comment]
https://www.youtube.com/watch?v=EwLOcI4h_kg&t=187s

SW:D poly with PW:S active at 3:!5

**Comment by haephaistoss** [comment]
> Ok so when should it NOT break from damage then?

In terms of CC that breaks on dmg - all the time. It should even be calculated into the 20 % Base HP threshold of fear effects.

But in terms of procing stuff like Overpower from Rend dmg, Mana restore from judgements of the wise, Unholy Blight from Dk, absorbed dmg doesn't count - because blizz logic.

**Comment by debugger12313** [comment]
Its not blizz logic though. The mechanic as is is broken

**Comment by haephaistoss** [comment]
While we were at it, I did a quick test, and voila, Fear effects are fucked too

https://github.com/gamefreedomgit/Frostmourne/issues/1408

**Comment by yeagerca** [comment]
> **Database links:** https://www.youtube.com/watch?v=QXbnix-kr4s&ab_channel=Hydramist

Provide a time stamp of this interaction occurring.


Quoting myself from report #1369 :
> On Frostmourne, when a spell is fully absorbed, such as during Divine Shield, it is entered into the combat log as SPELL_MISSED.

If devs want to implement CC-breaks through absorbs, they should implement the combat log event "[SPELL_ABSORBED](https://wowpedia.fandom.com/wiki/COMBAT_LOG_EVENT#SPELL_ABSORBED)" which is a subevent that can fire in addition to the SPELL_MISSED event.

When was this combat log event implemented on retail?
September 1, 2019: The [earliest edit mentioning this event on warcraft.wiki.gg](https://warcraft.wiki.gg/index.php?title=COMBAT_LOG_EVENT&oldid=3823372).
November 29, 2014: A [Reddit thread](https://www.reddit.com/r/wow/comments/2nsbxu/recount_unknown_combat_log_event_type_spell/) that mentions it.
October 14, 2014: A [git-blame in Details Damage Meter](https://github.com/Tercioo/Details-Damage-Meter/blame/a5b1fd424c13b827de3ccc6637b9227a67233ab3/core/parser.lua#L5001) mentioning 6.0.2 pre-patch.

**Comment by haephaistoss** [comment]
https://youtu.be/EwLOcI4h_kg?t=194

As @Chaos-within linked from an actual Wotlk video.

It can be clearly seen, Poly being cast, he's spamming SHW:D Poly finished, poly applied, SHW:D absorbed on mage (didn't penetrate Ice Barrier, but dmg was still registered, nor did it kill the mage -> backlash dmg), backlash from absorbed dmg was absorbed by priest's own PW:S, Poly was broken.

My job here isn't to develop the game or combat log events, it is to tell devs how stuff should work, and what's not working as it should, the rest is up to them.

**Comment by haephaistoss** [comment]
In my testing it works fine if enemy hits you, Poly breaks on enemy DMG, it doesn't break on "friendly" dmg, prolly because it isn't registered as part of the original hit, rather as friendly fire, or whatnot

See:

![image](https://github.com/user-attachments/assets/fc9099f3-6dfc-4680-b369-a6932dddbf34)


![image](https://github.com/user-attachments/assets/2dbb8ef1-6dea-4345-9650-a8771e715f2f)

**Comment by yeagerca** [comment]
Great job finding that some work and some don't but I think "friendly" damage is a misdirection. The distinction appears to be in SPELL_MISSED versus SPELL_PERIODIC_MISSED combat log events.

Test 1, Power Word: Death
Result: SPELL_PERIODIC_MISSED did not break Polymorph through an unbroken shield.
```
7/18 18:34:39.842  SPELL_CAST_SUCCESS,0x0000000000006C81,"Derosia",0x511,0x0000000000006C81,"Derosia",0x511,48066,"Power Word: Shield",0x2
7/18 18:34:39.842  SPELL_AURA_APPLIED,0x0000000000006C81,"Derosia",0x511,0x0000000000006C81,"Derosia",0x511,48066,"Power Word: Shield",0x2,BUFF
7/18 18:34:43.556  SPELL_CAST_START,0x0000000000006C82,"Polydeath",0x10548,0x0000000000000000,nil,0x80000000,12826,"Polymorph",0x40
7/18 18:34:45.123  SPELL_CAST_SUCCESS,0x0000000000006C81,"Derosia",0x511,0x0000000000006C82,"Polydeath",0x10548,48158,"Shadow Word: Death",0x20
7/18 18:34:45.224  SPELL_DAMAGE,0x0000000000006C81,"Derosia",0x511,0x0000000000006C82,"Polydeath",0x10548,48158,"Shadow Word: Death",0x20,767,0,32,0,0,0,nil,nil,nil
7/18 18:34:45.224  SPELL_AURA_APPLIED,0x0000000000006C82,"Polydeath",0x10548,0x0000000000006C81,"Derosia",0x511,12826,"Polymorph",0x40,DEBUFF
7/18 18:34:45.224  SPELL_AURA_APPLIED,0x0000000000000000,nil,0x80000000,0x0000000000006C81,"Derosia",0x511,32409,"Shadow Word: Death",0x20,DEBUFF
7/18 18:34:46.207  SPELL_PERIODIC_MISSED,0x0000000000000000,nil,0x80000000,0x0000000000006C81,"Derosia",0x511,32409,"Shadow Word: Death",0x20,ABSORB,767
7/18 18:34:46.207  SPELL_AURA_REMOVED,0x0000000000000000,nil,0x80000000,0x0000000000006C81,"Derosia",0x511,32409,"Shadow Word: Death",0x20,DEBUFF
7/18 18:34:55.224  SPELL_AURA_REMOVED,0x0000000000006C82,"Polydeath",0x10548,0x0000000000006C81,"Derosia",0x511,12826,"Polymorph",0x40,DEBUFF
```

Test 2, Fireball damage over time effect
Result: SPELL_PERIODIC_MISSED did not did not break Polymorph through an unbroken shield.
```
7/18 18:45:48.801  SPELL_CAST_SUCCESS,0x0000000000006C81,"Derosia",0x511,0x0000000000006C81,"Derosia",0x511,48066,"Power Word: Shield",0x2
7/18 18:45:48.801  SPELL_AURA_APPLIED,0x0000000000006C81,"Derosia",0x511,0x0000000000006C81,"Derosia",0x511,48066,"Power Word: Shield",0x2,BUFF
7/18 18:45:50.614  SPELL_CAST_START,0x0000000000006C82,"Polydeath",0x10548,0x0000000000000000,nil,0x80000000,3140,"Fireball",0x4
7/18 18:45:53.794  SPELL_MISSED,0x0000000000006C82,"Polydeath",0x10548,0x0000000000006C81,"Derosia",0x511,3140,"Fireball",0x4,ABSORB,103
7/18 18:45:53.794  SPELL_AURA_APPLIED,0x0000000000006C82,"Polydeath",0x10548,0x0000000000006C81,"Derosia",0x511,3140,"Fireball",0x4,DEBUFF
7/18 18:45:53.992  SPELL_CAST_START,0x0000000000006C82,"Polydeath",0x10548,0x0000000000000000,nil,0x80000000,12826,"Polymorph",0x40
7/18 18:45:55.616  SPELL_AURA_APPLIED,0x0000000000006C82,"Polydeath",0x10548,0x0000000000006C81,"Derosia",0x511,12826,"Polymorph",0x40,DEBUFF
7/18 18:45:55.785  SPELL_PERIODIC_MISSED,0x0000000000006C82,"Polydeath",0x10548,0x0000000000006C81,"Derosia",0x511,3140,"Fireball",0x4,ABSORB,3
7/18 18:45:57.814  SPELL_PERIODIC_MISSED,0x0000000000006C82,"Polydeath",0x10548,0x0000000000006C81,"Derosia",0x511,3140,"Fireball",0x4,ABSORB,3
7/18 18:45:59.784  SPELL_PERIODIC_MISSED,0x0000000000006C82,"Polydeath",0x10548,0x0000000000006C81,"Derosia",0x511,3140,"Fireball",0x4,ABSORB,3
7/18 18:46:01.785  SPELL_PERIODIC_MISSED,0x0000000000006C82,"Polydeath",0x10548,0x0000000000006C81,"Derosia",0x511,3140,"Fireball",0x4,ABSORB,3
7/18 18:46:01.785  SPELL_AURA_REMOVED,0x0000000000006C82,"Polydeath",0x10548,0x0000000000006C81,"Derosia",0x511,3140,"Fireball",0x4,DEBUFF
7/18 18:46:05.618  SPELL_AURA_REMOVED,0x0000000000006C82,"Polydeath",0x10548,0x0000000000006C81,"Derosia",0x511,12826,"Polymorph",0x40,DEBUFF
```

Test 3, Fireball initial hit
Result: SPELL_MISSED broke Polymorph through an unbroken shield.
```
7/18 18:47:37.256  SPELL_CAST_SUCCESS,0x0000000000006C81,"Derosia",0x511,0x0000000000006C81,"Derosia",0x511,48066,"Power Word: Shield",0x2
7/18 18:47:37.256  SPELL_AURA_APPLIED,0x0000000000006C81,"Derosia",0x511,0x0000000000006C81,"Derosia",0x511,48066,"Power Word: Shield",0x2,BUFF
7/18 18:47:38.386  SPELL_CAST_START,0x0000000000006C82,"Polydeath",0x10548,0x0000000000000000,nil,0x80000000,12826,"Polymorph",0x40
7/18 18:47:40.047  SPELL_AURA_APPLIED,0x0000000000006C82,"Polydeath",0x10548,0x0000000000006C81,"Derosia",0x511,12826,"Polymorph",0x40,DEBUFF
7/18 18:47:40.114  SPELL_CAST_START,0x0000000000006C82,"Polydeath",0x10548,0x0000000000000000,nil,0x80000000,3140,"Fireball",0x4
7/18 18:47:43.314  SPELL_MISSED,0x0000000000006C82,"Polydeath",0x10548,0x0000000000006C81,"Derosia",0x511,3140,"Fireball",0x4,ABSORB,110
7/18 18:47:43.314  SPELL_AURA_REMOVED,0x0000000000006C82,"Polydeath",0x10548,0x0000000000006C81,"Derosia",0x511,12826,"Polymorph",0x40,DEBUFF
7/18 18:47:43.314  SPELL_AURA_APPLIED,0x0000000000006C82,"Polydeath",0x10548,0x0000000000006C81,"Derosia",0x511,3140,"Fireball",0x4,DEBUFF
7/18 18:47:45.306  SPELL_PERIODIC_MISSED,0x0000000000006C82,"Polydeath",0x10548,0x0000000000006C81,"Derosia",0x511,3140,"Fireball",0x4,ABSORB,3
7/18 18:47:47.307  SPELL_PERIODIC_MISSED,0x0000000000006C82,"Polydeath",0x548,0x0000000000006C81,"Derosia",0x511,3140,"Fireball",0x4,ABSORB,3
7/18 18:47:49.306  SPELL_PERIODIC_MISSED,0x0000000000006C82,"Polydeath",0x548,0x0000000000006C81,"Derosia",0x511,3140,"Fireball",0x4,ABSORB,3
7/18 18:47:51.306  SPELL_PERIODIC_MISSED,0x0000000000006C82,"Polydeath",0x548,0x0000000000006C81,"Derosia",0x511,3140,"Fireball",0x4,ABSORB,3
7/18 18:47:51.306  SPELL_AURA_REMOVED,0x0000000000006C82,"Polydeath",0x548,0x0000000000006C81,"Derosia",0x511,3140,"Fireball",0x4,DEBUFF
```

**Comment by scrublama** [comment]
There are macros for SW:D in combination with cancelaura: divine aegis and power word: shield for a reason, it shouldn't break poly if your shield is intact

**Comment by haephaistoss** [comment]
That is simply Bs.

Watch retail video I linked and explain what happened then...

**Comment by scrublama** [comment]
same logic applies to ret pala judgement, it only gives mana if its a damaging attack that breaks shield, if it doesnt break a shield and is completly absorbed you wont get mana return
![image](https://github.com/user-attachments/assets/16ac07de-be79-48a7-ad85-dc1e7b07bb27)

**Comment by haephaistoss** [comment]
let's say you're right (which you aren't), but still no explanation as to what happened to hydra in the video?

You have 2 options: 

1 heartbeat resist
2 DMG from absorb does break ccs

1: HR didn't start ticking until -25% of the ccs duration remaining, and is also very unlikely, so no, that's not what we're looking for here.

2: Bingo, you won

**Comment by Riztazz** [comment]
Fixed, will be applied to a server in a few days
