### ISSUE TITLE
[CORE] Fear DMG Threshold Numbers Are Off, Also Absorb Doesn't Get Taken Into Account

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1408]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**  
Fear Breaking threshold numbers feel off and 
Currently Fear effects don't take absorbed dmg into account for breaking.

Currently this is how it works:

![image](https://github.com/user-attachments/assets/0168c1a1-eecc-4b65-9d64-cb1999cb80d9)

**How to reproduce:** Cast Fear, or Phsychic scream, or Scare Beast onto any player, or player controlled target (pets) and deal dmg to them that is greater than 40 % of their Base HP.

**How it should work:**  Fear effects should break if the affected target takes more than (40%-1) of their Base HP (HP without ANY stamina, only from lvls) in dmg. Absorbed DMG should count too, in terms of CC, there is no distinction between absorbed, and non-absorbed dmg.

Class Base health value 40% of Base HP
Death Knight 8121 3248
Druid 7417 2967
Hunter 7324 2930
Mage 6963 2785
Paladin 6934 2774
Priest 6960 2784
Rogue 7604 3042
Shaman 6960 2784
Warlock 7164 2866
Warrior 8121 3248

Also the dmg threshold numbers seem off, on a lvl 80 Priest 2.2k dmg broke fear, even though it shouldn't have broken it at all, 2784 dmg should have

**Database links:**

**Comment by haephaistoss** [comment]
Probably it is using an older formula with 10 % max hp. 

Possible workaround is using 10 % max hp formula til it's lower and 40 % base hp after max HP in s7 becomes larger.

**Comment by haephaistoss** [comment]
Also IIRC, previous version (10% max hp) didn't take absorbed dmg into account just like it is now, but when it was changed to 40 % base hp, it started counting it into the threshold.

**Comment by Riztazz** [comment]
Can i get some proof on the 40%? I can't find anything on the internet

**Comment by Riztazz** [comment]
absorbed damage:
```
Spells which have an effect broken by taking damage past a threshold (Spell nature stranglevines [[Entangling Roots]](https://wowpedia.fandom.com/wiki/Entangling_Roots), Spell shadow possession [[Fear]](https://wowpedia.fandom.com/wiki/Fear), Spell frost frostnova [[Frost Nova]](https://wowpedia.fandom.com/wiki/Frost_Nova), etc.) now count damage that was prevented by damage absorbs or other damage reducing effects.
```

And this comes from patch 4.3 https://wowpedia.fandom.com/wiki/Patch_4.3.0

**Comment by haephaistoss** [comment]
> absorbed damage:
> 
> ```
> Spells which have an effect broken by taking damage past a threshold (Spell nature stranglevines [[Entangling Roots]](https://wowpedia.fandom.com/wiki/Entangling_Roots), Spell shadow possession [[Fear]](https://wowpedia.fandom.com/wiki/Fear), Spell frost frostnova [[Frost Nova]](https://wowpedia.fandom.com/wiki/Frost_Nova), etc.) now count damage that was prevented by damage absorbs or other damage reducing effects.
> ```
> 
> And this comes from patch 4.3 https://wowpedia.fandom.com/wiki/Patch_4.3.0

IIRC, these notes are sometimes put out to reflect stuff that was known previously and never documented as a change.

CC-s that break on dmg, and CCs that break on a dmgthreshold are essentially the same thing, with the only difference being the amount of dmg they can take before breaking.

For instance: ccs that break on dmg require dmg to be greater or equal than 0 -> look at my report in absorbed dmg splitting into absorb

Others have a set amount of dmg, tied to some function.

**Comment by Riztazz** [comment]
That's almost entire expansion in-between, i don't buy this.
I agree with the 40% of base HP, as some sources confirm this, mostly:
https://www.mmo-champion.com/threads/711283-The-History-of-Fear?p=7706112&viewfull=1#post7706112
and early cata PvP posts also mention it being based on base HP

**Comment by Riztazz** [comment]
Fixed, will close once it's live
