### ISSUE TITLE
BLOCK not working

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#1409]
Guys, this is not funny anymore.

**Description:**
The Block mechanics are not working correctly. The block has stopped blocking damage from NPC abilities, for example, the Hateful Strike ability has stopped blocking. Cleave, which uses Sapphiron/The Sartarion also stopped blocking. Melee abilities used by NPCs in 5 ppl dungeons have also stopped being blocked.  At the same time, the usual automatic attacks are blocked correctly. It is unrealistic for shield bearers to play.

Running through dungeons and raids, I notice that many abilities (most likely even all abilities) of ordinary NPCs And bosses that deal weapon damage are not blocked. The problem is the mechanics of blocking 100%. I don't think that all these abilities have somehow begun to work incorrectly.
![image (31)](https://github.com/user-attachments/assets/d1c74974-5bfa-4b9b-a517-81014c2f0b6d)
![image (32)](https://github.com/user-attachments/assets/8fb41894-6276-474a-954e-1540c05446d7)
![image (33)](https://github.com/user-attachments/assets/6f35719f-5432-4558-9e01-5539ab9692b6)

**How it should work:**
The block must block damage from melee and ranged combat abilities inflicted from weapons.  Everything is simple here.

**Database links:**
https://www.wowhead.com/wotlk/spell=107/block

Links to abilities that I take damage from through the block.
https://www.wowhead.com/wotlk/spell=42746/cleave
https://www.wowhead.com/wotlk/spell=55703/cobra-strike

**Comment by wowclassic1234** [comment]
Here is another screenshot for example, I have Block activated, the chance to block an attack is 130%, the block indicator is 5k, the boss uses Whirlwind causing me 9k damage, of which zero is blocked.
![image (34)](https://github.com/user-attachments/assets/d266920d-f2cd-437b-8a68-d61fcd3f98d6)

**Comment by UltraNix** [comment]
Fixed.
