### ISSUE TITLE
[Quest] The Light of Dawn

### ISSUE THREAD

**Issue by Savageferret** [gamefreedomgit/Frostmourne#141]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
[The Light of Dawn](https://www.wowhead.com/wotlk/quest=12801/the-light-of-dawn) and subsequent quests should give you the [The Might of Mograine](https://www.wowhead.com/wotlk/spell=53642/the-might-of-mograine) buff. Right now, only "The Battle For The Ebon Hold" is giving the buff

**How it should work:**
https://www.wowhead.com/wotlk/spell=53642/the-might-of-mograine should be applied to player during The Light of Dawn battle

**Database links:**
https://wowpedia.fandom.com/wiki/The_Might_of_Mograine
https://www.wowhead.com/wotlk/spell=53642/the-might-of-mograine#comments:id=614156
https://youtu.be/43wEFWNu3r0?si=NbADmE6SxDzrwQ8S&t=2831 (buff in top right)

**Comment by UltraNix** [comment]
The buff is casted right before the main event started.
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/e8f266e3-ff4d-485a-a859-75c8607d8422)
