### ISSUE TITLE
Custom Whitemane Legendary Axe is working in arena

### ISSUE THREAD

**Issue by Moonlxght69** [gamefreedomgit/Frostmourne#1410]
Currently on Frostmourne the Legendary Axe is working in arena it was told at start that custom legendaries will be disabled in arena because it will cause game unbalance, but atm people are able to use it
https://clips.twitch.tv/PluckyStupidMetalEleGiggle-c1VYfI20tR_tRSfi

On top of that the proc rate is completly broken, it has no icd proc rate is way too high sometimes its even 1ppsec as u can see in that clip 
https://cdn.discordapp.com/attachments/1096820651639193716/1263296674462437487/Blinkstrike.mp4?ex=669b09b6&is=6699b836&hm=3abb1a6cc885fb87f203ae9e58ca56f81eed23a5be7d23ee8659e67fd7f588c2&
Blinkstrike proc'd 5 times in 5 seconds

**Comment by haephaistoss** [comment]
All legendaries should be disabled in arena, with their many flaws, old At had this right

**Comment by UltraNix** [comment]
Fixed.
