### ISSUE TITLE
Bag with Legendary

### ISSUE THREAD

**Issue by irinasvarichevskaya** [gamefreedomgit/Frostmourne#1411]
![screen](https://github.com/user-attachments/assets/d656fbc9-f3b8-4131-9ab4-56e52ecb0a47)
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I killed C'tun, but didn't get Base of Atiesh. You asked for evidence of murder.
To prove the kill, I have a quest item with C'tun and the achievement received last night.

**How to reproduce:**

**How it should work:**

**Database links:**
![screen](https://github.com/user-attachments/assets/83d15916-081a-47d7-aaba-f97546bdb926)
![screen2](https://github.com/user-attachments/assets/907642f0-64c0-4341-93aa-ecea87538c6e)

**Comment by Manpower99** [comment]
I believe on this server you get it by Killing Killjaeden instead.

**Comment by Manpower99** [comment]
Well GMs have been quite often incorrect on things, its not uncommon.
Copy pasted from discord:
Atiesh, Greatstaff of the Guardian: the staff of legends, obtainable by Druids, Priests, and Mages. This questline works exactly like it did in Classic WoW, with two exceptions: Warlocks cannot get it anymore, and [Head of Atiesh] drops from Kil'jaeden from Timewalking: Sunwell Plateau. Note: you won't need to be neutral with Brood of Nozdormu to complete this chain.  [Full Questline Guide](https://www.wowhead.com/classic/guide/wow-classic-atiesh-greatstaff-of-the-guardian-questchain)

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/1358
