### ISSUE TITLE
Weekend bonus Reputation bug

### ISSUE THREAD

**Issue by Mysubmarine** [gamefreedomgit/Frostmourne#1412]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When turning in the Kaluak Daily, I do not receive the correct amount of Rep as with the increase it should be 725, however it is only 500.

**How to reproduce:**
Turn in Daily during bonus weekend

**How it should work:**

**Database links:**

**Comment by WhitemaneChronus** [comment]
based on the reports and with players help:

- [Preparing for the Worst](https://www.wowhead.com/wotlk/quest=11945/preparing-for-the-worst)
- [Planning for the Future](https://www.wowhead.com/wotlk/quest=11960/planning-for-the-future)

are not considering the bonus weekend
however the 3rd one, [The Way to His Heart...](https://www.wowhead.com/wotlk/quest=11472/the-way-to-his-heart) is working properly (players gaining around 1500 reputation)

**Comment by Piootrek** [comment]
Fixed
