### ISSUE TITLE
Hidden ICD on equip from Libram of furious Blows

### ISSUE THREAD

**Issue by scrublama** [gamefreedomgit/Frostmourne#1413]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Equip Libram of Furious Blows and it doesn't proc until after 30sec (there is some invisible ICD)
It's not like this with any other librams I tested.
This is prebis libram and its really boring that I can't libram swap with this.

**How to reproduce:**
Equip some libram then swap to Libram of Furious Blows and notice it wont proc at all until after some time

**How it should work:**
Equip libram of furious blows and it should proc when you cast judgement, no hidden cd when equip

**Database links:**
https://wotlk.evowow.com/?item=37574

**Comment by PanJanuszek** [comment]
Where did you find info about ICD and fact that it should proc from start?

**Comment by scrublama** [comment]
only items with cooldowns should be put on cooldown when you equip them

**Comment by PanJanuszek** [comment]
I disagree:
https://www.mmo-champion.com/threads/634816-Switch-Libram-Macro
