### ISSUE TITLE
[CORE / PVP] Heartbeat Resist

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1415]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** in OG Wotlk (I don't know about classic) there was a mechanic called 'Heartbeat Resist'. It basically meant that certain CCs (mostly spammable ones) had a small but non 0 chance of breaking early randomly. I haven't seen this mechanic so far in my testing, but it may be implemented, so I'll just leave it here in case you wanna check it further.

**How to reproduce:** Well this is a though one, I recommend checking if such a thing even exists in the code :D

**How it should work:** Some will complain that in their experience of 15 years of private servering they have never seen this and that it was removed in tbc, that's why I collected a few instances from retail wotlk to prove them wrong.

Information is a bit scarce, but what seems to hold up is the following:

- THe chance to break early by HR is the combined chance of resistance + (100 % - actual hit chance against the target) + miss chance. (looking at https://github.com/gamefreedomgit/Frostmourne/issues/1332)
-Check happened at 25%, 50%, 75% of the duration of the CC applied
- In case the target has multiple auras that are capable of heartbeat resist, they are independent of each other, so if one breaks by HR, the other may still remain
- Both players and NPCs had this characteristic, but in PvP it was different.
- This mechanic works in conjunction with my previous report of Negative Hit chance and Miss Chance, as they both are taken into account when HR-ing. (For instance: Night Elf passive, or Divine Purpose on Paladins)
- Note that HR is different from chance to break randomly on DMG, it is independent of that mechanic.
- There was a base chance to HR, and everything else added to that, it could never ever be 0.

Spell(s) that are proven to be affected:

Fear effects (including TUrn Evil, Scare Beast, Intimidating Shout)
Charm effects (Succubbus)
Root effects (Druid for instance, triggered Root Effects: from, Nature's Grasp)
Polymorphs (Mage)
Banish Effects (Banish Warlock, Cyclone Druid)
Sap / Blind - Rogue
Freezing Trap (hunter - frost)

Effects that are unproven:

Repentance (being holy school)
Scatter shot - too short maybe?
Frost Nova (Need more research, memories are fuzzy here sry) - Water Elemental Freeze, Ice Barrier triggered Root

Stun effects are exception from this rule as far as we know - they usually have large CD, and shorter DUration and are not spammable.

This post is a work in progress, if you have anything to add, please do so

**Database links:**

https://www.warcraftmovies.com/movieview.php?id=164185   -> 7:55 -> gets polied, uses no trinket, takes no dmg, Poly breaks on its own randomly at 5ish seconds.

https://www.warcraftmovies.com/movieview.php?id=161533  -> 14:46 Poly again, breaking at around 50 %

https://www.warcraftmovies.com/movieview.php?id=136263 ->  18:15 Intimidating Shout breaks early randomly - has no trinket as can be clearly seen, takes no dmg, and IS can't be removed by anything else except for HoP, but that is clearly not applied.

https://www.warcraftmovies.com/movieview.php?id=133167 -> 7:15  Fear breaks randomly, no trinket, no dmg, warr / druid can't remove it (has no magic dispel)

**Comment by haephaistoss** [comment]
Also why I'm showing mostly Paladin videos? Simple:
In my time on retail people were pretty much hitcapped to the teeth at ratings above 2k, my personal highest was 2.8k in 2v2 in s6.
And no, I'm not talking about 5 % hit for melees and so on, we went to preferably above 6-7% just in  case - because https://github.com/gamefreedomgit/Frostmourne/issues/1332

There were only very few specs that had talents that couldn't be capped against, Ret being the strongest of them all, other being Frost Mage with Arctic Winds.

Nelf Racial could and should be possible to cap against as it is racial, not talent.

So Rets had an unusually high chance of HR-ing.

**Comment by Meaninglessx** [comment]
Heartbeat is a TBC mechanic not wrath 3.3.5

**Comment by Meaninglessx** [comment]
Beta Test Release Build 44043
August 10, 2022 
you can read in this post that Heartbeat resist is removed in wrath
https://www.bluetracker.gg/wow/topic/us-en/1267790-wrath-classic-beta-development-notes-updated-september-23/
it was only available in the early patches of the old retail and then got removed it never existed in 3.3.5 due to the huge rng that causes in high competitive arenas and since talents and spells on whitemane are 3.3.5 there's no need to add post 3.3.5 mechanics to the server

**Comment by haephaistoss** [comment]
I have included clips from s8, which is well past 3.3.x, so then what?

**Comment by haephaistoss** [comment]
> Beta Test Release Build 44043
> August 10, 2022 
> you can read in this post that Heartbeat resist is removed in wrath
> https://www.bluetracker.gg/wow/topic/us-en/1267790-wrath-classic-beta-development-notes-updated-september-23/
> it was only available in the early patches of the old retail and then got removed it never existed in 3.3.5 due to the huge rng that causes in high competitive arenas and since talents and spells on whitemane are 3.3.5 there's no need to add post 3.3.5 mechanics to the server 

"Heartbeat Resist mechanics have been removed from Arena.
Developer’s Note: There is a mechanic in place on Crowd Control effects that does a periodic check while a CC is active to see if the effect resists and ends early. In Wrath of the Lich King this check does not start to occur until several seconds into a CC’s duration, so in PvP Settings this had a relatively small chance to occur, but it was very impactful when it did. After receiving feedback on this mechanic over the course of Classic and Burning Crusade Classic, we’ve decided to make a small adjustment and completely remove this chance in Arena."

It was wotlk classic, so in og wotlk it was present all the way through

**Comment by haephaistoss** [comment]
3.3.5 has never ever been a "finished product", there were tons of stuff broken, bugged, or outright not working as intended, but cata was the priority so blizz didn't rly give a shit anymore.

What You linked is from wotlk classic which is 3.4, and what you are referring to is the part I copied which clearly states it was wotlk classic not og wotlk they are talking about.

Also I linked several videos from retail 3.3.5 feel free to watch them and tell us what is going on according to your investigation!

**Comment by BalanCV** [comment]
Heartbeat resists have been removed from pvp in early TBC patches, while for pve it lasted until early wrath patches. This does not matter, however, as both classic and private servers in general are replicating patch 3.3.5a, which 100% did not have heartbeat mechanic for either pvp nor pve.

There is no proof that those videos are 3.3.5, the upload date is irrelevant since they could have been filmed in any prior patch.
Honestly, even if you did find some kind of fringe proof and this change goes through, it would be so universally hated in practice that it would break speed record of the rest of your bugreports in being reverted.

**Comment by haephaistoss** [comment]
> Heartbeat resists have been removed from pvp in early TBC patches, while for pve it lasted until early wrath patches. This does not matter, however, as both classic and private servers in general are replicating patch 3.3.5a, which 100% did not have heartbeat mechanic for either pvp nor pve.
> 
> There is no proof that those videos are 3.3.5, the upload date is irrelevant since they could have been filmed in any prior patch.
> Honestly, even if you did find some kind of fringe proof and this change goes through, it would be so universally hated in practice that it would break speed record of the rest of your bugreports in being reverted.

I'm not here to argue about how *other private servers* work, I'm here to shed light on how stuff worked on retail wrath.

I know wrath players don't like actually playing wrath, it's hilarious.
Your idea of wrath is that of *other private servers* and that's not how stuff worked on retail.

A lot of stuff was *hated* by players, and they survived, and I bet there's still a lot to complain about, and there'll always be.

Wrathful gear to me seems a lot like 3.3.x, and unless you can dig up something that exclusively proves what you say is true, video evidence supports the statements I've made based on said video evidence - surprise. 

I'm fine with work classic stuff as long as it is consistent, and not because someone doesn't like the idea of not being stronger in certain situations than they should have ever been 🤷

**Comment by haephaistoss** [comment]
> Heartbeat resists have been removed from pvp in early TBC patches, while for pve it lasted until early wrath patches. This does not matter, however, as both classic and private servers in general are replicating patch 3.3.5a, which 100% did not have heartbeat mechanic for either pvp nor pve.
> 
> There is no proof that those videos are 3.3.5, the upload date is irrelevant since they could have been filmed in any prior patch.
> Honestly, even if you did find some kind of fringe proof and this change goes through, it would be so universally hated in practice that it would break speed record of the rest of your bugreports in being reverted.

Actually the blue post linked above proves it was present all the way through old wrath, so 🙏, I don't have to dig that one up at least.

**Comment by debugger12313** [comment]
Why would anyone want this?

**Comment by haephaistoss** [comment]
Why would you want SW:D to break Poly as it should with an absorb shield on you?
Because taht is how the game worked, and you wanna play the game as it was - the reason for every bugfix
And because statistically the game was balanced with everything in mind, including this mechanic - if it is not present the scales shift from where they are supposed to be, to somewhere else, and if you wanna shift them back, you gotta change something else, and in no time you'll end up playing a different game altogether

**Comment by debugger12313** [comment]
This is just annoying RNG for everyone involved. Keep it out of pvp and im ok with it

**Comment by haephaistoss** [comment]
Only fix bugs that affect you negatively I see, how convenient :D

**Comment by debugger12313** [comment]
Bugs and mechanics are two different things. This is not a good change, youre the only one thats vouching for it

**Comment by haephaistoss** [comment]
ppl generally are hypocritial especially when anonimity is on their side.
difference being, I'm not vouching for anything I'm simply telling devs how stuff worked in og wrath, that's it.
Most who come to my reports to cry about stuff have never played a single arena match in retail wrath, all their experience comes from probably crapmane and other low quality private servers, that's why it is scary for them to realize how stuff actually has to work, they have never seen it in 10ish years

**Comment by debugger12313** [comment]
"Developer’s Note: There is a mechanic in place on Crowd Control effects that does a periodic check while a CC is active to see if the effect resists and ends early. In Wrath of the Lich King this check does not start to occur until several seconds into a CC’s duration, so in PvP Settings this had a relatively small chance to occur, but it was very impactful when it did. After receiving feedback on this mechanic over the course of Classic and Burning Crusade Classic, we’ve decided to make a small adjustment and completely remove this chance in Arena."

Why did they remove it?

**Comment by haephaistoss** [comment]
because classic = og #nochanges
That's why some ppl who were peak back then didn't return, it's simply not the same game anymore
Classic is a different game 

Ask blizz why they removed it I'm not affiliated with them lol

**Comment by debugger12313** [comment]
The answer is in the text: 
"After receiving feedback on this mechanic over the course of Classic and Burning Crusade Classic, we’ve decided to make a small adjustment and completely remove this chance in Arena."

**Comment by haephaistoss** [comment]
it is classic, not wrath, so it's not a basis for anything here

**Comment by Moonlxght69** [comment]
u want #nochanges on a realm where u get bonus exp everyweek autolearn spells each level, leveling with bgs, whitemane+ where u can teleport to all flight paths instantly custom raid difficulty timewalking raids and much more changes, cmon bro

**Comment by haephaistoss** [comment]
I don't want anything
I just report stuff based on the instructions I was told to report stuff by

**Comment by debugger12313** [comment]
We appreciate that but no one wants heartbeat resist, atleast not in pvp

**Comment by haephaistoss** [comment]
if you asked ppl what they want you'd never have a game, they could never agree on anything

It's not a question of wanting, if it was in og wotlk it must exist on any replication of that 🤷

**Comment by debugger12313** [comment]
This is far from a blizzlike server

**Comment by haephaistoss** [comment]
and yet if we want any reasonable pvp, we wanna keep as close to blizzlike as we can.

Some QoL changes here and there are fine, but it holds inherent risk.

Most high lvl players want an Arenatournament that is pvp only without legendaries and fully blizzlike scripting, but since old at was bought by you know whom, and scrapped their core in favor of their shittier one, prolly this is our last hope

By today's Standards old at scripting would be trash too, but back then it was better than most other options.

**Comment by haephaistoss** [comment]
> This is far from a blizzlike server

then why do you wanna have something fixed based on evidence from blizz servers? 🤔

**Comment by debugger12313** [comment]
Adopt what is useful and disregard what is not useful  ( or something like that )

-bruce lee

**Comment by haephaistoss** [comment]
> Adopt what is useful and disregard what is not useful  ( or something like that )
> 
> -bruce lee

one man's trash is the treasure of another 

-

common saying

**Comment by bandini9** [comment]
Just putting my 5 cent here, while I remember Heartbeat mechanc exists, It was on vanilla, not sure wotlk, could be but not sure.

**Comment by UltraNix** [comment]
We decided to this only on PvE.
PvP will be not affected by this.

**Comment by UltraNix** [comment]
Fixed.
