### ISSUE TITLE
[Jewelcrafting] having 2 sets with 3 dragon's eye gem per set causes the bug you have the maximum number of those gems socketed into equipped items

### ISSUE THREAD

**Issue by Cure-whitemane** [gamefreedomgit/Frostmourne#1417]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

I have 2 wearing sets. Each set has 3 dragon's eye gems. There is no similarity in sets: each set contains its own items.

When wearing either of 2 sets it says `You have the maximum number of those gems socketed into equipped items` and not wearing 1 item. Then I can manually wear this last item and have 3 dragon's eye gems on myself.

![image](https://github.com/user-attachments/assets/f581609e-11ef-4eb3-9e91-5887d2bd210f)

**How to reproduce:**

1. Be jewelcrafter
2. Create 2 wearing sets
3. Set 3 gems per set
4. Equip it

**How it should work:**

We should be able to wear 3 dragon's eye gems per set independently. 

I can also probably do the screen recording if needed. But now I will provide the equipment screens in the following comments.

We can also connect through Discord and I can do screen sharing - discord ID is `lucky139191`

**Comment by Cure-whitemane** [comment]
First set:

3 gems:

- 2 belt
- 1 legs

And while wearing the set I am not wearing the legs, but getting the error. But once I wear the set with the equipment manager I am able to replace the past legs with no dragon's eye gem with the new - with dragon's eye gem.

![image](https://github.com/user-attachments/assets/c260a320-3bad-40c7-bf15-6151ca13ece6)
![image](https://github.com/user-attachments/assets/9fcb72d9-54ac-49a6-bda5-84bad4ad5a5c)
![image](https://github.com/user-attachments/assets/14db4300-04aa-4e3d-b227-7d2a3bcc3025)

**Comment by Cure-whitemane** [comment]
The second set

3 dragon's eye gems:

- shoulder
- hands
- belt

The same happens here: I cannot wear automatically shoulders, but then I am able to replace them with the ones, that contains dragon's eye gem

![image](https://github.com/user-attachments/assets/b2536393-2f26-4fc9-bcb4-137061004fb9)
![image](https://github.com/user-attachments/assets/a012b1c6-5206-4ff2-9823-196233383796)
![image](https://github.com/user-attachments/assets/9219cfb3-124b-4ff1-81e4-347eef44d1eb)
![image](https://github.com/user-attachments/assets/b90a31ab-3f49-4165-8d29-92ec5386bfa3)

**Comment by yeagerca** [comment]
Does attempting to equip Set 2 multiple times correctly equip all items?

**Comment by Moonlxght69** [comment]
Press the button for Equip set twice and it should be working fine, it will change the first piece on the list and then the second one

**Comment by Cure-whitemane** [comment]
@yeagerca @Moonlxght69 yeah, pressing 2 times works as expected. Thank you for the hint!

**Comment by Cure-whitemane** [comment]
So is it a bug or it is not?

**Comment by yeagerca** [comment]
Probably not a bug. The algorithm could be changed to calculate unique-equipped items before attempting to equip them, but that change may introduce new problems. I think its best to leave it how it is.

**Comment by Cure-whitemane** [comment]
> Probably not a bug. The algorithm could be changed to calculate unique-equipped items before attempting to equip them, but that change may introduce new problems. I think its best to leave it how it is.

gotcha, ty. So just double click equip and that's it, right? xD

**Comment by Dalvae** [comment]
Yes, the client tries to equip all items procedurally, which causes errors when you have jewelcrafting gems. One workaround is to place the jewelcrafting gems in the same slot as the other equipped items. Another workaround is to press the equip button twice. This issue has always existed.
