### ISSUE TITLE
Terokk's Divine Shield isn't being dispelled properly

### ISSUE THREAD

**Issue by IpLucKI** [gamefreedomgit/Frostmourne#1418]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
NPC called Terokk has a Divine Shield ability when he reaches 25% HP. That Divine Shield can only be dispelled by a special blue flare which is dropped at a location on the platform. That interaction doesn't work properly because the Divine Shield isn't dispelled when Terokk is standing on the blue flare

**How to reproduce:**
Get Terokk to 25% HP, while he has the Divine Shield spell on him move him to the blue flare and just wait until the flare expires and the Divine Shield still remains on Terokk

**How it should work:**
The Divine Shield should be dispelled when Terokk is standing on the blue flare

**Database links:**

**Comment by WhitemaneChronus** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/1067

**Comment by PanJanuszek** [comment]
![image](https://github.com/user-attachments/assets/64de1491-a06d-460a-b83b-2a8e5ac29d8a)
