### ISSUE TITLE
[DK] Anti-Magic Shell Energize Coeff Wrong

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1422]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** AMS energize coeff currently is 0.02 RP / magic dmg absorbed, it should be 0.0125

![image](https://github.com/user-attachments/assets/09701d41-49de-4a01-a4cd-a1192e8d4e93)

**How to reproduce:** Cast anything onto a DK in AMS and check RP generated

**How it should work:** It should be 0.125f, instead of 0.2f

Ams energizing coefficient is wrong, currently it seems to be 0.2f should be 0.125f

// https://www.youtube.com/watch?v=BYK6OkFwbv8 -> around 6:30 you can see he uses AMS, absorbs quite a few things and his energy bar doesn't get filled up fully.

From HP and gear we can assume it was close to wotlk ending, so S8 WF, also we can assume he has the + 30 max RP talent, because PvP gear gives + 5 RP from chains of ice, and his RP bar fills up upon casting CoI less than 1/6th, which would be roughly the amount if he had PvP gear and 100 RP. Also it was a common talent at the time.
Which means in WF gear he didn't get 130 RP full in 7 seconds (note he's running the glyph).

Side note: in my testing from 6k dmg which is 1 noncrit spell in wf gear, I got 118 RP on PTR - Whitemane

//http://www.worldoflogs.com/reports/up5rno2y5w0lta6h/xe/?x=spell+%3D+%22Anti-Magic+Shell%22+or+%28targetname+in+%28%22Razielz%22%2C+%22Mca%22%29+and+sourcereaction+%3D+REACTION_HOSTILE+and+absorbed+%21%3D+0%29

THe log is from an ICC Dragon boss from retail wotlk, with worldoflogs gone it may be gone forever... we used it to fix this very thing on another server long ago.

It is wrong in every public mangos or trinitycore build afaik.

Also funny thing is, it is literally a fixed number, not even a ratio of % hp dmg absorbed or anything - so it means it is gonna energize more and more as the xpansion progresses, as dmg-es tend to increase. Same in PvP and PvE

**Database links:** https://www.wowhead.com/wotlk/spell=48707/anti-magic-shell#taught-by-npc

**Comment by UltraNix** [comment]
Fixed.
