### ISSUE TITLE
Loot Threshold not working under Master Looter

### ISSUE THREAD

**Issue by LezChap** [gamefreedomgit/Frostmourne#1423]
While under Master Looter, the Master Looter should only be responsible for loot at or above the Loot Threshold (Common/Rare/Epic/etc).  Items below the loot threshold should be lootable by any member of the raid, each corpse being distributed in a "round robin" fashion (if the player opens the corpse and leaves it, it becomes free for all).

Right now, ALL loot is distributed by the Master Looter, and the loot threshold is being ignored, resulting in many things (greys for vendoring, cloth, potions) to remain on corpses and unable to be looted unless the Master Looter wastes their time to distribute them.

Please allow loot under the Loot Threshold to be picked up by members of the raid.

**Comment by Afgann** [comment]
fixed
