### ISSUE TITLE
[DK] Desolation 

### ISSUE THREAD

**Issue by Miguelsanx** [gamefreedomgit/Frostmourne#1424]
**Description:**
Blood strike has a minimal chance of not proc Desolation 

**How to reproduce:**
It's difficult to reproduce since it only happens 2 out of 100 times, but I'll attach a Twitch clip where it occurs

**How it should work:**
Desolation is a talent in the Unholy tree for Death Knights, giving the Death Knight a 5% increase in all damage each time the player casts Blood Strike.

**Database links:**
https://www.twitch.tv/gono12x/clip/WildWildJellyfishPunchTrees-wjav6sMk5BLPx14v?filter=clips&range=7d&sort=time. At 0:15 seconds
https://imgur.com/a/CPoG2We
https://www.wowhead.com/wotlk/spell=66817/desolation

**Comment by Miguelsanx** [comment]
Another clip when it happen https://clips.twitch.tv/EasyDifficultTubersBrokeBack-iAfff1mLlvLlE4FO

**Comment by Manpower99** [comment]
Yeah it still happens ( both ptr and live )

**Comment by Miguelsanx** [comment]
another clip https://clips.twitch.tv/FitFitEmuPogChamp-xm92PJGYyXAcEELp

**Comment by Miguelsanx** [comment]
when gonna fix that its so annoying 
https://clips.twitch.tv/FriendlyCheerfulKittenPeoplesChamp-dWVY312ZhwCqP5tP

**Comment by Manpower99** [comment]
yeah i dont get it either its legit been happening for so long..

**Comment by Riztazz** [comment]
Any chance someone could try reproducing this outside of raid environment? I can't even reproduce it once so i don't know what to fix :(

**Comment by Manpower99** [comment]
> Any chance someone could try reproducing this outside of raid environment? I can't even reproduce it once so i don't know what to fix :( I want to exclude it is not some stacking issue

Issue is that it is SUPER random when it happens, the bloodstrike is not missed, not blocked, not parried and dodged either.
and yet the desolation buff isnt applied.
it happened there in his recorded vod not sure how to reproduce it lol

**Comment by Riztazz** [comment]
Yeah i understand, i've been spamming blood strike for an hour and each applied desolation. I'll think of code to replicate the buffs he had and check then, my only guess at the moment is some stacking rule disallowing application of the aura.
The request still stands, if someone has some time and want to test it on a dummy and manages to reproduce it on a dummy, please let me know

**Comment by Riztazz** [comment]
Ok, i have found the issue, testing the fix and pushing, will close once it's fixed
