### ISSUE TITLE
[PTR] Sack of Ulduar Spoils emblems

### ISSUE THREAD

**Issue by yeagerca** [gamefreedomgit/Frostmourne#1426]
**Description:**
Sack of Ulduar Spoils and Large Sack of Ulduar Spoils award Emblem of Heroism instead of Emblem of Conquest. The other loot (gold, orbs, and recipes) and number of emblems is accurate.

**How to reproduce:**
Spawn and loot the bags:
`.add 45875` 
`.add 45878` 

**How it should work:**
These sacks should award Emblems of Conquest.

**Database links:**
https://www.wowhead.com/wotlk/item=45875/sack-of-ulduar-spoils#comments:id=5590493
https://www.wowhead.com/wotlk/item=45878/large-sack-of-ulduar-spoils#comments:id=758705

**Comment by Afgann** [comment]
fixed
