### ISSUE TITLE
[PTR] Kologarn Stone Grip vs Hunter Disengage

### ISSUE THREAD

**Issue by yeagerca** [gamefreedomgit/Frostmourne#1427]
**Description:**
When Kologarn uses Stone Grip on a hunter that is flying due to Disengage, the hunter will be released from Stone Grip at the bottom of Kologarn's pit and instantly die.

**How to reproduce:**
A hunter must Disengage immediately before Kologarn targets them with Stone Grip, then be broken out of the Stone Grip from sufficient damage (or survive the duration, maybe).

**How it should work:**
When Kologarn drops players they should return to the spot they were picked up at, even if they are not on the ground.

**Database links:**
https://www.wowhead.com/wotlk/spell=62166/stone-grip
https://www.wowhead.com/wotlk/spell=781/disengage

**Comment by Afgann** [comment]
fixed
