### ISSUE TITLE
Warlock Infernal Suggestion

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#1429]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Make it so the infernal pet can proc the Demonic Pact talent as per the approved suggestion:
https://discord.com/channels/1040715551531618365/1257094727107477616
![image](https://github.com/user-attachments/assets/79c065ff-4253-464f-8c28-e7b5fc1eb297)

**Comment by UltraNix** [comment]
Implemented.
