### ISSUE TITLE
Escape from Silverbrook bugged

### ISSUE THREAD

**Issue by B3rthell** [gamefreedomgit/Frostmourne#1430]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The quest Escape from Silverbrook isn't working properly. The player is supposed to mount the horse and kill the worgens that attack him while the horse rides to Amberpine Lodge. I've been stuck on it for the past hour on my character Nomvader. would appreciate any help

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/wotlk/quest=12308/escape-from-silverbrook

**Comment by PanJanuszek** [comment]
![image](https://github.com/user-attachments/assets/85b22208-5084-46a3-8d68-b13cb514d7e9)
![image](https://github.com/user-attachments/assets/9a8e6f61-2a70-4acd-a1cd-e8e6106b30da)
![image](https://github.com/user-attachments/assets/317ad706-291e-4561-b8e7-0ba87cffd1e7)

Cannot reproduce works as should
