### ISSUE TITLE
[Wintergrasp] Cannons are dealing damage through walls

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1431]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Cannons are dealing damage to the other side of walls that are being shot at, as if no wall is there.

**How to reproduce:**
Mount a wintergrasp fortress cannon, shoot at a wall with a siege on the other side (not in sight). Damage is being done to the siege.

**How it should work:**

**Database links:**

**Comment by Riztazz** [comment]
I need some proof that it shouldnt

**Comment by Chaos-within** [comment]
@Riztazz I know this is already closed but I never got a chance to provide some evidence. All vehicle projectiles have the "Ignore Line of Sight" flag on them. I think when these abilities were emulated, this flag was misunderstood. This flag is specifically for vehicle projectiles that follow the aiming trajectory, which doesn't require line of sight as the trajectory can be shot over objects, but was improperly applied to the cannon blast (or damaging effect) in this case.

Here are a list of some vehicle projectiles which have this 'line of sight' flag, that don't and/or shouldn't ignore line of sight:
https://www.wowhead.com/wotlk/spell=51421/fire-cannon
https://www.wowhead.com/wotlk/spell=55987/engulfing-fireball
https://www.wowhead.com/wotlk/spell=50025/plague-barrel
https://www.wowhead.com/wotlk/spell=52435/scarlet-cannon
https://www.wowhead.com/wotlk/spell=67440/hurl-boulder
https://www.wowhead.com/wotlk/spell=66218/launch

The most telling one is probably Launch, as it's pretty well known you can't shoot yourself through the keep gates inside Isle of Conquest using the catapult, you have to aim above.

**Comment by Riztazz** [comment]
Well, what if i shoot over the wall?

Launch case is not a very good example, because it doesn't work like other spells you've listed. While visually it might, it's just a jump movement that happens so a model 'body' checks for the collisions.
Unless i misunderstand something and you can't launch yourself on the gate on retail? Which wouldn't make sense, you will just fly and splat on the gate

**Comment by Chaos-within** [comment]
Shooting over walls isn't the problem and should work. The problem is shooting one side of a wall and dealing damage to things on the other side (through the wall). Launch is a good comparison as it indicates even if there is no damaging projectile, the ignore line of sight flag is used for any trajectory whether it deals damage or not. For dealing damage through walls with these projectiles, a siege engines cannon doesn't deal damage through a small wall (wall must be smaller as it has lower AoE compared to fortress cannons) yet still has the ignore line of sight flag.

**Comment by Riztazz** [comment]
The flags are fine, but i think i know where the issue might lie

**Comment by Riztazz** [comment]
Fixed, will close once it's live
