### ISSUE TITLE
[Wintergrasp] Vehicles are effected by friendly auras and wild growth

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1432]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Manpower99** [comment]
Something like this happens to FL Auras aswell on ptr, vehicles even got dazed by Aspect of the Pack

**Comment by Godmatik** [comment]
This affects all vehicles.

Even the dragons on Kil'jaedan.

They should be immune to all of it

**Comment by Chaos-within** [comment]
Vehicles also able to dodge/parry...

**Comment by PanJanuszek** [comment]
Can you point all wrong mechanics for vehicles + their names?

**Comment by Chaos-within** [comment]
No

**Comment by Godmatik** [comment]
Winterspring Catapult, demolisher, siege engine
All 3 Ulduar vehicles (dont remember their names)
and the dragons from KJ

It affects literally every single vehicle

**Comment by Riztazz** [comment]
Fixed, will close once it's live

**Comment by Manpower99** [comment]
Dragon's in KJ are not vehicles, they are similar to the Razuvious Orbs in Naxx10 with the mind control selection.
regardless they should indeed not be healable but i believe that fix is already on live.
