### ISSUE TITLE
Thaddius [Naxx 10] and maybe Naxx10Asc

### ISSUE THREAD

**Issue by bandini9** [gamefreedomgit/Frostmourne#1436]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Thaddius still have threat table at the start of fight in 10man

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
@bandini9 Tested with Omen addon maybe?

**Comment by Manpower99** [comment]
Happens to us aswell yesterday, it would normally aggro the closest person to him when he's targetable ( due to proximity and that he has no prior threat) instead he went for the furthest healer since that healer built up aggro on him from the first phase.

**Comment by UltraNix** [comment]
Not really what happened. That's why I need a test with Omen or any threat addon.

**Comment by bandini9** [comment]
> @bandini9 Tested with Omen addon maybe?

Yes, as a resto druid I got threat warning from omen.

**Comment by UltraNix** [comment]
@bandini9 As I can't reproduce it - could you send some screenshots with bug (next time when happen)?

**Comment by wowclassic1234** [comment]
Rsham 20k threat
![image (35)](https://github.com/user-attachments/assets/91638c7d-6985-4574-8f21-37c5d6845982)

**Comment by wowclassic1234** [comment]
> @bandini9 Поскольку я не могу это воспроизвести - не могли бы вы прислать несколько скриншотов с ошибкой (когда это произойдет в следующий раз)?

^
||
||
||

**Comment by UltraNix** [comment]
Fixed.
