### ISSUE TITLE
Maexxna bug - Naxx 10 HC

### ISSUE THREAD

**Issue by LudaBaby** [gamefreedomgit/Frostmourne#1437]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** 

So the group I joined was killing Maexxna, me and some random lad joined them to finish it. We entered came to the boss but few of us couldnt see the boss at all. After wiping the boss we tried going again, when we came the Boss was abnormal size, never saw that anywhere lol We tried killing it but we couldnt since of his size, we couldnt find our players who were webbed and we couldnt hit the boss, only ranged players could. Anyway we wiped 5-6 times and we just called it, locked for a stupid reason and wasted our time. We made a ticket about it, GM answered and told me report the bug here, we asked him if he could just come and resize the boss to his normal size so we can continue with our wasted time and raid, but nah man didnt give a single fk. Overall, bad support from GM, hope this helps fix the bug.

**How to reproduce:**

**How it should work:**
Idk why was boss invisible to few of us but it shouldnt work like that, boss should be targetable and visibe also normal size, not size of the whole Raid.

**Database links:**
https://www.wowhead.com/classic/npc=15952/maexxna

**Comment by UltraNix** [comment]
@LudaBaby Got any screenshots? Sounds weird about that "size" bug.

**Comment by WhitemaneIsa** [comment]
No reply from poster and no further complaints at all, closing for now.
