### ISSUE TITLE
If you cancel the auction the item will not arrive in your mailbox instantly, but after a few hours

### ISSUE THREAD

**Issue by Cure-whitemane** [gamefreedomgit/Frostmourne#1443]
**Description:**

If you cancel the auction the item will not arrive in your mailbox instantly, but after a few hours

**How to reproduce:**

1. Create an auction
2. Cancel it
3. Observe no item in the mailbox returned immediately

**How it should work:**

It should go back to you right away

**Comment by UltraNix** [comment]
@Cure-whitemane You are sure you did not exceed daily auction cancel limit?

**Comment by Cure-whitemane** [comment]
@UltraNix I updated the title and the description

**Comment by UltraNix** [comment]
Then it's not a bug, but our feature.
Mails are delayed if you exceed daily limit.

**Comment by Cure-whitemane** [comment]
@UltraNix but you asked me if I exceeded the daily limit - I answered, that no I did not exceed. Now you just claimed that I exceed and closed the issue. 
How should we build the dialogue then if you simply do not care about the answers?

**Comment by UltraNix** [comment]
@Cure-whitemane Sorry - I missread your comment.

**Comment by UltraNix** [comment]
@Cure-whitemane Poke me on Discord.

**Comment by Cure-whitemane** [comment]
The issue was in the addons

**Comment by Cure-whitemane** [comment]
Thank you @UltraNix for the help in figuring it out!
