### ISSUE TITLE
[RDF] People votekicked from the group are able to rejoin

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1446]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Votekicked players are able to rejoin the same group. Should be restricted

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
@Chaos-within Do we have any info about this one?

**Comment by Chaos-within** [comment]
Not for rejoining a group once kicked, but I'd like to add:

"If they’re on your ignore list, RDF won’t group you with them. At least it didn’t in original Wrath."

"Putting players on ignore already prevents you from being grouped with them."

https://us.forums.blizzard.com/en/wow/t/rdf-must-get-an-ignore-function/1722711/3

**Comment by Riztazz** [comment]
@RadeghostWM This needs design decision really, as this is not really verifiable at this point

**Comment by UltraNix** [comment]
@Riztazz 
<img src="https://media2.giphy.com/media/3o84sw9CmwYpAnRRni/giphy.gif"/>

**Comment by Riztazz** [comment]
fixed, will close once it's live
