### ISSUE TITLE
Rotten Aromas after Battle for Undercity

### ISSUE THREAD

**Issue by AgentMalice** [gamefreedomgit/Frostmourne#1448]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
After completing the [Battle for Undercity quest](https://www.wowhead.com/wotlk/quest=13267/the-battle-for-the-undercity) every time I visit Thrall in Orgrimmar I am now bombarded with Rotten Aromas and Spit from the Kor'kron Elites.

**How to reproduce:**
Finish the questline and then go walk over to Thrall.

**How it should work:**
This shouldn't be happening. I am a Blood Elf Warlock.  These effects only occur to new Death Knights when the finish their starting quests. https://www.wowhead.com/wotlk/spell=58514/rotten-banana-aroma#comments

**Database links:**
![WoWScrnShot_072324_125956](https://github.com/user-attachments/assets/60129a6a-dddf-4d2c-8f7e-72304de41e33)

**Comment by PanJanuszek** [comment]
Server has not been updated till today.
