### ISSUE TITLE
leash/pursuit range is not blizzlike

### ISSUE THREAD

**Issue by qqdbpp** [gamefreedomgit/Frostmourne#145]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
![image](https://github.com/gamefreedomgit/Frostmourne/assets/159703358/4a36926a-ccc6-4e79-8d66-facc1ff7ebea)
https://github.com/azerothcore/azerothcore-wotlk/issues/5455

exact same problem on this server as this azerothcore discussion from 2021. mobs have a fixed reset range instead of starting a 12-15s timer upon exiting their leash range.

**Comment by Afgann** [comment]
fixed

**Comment by qqdbpp** [comment]
still broken : - (

**Comment by Godmatik** [comment]
yeah seems even worse now than previously. Feels like mobs are randomly resetting with no logic behind it.
