### ISSUE TITLE
[CORE] Transferred DMG Transfer Doesn't Work (Soul Link + Hand of Sacrifice)

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1451]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Hand of Sacrifice doesn't transfer dmg from warlock pet who took the dmg from Soul Link. Breaking CCs doesn't work either - because the dmg part that is supposed to break CCs is missing

![image](https://github.com/user-attachments/assets/d3e23abf-f11d-4a5f-9a6e-b0267e81295d)

**How to reproduce:** Deal any dmg to the Warlock while having Soul Link and his or her pet has Hand of Sacrifice or Divine Sacrifice on them

**How it should work:** It should transfer dmg from Soul Link transferred dmg to the Paladin. With Divine Sacrifice, both warlock and Pet should transfer 20 % of the dmg they take to the Paladin, if both are in range. Currently only the Warlock does.

Related to https://github.com/gamefreedomgit/Frostmourne/issues/1369

**Database links:**   https://www.wowhead.com/wotlk/spell=19028/soul-link  https://www.wowhead.com/wotlk/spell=6940/hand-of-sacrifice https://www.wowhead.com/wotlk/spell=64205/divine-sacrifice

**Comment by haephaistoss** [comment]
Doesn't work with hellfire either, it should*

**Comment by Piootrek** [comment]
Do you have any proof it should work that way?

**Comment by Piootrek** [comment]
Fixed
