### ISSUE TITLE
[Spell] Conflagrate - Low dmg

### ISSUE THREAD

**Issue by InterstellarWhitemane** [gamefreedomgit/Frostmourne#1452]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

I tried my dps on dummies now and at full proc I gave **3280**dmg. 
At that moment I had **3859**sp + Curse of elements on the target. 
Should give it for 5000-5500 non crit. And not **3280**. 

Periodic dmg from conflagrate was also very weak. Only **728**dmg per tick

I've been playing this class and spec for a long time and a lot of servers, and I've been playing it on this server since the beginning. And it's the weakest I've ever played. In my opinion, this spell is at least 25% weaker than on other servers I've played, including Wotlk Classic.

In the long term, Destro warlock is uncompetitive in PVE on this server. I would be happy if he was given at least a little love.

This spec must be weaker than normal even in PvP.

**How to reproduce:**

Log and tests this spell. 

**How it should work:**

Try to see if some dmg-increasing talent isn't buggy. Or change the power of the ability manually.

**Database links:**

https://www.youtube.com/watch?v=mk41sEHh-1Y&ab_channel=Rawor
- Just to compare how weak the conflagrate spell is now.

https://www.wowhead.com/wotlk/spell=17962/conflagrate#comments
- In the comments, one person tested how much dmg he is able to deal with immolate + conflagrate when he crits with both. With my spellpower I should be able to max 16.8k but I can max 10.5k on this server. Yes, this is hybrid testing, so it has 25% extra dmg from talents, but I have +10% immolate from glyph + 13% CoE on the target.

Another Testing: 

Combat log:
https://ctrlv.cz/Q8IQ
https://ctrlv.cz/ePyl
Conflagrate instant: Immolate tick = 1090 x5 (full immolate) = 5450 x 0.69 (Conflagrate instant dmg 69% from immolate) = 3760,5 x1.13 (Curse of Elements + 13% magic dmg done) = **4250**. And my dmg in this situation is only **3277**.
Conflagrate tick: = 40% immolate = 2190 x 1.15 (Emberstorm talent 15% fire dmg spells done) = 2507 x 1.13 (CoE) = 2833 with all 3 ticks = **944** one tick. And my ticks is only **726**.

https://ctrlv.cz/Xt99
https://ctrlv.cz/OU0y
https://ctrlv.cz/KgzH
https://ctrlv.cz/J0Fx
Conflagrate: Immolate 1010 tick = 5050 x0.69 = 3484 x 1.06 (Pyroclasm 6% fire/shadow dmg) =  **3693**. My dmg is **2902**.
Conflagrate tick: 5050 x 0.4 = 2020 x 1.15 = 2323 x 1.06 = 2462 /3 = **821** per tick and my is **642**.

**Comment by haephaistoss** [comment]
In my testing:

![image](https://github.com/user-attachments/assets/f93da13b-394e-49a7-955a-80cc87f39d81)
![image](https://github.com/user-attachments/assets/0c758c05-f021-4bfe-9a02-1e5d5eb222ed)


seems perfectly OK for me - within rounding error margin

**Comment by haephaistoss** [comment]
you may have an aura bugged on you that reduces your dmg, the above test was conducted with 1469 bonus SP as you can see from the image

**Comment by InterstellarWhitemane** [comment]
Conflagrate has nothing to do with spellpower but with the power of immolate on the target.

**Comment by haephaistoss** [comment]
immolate scales off of SP - conflagrate scales off of immolate, so yes, conflagrate does scale off of SP, simply not directly, rather indirectly, so your statement doesn't hold up

> Conflagrate has nothing to do with spellpower but with the power of immolate on the target.

**Comment by InterstellarWhitemane** [comment]
> immolate scales off of SP - conflagrate scales off of immolate, so yes, conflagrate does scale off of SP, simply not directly, rather indirectly, so your statement doesn't hold up
> 
> > Conflagrate has nothing to do with spellpower but with the power of immolate on the target.

That's why I have ticks of immolation on the screens so that it can be seen that it is calculated incorrectly. At that moment I had 3859sp + Curse of elements  = only 3280. One of the examples.

**Comment by haephaistoss** [comment]
Immolate DoT seems to be in order too

![image](https://github.com/user-attachments/assets/f0c778ac-4eac-4a82-86c8-e8573c5759b9)


![image](https://github.com/user-attachments/assets/191c7560-cac3-4824-89c6-1c1cd23e39e4)
 2 dmg difference from theoretical

**Comment by InterstellarWhitemane** [comment]
Are there any plans to fix this essential spell for destro warlock? It's been a few weeks since my report. ^^

**Comment by Piootrek** [comment]
The instant damage part didn't benefit from Emberstone and did 60% of immolate damage instead of 69%. Emberstone talent changes Conflagrate tooltip so I assumed it should change its damage, but the dot part remains static. 
Do you have any proof that dot damage should benefit from other talents too?

**Comment by InterstellarWhitemane** [comment]
Hello. :) Dot damage is also visible in my screenshots and testing. In my opinion, the calculation of the whole spell is set wrong. Direct and Periodic components too of this spell. I'm looking forward to the 15% boost from the emberstorm talent being applied, which I'm really glad that at least something is being done about it.
