### ISSUE TITLE
Army of the dead is back doing way more dmg than it should

### ISSUE THREAD

**Issue by jonathansbb** [gamefreedomgit/Frostmourne#1454]
**Description:**
Army is doing way too much dmg again… seems like you have boosted the base damage. 17th of July it was working good (i.e, last reset) but now it just botched again. 

I wont be writing any more because there has been written x amount or issues on this topic. Should in other words know what it is about. I havent seen anything in changelog on this recently so no idea what has been done from your part. But one thing is for sure and that is base dmg being way to high. 

25th of July it is doing 290k:
https://uwu-logs.xyz/reports/24-07-24--19-10--Goggins--Whitemane-Frostmourne/player/Smoother/?boss=patchwerk&mode=25N&s=2999&f=3110&attempt=1

17th of july ir is doing 160k:
https://uwu-logs.xyz/reports/24-07-17--20-23--Spin--Whitemane-Frostmourne/player/Spin/?boss=patchwerk&mode=25N&s=194&f=303&attempt=0

17th of July = good.
25th of july = omega bad

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Nihaobeachez** [comment]
![image](https://github.com/user-attachments/assets/26edd69a-de78-4b63-920c-98dd4457782c)
Its the "fix" from 2 weeks ago which went live yesterday. I wonder when it actually gets properly fixed, getting old. Same story since weeks

**Comment by jonathansbb** [comment]
> ![image](https://private-user-images.githubusercontent.com/96308500/352075585-26edd69a-de78-4b63-920c-98dd4457782c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MTIwNDUsIm5iZiI6MTcyMTkxMTc0NSwicGF0aCI6Ii85NjMwODUwMC8zNTIwNzU1ODUtMjZlZGQ2OWEtZGU3OC00YjYzLTkyMGMtOThkZDQ0NTc3ODJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDEyNDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjYWQ0NjYyZWVhOTU2ZjhlOTU1ZDQ2MmI3NTdjNTMxNTBkNGYxZWQ0M2Q2NzE3YWU1ZTJhZmY1ZWZjZDg5NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jSuby5FRsp49fubNgO0H-973BtG8e3i-U-m8MC3Egvc) Its the "fix" from 2 weeks ago which went live yesterday. I wonder when it actually gets properly fixed, getting old. Same story since weeks

Not true. I tested this on the ptr and it nerfed the base dmg. So idk whats going on here.

**Comment by Nihaobeachez** [comment]
> > ![image](https://private-user-images.githubusercontent.com/96308500/352075585-26edd69a-de78-4b63-920c-98dd4457782c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MTIwNDUsIm5iZiI6MTcyMTkxMTc0NSwicGF0aCI6Ii85NjMwODUwMC8zNTIwNzU1ODUtMjZlZGQ2OWEtZGU3OC00YjYzLTkyMGMtOThkZDQ0NTc3ODJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDEyNDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjYWQ0NjYyZWVhOTU2ZjhlOTU1ZDQ2MmI3NTdjNTMxNTBkNGYxZWQ0M2Q2NzE3YWU1ZTJhZmY1ZWZjZDg5NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jSuby5FRsp49fubNgO0H-973BtG8e3i-U-m8MC3Egvc) Its the "fix" from 2 weeks ago which went live yesterday. I wonder when it actually gets properly fixed, getting old. Same story since weeks
> 
> Not true. I tested this on the ptr and it nerfed the base dmg. So idk whats going on here.

how much was it? 150k? if so, ure probably the guy who tested it on dummy without any raidbuffs

**Comment by jonathansbb** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/96308500/352075585-26edd69a-de78-4b63-920c-98dd4457782c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MTIwNDUsIm5iZiI6MTcyMTkxMTc0NSwicGF0aCI6Ii85NjMwODUwMC8zNTIwNzU1ODUtMjZlZGQ2OWEtZGU3OC00YjYzLTkyMGMtOThkZDQ0NTc3ODJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDEyNDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjYWQ0NjYyZWVhOTU2ZjhlOTU1ZDQ2MmI3NTdjNTMxNTBkNGYxZWQ0M2Q2NzE3YWU1ZTJhZmY1ZWZjZDg5NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jSuby5FRsp49fubNgO0H-973BtG8e3i-U-m8MC3Egvc) Its the "fix" from 2 weeks ago which went live yesterday. I wonder when it actually gets properly fixed, getting old. Same story since weeks
> > 
> > 
> > Not true. I tested this on the ptr and it nerfed the base dmg. So idk whats going on here.
> 
> how much was it? 150k? if so, ure probably the guy who tested it on dummy without any raidbuffs

https://github.com/gamefreedomgit/Frostmourne/issues/1322

**Comment by Nihaobeachez** [comment]
so basically what ive said. tested it on dummy without any buffs. 
either way, need to look at it again and nerf it, close to 300k dmg is just dumb

**Comment by jonathansbb** [comment]
> so basically what ive said. tested it on dummy without any buffs. either way, need to look at it again and nerf it, close to 300k dmg is just dumb

I dont see your point tho. Nothing in the changelog has caused the dmg we are seeing on live right now. The change that was pushed from the ss/fix you provided, lowered the dmg even more on the ptr, so this its definitely something else from whitemanes side. And yes i agree its ridicolous the dmg it produces now. In icc bis army is doing 400k selfbuffed 🤪

**Comment by Manpower99** [comment]
I think its obv something got reverted when they compiled their latest update without noticing, theres no real need to panic.

**Comment by jonathansbb** [comment]
![IMG_9377](https://github.com/user-attachments/assets/ce600de1-ca11-4296-ac14-5dfe6f25b103)

There has been another log after revertion (above) was applied. Army, however is still doing too much dmg: 
https://uwu-logs.xyz/reports/24-07-26--20-45--Pepsiman--Whitemane-Frostmourne/player/Pankcho/?boss=patchwerk&mode=25N

Dmg 220k with non-optimized snapshot.

**Comment by Manpower99** [comment]
Because the change is obv not applied to ptr yet, if it was then deepwounds wouldnt be doing this level of damage still.

**Comment by jonathansbb** [comment]
> Because the change is obv not applied to ptr yet, if it was then deepwounds wouldnt be doing this level of damage still.

![IMG_9395](https://github.com/user-attachments/assets/c56186ba-ddd5-4e7b-bfef-63c019d135a6)

Yes. So obvious especially with this.

**Comment by Manpower99** [comment]
It is obvious, if you even checked PTR when that changelog was posted, the change wasnt even applied there

**Comment by jonathansbb** [comment]
> It is obvious, if you even checked PTR when that changelog was posted, the change wasnt even applied there

The fact they post a changelog and then proceeds by saying «above» is applied to live makes this obvious is beyond me. But sure, whatever floats your boat 💀

**Comment by Manpower99** [comment]
Gaga posted it by replying to the Patchwerk change, implying that any fix after it is not. idc either way. i spent over 6 hours in PTR yesterday testing ulduar and army was not fixed there lol

**Comment by Riztazz** [comment]
Is this still up to date? Army has been heavily changed recently

**Comment by jonathansbb** [comment]
> Is this still up to date? Army has been heavily changed recently

No, you can close this one.
