### ISSUE TITLE
[PRIEST] Devouring Plague SP Coeff Wrong

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1455]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** DP shuld have an SP coeff of 0.184875 / tick. Currently it has ~ 0.2 / tick. Tested fully naked with 0 SP, base dmg was spot on, with SP it started to slide off.

**How to reproduce:** Cast DP on any target and calculate the result.

**How it should work:** It should have the following formula: DP = Base + SP * 1.479 = 1376 + SP * 1.479
Now each tick should do 1/8th of that so it gives us: DP / 8 = 172 + SP * 0.184875

With SP coeff being wrong, the instant dmg value is off too, since it derives its dmg from the periodic part.
Obviously the more SP the player has, the greater the difference will be.

**Database links:** https://www.wowhead.com/wotlk/spell=2944/devouring-plague#comments

**Comment by UltraNix** [comment]
Fixed.

**Comment by Stancone** [comment]
Hello, the value is wrong, it's most likely from the first iteration of WOTLK, the correct one from patch 3.2 is 20%. 
Please see relevant links: 
1. Announcement of DP coefficient change: https://wowwiki-archive.fandom.com/wiki/Patch_3.0.3
2. Correct value: https://wowwiki-archive.fandom.com/wiki/Spell_power_coefficient 20% in change 3.2.0

Please address this issue.
