### ISSUE TITLE
Zul'Aman - Bear Mount / Last Chest Not Spawning

### ISSUE THREAD

**Issue by Davud-P** [gamefreedomgit/Frostmourne#1457]
**Description:**
Doing a regular ZA run with some guildies, we were speed running it and got the first two chests and sacrifices. At the third boss, with well over 36 minutes on the timer, we killed the boss and the timer disappeared. We got the sacrifice, and the chest but the timer disappeared. We killed the 4th boss, and did not get the bear mount :(

**How to reproduce:**
Clear the bosses. We did top left, bottom left, bottom right, top right (Counter-clockwise order).

**How it should work:**
Kill the 3rd boss, timer gains +10 minutes and the chest. Kill the last boss while the timer is still running, and it drops an extra chest with the mount in it.

**Database links:**
https://www.wowhead.com/wotlk/item=33809/amani-war-bear

**Comment by Manpower99** [comment]
Bear mount is unobtainable after Wotlk pre patch.
![image](https://github.com/user-attachments/assets/1186be84-5d5c-41aa-9a1c-0a495c685fac)

**Comment by Davud-P** [comment]
> Bear mount is unobtainable after Wotlk pre patch. ![image](https://private-user-images.githubusercontent.com/100322493/352344352-1186be84-5d5c-41aa-9a1c-0a495c685fac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMTA4MjcsIm5iZiI6MTcyMjAxMDUyNywicGF0aCI6Ii8xMDAzMjI0OTMvMzUyMzQ0MzUyLTExODZiZTg0LTVkNWMtNDFhYS05YTFjLTBhNDk1YzY4NWZhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQxNjE1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmNjOTMwMzY0MzVhMDlkYWUzOWY0YTQzNzMyZTlhOGFjOTZlMGE5NTkwNTgyMDhiNDM2OTkyNDdmZjg4ZGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LuIAN9cVEL0HNGqG-M3CtFstdSuvH6hJKnJckV6Yti8)

But the loot chest does not spawn either, which should have other drops besides the bear mount. The mount is specifically tied to the timer, which is also not functioning correctly.

**Comment by yeagerca** [comment]
My group also had this issue. The sacrifice timer disappeared some time around the third boss and we did not get a bonus chest for third or fourth boss.

**Comment by Piootrek** [comment]
Fixed
