### ISSUE TITLE
Molten Core Majordomo Bugs out

### ISSUE THREAD

**Issue by bandini9** [gamefreedomgit/Frostmourne#1458]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
After killing all bosses, incluiding majordomo executus encounter nothing happens. He teleports and never shows up at Ragnaros' spawn location

**How to reproduce:**
Kill all bosses

**How it should work:**
After killing majordomo It's supposed to go Ragnaros' chamber

**Database links:**

**Comment by bandini9** [comment]
side note : gm aule can confirm it

**Comment by yeagerca** [comment]
#827
