### ISSUE TITLE
Catching a fish gets you stuck in "channeling" state

### ISSUE THREAD

**Issue by Perilynn** [gamefreedomgit/Frostmourne#1460]
**Description:**
When casting a fishing line and catching a fish. You get stuck in a "channeling state" that cannot get cleared (even from death or relog) until you cast another fishing line and let the fish "get away". Seems like your channeling state isn't clearing on fish catch success. 

**How to reproduce:**
cast fishing and hook a fish. Channeling state will persist.
Video reproducing problem and how to "fix".

https://streamable.com/36lvng

**Comment by UltraNix** [comment]
Fixed.
