### ISSUE TITLE
Risen ghoul

### ISSUE THREAD

**Issue by danniellos94** [gamefreedomgit/Frostmourne#1461]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Risen ghoul casts 'Leap' in melee range.  Risen ghoul spawns with 0 energy and really slacks at using claw even with 100 energy
Risen ghoul also casts huddle when at full HP and you lose like 10 seconds of him doing nothing.

**How to reproduce:**
Use raise dead in melee range on dummy.

**How it should work:**
Leap should have 5-30 yard range (20 sec cooldown) and ghoul should only use it if he is at least 5 yards aways from the target to not waste energy. He should more reliable use the energy on claw and his attack speed scale with haste (I think it does).
Risen ghoul should not use huddle at full HP. 
https://www.youtube.com/watch?v=sSO-QXUlvqs Here the dk spawns risen ghoul and he immediately attacks target and use claw.

**Database links:**

**Comment by Sylanha** [comment]
![image](https://github.com/user-attachments/assets/41d9cb22-10f0-469c-9f3b-c324a03242f1)

Ye, can confirm about the Leap and Huddle and not using Claw even with 100 Energy + it spawns with 0 Energy aswell. Risen Ghoul is doing more than double the damage on classic compared to Whitemane. It should definitely benefit from haste and either STR or ATP.

**Comment by danniellos94** [comment]
It benefits from STR and haste also ravenous dead should work for risen ghoul.
On video you can see ghoul is spamming claw to 0 energy literally.

**Comment by UltraNix** [comment]
Fixed.
