### ISSUE TITLE
Rep increase - Dailies

### ISSUE THREAD

**Issue by disruption01** [gamefreedomgit/Frostmourne#1462]
![image](https://github.com/user-attachments/assets/db230948-c763-485c-ae9b-85dcf1ca284b)
Same rep as a normal day for "Planning for the Future" quest (today is 100% more rep)

I should be getting 1k rep on this one.

**Comment by UltraNix** [comment]
This quest is not affected by this - it gives 500 rep and it's an overriden (constant) value.
