### ISSUE TITLE
[Raid] The EoE 10 ascended doesn't drop 25 heart quest item

### ISSUE THREAD

**Issue by Cure-whitemane** [gamefreedomgit/Frostmourne#1463]
**Description:**

[Raid] The EoE 10 ascended doesn't drop 25 heart quest item. It simply does not make sense in this restriction as 10a considered as a complete replacement of 25 normal.

![image](https://github.com/user-attachments/assets/04e90625-a3d2-406b-b312-5a2695e9fdf6)

**How to reproduce:**

1. Loot the key from saph 10a
2. Go to eoe 10a
3. No heart quest item loot for the question

**How it should work:**

EoE 10a should drop 25n quest item

**Comment by UltraNix** [comment]
#1433
