### ISSUE TITLE
Ulduar PTR - pre-Mimiron trash packs #2

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#1464]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
This applies to both 10, 25man and all difficulties.

Currently in the tunnel that leads to Mimiron tram there are 4 trash packs instead of 3.
Because of this difference in number of trashpacks, the correct number and type of mobs per trash pack is also wrong - correct version detailed in "how it should work" section.

**How to reproduce:**
Check the tunnel, observe 4 trash packs instead of 3.

**How it should work:**
PRE MIMI TRASH PACKS:
https://youtu.be/ZHpb17H9LXY?si=tX3w4ZkN7b3V8TXV&t=6208 - this video is timestamp of full run, so you can see no trash has been cleared from there beforehand and where they are correctly positioned on the map
https://www.youtube.com/watch?v=PZEONR7sqDU&t=30s - this video shows the packs individually to confirm numbers written below are true

You can see where these packs are supposed to be positioned by the pillars in the tunnel:
1st pack: **Positioned on the first pillar set from the entrance**, contains:
1 arachnopod destroyer
3 boomer xp-500
6 trash

2nd pack:**Positioned on the 3rd pillar set from the entrance**, contains:
4 boomer xp-500
3 clockwork sapper
2 arachnopod destroyer

3rd pack:**Positioned on the 4th pillar set from the entrance**, contains:
2 clockwork sapper
9 trash
6 boomer xp-500

4th pack doesn't exist in correct version

**Database links:**

**Comment by Manpower99** [comment]
Any chance this gets fixed @Afgann ?, didnt want to do a duplicate in my recent bug report.

**Comment by Afgann** [comment]
fixed
