### ISSUE TITLE
[Death Knight] - [Raise Dead]>>>> [Corpse Explosion] 

### ISSUE THREAD

**Issue by tankpajzl** [gamefreedomgit/Frostmourne#1467]
Hi, 
the ghoul is overpowered bugged with his scaling from STAMINA + STRENGHT
Bug is in talent **Ravenous Dead** (Increases your total Strength by 3% and the **contribution** your Ghouls get from your Strength and Stamina by 60%
   ) which dont increased base scaling from 30% up to 48% but it does additional 60%. **So instead of 48% u have 90%  which Is like double scale for pet!**

**5145**--base ghoul HP with no gear on master or ghoul improve talent and master 160 stamina as human 
-then i used savage chest with 115 stamina , so total 275 stamina on master for first test
**5485**   -hp with chest-should be add 30% of master stamina to ghoul so  345 hp from the chest /should be **5490** hp/ ***works
**5785**-  **without chest** and with Glyph of the Ghoul which add additional 40% so its 70% stats scale, it should have add 640 hp to Ghoul /should be **5785** hp/ *** works   
**6745** - **without chest** and with Ravenous Dead talent which improve scaling from 30% up to 48% <add 60% to scaling, so base scaling is 30x1,6=48> and then we add 40% from glyph which is **88% total master stamina to ghoul** we should have add 1408 hp to ghoul to 6553 hp. but ghoul have 6745 which is wrong

**After all , i put on the chest with 115 stamina and i got 1150 HP and my ghoul get 1490 HP***/ WTF?? my ghoul got more hp from chest like me :D /
in arena when play dk with paladin and paladin use kings on ghoul and his master, ghoul have like 34000+ HP -WTF again--- -CORPSE EXPLOSION HIT LIKE 10K """!!"""" pve must be also affected  with that STR scaling 

**This is absolutely wrong scaling, SO GHOUL GET TOTAL 130% STAMINA + 170% STR SCALING INSTEAD OF 88% and 152% . That causing ghoul hits more with corpse explosion, bcs CE is damage based on ghoul total HP (stamina)**

https://wotlk.evowow.com/?spell=49572

link as prove: https://wowwiki-archive.fandom.com/wiki/Risen_Ghoul

+Ghouls' have a "weapon" speed of 2.00.

+Ghouls scale as follows:

+Like all class pets, ghouls' base stats scale with their level.
+Ghouls receive 70% of their master's strength untalented and 112% of their master's strength fully talented with 3/3 [Ravenous Dead](https://wowwiki-archive.fandom.com/wiki/Ravenous_Dead). A [Glyph of the Ghoul](https://wowwiki-archive.fandom.com/wiki/Glyph_of_the_Ghoul) causes ghouls to inherit an additional 40% of their master's strength, for a maximum strength inheritance of 152%.
+Ghouls receive 1 attack power per point of strength over 10.
**+Ghouls receive 30% of their master's stamina untalented and 48% of their master's stamina fully talented with 3/3 Ravenous Dead. A Glyph of the Ghoul causes ghouls to inherit an additional 40% of their master's stamina, for a maximum stamina inheritance of 88%.**
 +Ghouls do not receive any health from their base stamina, and receive 10 points of health for each additional point of stamina.
+  Ghouls receive 40% of their master's resilience rating.
+    Claw deals 150% of a ghoul's AP-modified ["weapon" damage](https://wowwiki-archive.fandom.com/wiki/Weapon_damage).[[1]](https://wowwiki-archive.fandom.com/wiki/Risen_Ghoul#cite_note-1)
+    Gnaw deals 12% of a ghoul's AP-modified "weapon" damage.[[2]](https://wowwiki-archive.fandom.com/wiki/Risen_Ghoul#cite_note-2)
+    Ghouls gain hit chance and expertise based on their master's hit chance, according to the [patch 3.2.0](https://wowwiki-archive.fandom.com/wiki/Patch_3.2.0) "If a player is at their appropriate spell hit chance or hit chance maximum, their pet will be at the maximum for spell hit chance, hit chance, and expertise. If they are below the maximum, their pet will be proportionately below those maximums."
+    Ghouls do not inherit any armor.

**Comment by vedude** [comment]
Confirming that this is true. Ghouls are very strong and have very high HP values.

It is also very tanky due to its stats and killing it takes forever. One time I had 1100 resilience and I got hit by 10-11k corpse explosions constantly, which is ridiculous.

This is a high-priority case and needs to be fixed asap as it does make DK's very strong in pvp, especially good ones that take advantage of this.

**Comment by haephaistoss** [comment]
Corpse explosion deals 25 % of the ghouls max hp *1.13 (ebon plaguebringer / Coe / balance druid debuff) = 28.25 % max hp dmg, so yeah that shit hits hard, but these numbers are kinda ridicolous

Also, afaik, impurity + 20 % AP should benefit the ghoul too, but I may not remember perfectly, need some more info on it.

Some additional resources:

https://github.com/WoWManiaUK/Redemption/issues/3040
https://www.mmo-champion.com/threads/680738-Ghoul-strength-and-AP-not-right
