### ISSUE TITLE
[Quest] Neutralizing the PLague

### ISSUE THREAD

**Issue by Mynameistakenalready** [gamefreedomgit/Frostmourne#1468]
**Description:**
Using Pustulant Spining fluid
https://www.wowhead.com/wotlk/item=44010/pustulant-spinal-fluid
on Cauldron. Got 2 waves of mobs, after those while game show message to add fluid nothing happens. Even after waiting another 30 seconds to add fluid again nothing happens, no new mobs no credit for completing quest.

**How to reproduce:**
Use spinal fluid on cauldron

**How it should work:**
After few waves of mobs should get message Cauldron neutralized and should get quest completed.

**Database links:**
https://www.wowhead.com/wotlk/quest=13297/neutralizing-the-plague

**Comment by PanJanuszek** [comment]
Cannot reproduce. Works as should.

There are 4-5 waves of NPC's. You have to use fluid on text "Add fluid NOW!!"

![image](https://github.com/user-attachments/assets/f5385a03-46b9-4771-aacc-eaa78c19338c)
