### ISSUE TITLE
Bloodworms aggressive stance

### ISSUE THREAD

**Issue by danniellos94** [gamefreedomgit/Frostmourne#1469]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Bloodworms sometimes attacks targets randomly.

**How to reproduce:**
I remember hitting vezzax and bloodworms were going on vapor all the time killing it slowly on old whitemane.

**How it should work:**
Never had a problem on wotlk classic with bloodworms attacking vapor on vezzax same as pulling randomly mobs in dungeon, they were simply always attacking the target you were attacking.

**Database links:**
https://www.wowhead.com/spell=195679/bloodworms

**Comment by danniellos94** [comment]
I targetted the mob on dungeon and they attacked (didn't use any spell etc), sadly I don't have evidence for now as I didn't record 
it. I was far back and this happened on azjol nerub on first three packs of spiders. I think it happened after killing first pack.

**Comment by danniellos94** [comment]
It would be an okay behaviour if this spiders were be aggressive on me yes, the problem is the aggro was on tank.
Look at this blood beasts on deathbringer saurfang are aggressive right and they're targetting players with threat why then my bloodworms didn't attack them? I just checked my old logs and 6 of them bloodworms did 100% damage to saurfang.
[![image](https://github.com/user-attachments/assets/faede65d-fb56-4a5c-9dd8-e035afa38d88)
](https://prnt.sc/fYQ_HFz1FNSm)

**Comment by Riztazz** [comment]
As far as the old logs thing go, the script has been rewritten on this version of wotlk so it's not applicable.
I'll fix the issue where bloodworms attack in some cases on their own

**Comment by Riztazz** [comment]
Fixed, will close after server has been updated
