### ISSUE TITLE
Gammerita, Mon!

### ISSUE THREAD

**Issue by qqdbpp** [gamefreedomgit/Frostmourne#147]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
currently Katoom the Angler ID14740 gives you the quest [Snapjaws, Mon!] and then opens [Gammerita, Mon!] only after the former is completed.

**How it should work:**

on classic you can accept both quests simultaneously.

**Comment by Afgann** [comment]
fixed
