### ISSUE TITLE
Fishing animation stance

### ISSUE THREAD

**Issue by Neroix** [gamefreedomgit/Frostmourne#1470]
Description: So recently I've been busy doing some daily fishing quests, until suddenly I'd be getting this bug where. My character would be stuck in a stance where you won't be able to interact with anything basically, like casting single spells, getting into mount (sometimes) or unable to use hearthstone to tp back to your inn location (For me dalaran)

Here's the example of appearance:

![WoWScrnShot_072724_141416](https://github.com/user-attachments/assets/a837c8b0-1e65-4022-a6bc-937deadd6dbe)

![WoWScrnShot_072724_141422](https://github.com/user-attachments/assets/eb9fba30-31a0-401e-a964-9965e574a9f9)

How to reproduce: All you need is to grab any fishing rod, and catch a fish then you should be seeing your channeling timer is still going down, that means you just performed the bug.

How it should work: Whenever you're stuck into the animation you should see, (Pov Paladin: You cannot cast abilities like Judgment, Shield of righteousness, or etc) And sometimes you should see whenever you get into a mount, you'd be moonwalking.

**Comment by UltraNix** [comment]
#1460
