### ISSUE TITLE
26/07/24 PTR 25N Ulduar

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1476]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Continuation from https://github.com/gamefreedomgit/Frostmourne/issues/1399
Some of the issues in the previous report are not fixed.

_**General issues:**_

 - Bosses are still dropping [Emblem of Heroism](https://wowpedia.fandom.com/wiki/Emblem_of_Heroism), should instead be [Emblem of Conquest](https://wowpedia.fandom.com/wiki/Emblem_of_Conquest)

 - Cooldown Resets upon kill/wipe are still not working.
also unrelated to Ulduar but Pets Sated is still not being cleared upon boss kill/wipe also, a massive issue that happens on live too https://github.com/gamefreedomgit/Frostmourne/issues/238
it should also affect players who are dead within the encounter and their pets.

**Kologarn:**
1. Main Body/Head Hitbox seems to be bigger than it should be perhaps? this could be the cause to why lazers keep happening in melee even after changelog saying it is fixed, possibly because boss is counting some casters as "melee" instead of ranged due to them being in middle of the room and his hitbox being big.
This is noticable in Comparison to Wotlk Classic's Kologarn, where warriors who charged ended up dead due to falling over the edge, and traps by hunters not being triggered like regular bosses would.

 2. Pets fall down behind him whenever they attack him or his arms, Kologarn is a boss with no "back side" so the pets should always be [hitting from the front.](https://www.youtube.com/watch?v=C5FX8u4996U)
[OG WotLK Proof also](https://www.youtube.com/watch?v=oeLt5hwCyhA)
-Abilities that would have interaction with the back side of a boss such as Killing Spree/Leap/Feral Charge Cat etc shouldn't work either. 
![image](https://github.com/user-attachments/assets/52ab10a0-9010-448a-a9b7-20087d9a935e)

 3. Right Arm should be absorbing damage while there are targets gripped, upon dealing sufficient damage the players need to be released.
Currently the damage that normally would be absorbed simply goes through directly to the arm's hp.

 4. On an Arm's death, the rubbles should have a delayed summon in their specific spots, currently they are instantly summoned.
https://youtu.be/_q0vSW0BYls?si=fsC8hmX0Ndz4WKde&t=31

_**Vezax Trash:**_
[Faceless Horrors](https://wowpedia.fandom.com/wiki/Faceless_Horror) are not patrolling.

_**Freya's Ancients:**_
Dropping Emblem of Heroism also
Their Abilities are not really being used
 1. [Elder Brightleaf](https://wowpedia.fandom.com/wiki/Elder_Brightleaf) Some Abilities not being used such as [this one](https://www.wowhead.com/wotlk/spell=62243/unstable-sun-beam) 
 2. [Elder Ironbranch](https://wowpedia.fandom.com/wiki/Elder_Ironbranch)  his [Iron Roots](https://www.wowhead.com/wotlk/spell=62438/iron-roots) wasn't casted.
 3. [Elder Stonebark](https://wowpedia.fandom.com/wiki/Elder_Stonebark) Did not use any of his abilities.

**Freya :**
-Her Nature Bomb ability doesn't throw all the bombs at once, massively delayed after a set amount/waves.
The bombs are all one river and are all thrown at the same time [here](https://youtu.be/ns96390lXbE?si=74SFNTKq_vvhGtrQ&t=368)

**Algalon:**
 1. After Big Bang is over and players are ported out, Algalon should have no target/doesn't attack for a small period. something like a grace period to allow players to reposition themselves. [Proof from OG](https://youtu.be/uv_b1-bsN5o?si=kow494ScEkpL7aaR&t=366 ) and [Proof from Classic](https://youtu.be/KmBXn5qOr60?si=i_blqgWUMfbmf-F4&t=199)
Threat done by everyone who enters shadow realm should be wiped also, noticable in the omen of the [OG Wotlk video](https://youtu.be/uv_b1-bsN5o?si=019uGuy3PFmLE7Mn&t=369), priest remained to soak big bang and is the only one on threat until the warrior taunted. this little grace period is for the tank to taunt/reposition and be first on aggro again.
![image](https://github.com/user-attachments/assets/903ea59e-6038-4240-8263-1ac5c0eac9fc)

 2. Upon wiping he walks back to his initial location while evading, should instead despawn after a second and about 20seconds later respawns in his initial location. This is not a strictly an algalon issue but it is an issue that happens consistently on many bosses in ulduar and even in Naxxramas. [Proof](https://youtu.be/JZiB554US1g?si=5MPAYc1x4bBL35PY&t=402)
noticed that Flame Leviathan, Thorim also that have the same issue, possibly there are more bosses.

**Yogg-Saron: (Tested on 0L)**
- All of the Tentacles are overspawning, might also be using pre nerf spawn timers despite being on 25N.
- Death Rays are stuck in one spot.

_Crusher Tentacle :_ 
- [Diminish Power ](https://www.wowhead.com/wotlk/spell=64145/diminish-power#comments)is Instant but should be channeled.
~~initial cast time should also be [slower ](https://youtu.be/eorQl3xqd8Q?si=MucgGNhzAzIcIQz5&t=231)~~
- [Focued Anger](https://www.wowhead.com/wotlk/spell=57689/focused-anger) should only be stacked through direct damage, not dots. [Here](https://youtu.be/W4Tzhflasbg?si=tVmHahY7TfR0kDnX&t=18951) the dots from explosive shot are not refreshing nor stacking it.

_Constrictor Tentacle:_
- [Squeeze](https://www.wowhead.com/wotlk/spell=64126/squeeze) cannot be escaped by having Hand of Protection Cast on you, did not test with other spells such as divine shield/ice block, but i assume the same issue is happening with those.
 Also behaves odd when it comes to proximity and which target is being picked for Squeeze, [tankspot video of how it should work](https://youtu.be/SFyaloBG7SI?si=DO3NvHy6RobKTQtD&t=207)

_Guardians of Yogg-Saron:_
 - The Clouds that summoned them should no longer be triggered when Sara starts her Roleplay transition to Phase2

https://www.twitch.tv/videos/2207939245
**Database links:**

**Comment by NickZedd** [comment]
Note in case a dev tries to address it in the future: The cast time of diminish power should not be slower. In the video, you can see that Mimiron applied the cast-time slowing beam to the crusher.

**Comment by Afgann** [comment]
fixed
