### ISSUE TITLE
PTR new Sun Lute spell effects

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1477]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Current form of Sun Lute on PTR is likely an attempt at redesigning the previously too broken custom legendary, after testing it i found a couple of bugs that should be looked at before it gets released to Live realm.
It is obviously using Tiny Abo's spell ids so that part is not a bug.

 1. if the 6th Stack is being procced by Slam, you do not get the weapon swing but the 6th stack is still consumed.
This is likely a bug that came due to the [previous slam fix](https://github.com/gamefreedomgit/Frostmourne/issues/1449)

 2. if you unequip the item, you keep the mote of anger stacks, un-sure if this intended or not.

 3. if the 6th stack is consumed to get an extra weapon swing you do not proc the Paladin Seal you're on.
 
4. it would seem this weapon is unable to be desynced entirely, something that works properly with other weapons but somehow not sunlute. keep in mind im talking about regular white hits, i understand the effect should reset swing timer but you cant even desync it using macros etc https://github.com/gamefreedomgit/Frostmourne/issues/1212

**Database links:**

**Comment by JJGodX** [comment]
I did a test on XT Hardmode yesterday with my warrior:

Average proc time: **13.23s**
Average procs per minute: **4.4**
Average proc overall damage: **3.09%**

The shortest time for 6 stacks was **6.53s** and the longest was **19.43s**.

The proc rate seems quite slow compared to Tiny Abo, especially on cleave. Not sure if this is intentional or not.

I can post details, recordings, and logs if it would be helpful in tuning.

**Comment by AlucardHellsingChapel** [comment]
> I did a test on XT Hardmode yesterday with my warrior:
> 
> Average proc time: **13.23s** Average procs per minute: **4.4** Average proc overall damage: **3.09%**
> 
> The shortest time for 6 stacks was **6.53s** and the longest was **19.43s**.
> 
> The proc rate seems quite slow compared to Tiny Abo, especially on cleave. Not sure if this is intentional or not.
> 
> I can post details, recordings, and logs if it would be helpful in tuning.

its intentional it has icd between stacks so it wont be stacked too fast

**Comment by WhitemaneIsa** [comment]
@RadeghostWM

**Comment by Manpower99** [comment]
Some of the bugs currently present seem to be part of a bigger issue also.
Hits that trigger within same second are inconsistent around the board (this ofc would include the extra hit from new sun lute)
Blade Caked Blade/New PTR Sun Lute/Tiny Abomination in a Jar/ possibly hack and slash and sword specs are completely munching things they would normally be able to benefit from like JoL/JoW/Seals/Proccing Enchants

This would be an even bigger issue if it affects Windfury weapon enchant from enhance even more negative which would make the core identity of the class nonexistant if this doesn't really get fixed. not making a bug report about it since there is already one https://github.com/gamefreedomgit/Frostmourne/issues/1491

**Comment by UltraNix** [comment]
Closing as new changes have been applied recently.
