### ISSUE TITLE
Spell casts aren't shown when the spell is started out of players sight

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1478]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Spells and items such as hearthstone aren't shown as being casting if they are started before the player enters the area/is able to see the caster.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
