### ISSUE TITLE
Thaddius accumulating threat before activation

### ISSUE THREAD

**Issue by Bromonga** [gamefreedomgit/Frostmourne#1479]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Thaddius, from both Naxxramas 10 and 25 is accumulating threat before his activation, during phase 1. This will result in him instantly attacking the healer with highest threat.

**How to reproduce:**
Normally doing the fight.

**How it should work:**
Thaddius should have a threat table clean before activation (or at least refreshed).

**Database links:**
https://www.wowhead.com/wotlk/npc=15928/thaddius

**Comment by UltraNix** [comment]
It's been already fixed. He is not accumalating any threat in phase 1 (already tested).
@Bromonga Show some evidences.

**Comment by Bromonga** [comment]
> It's been already fixed. He is not accumalating any threat in phase 1 (already tested). @Bromonga Show some evidences.

Well it happened to me two times this week, last one yesterday. I will record it next reset.

**Comment by UltraNix** [comment]
No futher info - closing.
