### ISSUE TITLE
hunter pet talent cobra reflexes doesnt reduce pet AA damage

### ISSUE THREAD

**Issue by qqdbpp** [gamefreedomgit/Frostmourne#148]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
should increase pet attack speed by 30% and reduce auto attack damage by 15% (on classic) but on this server it doesnt decrease pet AA damage at all. 2 dummy tests without and then with cobra reflexes showing roughly same damage per pet hit.

![image](https://github.com/gamefreedomgit/Frostmourne/assets/159703358/98edff85-8daf-4140-b5fc-29623d55ba26)

**Comment by Afgann** [comment]
fixed
