### ISSUE TITLE
[Mage] Torment the weak not working on boss

### ISSUE THREAD

**Issue by Nightw4re** [gamefreedomgit/Frostmourne#1480]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Talent in arcane tree "Torment the Weak", that should increase damage by 12% by the mage when slow & snare effects are applied on bosses.

**How to reproduce:**
1. Go to Heroic Training dummy or any Boss classified NPC
2. Hit it with fireball or other spell listed in this
3. Use any slow effect on it, cast frostbolt, frostfire bolt, frost nova, hunter's frost trap, Priest Mind Flay, etc
4. Hit it with fireball or other spell listed in this
5. Observe damage is not increased by 12%

**How it should work:**
Even bosses are immune to slow movement effects, those effects should be applied on them anyway as Mind Flay most, or frost trap as most common spells and damage should be increased by this talent.

**Database links:**
https://www.wowhead.com/wotlk/spell=55340/torment-the-weak
>  Another thing to note is that Slow sticks to almost every mob in the game, **_including raid bosses._**

https://imgur.com/a/35sip6L

**Comment by Manpower99** [comment]
Slow and Snare effects don't work on most raid bosses. Torment of the Weak works against bosses with attack speed slow applied to them, From Frost Fever/Thunderclap/Judgement of Justice/Infected Wounds/Poison from Hunter's Traps and possibly more.
on players it should work while they are snared/ movement slowed however.
![image](https://github.com/user-attachments/assets/5705c58f-5092-458c-bfbf-0a6528510af1)
https://www.wowhead.com/wotlk/spell=55340/torment-the-weak#comments:id=783998

https://www.wowhead.com/wotlk/spell=55340/torment-the-weak#comments:id=599148

> You get no bonus from anything which is immune to snares; i.e. -ALL- wotlk bosses except for maybe a couple (Grand Widow Faerlina's "frenzy adds" come to mind). If something is immune, the snare-type debuff is not applied, and thus, you get no bonus from it.

**Comment by Nightw4re** [comment]
@Manpower99 info you provided is from 3.0.3 
![image](https://github.com/user-attachments/assets/cef28cce-ce88-43ce-bfd9-b72924265826)

![image](https://github.com/user-attachments/assets/00270628-242b-41fb-95fc-df8f47d0e168)

**Comment by Nightw4re** [comment]
so it means slow effect on target activate this talent, and no matter if his speed is affected or not.

**Comment by Nightw4re** [comment]
https://wowwiki-archive.fandom.com/wiki/Patch_3.1.0
![image](https://github.com/user-attachments/assets/e2491fa0-71f0-4f86-a5ed-55e5dd6597b0)

**Comment by Nightw4re** [comment]
> Frost trap does not affect bosses, they are not slowed, if you trigger frost trap for example on a boss you do not get Lock and Load for a reason, slow effect debuffs shouldnt even show on bosses who are immune to it (like chill debuff from mages). it would only work on bosses when their attack speed was reduced. ![image](https://private-user-images.githubusercontent.com/100322493/353120021-e454650b-10d8-472d-9e94-413b737c6029.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjQ4NTQsIm5iZiI6MTcyMjI2NDU1NCwicGF0aCI6Ii8xMDAzMjI0OTMvMzUzMTIwMDIxLWU0NTQ2NTBiLTEwZDgtNDcyZC05ZTk0LTQxM2I3MzdjNjAyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQxNDQ5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDY5MzliYjA1MDU4M2EwNDllNmI3ZWM0MmExOTlhY2RjYTk1ZTZmMzRlMzY2NDg1YjZmMzk0N2FjYmU3MzViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._pfTODfYmRup3iYGGva5h3c3Nl6lu0ovrkY17gIRPkw)

I don't understand you on the image is written what I am saying ... "**Torment the Weak talent works on all mobs, bosses, enemies**, regardless f they can get movement speed slowed or not." and as I mentioned from patch 3.1.0 even boss has no slow effect it is **a victim** of the frost trap, so it should work as well.

**Comment by Nightw4re** [comment]
![image](https://github.com/user-attachments/assets/9492e0cf-e7e3-4b99-a053-f398070e1d53)

> https://www.mmo-champion.com/threads/943982-torment-the-weak-in-pve?p=12393600&viewfull=1#post12393600

**Comment by Manpower99** [comment]
> > Frost trap does not affect bosses, they are not slowed, if you trigger frost trap for example on a boss you do not get Lock and Load for a reason, slow effect debuffs shouldnt even show on bosses who are immune to it (like chill debuff from mages). it would only work on bosses when their attack speed was reduced. ![image](https://private-user-images.githubusercontent.com/100322493/353120021-e454650b-10d8-472d-9e94-413b737c6029.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjQ4NTQsIm5iZiI6MTcyMjI2NDU1NCwicGF0aCI6Ii8xMDAzMjI0OTMvMzUzMTIwMDIxLWU0NTQ2NTBiLTEwZDgtNDcyZC05ZTk0LTQxM2I3MzdjNjAyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQxNDQ5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDY5MzliYjA1MDU4M2EwNDllNmI3ZWM0MmExOTlhY2RjYTk1ZTZmMzRlMzY2NDg1YjZmMzk0N2FjYmU3MzViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._pfTODfYmRup3iYGGva5h3c3Nl6lu0ovrkY17gIRPkw)
> 
> I don't understand you on the image is written what I am saying ... "**Torment the Weak talent works on all mobs, bosses, enemies**, regardless f they can get movement speed slowed or not." and as I mentioned from patch 3.1.0 even boss has no slow effect it is **a victim** of the frost trap, so it should work as well.

The image mentions that the talent works on slow immune bosses as long they have an attack speed slow on them, you could if you wish to ask in the same Wow classic mage discord how it works.

**Comment by Nightw4re** [comment]
Related question: What is the aim of Whitemane to be as a classic or original WotLK?

**Comment by Riztazz** [comment]
Fixed, will close once it's live.
This only applies to auras with multi-effects, if an aura is only going to slow and boss is immune, entire aura will be immuned and TTW will not activate, but if there are other effects it should now properly activate and increase the damage
