### ISSUE TITLE
[item/buff] Kreeg's Stout Beatdown should stack with well-fed

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1482]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The buff applied by [Kreeg's Stout Beatdown](https://www.wowhead.com/wotlk/item=18284/kreegs-stout-beatdown) should stack with any other spirit or food buff (including well-fed) 

This changes on Patch 3.3.0: The Spirit buff no longer stacks with other food and spirit buffs

**Database links:**
https://wowwiki-archive.fandom.com/wiki/Kreeg%27s_Stout_Beatdown

**Comment by Nightw4re** [comment]
unfortunatelly the current state is correct as it is described on page you provided ...
![image](https://github.com/user-attachments/assets/4f6886f1-5068-4cd0-82b0-dc84a9f00274)

**Comment by WhitemaneChronus** [comment]
didnt think i have to respond to this comment, but as you can see
its REMOVED in **patch 3.3.0**, we are not there yet.

Ofc Its a very minor and low priority issue though.
