### ISSUE TITLE
Deep wounds munching for warriors

### ISSUE THREAD

**Issue by Stroopdark** [gamefreedomgit/Frostmourne#1483]
**Description:**
If more than one crit occurs in the exact same timestamp just 1 of this crits will aply a proc of deepwounds.

**How to reproduce:**

*srry the examples i did on Frostmourne PTR are in spanish*

1st: Use two weapons with the same swing speed, the swing timer of both will sync because both have the same speed  so if both crit at the same time only 1 of the crits will aply a deepwounds proc.
Example: 
![image](https://github.com/user-attachments/assets/0db8f4c4-cb54-4470-86e9-af52a1019c9d)

2nd: use the whirlwind ability(https://www.wowhead.com/wotlk/spell=1680/whirlwind) until both hits of the ability crit, both hits occurs in the same timestamp and only 1 of the crits will aply a deepwounds proc.
Example:
![image](https://github.com/user-attachments/assets/74800f3d-a996-4be2-a079-25bb2e494dee)

**How it should work:**

Every crit from both: white attacks and abilities from the warrior should refresh and aply a proc of deepwounds without worring about the timestamps of the crits.

**Comment by UltraNix** [comment]
Deep Wounds munching was a thing on wotlk.
Not a bug.

**Comment by Riztazz** [comment]
Will close once it's live

**Comment by Manpower99** [comment]
> Will close once it's live

Wouldnt it also make sense to disable it for mage's ignite though?

**Comment by Manpower99** [comment]
Was asking the devs but i assume you already know the answer as usual you had a hand in it.
All good thank you for implementing a nice quality of life to the server.
would be appreciated if ignite/deep wounds munching gets implemented to cataclysm also.
