### ISSUE TITLE
Achievement [Not in my House] not working if you're put on opposite faction upon joining BG

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1484]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Not working if you're put on the opposite faction upon entering BG

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/wotlk/achievement=203/not-in-my-house
https://www.wowhead.com/wotlk/achievement=1251/not-in-my-house

**Comment by UltraNix** [comment]
Fixed.
