### ISSUE TITLE
[Boss] Terokk (Shattari Skyguard)

### ISSUE THREAD

**Issue by disruption01** [gamefreedomgit/Frostmourne#1485]
![image](https://github.com/user-attachments/assets/f09eedfa-406a-4dbc-a8e3-2e21341e166c)

https://wowpedia.fandom.com/wiki/Terokk
as explained in the wiki

**Immunity Shield: At 25% health he raises a shield that makes him 100% immune to all physical and magical attacks. To shatter the shield you have to drag him to the "blue smoke markers" where the Sha'tari Skyguard will drop bombs. When his shield is down he will go into a Frenzy, increasing his damage and the frequency of his shadowbolt volleys. Throw everything you got at him when his shield is down. After a few seconds he will raise his immunity shield again. Simply repeat until he is dead. The tank can already pull him towards another near marker while the shield is down, if present. It is rather tricky to lure him into the upcoming fire and not get the dot as well, so don't waste your time running around the marker, just go through.**

I brought him to the blue marks multiple times, nothing happened

**Comment by PanJanuszek** [comment]
No, in the air there is neutral shatari NPC who shoots on this blue location sth called "Ancient Flames". After he hit it, you will see on the ground blue flames by couple of sec.

If not, please show me video from your side :)

**Comment by PanJanuszek** [comment]
![image](https://github.com/user-attachments/assets/a2456d90-742d-4387-829d-6e180c7eef9f)
![image](https://github.com/user-attachments/assets/c2bdf931-9a1c-4f3a-ab1c-3c9be7839ccd)

As you see on focus guard is shooting, on 2nd screen after hit divine shield is removed.
Closing as no repro.

**Comment by disruption01** [comment]
check my print, there are blue flames on the ground and he keeps being immune, I've done this HUNDREDS of times in wotlk classic because I was farming the toy and I know how it works.

it's bugged!

**Comment by disruption01** [comment]
@PanJanuszek
