### ISSUE TITLE
[CORE] Achievement [DAMAGE CONTROL] Not Popping if Mercenary BG

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1486]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** The shown achiv is not popping when opposite faction BG-ing

![image](https://github.com/user-attachments/assets/936d22b7-4651-4072-ba52-9deac8ee559c)

**How to reproduce:**

**How it should work:** I guess it's just me complaining, and its not a neccessarily blizzlike feature, but the achievement doesn't specify on which team i should be dealing the 300k dmg or healing

**Database links:**

**Comment by UltraNix** [comment]
Achiev works okay.
As description says - damage/healing done to only players does count.
