### ISSUE TITLE
[DK] Unholy Blight if DC is Absorbed

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1487]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** UH Blight is still applied when DC is absorbed. The last fix didn't work fully.

![image](https://github.com/user-attachments/assets/32d2ae63-12a6-4bfd-ad99-239c52ea2fed)

**How to reproduce:**

**How it should work:**It shouldn't be applied in this case.

**Database links:** https://github.com/gamefreedomgit/Frostmourne/issues/1249

**Comment by Riztazz** [comment]
fixed with next update, forgot to push issue id in the commit name
