### ISSUE TITLE
[DK / WAR] Death Coil vs Spell Reflect

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1489]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Death Coil if reflected HEALS the DK instead of doing DMG.

![image](https://github.com/user-attachments/assets/297fb3ef-be07-4398-986c-60391ae75d73)

**How to reproduce:** Cast DC into SR

**How it should work:** Death Coil should be reflected, dmg  should be applied to the DK and UH Blight should be applied from the DMG, if not fully absorbed.

**Database links:** https://www.wowhead.com/wotlk/spell=23920/spell-reflection   https://www.wowhead.com/wotlk/spell=49895/death-coil

**Comment by UltraNix** [comment]
Fixed.
