### ISSUE TITLE
springpaw stalker npc=15651

### ISSUE THREAD

**Issue by qqdbpp** [gamefreedomgit/Frostmourne#149]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
on this server they are stealthed and very hard to detect at the proper level range.

**How it should work:**

on classic they are not stealthed at all.

![image](https://github.com/gamefreedomgit/Frostmourne/assets/159703358/f31d7534-230d-4ae3-b295-1fcc1e2024e7)

https://www.wowhead.com/wotlk/npc=15651/springpaw-stalker

wowhead thread makes no mention of stealth

**Comment by Afgann** [comment]
fixed
