### ISSUE TITLE
Ulduar 25m Bugs (PTR) - Flame Leviathan, XT, Iron Council, Algalon

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#1490]
**Flame Leviathin**
- Siege engine ram attacks were hitting turrets - only people who get launched up should be able to damage turrets. None of the vehicles abilities should be able to.
- At ~70% health FL randomly took an insane amount of damage and suddenly died a few seconds later, not sure what caused it
- "Thorim's Hammer" beams were never activated as far as I could tell

**XT-002**
- Tympanic Tantrum sometimes does not deal 10% of health per tick, occasionally it is 7% or 8%, not sure why. Nothing should be able to mitigate the damage, it should always be 10% per tick.
- Melee damage dealt by boss is incredibly low even with heartbreaker buff up

**Iron Council**
- Rune of Power just appears instantly - there should be a cast time from Runemaster Molgelm when he uses it
- Steelbreaker does a melee immediately after Fusion punch. His swing timer should reset after fusion punch so they don't both land at the same time (see below log from classic):
![fusionpunch](https://github.com/user-attachments/assets/de71fd22-0ca8-4715-b7cd-afe0c6b42597)
- Steelbreaker can hit someone with Static Disruption who already has the debuff on them, this should not be possible:
![qweqweqwestatic](https://github.com/user-attachments/assets/2ea49acf-aa00-4563-a444-915e955f16d7)

**Algalon**
- If tank gets knocked up in the air because of cosmic smash - Algalon flies into the air to follow him and stays mid-air rest of encounter. Algalon should never float up, he should just stay on ground and wait for tank to land/die.
- Collapsing Stars pathing is completely bugged - they seem to be following random people and thus going through the middle. They should be rotating around the room in a set path.
- Collapsing stars are spawning WAY too quicky. They should spawn 15 seconds after the encounter begins, and then every 60 seconds after that (until phase 2). 
- Additionally - when stars do spawn, the amount that are present in the battle should never exceed 4 (so if there is still 1 star up and it's time for stars to spawn, only 3 extra should spawn. If there are still 2 stars alive and the spawn timer is up, then only 2 new ones should spawn, etc)

**Comment by oomshroom** [comment]
The bug with Flame Leviathan randomly taking huge damage is caused by Mimiron's Inferno:
7/19 21:26:03.076  SPELL_PERIODIC_DAMAGE,0xF13000825A10C72C,"Mimiron's Inferno",0xa48,0xF15000815910BE79,"Flame Leviathan",0x30a48,62910,"Mimiron's Inferno",0x4,11648433,6175513,4,0,0,0,nil,nil,nil

**Comment by Godmatik** [comment]
kek

**Comment by Afgann** [comment]
fixed
