### ISSUE TITLE
[DK] Blood-caked Blade not proccing on-hit effects 

### ISSUE THREAD

**Issue by Karsenity** [gamefreedomgit/Frostmourne#1491]
**Description:** Blood-caked blade currently isn't proccing on-hit effects such as rune of the fallen crusader, or judgement of light from paladins. Since 30% of auto-attacks trigger blood-caked blade, this is a large loss of uptime on buffs such as unholy strength.

**How to reproduce:** Easy way to test is to equip Brunnhildar Great Axe (ID: 43601) and hit a target dummy with judgement of light on it until blood-caked strike happens. This weapon has a 4.0 speed so it's guaranteed to proc JoL, so when this occurs you should see 2 instances of it healing you. Currently this only happens once.
![image](https://github.com/user-attachments/assets/61564b34-896c-4c82-aa74-406aee05575c)

**How it should work:** As BCB is striking with your melee weapon, it should be proccing melee on-hit effects

**Database links:**

**Comment by Manpower99** [comment]
This is very noticable after the Fallen Crusader PPM change.

**Comment by haephaistoss** [comment]
In my testing non-auto attack / attacks don't procs any of these - Tiny Abo proc for instance, Paladin seals etc are not proced at all.
Seems to me like a global issue

**Comment by Eradicatepls** [comment]
The uptime of unholy strength is tragically low tbh compared to classic.
I've been testing on a 10 min dummy session is barely near 50% uptime

https://fr.classic.warcraftlogs.com/reports/g9h1zLyAtDjf7rX4#fight=20&type=auras&source=19
https://fr.classic.warcraftlogs.com/reports/Vfc3F2T6nwY9dzLb#fight=44&type=auras&source=51
https://fr.classic.warcraftlogs.com/reports/RbCTKDc78hBNqtwk#fight=44&type=auras&source=29

we should be at 85% ish 
https://gyazo.com/e56f9d823e3d275558c21a88b0a5c031

**Comment by haephaistoss** [comment]
classic is a different game, mostly fan service, not an exact replica of what it's being marketed as.

Should look for stats from the actual era

**Comment by Eradicatepls** [comment]
A proc rate is a proc rate. You have thousands of logs of 3min fights with 30% avrg uptime more than here. We should Fix that.

**Comment by Manpower99** [comment]
> The uptime of unholy strength is tragically low tbh compared to classic. I've been testing on a 10 min dummy session is barely near 50% uptime
> 
> https://fr.classic.warcraftlogs.com/reports/g9h1zLyAtDjf7rX4#fight=20&type=auras&source=19 https://fr.classic.warcraftlogs.com/reports/Vfc3F2T6nwY9dzLb#fight=44&type=auras&source=51 https://fr.classic.warcraftlogs.com/reports/RbCTKDc78hBNqtwk#fight=44&type=auras&source=29
> 
> we should be at 85% ish https://gyazo.com/e56f9d823e3d275558c21a88b0a5c031

It is likely related to the BCB issue, all uwulogs show that double fallen has almost same uptime as a fdk with 1 in offhand.
if they fix BCB perhaps this issue gets fixed.

**Comment by haephaistoss** [comment]
> A proc rate is a proc rate. You have thousands of logs of 3min fights with 30% avrg uptime more than here. We should Fix that according to classic data. That's all I say

I'm not questioning the vailidity of the issue, I'm merely pointing out that classic is no basis for anything. It may or may not have been the same in og wrath, but the fact that they happen to be the same in 2 games, doesn't imply causality in itself.

If you wanna be sure, look for og wrath era stuff, since classic is a different game.

**Comment by Karsenity** [comment]
I think this thread is getting off-topic. This bug report is just for blood-caked blade. It would be a good idea to either wait until this is fixed to bring it up again, or investigate other potential causes in the meantime and create a separate ticket.

**Comment by Riztazz** [comment]
Pushed a fix, it should be on realm in a few days
