### ISSUE TITLE
Missing item from vendor: Deadly Gladiator's Tabard

### ISSUE THREAD

**Issue by vedude** [gamefreedomgit/Frostmourne#1492]
Hello,

The vendor that is supposed to sell all Deadly Gladiator items are missing the tabard.

Full item name: Deadly Gladiator's Tabard
Link: https://www.wowhead.com/wotlk/item=201993/deadly-gladiators-tabard 

NPC name: Nargle Lashcord
Link: https://www.wowhead.com/wotlk/npc=31863/nargle-lashcord

**Comment by UltraNix** [comment]
That item does not exist on 3.3.5
https://wowpedia.fandom.com/wiki/Deadly_Gladiator%27s_Tabard
`[Patch 3.4.0](https://wowpedia.fandom.com/wiki/Patch_3.4.0) (2022-08-30): Added.`

**Comment by vedude** [comment]
It's added in 3.4 but it's meant to be available for the deadly season which is right now

**Comment by UltraNix** [comment]
No - it's meant it was added on classic, not on 3.3.5.
That item did not exist on 3.3.5
