### ISSUE TITLE
[Quest] Further Corruption (4906) has minor issues

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1493]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
This is a low level quest in felwood, also not a group quest.
One objective of this quest is to kill a [Jadefire Trickster](https://www.wowhead.com/wotlk/npc=7107/jadefire-trickster). 
The npc casts an instant spell [Cause insanity](https://www.wowhead.com/wotlk/spell=24327/cause-insanity) which causes the player and npc to get out of combat. (if no other player is around)

Can still be completed if player is quick with killing the npc or CC it.

**How it should work:**
Even though i believe it's how it worked on blizzard main servers as well, but its challenging for players playing classes without any sort of hard CC in that level range.

**Database links:**
https://www.wowhead.com/wotlk/npc=7107/jadefire-trickster
https://www.wowhead.com/wotlk/spell=24327/cause-insanity

**Comment by PanJanuszek** [comment]
Unfortunately, I've checked it on retail and it's the same. The only difference is that we have wrong timers on second cast. Gonna change it.
