### ISSUE TITLE
Brutal Gear / Season 4 PVP Rewards from TBC

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1494]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
They are currently sold by arena points and require area ratings but they are from season 4 in TBC.

**How it should work:**
Player should be able to purchase them with honor gear

https://www.wowhead.com/wotlk/npc=20278/vixton-pinchwhistle

**Comment by Riztazz** [comment]
This was decided to be kept blizzlike, closing
