### ISSUE TITLE
Sun-Lute Proc ICD is incorrect

### ISSUE THREAD

**Issue by JJGodX** [gamefreedomgit/Frostmourne#1496]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The [Sun-Lute of the Phoenix King] Blinkstrike proc internal cooldown (ICD) was set to 12s and later reverted to 6s; however, the 6s change doesn't seem to have been implemented.

**How to reproduce:**
Create a Weakaura (or use the provided one below) to track the Blinkstrike procs. Attack a training dummy with high actions per minute (APM) and look for procs (visual animation and extra meele hit). There will never be less than 12s between Blinkstrike procs due to the current ICD.

**How it should work:**
The ICD should be set to 6s as it was announced.

**Database links:**
![Lute Nerf](https://github.com/user-attachments/assets/e35afcdc-f0d6-4c30-b7d3-5bd796a5929f)
https://discord.com/channels/1040715551531618365/1154930527091044502/1264377340688072735
https://discord.com/channels/1040715551531618365/1154930527091044502/1264562273121337395
https://www.wowhead.com/wotlk/spell=38308/blinkstrike

Blinkstrike ICD WA tracker, currently set to 12s:
`!WA:2!Dr1tVTTnu8y0TLnDOyXalyBihc6HIHbKS001UEzyZY1z2RoXgukTzBbiMsKsKZYKAKuoj9Op1D1Fe05DYFek2habJ9jiFeYNG9iLBsA1f(7907V)EpYgh0CststYB(UsDown(vCIH9fV1HhKKOPMtAOUOg19N2)p(BVTxBn1L1k26ZwGfXmPAOKlmrT7Cuyh0sNViPbB4srJ8nEp5dLeQFRJdh4ZJLc2mJINMsv67)q1k4B(kLoNML1JGE8ZE8EpBrHMEgxmfmIYwMsfufpoGjpFG4kT7OTuMrKNlMzTSqWnJCigwqgLVHf(EEn6kDreDkvygQOj8lqbd70VVV1C)jyUyUl9hHNqx4NXfJ1qHnMIeGcTNV5YC68y5KiSjtMwQLfQyQ14Q7FtCdksG4E1zDoje16SwHHTA)IGRSfYTMZU2jBtvaqHYmgY5BzBxS3UVmD5nwyDy0sffNf8oXQVEXn)Uhz0SvaT3DYZXaxWCrrrTDgxKYMrkuUjXdE0((wYkkpdFjvvsOrqzhcTNQBN(dp44(ZleRMjE5BGJn8P0WAz7u8FwR0ocplwMjv)69GVRHLaQsGZEjmRGmWNRPzjUDJQpzwew1(gtHSPXgBLqz3Dz73AucKiIMcUR)2nR2AjigHJhNQKfcYkfjsfTwreJYtzM19ZKysYCBRgNH16roOayuflYGZaIDt0KImd3d5m4HrAGnYOQx1cH6nav9ZE(afgVPdWFn1cUYvz(G3eBhVFRN)88phcClYFwOnucLCi(c2d4K8nUZMY27STpwPSeg0epfPnyLXZhOFJxucCOzEFyy4cwPY11UbagygGVwIlmWTRb5Ui5547a3KDR1M7iFnNqH6)x6gE9TSunn3OrJH3BVDFsn9gsVaOBA(30ZoJsWX0tBJ1gGdGA90J7TZTs7eyDyHZTUo69hvMA3x0jB6X922pdlgx)EXTJu)xlLtAGCAzLgz806TGpD6PRIfNqOc0rDEzh011VBCGc2KTDCuqBuNohTiXQiWa7f4pgDU9TO)TjcNLZWd)O929hEse00j8up1QhegTFbNSOD0bPpQRzSQ)4fsfhg2Un8YUdq9(9bhf2QFj4hHxtJl4cybAIZeV5ybVg(0QxCq1w(cPG(wkwBRcQi1WwF57UXCM9UpKuBS0ZS2yl9kz1xcoch5Rx9xvQknap8d10uJ((D3B39Ao9)o5)d`

**Comment by UltraNix** [comment]
Sun-Lute proc effect is modified.
This change is not longer valid for this.
