### ISSUE TITLE
[MAGE] Fingers of Frost Proc Rate

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1497]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** FoF proc rate seems way higher than 15 %, it is constantly on my mage.

In my testing 47 slow casts -> 21 FoF procs or refreshes.
Less applications tho, because Frostfire bolt and Frostbolt with talents both slow for 60 %, and because they shouldn't stack, you know the jest.

**How to reproduce:** Cast Chills on a target, and count FoF applications.

**How it should work:** It should apply from 15 % of applied chills. 

**Database links:** https://www.wowhead.com/wotlk/spell=44545/fingers-of-frost

**Comment by Acurtis03** [comment]
you could apply a chill effect 10 times, and get FoF proc 0 out of those 10 casts. that doesn't mean the proc rate is 0%.
"Gives your Chill effects a 15% chance to grant you the Fingers of Frost effect"
you could get 5 procs in a row, for 5 out of 5 casts. that doesn't make the proc rate 100%.
each chill effect has a 15% chance to grant you FoF, every time its applied. 

You are looking at a very small sample of observation and implying that the proc rate is wrong. 
in probability you should distinguish between small sample observation and actual long term probability. 
You are ignoring the rule of random variability.

**Comment by haephaistoss** [comment]
> you could apply a chill effect 10 times, and get FoF proc 0 out of those 10 casts. that doesn't mean the proc rate is 0%. "Gives your Chill effects a 15% chance to grant you the Fingers of Frost effect" you could get 5 procs in a row, for 5 out of 5 casts. that doesn't make the proc rate 100%. each chill effect has a 15% chance to grant you FoF, every time its applied.
> 
> You are looking at a very small sample of observation and implying that the proc rate is wrong. in probability you should distinguish between small sample observation and actual long term probability. You are ignoring the rule of random variability.

Correct.

I've done the test 3 times, with similar result, all around 47 spell cast mark.

The probability in my testing seems to be around 45 %.

True, randomness is by definition random, and what you are implying is true, so I did the math to calculate the probability of all 3 tests with 47 spellcasts coming to be around 45 %, if the random chance is indeed 15 %.

the probability of 21 or more from 47 to be a random event and proc chance is 15 %, is 1.15 * 10^(-6). Not impossible, but come on.



Which came to be 1.52 * 10^(-18), which is abysmal, so I'm assuming the measurement is correct. Still not impossible, but still

Or I'm extremely lucky, will do a lottery today in that case.

**Comment by haephaistoss** [comment]
The question now is, what's causing the deviance?

It may be that the proc rate is wrong - that's the easiest, or it's procing to something it shouldn't be procing to, or an aura is applied that shouldn't be applied, thus making FoF proc to itself, that isn't a bug in FoF code, rather something else.

It's worth having a look at this

https://github.com/gamefreedomgit/Frostmourne/issues/1498

If a chill effect is present, another one shouldn't be applied, unless its more potent, thus FoF can't proc to it - since there's nothing to proc to.

**Comment by haephaistoss** [comment]
I have a slight idea, that the difference may come from FoF procing to FoF cast spells, treating FoF as if it was a chill effect. - Or winter's chill debuff

**Comment by Riztazz** [comment]
I've debugged a bit, talked with other devs and we've concluded that it is frostbite triggering FoF and this is intended interaction between the spells. Quick google confirms that behavior. I'm gonna leave it open for a bit in case someone has something to add, but for now it seems to be okay
