### ISSUE TITLE
Shaman Feral Spirts Vendor and trainer hostial

### ISSUE THREAD

**Issue by Zipica** [gamefreedomgit/Frostmourne#1499]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
If Shaman is neutral with trainers and Vendors in Dalaran(Kirin Tor) and he cast Feral Spirts they attack wolfs and move from correct places....

**How to reproduce:**
Cast Fearl Spirit at vendor or trainer in dalaran

**How it should work:**
They should not be pulled by wolfs 

**Database links:**

**Comment by Zipica** [comment]
I would like to add, that bug is not consistent it appears just sometimes

**Comment by Piootrek** [comment]
Can't reproduce. Please make a screenshot/video when you encounter this problem next time and post it here
