### ISSUE TITLE
Rolling on items is ignored if releasing after death

### ISSUE THREAD

**Issue by bl2x14** [gamefreedomgit/Frostmourne#1500]
As title says.. rolling on items should be seen and should be finished even if somebody releases after dying in any instance.

So if a boss is looted and 
1, somebody is outside of the dungeon/raid, they can't see the pop-up window, therefore can't roll for anything
2, If they roll on an item and release after, but before the loot is rolled by everybody, their roll is ignored like they didn't press anything.

**How to reproduce:**
Die on boss, and either release after need/greed/ but before everybody does so or release before the boss is looted, and won't see the pop-up window as ghost.

**How it should work:**
The pop-up window should be seen no matter if the player stays in the instance or releases and is a ghost, or even if is on loading screen (obviously, there's no loot window on loading screen, but you got the point).

It can be seen for example Falusicsok and myself pressed need for the mount, but we did release before everybody selected what they want:
![WoWScrnShot_073124_122443](https://github.com/user-attachments/assets/d5fcbbc2-2605-47f2-8295-95f463b2b308)
![WoWScrnShot_073124_122421](https://github.com/user-attachments/assets/1b9a784f-e092-4137-98c0-58a22be5a436)

so here it looks like only 2 people needed the mount, the others (who probably released) rolls are nowhere to be seen:
![WoWScrnShot_073124_122455](https://github.com/user-attachments/assets/a3ae3a2c-f2b0-4b04-8844-ef5cfc7c5e24)

**Comment by UltraNix** [comment]
Fixed.
