### ISSUE TITLE
[Quest] Banshee's Revenge

### ISSUE THREAD

**Issue by WhitemaneIsa** [gamefreedomgit/Frostmourne#1501]
**Description:**
The NPC is not properly spawning when clicking the War Horn of Jotunheim and is not attackable if spawned manually

**How to reproduce:**
Accept quest, click horn

**How it should work:**
NPC should spawn and engage after clicking the horn

**Database links:**
https://www.wowhead.com/wotlk/quest=13142/banshees-revenge
https://www.wowhead.com/wotlk/npc=31016/overthane-balargarde

**Comment by PanJanuszek** [comment]
Increased visibility to 140yrd, should be ok, after server update

**Comment by WhitemaneChronus** [comment]
We are still having issues with this quest, NPC is under texture and its not even hostile 
must restart the event after killing it

**Comment by WhitemaneChronus** [comment]
After a few tests it seems to happen once player dies / fails in this encounter - it doesnt reset

**Comment by PanJanuszek** [comment]
Reset is 3min if no one participating

**Comment by WhitemaneChronus** [comment]
yes like the other mobs disappear but [overthane-balargarde](https://www.wowhead.com/wotlk/npc=31016/overthane-balargarde) is underground non-hostile and [Vardmadra](https://www.wowhead.com/wotlk/npc=30945/vardmadra) is standing there with 80-90% hp. if you bring overthane he wont attack anyone, using the horn again wont do anything as well.

**Comment by Althora** [comment]
Overthane-Balagarde spawns on the east side of the building off the edge. He seems to need to be spawned in the correct location.

He despawns/phases once you get too far from the horn/roof of the building preventing any interaction as well.

**Comment by Piootrek** [comment]
Should be fixed already
https://github.com/gamefreedomgit/Frostmourne/issues/1676

**Comment by Greywolf59** [comment]
Further issues observed today: If boss Balargarde gets under 50%, there is a break in the fight. If player dies after this break, the fight does not reset properly and after ressurecting and attacking again, the fight starts at the post-50% phase. In one of my wipes he did not even replenish his HP back to 50% so I was able to finish him. His dragon is not joining the fight by dropping patches of ice either.
