### ISSUE TITLE
[CORE] Killing Players in/after Duels

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1503]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Spells and pet effects that are midair at the moment the Duel ends do dmg to both parties, sometimes resulting in killing one, or both players.

Happened to me by Mirror Image frostbolt

**How to reproduce:**

**How it should work:** There should be a moment of immunity at the moment a duel ends for both parties, or their spell effects.

**Database links:**

**Comment by haephaistoss** [comment]
![image](https://github.com/user-attachments/assets/00f5d184-517c-4d32-ac6f-e09e03c0db10)


In a duel on Test Server

**Comment by UltraNix** [comment]
Fixed.
