### ISSUE TITLE
PVP combat issue

### ISSUE THREAD

**Issue by dfmagex** [gamefreedomgit/Frostmourne#1507]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
You cannot enter combat by buffing a friendly player/pet (!) that is in combat.

**How to reproduce:**
You need to buff someone who is in **pvp** combat. Nothing happens, you won't get combat.

**How it should work:**
If you are not in a combat and buffing a friendly player/pet, you should enter combat. Also, there is no possibility to make an infinite combat cycle, if you and other player buffing each other every 5> seconds

**Database links:**
https://www.youtube.com/watch?v=EwLOcI4h_kg
This is Hydra 8, filmed back in 2010. At 13:28 Hydra leaves combat to drink, and at 13:45 he only buffs his teammate with a shield and gets combat.

**Comment by haephaistoss** [comment]
In retail wrath there was a bug with warlock - that if you cast hellfire and your pet took dmg from soul link the pet got in combat for 5 sec, and if you buffed your pet immediately after this, you could get in combat - so could your teammates.
