### ISSUE TITLE
ROGUE -  DK (Most likely) QoL and Internal Cooldown on weapon enchant's.

### ISSUE THREAD

**Issue by Eradicatepls** [gamefreedomgit/Frostmourne#1509]
**Description:**
Atm, when you switch to a black magic weapon, there is a 30s internal cooldown before enchant can proc, i guess it's the same for berserking and Mongoose, i've not tested it, because not owning them on frostmourne, but after multiple tries on black magic i can confirm it's going every single time on a 30s cooldown.

**How to reproduce:**
Simply go back and forth with a Black Magic weapon while in combat and you will see the enchant is basically never proccing.
You can also equip your weapon right after combat start and wait the 30S exactly it will instantly proc.

**How it should work:**
Enchant on weapon Shouldnt be summited to Icd when switching from a weapon to another, and it beeing that way removes a lot of the skill expression of rogues switching weapons during diverses encounters, for slower off hand, or mutilate switching to AoE dagger set up on Freya, triggering a double 30S cooldown on both their berserking, same goes for dks, that might wanna go Cinderglacier on some fights.

**Database links:**
I can link many diverse source from retail wow classic that are showing how weapons could proc berserking on rogue, and black magic on dk without having to wait those 30S but if it's necessary i'll do so in a later message.

**Comment by Flechero** [comment]
This person is reading my mind; I was just about to report the exact same Issue. Yes, as they mentioned, in WoW Classic, you should be able to switch weapons and activate another enchant without the 30-second cooldown interval.

**Comment by Karsenity** [comment]
Just wanted to add this is all on equip items, not just weapon enchants. Try equipping fiery gauntlets and you'll notice the same behavior.

**Comment by Manpower99** [comment]
Essentially only items with an ICD should trigger the 30s cd when equipped.
Items with PPM or no ICD shouldn't trigger it. can confirm this to be an issue with many items atm.
