### ISSUE TITLE
[spell] Engineering gloves enchant in EOE 

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1510]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
During phase 2 of Eye of the eternity raid, after jumping on platforms players cannot use their [Hyperspeed Accelerators
](https://www.wowhead.com/wotlk/spell=54999/hyperspeed-accelerators).

Seems they can use it in any other stage, just not on the platforms. 

**Database links:**
[Hyperspeed Accelerators](https://www.wowhead.com/wotlk/spell=54999/hyperspeed-accelerators).

**Comment by Manpower99** [comment]
Yeah, this happens consistently. 
a player on his/her disk while floating in the air cannot use engi gloves, could be other active items too.

**Comment by Eradicatepls** [comment]
Scions hit box is also obnoxious tbh, super hard to hit them when fighting from a disc as a melee dps. Think is also something to check.
