### ISSUE TITLE
QueryAuctionItems getAll argument is not working

### ISSUE THREAD

**Issue by Nightw4re** [gamefreedomgit/Frostmourne#1511]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The Auctionator is loading only 50 items only on "full scan", I am pretty sure there are hundreds of pages so it means order of arguments is changed for getAll or this argument is just not working. 

> Download the ENTIRE auction house as one single page. Only allowed when [CanSendAuctionQuery](https://wowwiki-archive.fandom.com/wiki/API_CanSendAuctionQuery)() returns true as its second return (~every 15 minutes).

**How to reproduce:**
1. Open AH
2. do `/script QueryAuctionItems("", nil, nil, nil, nil, nil, nil, nil, nil, 1)`

**How it should work:**
the last argument should mark that you want list all items on one page, but this is still limit by 50 per page.

**Database links:**
https://wowwiki-archive.fandom.com/wiki/API_QueryAuctionItems

**Comment by Nightw4re** [comment]
any dev to review this please?

**Comment by yeagerca** [comment]
Would definitely be nice to have this. I assumed it was an intentional limitation akin to the AH posting/cancelling limits.

**Comment by Nightw4re** [comment]
it should be fixed and deployed but still displaying 50 items, only difference is it takes 2min to get results instead, shouldn't be maybe missing on client side as well?

**Comment by Nightw4re** [comment]
Ok it works, I figured out why it was failed before ... that bug with "retrieving item information"

**Comment by UltraNix** [comment]
Fixed.
