### ISSUE TITLE
Spellqueue vs Channeled spells

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#1512]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

https://vimeo.com/994055927?share=copy
Problem:
Currently spellqueue does not work with anything relating to channeled spells. I believe this is why there were previous reports of people losing their last tick of their channeled spell.(<-Update: this seems to be a separate issue)

How it currently works:
While channeling a spell, if you attempt to queue another one mid-channel (regardless if the next spell is channeled or normal cast) it will interrupt the current channel, thus losing your last tick of the current channeled spell.

How it should work:
Casting another spell (channel or normal) within your chosen spellqueue timer (default 0.4s) should simply queue the next spell to be casted after your current channel is over and not interrupt your current channel.

**Comment by Manpower99** [comment]
I cannot express how annoying this bug is, it is currently affecting every priest and warlock negatively. and not exclusive to those two classes but also mage and dk on some of their channeled spells. could list the spells if need be but this seems to be a general issue related to spell queue itself.

**Comment by Eradicatepls** [comment]
I think it's even worth, it's simply denying last tick, needs more testing, but i dont even think last drainsoul tick even happens.

**Comment by BalanCV** [comment]
@Eradicatepls You are right, just tried it, last drain soul tick sometimes just doesn't happen, using just a single cast without involving queing. However, the spellqueue not working on channel spells is a separate issue so I'll just open another post for it.

**Comment by Afgann** [comment]
fixed
