### ISSUE TITLE
Drain soul last tick bug

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#1514]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Currently it seems that the last tick of drain soul never gets fired. This doesn't seem to happen every single time but it happens often enough to be noticeable.
On this vid you can see it happening twice: check combat log/battle text/weakaura
https://vimeo.com/994135529?share=copy

**How to reproduce:**
Drain soul a mob, check if the last tick fires or not

**How it should work:**
Last tick should always fire unless interrupted

**Database links:**

**Comment by Eradicatepls** [comment]
PLS SAVE US ahah

**Comment by Riztazz** [comment]
I am on a hunt with this one but issue appears to be more complicated

**Comment by scrublama** [comment]
@Riztazz 
Still happens sometimes
https://www.twitch.tv/scrublama/clip/RoundAdorableWrenCoolStoryBob-XXDG0jUNmmbsUw73
