### ISSUE TITLE
[CORE] Strand of the Ancients Demolisher Passenger Bug

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1515]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** In SoTa Demos a passenger player's direction they are facing doesn't depend on the actual direction their character is facing, but on the direction the vehicle is facing - making casting spells to enemies behind impossible.

Also players in this state can be damaged by rockets screenshot below.

![image](https://github.com/user-attachments/assets/28690cc7-c58e-483c-9c17-bcbf7d4015fd)

**How to reproduce:**

**How it should work:** The direction the player is facing should determine the ability to cast a spell. Also rockets should dmg only the demolishers and people on the ground, passengers, not at all.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
