### ISSUE TITLE
[CORE] PoW Zone Duel Bugs

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1517]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** PoW Zone Duels have some gimmicks that need to be ironed out:

1) The unit collision boxes on NPCs act as invisible Pillars blocking LoS, and movement, making it pretty annoying to duel around.
2) CDs, and HP / Resources don't reset automatically, though phasing works fine.
3) Spells / Items that are not usable in arena are usable in duels

**Comment by Riztazz** [comment]
Fixed collision, 2 is a config value, asked Gaga to update it for POW
3 sounds silly, but im gonna confirm with others and implement if needed
will close once it's live
