### ISSUE TITLE
[CORE] Items Missing Stats

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1518]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Some Savage Items are still missing stats:

![image](https://github.com/user-attachments/assets/13177316-e235-45b4-8a6b-4f3be122e3ad)
![image](https://github.com/user-attachments/assets/914565a9-7763-4da3-99fc-24a4e1649e19)
![image](https://github.com/user-attachments/assets/8da74d56-4c1d-4976-a8e6-1c6d81c05a1e)
![image](https://github.com/user-attachments/assets/8713d169-3135-4cee-b451-1a2ef66581a3)

**How to reproduce:**

**How it should work:**

https://www.wowhead.com/wotlk/item=42517/savage-gladiators-piercing-touch
https://www.wowhead.com/wotlk/item=42343/savage-gladiators-spellblade

Totem should function as Totem in terms of casting totem spells.

Thrown should function as thrown equipped in terms of casting the thrown attack.

**Database links:**

**Comment by Riztazz** [comment]
Are those all the items that are missing the stats?

**Comment by Riztazz** [comment]
Actually they do, please delete your cache folder
![image](https://github.com/user-attachments/assets/cf798c8c-d281-4c18-8d84-609228715359)

**Comment by Riztazz** [comment]
The only item that is missing stats is 42448, 142448 missing stats spellpower 28, gonna close once it's live

**Comment by UltraNix** [comment]
Fixed.
