### ISSUE TITLE
[PARTIALLY FIXED] messages sent with SendAddonMessage() are incorrectly blocked

### ISSUE THREAD

**Issue by oomshroom** [gamefreedomgit/Frostmourne#152]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Currently, messages sent using SendAddonMessage() are incorrectly blocked by the server: they get blocked if they contain characters with byte values above 127 (from my testing).
Addon messages should be allowed to contain any character excluding '\0'.
**This breaks some addons, notably the widely used LibHealComm.**

**How to reproduce:**
watch for CHAT_MSG_ADDON
this works fine and results in an event firing:
/run SendAddonMessage("a", "a\127", "WHISPER", UnitName("player"))
this does not work and does not result in an event firing:
/run SendAddonMessage("a", "a\128", "WHISPER", UnitName("player"))

**How it should work:**
Addon messages should be allowed to contain any character excluding '\0'.

**Database links:**
[https://wowwiki-archive.fandom.com/wiki/API_SendAddonMessage](https://wowwiki-archive.fandom.com/wiki/API_SendAddonMessage)
"except NULL (ASCII dec-ID 0) all characters (decimal ID 1-255) are allowed (in opposition to [SendChatMessage](https://wowwiki-archive.fandom.com/wiki/API_SendChatMessage) where many characters are disallowed)"

[https://wowpedia.fandom.com/wiki/API_C_ChatInfo.SendAddonMessage](https://wowpedia.fandom.com/wiki/API_C_ChatInfo.SendAddonMessage)
"All characters (decimal ID 1-255) are permissible except NULL (ASCII 0)."

**Comment by oomshroom** [comment]
NOT FIXED!
The applied fix only addressed messages sent to "WHISPER". Messages send to "RAID" and "PARTY" (and probably the other distributions as well, haven't tested) are still blocked in the same way -- 127 and below works, 128 and above doesn't.

/run SendAddonMessage("a", "a\127", "RAID")
vs
/run SendAddonMessage("a", "a\128", "RAID")

**Comment by Afgann** [comment]
fixed
