### ISSUE TITLE
ERW - Not Reseting after a boss kill in 10 asc.

### ISSUE THREAD

**Issue by Eradicatepls** [gamefreedomgit/Frostmourne#1520]
I don't know it's every time, or if there is a TTK component in deciding if yes or no you reset cooldown but ERW doesnt seems to reset at every encounter, i can guarantee it didn't atleast on like 3/4 bosses i did this afternoon.

**Comment by UltraNix** [comment]
You mean Empower Rune Weapon?

**Comment by Eradicatepls** [comment]
Yes, Empower Rune Weapon

**Comment by Piootrek** [comment]
Where it didn't reset for you? I checked few bosses and everywhere it works correctly

**Comment by UltraNix** [comment]
No further info - closing.
