### ISSUE TITLE
Boss Resisting damage ? 

### ISSUE THREAD

**Issue by Eradicatepls** [gamefreedomgit/Frostmourne#1522]
Loatheb :
https://gyazo.com/ed5c198b78d00ef7714b2d85d55e83c0
https://gyazo.com/8ed3d0a0fa6cda9a7b131273ffa5eb87
https://gyazo.com/8dbb5e8fc45e5d1887ffb27626796bb8
https://gyazo.com/a4ea49cef28aa6c86d63af2fa6dae238

Saphiron :
https://gyazo.com/0b431cc73625b7e14dc7af54cbe8d421
https://gyazo.com/f6438e26987055a83ca6ec24a45ebc0f
https://gyazo.com/ec81e8898a736fa5175a84676e760be3

Go Spell pene cap i guess ? Is it a known issue ?

**Comment by Manpower99** [comment]
Partial resists are not a bug.

**Comment by Eradicatepls** [comment]
Yeah true. It's just my addon showing them as a total. It's indeed partial resist.
