### ISSUE TITLE
Bug path of war "Español"

### ISSUE THREAD

**Issue by Chemavenegas77** [gamefreedomgit/Frostmourne#1524]
Buenas tardes 
Los jugadores del path of war están teniendo una gran ventaja gracias a un bug 
El cual consiste en que las monturas ignoran los.lugares cerrados es decir no se desmontan
Cómo ejemplo al pasar por el túnel de Garganta grito de guerra los player de path of war siguen montado en las monturas por más que ahí no se pueda usar 
Ya hice el testeo con un amigo y solo pueden aprovecharlos los pj insta 80 
Wotlk 
![IMG_20240803_111600_137](https://github.com/user-attachments/assets/c37f44f1-ba08-46b1-9641-c86f9697ac19)
Ahí en la imagen que proporciono se ve claramente mi pj y otro path of war 80 dentro de un lugar cerrado el cual no se puede usar la montura 
Arreglen eso antes que los demás player acusen de hacks a los demás path of war

**Comment by UltraNix** [comment]
@Chemavenegas77 Please - translate to english.

**Comment by WhitemaneIsa** [comment]
> @Chemavenegas77 Please - translate to english.

It's about POW being able to mount in BG tunnels eg. Warsong Gulch Tunnel
