### ISSUE TITLE
[MAGE] Water Elemental Immune to Frost Dmg

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1525]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Currently Mage's Summoned Water elemental is Immune to frost school abilities, and effects.

**How to reproduce:**

**How it should work:** No player controlled stuff that can be used in arena is immune to anything by default. It'd totally render stuff unplayable. Pvp is chess, not roleplay stuff

**Database links:**

**Comment by Manpower99** [comment]
https://www.youtube.com/watch?v=nxPyU7tCVTQ
this od vod where ele wasnt taking any damage from sapph's frost aura and a wowhead [comment ](https://www.wowhead.com/spell=31687/summon-water-elemental#comments:id=545993)pretty much confirm it should be frost immune.

apparently even its AI is supposed to be intelligent and won't attempt to cast on frost immune (other water elemental) targets
[here](https://www.wowhead.com/spell=31687/summon-water-elemental#comments:id=1046269)

**Comment by haephaistoss** [comment]
I do recall this not working with DK frost fever, at least in terms of application, the debuff could be applied. It may have something to do with the other bug then, that frost fever got applied in weird circumstances.

It was a common tactic while playing DK, to dot water elemental if mage wasn't paying attention and heal yourself through death strikes, and pestilence spread diseases after death gripping him closer.

I'll try to sweep through videos of old.

I don't remember actual DMG tho, if what you propose is true, even chains of ice  application could be denied then, which I oddly not remember being the case, it may have been a special interaction then, or simply a bug blizz never gave a fuck to fix before later

**Comment by haephaistoss** [comment]
https://youtu.be/AneH1dAtbto

0:54 - water elemental is clearly seen frozen in place. If it was truly immune - which it isn't, and shouldn't be, that would be impossible.

It is cata, but in competitive PvP complete and permanent immunity is a nono

![image](https://github.com/user-attachments/assets/d2a10a35-e6ee-4b83-abf1-c64c5db9d44f)

**Comment by Riztazz** [comment]
https://www.youtube.com/watch?v=CwVYncsjeqg
5:10, you can see the combat log, Water Elemental is Immune

**Comment by Manpower99** [comment]
> https://www.youtube.com/watch?v=CwVYncsjeqg 5:10, you can see the combat log, Water Elemental is Immune to frost nova, the quality is crap but you can figure out what it says
> 
> I will need a definite wotlk video otherwise we will close this

Elementals pre cata were always immune to their own spell school so yeah, Cata removed this immunity and you can even see it in many elementals in their patch notes in Molten Core losing fire immunity etc.
