### ISSUE TITLE
[CORE] Auras Stay on Target After Leaving Group

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1526]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Auras currently stay on players if they leave the group in which they got the aura applied on them.

**How to reproduce:**

**How it should work:** Auras should get removed once players are no longer present in the caster's group. Same applies if the caster leaves the group, their applied aura should be removed from the remaining group members.

**Database links:**

**Comment by UltraNix** [comment]
Never heard about it.
Please - provide some sources.

**Comment by UltraNix** [comment]
No further info - closing.
