### ISSUE TITLE
Thorns wrong tooltip or wrong rank scaling.

### ISSUE THREAD

**Issue by za-x-az** [gamefreedomgit/Frostmourne#1528]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Casting Rank 8 Thorns on a low lvl player gives Thorns rank 2 tooltip but damages like it rank 8

**How to reproduce:**
cast thorns on a low lvl char like lvl 1 or 10 or any lvl really.

**How it should work:**
it should display propper tooltip of the rank it cast, or the dmg should match the rank that was casted.

**Database links:**
Rank 8: https://www.wowhead.com/wotlk/spell=53307/thorns
Rank 2: https://www.wowhead.com/wotlk/spell=782/thorns

![image](https://github.com/user-attachments/assets/2d5b54a9-05d5-4038-897f-66ffa7fe6d57)
![image](https://github.com/user-attachments/assets/952d0d51-0caa-469c-a03c-b933c57e9373)

**Comment by Nihaobeachez** [comment]
With 3.1 Thorns was changed to scale with Spellpower. You can even boost it more with skilling improved Thorns etc, its a well known speedleveling strat for a long time.

https://www.youtube.com/watch?v=IQ9bZozClHQ

**Comment by UltraNix** [comment]
Just tested and works okay.
![image](https://github.com/user-attachments/assets/a74c1a29-6616-430a-b027-f604c77cca48)
