### ISSUE TITLE
[Quest] The Disruption Ends

### ISSUE THREAD

**Issue by Savageferret** [gamefreedomgit/Frostmourne#153]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
The quest [The Disruption Ends](https://www.wowhead.com/wotlk/quest=872/the-disruption-ends) should be available after turning in [Disrupt the Attacks](https://www.wowhead.com/wotlk/quest=871/disrupt-the-attacks). Right now, it's only available after [Supplies for the Crossroads](https://www.wowhead.com/wotlk/quest=5041/supplies-for-the-crossroads), when it should be able to be picked up along side it.

**How it should work:**
Turn in disrupt the attacks, quest giver should then offer the 2 quests above

**Database links:**
https://www.wowhead.com/wotlk/quest=5041/supplies-for-the-crossroads#comments:id=2964923

**Comment by Godmatik** [comment]
Yes I also noticed similar.

Related issue:
https://github.com/gamefreedomgit/Frostmourne/issues/115

Supplies for the Crossroads quest should be available immediately at level 9 with no pre-req necessary

**Comment by Afgann** [comment]
fixed
