### ISSUE TITLE
Eoe10 ascend loot

### ISSUE THREAD

**Issue by Fegyox** [gamefreedomgit/Frostmourne#1530]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
We just killed eoe10 ascended and it didnt drop any 25 man loot just 2 10man loot.
![bug](https://github.com/user-attachments/assets/63d0e834-f018-4d81-9ba3-37fb6857974e)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by WhitemaneChronus** [comment]
You have 50% chance in EoE 10 Ascended to get 226 item, otherwise you get another 213.

Malygos
Item (213 iLvl)
Item (50% for 213 iLvl, 50% for 226 iLvl)
