### ISSUE TITLE
Healing Potions Bugged

### ISSUE THREAD

**Issue by DarthLordVoid** [gamefreedomgit/Frostmourne#1532]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

Oddly I got this fixed but spam clicking on a bunch of different potions in my inventory Lion's, Minor Defense, Troll's Blood and then the CD appeared on the health potions so I tried one and it worked so I truly have no what the heck that's about but hope that helps you figure out the problem.

**Description:**
Healing Potions acting like I've recently used one but haven't and no matter how long I wait nor what I try to do to fix it I just can't use them. Game just keeping saying you cannot use that right now or something like that.

**How to reproduce:**
No idea, sorry but I don't know what started it as they worked fine for me earlier today. Logged on set out like normal and went to use one can't keep getting told what it says when they're on CD but they shouldn't be on it, other types of potions work just fine just not health potions.

**How it should work:**
Well potions have cooldown timers between being able to use them but that's after you use one, I didn't yet game seems to think that I have and no matter how long I wait it won't let me use a health potion. Yet A Lion's potion worked just fine it's seemingly just health restore potions. I've tried the Minor the Lessor and Healing Potion the first 3 tiers of healing potions I believe and all acting like they're on cooldown but they're not on CD as I haven't used one yet tried lots of things all expect reinstalling the game in whole might try that but doubting it'll fix. Hopefully it's a easy fix but thanks, good luck.

**Database links:**

**Comment by Riztazz** [comment]
It's troll's blood that was causing the issue for you, pushing a fix for it

**Comment by nzxtnemesis** [comment]
Can you revert that change the server is hosed up. No one can play lol
