### ISSUE TITLE
scourgebane elixirs

### ISSUE THREAD

**Issue by Requiemafk** [gamefreedomgit/Frostmourne#1534]
Description: Scourgebane infusion and scourgebane draught are elixirs that only horde can use (because a quest in tranquillien) this elixir can use in PVE against undead (naxx and icecrown) and its usable with potion and flask at the same time. that means an advantage for horde players, this item is soulbound.

How it should work: My suggestions are: 
1. Create a similar quest for alliance players with same reward
2. Make the elixirs don't soulbound to trade or sell it on AH
3. Make the item non usable in PVE like the beer from Dire Maul North

Database links:
https://www.wowhead.com/tbc/item=22779/scourgebane-draught
https://www.wowhead.com/tbc/item=22778/scourgebane-infusion

**Comment by UltraNix** [comment]
If it's a suggestion or some OoL improvemenet - make a thread on Discord.
No bug here.
