### ISSUE TITLE
Judgement Not Spreading

### ISSUE THREAD

**Issue by Aar0nzy** [gamefreedomgit/Frostmourne#1535]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

The Paladin spells _Judgement of Light_, _Judgement of Wisdom_ and _Judgement of Justice_ when used on harmful targets places a magical debuff on that target for 20 seconds. Upon using any of these spells to a different target within 20 seconds of the previous use, the magical debuff is removed. This should not occur.

To reproduce this bug, use _Judgement of Light_, _Judgement of Wisdom_ or _Judgement of Justice_ as a Paladin on a harmful target. Within 20 seconds before the target's magical debuff from Judgement has expired, use _Judgement of Light_, _Judgement of Wisdom_ or _Judgement of Justice_ on a **different** harmful target. Notice that the debuff from Judgement on the previous target has been removed.

The debuff should persist even when Judgement is used on a different target for the full duration. Some helpful evidence showing how it should work can be found here: https://github.com/azerothcore/azerothcore-wotlk/issues/13340 and in a WotLK classic video of a player doing it at _time = 0:18_ here: https://www.youtube.com/watch?v=G7kde1Roma0.

https://www.wowhead.com/wotlk/spell=20186/judgement-of-wisdom
https://www.wowhead.com/wotlk/spell=20185/judgement-of-light
https://www.wowhead.com/wotlk/spell=20184/judgement-of-justice

**Comment by Chaos-within** [comment]
On the spell itself: "Only one Judgement per Paladin can be active at any one time."

**Comment by Aar0nzy** [comment]
> On the spell itself: "Only one Judgement per Paladin can be active at any one time."

Yes, you cannot have both Judgement of Light and Judgement of Wisdom on the **same** target within 20 seconds, of course. You are misinterpreting the text tooltip; just like another person did in the azerothcore post. I am not demanding that Paladins should be able to use a mixture of Judgements (i.e. Judgement of Light and Judgement of Wisdom) on the same target and place a mixture of both debuffs simultaneously. In the situation where you are attacking the same harmful target, the previous debuff should be removed, as per the tooltip. When it comes to judgement spreading, the previous debuff should not be removed. Please check the evidence that I linked as this is covered.

**Comment by Manpower99** [comment]
Yup can confirm it also, this is a common misconception on how judgement debuffs work in private servers.
trying to have JoL on two targets with one paladin atm is impossible.

**Comment by Godmatik** [comment]
Confirmed.

You can not apply more than one of your judgements on a specific target
But you should still be apply to another judgement to a separate target at the same time.

The wording of the spell is a bit confusing, but classic has proven it does function this way.

**Comment by Afgann** [comment]
fixed
