### ISSUE TITLE
Killing Spree is not jumping properly, sometimes not doing any damage - sometimes completely stops jumping when a mob dies.

### ISSUE THREAD

**Issue by Tetrahydrx** [gamefreedomgit/Frostmourne#1536]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Killing spree more often than not, doesnt jump properly. Doesnt do the 5 hits as intended and doesnt jump to another mob after a mob dies in dungeons for example. 

https://github.com/user-attachments/assets/644723df-103b-4811-a3a3-28a4ed521fef

**How to reproduce:**
Press Killing Spree on target dummies in Orgrimmar I guess

**How it should work:**
It should jump and do 5 "assaults" - during those assaults, autoattacks should still be happening.

**Database links:**
https://www.wowhead.com/wotlk/spell=51690/killing-spree

**Comment by Tetrahydrx** [comment]
Seems to be fixed after server restart today. Thanks!

**Comment by Afgann** [comment]
fixed
