### ISSUE TITLE
druid dash skill

### ISSUE THREAD

**Issue by Macilious** [gamefreedomgit/Frostmourne#1537]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Dash skill in druid , it's suppose to be turned off/dimed/unavailable to click , when in any form other than cat , also you can use it in travel but it won't increase the speed, that's why it's suppose to be locked into cat form which what the description says.

**How to reproduce:**
just use any form in druid and the skill will still clickable but no effect .

**How it should work:**
it shouldn't be available/clickable/possible to activate in any form other than cat

**Database links:**

**Comment by UltraNix** [comment]
You can activate it in normal form and then shapeshift into cat form and still benefits from it.
Dash acitvation is not limited to cat form.
It was fixed on Legion;
`
(2016-07-22): Prowl and Dash can now be activated while the Druid is in Cat Form or Bear Form.
`
No bug here.
