### ISSUE TITLE
Bug Server - shit Server

### ISSUE THREAD

**Issue by BuizzyGER** [gamefreedomgit/Frostmourne#1538]
Ich kann nicht empfehlen auf dem server zu spielen. Es gibt nur wenige dinge, welche nicht buggy sind. Angefangen beim scaling der Pets, über das scaling von druiden. Weiter gehts, dass buffs, welche nicht dispellbar sind einfach dispellt werden können. Resi funktioniert nicht, genauso wie alles andere.
Ausserdem stirbt der Server an Spielern aus, leute welche offentsichtlich Scripts am laufen haben werden nicht gebannt um Spieler auf dem Server zu halten. 

Traurige angelegenheit. Sucht euch einen anderen Server aus, der den Fokus nicht auf neue Bezahlmethoden legt, sondern auf vernünftiges Gameplay... bin raus ihr noobs!

**Comment by BuizzyGER** [comment]
I cannot recommend playing on the server. There are only a few things that are not buggy. Starting with the scaling of pets and the scaling of druids. It goes on that buffs, which are not dispellable, can simply be dispeled. Resi doesn't work, just like everything else.
Also, the server is dying of players, people who obviously have scripts running are not banned to keep players on the server. 

Sad affair. Find another server that doesn't focus on new payment methods but on reasonable gameplay... I'm out you noobs! 

Translated with DeepL.com (free version)

**Comment by WhitemaneIsa** [comment]
Good riddance
