### ISSUE TITLE
ZulAman - Time Reward Chest (Chest number 3)

### ISSUE THREAD

**Issue by Mlynasek** [gamefreedomgit/Frostmourne#1540]
**Description:**
Chest number 3 ( https://www.wowhead.com/tbc/object=186667/krazs-package ) didnt respawn after kill boss. Friendly NPC https://www.wowhead.com/npc=24024/kraz is dead all time. NPC should be alive and after interacting with "Kraz" should spawn up a chest. Chest number 1 and 2 working properly.

**How to reproduce:**

**How it should work:**
After killing the boss within the time limit after interacting with "Kraz" a chest should spawn up.

**Database links:**

**Comment by yeagerca** [comment]
#1457
