### ISSUE TITLE
The Amphitheater of Anguish: From Beyond!

### ISSUE THREAD

**Issue by WhitemaneIsa** [gamefreedomgit/Frostmourne#1541]
**Description:**
Azbarin doesn't count as kill credit.

**How to reproduce:**
Take quest and have Azbarin spawn

**How it should work:**
Azbarin should give credit too.

**Database links:**
https://www.wowhead.com/wotlk/quest=12934/the-amphitheater-of-anguish-from-beyond
https://www.wowhead.com/wotlk/npc=30026/azbarin-prince-of-the-gust

**Comment by PanJanuszek** [comment]
Cannot reproduce
