### ISSUE TITLE
Bugged Quest - NPC missing dialogue - Quest 5742

### ISSUE THREAD

**Issue by Althora** [gamefreedomgit/Frostmourne#1543]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Speaking to NPC Tirion Fordring after accepting quest Redemption is supposed to have dialogue options to "Listen to a tale". dialogue option to continue is missing.
QuestID: 5742
Location: Eastern Plaguelands

**How to reproduce:**
Attempt the quest
**How it should work:**
Be able to continue dialogue.

**Database links:**
https://www.wowhead.com/wotlk/quest=5742/redemption#videos:id=220395

**Comment by Chaos-within** [comment]
It requires the player to /sit, which should have been removed some point before WOTLK.
