### ISSUE TITLE
Devouring Plague coefficient?

### ISSUE THREAD

**Issue by Stancone** [gamefreedomgit/Frostmourne#1545]
DP coeffs fix:

Hello, the value 0.185 is wrong, it's most likely from the first iteration of WOTLK, the correct one from patch 3.2 is 20%. 
Also, naked testing is irellevant IMHO, if you say the values were correct where was the problem? Spellpower/Gear is in the game to affect spells/ abilities. 

And, wowhead is well known to provide bullshit data.

Please see relevant links: 
1. Announcement of DP coefficient change: https://wowwiki-archive.fandom.com/wiki/Patch_3.0.3
2. Correct value: https://wowwiki-archive.fandom.com/wiki/Spell_power_coefficient 20% in change 3.2.0

Please address this issue.

_Originally posted by @Stancone in https://github.com/gamefreedomgit/Frostmourne/issues/1455#issuecomment-2275759151_

**Comment by UltraNix** [comment]
Even on classic it's 0.185.
The value is taken from 3.3.5 DBC(aka Blizzard) files.

![image](https://github.com/user-attachments/assets/7d6e4261-bd78-4d71-8f24-ee8218a840fb)

There is no bug here.
