### ISSUE TITLE
Path of War's wands not having an actual range distance

### ISSUE THREAD

**Issue by jojofx87** [gamefreedomgit/Frostmourne#1547]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
All the Savage Gladiator wands from the vendor in the Path of War's island can only be used in melee range instead of normal cast range (30+ yards).

I don't know if Hateful and Deadly wands have same problem.

**How to reproduce:**
Create a caster class for Path of War and buy a savage gladiator wand to test on dummies.

**How it should work:**
The wand should allow to attack from far distance and not only melee range.

**Database links:**
https://www.wowhead.com/wotlk/item=42448/savage-gladiators-touch-of-defeat

**Comment by Piootrek** [comment]
Fixed. Remember to delete the cache directory after server update to make it effect
