### ISSUE TITLE
Obsidian Sanctum, drakes respawn on wipe

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1548]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

As of now, if players kill a drake **after** engaging Sartharion and then wipe, they are saved to that raid and the drake wont respawn on next attempts. 

Based on player reports so far, there is a mixed behavior as in sometimes they will respawn and sometimes they wont.
However none of the drakes respawned in any of our tries on PTR. 

Notice that if a drake dies without engaging Sartharion, it should not respawn.

**How to reproduce:**

Pull sartharion, damage it until he calls a drake down, kill the drake and wipe.

**How it should work:**

I cannot find another resource on this matter except the comment on wowhead. Therefore I would like you to kindly take a look into this as getting saved for a failed attempt doesn't seem right.
In case of respawn, if the drakes are killed in this way (upon Sartharion calling them and not engaging them beforehand) players shouldnt receive emblems from those drakes. (which is how it works on PTR atm)
**Database links:**

https://www.wowhead.com/wotlk/npc=28860/sartharion
![Screenshot 2024-08-08 124301](https://github.com/user-attachments/assets/7f6106ac-e559-451f-9eff-540f22de4cd9)

**Comment by Manpower99** [comment]
Does happen on live also.

**Comment by Aeradel** [comment]
I have also had these drakes become untargetable in conjunction to this issue.

**Comment by yeagerca** [comment]
Tenebron did not respawn after my failed 3D attempt (10 Ascended). I was told that someone else's group on the same day was able to respawn Tenebron by evading Sartharion during a 2D attempt where Vesperon was killed before the fight (difficulty unknown).

**Comment by WhitemaneChronus** [comment]
Summarizing current issues and adding new ones:

- Drakes who are killed after engaging Sarth wont respawn on wipe
- Sometimes Drakes or Whelps spawn on top of the boss after a wipe
- Sometimes Drakes wont be targetable after getting called by Sarth
- Encounter in progress after a wipe, players are unable to move in

Drakes referring to [Vesperon](https://www.wowhead.com/wotlk/npc=30449/vesperon), [Tenebron](https://www.wowhead.com/wotlk/npc=30452/tenebron), and [Shadron](https://www.wowhead.com/wotlk/npc=30451/shadron)

**Comment by Manpower99** [comment]
Defeating sartharion should also despawn the portal and all mobs inside it, anyone who's still inside should be ported out.

**Comment by Piootrek** [comment]
> Sometimes Drakes or Whelps spawn on top of the boss after a wipe
> Sometimes Drakes wont be targetable after getting called by Sarth
I wasn't able to reproduce those bugs. If they still happen please make a new report with full fight video. Other bugs are fixed.

**Comment by Zipica** [comment]
One guy told me they were alive after paladin used DI on some healer. So I guess maybe that was making problem?

**Comment by WhitemaneIsa** [comment]
> One guy told me they were alive after paladin used DI on some healer. So I guess maybe that was making problem?

Unlikely.

**Comment by WhitemaneChronus** [comment]
![image](https://github.com/user-attachments/assets/c0c0ef41-7f04-421d-af54-1e97788e11c8)

Players engaged Sartharion and killed 3 drakes but they wiped.
all 3 are alive now (even the one you cannot see in this picture, i can confirm drakes and the boss are alive)
but players got id.

**Comment by Manpower99** [comment]
> ![image](https://private-user-images.githubusercontent.com/170808156/361168712-c0c0ef41-7f04-421d-af54-1e97788e11c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1NDk1OTksIm5iZiI6MTcyNDU0OTI5OSwicGF0aCI6Ii8xNzA4MDgxNTYvMzYxMTY4NzEyLWMwYzBlZjQxLTdmMDQtNDIxZC1hZjU0LTFlOTc3ODhlMTFjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNVQwMTI4MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGQzZGRlOWIxNTk5MmFlZDg3MTc2OTc2NjY3MGZlYzg1YmZlYWVmOWYyYjEwMjE1NjU3ZDM1N2QwOWZiODRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yguy7PPZsXFjadEBnaLvsWrwo0UfDB4nw2wnT-MVAnY) ![image](https://private-user-images.githubusercontent.com/170808156/361168968-ee9be64e-f796-42ad-8ab8-dd7be70a4ef2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1NDk1OTksIm5iZiI6MTcyNDU0OTI5OSwicGF0aCI6Ii8xNzA4MDgxNTYvMzYxMTY4OTY4LWVlOWJlNjRlLWY3OTYtNDJhZC04YWI4LWRkN2JlNzBhNGVmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNVQwMTI4MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGFiNjRlYzJhYzIwZDUzM2M1ZGRiYzM2MDRiYjY3Y2NkMWY2NjIxZjcyMzIyZjc3MDhlYjgyZjI0MGEzNjI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R3ilj1TR8fX4mO4AHGfbDq3x0DEFDyz75UMHJPQ_vO0)
> 
> Players engaged Sartharion and killed 3 drakes but they wiped. all 3 are alive now (even the one you cannot see in this picture, i can confirm drakes and the boss are alive) but players got id.
> 
> While players can continue on this id, in case a raid disbands its inconvenient to join fresh groups later.

Happened to me an hour ago also, can fully confirm it still happens.

**Comment by Piootrek** [comment]
Fixed
