### ISSUE TITLE
Warlock Decimation bug

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#1549]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Decimation won't proc if the warlock has the hand of protection buff from a paladin

**How it should work:**
It should proc anyway

https://youtu.be/0KUZsI-XJVE

**Comment by Afgann** [comment]
fixed
