### ISSUE TITLE
Bugged Quest: Valduran the Stormborn (Part 1 of 2)

### ISSUE THREAD

**Issue by Naloomi** [gamefreedomgit/Frostmourne#1551]
**Description:**
When starting the fight with Valduran and blowing the war horn the 2 NPC's that are supposed to show up to assist do not show up, or show up way late.
Mid (GM) also blew home when I reported this in game, and they did not show up. 

**How to reproduce:**
Start fight with NPC and blow horn

**How it should work:**
NPC's should appear after blowing the horn

**Database links:**
https://www.wowhead.com/wotlk/quest=12984/valduran-the-stormborn

**Comment by Althora** [comment]
NPC's which are to assist you with this fight indeed spawn after a long delay. However, once the NPC engages the boss in combat, it locks you out of the fight preventing you from killing the boss.
