### ISSUE TITLE
Missing stats on items

### ISSUE THREAD

**Issue by laimewow** [gamefreedomgit/Frostmourne#1554]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Missing stats on the following items:
Savage Gladiator's Piercing Touch - missing spellpower and spell penetration
Savage Gladiator's Touch of Defeat - missing spellpower
Savage Gladiator's Shanker - missing attack power

**How to reproduce:**
Get correspoding items

**How it should work:**
As described at the database

**Database links:**
https://www.wowhead.com/wotlk/item=42517/savage-gladiators-piercing-touch
https://www.wowhead.com/wotlk/item=42448/savage-gladiators-touch-of-defeat
https://www.wowhead.com/wotlk/item=42216/savage-gladiators-shanker

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/1518
