### ISSUE TITLE
(PTR) Thorim 10 arena + gauntlet

### ISSUE THREAD

**Issue by NNassib336** [gamefreedomgit/Frostmourne#1555]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

This is from the arena point of view:

The gauntlet seems fine (probably too easy but this is post-nerf difficulty here), but the arena is unnecessarily difficult and darn near impossible without a disarm. 

-Dark Rune Champions seem to use their abilities too often. Charge into whirlwind is almost always an instant kill, and happened every single pull we did. I get that we can disarm but not every 10m comp has a disarm (ours didn't), plus when 2 spawn at the same time it's even worse. Adding a small cd between abilities would help. I believe there should also be a greater delay between when the Champion spawns and when it should use whirlwind, but no proof of this. I just don't remember it using the ability if we killed it quick enough.
*AND/OR*
Dark Rune Champions currently do ~2-3x the damage they're supposed to do. Charge and whirlwind are supposed to do just over weapon damage but charge is doing ~9k and whirlwind 10k+
https://wotlk.evowow.com/?npc=32922
https://www.wowhead.com/wotlk/npc=32876/dark-rune-champion#abilities;mode:n10

-Besides the commoners, we shouldn't get 2 of the same add in a single wave. No proof and I might be misremembering, hopefully someone can confirm one way or the other.

-All arena adds seem to be using their pre-nerf versions even on 10 normal. If this is intended, that's fine. Still worth pointing out, though.
https://wotlk.evowow.com/?npc=32922
https://wotlk.evowow.com/?npc=32876

Before anyone says "iTS sO EaSy" - the intent is to align the encounter with post-nerf difficulty, not to complain about how difficult it is.

**Comment by Afgann** [comment]
fixed
