### ISSUE TITLE
dodged Slam doesn't enable Overpower

### ISSUE THREAD

**Issue by taralej90** [gamefreedomgit/Frostmourne#1556]
**Description:**
When Slam gets dodged or parried, it doesn't enable Overpower.

**How to reproduce:**
Grab a rogue, tell them to pop Evasion, cast Slam. Overpower will not flash.
Grab a hunter, tell them to pop Deterrence, cast Slam. Overpower will not flash (even though it's glyphed).

**How it should work:**
Just like with any other ability, getting a dodge (or parry with glyph) on Slam should enable Overpower.

**Database links:**
https://www.wowhead.com/wotlk/spell=7384/overpower
https://www.wowhead.com/wotlk/spell=47475/slam

Obviously, this is a huge hit for Arms PvE before you get expertise-capped, as well as for leveling Arms. I have noticed that when Slam gets dodged or parried, it doesn't even register in the combat log, which may have something to do with the issue...

**Comment by taralej90** [comment]
Update: tested with hunter's Deterrence. Slam also doesn't enable Overpower when parried... Same as with dodge, it doesn't even register in the combat log.

**Comment by yeagerca** [comment]
Try using the `/combatlog`command to see what event is being sent.
