### ISSUE TITLE
Mob aggro and roots

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1557]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Currently on whitemane if a mob is rooted his target selection remains the same regardless of it's access to its targets who are in the aggro list.
If certain abilities impair the access of the mob to its higher threat-ranked targets (e.g., [root](https://wowpedia.fandom.com/wiki/Root) spells like Entangling Roots or Frost Nova), the mob should attack the highest threat-ranked target in its ability range (usually visible for melee mobs or [silenced](https://wowpedia.fandom.com/wiki/Silence_effect) casters, which have a combat range of 5 yards)

This is something that can be noticed in bossfights such as Deathbringer Saurfang with his beasts doing very high damage to targets within their melee range whenever they get frost nova'd, which is why the way the bossfight gets done in a blizzlike setting is by slowing/stunning the mobs to kite and kill/burst asap and not rooting them since that would kill the players within their melee range.

Another boss is Freya and her wave of adds which are always stunned/typhooned and never rooted to prevent them meleeing targets within their melee range. notably the Snaplasher is always slowed and never rooted/frost nova'd for this reason.

**Database links:**

**Comment by Manpower99** [comment]
Any chance this gets fixed prior to ulduar? it does affect some bosses in it.

**Comment by Riztazz** [comment]
We currently have no way to define what is a ranged creature in core so sadly this will be put on hold, i'll have to think how to go about it

**Comment by Manpower99** [comment]
> We currently have no way to define what is a ranged creature in core so sadly this will be put on hold, i'll have to think how to go about it

Possibly by its ability to melee/cast spells, since Shoot is technically a spell id idk. but alright thank you for the response.

**Comment by Riztazz** [comment]
Not as simple as it sounds

**Comment by Riztazz** [comment]
Ok that was quick, we came up with a solution, i'll implement it tomorrow

**Comment by Manpower99** [comment]
> Ok that was quick, we came up with a solution, i'll implement it tomorrow

You're a lifesaver thank you riz!

**Comment by Riztazz** [comment]
Fix is coming, we just gotta figure out a few things;p

**Comment by Riztazz** [comment]
fixed, will close once it's live

**Comment by Manpower99** [comment]
> fixed, will close once it's live wish me luck;p

i'll keep u updated on if this, thanks alot!

**Comment by Manpower99** [comment]
So far works pretty well.
