### ISSUE TITLE
Outlands Cooking Daily not giving cooking plans

### ISSUE THREAD

**Issue by Lemmy-90** [gamefreedomgit/Frostmourne#1562]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The outlands cooking dailies are supposed to give cooking plans in the meat crate / fish barrel rewards. I've done the daily for 4 days and have not received a single plan. This reward is part of at least 2 achievements in the "Chef" title reward. "The Cake is not a lie" and "The Outland Gourmet"

**How to reproduce:**
Do the cooking daily "Revenge is Tasty" "Manalicious" "Super Hot Stew" or "Soup for the Soul" and after selecting your reward and opening the reward.

**How it should work:**
The reward for these quests should have a chance to give at least 1 of 6 cooking recipes.

**Database links:**

**Comment by Chaos-within** [comment]
The recipes are low drop-rates and the rewards do contain them.
https://www.wowhead.com/wotlk/item=33844/barrel-of-fish#contains

**Comment by PanJanuszek** [comment]
I have opened 10x barrels as a check, results:

![image](https://github.com/user-attachments/assets/28b7694f-9022-479b-b115-c18a56cf81d2)

So, according to recipe percentage, we do have even higher (12%) than retail (5%).

Not an issue then.
