### ISSUE TITLE
Soul Preserver + Lifebloom Interaction

### ISSUE THREAD

**Issue by Aeradel** [gamefreedomgit/Frostmourne#1565]
[Soul Preserver's](https://www.wowhead.com/wotlk/item=37111/soul-preserver) (37111) proc, Healing Trance, is improperly consumed on the bloom heal of Lifebloom.

This proc reduces your next **casted** heal's mana cost by 800. Lifebloom's bloom heal is not cast. This effect also has no change to the amount of mana refunded by Lifebloom at the end of it's duration.

![image](https://github.com/user-attachments/assets/aafc559b-485f-4487-991d-5ee8fb63ed08)

This was tested on the PTR, but has proven replicable in Live as well.

**Comment by Piootrek** [comment]
Do you have any better evidence of how it should work? Blizzard tooltips are usually not accurate.

**Comment by Aeradel** [comment]
I am unable to find evidence that this is intended or something that happens.

In instances like this one, it would be mentioned somewhere - usually Wowhead - by min-maxxers, but I can't find any resources warning Restoration Druids of this unintended mana reduction protentional being wasted.
