### ISSUE TITLE
(PTR) Freya 25N HC Loottable

### ISSUE THREAD

**Issue by Nihaobeachez** [gamefreedomgit/Frostmourne#1566]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**Freya25N HM dropped Mimiron25N HM Item. https://youtu.be/KgLAJK3s8tk?si=s6tVbfTxgWV0ln_p&t=4355
https://www.wowhead.com/wotlk/item=45494/deliriums-touch

**How to reproduce:** Kill Freya 25N HM Version

**How it should work:** https://www.wowhead.com/wotlk/item=45494/deliriums-touch should drop from Mimiron25 HM, not Freya

**Database links:**

**Comment by Afgann** [comment]
fixed
