### ISSUE TITLE
HC gold

### ISSUE THREAD

**Issue by GMtiedemanns** [gamefreedomgit/Frostmourne#1568]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
creating a level 1 character and sending it gold allows you to send it to another hardcore character.

**How to reproduce:**
create a level 1 character, send gold to it, make it hardcore, pick up gold from mail, send gold to Hardcore character.

**How it should work:**
should not be able to send Hardcore characters gold from normal characters.

**Database links:**

**Comment by scrublama** [comment]
can u do this with heirlooms too? xd

**Comment by Afgann** [comment]
fixed
