### ISSUE TITLE
Verdant Sphere - World buff incorrectly working outside TK

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1569]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
[Verdant Sphere ](https://www.wowhead.com/wotlk/item=32405/verdant-sphere#comments:id=121246) [Quest ](https://www.wowhead.com/wotlk/quest=11007/kaelthas-and-the-verdant-sphere)when turned in, applies a [world buff](https://www.wowhead.com/wotlk/spell=39953/adals-song-of-battle) to everyone in shattrath as it should.
However this buff works outside the intended instances, and works in other instances.
As the tooltip states it should only work inside the Tempest Keep Dungeons The Botanica, The Mechanar, and The Arcatraz.

**Database links:**
https://www.wowhead.com/wotlk/item=32405/verdant-sphere

**Comment by Manpower99** [comment]
@Piootrek verdant sphere world buff still bugged and abusable.
tested on ptr went into naxx with it and the damage amplification was there.

**Comment by Piootrek** [comment]
My bad, I disabled only a reputation part. Fixed.
