### ISSUE TITLE
DTR BOOMKIN 

### ISSUE THREAD

**Issue by Kult321** [gamefreedomgit/Frostmourne#157]
**Description:**
DTR does not work when there is a duplicate spell does not give eclipse power.

**How it should work:**
I found a video that should work like this, it can be seen at 49 seconds and at 1:50. It's better to watch the video at 0.25
Dragon Soul - Heroic Morchok Heroic 10 man - Boomkin 
https://www.youtube.com/watch?v=333Wzpd5ZDA

**Comment by Manpower99** [comment]
brother this is frostmourne, their wotlk realm.
