### ISSUE TITLE
[Combat] Cast success puts you in combat before spell lands

### ISSUE THREAD

**Issue by scrublama** [gamefreedomgit/Frostmourne#1570]
**Description:**
Very very often people prepull because of this bug and ruin gameplay for 24 others.

The behaviour is that creatures incl. bosses are putting you in combat immediately whenever: 
You or party/raid member succeds a hostile cast against the target even if it has a traveltime, its not taken into account. 

**How to reproduce:**
Cast lightning bolt/shadow bolt and see you get into combat immediately when spell finishes and before landing

**How it should work:**
Cast lightning bolt/shadow bolt and get in combat when target attacks

**Database links:**

**Comment by Piootrek** [comment]
Casting spell puts a player in combat but doesn't put a boss. That's blizzlike behavior. Please post a video if you have other experience
https://streamable.com/exvk29

**Comment by scrublama** [comment]
https://youtu.be/8ccCWjt_x_Q?si=icCwHZm9b2USNgf6&t=12

**Comment by Aeradel** [comment]
> Author

This doesn't really show what you mentioned. As Piootrek mentioned, a sucessful cast of a spell will put the player in combat, but not the target, until the spell lands.

**Comment by scrublama** [comment]
In case you missed let me clarify, hunter shots explosive shot and when it hits they enter combat

**Comment by Aeradel** [comment]
> In case you missed let me clarify, hunter shots explosive shot and when it hits they enter combat

Yes. A successful cast of a spell will put the player in combat, but not the target, until the spell lands.

**Comment by scrublama** [comment]
So what im trying to say the bug is: You enter combat before the spell lands here
In the video I linked they enter combat when the spell lands

**Comment by Piootrek** [comment]
I asked for the video from Whitemane server. As you can see on my video everything works correctly for me.

**Comment by scrublama** [comment]
https://gyazo.com/a5824707de2f7c106d8979d4340fc9a6 this is from Whitemane, and bug is u get in combat before spell lands

https://www.youtube.com/watch?t=12&v=8ccCWjt_x_Q this is from blizz, u get in combat after spell lands

**Comment by Piootrek** [comment]
Yes, as I mentioned before you get combat on cast, but a target gets combat when the spell lands. Closing.
