### ISSUE TITLE
(PTR) Boss frames for Ulduar

### ISSUE THREAD

**Issue by Covidisreal** [gamefreedomgit/Frostmourne#1571]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

Is there any chance you can implement properly working "boss frames" on multitarget fights like Kologarn and Mimiron? 

On Naxx PTR / release there were also no working boss frames on, for example, Sartharion, which made multidotting a bit more complicated (works now). But in Ulduar that option would be a really great QoL. 

Any chance you can make it work before actual release, so people can have easier time practicing on PTR?

**Comment by Afgann** [comment]
fixed
