### ISSUE TITLE
Soul preserver bug on druid

### ISSUE THREAD

**Issue by HosseinEkv** [gamefreedomgit/Frostmourne#1572]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When u cast lifebloom on urself and the trinket procs(healing trance) after lifebloom explodes ur trinket proc will go off also which it shouldnt cuz u didnt cast any healing its just the lifebloom poping

**How to reproduce:**

Get soul preserver(37111 itemID) then cast lifebloom on yourself till u proc the trinket after that dont so anything and u will see after lifebloom expire the trinket buff will disappear
**How it should work:**

**Database links:**

**Comment by GMtiedemanns** [comment]
https://www.wowhead.com/wotlk/item=37111/soul-preserver

**Comment by Aeradel** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/1565#issuecomment-2286391102
