### ISSUE TITLE
13/08/24 PTR Ulduar 10n

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1573]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
_Done with a fully random pug all with t7 bis._

**FL 10n HM:**
 1. worked fine overall small issues related to pushing ppl to perform shutdown, they sometimes fall to floor instead of being ontop of the boss. once someone also actually fell under the map.
 2. throwing pyrite on boss sometimes doesnt refresh/apply new stacks (the pyrite initial damage is taken by FL himself, meaning it wasnt missed and yet the debuff sometimes just doesnt work)

**Ignis 10n:**
  ~~1. Ignis is one of the bosses that should parry haste in both normal (postnerf) and heroic (prenerf). on multiple pulls consistent swing timer. meaning it is disabled on this server but it shouldn't be.~~ Potentially this one is incorrect, i know for a fact that the only boss that currently (Whitemane PTR) parry hastes on normal mode is Vezax but i cannot confirm if that is blizzlike or not besides proof that can no longer be viewed from Warmane's bugtracker. i will make a seperate report on parry hastes later.

 2. Ignis didnt spawn fire on floor for multiple pulls then randomly it started working again, basically unable to do the boss mechanic this way.
 
**Razorscale 10n :** 
while she was on floor her model's positioning was incorrect, but her hitbox somehow wasnt.
our feral was not able to shred from from the back but rather from the far side. 
relatively the feral's positioning is correct to how it should be(so her hitbox is correct) so its just a matter of model being placed incorrectly while she is pulled by harpoons to the floor.

**XT 10n HM:**
 1. Heart hitbox is quite massive you'd need to go quite backwards or you'd be in center of hitbox and unable to melee it.
 2. (this bug occured about a week ago but i forgot to report it). the damage from tantrum is percentage based physical damage that is not reduced by Armor. so under regular circumstances it should be the exact same damage every time, unless reduced by External auras. [Proof](https://classic.warcraftlogs.com/reports/14tgPHxNkqMJz6LW#fight=13&type=damage-taken&ability=62775&source=10&view=events)

**Kologarn 10n:**
Same issue as 25Man, players/pets able to use abilities such as Killing Spree from combat rogue / Leap from Ghoul Pets and Army

**Auriaya 10n:**
Feral Defenders were not stunnable but should be https://www.wowhead.com/wotlk/npc=33515/auriaya#comments:id=686611

**Iron Council:** 
ending encounter gave us combat bug. had to be fixed by hearthstoning entire raid out and using tele commands.

**Database links:**

**Comment by Afgann** [comment]
fixed
