### ISSUE TITLE
(PTR) Ulduar 25m Algalon Constellations

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#1574]
Constellations that are spawned are barely moving and are not coming to the ground while casting, thus making it nearly impossible to close the black holes with them.

They need to fly directly to the ground after spawned, and then they need to be able to move around while casting on the ground.

**Comment by Godmatik** [comment]
Possible that the PTR was not updated with the constellations fix when we ran it, but if you can verify plz

**Comment by Afgann** [comment]
fixed
