### ISSUE TITLE
(PTR) 25m Freya

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#1575]
1. Every so often, on hard mode, Freya will cast an extra iron roots randomly on top of the 3 roots she casts on cooldown. Should only be 3 roots every so often.

2. Army of the Dead ghouls can taunt the Ancient Conservator but should not.

3. The elder adds are doing /yell when you engage and wipe in the fight on hard mode, they should not.

4. Lashers (little adds) are immune to slow. They should not be (at least in normal mode, dunno about heroic).

5. The charge from Ancient Water Spirit doesn't appear to do any damage or knockback.

6. One of the sunbeams is showing an infernal trigger that should be invisible.

7. If someone is removed from roots (like blessing of freedom), the roots should completely be destroyed, but they are not.

**Comment by Manpower99** [comment]
the AotD periodically taunting the Ancient Conservator, that is not a bug. it was an annoying issue on Classic also but is blizzlike.

**Comment by Afgann** [comment]
fixed
