### ISSUE TITLE
(PTR) Mimiron 25m

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#1576]
Ability "Heat Wave" is almost never used in phase 2. It should be every ~10 seconds, and can be used while he is channeling laser barrage as well.

Arm Pulse damage in phase 4 seems much too high for normal mode or it is hitting too many targets perhaps. 

Fire cap does not appear to be working.

Sometimes we drop a trap in phase 3 but the head does not come down if it is standing still.

**Comment by Manpower99** [comment]
Trap/Magnetic Core consistently worked for us only if we used it when the head was standing still also, and only if we placed it directly underneath the head. if the head was moving or if Magnetic Core was used slightly ahead of its current location it wasn't dropping either. so unless it gets changed slightly you have to use it exactly under a stationary Aerial Command Unit.

Heat wave happened to us consistently, perhaps the timer is not correct yeah. https://www.youtube.com/watch?v=_Bab3749jiU using this as proof that the timer should indeed be every 10s.

**Comment by Godmatik** [comment]
Heat wave happened to us only once before barrage and once after. Even if it's on a timer it probably is getting reset during barrage. 

It should be able to be used during barrage

**Comment by Afgann** [comment]
fixed
