### ISSUE TITLE
Inferno Effect transfers threat too the Warlock instead of the Infernal Guardian

### ISSUE THREAD

**Issue by Steadydnt** [gamefreedomgit/Frostmourne#1577]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Hello I noticed alot in dungeons that when I cast Inferno into a big add group to Stun it and deal massive AoE dps the Impact Damage from Inferno (like 2-4k dmg) will get me alot of threat. Instead all the generated threat should be go to the Infernal instead of the caster Warlock.

**How to reproduce:**

**How it should work:**
Threat should go the Inferno instead of the Warlock. Inferno has alot of Health and Armor and should be able to tank adds for a bit.

**Database links:**

**Comment by Piootrek** [comment]
Damage and stun come from the Inferno spell cast by a player, not from a summon so I don't see any reason why a summon should get a threat from this. If you have proofs it should work differently please post them here.

**Comment by Steadydnt** [comment]
I just overlooked a few sources again and I was wrong sorry for the missinformation. The Inferno Effect actually transfers threat to the caster. The Immolation Aura and Melee attacks will only generate Threat on the Infernal. This Post will be deleted.
