### ISSUE TITLE
Scarab brooch

### ISSUE THREAD

**Issue by Powerofpala** [gamefreedomgit/Frostmourne#1579]
**Description:**
The item scarab brooch does not work as intended. The way that it works on frostmourne is : When the trinket is used each heal (no matter how stron or weak) gives the exact same shield, and each time you cast another heal with the proc still up it just restarts the timer  of the shield and does not contribute to more shields which it should.

**How to reproduce:**
If the trinket is used and you heal someone whilest active and have some way of traking shileds, no matter if you heal with a spell that heals for 5hp or for 160000hp the shield from the proc will be the same.

**How it should work:**
The way that it is supposed to work is : once the trinket is proced each heal that you cast contributes to a shield, each heal cast (no matter if fully overheal or not) contributest 15% of the heal amount to a shield. The shield has an absorb priority over a priest's Power word: shield, meaning if both of those shields are present on a target the first to be used is not Power word: shield but rather persistent Shield (the proc from scarab brooch). The maximum amount of shield that can be contributed to a single person is 10000 (ten thousend)
each heal should contribute to the shield and also refresh the time of the shield which is 8 seconds.
**Database links:**
https://www.wowhead.com/classic/item=21625/scarab-brooch

**Comment by Riztazz** [comment]
Any proof to support this? I can think of a single item that behaves like that and it's Val'anyr and it's legendary

**Comment by Powerofpala** [comment]
It does work exactly like val'anyr the only difference being that instead of the 25 000 max shield from the val'anyr tis 10 000 for the scarab brooch.

**Comment by Manpower99** [comment]
https://www.reddit.com/r/classicwow/comments/lk3136/comment/gnhp56b/

https://www.wowhead.com/classic/item=21625/scarab-brooch#comments
lots of comments claim it isnt stacking like valanyr.
