### ISSUE TITLE
Dungeon bosses drop Emblem of Conquest

### ISSUE THREAD

**Issue by NNassib336** [gamefreedomgit/Frostmourne#158]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Bosses from heroic level 80 dungeons drop conquest instead of heroism - at this phase, they should drop heroism, though I personally would not mind if this was kept :)

**How to reproduce:**
Kill any boss in the heroic version of wotlk dungeon

**How it should work:**
Bosses should drop an emblem of heroism

**Database links:**

**Comment by Manpower99** [comment]
naxx bosses also. didnt check os and eoe

**Comment by Afgann** [comment]
fixed
