### ISSUE TITLE
Tempest Keep Kel Thas should drop more loot (2 pieces not only 1)

### ISSUE THREAD

**Issue by gforghieri** [gamefreedomgit/Frostmourne#1581]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

Tempest Keep Kel Thas should drop more loot (2 pieces not only 1)

It drops 3x chest token, Verdant Sphere, 1 piece of loot from loot table.

It should drop 2 pieces.

Example: https://youtu.be/FEYAX7l5H6A?si=A-zZ8UkWEHploprT

**Comment by BalanCV** [comment]
@PanJanuszek  I know you're mainly handling older content stuff. Sorry for tag, but I feel this is pretty important. TK seems to be the most popular old raid being done right now for the mount and goodies.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
