### ISSUE TITLE
Stomper Kreeg Vendor Issue

### ISSUE THREAD

**Issue by Neroix** [gamefreedomgit/Frostmourne#1583]
Description: So I went to "Dire Maul" Dungeon for the Npc "Stomper Kreeg" to purchase some materials for "Goblin Rocket Fuel" but after mind controlling the Npc, we were not able to access the Npc, and all we were able to see is the quest mark but unable to interact with the Npc. If possible try to visit the issue for it is needed for few particular recipes, thx

How to reproduce: Try to mind control the Npc with a shadow priest and try to interact it with right click, you should see that the interaction animation but no further option is possible.

How it should work: It's suppose to be giving us access to purchase items or get few quests from the Npc itself

**Comment by Piootrek** [comment]
Actually he should be immune to a mind control. Fixed

**Comment by Neroix** [comment]
Not really, since in classic usually he had to be mc'd to access a quest / vendor while interaction.
It is part of the quest of "war of the shifting sands".

**Comment by yeagerca** [comment]
> Not really, since in classic usually he had to be mc'd to access a quest / vendor while interaction. It is part of the quest of "war of the shifting sands".

You should be able to interact with Stomper Kreeg by completing a Dire Maul Tribute run (which might be bugged currently; kill all bosses instead of leaving them alive). Volatile Rum for the fuel can also be obtained from pirate mob drops in Tanaris.

**Comment by Neroix** [comment]
Hummm I'd suppose that works.
