### ISSUE TITLE
Obsidian Sanctum, ending counter doesnt despawn whelps

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1584]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Ending encounter in OS, while whelps got released from the Portal/shadow realm into the physical realm, doesn't despawn the whelps.

**Database links:**

**Comment by Piootrek** [comment]
Fixed
