### ISSUE TITLE
Ability : Crusader Strike

### ISSUE THREAD

**Issue by prohub001** [gamefreedomgit/Frostmourne#1585]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Lets start with first basic fact in crusader's strike tooltip "a melee strike that does 93% of melee weapon's damage", so its a melee strike, 
and second "seal of corruption/vengence" applies x1 stack once you do a melee strike,
if you have that seal and you do melee strike using "crusader strike" it won't apply stack.

**How to reproduce:**
wait for your melee to enter "swing cooldown" and force the character to hit during that swing cooldown by using crusader strike

**How it should work:**
Seal of vengence/corruption must benefit from all melee strikes including crusader strike.

**Database links:**
https://www.wowhead.com/spell=35395/crusader-strike

**Comment by Manpower99** [comment]
It did not on 3.3.5a, the behavior you're referring to is only a new change in classic wotlk 3.4.1

https://www.icy-veins.com/forums/topic/71147-upcoming-retribution-paladin-changes-in-wrath-classic/

> The Holy Vengeance and Blood Corruption DoT effects from Seal of Vengeance and Seal of Corruption may now be applied by Divine Storm and Crusader Strike, in addition to normal melee hits.
As we’ve previously stated, we do not make these changes lightly and we are extremely hesitant to make modifications to the original 3.3.5 designs of classes. We will continue to monitor class representation as we have been, and will make additional adjustments if things start to play out in a way that deviates significantly from how we and other Wrath enthusiasts would expect them to. We also may roll back these changes or make further adjustments if we feel this adjustment went too far. We will continue to be very cautious with changes in general, and will reserve these adjustments for specific situations.
