### ISSUE TITLE
HC qiraji mount has a 3 second cooldown

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1586]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
HC qiraji mount currently has a 3 second cooldown, making you unable to dismount and mount right back up. Big functionality downside and extremely annoying after constant use.
(Unintended consequence of copy-pasting vanilla legendary mount?)
**How to reproduce:**

**How it should work:**
Mount should have no CD

**Database links:**

**Comment by Chaos-within** [comment]
Also when the mount is being used as the ground mount version, it still dismounts in water.

**Comment by Chaos-within** [comment]
Can't use it in battlegrounds... Did this mount go through any quality testing?

**Comment by RadeghostWM** [comment]
Yes, you just did. We will fix this.

**Comment by Chaos-within** [comment]
It also does not gain 310% speed if you have a 310 already learned. Stuck at 280%.

**Comment by Chaos-within** [comment]
Cannot use in arenas either.

**Comment by UltraNix** [comment]
Fixed.
