### ISSUE TITLE
[PTR - Ulduar25m] Mimiron, emergency fire bot water spray doesn't clear fires correctly, should be 15y wide/length cone

### ISSUE THREAD

**Issue by gforghieri** [gamefreedomgit/Frostmourne#1588]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

[PTR - Ulduar25m] Mimiron, emergency fire bot water spray doesn't clear fires correctly, should be 15y wide/length cone

![image](https://github.com/user-attachments/assets/47a6ebda-b1ae-42c3-b592-f91537deb55f)

Correct way on WOTLK classic 15y wide/length cone easily cleans multiple patches of fire, video: https://youtube.com/clip/UgkxLisgrd2Ipj3a-4OeuVJd0Qy0GsNMAJbW?si=WLpOHKp2b04KdzwP

On whitemane its clearing 1 patch, sometimes not even: video https://youtube.com/clip/Ugkxe4bzWP6-881omsaO2OgAFHsQ9gD0x8NR?si=31Q0DCHHNdpcqsGy

**Comment by roperoperope** [comment]
yes sir

**Comment by Manpower99** [comment]
Bump bump

**Comment by Afgann** [comment]
fixed
