### ISSUE TITLE
[PTR - Ulduar25m] Mimiron, last phase, ranged dps pulling threat on bottom part, while targetting only the head

### ISSUE THREAD

**Issue by gforghieri** [gamefreedomgit/Frostmourne#1589]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

[PTR - Ulduar25m] Mimiron, last phase, ranged dps pulling threat on bottom part, while targetting only the head

The threat on the head transfers to the bottom and ranged dps pull threat. This should not be possible.

Clip: https://youtube.com/clip/Ugkx86_lFjVr_hiptEW3GWIS4bAv2HahDC4h?si=lOL2UmUNn_WEMQ1S

![image](https://github.com/user-attachments/assets/1d7eabc1-12f9-47c7-afd6-f6743cff7434)

![image](https://github.com/user-attachments/assets/4ef2c1dc-3493-4e4f-981b-d418e56c7df3)

**Comment by roperoperope** [comment]
bump

**Comment by gforghieri** [comment]
@Afgann forgot to add video here it is: https://youtube.com/clip/Ugkx86_lFjVr_hiptEW3GWIS4bAv2HahDC4h?si=lOL2UmUNn_WEMQ1S

**Comment by Afgann** [comment]
fixed
