### ISSUE TITLE
Cannot requeue rdf

### ISSUE THREAD

**Issue by NNassib336** [gamefreedomgit/Frostmourne#159]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Cannot requeue after completing a dungeon using the dungeon finder. Currently, we need to disband and reform

**How to reproduce:**
Queue with the dungeon finder (even as a full party), complete the dungeon, then try to requeue

**How it should work:**
You should be able to requeue after the dungeon is complete (killing the last boss)

**Database links:**

**Comment by Afgann** [comment]
fixed
