### ISSUE TITLE
PTR - 25n Ulduar - Freya's Detonating Lashers and few remaning issues

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1591]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
https://www.wowhead.com/wotlk/guide/raids/ulduar/freya-strategy

> There` are several ways to deal with the kill phase of these lashers. The slow approach is to kill them one by one and let the healers top off the raid between each detonation. A more efficient strategy is to stun all the adds with a  Shockwave or  Shadowfury when they are low health before knocking them away with a  Thunderstorm,  Typhoon and  Blast Wave to die. Or use a  Challenging Shout to drag them all away from the raid as they are about to die, paired with defensive cooldowns to protect the tank. Or trap them in a  Frost Nova while the raid runs away... Be creative!

![image](https://github.com/user-attachments/assets/df48e7a7-a45a-4906-8173-48ebe3085570)

 **1. Detonating Lashers :** 

 - Lashers Seem to be always attacking their highest threat target and never changing.
this could be part of the[ Flame Lash Ability](https://www.wowhead.com/wotlk/spell=62608/flame-lash#used-by-npc), every couple of seconds it would be used to deal its damage 2-3s within melee range and swap target to ones far from it.(even if it didnt have a target do hit or if it even hit)
 
 - They shouldn't be taunt immune, they currently are immune to taunt in PTR but shouldn't be, every time they get taunted they should be focusing the target who taunted them for the duration of the Taunt debuff. 
in PTR currently they were immune to Challenging Shout and possibly every other Taunt ability.
You can see in the Tankspot [video ](https://youtu.be/HJ1gxZZSRtI?t=51)they are changing their targets every 3-4seconds or so, they are not supposed to be permanently tankable by holding threat due to resets. but if taunted they would be forced to attack for the duration of the taunt debuff. the taunt debuff should override the flame lash of course.

 - https://www.youtube.com/watch?v=fXj882q2CrM this is an off tank video from WotLK classic which shows the threat meter perfectly and the intervals between threat reset and target swapping to random furthest range players.

 **2. Freya's Nature Bomb has few remaining Issues :** 

 - If encounter ends before any of them explode, they should just dissappear without exploding, currently if the encounter ends and some didnt explode, they will explode right after. [Proof ](https://youtu.be/fXj882q2CrM?si=ja_X7-eu66lrr3kH&t=244)
 
 - Their Timer should be about 20seconds before she throws another set of Nature Bombs.
 
 -  you can see [Here ](https://youtu.be/CKyJYaSjiww?si=7bmVj88v72ZYqp6-&t=382)they explode 10seconds after they're thrown.
 They're thrown at 06:27 and explode at 06:37.

**Database links:**

**Comment by NickZedd** [comment]
In the video you linked it always takes 15-18 seconds before new bombs are thrown, never 20. This is also what I've seen in other videos. Having them be thrown more often on HC for an additional challenge would also be awesome. @Afgann

**Comment by Afgann** [comment]
fixed
