### ISSUE TITLE
The .pvpinfo command doesn't work

### ISSUE THREAD

**Issue by LezChap** [gamefreedomgit/Frostmourne#1594]
Just as the title says...using the PVP Toggle from the Whitemane addon makes you say ".pvpinfo" in your chat channel, but doesn't remove the Arena spam in the chat.

Tried searching the discord and say ".pvpinfo off" and that didn't work either.  Also tried "/pvpinfo" without success.  Please fix so I can clean up my chat window of all the unwanted spam.

**Comment by Piootrek** [comment]
There are new commands:

- .bg ann
- .arena ann
- .wg ann

**Comment by LezChap** [comment]
> .arena ann

This command always returns "Arena announcements are now enabled!"...tried .arena ann off and just .arena ann (twice).

**Comment by LezChap** [comment]
@Piootrek If you want me to create the above as a new issue I will, leaving it here for now since the commands you listed were the "solution" to the main issue in the OP.
