### ISSUE TITLE
Deathknight Pestilence Leeway not fixed

### ISSUE THREAD

**Issue by Sylanha** [gamefreedomgit/Frostmourne#1595]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)
![image](https://github.com/user-attachments/assets/c40f95b4-f699-4db1-810c-04444e3bb1be)
https://github.com/gamefreedomgit/Frostmourne/issues/878

**Description:**
Some time ago, the changelogs said that the leeway from Deathknight's Pestilence got fixed and I made a Github bugreport before, BUT it did in fact not get fixed.

**How to reproduce:**
Make a DK and go to Acherus/DK city and get Glyph of Pestilence (it should work without the Glyph too, but it makes it easier since the increase range) and try to press Pestilence while a disease is up to spread it on the other dummies. (I works on Warmane (see the videos below))
![image](https://github.com/user-attachments/assets/de95ded8-7a64-444c-b109-7a6ac7236d7a)

**How it should work:**
The disease should spread further if you are moving into the direction that it should spread to.

**Database links:**
https://www.youtube.com/watch?v=10GcrBpnGyI
https://www.youtube.com/watch?v=axqyHHiffrg

**Comment by Piootrek** [comment]
Leeway bonus is correctly applied to the Pestilence radius and makes it 17.65y instead of 15. Small training dummies are around 20y from the big one, so they are still too far.

**Comment by Sylanha** [comment]
@Piootrek 
Did you at least watch the video proof that I sent you? It is working on warmane... and on Whitemane it is not. The concept of Leeway is that if you jump or move in that direction, it is supposed to reach further, like an extension.

**Comment by Piootrek** [comment]
I watched and I don't see any reason to treat warmane video as a valid proof

**Comment by Sylanha** [comment]
@Piootrek 
The Leeway mechanic also exists in classic
https://www.youtube.com/watch?v=FrE9iFB1rj8&t=37s at 0:37 he explains the Leeway mechanic. This does not work on Whitemane...

**Comment by Piootrek** [comment]
Leeway mechanic didn't work for Death and Decay, I fixed this. 
It was implemented for Pestilence before and it works correctly
https://streamable.com/9bvo1f

**Comment by Sylanha** [comment]
Okay, but do these dummies have the same spacing as in DK city? For accurate testing why do you not use the dummies in DK city? The range/testing/circumstances may be different, why not use the same as I did to prove the point? 

Look in this video Leeway also works as intended. 
https://www.youtube.com/watch?v=jb8Dp-nprNs
You see that he is in DK city. First he is using pestilence and it only spreads to the 3 targets in range. Then he jumps (Leeway) and it spreads further (works with either jumping or stafing).

**Comment by Piootrek** [comment]
Before you showed the pestilence from the training dummy on the middle, as I said before it's too far and cannot reach other dummies even with a leeway. 
However between other dummies it works exactly same as you showed on a video above
https://streamable.com/2fn2o8

**Comment by Sylanha** [comment]
Is this on the live server? Because there it doesn't work as you can see in the video that I posted. And try to do it from the center dummy too please.

**Comment by Piootrek** [comment]
It's from my local server, but the code is the same on the live server. As I said before it won't work from the center dummy, because distance is too big

**Comment by Sylanha** [comment]
Okay, but it should work. So it obviously isn't the same code. If it is the same code please go to the PTR or the liveand try the same, it doesn't work!
To be 100% sure do the same tests on the PTR or live server. I am literally there right now as we speak and it doesn't work for me.

**Comment by Piootrek** [comment]
Turn around, there are other dummies on the other side. I tested it on the same dummies as the guy from your video

**Comment by Manpower99** [comment]
I believe the issue of leeway on this server is that it doesnt include the modified range of spells when they get amplified through talents glyphs set bonuses etc. it should be about 20% more radius/range for every spell during leeway, so with glyphof pestillence it would be more than 2 yards

**Comment by Piootrek** [comment]
Leeway range is static and it's always 2.66y. This value comes from the decompiled wow client https://www.reddit.com/r/classicwow/comments/c8eg81/to_all_of_those_who_claim_melee_leeway_wasnt_in/

**Comment by Sylanha** [comment]
I found more proof that the range in Whitemane is not big enough.

https://www.youtube.com/watch?v=XElQYaRZlT8&t=53s

Look at this video at 0:53 seconds. The range is way way bigger than on Whitemane + he is walking forward while using Pestilence, making it reach forward way more

**Comment by Manpower99** [comment]
> Leeway range is static and it's always 2.66y. This value comes from the decompiled wow client https://www.reddit.com/r/classicwow/comments/c8eg81/to_all_of_those_who_claim_melee_leeway_wasnt_in/

https://www.wowhead.com/blue-tracker/topic/sticky-warlords-of-draenor-theorycraft-discussion-13087818929#135929566858

**Comment by Manpower99** [comment]
Besides this https://www.wowhead.com/blue-tracker/topic/sticky-warlords-of-draenor-theorycraft-discussion-13087818929#135929566858 which might give a slight idea of how its coded on blizzard's.
https://youtu.be/LRuIxzB18qY?t=117 you can see him facing the mobs and pesti the mob he targeted while tanking and it hit all of them, on whitmane you would need to use leeway to hit all of them or might not even hit all.
also here https://youtu.be/DJAYULMSAzw?t=533 the mob in the back gets hit, on whitemane it wouldnt get hit, which prob is not that hard to reproduce at all.
This is why i believe spell leeway is not always a static amount but rather It's % of the spells total range, the total range is the range after taking Combat reach and range increase talents/effects etc into account.
it is likely static for melee leeway though.

**Comment by Manpower99** [comment]
https://www.reddit.com/r/classicwow/comments/chf071/comment/euubpzw/
