### ISSUE TITLE
Wintergrasp Cannons respawn too quickly

### ISSUE THREAD

**Issue by LezChap** [gamefreedomgit/Frostmourne#1596]
I did a WG this morning, and the cannons at the fortess were respawning WAY too fast...I didn't start a timer, but I'd be surprised if they stayed dead for more than 60 or 90 seconds.  At one point, one was killed while we approached with a few Siege Tanks, the tanks were under active attack by the defense players, and the cannons respawned and were manned again before our Sieges were destroyed (with the cannon assistance).  Seems like this bug really buffs the defense team, which in turn makes the "balance" of swapping control of WG that much harder.

**Comment by Piootrek** [comment]
Cannons have about a 6-minute respawn timer. If you think it's too fast please write a response here with proof.
