### ISSUE TITLE
Titanium seal of Dalaran

### ISSUE THREAD

**Issue by Lemmy-90** [gamefreedomgit/Frostmourne#1597]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Its a minor typo that has bothered me. I received my Titanium seal of Dalaran and the emote has a typo. When it does the emote it doesn't say the correct gender for my female character. 

**How to reproduce:**
Have a female character with the Titanium seal of Dalaran. It will say "casually flips his Titanium Seal of Dalaran"

**How it should work:**
Should say the characters correct gender.

**Database links:**
![2](https://github.com/user-attachments/assets/d216a979-4a1b-47dc-8bc9-3f4901f809c4)

**Comment by Afgann** [comment]
fixed
