### ISSUE TITLE
[WARRIOR] Weapons with different attack speed not desyncing

### ISSUE THREAD

**Issue by RealDerpyDude** [gamefreedomgit/Frostmourne#1598]
Currently when playing fury warrior with weapons with a different attack speed, the swingtimers will not desync. You can never desync your weapons since the offhand will always catch up to the mainhand but won't surpass it.  This only seems to happen when using a 3.6 and 3.4 speed weapon. When using a 3.7 weapon in mainhand and 3.4 in offhand, the difference in attack speed is large enough for the weapons to desync.

https://www.youtube.com/watch?v=Apw1gUKj5vI

**Comment by RealDerpyDude** [comment]
https://www.youtube.com/watch?v=M8fExVC3NJE

In this video from classic you can also see the offhand swings independantly of the mainhand, and doesnt "wait" for it to hit like it does in my previously posted video.

**Comment by Riztazz** [comment]
Fixed, will close once it's fixed
