### ISSUE TITLE
Chaotic rifts in The Nexus

### ISSUE THREAD

**Issue by NNassib336** [gamefreedomgit/Frostmourne#160]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Chaotic rifts spawn their adds well before reaching them in the Nexus. All rifts had like 20 or so spawns by the time we reached them - looks like a 2-fold issue:
                   1 - rifts spawn adds out of combat
                   2 - the azure mobs don't engage in combat with the spawns

**How to reproduce:**
Enter the Nexus and reach the area the chaotic rifts are located

**How it should work:**
Chaotic rifts should not spawn adds outside of combat
Chaotic rifts should spawn adds when the dragonkin adds are nearly. The dragonkin then attack the adds but not the rift
Chaotic rifts should spawn adds when in combat with players (This is working fine)

**Database links:**

**Comment by Manpower99** [comment]
actual aids bug.

**Comment by Afgann** [comment]
fixed
