### ISSUE TITLE
[PTR] [Gamebreaking] 25m heroic freya broken

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#1600]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When switching to heroic 25m difficulty, two freyas spawn. When one of these has died, the other becomes unkillable. The order doesn't seem to matter.
If you attempt to kill one, wipe, and then engage the other freya, it will be on normal mode since all the elders are gone, and she will still be unkillable.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
