### ISSUE TITLE
[PTR] 25m heroic XT spawns twice

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#1601]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
If you switch to heroic on 25m difficulty, there will be two XTs. The one closer to the entrance - which is not supposed to be there - does not patrol and killing it's heart does not put it into heroic mode. Killing the heart of the bugged XT causes the regular one to berserk after a while if they were both pulled.

Luckily we can use commands on the PTR to kill the first boss without getting into combat, and then fight the other one as usual, but this still needs to be fixed.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
