### ISSUE TITLE
[PTR] XT 25m heroic buffs not applied correctly

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#1602]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
For now I'm just going to mention some obvious stuff I noticed testing on my own. If heroic gets applied I can test with my guild and look into old videos to find details that differ.

- The heartbreak debuff only gives the boss 15% more damage and 60% more health which are pre-nerf values. 
- tantrum is only 8 seconds long
- boss does not cast gravity bomb or searing light during tantrum
- boss melees for 38-42k on a tank (in spite of his damage bonus being too low)
- pummelers melee for approx 7k on a tank

**How it should work:**
Basing this mostly on the buffs in this frosthold announcement for now https://archive.is/6WwGI
- Heartbreak should give +40% damage and +220% health
- tantrum should last for 12 seconds
- boss should continue casting gravity bomb and searing light while channeling tantrum
- boss currently oneshots a tank, so damage has to be reduced. I am not sure how much damage he did pre-nerf on retail, or how much he did on frosthold. I can find out these details for you in the future when the encounter is fixed.
- From memory I believe the pummelers should hit for more than the boss (but less than the boss currently hits for), so that they must be dealt with quickly. This should also be looked up.

**Database links:**

**Comment by Afgann** [comment]
fixed
