### ISSUE TITLE
[Ulduar PTR] Assembly of Iron: Issues with Runemaster Molgeim hitbox

### ISSUE THREAD

**Issue by ottovonwulffen** [gamefreedomgit/Frostmourne#1603]
**Description:** Runemaster Molgeim's (medium boss) buff hitbox seems to have the wrong size, as he gets the rune of power buff when he is visually clearly standing outside of it. His hitbox appears to have the same size as Steelbreaker's (large boss).

**How to reproduce:** Pull iron assembly and wait for rune of power. Position medium boss on the edge of the rune where melees would be able to hit him but he would not get the buff. Examples below:
https://youtube.com/clip/Ugkx_EoZl0d5ZVUz3x-Awh1SXsiItly2zybE?si=cB-GuTLh1coYZJJf
In this clip you can see the tank dragging the boss away from the rune so he does not have the buff anymore. At 5 seconds into the clip, the boss still has the buff (see weakaura on the left side of the screen, and the debuff to the top right corner of his unit frame), while he visually is clearly standing outside of the rune. When the boss takes one step further away (see second 8 of the clip), the boss doesn't have the debuff anymore, but is no longer attackable for melee inside the rune.
For comparison, below is a clip to see steelbreakers hitbox for the rune of power buff. 
https://youtube.com/clip/UgkxmBAJyvCxwJFLYrK_lsLMHz_XYuCxMiKk?si=Ug-dmz3-PZhjG-KV
You can see that he doesn't have the debuff anymore once his hitbox circle is no longer in the rune, and it is very straightforward to position him at the edge of the rune for melees to be able to hit from the rune.

**How it should work:**
Runemaster Molgeim's hitbox for getting the rune of power should match his size, i.e., once the target circle on the ground is no longer in the rune, he shouldn't get the "debuff" from it anymore.

**Database links:**
Rune of power ability: (https://www.wowhead.com/wotlk)](https://www.wowhead.com/wotlk/spell=61973/rune-of-power)

**Comment by Afgann** [comment]
fixed
