### ISSUE TITLE
[PTR] 25m heroic mimiron broken

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#1604]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Setting the raid difficulty to heroic 25m will cause 2 additional Mimirons to spawn. Pressing the button ends combat immediately, while attacking one of them causes the fight to bug out. It doesn't seem to matter which one you attack.

Flames will be doubled or tripled, with slightly different delays between them (the delays seems to be determined when you pull). Mines were also doubled on one pull but I wasn't able to recreate it.
Two of the Mimirons will be stuck in the middle, always facing the player. Note that even though I attacked the one marked square, the one with the cross was in the vehicle.
Finishing phase 1 will cause the fight to reset as the Mimiron inside the vehicle runs back to his starting location. The player remains in combat.
Flames spawned while the boss is "transitioning" back into phase 1 will despawn immediately.
phase 1 then begins again. You cannot get out of combat except by wiping.

**How it should work:**
Not like this.

**Video links:**
https://www.youtube.com/watch?v=nzAgBxl7G_Q

**Comment by Afgann** [comment]
fixed
