### ISSUE TITLE
Highland Mixed School

### ISSUE THREAD

**Issue by Scolix9** [gamefreedomgit/Frostmourne#1606]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Pools around skettis in Terokkar Forest

**How to reproduce:** There is literally not a single pool to fish.

**How it should work:** Last night there were at least 8 nods in there to fish but after i spoke to a gm through a ticket about Mr.Pinchy issue that it wasn't dropping at all even tho it is a 2-set achievment to do, woke up today to find out out that all pools are not there. Is this an ongoing fix i should wait for in order to continue with my achievment or this is a bug ?

**Database links:**

**Comment by Riztazz** [comment]
This seems to work fine, i've asked Radeghost to test it on production as well, will close if there is no issues found
