### ISSUE TITLE
PTR - 25n Ulduar - Freya Unstable Beam and Iron Roots at the same time

### ISSUE THREAD

**Issue by broizter** [gamefreedomgit/Frostmourne#1607]
On PTR freya casts Unstable Beam and Iron Roots every 30 seconds, both abilities at the exact same time. So people will constantly be rooted inside beams making this mechanic EXTREMELY deadly. Check log below to see that it happens the same second. On classic they are not happening at the same time. https://www.youtube.com/watch?v=CKyJYaSjiww&t=382s

```lua
<108.81 12:18:54> [CLEU] SPELL_AURA_APPLIED#0x0000000000006998#Zintwo#0x0000000000006998#Zintwo#62438#Iron Roots#DEBUFF#nil#", -- [1556]
<108.81 12:18:54> [CLEU] SPELL_AURA_APPLIED#0xF1300081921E872D#Sun Beam#0xF1300081921E872D#Sun Beam#62865#Unstable Energy#BUFF#nil#", -- [1550]
```

**Comment by Afgann** [comment]
fixed
