### ISSUE TITLE
Druid version of  [Atiesh, Greatstaff of the Guardian] cant create portal

### ISSUE THREAD

**Issue by Deadlifey** [gamefreedomgit/Frostmourne#1608]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Druid version of [Atiesh, Greatstaff of the Guardian] doesnt have the on use effect that creates a portal to Dalaran

![obraz_2024-08-16_225716873](https://github.com/user-attachments/assets/5ee510f3-897e-4647-859a-53f43e2fdb44)

**How to reproduce:**
by obtaining the staff

**How it should work:**
There should be a on use effect to create a portal

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
