### ISSUE TITLE
Engineering Mount

### ISSUE THREAD

**Issue by War12100** [gamefreedomgit/Frostmourne#1609]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
unable to use the engineering mount on different charaters that have engineering as well.

**How to reproduce:**
Make engineering mount and use on a character. Have another character with max engineering as well but mount doesn't show up in pet list.

**How it should work:**
Should have engineering mount in pet list if characters have max engineering.

**Database links:**

**Comment by Piootrek** [comment]
That works correctly for me. What mount you are trying with?
