### ISSUE TITLE
[Warlock] Shadow embrace debuff random drop in boss fight

### ISSUE THREAD

**Issue by scrublama** [gamefreedomgit/Frostmourne#1610]
**Description:**
I got screenshot of my warlock _Shadow embrace_ debuff dropping midfight during heigan encounter in naxx25.
I went into uwulogs to analyze and saw it drop from the other affliction lock aswell.
Included proof that we are casting shadowbolt and haunt which should apply shadow embrace.
Only once I did a sidestep after noticing it started to reapply again

https://imgur.com/a/shadow-embrace-drop-on-heigan-KjFbzNa

https://uwu-logs.xyz/reports/24-08-15--19-22--Laurynhance--Whitemane-Frostmourne/casts/Moonie/?boss=heigan-the-unclean&mode=25N&s=4274&f=4362&attempt=0

https://uwu-logs.xyz/reports/24-08-15--19-22--Laurynhance--Whitemane-Frostmourne/casts/Tricksme/?boss=heigan-the-unclean&mode=25N&s=4274&f=4362&attempt=0

**How to reproduce:**
https://gyazo.com/9ffd60797b1775382ea58073a2af3ad3

**How it should work:**

**Database links:**

**Comment by Riztazz** [comment]
fixed, will close once it's live

**Comment by Riztazz** [comment]
Thank you for detailed report, "Only once I did a sidestep after noticing it started to reapply again" this gave me an idea that turned out to be true :P
