### ISSUE TITLE
Boss parry haste - ulduar 25n/25hc (PTR)

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1612]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Currently on Naxx parry haste works as intended, Gluth Saph and KT are the only bosses who do it.
in RS its Halion
in ICC its LDW and Sindragosa
In Togc its Worms duo and Icehowl. 
Onyxia still does it also.

Ulduar however in PTR seems to be incorrect.
 1. Vezax is currently parry hasting on **25N** , it should be only Thorim and Auriaya who do on Post nerf.
 This is both inline with the findings in 2018 during [sunwell times](https://github.com/SunwellTracker/issues/issues/401) and also classic 
![image](https://github.com/user-attachments/assets/2068b298-214e-4103-aff9-17291bb9ef89)

 2. **25HC** from https://archive.ph/6WwGI which are some of your intended boosts, it should be that every Boss except Kologarn should have it, currently it is also only Vezax.

**Database links:**

**Comment by Manpower99** [comment]
@Afgann thank you for the quick fix, however changelog didnt state that it removed parry haste from vezax on normal mode

**Comment by Afgann** [comment]
@Manpower99 It was removed from vezax, forgot to mention it in changelog.

**Comment by Manpower99** [comment]
> @Manpower99 It was removed from vezax, forgot to mention it in changelog.

Thank you for the fix.

**Comment by Manpower99** [comment]
@Afgann don't want to do a seperate bug report, i will if you need me to.
today's ptr showcased that there was no changes to parry hastes so far, Vezax still does it and Thorim and Auriaya are not.
Normal mode testing on 25m.
