### ISSUE TITLE
Hadronox in Azjol Nerub not respawning after a wipe

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1613]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Currently there's an issue with [Hadronox](https://www.wowhead.com/wotlk/npc=28921/hadronox), after a wipe the boss vanishes for players (shows dead to us) and will not respawn.
Apparently its not only hadronox. the first two bosses are having this issue time to time.
sometimes they despawn as player engages.

**How to reproduce:**

engage hadronox and wipe

**How it should work:**

Should respawn correctly if it didnt die.

**Comment by Riztazz** [comment]
I cannot reproduce the hadronox issue where he never respawned, but i've found two issues where he could be kinda stuck and i've fixed them, please let me know if it happens again

**Comment by WhitemaneChronus** [comment]
@Riztazz Thanks for the dedicated work on this issue;
Currently there's a loot issue on Hadronox.
it appears that the boss dies quickly to mobs around while its walking up; Players fail to 'tag' the boss and they are receiving no loot (no emblem / item)

**Comment by Riztazz** [comment]
I haven't changed anything regarding that so that's interesting, i'll take a look tomorrow
