### ISSUE TITLE
(PTR) Kologarn boss frames

### ISSUE THREAD

**Issue by Covidisreal** [gamefreedomgit/Frostmourne#1614]
In addition to original post ( https://github.com/gamefreedomgit/Frostmourne/issues/1571 )

Mimiron boss frames are working perfectly, however kologarn only displays 2 / 3 active body parts (body + 1 arm), and if one arms is destroyed - second one takes place. If the initially destroyed arms is then restored - it will not appear in boss frames.

**Comment by Afgann** [comment]
fixed
