### ISSUE TITLE
Elixir of Deadly Strikes not affected by Mixology

### ISSUE THREAD

**Issue by crabcakeowo** [gamefreedomgit/Frostmourne#1615]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** 
Elixir of Deadly Strikes only grants 45 critical strike rating and has a duration of 1 hour even with Mixology affecting it.

**How to reproduce:**
Get 450 alchemy with Mixology and use Elixir of Deadly Strikes.

**How it should work:**
Elixir of Deadly Strikes should be affected by mixology and gets the duration bonus which will put it at 2 hours.
Additionally, with mixology bonus, this elixir will give 61 critical strike rating. An increase of 35.56%.

**Database links:**
https://www.wowhead.com/wotlk/item=44327/elixir-of-deadly-strikes#comments

![123](https://github.com/user-attachments/assets/b8491d46-faf0-4e68-b0e3-e14468590e12)
![122](https://github.com/user-attachments/assets/450a0d99-de09-4031-8f8e-4b085695a97d)
![121](https://github.com/user-attachments/assets/b5b14a73-abc8-4214-bb4d-d4b403ff19b2)

**Comment by Piootrek** [comment]
It works. You must have discovered recipe for this elixir to get Mixology bonus.
