### ISSUE TITLE
[Ulduar PTR] Freya not casting unstable energy.

### ISSUE THREAD

**Issue by ottovonwulffen** [gamefreedomgit/Frostmourne#1616]
**Description:** 
After the recent timer changes (everything casting every 30 seconds rather than as an ability CD), Freya appears to no longer cast unstable energy.
See this video I took 10 minutes ago, when I wanted to check new timings: https://www.youtube.com/watch?v=K6Ow2dYqaQw

**How to reproduce:**
Pull Freya with all keepers alive.

**How it should work:**
She should cast unstable energy at some point, and then every 30s after that.

**Database links:**
https://www.wowhead.com/wotlk/spell=62865/unstable-energy

**Comment by Afgann** [comment]
fixed
