### ISSUE TITLE
Ulduar PTR algalon two remaining major issues

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1619]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
 1. Currently using any spell with a cast time while inside the shadow realm in algalon **crashes the client** and after restart you're outside ulduar. happened to us every week of PTR testing, basically preventing heals from happening while inside shadow realm.
 willing to provide a video of it happening, this has happened everyweek in our PTR sessions.

 2. Taunting constellation doesn't force it to move towards the caster while it is casting towards slomeone, everytime it would cast randomly on someone it tries to follow him. basically impossible to consistently taunt a constellation towards a black hole thus making a major part of this encounter impossible/heavily rng when it shouldn't be.
 - https://youtu.be/9XjyurM1Eh0?si=tdnhVvJxxB7ncpzP&t=82 the dk here taunts a constellation, it is still casting while moving but still follows the dk to be in his melee range, you can see they're slowably by chains of ice and when icy touched they followed the highest on aggro which is the dk himself.

**Database links:**

**Comment by Afgann** [comment]
fixed

**Comment by Manpower99** [comment]
> fixed

Taunting constellation part still does not work. observed it had no target at all and was moving randomly and closing black holes and basically griefing the raid lol.
