### ISSUE TITLE
Ulduar PTR 25Normal Yogg-Saron

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1620]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
 1. [Constrictor Tentacle](https://wowpedia.fandom.com/wiki/Constrictor_Tentacle)
  - If grabbed by it you should be able to clear it/it despawns by immunities such as iceblock/hop/divine shield etc. this is the standard blizzlike behavior. potentially you could keep it this way as a custom buff to 25HC, but on 25N it should be blizzlike.
  - You should be able to still use spells while grabbed and even melee it. [Proof](https://youtu.be/ScgHjGnLsF4?si=oiFFLJdcCVHwwmI-&t=406)
  - Using a spell like Demonic Circle/Blink, generally similar spells who displace the caster are exempt and should not be usable however.
 
2. [Crusher Tentacle](https://wowpedia.fandom.com/wiki/Crusher_Tentacle)
 - [Focued Anger](https://www.wowhead.com/wotlk/spell=57689/focused-anger) should only be stacked through direct player damage, not dots and not pets. [Here](https://youtu.be/W4Tzhflasbg?si=tVmHahY7TfR0kDnX&t=18951) the dots from explosive shot are not refreshing nor stacking it.
 [Hotfix](http://blue.mmo-champion.com/23/17631614070-recent-ingame-fixes--6409.html) (2009-06-15): [Focus Anger](http://www.wowhead.com/?spell=57689), on Yogg-Saron's Crusher tentacles, will no longer result from pet attacks. 
Edit : the pet thing should only be fixed on normal mode, pets should still stack it on HC. 
dots issue however should be for both normal and hc.

3. [Death Rays](https://www.wowhead.com/spell=63884/death-ray) are stuck in one spot. they should be roaming around like [this](https://youtu.be/ScgHjGnLsF4?si=MnAx69CbYihoUFU3&t=236)

**Database links:**

**Comment by NickZedd** [comment]
Quick addition: Please keep the pets stacking focused anger on pre-nerf as it was a hotfix change, and only change it on normal mode.

**Comment by Manpower99** [comment]
@Afgann changelog implies it is fixed only for explosive shot, it should be for all dots.
Constrictor vs immunities also not fixed, this is something mentioned in multiple guides + tankspot video and have witnessed it happening myself. if visible proof is required for it i will start looking there is no problem.

**Comment by Afgann** [comment]
@Manpower99
Which dot still procs focused anger? I fixed explosive shot because its handled differently than other dots, others seemed fine from what i've checked.
Immunities vs constrictor weren't mentioned in the last commit, don't worry it'll be fixed.

**Comment by Manpower99** [comment]
> @Manpower99 Which dot still procs focused anger? I fixed explosive shot because its handled differently than other dots, others seemed fine from what i've checked. Immunities vs constrictor weren't mentioned in the last commit, don't worry it'll be fixed.

Drain Soul, Mindflay also they are both considered dots and looked like they were stacking it, by friday my Guild will be PTRing again i will make sure to check every individual dot since now we have better testing commands on PTR.

**Comment by Afgann** [comment]
fixed
