### ISSUE TITLE
[PTR] Stormjewels, Bag of Fishing Treasures, Tiny Titanium Lockbox

### ISSUE THREAD

**Issue by yeagerca** [gamefreedomgit/Frostmourne#1621]
**Description:**
Stormjewels are not dropping from Bag of Fishing Treasures or Tiny Titanium Lockbox on the test realm (Ulduar patch).

**How to reproduce:**
Open a significant number of Bag of Fishing Treasures and Tiny Titanium Lockbox.

**How it should work:**
Bag of Fishing Treasures and Tiny Titanium Lockbox should have a reasonable chance to drop Stormjewels beginning in Ulduar patch.

**Database links:**
https://www.wowhead.com/wotlk/item=46007/bag-of-fishing-treasures#contains;0-20+17+1;q=Stormjewel
https://www.wowhead.com/wotlk/item=45986/tiny-titanium-lockbox#contains;0-20-1+17;q=Stormjewel

**Comment by scrublama** [comment]
remember to make them unique equipped thx

**Comment by crabcakeowo** [comment]
back then its only unique equipped before epic gems were released, seeing as how we are in 3.3.5, i believe its okay to have it not be unique equipped.

**Comment by crabcakeowo** [comment]
the reasoning is because these gems will be highly sought after and will definitely be overpriced, having more things to do to improve your own character is a welcoming bonus IMO. It will definitely at least promote people to farm more gold or do fishing dailies to get them, which means more players will be playing.

**Comment by scrublama** [comment]
@crabcakeowo you wanna suggest changes do it on discord

**Comment by crabcakeowo** [comment]
Stormjewels still aren't dropping from the bag/lockbox.

**Comment by ItsPope** [comment]
Stormjewels still aren't dropping from the bags in PTR

**Comment by ItsPope** [comment]
Hi, I tested the drops on PTR after it was supposedly implemented according to discord:
""
Author: afgann
Message: DB/Loot: Add Stormjewel drops to Bag of Fishing Treasures and Tiny Titanium Lockbox. 
""
and later 
'''
The fixes above have been applied to the Production server and are now live.
'''

Assuming that this would also be implemented on PTR as well, I opened 1000 fishing bags and 150 Tiny Titanium Lock Box

After 1000 fishing bags I had still not seen a single Stormjewel of any kind (used Fishing bags from ID = 46007)
After 150 Tiny Titanium same story (Lockbox ID = 45986)

#1881 for the live version was closed, so figured I should comment on this thread instead?

So I am asking
a) is the droprate so low that this seems possible?
or b) has this not been implemented yet (on live or ptr)?

Best regards,
Pope

**Comment by yeagerca** [comment]
Works on PTR, but the drop rates are questionably low. Feels like the containers may be rolling for a low chance to get a single Stormjewel instead of rolling them independently.

**Comment by Afgann** [comment]
fixed
