### ISSUE TITLE
Kil’jaeden, SWP (TW)

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1622]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Timing for dragon orbs are incorrect (late). players were unable to spawn 3rd drake in order to avoid the wipe mechanic. 

**How to reproduce:**

start Kiljaeden fight and continue until 3rd orb

**How it should work:**

dragon orbs should be available in time.

**Database links:**

**Comment by Piootrek** [comment]
It works correctly. How fast orbs will spawn depends on your damage. First orb will be empowered 35s after start of the phase 3 (85%), 2nd 35s after phase 4 (55%) and all of them 35s after phase 5 (25%)
