### ISSUE TITLE
All Flask unaffected by alchemist Mixology

### ISSUE THREAD

**Issue by tycozul** [gamefreedomgit/Frostmourne#1623]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** we only get the flask effect and 2 hour flask duration without the mixology bonus

**How to reproduce:**

**How it should work:**[Flask of Stoneblood](https://www.wowhead.com/wotlk/item=40083) 650 HP => 970 HP = +320 HP = ~+49%
[Flask of Endless Rage](https://www.wowhead.com/wotlk/item=40084) 180 AP => 244 AP = +64 AP = ~+35%
[Flask of Pure Mojo](https://www.wowhead.com/wotlk/item=40404) 38 MP/5 => 51 MP/5 = +13 MP/5 = ~+35%
[Flask of the Frost Wyrm](https://www.wowhead.com/wotlk/item=40082) 125 SP => 162 SP = +37 SP = ~+29%

**Database links:**

**Comment by tycozul** [comment]
![Screenshot 2024-08-19 131833](https://github.com/user-attachments/assets/066fe29e-0f31-414f-a717-c935f5379be8)
![Screenshot 2024-08-19 131855](https://github.com/user-attachments/assets/c8e2ba4c-8132-4a04-a3c7-0a4a763efabd)
![Screenshot 2024-08-19 131919](https://github.com/user-attachments/assets/a7f600f8-8b51-449c-9b83-0ff0670b9511)

**Comment by Piootrek** [comment]
Mixology bonus works correctly. Check the actual stats you get, tooltip is not updated.
