### ISSUE TITLE
Transmog bug

### ISSUE THREAD

**Issue by Meowow123** [gamefreedomgit/Frostmourne#1627]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Cannot transmog the chest piece slot into the Blackened Defias Armor, only 3-4 options appear.

**How to reproduce:**
Go up to the transmog guy, select chest on any leather wearer and check the transmog options.

**How it should work:**
Going up to the transmog guy, selecting the chest option on a leather wearer and having all the unlocked transmogs as options.

**Database links:**
-

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/1624
