### ISSUE TITLE
[Paladin] Heart of the Crusader Stays on Target once Judgement causing it has worn off

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1629]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Heart of the Crusader debuff stays on target even after the judgement causing it has fallen off.

**How to reproduce:** Cast judgement of Justice on a player (duration 10 seconds in pvp) and wait 10 seconds for the JoJ to fall off, and see that the HotC (duration 20 sec by default) stays on with no Judgement debuff present.

**How it should work:** Heart of the Crusader is an extension of the Judgement Debuff and if the judgement debuff is not present anymore it should be removed as well. It also applies to the Judgement debuff getting dispeled by magic dispel mechanics, or pvp trinket.

**Database links:** https://www.wowhead.com/wotlk/spell=20337/heart-of-the-crusader

**Comment by haephaistoss** [comment]
Same with https://www.wowhead.com/wotlk/spell=53696/judgements-of-the-just

Do we need a separate report, or is it fine if I just leave it here?

These were all extensions of judgement debuffs which already have all 3 spell effect slots taken by other effects, so blizz usually goes around this by simply calling another debuff to do the rest.

**Comment by haephaistoss** [comment]
@Piootrek 

Yesterday on BG I cleansed enemy paladin's judgement debuff, and HotC remained on me. 

It was judgement of wisdom though.

It should be removed in any case the judgement debuff that applied it is removed

**Comment by Piootrek** [comment]
Fixed
