### ISSUE TITLE
Ritual of Summoning takes an eternity to cast 

### ISSUE THREAD

**Issue by Robosterone** [gamefreedomgit/Frostmourne#163]
**Description:**
Warlock Portal takes an eternity to cast even when 2 ppl are clicking it

**How to reproduce:**
i guess you'll need 2 another ppl to help you with that

**How it should work:**
It should be cast in around 5 seconds.

**Database links:**

**Comment by WhitemaneIsa** [comment]
No further info/complaints, closing.
