### ISSUE TITLE
[PTR] Hodir, mages spawn fire too late.

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#1630]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)
Note: this was tested over a week ago but I didn't get around to writing reports.

**EDIT: I tested again with commands and It turns out the mages don't spawn fires until both of the mages have been freed, and they always spawn them at the same time. I tested this by pulling the boss, immediately freeing one mage and waiting about 19 seconds before freeing the second one. Both fires spawned 15 seconds after that. A total of 34 seconds after the first mage was freed. The fires always seem to spawn 10-15 seconds after the second mage has been freed.**

**Description:**
The mages on Hodir place fire too slowly. I timed it to approximately 20 seconds after they are freed, which makes it essentially impossible to keep the fire stacks on the boss. 

How it should work:
If you bring it down to 15 seconds it is possible, but difficult. On Frosthold they wrote that it was supposed to be cast after 10 seconds. 

On retail I saw it spawn after 2-4 sec but that was post-nerf and should only happen on normal difficulty. In the video, the mage is freed after 5 seconds and fire spawns at the bottom at 9 seconds. Same thing after flash freeze: the mage is freed at 1:24 into the fight and fire spawns at 1:26.

This hotfix from 2 weeks after ulduar released shows the nerf.
https://wowwiki-archive.fandom.com/wiki/Hodir_(tactics)
_Hotfix (2009-04-30): "The NPCs in the Hodir encounter will now cast [Storm Power](http://www.wowhead.com/?spell=65123) and Toasty Fire more quickly after being freed from Flash Freeze at the start of the encounter. [Toasty Fire](http://www.wowhead.com/?spell=62821) will also be cast more consistently throughout the fight._

https://archive.is/6WwGI
https://www.youtube.com/watch?v=QAFfbZHUf5Y -

**Comment by Afgann** [comment]
fixed
