### ISSUE TITLE
[PTR] Hodir, fire stacks too much

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#1631]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)
Note: this was tested a week ago but I didn't get around to posting.

**Description:**
The fire debuff on the boss currently stacks up to 30, when it should stop at 25. On some websites you will see it say 30 stacks and a comment from wowhead mentioned how it was changed in patch 3.1.2, but neither me or my guildies can find it in any changelog. 

I then went back to look at several videos of kills from before that patch which I've linked below, and I never saw it stack up to 30.

**Database links:**
![image](https://github.com/user-attachments/assets/cdc1a682-f6cf-4b82-a245-de8facc26522)

Video after patch 3.1.2:
https://www.youtube.com/watch?v=cp3DWc9E3sw
Videos before patch 3.1.2: 
https://www.youtube.com/watch?v=Z82I60IeXPo
https://www.youtube.com/watch?v=CFrtcxjT9ro
https://www.youtube.com/watch?v=O075LDUA0Pw

**Comment by Manpower99** [comment]
Classic vods also had it on 25 Stacks max.

**Comment by Afgann** [comment]
fixed
