### ISSUE TITLE
[PTR] Hodir becomes permanently bugged if the server crashes/restarts while he is respawning

### ISSUE THREAD

**Issue by oomshroom** [gamefreedomgit/Frostmourne#1632]
While Hodir was in the process of respawning after despawning due to a wipe, the server crashed. Once the server came back up, Hodir was spawned but the other mobs which are part of the encounter (friendly NPCs and their associated Flash Freeze) were nowhere to be found. Pulling the boss and resetting/wiping did not fix the problem, there seemed to be no way to un-bug the encounter.

Obviously not easy to reproduce on the PTR due to requiring a server crash.

**Comment by Afgann** [comment]
fixed
