### ISSUE TITLE
[PTR] Algalon doesn't spawn on heroic 25m

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#1634]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Even after unlocking the door to Heroic 25m Algalon by killing all of the prerequisite hardmodes on heroic, Algalon doesn't spawn. The Brann roleplay starts but the boss never arrives and Brann simply remains where he's standing.

Just to make sure, I killed every single boss on heroic and made sure hardmode was enabled in cases where it wasn't forced.

**Comment by Afgann** [comment]
fixed

**Comment by Afgann** [comment]
fixed
