### ISSUE TITLE
[API] Event(s) related to reset of spells CDs after encounters

### ISSUE THREAD

**Issue by Shineslippers** [gamefreedomgit/Frostmourne#1637]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Addons and WA auras doesn't reset after encounters.

**How to reproduce:**
Use any of it  in dungeons, raids and etc. 

**How it should work:**
Need some API event(s) that can use addons or WA that will call reset of CDs. Something like ENCOUNTE_END, ENCOUNTER_RESET

**Database links:**
It's about [this](https://github.com/gamefreedomgit/Frostmourne/issues/12) topic

**Comment by Manpower99** [comment]
Yes please, improvements to the CD/sated reset system would be appreciated, along with API event so we can add it to our weak auras.

**Comment by Riztazz** [comment]
Ok, so all bosses should send INSTANCE_ENCOUNTER_ENGAGE_UNIT event, the way to interact with this event is to query the global tables _G["Boss"..i.."TargetFrame"]

which returns a target frame structure which contains .unit field which we can use to check if unit exists or not
```
function SomeFunction()
    print("Instance Encounter Addon Loaded!")
    local frame = CreateFrame("Frame")
    frame:RegisterEvent("INSTANCE_ENCOUNTER_ENGAGE_UNIT")

    frame:SetScript("OnEvent", function(self, event, ...)
        if event == "INSTANCE_ENCOUNTER_ENGAGE_UNIT" then
            for i = 1, MAX_BOSS_FRAMES do
                local boss = _G["Boss"..i.."TargetFrame"];
                if ( not UnitExists(boss.unit) ) then
                    print("Boss not exists")
                else
                    print("Boss exists")
                end
            end
        end
    end)
end
```

https://github.com/wowgaming/3.3.5-interface-files/blob/d0339b17b0221db76e6acd2dc2915d224a5b62ca/TargetFrame.lua#L158

in 3.3.5a interface code from Blizzard.

Is this enough?

Some bosses might be missing code to initialize the frame but that's per boss issue and report as boss issue please

**Comment by Shineslippers** [comment]
Thank you for the info. I did check some bosses and it's seems like working. I can use it for raids, but it's not the solution. Server has several other instances where reset of spells is working. We're talking abount dungeons, duels and idk what else. Will be nice to have general solution for everything and don'r relay on specific cases. I'm sure you're running same code for this and it can give callback as event.

**Comment by Riztazz** [comment]
Alright, i'll talk with other devs and come up with something

**Comment by Shineslippers** [comment]
Not sure i do understand what addons you're talking about. Something like OmniCC? It shows only personal CDs. We're talking about group CDs. As example when in group several shamans only one is using Bloodlust. So any personal CD can't get use as reference to addon/wa about raid CDs. If player is not using spells - doesn't mean it didn't get reset.

Addon channel message at the end anyway fires CHAT_MSG_ADDON event. It's ok for Addons/WA. If i can get it from server this way that will be nice too. I guess this way it will not work without `Whitemane-WotLK-Patch`.

**Comment by Riztazz** [comment]
Alright, i'm down for implementing WM_GROUP_COOLDOWN_RESET or whatever via addon channel but it's not solely up to me, i'll ask around and get back to you

**Comment by Shineslippers** [comment]
Hope "GROUP" doesn't stand for group(several players). Reset is working as i mentioned for duels. Player should not be in group for it. Hope it will cover all occasions where the reset is implemented.

**Comment by Riztazz** [comment]
I'll see what i can do about duels, but there is high chance i won't be able to broadcast cooldown reset for nearby player in non-instance map due to.. optimizations, that's pretty expensive to do but like i said, i'll see what magic i can do

**Comment by Riztazz** [comment]
Ok, we will do this via addon channel like i've mentioned previously:
The addon event will be:
WME_CDOWN_RESET

The message payload will always start with reset type, where:

0 - Instance reset
1 - Duel reset, followed by dueler names separated by ; 
For example: WME_CDOWN_RESET\t1;PlayerA;PlayerB

for instance reset the message will be: WME_CDOWN_RESET\t0

For duelers only people in close vicinity will receive that message, i am gonna add 50 yards as default and it can be tweaked via config but that's up to @RadeghostWM later :)

**Comment by Riztazz** [comment]
Fixed, will close once it's live

**Comment by Riztazz** [comment]
```
function Tester()
    print("Tester initialized!")
    local frame = CreateFrame("Frame")
    frame:RegisterEvent("CHAT_MSG_ADDON")

    frame:SetScript("OnEvent", function(self, event, ...)
        if event == "CHAT_MSG_ADDON" then
            local prefix, message, channel, sender = ...
            print("got addon message with prefix: " .. prefix)

            if prefix == "WME_CDOWN_RESET" then
                print("Received WME_CDOWN_RESET with payload: " .. message)
            end
        end
    end)

    C_ChatInfo.RegisterAddonMessagePrefix("WME_CDOWN_RESET")
end
```

Leaving my test code in case anyone needs it

**Comment by Shineslippers** [comment]
Appreciate it. Did check in some instances and duel. So far so good. Waiting for live release to check it in real life xD
