### ISSUE TITLE
Transmog rules are wrong and should be changed.

### ISSUE THREAD

**Issue by Steadydnt** [gamefreedomgit/Frostmourne#1638]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Hello. Since Transmog is free now for everyone there is still a big problem for every Caster Class with it. They cant transmog weapons especially Warlocks, Mages, Priests, Druids and Shamans because you have a restriction only towards these 5 classes. The Restriction off only beeing allowed to Transmog MAINHANDS to your current lvl 80 Caster Mainhand. I saw a message on your Discord about your rules in Transmog that is similar to Retail Cataclysm. But in Retail Cataclysm , you were allowed to enchant any one-handed weapon that you are allowed to wear to your current Main-Hand weapon.
**How to reproduce:**
Any One-Handed weapon, that your class is allowed to wear, should be able to be used as Transmog Appearance for your current Spellpower-Mainhand weapon.

**How it should work:**
Any One-handed weapon for example any one-handed sword should be allowed to be used as transmog , for a casters Mainhand.
The Link below is from orginal Blizzard Retail forum back in 2011. Where the Community Admin posted the rules of transmog with it release in Phase 3.
Its saying "One-handed weapons can be used to transmogrify a Main hand or Off-hand weapon.

**Database links:**
https://web.archive.org/web/20110923232914/http://us.battle.net/wow/en/forum/topic/3196342583

**Comment by Piootrek** [comment]
@RadeghostWM
