### ISSUE TITLE
Two of the Kalu'ak Dailies don't apply Rep Bonuses

### ISSUE THREAD

**Issue by LezChap** [gamefreedomgit/Frostmourne#1639]
https://www.wowhead.com/wotlk/quest=11945/preparing-for-the-worst
https://www.wowhead.com/wotlk/quest=11960/planning-for-the-future

These two quests started giving 500 rep in patch 3.3.3 (according to comments).  Currently on live they give 500 rep on each turn-in, both before and after the bonus weekend.  I'm doubting the Ancestral Spirit or whatever bonus is applying either, but I can't test that on my account.  The third daily (https://www.wowhead.com/wotlk/quest=11472/the-way-to-his-heart) appears to be applying bonuses as it gives much higher rep than the other two, when all three should give the same rep.

**Comment by Riztazz** [comment]
fixed, will close once it's live
