### ISSUE TITLE
Boss frames problem

### ISSUE THREAD

**Issue by Robosterone** [gamefreedomgit/Frostmourne#164]
**Description:**
I don't think boss frames are implemented correctly. On our raid I had only KTs bossframe showing up from all bosses. Twitch VOD so you can actually check (stream from 16.2.) https://www.twitch.tv/videos/2064557382

**How to reproduce:**
Go in raid with enabled bossframes (in elvui for example.)

**How it should work:**
Every boss should have its frame

**Database links:**

**Comment by UltraNix** [comment]
Already fixed.
