### ISSUE TITLE
Command .arena ann doesn't toggle

### ISSUE THREAD

**Issue by LezChap** [gamefreedomgit/Frostmourne#1640]
https://github.com/gamefreedomgit/Frostmourne/issues/1594#issuecomment-2293081574

Dev said there's three commands to toggle various server announcements in the issue above.  Two seem to work as expected, but the ".arena ann" command always returns that arena announcements are enabled, and doesn't toggle them off.

**Comment by RadeghostWM** [comment]
.arena ann on

That's how it works for now and it will be changed when a new patch hits. Please respond whether it works for you

**Comment by WhitemaneChronus** [comment]
`.arena ann on` and `.arena ann off` both results in "Arena announcements are now enabled!"

![image](https://github.com/user-attachments/assets/f76bcfe6-a71b-421c-9f6d-08828c8d5453)
