### ISSUE TITLE
Questioning Reethe

### ISSUE THREAD

**Issue by Vaxsysl** [gamefreedomgit/Frostmourne#1641]
**Description:**
Quest can get bugged easily. Once, I CCed the archer NPC and upon killing everyone, Ogron did not talk to Reethe. GM reset the NPCs for me. A week later I'm here with a new char and upon arriving to the area it was bugged and I couldn't take the quest. I asked a GM to reset NPCs for me. The battle went through, dialogue went through, but I got no completion prompt. I abandoned, talked with Ogron and restarted the quest, but Paval Reethe was not spawned yet. Dialogue went through even though NPC was dead (??), Theramore squad spawned, and nothing happened. NPCs got bugged. After another GM reset, the encounter worked just fine.

**How to reproduce:**
First bug I got was when I CCed the archer NPC and killed the rest first and it last. Someone can also perma-bug it if they run away or start the quest while Reethe has not yet respawned. It takes GMs resetting NPCs to get the quest into working state again.

**How it should work:**
Quest "works" fine, but it can get bugged as explained above, needing GM help or realm reset to get it into working state again.

**Database links:**
https://www.wowhead.com/wotlk/quest=1273/questioning-reethe
https://www.wowhead.com/wotlk/npc=4980/paval-reethe
https://www.wowhead.com/wotlk/npc=4983/ogron

**Comment by Piootrek** [comment]
Fixed
