### ISSUE TITLE
Overstock Quest - NPCs spawn under map.

### ISSUE THREAD

**Issue by Althora** [gamefreedomgit/Frostmourne#1642]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Quest "Overstock" does not spawn necessary quest-related mobs in the designated area. (Minefield). Scanning minimap for humanoids show them spawning, but I believe they may be underneath the map. 

QuestID: 12833

**How to reproduce:**
Self-Explanatory.

**How it should work:**
Get Quest.
Place Landmines in minefield as designated.
Enemies spawn and run over mines & die.
Dance and turn in quest.

**Database links:**
https://www.wowhead.com/wotlk/quest=12833/overstock#comments

**Comment by Riztazz** [comment]
Possibly fixed as i couldn't really reproduce but educated guess was the long paths, i've created detailed paths for them so hopefully that fixes it.
Will let you know once it's live
