### ISSUE TITLE
[PoW] Items Missing from PoW

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1643]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Some items that are bis on wotlk are missing from PoW vendors:

https://www.wowhead.com/wotlk/item=33504/libram-of-divine-purpose
https://www.wowhead.com/wotlk/item=33503/libram-of-divine-judgement
https://www.wowhead.com/wotlk/item=30846/arcanum-of-the-outcast

Also 33503 is bugged and doesn't work as it should.

https://github.com/gamefreedomgit/Frostmourne/issues/1230

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Riztazz** [comment]
fixed, will close once it's live
