### ISSUE TITLE
[Quest] The cleasing - Howling Fjord

### ISSUE THREAD

**Issue by Urukhaii93** [gamefreedomgit/Frostmourne#1644]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
We braved the Rivenwood because of my troubled dreams concerning my worg life-friend, Ulfang. He has called out for help, and you must go to him.

But, you do not have the means to speak with him, or walk amongst the other worgs. I know a way.

First, you must cleanse [your inner turmoil](https://www.wowhead.com/wotlk/npc=27959/your-inner-turmoil).

There is a shrine that sits at the top of Frostblade Peak, northeast of Camp Winterhoof. A single path leads up to it from the western base of the mountain.

Meditate there and then return to me.
**How to reproduce:**
Be horde and try the quest.

**How it should work:**
You should click on altar

**Database links:**

**Comment by Riztazz** [comment]
fixed, will close once it's live
