### ISSUE TITLE
[Paladin] Beacon of Light applies the original heal's modifiers to the beacon heal

### ISSUE THREAD

**Issue by oomshroom** [gamefreedomgit/Frostmourne#1645]
The duplicated heal from Beacon of Light includes healing modifiers to the target of the original heal (say, Holy Light).

Example:
- assume a normal Holy Light heals for 10k
- place Beacon of Light on unit A, which has no modifiers to healing taken
- cast Holy Light on unit B, which has 40% increased healing taken
- unit A gets healed by beacon for 14k instead of 10k

This can easily be abused in raids with a Hunter tenacity pet, Warlock Demon Armor, etc.

[comment about wotlk 3.3.5](https://www.wowhead.com/forums/topic/a-question-about-beacon-and-dreamwalker-157793#p2083673)
[comment about wotlk classic](https://old.reddit.com/r/wotlk/comments/17eoe89/valithria/k64rlmr/)

**Comment by reminuz** [comment]
Same thing with mortal strike in arena. If i heal a target with mortal strike, beacon should receive 100% healing, not 50%

**Comment by oomshroom** [comment]
In the example you provided, target A with Demon Armor SHOULD receive 20% more healing from beacon.

Proof from wotlk classic:
[](https://classic.warcraftlogs.com/reports/TZN7kKHnV9c2BFm8#fight=5&type=summary&view=events&pins=2%24Off%24%23244F4B%24expression%24ability.name%3D%22Beacon%20of%20Light%22%5E2%24Off%24%23909049%24expression%24ability.name%3D%22Vampiric%20Blood%22)
When Vampiric Blood is used, beacon heals clearly become 35% larger (21k->28k or so)


Proof from wotlk 3.3.5:
[](https://www.youtube.com/watch?v=nt8ZUyVDqYc)
at around 3:07 you can see him use Vampiric Blood, and the beacon heals from crit holy lights become ~27k when they were previously ~20k.

**Comment by Rowern96** [comment]
as far as i understand it, the spell is copied on the beacon target but the heal amount is calculated seperatly on both targets depending on their buffs and debuffs

**Comment by reminuz** [comment]
https://youtu.be/8HnEhpwDdEI?si=rdRDfm-t6RZ-Id49
min 42.50
U can see 2.6k healing on war with mortal strike and 5.2k on paladin with beacon

**Comment by reminuz** [comment]
Up
