### ISSUE TITLE
[Paladin / Rogue] Evasion vs Hammer of Wrath

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1647]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Rogue with evasion seems to affect hammer of wrath hit chance

**How to reproduce:** Cast hammer of wrath onto a rogue with evasion fully hitcapped

**How it should work:** HoW is a 'spell' that deals holy dmg, uses melee hit table (thus being melee attack), cannot be dodged, or parried, and isn't affected by ranged modifying stuff. Currently it seems to be affected by ranged hit chance reduction.

**Database links:** https://www.wowhead.com/wotlk/spell=48806/hammer-of-wrath    https://www.wowhead.com/wotlk/spell=26669/evasion

**Comment by Afgann** [comment]
fixed
