### ISSUE TITLE
[Quest] The Cleansing

### ISSUE THREAD

**Issue by Aeradel** [gamefreedomgit/Frostmourne#1648]
There is a horde and an alliance version to this quest.

The alliance version [11322] works fine.

The horde version [11317] does not work properly. The item (which is also used in the alliance version) can not be used. It can not be interacted with.

**Comment by Riztazz** [comment]
duplicate of https://github.com/gamefreedomgit/Frostmourne/issues/1644 which im going to fix in a bit :P
