### ISSUE TITLE
sourgebane elixir

### ISSUE THREAD

**Issue by Requiemafk** [gamefreedomgit/Frostmourne#1649]
Description: scourgebane infusion and scourgebane draught its stackable with flask and elixirs

How it should work: these elixirs must share cooldown with flasks and battle or guardian elixir as the wowhead database says.

Database links:
https://www.wowhead.com/wotlk/item=22778/scourgebane-infusion#shared-cooldown;50
https://www.wowhead.com/wotlk/item=22779/scourgebane-draught#shared-cooldown;50

**Comment by Steadydnt** [comment]
They do and should stack with Flask if you mean this. The "Shared Cooldown" list from wowhead is not about stacking effects.

**Comment by Requiemafk** [comment]
they shouldnt stack with battle or guardian elixir, thats why this elixir was fixed in warmane s3, same situation with kreegs beer from dire maul btw this beer works properly in this server.

**Comment by Manpower99** [comment]
Bruh this is another ridiculou bug report from an alliance player i have no words except please touch grass and maybe try again with actual proof.

regardless i will do my best to provide proof against this fallacy :
 1. Shared cooldown does not mean anything except the 1-3s timer between using consumes, you know this 100% you are just attempting to mislead devs into believing this bovine fecal matter theory.
 2. It does not state in the tooltip of the item or the buff that is either an elixir of a guardian/battle elixir or a flask so thats a hard no.
 3. warcraftlogs there are thousands of players who used it with the regular flask and it stacked, you can look up all the top logs in naxxramas if you wish for it. 
 This is P1 US/EU top1 unholy dk log and quite easily you can see which buffs he had 
https://classic.warcraftlogs.com/reports/g9h1zLyAtDjf7rX4#fight=20&type=auras&source=19
100% Uptime of flask of endless rage and 100% uptime on scourgebane draught.


 - You know it is quite obvious you're an alliance player who couldnt convince devs to make the game run your way and allow it for alliance also as evidenced by this https://github.com/gamefreedomgit/Frostmourne/issues/1534 so you decided to try and ruin it for the rest of the players.

**Comment by BalanCV** [comment]
It takes one click from OPs links to wowhead to reach comments and see some from 3.3.5 affirming that it stack with flask and with themselves.
Also warmane actually made them stack sometime in fm3, similar to what whitemane did in beta, as stock trinity considers them elixirs for deprecated reasons.

Good effort false reporting for personal benefit(other's detriment?) though. As a prize I'm going to tell you that alliance can use this small buff as well, but I'm not gonna tell you how.

**Comment by Steadydnt** [comment]
I didnt want to roast him like this but yea people confirming he is wrong and speaking absolute no sense.
Issue can be closed here.

**Comment by Manpower99** [comment]
Regardless of my previous comment which is proof relevant to Whitemane, i will also link proof against your claim that Warmane "fixed" it. the reality is that it is prior to S3 where it was bugged and didnt stack, after S3 it started to stack ( both with flask and with eachother )
https://www.warmane.com/bugtracker/report/116663
