### ISSUE TITLE
Late combat bug

### ISSUE THREAD

**Issue by Robosterone** [gamefreedomgit/Frostmourne#165]
**Description:**
It takes around 5 seconds to get combat after a trash pull in Naxx. Clip: https://clips.twitch.tv/JollySavagePidgeonJonCarnage-E0CJYch6j_4LQLDN (see combat icon in middle of my frame)

**How it should work:**
You should get combat immediately as you attack.

**Database links:**

**Comment by Afgann** [comment]
fixed
