### ISSUE TITLE
[PTR] XT 25 hc gravity bomb damage

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#1651]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

The damage of gravity bomb on 25m hc XT is exactly 15k unmitigated, the same as on normal mode and a lot less than the 19k-21k dmg listed for frosthold. It's also less than you can see it doing in classic sometimes. (I saw up to 18.6k after resistances)

The bomb damage on the PTR is unaffected by heartbreaker damage bonus, but based on the videos I linked, I don't think it's supposed to be affected. Difficult to tell for sure because of shields and other damage reduction.

Increase the base damage of the gravity bomb in 25hc to 19k-21k.

**Database links:**
https://archive.is/6WwGI

Frosthold: Early gravity bombs may have done less before hardmode activation. DK and demo lock got hit though, so it's difficult to compare damage.
https://www.youtube.com/watch?v=IVEOiyqbeKA&t

Classic: Damage seems essentially unchanged after hardmode activation. Also, you can see the hunter take 18.6k dmg at 2:34.
https://www.youtube.com/watch?v=MDu8Lo1Q8sI

**Comment by Afgann** [comment]
fixed
