### ISSUE TITLE
[PTR] Yogg 25 heroic health

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#1653]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

Yogg 25 heroic has 13.2 million hp in the last phase, instead of the stated 16.5 million. Only applies to 0 lights.

**Database links:**
https://archive.is/6WwGI

**Comment by Afgann** [comment]
fixed
