### ISSUE TITLE
Hateful Strike Target Selection - Patchwerk

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1654]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Currently if Main Tank/Patchwerk's Target is below someone in threat from 101-109%, he will be be the target of both his white swings and his hateful strike.
It shouldn't be like this, if this ever occurs it would be the 3rd/1st highest threatening target in melee range with highest current hp who gets it since a Main tank is the Primary target.

This issue was not noticable previously since patchwerk was incorrectly tauntable, because initial threat and build up was way easier and now it is relied upon actually building threat as it should be since patchwerk correctly got fixed into a taunt-immune boss, the only way to correct it is by offtanks intentionally doing less threat than they should. however when dealing with a high melee dps raid and tanks who could possibly be weaker geared or generally clueless pugs, then this becomes quite a headache.

**Database links:**

**Comment by Riztazz** [comment]
Fixed, will close once it's live
