### ISSUE TITLE
Sapphiron's Key to the Focusing Iris and ML

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1655]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Both the Regular 10man and the Heroic 25man versions cannot be masterlooted/assigned by the masterlooter if he already has the item/quest done. 
it should never work this way, items of similar nature such as Onyxia's Head/Nefarian's Head etc, by blizzlike standards should always be able to be masterlooted.

**Database links:**
https://www.wowhead.com/wotlk/item=44569/key-to-the-focusing-iris
https://www.wowhead.com/wotlk/item=44577/heroic-key-to-the-focusing-iris

**Comment by Piootrek** [comment]
Fixed
