### ISSUE TITLE
SWP (TW) - Kalecgos fight, portals not working properly

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1656]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

We have several raids that are having an issue with [Kalecgos](https://www.wowhead.com/wotlk/npc=24850/kalecgos) fight.
After taking a portal, the NPC [Sathrovarr the Corruptor](https://www.wowhead.com/wotlk/npc=24892/sathrovarr-the-corruptor) does not spawn. players cannot find any npcs inside the portal.

**How to reproduce:**

fight kalecgos in timewalking mode and go through portals.

**How it should work:**

Sathrovarr the Corruptor, should be inside so players can defeat it.

**Comment by WhitemaneChronus** [comment]
Trying it with a group atm, seems both npcs kalecgos (human form) and Sathrovarr are under the texture.

**Comment by WhitemaneChronus** [comment]
Players are getting teleported without clicking on the portals. after a few the entire raid is stuck on other platform and cannot get out.

**Comment by Afgann** [comment]
fixed
