### ISSUE TITLE
Hand of sacrifice and Divine Sacrifice

### ISSUE THREAD

**Issue by reminuz** [gamefreedomgit/Frostmourne#1657]
There is the same problem of SWD. https://github.com/gamefreedomgit/Frostmourne/issues/1407#issue-2417441340
Sacrifices don't break any cc if damage is absorbed.

**Comment by haephaistoss** [comment]
Which dmg is absorbed?
The dmg from the saced target, or the paladin the dmg should be transferred to? Or both? ^^
In any case it should work tho

**Comment by haephaistoss** [comment]
if the saced target has absorb on them, sac should split 0 dmg to the paladin, that 0 dmg should be absorbed but still count as dmg, and break ccs that break on dmg, as mentioned in a previous post

**Comment by haephaistoss** [comment]
Same if dmg is further split:

For instance: 

Warlock SL + Pet + sac on pet.

or Target saced by paladin1 who is saced by paladin2

and in all of the above, everybody has a shield that absorbs all dmg.

**Comment by haephaistoss** [comment]
Also, it should keep working this way when spellstolen:

https://github.com/gamefreedomgit/Frostmourne/issues/1650

**Comment by Piootrek** [comment]
Fixed
