### ISSUE TITLE
Yog 25 nm critical bug, Crusher tenticle Focused Anger debuff 

### ISSUE THREAD

**Issue by gforghieri** [gamefreedomgit/Frostmourne#1658]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

[ULDUAR PTR25M] YOGG25 normal 0 light, Crusher tenticle Focused Anger debuff is being stacked by dots, it should only be direct attacks

As the title says, it should only be direct damage, fix that,  DOTs should not keep the stacks up.

**Comment by Afgann** [comment]
fixed
