### ISSUE TITLE
You can blink through the textures in EoE

### ISSUE THREAD

**Issue by query-wow** [gamefreedomgit/Frostmourne#1659]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

![image](https://github.com/user-attachments/assets/6d23993a-dedc-4e2f-9dd0-5ae75e09a4be)

**How to reproduce:**
Blink or use the Warlock Summoning circle during vortex, which prob shouldn't even be possible 
https://youtu.be/cyGDGV49CZ8?t=105
**How it should work:**
You either shouldn't be able to blink or Summoning circle during vortex

**Database links:**

**Comment by InterstellarWhitemane** [comment]
First of all, there is no evidence on the video that you cannot free yourself from the vortex. Only that this mage doesn't even try. He didn't use the blink. Based on this video, it is nonsense to decide that it should not work.

And secondly, sparks aren't supposed to give stacks either, so even if this little help for warlocks and mages worked, it wouldn't help them at all. They can't afford to stand in spark and pump the boss anyway. Stacks would kill them when the healers are in the vortex. As a warlock main, I know that it basically only brings problems with aggro.

**Comment by query-wow** [comment]
> First of all, there is no evidence on the video that you cannot free yourself from the vortex. Only that this mage doesn't even try. He didn't use the blink. Based on this video, it is nonsense to decide that it should not work.
> 
> And secondly, sparks aren't supposed to give stacks either, so even if this little help for warlocks and mages worked, it wouldn't help them at all. They can't afford to stand in spark and pump the boss anyway. Stacks would kill them when the healers are in the vortex. As a warlock main, I know that it basically only brings problems with aggro.

There's no evidence that you can either. Feel free to get one. I've watched 3 videos and no one does it, if they could do so, they would for the muh parsing. It's obviously not intended and the only video where you can see this is a kekmane video

**Comment by Afgann** [comment]
fixed
