### ISSUE TITLE
[NPC] Zul'Farrak, Chief Ukorz Sandscalp is casting Felfire Fission

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1662]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

NPC in low level dungeon, [Chief Ukorz Sandscalp](https://www.wowhead.com/wotlk/npc=7267/chief-ukorz-sandscalp) is casting the spell [Felfire Fission](https://www.wowhead.com/wotlk/spell=45779/felfire-fission).
The spell kills level 80 characters immediately.

additionally the door to this boss is open by default which shouldnt be. it opens after the event on previous boss. (freeing prisoners)

![image](https://github.com/user-attachments/assets/65223d5b-5d09-4bd6-b924-3d57d55ff226)

**How to reproduce:**

start the fight with Chief Ukorz Sandscalp

**How it should work:**

that's a spell from swp mobs, this npc should cast this spell 

**Database links:**
https://www.wowhead.com/wotlk/npc=7267/chief-ukorz-sandscalp
https://www.wowhead.com/wotlk/spell=45779/felfire-fission

**Comment by WhitemaneIsa** [comment]
Copy paste from the two tickets:

here are the screenshots about the kill, sadly i dont have the combat log without being cropped.
https://imgur.com/D7qJA0f
https://imgur.com/7SBCkVX
https://imgur.com/a/EEYdayn
