### ISSUE TITLE
[MAGE / WARLOCK] Nightmare (Improved Fear) vs Mage Armor

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1663]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**  in some cases Mage Armor magic debuff 50 % duration reduction was not affecting certain magic debuffs on OG Wrath.

One notable example is Improved Fear in Affliction Warlock tree.

Currently the applied debuff is cut in half as it theoretically should be, but in reality that's not how it worked.

Like this:

![image](https://github.com/user-attachments/assets/0c53145a-43ab-4758-add4-5eb7a25a5df8)

Generally speaking, a rule of thumb here is that if a magic debuff is refreshed rather than 'applied', it should be back to it's full (uncut) duration, even if it was halved at the parent application. - this part seems to be working, only outlier is Nightmare here.

Effects like this include: corruption refresh via shadowbolt, and similar magic refreshes.

**How to reproduce:**

**How it should work:** 

https://www.warcraftmovies.com/movieview.php?id=161647
8:43

https://www.warcraftmovies.com/movieview.php?id=158353

15:48

**Database links:**  https://www.wowhead.com/wotlk/spell=43024/mage-armor  https://www.wowhead.com/wotlk/spell=53759/improved-fear 
https://www.wowhead.com/wotlk/spell=60947/nightmare

**Comment by Piootrek** [comment]
Fixed
