### ISSUE TITLE
[Ulduar PTR] Yogg Crusher Tenticle Diminishing Power should have cooldown between casts

### ISSUE THREAD

**Issue by gforghieri** [gamefreedomgit/Frostmourne#1664]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

[Ulduar PTR] Yogg Crusher Tenticle Diminishing Power should have cooldown between casts

Right now when diminishing power is interrupted, it is instantly recast, this is incorrect.

There should be some cooldown after it is interrupted.

Proof:
https://youtube.com/clip/UgkxfcvrbdIJbf7gzRY_Ax48kh7QlYcmwNYK?si=mL5Hq5sgfqnpp9_8

**Comment by Manpower99** [comment]
Looks to be around 4s

**Comment by BalanCV** [comment]
It's a shadow school spell. Technically an interrupt should stop anything casting the same spell school for a few seconds depending on the interrupt spell (ex: rog kick=5sec, dk mind freeze=4sec)
Weirdly enough this is working properly for corruptor tentacles which use 2 spell schools(nature,shadow), this one uses only 1...

**Comment by Manpower99** [comment]
> It's a shadow school spell. Technically an interrupt should stop anything casting the same spell school for a few seconds depending on the interrupt spell (ex: rog kick=5sec, dk mind freeze=4sec) Weirdly enough this is working properly for corruptor tentacles which use 2 spell schools(nature,shadow), this one uses only 1...

yes but the interrupt happens without an actual interrupt it is simply being hit by a melee spell or judgement. so in this case it is more about jut adding a timer to recast it.

**Comment by sputnikk** [comment]
> > It's a shadow school spell. Technically an interrupt should stop anything casting the same spell school for a few seconds depending on the interrupt spell (ex: rog kick=5sec, dk mind freeze=4sec) Weirdly enough this is working properly for corruptor tentacles which use 2 spell schools(nature,shadow), this one uses only 1...
> 
> yes but the interrupt happens without an actual interrupt it is simply being hit by a melee spell or judgement. so in this case it is more about jut adding a timer to recast it.

Hm must mean its a mechanic to mimic spell lock from kick since you dont have that from melee spells - assuming its 4-5sec average then

**Comment by Afgann** [comment]
fixed
