### ISSUE TITLE
Ulduar Suggestion

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1667]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
In order to prevent griefing in pugs or realm first races it would be ideal if only the **Raid Leader** could speak to
[Brann Bronzebeard](https://wowpedia.fandom.com/wiki/Brann_Bronzebeard)
[Lore Keeper of Norgannon](https://wowpedia.fandom.com/wiki/Lore_Keeper_of_Norgannon_(Ulduar))

In addition to this, after defeating each Titan Keeper, only raid leader should be allowed to turn in each one of the Titan Keepers to assist them against[ Yogg-Saron.](https://wowpedia.fandom.com/wiki/Yogg-Saron_(tactics))

Understandbly not a bug but it is imo of vital importance to reduce GM tickets and overall less issues.
**Database links:**

**Comment by Manpower99** [comment]
@RadeghostWM

**Comment by LezChap** [comment]
I'd say allow Raid Leader and Raid Assists.  You shouldn't be giving assists out to people you don't trust anyways.

**Comment by Afgann** [comment]
fixed
