### ISSUE TITLE
[Critical] Yogg 25 most major bugs

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#1668]
Please address this one fully as Ulduar is close to releasing.
Yogg right now is in the worst spot, especially when compared to the other bosses that have been decently polished through reports.
TLDR: Yogg 25 nm is mostly using PRENERF elements that are intended for use in 25 HC. Essentially making the 25nm fight same as 25hc without the whitemane custom buffs.
In whitemane established terms 25nm=post nerf, 25hc=pre nerf+custom buffs.
https://www.youtube.com/watch?v=ScgHjGnLsF4
-Classic video source(using pre nerf values) as reference for some of the bugs and deductions below.
https://www.reddit.com/r/classicwow/comments/11rr1rk/i_compiled_a_complete_list_of_patches_hotfixes/
-Compilation of most/all ulduar related patch notes, reflecting transition from "prenerf" to "postnerf" from OG wrath. (https://archive.ph/6WwGI also alligns with some findings)

BUGS:
1. Using immunities to free yourself/others from constrictor tentacle leaves the player with Squeeze debuff still on them, causing death. This only happens when using immunity, normally damaging is fine. Debuff should be removed. (**BUG APPLIES TO BOTH 25NM and 25HC**)

2. When phase 2 starts on whitemane it instantly spawns: 1 constrictor, 2 corrupters, 1 crusher
You can see in the prenerf video initial adds should be:1 constrictor, 1 corrupter, 1 crusher (**There is an extra corrupter at spawn only that should be removed**) -**BUG APPLIES TO BOTH 25NM and 25HC (can be kept at discretion for 25HC as custom buff)**

3. After initial set of adds mentioned in 2. each tentacle spawns on a cooldown that is completely wrong on whitemane 25NM.
**Currently**: constrictor spawns every 15sec, corruptor spawns every 30sec, crusher spawns every 55sec.
**How it should be on 25NM**: constrictor spawns every 20sec, corruptor spawns every 40sec, crusher spawns every 60sec.
**How it should be on 25HC**(prenerf can be seen in video): constrictor spawns every 15 sec, corruptor spawns every 25sec, crusher spawns every 50sec.

4. Corruptor tentacles can spawn next to or inside the crusher tentacle, making it impossible for melees to dps it because Crusher has huge melee range. Either make it so they can't spawn next to each other or decrease the melee range of Crusher so that melee dps can max melee range dps the Corruptor if it spawns close to Crusher. (Could be kept as custom buff for hc?)

5. Psychosis+Malady of the mind spells function as prenerf in 25NM (these spells should not target people that have 40 sanity or less on 25NM but they do) -**NM ONLY BUG**

6. Psychosis is using wrong spell ID:
USING THIS CURRENTLY:https://wotlk.evowow.com/?spell=65301
SHOULD USE THIS:https://wotlk.evowow.com/?spell=63795
This is deduced from patch note that says psychosis can reduce you below 40 sanity as example if you have 41 to 32 (-9 sanity which is the second spell) -**BUG APPLIES TO BOTH 25NM and 25HC (can be kept at discretion for 25HC as custom buff)**

7. P3 Immortal guardians using prenerf, for 25NM they should use this instead:
- "Immortal Guardians in phase 3 have had their health reduced by 15% in heroic mode"
-"Increased the cooldown on Immortal Guardians' Drain Life ability in the Yogg-Saron encounter." unspecified by how much, can't find exact number so at dev discretion
-"Empowering Shadows in the Yogg-Saron encounter now targets a maximum of three Immortal Guardians in 25-player mode."
- Immortal Guardians' movement speed seems to be higher than it should on this server, I don't want to use "feelscraft" but I can't accurately measure this. Reference video for further investigation:https://youtu.be/bXP9TEAwhzU?si=BBDYsAlmmtkTWBS2&t=4504

**Comment by Afgann** [comment]
fixed

**Comment by Manpower99** [comment]
@Afgann unsure if this was a typo in changelog or actually applied :  
 - Crusher Tentacle will be spawned every 25s on heroic and 60s on normal mode.

**Comment by Manpower99** [comment]
@Afgann 
![image](https://github.com/user-attachments/assets/b8776282-f977-4eae-bbff-98b9311ae667)
referring to my previous comment and a possible typo in the changelog, or maybe it is actually applied but it is incorrect.

**Comment by Afgann** [comment]
@Manpower99 It was a typo, i'll change it to 50s, thanks.
