### ISSUE TITLE
SWP TW-Killjaeden bug if boss dies during darkness

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1669]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
If boss dies while casting darkness of a thousand souls, the cast prematurely gets successfully casted and oneshots the raid.

**Database links:**

**Comment by Piootrek** [comment]
Fixed
