### ISSUE TITLE
sapphiron port

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#167]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
sapphiron can be teleported into before all quarters are cleared

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
