### ISSUE TITLE
[General Vezax] Aura of Despair Shouldn't disable Blessing of Sanctuary mana procs.

### ISSUE THREAD

**Issue by awildmouse** [gamefreedomgit/Frostmourne#1671]
**Description:**
-Vezax's Aura of Despair is improperly disabling mana regen from BoS procs.

https://www.wowhead.com/spell=62692/aura-of-despair#comments

https://redmine.rising-gods.de/issues/606

**How to reproduce:**
-Place BoS on a player and dodge-block-parry, mana won't be generated.

**How it should work:**
-Should regain mana upon triggering Blessing of Sanct.

**Comment by Afgann** [comment]
fixed
