### ISSUE TITLE
Tireless Skyflare Diamond does nothing

### ISSUE THREAD

**Issue by Amhellpvp** [gamefreedomgit/Frostmourne#1674]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I have added a meta gem to my head gear but it does nothing even though it shows activated (all requirements white and not grey)

**How to reproduce:**
I suggest use same gear, but no clue what it may be the problem. I did switch gems at a point to belt from Runed Scarlet Ruby (https://www.wowhead.com/wotlk/item=39998/runed-scarlet-ruby) to https://www.wowhead.com/wotlk/item=40025/glowing-twilight-opal
Also  at a point I switched from https://www.wowhead.com/wotlk/item=28123/potent-ornate-topaz to https://www.wowhead.com/wotlk/item=40051/reckless-monarch-topaz

**How it should work:**
It should give me 25 SP and minor move speed (8%) but does nothing, neither SP nor movement speed.

**Database links:**
Head
https://www.wowhead.com/wotlk/item=42553/visage-liquification-goggles
https://www.wowhead.com/wotlk/item=40051/reckless-monarch-topaz
https://www.wowhead.com/wotlk/item=41375/tireless-skyflare-diamond (THIS DOES NOTHING)

Neck
https://www.wowhead.com/wotlk/item=37929/guardians-pendant-of-reprieve
https://www.wowhead.com/wotlk/item=40051/reckless-monarch-topaz

Belt
https://www.wowhead.com/wotlk/item=43969/frostsavage-belt
https://www.wowhead.com/wotlk/item=41611/eternal-belt-buckle
https://www.wowhead.com/wotlk/item=40025/glowing-twilight-opal

**Comment by WhitemaneChronus** [comment]
Testing on PTR, seems the prismatic socket from belt buckle is not counting towards meta gem requirements.

https://www.wowhead.com/wotlk/spell=55655/eternal-belt-buckle

**Comment by Amhellpvp** [comment]
Understood, but it showed the bonus would have been activated, and then shows is still active. Anyway, thanks for the clarification.

**Comment by WhitemaneChronus** [comment]
Based on the description ive provided, It's a bug as far as i know that needs to be addressed. 
Prismatic sockets should contribute towards meta gem activation.

**Comment by Afgann** [comment]
fixed
