### ISSUE TITLE
Item Equip/Swap forced CD

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1675]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Many Items are currently going on a 30s icd when they shouldn't be, and others are going on a 30s icd when it should be more.
https://wowwiki-archive.fandom.com/wiki/Patch_3.2.0

> Items with Triggered Effects: These items generally have cooldowns on how often they can be triggered. Those cooldowns are now triggered each time the item is equipped (example: A trinket has a 45-second cooldown on an effect triggered by player attacks; when a player equips that item, the effect will be unable to be triggered for the first 45 seconds it is worn).

Items/Enchants with PPM or no ICD should not go on a 30s ICD
Equipped shadowmourne on PTR couldn't get the stacking buff until 30s after which shouldn't be a thing
 - https://www.wowhead.com/wotlk/spell=71903/item-shadowmourne-legendary it does not have an ICD.

Many enchants with PPM are also going on a 30s ICD despite being PPM.
Trinkets should go on their full ICD, equip a trinket of 45s icd and watch as it doesnt proc until 30s later, while it should be 45s
Active Items like Active Trinkets and Enchants such as Nitro Boots/Hyperspeed Accelerators etc. should still go on a 30s Cooldown on Equip/Swap.

How it Should work : https://www.youtube.com/watch?v=NgY9BgD_r4k
**Database links:**

**Comment by Sylanha** [comment]
Not only Shadowmourne, but also the legendary weapon (Sunlute) is not doing both the Anger of motes/Blinkstrike mechanic 30 seconds after equipping the weapon.

**Comment by Manpower99** [comment]
> Not only Shadowmourne, but also the legendary weapon (Sunlute) is not doing both the Anger of motes/Blinkstrike mechanic 30 seconds after equipping the weapon.

Yes, it is a general issue. every item goes on 30s cd on equip/swap, while the way it should be is that the item goes on its Internal Cooldown. noticable even with Valanyr going on a 30s instead of 45s

**Comment by Piootrek** [comment]
Fixed

**Comment by Manpower99** [comment]
> Fixed

Thank you for the quick fix, i will make sure to report to you if anything is incorrect after it is applied to ptr

**Comment by Manpower99** [comment]
> Fixed

Unsure what is applied and what is not at this point, Black Magic which should go on a 35s CD on equip/swap is instant proccing lol. should i remake the bug report or what

**Comment by Piootrek** [comment]
Server wasn't updated with this fix yet

**Comment by Manpower99** [comment]
> Server wasn't updated with this fix yet

Understood 👍

**Comment by Piootrek** [comment]
Actually, my fix worked just for item effects, not for enchants. Fixed, thank you for the report
