### ISSUE TITLE
Bugged quest - Banshee's Revenge

### ISSUE THREAD

**Issue by rapco259** [gamefreedomgit/Frostmourne#1676]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Banshee's Revenge on Live server. After blowing horn the Overthane Balargarde doesn't spawn where he should. He instead keeps falling on the other side of the tower all the way down to the balcony where he can't be engaged in a fight.

**How to reproduce:**
Blow horn. Wait. Boss nowhere to be found:p.

**How it should work:**
Boss should spawn properly and should engage in a fight.

**Database links:**
https://www.youtube.com/watch?v=9mACaDzbiG8
https://www.wowhead.com/wotlk/quest=13142/banshees-revenge

**Comment by WhitemaneChronus** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/1501
for now try to use the horn and run into the middle of the platform immediately or open an in-game ticket

**Comment by rapco259** [comment]
Thank you for helping me!:)

**Comment by Piootrek** [comment]
Fixed
