### ISSUE TITLE
Fury of the Five Flights has an ICD

### ISSUE THREAD

**Issue by Sylanha** [gamefreedomgit/Frostmourne#1678]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)
https://www.wowhead.com/wotlk/item=40431/fury-of-the-five-flights

**Description:**
Fury of the Five Flights has an ICD, which it shouldn't have. So if I equip it, it should be ready and able to stack instantly. It has an internal cooldown of 30 seconds before being able to apply stacks on the user. (It should be stacking instantly)

**How to reproduce:**
Equip the trinket Fury of the Five Flights and watch your buff bar if the trinket buff applies (or not in this case).

**How it should work:**
Equipping the trinket should make it that if I attack right after doing so it should instantly start stacking and not after an ICD, which shouldn't be there at all (the ICD I am talking about is 30 seconds).

**Database links:**
https://youtu.be/RHMrTQy9ftY

**Comment by Manpower99** [comment]
Same issue with many trinkets/items that have no ICD triggering a 30s cooldown on item swapping or equipping.
https://github.com/gamefreedomgit/Frostmourne/issues/1675

**Comment by Piootrek** [comment]
Fixed
