### ISSUE TITLE
Maexxna Wraps

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#168]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
If you kill maexxna while people are still wrapped, the wraps are not attackable but they still go through full duration.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
