### ISSUE TITLE
Transmog not found  [Wildheart Kilt] leather leggings

### ISSUE THREAD

**Issue by jpaardekooper** [gamefreedomgit/Frostmourne#1680]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
 [Wildheart Kilt] not able to select this option in transmog menu

**How to reproduce:**
Farm baron rivendare 3 weeks straight to get  [Wildheart Kilt]. And figure out that you can't select the leggings as a option

**How it should work:**
Should be able to select this transmog 

**Database links:**
https://www.wowhead.com/classic/item=16719/wildheart-kilt

**Comment by Piootrek** [comment]
Works correctly for me. What item are you trying to transmogrify with?
