### ISSUE TITLE
DRW should swap target on immunities

### ISSUE THREAD

**Issue by danniellos94** [gamefreedomgit/Frostmourne#1681]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

DRW (Dancing rune weapon) should swap target on immunities.

**How to reproduce:**
Use DRW on paladin which makes bubble.

**How it should work:**
DRW should swap to the next player you target after the first did iceblock/ divine shield / HOP is cycloned etc (any immunity).

**Database links:**
https://www.wowhead.com/wotlk/spell=49028/dancing-rune-weapon
https://youtu.be/8hbS9hRJXGk?t=144

**Comment by Piootrek** [comment]
Fixed
