### ISSUE TITLE
PTR Kologart Hitbox and boss frame bug 

### ISSUE THREAD

**Issue by elyoph** [gamefreedomgit/Frostmourne#1682]
Kologart has two bugs:

Hitbox issue with the left arm: When clicking on the nameplate of the left arm, it toggles between the torso and the arm due to a hitbox problem. This issue does not occur with the right arm. You can see this in the following video:

https://www.youtube.com/watch?v=bxGA6DvJFqQ

How to replicate: Open the game without addons, stand in front of the boss, and click repeatedly on each of the arms from the respective nameplates.

Boss frames disappearing after death: When you die once in Kologart, the boss frames break and disappear. This means that unless you close and reopen the game, the boss frames will disappear permanently on all the next bosses. The video shows how the boss frames, located below the minimap, disappear one by one.

https://youtu.be/lxNkXFM8sG8

How to replicate: Stand in front of the boss, die, revive, and repeat the process twice. The first time, one of the three boss frames will disappear, and the second time, all the boss frames will disappear.

Interestingly, nameplates work correctly with other bosses, regardless of the addons used, but with Kologart, all existing configurations break and must be reset from scratch.

**Comment by Afgann** [comment]
fixed
