### ISSUE TITLE
Path of war dual talent specialization 

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1683]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

PVE characters who are joining path of war using the NPC Thalor the Tenacious, cannot learn dual talent specialization.
Talking to NPC big daddy mane only changes the gear on main spec, and talking to NPC Arcanis (class master) does not work as well, "you dont have enough money". The cost is 10g and player has 200g after joining pow.

![Screenshot 2024-08-25 220055](https://github.com/user-attachments/assets/5798dbe3-127b-40d7-b31d-bfe95cd66861)

**How to reproduce:**

Join path of war by talking to Thalor the Tenacious on a level 80 character that does not have dual talent specialization enabled.

**How it should work:**

Player should be able to purchase it using the class master npc in pow area.

**Comment by Riztazz** [comment]
fixed, will close once it's live
