### ISSUE TITLE
[Quest] Let's Get Out of Here - escort doesn't move

### ISSUE THREAD

**Issue by LezChap** [gamefreedomgit/Frostmourne#1684]
https://www.wowhead.com/wotlk/quest=13481/lets-get-out-of-here

After accepting, you should escort Father Kaniaros down the path to safety.

I didn't try until the second phase of the area, and this quest is mutually exclusive with:
https://www.wowhead.com/wotlk/quest=13229/im-not-dead-yet which is pretty much the same, but I can't test of the first phase one works or is similarly broken.

**Comment by Piootrek** [comment]
Fixed
