### ISSUE TITLE
Kil'Jaden incorrect yell on spanish client

### ISSUE THREAD

**Issue by broizter** [gamefreedomgit/Frostmourne#1687]
(This was reported by someone else to me because it breaks DBM on Kil'Jaden)

When the adds before Kil'Jaden dies and the emerges he the yell he does is broken when using a spanish client.
![bild](https://github.com/user-attachments/assets/e7a0338d-ef0a-480e-885f-79f12cfdca05)

The correct yell should be "Los prescindibles han muerto. ¡Qué así sea! ¡Ahora triunfaré donde Sargeras no lo logró! ¡Desangraré este despreciable mundo y me aseguraré mi puesto como verdadero maestro de la Legión Ardiente! ¡El final ha llegado! ¡Dejad que se desvele el misterio de este mundo!"

**Comment by Riztazz** [comment]
Fixed, will close once it's live
