### ISSUE TITLE
AQ40 Twin Emperors

### ISSUE THREAD

**Issue by bandini9** [gamefreedomgit/Frostmourne#1688]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Twin emperors are not teleporting properly, only melee one teleports and they heal back to full HP

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Piootrek** [comment]
Fixed
