### ISSUE TITLE
Path of War, thrown weapon issue

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1689]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

 [Savage Gladiator's War Edge](https://www.wowhead.com/wotlk/item=42444/savage-gladiators-war-edge) seems to have issues on path of war. players cannot use [deadly throw](https://www.wowhead.com/wotlk/spell=48673/deadly-throw) or [throw](https://www.wowhead.com/wotlk/spell=2764/throw)

**How to reproduce:**

Create a path of war rogue and equip Savage Gladiator's War Edge.
Use the mentioned spells.

**Comment by Piootrek** [comment]
Fixed. Players will be required to delete a cache directory after the server update to make it work for them.
