### ISSUE TITLE
Kelthuzad's Phase 1 adds

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#169]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Once Phase 2 starts, they should despawn but here they currently do not

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Godmatik** [comment]
Not true, any adds currently aggroed onto something should not despawn when phase 2 starts.
That's a Warmane bug.
