### ISSUE TITLE
[Quest] Good Troll Hunting not offered

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1692]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Quest [Good Troll Hunting](https://www.wowhead.com/wotlk/quest=12208/good-troll-hunting) only requires min level 73 / Horde must be offered by NPC [Sergeant Thurkin](https://www.wowhead.com/wotlk/npc=27266/sergeant-thurkin).

Alliance version ([Troll Season!](https://www.wowhead.com/wotlk/quest=12210/troll-season)) is working fine.

**Comment by Afgann** [comment]
fixed
