### ISSUE TITLE
WinterGrasp (Low priority)

### ISSUE THREAD

**Issue by Amine-x-x** [gamefreedomgit/Frostmourne#1694]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
If you inside relic room as alliance while horde controlling the fortress then battle starts , you get teleported to horde fortresss spawn zone (the point that all horde teleports too once they start battle)
this can be use to AOE them and delay them from mounting which helps oposite team to gain some time.

**How to reproduce:**
Go inside the relic room and wait for battle to start (the 15 seconds count down even if not accepted)

**How it should work:**
Delaying the enemy team with AOE combat ,gives advantage to other team so he reach some zones before other team.

**Database links:**

**Comment by Afgann** [comment]
fixed
