### ISSUE TITLE
Seed of Corruption - chain exploding dont work

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Frostmourne#1695]
**Description:**
Explosion from Seed of Corruption should detonate nearby targets with Seed of Corruption.

**How to reproduce:**
Put seed on 2 targets.When one explode second one still last on mob.

**How it should work:**
Explosion from Seed should detonate nearby Seeds

**Comment by Scolix9** [comment]
Seed of Corruption explodes when you do a certain amount of damage on the mob that has it. You can see the tool of SoC in wowhead as well. If your SoC didnt do enough damage on the other mob that had it then ofc it wont proc it. You lack again evidence on how spell works and what is the problem of the spell currently.

**Comment by Manpower99** [comment]
this is really going on a wotlk bug tracker?
getting ruined day by day by bovine fecal matter.

**Comment by scrublama** [comment]
So before anything, keep this in mind.
Recognize that seed works different on the PTR and on Live for whatever reason atm.

Some differences being
**on live:**
1. Seed explosion has no dmg threshold, you can seed on a target and cast rank1 shadowbolt, or autoattack etc. and it will trigger.
https://gyazo.com/5a4a802ab8c29181dc3f8f66ac72f34d
2. Seed explosion on target X will not trigger a seed explosion on target Y. Like OP said
https://gyazo.com/42da155f4d2ffeebaddd20acdba2b939

Guess devs are working on it hence
**on PTR:**
1. Seed explosion has a threshold and will explode once its met, but it's just like on live not triggering from another seed explosion.

**Comment by Afgann** [comment]
fixed
