### ISSUE TITLE
[CORE] Arena Exit doesn't dispel enemy auras

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1697]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Leaving arena doesn't remove enemy auras, players can die if they won with very low hp left and dots on them.

**How to reproduce:**

**How it should work:** Enemy auras should be removed upon exiting arena - or invalidated. 

**Database links:**

**Comment by Afgann** [comment]
fixed
