### ISSUE TITLE
[CORE] Fear off Ledges 

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1698]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Today in Dalaran Arena i was feared off the ledge, causing me to fall down

**How to reproduce:**

**How it should work:** Fear effects' pathfinding should NOT let players get to a location where they can't walk back normally

**Database links:**

**Comment by Afgann** [comment]
fixed

**Comment by haephaistoss** [comment]
@Afgann 

Yesterday it happened again in Dalaran Arena, is the fix live?
