### ISSUE TITLE
[PoW] Dying on PoW Island

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1699]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** If a player dies on PoW island, their spirit spawns in the middle of Tanaris. The only way to get back in a reasonable amount of time is to res yourself from another account - or by somebody else.

**How to reproduce:**

**How it should work:** It's not technically a bug, since PoW did not exist (sadly) on og wrath, but I do advise putting a spirit guide there  - much like the ones on BG that periodically resurrects ppl dying there. And putting the spirit spwan point there as well - but only for people dying in the island's vicinity, I don't wanna mess up the game for non pow chars questing in Tanaris.

**Database links:**

**Comment by Afgann** [comment]
fixed
