### ISSUE TITLE
[PoW] Items Still Missing Stats

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1700]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** SG Wands are missing stats.

**How to reproduce:**

**How it should work:** https://www.wowhead.com/wotlk/items/weapons/wands/name:savage+gladiator's

Spell pen, and SP are missing completely, not just visually

**Database links:**

**Comment by Piootrek** [comment]
Fixed

**Comment by laimewow** [comment]
@Piootrek 
Just deleted Cache folder, updated whitemane patch - no changes
![image](https://github.com/user-attachments/assets/09afcb0e-6593-455f-9f3e-6302eff93dad)
![image](https://github.com/user-attachments/assets/55f1bdc7-e604-4fa9-916b-161e420b4118)

Also throwns is still 0 yd range

**Comment by haephaistoss** [comment]
still midding said stats for me too, and on char sheet as well, so it's not visual only.
