### ISSUE TITLE
[PALADIN] Hammer of Wrath shouldn't proc Seal(s)

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1702]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Hammer of Wrath now procs Seal of Righteousness dmg on hit.

**How to reproduce:**

**How it should work:** It shouldn't proc SoR dmg - or any seal, only Vengeance if crits, and / or anything else that happens on hit / crit.

**Database links:** https://www.wowhead.com/wotlk/spell=48806/hammer-of-wrath

EDIT: by Vengeance, I mean the talent 'Vengeance' that procs off crits, not seal of vengeance

**Comment by Afgann** [comment]
fixed

**Comment by haephaistoss** [comment]
@Afgann 

So funny:

https://github.com/ClassicWoWCommunity/cata-classic-bugs/issues/625

:D
