### ISSUE TITLE
[PoW] Crafted Items Not Available to PoW

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1703]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** on PoW Island crafted starter items are missing completely, and HC items too.
Also it's advised to have these 200 item lvl stuff available for honor only without rating, as normally you can get them from PvE or crafting, and they provide an essential stepping stone - especially at the end of the season where ppl are running with legendaries. Usually ppl get them before entering arena or BG anyway.

**How to reproduce:**

**How it should work:**

https://www.wowhead.com/wotlk/items/min-level:200/max-level:200?filter=3:86;1:11;0:0

- Titansteel Guardian is bis for 1h

https://www.wowhead.com/wotlk/item=37653/sword-of-justice -> bis for 2h ret in s5, until s6 weapons are obtainable (if ds and crus. strike were fixed, that is)

https://www.wowhead.com/wotlk/item=42989/darkmoon-card-berserker - not sure it's bis for anybody, but it's missing too

I'm sure other classes have some of their basic items from random places too

Please feel free to add more items that should be available.

**Database links:**

**Comment by RadeghostWM** [comment]
They can be added with the same price as low weapons (s5 weapons)

**Comment by Riztazz** [comment]
I need a more complete list of items that need to be added :/

**Comment by haephaistoss** [comment]
It's in the opening post:

https://www.wowhead.com/wotlk/items/min-level:200/max-level:200/quality:4?filter=3:86;1:11;0:0
https://www.wowhead.com/wotlk/item=37653/sword-of-justice
https://www.wowhead.com/wotlk/item=42989/darkmoon-card-berserker

**Comment by Riztazz** [comment]
Fixed, will close once it's live
