### ISSUE TITLE
POW Wartorn vendor refunds gold instead of points

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1704]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Players refunding within 2h of purchase without any enchant/gem, to wartorn vendor in pow is refunding gold instead of arena points.

Here are two screenshots submitted by player:
![image](https://github.com/user-attachments/assets/05418d98-3f98-4982-bbe6-5ace1b4c19fd)
![image](https://github.com/user-attachments/assets/2b610044-f6b0-4b9b-afb6-d2ffe07e28ee)

There are rare reports of other vendors as well, such as valor emblems but no proof/screenshot on it yet.

**How to reproduce:**

Refund an item from warton vendor in pow

**How it should work:**

should reward arena points if its returned within 2h of purchase without modifications.

**Comment by Afgann** [comment]
fixed
