### ISSUE TITLE
[PALADIN] Hammer of Wrath Getting Deflected

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1705]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** HoW is getting deflected by random ppl for some reason.

**How to reproduce:**

**How it should work:** HoW should be immune to parry and dodge - deflect is parrying a spell

**Database links:** https://www.wowhead.com/wotlk/spell=48806/hammer-of-wrath

**Comment by Afgann** [comment]
fixed
