### ISSUE TITLE
Improved hunter's mark

### ISSUE THREAD

**Issue by HosseinEkv** [gamefreedomgit/Frostmourne#1706]
I think the talent in marksmanship , improved hunter's mark is not currectly working i used my hunter once only with 3/3 improved hunter mark ( i didnt take any other talent tree ) then once without it . I shotted 100 hits( i didnt count the crits) the output was exactly the same 30% of 500ap is 150 ap it should be slightly notable .( i also removed any item and trinket that they proc on hits so i dont make something wrong . I submitted this in another private server also and it got fixed 
Another thing to note is with the talent shouldnt the tooltip also change idk about this but i thought its good to ask since you are a dev .
Thank you for ur services.

**Comment by Piootrek** [comment]
Hello. I've checked the code and it works correctly. Closing.

**Comment by HosseinEkv** [comment]
What about the tooltip of ability and debuff?
