### ISSUE TITLE
Shadowfang keep - Gate not opening

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1708]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

The door after [Fenrus the Devourer](https://www.wowhead.com/wotlk/npc=4274/fenrus-the-devourer) doesnt open after defeating the boss.
https://github.com/gamefreedomgit/Frostmourne/issues/963#issuecomment-2266688834

**Description:**

After defeating Fenrus, there should be a rp where players kill the voids and door opens. but the RP does not happen and door will never open.

**Comment by Piootrek** [comment]
I wasn't able to reproduce this issue, but I made some changes. Please let me know if the issue persists after the server update

**Comment by WhitemaneChronus** [comment]
@Piootrek (sry for the ping, but the issue is closed)
![image](https://github.com/user-attachments/assets/f9048113-4b3e-410b-91d2-ce8a862cd6da)
Today i received another case of this issue, you can see the boss is dead but the door is closed.

**Comment by Piootrek** [comment]
Pushed another possible fix, please let me know if it bug again after server update

**Comment by WhitemaneChronus** [comment]
@Piootrek i have another case here after the update.
![image](https://github.com/user-attachments/assets/77bc4b5c-07cd-41c7-b1b5-6483d88bfe80)
