### ISSUE TITLE
Racial Shift

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#171]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
In Middle of Naxxramas, relogged few times an everytime i did my racials were reset to my original race's racial abilities.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Manpower99** [comment]
> @Manpower99 What is your original race and what racial did you pick up?

Orc into Troll swap, tried other combinations and similar result

**Comment by Afgann** [comment]
fixed
