### ISSUE TITLE
[Quest] Rescue OOX-17/TN (648) NPC stops moving

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1710]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Homing Robot OOX-17/TN stops moving after last pack of the mobs (Wastewander nomads) 
This is only happening on live server, on PTR its working fine. 

**How to reproduce:**

Take the quest from Robot and do the escort on live server.

**How it should work:**

It should continue to move towards its path after engaging any of the mobs along the way.

**Database links:**

https://www.wowhead.com/wotlk/quest=648/

**Comment by Piootrek** [comment]
I wasn't able to reproduce this issue, but I made some changes. Please let me know if the issue persists after the server update
