### ISSUE TITLE
[POW] Insane strength potion missing from consumables

### ISSUE THREAD

**Issue by danniellos94** [gamefreedomgit/Frostmourne#1711]
**Description:**
Insane strength potion is missing from consumables, It's propably best potion for strength users on bg.

**How to reproduce:**
Check the 'Rixa Trinketblast' NPC.

**How it should work:**
If it's possible please add insane strength potion to the POW consumable vendor.

**Database links:**
https://www.wowhead.com/wotlk/item=22828/insane-strength-potion

**Comment by Afgann** [comment]
fixed
