### ISSUE TITLE
[Critical Core Mechanic] Boss Combat Pulse

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#1712]
**Description:**
Every boss in the game has a mechanic called Combat Pulse which adds everyone in the raid to the boss threatlist. 
Currently on this server this mechanic happens the instant the boss is pulled, however, **in both OG(3-4sec) and Classic this pulse happens 5seconds into the fight.** 

**How this happens:**
In stock trinitycore, every single boss script calls the function "DoZoneInCombat()" exactly on boss engage. There should be a pause 5 sec event before this happens. Naturally, modifying every boss script with this would be an inefficient undertaking so I suggest adding this pause inside the function itself.
To give further details, this function calls another funtion "EngageWithTarget()" defined in Unit.cpp - this function is the one who actually adds people to the threatlist/ defines combat state.

**How it should work:**
The person who pulls the boss should be the only one on the boss threat list for 5sec, unless a threat redirect mechanic is used by the person who pulls. In that case 2 people will be on the threat list for the first 5 seconds. After 5 seconds everyone in raid will be on the boss threatlist and thus in combat.
This is important for original mechanics such as hunter pull into feign death makes the boss despawn (unless tank received misdirection)

**Evidence links:**
1. https://www.youtube.com/watch?v=8oi1zz6wC5g
Wrath classic video.
As you can see in this video a ninjapull 1-2 seconds before the warrior actually notices and faces the boss. Around 3 seconds after the "Entering combat" pops even though he didn't do any action towards the boss - this is the 5second combat pulse, it does not happen the exact moment the boss is pulled.

2.https://youtu.be/PyBagNp-7Ig?si=uqyfaRox903UlF5J&t=17
OG wrath video, you can see ninja pull at second 18, rest of the party only gets combat at second 21. Wrath spells can be seen on the action bars.

UPDATE: Removed 2nd point I previously made in this post due to finding evidence against. The main topic this thread is still very relevant.

**Comment by bandini9** [comment]
No, this is just a thing in vanilla, which i remember pretty well abused back in time as rogue to save repair costs. I had a vanish+unequip all macro

It’s not a thing in wotlk

your evidences are from vanilla classic

**Comment by sputnikk** [comment]
My evidence being from vanilla classic is incorrect, you can clearly see wrath spells on the warrior's spellbar. These mechanics are same in wrath as well. I made the same report in warmane bugtracker and it was applied there if thats worth anything.

**Comment by NickZedd** [comment]
Very interesting. Haven't really looked into this myself, but I was told by classic players that you could not vanish to reset potions there. Do you have evidence that this was possible as well?

**Comment by NickZedd** [comment]
Oh and also, does this mean that some spells which should take you out of combat currently also fail to reset your threat on whitemane?

**Comment by Manpower99** [comment]
> No, this is just a thing in vanilla, which i remember pretty well abused back in time as rogue to save repair costs. I had a vanish+unequip all macro
> 
> It’s not a thing in wotlk
> 
> your evidences are from vanilla classic

I guess shattering throw was a vanilla spell lol.

**Comment by sputnikk** [comment]
> Oh and also, does this mean that some spells which should take you out of combat currently also fail to reset your threat on whitemane?

Yes there are specific cases in which this can happen.
Real case example - during a wipe in progress, 2/3 people still alive and the boss goes on rogue which survives with evasion.
Rogue casts vanish but the boss doesn't even target swap to one of the others and rogue keeps full threat.

Vanishing in a normal case scenario when you aren't the main target of the boss resets threat properly, but not your pot cd. Pretty sure it has to do with the combat script doing "pulse" too fast as other tricks such as macroing gear change with vanish works(as related to me by others - have not yet tested myself) if macro is spammed fast enough.

**Comment by sputnikk** [comment]
> Very interesting. Haven't really looked into this myself, but I was told by classic players that you could not vanish to reset potions there. Do you have evidence that this was possible as well?

This had me go into some digging and found evidence in both og and classic against what I thought about pot cd, as such I've removed that part from the post. Luckily I've found more evidence for the combat pulse mechanic, which is the main part of this post.
https://youtu.be/CntnzdUxxHk?si=z__40vO2dClEkUiN&t=113 - classic vid rogue vanishes pot does not go on cd.

 
https://youtu.be/pgckZnEeq7w?si=sNXqyvu8q_sdV_x2&t=807
https://youtu.be/H_HthHs27fA?si=CgpsI5OVS07K9zoH&t=177- og wrath vids vanish did not reset pot cd. This was pretty hard to find, seems back in the day people disliked potting on camera. Not entirely sure 2nd isn't pserv but scripting seems too good for 2009 for it to be

**Comment by Riztazz** [comment]
I've talked with @UltraNix about this issue and whether i should implement this part or not. The decision from the top is that if you guys can provide a video where the combat didn't kick right away on original wotlk then we will implement this.
Don't hate the messenger :( Closing

**Comment by sputnikk** [comment]
@Riztazz @UltraNix 
https://youtu.be/gqDPN3b3ymI?si=Vn-U9BffkK3_fMua&t=19
Another OG Wrath proof video, dk ninja pulls boss at 0:23, pov char gets it at 0:22 because he attacked, everyone else gets combat at 0:26. Solidifies once again that og wrath had combat pulse after 3 sec while classic has it at 5sec.

**Comment by Riztazz** [comment]
I'll implement this then :)

**Comment by Riztazz** [comment]
fixed for ulduar/naxx bosses, not all of them, some bosses that have event intros will pull raid instantly and i've confirmed that with a few videos

Will close once it's live
