### ISSUE TITLE
[PTR] Yogg 25m nm bugs

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#1713]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)
Tested with no keepers active.

Psychosis doesn't reduce sanity. 
It should remove 9 sanity with each hit. In the first screenshot you can see a lot of psychosis damage taken but not much sanity loss. All of the loss comes from malady and brain link.

![image](https://github.com/user-attachments/assets/d5966866-6361-495b-8e7a-5d29875bb26c)

Brain link debuff only applies to one of the targets. 
In the 2nd screenshot you can see both of my characters linked, with the debuff only appearing on one of the raid frames. Also, the debuff can be seen on the nameplate of my warlock, but doesn't appear under the paladin's debuffs at all.

![image](https://github.com/user-attachments/assets/19f6e0ae-b6fe-47ab-bbdc-b23dfc5ed9ee)

In this video at this timestamp you see that it did apply to both of the linked people in classic:

https://youtu.be/3H1AMQjbleQ?t=149

**Comment by Afgann** [comment]
fixed
