### ISSUE TITLE
[PTR] Mimiron assault bot damage

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#1714]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)
Assault bots do too little damage. On classic they did up to approx. 172k unmitigated, and the Frosthold (https://archive.is/6WwGI) damage is listed as 40-55k physical melee damage. I assume that this is after mitigations, since you can see it hitting for about 35k in the below video. It still doesn't quite add up though so perhaps they nerfed it early on, or perhaps it does up to 55k without attack power reduction being active.

Proof from classic:
The unmitigated damage is after attack power reduction from vindication, but I'm not sure how much that reduces it.

Assault bot hits on tank:
![image](https://github.com/user-attachments/assets/6a9590ff-d6e8-4b54-a9fe-e27fb3526f17)
https://classic.warcraftlogs.com/reports/q47FkMW8rYn2vBgj#fight=17&type=damage-taken&source=3&ability=1&view=events

Application of vindication
https://classic.warcraftlogs.com/reports/q47FkMW8rYn2vBgj#fight=17&type=auras&source=3&view=events&spells=debuffs&by=target&ability=26017
![image](https://github.com/user-attachments/assets/b1aa832d-bfb8-4b04-8620-e128c2178618)
突击机器人 is the assault bot.

Frosthold video with timestamp:
The tank takes a hit without much damage reduction. It gets healed quickly so go at 0.25 speed. Note that later in the video he uses Divine protection so the damage is much reduced.
Keep in mind that he may have had a disc shield, holy shield, sacred shield, inspiration etc but it can't be known which if any were active.

https://youtu.be/hyIdyRSpibo?t=256

**Comment by NickZedd** [comment]
Addition: I forgot to mention the damage they do on Whitemane currently. I tested it solo using commands a while ago and it is approximately 20k on a tank, and 50k without any mitigation. The exact numbers I don't find very important since it is so far off.

**Comment by Manpower99** [comment]
[Hotfix](https://web.archive.org/web/20090604123140/http://blue.mmo-champion.com//23//16474158165-recent-ingame-fixes--41609.html) (2009-04-28): The Assault Bots on the Mimiron encounter will now attack faster, in turn they will do less damage per hit.
I would assume this is the difference between Classic's Pre nerf and the post nerf version @Afgann

**Comment by Afgann** [comment]
fixed
