### ISSUE TITLE
Path of Frost/Levitate/etc and Swimming

### ISSUE THREAD

**Issue by LezChap** [gamefreedomgit/Frostmourne#1715]
When under the effect of one of these spells (and probably other similar spells, these are the only two I've tested on) and jumping above the water's surface (when swimming), you should, at the end of the jump, stop swimming and be "standing" on the water's surface.  However, something here is broken and it sometimes takes several jumps or moving and jumping before the server recognizes you as "standing" and stops you from swimming (and allows you to do actions that swimming prevents, like mounting).

**Comment by Riztazz** [comment]
No answer, closing
