### ISSUE TITLE
Missile Barrage proc should be consumed at the beginning of Arcane Missiles cast.

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#1716]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Missile Barrage talent gives you a chance to reduce your next Arcane Missiles cast by 2.5 and cost no mana etc. 

**How to reproduce:**
Cast Arcane Blast until you get Missile Barrage proc, then use Arcane Missiles.

**How it should work:**
The proc should be consumed at the moment of casting Arcane Missiles, not at the end of channeling.

Because of this bug, it conflicts with T8 4 set bonus. I tested on PTR with the T8 4 set bonus where you have a chance for this proc to not be consumed for the spell which benefits (you can do 2 Arcane Missiles in a row benefiting the proc). The T8 4 set bonus works correctly on fire spec, just on arcane spec it doesn't work because of this bug (not consuming the proc on beginning of Arcane Missiles)

**Database links:**
Check any video related to Arcane mage
https://youtu.be/Co2UEsJLHoM?si=EQmqkSP6SA7ZZy5l&t=170

**Comment by Riztazz** [comment]
https://youtu.be/jD4Ds6f_6wo?t=273

Saving in case of complaints:P this confirms the bug

**Comment by oneadanut** [comment]
Also, arcane blast debuff doesn't reset at the moment of casting arcane missiles, but I hope the fix doesnt interfere with the damage of it. I think it's a general bug regarding channeling spells, not consuming the buff on the cast, but in the end of it

**Comment by Riztazz** [comment]
Another issue for arcane blast please :P fixed the missile barrage as it is individual case, will close once it's live

**Comment by Riztazz** [comment]
Ok, i'll take a look

**Comment by oneadanut** [comment]
> Another issue for arcane blast please :P fixed the missile barrage as it is individual case, will close once it's live

I created a new issue for Arcane Blast which has 2 bugs: https://github.com/gamefreedomgit/Frostmourne/issues/1776

**Comment by Riztazz** [comment]
Fixed will close once it's live
