### ISSUE TITLE
[PTR] Firefighter fire cap too low

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#1717]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

The fire cap on Firefighter is lower than it's supposed to be at the moment, and could potentially enable killing the boss without dealing with the flames correctly. Also, fires can spawn even though the fire cap has been reached.

I went on the PTR and spread fires, trying to avoid stacking them. A few fires are stacked in the middle but that is the case in the tank spot video as well, since at times they all run together and kite fires in the same direction, making them stack on each other.

As you can see, the cap is very low and new fires spawn even after the old ones stop growing.

https://www.youtube.com/watch?v=syPKFNPhl94

To prove it's not an issue that arises from testing solo, here is a screenshot from our 25m PTR run where the fire cap was reached in p4. Most likely the flames were a little less stacked here since they were following different people instead of just following me. (the whole video is too long to upload at the moment)
![image](https://github.com/user-attachments/assets/7f7af8cb-5eb4-478a-b194-ca84dfdc3858)

**How it should work**
The fire cap should be approx. 2 times greater, and fires should not be able to spawn at all once the cap has been reached.

In this screenshot from a Tankspot video (which was used as evidence in a previous report on the flame cap) you can get an idea of roughly how many flames should be able to exist at one time. Keep in mind that they have some stacked flames.
https://youtu.be/Jee971qfSMQ?t=307
![image](https://github.com/user-attachments/assets/4df7b940-a38a-44ea-a77e-4a46082d076c)

**Comment by sputnikk** [comment]
Even when the flame cap is reached, the periodic spell casted by mimiron still spawns the initial 2 new flames, thats how flames are still added even if it should be capped. the only difference is that the flames that already exist stop spreading.

**Comment by NickZedd** [comment]
I'm aware that that is why it's happening, but they didn't spawn like that on classic or retail once the fire cap was reached. Also, iirc it was working the same way on Whitemane 1-2 weeks ago when I first tested.

**Comment by Afgann** [comment]
fixed
