### ISSUE TITLE
4 Horsemen Stacks affecting pets

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#172]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Currently every pet and summonable guardian/minion are being affected by the debuffs, uncertain if its affecting the custom mechanic of 100 = enrage though.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Godmatik** [comment]
The more than 100 marks = enrage I think is a custom buff btw and not blizzlike. But yes, pets being affected by this was always an old bug on previous iterations of this core.

**Comment by Manpower99** [comment]
I already mentioned it is custom mechanic, not reporting it as a bug.
the bug report is purely on pets getting stacks, just because yesterday we had to dismiss all pets which lowered the raid's damage to even pass the encounter as bosses were enraging on pets and even summonable temporary ones such as treants goyles spirit wolves and armies. however we were uncertain if the enrage was counting the pets or not but it seemed like it was.

**Comment by Afgann** [comment]
fixed
