### ISSUE TITLE
Carbonite addon, new patch

### ISSUE THREAD

**Issue by Mynameistakenalready** [gamefreedomgit/Frostmourne#1720]
Carbonite addon doesn't load maps which normally load after getting online.
The icon on minimap is visible and interactive but maps doesn't show at all. Have to turn addon off to be able to open regular maximized map.

**Comment by sstndr** [comment]
Date: 2024-08-31 13:59:50
ID: 38
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite\Carbonite.lua line 24655:
   table index is nil
Debug:
   [C]: ?
   Carbonite\Carbonite.lua:24655: InT1()
   Carbonite\Carbonite.lua:21284: Ini()
   Carbonite\Carbonite.lua:25949: h()
   Carbonite\Carbonite.lua:20948: NXOnEvent()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
AddOns:
  AckisRecipeList, vv2.0
  Carbonite, v3.34
  Swatter, v5.0.0
  TipTac, v10.05.01


To whoever it may concer, that's swatter log regarding carbonite bugs.

**Comment by UltraNix** [comment]
Already fixed.

**Comment by Mynameistakenalready** [comment]
How about maps still doesn't show?
