### ISSUE TITLE
Invisibility potion cooldown issue

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#1723]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Currently using invisibility potion will put every other potion on 10minute cooldown

**How to reproduce:**
Use invis potion and watch other potions like potion of speed - will have 10min cooldown

**How it should work:**
Other potions should go on their normal cooldown which is 1minute. Only the invisibility potion itself should have the 10min cd.

**Database links:**

**Comment by Godmatik** [comment]
![invisz](https://github.com/user-attachments/assets/2ed65dd6-1750-41d3-a995-d48a5d689149)

Working as intended
