### ISSUE TITLE
[PATCH] [UI ISSUE] Font not working

### ISSUE THREAD

**Issue by Shadowmeth** [gamefreedomgit/Frostmourne#1724]
Everything was working fine until I got the new patch. It messed up my font for everything. I am using elvui if it helps and I can change elvui fonts but the default one I use is straight up not showing in the list of elvui fonts. I tried using a backup I had of WTF folder and it still didn't get fixed. Also tried going back to older version of patch but it didn't work. The font I use is "ArchivoNarrow-Bold" if it helps.

**Comment by UltraNix** [comment]
Already fixed.
