### ISSUE TITLE
Pre-mimiron bombs combat bug

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#1725]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Doing anything to Boomer XP-500 bomb npcs right before mimiron puts player and then party in perma combat. (using hunter trap or interracting with them in any way) This lasts until you kill the bomb/s

**How to reproduce:**
Get close to bombs or use cc on them like hunter trap.

**How it should work:**
They should continue their patrol or remove combat. Their only interraction with players should be explosion upon close contant with player.

**Database links:**

**Comment by Afgann** [comment]
fixed
