### ISSUE TITLE
Kologarn throws people he grabs under the map

### ISSUE THREAD

**Issue by Tetrahydrx** [gamefreedomgit/Frostmourne#1726]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Kologarn is throwing people under the map at the end of his grabbing ability. In my specific case the right arm was dying while I was being held by it.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/1721
