### ISSUE TITLE
Pet's Sated on boss kill

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#173]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
it was marked as fixed but today it was not in naxxramas.
after every kill, the pets kept the sated debuff

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
