### ISSUE TITLE
[PTR] You can hit your own root on Freya

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#1730]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
You can hit a strengthened iron root that is attached to you on Freya if you face anywhere within 90° of north. This seems to be true regardless which direction you were moving when it was applied, or if you were jumping or standing still.

I recorded a video where you can see me spamming my abilities while facing south, and as I turn north they finally go off. At the end you can see that judgement and hand of reckoning, which do not require you to be facing the target, can hit regardless.

https://www.youtube.com/watch?v=FzcPAgxDPPk

**How it should work:**
I have been told by guildies that you were not able to hit your own root on classic, but quite frankly it can be difficult to find evidence for something like this in a video. Internet searches didn't turn anything up on forums or comments. If someone has some concrete proof of that it would be helpful.

Regardless, it seems the intention on whitemane at the moment is that you should not be able to hit your root since it only works from one direction?

**Comment by Manpower99** [comment]
From what i know you can both melee it and cast on your own roots on classic
https://youtu.be/YNmf6pxUMy4?si=bku0B_4FJiWs0iF_&t=296 timestamped with visual effect of starfire hitting the same root the same boomie is stuck in.
So the bug is that you can only hit while in specific direction.

**Comment by Afgann** [comment]
fixed
