### ISSUE TITLE
La profesion secundaria se crashea

### ISSUE THREAD

**Issue by raknarsson13** [gamefreedomgit/Frostmourne#1731]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Con esta nueva actualizacion cada vez que quiero intentar abrir la profesion secundaria se me crashea el juego y se me cierra
y pasa con todos mis pjs cada vez que se abre la profesion secundaria se me cierra el juego
**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
#1732
