### ISSUE TITLE
Game crashing when pressing the Enchanting button.

### ISSUE THREAD

**Issue by AMilicIT1221** [gamefreedomgit/Frostmourne#1732]
The game keeps crashing every time i try to press the icon to open up my Enchanting profession menu. It started happening after the new update.

**Comment by s71n63r** [comment]
![crash1](https://github.com/user-attachments/assets/88af6fcf-9903-4be1-85c5-58392757c8a8)

**Comment by scrublama** [comment]
Did u try delete cache and or remove read-only from file properties?

**Comment by s71n63r** [comment]
> Did u try delete cache and or remove read-only from file properties?

Deleting cache folder and setting RW on WoW folder does not fix issue.

**Comment by scrublama** [comment]
did you get the new patch?

**Comment by s71n63r** [comment]
> did you get the new patch?

3.3 patch fixes issue

**Comment by UltraNix** [comment]
Already fixed.

**Comment by GM-Aule** [comment]
We are still getting reports on crashes when trying to open professions. It seems something is still amiss.
