### ISSUE TITLE
Yogg Saron Death Rays Radius -MPG

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1733]
Live Testing today on 25n.
It seems my previous bug report was misinterpreted https://github.com/gamefreedomgit/Frostmourne/issues/1670
what i meant was that the death rays were often hitting people who were next to it and not under it. 
Now their radius is far too big and it goes through Yogg-Saron Himself. previously the movement pattern was fine so just revert it to how it was.

**Comment by Afgann** [comment]
fixed
