### ISSUE TITLE
[Patch V3] Emoji

### ISSUE THREAD

**Issue by Shineslippers** [gamefreedomgit/Frostmourne#1735]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Add option to client to disable emoji

**Comment by Manpower99** [comment]
please do as it is actually causing client crashes and somhow crippling FPS for some people.

**Comment by RadeghostWM** [comment]
You can do it. write /emoji

**Comment by Shineslippers** [comment]
No, no! It doesn't work! After relog it switching to enable again.

**Comment by Manpower99** [comment]
Yeah you have to do /emoji every time you login atm, any chance it gets added to the whitemane assistant addon so its automated?
