### ISSUE TITLE
Gear Score addon fail

### ISSUE THREAD

**Issue by Narma93** [gamefreedomgit/Frostmourne#1736]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The gs addons are not working properly. We can see other players gs but on the char info we cannot. I have tried multiple version non worked. 

**How to reproduce:**

**How it should work:**

We should see in the Char info under gear score slot.4
**Database links:**
http://www.kepfeltoltes.eu/view.php?filename=770gs.png

**Comment by scrublama** [comment]
Are you using Elvui? try updating it

**Comment by Narma93** [comment]
Yes, im using it. How can I update it?

scrublama ***@***.***> (időpont: 2024. aug. 31., Szo, 16:19)
ezt írta:

**Comment by scrublama** [comment]
nvm looks more like its this backported interface bugging with elvui and character info panel and spellbook. Happens with latest elvui aswell

**Comment by scrublama** [comment]
nvm just dont use the hd client
