### ISSUE TITLE
[PROFESSIONS] [DUPLICATE issue:1732] Client crash when attempting to load profession window

### ISSUE THREAD

**Issue by s71n63r** [gamefreedomgit/Frostmourne#1737]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Client crashes when clicking Engineering skill launch icon. Crash occurs when launching from action bar or from spellbook window.
![crash1](https://github.com/user-attachments/assets/eaf7be9e-a515-48fd-a9b9-807649ac0b4b)

**How to reproduce:**
Engineering skill level is 385, training is maxed up to 385. Click engineering skill from spellbook or launch from action bar. Client crashes. Crash occurs on all my characters. Not isolated to Engineering.

**How it should work:**
Profession window should open. Client should not crash.

**Database links:**

**Comment by UltraNix** [comment]
#1732
