### ISSUE TITLE
CD reset doesn't always work

### ISSUE THREAD

**Issue by Robosterone** [gamefreedomgit/Frostmourne#174]
**Description:**
After some bosses, the CD reset is not working. For example The Four Horsemen. Adding clip, you can see Inferno CD on the bars and Sated debuff not reseting after the kill.
https://clips.twitch.tv/ComfortableLaconicCheesecakeSSSsss-QpU0jC7-_SVReeyH

**Comment by Afgann** [comment]
fixed
