### ISSUE TITLE
[MPG] Kologarn Focused Eyebeam target

### ISSUE THREAD

**Issue by Xetherion** [gamefreedomgit/Frostmourne#1740]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Kologarn's Focused Eyebeam always target the ranged dps with the most aggro.

**How to reproduce:**

**How it should work:**
Target a random ranged player, if there is enough in range (5 in 25man and 3 in 10man i believe).
If there is less than required players in range, target a random player even in melee.

**Database links:**
https://www.warcrafttavern.com/wotlk/guides/kologarn-strategy-guide-ulduar-25/
Occasionally Kologarn will cast [Focused Eyebeam](https://wowclassicdb.com/wotlk/spell/63976) at a random player

**Comment by Godmatik** [comment]
To add to this, it should prefer a ranged player. But yes, random selection

**Comment by Afgann** [comment]
fixed
