### ISSUE TITLE
Redridge Mountains, inaccessible mining node

### ISSUE THREAD

**Issue by DrSLDR** [gamefreedomgit/Frostmourne#1741]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
There's a mining node hidden inside a cliff face in Redridge Mountains, at (49, 27), right at the border to (50, 27). Shows up on Find Minerals, but is not accessible.

**How to reproduce:**
N/A. Go to Redridge Mountains, behold the absence of accessible mining node at this location.

**How it should work:**
Mining node should be accessible from the overworld.

**Database links:**
N/A

**Comment by Riztazz** [comment]
At the specified coordinates, the node is on the little hill above your head.
