### ISSUE TITLE
Taunt in arena

### ISSUE THREAD

**Issue by danniellos94** [gamefreedomgit/Frostmourne#1745]
**Description:**
Taunt in arena should makes the enemy pet target you until the owner will not command again to attack other target.

**How to reproduce:**
Use taunt in arena on the pet.

**How it should work:**
https://youtu.be/gJA7xHoQh0M?t=146 

Dk sended ghoul on priest, dk taunted it and it went on him, dk used petattack to attack priest again.

**Database links:**
https://www.wowhead.com/wotlk/spell=56222/dark-command

**Comment by Manpower99** [comment]
was fixed after this report https://github.com/gamefreedomgit/Frostmourne/issues/692
tested it at the time and it worked fine, perhaps it got bugged recently again

**Comment by danniellos94** [comment]
Tested on duel today and was working weirdly didn't work for me yesterday in arena, for now closing.
