### ISSUE TITLE
[Dungeon] Azjol-Nerub: Hadronox dying to mobs / not dropping loot 

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1747]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

After killing the crushers, Hadronox starts walking up but it takes a significant amount of damage from mobs and almost dies.
Therefore it will not drop any loot for players, not items not emblems and it doesnt count towards the achievement as well.
@Riztazz (as you requested)

**How to reproduce:**

Kill crushers, start the fight and dont damage the boss, it dies fairly fast to other npcs.

**How it should work:**

shouldnt lose that much hp while walking up the platform.

**Comment by Riztazz** [comment]
Fixed, will close once it's live. if possible, please test on PTR if everything is A-okay once it's updated :D

**Comment by WhitemaneChronus** [comment]
![image](https://github.com/user-attachments/assets/929f18d0-472a-47ef-b2e4-c9086f4ff96d)
This is how it looks on PTR now. I pulled on crusher away and killed it so i dont get aggro on others.
You can see two crushers are still up and the boss is already half health.

**Comment by Riztazz** [comment]
I am not sure if PTR is updated :)

**Comment by itsemmastone** [comment]
The PTR has been updated with the latest core fixes. You can check it out now, and we appreciate any help you can provide.

**Comment by WhitemaneChronus** [comment]
Seems fine now; I delayed crushers as much as possible, and regens its hp back (didnt go below 95%) while not being aggro'd by player.
Thanks a lot

**Comment by Riztazz** [comment]
Alright, i'll close once it's live on prod :)
