### ISSUE TITLE
[Hunter PVP] - Snake Trap (snakes griefing)

### ISSUE THREAD

**Issue by Ingeniouskid** [gamefreedomgit/Frostmourne#1748]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Snake Trap not working properly: snakes are hitting random targets after the trap is triggered, instead of attacking the target who actually triggered the trap.

**How to reproduce:**
Use snake trap with multiple enemies in medium range (up to 20-30 ingame yards, seen sometimes even more ridiculous aggro ranges in arena). Then one of the enemy targets steps into snake trap, triggering it. Snakes choose random target instead of the one that triggered the trap. See the picture below, where one sees that Paladin triggered the trap but snakes are attacking the dummy for some reason. 

This is very sensitive in PVP since snake trap randomly poisons (sometimes both) targets with dots that break CC (Scatter Shot etc.)

![image](https://github.com/user-attachments/assets/eab088de-1cfa-4e8f-86f5-3524f2a2d772)

**How it should work:**
Please read spell description.

Option 1 (as per stated spell mechanics): Snakes should attack the target that triggered the trap, no one else. Option 2 (other servers): On Warmane they are semi-controllable with the help of pet control buttons - meaning they attack the target which hunters pet is attacking (and can switch targets accordingly). 

Either of these two fixing option would be a great improvement vs status quo.

**Database links:**
https://www.wowhead.com/wotlk/spell=43449/snake-trap

**Comment by Piootrek** [comment]
Fixed
