### ISSUE TITLE
Maexna Wraps Nameplates

### ISSUE THREAD

**Issue by Robosterone** [gamefreedomgit/Frostmourne#175]
**Description:**
In most of the cases we are getting 2 wraps on top of each other and nameplates are also stacked this way which I think is not good and it shouldn't work like that, since you cannot see HP of both wraps consistently. Clip: https://clips.twitch.tv/PlacidYummyPorpoisePupper-dSdCC50rfQzb8EQo

**How it should work:**
It shouldn't be so stacked or do something with nameplates please.

**Database links:**

**Comment by wotlkenjoyer** [comment]
![photo_2024-02-18_19-02-36](https://github.com/gamefreedomgit/Frostmourne/assets/158612010/51c2052c-2732-49bf-8c04-1defc71681e9)

When you saying they stacked, they actually overlapped, and if you choose  **stacking nameplates** option they will be like here

![image](https://github.com/gamefreedomgit/Frostmourne/assets/158612010/f2ef9b3d-8846-449c-9fcf-1ce2be1abfd1)

**Comment by Afgann** [comment]
fixed
