### ISSUE TITLE
Venture Co. Machine Smiths bugged pets

### ISSUE THREAD

**Issue by HieronymusGooch** [gamefreedomgit/Frostmourne#1759]
**Description:**
The Compact Harvest Reaper NPC has a level range from 19-41. According to wowhead they can be found in STV, Stonetalon, and the barrens. In Stonetalon Mountains these NPCs are summond by "Venture Co. Machine Smiths" in northern windshear crag. The machine smiths I encountered were level 21, and according to videos I've seen of the quest being completed on retail WoW, they should be summoning harvest reapers that are the same level as themselves. But instead they are summoning the level 41 variant, which I believe probably belongs only in Stranglethorn Vale, as this is way above anything in Stonetalon mountains.

**How to reproduce:**
All you have to do is get aggro from a Venture Co. Machine Smith and wait for them to summon the harvest reaper. When that happens, you'll see this low level mob summon something almost 20 levels above its own.

**How it should work:**
Venture Co. Machine Smiths should summon Compact Harvest Reapers that are their own level, instead of ones much higher than them.

**Database links:**
https://www.wowhead.com/classic/npc=2676/compact-harvest-reaper#comments

**Comment by HieronymusGooch** [comment]
I lost my HC druid because of this >:(

**Comment by Piootrek** [comment]
Fixed
