### ISSUE TITLE
[Suggestion] Quest objects

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#176]
Quest objects you collect typically are on a ~5 minute cooldown until they respawn, which can cause bottlenecks in many high traffic quest areas.

Consider reducing them to 1 minute

**Comment by qqdbpp** [comment]
or even just reduce  it to 5 or 10 seconds, especially for quests where you only collect 1 of an object (dar'khan questline in ghostlands comes to mind, respawn on orbs is more than a minute for a quest in a very packed zone)

**Comment by Afgann** [comment]
fixed
