### ISSUE TITLE
Game crash when trying to open Enchanting

### ISSUE THREAD

**Issue by Nightowlamerz** [gamefreedomgit/Frostmourne#1760]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**When I try to open Enchanting profession the game crashes, but when I Disenchant no issues. I am not using any professions add on at all.

**How to reproduce:**Try opening enchanting with new updated client.

**How it should work:**Enchanting should open
![Whitemane2](https://github.com/user-attachments/assets/f2c0af40-3142-467d-8285-38c3d3c79cd1)

**Database links:**

**Comment by UltraNix** [comment]
Update your client with the newest patch.
