### ISSUE TITLE
no funciona elegir racial

### ISSUE THREAD

**Issue by belilla** [gamefreedomgit/Frostmourne#1762]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
cuando creo un pj elijo una racial distinta a la suya pero cuando desconecto y vuelvo a conectar el pj aparece con la racial de su raza. Si vas al npc para cambiarla puedes volver a elegirla pero en cuando desconectas se le quita 

**How to reproduce:** creas pj y desconectas y desaparece la racial elegida

**How it should work:**cuando eliges la racial para tu pj se mantiene para siempre

**Database links:**

**Comment by Piootrek** [comment]
Fixed
