### ISSUE TITLE
Class damage buffs incorrectly stacking with eachother

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#1764]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Tricks of the trade on this server is currently stacking with other damage buffs that it shouldn't: Hysteria, Enrage, Wrecking Crew, Death Wish, Arcane Power.

**Its not just about tricks as well**, many other combinations of these buffs like Hysteria+Avenging wrath stack when they shouldn't. **Basically all the buffs mentioned in "how it should work" below should be in a no stack category.**

If you have more than one of these buffs on the list present on your character, it should only count the highest amount of % damage out of all of them.

**How to reproduce:**
Give hysteria to someone(or any one of the buffs above) then give tricks of the trade and the damage buffs will stack checking character tab % damage

**How it should work:**
Patch 3.1 : "Tricks of the Trade, Hysteria, Enrage, Wrecking Crew, Death Wish, Arcane Power, Owlkin Frenzy, The Beast Within, Avenging Wrath damage bonuses no longer stack together."

**Database links:**
https://wowpedia.fandom.com/wiki/Patch_3.1.0
https://wowwiki-archive.fandom.com/wiki/Tricks_of_the_Trade

**Comment by Manpower99** [comment]
Easily noticable how on some logs timelines you can see people abusing this to inflate their damage, tested it on PTR and it is indeed stackable

**Comment by danniellos94** [comment]
It was never fixed for blood dk hysteria and tricks, even in classic.
https://prnt.sc/8vw1RyMnOWd-

here for DRW autoattacks
https://www.youtube.com/watch?v=NYEsLAqC-20
https://www.youtube.com/watch?v=wNgnm1YnALs
old video you can see watching this video slowly he got tricks this crit would be impossible to do without tricks and hysteria stacking https://www.youtube.com/watch?v=v7b4uUxkhhA&t=33s

**Comment by Manpower99** [comment]
Oh so we gonna abuse more classic bugs? might aswell introduce bugged black magic also.

**Comment by danniellos94** [comment]
> Oh so we gonna abuse more classic bugs? might aswell introduce bugged black magic also.

Not saying that just wanted to point out it wasn't fixed for that specific interaction, I believe rest of them was fixed, I have nothing against it being fixed to be honest.

**Comment by Manpower99** [comment]
https://github.com/ClassicWoWCommunity/cata-classic-bugs/issues/302
labeled as a bug indeed

**Comment by UltraNix** [comment]
Fixed.
