### ISSUE TITLE
[Xmog] Main hand swords

### ISSUE THREAD

**Issue by MarcioMatteucci** [gamefreedomgit/Frostmourne#1765]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I don't know if it happens with every sword, but I have 2 main hand swords and neither one appears to transmog in my main hand slot.
It was supposedly fixed but I don't know if it applied to swords.
https://github.com/gamefreedomgit/Frostmourne/issues/1624#issuecomment-2298988216

![imagen](https://github.com/user-attachments/assets/72cb1e37-88f1-43b0-b968-595b77dda7e1)
![imagen](https://github.com/user-attachments/assets/eda33f7e-039e-4ac2-befd-f908c277121a)

**Comment by Piootrek** [comment]
Fixed
