### ISSUE TITLE
Mailbox doesn't sort mail

### ISSUE THREAD

**Issue by NNassib336** [gamefreedomgit/Frostmourne#177]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Items in the mailbox aren't sorted from newest to oldest - the order appears to be random
![image](https://github.com/gamefreedomgit/Frostmourne/assets/95701954/f4b48bd9-ff9f-4a2c-a6be-19a348826289)

**How to reproduce:**
Receive mail from others

**How it should work:**
Mail should be sorted from newest to oldest

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
