### ISSUE TITLE
Gift of Arthas not increasing damage by correct amount

### ISSUE THREAD

**Issue by Karsenity** [gamefreedomgit/Frostmourne#1770]
The damage increase from gift of arthas is seemingly scaling rather than being a static 8 damage increase. 

Easiest way to verify I found was using the death knight ghoul pet, as it does the exact same damage with each attack. The auto's and claw only increased by 5 damage, while frost fever increased by 1, and fiery plate gauntlets increased from 4 to 7.

**Comment by Piootrek** [comment]
Damage is correctly increased by 8 and it's still reduced further by armor. I don't see a reason why it shouldn't as it's still physical damage.

**Comment by Karsenity** [comment]
> Damage is correctly increased by 8 and it's still reduced further by armor. I don't see a reason why it shouldn't as it's still physical damage.

2 of the damage sources listed are spell damage, not physical damage. Same also applies with death and decay, as the increase is only 5 damage each tick.
