### ISSUE TITLE
Ouro (AQ40) Boss bugs out once his HP drops under 20%

### ISSUE THREAD

**Issue by everynameistakenomg** [gamefreedomgit/Frostmourne#1771]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Ouro (AQ40) Boss submerges under 20% and takes a multiple minutes to emerge again. When he emerges he does so at a random place in the room and stays emerged for less than 1 second before submerging again.  

**How to reproduce:**
Engage a fight with Ouro and get his HP under 20%. 

**How it should work:**
He should emerge on/near the position of a  player and stay above the ground so he can be killed. 

**Database links:**

**Comment by Piootrek** [comment]
Fixed

**Comment by everynameistakenomg** [comment]
thanks for the fast fix
