### ISSUE TITLE
[Paladin] Beacon of light transfering partial heals.

### ISSUE THREAD

**Issue by sstndr** [gamefreedomgit/Frostmourne#1772]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)
https://www.wowhead.com/wotlk/spell=53563/beacon-of-light
https://imgur.com/a/O59ve9O
**Description:**
Beacon healing is not properly transfered. 50% of the base heal of Holy Light (not counting crit) gets copied, and 25% of the base heal of Flash of Light (again, without considering crit) is being copied to the beacon'ed target. Holy Shock wasn't tested, I might have forgotten.

**How to reproduce:**
1. Have a paladin with the 51 point talent Beacon of Light.
2. Have two targets at low enough health to prevent overhealing
3. Apply Beacon to either target
4. Heal the second target.

**How it should work:**
Healing should be transfered 1:1 to the second target.

**Database links:**

https://www.wowhead.com/wotlk/spell=53563/beacon-of-ligh

**Comment by Piootrek** [comment]
Hey. I don't know why you encountered such an issue, I just double-checked and it works correctly for me. Can you reach me on Discord?

**Comment by peninagedola** [comment]
still bugged

**Comment by Piootrek** [comment]
Server wasn't updated with the fix, will be updated tonight.
