### ISSUE TITLE
 Issue with Naxxramas 10-Man Raid ID

### ISSUE THREAD

**Issue by alexis540** [gamefreedomgit/Frostmourne#1773]
[[//] # (screenshot <)
[//]: # (https://imgur.com/mH36vL4)
[https://imgur.com/mH36vL4](url)

Dear [Support Team/Game Master]

**I hope this message finds you well. I am writing to report an issue that occurred during a recent raid in Naxxramas 10-man (Ascended).

nickname: Malboro
instance id: 25
Problem Description: I joined a Naxxramas 10-man (Ascended) raid group, intending to do a full run of the instance. However, the group I was in decided to only focus on two bosses: Kel'Thuzad and Sapphiron. Since I was specifically looking for a full clear, I chose to leave the group before engaging any bosses.

Unfortunately, upon leaving the group, I was locked into the raid ID despite not having participated in any boss kills or engaging in combat with any mobs. This situation has left me with a saved raid ID in Naxxramas 10-man (Ascended), but I have not received any loot or achieved any progress within the instance.

Request for Assistance: I kindly request your help in resolving this issue. Specifically, I would appreciate it if the raid ID could be reset or removed so that I can participate in a full Naxxramas 10-man run with another group. This situation has been frustrating as it prevents me from completing the content I was aiming for this week.:**

Best regards,

**Comment by 0IHI0** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by UltraNix** [comment]
When joining that raid, you did not receive any prompt on your screen with raid ID confirmation?

**Comment by Riztazz** [comment]
He did, but the encounter mask is always 0 for ascended mode thus it might be misleading

**Comment by Riztazz** [comment]
Fixed, will close once it's live
