### ISSUE TITLE
furious items@horde vendor

### ISSUE THREAD

**Issue by peninagedola** [gamefreedomgit/Frostmourne#1774]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
(horde side, dont know about alliance) medallion of the horde, 2x furious rings, and 1 furious neckless still require arena rating@horde vendor "doris volanthius" 

**How to reproduce:**

**How it should work:**
should be available without any rating required

**Database links:**

**Comment by Riztazz** [comment]
This is not a bug, furious gear required arena rating in WOTLK sadly
