### ISSUE TITLE
[MPG] Yogg - Sara's target

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#1775]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Currently in Phase 1 Yogg, Sara does not show any target when casting her spells - Sara's fervor and Sara's blessing. Same in Phase 2 for Psychosis and Malady of the Mind. 

This is important for people to pre-emptively know if they will be affected by her spells soon, also DBM uses this target to pre-emptively warn people.

**How to reproduce:**
Target Sara when she's casting spells, see no target.

**How it should work:**
The player targeted by sara's spells should appear as Target of Target when having sara on target or focus.

**Database links:**

**Comment by Afgann** [comment]
fixed
