### ISSUE TITLE
Arcane Blast buff damage vs Arcane Missiles

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#1776]
**Description:**

Arcane Blast buff increases damage for all Arcane spells and increases mana cost of Arcane Blast with each stack.
There are 2 bugs:

1. Arcane Blast buff should reset after casting any Arcane spell, but doing Arcane Missiles, it should reset at the moment of casting Arcane Missiles, not at the end of the cast, maintaining the Arcane damage increase from Arcane Blast buff for each tick of Arcane Missiles.
2. The second bug corelates with first bug, meaning that Arcane damage from Arcane Blast buff is increasing the damage of Arcane Missiles only if the buff is present. For example if I stack Arcane Blast buff to 4 and I wait until 2 seconds, then I cast an Arcane Missiles, it will increase the damage only for the first 2 ticks of Arcane Missiles and the rest of 3 ticks will do normal damage.

**How to reproduce:**
Cast Arcane Blast until 4 stacks, wait until you have 2 seconds left on it, you can remove Missile Barrage proc to have a 5 seconds channeling cast of Arcane Missiles (or try it without the talent), then do Arcane Missiles. 

**How it should work:**
Arcane Blast buff should reset the moment Arcane Missiles is casted and maintain the increased damage for all 5 ticks.

Keep in mind that trinket procs which ncrease spellpower can modify the damage of ongoing ticks of Arcane Missiles. If your trinket proc ends during the channel of Arcane Missiles, the remaining ticks should do less damage calculated with the current spellpower (which it works now, but test this too after you fix the above to be sure it doesn't bug). Same applies for Arcane power, because Arcane Missiles cannot "snapshot" damage modifiers spells or spellpower as far as I know. By "snapshot" I mean doing Arcane Missiles on the last second of Arcane Power and expect damage increase on all 5 ticks.
The only "snapshot" you can do is casting Arcane Missiles on the last second of Arcane Blast buff.

**Database links:**
Check any video related to Arcane Mage to see the buff resetting on Arcane Missiles cast:
https://youtu.be/OQf1-QsrqjI?si=TulPPI4mjJPt_TcO&t=190

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by Piootrek** [comment]
Server will be updated in ~40 minutes from now
