### ISSUE TITLE
[MPG] Vezax shadow crash target

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#1777]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Currently the farthest target within 100yrds-ish ALWAYS get the shadow crash on him. This is problematic because the marked player will always get shadow crash on him since he needs to move away from boss. Also problematic because you can cheese bait the crashes if you know who gets it.

**How to reproduce:**
have 1 tank on vezax ptr, 1 person in the middle, 1 person right behind the middle guy will always get shadow crash

**How it should work:**
RANDOM person from guys that are further away from vezax should get shadow crash
https://youtu.be/bXP9TEAwhzU?si=j88V8aE6uW6IVpgM&t=3982
Check this vid and see that person furthest away doesn't get it by default.

**Database links:**

**Comment by Afgann** [comment]
fixed
