### ISSUE TITLE
[MPG] Yogg kill hp

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#1778]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Currently Yogg counts as dead at exactly 1% hp. On classic and og he died at 1.5% instead. Minor thing overall I guess

**How to reproduce:**
Kill yogg normally, he will die at 1% hp phase 3.

**How it should work:**
https://youtu.be/bXP9TEAwhzU?si=tgfr7GfGnrLgK7in&t=4509 timestaped classic vid, yogg dies at 1.5% hp (1.43% to be exact because of overhead dmg) 
https://youtu.be/grT9Awoud_U?si=XIOgusJ-XlsTJ7wi&t=33 - timestamped OG vid, yogg dies at 820k/55m=1.5%

**Database links:**

**Comment by Afgann** [comment]
fixed
