### ISSUE TITLE
Infinite Ground AOE Visual

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#178]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Ground AOE spells like Death and Decay and Explosive Trap have a chance to stay on the ground forever visually. It keeps doing the animation repeatedly forever even after their damaging effect expires. Probably other similar aoe spells as well have only seen these two so far. Could cause potentially serious loop issues.

Most likely related to either leeway or batching implementation as I've only seen it happening after those were applied.
Slight possibility its also related to https://github.com/gamefreedomgit/Frostmourne/issues/163 but just a guess.

**How to reproduce:**
Doesn't happen all the time but the explosive trap I've been able to reproduce a lot in duels. 
The trap can also easily bug and not pop at all ( a more serious issue) -  this part is definitely related to leeway implementation.

DnD one have only seen it once in naxxramas while I was lagging behind the group it stayed on the ground minutes after the dk who casted it moved on forward.

**How it should work:**

**Database links:**

**Comment by WhitemaneIsa** [comment]
No further info/complaints, closing.
