### ISSUE TITLE
Sapphiron visual spawn

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1780]
Sapphiron RP/Bone swirl often does not happen at all. she just randomly appears after a period of nothing being visible.
sometimes the animation gets canceled randomly and it takes about 2-5mins to actually spawn him due to how random it is.

**Comment by Riztazz** [comment]
Fixed, will close once it's live

**Comment by Manpower99** [comment]
> Fixed, will close once it's live
> 
> That was hard to debug lol

Funny enough, this was not an issue until very recently.
