### ISSUE TITLE
[MPG] Yogg - Crusher tentacle Focus Anger

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#1781]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Pet attacks are still adding stacks of focus anger on crusher tentacles. They should not on 25nm/10nm modes.

**How to reproduce:**
Send a warlock pet while crusher is stunned by the room, watch its attacks add stacks of focus anger

**How it should work:**

Hotfix(2009-06-15): "Focus Anger, on Yogg-Saron's Crusher tentacles, will no longer result from pet attacks."

**Database links:**

**Comment by Afgann** [comment]
fixed
