### ISSUE TITLE
MPG Thorim Aura of Celerity

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1784]
Mind controlling the Dark Rune Warbringers gives Aura of Celerity only to Party of the priest instead of entire raid.
I would recommend to keep it this way on HC pre nerf and allow to be raid wide on normal post nerf.
https://www.wowhead.com/wotlk/npc=32877/dark-rune-warbringer#comments:id=723188

**Comment by Afgann** [comment]
fixed
