### ISSUE TITLE
[PTR] Yogg 25m bugs including gamebreaking ones

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#1785]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

Tested on the PTR, and not on Mimiron's playground.
Sunday the 1st and Wednesday the 4th, all pulls are with 0 lights.
**Full raid session recordings can be linked privately to devs if they  ask, but I won't post them publicly here.**

### Auriaya said hello
On two separate pulls while we were in phase 2, Auriaya got pulled, started walking towards the yogg room and eventually wiped us with sentinel blast. Huge issue for guilds that skip cat lady to clear faster. No real idea about what might cause it though.

### Diminish power in brain room
**Issue:** 
If a crusher is channeling diminish power while a player enters the brain room, the debuff will stay on them for the full 5 minutes or until they die. 

In this screenshot you can see that everyone who is in range of the rogue has diminish power while people outside the room don't. The rogue died, so he lost the debuff.
![image](https://github.com/user-attachments/assets/7b440842-2f0d-4b6e-a0fc-4e7ae063d06e)

**How it should work:**
It should still apply to people in the brain room, but it should be removed when the crusher stops casting as usual.
Proof at 5:30 in video https://www.youtube.com/watch?v=QhvuZHuzj4M

### Pets can't reach yogg brain
When a player with a pet is inside the brain room and tries to send his pet to attack the brain, it will always get stuck in a spot just outside of melee range, by the portal between the stormwind and icecrown rooms. They are not able to attack.

**Screenshot** 1: Pets in the top left.
![image](https://github.com/user-attachments/assets/396fcdf4-751e-418b-95ae-7dc14e5db2e5)

**Screenshot** 2: Different orientiation. Pets in the bottom right, but they are stuck in the same spot in the game world.
![image](https://github.com/user-attachments/assets/39988a94-fc0b-4b48-b52b-b7bcc8fd78ae)

### Squeezed while entering portal
constrictor tentacles always spawn just after portals spawn. A player can get picked up just as they are entering a portal, bugging out the positioning of the tentacle while the player gets teleported inside and dies to squeeze.

**Suggestion**: If it's hard to fix, just make the constrictor spawn a split second before the portals to avoid the issue.

**Screenshot**: Tentacle is floating above me out of range, and you can see that the shaman who got gripped is in the brain room as his raidframe is darkened.
![image](https://github.com/user-attachments/assets/cfc36f5d-081a-433c-a61c-5a642d03e3a8)

**Comment by Afgann** [comment]
fixed
