### ISSUE TITLE
[PTR] Alga constellations big issue

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#1786]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description**
After my recent report, constellations now have a threat table, however they cannot move while casting, which is most of the time. The only time they move is while algalon is casting big bang, as the constellations stop casting then.

**How it should work:**
They should always move towards the player that has aggro on them, **even while casting, and they should move more quickly than they do currently.** For more information, refer to the original report. https://github.com/gamefreedomgit/Frostmourne/issues/1722

I recall this exact bug popping up weeks ago, the first time constellations were fixed by adding a cast time to them and making them interruptable. Please be careful to get it right this time. The boss will be very RNG heavy if constellations cannot be controlled.

Quick video showing stars getting stuck in the air and not following their aggro target unless interrupted.
https://youtu.be/v44uDuOjFGk

**Comment by Afgann** [comment]
fixed
