### ISSUE TITLE
Lost my Soul-Trader Beacon plz help

### ISSUE THREAD

**Issue by DarthLordVoid** [gamefreedomgit/Frostmourne#1788]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
So I placed him on my Hardcore druid, that toon died so I deleted them to reuse the name but now I'm missing my store pet on all my toons.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Report that on our Discord channel or open in-game ticket.
