### ISSUE TITLE
[PTR] Assault bot doesn't drop core

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#1790]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

Several times during our firefighter 25m hc pulls, the assault bots in phase 3 have either not dropped anything at all, or the magnetic core on the corpse has been unlootable even for the raid leader and despite the loot system being set to free for all.

Once again, I forgot to press record on firefighter so there's no video. Apologies.

**Comment by Chaos-within** [comment]
Since drops are disabled, the core is sold from the vendor at Ulduar entrance

**Comment by NickZedd** [comment]
this was on the ptr, not playground.

**Comment by Manpower99** [comment]
even on PTR the drops are same from what i see, getting scarlet sigils instead of actual items.
