### ISSUE TITLE
Illustration of the Dragon Soul trinket and Levitate

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#1791]
**Description:**
Casting Levitate does not give you a stack of trinket proc while wearing Illustration of the Dragon Soul

**How it should work:**
It should

**Database links:**
https://www.wowhead.com/wotlk/item=40432/illustration-of-the-dragon-soul#comments

![2024-09-04 21_18_11-Illustration of the Dragon Soul - Item - WotLK Classic](https://github.com/user-attachments/assets/875b4e9e-e9df-4e0b-a624-3d3931b738f1)

**Comment by Godmatik** [comment]
.

**Comment by Godmatik** [comment]
Bump =(

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
