### ISSUE TITLE
[PoW] WG S6 Items Missing from Vendor

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1792]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** On PoW island WG vendor is missing items that are introduced in S6 - namely 213 ilvl stuff. PvP Trinkets, and offset pieces.

**How to reproduce:**

**How it should work:** They should be present

**Database links:**

**Comment by Ingeniouskid** [comment]
they are not missing though

**Comment by haephaistoss** [comment]
seems fixed
