### ISSUE TITLE
[PoW] S6 Wartorn Items Missing

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1793]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** S6 (3.1 / Ulduar) content wartorn (PvE - Badge - Crafted) Items are missing from PoW Island Vendors. Honorable Mention: Val'Anyr (though the passive should be turned off for pvp applications)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Riztazz** [comment]
@RadeghostWM need your decision on this

**Comment by RadeghostWM** [comment]
They will be added, but not just yet. Some time need to pass @ Ulduar.

**Comment by RadeghostWM** [comment]
Close
