### ISSUE TITLE
[PoW] S5 Weapons Missing

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1794]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** On PoW Island S5 weapons are missing from vendors. While they were removed in OG wrath with the release of s6, having them as a catch up mechanic may be useful if we want a competitive experience

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Riztazz** [comment]
@RadeghostWM need your decision on this

**Comment by RadeghostWM** [comment]
They can be re-added to vendor.

**Comment by haephaistoss** [comment]
they already have been readded (although offhands, like grimoirs are missing)

**Comment by Riztazz** [comment]
![image](https://github.com/user-attachments/assets/537e9a01-1fe6-492b-8aec-0ee45bf0ab96)
I can see those items just fine including offhands, closing.
If you see a vendor with missing items, please specify which items
