### ISSUE TITLE
[POW] Requirements for old trinkets

### ISSUE THREAD

**Issue by danniellos94** [gamefreedomgit/Frostmourne#1795]
**Description:**
Requirements for the trinkets from Kizz Fizzlebolt should be decreased 1950 arena rating and 2370 arena points is big cost for a 200 ilvl trinket even if its bis for many class seems too high especially with new ulduar trinkets coming. There were also a lot of suggestions to add more trinkets like jet'ze bell etc so maybe it's a good thing to look.

**How to reproduce:**
Check the price of the trinkets.

**How it should work:**
The price of old trinkets and requirements should be reduced a bit.

**Comment by Riztazz** [comment]
@RadeghostWM need your decision on this

**Comment by RadeghostWM** [comment]
Yes, that can be done for all trinkets.

**Comment by Riztazz** [comment]
To what values? For PVE trinkets i will need some list, 'etc' does not help;p

**Comment by danniellos94** [comment]
All darkmoon cards should be avalaible listed here https://www.warcrafttavern.com/wotlk/guides/wotlk-classic-darkmoon-faire-guide/ some of them are not avalaible.
Also these trinkets seems to be missing:
https://www.wowhead.com/wotlk/item=37111/soul-preserver
https://www.wowhead.com/wotlk/item=40684/mirror-of-truth
https://www.wowhead.com/wotlk/item=40682/sundial-of-the-exiled
https://www.wowhead.com/wotlk/item=37835/jetzes-bell
https://www.wowhead.com/wotlk/item=37723/incisor-fragment
https://www.wowhead.com/wotlk/item=37166/sphere-of-red-dragons-blood
https://www.wowhead.com/wotlk/item=37873/mark-of-the-war-prisoner

For the price it's really up to you in my mind was to half the arena points requirements at least and 1400 arena rating for 200ilvl trinket and 1500 for 213, but some of the worse 200ilvl trinkets should be avalaible for just honor in my opinion.

**Comment by Riztazz** [comment]
Fixed, will close once it's live. All trinkets will be 60k honor ( no hate, i just implement stuff )

**Comment by haephaistoss** [comment]
That's perfectly priced ❤️
