### ISSUE TITLE
MPG- Yogg Saron Brain rooms and pets

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1796]
Pets are simply useless atm in Brain Room's.
They cannot attack the influence tentacles due to weird pathing being very far range from it. but also not the brain itself.

Simply send pets to attack [Influence Tentacle](https://wowpedia.fandom.com/wiki/Influence_Tentacle) or [Brain of Yogg-Saron](https://wowpedia.fandom.com/wiki/Brain_of_Yogg-Saron) and observe the issue.

**Comment by Afgann** [comment]
fixed
