### ISSUE TITLE
Kelthuzad MC'd targets

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1797]
getting mc'd by KT should increase the size of the players affected
https://youtu.be/QsvCeOUOvuw?si=yUmEnDckPnAM1vVF&t=355

![image](https://github.com/user-attachments/assets/b2d09cd9-5e80-4aae-92ec-5df96f08d63c)

**Comment by Piootrek** [comment]
Fixed, will close this issue once the fix comes live.

**Comment by Manpower99** [comment]
> Fixed, will close this issue once the fix comes live.

Thanks!
