### ISSUE TITLE
[Deathknight] Risen ghoul casting gnaw

### ISSUE THREAD

**Issue by danniellos94** [gamefreedomgit/Frostmourne#1798]
**Description:**
Risen ghoul should not cast gnaw despite knowing that ability.

**How to reproduce:**
Use risen ghoul in pvp scenario as frost or blood dk.

**How it should work:**
Risen ghoul should only use leap and claw. Looking at frost dk logs you can see risen ghoul never casted a gnaw in pve scenarios.

**Database links:**
https://wowwiki-archive.fandom.com/wiki/Risen_Ghoul

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
