### ISSUE TITLE
[Deathknight] Corpse explosion cast should be interruptable

### ISSUE THREAD

**Issue by danniellos94** [gamefreedomgit/Frostmourne#1799]
**Description:**
Corpse explosion casted by ghoul should be interruptable.

**How to reproduce:**
Use pummel or mind freeze/ any interrupt on ghoul casting explode.

**How it should work:**
The cast should be interruptable.

**Database links:**
https://github.com/ClassicWoWCommunity/cata-classic-bugs/issues/96

**Comment by haephaistoss** [comment]
They even finish the cast while CC-ed in my testing with holy wrath

**Comment by Piootrek** [comment]
Fixed, will close this issue once the fix comes live on the server.
