### ISSUE TITLE
[SHAMAN] Fire Elemental Attacking targets from the front

### ISSUE THREAD

**Issue by gmforghieri** [gamefreedomgit/Frostmourne#180]
**Description:**
Fire elemental is attacking targets from the front instead of back this is causing lost dmg due to extra parried attacks or potentially being cleaved down, making the biggest CD of the Shaman class useless.

**How to reproduce:**
Summon fire elemental and see it not position itself correctly. 

https://www.twitch.tv/videos/2064557382

![image](https://github.com/gamefreedomgit/Frostmourne/assets/23323833/5050cd86-339d-487f-a0d9-80825c8c2535)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/23323833/44812c1d-90bc-446c-8d6c-6050a2de884c)

**How it should work:**
Pets/Guardians should attack the boss from behind.

**Comment by Afgann** [comment]
fixed
