### ISSUE TITLE
[PoW] Yellow Gem Gossip Option Wrong Color

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1800]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

![image](https://github.com/user-attachments/assets/0da3a298-9311-4f69-b04e-a06bc86e8f8c)

Yellow has blue image

**How to reproduce:**

**How it should work:** Yellow should have yellow image

**Database links:**

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fixe comes live.
