### ISSUE TITLE
[General] Away status not clearing

### ISSUE THREAD

**Issue by sstndr** [gamefreedomgit/Frostmourne#1801]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Away status clearing after multiple inputs

**How to reproduce:**
https://imgur.com/a/NB26fS5

**How it should work:**
I shouldn't have to /away twice to clear it. Moreover the message is not aligned to the <away> status

**Comment by Riztazz** [comment]
fixed, will close once it's live
