### ISSUE TITLE
Warrior: Deep wounds stack issue

### ISSUE THREAD

**Issue by vedude** [gamefreedomgit/Frostmourne#1808]
**Description:**

Now that munching is gone and after some testing, I realized that the reason Deep Wounds is doing so low after the bug fix is that it's not stacking as it is supposed to and it's delayed on each proc. Let me clarify below.

**How to reproduce:**

You do your rotation. Deep wounds stacks up. However, I noticed a big problem immediately and that is if you do not followup crit during the next 1-2 seconds the damage value of deep wounds goes lower.

It's like this: You crit a couple of times consistently and it ticks for 1800-2000. Next gcd you didn't crit, and deep wounds ticked 1800 for 3 times before you get another crit. It now ticks for 1000 or less.

This is wrong. Deep wounds debuff lasts for 6 seconds. As long as you keep critting it should keep stacking. You should not be punished for failing to crit within 3 seconds.

Another problem is every crit rather than stacking deep wounds on top of it's previous one, it counts as adding a new deep wounds debuff instead.
That is why you probably noticed that deep wounds take a small delay after a crit is done and the new damage number appears.

**How it should work:**

Deep wounds should keep stacking by critting within 6 seconds of the debuff timer. 
Instead of applying new debuff and having delay for the new deep wounds damage to show, it should be like clockwork and tick every second no matter how much you crit within the 6 seconds.

Here is a video explaining the wotlk edition of deep wounds:

https://www.youtube.com/watch?v=ibGHckCYDjk

**Comment by Manpower99** [comment]
Each crit adds to its "bank" which depletes over 6s each 1s
![image](https://github.com/user-attachments/assets/d13b7eba-ec55-4f0e-a115-310db741abc5)
og wow proof, not necessarily keeps growing only, it can also deplete and go lower.

**Comment by vedude** [comment]
Thanks for the clarification. Does it match exactly on how it works on Whitemane though?

The delayed ticks should for sure be looked at though.

**Comment by Manpower99** [comment]
> Thanks for the clarification. Does it match exactly on how it works on Whitemane though?
> 
> The delayed ticks should for sure be looked at though.

To be fair with you, OG wotlk had munching and today less than hr ago there was an update to make it like classic and removed munching, so you should expect more damage added to your deep wounds bank overall. wether or not their formula matches blizzard's damage formula for deepwounds or not, i don't know.
Perhaps if devs here would show us in how they have it in their core we would see if it matches their classic's formula or not in addition to proper testing to see how it handles percentage damage modifiers on the player.

**Comment by Riztazz** [comment]
```
baseAmountOfDeepWound + ((OldDeepWounds->TotalAmount() * max( TotalTicks - CurrentAuraTick, 0)) / TotalTicks);
```
so whatever was left in the old deep wounds is added to the new deep wounds and refresh on a target

**Comment by Manpower99** [comment]
> ```
> baseAmountOfDeepWound + ((OldDeepWounds->TotalAmount() * max( TotalTicks - CurrentAuraTick, 0)) / TotalTicks);
> ```
> 
> so whatever was left in the old deep wounds is added to the new deep wounds and refreshed on a target

So i guess it works perfectly by this.
will check how it handles percentage damage modifiers on the player on PTR, some people were claiming some auras were giving less to deepwounds than it should. will report back

**Comment by Riztazz** [comment]
So, can be closed?

**Comment by Manpower99** [comment]
Completely forgot about this due to focus on Ulduar and Paladin Auras, will do some tests asap.

**Comment by Manpower99** [comment]
So far works fine, close it if you wish but i'll comment and tag you if i notice anything in the future.
