### ISSUE TITLE
Risen ghoul should not be able to use corpse explosion

### ISSUE THREAD

**Issue by danniellos94** [gamefreedomgit/Frostmourne#1809]
**Description:**
Currently you can use corpse explosion with risen ghoul.

**How to reproduce:**
Cast raise dead and get 40 runic power and use corpse explosion.

**How it should work:**
Corpse explosion should only work on permanent ghoul.

**Database links:**
https://www.reddit.com/r/wotlk/comments/wp7e79/death_knight_mechanics_from_ptr_testing/
Using Corpse Explosion on your Risen Ghoul is only possible when your Ghoul is permanent, and causes zero threat to you.

**Comment by Sylanha** [comment]
![image](https://github.com/user-attachments/assets/78adbe97-1acb-4a02-9e58-c2f86d240ee8)

In the same evidence you posted you can read that it actually is working as intended. Please double check your proof, otherwise you are not helping, but nerfing/fixing by using false reports.

**Comment by danniellos94** [comment]
As there is no more proofs to be found and I think this one is not enough I'll close this.
