### ISSUE TITLE
Horn of Winter an Str of Earth totem logic

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#181]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Currently if you have improved strength of earth totem by talents, you cannot apply horn of winter
while they should not stack, you should still be able to apply it
**How to reproduce:**
have imp str of earth talented cast it , apply horn of winter and it won't add it as a buff

**How it should work:**
Should coexist as a buff but only the strongest apply ( this way if you outrange the totem, the horn of winter effect is in place )

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
