### ISSUE TITLE
[CORE] CC While Moving

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1810]
CCs that cause the character to move, like Poly, Fear, Death Coil, Psychic Scream etc... teleport the affected player back 5-10 yards if they were caught during locomotion. It's more noticeable the higher movement speed the affected player has at the moment of getting cc'ed, but it has severe implications.

You were running behind pillar to not get caught in the open, poly is cast you are already behind the pillar, the poly is finished, and you are teleported back outside where you can get nuked.

CCs like this should obviously not teleport Players back.

It happens most often with mounted players, but I've seen it happen during jumping too.

**Comment by Riztazz** [comment]
Is this still valid? This is potentially fixed by fleeing commit recently

**Comment by haephaistoss** [comment]
haven't been playing since last week, gotta check it later tonight

**Comment by Riztazz** [comment]
Could i get a video of it please?

**Comment by haephaistoss** [comment]
> Could i get a video of it please?

I'm trying, but I can't alt tab fast enough, and I don't know what it looks like from inside

**Comment by haephaistoss** [comment]
can't reproduce it, it may have been a wierd client shenanigan. I say it's fixed fair and square. I'll reopen if it happens again
