### ISSUE TITLE
Corpse explosion range

### ISSUE THREAD

**Issue by danniellos94** [gamefreedomgit/Frostmourne#1811]
**Description:**
The range of corpse explosion on ghoul is too much. It is propably 10 range

**How to reproduce:**
Use corpse explosion on ghoul.

**How it should work:**
Corpse explosion on the ghoul should have 5 y range, and the glyph of corpse explosion shouldn't increase that (it should only increase the range of corpse explosion for corpses on the ground).

**Database links:**
https://www.reddit.com/r/wotlk/comments/wp7e79/death_knight_mechanics_from_ptr_testing/
While Corpse Explosion on enemy corpses is a 10 yard range, using it on your Ghoul is a tiny 5 yards range.
https://prnt.sc/pOFrc7fa19xf

**Comment by Riztazz** [comment]
It does not work like you describe it, it has 5yards and glyph does not affect the 'explode' corpse explosion (of a real pet).
Those are two very different spells
