### ISSUE TITLE
Ratos to fish Mr. Pincgy are ok??

### ISSUE THREAD

**Issue by tbragulat** [gamefreedomgit/Frostmourne#1812]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I can't catch Magical Crawdad (Mr. Pinchy). I've spent many hours and there's no way to fish it. I would like to know if the drop rates to get it are correct, as I've talked to other people, and they haven't been able to get it either... When I spoke with a GM, they suggested I write here so the developers can give me a response.
Thank you very much for your time,
Best regards

https://www.wowhead.com/achievement=726/mr-pinchys-magical-crawdad-box
https://www.wowhead.com/item=27388/mr-pinchy

**How to reproduce:**
I can't fish Mr. Pinchy

**How it should work:**
Fix the rates maybe...

**Database links:**
https://www.wowhead.com/achievement=726/mr-pinchys-magical-crawdad-box
https://www.wowhead.com/item=27388/mr-pinchy

**Comment by Riztazz** [comment]
It's 0.5%

**Comment by Chaos-within** [comment]
Spent a few days fishing there in July, to no avail. Figured it was bugged as well.

**Comment by Riztazz** [comment]
@RadeghostWM I've tried googling about the rates for this item but fell short, should we bump it a bit? I think 0.5% is slightly too small

**Comment by RadeghostWM** [comment]
Let's give it 1%. I fished 1000+ times for it on retail Classic WotLK but never got it either :P

**Comment by Riztazz** [comment]
will close once it's live
