### ISSUE TITLE
Frost Nova Debuff

### ISSUE THREAD

**Issue by reminuz** [gamefreedomgit/Frostmourne#1817]
https://imgur.com/a/80hKoxL

https://www.wowhead.com/wotlk/spell=33395/freeze
https://www.wowhead.com/wotlk/spell=122/frost-nova
https://www.wowhead.com/wotlk/spell=54787/shattered-barrier

**Description:**
There are 3 differents debuff from freeze, frost nova and shatter barrier.

**How to reproduce:**
Cast Pet's Freeze, Frost nova and break Ice Barrier.

**How it should work:**
There should be one debuff, not three.

**Database links:**

https://www.wowhead.com/wotlk/spell=54787/shattered-barrier#comments

**Comment by haephaistoss** [comment]
Another case of aura stacking
https://github.com/gamefreedomgit/Frostmourne/issues/1498

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
