### ISSUE TITLE
[PTR] Yogg Psychosis bugs

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#1819]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

The psychosis spell cast by Sara does not reduce sanity. Each hit should remove 9 sanity on 10m and 12 sanity on 25m.

Also, psychosis hits people inside the brain room when it should not. We've been unable to find any instance of psychosis hitting inside the brain room in any videos. Some of them are linked below if you want to check.

From PTR:
https://youtu.be/i10E2YL0Sos

From classic:
https://youtu.be/AQQ9zKoYwMo?t=212

From retail (2009)
https://youtu.be/VWtJL-A81u0?t=353
https://youtu.be/zKzO0Mdg4e0?t=247

https://www.wowhead.com/wotlk/spell=65301/psychosis
https://www.wowhead.com/wotlk/spell=63795/psychosis

**Comment by Manpower99** [comment]
can fully confirm both of the issues
it happens in brain room and it does not reduce sanity.

**Comment by Afgann** [comment]
fixed
