### ISSUE TITLE
Crocolisks in Blackmorass not moving

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1820]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

There's an issue with a few [Darkwater Crocolisk](https://www.wowhead.com/wotlk/npc=17952/darkwater-crocolisk)s pathing. Even though player has aggro on them, they will not move.

Here's a short video of one; They arent moving at all.
![2024-09-0622-38-00-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/aadc0d11-def0-4d05-a96b-7d1878cc335e)

**How to reproduce:**

Pull the crocolisks in black morass dungeon.

**How it should work:**

All mobs in that dungeon should follow the player.

**Comment by Afgann** [comment]
fixed
