### ISSUE TITLE
boss frames bug out on fights with changing boss units

### ISSUE THREAD

**Issue by oomshroom** [gamefreedomgit/Frostmourne#1821]
Boss frames and boss units (boss1/2/3...) bug out when the boss unit changes to a different one (different phase etc) and stays bugged until you re-enter the instance.

Example:
1. pull Yogg-Saron. boss1 is now Sara
2. get to phase 2. boss1 correctly changes to Yogg-Saron (boss frame disappears for me though, not sure if server bug)
3. wipe and pull again WITHOUT LEAVING INSTANCE. boss1 is now Unknown and Sara is boss2

Similar issue on Kologarn.

The last "correct" boss unit will continue becoming Unknown and moving down the list with each pull, and it will only get fixed upon re-entering the instance.

**Comment by Afgann** [comment]
fixed
