### ISSUE TITLE
Classes benefit from [Turn the Tables] [Rogue]

### ISSUE THREAD

**Issue by Miguelsanx** [gamefreedomgit/Frostmourne#1824]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
There are classes benefiting from a rogue talent [Turn the tables] (52910), when this should only be for the rogue or feral.

This talent works: Whenever anyone in your party or raid blocks, dodges, or parries an attack your chance to critically hit with all combo moves is increased by 6% for 8 sec.

**How to reproduce:**
Create lvl 80 Protection paladin
Create lvl 80 Assa Rogue (With this talent)
Create lvl 80 Enha Shaman

Make a party with these 3 and when Protection Paladin block, dodge or parries, rogue will get the buff [Turn the tables] and shaman too.

**How it should work:**
This buff should only be for the rogue or feral

**Database links:**
https://www.wowhead.com/wotlk/spell=51629/turn-the-tables
https://imgur.com/Th4ETWV

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
