### ISSUE TITLE
[DK] Chill of the Grave talent affected by Threat of Thassarian talent

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#1825]
**Description:**
Chill of the Grave 2/2 talent from Frost spec on DK, generates additional 5 Runic Power on Obliterate.
Threat of Thassarian 3/3 talent from Frost spec on DK, gives you 100% chance for Obliterate to also deal damage with your offhand.

Right now, Chill of the Grave 2/2 is generating additional 10 Runic power on Obliterate, if you have Threat of Thassarian 3/3 talent.
The T7 4 set bonus has the same tooltip as Chill of the Grave talent and It generates 10 Runic Power on Obliterate, if you have Threat of Thassarian 3/3 talent.

**How to reproduce:**
Put the talents above and cast Obliterate.

**How it should work:**
The additional Runic Power is wrongly generated. It should be only 5 for Chill of the Grave and 5 for T7 4 set bonus on Obliterate cast, even if you have Threat of Thassarian talent or not, giving you a total of 25 Runic Power instead of 35. (Obliterate itself generates by default 15 Runic Power)

I found out about this bug after I made a bug report on the other "mane" wotlk server, thinking it works correctly here, but not there. After my ticket was dismissed, I started to look closely to videos from wotlk classic to see how much Runic Power is generated.

![image](https://github.com/user-attachments/assets/66cdc325-3d7e-428c-a078-7fd9ecb4cdec)

**Database links:**
Check any video related to Frost DK doing Obliterate: (you might need to slow the speed of the video)
https://youtu.be/6TZVE3-Qh_8?si=dIIy-HxXAKqx_eMj&t=22 here is a video from Naxx where Obliterate generates 25 runic power (15 from Obliterate + 5 from Chill of the Grave + 5 from T7 4 set bonus)
https://youtu.be/4JKK5fHIKWs?si=54m0gZzAIMI19o0N&t=24 here is a video from Icc where Obliterate generates 20 runic power (15 from Obliterate + 5 from Chill of the Grave)

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
