### ISSUE TITLE
[Prot Pala] Guarded by the Light: Judgement doesn't refresh Divine Plea duration

### ISSUE THREAD

**Issue by gugovgeorgi** [gamefreedomgit/Frostmourne#1826]
https://www.wowhead.com/wotlk/spell=53585/guarded-by-the-light
https://www.wowhead.com/wotlk/spell=54428/divine-plea

**Description:** 
The talent 'Guarded by the Light' should refresh the duration of 'Divine Plea'.
'Guarded by the Light' reads: _Reduces spell damage taken by 6% and gives a 100% chance to **refresh the duration of your Divine Plea when you hit an enemy**.  In addition, your Divine Plea spell is 100% less likely to be dispelled._

The "...refresh the duration of your Divine Plea when you hit an enemy." part should work for any attack, i.e. melee swings and attack skills.
Judgement falls under attack skills. This is reflected in it's requirement of 8% melee hit to guarantee no misses on Judgement.
As such, using any Judgement should count as 'hitting' the enemy and, subsequently, refresh the duration of 'Divine Plea'.
Here is a link to a video showing the interaction as it currently is on Whitemane, i.e. Judgement does not refresh the duration of 'Divine Plea':
https://youtu.be/gd0YkS-htMI

**How to reproduce:**
1. Get 2/2 in 'Guarded by the Light'.
2. Apply 'Divine Plea' on yourself.
3. Move out of melee range (to eliminate the possibility of the character doing a melee swing, which WOULD re-apply 'Divine Plea')
4. Cast any Judgement.

Actual Result: Divine Plea is not refreshed.

**How it should work:**
Expected Result: 'Divine Plea' should be refreshed.

**Database links:**

**Comment by haephaistoss** [comment]
patch 3.2

**Comment by haephaistoss** [comment]
Patch 3.2.0 (04-Aug-2009): This talent will no longer cause Divine Plea's duration to be refreshed by using Judgement of Wisdom, Judgement of Justice, or Judgement of Light.

**Comment by gugovgeorgi** [comment]
Damn, I guess it's supposed to work that way... Thanks for the info, closing the issue!
