### ISSUE TITLE
Azjol-Nerub instance

### ISSUE THREAD

**Issue by Amine-x-x** [gamefreedomgit/Frostmourne#1827]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Hello , I was doing this dungeon and i did notice that the adds npcs in that dungeon (Anub'ar Webspinner) they are able to use Weeb wrap that traps the player inside a weeb on totems to instead of players only, and i think weebing a totem instead of players is a bug as some experienced dev pointed his opinion too.

**How to reproduce:**
Simply engage with the npc with totems near you and wait for the RNG of channeling that spell to be on totems.

**How it should work:**
It should weeb players only.

**Database links:**
https://wowpedia.fandom.com/wiki/Anub%27ar_Webspinner

**Comment by Afgann** [comment]
fixed
