### ISSUE TITLE
Piercing Shots Munching

### ISSUE THREAD

**Issue by Flohinwow** [gamefreedomgit/Frostmourne#1828]
Since we got ignite and deepwounds fixxed, might as-well ask for Piercing Shots.

Piercing Shots will cause a target to bleed for 30% of the damage caused by critical Chimera, Aimed, and Steady Shots.

If you are casting a Steady Shot that is immediately followed up by a Chimera Shot, both spells will land at the same time and only one spell’s damage will apply/refresh the bleed effect (assuming they both crit).

Say two critical hits land at the same time: one for 10,000 dmg (Chimera Shot) and another for 5,000 dmg (Steady Shot).

In theory, you would expect the target to bleed for (0.3)(10,000)+(0.3)(5,000) = 4,500 dmg, but in reality it will only bleed for (0.3)*(5,000) = 1,500 dmg.

Low prio since no one plays MM :kekw:

**Comment by scrublama** [comment]
how about righteous vengeance ret

**Comment by Afgann** [comment]
fixed
