### ISSUE TITLE
[CORE] Fear + Melee Hit = Random Teleporting all over the palce

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1830]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Melee hitting somebody under the effect of fear effects (fear, pshychic scream...) may sometimes cause the target to appear stationary but unable to be melee hit and then teleporting all over the place. It seems to be a visual issue, because hitting the target in melee is impossible since he's not actually there according to the server.

**How to reproduce:** Fear and start randomly meleeing feared target

**How it should work:** Players' models should be where they actually are

**Database links:**

**Comment by haephaistoss** [comment]
Happens with Death Coil too

**Comment by Riztazz** [comment]
Possibly fixed, let me know after an update how it looks

**Comment by haephaistoss** [comment]
> Possibly fixed, let me know after an update how it looks

will do, thanks!

Is it on the PTR yet?

**Comment by Riztazz** [comment]
It is on live as well, gonna keep this ticket open for a bit

**Comment by haephaistoss** [comment]
seems to not happen with warlock fear and dc anymore, awesome!

**Comment by Riztazz** [comment]
closing as fixed
