### ISSUE TITLE
The culling of stratholme (infinite corruptor npc)

### ISSUE THREAD

**Issue by Amine-x-x** [gamefreedomgit/Frostmourne#1836]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When you apply to the infinite corruptor npc in COS Heroic slow effect (i tested chain of ice as dk) he get the debuff of "slowed" but his speed remain same.

**How to reproduce:**
Apply slow effect to him and make him chase you.

**How it should work:**
Should either slow him or say "Immune". as every boss.

**Database links:**
https://www.wowhead.com/wotlk/npc=32273/infinite-corruptor

**Comment by Riztazz** [comment]
Fixed, will close once it's live

**Comment by Riztazz** [comment]
Had to revert, there were some issues

**Comment by Riztazz** [comment]
Fixed
