### ISSUE TITLE
Infinite AOE spells visual bug

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#1837]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Very rarely and in unknown conditions, aoe spells visual continues on forever on the spot it was casted (volley, hurricane, dnd, explo trap, etc).
Bug existed since beta and still happens, but original bugpost was closed. #178 
https://vimeo.com/1007395242?share=copy#t=0
this vid is from today.

**How to reproduce:**
Good luck finding this, all I can hint at is that back in the beta it seen it happen when spamming spells close to the end of their duration (spellqueue timer?) while also having high amounts of haste - it happens very rarely nowadays so my assumption could be completely wrong.

**How it should work:**
Aoe visual effects should end when the spell ends.

**Database links:**

**Comment by Afgann** [comment]
fixed
