### ISSUE TITLE
Druid talent "Feral Instinct" - feels very undertuned 

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#184]
**Describe the bug**
Tested both with 3/3 and without Feral Instinct talents - the mobs have a very high ability to detect you regardless (tested on mobs of same level), Feral instinct only increases your stealth power very slightly

**Expected behavior**
Feral Instincts talent should increase your stealth by 5 points per talent - up to 15 points when 3/3. That means three levels of stealth rating.

https://www.wowhead.com/wotlk/spell=16949/feral-instinct#comments

**Comment by qqdbpp** [comment]
i think this might be a problem with mobs aggro radius because it happens on rogue also, even with night elf racial and 3/3 master of deception you can just barely sneak up behind a same level mob, and if you stand in front they will aggro from nearly 10 yards away even in stealth

**Comment by UltraNix** [comment]
@Godmatik @qqdbpp Can you record it or give us some screenshots? I tested on mammoth with the same lvl as me - I was able to move in almost at its bounding radius.

**Comment by qqdbpp** [comment]
@UltraNix it feels a lot better on night elf rogue now at least, maybe some aggro range change in the last 20 days fixed it
