### ISSUE TITLE
Getting disconnected after reloading game

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#1840]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Since yesterday I've been getting consistently disconnected every time I /reload my game. The reload seems at first to work as intended, but about 0.5 seconds after loading back into the game, it freezes completely. After a while, it disconnects me and puts me back at the login screen with the message "You have been disconnected from the server."

This happens whether I'm using the old patch or the new one. Some guildies have mentioned having the same issue.

**Comment by Manpower99** [comment]
Same issue since yesterday.

**Comment by Riztazz** [comment]
How many addons do you guys have?

**Comment by Riztazz** [comment]
Can you guys try reproducing this when you're online then if it kicks you, let me know the exact server-time and your in-game names, i'll have to crawl through some logs;p

**Comment by UltraNix** [comment]
@Manpower99 @NickZedd Poke me on Discord.

**Comment by NickZedd** [comment]
Too many addons. 

I reproduced and reloaded at about 01:37:10 on the 11th. loaded back in and froze about 30 seconds later, got disconnected 26 seconds after that. In-game name is Nickzed.

It's easiest to reach me on discord if you need to ask more questions. Discord name is also Nickzed.

![image](https://github.com/user-attachments/assets/60106a0b-690d-4019-ba26-4055be0c465b)
![image](https://github.com/user-attachments/assets/c8a4ad76-03fb-4da7-8852-2b9ee986ba06)
![image](https://github.com/user-attachments/assets/05ee01ae-028e-4644-8a4b-72bfa9782d5f)
![image](https://github.com/user-attachments/assets/ad4b65ab-b267-4723-b51a-4e6a7d126b24)

**Comment by UltraNix** [comment]
It's some addons that causing the problem.

**Comment by scrublama** [comment]
@UltraNix im disconnecting on reload

**Comment by Manpower99** [comment]
@UltraNix Yesterday played whole day without addons in order to confirm it, and the disconnect thing still happens.

**Comment by NickZedd** [comment]
Yeah it still happens to a lot of people and I believe it started very close to the date when I originally posted this. I tried re-applying large address aware thinking it might not be working since using the new .exe from whitemane, but it didn't help.
