### ISSUE TITLE
[Ulduar] XT 25 nm spawned 2 hearts

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#1841]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Happened on 25 normal, non-hardmode in Mimirons playground.

After leaving the first heart of the deconstructor alive at about 20%, the boss activated but the heart was still attackable. It got cleaved to about 1% but I don't believe it died. It Despawned when the next heart spawned after pushing the boss low enough.

**How to reproduce:**
No idea. I can provide video evidence when my guildie sends it to me or uploads it.

**How it should work:**
The heart should always despawn after 30 seconds if not killed.

**Database links:**
https://www.wowhead.com/wotlk/npc=33329/heart-of-the-deconstructor

**Comment by Afgann** [comment]
fixed
