### ISSUE TITLE
Zul'darak fishing 

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1842]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Players get low level fish from the lake in Zul'darak.
![Screenshot 2024-09-09 115847](https://github.com/user-attachments/assets/fa9ed71c-d575-4e1d-9ff2-e6fca275b2cc)
These fish are from starting areas
character has fishing skill 450

**How to reproduce:**

Fish in the lake in zul'darak (right below altar of rhunok)
`Map: 571 (Northrend) Zone: 66 (Zul'Drak) Area: 4327 (Drak'Mabwa) Phase: 4294967295
X: 6024.736328 Y: -3330.354492 Z: 351.649689 Orientation: 6.212643
grid[43,25]cell[2,6] InstanceID: 0
ZoneX: 54.675434 ZoneY: 49.382126
GroundZ: 350.357330 FloorZ: 350.357330 Have height data (Map: 1 VMap: 1 MMap: 1)
MMAP Height: 350.90094`

**How it should work:**

Should drop high level fish according to https://www.wowhead.com/wotlk/zone=66/zuldrak#fishing

**Database links:**
https://www.wowhead.com/wotlk/zone=66/zuldrak#fishing

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
