### ISSUE TITLE
Freya - Ancient Water Spirit bug

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#1843]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
This is a very weird and specific bug: On Freya (tested 25nm, might happen on all difficulties) the Ancient Water Spirit cannot be used to cast Hunger for Blood on. It will consume your energy but you don't receive the hunger for blood buff.

**How to reproduce:**
Use bleed on Ancient Water Spirit, cast hunger for blood, see energy consumed but no buff.

**How it should work:**
Should be able to cast hunger for blood and receive buff on any target that has bleed on it.

**Database links:**

**Comment by Manpower99** [comment]
Somehow this is the only mob where i've encountered this issue also. cannot confirm for any other mob atm, but it happens consistently on Ancient Water Spirit(during mimirons playground)

**Comment by Afgann** [comment]
fixed
