### ISSUE TITLE
All Traps - Hunter and Trigger Radius/Range

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1844]
https://github.com/gamefreedomgit/Frostmourne/issues/1754
So far proof from wotlk classic and changelogs from retail indicate that it should be 5 **Yards from its center**, same as melee range.
on previous reports it was stated it should be 3 yard range which is incorrect and  lower than it should actually be.
https://wowpedia.fandom.com/wiki/Explosive_Trap
 https://wowpedia.fandom.com/wiki/Freezing_Trap

> [Patch 7.2.5](https://wowpedia.fandom.com/wiki/Patch_7.2.5) (2017-06-13): Explosive Trap now has a damage radius of 8 yards (was 5 yards).

> [Hotfix](https://worldofwarcraft.com/en-us/news/16561637/) (2015-01-08): Freezing Trap now has a trigger radius of 3 yards (down from 5 yards).

https://www.youtube.com/watch?v=QsvCeOUOvuw is a vod explaining how leeway should work and also it trigger range.
At 3:21 you can see he jumps to trigger leeway to place it further, it gets triggered simply due to being within melee range of the target dummy.
Will try to keep digging for further info if required, it has been quite noticable in raids this Weekly reset that traps are barely being triggered.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by Tednugg** [comment]
Amazing report, keep it up :)

**Comment by reminuz** [comment]
Totally wrong report. 5y was the radius in mop.

**Comment by Manpower99** [comment]
> Totally wrong report. 5y was the radius in mop. Wotlk radius was 2y. Check ur information before to report wrong.

At the very least i'm actually providing a video proof rather than a trustmebro argument which is fine for something that wouldnt screw over so many players. prove the bug report wrong by a video from og wrath or even classic or a changelog/elitistjerks archive if thats what you wish to do. 
previously this bug tracker had someone said "trustmebro" gargoyle had a gcd in wotlk and it was implemented, luckily it is no longer the case due to ample evidence and player feedback. the "fix" to make it 2yards was obviously rushed and i do not blame devs for it.

**Comment by lineagedr** [comment]
> Totally wrong report. 5y was the radius in mop. Wotlk radius was 2y. Check ur information before to report wrong.

You're right. Out of curiosity I decided to take a look at the WoTLK Classic DB2 files and for the traps the EffectRadiusIndex_0 is 7 and index 7 is 2 yards.

![image](https://github.com/user-attachments/assets/48fff6c4-0eb5-4210-b850-24359fff11a3)

**Comment by Manpower99** [comment]
> > Totally wrong report. 5y was the radius in mop. Wotlk radius was 2y. Check ur information before to report wrong.
> 
> You're right. Out of curiosity I decided to take a look at the WoTLK Classic DB2 files and for the traps the EffectRadiusIndex_0 is 7 and index 7 is 2 yards.
> 
> ![image](https://private-user-images.githubusercontent.com/12139798/365969190-48fff6c4-0eb5-4210-b850-24359fff11a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NjIyMjAsIm5iZiI6MTcyNTk2MTkyMCwicGF0aCI6Ii8xMjEzOTc5OC8zNjU5NjkxOTAtNDhmZmY2YzQtMGViNS00MjEwLWI4NTAtMjQzNTlmZmYxMWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA5NTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2YjQ3MDI3MzhkN2ZmYmQ1ZGUxYmVhODNhMTRkMmU1OWFiOTA1MTVjNDA0MGQzNTY3MTEwZjUwNzZhOGM2NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BNhfw8inY_XGRUuzkPYgWeIQxezcDc1jtapd21xlWbM)
> 
> [https://wago.tools/db2/SpellEffect?build=3.4.3.54261&filter[SpellID]=37368&page=1](https://wago.tools/db2/SpellEffect?build=3.4.3.54261&filter%5BSpellID%5D=37368&page=1)

Wowhead seems to indicate this as well, but in effect it doesnt look that way at all. players were triggering it by just being within melee range of it.

**Comment by Manpower99** [comment]
In fact there seems to be an intended feature by blizzard which their devs in classic labeled as "Not a Bug"
"The trigger range on Hunter’s traps are reduced by Stealth when the stealthed player is a similar or higher level than the Hunter." - Classic WoW "Not A Bug" List
https://www.reddit.com/r/classicwow/comments/ikcauz/comment/g3nmh8f/?utm_source=reddit&utm_medium=web2x&context=3

"" I've found that it is literally impossible to disarm a trap while unstealthed (5yd trigger radius?) but while I am stealthed it has like a 2 yd trigger radius, not sure why this works like this ""

@Piootrek perhaps this could be implemented?

**Comment by Manpower99** [comment]
https://www.youtube.com/watch?v=pFloJxdBCSU&t=749s check the trigger range here

**Comment by lineagedr** [comment]
By default the trap radius is 2 yards but I assume while the target is moving it applies the default leeway range of 2.6f and it becomes around 4.6

**Comment by lineagedr** [comment]
> https://www.youtube.com/watch?v=pFloJxdBCSU&t=749s check the trigger range here

The default radius is 2 yards and I'm assuming that blizzard is adding the default leeway of 2.6f internally making the radius 4.6f.

**Comment by Manpower99** [comment]
> > https://www.youtube.com/watch?v=pFloJxdBCSU&t=749s check the trigger range here
> 
> The default radius is 2 yards and I'm assuming that blizzard is adding the default leeway of 2.6f internally making the radius 4.6f.

Possibly yeah, it does make sense this way, its a 2yard radius with an improvement that only functions if the target is visible, thus invisibile enemy trigger is 2y

**Comment by Manpower99** [comment]
https://www.youtube.com/watch?v=og-2PjBJk2Q
Another vod, rogue does not trigger it in range due to stealth, warlock next to him does.

**Comment by Manpower99** [comment]
https://www.youtube.com/watch?v=lO5L-FROJvs&t=167s
And another one, the caster triggers it from 5y due to him being visible.

**Comment by Manpower99** [comment]
https://www.youtube.com/watch?v=yvebcQnII5w&t=37s
excuse the 2007 quality.
I don't know if all of this is sufficient proof of this interaction between visibility vs stealth trap activation range, but i can keep looking for more if it is required.

**Comment by reminuz** [comment]
https://youtu.be/ho0go3iH61A?si=EHNZBOFbaaW7MNSu
min 25.55 double trap crearly 2y trigger. Official wotlk pvp tournament.

**Comment by reminuz** [comment]
![IMG_4926](https://github.com/user-attachments/assets/9ad3ec38-eb2e-45fe-a278-a09e0d4cce83)

**Comment by Piootrek** [comment]
Decreased traps trigger radius for stealthed units. I will close this issue once the fix comes live.
