### ISSUE TITLE
POW item missing in vendors

### ISSUE THREAD

**Issue by Taicex** [gamefreedomgit/Frostmourne#1846]
**Description:** There is no pvp trinket for hordes 226ilvl,only for aliance,Medallion of the Horde is mising

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by danniellos94** [comment]
Bumping this.

**Comment by haephaistoss** [comment]
A lot of items are missing tho 🤕

**Comment by Afgann** [comment]
fixed
