### ISSUE TITLE
Hunter Pet Bug

### ISSUE THREAD

**Issue by Zniperzeu** [gamefreedomgit/Frostmourne#1847]
**Description:**
The "Sentry Worg" from Icecrown should be changing colors everytime u Dissmiss and call ur pet.

It should be switching from Black, to brown, to white and finally grey.

**How to reproduce:**
-

**How it should work:**

This wolf actually changes colors everytime you summon/call it. It switches from Black, brown, white and grey colors of this model. Perfect for those who can't decide which color is the best.

**Database links:**

https://www.wow-petopia.com/classic_lk/look.php?id=worg-multi-black-brown-gray-white

https://www.wowhead.com/wotlk/npc=30430/sentry-worg#drops

![worg-multi-black-brown-gray-white](https://github.com/user-attachments/assets/3667f8f2-5717-4dfc-8d5e-a4b7a327315e)

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by Zniperzeu** [comment]
Thankyou alot! <3
