### ISSUE TITLE
[Quest] [Whispers of the Raven God] 10607

### ISSUE THREAD

**Issue by GM-Nightmare** [gamefreedomgit/Frostmourne#1848]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Quest Object Is not giving quest credit , 

**How to reproduce:**
![image](https://github.com/user-attachments/assets/f74377cd-b177-4422-8aae-724ab4708dd4)

clicking the prophecies doesnt give credit
**How it should work:**
clicking the prophecies should give credit

**Database links:**
https://www.wowhead.com/wotlk/quest=10607/whispers-of-the-raven-god

**Comment by Piootrek** [comment]
It works correctly. You need Understanding Ravenspeech buff to get quest credit. You have a chance to get this buff after killing nearby creatures.
