### ISSUE TITLE
Blinking in the Air - Mage - Blink Spell

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1849]
1. Currently Blinking in the Air just resets the fall's momentum and you keep falling further regardless of how far you are from the ground below you.
If a mage blinks in the air about 40/38 yards from the ground's level it should put him on the ground right below him (with no fall damage ofcourse), it should still just reset the fall the same way if above 40yards.
the blinking to the ground shouldn't function while swimming.

https://youtu.be/I9AD1FHHWKY?si=2ZgTedIQ1rNb_cCn
https://www.youtube.com/watch?v=Nr4B0wmIj74
https://www.youtube.com/watch?v=LhuHvq1_So4
https://www.youtube.com/watch?v=tsOcWPhQBus&t=45&feature=youtu.be
https://www.youtube.com/watch?v=FUaOo02E0Q0
https://www.youtube.com/watch?v=TvFDr_8hj58

 2. When you jump from a cliff or some platform, it seems you should be able to jump back also (approximately 2-3 yards or possibility of batching/game tick for player's position which i believe it was blizzlike 300ms tick) https://www.youtube.com/watch?v=tK3onrwublo 0:52 and 25:12.

![image](https://github.com/user-attachments/assets/1a2255d6-5985-4427-8ad6-1f405f27d955)

 3. 
[Patch 1.4.0](https://wowpedia.fandom.com/wiki/Patch_1.4.0) (2005-04-19): An error message is now displayed if you try to use Blink on boats and zeppelins.
[Patch 1.3.0](https://wowpedia.fandom.com/wiki/Patch_1.3.0) (2005-03-07):
Using this spell should no longer cause you to fall through the world.
Blink can now be used to escape more of the stun effects used by creatures in the world.
Blink is no longer usable on boats or zeppelins.
 - Unsure if the zeppelin/boat fizzle was removed or not in wrath but it does make sense for blizzard to implement this.

Edit: Adding more info the more i find.

**Comment by Riztazz** [comment]
```
Blink is no longer usable on boats or zeppelins.
```

Pretty sure this was lifted at some point, because boats in ICC are transports as well

**Comment by Manpower99** [comment]
> ```
> Blink is no longer usable on boats or zeppelins.
> ```
> 
> Pretty sure this was lifted at some point, because the flying boat thingies during gunship in ICC are transports as well

Yeah i found some good proof of many things that happen in zeppelins/boats in wotlk as failsafes but no video proof of this as of yet. will try to keep finding but it isn't necessarily the biggest improvement the spell could use in comparison to  1.

**Comment by Manpower99** [comment]
> Report 2 as batching issue please, i'll fix 1, but i don't wanna touch 2 and it probably needs game decision :D

Will do!

**Comment by Manpower99** [comment]
> Fixed, will close once it's live

May i ask what minimum range did u introduce for it to? videos i posted i estimate the range to be 38/40 yards

**Comment by Riztazz** [comment]
40y
