### ISSUE TITLE
Adds getting pulled on their own while inside an instance

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#185]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
We entered naxx10 ascended and headed towards anub, after clearing the first 2 trash packs we were combat stuck and every 15-20 seconds or so we had 3-5 spider adds aggro towards us all coming from maexxna's path. We cleared up to maexxna while dealing with the constant adds and after that we headed towards the military quarter.

On our way to razuvious(on the room shown in the picture for reference), while clearing the trash the boss somehow got pulled on his own, this all happened while nobody was even downstairs, we walked back to let the boss reset and after clearing all the trash we had the unholy weapon adds from the room after razuvious start getting pulled towards us.
![opera_IHGdwndEtT](https://github.com/gamefreedomgit/Frostmourne/assets/101921457/ff101cf9-cfb9-44a5-b96f-d6fc1435aef0)

After dealing with all those bugged chain pulls we decided to go do os3d instead, and while clearing the 2 guardian adds right next to vesperon, the adds from the far right side of the room got pulled towards us, nobody was even remotely close to them to have somehow pulled them.

Also, during the actual sartharion fight, vesperon got pulled 20-25s before he was actually supposed to start flying down, but again, nobody was close enough to even damage him.

**Comment by wotlkenjoyer** [comment]
we were experiencing the same, after you guys changed something with spell queue or whatever it called, you broke something, it is going everywhere, raids, dungeons,  mobs being stuck under the ground (unhittable)    

In naxx we went ascended,  mobs coming from every quarter, spiders, bats, abominations, everything coming during each boss encounter.

**Comment by Afgann** [comment]
fixed
