### ISSUE TITLE
[CORE] Can't Join BG as a Group (XFaction)

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1851]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Crossfaction groups can't join rbg together
 
![image](https://github.com/user-attachments/assets/bb90e1e8-6e38-4c8b-b351-2ecd48804382)

**How to reproduce:**

**How it should work:** We should be able to join rbg together

**Database links:**

**Comment by WhitemaneChronus** [comment]
it's not about crossfaction, you are trying to queue with someone who has their xp locked as the message says.
You cannot queue with twinks if you arent one.

**Comment by haephaistoss** [comment]
we were both lvl 80, I'm not a retard :D

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
