### ISSUE TITLE
Hand of sacrifice los 

### ISSUE THREAD

**Issue by reminuz** [gamefreedomgit/Frostmourne#1852]
I don't take damage from hand of sacrifice when i'm in los.

### Expected Blizzlike Behaviour

I should take damage from hand of sacrifice when i'm in los.

### Source

https://www.wowhead.com/wotlk/spell=6940/hand-of-sacrifice#comments
https://www.youtube.com/watch?v=zUpBrGJEP_s 
You can see it at 9.45.

### Steps to reproduce the problem

I cast Hand of protection on party members
He goes in los and he tanks some mobs.
I don't take any damage.

**Comment by haephaistoss** [comment]
Can you check all similar effects? Like Soul Link and Divine Sac? They kinda work on the same principle

**Comment by haephaistoss** [comment]
Just tested in Arena, Dsac doesn't work either

**Comment by Afgann** [comment]
fixed
