### ISSUE TITLE
AotD taunting raid bosses

### ISSUE THREAD

**Issue by Alexc7700** [gamefreedomgit/Frostmourne#1853]
I was told that this issue was already considered fixed a while ago but I encountered it again.

Description:
Army of the dead taunting raid bosses. 

How to reproduce:
I was in a raid today  and used the spell "Army of the dead" and the boss wasn't immune to the pets taunts. The raid in this case was VoA.
To reproduce just use the spell in a raid boss fight.

How it should work:
Raid bosses should be immune to the AotD pets taunts.

Database links:
https://wowwiki-archive.fandom.com/wiki/Army_of_the_Dead

**Comment by Piootrek** [comment]
It works correctly, do you have any video or screenshot?

**Comment by Alexc7700** [comment]
Unfortunately no, but from what i heard also in the global chat apparently AotD and druid trents have the same problem.
If it happens again i'll try to get a screenshot or a video

**Comment by Alexc7700** [comment]
I had the chance to do another raid and voa again and this time worked perfectly fine.
Thank you and sorry for the bother.
