### ISSUE TITLE
Earthliving Weapon on Offhand not proccing

### ISSUE THREAD

**Issue by Karsenity** [gamefreedomgit/Frostmourne#1854]
**Description:**
Earthliving weapon is not proccing when used on OH weapons

**How to reproduce:**
Spec into dual wield in the Enhancement tree and put Earthliving Weapon on your OH, then start spamming heals

**How it should work:**
Earthliving Weapon should be able to proc off the OH weapon. Additionally, the hot it applies should be separate from the one applied by the MH (i.e. you can have 2 instances of Earthliving rolling at the same time)

**Database links:**
Logs from Wotlk Classic displaying this behavior: https://classic.warcraftlogs.com/reports/Wj4ydcxbKLpCvknP#fight=49&type=healing&source=61

**Comment by scrublama** [comment]
it is downranked 4 and rank 5

**Comment by scrublama** [comment]
in the logs its downranked rank 4 and rank 5, is that what u tried?

**Comment by scrublama** [comment]
in the logs its downranked rank 5 and rank 6, is that what u tried?

**Comment by Karsenity** [comment]
> in the logs its downranked rank 5 and rank 6, is that what u tried?

Yes, which is what lead me to the realization the ticket is about: it just doesn't apply at all from an OH weapon. If you unequip your MH and heal, it just won't proc

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
