### ISSUE TITLE
AoTD doesn't attack in bg

### ISSUE THREAD

**Issue by danniellos94** [gamefreedomgit/Frostmourne#1855]
**Description:**
Army of the dead just doesn't attack in battleground.

**How to reproduce:**
Use army on bg see it doesn't attack.

**How it should work:**
Army should attack enemies on battleground. Not sure what is causing the issue but maybe a crossfaction?

**Database links:**
https://www.wowhead.com/wotlk/spell=42650/army-of-the-dead

**Comment by UltraNix** [comment]
@danniellos94 Do you have any video here?

**Comment by Piootrek** [comment]
Fixed, I will fix this issue once the fix comes live.
