### ISSUE TITLE
Druids can't get past certain doors in Naxx?

### ISSUE THREAD

**Issue by gugovgeorgi** [gamefreedomgit/Frostmourne#1856]
**Description:**
Druids are getting stuck at certain doors:

- **Exit from Saph**
https://www.twitch.tv/iumruk/clip/SneakyTrustworthyCardMikeHogu-o7T35uVyn9JYBoPR
- **Entrance to Arachnid Quarter**
https://www.twitch.tv/iumruk/clip/ColorfulTangentialClipzNotATK-aDQEWTLOuAB1z2vZ

(possibly others (?), experienced only these two)

_P.S. The Arachnid one seemed passable with quite a bit of fidgeting around... Still one of the druids was unable to get through_

**How to reproduce:**
No idea... Bring a druid into Naxx? Someone in the raid suggested it might have something to do with KT Mind Control, no idea if it is related

**How it should work:**
Being able to get past the door, like the rest of the raid

**Comment by gugovgeorgi** [comment]
Seems second clip is broken, and I am unable to re-clip it, gives me the same error ("Failed to determine content classification")...
The second impassable door appears at around 1:33:20 in this video: https://www.twitch.tv/videos/2246815172

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
