### ISSUE TITLE
Teleporting Trolls at Conquest Hold

### ISSUE THREAD

**Issue by Zeehra** [gamefreedomgit/Frostmourne#1857]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I've just landed at Conquest Hold by flightpath from Dalaran, and the second I landed, I was attacked by a Drakkari Warrior and a Drakkari Shaman, who both just hung around the Hold for no appearant reason. When trying to run from them, they just teleported after me - and the guards did nothing. It might be the caged trolls that are used for the pit fights, but they are absolutely not as caged as they should be.

**How to reproduce:**
Go to Conquest Hold in Grizzly Hills.

**How it should work:**
The trolls should be in cages, and not attacking at random - and the guards should be defending the player.

**Database links:**
https://imgur.com/a/SIy0nn7

https://www.wowhead.com/wotlk/npc=26447/drakkari-shaman
https://www.wowhead.com/wotlk/npc=26425/drakkari-warrior

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
