### ISSUE TITLE
[DK] Runic Focus shouldn't affect Death Coil Heal

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1858]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Currently runic focus affects the healing portion of death coil when used on friendly undead targets, causing critical heals to be 200 % of non critical heals.

**How to reproduce:** Cast Death Coil on a friendly target

**How it should work:** Death Coil critical heals should be 150 % of the original non crit amount, runic focus should only affect damaging spells.

**Database links:**   https://www.wowhead.com/wotlk/spell=61455/runic-focus
https://www.wowhead.com/wotlk/spell=49895/death-coil

https://www.warcraftmovies.com/movieview.php?id=160059
3:32 - crit healing with mortal 20% - 3754
3:40 - non crit heal without mortal 20% - 3129/3128
3128 * 0,8 * 1,5 = ~3754

5:10 - crit healing - 5724, non crit - 3815
5724/3815 = 1,5

**Comment by Afgann** [comment]
fixed
