### ISSUE TITLE
[DK] Death Grip no effect

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1859]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** DG is cast, nothing happens, the enemy player isn't teleported, or flown to the DK.
https://medal.tv/games/world-of-warcraft/clips/iELDpqaC1Wrzd3V9y/d1337NNYPUVN?invite=cr-MSxYbEYsMTUxNjU2MjYs

**How to reproduce:** Cast DG on enemy player(s)

**How it should work:** Death groip should have an effect

**Database links:** https://www.wowhead.com/wotlk/spell=49576/death-grip

**Comment by Riztazz** [comment]
fixed, server will be updated soon
