### ISSUE TITLE
Elemental Focus

### ISSUE THREAD

**Issue by tankpajzl** [gamefreedomgit/Frostmourne#1860]
https://wowwiki-archive.fandom.com/wiki/Elemental_Focus

Not procing from HW and LHW crits, its small bug but still...

[Patch 3.0.2](https://wowwiki-archive.fandom.com/wiki/Patch_3.0.2) (14-Oct-2008): Now also can proc off Lesser Healing Wave and Healing Wave, and can be used on all healing spells.

**Comment by Piootrek** [comment]
Apparently it's not correct. The tooltip clearly says it should proc only from damage spells, same with Wowhead comments. Also I watched a few videos from 3.3.5 wotlk and didn't see a single proc from healing spells. I don't know why it was in a patch notes tho. Closing.
