### ISSUE TITLE
Faerie Fire+Curse of Elements stacking bug

### ISSUE THREAD

**Issue by tankpajzl** [gamefreedomgit/Frostmourne#1861]
Hi, 
i tried to play lock+resto druid in arenas and its rly unplayable with this critical bug.
U cant simply apply Faerie Fire on target with Curse of Elements because it says 'more powerful spell is on target' so u can't add additional magic debuff for dispels. Rly hard to play vs War Pal (because u cant cover sedduction when have warrior curse debuff .) or any rogue setups. 
Please fix this as soon is possible. Thank you

https://wotlk.evowow.com/?spell=770
https://wotlk.evowow.com/?spell=47865

**Comment by Piootrek** [comment]
I cannot reproduce. Can you post a screenshot of your and druid talents?
