### ISSUE TITLE
Lay on Hands doesn't transfer to beacon of light

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#1862]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Currently on live server, if you lay on hands a target, the heal does not transfer to your assigned beacon of light target.

**How to reproduce:**
Lay on hands X while your beacon is on Y, Y will receive 0 heals from beacon.

**How it should work:**
Until patch 4.0.6 Lay on Hands heal should be transferred to beacon of light target.
Probably unintentional spaghetti from the recent beacon fix though.
In case extra proof needed: https://youtu.be/GbWCalzGvVg?si=0BfTCSpzFbbPVIse&t=283
4:48 timemark you can see 2 heals at same time when lay is casted over 100k - one is lay target, the other is beacon transfer.

**Database links:**
https://wowwiki-archive.fandom.com/wiki/Patch_4.0.6

**Comment by Afgann** [comment]
fixed
