### ISSUE TITLE
DK - Death and Decay 

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1863]
Death Knight Spell [Death and Decay](https://www.wowhead.com/wotlk/spell=43265/death-and-decay) currently scales dynamically with AP and Player's percentage damage modifiers.
While it is blizzlike that it should scale dynamically with the casting player's percentage damage modifiers, **but it should snapshot AP on cast.**

This is currently noticable through testing it without Procs and then getting AP procs afterwards.
1.Cast dnd
2.proc greatness + fallen crusader + unbreakable armor + horn of winter
3.notice how the damage actually goes up instead of staying the same.

Easily noticable through warcraftlogs how unless the DnD tick is critting or being resisted, the damage each tick is doing is the same because **It is scaling dynamically with Percentage damage modifiers on the player, but it is snapshotting the caster's melee attack power on cast success.**
https://classic.warcraftlogs.com/reports/g9h1zLyAtDjf7rX4#fight=20&type=damage-done&view=events&source=19&target=129&ability=52212
![image](https://github.com/user-attachments/assets/f83d5075-d42e-4359-9f48-26e4b3bdceca)

despite losing uptime on FC/Sigil the damage tick remains the same because the amount of AP snapshotted on cast is the same.

**Comment by haephaistoss** [comment]
It's classic log, so take it with a grain of salt.

Also note, that the paladin ability consecration should recalculate each tick dynamically - according to og wrath, so if they currently work in a similar manner, and this is found to be the case in og wrath too (which is totally likely), consecration and maybe some other effects shouldn't be affected by fixing this ability.

**Comment by Manpower99** [comment]
There is absolutely no difference between Death and Decay in og or classic with the reference being 3.3
i did not report things like consecration or explosive trap because they are supposed to be updating dynamically, so there are no issue with those on whitemane.
even on the Dk discords it was fully confirmed to be blizzlike that it should function as i reported.
![image](https://github.com/user-attachments/assets/43d3488c-d409-4e34-b840-0b0e273b5adc)
Even on og cata and cata classic it functions similarly except the addition of Mastery.

https://www.youtube.com/watch?v=T29OvMtU6wo

**Comment by haephaistoss** [comment]
I mean in terms of serverside handling - to not cause spaghetthi code shenanigans, like spellsteal and HoSac

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
