### ISSUE TITLE
[Rogue] Envenom buff when overkill a target

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#1864]
**Description:**
Envenom gives you a buff for 1 sec + 1 additional sec per combo point to increase your chance to apply poisons etc.
If you overkill a target with Envenom, no matter how many combo points you have, you get the Envenom buff only for 1-2 seconds instead of 1 + 1 per combo point.

**How to reproduce:**
Make combo points to a target, get it low hp, then overkill it with Envenom (overkill = Envenom damage has to be higher than current target health)

**How it should work:**
The Envenom buff should get 1 + 1 additional sec per combo point every time, no matter if you overkill the target.
I tested in both Pve and Pvp and it's the same bug.

**Database links:**
https://youtu.be/Lf5J7nIwbL8?si=wAB1xeczAVU1E-A9&t=56 this is the only video I found where the rogue killed the warrior with Envenom and you can see he got 6 sec of Envenom buff.

**Comment by Riztazz** [comment]
fixed, will close once it's live
