### ISSUE TITLE
[MPG] Yogg constrictor vs iceblock

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#1866]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
On live Iceblock did not remove constrictor today when mage tried it, on PTR it did(for the same guy).

**How to reproduce:**
Use mage iceblock while constricted.

**How it should work:**
Should despawn constrictor, remove squeeze debuff, player should move freely.

**Database links:**

**Comment by Manpower99** [comment]
Noticed it too, some things seem to be fixed on live but not ptr and some are fixed on 25 but not 10. will try to make more bug reports after live release.

**Comment by Afgann** [comment]
fixed
