### ISSUE TITLE
Bug en Cuerno Negro 10 modo heroico

### ISSUE THREAD

**Issue by Crisyangod** [gamefreedomgit/Frostmourne#1867]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

https://www.wowhead.com/es/npc=150002/maestro-de-guerra-cuerno-negro

**Description:**

Cuando empiezas el encuentro, haces la mecánica normal, sin embargo hoy mi guild y yo nos percatamos que al ingresar un zapador y morir (wipe) al siguiente try el zapador no hace daño al barco. No es la primera vez que nos ha pasado, sin embargo no teníamos noción de cómo se realizaba, sin embargo después de un par de wipes uno se da cuenta. Cabe resaltar que lo hablé con un gm ingame, el mismo respondió que lo reporte aquí, y no se bien cómo hacerlo, usarlo o si lo estoy haciendo bien.

**How to reproduce:**
Entra el zapador al barco, se wipea y luego al siguiente intento el zapador no hace daño.

**How it should work:**

Debería siempre hacer daño y no existir ese bug.
 
**Database links:**

**Comment by Riztazz** [comment]
This is wotlk bugtracker, closing
