### ISSUE TITLE
Ulduar - Flame Leviathan and Mimiron's Inferno

### ISSUE THREAD

**Issue by Nessy27** [gamefreedomgit/Frostmourne#1868]
**Description:**
The devices on top of FL are taking damage from Mimiron's Inferno (spell id 62910). Specifically, the Flame Leviathan Seat that the launched people sit in while on top of FL are dying and kicking them out. I'm not sure what happens if the people get launched again when these are dead (our people died when they were kicked out so we never launched them again in the same attempt), but I am guessing they just miss. Also check the devices Leviathan Defense Turret and Overload Control Device taking damage.

**How to reproduce:**
Drag FL through Mimiron's Inferno. After the devices take 10 ticks from the fire, they die. The seats will kick anyone out (and prevent people from getting launched on?).

**How it should work:**
Whatever devices on top of FL (and pyrite/everything else?) shouldn't be taking Mimiron's Inferno damage. Only the raid and vehicles should take damage.

**Database links:**
Flame Leviathan Seat https://wotlk.evowow.com/?npc=33114
Leviathan Defense Turret https://wotlk.evowow.com/?npc=33142
Overload Control Device https://wotlk.evowow.com/?npc=33143

9/10 18:19:30.360  SPELL_AURA_APPLIED,0xF13000825A8646B4,"Mimiron's Inferno",0xa48,0xF15000815A85EB95,"Flame Leviathan Seat",0xa18,62910,"Mimiron's Inferno",0x4,BUFF
9/10 18:19:30.457  SPELL_PERIODIC_DAMAGE,0xF13000825A8646B4,"Mimiron's Inferno",0xa48,0xF15000815A85EB98,"Flame Leviathan Seat",0xa18,62910,"Mimiron's Inferno",0x4,1260,0,4,0,0,0,nil,nil,nil

9/10 18:19:34.387  SPELL_PERIODIC_DAMAGE,0xF13000825A864698,"Mimiron's Inferno",0xa48,0xF130008176864610,"Leviathan Defense Turret",0xa48,62910,"Mimiron's Inferno",0x4,6401,0,4,0,0,0,nil,nil,nil
9/10 18:19:34.391  SPELL_PERIODIC_DAMAGE,0xF13000825A864698,"Mimiron's Inferno",0xa48,0xF130008177864611,"Overload Control Device",0xa18,62910,"Mimiron's Inferno",0x4,535,0,4,0,0,0,nil,nil,nil

**Comment by Afgann** [comment]
fixed
