### ISSUE TITLE
Unresponsive mobs

### ISSUE THREAD

**Issue by Savageferret** [gamefreedomgit/Frostmourne#187]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Randomly, mobs in an area will randomly go unresponsive, unable to path or attack, but able to receive damage and put you in combat. I say area, because if I bring my hunter pet into the affected area, my pet gets stuck is unable to path out. Only by relogging do the mobs in the area become normal. This has happened in different zones at different times of day.

Game objects in the area seem affected. In the replay below, I interact with a game object, receive the loot, but the game object doesn't despawn.

https://streamable.com/q5s0zo the start shows gameplay / looting a game object as normal, then 20 seconds in you can see the unresponsive mobs / game object

**Comment by Godmatik** [comment]
Confirmed, noticed it in southern Mulgore

**Comment by Savageferret** [comment]
@Afgann this is still happening, I have no idea what's causing it. It's happened a couple times today & yesterday in the barrens. My pet will get stuck, mobs will get stuck, but I can still attack and kill them. It fixes itself after ~30 seconds, so mobs that I've attack will come to me, pet follows me, etc

**Comment by Savageferret** [comment]
https://streamable.com/rtfmw9

**Comment by Afgann** [comment]
@Savageferret does the pet get stuck while chasing a target? or during follow?

**Comment by Savageferret** [comment]
Pet or mobs get totally stuck, no following / attacking / patrolling

updated video links, shouldnt expire anymore. In both videos, before the recording starts, I'm running to next quest with pet on follow, bug happens, pet gets totally stuck. I continue running til it despawns, then 'Call Pet' as shown:
https://streamable.com/s9p908
https://streamable.com/wooi0n

**Comment by Afgann** [comment]
fixed
