### ISSUE TITLE
[Live Mimiron's Playground Ulduar25] Yogg Diminish power still stuck on people inside portals

### ISSUE THREAD

**Issue by gforghieri** [gamefreedomgit/Frostmourne#1870]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

[Live Mimiron's Playground Ulduar25] Diminish power still stuck on people inside portals

Diminish power debuff is still stuck in people inside portals, tested yesterday on live mimiron's playground.

Related reports, supposed to be fixed but its not.

https://github.com/gamefreedomgit/Frostmourne/issues/1785
https://github.com/gamefreedomgit/Frostmourne/issues/1743

**Comment by Afgann** [comment]
fixed
