### ISSUE TITLE
Cant jump up ruins of lordaeron tomb sides

### ISSUE THREAD

**Issue by vurtne77** [gamefreedomgit/Frostmourne#1872]
Description: well since server mostly follows wotlk classic , on it u can jump ruins on lordaeron tomb sides like you can jump it and continue forward on top of the tomb and here its not working like that u cant jump it at all

How to reproduce:
try jumping the tomb sides and it doesnt work 

How it should work:  should be able to jump it and get on top of the tomb in the ruins of lordaeron

Database links: got a link of a record that i cut from hydra stream on wotlk classic ( if uneed more  i can provide ofc )
https://www.youtube.com/watch?v=LKp8zcv_UBY&ab_channel=ZerkQGaming

**Comment by UltraNix** [comment]
Nothing we can do about it. It's different model/textures of this tomb.
