### ISSUE TITLE
Dirkee dies to other mobs when spawned next to the cave.

### ISSUE THREAD

**Issue by Ghanris** [gamefreedomgit/Frostmourne#1873]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Dirkee (rare mob in Storm Peaks) gets aggro'ed and killed by other mobs.

**How to reproduce:**
Spawn Dirkee on PTR, check if he aggroes.

**How it should work:**
He should be neutral.

**Database links:**
https://imgur.com/a/AuzXRm8
https://www.wowhead.com/wotlk/npc=32500/dirkee

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
