### ISSUE TITLE
[PoW] Stormjewels missing from Vendors

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1874]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Stormjewels were introduced in 3.1 content as unique-equipped items. They should be made available to PoW characters when they are released to non-pow chars

**How to reproduce:**

**How it should work:**

**Database links:**  https://www.wowhead.com/wotlk/item=46007/bag-of-fishing-treasures#contains;0-20+17+1;q=Stormjewel

reference: https://github.com/gamefreedomgit/Frostmourne/issues/1621

**Comment by yeagerca** [comment]
Please make Stormjewels available to real characters too, thanks 👍 #1621

**Comment by haephaistoss** [comment]
works like a charm, thanks
