### ISSUE TITLE
Bounty Hunter achievement bug

### ISSUE THREAD

**Issue by pedroazor** [gamefreedomgit/Frostmourne#1876]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I just completed the achievement "The Bounty Hunter" and got the title, but i don't receive the mount. It is not in my bags either mailbox either in "Mounts".

**How to reproduce:**

**How it should work:**
I should receive title and mount.

**Database links:**
![prueba](https://github.com/user-attachments/assets/f1b83a7b-a5a7-4f9c-a1b1-dc1bb3d583b8)

**Comment by Afgann** [comment]
fixed
