### ISSUE TITLE
Leash range of mobs / daze / loot mechanics.

### ISSUE THREAD

**Issue by Selot1234** [gamefreedomgit/Frostmourne#1877]
hey, couple things:

**Sources:**
https://www.youtube.com/watch?v=5QoK7K7Or8A
https://www.youtube.com/watch?v=kqaBnv7E0ws
![image](https://github.com/user-attachments/assets/a30f9804-b7a3-49ce-a3c8-946c1f467753)

1. The range of which hostile mobs can follow a player that pulled them should be increased. In OG wotlk they could follow you forever if you kept close range to them or kept damaging them. Notice how this guy is pulling 30+ mobs and they keep following him without losing aggro. Also comment i linked from youtube proves that to be the case.
On Frostmourne server the "leash" range seems very small, somewhere around 20-30 yards.

2. Daze effect. Currently there's really high chance you get dazed if mobs are hitting you. when you pull 5+ mobs you have 100% uptime of daze. Again i refer to two previously linked vids. Notice how the guy has 30+ mobs on him for over minute and don't get dazed once. I assume it be either that mobs that are considered grey level (more than 10 level gap) cannot daze player, OR in general this mechanics happens very rarely in PVE environment

3. AOE looting bugs out in party + FFA loot. it just does not work. If player A (group master) kills several mobs, and Player B wants to loot them, then player B needs to loot them one by one. I attach video showcasing this: https://streamable.com/9eqbb0

**Comment by sputnikk** [comment]
2. Daze immunity mechanic probably doesn't work on private servers need to be tested.
This vid explains it: https://www.youtube.com/watch?v=WDOeqM-wGcI
The formula should be (Mob level*5)+100 for daze immunity.
Needless to say chance for daze should also be gradually reduced the more defense u have vs mobs level(wep skill), that probably doesn't exist either.
Pretty easy to test since def capped tanks should technically never get dazed. Also needs research since i know daze immunity was 100% a thing in tbc don't know yet if it was changed in wrath.

**Comment by Manpower99** [comment]
Dont know if they should make "leash" work as blizzard intended since it does introduce issues. worth to note that it is only direct damage to extends the leash on Blizzard servers, not thorns/retri aura, damage shield etc.
But you are 100% correct on Daze, and also AoE loot being extremely buggy. it is simply better at this moment to kill mobs one by one than kill multiple mobs then aoe loot them.

**Comment by Riztazz** [comment]
Fixed daze, leashing should already work with non-dot damage, can someone check?
Seperate issue for aoe looting please

**Comment by Riztazz** [comment]
It's spaghetti code that prevents this really, not abuse ;p I will take a look at dots and leash

**Comment by Riztazz** [comment]
Fixed the leash, the issue was something unrelated to thorns, will close once it's live

**Comment by Riztazz** [comment]
Ok everything has been fixed and implemented, seperate issue about aoe loot please as it's unrelated to other two. closing

**Comment by Selot1234** [comment]
@Riztazz hey after last update (2.10.2024 2pm) leash range is completely broken, please see attached vid. Mobs are deaggroing from 20-25 yards, it's way too low. Also damaging them with consecration does not make them stay. :( :( pls revert changes
https://streamable.com/dek1nm

**Comment by Selot1234** [comment]
The purpose of ticket was to make aoe farming more blizzlike, now it's scuffed :sadpepe:
1. Initial leash range before any extending mechanics should be somewhere around 60-80yds. This is math based on how much you can move as prot pally in 8 seconds period when you are waiting for consecration to come up with CD. This is how it worked on vids i posted from 2008.
2. dunno about this "dot" damage not extending leash range, can you show your source? @Manpower99
```
worth to note that it is only direct damage to extends the leash on Blizzard servers, not thorns/retri aura, damage shield etc.
```
Where you get that from? On links i provided from 2008 you can clearly see abilities like consecration / Demoralizing Roar / swipe are extending leash range. Consecration can be considered DOT damage I suppose?

Also what about all those locks powerleveling with dots from classic?:
https://www.youtube.com/watch?v=XCSPYsPShD4&ab_channel=xray1337
All they are doing here is just putting corru (dot) and moving to next mob, so pretty sure DOT damage is extending leash range as well.

Thx for fixing daze, i'm yet to check it

**Comment by Riztazz** [comment]
I've only fixed a logic typo that seemed like "thorns" effect which in reality was infinite leash, always.
There is something else broken somewhere and now it manifests itself. From the video i can see that the mobs are much lower level than you.
The initial implementation of leash is by @Afgann and he made it level based, for lower levels the leash radius is probably very small hence the evades

**Comment by Manpower99** [comment]
You can check every asmongold video where they were extending leashes and dragging world bosses into cities, it was only through direct hits from offensive abilities and melee attacks. putting/applying corruption on a target is considered an offensive ability, the damage itself is a dot. if you wish to implement it from thorns and dots thats your choice.
https://www.youtube.com/watch?v=ByZx6IDLxFs&t=4s 
https://www.youtube.com/watch?v=xnrUkbEbiJk Refer to the Hostile Action part.

**Comment by Riztazz** [comment]
Alright, i stand corrected on a few topics, in the initial issue the thorns you guys were describing is not thorns, it's a standstill mechanic thing you can observe on linked videos. I've pushed a commit, it will work like it's supposed to after an update
