### ISSUE TITLE
Emalon not dropping correct emblems after death

### ISSUE THREAD

**Issue by hunturd69** [gamefreedomgit/Frostmourne#1879]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

**How to reproduce:**

**How it should work:**
Emalon should give 2x emblem of conquest instead of 2x valor after death 

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
