### ISSUE TITLE
Grobbulus slimes AoE is only 30 yards

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#188]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
the fallout slimes spawned by grobbulus only damage players within 30 yards with disease cloud.

**How to reproduce:**

**How it should work:**
In retail it was 10 yds but since the buffs are based on frosthold, it should be raidwide.

**Database links:**
https://archive.ph/6tylD

**Comment by Afgann** [comment]
fixed
