### ISSUE TITLE
Teron Gorefiend, I am... event doesnt start

### ISSUE THREAD

**Issue by Lemmy-90** [gamefreedomgit/Frostmourne#1880]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Quest Teron Gorefiend, I am is supposed to start an event after picking up the quest. The event doesn't start to kill Karsius the Ancient Watcher, only the untargetable mobs spawn. 

**How to reproduce:**
Pick up the quest "Teron Gorefiend, I am..." from "Ancient Shadowmoon Spirit" in Shadowmoon Valley. 

**How it should work:**
An event to kill an elite mob is supposed to start after you get "possessed" by Teron to kill Karsius the Ancient Watcher

**Database links:**
How quest is supposed to work 
https://www.youtube.com/watch?v=Mg_nO9yG00U&t=2s
How it is currently working
![2](https://github.com/user-attachments/assets/090bf9ba-c835-458c-ad50-fe8c89e9cbaf)

**Comment by WhitemaneChronus** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/1235

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
