### ISSUE TITLE
Missing Stormjewels from fishing bags and Tiny Titanium Lockbox

### ISSUE THREAD

**Issue by ItsPope** [gamefreedomgit/Frostmourne#1881]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Stormjewels do not drop from the [Bag of Fishing Treasures] or the [Tiny Titanium Lockbox], even though they were added with the release of the Ulduar patch 3.1 [1, 2].

(There is an abandoned PTR thread on this, but this report concerns the live version. Hopefully, this will draw some attention to the issue, as the PTR version seems to have been ignored. It doesn’t appear to be a difficult change.)

**How to reproduce:**

Open a fishing bag and observe that Stormjewels do not drop. Based on Wowhead droprates, the chance for **any** Stormjewel to drop should be 2.11%, meaning they should drop approximately once in every 48 bags [3].

**How it should work:**

Stormjewels should drop from the [Bag of Fishing Treasures] and the [Tiny Titanium Lockbox] with droprates ranging from 0.1% to 0.6% (according to Wowhead [3, 4]), as they were added in patch 3.1 (Ulduar) according to Wowpedia [1, 2].

**Database links:**

Wowpedia - when were they introduced:

When were they introduced:
[1] https://wowpedia.fandom.com/wiki/Bag_of_Fishing_Treasures_(Dalaran)
[2] https://wowpedia.fandom.com/wiki/Tiny_Titanium_Lockbox

Droprates from wowhead
Fishing Bags
[3] https://www.wowhead.com/wotlk/item=46007/bag-of-fishing-treasures#contains;q=Stormjewel
Tiny Titanium Lockbox
[4] https://www.wowhead.com/wotlk/item=45986/tiny-titanium-lockbox#contains;q=Stormjewel

**Comment by UltraNix** [comment]
#1621
