### ISSUE TITLE
penence is bugged 

### ISSUE THREAD

**Issue by vurtne77** [gamefreedomgit/Frostmourne#1882]
**Description:** penence last tick heal doesnt work ( completely canceled ) on melee / range hits instead of applying pushback mechanic

**How to reproduce:** use penence while getting any dmg and u wont get heals from the last tick ( should be 3 total )

**How it should work: penence should always heal u with 3 ticks anyway except if u are kicked or silenced , when u are hit by spells or melee hits it should just apply pushback but never cancel any tick

**Database links:**https://www.youtube.com/watch?v=lVT64oOosjQ&ab_channel=ZerkQGaming  u can see from the addon '' mike's scrolling battle text that im getting only 2 tick heals from it and 3rd one doesnt happel

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by vurtne77** [comment]
@Piootrek ur link isnt from WOTLK idk man , penance never worked like this ever

**Comment by Piootrek** [comment]
Provide proof please

**Comment by Piootrek** [comment]
No answer for 2 weeks, closing.
