### ISSUE TITLE
Conquest daily (the normal one) 

### ISSUE THREAD

**Issue by Tupso** [gamefreedomgit/Frostmourne#1883]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I picked up yesterday the daily quest (the 1 emblem one) when it already gave conquest emblem on the quest description, I completed it and I delivered it today morning cause I forgot to do it in the night. It have given me 1x[Valor Emblem] instead of 1x[Conquest emblem]

Evidence: https://imgur.com/a/zcQz4rC

![WoWScrnShot_091424_104311](https://github.com/user-attachments/assets/982a8718-c6d0-4f4f-80d4-75ba17be91f0)

**How to reproduce:**
Pick up the daily quest and complete it

**How it should work:**
It should give conquest instead of valor, but it gave me valor

**Database links:**

**Comment by Valx27** [comment]
I have exactly the same issue, if i go to totake the daily hero quest it will show conquest as reward, but when i take it the reward change to valor

**Comment by Afgann** [comment]
fixed
