### ISSUE TITLE
Casting totems before a respawn bugs the NPC

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1884]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

If you cast totems before a npc respawn, no matter if its a boss or not they keep despawn/respawning and will bug out.
examples are arena quests putting totems down near where the mob should spawn after taking the quest, will results in npc not spawning or disappearing. 
We recently had an issue with general vezax in Ulduar keeps respawning due to totems.

**How to reproduce:**

Take quests such as The Amphitheater of Anguish: Tuskarrmageddon! and put totems down near where NPC should spawn before you start the event.

**How it should work:**

NPCs should still appear despite totems being there.

**Database links:**

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
