### ISSUE TITLE
Meele range vs Ability range

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#1885]
**Description:**
There is a desynchronization between meele range and ability range. You can autoattack, but you can't use abilities in a certain range and mobs can attack you as well. You can see in the screenshot:
![WoWScrnShot_091424_192321](https://github.com/user-attachments/assets/889d18a8-b07b-4355-9515-007d896a7ee5)

**How to reproduce:**
Attack a mob and backpaddle until you can't use abilities but still autoattack.

**How it should work:**
Meele range and abilities range should have the same value.

**Comment by UltraNix** [comment]
@oneadanut It will be better to record this one and explain in details.
What ability we are talking about? What desynchro - you mean some delay?

**Comment by oneadanut** [comment]
You can see all my meele abilities Blood Strike, Frost Strike, Plague Strike, Obliterate are in red because I'm too far away from mob, but still my auto attacks go through and damage the mob, also the mob can attack me

**Comment by oneadanut** [comment]
@UltraNix It seems fixed after today's restart.

**Comment by oneadanut** [comment]
https://github.com/user-attachments/assets/dab3194c-2ff2-4c37-9f63-9b02044023b1

**Comment by Riztazz** [comment]
It is some obscure client code that i cannot figure out, i am un-assigning myself for now, but it works on most models, it doesn't on Shadow Revenant, it seems the geomodels are offset in client? When i'm moving on Z axis a little bit (jump), im suddenly in reach for the client

**Comment by oneadanut** [comment]
It happens also on Dragonflayer Deathseeker mob in Utgarde Pinnacle. This is the first mob where I found the issue.

**Comment by haephaistoss** [comment]
> It is some obscure client code that i cannot figure out, i am un-assigning myself for now, but it works on most models, it doesn't on Shadow Revenant, it seems the geomodels for this model have some offset? When i'm moving on Z axis a little bit (jump), im suddenly in range

That's because of leeway i suppose
