### ISSUE TITLE
[Warrior] [Arms] Recklessness and Juggernaut Interaction

### ISSUE THREAD

**Issue by JJGodX** [gamefreedomgit/Frostmourne#1888]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
[Warrior] [Arms] When using **Recklessness** and **Juggernaut** together, there's an odd interaction that prevents Mortal Strike or Slam from always landing a critical hit.

- If Mortal Strike or Slam lands a crit, it consumes one Recklessness stack and the Juggernaut buff.
- If Mortal Strike or Slam does not crit, it only consumes the Juggernaut buff and ignores Recklessness entirely.

**How to reproduce:**
To test this, activate Juggernaut talent and cast Recklessness, Charge at a target, and cast Mortal Strike or Slam. Repeat until you observe both a crit and a non-crit.

**How it should work:**
Mortal Strike or Slam should **always** use one Recklessness stack and **guarantee** a crit, even if the Juggernaut buff is active.
https://youtu.be/l2aXYmkyDQI?si=Dj5L8wnc6XNH8G1C&t=375 **6:15**
https://youtu.be/9YBxx0GiRuM?si=lzeH2veFJG5sEvOn&t=243 **4:03**
https://youtu.be/9YBxx0GiRuM?si=1ZgpWcf0IP9u_Hht&t=541 **9:01**
https://youtu.be/rLogPe0SkEg?si=XRxYUwVb-zBW-7q-&t=442 **7:22**
https://youtu.be/rLogPe0SkEg?si=sQdQo6-7AY0rSNrM&t=485 **8:05**
I couldn't find any example where this wasn't the case.

**Database links:**
https://www.wowhead.com/wotlk/spell=1719/recklessness
https://www.wowhead.com/wotlk/spell=64976/juggernaut

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
