### ISSUE TITLE
Faerlina doesn't cast frenzy

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#189]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
In our ptr raid about a week ago, faerlina went 80 seconds without casting frenzy after the last widow's embrace ran out. The same happened in a different run i saw a video of.

**How to reproduce:**

**How it should work:**
I haven't looked up videos from retail/sunwell but when widow's embrace runs out, i believe she should cast frenzy after approx. 5-10 sec if it's off cooldown.

**Database links:**
for evidence, see this stream from about 12 minutes, 35 seconds in, and 16 minutes 20 seconds in, respectively.
edit: forgot the link
https://www.twitch.tv/videos/2060870622

**Comment by Godmatik** [comment]
Did you have multiple widow's embrace stacked? I think doing so extends the timer of it, unsure if that is intended though.

**Comment by NickZedd** [comment]
just one embrace at a time, and it was too far into the encounter for any of them to be up anyway. I believe we tried stacking two of them at the beginning of the first pull, but it doesn't work on this server. Also not sure if that's how it should work or not.

**Comment by Afgann** [comment]
fixed
