### ISSUE TITLE
Emalon has wrong loot table

### ISSUE THREAD

**Issue by Shineslippers** [gamefreedomgit/Frostmourne#1890]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Emalon dropped 2 PvP items in VoA10

**How to reproduce:**
Kill it alot of times

**How it should work:**
As every other VoA boss it should drop 50/50 PvE/PvP

**Comment by Shineslippers** [comment]
Все еще не работает. Плащей быть не должно.
![Снимок](https://github.com/user-attachments/assets/84974801-4e6f-4b07-a0ff-8c4ed39cf665)

**Comment by Afgann** [comment]
fixed
