### ISSUE TITLE
Chains of Ice BUG

### ISSUE THREAD

**Issue by tankpajzl** [gamefreedomgit/Frostmourne#1894]
Please can u fix https://wotlk.evowow.com/?spell=45524 ?
its rly critical pvp bug, if enemy have freedom or any immune slow effect, chains dont apply frost fever dot diseas. It just say immune and no effect. Thank you

**Comment by haephaistoss** [comment]
#1406

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
