### ISSUE TITLE
Portal : Thunder Bluff not autolearned

### ISSUE THREAD

**Issue by snurfisbugged** [gamefreedomgit/Frostmourne#1897]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

Hi , 

As title says, i did not learned automatically the spell "Portal : Thunder Bluff"at my 40th level. I've learned all others portals automatically.

**How to reproduce:**

Level-up a mage past level 40, and see you don't learn it along all the others portals. Teleport to NPC "Brigitte Cranston" (ID : 5957)
You can buy the spell at level 40. 

Link and Screen :

https://wotlk.evowow.com/?npc=5957

![portal TB](https://github.com/user-attachments/assets/ea598ee4-e567-4613-9839-a2b312a12cbe)

**Comment by Piootrek** [comment]
Spell is correctly auto-learned at level 50, npc required 40lvl incorrectly.
Fixed, I will close this issue once the fix comes live.
