### ISSUE TITLE
Argent Tournament

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1898]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Supposed to be introduced in patch 3.1 alongside Ulduar.

**How to reproduce:**

**How it should work:**
Players should be able to help efforts to construct the Crusaders' Coliseum.

**Database links:**
https://wowpedia.fandom.com/wiki/Argent_Tournament

**Comment by RadeghostWM** [comment]
Already here
