### ISSUE TITLE
[PTR] HC algalon accessible immediately

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#1899]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
the door to Heroic algalon, and the boss itself, can be accessed with a completely fresh character on the PTR if you add the key. Clearing the raid is not required, even though the character has no achievements.

The boss also stays spawned if you open the door on normal mode and switch to heroic after.

**How it should work:**
It should not be possible to open the door on heroic difficulty without killing every boss on heroic difficulty in the same ID.

Also, if algalon has been spawned, and the difficulty is changed to heroic without every other heroic boss having been killed, algalon should despawn. 

Source: 
Ulduar announcement on discord and replies by Radeghost in the frostmourne channel.
![image](https://github.com/user-attachments/assets/d724aa64-9eb6-43f4-bdd7-d35006200984)

![image](https://github.com/user-attachments/assets/9c2ac6c7-6e4d-4c33-b626-1dee397d4ccd)

![image](https://github.com/user-attachments/assets/f0cca09c-7c04-434c-9b75-7ea6793da401)

![image](https://github.com/user-attachments/assets/9a9ed2f6-40db-49c4-9f14-6ecdec42a436)

**Comment by Afgann** [comment]
You can open the door, but you can't aggro the boss unless all other bosses are killed on heroic, he will despawn.

**Comment by NickZedd** [comment]
@Afgann okay that's a good way to do it, but he currently doesn't though. You can kill him on a fresh character in a fresh raid.
https://www.youtube.com/watch?v=S6XPxTCY8UQ

**Comment by Afgann** [comment]
Alright, i'll recheck it.

**Comment by Afgann** [comment]
fixed
