### ISSUE TITLE
[PTR] Vezax hardmode not forced on heroic

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#1900]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Vezax can be killed on heroic difficulty before the animus spawns.

**How it should work:**
Hardmodes should be forced on heroic difficulty.

**Personal suggestion:** 
Make the animus spawn if the boss gets to [x] amount of health, so we don't have to sit around waiting for it.

**Source:** 
Radeghost messages in frostmourne chat

![image](https://github.com/user-attachments/assets/163e4403-0288-4225-ae77-0710a076355d)

PS: We need official information regarding forced hardmodes and hc bosses being locked until you kill other hc bosses.

**Comment by Afgann** [comment]
fixed
