### ISSUE TITLE
Alchemy - Mixology inconsistencies

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#1903]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Most mixology stat bonuses are affected by a server decimal approximation error that approximates to the lower number instead of the higher one, resulting in -1 of that stat from the mixology bonus. Most flasks/elixirs I've tested are affected by this error **except for Frost Wyrm and Stoneblood which give correct bonus exactly.**
This is related to mixology specifically and not character stats having hidden decimals leading to lower end calculation since this is affecting elixirs such as haste as well (which characters have 0 flat by default naked)

**How to reproduce:**
Pop flasks and elixirs on a naked character with mixology.

**How it should work:**
Frost Wyrm works correctly: 47sp bonus from mixology
Stoneblood works correctly: 650hp bonus from mixology
ENDLESS RAGE FLASK: 79 bonus ap (-1 from approx -2 from incorrect trinitycore info?) **should give 82 bonus ap**

**EVERY other flasks/elixirs I've tested in the game give -1 from the approximation error (distilled wisdom, mighty thoughts, lightning speed, etc)**
All of these were tested on PTR for reference.
**Database links:**
https://www.wow-professions.com/wotlk/wotlk-classic-profession-bonuses-perks

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
