### ISSUE TITLE
Flame Leviathan Vehicles - Unable to Kick Passengers

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1904]
Normally Drivers can kick their passengers by right clicking on their passenger in the vehicle Ui underneath minimap. Similarly should be able to do the same for multiple vehicles who have passenger seats.
Currently iam unable to kick the passengers.
Unsure if its addon related, as other players said they encountered the same issue so i assume it isn't an addon issue.

**Comment by Afgann** [comment]
fixed
