### ISSUE TITLE
Thorim-Starting Phase2 No RP Delay.

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1905]
After Finishing Gauntlet ( both 10 and 25 tested ) thorim prematurely goes down into the arena.
https://youtu.be/0UGCCqLi7F4?si=3Z_I_pwD-GZx0lAH&t=142
So far vods show he either he waits until someone damages him with a slight delay afterwards.
https://youtu.be/EoYM-iI0paE?si=ZkJSFCbrhq7Ad_yt&t=131
Warrior hits with heroic throw and after a roleplay event Thorim goes down.

**Comment by Afgann** [comment]
fixed
