### ISSUE TITLE
delete me

### ISSUE THREAD

**Issue by anticlutch** [gamefreedomgit/Frostmourne#1907]
not done

**Comment by Manpower99** [comment]
No it shouldn't, this is not cataclysm or any further expansion.
you're also referring to haste and this is a spell where haste only affects its GCD and not its tick frequency.

**Comment by anticlutch** [comment]
Had you read the sources you'd know it wasn't a Cataclysm addition.

**Comment by Manpower99** [comment]
oh trust me i did, and the same sources you linked are
1. Labeled as a bug in cataclysm and fixed already on their current live version on classic cataclysm
2. all are from 2010+ and explain how it worked in cata and wotlk and they THOROUGHLY explained the difference in both.
![image](https://github.com/user-attachments/assets/b4ef33ba-76a6-4ad3-b5c4-2c0688511c5e)
![image](https://github.com/user-attachments/assets/49110dc9-12a9-4419-b2a7-ae9ae590ef0c)
