### ISSUE TITLE
Ulduar Vezax shadow crash should not go in melee range

### ISSUE THREAD

**Issue by gforghieri** [gamefreedomgit/Frostmourne#1908]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

Ulduar Vezax shadow crash should not go in melee range

Please double check the range selection for this, sometimes it happens that melee hitting vezax on the outer edge of the melee hitbox get selected for sahdow crash. This should not happen.

Increase the range for this should be above 15y, counting from the edge of the melee hitbox, not the center of the boss.

**Comment by Manpower99** [comment]
Can confirm it on multiple pugs, it landed on melee despite not being below the 2/3 threshold outside of melee range.
unsure what causes it, potentially the range check for the melee being lower than it should be

**Comment by NickZedd** [comment]
Can also confirm. Happened to us in 10m today with 4 ranged dps outside.

**Comment by Afgann** [comment]
fixed
