### ISSUE TITLE
Ulduar Collapsing Star can fall through the floor

### ISSUE THREAD

**Issue by yeagerca** [gamefreedomgit/Frostmourne#1913]
**Description:**
Collapsing Stars can sometimes clip through the floor when moving randomly. This causes them to slowly fall until they naturally die. It's not clear if these stars still do damage when they die.

https://www.twitch.tv/pwongers/clip/CreativeSpotlessMage4Head-ShLXPOX5ymAVVWBF
The star that becomes marked with a skull can be seen falling in the linked clip.

**How to reproduce:**
Not sure.

**How it should work:**
Stars should only path horizontally.

**Database links:**
https://www.wowhead.com/wotlk/npc=32955/collapsing-star
https://www.wowhead.com/wotlk/npc=32871/algalon-the-observer

**Comment by Afgann** [comment]
fixed
