### ISSUE TITLE
Yogg - Squeeze + Portal

### ISSUE THREAD

**Issue by MarcioMatteucci** [gamefreedomgit/Frostmourne#1916]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

When the portals appear, at the same time a constricting tentacle appears, it usually happens that someone clicks on the portal and enters with the squeeze debuff and dies inside without being able to save it.

**How to reproduce:**
https://www.twitch.tv/kreiita/clip/WanderingPiercingDogDatBoi-1R__O6meRVVfJfXF

**Database links:**
https://www.wowhead.com/wotlk/npc=33983/constrictor-tentacle
https://www.wowhead.com/wotlk/spell=64126/squeeze

**Comment by Afgann** [comment]
fixed
