### ISSUE TITLE
Cyclone resets every DR

### ISSUE THREAD

**Issue by reminuz** [gamefreedomgit/Frostmourne#1917]
https://www.wowhead.com/wotlk/spell=33786/cyclone

**Description:**
Cyclone resets every DR.

**How to reproduce:**
Cast Seduction on a target.
Cast Cyclone.
Cast Seduction on the same target.
Both seduction are 9 sec cc.

**How it should work:**
Second seduction should be 5 sec, not 9 sec.

**Comment by Riztazz** [comment]
I cannot reproduce this, i'm getting properly DR'd seduction every time. any chance i could get a video?

**Comment by Riztazz** [comment]
Closing in a week if no proof provided
