### ISSUE TITLE
Flame Leviathan should gain the aura "Flame Vents" when channeling the spell

### ISSUE THREAD

**Issue by broizter** [gamefreedomgit/Frostmourne#1918]
While Flame Leviathan is channeling the spell "Flame Vents" he should get the aura with spell id 62396. This is important because it's needed by DBM to check for the the cast being interrupted by a siege engine.

Here is a link to the "official" DBM where you can see it tracks for the spell being removed.
https://github.com/DeadlyBossMods/DBM-WotLK/blob/da41c91c27439fc5021d77cb8e7d3f7be91b4ccd/DBM-Raids-WoTLK/Ulduar/FlameLeviathan.lua#L83

Link to the aura.
https://www.wowhead.com/wotlk/spell=62396/flame-vents

**Comment by Afgann** [comment]
Aura works fine from what i've tested, 62396 is a periodic channeled aura that triggers 63847 (spell that actually deals damage). If there was no aura then there wouldn't be any way to interrupt the spell, and it wouldn't be visible as a channeled cast.

**Comment by broizter** [comment]
You are 100% right. Error on my part. Closing.
