### ISSUE TITLE
Horn of Winter with glyph

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#1919]
**Description:**
Glyph of Horn of Winter increases the duration of your Horn of Winter by 1 minute resulting in 3 minutes.
If someone else from raid does Horn of Winter without glyph, it will override the glyphed one.

**How to reproduce:**
Make a party with 2 dks, 1 with glyph of horn of winter, 1 without.

**How it should work:**
Unglyphed horn of winter shouldn't override the glyphed one. It should let you do Horn of Winter but not applying the buff since 3 minutes is more powerful than 2 minutes.

**Comment by haephaistoss** [comment]
just gonna leave it here

https://github.com/gamefreedomgit/Frostmourne/issues/1498

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by oneadanut** [comment]
This bug is not fixed @Piootrek

**Comment by Piootrek** [comment]
Sorry, my bad. Will be fixed after the next server update.
