### ISSUE TITLE
Flame Leviathan pursuit same target

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#1920]
**Description:**
Flame Leviathan can pursuit the same target even 3-4 times in a row.

**How to reproduce:**
Do FL10 in 2 players, 2 vehicles

**How it should work:**
FL should choose another vehicle to pursuit, not the same one it was before.

**Database links:**
https://youtu.be/lCyZnr9CKE4

**Comment by Afgann** [comment]
fixed
