### ISSUE TITLE
[???] 204 Item Level AVG Char can't join SoloQ 

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1921]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Fully gemmed, enchanted, 204 avg item lvl char can't join soloQ because of not meeting 200 item level requirement.
Tried with everything, no idea what's going on.

Character the bug occured on: Baladrim

![image](https://github.com/user-attachments/assets/20ebf3d3-21f3-427e-bfc8-850db2bfd8f9)

![image](https://github.com/user-attachments/assets/b843800a-bb8d-4e0a-b298-9fbdad0f5b47)

![image](https://github.com/user-attachments/assets/9681a907-1e36-4c7b-a503-e24659b0395e)

![image](https://github.com/user-attachments/assets/f7501d02-c969-4505-81a6-1f59d7c9f2ba)

**How to reproduce:** no idea

**How it should work:** it should let toons with more than 200 itemlvl

**Database links:**

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by haephaistoss** [comment]
thanks! What was the issue tho? Just curious, I couldn't seem to find the cause
