### ISSUE TITLE
Dungeon : the culling of stratholme

### ISSUE THREAD

**Issue by Amine-x-x** [gamefreedomgit/Frostmourne#1923]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
You can use dk unholy pet to pull the infinite corruptor boss before starting arthas door roleplay that spawns 3 mobs to clear them , usable to bypass timer
----------
https://prnt.sc/tYTxcgnmHxBo
----------
**How to reproduce:**
Use dk pet at door near arthas roleplay starting point after clearing final boss from waves , then stand in the metal door and use /target infinit (to target the add boss) and send pet , when the pet take aggro , make it come to you (ctrl +2 or follow ability of pet)

**How it should work:**
I Mean,  the timer exist for a reason ,if you can bypass it with an easy bug to kill it after 20 seconds of it spawning, there is no point from a timer, maybe make boss immune to attacks (shows error cannot attack / or cannot be pulled) if you didn't clear the zone.

**Database links:**
https://www.wowhead.com/wotlk/npc=32273/infinite-corruptor

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
