### ISSUE TITLE
Players stuck on icecrown graveyard 

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1924]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Players getting teleported to spirit healer on graveyard-1407 are stuck and cannot move.
it might happen when they release spirit and get the flying mount in ghost form afterwards. we have several cases so far.
`Map: 571 (Northrend) Zone: 210 (Icecrown) Area: 4496 (Jotunheim) Phase: 1
X: 7148.598145 Y: 3705.807129 Z: 824.098450 Orientation: 4.990813
grid[45,38]cell[3,7] InstanceID: 0
ZoneX: 27.714703 ZoneY: 54.492912
GroundZ: 824.100037 FloorZ: 824.100037 Have height data (Map: 1 VMap: 1 MMap: 1)
MMAP Height: 824.45807`

**How to reproduce:**

release spirit / unstuck to the graveyard 

**How it should work:**

player shouldnt get stuck

**Database links:**

**Comment by Riztazz** [comment]
I cannot reproduce this :( Can you do .list auras next time it happens and ask players what quest they were doing just now? How they died? Were they on a mount?
