### ISSUE TITLE
Herald Volazj in Ahn'kahet

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1926]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

After the last restart, the clones on this boss are doing too much damage and wiping the group. even tanks are not surviving it.
It appears each auto is hitting for 4-6k.

**How to reproduce:**

pull the boss and let it spawn the clones

**How it should work:**

clones damage must be adjusted.

**Database links:**

**Comment by Afgann** [comment]
fixed
