### ISSUE TITLE
Swapping between NM and HC difficulty while inside ulduar

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#1928]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Swapping to normal and after to heroic inside ulduar caused all the raid members to get disconnected and when we reconnected we were in front of icecrown citadel.

**Comment by NickZedd** [comment]
Same thing happened to us when we swapped to heroic, but not the first time when we went from heroic to normal.

**Comment by Godmatik** [comment]
only happens on Normal to Heroic swap, not other way around

Can be bypassed if you are logged out while the swap happens

**Comment by MarcioMatteucci** [comment]
We couldn't swap the difficulty on any boss. I think after killing normal FL hm it doesn't let you swap anymore.

**Comment by sputnikk** [comment]
Today, the bug is still present when swapping to heroic. It still disconnects everyone but teleports you in front of ulduar instead of icc.

**Comment by oneadanut** [comment]
> Today, the bug is still present when swapping to heroic. It still disconnects everyone but teleports you in front of ulduar instead of icc.

I can confirm the bug, happened yesterday in ulduar10 @Afgann

**Comment by Afgann** [comment]
fixed
