### ISSUE TITLE
Missing items - Echoes of Titans vendor

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#1929]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

1.
On the new vendor in ulduar that exchanges echoes of the titans currency, there are a few wrong/missing items:
https://wotlk.evowow.com/?item=45857 is present on the vendor instead of https://wotlk.evowow.com/?item=46053
This makes no sense since the first item is just the key quest for algalon which gives no item while the second one is for the rings (reply code alpha drops from algalon)

2.
https://wotlk.evowow.com/?item=45135 - missing
https://wotlk.evowow.com/?item=45244 - missing
https://wotlk.evowow.com/?item=45607 - missing
https://wotlk.evowow.com/?item=45612 - missing
https://wotlk.evowow.com/?item=45613 - missing
https://wotlk.evowow.com/?item=45519 - missing

3.
Algalon items seem to be missing entirely so I presume that to be intended. Some items from 2. are shared between multiple bosses including Algalon, but they should be available on vendor since they don't drop exclusively from him.

**Comment by Afgann** [comment]
fixed
