### ISSUE TITLE
Ulduar Echo Drops+Emblems

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1931]
Bosses with forced HM should drop Echos afaik
Today it didnt drop on
25HC FL
25HC Vezax
10HC Vezax
Cannot confirm for any other boss but likely there are some which slipped through.
In addition to this, Iron Council is giving an emblem per boss kill (noticed it on small guy) but not at the encounter end, Meaning if you end up wiping after killing 1-2 bosses you can perma-farm Emblems of Conquest.

**Comment by Afgann** [comment]
fixed
