### ISSUE TITLE
Yogg 25 NM - Marked Immortal Guardian

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#1932]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
On Yogg 25NM ONLY (does not apply to heroic) the Immortal guardians targeted and affected by the shadow beacon should turn into a different NPC called "Marked Immortal guardian"
Should turn from this npc: https://wotlk.evowow.com/?npc=33988
Into this npc: https://wotlk.evowow.com/?npc=36064
And turn back into the normal "Immortal Guardian" after they are no longer affected by beacon. Of course they should keep their current hp while swapping between these two npc ids.

**How to reproduce:**
Reach yogg p3, shadow beaconed guardians stay the same.

**How it should work:**
Patch 3.2.0 (04-Aug-2009):
An Immortal Guardian targeted for Empowering Shadows http://www.wowhead.com/?spell=64486 in the Yogg-Saron encounter will now become a 'Marked Immortal Guardian' while targeted.

**Database links:**
https://wowwiki-archive.fandom.com/wiki/Immortal_Guardian
[Patch 3.2.0](https://wowwiki-archive.fandom.com/wiki/Patch_3.2.0) (04-Aug-2009):
An Immortal Guardian targeted for [Empowering Shadows](http://www.wowhead.com/?spell=64486) in the [Yogg-Saron](https://wowwiki-archive.fandom.com/wiki/Yogg-Saron_(tactics)) encounter will now become a 'Marked Immortal Guardian' while targeted.

**Comment by MarcioMatteucci** [comment]
3.2 Call of the Crusade Patch

**Comment by Godmatik** [comment]
That is when most of the nerfs happened, yes

Normal mode Ulduar is using all the post-nerf mechanics, while heroic is using the pre-nerf ones

**Comment by Afgann** [comment]
fixed
