### ISSUE TITLE
Yogg-Saron Brain Rooms All difficulties

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1933]
Brain rooms are currently set in stone in the same order, thus predictable every single pull.
Each 3 Rooms should be in a random order and not predictable like this unless its the last one within a set.
Last of 3 Rooms should be predictable like this of course, and then the set would be reset if you happen to need more than 3 rooms.
On this [Vod ](https://youtu.be/KDSfko0KxBE?si=L27YqiZZ_-WMpn1T)you can see
Icecrown Room > Stormwind Keep.
[Here ](https://www.youtube.com/watch?v=EQWITF63ucI)however it is different, its Aspect Chamber > Icecrown Room.
and [here](https://www.youtube.com/watch?v=ZIyjkblOssw)
its Stormwind Keep > Aspect Chamber

https://youtu.be/t5YWAZSCjBY?si=RbsrwGJ_PC6fg4Qt&t=15424 Long video, timestamped is one of their attempts
Icecrown Room>Stormwind Keep

In the same video previously https://youtu.be/t5YWAZSCjBY?si=DzEJQPnGI2C3KCZU&t=14712
Aspect Chamber >Icecrown Room.

Could just make it so its completely random but next 2 rooms you get wont be the same as the one you just got so it guarantees next 2 Rooms wont be the same but it is still randomized on the first 2 with the third one being predictable.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
