### ISSUE TITLE
Rare Spawn Loot Tables/Drop Rates wrong/incorrect?

### ISSUE THREAD

**Issue by SeraphTV** [gamefreedomgit/Frostmourne#1934]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

To prefice, I'm not sure if this is only an issue on Hardcore, or if this happens in regular as well. This might only be the case for Vanilla Rares. It's been talked about a lot in the hardcore guild about the loot tables of rare spawns not dropping items. Every rare spawn in the mid level zones are supposed to drop at least 1 guaranteed green or better item upon kill. I am currently level 53 in hardcore and have killed a TON of rare spawns so far. All of which, only seem to drop money. No actual items ever drop.

This doesn't seem to be the case for rare spawns that have a few items tied to them with non randomized items attached to their loot table. For example I've killed the the Wyvern Rare in Stone talon mountains 'Pride Wing Patriarch' twice and both time it dropped the green +5 agi cloak aka 'Webwing Cloak' as it's supposed to. Also the spider in the cave above Darkshire in Duskwood dropped the dagger as intended.

I've killed 2 rare spawns in Dustwallow Marsh in the last 24 hours. Both of which dropped money. The first was the Wind Serpent, Hayoc. That only dropped a silver. And the 2nd was Drogoth the Roamer, which only dropped 99 copper. These are both rares that are supposed to have a guaranteed green item drop. 

How to reproduce:
Kill any rare spawn with a randomized item loot table.
https://www.youtube.com/watch?v=SuX5_wxQl6I - A couple examples of 50+ rare spawns only dropping silver/cloth

I can continue to provide more examples if requested.

How it should work:
Guaranteed green item should be lootable upon killing a rare spawn when the level of that rare spawn is greater than or equal to 20.

**Database links:**

**Comment by Godmatik** [comment]
Yeah issue was reported months ago.

A full list of rare mobs missing loot is here:
https://github.com/gamefreedomgit/Frostmourne/issues/154

**Comment by UltraNix** [comment]
Duplicate.
