### ISSUE TITLE
Fire at Will! quest does not work

### ISSUE THREAD

**Issue by Lemmy-90** [gamefreedomgit/Frostmourne#1935]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Fire at Will! quest in Blade's Edge Mountains does not work correctly. Upon accepting the quest, the player should use the item given by the quest giver to control the Fel Cannon to shoot canon balls at Warp-Gate. The Fel Canon doesn't become controllable, and simply follows the player around like a summoned pet, and will eventually attack the player.

**How to reproduce:**
Pick up quest Fire at Will! from the quest giver and use the item "Naturalized Ammunition" on a Fel Canon

**How it should work:**
Fel Canon should become controllable as soon as the player uses the item on the canon, giving a special pet bar

**Database links:**
https://www.youtube.com/watch?v=-uYJygRbd1M

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
