### ISSUE TITLE
Wagner Hammerstrike

### ISSUE THREAD

**Issue by Aeradel** [gamefreedomgit/Frostmourne#1938]
Wagner Hammerstrike disappears - possibly killed - and does not respawn. I can see where he should respawn, but I can't see a corpse or anything to actually respawn or reset him.

He's not in his secondary spawn location either.

https://www.wowhead.com/npc=15011/wagner-hammerstrike

This makes the quest Honoring a Hero impossible to complete.

**Comment by Chaos-within** [comment]
Pretty certain the event ended, that's why he's gone.

**Comment by Aeradel** [comment]
> Pretty certain the event ended, that's why he's gone.

Brewfest?

**Comment by Chaos-within** [comment]
[Harvest Festival](https://www.wowhead.com/event=321/harvest-festival)

**Comment by Aeradel** [comment]
> [Harvest Festival](https://www.wowhead.com/event=321/harvest-festival)

I see, thank you. For whatever reason I thought this was a Brewfest quest.
