### ISSUE TITLE
Noth curse bug

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#194]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Noth no longer casts curse of the plaguebringer after he has teleported back from the balcony.

**How to reproduce:**

**How it should work:**

**Database links:**
teleports back at 1:49:46. Still no curse after 40 seconds when he dies.
https://www.twitch.tv/videos/2060870622

**Comment by Afgann** [comment]
fixed
