### ISSUE TITLE
[Quest] There and Back again! daily quest is missing

### ISSUE THREAD

**Issue by Chaos-within** [gamefreedomgit/Frostmourne#1940]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Should be able to do this quest daily to collect tokens.

**How to reproduce:**

**How it should work:**
Doesn't show as a daily quest on wowhead, but according to comments (from original WotLK) and the guide (from classic WotLK) it is something that should be able to be done daily.

**Database links:**
https://www.wowhead.com/wotlk/quest=11122/there-and-back-again
https://www.wowhead.com/wotlk/quest=11122/there-and-back-again#comments:id=848805
https://www.wowhead.com/wotlk/guide/brewfest-event-achievements#repeatable-quests

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
