### ISSUE TITLE
Ulduar XT 25M normal hardmode, Buff post-nerf tantrum damage (proof inside)

### ISSUE THREAD

**Issue by gforghieri** [gamefreedomgit/Frostmourne#1941]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

Ulduar XT 25M normal hardmode, Buff post-nerf tantrum damage (proof inside)

**its doing too little damage at the moment.** makes the fight a joke

The damage should be percentage based, the post-nerf is 

![image](https://github.com/user-attachments/assets/22b38bca-637b-4ed2-877d-367ceb9cf51c)

![image](https://github.com/user-attachments/assets/1d7a9ce0-e0f1-479e-8b86-eb5abd111014)

https://archive.is/6WwGI

**Comment by Manpower99** [comment]
The difference is noticable and likely due to multiple bugs
1.Tantrum duration on normal is noticably higher than 8seconds sometimes (debuff on players but not the cast) 
2.Tantrum should be health percentage based physical damage not reducable by armor, it is likely being reduced by armor in normal mode atm.
3.In 25HC it is ignoring every form of damage reduction including Divine Sacrifice etc. while this was kept as a "feature" despite being a bug it is not blizzlike.

@Afgann

**Comment by Nessy27** [comment]
On Monday (NA) the tantrum for 25 normal hardmode was doing 10% hp per tick to me. I had ~22600 hp at the time and it was doing 2261 without divine guardian and 1808 with divine guardian. Is that not working as described? I admit it feels extremely underwhelming to heal it, though.
![image](https://github.com/user-attachments/assets/3d6c039c-9f74-42ee-986b-802dbf50fe74)

**Comment by oomshroom** [comment]
> On Monday (NA) the tantrum for 25 normal hardmode was doing 10% hp per tick to me. I had ~22600 hp at the time and it was doing 2261 without divine guardian and 1808 with divine guardian. Is that not working as described? I admit it feels extremely underwhelming to heal it, though. ![image](https://private-user-images.githubusercontent.com/88573893/369598127-3d6c039c-9f74-42ee-986b-802dbf50fe74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MTkwNTAsIm5iZiI6MTcyNjkxODc1MCwicGF0aCI6Ii84ODU3Mzg5My8zNjk1OTgxMjctM2Q2YzAzOWMtOWY3NC00MmVlLTk4NmItODAyZGJmNTBmZTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDExMzkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMmVmMTMzYzBkYmUyOWFmOTAwZDVlNWMxMzdkMTRhYWEwZjY3Y2FhMjU5ODcyM2RiNzRlNTkwMDQzZDZhMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WtOngPOkD-Os763ZHJXKHNtlpYPOtmeknmspwC7rJW0)

It should get increased by the Heartbreak buff, but currently it seems not to.

**Comment by Afgann** [comment]
> The difference is noticable and likely due to multiple bugs 1.Tantrum duration on 25n/10n is noticably higher than 8seconds sometimes (debuff on players but not the cast) 2.Tantrum should be health percentage based physical damage not reducable by armor, it is likely being reduced by armor in 25n/10n atm. 3.In 25HC/10HC it is ignoring every form of damage reduction including Divine Sacrifice etc. while this was kept as a "feature" despite being a bug it is not blizzlike.
> 
> @Afgann

1. 8s aura duration (or 12s on heroic) is related to spell 62776, debuff on players is 62775, and it has 4s duration which is applied on every periodic tick when damage is dealt. You can see on old videos that it is the correct behavior (https://www.youtube.com/watch?v=Z6S4f2OS9Co around 2:20 for example, damage isn't dealt anymore but aura persists for a short time afterwards).

2. No it's not, it wasn't increased by Heartbreak buff as @oomshroom pointed out.

3. Will be fixed with next update.

**Comment by Manpower99** [comment]
> > The difference is noticable and likely due to multiple bugs 1.Tantrum duration on 25n/10n is noticably higher than 8seconds sometimes (debuff on players but not the cast) 2.Tantrum should be health percentage based physical damage not reducable by armor, it is likely being reduced by armor in 25n/10n atm. 3.In 25HC/10HC it is ignoring every form of damage reduction including Divine Sacrifice etc. while this was kept as a "feature" despite being a bug it is not blizzlike.
> > @Afgann
> 
> 1. 8s aura duration (or 12s on heroic) is related to spell 62776, debuff on players is 62775, and it has 4s duration which is applied on every periodic tick when damage is dealt. You can see on old videos that it is the correct behavior (https://www.youtube.com/watch?v=Z6S4f2OS9Co around 2:20 for example, damage isn't dealt anymore but aura persists for a short time afterwards).
> 2. No it's not, it wasn't increased by Heartbreak buff as @oomshroom pointed out.
> 3. Will be fixed with next update.

Thanks!

**Comment by Afgann** [comment]
fixed
