### ISSUE TITLE
Firethorn should only yield fire leaf

### ISSUE THREAD

**Issue by Karsenity** [gamefreedomgit/Frostmourne#1944]
**Description:**
Originally was looking at it on wowhead because droprate felt off, but apparently firethorn shouldn't be yielding fire seed at all. Wowhead comments from patch 3.0.3 talk about how they removed all uses for them and dropped them from the loot table.

![image](https://github.com/user-attachments/assets/75c1f2a2-d826-481c-9635-f600c7c54fb9)

**How it should work:**
Firethorn yields just Fire Leaf, not fire seed

**Database links:**
https://www.wowhead.com/wotlk/object=191303/firethorn#herbalism

**Comment by Karsenity** [comment]
While firethorn is no longer dropping fire seed, it now sometimes gives you no herb at all.

**Comment by Afgann** [comment]
fixed
