### ISSUE TITLE
Missing items POW deadly 213ilvl

### ISSUE THREAD

**Issue by Taicex** [gamefreedomgit/Frostmourne#1947]
**Description:** There are mising some items in the POW vendor Zom Bocom,who offers deadly pvp weapons(213ilvl) for honor points.Dk sigil,shamam totems,paladin librarms and druid relics.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by haephaistoss** [comment]
They are at the other one, for a r ena points and 700 rating

**Comment by Taicex** [comment]
> They are at the other one, for a r ena points and 700 rating

Wands are here for honor,so should be the others also

**Comment by haephaistoss** [comment]
I agree, just saying that if you want them, you can get them.

It's kinda bs that they are at 2 different vendors for different currencies, but at the very least, they are available

**Comment by Riztazz** [comment]
They are not missing. Some items are only visible to classes that can use that item, otherwise they are not shown in vendor list.
If you think some items are incorrectly marked, please tell me what class are you and which items you would like to see, then i can check if there are any issues.
Im not gonna disable that system, but maybe i should for deadly vendors? @RadeghostWM

**Comment by Taicex** [comment]
> They are not missing. Some items are only visible to classes that can use that item, otherwise they are not shown in vendor list. If you think some items are incorrectly marked, please tell me what class are you and which items you would like to see, then i can check if there are any issues. Im not gonna disable that system, but maybe i should for deadly vendors? @RadeghostWM

I am DK and i cant see my sigil,also i van some of the other items in he ither vendor,for arena points,but not here for honor

**Comment by Riztazz** [comment]
Ok, it's probably item classified wrongly :/ I will see what's up

**Comment by Riztazz** [comment]
You mean hatefuls?

**Comment by Riztazz** [comment]
> > They are not missing. Some items are only visible to classes that can use that item, otherwise they are not shown in vendor list. If you think some items are incorrectly marked, please tell me what class are you and which items you would like to see, then i can check if there are any issues. Im not gonna disable that system, but maybe i should for deadly vendors? @RadeghostWM
> 
> I am DK and i cant see my sigil,also i can some of the other items in he other vendor,for arena points,but not here for honor

do you mean hatefuls?
