### ISSUE TITLE
Companion Pets not counted correctly between characters

### ISSUE THREAD

**Issue by AgentMalice** [gamefreedomgit/Frostmourne#1949]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I have a strange disparity between the counting of my companion pets between characters.  On my main it counts 72 pets, but I actually have 73.  And on my alt it only counts 70.  The alt does not have Higher Learning achievement, but has access to that pet.

**How to reproduce:**
I got the disparity when I acquired a pet on my alt instead of the main character.  They are on the same account.

**How it should work:**
Shouldn't they share the same amount of pets?

**Database links:**
Main Character
![WoWScrnShot_092024_182253](https://github.com/user-attachments/assets/f22c3081-cc6d-4b7b-951c-ecc359a2b9db)

Alt Character
![WoWScrnShot_092024_182621](https://github.com/user-attachments/assets/1b945cc7-312f-4817-b739-644c12921081)

**Comment by Aeradel** [comment]
Are you able to find which pets are causing this?

**Comment by AgentMalice** [comment]
My main character has not counted the Pint-Sized Pink Pachyderm, but I see it in her collection and it is usable on that character.  She should be at 73 and not 72.

The alt character is missing Miniwing, Smolderweb Hatchling, and Worg Pup.  Those three are given as items from 3 different quests that I completed on the main character.

Miniwing- https://www.wowhead.com/wotlk/item=31760/miniwing
Smolderweb Hatchling- https://www.wowhead.com/wotlk/item=12529/smolderweb-carrier
Worg Pup- https://www.wowhead.com/wotlk/quest=4729/kiblers-exotic-pets

**Comment by Afgann** [comment]
fixed
