### ISSUE TITLE
Malygos begins channeling Surge of Power immediately after warning the target

### ISSUE THREAD

**Issue by oomshroom** [gamefreedomgit/Frostmourne#195]
"<139.05 18:25:47> [CHAT_MSG_RAID_BOSS_EMOTE] Malygos fixes his eyes on you!#Malygos###Oomshroom##0#0##0#477##0#", -- [252]
"<139.65 18:25:47> [CLEU] SPELL_PERIODIC_DAMAGE[CONDENSED]#0xF1300070BB0C9E4A#Malygos#2 Targets#60936#Surge of Power", -- [262]

^ That's from current PTR. 0.6 seconds from warning to damage.

[here (5:53)](https://youtu.be/CDZDZWiS-dw?t=353) you can see that upon warning the player (Malygos fixes his eyes on you!), Malygos begins casting a 2.5s "Surge of Power" before the actual damaging channel. On the PTR he does not do the 2.5s cast and instead begins channeling immediately.

**Comment by Afgann** [comment]
fixed
