### ISSUE TITLE
[PALADIN] Hand of Reckoning shouldn't dmg Players

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1956]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Hand of Reckoning should not deal dmg to players, currently it does

![image](https://github.com/user-attachments/assets/2394563e-5906-4b14-89b4-26f9c14114b6)

**How to reproduce:** Cast Hand of Reckoning on an enemy player

**How it should work:** Hand of Reckoning should not deal dmg to players, it should make them get in combat, and stand up while drinking or eating in pvp. 

**Database links:** https://www.wowhead.com/wotlk/spell=67485/hand-of-reckoning https://www.wowhead.com/wotlk/spell=62124/hand-of-reckoning

**Comment by Afgann** [comment]
fixed
