### ISSUE TITLE
[PALADIN] Sacred Shield Proc on Last Second and Absorbed Dmg Not Working

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1957]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Easier to explain as  a series of events:
Currently how it works:

Target A with sacred shield takes dmg,
Target A gets the absorption pshield part,
The 6 second ICD is triggered.
The shield holds, dmg is not enough to detroy it completely.
THe 6 seconds have elapsed
target A takes dmg, 
the shield from the previous trigger absorbs the dmg.
With the ICD spent, and the dmg absorbed, a new shield is not triggered, until 'new' non absorbed dmg is taken.
This is wrong behavior.

**How to reproduce:**

**How it should work:** 

Target A with sacred shield takes dmg,
The 6 second ICD has been triggered,
the absorption shield part is applied onto Target A.
The shield holds, dmg is not enough to detroy it completely.
THe 6 seconds have elapsed
target A takes dmg, 
the shield from the previous trigger absorbs the dmg.
With the ICD spent, and the dmg absorbed, a new 6 second ICD is started, then a new shield is applied.

https://www.warcraftmovies.com/movieview.php?id=115963

1:19     player has dots on him, sacred shield is on him, all the dmg he takes is absorbed, yet sacred shield is refreshed to full duration once the icd has elapsed.

1:26   - again, last tick of forst fever refreshed the shield

![image](https://github.com/user-attachments/assets/71368d0c-fc88-4832-93b6-b80654f0a2a4)

It should be possible for an untalented sacred shield to keep procing onto itself on icd if dmg is taken in the very last portion of the buff, so the target actually takes no dmg, it is all absorbed.

**Database links:** https://www.wowhead.com/wotlk/spell=53601/sacred-shield#comments

(Another example of taking dmg including absorbed dmg too - unless specific proof to the contrary exists.)

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by haephaistoss** [comment]
that was quick af, thanks
