### ISSUE TITLE
Freya phase 2 nature bombs has a slight randomness on heroic difficulty

### ISSUE THREAD

**Issue by broizter** [gamefreedomgit/Frostmourne#1958]
On normal freya, including hardmode, the nature bombs in p2 are on a very consistent timer making it easy to create a DBM timer for it. But when switching over to heroic mode there is suddenly a variance of up to multiple seconds between how often she throws nature bombs.

**Comment by broizter** [comment]
I saw that a fix was pushed to the server and it seems like things have improved, although there is still a variance of up to almost 2 seconds.

```
11.07
11.87
10.74
11.98
11.38
10.85
11.18
10.55
10.3
10.84
11.07
11.71
11.38
11.29
11.74
```

**Comment by broizter** [comment]
I just compared to normal version of the boss and the variance is about the same. So maybe it's considered normal.

```
16.301
17.331
15.891
15.811
15.5695
15.0601
17.2301
17.3301
17.1501
17.4801
16.8701
15.6201
```

**Comment by Afgann** [comment]
fixed
