### ISSUE TITLE
QoL totem not granted if bags full

### ISSUE THREAD

**Issue by Aeradel** [gamefreedomgit/Frostmourne#1961]
The QoL totem - the one that is granted to shamans at the beginning of their leveling journey and allows them to use all 4 totem element types - is not rewarded to players with full bags. It makes sense that this doesn't happen, but the issue is that it should be mailed to them if their bags are full. Otherwise, they are severely lacking. I have only seen reports of this happening with HC characters, but this is likely because they are more likely to have their bags full by the granting level than someone that isn't HC.

**Comment by Riztazz** [comment]
fixed, will close once it's live
