### ISSUE TITLE
Ahn'kahet - Herald Volazj twisted visage

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#1962]
**Description:**
Twisted visage mobs on last boss in Ahn'kahet are doing too much damage, I think someone implemented this damage for Ascended dungeon, but It copied to the normal dungeon as well? **It should be fixed asap since today's daily heroic quest is Ahn'kahet.**

**Database links:**
All those meele damages are from Twisted Visage mobs.
![WoWScrnShot_092324_130831](https://github.com/user-attachments/assets/ca5d1aa7-e524-4d94-b599-2af3981523a7)

**Comment by Manpower99** [comment]
Yeah they are hitting way too hard and often using incorrect spells for their spec.
example : feral hardcasting wrath nonstop while in cat form which hits way too hard
0 delay between casts so very spammable. usually theres a 100-200ms between casts.

**Comment by Piootrek** [comment]
They will now mimic player melee damage, you can unequip weapons to minimize the damage.  I will close this issue once the fix comes live.
