### ISSUE TITLE
Mage - Permanent Water Elemental stays after respec/login

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1963]
Minor issue that i noticed recently.
Have a mage with Spec2 Frost with Water elemental talent+glyph to make it remain permanent as a pet.
Respec into Spec1 Fire, Log off and Login, Water elemental stays as a permanent pet.
Mounting/Dismounting/Going into different zone dismisses the pet so i assume there are checks to dismiss the pet there, but if you login infront of bosses you could abuse this.

**Comment by Piootrek** [comment]
Hey, I cannot reproduce this. Can you post screenshots of your talents in both specs?
