### ISSUE TITLE
Herald Volazj

### ISSUE THREAD

**Issue by Aeradel** [gamefreedomgit/Frostmourne#1964]
Herald Volazj occasionally becomes untargettable and unkillable and around half health. I have not tested the exact reasoning as to why he does this, but I have received <4 tickets about this issue this/last week.

**Comment by Riztazz** [comment]
Does he have insanity visual? any screenshot, a video maybe?

**Comment by Aeradel** [comment]
I will try my best to gather footage of it happening again. Unfortunately it's a bit of a rare bug. 

He doesn't seem to have anything out of the ordinary. Just like his normal self, but he doesn't attack nor can he be attacked. He just follows.

**Comment by Riztazz** [comment]
My guess is maybe second insanity is happening while he is under insanity, but i've tried reproducing this and nothing, always looks ok. Need some clues, a vid would help a lot :P

**Comment by Aeradel** [comment]
> Does he have insanity visual? any screenshot, a video maybe?

Happened again, it was exactly this.

I have a video, but it's just him casting insanity - so nothing really interesting. It has sensitive information I can't share publicly, but I will share the video if you reach out via Discord. My username is the same as my name.

**Comment by Riztazz** [comment]
Pushed possible fix, let's see if it happens again
