### ISSUE TITLE
pvp battlemaster trinkets on alliance requires rating

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1965]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Currently battlemaster trinkets on alliance requires 62k points and 1450 rating 
![Screenshot 2024-09-23 142323](https://github.com/user-attachments/assets/1e629d1f-1508-46ac-bc77-956948edbbe4)
however on horde side same trinkets require 49.6k points without rating.
![Screenshot 2024-09-23 142533](https://github.com/user-attachments/assets/27baa931-6711-471b-bd4c-5a16f27e1329)

**Comment by haephaistoss** [comment]
item prices and requirements are all over the place rn :(

**Comment by Riztazz** [comment]
@WhitemaneChronus Is this on POW or just regular?

**Comment by Riztazz** [comment]
fixed, will close once it's live

**Comment by Riztazz** [comment]
New season, new issues :) I'll update for new season trinkets
