### ISSUE TITLE
[Ulduar] Brain of Yogg-Saron Hitbox & Charge/Intercept Pathing 

### ISSUE THREAD

**Issue by JJGodX** [gamefreedomgit/Frostmourne#1967]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When using Warrior's Charge or Intercept on Yogg-Saron's Brain, your character's pathing leads upward into the air above the brain. After falling to the floor, you are positioned outside the melee hitbox and must move forward to engage the brain.

**How to reproduce:**
1. Teleport to Yogg-Saron's Brain room with a warrior.
2. Use Charge or Intercept on the brain.
3. Observe the pathing behavior.

**How it should work:**
The Charge and Intercept pathing should follow the floor level, bringing you directly into the brain's melee hitbox, allowing for immediate damage.

**Database links:**
https://www.wowhead.com/wotlk/npc=33890/brain-of-yogg-saron
https://www.wowhead.com/wotlk/spell=11578/charge
https://www.wowhead.com/wotlk/spell=20252/intercept

**Comment by Manpower99** [comment]
Similar issue using a spell such as killing spree.
https://youtu.be/jnnu5Waet68?si=ohvB4BT9tNoUihYh&t=219
Vod on classic of rogue using killing spree and not being shot up the air like it works on this server, same issue with Warrior Charge + Druid Feral Charge.

**Comment by Piootrek** [comment]
Fixed, I will close this once the fix comes live.
