### ISSUE TITLE
[Theramore] Combat Dummy Immune to Bleed Damage

### ISSUE THREAD

**Issue by JJGodX** [gamefreedomgit/Frostmourne#1968]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Theramore Combat Dummies are immune to bleed damage such as Rend, Deep Wounds, and Blood Frenzy, making them unsuitable for damage testing with certain classes.

**How to reproduce:**
1. Teleport to Theramore and go to the Theramore Combat Dummies outside the Foothold Citadel.
2. Apply a bleed effect and observe the "immune" reaction.

**How it should work:**
Theramore Combat Dummies should not be immune to bleed effects.

**Database links:**
https://www.wowhead.com/wotlk/npc=4952/theramore-combat-dummy

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
