### ISSUE TITLE
Grizzly Hills Quests

### ISSUE THREAD

**Issue by ArnEmp** [gamefreedomgit/Frostmourne#1972]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The quest items Grizzly Flank or Succulent Venison  have a very low drop chance.

**How to reproduce:**

**How it should work:** The drop rate should be higher

**Database links:**
https://www.wowhead.com/wotlk/item=37200/grizzly-flank
https://www.wowhead.com/wotlk/item=37200/grizzly-flank

Other quests with drop rates like this should be checked, probably.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
