### ISSUE TITLE
There and back again! fixed incorrectly

### ISSUE THREAD

**Issue by Karsenity** [gamefreedomgit/Frostmourne#1973]
**Description:**
The one-time quest was made daily instead of the followup.

The initial quest appears to be a one-time turn-in for 10 tokens. He should then have a dialogue option every 18 hours allowing you to help out again, which when used will put you back on the ram and allow you to run additional kegs for 2 tokens each. Additionally, each keg turned in should increase the duration of the ram by 30 seconds. 

Alongside WoWhead comments, I've included a guide someone made from MoP that explains all these behaviors.
![image](https://github.com/user-attachments/assets/9bb24cfc-b6f8-4ad6-bfa9-b80d8f939c2c)
![image](https://github.com/user-attachments/assets/ff825771-5a23-45f8-8f59-f3e4d89268c8)
![image](https://github.com/user-attachments/assets/95a7b627-16dd-43fd-b484-d00ef1db7864)

https://youtu.be/b3AL0FqhKMc?si=HXDD55xSNtgEsPcv&t=574

**How it should work:**

- Dialogue option every 18 hours
- 2 tokens per keg
- Ram duration extended 30 seconds per keg

**Database links:**
Comments from - https://www.wowhead.com/wotlk/quest=11122/there-and-back-again#comments

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
