### ISSUE TITLE
Catch the Wild Wolpertinger! missing

### ISSUE THREAD

**Issue by Karsenity** [gamefreedomgit/Frostmourne#1974]
**Description:**
The quest "Catch the Wild Wolpertinger!" is missing from Brewfest. It should be offered by Goldark Snipehunter

**Database links:**
https://www.wowhead.com/wotlk/quest=11117/catch-the-wild-wolpertinger#comments

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes alive.

**Comment by WhitemaneChronus** [comment]
players can complete the quest but are unable to turn in, it has happened on both alliance and horde side.

**Comment by Piootrek** [comment]
Will be fixed after server update.

**Comment by disruption01** [comment]
I have the quest but can't deliver

![image](https://github.com/user-attachments/assets/f809d657-6049-44f2-87e2-dab480b26c58)

**Comment by Piootrek** [comment]
Server wasn't updated with the fix yet
