### ISSUE TITLE
Proof of Demise

### ISSUE THREAD

**Issue by Aeradel** [gamefreedomgit/Frostmourne#1975]
Proof of Demise quests are not always rewarding the quest item necessary, even when the proper conditions are met.

Anub'arak and Azjol-Nerub are the two biggest troublemakers.

**Comment by Piootrek** [comment]
The quest item from Anub'arak wasn't properly autolooted after killing the boss. Players still could open the boss and manually loot it, but probably they didn't notice that. Checked other quest items from Proof of Demise quests and they work correctly. This one got fixed.

**Comment by oneadanut** [comment]
> The quest item from Anub'arak wasn't properly autolooted after killing the boss. Players still could open the boss and manually loot it, but probably they didn't notice that. Checked other quest items from Proof of Demise quests and they work correctly. This one got fixed.

you might wanna check Utgarde Keep, i always had to loot quest item there

**Comment by Piootrek** [comment]
> > The quest item from Anub'arak wasn't properly autolooted after killing the boss. Players still could open the boss and manually loot it, but probably they didn't notice that. Checked other quest items from Proof of Demise quests and they work correctly. This one got fixed.
> 
> you might wanna check Utgarde Keep, i always had to loot quest item there

You're right, I skipped this one by mistake. Fixed :smile:
