### ISSUE TITLE
Anvil of Titans

### ISSUE THREAD

**Issue by Barogor** [gamefreedomgit/Frostmourne#1976]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** The item [Anvil of Titans](https://www.wowhead.com/wotlk/item=44914/anvil-of-titans) uses the wrong spell, incorrectly it uses the spell from [Coren's Chromium Coaster](https://www.wowhead.com/wotlk/item=49074/corens-chromium-coaster) and [Mirror of Truth](https://www.wowhead.com/wotlk/item=40684/mirror-of-truth) but it should use this spell [Strength of the Titans](https://www.wowhead.com/wotlk/spell=62115/strength-of-the-titans).

https://www.wowhead.com/wotlk/item=44914/anvil-of-titans 
- https://www.wowhead.com/wotlk/spell=62115/strength-of-the-titans

https://www.wowhead.com/wotlk/item=40684/mirror-of-truth / https://www.wowhead.com/wotlk/item=49074/corens-chromium-coaster 
- https://www.wowhead.com/wotlk/spell=33648/reflection-of-torment

**Comment by Piootrek** [comment]
It uses good spell, check the proc trigger spell from Strength of the Titans  https://www.wowhead.com/wotlk/spell=62115/strength-of-the-titans
![image](https://github.com/user-attachments/assets/dacc2439-4108-4270-adc7-56cfb39a2680)
