### ISSUE TITLE
[QUEST] The Admiral Revealed – unobtainable after abandon

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#1978]
The quest [The Admiral Revealed](https://www.wowhead.com/wotlk/quest=12852/the-admiral-revealed#comments) is not avaialble again if the player ever abandons it, sicne it is provided by version of [Lord-Commander Arete](https://www.wowhead.com/wotlk/npc=29560/lord-commander-arete) that is spawned during the previous quest, and that quest is handed in to get The Admiral Revealed.
I suggest to add this quest, with the same prerequisites to his [version stationed in the Death's Rise camp](https://www.wowhead.com/wotlk/npc=29344/lord-commander-arete). Otherwise the player who abandons the quest and later wants to reaquire it has to either hope for some other player to do the quest or pester a GM over ticket.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
