### ISSUE TITLE
[QUEST] A Flawless Plan – available too late

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#1980]
[A Flawless Plan](https://www.wowhead.com/wotlk/quest=12823/a-flawless-plan) is available only after handing in [Know No Fear
](https://www.wowhead.com/wotlk/quest=12822/know-no-fear). It should be available at the same time. It is logical and if player hands in Know no Fear, for which they need to fly back to K3, nothing hints about the existence of A Flawless Plan quest, making it absolutely easy to miss without any outside sources or addons.

https://www.wowhead.com/wotlk/quest=12822/know-no-fear#comments:id=598905

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
