### ISSUE TITLE
Yogg Brain Room - Skulls randomization

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1981]
Currently skulls in Brain rooms are not randomized and at same location.
![image](https://github.com/user-attachments/assets/f6b793e9-bec0-41bb-a045-38a3e6bcffa3)

**Comment by Piootrek** [comment]
Fixed, I will close this once the fix comes live.

**Comment by jonathansbb** [comment]
Skulls are spawning on top of tentacles and dont disappear now once they are dead. just revert it, no need for this to be changed.

**Comment by jonathansbb** [comment]
or for the love of god, test this shit before you push it to the live server. Omega annoying.

**Comment by Manpower99** [comment]
@Piootrek 
Couple of bugs got introduced here
1. they spawn directly ontop of the Illusion Tentacles sometimes when they should be a lil be further from them if ever close. sometimes spawn very close to eachother and many time spawned inside the walls/pillars.
2. they dont despawn when all the illusion tentacles have been cleared in the room.

**Comment by Piootrek** [comment]
Fixed

**Comment by jonathansbb** [comment]
Skulls are still not despawning once room is cleared.

**Comment by Piootrek** [comment]
Server wasn't updated yet

**Comment by Manpower99** [comment]
@Piootrek Apologies for this, but i was trying to figure out why sanity on this server depletes at much faster rate than classic or retail and found a couple of reasons, some require their own bug reports but this one is specific to the Laughing Skulls specifically so i'm posting it here if thats okay.
Vods on retail and classic showcase a max of 3 skulls in each room, i believe the amount of skulls currently on live is higher than this. https://www.youtube.com/watch?v=Pf4MAONG1vs&t=450s OG wotlk video of ensidia you can see only 3 skulls floating in the air.
