### ISSUE TITLE
Skinning

### ISSUE THREAD

**Issue by Hunterwip** [gamefreedomgit/Frostmourne#1982]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Firemane Flamecallers and Firemane Scalebane mobs located in Dustwallow Marsh do not drop the respective leathers upon skinning,only give out trash loot.

**How to reproduce:**

**How it should work:**The respective mobs should drop Heavy and/or Thick Leather when skinned

**Database links:**

**Comment by Piootrek** [comment]
Firemane Scalebanes already have the correct loot, fixed it for Firemane Flamecallers. I'll close this issue once the fix comes live.
