### ISSUE TITLE
[Item][Profession] Can not replace head enchant with engineering enchant.

### ISSUE THREAD

**Issue by Zeehra** [gamefreedomgit/Frostmourne#1983]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I maxed out my engineering, and wanted to use the bis head enchant for tanks, "Mind Amplification Dish", instead of the "Arcanum of the Stalwart Protector" I had on before. However, I am not able to do so because "that item already has an activated ability". I'm not sure if this is because my headpiece is Weakness Spectralizers, that have their own use effect, but I should still be able to enchant them with the engineering enchant AFAIK.

**How to reproduce:**
Follow the steps described above.

**How it should work:**
I should be able to enchant my headpiece with my engineering enchant.

**Database links:**
https://imgur.com/a/6CfoTLe

https://www.wowhead.com/wotlk/item=50369/arcanum-of-the-stalwart-protector
https://www.wowhead.com/wotlk/spell=67839/mind-amplification-dish
https://www.wowhead.com/wotlk/item=42550/weakness-spectralizers

**Comment by Piootrek** [comment]
Hello, apparently it's blizzlike and it's not possible to apply tinker enchant as this item already has its own ability
