### ISSUE TITLE
Yogg-Saron Cooldown resets not working

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1984]
Every try of 10HC yogg0 tonight did not reset any of the cooldowns forcing a delay on progress by having to wait for cds.

-Unsure of its 10hc yogg0 only or every form of yogg-saron, but due to how vital some of the long cooldowns are for this bos, this serves as nothing but a headache.

**Comment by Godmatik** [comment]
25m same issue

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
