### ISSUE TITLE
[Ulduar] Yogg-Saron, Mimiron and Thorim doesn't reset CDs on wipe

### ISSUE THREAD

**Issue by Shineslippers** [gamefreedomgit/Frostmourne#1985]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Yogg-Saron, Mimiron and Thorim doesn't reset CDs on wipe

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
