### ISSUE TITLE
Oculus - Centrifuge Constructs

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1988]
Centrifuge Constructs still have few issues
they constantly activate/deactivate their energy link, the buff is constantly flickering. noticed similar issues in many NPC auras on this server.
and energy link is capped at 1 on each construct
Each construct alive should buff the other two by 1 instance of energy link
So if all 3 are alive then every construct would be buffed by the other 2. currently only one buff is active even if all 3 are alive.

https://www.youtube.com/watch?si=PP0DmpbuKmgDjUUN&t=561&v=PBQ0e1mLcoA&feature=youtu.be

**Comment by Piootrek** [comment]
Fixed, I will close this once the fix comes live.
