### ISSUE TITLE
[DK] Death Grip doesn't taunt if target is immune to forced movement mechanics

### ISSUE THREAD

**Issue by Cwiercpasiec** [gamefreedomgit/Frostmourne#1989]
**Description:**
Death Grip doesn't work on bosses. It doesn't move them, which is correct, but it also doesn't taunt them, which is a bug. 

**How to reproduce:**
Try to taunt boss with death grip.

**How it should work:**

Death Grip should taunt every tauntable enemy.
**Database links:**

**Comment by Riztazz** [comment]
Bosses usually are immune to taunt effect, can you show an example of a boss? So i can further investigate

**Comment by Manpower99** [comment]
If the target is immovable, he shouldnt be gripped, but the taunt forced attack debuff should force the NPC who would have been gripped to target the player who casted it.

**Comment by Cwiercpasiec** [comment]
Any 5man, Moorabi in Gundrak for example. Dark Command (DK taunt) works perfectly fine on him, Death Grip doesn't do anything. You don't even see Immune, all you get in combat log is You cast Death Grip at Moorabi, no further info. 
It should work as Manpower99 said. Shouldn't move boss, but should taunt it.
Also most bosses are tauntable, just a few are immune (vezax for example, or Patchwerk on some difficulties), so you should actually be able to reproduce it anywhere.

**Comment by Riztazz** [comment]
Sure, thanks, i'll debug a bit over the weekend

**Comment by oneadanut** [comment]
there is also another bug with it, if the mob has taunt debuff from another player (the 3 seconds one) and you do grip, it doesnt do anything

**Comment by Riztazz** [comment]
Fixed, will close once it's live
