### ISSUE TITLE
Azjol-Nerub Anub'arak - couple of issues

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1992]
1. Venomancers and Guardians should spawn 2 on Heroic instead of 1 like Normal Mode, once one reaches the other one comes also. [OG Proof](https://youtu.be/6tT2y1BvSao?si=BsCEORYyS6HEBHWn&t=161) [Classic Proof](https://youtu.be/imJXpj98BfU?si=Rj-edWQopMM3C1bY&t=948) [OG Proof 2](https://youtu.be/JyUcNMm4Bhw?si=XKvCW3cCp0BUeQRY&t=33)

2. There should be a 1s Grace Period when he emerges. [Classic Proof](https://youtu.be/imJXpj98BfU?si=HTb1pKUGxaxSFSu7&t=966) [OG Proof](https://youtu.be/6tT2y1BvSao?si=CsSLNDISGxlD07pt&t=61) [OG Proof 2](https://youtu.be/JyUcNMm4Bhw?si=yFLfeDY90rzrdjhJ&t=53)

3. When he casts submerge he should reset debuffs, but should remain attackable until he is truly burrowed. [Classic Proof](https://youtu.be/imJXpj98BfU?si=b1H9SZq2x5mc7pbW&t=907) [OG Proof](https://youtu.be/JyUcNMm4Bhw?si=F8oxgduRrkzqKKtP&t=66)

4. Cannot confirm if its an issue of wrong spell IDs or not, but often it feels pound's damage is lower than it should be on HC. [Damage taken Example](https://youtu.be/JyUcNMm4Bhw?si=F8oxgduRrkzqKKtP&t=66)
 [5N Spell ID](https://www.wowhead.com/wotlk/spell=53472/pound)
  [5HC Spell ID](https://www.wowhead.com/wotlk/spell=59433/pound)

**Comment by Afgann** [comment]
fixed
