### ISSUE TITLE
[There and Back Again] daily quest for brewfest not available since two days ago to pick up and complete.

### ISSUE THREAD

**Issue by anticlutch** [gamefreedomgit/Frostmourne#1993]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
https://wotlk.evowow.com/?quest=11122

**Description:**
The daily quest [There and Back Again] hasn't been able to be picked up multiple days in a row (Today would be the 3rd day for me). Missing me out on 40 brewfest coins per day (120 as of today). 

**How to reproduce:**
Go to the NPC Neill Ramstein (for alliance) and the quest isn't available. It was for the first many days of brewfest and then disappeared. I've spoken to multiple other people who are experiencing this big.

**Comment by Chaos-within** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/1973

**Comment by Riztazz** [comment]
I am gonna close this, while i know this is an issue, it has been fixed. The server sadly has not yet been updated
