### ISSUE TITLE
Coren Direbrew (Low Prio)

### ISSUE THREAD

**Issue by Amine-x-x** [gamefreedomgit/Frostmourne#1994]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Ability of coren direbrew (direbrew's disarm) count as buff from players, not as a debuff, spell description (You lost your weapon!  Next time, distance yourself from Coren when he drinks.) , i think thats disadvantage , not advantage to be a buff.
**How to reproduce:**
engage with the boss and let him use it on you.

**How it should work:**
debuff so people can track it .

**Database links:**
[Direbrew's Disarm](https://www.wowhead.com/spell=47310/direbrews-disarm)

**Comment by Afgann** [comment]
fixed
