### ISSUE TITLE
Paladin Judgement not counting as melee attack

### ISSUE THREAD

**Issue by bandini9** [gamefreedomgit/Frostmourne#1996]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Paladin Judgement not counting as melee attack

it was working as intented on naxx, not anymore

You are supposed to be able to interrupt big tentacle stacks with judgement

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Manpower99** [comment]
you can interrupt on normal mode, on HC you cannot as that is an intended pre-nerf thing.

**Comment by Godmatik** [comment]
it interrupts in normal just fine

**Comment by Riztazz** [comment]
not a bug
