### ISSUE TITLE
Issue with sharing Flying machine mount on other characters

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1997]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

This mount requires level 60, expert riding and engineering 300 and increases flight speed by 150%
However for it being shared on other characters within the same account, it requires artisan riding to be unlocked.

**How to reproduce:**

Set engineering skill on two characters (of the same account and at least level 60) on 300, learn expert riding and then learn the mount using [flying machine control](https://www.wowhead.com/wotlk/item=34060/flying-machine-control)
switch to the other character, learn expert riding and it will not be unlocked.
however it will show up after learning artisan riding.

**How it should work:**

Requirements on alt characters should be adjusted to expert riding

**Database links:**

https://www.wowhead.com/wotlk/spell=44155/flying-machine
https://www.wowhead.com/wotlk/item=34060/flying-machine-control

**Comment by Afgann** [comment]
fixed
