### ISSUE TITLE
[11122 + 11412] [There and back again] 

### ISSUE THREAD

**Issue by GM-Nightmare** [gamefreedomgit/Frostmourne#1998]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
players are not able to obtain it after completing the quest , After adding and player completing the quest they cant hand it laso

**How to reproduce:**
complete the quest and wait until next day

**How it should work:**
![image](https://github.com/user-attachments/assets/434a7c2b-ec4f-4a8c-8235-cc25921b5c7a)
quest should be repeat-able 

**Database links:**
https://www.wowhead.com/quest=11412/there-and-back-again#guides
https://www.wowhead.com/quest=11122/there-and-back-again#guides
https://www.wowhead.com/wotlk/guide/brewfest-event-achievements

**Comment by Chaos-within** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/1973

**Comment by Riztazz** [comment]
Quest has been fixed by Piootrek, realm has not yet been updated, im gonna close this
