### ISSUE TITLE
Pet follow too slow

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#200]
**Description:**
Pet follow speed is slow and ends up lagging behind player even at 0% speed buff
When there is a great distance between pet and player, the pet moves back to player at its normal speed (slow)

**How to reproduce:**
Get a pet and walk around
Make good distance between you and pet and watch it move back

Tested with warlock but I assume the scripting applies the same to other pet classes

**How it should work:**
Pet should follow on the left hand side of the player and not much further behind
If pet is far away and is pathing back to the player (also not in combat iirc), it should do so at greater speed

**Database links:**

**Comment by Afgann** [comment]
fixed
