### ISSUE TITLE
[Quest] [11661] [Orabus the Helmsman] 

### ISSUE THREAD

**Issue by GM-Nightmare** [gamefreedomgit/Frostmourne#2000]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Quest item is not starting the event / npc is not coming
im getting the error (You can't do that yet)

**How to reproduce:**
![image](https://github.com/user-attachments/assets/b87c00c0-1bec-4fd7-a500-7690fef18d6a)
![image](https://github.com/user-attachments/assets/d4dd889d-0720-46bc-86bd-a505e2fc7cc2)

**How it should work:**
using the item should make the boss come.

**Database links:**
https://www.wowhead.com/wotlk/quest=11661/orabus-the-helmsman

**Comment by Piootrek** [comment]
I couldn't reproduce this issue. This message should appear when there is already spawned ship nearby. I made it to despawn faster after being summoned, it might fix the problem.
