### ISSUE TITLE
[Deathknight] DRW should be able to heal owner with lichborne active

### ISSUE THREAD

**Issue by danniellos94** [gamefreedomgit/Frostmourne#2001]
**Description:**
DRW (Dancing rune weapon) should be able to heal owner with lichborne active.

**How to reproduce:**
Get full runic power with rune weapon active use lichborne and cast death coil on urself.

**How it should work:**
DRW should heal you for 50%.

**Database links:**
"Summons a second rune weapon that fights on its own for 12 sec, doing the same attacks as the Death Knight but for 50% reduced damage and healing."
https://prnt.sc/ZaA1YrsM6PMN
https://www.wowhead.com/wotlk/spell=49028/dancing-rune-weapon

**Comment by Riztazz** [comment]
The print-screen you provided is a report of a bug that happened on classic cata - that's not something we're going to implement.
There is a bug with DRW that only copies the damage of death coil and never heal if the target is friendly, so im going to fix that

**Comment by Riztazz** [comment]
Fixed, will close once it's live
