### ISSUE TITLE
EOE 10A P2 bubbles not mitigating damage. 

### ISSUE THREAD

**Issue by Lanarrin** [gamefreedomgit/Frostmourne#2005]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
EOE 10A P2 bubbles do not mitigate damage making it no possible to heal through the damage. we tried with 3 healers. still too much. 

**How to reproduce:**
Attempt maly 10A get to P2. Notice healing needed vs norm

**How it should work:**
The bubbles should mititgate damage from aoe. easily healable fight 

**Database links:**

**Comment by Manpower99** [comment]
Unsure if it is bugged or not, but coupled with that 10A has as much Disk NPCs as 25man, it is definitely a massive challenge to heal through, please consider reducing the [Scion of Eternity](https://wowpedia.fandom.com/wiki/Scion_of_Eternity)damage or reduce the amount of the [Scions ](https://wowpedia.fandom.com/wiki/Scion_of_Eternity)as currently if an unlucky player gets hit by two [Arcane Barrages](https://www.wowhead.com/wotlk/spell=56397/arcane-barrage) at the same time then it will oneshot the player (even inside the bubble). making Phase2 a RNGfest. in 25Man there are more players to deal damage to the scions and more players to soak the Barrages so it is way more managable.

**Comment by Afgann** [comment]
@Manpower99 Aura part of Arcane Barrage was missing (2s aura that prevents already hit target from being hit again in short period). It should feel more fair now.

**Comment by Manpower99** [comment]
> @Manpower99 Aura part of Arcane Barrage was missing (2s aura that prevents already hit target from being hit again in short period). It should feel more fair now.

Thank you very much!
