### ISSUE TITLE
Deserter Debuff After Accepting Dung/BG Prompt

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#2006]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Players using dungeon finder or BG queue getting automatically removed after accepting the prompt with deserter debuff. it's not all the time but we had several cases of it.
![image](https://github.com/user-attachments/assets/049f0735-e53b-4227-8a7c-96ea76eb76ae)

Unsure if the player being _Away_ before it pops had any impact on it

**How to reproduce:**

queue for battleground / dungeon and accept the prompt

**How it should work:**

Player shouldnt get removed or deserter debuff.

**Comment by Afgann** [comment]
fixed
