### ISSUE TITLE
Yogg Brain Room - Skulls P2

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#2008]
Vods on retail and classic showcase a max of 3 skulls in each room, the amount of skulls currently on live realm (30/09/24) is higher than this. 
https://www.youtube.com/watch?v=Pf4MAONG1vs&t=450s 
https://youtu.be/Pf4MAONG1vs?si=1IjU_RUxkbQVKkFH&t=365
OG wotlk video of ensidia you can see only 3 skulls floating in the air.

**Comment by Afgann** [comment]
fixed
