### ISSUE TITLE
Autumnal Acorn Ale summon is hostile in sanctuaries

### ISSUE THREAD

**Issue by yeagerca** [gamefreedomgit/Frostmourne#2009]
**Description:**
The friendly squirrel spawned by drinking Autumnal Acorn Ale is aggressive to enemies in Dalaran and may attack players.
![WoWScrnShot_093024_180508](https://github.com/user-attachments/assets/049ad88e-870f-4f76-a5c7-fa52a92e2481)

**How to reproduce:**
Drink it in Dalaran.

**How it should work:**
Probably shouldn't be hostile at all, I don't know.

**Database links:**
https://www.wowhead.com/wotlk/item=37907/autumnal-acorn-ale#comments:id=853771

**Comment by Afgann** [comment]
fixed
