### ISSUE TITLE
Firethorn empty loot table.

### ISSUE THREAD

**Issue by tubefrede** [gamefreedomgit/Frostmourne#2010]
The firethorn loot table was recently patched to no longer include 'Fire Seed', which is in line with how original wrath was. 
This has however resulted in half of the firethorn herbs having no actual "herb" when gathered. Sometimes they contain crystalized life or a frost lotus, but oftentimes the herb node is simply empty and disappears when gathered.
So instead of deleting 'fire seed' from the loot table, it should instead be replaced with 'Fire leaf', so that there are no empty herb nodes.

**Comment by Riztazz** [comment]
fixed, will close once it's live
