### ISSUE TITLE
Ulduar - Mimiron Issues 01/10/24

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#2012]
1. There should be a 1s Grace period where boss doesnt even move or attack upon becoming attackable https://youtu.be/hZLzmte5vqw?si=WbRk_rYMzHdsYs24&t=204
https://youtu.be/AdQcu0hVvfo?si=pDiL7yj_Cq207b4B&t=14

2. Approximately from blizzard videos the number of Fires both spread and summoned by the boss for the Fire Cap is 50 total, if reached then no more should appear until the amount is cleared below 50. idk how much it is on live since even when room is full of fire we've never reached it. This is pure estimation from Tankspot vod + Ensidia vod and many classic vods. There are some claims that it is up to 60 total fire patches from mmo champion, so i'll leave it up to you guys which amount u wanna pick. https://youtu.be/AdQcu0hVvfo?si=-XX5-Vgi5Tqrstt5&t=237
Note : this was easier to estimate than i thought when i learned that the fire only spreads from the "Head" part of the fire patches as explained in this video https://www.youtube.com/watch?v=hZLzmte5vqw
![image](https://github.com/user-attachments/assets/564a112a-bfee-4976-89ab-db56e9ee4f95)

3. in Phase4 some issue occurs and the boss makes random turns during it https://youtu.be/tSflZ8HjkKU?si=4JQTGwTXDC8WhBVF&t=3929 this is possibly to cast Hand Pulse during barrage, which it shouldn't cast anyway to begin with while Lazer barrage is active.
There were even attempts i've done where the boss was casting Lazer barrage but it was hitting towards his back side instead of front side. sadly i did not record it but i will make sure to screenshot it if it happens again as it is EXTREMELY misleading for some players and leads to unecessary deaths.

4. Phase3/Phase4's Head should be directly reachable by melees if they jump/move while underneath it ( primarily due to leeway ) i can't consistently pull this off on this server but on classic many vods show it to be easily doable. likely the issue on this server is the Hitbox being smaller than it should be or an issue with leeway script itself.
Proof: [1](https://youtu.be/Fnx8TfGnhz0?si=unZnLVOe_oZE3Rnv&t=265) + [2 ](https://youtu.be/Fnx8TfGnhz0?si=RJNQ4WjHCXDAY6Q_&t=336)+ [3 ](https://youtu.be/Fnx8TfGnhz0?si=12upVCSnquUYrQg_&t=347)

5. Seems Deafening Siren should also be a thing on 25N, not just 10HC/25HC. the only raid difficulty where it shouldn't exist is 10N. this is my mistake in a different bug report i've made. it is something related to how blizzard used to refer to 25Man raids as "Heroic Raids" and "Normal Raids" as 10Man prior to ToGC being released, but the aura should have reduced radius than 25HC/10HC according to the hotfix but i can't find proof to this range difference but it should probably remain 10yards across all the 3 Difficulties (25N/25HC/10HC).
[Patch 3.2.0](https://wowpedia.fandom.com/wiki/Patch_3.2.0) (2009-08-04): Renamed from Heroic: Firefighter to Firefighter (25 player).
[Hotfix](http://blue.mmo-champion.com/23/17631614070-recent-ingame-fixes--6409.html) (2009-06-25): The hard mode of the Mimiron encounter has received the following changes: the damage of the flames has been reduced, the damage/health gained from the Emergency Buff has been slightly reduced, the range of the Emergency Fire Bot’s Deafening Siren ability has been reduced in heroic difficulty and this ability is no longer cast in normal difficulty, the damage of Heat Wave in phase 2 has been reduced, and the damage from Plasma Blast in phase 1 has been reduced.

**Comment by Afgann** [comment]
fixed

**Comment by oneadanut** [comment]
The fix for 4. increasing Aerial command unit hitbox, made it being attackable in phase 4 by any meele without any effort. The original poster brought up leeway mechanic which it should work on moving/jumping if the target is also moving.

As you can see in the video below, the warrior targeted the head for a second when raid leader said "more on middle" and all his abilities are out of range. Just slow down the video at 8:50
https://youtu.be/PkK5CoLNafg

Here is a video of Leeway mechanic explained:
https://youtu.be/S3GH5cWPFOE
