### ISSUE TITLE
furious shoulders price incorrect

### ISSUE THREAD

**Issue by vurtne77** [gamefreedomgit/Frostmourne#2014]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**the furious shoulders ( pvp ) are priced incorrectly  ITS  2370AP , it has same price as chest / legs / head wich shouldnt be that way
chest legs head are always the most expensive > shoulders > hand  . 2370AP > 1750AP > 1430AP

**How to reproduce:** check the vendors at POW isnland ( idk about dalaran vendor ) its 2370AP instead of 1750AP

**How it should work:** it should be priced at 1750 like every wotlk server ever 

**Database links:** https://gyazo.com/2cae87c02e1e4d1964fb0b1581e691e4
https://www.wowhead.com/wotlk/guide/classes/priest/discipline/healer-bis-gear-pvp-arena-season-6 u can also check wowhead for prices ^^

**Comment by Afgann** [comment]
fixed
