### ISSUE TITLE
[Kologarn] Overhead Smash should be dodgable/parriable

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2015]
**Description:**
The ability Overhead Smash from Kologarn is applying the debuff every cd without tanks dodging or parrying any of them.

**How it should work:**
![image](https://github.com/user-attachments/assets/febaece5-abd9-4c7c-9abc-455e695516b5)

**Database links:**
https://www.wowhead.com/spell=64003/overhead-smash#comments

**Comment by Aeradel** [comment]
![image](https://github.com/user-attachments/assets/8ec8c90d-6521-4ada-afff-b7e84b1b8856)

**Comment by Manpower99** [comment]
![image](https://github.com/user-attachments/assets/faa26690-dacb-46e4-b035-908e847c209f)

**Comment by Aeradel** [comment]
> ![image](https://private-user-images.githubusercontent.com/100322493/372746180-faa26690-dacb-46e4-b035-908e847c209f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NDkyNzYsIm5iZiI6MTcyNzg0ODk3NiwicGF0aCI6Ii8xMDAzMjI0OTMvMzcyNzQ2MTgwLWZhYTI2NjkwLWRhY2ItNDZlNC1iMDM1LTkwOGU4NDdjMjA5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQwNjAyNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Yzk3MjU3YTQxMWE2ZGIxYWEyZDI4NjMwMmU3ZTY2NzFmNjZjMjcwYzgwZmFjZGJiODA4OTZiZmRjZjUyNTkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xtCkqsIXJP7aAmlg1Z70Y4-Kt6rxG-r5NcxCYQfkoVg)

I added this same graphic shortly after this was made - but deleted my comment after finding **several** sources that show that this is incorrect. Likely a typo or mistake on this website.

**Comment by Manpower99** [comment]
cant find a classic log where either Overhead Smash or One-Armed Overhead Smash got avoided, could be that it was only like this in classic then if you have sources that state otherwise idk, wowpedia does claim that the ability can be avoided to not get the crunch armor debuff.

**Comment by Riztazz** [comment]
Further confirmed by tactics in e.g. https://www.tentonhammer.com/guides/ulduar-kologarn-strategy#:~:text=Overhead%20Smash%20Kologarn%20uses%20this%20high%20damage%20attack%20against%20the

**Comment by Riztazz** [comment]
fixed, will close once it's live

**Comment by oneadanut** [comment]
@Riztazz did you test this? because I never saw it being dodged or parried by any tanks.
