### ISSUE TITLE
[dungeon][ascended] Culling of Stratholme - Arthas disappearing

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#2019]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Arthas has disappeared after players wiping on Mal'Ganis fight. 
He didnt move back to previous stages, and cant be found in the instance 

**How to reproduce:**

Wipe during malganis encounter in CoS ascended mode.

**How it should work:**

Arthas should be available so players can restart the encounter.

**Comment by WhitemaneChronus** [comment]
seems its about arthas dying, he also disappeared when he died to the zombies in the passage.

**Comment by Riztazz** [comment]
Fixed, will close once it's live

**Comment by WhitemaneChronus** [comment]
Also there are reports of players not getting the loot for defeating malganis. the chest does not appear.
Some of them had arthas alive in the fight too.

**Comment by Riztazz** [comment]
I don't think my fix has been applied yet:P I will see into arthas after malganis

**Comment by WhitemaneChronus** [comment]
it's not live, i added the comment in case more adjustments is required before server restart.
according to 1 group of players, Arthas was present but they still didnt get any loot on malganis. 
we can check again after the update.

**Comment by Riztazz** [comment]
Will do, open a new issue if it pops up please

**Comment by Aeradel** [comment]
> Will do, open a new issue if it pops up please

this is still relevant and happening
