### ISSUE TITLE
Pure Stratholme Holy Water

### ISSUE THREAD

**Issue by AlucardHellsingChapel** [gamefreedomgit/Frostmourne#2020]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Pure Stratholm Holy water is dispelling forbidance sated etc 

**How to reproduce:**
Throw it on sated target

**How it should work:**
It should not mostlikely

**Database links:**

**Comment by oomshroom** [comment]
The item is also usable outside of its dungeon.

**Comment by Piootrek** [comment]
Fixed
