### ISSUE TITLE
off hand pvp rating requirement + price incorrect 

### ISSUE THREAD

**Issue by vurtne77** [gamefreedomgit/Frostmourne#2022]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** the price and the rating requirement for Off-hands in pvp are incorrect they require 1930 rating instead of 1800 
and also 1350AP instead of 350AP

**How to reproduce:** check the vendor in POW island 

**How it should work:** the OH rating requirement should be same as weapon ( 1800 rating ) and the price is 350AP obviously less than the weapon  here we have OH more expensive than the weapon 1350AP for OH 1300AP weapon ^^ 

**Database links:**https://gyazo.com/fff702735718de30e8d4fb4ba29fd572 this is the whitemane price / rating requirement 1930

https://gyazo.com/1716d2fc51f4fcbeb0e4a3fe19260a23 this is ss from wow head 
https://www.wowhead.com/wotlk/guide/classes/priest/discipline/healer-bis-gear-pvp-arena-season-8

**Comment by Afgann** [comment]
fixed
