### ISSUE TITLE
Yogg Laughing Skulls - Randomization improvements

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#2023]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
#2008  Introduced a couple bugs. There needs to be some rules to the skull randomization inside, otherwise we have 3 skulls in front of the entrance one-shotting people right now on live.
Rule 1:
Skulls must be 20-30yrds away from other skulls so as to not stack on top of each-other.
Rule 2:
Skulls must not spawn at or in front of the entrance so that people can safely enter the theme rooms.

Proof is same as original post, you can see no skulls in entrance line and skulls have distance between each-other.
https://www.youtube.com/watch?v=Pf4MAONG1vs&t=450s
https://youtu.be/Pf4MAONG1vs?si=1IjU_RUxkbQVKkFH&t=365

**How to reproduce:**
Enter yogg brain room, rng skulls stacked and/or at the entrance.

**How it should work:**
Pics with red zone where they shouldn't spawn at all and distance between eachother, randomized in the non-red zone.
![plan](https://github.com/user-attachments/assets/95c178fa-c900-4021-808c-73f4c5bfa16b)

![plan (1)](https://github.com/user-attachments/assets/290002b4-f074-458c-8de1-c93779341045)

![plan (2)](https://github.com/user-attachments/assets/6bfdb15a-db37-48d4-9c32-e8fbda8bc83c)

**Database links:**

**Comment by Manpower99** [comment]
The issue is that they can spawn close to eachother, but there should be some rules yes i will scour more videos to confirm more about this!

**Comment by Afgann** [comment]
fixed
