### ISSUE TITLE
missing meta gem in POW vendor

### ISSUE THREAD

**Issue by vurtne77** [gamefreedomgit/Frostmourne#2025]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**missing one meta gem in POW  gem vendor

**How to reproduce:** check the gem vendor :p

**How it should work:**we should have this meta gem from TBC since its not accesible for POW players 

**Database links:**https://www.wowhead.com/wotlk/search?q=Powerful+Earthstorm+Diamond 
https://gyazo.com/6f0b4adb0ea69c7fc2581b5d00689601

**Comment by Afgann** [comment]
fixed
