### ISSUE TITLE
I cant see a item in the transmog options

### ISSUE THREAD

**Issue by Stancone** [gamefreedomgit/Frostmourne#2026]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The item Diamond-tipped Cane, linked below, is missing from the mog vendor

**How to reproduce:**
Item is missing from transmog mob options; with or without a staff equipped.

**How it should work:**
i should be able see the item in the transmogrifier's options

**Database links:**
https://www.wowhead.com/wotlk/item=45861/diamond-tipped-cane

**Comment by Afgann** [comment]
fixed
