### ISSUE TITLE
[POW] Missing trinket - lavanthor's talisman

### ISSUE THREAD

**Issue by danniellos94** [gamefreedomgit/Frostmourne#2028]
Description:
This trinket is missing from a path of war vendor. This trinket is best in slot for prot warrior (at least on this stage) and propably prot paladin.

How to reproduce:
Add this trinket to a pow vendor.

How it should work:
The trinket should be there.
Database links:
https://www.wowhead.com/wotlk/item=37872/lavanthors-talisman

**Comment by danniellos94** [comment]
https://prnt.sc/WupypbgiP1ea

This trinket should cost 60k honor points like other not arena points.

**Comment by Afgann** [comment]
fixed
