### ISSUE TITLE
Non-attacked mobs reset for group pulls

### ISSUE THREAD

**Issue by Wuspop** [gamefreedomgit/Frostmourne#203]
**Description:**
When you pull a mob in a group, the other mobs that have not taken damage yet reset after a few seconds before they reach you.

**How to reproduce:**
Range pull a mob in a group without damaging the other mobs in the group - watch other mobs reset.

**How it should work:**
Other mobs should come and start attacking you.

**Comment by Afgann** [comment]
fixed
