### ISSUE TITLE
[achievement] Ulduar - Algalon 10m on HC 

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#2030]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Players are not getting the achievement for defeating algalon on 10m heroic (Astromancer)
They already had the achievement for 10 normal
no cases of dying + releasing spirit middle of encounter.
**How to reproduce:**

Defeat Algaon on 10m heroic

**How it should work:**

Should reward the achievement accordingly

**Comment by Afgann** [comment]
fixed
