### ISSUE TITLE
Difficulty change from normal to HC in Ulduar causes issues (soulstone missing, fish despawn, focus megic, missing warlock protal etc.)

### ISSUE THREAD

**Issue by gforghieri** [gamefreedomgit/Frostmourne#2032]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

Difficulty change from normal to HC in Ulduar causes issues (soulstone missing, fish despawn, focus megic, missing warlock protal etc.)

**Comment by Aeradel** [comment]
Seems if people change to Heroic before grabbing loot, it also removes the loot. Haven't tested, but have had several reports.

**Comment by Manpower99** [comment]
Don't know if it possible when its related to fish/items placing on map, but thank you for the rest its highly appreciated and saves us from alot of headaches and time being wasted.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by WhitemaneChronus** [comment]
@Piootrek After the update, players are unable to change difficulty even though all dead bosses are empty to them.
According to 3-4 raids so far "we looted every boss but cannot swap difficulty", getting the error that some loot is still available.
