### ISSUE TITLE
Web wrap + Herald Volazj

### ISSUE THREAD

**Issue by Aeradel** [gamefreedomgit/Frostmourne#2034]
Players shouldn't be web wrapped [ascended] during insanity. That's a death sentence. It's just instant death.

**Comment by Manpower99** [comment]
https://youtu.be/lE-89qjXifE?si=5sfMbcfapi3zid7A&t=322
Illusions shouldn't have the debuff either

**Comment by Riztazz** [comment]
fixed, will close once it's live
