### ISSUE TITLE
[CORE] Fear Off Blade's Edge Arena Bridge

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#2037]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Fear caused me to fall down from Blade's Edge Bridge twice in a row...

**How to reproduce:**

**How it should work:** You shouldn't fall down in fear obviously

**Database links:**

**Comment by UltraNix** [comment]
@haephaistoss Need more info here. Do you have any screenshots of that spot?

**Comment by Riztazz** [comment]
Do you jump a lot during gameplay? were you jumping just before fear? We are trying to find clues because it does not happen when we are performing tests and we do not fix stuff blindly
