### ISSUE TITLE
[Asc] Utgarde Keep / Utgarde Pinnacle

### ISSUE THREAD

**Issue by OrceMaceski** [gamefreedomgit/Frostmourne#2040]
Ascended ability `Glaciate` should be removed after combat or at least not activate `Icy Path` when out of combat. It is annoying to run around long after combat waiting for `Glaciate` to expire to be able to drink/eat or to resurrect someone. `Glaciate` should be removed upon leaving the dungeon. 
`Icy Path` should gradually increase its damage if the player is not moving while affected by it.

**Comment by Manpower99** [comment]
https://www.youtube.com/watch?v=jkD-djBdyuc
the current one on live seems to be incorrect, it is also doing the Path of Frost sound incorrectly everytime it is spawned.
 - the stacking debuff frostbite which increases the damage should be magic and dispellable (at start of vod hes using decursive addon to dispell). 
 - Glaciate shouldn't have visible duration, you can see on [this video](https://youtu.be/cPSdiOZvFaU?si=AUp1wy0qftQA_gWa&t=641) the debuff is removed after 6steps regardless of how many ice patches it spawned which is  pretty similar to every vod i've seen it does not last the full 1 minute duration it currently has on live.
![image](https://github.com/user-attachments/assets/ba1e6db5-cc0d-4bc2-83c2-aacc4567625f)

**Comment by Afgann** [comment]
fixed
