### ISSUE TITLE
[Ulduar] Razorscale's Flame Breath doesn't do damage

### ISSUE THREAD

**Issue by Shineslippers** [gamefreedomgit/Frostmourne#2041]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
[Razorscale](https://www.wowhead.com/wotlk/npc=33186/razorscale)'s Flame Breath([63317](https://www.wowhead.com/wotlk/spell=63317/flame-breath), [64021](https://www.wowhead.com/wotlk/spell=64021/flame-breath)) doesn't do damage when boss is **_above_** 50% of HP i.e. Phase 1. Either 10 or 25 mod

**How to reproduce:**
Shackle him and wait for breath

**How it should work:**
Should do damage...

**Comment by oneadanut** [comment]
Also, in phase 2, devouring flame should be casted on random player. Currently he cast it only on tank.

**Comment by Godmatik** [comment]
It does do damage, but it is doing so in the wrong direction of where he is facing when shackled

**Comment by Manpower99** [comment]
From what i saw it does damage to the right side of the area when entering instead of the front, possibly related to the previous bug where the boss' orientation was incorrect.
![image](https://github.com/user-attachments/assets/6149fb7e-4559-421e-b001-fb4ddff9e806)

**Comment by Afgann** [comment]
fixed

**Comment by oneadanut** [comment]
> Also, in phase 2, devouring flame (blue fire) should be casted on random player. Currently he casts it only on tank.

Boss should face and target the player when doing Devouring Flame. Can you check @Afgann ?

**Comment by Afgann** [comment]
@oneadanut done, will be fixed after next update

**Comment by oneadanut** [comment]
@Afgann The boss is facing the player when doing Devouring Flame, but he doesn't target him. Also, the boss should have a cast bar of both Flame Breath and Devouring Flame. Check this video: https://www.youtube.com/live/4HO7YdaMv1E?si=vBHdJNN-mu1WWRDB&t=2506

Not a high prio, just if you want to polish the encounter to be more accurate.
