### ISSUE TITLE
Incorrect prices on Ascension quartermaster

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2042]
**Description:**
Final voyage (crossbow) costs 12 emblems, while Arrowsong (bow) costs 38.
213 cloaks have the same price as 226 cloaks.

**How it should work:**
Both ranged weapons should have the same price since both are 213 ilvl.
213 cloaks should have lower price than 226 cloaks.

**Comment by Afgann** [comment]
fixed
