### ISSUE TITLE
[DK] - Corpse Explosion Auto-targets Ghoul pet rather than existing corpses

### ISSUE THREAD

**Issue by postits** [gamefreedomgit/Frostmourne#2043]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
As per title: Corpse Explosion Auto-targets Ghoul pet rather than existing corpses, which ruins the use of the spell.

**How to reproduce:**
Using Corpse Explosion during any fight where multiple corpses are available.
Using Corpse Explosion without any target while having enough Runic Power.

**How it should work:**
It should not auto-detect your ghoul pet, you should have to actively target the pet for it to get exploded - Either by macro, or manual targeting.
You should not need to worry about sacrificing your ghoul every time you press the button.

**Database links:**
https://www.wowhead.com/wotlk/spell=50444/corpse-explosion
https://www.wowhead.com/wotlk/spell=51328/corpse-explosion

**Comment by Manpower99** [comment]
Prio should be afaik Random Closest corpse>Army Ghouls>Ghoul. 
Unless of coure it is specifically targeted.

**Comment by postits** [comment]
Noted the discord changelog post.

This issue still persists - Pet Ghoul is still valid and will get blown up without being targeted, with or without other available corpses.

**Comment by Afgann** [comment]
Change will apply after next update.

**Comment by Afgann** [comment]
fixed
