### ISSUE TITLE
Yogg-Saron Tentacles Behavior + Death Rays

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#2044]
All are an issue as of 04/10/24
 1. Constrictor Tentacle after it spawns will grip whichever is closest to it instead of a **pre-determined random player** that it spawns very close to.
 if a constrictor spawns abit further all you have to do is walk to it and you'll get gripped instead of whoever it is intended to grip, this way it also makes being gripped avoidable.
 - Should be completely random whichever gets picked. the constrictor spawns very close/approximate to that player's position and grips him. https://youtu.be/pHoD7Io13UQ?si=IfamwYkik3vnS2sK&t=291 Here the player gets instantly picked up, pre-determined target to be picked up from before constrictor spawn.
 
 2. Tentacles in general but especially Crushers and Corruptors are able to spawn very close to eachother but **shouldn't be**, and sometimes Crushers and Corruptors super close to eachother ensuring any melee's death if they attempt to damage a Corruptor this way. 
last 10HC i did, the Corruptors were straight up directly ontop of the crushers + [RF video corruptor hugging constrictor](https://youtu.be/tSflZ8HjkKU?si=icxY9Mrm03f9E6l2&t=5624)
 - There should be about some minimum range between eachother so they dont hug eachother this way.
 
 3. The 4 Death Rays should randomly spawn spread all over the boss area, But the issue is that sometimes their initial spawn location  way too close to eachother, this is primarily noticable on 10Man Yogg.
  - https://youtu.be/ScgHjGnLsF4?si=uurdbayoIATvFF4L&t=298 this is how they should be spread, with some minimum range coded to them so they're they never spawn at almost the same location.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
