### ISSUE TITLE
Ascended Dungeon - Oculus - Eregos

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#2045]
These issues didn't happen to me but to others and asked me to report them since they do not have Git accounts.
Ley Guardian Eregos and his Whelps should benefit from the Titan Rune's Health and Damage Buffs but shouldn't be able to summon Mirror Images.
https://www.youtube.com/watch?v=V39KoWJIsCg
https://www.youtube.com/watch?v=IsERjBqPkZ4

Azure Ring Captains shouldn't proc mirror images.
Mage-Lord Urom Shouldn't proc mirror images only from his Empowered Arcane Explosion.
Both should still benefit from the Health and Damage increase.

![image](https://github.com/user-attachments/assets/f91c2f97-db65-4920-a939-0f0a5544c150)

**Comment by Afgann** [comment]
fixed
