### ISSUE TITLE
Ascended Dungeon - Utgarde Pinnacle - King Ymiron

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#2047]
![image](https://github.com/user-attachments/assets/a66b6394-ddcc-4218-9fda-65d8aaed8ccd)
From what i've seen the Glaciate ice patches floor shouldn't deal damage if you are CC'd by Him and the debuff on the player that spawns the ice patches is removed once affected by the stun.
https://www.youtube.com/watch?v=_2q4GJtnDME
https://www.youtube.com/watch?v=eUgD6RbXnvk
It is currently a guaranteed death sentence if any of the targets get the debuff during or right before the stun happens.

Also In every Difficulty, if he AoE stuns currently on this server he becomes unattackable. he should remain attackable.
https://youtu.be/5PsioIa5F5U?si=YzBjqrEPB_f2RFpp&t=1939 Mage cancels it through blink and is able to cast spells at the boss.

**Comment by Afgann** [comment]
fixed
