### ISSUE TITLE
[Asc] Culling of Stratholme

### ISSUE THREAD

**Issue by OrceMaceski** [gamefreedomgit/Frostmourne#2049]
Using engineering bomb or a frag belt triggers 1 min CD on `Pure Stratholme Holy Water`
`Pure Straholme Holy Water` should be removed from backpack upon leaving the dungeon.

**Comment by Manpower99** [comment]
Should be a 1.5s CD on the Item currently 0, shouldn't share cd with anything afaik but currently using engi bombs put it on cd which is a big issue

**Comment by Afgann** [comment]
fixed
