### ISSUE TITLE
shaman class not automatically learning 2h axes + 2h maces

### ISSUE THREAD

**Issue by qqdbpp** [gamefreedomgit/Frostmourne#205]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
shamans do not auto learn 2h axes and 2h maces weapon skill when leveling

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/583a7c53-b0d8-43aa-8f3e-a97d1f582aa5)
At 20 lvl.
