### ISSUE TITLE
Pet pathing on summon

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#2050]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When being summoned close to the spot where player already is (less than 100yrd-ish) instead of de-summoning and re-summoning the pet, your pet goes through walls running very fast towards the spot the player was summoned. This causes the pet to ninjapull anything between old and new player location.

**How to reproduce:**
summon inside vezax room while player with pet is at the very entrance (where the 2 colossals are). In a few second you'll notice the pet ninja pulled the collosals if not dismissed before taking summon

**How it should work:**
Pet should be temporarily dismissed when player accepting summon, then recalled upon landing on the summon

**Database links:**

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
