### ISSUE TITLE
POW chars need bigger bags plz 

### ISSUE THREAD

**Issue by vurtne77** [gamefreedomgit/Frostmourne#2051]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** ayo wassup devs hope u doing alright , thnx for the good work anyway , we need bigger bags in path of war plz <3 i beg
you might ask why so here is the answer : as experienced PVP players we need a lot of space bags for  gems to exchange before arena start / enchants at arena que pop sometimes you have to change 5-8 gems ,change few enchants so u need them all in ur bags ready because you have 10-20sec of time to change  them all depending on the enemy team u facing  / lot of  trinkets to change / lot of consumes for BG's but yea the most important is arena

**How to reproduce:**
 put bigger bags on the consume vendor so everyone can purchase them

**How it should work:**
well everything is in the description i guess  

**Database links:** this is the bags we want :  https://www.wowhead.com/item=23162/a-very-large-bag 
this is an example of how crouded bags can be : https://gyazo.com/a8db7ae1ffa0b9ec00285b54a0e21c0c

**Comment by UltraNix** [comment]
Post this suggestion on our Discord channel.
https://discord.com/channels/1040715551531618365/1163874902617620612
