### ISSUE TITLE
[fishing] Bobber not working properly sometimes

### ISSUE THREAD

**Issue by HosseinEkv** [gamefreedomgit/Frostmourne#2053]
https://github.com/user-attachments/assets/6a958fce-4e4e-4940-8558-bd889b9112d6

**Description:**
sometimes when u are fishing the bobber wont hook the fish up as it is shown in the video , i also had auto loot off plus all addons (except addon control panel) turned off as a gm told me that might help the problem

**Comment by Afgann** [comment]
fixed
