### ISSUE TITLE
Down With The Dark Iron achievement dwarfs spawn time and movement speed is to fast

### ISSUE THREAD

**Issue by mplecko** [gamefreedomgit/Frostmourne#2055]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
[Down With The Dark Iron](https://www.wowhead.com/wotlk/achievement=1186/down-with-the-dark-iron) 
After few tries solo i realized it is impossible so i tried with 3 and then with 4 more friends, but we weren't able to defend a single barrel. 
Spawn time and running speed of dwarfs shouldn't be so fast. It is insanely fast compared to retail.

**How to reproduce:**
Every 30 min dwarfs spawn at brewfest area and you have to defend barrels by hitting them with [Complimentary Brewfest Sampler].
I haven't tried it with 25 man raid, but doing it solo is impossible while on retail classic it was easily doable.

**How it should work:**
They should move and spawn like they do in this video from WOTLK classic:
https://www.youtube.com/watch?v=c_tfrhXRiJA

**Database links:**

**Comment by Riztazz** [comment]
Fixed, will close once it's live
