### ISSUE TITLE
Utgarde Keep - Skarvald the Constructor/Dalronn the Controller

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#2056]
Regardless of what guides say and even wowhead and wowpedia, the accurate behavior in both retail and classic are like this :
If one dies while the other is alive, it turns into a targetable and damagable enemy which you can both use spells on etc.
they're targettable but unkillable and will heal themselves up if you damage them.
[Retail behavior](https://youtu.be/gcxBT9C9ZOE?si=-MHJBLyndU-GPILF&t=23)
[Behavior during Wotlk classic's Alpha Dungeon](https://youtu.be/LCFtJF0Z7_8?si=qzXPTHNvOHqIN1g0&t=48) you can fully see it is damagable, tauntable, shadowbolt interruptable(while dead but not while alive), there is a threat list and but the damage is just being healed.
[Another Retail vod](https://youtu.be/cp0G-_p15Jw?si=_lBxQBGGXPLMOW-f&t=21)
[OG vod without nameplates](https://www.youtube.com/watch?v=pyywai0dVlg) NPC name is visible even after death and same behavior as vods above.
[Here you can see Dalronn Dies, there is a delay and an animation for his Ghost to appear but also same behavior](https://youtu.be/kp-Or869l4k?si=QeXO-rDTkCpbDxmO&t=34)
[Timestamped here you can see the healer targeting the ghost and there is a full threat list on omen addon](https://youtu.be/wXm2lRNTg7M?si=8T62E4J8vw8gWMq3&t=134)

**Comment by Afgann** [comment]
fixed
