### ISSUE TITLE
frostmane troll whelp id 706 frostmane novice id 946

### ISSUE THREAD

**Issue by qqdbpp** [gamefreedomgit/Frostmourne#206]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**

these mobs just stand there and do not attack you when you engage them
https://i.imgur.com/oACrP7d.gif

**Comment by wotlkenjoyer** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/185

pretty sure it is a part of this , it is going everywhere, something with hit boxes, mobs under the ground and etc

**Comment by Godmatik** [comment]
Happens in Mulgore as well
