### ISSUE TITLE
Mimiron 10m HC - 1 hp bug

### ISSUE THREAD

**Issue by oXnOi** [gamefreedomgit/Frostmourne#2061]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Last part of the mimiron boss was at 1 hp for around 5-6 seconds after killing 2nd last part. And couldnt die.

**How to reproduce:**
We believe it has something to do with mechanics lining up. like Shock Blast procing right as we kill first two parts.
From second 8-14 in the clip the boss clearly takes damage, even though it has 1 hp, and doesnt die. 

**How it should work:**
should be able to kill the last part within the timer. 

**Database links:**
Here is a link to the video of the last part of the fight. - https://youtu.be/F1lzmfrFfOQ (music is a bit loud in video).

**Comment by Afgann** [comment]
fixed
