### ISSUE TITLE
Flame Leviathan sometimes constantly pulls after reset

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2062]
**Description:**
Flame Leviathan gets pulled after 2 big adds are killed and people usually resets it by being outside the barrier to have all vehicles spawned in front. Sometimes, after reset, FL is constantly pulling and trying to reach people or vehicles outside the barrier and all the raid has to die or go out to remove the bug. He also targets himself for some reason.

![WoWScrnShot_100124_203856](https://github.com/user-attachments/assets/aa0a8e36-6806-4ffd-ae8c-bf04b8aa1967)
![WoWScrnShot_100124_203951](https://github.com/user-attachments/assets/53d25347-89b3-4731-a6ea-3eaca56453b6)

**How it should work:**
Flame Leviathan should reset if no vehicles are inside boss zone after the 2 big adds are killed.
Right now, he resets after he reaches a certain range after barrier, but shouldn't work this way. Or at least he shouldn't constantly pulling after reset. A fix for this would be to check if any vehicles are inside, to pursuit only those. If no vehicles are inside, it should reset.
Also, I think he shouldn't pursuit players, he has to pursuit only vehicles, even if they are without drivers.

![image](https://github.com/user-attachments/assets/7bb847fb-88ae-49ac-b56a-8a7af48c0022)

**Comment by Afgann** [comment]
fixed
