### ISSUE TITLE
UP Proto drake boss Ascended version

### ISSUE THREAD

**Issue by Bugreporter99** [gamefreedomgit/Frostmourne#2064]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When you first trigger the Proto drake boss fight, there's a chance if you run under the dragon instead of going left after the boss mounts, The drake will 1 shot you. I do not recall this ever happening in Heroic. (Of course you should just run left, but some don't lol) 

**How to reproduce:**
I have seen the 1 shot happen a few times, and sometimes it was just a bit of damage. But trigger the boss, and while the boss is mounting the drake, stand under drake as it starts to fly away.

**How it should work:**
Shouldn't be doing damage (If bugged, as I never seen it happen before Ascended version released)

**Database links:**

**Comment by Manpower99** [comment]
Correct, on this server the boss does 1 melee hit while untargetable before going up on his dragon. which can oneshot a player if low geared or can trigger glaciate if in ascended and ruin the entire encounter.
It shouldn't do that one melee hit however, you can always avoid it by going far right side but its a work-around to a bug.

**Comment by Afgann** [comment]
fixed
