### ISSUE TITLE
Hidden worm from path to Hodir arena keeps the raid in combat

### ISSUE THREAD

**Issue by fabio1079** [gamefreedomgit/Frostmourne#2068]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
In Ulduar, on the path to Hodir's arena, just before the entrance, there are two possible routes: one with a patrol and another leading to a hidden worm nest on the right side. 
Some players might not notice the white smoke marking the worm nest and will accidentally step on it. The issue is that one of the worms remains hidden and keeps the raid in combat, which prevents mana regeneration, resurrection, etc.

**How to reproduce:**
Step on the worm nest located on the path right outside Hodir's arena.

**How it should work:**
All worms should spawn, and once they are defeated, the players should exit combat.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
