### ISSUE TITLE
pickpocket drop table

### ISSUE THREAD

**Issue by qqdbpp** [gamefreedomgit/Frostmourne#207]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
currently 68-80 mobs in northrend only give silver when pickpocketed, nothing else. this makes it impossible to get reinforced junkbox to train lockpicking.

**How to reproduce:**
pickpocket any humanoid/undead in northrend

**How it should work:**
look at a drop table like https://www.wowhead.com/wotlk/npc=27203/onslaught-footman#pickpocketing (mob that has been pickpocketed 1000+ times) and see theres about a 35% chance to get a junk flavor item, 30% junkbox, 10% vendor grey,  10% food/drink/healing potion

**Comment by qqdbpp** [comment]
after some more testing it looks like some mobs do have junkboxes on their table, but a lot only have silver (even though they have junkboxes on wowhead)

**Comment by Afgann** [comment]
fixed
