### ISSUE TITLE
Withered / Unliving Choker

### ISSUE THREAD

**Issue by Vaxsysl** [gamefreedomgit/Frostmourne#2070]
**Description:**
I am unable to get Unliving Choker from Withered Trolls to start Ebon Blade questline in Zul'Drak. I am continuously getting Withered Choker. Must be because I did Drakuru questline up until the dungeon quest? Maybe.

**How to reproduce:**
FInish Drakuru questline in Grizzly Hills up until Cleansing Drak'Tharon and kill Withered Trolls in Zul'Drak. Withered Chokers are everywhere (got over 30 of them).

**How it should work:**
AFAIK the game should "see" if we did the said quest or not and drop the appropriate chokert?

**Database links:**
https://www.wowhead.com/wotlk/npc=28519/withered-troll
https://www.wowhead.com/wotlk/item=38673/writhing-choker <the one that drops constantly
https://www.wowhead.com/wotlk/item=38660/unliving-choker <the one I can't get
https://www.wowhead.com/wotlk/quest=12238/cleansing-draktharon < Drakuru quest in my quest log

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by WhitemaneChronus** [comment]
As far as i know this issue isnt bugged, if you have completed the quest [Cleansing Drak'Tharon](https://www.wowhead.com/wotlk/quest=12238/cleansing-draktharon) then you can get the unliving chokers. but you must finish that first.

**Comment by Vaxsysl** [comment]
I have it active, not completed. I should get be getting the Unliving choker.
