### ISSUE TITLE
Hazzarah skipped in Edge of Madness rotation

### ISSUE THREAD

**Issue by Karsenity** [gamefreedomgit/Frostmourne#2073]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
In Zul'gurub, the edge of madness bosses should rotate every 2 weeks. A few bugs currently exist, one being that Renataki's stone always thinks he's near the edge of madness, and Gril'oks stone currently says he's still near the edge of madness despite Renataki being summoned.

The bigger one is that the cycle skipped from Gril'ok straight to Renataki without doing Hazzarah. It should be going in order. As part of this fix, it would also be appreciated if it reverted back to Hazzarah, as otherwise players waiting for his turn will have to wait an additional 2 months.

**Comment by Piootrek** [comment]
Fixed, rotation should be now the same as shown here https://edgeofmadnesscalendar.com/us/west#calendar
I will close this issue once the fix comes live.
