### ISSUE TITLE
[Ulduar] dark rune/demonic rune not working on general vezax

### ISSUE THREAD

**Issue by HosseinEkv** [gamefreedomgit/Frostmourne#2074]
https://www.wowhead.com/wotlk/item=20520/dark-rune
https://www.wowhead.com/wotlk/item=12662/demonic-rune
Hi , I used to play wotlk classic and these to rune would restore mana , there isnt really much to proof cuz its something normal but if u do research about it, u see that they work actually. I think thats a bug on this server . there is threads in reddit where ppl posted about it

**Comment by sputnikk** [comment]
https://www.mmo-champion.com/threads/649182-General-Vezax
This thread implies it to be true even for OG wrath

**Comment by Afgann** [comment]
fixed
