### ISSUE TITLE
[Flame Leviathan] Ward of Life and Writhing Lasher

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2076]
**Description:**
Tower of Life from FL HM spawns adds from each corner, 1 Ward of Life (big add) and few Writhing Lashers (small adds). Their health is incorrect, the big add having around 190k while small adds around 550k. The big add Ward of Life should have more health than small adds Writhing Lashers.

**How it should work:**
![image](https://github.com/user-attachments/assets/e3afb82d-5260-4b53-8bd3-6efc4e6cf6cd)

**Comment by Afgann** [comment]
fixed
