### ISSUE TITLE
[Freya] Pulling in hard mode

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2077]
**Description:**
Pulling Freya in hard mode makes her do an animation of roots coming from the 3 Elders, but she follows the player who pulled making the animation look weird, boss floating towards the player.

**How it should work:**
Freya should stay in place until she finishes the root animation.

**Comment by Afgann** [comment]
fixed

**Comment by oneadanut** [comment]
She shouldn't attack while doing her animation.
