### ISSUE TITLE
[Mimiron] Aerial Command Unit

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2078]
**Description:**
Aerial Command Unit can parry attacks when dragged down and spinning.

**How it should work:**
I didn't find any evidence for this, but I think It shouldn't parry attacks or even dodge due to logical reasons of being incapacitated and spinning.

**Comment by Afgann** [comment]
fixed

**Comment by oneadanut** [comment]
@Afgann the head is still parrying while on the ground.
