### ISSUE TITLE
[QoL] Engi Gloves + trinket CD share

### ISSUE THREAD

**Issue by RadeghostWM** [gamefreedomgit/Frostmourne#208]
Remove shared CD between engineering glove enchant and on-use trinkets

**Comment by alphalphauser** [comment]
Tested today and not working. Simple macro with /use 10 and /use 13 or 14

**Comment by UltraNix** [comment]
@alphalphauser Tell me what trinkets do you have.

**Comment by alphalphauser** [comment]
mark of the war prisoner slot 13
sundial of the exiled slot 14

**Comment by Nuy** [comment]
Pretty sure they should have PARTIAL shared CD if we're taking about Hyperspeed. When you use on-use trinket first you should have like 20 sec CD on Hyperspeed and if you use Hyperspeed befor trinket then your trinket should get similar CD.

**Comment by UltraNix** [comment]
Fixed.

**Comment by Tahtoh88** [comment]
while testing on enhancement, i can't seem to use both engi gloves and on use trinket along shamanistic rage
engi glove goes on a 30 sec cd when i add shamanistic rage to the following macro
#showtooltip Shamanistic Rage
/cast Blood Fury(Racial)
/use 14   (Sphere of the dragon's blood)
/use 10   (Hyperspeed Accelerators)
/cast Shamanistic Rage

the macro properly works when i omit shamanistic rage
