### ISSUE TITLE
FPS drops around Repair npc inside Ulduar

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2081]
**Description:**
When you want to repair inside Ulduar to the npc at the entrance, you get a FPS drop for a few seconds. It happnes even on Repair bot people put from Engineering. It happens to everybody.

**Comment by Piootrek** [comment]
Can't reproduce. Have you tried with disabled addons?

**Comment by oneadanut** [comment]
I didn't try without addons and I see it doesn't drop FPS when I go alone. I think it happens when more people goes for repair, for example after a wipe.
