### ISSUE TITLE
Escape from Durnholde

### ISSUE THREAD

**Issue by Aeradel** [gamefreedomgit/Frostmourne#2082]
quest is not scripted.

this was reported previously by nightmare, months ago, and was closed as working, but i've had ticket after ticket. there's no beginning dialog.

**Comment by Piootrek** [comment]
It works correctly. Did player burn barracks and kill 1st boss?

**Comment by Aeradel** [comment]
> It works correctly. Did player burn barracks and kill 1st boss?

that's what chronus mentioned to me shortly after :p

I'll do some more testing and re-open if needed.
