### ISSUE TITLE
[Lady Vashj] [serpentshrine cavern instance]

### ISSUE THREAD

**Issue by GM-Nightmare** [gamefreedomgit/Frostmourne#2083]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Lady Vashj [Tainted Elemental](https://www.wowhead.com/npc=22009/tainted-elemental) are not dropping 
Tainted Core[ Tainted Core](https://www.wowhead.com/item=31088/tainted-core)
making the boss impossible to kill 

**How it should work:**
Tainted Elementals should drop tainted core , its a mechanic of the boss.

**Database links:**
https://www.wowhead.com/npc=21212/lady-vashj#comments;mode:n25

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
