### ISSUE TITLE
Element-Tamer Dagoda

### ISSUE THREAD

**Issue by Vaxsysl** [gamefreedomgit/Frostmourne#2084]
**Description:**
I encountered Element-Tamer Dagoda while questing in Zul'Drak (obv). When I turned in Bringing Down Heb'Jin, I got a dialogue prompt "I'm ready to battle the dreadlord, sire." Being HC I dare not touch this lest I get instagibbed. Someone else must investigate if anything happens at all.

![WoWScrnShot_100824_204210](https://github.com/user-attachments/assets/d7218da3-33d3-44c0-8569-7a330ee8c04a)

**How to reproduce:**
Finish said quest and interact with her. 

**How it should work:**
...she should not have this dialogue box?

**Database links:**
https://www.wowhead.com/wotlk/npc=28480/element-tamer-dagoda#starts
https://www.wowhead.com/wotlk/quest=12662/bringing-down-hebjin
https://wowpedia.fandom.com/wiki/Mal%27Ganis_(tactics) (that's NPC prompt to engage Mal'Ganis)

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
