### ISSUE TITLE
Eye of the Broodmother trinket

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2086]
**Description:**
The trinket Eye of the Broodmother should work the same as Illustration of the Dragon Soul, prestacking it with any spell.

**How it should work:**
![image](https://github.com/user-attachments/assets/2f2817d8-4ddf-484e-a8fe-c9637ffdb1a0)

Some of the comments say this was fixed in 3.3 patch, but it worked this way during 3.1 and 3.2
![image](https://github.com/user-attachments/assets/3bedbd62-cf44-4599-9031-3f8cad6e55b1)

**Database links:**
https://www.wowhead.com/wotlk/item=45308/eye-of-the-broodmother#comments

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix come live.
