### ISSUE TITLE
[Oculus] Planar Anomaly from last boss

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2087]
**Description:**
Planar Anomaly are the sparks that are summoned on 60% and 20% of the last boss when he phases. The problem is the speed of these sparks following players, they have the same speed as the drake, sometimes you need to run in a straight line to avoid them. Basically if it reaches you, you can't escape. It will do damage to your drake until you die. Also, they should have a grace period until they start running for people when spawning.

The speed of these Planar Anomalies should be lower as I saw in many videos on youtube. Also they should be smaller in size, thus having smaller range.

In ascended, this boss is summoning a mirror of him, but if you are outranging it, the mirror falls down slowly until it dies/despawn. If you are in range, he will spam Frostbolt on you, slowing your movement. Shouldn't the mirror mimic the attacks of the boss? Aka doing Arcane barrage/volley?

**Database links:**
https://youtu.be/KR-1C_q-0vs?si=XAJR7_7DDxAdZ-Fx&t=1006
https://youtu.be/yPjb_PQ_sfk?si=Z7XsJqQ5QbacCZ-_&t=732

**Comment by Afgann** [comment]
fixed
