### ISSUE TITLE
Yogg 10/25 Sara cast on wrong target malady

### ISSUE THREAD

**Issue by starfallminiedziala** [gamefreedomgit/Frostmourne#2088]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)
Sara after phase 1 change and start cast debuffs and Malady on playera.

**Description:**
When she cast Malady On HER Target other person get debuffs them her actually target.

**How to reproduce:**
...

**How it should work:**
She should cast Malady on Her target like all the spells.

**Database links:**

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by starfallminiedziala** [comment]
Thx U Piootrek!
