### ISSUE TITLE
[Quest] Unable to use vehicles

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#2089]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Players getting dismounted immediately on quests that require a vehicle. Unable to use it.
Quests such as 11652 (plains of nasam) and 11690 (bring 'em back alive)

**How to reproduce:**

Take the quest and mount the vehicle.

**Comment by Aeradel** [comment]
This may be relevant to a fix to a different quest, which acted exactly the same before it was fixed. https://github.com/gamefreedomgit/Frostmourne/issues/2013#event-14487622801

**Comment by Piootrek** [comment]
It's not related to the previous issue. 
Fixed, I will close this issue once the fix comes live.

**Comment by WhitemaneChronus** [comment]
in case the quest itself matters following ones are also having an issue
- [13043](https://www.wowhead.com/wotlk/quest=13043/the-sum-is-greater-than-the-parts)
- [13288 ](https://www.wowhead.com/wotlk/quest=13288/thats-abominable) / [13264](https://www.wowhead.com/wotlk/quest=13264/thats-abominable)

**Comment by Piootrek** [comment]
Fixed for The Sum is Greater than the Parts. 
Are you sure those 2 quests are correct [13288 ](https://www.wowhead.com/wotlk/quest=13288/thats-abominable)/ [13264](https://www.wowhead.com/wotlk/quest=13264/thats-abominable)? I don't see any vehicles there

**Comment by WhitemaneChronus** [comment]
> Fixed for The Sum is Greater than the Parts. Are you sure those 2 quests are correct [13288 ](https://www.wowhead.com/wotlk/quest=13288/thats-abominable)/ [13264](https://www.wowhead.com/wotlk/quest=13264/thats-abominable)? I don't see any vehicles there

Those 2 are working fine now, unsure what was the issue.

**Comment by Piootrek** [comment]
Fixed. If you ever see a similar issue please make a screenshot with a .gps output visible

**Comment by Furiianda** [comment]
This issue (Plains of Nasam) has bugged again. Players are told they're "in the wrong zone".
.gps:

You are outdoors
Map: 571 (Northrend) Zone: 3537 (Borean Tundra) Area: 4027 (Coast of Echoes) Phase: 4294967295
X: 2784.868164 Y: 6742.385742 Z: 7.833620 Orientation: 1.184089
grid[37,44]cell[1,5] InstanceID: 0
ZoneX: 31.718639 ZoneY: 54.973614
GroundZ: 7.716454 FloorZ: 7.833644 Have height data (Map: 1 Vmap: 1 MMap: 1)
MMAP Height: 7.8782134

**Comment by WhitemaneChronus** [comment]
@Piootrek same issue on the 3 quests is happening atm
13043
11652 
11690
