### ISSUE TITLE
Target dummy's not performing aoe taunt

### ISSUE THREAD

**Issue by roblox-oof-dot-mp3** [gamefreedomgit/Frostmourne#2090]
**Description:**
All 3 target dummies that engineers create should have an additional ability when first deployed that AOE taunts everything within a certain radius (like bear challenging roar). Currently they aren't using this ability.

**How it should work:**
![image](https://github.com/user-attachments/assets/482e782b-186e-4759-a8d9-78b5e3b41586)

**Database links:**
https://www.wowhead.com/wotlk/item=4366/target-dummy#comments
https://www.wowhead.com/wotlk/item=16023/masterwork-target-dummy
https://www.wowhead.com/wotlk/item=4392/advanced-target-dummy

**Comment by Afgann** [comment]
fixed
