### ISSUE TITLE
Target Dummy has no loot

### ISSUE THREAD

**Issue by roblox-oof-dot-mp3** [gamefreedomgit/Frostmourne#2091]
**Description:**
When a target dummy explode (either from dying or expiring)  it should drop back some of the parts used to create it or a fused wiring

**How it should work:**
Comment specifically for Advanced Target Dummy:
![image](https://github.com/user-attachments/assets/407b25f3-b958-4702-a916-b62a763a3f10)

**Database links:**
https://www.wowhead.com/wotlk/item=4366/target-dummy#comments
https://www.wowhead.com/wotlk/item=16023/masterwork-target-dummy
https://www.wowhead.com/wotlk/item=4392/advanced-target-dummy

**Comment by Afgann** [comment]
fixed
