### ISSUE TITLE
Old Hillsbrad Foothills in the Caverns of Time HC loot

### ISSUE THREAD

**Issue by Grimmwow** [gamefreedomgit/Frostmourne#2094]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I'm running the dungeon of Old Hillsbrad Foothills in the Caverns of Time on hard mode, which is supposed to drop level 70 items with an item level of 115. However, after killing the second boss multiple times, it only drops level 66 items (item level 103), which are supposed to drop in normal mode. Please fix the item drops to what they should be.

**How to reproduce:**
Scaled Greaves of Patience - Mail Legs and Stormfront Gauntlets - Mail Gloves are dropping in heroic mode, but they shouldn't be dropping in heroic

**How it should work:**
**### The following items should be dropping:

Boots of the Watchful Heart - Plate Boots
Dathrohan's Ceremonial Hammer - Main Hand Mace
Emerald-Scale Greaves - Mail Legs
Moon-Crown Antlers - Leather Head
Pontiff's Pantaloons of Prophecy - Cloth Legs
Tarren Mill Vitality Locket - Necklace**

**Database links:**
https://www.wowhead.com/tbc/guide/old-hillsbrad-foothills-dungeon-strategy-burning-crusade-classic

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
