### ISSUE TITLE
Moa'ki Harbor to Unu'pe Village flight path - killing players

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#2095]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

I copy the info from 3 of our players.

> i am writing to report a bug that involves taking a flypath from Moa'ki Harbor to Unu'pe Village. It looks like that taking this flypath would give damage where it instantly kills the player. Damage was received upon landing to Unu'pe.
Character landed through the textures and died 

**How to reproduce:**

Take flight path from Moa'ki Harbor to Unu'pe Village

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
