### ISSUE TITLE
deadly belt incorrect price 

### ISSUE THREAD

**Issue by vurtne77** [gamefreedomgit/Frostmourne#2096]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**so we have deadly belt on POW npc priced at 49600H at the other hand we have furious belt at 39400H this doesnt realy make sens how deadly is more expensive than frious in this season :')

**How to reproduce:** check the NPC in POW island 

**How it should work:** deadly belt should be cheaper than the furious one ( i dont exactely know the exact price but yea ) 

**Database links:** https://gyazo.com/d4d1baf1107eb274d86053258c829198

https://gyazo.com/249fb1bb71c05c15f8ad840f02d4082b
this screenshot are from the POW vendor in tanaris

**Comment by Afgann** [comment]
fixed
