### ISSUE TITLE
deadly off hands + wands incorrect price and requirement

### ISSUE THREAD

**Issue by vurtne77** [gamefreedomgit/Frostmourne#2097]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** so we have deadly offhands and wands requiring 350 arena points in addition of honnor points and require 700 rating to purchase while the deadly weapons are for 34k honnor only and no rating requirement at all 
this doesnt make sens how can the weapon be easier and cheaper to get than the off hand and the wand ^^ 

**How to reproduce:** check the npc in the POW island and ill also provide screenshots of them 

**How it should work:** off hands and wands should require honnor points only , no arena points and no rating requirement exactely like the weapons  , in addition they should be cheaper than the weapon it self 

 
**Database links:**  https://gyazo.com/f211b30dce755d66e1da3893eb141b2c

https://gyazo.com/5ff9aa3f070f836cf006e0c464cf55d4
this screenshots are provided from the vendor in POW tanaris island

**Comment by Afgann** [comment]
fixed
