### ISSUE TITLE
deadly set items price correction

### ISSUE THREAD

**Issue by vurtne77** [gamefreedomgit/Frostmourne#2098]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**so after season6 starts deadly set parts prices should be corrected for POW players from requiring arena points to requiring only honnor 

**How to reproduce:**check the NPC in POW island in tanaris

**How it should work:** deadly set should require honnor only in season6 since furious set is out for POW players

**Database links:**https://gyazo.com/ccc662a6ebbb2baec655de5bd78dcc3f this ss is from the POW vendor in tanaris

**Comment by Afgann** [comment]
fixed
