### ISSUE TITLE
Old WG trinket reprice after new ones out

### ISSUE THREAD

**Issue by vurtne77** [gamefreedomgit/Frostmourne#2099]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** the WG npc in POW island has old trinkets (200ilvl) priced as 25 wintergrasp mark of honnor same as the new trinkets out with the season6 start (213ilvl) 25 marks wich i think should be the case , the old trinkets should be repriced cheaper into 15 marks instead of 25 

**How to reproduce:** check the WG npc vendor in POW island

**How it should work:** price should be recorected to be cheaper than the new trinkets accordingly 

**Database links:** old trinkets: https://gyazo.com/49d1fdc91a28a8baf412ead443a175d2
new trinkets: https://gyazo.com/5d465bf86be41b25d85b0022d6e44a36

**Comment by Afgann** [comment]
fixed
