### ISSUE TITLE
missing frostweave bag from the POW npc

### ISSUE THREAD

**Issue by vurtne77** [gamefreedomgit/Frostmourne#2100]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** we are missing 20 slot bag on the POW npc , since netherweave bag is here (  from tailoring ,  and we all know all proffs are available with comps in POW island ) why dont u add the 20 slot bag also wich is provided from tailoring also 

**How to reproduce:** check the general vendor NPC in POW island 

**How it should work:** 20slot bag should be available since its provided from the same source as netherweave bag wich is tailoring 

**Database links:** https://gyazo.com/b0fd33e885ae9251c281c3b4f4eb6a0c

**Comment by Afgann** [comment]
fixed
