### ISSUE TITLE
tier8 PVE items missing from POW island

### ISSUE THREAD

**Issue by vurtne77** [gamefreedomgit/Frostmourne#2101]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** so after like 6 weeks now or maybe more of season6 start all non POW pvp players had the time to get their pve gear on ulduar from 10hm/hc + 25hm/hc in addition of the emblem of echoes vendor that speed up the gearing process also 
i find it unfair that for example me that is literaly BIS in POW full furious cant have access to any PVE item available on this tier8 patch for all this weeks 
at the start the argument was that players of POW cant have direct access to PVE items since non POW players will have to farm and struggle to get them and actualy raid wich i understand and respect and i also raid and i know the struggle , but after all this weeks tons of players got their gear including me on my non POW char that is already 5k gs with all gear that u can imagine even tho im not bis yet  but yea u get my point 

**How to reproduce:** my pow priest is full furious still wearing pve items from naxx

**How it should work:** at this point ( 6 weeks of season start !! ) we should have access to our pve items with AP+ Rating requirement like past season 

**Database links:**

**Comment by vurtne77** [comment]
@RadeghostWM  maybe an answer to this plz ? been 2days

**Comment by RadeghostWM** [comment]
NEXT Wednesday. @Afgann

**Comment by Afgann** [comment]
fixed
