### ISSUE TITLE
[Warlock] Immolation aura (from Metamorhosis) is a debuff

### ISSUE THREAD

**Issue by danniellos94** [gamefreedomgit/Frostmourne#2102]
**Description:**
Immolation aura is a debuff, so you as a player can't cancel it with a macro.

**How to reproduce:**
Use metamorphosis and immolation aura on a warlock.
https://ibb.co/82bSNsx

**How it should work:**
Immolation aura should be a buff, I believe it's not dispellable.
Dispel type | n/a

**Database links:**
https://youtu.be/dAWo3YMu81A?t=93
https://www.wowhead.com/wotlk/spell=50589/immolation-aura#comments

**Comment by Afgann** [comment]
fixed
