### ISSUE TITLE
Some species of hunter pets have wound up miniaturized

### ISSUE THREAD

**Issue by DJ-Zephyr** [gamefreedomgit/Frostmourne#2103]
**Description:**
So a few weeks back, I noticed my devilsaur and warp stalker have been shrunk.  My other pets- bear, cat, and Skoll the spirit beast are all sized as expected, but these two are much smaller than they used to be...

**How to reproduce:**
Just pull either pet out of the stable.  Neither has any buffs or debuffs.  It persists thru dismissing/re-summoning and death.  I tamed another warp stalker, and a different devilsaur, and they were even MORE shrunk.

**How it should work:**
The devilsaur should be as tall as even my night elf.  The warp stalker should be pretty long and wide.
![WoWScrnShot_101024_121010](https://github.com/user-attachments/assets/78169461-50d7-4fd7-a766-24966681a697)
![WoWScrnShot_101024_121002](https://github.com/user-attachments/assets/7b10fc19-903d-4808-af01-00fb363f27e2)

**Comment by Afgann** [comment]
fixed

**Comment by DJ-Zephyr** [comment]
Half-fixed.  My Devilsaur is back to normal size, but my warp stalker is still shrunken.
![WoWScrnShot_101724_113912](https://github.com/user-attachments/assets/0c86a077-a854-45e2-ab7e-e9d8be59cedc)

**Comment by DJ-Zephyr** [comment]
He's back!  He's BIG and he's back!
![WoWScrnShot_102024_135729](https://github.com/user-attachments/assets/942b0ce6-5a4c-4b2a-a3b2-aba231e3e1d6)
