### ISSUE TITLE
Gnomish battle chicken incorrect level

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#2104]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Gnomish battle chicken, as well as most other engineering pet's levels should scale with owner's engineering skill using the formula Level=Engineering skill / 5. Currently it is static at Lv83.

**How to reproduce:**
Have 450 engi skill, summon chicken, it will be lvl 83 and lower hp than it should.

**How it should work:**

![battlechick](https://github.com/user-attachments/assets/572787fc-d1d2-4803-ab47-91ff850edeea)

450skill/5=Lv90 chicken with corresponding 2157 hp (most likely just scaling from the 7 lvl difference.
Gnomes with +15 engineering racial should have lv 93 chickens at 465 skill.

**Database links:**

**Comment by Afgann** [comment]
fixed
