### ISSUE TITLE
Aether-tech Master vendor missing items

### ISSUE THREAD

**Issue by Rocksmashguy** [gamefreedomgit/Frostmourne#2105]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
NPC vendor Aether-tech Master in Blade's Edge Mountains is missing the following Items:
Small Gold Metamorphosis Geode
Large Gold Metamorphosis Geode

**Database links:**
https://www.wowhead.com/wotlk/npc=23245/aether-tech-master
https://www.wowhead.com/wotlk/item=32630/small-gold-metamorphosis-geode
https://www.wowhead.com/wotlk/item=32629/large-gold-metamorphosis-geode

**Comment by Chaos-within** [comment]
Added in patch 2.5.1... These aren't normal wrath items.

**Comment by Rocksmashguy** [comment]
After fixes that went live today the vendor now (in addition to what he had before) sells:
- Small Iron Metamorphosis Geode
- Large Iron Metamorphosis Geode
They are wrongly labled with "Classes: Priest, Mage, Warlock"
Should be labled as "Deathknight, Warrior, Paladin." as they contain the plate version of this vendors armor items

The vendor is still missing the Copper, Silver and Gold Geodes for the corresponding armor types.
https://www.wowhead.com/wotlk/npc=23245/aether-tech-master

![Aether Tech Master](https://github.com/user-attachments/assets/3dfe298a-ef56-4eee-8831-972a79652675)

**Comment by Afgann** [comment]
fixed
