### ISSUE TITLE
Death problem when using Forsaken Blight Spreader for quest (Spread the Good Word)

### ISSUE THREAD

**Issue by Ophiceb** [gamefreedomgit/Frostmourne#2107]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
While operating a Forsaken Blight Spreader as directed by the quest(Spread the Good Word), right after I exited Venomspite and headed to Carrion Fields, the vehicle exploded, dealing nature damage at(Coordinates 80, 61). Upon reviewing the death logs, it appeared I was hit by a plague bomb, a skill associated with this vehicle. As I understand it, the vehicle should sustain damage from its own abilities, and my character should not have taken damage while mounted.

**How to reproduce:**
Operate Forsaken Blight Spreader and head to Carrion Fields. What i didn't do, but its crucial to reproduce: (probably try to shoot a plague bomb in a wall where it will be close proximity to the vehicle, possibly a wall)

**How it should work:**
The vehicle should sustain damage from its own abilities, and characters should not take damage while mounted. In addition, you have to be in the Carrion Fields for the blight bombs to explode. Shooting into it from another area should not work.

**Database links:**
https://www.wowhead.com/wotlk/quest=12218/spread-the-good-word
Have also opened an in-game ticket.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
