### ISSUE TITLE
WG quest NPC missing on POW island

### ISSUE THREAD

**Issue by vurtne77** [gamefreedomgit/Frostmourne#2108]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** we are missing the wintergrast quest NPC in POW island , so whenever we do quests in WG we get insta teleported back to the island and we cant realy redeem the quests back , so i suggest putting one NPC down with ALL the WG quests in POW island so we can pick quests from him and redeem them back there when we get teleported back
because now when we do quests we need to wait for the next WG to turn them back 2 hours later 

**How to reproduce:** 

**How it should work:** we should have an npc to turn back quests on after we get teleported back to the island 

**Database links:**

**Comment by Riztazz** [comment]
Fixed, will close once it's live
