### ISSUE TITLE
daily battleground quest missing from POW island

### ISSUE THREAD

**Issue by vurtne77** [gamefreedomgit/Frostmourne#2109]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**wee missing the daily BG quest npc in POW since its available for non POW players we have the right to have it too since it gives extra 25 arena points and some honnor

**How to reproduce:** missing NPC on tanaris POW island

**How it should work:**we should have one there that gives the quest

**Database links:** https://gyazo.com/2a93a4038ca74f3fa84ea435971d3a04

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
