### ISSUE TITLE
Arfus Companion not BOA

### ISSUE THREAD

**Issue by Bugreporter99** [gamefreedomgit/Frostmourne#2111]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The pet Arfus from Achievement Ascended First Contact is not Bind to account.

**How to reproduce:**
Get the achievement, and swap characters 

**How it should work:**
Companions and mounts are Bind to account (unless of course class specific or Faction specific)
![20241011_120004](https://github.com/user-attachments/assets/56924482-37a3-4ecc-8222-fa3ddd1c92de)
![20241011_120754](https://github.com/user-attachments/assets/5109a792-f63f-46df-a460-d0a73138e6fe)

**Database links:**

![20241011_121301](https://github.com/user-attachments/assets/f61edb9f-2b87-4c99-a7b1-e989b645d08d)
![20241011_121314](https://github.com/user-attachments/assets/7e6c5c88-e2c4-402a-9e3b-584acae9d947)

First 2 pictured are the character on the account with Arfus and the achievement. Last 2 is a different character on the account without the companion.

**Comment by Afgann** [comment]
fixed
