### ISSUE TITLE
Echo of the Titans bug

### ISSUE THREAD

**Issue by Khaelethika** [gamefreedomgit/Frostmourne#2113]
**Description:**

Doing Ulduar 10 men and 25 men Hard mode Bosses they should drop items usable to buy Items but i never got any of the and i do HM since Ulduar riad cam out

my latest ulduar ID are:
10 men : 1360
25 men: 320

![WoWScrnShot_101224_091659](https://github.com/user-attachments/assets/a3172630-0646-41f8-b19f-7eabe874dab0)
![WoWScrnShot_101224_091655](https://github.com/user-attachments/assets/5b8c4df7-5395-4a3d-8c7b-d3cdc1d33aad)

**Comment by buza-me** [comment]
Hey, echoes drop if you do hard mode bosses on heroic (ascended) difficulty. So for example Ignis or Kologarn in ascended will not drop echoes.
