### ISSUE TITLE
Echo of the Titans items are not refundable.

### ISSUE THREAD

**Issue by buza-me** [gamefreedomgit/Frostmourne#2114]
I accidentally have bought a [[Charm of Meticulous Timing]](https://www.wowhead.com/wotlk/item=45443/charm-of-meticulous-timing) instead of a [[Pendant of Fiery Havoc]](https://www.wowhead.com/wotlk/item=45133/pendant-of-fiery-havoc) at around 11:15 - 11:20 PM ST yesterday,  October 11th. And the [Charm of Meticulous Timing] is not refundable. ~~Besides making a fix I also plea for an item swap in my inventory because it really is a lot of effort wasted...~~
Character named Solti.

**Comment by buza-me** [comment]
It can't be vendored for gold either btw.

**Comment by Riztazz** [comment]
This has been fixed recently by @Piootrek
