### ISSUE TITLE
deadly shield missing on POW vendor

### ISSUE THREAD

**Issue by vurtne77** [gamefreedomgit/Frostmourne#2116]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** we missing the deadly  shield for heals / dps  on POW deadly gear vendor if u can add them plz

**How to reproduce:** check the vendor

**How it should work:** should be there :p

**Database links:**https://gyazo.com/62ee3f6b616033533d8fdea9ee80dc3f

https://gyazo.com/6606c09882b63d31ad0f4e5839a012cc

**Comment by Afgann** [comment]
fixed

**Comment by peninagedola** [comment]
only deadly shield with resilience was added, shields with crit+sp and mp5+sp are missing
