### ISSUE TITLE
Quest : The way to his heart Bug

### ISSUE THREAD

**Issue by christianabdou-dotcom** [gamefreedomgit/Frostmourne#2117]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Hello, so i was doing the quest in howling fjord but it seems like it is bugged since there's no fish school to use the net on in order to complete the quest.

**How to reproduce:**

**How it should work:**

**Database links:**
A little fast guide to demonstrate how to do the quest : https://www.youtube.com/watch?v=hMCDuZejnmQ

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
