### ISSUE TITLE
Yogg - Brain links

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#2118]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Affecting all difficulties.
If both people with brainlink go inside portals, the brainlink will remain inside yogg brain room.

**How to reproduce:**
Have the 2 brainlinked people click portal at same time.

**How it should work:**
Brainlink should be removed from any and all people clicking the portals as soon as they are inside.

**Database links:**

**Comment by Afgann** [comment]
fixed
