### ISSUE TITLE
Yogg - Constrictor tentacle

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#2119]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Affecting all difficulties.
If a player that gets targeted to be constricted clicks on a brain portal, he will get teleported inside the brain room and then the will be teleported back outside in the constrictor, deleting the portal(because it was technically used) AND causes a weird bug that people can't even kill that constrictor so you die (server probably confused because 2 positions at once?)

**How to reproduce:**
Hard to replicate, basically once you see a constrictor spawn next to you, you are the most likely target to get constricted and have a split second before that happens. Click on the portal in that split second and this bug will happen.

**How it should work:**
Once you are inside the brain room you shouldn't be teleported back by any means except clicking on the brain room portals. Players inside should not get constricted/get squeeze debuff under any means.

Update: Apparently the blizzlike way is that there shouldn't be a slight delay from when the constrictor spawns until you get grabbed, should be instant instead so you wouldn't even have time to click the portal. This is the root problem of this bug.

**Database links:**

**Comment by Afgann** [comment]
fixed
