### ISSUE TITLE
Summoning stones, Ritual of Souls and pets get stuck in raid sometimes

### ISSUE THREAD

**Issue by PhillWarmane** [gamefreedomgit/Frostmourne#212]
**Description:**
When using Ritual of summoning, Ritual of Souls or moving your pet just completely halts. The channel for the spells can be done 100% but no one can click it, pets can't move or get buffed.
I noticed that everything unstucks at a certain time. If the ritual was clicked, tv will pop, pets can move again.

**Comment by PhillWarmane** [comment]
Related https://github.com/gamefreedomgit/Frostmourne/issues/163

**Comment by WhitemaneIsa** [comment]
No further info/complaints, closing.
