### ISSUE TITLE
[Quest] Beetix Ficklespragg's quest missing completion events

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2122]
[Deadly Desert Venom](https://www.wowhead.com/wotlk/quest=8277/deadly-desert-venom)
Missing post-completione event:
Noggle Ficklespragg says: Wha... where am I? So... weak..
https://wowpedia.fandom.com/wiki/Deadly_Desert_Venom?so=search

[Noggle's Last Hope](https://www.wowhead.com/wotlk/quest=8278/noggles-last-hope)
Missing post-completion event:
Noggle suddenly gets up.
Noggle Ficklespragg says: Yes! I'm cured! I'm cure... whoa, got up too fast!
Noggle falls back onto the bench.
https://wowpedia.fandom.com/wiki/Noggle%27s_Last_Hope

[Noggle's Lost Satchel](https://www.wowhead.com/wotlk/quest=8282/noggles-lost-satchel)
Missing post-completion event:
Noggle briefly sits up.
Noggle Ficklespragg says: Thanks for finding my reagents! *yawn* That poison's made me... a bit tired...
https://wowpedia.fandom.com/wiki/Noggle%27s_Lost_Satchel

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
