### ISSUE TITLE
[Quest] When All Else Fails (Alliance) – Player can drive the rocket

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2123]
[When All Else Fails (Alliance)](https://www.wowhead.com/wotlk/quest=12862/when-all-else-fails#comments) should put the player on a rocket that automatically takes the player to Frosthold. Currently the player can and has to manipulate the rocket to get there. Horde version might have the same issue.

(classic) https://www.youtube.com/watch?v=qQZ7ubN6V9k&ab_channel=GripT

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
