### ISSUE TITLE
[Quest] Just Around the Corner – AA cannons don't work

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2124]
[Just Around the Corner](https://www.wowhead.com/wotlk/quest=12819/just-around-the-corner)
AA cannons around the Mine Field should automatically shoot on players passing on flying mount and take them down. They don't.
https://wowpedia.fandom.com/wiki/Just_Around_the_Corner?so=search#Notes

**Comment by Afgann** [comment]
fixed
