### ISSUE TITLE
[Quest] Fate of the Titans - missing dead bodies and other minor things

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2125]
COPY OF MY REPORT FROM ANOTHER SERVER. SAME ISSUES.
Links:
Video of the quest from 2015, only one I have found https://www.youtube.com/watch?v=uxFLWbMnM6s
→ but what databanks says on Mania is in alignement with this video.
Quest: https://wow-mania.com/armory/?quest=12986
Creteus' Mobile Databank (typo in the armory btw) https://wow-mania.com/armory/?item=42679
Mobile Databank: https://wow-mania.com/armory/?npc=30313

What is Happening:
1: There are no dead bodies in Temple of Invention.
→ Dead bodies: Mechagnome Attendant https://wow-mania.com/armory/?npc=30170
2: There are no dead bodies in temple of winter.
→ Dead bodies: Servant of Hodir https://wow-mania.com/armory/?npc=30881
3: I think Mobile Databank is missing that little light beam/tentacle analysis when analysing objects.

What Should happen:
1: There should be the bodies.
2: Databank should have the light tentacle when doing analysis

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
