### ISSUE TITLE
[Quest] Fury of the Frostborn King – event could use some honing

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2127]
COPY OF REPORT FROM ANTOHER SERVER. SAME ISSUES.
Links:
Video (2015) https://www.youtube.com/watch?v=GNp0RIYR8kU
Wowpedia: https://wowpedia.fandom.com/wiki/Fury_of_the_Frostborn_King
→ Revision 28th September 2008: https://wowpedia.fandom.com/wiki/Fury_of_the_Frostborn_King?oldid=1615322
Quest - Fury of the Frostborn King: https://wow-mania.com/armory/?quest=12879
Prequest - The Hidden Relic: https://wow-mania.com/armory/?quest=12878
Comment confirming spawn of the NPC: https://www.wowhead.com/quest=12879/fury-of-the-frostborn-king#comments:id=461504

After completing the quest The Hidden Relic, Frostborn Axemaster should spawn as player's Guardian…
→ Frostborn Axemaster:
→ → Probably the automatic summon: https://wow-mania.com/armory/?spell=55383
(There is another one with huge range whcih is I think a trigger for the army outside)
→ → NPC itself: https://wow-mania.com/armory/?npc=29729
(There are other NPCs with same name without additional info but this is the one where summon link takes me)

→ In the video there is infighting between Frostborns and Iron Dwarves in the cave. The cave empty at the moment.

→ Outside the cave there are no NPCs, the Iron Dwarves Army is spawning one by one, attacking Frostborns holding the cave, and dying. On Red both armies stand fully spawned at the entrance, standing against each other idly.

→ In the Foot Steppes there are dead bodies, NPCs fighting each other, lot of action. Most of the NPCs is spawned in predetermiend positions and they do not fight each other too much.

I know the video is from 2015 and it is basically the only proof, beside wowpedia and implications from wowhead comments, that would suggest this quest is wrong but it would be cool of this phase would get some more action.
Also starting description of the Quest states: <As you retrieve the core from the chest, you hear the thumping of heavy footsteps rushing towards you from the corridor. There is the faint sound of battle in the distance.>
Everytime I did this quest I felt it a bit odd that after the footsteps in the corridor nothing happens and I am alone in the cave.
Also the linked comment from 3.0.3 mentions the constant battle outside.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
