### ISSUE TITLE
Trash mobs before Flame Leviathan combat bug

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2128]
**Description:**
The trash mobs or maybe the pillars that spawn dwarf mobs are constantly getting the raid members in and out of combat.

**How it should work:**
The raid members that are not participating in killing trash until FL, shouldn't get combat.

![WoWScrnShot_101324_134130](https://github.com/user-attachments/assets/37b92231-4133-49f5-9604-c152632ae9be)

**Comment by Afgann** [comment]
fixed
