### ISSUE TITLE
[Quest] The Brothers Bronzebeard – Mobs don't jump on the plane

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2129]
[The Brothers Bronzebeard](https://www.wowhead.com/quest=12973/the-brothers-bronzebeard)

During the flight out of "the hole", some of the enemies should jump on the airplane and try to damage it. Player needs to kill them. No [Stormforged Soldier](https://www.wowhead.com/npc=30136/stormforged-soldier) jumps on the airplane on the server.

https://www.youtube.com/watch?v=2YJJ-yhOJKM&ab_channel=GitGudGuides
https://wowpedia.fandom.com/wiki/The_Brothers_Bronzebeard?so=search#Notes
https://wowpedia.fandom.com/wiki/Stormforged_Soldier#Notes

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
