### ISSUE TITLE
AFK status cannot be cleared

### ISSUE THREAD

**Issue by oomshroom** [gamefreedomgit/Frostmourne#213]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Once AFK status is turned on, it cannot be turned off by any means. Walking or "/afk" print a message "You are no longer Away", but the player remains flagged as AFK.

**How to reproduce:**
/afk
walk a bit
/run print(UnitIsAFK("player"))

**How it should work:**
AFK status should be cleared

**Database links:**

**Comment by Godmatik** [comment]
It clears AFK for me?

**Comment by oomshroom** [comment]
fixed
