### ISSUE TITLE
[Halls of Stone] Ascended last boss

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2131]
**Description:**
The last boss from Halls of Stone ascended is insanely hard for no reason. Average groups wipe on this boss because the adds are doing a lot of damage. Also, the rune is increasing the health by 118%? That's too much, or at least adjunst the base health of Forged Iron Trogg as per screenshot. Boss is spawning 4 adds, all with 60k hp and then oozes. If oozes merge, they have 30k hp.
As per youtube video, the boss shouldn't spawn 4 adds at once and oozes should spawn like in the video, not spawning in the same time from each side.

After wipe, he doesn't completely reset until everyone releases, making the cd reset not working.

https://youtu.be/NSgvS5-gm6k?si=GzxwYAnGkbjNRCCq&t=1262

https://youtu.be/rdCU7Zh0VWo?si=YNCaniCPqBeWo72N

![image](https://github.com/user-attachments/assets/bf082513-7a1e-4ef7-a0b8-ca7241957c78)

**Comment by WhitemaneChronus** [comment]
There's a report on players killing last boss (they skipped the entire event, and got to last boss straight) and got hc loot.
the dungeon is ascended and the boss is dead.
They got emblems of conquest and no ascension ones; also no additional loot for asc mode.
They have whitemane client.
