### ISSUE TITLE
[Utgarde Pinnacle] Svala Sorrowgrave

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2133]
**Description:**
The first boss in Ugarde Pinnacle, Svala Sorrowgrave, shouldn't put players in combat during her roleplay and pull if you skip it.

**How it should work:**
The boss should be skippable.
https://youtu.be/LZzkNuDVGFE?si=lAjdup9tOXgUT5Rv&t=127

**Comment by Afgann** [comment]
fixed
