### ISSUE TITLE
[Azjol-Nerub] Hadronax

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2134]
**Description:**
Hadronax shouldn't put players in combat before he reaches the room.

**How it should work:**
You can check this mage combat by looking at his teleport spells.
https://youtu.be/GhfCYPhnm4w?si=2ITa6_oU6HtVH8vD&t=303

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
