### ISSUE TITLE
Vanish, Invisibility, probably Feign Death on non-raid bosses

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2135]
**Description:**
Vanish and Invisibility should drop combat on non-raid bosses (lvl 82).

Also, there is a bug that occurs doing invisibility to any boss (in raids too), where Omen Threat Metter bugs.
You can see my Omen on bottom right corner.

![WoWScrnShot_101424_143832](https://github.com/user-attachments/assets/dec89d7c-58a2-4ead-aa6b-12d705dc558c)
![WoWScrnShot_101424_143835](https://github.com/user-attachments/assets/c8e1007d-ee15-4196-811f-befcb6ae711d)

**Comment by Piootrek** [comment]
Do you have any proof it should work this way? As far as I know players shouldn't be able to lose combat during boss encounters.

**Comment by oneadanut** [comment]
https://youtu.be/S51AW3UdESc?si=sgH_tQuqJ8x8nnlS&t=158

Proof right here, where rogue vanishes to avoid his death. You can see on his avatar the combat drops after vanish. (the cross swords)

**Comment by oneadanut** [comment]
https://youtu.be/wnRvGXomdk0?si=ecQjKqmj6flhjzhQ&t=433

Another proof here in a heroic dungeon,

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
