### ISSUE TITLE
No Fire Seed from Firethorn 

### ISSUE THREAD

**Issue by Paidhelmz** [gamefreedomgit/Frostmourne#2136]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Fire Seed not dropping from Firethorn Nodes. Farmed 30 stacks of Fire Leaf with no drop. Don't believe this is bad luck because even with a lower drop rate. I got a whole stack of Eternal Life and Frost Lotus and no Fire Seed. Other herbers in my guild have also said they haven't been getting any.
I think these were nerfed along with the flame caps incorrectly since they no longer give a buff and are strictly a milling item.

**How to reproduce:**
Herb Firethorn in Tundra area by airstrip.

**How it should work:**
Firethorn should drop both Fire Seed and Fire Leaf along with the crystalized life and Frost Lotus. 

**Database links:**
https://www.wowhead.com/wotlk/item=39969/fire-seed#comments

**Comment by oneadanut** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/1944

**Comment by Paidhelmz** [comment]
Ahh ty I did not realize that it was completely removed from they game I thought it was just changed to a white milling herb.
