### ISSUE TITLE
[Freya] Detonating Lashers became dormant

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2137]
**Description:**
We got a bug on Freya on Detonating Lashers where they became dormant for some reason, we couldn't attack them anymore and boss kept 12 stacks of healing buff in phase 2.

**How to reproduce:**
I don't really know how that happened.

![WoWScrnShot_101424_225736](https://github.com/user-attachments/assets/6ceb1a6e-2149-4491-8eba-ea01d3c3d4fd)
![WoWScrnShot_101424_225624](https://github.com/user-attachments/assets/fb9a2347-7992-4b06-b27d-007a5d2bf0fb)
![WoWScrnShot_101424_230213](https://github.com/user-attachments/assets/f8007cd4-acb7-4c85-b50f-9aea2ba40d69)

**Comment by Afgann** [comment]
fixed
