### ISSUE TITLE
[Ulduar trash] Arachnopod Destroyer bug

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2138]
**Description:**
We couldn't hop on the Arachnopod Destroyer mobs after they got low and yellow nameplates. They should allow players when right clicking to control them.

![WoWScrnShot_101424_230755](https://github.com/user-attachments/assets/3552b745-7458-41b9-9e04-54065e2b677a)

**Comment by Afgann** [comment]
fixed
