### ISSUE TITLE
[Vezax] Mark of the Faceless

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2139]
**Description:**
The Mark of the Faceless is keeping 1 beam of healing from the player debuffed. You can see in the screenshot the green beam from me, 
![WoWScrnShot_101424_233659](https://github.com/user-attachments/assets/c6580549-2e02-4d43-8282-58ea80c605fa)

**How it should work:**
The green beam and healing should stop the moment no one is in range from the debuffed player.

**Database links:**
You can see in the youtube video that the beam stops when debuffed player goes far away from others.
https://www.youtube.com/watch?v=X_VYbla1pwc&ab_channel=fojjiwow

**Comment by Afgann** [comment]
fixed
