### ISSUE TITLE
OS 3D Major bug

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#214]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Portal spawned by the second drake during the fight is never actually spawned so no one can go inside the shadow realm and we're stuck with reflect damage debuff.

Drakes have increased hp compared to last weeks. Not sure if intentional but if so undocumented change.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/3eea6cce-e7e2-4539-ac53-f1ba4545e4a2)
@BalanCV Can you record it?

**Comment by BalanCV** [comment]
Has not happened since 2 weeks ago when I reported, I assumed you guys fixed it in the meantime.
