### ISSUE TITLE
[Quest: Escape from Durnholde Keep] Thrall uninteractable 

### ISSUE THREAD

**Issue by AllyEmmi** [gamefreedomgit/Frostmourne#2141]
**Quest:** (https://wowpedia.fandom.com/wiki/Escape_from_Durnholde_Keep)

**Description:** Quest can't progress to next stage, after completing the prerequisite quest Taretha's Diversion, and speaking to Thrall in the basement. He reverts back to having no interactable dialog, but the quest directs you to speak with him to begin the escort. 

**How to reproduce:** Complete prerequisite quest (https://wowpedia.fandom.com/wiki/Taretha%27s_Diversion), talk to Thrall.

**How it should work:** Should be able to interact with Thrall after completing Taretha's Diversion, telling him you're ready to start the escort quest. 

![first](https://github.com/user-attachments/assets/9baece3e-5f82-4cb6-9cc7-fb671fe882a5)
![second](https://github.com/user-attachments/assets/e174e40f-7dc5-4a38-a986-2c57bfa34b96)

**Comment by AllyEmmi** [comment]
> Did you burn barracks and killed 1st boss?

That is the objective of Taretha’s Diversion…  which I completed.

**Comment by AllyEmmi** [comment]
> The quest is working fine you have to **kill 1st boss** and **do the barracks event**. which
I… did that. *Please* read the previous conversation and the description of this issue carefully.

**Comment by Piootrek** [comment]
You most likely didn't kill 1st boss. I checked on retail and it shouldn't be required.
Fixed, I will close this issue once the fix comes live.
