### ISSUE TITLE
HC mail cannot be opened after sender dings 80

### ISSUE THREAD

**Issue by ItsPope** [gamefreedomgit/Frostmourne#2142]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Mail sent to a hardcore player before a character reaches 80 becomes unavailable when the character becomes 80.

The mail becomes unavailable for both the hardcore recipient but also the now normal level 80 character.
This should not be the case as the mail was sent while the character was still hardcore. Meaning the recipient should be able to open it.

I think the issue stems from the game checking the status of the sender when the recipient opens the mail. This is however redundant as one cannot send mail from a non-hardcore to a hardcore (or vice-versa), I.e. there is already a check in place.

**How to reproduce:**
Send mail as hardcore at level <80, when you reach 80 that mail is not able to be opened (and if it is sent back, the level 80 cannot open it as well)

**How it should work:**
The recipient should be able to open the mail. The recipient should be unable to send the mail back, as this would now be a mail from a hardcore to a non hardcore character.

**Database links:**

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by Aeradel** [comment]
> Fixed, I will close this issue once the fix comes live.

This caused a new issue that causes players that were previously HC to send mail to non-HC characters, and have those non-HC characters unable to collect the item. 

When the HC-character's mail is sent, the non-HC character will receive an "Internal Mail Error" or something of the sort, that prevents them from collecting the items.

**Comment by Piootrek** [comment]
Will be fixed after server update
