### ISSUE TITLE
Drop rate for crocolisk tear is unusally low for Quest A Dark Threat Looms, Wetlands Alliance

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#2146]
[https://www.wowhead.com/wotlk/quest=278/a-dark-threat-looms](url)

**Description:**
The drop rate for [Crocolisk tear]https://www.wowhead.com/wotlk/item=2939/crocolisk-tear(url) Is low.

I have cleared all the crocs int he zone 3x over and it hasnt dropped.. Its silly that there are some quests where the items drop 100% ands others like this where you can spend an hour farming it and it wont drop.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
