### ISSUE TITLE
Trusty Copper Racer can't be mounted

### ISSUE THREAD

**Issue by nyxaria** [gamefreedomgit/Frostmourne#2147]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Items:
https://www.wowhead.com/wotlk/item=44482/trusty-copper-racer
https://www.wowhead.com/wotlk/item=44599/zippy-copper-racer
https://www.wowhead.com/wotlk/item=44601/heavy-copper-racer

Can't be mounted when put down / can't be interacted with at all

**How to reproduce:**

Put one down after purchasing in Dalanar and try to interact with it

**How it should work:**

Mount it and ride for 20yds to race your friends

**Database links:**

https://www.wowhead.com/wotlk/item=44482/trusty-copper-racer
https://www.wowhead.com/wotlk/item=44599/zippy-copper-racer
https://www.wowhead.com/wotlk/item=44601/heavy-copper-racer

**Comment by Piootrek** [comment]
Those toys shouldn't be possible to be mounted, they should just race forward for 20 yards. I scripted them like that.
I will close this issue once the fix comes live.
