### ISSUE TITLE
Quest: For the Horde!

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#2149]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
https://www.wowhead.com/wotlk/quest=4974/for-the-horde
On this server thrall does not do his speech when handing in rend head and does not provide rend buff either.

**How to reproduce:**
Finish the quest and nothing happens on quest completion.

**How it should work:**
1. On quest completion, thrall should stand up and yell:
"Thrall yells: Honor your heroes! On this day, they have dealt a great blow against one of our most hated enemies! The false Warchief, Rend Blackhand, has fallen!
Thrall yells: Be bathed in my power! Drink in my might! Battle for the glory of the Horde!"
2. After he yells this 10 seconds later **everyone in Orgrimmar and Crossroads that is level 63 and lower should receive rend buff** https://www.wowhead.com/wotlk/spell=16609/warchiefs-blessing
_Note that in crossroads the rp event and buff giving will be handled by an npc called Herald of thrall that basically mirrors his behaviour on quest complete._

**Database links:**
Azeroth core seemed to have same bug at some point: https://github.com/azerothcore/azerothcore-wotlk/issues/1690
This video shows wcb is still a thing in wrath: https://www.youtube.com/watch?v=sDd4U_cRu3c

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
