### ISSUE TITLE
Macro conditions missing

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2150]
**Description:**
The macro conditions like @player or @cursor are missing or not working. I think they were added in later expansions in OG wow, but they were added in classic wow. It would be nice to add them here too.

**How it should work:**
The condition @player should cast the spell at player's feet. /cast [@player] Death and Decay
The condition @cursor should cast the spell at player's cursor. /cast [@cursor] Death and Decay

**Database links:**
https://www.youtube.com/watch?v=zrrcrtb9h9U&ab_channel=Paper

**Comment by vurtne77** [comment]
this issue was already posted and there is nothing that can be done about it , its client limitation it sadly cant be implimented

**Comment by sputnikk** [comment]
these have been implemented in legion client and forward

**Comment by oneadanut** [comment]
I'm closing this ticket then.
