### ISSUE TITLE
trinkets incorrect price on POW

### ISSUE THREAD

**Issue by vurtne77** [gamefreedomgit/Frostmourne#2151]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** trinkets are for 60k honnor only 

**How to reproduce:**check the npc

**How it should work:** trinkets from tier8 should be with arena points (2370ap each) + rating requirement of 2050 rating 

**Database links:**  https://gyazo.com/ec5c052e496eaf47a57f072ba5618d9c

**Comment by Afgann** [comment]
fixed
