### ISSUE TITLE
some weapons on POW are incorrectly priced

### ISSUE THREAD

**Issue by vurtne77** [gamefreedomgit/Frostmourne#2152]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** some 239 weapons on the POW island are incorrect 

**How to reproduce:**check the npc

**How it should work:** 2H 239ilvl weapons should be same price as r2 pvp weapons and same rating requirement 3585AP + 2350 rating requirement and not 1500ap and few honnor and 1800rating like other weapons 

**Database links:**
https://gyazo.com/73ca7f534e5485fb61861edd189561cd

**Comment by Afgann** [comment]
fixed
