### ISSUE TITLE
missing item from tier8 POW npc

### ISSUE THREAD

**Issue by vurtne77** [gamefreedomgit/Frostmourne#2153]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** hey so we missing total 8 items that are from algalon quest item(10/25)  2 rings 2 backs each

**How to reproduce:** check the npc in pow

**How it should work:** should be there since they are part of BIS item list of nearly all classes for pvp

**Database links:**https://gyazo.com/3cb9050e50ab4e25d4349a2f11d7ecc4  ( dont forget to add both 10mans and 25mans ones plz <3 )

**Comment by vurtne77** [comment]
https://www.wowhead.com/wotlk/item=45588/drape-of-the-skyborn
https://www.wowhead.com/wotlk/item=45618/sunglimmer-cloak
https://www.wowhead.com/wotlk/item=45608/branns-signet-ring
https://www.wowhead.com/wotlk/item=45614/starshine-circle
https://www.wowhead.com/wotlk/item=46320/drape-of-the-skyherald
https://www.wowhead.com/wotlk/item=46321/sunglimmer-drape
https://www.wowhead.com/wotlk/item=46322/branns-sealing-ring
https://www.wowhead.com/wotlk/item=46323/starshine-signet
@Afgann  here is the link to the items ( sry for the ping )

**Comment by reminuz** [comment]
Miss craftable items:
https://www.wowhead.com/wotlk/item=45089/plans-battlelords-plate-boots
https://www.wowhead.com/wotlk/item=45550/belt-of-the-titans
https://www.wowhead.com/wotlk/item=45551/indestructible-plate-girdle
https://www.wowhead.com/wotlk/item=45552/plate-girdle-of-righteousness
https://www.wowhead.com/item=45560/spiked-deathdealers
https://www.wowhead.com/wotlk/item=45556/belt-of-arctic-life
https://www.wowhead.com/wotlk/item=45553/belt-of-dragons
https://www.wowhead.com/wotlk/item=45554/blue-belt-of-chaos
https://www.wowhead.com/wotlk/item=45562/boots-of-living-scale
https://www.wowhead.com/wotlk/item=45565/boots-of-wintry-endurance
https://www.wowhead.com/wotlk/item=45555/death-warmed-belt
https://www.wowhead.com/wotlk/item=45564/footpads-of-silence
https://www.wowhead.com/wotlk/item=45563/lightning-grounded-boots
https://www.wowhead.com/wotlk/item=45558/cord-of-the-white-dawn
https://www.wowhead.com/wotlk/item=45557/sash-of-ancient-power
https://www.wowhead.com/wotlk/item=45567/saviors-slippers
https://www.wowhead.com/wotlk/item=45566/spellslingers-slippers

**Comment by reminuz** [comment]
https://www.wowhead.com/wotlk/item=45561/treads-of-destiny

**Comment by Afgann** [comment]
fixed
