### ISSUE TITLE
[Achievement] [Key master not counting keys]

### ISSUE THREAD

**Issue by GM-Nightmare** [gamefreedomgit/Frostmourne#2154]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
they have all the keys and the violet hold key, the scarlet key are not counting

**How to reproduce:**
https://cdn.discordapp.com/attachments/1296128258156531754/1296129315603484773/WoWScrnShot_101624_171013.jpg?ex=671129fd&is=670fd87d&hm=5b29f195c6ee8f9cad205dd47884cd65fc614e4d7dbacfa15c0c7e55c0e0d6d9&
https://cdn.discordapp.com/attachments/1296128258156531754/1296129316001681458/WoWScrnShot_101624_171035.jpg?ex=671129fd&is=670fd87d&hm=229beef7b348e5c069df6344a3ddb8c029180dc48d17e58bbdd08e345f2d11c3&

**How it should work:**
the keys should count toward the achievement 

**Database links:**
https://www.wowhead.com/wotlk/achievement=1187/the-keymaster

**Comment by Chaos-within** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/1190
