### ISSUE TITLE
Lightning overload talent needs rework

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#2155]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
https://wotlk.evowow.com/?spell=30675
https://wotlk.evowow.com/?spell=30678
https://wotlk.evowow.com/?spell=30679
Lightning overload talent is broken in many ways: The copied spells that proc from LB and CL have the wrong spell ids, perhaps because of that the procs can cause procs on themselves(or some loop) that causes 2-5 hits in an instant. The wrong procs have lower base damage and scaling than intended so sometimes it evens out but makes the class feel unstable. In addition, chain lighning proc chance calculation is wrong.

**How to reproduce:**
Get talent, use lightning bolt and chain lightning until you get a instant 4x proc.

![WoWScrnShot_101424_150759](https://github.com/user-attachments/assets/d92f405a-296f-4bb1-bb09-05479bd55dea)

![WoWScrnShot_101424_150823](https://github.com/user-attachments/assets/6e4a5c1e-fc55-4e95-8912-6349f1ae325e)

**How it should work:**
1.  The procs from this talent should use the correct spell ids written below.
2. The procs should not proc from themselves or loop (1 LB should only proc 1 copy LB, not 2-5) - there's a chance using the right spell id fixes this automatically.
3. The proc chance from this talent for chain lightning should not be 33% for every chain jump, but use the formula: (chance per jump=33% / number of jumps) - 11% per jump if 3 jumps or 8.25% per jump if glyphed for 4 jumps. (basically should be 33% for the entire cast not per jump)

**Database links:**
Lightning Overload(Rank 3) - Spellid:30679 - Uses wrong copy spells spell ids.
Current wrong proc - Lightning bolt - Spellid:45284 (7 base dmg 0.07 sp scaling)
Can proc on itself 2-5 times extra.
**Correct proc - Lightning bolt - Spellid:49240** (357 base 0.357 sp scaling - exactly half of normal lightning bolt id49238)

Current wrong proc - Chain Lightning - Spellid:45297 (96 base dmg 0.2855 sp scaling)
Can proc on itself 2-5 times extra as well.
**Correct proc - Chain Lightning - Spellid:49269** (487 base 0.2855 sp scaling - exactly half of normal chain lightning id49271)

https://classic.warcraftlogs.com/reports/pkKTjqyvtVA6G7mz#boss=-2&wipes=2&start=255199&end=6342152&type=damage-done&source=14
This log can be used to fact check that these are the correct spell ids.

**Comment by scrublama** [comment]
![WoWScrnShot_101924_031115](https://github.com/user-attachments/assets/d5acd46c-6944-4b35-b201-b1977d9e0071)
![WoWScrnShot_101924_031114](https://github.com/user-attachments/assets/7b53e157-9829-4e5e-9c1c-a9227dd0840a)

Changes just went live,
and this is the result? doesnt seem to be 50% dmg of lightning bolt to me

**Comment by Psychh** [comment]
![Wow_1a7n1tyRxD](https://github.com/user-attachments/assets/bd0c36fe-51e0-43a3-914e-05607a1799fe)
![Wow_5ixHj0fCli](https://github.com/user-attachments/assets/06a14710-e427-4081-acf8-4ee6dcddf190)
![Wow_Zn0jupfHoW](https://github.com/user-attachments/assets/e3493038-1342-4bc1-aabb-9f420d5c0c48)
![Wow_PH3UaQspF5](https://github.com/user-attachments/assets/09290a5b-2f93-4f1c-8b7b-fb736aa35070)

**Comment by Psychh** [comment]
bump
![Wow_X1P0JZd6sm](https://github.com/user-attachments/assets/c95bf6d7-998b-4a1b-95c5-ef5c3e49b400)
![Wow_e01o9WMoHM](https://github.com/user-attachments/assets/dd7e0fe9-7b75-47b0-9197-4b3a8b4a599f)

**Comment by Psychh** [comment]
bump

**Comment by nongrata7793** [comment]
![image](https://github.com/user-attachments/assets/5e32ea2d-5a83-455d-888c-a92370c35f8a)
Problem remains still, pls fix :D

**Comment by Afgann** [comment]
fixed
