### ISSUE TITLE
missing items on POW npc

### ISSUE THREAD

**Issue by vurtne77** [gamefreedomgit/Frostmourne#2156]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** missing ulduar trash items 

**How to reproduce:**check the npc

**How it should work:** should be there :p

**Database links:**https://gyazo.com/7dfbc84d3090c941e32306eae2109536

**Comment by Afgann** [comment]
fixed
