### ISSUE TITLE
tier8 pve shoulders requirement ajustement

### ISSUE THREAD

**Issue by vurtne77** [gamefreedomgit/Frostmourne#2157]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** for now the requirement for shoulders tier8 (pve) is 2000 rating on v3/v5 wihch is a bit not obtainable on the server since even 2v2 is a bit dead so might change the requirement to 2000rating 2v2 not v3 or v5

**How to reproduce:**check the npc

**How it should work:** 

**Database links:**https://gyazo.com/27aeeeb7104535da9aae1b0ee8b2dd9a

**Comment by Riztazz** [comment]
Talked with radegehost, it will be adjusted to pvp version

**Comment by Riztazz** [comment]
fixed, will close once it's live
