### ISSUE TITLE
Mount share on characters

### ISSUE THREAD

**Issue by oXnOi** [gamefreedomgit/Frostmourne#2158]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I've bought "Reins of the Traverler's Tundra Mammoth" for my Horde character "Oksen" for 16k. i thought i was smart and buy it there because of Kirin tor exalted rep. 

I wanted it for my main Char "Maffiaff" which is Allience. 

**How to reproduce:**
Buy mount on a Horde char. 
Expect mount on allience char. 

**How it should work:**
I thought they would share. i talked to a GM ingame though a ticket and they told me it should share. The GM asked me to make this "ticket" in here. 

Best regards

**Comment by oneadanut** [comment]
The mount has race specific to horde and alliance, that's why it doesn't share with the opposite faction.

**Comment by oXnOi** [comment]
So it is intended not to share? will i be able to get it removed from my horde characters then and a refund since its quite expensive, when i was told it should share. the mount's name is also exacly the same on both sides.

**Comment by Afgann** [comment]
fixed

**Comment by WhitemaneChronus** [comment]
If this is approved, there are other mounts like [Mechano-hog](https://www.wowhead.com/wotlk/item=41508/mechano-hog) /[Mekgineer's Chopper](https://www.wowhead.com/wotlk/item=44413/mekgineers-chopper). they look slightly different and the names are different but im posting in case it can be considered.
