### ISSUE TITLE
[dodge] i got a dodge on a spell, spells should never be able to be dodged.

### ISSUE THREAD

**Issue by Acurtis03** [gamefreedomgit/Frostmourne#216]
Description:

when fighting spiders in stonetalon mountains, they were using their ability "toxic spit" on me which does nature damage. occasionally, i would dodge one of the toxic spit spells. dodging a spell shouldn't be able to happen according to this link 

https://wowwiki-archive.fandom.com/wiki/Dodge
    "Only close range melee attacks could be dodged; a ranged attack or a spell cannot be dodged." - from the website

How to reproduce:

go to stonetalen and let the Deepmoss Venomspitter use toxic spit on you and you will see you dodge the spell..

How it should work:

you should never dodge a spell, a spell can miss and or be resisted, not dodged. it also says ranged attacks cant be dodged either, so if someone wants to say "well toxic spit is not a spell its actually a ranged ability" well look again at dodge definition quote from wowwiki, ranged attacks cant be dodged either... so this is bug. :)

evidence of it happening.

![spelldodged](https://github.com/gamefreedomgit/Frostmourne/assets/159967681/354da133-2a77-46d4-b4d1-e51fca0ff8e8)

**Comment by Afgann** [comment]
fixed
