### ISSUE TITLE
[Quest] Soft Packaging – drop rate from Condors

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2160]
During [Soft Packaging](https://www.wowhead.com/wotlk/quest=12046/soft-packaging) there should be 100% drop rate of [Thin Animal Hide](https://www.wowhead.com/wotlk/item=36729/thin-animal-hide) from [Jormungar Tunneler](https://www.wowhead.com/wotlk/npc=26467/jormungar-tunneler) and [Dragonbone Condor](https://www.wowhead.com/wotlk/npc=26483/dragonbone-condor).
Currently Dragonbone Condors drop the Hide very rarely, if at all.
Based on:
https://www.wowhead.com/wotlk/quest=12046/soft-packaging#comments:id=336963

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
