### ISSUE TITLE
[Quest] Springing the Trap – event incomplete

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2163]
[Springing the Trap](https://www.wowhead.com/wotlk/quest=11969/springing-the-trap) is mostly an RP event, culmiantion of long quest chain in Coldarra. This event is incomplete. There is no [Malygos](https://www.wowhead.com/wotlk/npc=26310/malygos) high in the sky getting fireballed by one or two ruby drakes, he only spawns when the player lands.

https://wowpedia.fandom.com/wiki/Springing_the_Trap#Notes
Classic: https://www.youtube.com/watch?v=4I6tqry_Qes&ab_channel=scarything
Cata, oldest video: https://www.youtube.com/watch?v=n_fVmqFpG1o&ab_channel=TomSanGames

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
