### ISSUE TITLE
Shamanistic Rage during Vesax Encoutner

### ISSUE THREAD

**Issue by Tahtoh88** [gamefreedomgit/Frostmourne#2165]
**Description:**
Shamanistic Rage does not provide enough mana to sustain your fight during Vesax Encounter

**How to reproduce:**
Use Shamanistic Rage as an enhancement shaman during vesax boss fight and auto attack

**How it should work:**
Vesax's debuff should empower your mana return while weakening your healing spells during Vesax Encounter

**Database links:**
https://www.wowhead.com/wotlk/spell=68415/corrupted-rage
https://www.wowhead.com/wotlk/spell=30823/shamanistic-rage
https://youtu.be/x9Izsmi-90w?si=vAtlwJANK6Z8_ZbX&t=93 (visual example of mana return)

**Comment by Piootrek** [comment]
Everything works correctly there.
> Vesax's debuff should empower your mana return while weakening your healing spells during Vesax Encounter

I don't know about what debuff you are talking about

**Comment by oneadanut** [comment]
@Piootrek, shamanistic rage is the one of the spells that regenerate mana at Vezax fight. Check below video:
https://youtu.be/x9Izsmi-90w?si=ETDL9kCL_ovJkM7_&t=160

**Comment by Tahtoh88** [comment]
I'm talking about this effect
![image](https://github.com/user-attachments/assets/d75b747a-96ae-4fd7-a0aa-b3434727ce1d)

Here is a vod from this week as an example
https://www.twitch.tv/videos/2277614201?t=01h54m13s
If you check the mana return here, it gives on average 1100 mana per swing (2k average on dual wield)
that mana return is the same on a target dummy
![image](https://github.com/user-attachments/assets/e5c22a88-e9f7-4c2e-bd09-2fc33465a414)

I've linked a classic wow vod from an enhancement pov getting 2k  (4.5k dual swing) mana return per swings

https://youtu.be/cUpjQ5n57rw?si=7fV7DXS1B4TYmsmq&t=297
Another example here on original lich king, where his mana % jumps from 46% to 74% on a swing, which was 3637 mana per swings

Please see this through again,

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
