### ISSUE TITLE
deadly shields

### ISSUE THREAD

**Issue by peninagedola** [gamefreedomgit/Frostmourne#2166]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
https://github.com/gamefreedomgit/Frostmourne/issues/2116   in the last fix only deadly shield with reslience was added, 

**How to reproduce:**

**How it should work:**
deadly shields with sp+crit and sp+mp5 should be added

**Database links:**

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
