### ISSUE TITLE
Emblems of Ascension quartermaster item missing

### ISSUE THREAD

**Issue by mortik13** [gamefreedomgit/Frostmourne#2168]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Missing item [Burdened Shoulderplates] 
**How to reproduce:**
go to Vendor and check in "shoulders" tab

**How it should work:**
should be able to buy

**Database links:**
(https://www.wowhead.com/wotlk/item=40334/burdened-shoulderplates)

**Comment by Afgann** [comment]
fixed
