### ISSUE TITLE
Missing craftable items from Pow npc

### ISSUE THREAD

**Issue by reminuz** [gamefreedomgit/Frostmourne#2169]
Miss craftable items:
https://www.wowhead.com/wotlk/item=45089/plans-battlelords-plate-boots
https://www.wowhead.com/wotlk/item=45550/belt-of-the-titans
https://www.wowhead.com/wotlk/item=45551/indestructible-plate-girdle
https://www.wowhead.com/wotlk/item=45552/plate-girdle-of-righteousness
https://www.wowhead.com/item=45560/spiked-deathdealers
https://www.wowhead.com/wotlk/item=45556/belt-of-arctic-life
https://www.wowhead.com/wotlk/item=45553/belt-of-dragons
https://www.wowhead.com/wotlk/item=45554/blue-belt-of-chaos
https://www.wowhead.com/wotlk/item=45562/boots-of-living-scale
https://www.wowhead.com/wotlk/item=45565/boots-of-wintry-endurance
https://www.wowhead.com/wotlk/item=45555/death-warmed-belt
https://www.wowhead.com/wotlk/item=45564/footpads-of-silence
https://www.wowhead.com/wotlk/item=45563/lightning-grounded-boots
https://www.wowhead.com/wotlk/item=45558/cord-of-the-white-dawn
https://www.wowhead.com/wotlk/item=45557/sash-of-ancient-power
https://www.wowhead.com/wotlk/item=45567/saviors-slippers
https://www.wowhead.com/wotlk/item=45566/spellslingers-slippers
https://www.wowhead.com/wotlk/item=45561/treads-of-destiny

**Comment by Afgann** [comment]
fixed
