### ISSUE TITLE
Tier 6 Warlock Tmog Set (Malefic Set) - Issue with wings

### ISSUE THREAD

**Issue by Noniiy** [gamefreedomgit/Frostmourne#2170]
Description:
The tier 6 head piece for warlocks (tmog included) should allow for wings to pop out everytime a player jumps or falls. However, when doing so, this does not occur. Instead it randomly pops out every 5-10 minutes (which should also occur). 

How to reproduce: 
By jumping or falling when wearing the Maleficient head piece (or Tmog).

How it should work:
Wings should pop out everytime a player jump or falls (in addition to random times).

Database links:
https://www.wowhead.com/transmog-set=669/malefic-raiment#comments

**Comment by Chaos-within** [comment]
A comment from the wowhead linked: 
https://www.wowhead.com/transmog-set=669/malefic-raiment#comments:id=1569497
This did not come out until a patch after 4.2.2.
