### ISSUE TITLE
Yogg orientation bug

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#2171]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Something is causing yogg to ignore his fixed orientation and start looking where the raid members are positioned. This causes players to parry when they attack him. I'm 99% certain that he shouldn't parry at all even from the front, being a blob with no hands, but lack the required proof to make that statement.

**How to reproduce:**
No clue, has happened 2 ids in a row now.

**How it should work:**
Yogg should have fixed orientation, looking at the entrance of his room and nothing should make him turn around.

**Database links:**
https://www.youtube.com/watch?v=iatGk4TOlEA

**Comment by Afgann** [comment]
fixed
