### ISSUE TITLE
Raid Markers - graphics and error message

### ISSUE THREAD

**Issue by yeagerca** [gamefreedomgit/Frostmourne#2172]
**Description:**
1. Raid Markers don't work on development servers yet. You are able to purchase them and activate them from the keyring or via macro, but the graphicals effects do not appear. The graphics do appear on PTR.

2. The error message when attempting to place a raid marker outside of raid is incorrect. They are usable only inside raids.
![image](https://github.com/user-attachments/assets/0e01af4f-689d-4a75-b92c-228e633d6e77)

**How to reproduce:**
Use a raid marker on both Frostmourne and PTR.

**How it should work:**
Yes 👍

**Comment by Aeradel** [comment]
When used properly, I've received no error.

Although I do agree, that it's not working as intended in Live as of this moment. The cool down is registered, but nothing appears.

**Comment by Afgann** [comment]
fixed
