### ISSUE TITLE
RE: Oil of Immolation permanent cooldown

### ISSUE THREAD

**Issue by yeagerca** [gamefreedomgit/Frostmourne#2173]
#1390 
#712
**Description:**
Oil of Immolation is still being affected by the once-per-combat cool down restriction as it if were a potion.

**How to reproduce:**
Try to use many Oil of Immolation in and out of combat.
https://imgur.com/a/USXdtue

**How it should work:**
Oil of Immolation should not be classified as a potion and should not have a once-per-combat usage restriction.

**Database links:**
https://www.wowhead.com/wotlk/item=8956/oil-of-immolation#comments:id=2641695

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
