### ISSUE TITLE
Kalu'ak Fishing

### ISSUE THREAD

**Issue by KryndorX** [gamefreedomgit/Frostmourne#2175]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Got a report from a player about him being doing this event which requires you to fish from fishing schools that contain pygmy fish in order to find a "Speckled Tastyfish", the play been fishing for 58 minutes with no luck , i tried to do the same in PTR realm , spent like 30 minutes and yet no luck. 

**How to reproduce:**
Fish from schools that contains pygmy fish.

**How it should work:**
just want to confirm that the drop rates are working as it suppose to be.

**Database links:**
https://www.wowhead.com/wotlk/item=19807/speckled-tastyfish

**Comment by roblox-oof-dot-mp3** [comment]
Wrong type of fish, the Kal’uak event gives a black-tipped shark which has an extremely low drop chance but you only need one.

**Comment by Piootrek** [comment]
Speckled Tastyfish is required for Stranglethorn Fishing Extravaganza. Are you sure you are talking about Kalu'ak?

**Comment by scrublama** [comment]
it should just be really low drop chance, if you want the salty achievement go do STV fishing event instead

**Comment by Piootrek** [comment]
I checked database and it's correctly added to loot tables with 0.5% chance.

**Comment by KryndorX** [comment]
Ok thank you for clearing this
