### ISSUE TITLE
Raid Markers broken

### ISSUE THREAD

**Issue by Worxeus** [gamefreedomgit/Frostmourne#2176]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Newly added raid markers are not working at all, using Whitemane client and using Whitemane 3.5 patch. They just go on cooldown but you can't see them

**How to reproduce:**
Use raid markers in raid

**How it should work:**
Raid markers should show (:

**Database links:**

![WoWScrnShot_101924_164025 - Copy](https://github.com/user-attachments/assets/00675b54-1640-49b0-aa1a-f3574c9a6fab)
![WoWScrnShot_101924_164025](https://github.com/user-attachments/assets/dbc74dd8-2bfc-4a2b-a75b-4c54a763adf9)

**Comment by Worxeus** [comment]
EDIT: I am using whitemane client xd

**Comment by yeagerca** [comment]
They work on PTR #2172

**Comment by Afgann** [comment]
fixed
