### ISSUE TITLE
Mass dispell may remove friendly Divine Sacrifice from self, party or raid members

### ISSUE THREAD

**Issue by Zaword** [gamefreedomgit/Frostmourne#2177]
**Description:** Friendly Divine Sacrifice can be dispelled by priest Mass Dispell in some scenarios. After some test with a guild member, we found that it may happen when the paladin has both Divine Sacrifice and Divine Guardian buff on himself (usually paladins have a macro to cancel aura of Divine Sacrifice)
See screenshot combat log.
![Divinesacrifice](https://github.com/user-attachments/assets/be66bae9-466a-4b36-b871-ad67c146f46c)

**How to reproduce:** Have a priest and a Paladin in the same party, let the Paladin use the standard spell Divine Sacrifice (without macro to cancelaura), then use mass dispell.

**How it should work:** Mass dispell shouldn't remove friendly buffs.

**Database links:**
https://www.wowhead.com/wotlk/spell=64205/divine-sacrifice
https://www.wowhead.com/wotlk/spell=32375/mass-dispel

**Comment by sputnikk** [comment]
can't zoom in the picture sadly, but if the two of them are different factions it might the classic crossfaction bug

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
