### ISSUE TITLE
Dungeon Deserter Debuff

### ISSUE THREAD

**Issue by OrceMaceski** [gamefreedomgit/Frostmourne#2178]
A player should not receive a dungeon deserter debuff if he/she leaves the dungeon after the 15th minute mark

**Comment by OrceMaceski** [comment]
I had a regular hc run in Utgarde Pinnacle, wiped 2 times on 3rd boss (Skadi gauntlet), in between there were also wipes on trash, people left, forgot to reactivate lfd for a couple of minutes then waited people to rejoin, i know that i didnt have the exact timer but according to my long running CDs was well above the 15th minute mark, left in frustration and received the deserter debuff.

The other time was in Violet Hold Asc where the group wiped on 2nd boss twice with an overly confident but not well geared group, now thats  24 waves with pause in between, well above the 15th minute mark (also tracked by long runing CDs), left in frustration and received deserter debuff.

**Comment by Piootrek** [comment]
UltraNix asked for proof it should not be applied after 15 minutes.

**Comment by OrceMaceski** [comment]
Nevermind, confused the timing with internal requeue system
