### ISSUE TITLE
[Reoccuring bug] Sara's targets

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#2179]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Currently on live Sara does not target the receiver of her spells. This is happening on 10nm 10hc, have not yet done 25 but it may be happening there as well.

**How to reproduce:**
do yogg p1 p2

**How it should work:**
Sara should show the target of her spells when casting: Sara's blessing, Sara's fervor, Psychosis, and Malady

**Database links:**

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
