### ISSUE TITLE
DK last starting zone quest not working properly

### ISSUE THREAD

**Issue by qwerty4444444444444444444444444** [gamefreedomgit/Frostmourne#218]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
"The Light of Dawn Uncovered" DK quest doesn't give hp/dmg buff.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by qwerty4444444444444444444444444** [comment]
I mean you also get one shot with the buff? Idk if its supposed to be like this. Or you just need to afk on side

**Comment by Iramtempus** [comment]
> I mean you also get one shot with the buff? Idk if its supposed to be like this. Or you just need to afk on side

Did you mass AOE? if so you will get one shot, as you did on retail.
But as you seem to have had a very different time, I will re-level a DK to check.

**Comment by Iramtempus** [comment]
So here are my findings;
You do get the buff.
They do indeed hit way to hard (Got critted for 50k+ from 1 attack)
The NPC "Defender of the light" have 2x health of original and hit harder.
Attached link to the video on whitemane.
With thta being said: You do respawn quite quickly as the spirit healer is next to the fight, should you die you can still complete the RP. This should be a low-priority ticket IMHO.

Youtube Link:
https://www.youtube.com/watch?v=VhdQqH8fTLs

Reference for the NPC.
https://wotlk.evowow.com/?npc=29174

**Comment by qqdbpp** [comment]
when the 5 minute timer for the battle starts, run to lights hope chapel, log out for 14 minutes, log back in, quest insta complete and you get to do something else instead of wasting 14 minutes for no reason. ta-da!

**Comment by Iramtempus** [comment]
> when the 5 minute timer for the battle starts, run to lights hope chapel, log out for 14 minutes, log back in, quest insta complete and you get to do something else instead of wasting 14 minutes for no reason. ta-da!

As much as this is true and I tend to just AFK, this is still a valid bug report.

**Comment by RadeghostWM** [comment]
No more reports of this, closing
