### ISSUE TITLE
Hardcore

### ISSUE THREAD

**Issue by KryndorX** [gamefreedomgit/Frostmourne#2180]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
If you have 2 characters, both are hardcore, and one of them sends a mail to the other one, then one of those characters reach level 80, the mail will no longer be eligible .

**How to reproduce:**
Use 1 hardcore character to send a mail to another, and make the first character get level 80 (it will be no longer a hardcore character which applies the rule of "Hardcore and normal characters cannot interact") , then log to the other character that is still hardcore and try to loot from the mailbox.

**How it should work:**
This is a bug that got reported few times in a short period, however since you sent a mail to someone, and the target was able to receive it, it should be always available from his mailbox and eligible.

**Database links:**

**Comment by Piootrek** [comment]
This issue has been fixed currently and should work. However, I've found an issue that could prevent taking items from a mailbox. 
Fixed, I will close this issue once the fix comes live.
