### ISSUE TITLE
Salvage loot missing from Mechanical Ulduar Bosses

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#2181]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
https://wowwiki-archive.fandom.com/wiki/Flame_Leviathan#Salvage
https://www.wowhead.com/wotlk/npc=33432/leviathan-mk-ii
https://www.wowhead.com/wotlk/npc=33293/xt-002-deconstructor#drops;mode:n25
https://www.wowhead.com/wotlk/npc=33113/flame-leviathan

In all modes and difficulties, using engineering salvage on one of these bosses' corpse should have a chance to drop goblin bike parts, cobalt and saronite bars, froststeel tubes, and a titansteel bar. Currently these mentioned items are not present in the salvage table.

**How to reproduce:**
Salvage one of the 3 mechanical bosses on any difficulty, notice items above never drop.

**How it should work:**
Drops should be added as follows on all 3 bosses:
https://www.wowhead.com/wotlk/item=44500/elementium-plated-exhaust-pipe quantity: 1 dropchance: 1%
https://www.wowhead.com/wotlk/item=44499/salvaged-iron-golem-parts quantity: 1 dropchance: 1%
https://www.wowhead.com/wotlk/item=44501/goblin-machined-piston quantity: 1 dropchance: 1%
https://www.wowhead.com/wotlk/item=37663/titansteel-bar quantity: 1 dropchance: 50%
https://www.wowhead.com/wotlk/item=36916/cobalt-bar quantity: 16-20 dropchance: 70%
https://www.wowhead.com/wotlk/item=36913/saronite-bar quantity: 16-20 dropchance: 70%
https://www.wowhead.com/wotlk/item=39683/froststeel-tube quantity: 2-3 dropchance: 35%
![drops](https://github.com/user-attachments/assets/a3642bc7-a66d-489d-a68a-b020589b460d)

**Database links:**
https://www.wowhead.com/wotlk/npc=33293/xt-002-deconstructor#comments:id=680680:reply=109827
"Tonight I managed to salvage 2 Goblin Pistons from XT on normal so it seems that salvagable bosses in ulduar all have a chance to drop the parts for the chopper."
Most of the bosses on wowhead show the items dropping as part of their normal loot table instead of having a separate salvage tab for proof reference.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
