### ISSUE TITLE
[Ulduar Trash] Misguided Nymph

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2182]
**Description:**
The mob Misguided Nymph from Freya trash casts Bind Life on itself, but dispelling it, does no aoe damage.

**How it should work:**
![image](https://github.com/user-attachments/assets/705edf6f-cce3-4723-8bf6-0bf2c528980d)

**Database links:**
https://www.wowhead.com/wotlk/npc=33355/misguided-nymph#abilities;mode:n10
https://www.wowhead.com/wotlk/spell=63082/bind-life

**Comment by Piootrek** [comment]
Fixed, I will close this once the fix comes live.

**Comment by oneadanut** [comment]
Still not working.

**Comment by Piootrek** [comment]
> Still not working.

Are you sure? I just checked and it works

**Comment by oneadanut** [comment]
Last night, the Bind Life was dispelled 2 times and no meele died. Both times, the Bind life was casted on the tree mob and not on herself. If dispelled, It should do around 30k dmg, killing everyone in the range, aka meeles.
As far as i know, she should cast the buff only on herself. Maybe, this causes the bug, when she casts it on a different mob.

**Comment by Piootrek** [comment]
It works for me even if it's casted on another target 
![image](https://github.com/user-attachments/assets/00a9eeaf-b542-4fa6-8344-28c8b1675be8)

**Comment by oneadanut** [comment]
Spellsteal from mage

**Comment by Piootrek** [comment]
Fixed, I will close this once the fix comes live.
