### ISSUE TITLE
Val'Anyr Proc is bugged and procs very rarely (once in 50 casts)~

### ISSUE THREAD

**Issue by Tetrahydrx** [gamefreedomgit/Frostmourne#2183]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)

[//]: # (https://www.wowhead.com/wotlk)
https://www.wowhead.com/wotlk/item=46017/valanyr-hammer-of-ancient-kings

**Description:**
The Val'Anyr procrate seems to be too low, it should be 10% on any hot or direct spell heal with a 45s Internal cooldown. The cooldown works correctly but the procrate seems to be bugged.

**How to reproduce:**
Cast Holy Light on yourself/next to 2-3 other players with the Holy Light Glyph while Val'Anyr is equipped.

**How it should work:**
10% Proc on any hot or direct spell.

**Database links:**
https://www.wowhead.com/wotlk/item=46017/valanyr-hammer-of-ancient-kings

(Proc chance: 10%, 45s cooldown)

**Comment by Chaos-within** [comment]
It doesn't proc on 100% overhealing. Your spell must do some healing, not sure if this was taken into account in your testing.
