### ISSUE TITLE
[PoW] Training Dummies remain visible in Duel Phase

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#2184]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Training Dummies remain visible during duel phase thus giving unfair adavantage to players that shouldn't exist in 1v1, or arena scenario.

**How to reproduce:**

**How it should work:** In duel phase nothing but stuff related to people dueling each other should be visible to both parties.

**Database links:**

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
