### ISSUE TITLE
[Item] The Horseman's Baleful Blade

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2185]
**Description:**
The Horseman's Baleful Blade that drops from Headless Horseman should summon 3 guardian pumpkins that help you kill enemies.
The sword is not always summoning 3 pumpkins, sometimes it doesn't summon any of them. Also, according to wowhead comments, they should do around 4k damage in total. Here, they barelly do 1k damage in total (all 3).

**Database links:**
https://www.wowhead.com/wotlk/item=49128/the-horsemans-baleful-blade#comments

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
