### ISSUE TITLE
[Black Temple Timewalking] Supremus missing phase change emote

### ISSUE THREAD

**Issue by broizter** [gamefreedomgit/Frostmourne#2187]
When Supremus exits the kiting phase and goes back to normal phase he is supposed to send the emote "Supremus punches the ground in anger!", it's currently not happening. It's important because it's used in DBM to detect the phase changing.

**Comment by broizter** [comment]
![bild](https://github.com/user-attachments/assets/70a922a9-8ddb-48d9-bd41-f4644d56339a)

**Comment by Riztazz** [comment]
fixed, will close once it's live
