### ISSUE TITLE
[NPC] Lieuetenant Icehammer – Vrykuls around should be dead

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2189]
[Lieutenant Icehammer](https://www.wowhead.com/wotlk/npc=24634/lieutenant-icehammer#comments) is Alliance quest giver near Nifflevar. He and his two Defenders are surrounded by hostile NPCs. These NPC should be dead.

2:25 https://www.youtube.com/watch?v=2oTWa6zU2Wo&ab_channel=Bue
0:35 https://www.youtube.com/watch?v=_ktZw3kguR0&ab_channel=TomSanGames

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
