### ISSUE TITLE
Vezax and Yogg bugs are all back

### ISSUE THREAD

**Issue by roblox-oof-dot-mp3** [gamefreedomgit/Frostmourne#2193]
**Description:**
Tonight in Ulduar, we noticed the previously fixed bugs with Vezax and Yogg all seemed to be happening again. We had:

- > melee shadow crash on vezax
- Mark of faceless in melee (even on MT)
- yogg spawning tentacles inside the center pool (sometimes unreachable) 
- Players being teleported underneath the brain room and being stuck

Not sure why these are all happening again suddenly, was a commit accidentally reverted?

**Comment by Piootrek** [comment]
Do you have any vod of this raid? On Vezax melee players can be targeted by Shadow Crash and Mark of Faceless if there are no players above 15 yards from the boss.

**Comment by broizter** [comment]
![WoWScrnShot_102124_210306](https://github.com/user-attachments/assets/9da9130f-c4c2-4909-ab96-78d943f7ef51)
From our raid 2 days ago.

**Comment by roblox-oof-dot-mp3** [comment]
> Code wasn't reverted. Do you have any vod of this raid? On Vezax melee players can be targeted by Shadow Crash and Mark of Faceless if there are no players above 15 yards from the boss. Edit: I fixed Constrictor Tentacles sometimes pulling players under textures, cannot reproduce bug with spawned tentacles inside the center pool

I don’t have any screenshots, but I can confirm we had players more than 15 yards away. We had about 3 casters and 2 healers all out, with our healers being the maximum range they could be while reaching the tank. 

The tentacles as well were specifically constrictor tentacles, they kept spawning inside the pool when we were just starting phase 2

**Comment by Piootrek** [comment]
Constrictor Tentacles are spawning around player's location. Are you sure there wasn't anyone inside? Maybe with lag or disconnect?

**Comment by Piootrek** [comment]
Changed a bit Mark of the Faceless targeting algorithm. It will have a lower chance to target melee player when there are not enough rangeds above 15 yards from the boss. Tank shouldn't be targeted at all unless he is the last valid target. 
Shadow Crash targeting algorithm looks good to me. Please make a video next time when you fight with Vezax.
