### ISSUE TITLE
Eye of the Broodmother and Illustration of the Dragon Soul

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2194]
**Description:**
These 2 trinkets don't act the same way. For example Eye of the Broodmother procs from heal over time effects, each tick stacking the buff, while Illustration of the Dragon Soul doesn't.

**How it should work:**
Make both act the same way please.

**Comment by Riztazz** [comment]
Proof that it should act in similar manner please

**Comment by oneadanut** [comment]
They have the same tooltip.

**Comment by oneadanut** [comment]
You either make Eye to not proc from hots or make Illu proc from hots. It's not a big issue since they proc full stacks from one gift of the wild, it's just they act different having the same tooltip.

**Comment by oneadanut** [comment]
@Piootrek you fixed these 2 trinkets, can you look into this?

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
