### ISSUE TITLE
[NPC] Deranged Explorer – Missing emotes

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2196]
[Deranged Explorers](https://www.wowhead.com/wotlk/npc=23967/deranged-explorer) should have /say emotes. They have none. Some might be on aggro, some should be said randomly. Same goes for [Squeeg Idolhunter](https://www.wowhead.com/wotlk/npc=24048/squeeg-idolhunter)
https://wowpedia.fandom.com/wiki/Deranged_Explorer
https://www.wowhead.com/wotlk/npc=23967/deranged-explorer#comments:id=445812

**Comment by Piootrek** [comment]
Added missing texts for Deranged Explorers, but I couldn't find in the Internet texts for Squeeg Idol hunter.
I will close this issue once the fix comes live.
