### ISSUE TITLE
[Quest] Steel Gate Patrol – Missing Gargoyle Strike

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2198]
During [Steel Gate Patrol](https://www.wowhead.com/wotlk/quest=11391/steel-gate-patrol) player needs to kill the gargoyles.
[Gjalerbron Gargoyles](Gjalerbron Gargoyle) are missing their spell [Gargoyle Strike](https://www.wowhead.com/wotlk/spell=43803/gargoyle-strike) (and 43804), they do only melee attacks, however they keep their distance from player so unless the player flies right into them, they are harmless.
Note about peculiar behaviour of the Gargoyle Strike: https://www.wowhead.com/wotlk/quest=11391/steel-gate-patrol#comments:id=635472

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by Greywolf59** [comment]
Thank you for all the work you are doing even on the smallest of reports. It is really deeply appreciated! :)
