### ISSUE TITLE
[Quest] Rejek's Dailies = wrong completion events

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2200]
[Rejek](https://www.wowhead.com/wotlk/npc=29043/rejek#starts) is a quest giver for Frenzyheart. Each day he offers one of the dailies randomly.
Whichever quest player completes (I did not get [Rejek: First Blood](https://www.wowhead.com/wotlk/quest=12734/rejek-first-blood) yet, but it is most likely also the case) handing it in triggers completion event belonging solely to [A Hero's Headgear](https://www.wowhead.com/wotlk/quest=12758/a-heros-headgear).

Hero's Headgear tirggers event properly.
[Strength of the Tempest](https://www.wowhead.com/wotlk/quest=12741/strength-of-the-tempest) should not have any event.
[Rejek: First Blood](https://www.wowhead.com/wotlk/quest=12734/rejek-first-blood) should not have any event.
[The Heartblood's Strength](https://www.wowhead.com/wotlk/quest=12732/the-heartbloods-strength) should have a different event tied to it.

https://wowpedia.fandom.com/wiki/A_Hero%27s_Headgear#Notes
https://wowpedia.fandom.com/wiki/Rejek:_First_Blood#Notes
https://wowpedia.fandom.com/wiki/Strength_of_the_Tempest#Notes
https://wowpedia.fandom.com/wiki/The_Heartblood%27s_Strength#Completion

**Comment by Piootrek** [comment]
Fixed starting RP event upon every quest completion. 
I couldn't find any video with The Heartblood's Strength event, if you find any please add it to this report.

**Comment by Greywolf59** [comment]
@Piootrek 
Wotlk Classic 2:52 https://www.youtube.com/watch?v=IgHyWCYcIL8&ab_channel=BloodyFoxGaming

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
