### ISSUE TITLE
[Quest][Event] Hallow's End dailies "Let the Fires Come!" and "Stop the Fires!" not giving experience to HC characters

### ISSUE THREAD

**Issue by emirie1** [gamefreedomgit/Frostmourne#2201]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
At the very least the two mentioned dailies ["Let the Fires Come!"](https://www.wowhead.com/wotlk/quest=12135/let-the-fires-come) and ["Stop the Fires!"](https://www.wowhead.com/wotlk/quest=11131/stop-the-fires) are not giving their listed exp to hardcore characters. I have personally experienced this issue myself and other hardcore characters in Deathwalkers have also experienced this issue. We are not sure if this is intentional to stop hardcore characters from getting easy exp or if it is truly a bug. We are also not sure if the third daily, [Smash the Pumpkin](https://www.wowhead.com/wotlk/quest=12133/smash-the-pumpkin) is affected by this as well or not, but it seems likely. Additionally, this is on an alliance hardcore character. I am not sure if it also applies to horde hardcore characters or not.

After submitting a ticket, Kryndor said that they tested it and it seems to give the exp. Given the nature of hardcore and how it is not affected by any exp modifiers it seems plausible that this could be intentional but clarification would be greatly appreciated.

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/wotlk/quest=12135/let-the-fires-come
https://www.wowhead.com/wotlk/quest=11131/stop-the-fires
https://www.wowhead.com/wotlk/quest=12133/smash-the-pumpkin

**Comment by Ka-Anor** [comment]
I've had this on all of my characters - only get exp the first time I do the quest, any subsequent completions give 0 exp, despite it being listed as reward on quest.

**Comment by Piootrek** [comment]
Fixed, I will close this once the fix comes live.
