### ISSUE TITLE
[Quest] [NPC] March of the Giants – Giants without buff, already transformed

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2203]
[March of the Giants](https://www.wowhead.com/wotlk/quest=11365/march-of-the-giants) sends player to kill [Runed Stone Giant
](https://www.wowhead.com/wotlk/npc=24329/runed-stone-giant) and analyze their corpse. There is lots of Runed Stone Giants walking in the area. Quest itself works fine.

ISSUE 1: These Giants are missing their abilities.
Based on this https://www.wowhead.com/wotlk/quest=11365/march-of-the-giants#comments:id=499023 and https://wowpedia.fandom.com/wiki/March_of_the_Giants#Notes, they are missing [Rune Fist](https://www.wowhead.com/wotlk/spell=49717/rune-fist) buff and thus do not cast [Dark Rune](https://www.wowhead.com/wotlk/spell=49718/dark-rune)

ISSUE 2: Scripting
Issue 1 might be rooted in how the area is scripted. Based on the same wowhead comment there are supposed to be [Stone Giants](https://www.wowhead.com/wotlk/npc=23725/stone-giant) roaming about/walking into the runes. When they step into the rune, they will get 30s buff [Bind Stone Giant](https://www.wowhead.com/wotlk/spell=43270/bind-stone-giant), which will transform them into Runed Stone Giants and gives them Rune Fist ability.
Currently there are no Stone Giants roaming about, there is only two of them standing still.
7:35 https://www.youtube.com/watch?v=hqbTJcEWTkA&ab_channel=scarything
Video shows Runed Giant stepping into rune and the process of how the Runed Giants are created. Shows the Bind Stone Giant buff and Rune Fist buff/ability.
No video however shows **Stone Giants** walking into the runes and getting transfromed. In every video there are only Runed Stone Giants walking around, same as on our server.

I think Issue 2 can be safely omitted, however adding the abilities to giants might be nice.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
