### ISSUE TITLE
[Quest] Rune of Command – Guardian missing abilities

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2204]
In quest [The Rune of Command,](https://www.wowhead.com/wotlk/quest=11348/the-rune-of-command#comments) player is suppsoed to use Quest Item on [Stone Giant](https://www.wowhead.com/wotlk/npc=23725/stone-giant), spawning [Enthralled Stone Giant](https://www.wowhead.com/wotlk/npc=24346/enthralled-stone-giant#abilities) guardian and use this guardian's help to kill [Binder Murdis](https://www.wowhead.com/wotlk/npc=24334/binder-murdis).
Binder Murdis is also not using his abilties Flame Shock and Rune of Binding.

[Enthralled Stone Giant](https://www.wowhead.com/wotlk/npc=24346/enthralled-stone-giant#abilities) is missing its abilities.
https://www.wowhead.com/wotlk/quest=11348/the-rune-of-command#comments:id=565654
https://wowpedia.fandom.com/wiki/Enthralled_Stone_Giant?so=search

https://www.youtube.com/watch?v=Jl6dDaU5zwk&ab_channel=Alex = visible damage from Flame Shock.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
