### ISSUE TITLE
XT-002 not dropping loot after dying to curse of doom

### ISSUE THREAD

**Issue by demolulz** [gamefreedomgit/Frostmourne#2205]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:Our Ulduar group killed XT with curse of doom while heart was up which spawned a doomguard that was glowing like it was lootable(noone could loot) but XT was not. **

![WoWScrnShot_102424_194434](https://github.com/user-attachments/assets/093edd58-f958-4cce-b58c-5cb5bc4e9136)

**How to reproduce:**

**How it should work:**

**Comment by Afgann** [comment]
fixed
