### ISSUE TITLE
time lost proto drake not drop mount

### ISSUE THREAD

**Issue by qqdbpp** [gamefreedomgit/Frostmourne#221]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**

: - ((((

![image](https://github.com/gamefreedomgit/Frostmourne/assets/159703358/bf927609-6059-4a37-8498-f4ddc5b7d4c7)

**Comment by qqdbpp** [comment]
it not in bag either

**Comment by Afgann** [comment]
fixed
