### ISSUE TITLE
Warsong Gulch Bug

### ISSUE THREAD

**Issue by Tellytubby123** [gamefreedomgit/Frostmourne#2215]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Hi there's a bug in wsg where if u have the flag and use iceblock cancel and try repick the flag it doesnt let u there is like a 5 second delay and same if u stealth also if u do slow fall mount drop flag and mount up to try get speed and repick it for a longer jump u also cant repick it theres a weird delay also some of the jumps are weird like the ally top of tunnel one when u jump up the right side its different to blizz wotlk plz can u fix these 

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by oneadanut** [comment]
When you drop the flag, you get a debuff for around 4 second that interdicts you to repick it.

**Comment by Tellytubby123** [comment]
Why is this though? This is different to retail WoTLK right so should be fixed?

**Comment by Riztazz** [comment]
This is blizzlike, those cooldown spells are also from blizzard, closing
