### ISSUE TITLE
Blink 

### ISSUE THREAD

**Issue by Tellytubby123** [gamefreedomgit/Frostmourne#2216]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Hi if i jump and blink it doesn't port me forward plz can u fix this?

**How to reproduce:**

**How it should work:**
U should be able to jump while blinking and blink forward

**Database links:**

**Comment by Riztazz** [comment]
It works fine for me every time i jump and blink. Where exactly did this happen to you or is it in entire world? Could i maybe get a video of it if it's everywhere?

**Comment by Tellytubby123** [comment]
Hi it happens everywhere it kinda stalls

**Comment by Riztazz** [comment]
Any chance i could get a video please? I really cannot reproduce this, maybe video will give me some hint
