### ISSUE TITLE
[CORE] Weapon Swap Macro in Combat

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#2217]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** wep swap macros work in a rly weird and unintended manner right now.

Let's take a look at this one:

#showtooltip Shield of Righteousness(Rank 2)
/equip Deadly Gladiator's Libram of Justice
/equip Deadly Gladiator's Gavel
/equip Deadly Gladiator's Redoubt
/cast Shield of Righteousness(Rank 2)

Currently only the libram is swapped, the other 2 slots aren't, until a gcd is spent.

**How to reproduce:**

**How it should work:** 
It should: equip all 3 items under the same GCD, if a gcd is already in progress when pressed it should equip all 3 items and restart the gcd, unless casting.
If all 3 items are equipped it should cast shield of right.

Funnily enought, the other way around it seems to work:

#showtooltip
/cast [worn:Shields] Shield of Righteousness; [worn:two-hand] Crusader Strike
/equip Sword of Justice
/equip Libram of Divine Purpose
/startattack

Casts the spell and on the same gcd swaps both items.
It may be the shield slot that causes the issue, not sure

**Database links:**

**Comment by Riztazz** [comment]
fixed, will close once it's live
