### ISSUE TITLE
General Vezax - saronite vapors

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#2218]
The problem is, saronite vapors should be immune to any Aoe damage so that any classes can press their full Pve rotation without fear of spoiling the HM mode.  We do not have this immunity on our server.
https://www.wowhead.com/npc=33488/saronite-vapors

![image](https://github.com/user-attachments/assets/e134352e-cd0a-4865-8fc5-0ebf558d3a75)

**Comment by Chaos-within** [comment]
This was added in classic and wasn't apart of original 3.3.5

**Comment by Riztazz** [comment]
https://us.forums.blizzard.com/en/wow/t/general-vezax-aoe-bug/1616960/3

Further confirming this, closing

**Comment by wowclassic1234** [comment]
Open again





> https://us.forums.blizzard.com/en/wow/t/general-vezax-aoe-bug/1616960/3
> 
> Further confirming this, closing

NO. Open again.
Vezax 2009
https://youtu.be/QZcnd7mXVhQ?t=105

**Comment by wowclassic1234** [comment]
https://youtu.be/QZcnd7mXVhQ?t=105

Zero damage in the melee zone.

**Comment by wowclassic1234** [comment]
https://youtu.be/O4gzcK3z6Vw?t=84 
Zero damage

**Comment by Chaos-within** [comment]
They appear to be phased to AoE where it won't even trigger immune. This warriors WW at 45 seconds is very clear.
https://youtu.be/-1b96-WHi_8?si=GTV6TbyHvk4epnl4&t=44

**Comment by wowclassic1234** [comment]
> They appear to be phased to AoE where it won't even trigger immune. This warriors WW at 45 seconds is very clear. https://www.youtube.com/watch?v=-1b96-WHi_8&t=44s

Yes, so do not rush to throw fakes, especially from stupid comments that are not confirmed by anything.

**Comment by Chaos-within** [comment]
> > They appear to be phased to AoE where it won't even trigger immune. This warriors WW at 45 seconds is very clear. https://www.youtube.com/watch?v=-1b96-WHi_8&t=44s
> 
> Yes, so do not rush to throw fakes, especially from stupid comments that are not confirmed by anything.

To be fair your post included no verifiable evidence and from research without completely deep diving into it, it appeared as if it was not the case.

**Comment by wowclassic1234** [comment]
> > > They appear to be phased to AoE where it won't even trigger immune. This warriors WW at 45 seconds is very clear. https://www.youtube.com/watch?v=-1b96-WHi_8&t=44s
> > 
> > 
> > Yes, so do not rush to throw fakes, especially from stupid comments that are not confirmed by anything.
> 
> To be fair your post included no verifiable evidence and from research without completely deep diving into it, it appeared as if it was not the case.

I showed a screenshot from the classic wow and that's enough. And no need to say that this is a different game and everything works in a new way. The differences are minimal compared to 2009 in terms of standard mechanics. The difficulty was only increased, but no more, but this problem does not relate to complexity.

**Comment by Chaos-within** [comment]
> > > > They appear to be phased to AoE where it won't even trigger immune. This warriors WW at 45 seconds is very clear. https://www.youtube.com/watch?v=-1b96-WHi_8&t=44s
> > > 
> > > 
> > > Yes, so do not rush to throw fakes, especially from stupid comments that are not confirmed by anything.
> > 
> > 
> > To be fair your post included no verifiable evidence and from research without completely deep diving into it, it appeared as if it was not the case.
> 
> I showed a screenshot from the classic wow and that's enough. And no need to say that this is a different game and everything works in a new way. The differences are minimal compared to 2009 in terms of standard mechanics. The difficulty was only increased, but no more, but this problem does not relate to complexity.

Believe it or not, a screenshot (which could be from anywhere) is not _verifiable_ proof...

**Comment by AlucardHellsingChapel** [comment]
Whirlwind still hits the vapors @Piootrek

**Comment by Riztazz** [comment]
Me, not piootrek, i'll take a further look

**Comment by Tahtoh88** [comment]
Spells that affected saronite vapors in my yesterday run
![image](https://github.com/user-attachments/assets/6b60b418-5858-45b2-8f77-578788991b64)
Magma totem can also hit them

**Comment by Riztazz** [comment]
I've fixed the underlying issue but realm was not yet updated

**Comment by Riztazz** [comment]
Test now please
