### ISSUE TITLE
Thorim - unbalancing strike

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#2219]
The problem is that the Unbalancing Strike ability lacks the mechanics of repeated use of the spell (the ability must be on spam, every 15 seconds), as a result of which the rotation of the use of this ability by the boss is disrupted. There are times when the Unbalancing Strike timer coincides with the chain lightning timer and the boss does not use Unbalancing Strike and it can last for 40-60 seconds + this error breaks the DBM and the timer stops showing. You also need to adjust the timer for repeated use of the ability, it costs 20-25 seconds for us. It should be 15.

https://www.wowhead.com/wotlk/npc=32865/thorim
https://www.wowhead.com/wotlk/spell=62130/unbalancing-strike

![image](https://github.com/user-attachments/assets/e1faac5e-2047-4c6a-bee6-d8c729b35069)

**Comment by Riztazz** [comment]
Which dbm are you using? The one adjusted for classic?

**Comment by Riztazz** [comment]
fixed, will close once it's live
