### ISSUE TITLE
[Quest] Master and Servant

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#222]
**Description:**
The robots don't assist you in combat once you use the item on their corpse

**How to reproduce:**
Kill a bot
Use quest item (you get credit)
Corpse just disappear

**How it should work:**
A friendly version of the mob should spawn following using the item on the corpse and assist you in combat for a min or so

**Database links:**
https://www.wowhead.com/wotlk/quest=11730/master-and-servant

**Comment by Afgann** [comment]
fixed
