### ISSUE TITLE
Steelbreaker - fusion-punch/static-disruption

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#2221]
The problem is that when the timers on the fusion punch and static disruption abilities coincide at the same time, steelbreaker starts using fusion punch and at the same moment interrupts it and uses static disruption. In situations of this kind, there should be no interruption of abilities, and if the timer for them matches, then they should be applied after each other. Both abilities must be scripted for reuse in case of failure. It doesn't work on our server. In a fight with the mimiron boss, a similar problem is observed, quite often I see when the boss interrupts the p3wx2-laser-barrage  ability during charging.

https://www.wowhead.com/spell=63494/static-disruption
https://www.wowhead.com/spell=61903/fusion-punch
https://www.wowhead.com/npc=32867/steelbreaker
https://www.wowhead.com/spell=63293/p3wx2-laser-barrage

**Comment by Piootrek** [comment]
Do you have any vod from this raid? Steelbreaker is already scripted as you said and he cannot interrupt one ability with another. There must be another reason why he interrupted the cast, but I cannot reproduce this.

**Comment by wowclassic1234** [comment]
> У вас есть видео с этим рейдом? Стальной Рыцарь уже прописан в сценарии, как вы и сказали, и он не может прерывать одну способность другой. Должно быть, есть другая причина, по которой он прервал каст, но я не могу это воспроизвести.

https://www.twitch.tv/videos/2284199748?t=0h30m26s



Here the caste of his ability will be shown and there it will be seen how it was interrupted and he began to use another one.
![image](https://github.com/user-attachments/assets/8ba1471b-317a-406b-a86d-ee2e20455323)

**Comment by wowclassic1234** [comment]
> Do you have any vod from this raid? Steelbreaker is already scripted as you said and he cannot interrupt one ability with another. There must be another reason why he interrupted the cast, but I cannot reproduce this.

Mimiron Interrupts Laser Barrage 
https://www.twitch.tv/videos/2278434110?t=2h6m19s

**Comment by Piootrek** [comment]
Fixed Steelbreaker, but still cannot reproduce Mimirion issue.

**Comment by wowclassic1234** [comment]
> Fixed Steelbreaker, but still cannot reproduce Mimirion issue.

The bug on mimiron does not work every time and most likely only in HM mode. It seems to me that you need more attempts to reproduce this. In the video, I showed how the bug happens. At the moment, unfortunately, I don't have any more information that would help you.
