### ISSUE TITLE
Illidan - Parasitic shadowfiend + potential server crash abuse

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#2222]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
 - Fix Parasitic Shadowfiend level and scaling.
 First of all this fix is worrying because it's only going to make the issues I'm describing more prevalent. I can't even test what this "scaling" means since ptr does not apply fixes anymore #2188 
 
 Currently on the server one parasitic shadowfiend debuff is spawning two mobs which, if they hit you, infect you with another parasitic shadowfiend debuff. This creates a dangerous EXPONENTIAL mobspawn loop. I believe this is the reason warmane removed the possibility of mobs from applying the debuff entirely and only illidan does it in their past timewalk, boosting the mob hp instead.
 However if you simply boost the mob hp without addressing the mechanic it becomes a problem.
 Classic tbc addressed this issue in a different way which i am going to explain in the how it should work section.

I have managed to crash the PTR server twice using this mechanic, realistically getting 6000+ debuffs will kill you and end the exponential loop before it leads to crash, However, where there's a will there's a way and players with malicious intent can figure out eventually how to stay alive on the lv70 version of BT using healers and cooldowns most likely.

**How to reproduce:**
https://vimeo.com/1024657642?share=copy#t=0

**How it should work:**
https://youtu.be/CXxxa0UIQ-I?si=dJSBZM7kW0LGzMla&t=3443
The way this mechanic should work as evidenced in the classic tbc video above:
1. Shadowfiends hp makes em die in 2 hits from tbc characters (3.5k hp)
This would scale into 2 hits from wrath characters to be around 10-15k hp max

2. Shadowfiends should have a 2 sec pacify effect on spawn where they do nothing ( no movement, no attacks) before the start following a target

3. Parasitic Shadowfiend debuff shadow only spawn 1 shadowfiend npc (this breaks the exponential loop potential)

I recommend applying at least point 3 to the lv70 version of BT as well to avoid any potential problems

**Database links:**

**Comment by Afgann** [comment]
fixed
