### ISSUE TITLE
Rogue - hack and slash talent 

### ISSUE THREAD

**Issue by lewyrobson** [gamefreedomgit/Frostmourne#2226]
**Description:**
Rogue hack and slash talent is not working properly right now, it should always use main hand weapon dmg, 
but right now this use main or offhand weapon dmg depending on which one procced the talent. 
Also its probly coded as white hit instead of yellow hit because this miss sometimes on proc on hit/exp capped character.
Probably important to fix due to glaive release.

Mimimum dmg 323 - offhand noncrit dmg
Maximum dmg 2k - main hand crit dmg
![image](https://github.com/user-attachments/assets/cafa143c-4daf-4a07-b527-b15bf547b0d9)
![image](https://github.com/user-attachments/assets/f00500ae-524d-4678-b308-4df463195c2d)
![image](https://github.com/user-attachments/assets/a0548868-d1e5-4800-a719-f220efe9f376)

**How to reproduce:**
Pick rogue > get hack and slash talent > equip dual swords/axes > auto attack > check combat log

**How it should work:**

"It can proc off both the main hand attack and the off hand attack, if there is a sword or axe equipped in the appropriate slot.
The extra attack is always done by the weapon in the main hand."
Also:
" [Patch 2.1.0](https://wowpedia.fandom.com/wiki/Patch_2.1.0) (2007-05-22): This ability now grants extra yellow attacks instead of extra white attacks. This change will make Sword Specialization no longer reset the weapon swing timer when it triggers off special attacks, and results in a net increase in damage dealt."

**Database links:**
Hack and slash - https://wowpedia.fandom.com/wiki/Hack_and_Slash_(rogue_talent)
Yellow hit - https://wowpedia.fandom.com/wiki/Hit#Special_attacks

**Comment by Piootrek** [comment]
It works correctly, extra attacks are always done by main hand weapon.
