### ISSUE TITLE
T8 2 set resto druid not working

### ISSUE THREAD

**Issue by Halogen0** [gamefreedomgit/Frostmourne#2228]
[//]: # https://www.wowhead.com/wotlk/spell=64756/item-druid-t8-restoration-2p-bonus

**Description:**
Using 2 pieces of T8 do not increase the healing of your Swiftmend(https://www.wowhead.com/wotlk/spell=18562/swiftmend)

**How to reproduce:**
Druid has 2 pieces, head and hands and 1884 SP (Cape and trinket removed to avoid sp increasing proc)
Druid used rejuvenation
Druid used swiftmend
Druid heal 6177
Druid switched gloves From T8 to Touch of the Occult (https://www.wowhead.com/wotlk/item=45840)
SP adjusted from 1884 to 1894 but losing 10% of healing increase in swiftmend
Druid Re-apply reju
Druid used siwftmend 
Druid heal 6197 (number increased for the difference in SP but, 10 extra SP should be less than 10% healing increase)

**How it should work:**
2 pieces set should increase the healing of Swiftmend for 10% which is not doing it atm.

**Database links:**
T8 resto druid 2 set bonus link: https://www.wowhead.com/wotlk/spell=64756/item-druid-t8-restoration-2p-bonus
Swiftmend link: https://www.wowhead.com/wotlk/spell=18562/swiftmend

Demonstration video: https://youtu.be/eYsOCJbxtA0

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
