### ISSUE TITLE
[Dungeon]Proto Drakes and Proto Drake Riders behind Ingvar The Plunderer are Active and Pull During Fight

### ISSUE THREAD

**Issue by bigchipbag** [gamefreedomgit/Frostmourne#2229]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
in Utgaard Keep, on the last boss, if you stand too close to the edge, you will aggro the dragons and riders 
![image](https://github.com/user-attachments/assets/1138d160-f6cf-420a-9555-faac20abd816)

**How to reproduce:**
Stand near the edge while fighting the boss

**How it should work:**
The adds flying around should be environmental and not involved in the fight.
From wowhead: * Ingvar is found speaking with two Vyrkul riding Proto-dragons at the end of his platform. Once he is agro'ed, the riders will fly away and will not bother your group for the duration of the fight.

**Database links:**
https://www.wowhead.com/wotlk/npc=23954/ingvar-the-plunderer#comments

**Comment by Afgann** [comment]
fixed
