### ISSUE TITLE
[Storm Peaks] Stormpeaks Wyrms pathing

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#223]
**Description:**
Stormpeaks Wyrms in the Foot Steppes are flying on the ground

**How to reproduce:**
Got to Foot Steppes in Storm Peaks

**How it should work:**
They should be pathing in the air

**Database links:**
https://www.wowhead.com/wotlk/npc=29753/stormpeak-wyrm

![WoWScrnShot_022824_090926](https://github.com/gamefreedomgit/Frostmourne/assets/45928535/cf231849-9c19-4ceb-b5ad-77c6112de3b6)

**Comment by Afgann** [comment]
fixed
