### ISSUE TITLE
[Dungeon] [NPC] Drak'Tharon Keep – Darkweb Spiders

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2230]
[Darkweb Recluse](https://www.wowhead.com/wotlk/npc=26625/darkweb-recluse) should run away to the nearest hole in the wall when it gets low on health while throwing an emote "Darkweb Recluse runs back to it's den!". If the spider reaches inside of the hole, group of [Darkweb Hatchlings](https://www.wowhead.com/wotlk/npc=26674/darkweb-hatchling) should spawn. If players kill the spider before reaching the end of the hole, they prevent Hatchlings from spawning. This goes for every single Recluse. As to what percentage of HP triggers this behaviour I havent found any information.
Currently Recluses do not run away at all and Hatchlings spawn automatically upon death of Recluse.

https://wowpedia.fandom.com/wiki/Darkweb_Hatchling
https://www.wowhead.com/wotlk/npc=26625/darkweb-recluse#comments:id=594333

**Comment by Afgann** [comment]
fixed
