### ISSUE TITLE
[Quest] Ruuna the Blind – Missing prerequisites

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2231]
Quest [Ruuna the Blind](https://www.wowhead.com/wotlk/quest=12161/ruuna-the-blind) is available right away. It should be available only after completion of [A Name from the Past](https://www.wowhead.com/wotlk/quest=12160/a-name-from-the-past).

https://www.wowhead.com/wotlk/quest=12161/ruuna-the-blind#comments:id=465438
https://www.wowhead.com/wotlk/quest=12161/ruuna-the-blind#comments:id=458003
https://wowpedia.fandom.com/wiki/Ruuna_the_Blind_(quest)#Progression

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
