### ISSUE TITLE
[Quest] The Runic Prophecies – Rune Plates do not activate emote

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2234]
During the quest [The Runic Prophecies](https://www.wowhead.com/wotlk/quest=11993/the-runic-prophecies) player needs to translate three Runic Plates in Thor Modan proper. Upon interaction with each Runic Plate, the player's character should say what is written there. This does not occur.

https://wowpedia.fandom.com/wiki/The_Runic_Prophecies_(Alliance)?so=search#Notes
https://www.wowhead.com/wotlk/quest=11993/the-runic-prophecies#comments:id=448718
0:55 → https://www.youtube.com/watch?v=Vi8yz7WLChc&ab_channel=GameGuides

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
