### ISSUE TITLE
[Quest] Anatoly Will Talk – Sasha's part of interaction missing

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2235]
In the quest [Anatoly Will Talk](https://www.wowhead.com/wotlk/quest=12330/anatoly-will-talk) after you delvier Tatjana to the camp, autoatic interaction should occur between [Sasha](https://www.wowhead.com/wotlk/npc=26935/sasha) and [Anatoly](https://www.wowhead.com/wotlk/npc=26971/anatoly). However only Anatoly's part is played out, Sasha does not do or say anything.

https://wowpedia.fandom.com/wiki/Anatoly_Will_Talk#Notes
https://www.wowhead.com/wotlk/quest=12330/anatoly-will-talk#comments:id=576346

Same goes for conversation they have when player happen upon them randomy/for the first time. Anatoly says his lines, Sasha is silent. It should be as follows:
https://www.wowhead.com/wotlk/npc=26935/sasha#comments:id=874735

**Comment by Piootrek** [comment]
Fixed, I will push it once the fix comes live.
