### ISSUE TITLE
[Ulduar trash] Ironwork Cannon

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2236]
**Description:**
The Ironwork Cannons from Towers have too much range and they are keeping you in combat after you outrange it.
It should drop combat few seconds after you outrange it to avoid any issues.

The big problem with this Cannon from screeshot is that people are trolling others by getting in combat with it, then waiting for a cast and run towards other people while spell is flying. When the flame reaches him, it kills everyone in range.

Maybe make the flame to not deal aoe damage.

![WoWScrnShot_102924_192712](https://github.com/user-attachments/assets/f2c7af83-b9b8-4bdb-a535-8a06c52ebe02)

**Comment by Afgann** [comment]
fixed
