### ISSUE TITLE
Quest [Reclaimed Rations] pre-req

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#224]
**Description:**
Quest [Expression of Gratitute] (kill Gnarlhide) is a pre-req to pick up [Reclaimed Rations] currently on the PTR
[Ample Inspiration] is also available once we turn in only [Expression of Gratitute]

**How to reproduce:**
Talk to npc Ricket at K3

**How it should work:**
We should be able to pick up [Expression of Gratitute] and [Reclaimed Rations] at the same time
[Ample Inspiration]'s pre-reqs should be both [Expression of Gratitute] and [Reclaimed Rations], and not just [Expression of Gratitute], as per https://www.wowhead.com/wotlk/quest=12828/ample-inspiration comments

**Database links:**
https://www.wowhead.com/wotlk/quest=12827/reclaimed-rations
https://www.wowhead.com/wotlk/quest=12836/expression-of-gratitude
https://www.wowhead.com/wotlk/quest=12828/ample-inspiration

**Comment by Afgann** [comment]
fixed
