### ISSUE TITLE
Warlock Destro talents

### ISSUE THREAD

**Issue by Yizwire1** [gamefreedomgit/Frostmourne#2242]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When empowered imp is procced during Rain of Fire the crit only works on one tic instead of entire spell cast/remaining left

**How to reproduce:**
Proc empowered imp mid rain of fire or cast rain of fire when procced.
It will only work on the first tic 

**How it should work:**

Work during the entire cast/ remaining spell cast of rain of fire

**Database links:**
https://www.wowhead.com/wotlk/spell=6219/rain-of-fire
https://www.wowhead.com/wotlk/spell=47283/empowered-imp

**Comment by Greywolf59** [comment]
I haven't found any information it that Empowered Imp should apply to whole Rain of Fire. No a single wowhead comment, patch note, anything. I am interested into this too, so I am curious if you can provide anything to back this up.

Actually while writing this comment I have dug around a bit more and found this:
https://www.wowhead.com/wotlk/spell=47223/empowered-imp#comments:id=751407

So only info concerning mechanics between Empowered Imp and Rain of Fire state it is consumed by one next tick (8s cast, every 2s aoe tick). So far issue seems invalid.

Btw what a shame on this server RoF doesnt benefit from Backdraft like on other free servers. It was fun. (And yes, no benefit from Backdraft is blizzlike as far as my research goes)

**Comment by Piootrek** [comment]
Invalid issue, closing.
