### ISSUE TITLE
[Quest] Disclosure – /Say timing and completion

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2249]
[Disclosure](https://www.wowhead.com/wotlk/quest=12710/disclosure) should be completed right after the player clicks the Moldy Coffin and [Malmortis](https://www.wowhead.com/wotlk/npc=28948/malmortis) says his first replica.

https://www.wowhead.com/wotlk/quest=12710/disclosure#comments:id=444994
Classic: https://www.youtube.com/watch?v=aAultbLDGZc&ab_channel=scarything (same on some old video too, can't find it anymore)

If palyer decides to follow Malmortis, they might notice his replocas are timed wrongly, they are too fast. I could not find the video from original wotlk, nor from Classic since everyone skips it, however I have found video from some later patch with reskins and I am inclined to believe the timing, or spots where the replicas are said should be the same.
11:40 https://www.youtube.com/watch?v=6wTrCQok1Is&ab_channel=ZaFrostPet

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
