### ISSUE TITLE
Knothide Leather Scraps appearing more frequently than they should

### ISSUE THREAD

**Issue by roblox-oof-dot-mp3** [gamefreedomgit/Frostmourne#2250]
**Description:**
When skinning mobs in Outland, higher-level mobs are supposed to yield Knothide leather at a much higher ratio than scraps. For example, Ripfang Lynx's in Netherstorm are supposed to be an 80% chance of leather and only 20% for scraps. 

Currently this isn't working as intended, as from my experience you receive scraps more than 50% of the time when skinning these mobs. The same applies to multiple other areas I've tested, including the talbuks directly north and the talbuks in Nagrand.

**How to reproduce:**
Go skin a bunch of mobs, divide your scraps by 2.5 and compare the value to the # of knothide leathers you have. Should be an 80:20 ratio, but currently around 50:50

**How it should work:**
Knothide Leather should be more common.

**Database links:**
https://www.wowhead.com/wotlk/npc=20671/ripfang-lynx#skinning
https://www.wowhead.com/wotlk/npc=20610/talbuk-doe#skinning
https://www.wowhead.com/wotlk/npc=17130/talbuk-stag#skinning

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
