### ISSUE TITLE
Handful of Candy not rewarding enough candy

### ISSUE THREAD

**Issue by roblox-oof-dot-mp3** [gamefreedomgit/Frostmourne#2251]
**Description:**
If you look at the loot table on wowhead, it shows that candies besides GNERD's are in about 60% of handful's of candy. This means if you hit all the candy buckets you would expect to see about 90 of each; currently you only see about 20-30. 

Seems like the probability on the 3 other candies are lower than they should be

**How to reproduce:**
Get a bunch of candy

**How it should work:**
More candy

**Database links:**
https://www.wowhead.com/wotlk/item=37586/handful-of-candy#contains

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
