### ISSUE TITLE
Ice block textures are green

### ISSUE THREAD

**Issue by roblox-oof-dot-mp3** [gamefreedomgit/Frostmourne#2252]
**Description:**
All of the Ice block textures are green instead of their normal color.

![image](https://github.com/user-attachments/assets/f4de457a-5852-402e-a325-39fb6458e202)

**How to reproduce:**
Ice block on a mage, look at Keri in the Nexus, trap a mob with a hunter, etc.

**How it should work:**
![image](https://github.com/user-attachments/assets/436803ee-95ae-47e7-90f0-2ee3f2174e82)

**Database links:**

**Comment by Riztazz** [comment]
Your character has green shading from the event auras.. ice block reacts to that, not a bug
