### ISSUE TITLE
Eye of Acherus incorrect speed until you jump

### ISSUE THREAD

**Issue by roblox-oof-dot-mp3** [gamefreedomgit/Frostmourne#2253]
**Description:**
When doing one of the first DK quests where you pilot the Eye of Acherus, it moves at normal walking speed until you jump. 

**How to reproduce:**
Pickup the quest Eye of Acherus at the start of the DK chain

**How it should work:**
Should start out with its usual flying speed

**Database links:**
https://www.wowhead.com/wotlk/quest=12636/the-eye-of-acherus
https://www.wowhead.com/wotlk/npc=30628/eye-of-acherus-dk

**Comment by KryndorX** [comment]
Same thing for "Captive proto-drake" located in dun niffelem that is required for quest "Cold Hearted".

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
