### ISSUE TITLE
[Quest] Gluttonous Lurkers – Missing Prerequisite

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2254]
Quest [Gluttonous Lurkers](https://www.wowhead.com/wotlk/quest=12527/gluttonous-lurkers) is available without any prerequisites. It should be available only after the quest [Precious Elemental Fluids](https://www.wowhead.com/wotlk/quest=12510/precious-elemental-fluids) is completed.
https://www.wowhead.com/wotlk/quest=12527/gluttonous-lurkers#comments:id=361984:reply=81143
https://wowpedia.fandom.com/wiki/Gluttonous_Lurkers#Progression

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live
