### ISSUE TITLE
[Quest] The Drakkari Do Not Need Water Elementals! – Missing Prerequisite

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2255]
Quest [The Drakkari Do Not Need Water Elementals!](https://www.wowhead.com/wotlk/quest=12562/the-drakkari-do-not-need-water-elementals) is available right away without any prerequisites.
It should be available only after [Strange Mojo](https://www.wowhead.com/wotlk/quest=12507/strange-mojo) is completed.

https://www.wowhead.com/wotlk/quest=12562/the-drakkari-do-not-need-water-elementals#comments:id=540647
https://wowpedia.fandom.com/wiki/The_Drakkari_Do_Not_Need_Water_Elementals!?so=search#Progress

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
