### ISSUE TITLE
Stack debuff Attack speed

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#2256]
The problem is that the different levels of attack speed deceleration effects add up to each other. For example, there is the boss algalon.  The base attack speed is 1.0 second with improved debuff(20%), the speed becomes 1.2 seconds. If you use the shaman's earth shock, which reduces 10% of the speed, the the time will become 1.32

Most likely, this is not an earth shock problem, but a common problem with all spells of this kind, which have different levels or modifiers for reducing attack speed and from pets with similar skills as well.

Debuffs should not stacks. The strongest of the imposed ones must act.

![image](https://github.com/user-attachments/assets/ddbb95fe-9c9b-4554-b68a-2fd7bddf4e0c)
![image](https://github.com/user-attachments/assets/ef427510-391d-4385-9cb2-f9414fa251d9)
![image](https://github.com/user-attachments/assets/e4adf5b6-4d50-44ff-ad87-f76f569414bc)

**Comment by haephaistoss** [comment]
Another case of:

https://github.com/gamefreedomgit/Frostmourne/issues/1498

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
