### ISSUE TITLE
[Quest] Trouble at the Altar of Sseratus – Wrong Prerequisites

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2258]
Quest [Trouble at the Altar of Sseratus](https://www.wowhead.com/wotlk/quest=12506/trouble-at-the-altar-of-sseratus) has wrong prerequisites.
It should be available after completing [Parachutes for the Argent Crusade](https://www.wowhead.com/wotlk/quest=12740/parachutes-for-the-argent-crusade), however it is available only after completing [Defend the Stand](https://www.wowhead.com/wotlk/quest=12503/defend-the-stand). So currently prerequisite is set either to require both PftAC and DtS or just DtS. I have completed PftAC first and it didn't open the quest.

[Trouble at the Altar of Sseratus](https://www.wowhead.com/wotlk/quest=12506/trouble-at-the-altar-of-sseratus) should have only one prerequisite: [Parachutes for the Argent Crusade](https://www.wowhead.com/wotlk/quest=12740/parachutes-for-the-argent-crusade).
https://www.wowhead.com/wotlk/quest=12740/parachutes-for-the-argent-crusade#comments:id=557532
https://www.wowhead.com/wotlk/quest=12506/trouble-at-the-altar-of-sseratus#comments:id=446487:reply=71945

**Comment by Riztazz** [comment]
fixed, will close once it's live
