### ISSUE TITLE
[Quest] New Orders for Sergeant Stackhammer – Wrong Prerequisites

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2259]
Quest Quest [New Orders for Sergeant Stackhammer](https://www.wowhead.com/wotlk/quest=12505/new-orders-for-sergeant-stackhammer) has wrong prerequisites.
It should be available after completing [Parachutes for the Argent Crusade](https://www.wowhead.com/wotlk/quest=12740/parachutes-for-the-argent-crusade), however it is available only after completing [Defend the Stand](https://www.wowhead.com/wotlk/quest=12503/defend-the-stand). So currently prerequisite si set either to require both PftAC and DtS or just DtS. I have completed PftAC first and it didn't open the quest.

[New Orders for Sergeant Stackhammer](https://www.wowhead.com/wotlk/quest=12505/new-orders-for-sergeant-stackhammer) should have only one prerequisite: [Parachutes for the Argent Crusade](https://www.wowhead.com/wotlk/quest=12740/parachutes-for-the-argent-crusade).

https://www.wowhead.com/wotlk/quest=12505/new-orders-for-sergeant-stackhammer#comments:id=557536
https://www.wowhead.com/wotlk/quest=12740/parachutes-for-the-argent-crusade#comments:id=557532

**Comment by Riztazz** [comment]
fixed, will close once it's live
