### ISSUE TITLE
Quest [Ample Inspirations]

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#226]
**Description:**
When you blow up the mammoth with the quest item bomb, only the big chunk spawns, requiring you to blow up multiple mammoth to complete the quest

**How to reproduce:**
Pick up bomb
Use on mammoth
Check how only the big meat chunk is available to loot

**How it should work:**
Several smaller chunks of meat should spawn in a circle around the big chunk
https://www.youtube.com/watch?v=aOFMacQA2dU

**Database links:**
https://www.wowhead.com/wotlk/quest=12828/ample-inspiration

**Comment by Afgann** [comment]
fixed

**Comment by ChronoWM** [comment]
Upon accepting the quest players are not able to see the Mammoths in the area.
NPC Ironwool Mammoth are there by default and players are on the same phase as NPCs. 
However they cannot see any of them.

NPC: https://www.wowhead.com/wotlk/npc=29402/ironwool-mammoth
Quest: https://www.wowhead.com/wotlk/quest=12828/ample-inspiration
![Screenshot 2024-06-03 171243](https://github.com/gamefreedomgit/Frostmourne/assets/170808156/5aeea7ba-a12f-4e19-8d8f-daf61cd0a5ce)
