### ISSUE TITLE
[Quest] Defend the Stand – Wrong Prequisites

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2260]
[Defend the Stand](https://www.wowhead.com/wotlk/quest=12503/defend-the-stand) should not have any "hard-set" prerequisites.
It should be available from the start, however currently it does requires completion of [Taking a Stand](https://www.wowhead.com/wotlk/quest=12795/taking-a-stand).

Taking a Stand should be a free breadcrumb quest not needed to get Defend the Stand.

Based on: https://www.wowhead.com/wotlk/quest=12795/taking-a-stand#comments:id=731421

**Comment by Riztazz** [comment]
https://wowpedia.fandom.com/wiki/Defend_the_Stand

Says it requires taking a stand first

**Comment by Greywolf59** [comment]
Yes, but the wowhead comment at the quest Taking a Stand says: "Note: If you've already completed https://www.wowhead.com/wotlk/quest=12503, then this quest won't be available." and it has 26 upvotes. 
Quest 12503 is defend the Stand.
Why would someone mention that Defend the Stand is not accessible once the player does Taking a Stand, if it would not be possible to acquire Taking a Stand without doing Defend the Stand in the first place.
There is also this site: https://wowpedia.fandom.com/wiki/Zul%27Drak_quests?oldid=1714223
But all in all I indeed haven't found any other information that Defend the Stand should be acquirable without Taking the Stand. Unsure, uncertain, closing.
