### ISSUE TITLE
Gizelton Caravan is too damn fast!!

### ISSUE THREAD

**Issue by Miodziemniak** [gamefreedomgit/Frostmourne#2261]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Gizelton Caravan is too fast, faster than the player that I have to mount up just to keep up, not even a pause after a combat to regenerate health and mana..

**How to reproduce:** Start either of the quests.

**How it should work:** Should be about half the speed of the player

**Database links:** 
https://www.wowhead.com/wotlk/en/quest=5821
https://www.wowhead.com/wotlk/en/quest=5943

**Comment by Riztazz** [comment]
fixed, will close once it's live
