### ISSUE TITLE
Haste Raing Visual Bug

### ISSUE THREAD

**Issue by Humaniak** [gamefreedomgit/Frostmourne#2262]
Haste from Spell Haste Totem and Hero/Bloodlust not Showing on Character Info

**Comment by roblox-oof-dot-mp3** [comment]
I'm pretty sure this isn't a bug, because they're separate haste sources.

The way haste works is your actual haste value is going to be all your different sources multiplied together. I.e. with bloodlust and spellhaste totem, you're going to have (1.2 * 1.05 * (your character sheet value + 1).

**Comment by UltraNix** [comment]
As described above - effects from these are not shown in your UI as haste rating.
You can see the effects looking at attack speed.
