### ISSUE TITLE
Warglaives set bonus completely broken

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#2263]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
![WoWScrnShot_110324_134729](https://github.com/user-attachments/assets/dcb8a764-083e-48dc-bb31-9b0b009fb7ec)
1. Sinister strike does not have 100% chance to give you the initial insight buff as tooltip says, it only becomes 100% once the initial buff is procced and starts progressing. You need 3-4-5 sinisters at the start to proc the initial buff. This makes no sense from both tooltip info standpoint and also combat rogue playstyle since you unload burst at start asap which means it would be favorable to have at least 3% buff during the trinkets, buffs and killing spree. This nullifies a lot of this weapons synergy in relation to its intended class.

2. The insight buff only applies to MELEE WHITE DAMAGE, not abilities or ranged attacks - tooltip states ALL DAMAGE against enemy
(proof photo in point 3)

3. Damage buff is much higher than intended: Slight Insight buff gives 10% instead of intended 3%, Moderate Insight gives 20% instead of intended 6%, Deep Insight gives 30% dmg instead of intended 10%.
![WoWScrnShot_110324_132509](https://github.com/user-attachments/assets/e2db92ab-b397-4f77-8f6e-71a76c2d35d9)
![WoWScrnShot_110324_132516](https://github.com/user-attachments/assets/92bf81e9-e619-47c3-8a5c-05316de3b3e7)
23900/184=130% dmg (slight variance due to 1-2 wep dmg) tested other buffs not present in photo and they behave as said above.
Sinister dmg is same with and without buff, also tested eviscerate and ranged wep auto (you gain no benefit on anything other than melee autos)

4. Insight buff remains on your character when you unequip warglaives/wepswap. This results in huge dmg cheese potential now and in the future. ( can even be used by other specs other than combat cheesing it)

**How to reproduce:**
Go on target dummy, proc the buff in a few sinisters, swap to a 1-2 dmg dagger and compare damage with buff vs after buff drops.

**How it should work:**
1. "Sinister strike has 100% chance to grant you an evolving insight" should proc slight insight buff on first sinister strike on the target.
2. Should apply to all damage the rogue does against target: melees, ranged, ability, external procs and consumables.
3.  Slight insight = 3% increased dmg; Moderate insight = 6% increased dmg; Deep Insight = 10% increased dmg.
4.  Any and all of the 3 insight buffs should be removed if one of the glaives is removed from character equip.

**Database links:**
Note: This was all tested on the PTR server

**Comment by Afgann** [comment]
fixed
