### ISSUE TITLE
[Pet] Murkidan – Counts as mount

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2264]
The new pet [Murkidan](https://www.wowhead.com/item=128427/murkidan), bought for running BT counts toward number of mounts held, instead of pets. It should count toward pet count.
![817f03449bdd41a46083ef47cba9e403](https://github.com/user-attachments/assets/a922d64b-8bb7-4c0e-a04f-6ea162fedd65)

**Comment by Piootrek** [comment]
Fixed, I will close this once the fix comes live.
