### ISSUE TITLE
 [Title] [Warglaives of Azzinoth are not giving the title]

### ISSUE THREAD

**Issue by GM-Nightmare** [gamefreedomgit/Frostmourne#2265]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
getting the warglavies should give the title (Wrath of Azzinoth) a player has both warglavies and didnt get the title 
![image](https://github.com/user-attachments/assets/3a731187-1892-4d95-b089-d4476c623a42)
![image](https://github.com/user-attachments/assets/e0a21a73-d760-417b-b76a-fc3b82f0eb1a)

getting warglavies should give the title Wrath of Azzinoth 
![image](https://github.com/user-attachments/assets/67f5ff1e-66a4-4c8a-a68d-1136b87a4b9c)

**Comment by GM-Nightmare** [comment]
![image](https://github.com/user-attachments/assets/ed5c923c-5940-4de7-ae7f-5a77731bf1b1)
![image](https://github.com/user-attachments/assets/4368a542-fdc2-4494-8181-d0b6bd3b8289)
these are the available titles for the player

**Comment by Afgann** [comment]
fixed
