### ISSUE TITLE
Warglaives of Azzinoth aren't giving Shallow/moderate/Deep insight

### ISSUE THREAD

**Issue by Jc0599** [gamefreedomgit/Frostmourne#2269]
Warglaives set bonus isn't working.

![Glaives](https://github.com/user-attachments/assets/c664e82f-205f-43da-9d52-a8c0e14f384d)

In game:
![Ingame](https://github.com/user-attachments/assets/608dd801-2b38-4207-9317-3c2a19b93237)
![In game](https://github.com/user-attachments/assets/272e27ac-05d0-4c21-a6d2-30e0bfce58dc)

Here u can see like 9 or 10 sinister strikes but the buff didn't proc
PTR:
![PTR](https://github.com/user-attachments/assets/9e19867f-b0ea-4f6b-8120-0890bcc0e022)
![PTR2](https://github.com/user-attachments/assets/062f364e-1adf-4b3f-a8c8-130f4848feb2)

**Comment by Afgann** [comment]
fixed

**Comment by Jc0599** [comment]
@Afgann The buff is working now, but when i use Eviscerate, the buff disappear, then i have to start again using Sinister strike for First Shallow Insight.

If i don't use Eviscerate it works well.

**Comment by scrublama** [comment]
@Afgann 
There's still issues with this proc.
I've noticed it sometimes not proccing at all for very long sometimes and it seemed bugged so I recorded on dummy, I dont know whats causing it, but I found re-equipping the offhand will make it start to proc again.

Ignore the background noices
https://vimeo.com/1042358538
