### ISSUE TITLE
Warrior talent Deep Wounds

### ISSUE THREAD

**Issue by qqdbpp** [gamefreedomgit/Frostmourne#227]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**

warrior talent deep wounds https://www.wowhead.com/wotlk/spell=12867/deep-wounds currently has an unintended interaction where it procs from spell damage on hit effects such as flame cap, fiery weapon, oil of immolation, fiery plate gauntlets etc. this was removed in OG wow and classic and is not consistent with other talents that proc on critical strikes such as shaman flurry and rogue focused attacks.

**How it should work:**

deep wounds should only proc from physical damage crits

**Comment by Manpower99** [comment]
i think u forgot to mention it was removed in OG wow not during wrath but after though.
