### ISSUE TITLE
 The spell "Horn of Winter" does not work correctly

### ISSUE THREAD

**Issue by Apakalipsis1992** [gamefreedomgit/Frostmourne#2273]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)
https://www.wowhead.com/wotlk/spell=57623/horn-of-winter

**Description:**
The default duration of the Horn of Winter spell is 2 minutes. With Glyph of Horn of Winter - 3 minutes. If I am currently affected by the Horn of Winter buff, which lasts for more than 2 minutes and I use Horn of Winter again, then the duration is not updated, but if the duration is less than 2 minutes left and I use Horn of Winter, then the buff is updated and the action time again becomes 3 minutes.

**How to reproduce:**

Use horn of winter while there is a buff with a duration of more than 2 minutes.

**How it should work:**

Horn of Winter should always refresh the buff time to 3 minutes, provided that Glyph of Horn of Winter is used.

**Database links:**

https://www.wowhead.com/wotlk/item=43544/glyph-of-horn-of-winter

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
