### ISSUE TITLE
[Ulduar] Minor/Major bugs

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2277]
**Description:**

**1. Flame Leviathan:**
Flame Leviathan turrets take damage from vehicles but restore the health after 1 sec. I guess it's fine, but they shouldn't take damage from vehicles in the first place.

**2. Razorscale:**
Razorscale's 3rd Flame Breath in phase 2 coincides with Devouring Flame and he doesn't return his face to the tank, doing the breath into the raid killing innocent people.

**3. XT:**
XT still drops shit salvaged loot on engineering.

**4. Iron council:**
Steelbreaker remains with increased damage stacks after wipe. People need to reset the boss to remove the stacks.

**5. Kologarn:**
Kologarn arm death shouldn't spawn adds if boss also dies in the same time due to -15% health removal upon arm death.

**6. Auriaya:**
Feral defender should have a 5 seconds cooldown on his Feral Rush (the ability that charges and intrerupts people).

**7. Thorim:**
Annoying visual bug where Thorim is running in place for 1 sec from time to time.

**8. Mimiron:**
Due to increased hitbox of Aerial Command Unit from previous reports, now it's attackable by any meele in phase 4. It shouldn't be attackable even when jumping, because leeway mechanic should work only when both player and target are moving.

**Comment by Piootrek** [comment]
1. Fixed
2. Fixed
3. What do you mean? Salvage Loot looks good for me 
![image](https://github.com/user-attachments/assets/f4f30074-f1c4-4891-a631-0ba3e3d114fb)
4. Couldn't reproduce. What stacks exactly? Do you have any screen/video?
5. Fixed
6. Fixed
7. Couldn't reproduce. When does it happen? When he is on the ground or on the platform?
8. Fixed

**Comment by oneadanut** [comment]
3. I've seen one time dropping only 3 neo-dynamic gear assembly, maybe it's random.

4. Steelbreaker gets stacks of increasing damage for each player death. He doesn't remove the buff after wipe.

7. It happens during phase 2, I will try to record next time.

**Comment by Vaxsysl** [comment]
I can confirm no.4 happening, had it happen last week. No proof though. Sorry.

**Comment by oneadanut** [comment]
Thorim running in place:

https://github.com/user-attachments/assets/78d739b1-5d1f-4661-9667-162fb2fb2934
