### ISSUE TITLE
[Lightning Overload] 

### ISSUE THREAD

**Issue by wernerwix** [gamefreedomgit/Frostmourne#2278]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Elemental shaman,  [Lightning Overload] is not affected by  [Elemental Fury]. "iIncreases the critical strike damage bonus of your Searing, Magma, and Fire Nova Totems and your Fire, Frost, and Nature spells by 100%."

**How to reproduce:**
Cast lightningbolt until you get a critical strike and compare to the critical strike of  [Lightning Overload] witch should be half, but its 25%

**How it should work:**
Shouldnt the  [Lightning Overload] be affacted by  [Elemental Fury] and deal 50% critical damage aswell?

**Database links:**
TBH just think its feels off.

**Comment by Piootrek** [comment]
Lightning Overload can crit independently from the proccing it spell, so there still can be a situation when the main spell crits and Lightning Overload not, as a result Lightning Overload will still do 25% damage. However, if Lightning Overload crits it will do correctly 50% dmg now, previously crit result was ignored.

I will close this issue once the fix comes live.

**Comment by scrublama** [comment]
lightning overload works correct 
,until you get a damage % buff, then ligthning overload does 100% or even 200% of lightning bolt instead of 50%

This can be seen in twins on t9 and similar fights with % dmg increase and they do alot more dmg than supposed to due to this

**Comment by kkozux** [comment]
"Lightning Overload spells shouldnt benefit from bonus damage done/taken auras" 

Is then not correctly at all or? if the target is supposed to get 50% more dmg then also overload should. 

Please dont remove the ability to get bonus dmg done auras, it will kill elemental.

**Comment by Piootrek** [comment]
Overload should do 50% of a base spell. If the base lightning bolt benefitted from +% aura, overload dmg will be bigger too. Previously final overload dmg was incorrectly affected by +% again.

**Comment by kkozux** [comment]
@Piootrek This is the best % dmg i could find after the fix (linked down below) - It deals mostly around 6% of my total dmg rn
Average normal Lightning Bolt is 9k
Average hit from Overload is 3.3k 

Maybe you accidently nerfed this? I feel like its almost non existent anymore but it shouldve just nerfed for +% auras like Council and Valks. 

Maybe you could doublecheck this again? :(


This is details from VOA18 as example
![Bild_2024-12-12_134533955](https://github.com/user-attachments/assets/2b8bc4a8-af96-4bbc-a6ec-4d28903a21db)

**Comment by Piootrek** [comment]
Show more details from addon please.

**Comment by scrublama** [comment]
81,6/490=0,167 
Thats about 16,7% of lightning bolt, looks alright

expected dmg as far as I know, every third cast half dmg:
0,33x0,5 =0,165
