### ISSUE TITLE
Pets purchased by emblem of eternity cannot be summoned

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#2279]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

We had 2-3 cases of Murkidan and Pocket Reaver not appearing.
players had the spell known but they dont appear after casting the spell.

**How to reproduce:**

Purchase pocket reaver or murkidan and try to summon it.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
