### ISSUE TITLE
Quest [A Delicate Touch]

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#228]
**Description:**
The mobs in the area are just standing still
They aggro you like normal mobs
The quest item [Improved Land Mines] do not get triggered by the mobs, so in order to complete the quest you just kill them

**How to reproduce:**
Go to Snowblind Hills in Storm Peaks

**How it should work:**
Garm Invader and Snowblind followers should run in waves from east to west, and get 1-shot zapped at the end of the field
They should trigger mines when running over them
They should not proximity aggro you

**Database links:**
https://www.wowhead.com/wotlk/quest=12820/a-delicate-touch

**Comment by Afgann** [comment]
fixed

**Comment by agemennon675** [comment]
Quest [A Delicate Touch] cannot be completed because the mobs cannot be killed by the player or using a mine
