### ISSUE TITLE
Murky Companion not Working

### ISSUE THREAD

**Issue by ProfeMurlok** [gamefreedomgit/Frostmourne#2281]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Wasted my Eternity Embles in Murky Companion, but it doesn't summon or anything.

**How to reproduce:**
Return the Eternity Embles, or well, make it work.

**How it should work:**
Return the Eternity Embles, or well, make it work.

**Database links:**
Was at the end of this stream (4:57:00): https://www.youtube.com/watch?v=RxXZsHY02bM

**Comment by UltraNix** [comment]
#2279
