### ISSUE TITLE
[Quest] Death to the Necromagi – Wrong prerequisites

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2285]
Quest [Death to the Necromagi](https://www.wowhead.com/wotlk/quest=12552/death-to-the-necromagi) is available only after completing whole [Pa'troll](https://www.wowhead.com/wotlk/quest=12596/patroll) quest.
It should be available after completing [Throwing Down](https://www.wowhead.com/wotlk/quest=12598/throwing-down) sub-part of Pa'Troll.
table with notes: https://wowpedia.fandom.com/wiki/Death_to_the_Necromagi
This reply to comment: https://www.wowhead.com/wotlk/quest=12552/death-to-the-necromagi#comments:id=464205:reply=100812

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
