### ISSUE TITLE
Anub'arak burrow phase is not functional

### ISSUE THREAD

**Issue by Perilynn** [gamefreedomgit/Frostmourne#2287]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
anub retargets multiple times a second and stays still the entire burrow phase
this is on 25 ascended mode, can see the perma-fires stacking up on the same spot.

**How to reproduce:**
https://www.youtube.com/watch?v=oAgbS86l0OE

Obvious critical issue here, no need to explain

**How it should work:**
Shouldn't retarget unless popped or target dies, gradually increasing in speed (regular functionality)

**Database links:**

**Comment by Perilynn** [comment]
[WoWCombatLog.txt](https://github.com/user-attachments/files/17656737/WoWCombatLog.txt)


combatlog of the ptr raid

**Comment by Afgann** [comment]
fixed

**Comment by scrublama** [comment]
> fixed

![image](https://github.com/user-attachments/assets/fbe0bce0-23da-4418-8be1-3ea9772f5428)
The persue is still bugged, you can vanish or shadowmeld and it will stay in place
