### ISSUE TITLE
[Calendar] not showing events

### ISSUE THREAD

**Issue by GM-Nightmare** [gamefreedomgit/Frostmourne#2289]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
the calendar not showing events of next month/year  , ONLY DARKMOON IS VISIBLE THERE

**How to reproduce:**

open calendar and its almost empty 
![image](https://github.com/user-attachments/assets/4021745d-9bf5-4eab-9b8c-a388602a806c)

**How it should work:**
Pilgrim's bounty is active at the moment and its not showing on calendar

**Database links:**

**Comment by Greywolf59** [comment]
→ https://github.com/gamefreedomgit/Frostmourne/issues/2267
