### ISSUE TITLE
Quest [Opening the backdoor]

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#229]
**Description:**
When you active the teleporter in Garm's Rise, it teleports you twice (2 loading screen), bringing you back to Garm's Rise, so you have to fly back to K3
The question still completes though.
When using the TP at K3, it properly teleports you once, to Garm's Rise

**How to reproduce:**
Use [Transporter Power Cell] at teleporter at Garm's Rise

**How it should work:**
You should be tp'd to K3 when using the tp at Garm's Rise
https://www.youtube.com/watch?v=V05NNbWbXS8

**Database links:**
https://wotlk.evowow.com/?quest=12821

**Comment by Afgann** [comment]
fixed
