### ISSUE TITLE
Boss Kagani Nightstrike - Magisters' Terrace.

### ISSUE THREAD

**Issue by Zipica** [gamefreedomgit/Frostmourne#2292]
**Description:**
Boss goes in infinite vanish and resets 

**How to reproduce:**
Remove ability to constantly use Vanish

**How it should work:**
He should be able to Vanish and then show up. 
As soon as he showup again, he gets in combat, cast vanish and restart.

People cant continue to next room for dungeon.

https://wowpedia.fandom.com/wiki/Kagani_Nightstrike)

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
