### ISSUE TITLE
[Core] Raid Markers require some improvements

### ISSUE THREAD

**Issue by Shineslippers** [gamefreedomgit/Frostmourne#2293]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
1. Raid Markers at this moment has only range 30. 
2. "Reset Markers" button is good idea but hard to use in combat.

**How it should work:**
1. Best range for it is size of Mimiron's room, but i would be happy if it will be at least 100.
2. Need some command for reset. Either macro one or via API. Something like `/script ResetRaidMarkers()`. Maybe some other workaround.

**Comment by Piootrek** [comment]
1. Increased range to 100 yards, there will still be "out of range" indicator on the ground, but it will let you put a marker.
2. There is already a command .rmark

I will close this issue once the fix comes live.
