### ISSUE TITLE
General Vezax 25 - searing flames 

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#2294]
The problem is that the cooldown of the searing flames boss's ability is 8 seconds and in these realities, 1 player (even a shaman) is enough to interrupt this spell. On the official server, he didn't have a cooldown on this ability in mode 25. 2-3 people were used to interrupt the spell, depending on the type of interruption that blocked the reuse of the ability. In different videos, you can see the delay, but it was due to the priority of the automatic attack, or to the throwing of the shadow spear.

This problem only concerns the 25-player mode. 

https://www.wowhead.com/spell=62661/searing-flames
https://youtu.be/BtTaQ0Adp60?t=199

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
