### ISSUE TITLE
Freya - Ancient Conservator 

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#2295]
The problem is that the NPC ancient conservator must be immune to slowing down movement speed and all other types of control, so that it is not possible to interrupt the spell "Conservator's Grip" and ignore the mechanics. We do not have immunity to slowing down the speed of movement on the server, I have not checked immunity to another type of control, but if it is missing, then it is better to do it.

https://youtu.be/LhZUqQy1pcc?t=132

**Comment by Piootrek** [comment]
I can't reproduce this. Can you give me any example spells that can interrupt Conservator's Grip?

**Comment by wowclassic1234** [comment]
https://www.wowhead.com/classic/spell=17926/death-coil
https://www.wowhead.com/wotlk/spell=2094/blind
https://www.wowhead.com/wotlk/spell=1776/gouge
https://www.wowhead.com/spell=853/hammer-of-justice
https://www.wowhead.com/spell=710/banish
https://www.wowhead.com/wotlk/spell=14311/freezing-trap
https://www.wowhead.com/wotlk/spell=49012/wyvern-sting
https://www.wowhead.com/wotlk/spell=10890/psychic-scream

If there is immunity to all the listed types of control, then everything is in order. You just need to add immunity to the slowdown.
Sorry to bring up the topic of checking immunity to other spells. It's just that according to my observations on private servers, this NPC constantly had problems with missing immunities.

**Comment by Piootrek** [comment]
He is immune to all of those spells. I don't understand how movement slow effect can affect Conservator's Grip cast. Can you explain?

**Comment by wowclassic1234** [comment]
> He is immune to all of those spells. I don't understand how movement slow effect can affect Conservator's Grip cast. Can you explain?

It won't have any effect. The immunity to deceleration has nothing to do with the Keeper's grip, these are different problems. But this Npc should be immune to the effects of deceleration, on the official server, the effects of deceleration did not affect him. On our server, the Ancient Conservator slows down and this causes inconvenience when you lead it from one mushroom to another.
