### ISSUE TITLE
(3rd time's the charm) Sara's target

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#2296]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
On 10nm and 10hc Sara does not show her target. It works fine on 25man.
When I reported it the second time and it was fixed it lasted for 1 id (3weeks ago-ish?) after that the last few ids she doesnt have a target again for her spells in 10man only.

**How to reproduce:**
Go yogg10man hc or not.

**How it should work:**
Sara should show as target of target for all spells she casts on players.

**Database links:**

**Comment by Riztazz** [comment]
I can't reproduce this, could we get a video of it happening? Maybe it will contain some clues

**Comment by sputnikk** [comment]
I'll record a vid of it next time i do 10man, it happens to me consistently only on 10man.

**Comment by Riztazz** [comment]
Additionally, 3.5 client or original one?
