### ISSUE TITLE
twin valkyrs not attackable without jumping

### ISSUE THREAD

**Issue by Perilynn** [gamefreedomgit/Frostmourne#2297]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
have to jump to get in melee range, valks not on the ground.

https://github.com/user-attachments/assets/b65e7111-0999-4760-94c4-86e2a7616fdf

self explanatory. plsfix. ty ty much luv

**Comment by Afgann** [comment]
fixed
