### ISSUE TITLE
Quest : The lost MistWhisper Treasure.

### ISSUE THREAD

**Issue by KryndorX** [gamefreedomgit/Frostmourne#2298]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Quest unable to be completed properly, Orb is non clickable and even if it is clickable(Which i never seen it clickable before) and the quest npc come and you kill him it won't count.

**How to reproduce:**
Simply do the quest.

**How it should work:**
Should be completed. (Bug did happen today after they posted that is has been fixed).

**Database links:**

**Comment by Riztazz** [comment]
Duplicate, fixed already but not yet on live server
