### ISSUE TITLE
Prospecting inside Black Temple

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2299]
**Description:**
Prospecting inside Black Temple gives no loot and maybe Icy Prism too, probably leftover code from Mimiron Playground.

![WoWScrnShot_110924_161433](https://github.com/user-attachments/assets/c9c4a033-122d-4a72-b9cf-c823b428f54a)
![WoWScrnShot_110924_161452](https://github.com/user-attachments/assets/1118039c-bcd7-4bc9-937f-807ae4104a35)

**Comment by Afgann** [comment]
fixed
