### ISSUE TITLE
[Black Temple] Fatal Attraction - Mother Shahraz

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2300]
**Description:**
The spell is chaining ticks from each player doing too much damage and kill people. It shouldn't do 6-9 ticks per second, it should be only 3, one from each player.

![WoWScrnShot_110924_151007](https://github.com/user-attachments/assets/603250a9-3853-4ea3-9d31-433ee66bd125)
![WoWScrnShot_110924_151017](https://github.com/user-attachments/assets/5a86577f-e195-419e-a687-14198310f497)

**Comment by oneadanut** [comment]
I forgot to specify that the damage should tick from each player when in 15y radius, if they spread fast, they should take only 1 tick from himself until they unlink completely.

![image](https://github.com/user-attachments/assets/d6446c92-18c3-4381-a8ba-6cf2eef41e84)

**Comment by Afgann** [comment]
fixed
