### ISSUE TITLE
Mage portals

### ISSUE THREAD

**Issue by Amine-x-x** [gamefreedomgit/Frostmourne#2301]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
players was trolling in battleground, he was using mage portals so the players click them and gets deserter. i just wish that those portals are disabled during battleground since there is no sense for them to exist there and to avoid trolls.

**How to reproduce:**

**How it should work:**
Disabled during battleground is good specially if the players are low levels with no clue about portals or some curious players thinking what will happen if they click.

**Database links:**

**Comment by Afgann** [comment]
fixed
