### ISSUE TITLE
Windfury+Icy Talon stackable

### ISSUE THREAD

**Issue by Nihaobeachez** [gamefreedomgit/Frostmourne#2303]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** We discovered randomly that Windfury Totem and Icy Talon are stackable right now (Windfury was 0/2 skilled, we didnt test 1/2 or 2/2)

**How to reproduce:** Place down 0/2 Windfury+DK with Icy talon to see they are stackable

**How it should work:** Only highest Attackspeed Buff of these 2 Buffs should be applied.

**Database links:**

**Comment by Afgann** [comment]
fixed
