### ISSUE TITLE
[Quest] Hunting for Ectoplasm

### ISSUE THREAD

**Issue by gingerdadman** [gamefreedomgit/Frostmourne#2305]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk/quest=8924/hunting-for-ectoplasm)

**Description:**
This quest grants Mux's Quality Goods which is supposed to contain goblin rocket fuel. I received none and had to have an alchemist make some to continue the quest.

**How to reproduce:**
You only get this bag the first time you take the quest

**How it should work:**
You should get 8 goblin rocket fuel

**Database links:**
https://www.wowhead.com/wotlk/item=22320/muxs-quality-goods#contains

**Comment by Afgann** [comment]
fixed
