### ISSUE TITLE
Speak with Ruga

### ISSUE THREAD

**Issue by Vaxsysl** [gamefreedomgit/Frostmourne#2306]
**Description:**
Warrior's quest Speak with Ruga not available in Undercity. I am unsure if it is the same for ther cities. I went to Orgrimmar to get it.

**How to reproduce:**
Login and see.

**How it should work:**
Every Warrior Class Trainer at capital town should give it once warrior reaches level 20.

**Database links:**
https://www.wowhead.com/wotlk/quest=1823/speak-with-ruga

**Comment by Afgann** [comment]
fixed
