### ISSUE TITLE
Skeletal Executioner

### ISSUE THREAD

**Issue by Vaxsysl** [gamefreedomgit/Frostmourne#2308]
**Description:**
That mob should not be in level 10-20 zone. It went a long way from the Plaguelands to chill with Murlocs.
![WoWScrnShot_110624_000754](https://github.com/user-attachments/assets/24db2dbd-65a2-404a-a3d7-3d0495157802)

**How to reproduce:**
Login there and see him. I encountered him on several HC chars already.
He might be far in the air. When he stops moving for a bit at the hut he goes so far up in the air he's invisible until you come close to loot the chest there. It's a lethal death trap, getting Frost Nova'd from the murlocs and him on your tail.

**How it should work:**
That mob should not be there. And he is for months. It seems I forgot to report it. Very lethal for HC if he's atop of the hut, high in the air, "invisible" until too late.

**Database links:**
https://www.wowhead.com/wotlk/npc=1787/skeletal-executioner

**Comment by Vaxsysl** [comment]
This is him months prior. Not highest I've seen him, but high enough. ![WoWScrnShot_081724_140158](https://github.com/user-attachments/assets/45a7ca19-0899-4576-b555-182952bfc6af)

**Comment by Vaxsysl** [comment]
Found highest point. 
![WoWScrnShot_071624_223614](https://github.com/user-attachments/assets/ee5a1bf0-decd-40e1-93a0-dd8f279d5c70)

Now just imagine him dropping down to cleave your face as murlocs root you...

**Comment by Afgann** [comment]
fixed
