### ISSUE TITLE
[TBC] [Quest] [Dungeon] Lost in Action – Claw can be killed

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2309]
During the quest [Lost in Action](https://www.wowhead.com/tbc/quest=9738/lost-in-action), player needs to fight [Claw](https://www.wowhead.com/tbc/npc=17827/claw) until he reaches 19% of HP and becomes friendly. Currently the player is capable of killing Claw before he becomes friendly. Observed on Heroic difficulty.
Note: there is nothing in my arsenal that would hit the boss for 20% of its HP (circa 17.5k)

https://www.wowhead.com/tbc/npc=17827/claw#comments:id=28242:reply=4058
https://www.wowhead.com/tbc/npc=17827/claw#comments:id=179958

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
