### ISSUE TITLE
[TBC] [Quest] Bring Me a Shrubbery – Not enough Hibisci spawns

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2310]
In quest [Bring Me A Shrubbery!](https://www.wowhead.com/tbc/quest=9715/bring-me-a-shrubbery) palyer needs to collect [Sanguine Hibiscus](https://www.wowhead.com/tbc/item=24246/sanguine-hibiscus) either by looting them from NPCs in Underbog or picking them up in Underbog. There should be more spawns of [Sanguine Hibiscus](https://www.wowhead.com/tbc/object=183385/sanguine-hibiscus). From another private servers I remember more spawns and this comment mentions being able to collect approximately 5 per run in stealth (no fighting) and not even while going the whole dungeon. Currently there is only 2 spawns, one at the ramp going to the 1st boss and one at the very end of the dungeon.

https://www.wowhead.com/tbc/quest=9714/bring-me-another-shrubbery#comments:id=2986860

**Comment by Piootrek** [comment]
There are currently 17 spawns of this object.
