### ISSUE TITLE
[TBC] [Dungeon] The Slave Pens – Wastewalker Captive

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2311]
[Wasterwalker Captive](https://www.wowhead.com/wotlk/npc=18206/wastewalker-captive) locked in the cage in The Slave Pens near Quagmirran, the last boss, left his cage when I got too close and started to melee me down 680-910 damage on dps plate warrior. This Captive did not have a name visible, wasn't targettable and no damage was able to harm him (Thunderclap AoE). He followed me through the dungeon until he killed me.
This should not occur and all the Captives should be checked. Occured in Heroic version fo the dungeon, probably the same issue in Normal.

**Comment by Afgann** [comment]
fixed
