### ISSUE TITLE
[TBC] [Quest] Fhwoor Smash! – Incomplete events

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2312]
During the quest [Fhwoor Smash!](https://www.wowhead.com/wotlk/quest=9729/fhwoor-smash#comments) player escorts [Fhwoor](https://www.wowhead.com/wotlk/npc=17877/fhwoor) to pick up Ark of Ssslith and get back with it. Parts of the event are missing. Fhwoor is not seen picking up any Ark (ark is missing, there is no emote) and on the way back [Ssslith](https://www.wowhead.com/wotlk/npc=18154/ssslith) and his guards do not spawn.

https://wowpedia.fandom.com/wiki/Fhwoor_Smash!#Notes
https://www.wowhead.com/wotlk/quest=9729/fhwoor-smash#comments:id=278409
https://www.youtube.com/watch?v=8daLzR6i5zI&ab_channel=TheChroniclesofAzeroth

**Comment by Riztazz** [comment]
The quest is poorly scripted by blizzard itself:P 
https://youtu.be/XvVA85qE2Z0?t=214

This is where pick-up happens, same effect on older videos as well. I'll fix a bunch of other stuff and the SSlith event

**Comment by Riztazz** [comment]
Fixed, will close once it's live
