### ISSUE TITLE
[TBC] [Quest] By Any Means Necessary – Missing prerequisite and event

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2314]
Quest [By Any Means Necessary](https://www.wowhead.com/wotlk/quest=9978/by-any-means-necessary) should be available once both [Clues in the Thicket](https://www.wowhead.com/wotlk/quest=9971/clues-in-the-thicket) and [Strange Energy](https://www.wowhead.com/wotlk/quest=9968/strange-energy). However the quest is offered after player completes Strange Energy, without need of doing Clues in the Thicket.

https://www.wowhead.com/wotlk/quest=9978/by-any-means-necessary#comments:id=30803
https://wowpedia.fandom.com/wiki/By_Any_Means_Necessary?oldid=874028

Second issue is that player is tasked of getting information out of [Empoor](https://www.wowhead.com/wotlk/npc=18482/empoor). Player should talk with him and Empoor and his [bodyguard](https://www.wowhead.com/wotlk/npc=18483/empoors-bodyguard) should attack the player. When Empoor is almost dead, or his HP depleted, he should turn friendly and should provide player with quest completion. However I met him without his bodyguard and he did not fight me at all, he simply complete the quest for me. It might have ben a result of some other player doign the quest shortly before me, hower as I write this report, his bodyguard is still nowhere to be found.

https://www.wowhead.com/wotlk/npc=18482/empoor#comments:id=2835599
https://wowpedia.fandom.com/wiki/By_Any_Means_Necessary?oldid=6246469#Notes
0:39 classic https://www.youtube.com/watch?v=whpkc1BaBAE&ab_channel=Bue

**Comment by Greywolf59** [comment]
Update: found the bodyguard at the spawn location, standing there and not moving.

**Comment by Piootrek** [comment]
Fixed, I will close this issue after the fix comes live.
