### ISSUE TITLE
[TBC] [Quest] Fel Orc Plans – Missing Prerequiste

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2315]
Quest [Fel Orc Plans](https://www.wowhead.com/wotlk/quest=10012/fel-orc-plans) should be obtainable only after player completes [Unruly Neighbors](https://www.wowhead.com/wotlk/quest=9998/unruly-neighbors) (A) or [An Unwelcome Presence](https://www.wowhead.com/wotlk/quest=10000/an-unwelcome-presence) (H). Currently the quest is obtainable even while doing the prequests, suggesting it is missing prerequisite whatsover.

https://www.wowhead.com/wotlk/quest=10012/fel-orc-plans#comments:id=288603

**Comment by Afgann** [comment]
fixed
