### ISSUE TITLE
[TBC] [Quest] Missing Friends – Only half of the children

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2318]
In the quest [Missing Friends](https://www.wowhead.com/wotlk/quest=10852/missing-friends), player needs to free [12 children](https://www.wowhead.com/wotlk/npc=22314/captive-child), however there is only 6 in total in the cages. Problem is that the cages have about half of the amount of children in them than they should have, two ground ones have 1 child, two tree ones have two children each. It should be doubled or, as other comments say, it should be made so that more children appear as the time since the cage was open last time gets longer.

https://www.wowhead.com/wotlk/quest=10852/missing-friends#comments:id=18462
https://www.wowhead.com/wotlk/quest=10852/missing-friends#comments:id=22681
https://www.wowhead.com/wotlk/quest=10852/missing-friends#comments:id=3000223:reply=1262531

**Comment by Afgann** [comment]
fixed
