### ISSUE TITLE
[Priest] Lightwell doesn't work properly

### ISSUE THREAD

**Issue by kinpie** [gamefreedomgit/Frostmourne#232]
**Links:**

[/Evidence/]: # https://www.youtube.com/watch?v=c1ZoAquHGPU&t=141s
[/Previous Post#2/]: # https://github.com/SunwellTracker/issues/issues/3572
[/Previous Post#1/]: # https://github.com/SunwellTracker/issues/issues/2697

/wave
/hello

**Description:**

Lightwell only allows one use per player.

**How to reproduce:**

Cast Lightwell and click it. Clicking it again will not cause the healing effect to occur.

**How it should work:**

Cast Lightwell and click it. You may click Lightwell again and get healed again. Each time you click Lightwell, a charge is removed.

**Additional Comments:**

It's broken again but should be an easy fix. I'm the same player who reported it on past projects.  Refer to my github links for more info. Refer to the YouTube link to see how Lightwell actually worked on 3.3.5 (Sept 4th, 2010).

Thank you in advance <3 <3 <3

/bow
/bye

**Database links:**

[/Evidence/]: # https://www.youtube.com/watch?v=c1ZoAquHGPU&t=141s
[/Previous Post#2/]: # https://github.com/SunwellTracker/issues/issues/3572
[/Previous Post#1/]: # https://github.com/SunwellTracker/issues/issues/2697

**Comment by Acurtis03** [comment]
i remember this being an issue on passed realms, and them getting the fix. hopefully they can get this fix implemented before launch, lightwell is one of the coolest spells that Holy priest has available to them so big hopes for this getting handled!
