### ISSUE TITLE
[TBC] [Quest] What Book? I Don't See Any Book – phrase spoken in Draenei speech

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2320]
During the quest [What Book? I Don't See Any Book](https://www.wowhead.com/quest=10231/what-book-i-dont-see-any-book) player has to talk with ["Dirty" Larry](https://www.wowhead.com/npc=19720/dirty-larry#ends) and beat him down to complete the quest.
The event after chatting with Larry is incomplete, missing:
["Epic" Malone](https://wowpedia.fandom.com/wiki/%22Epic%22_Malone) and ["Creepjack"](https://wowpedia.fandom.com/wiki/%22Creepjack%22) get up.
"Epic" Malone cracks his knuckles.
"Creepjack" cracks his knuckles.

Also one line spoken By Larry is in Draenei speech. The faulty line is:
"Dirty" Larry says: Time to meet your maker!

https://wowpedia.fandom.com/wiki/What_Book%3F_I_Don%27t_See_Any_Book.#Progress

**Comment by Piootrek** [comment]
Fixed, I will close this issue when the fix comes live.
