### ISSUE TITLE
[TBC] [Quest] Digging Through Bones – Missing escord NPCs, incomplete event

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2321]
During the quest [Digging Through Bones](https://www.wowhead.com/wotlk/quest=10922/digging-through-bones), player needs to escort [Chief Archaeologist Letoll](https://www.wowhead.com/wotlk/npc=22458/chief-archaeologist-letoll) and [Explorers' League Researchers](https://www.wowhead.com/wotlk/npc=22464/explorers-league-researcher) to a digging spot. However the Researches are not in the camp, rather a bit further away and they do not join the escort.

https://wowpedia.fandom.com/wiki/Digging_Through_Bones#Notes
https://www.wowhead.com/wotlk/quest=10922/digging-through-bones#comments:id=57144
https://www.youtube.com/watch?v=1HzdAMDeoJw&ab_channel=TomSanGames

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
