### ISSUE TITLE
[TBC] [Quest] The Totem of Kar'dash (A) – one line in Orcish, enemies not talking

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2322]
During the escort at quest [The Totem of Kar'dash](https://www.wowhead.com/wotlk/quest=9879/the-totem-of-kardash#comments), [Kurenai Captive](https://www.wowhead.com/wotlk/npc=18209/kurenai-captive) says this line in Orcish: Kurenai Captive says: It's an ambush! Defend yourselves!
Some lines are missing during the escort, both Captive's and [attackers](https://www.wowhead.com/wotlk/npc=18202/murkblood-putrifier).
Reskin: https://www.youtube.com/watch?v=kqJbUTHAWXI&ab_channel=MichaS
ITBC classic: https://www.youtube.com/watch?v=YlpyJpr605k&ab_channel=Bue

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
