### ISSUE TITLE
Allow Algalon Big Bang to be soaked by shaman totems

### ISSUE THREAD

**Issue by query-wow** [gamefreedomgit/Frostmourne#2324]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Currently in Algalon during the big bang, one player has to soak it so it doesn't wipe the raid, however, leaving the shaman Earth Elemental doesn't work. This **IS** probably intended in the 3.3.5a version, however, in classic this is no longer the case. Since some classic mechanics were introduced here, could you allow us to be able to soak Big Bang with Shaman totems as well? 
In 10man, not everyone has a shadow or a rogue, without these classes you're basically bound to soak one with Ardent or some other huge raid CD and not have it for the second one.
We tried this even with the Elemental being on the threat table, Algalon just casts Ascend to the Heavens anyways. 

**How to reproduce:**
Leave the earth elemental on the normal phase and everyone enters the black hole

**How it should work:**
 - This is probably a classic introduced mechanic, therefore i'll leave it to your discretion whether or not you want to implement this. 

**Database links:**
https://www.reddit.com/r/classicwow/comments/1132ks5/how_to_survive_algalon_big_bang/

**Comment by Piootrek** [comment]
We've decided to implement this. It will be live after next server update.

**Comment by wowclassic1234** [comment]
This is contrary to blizzlike. Neither in 2009 nor in 2023 did it work like that.

**Comment by sputnikk** [comment]
It did indeed work in wotlk classic, people were soaking 2 bigbangs with a single shaman elemental guardian totem.
However, I'm pretty sure this is a classic bug that they cba'd addressing more than a feature or anything else.

**Comment by query-wow** [comment]
> This is contrary to blizzlike. Neither in 2009 nor in 2023 did it work like that.

Clearly https://www.youtube.com/watch?v=PuM_-mddChI
