### ISSUE TITLE
[Graveyard] [Dying in Scarlet monastery entrance teleports you to the barrens graveyard

### ISSUE THREAD

**Issue by GM-Nightmare** [gamefreedomgit/Frostmourne#2329]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
![image](https://github.com/user-attachments/assets/565ffd1c-31be-4d66-98e1-7cc16279438f)
exact location 

**How to reproduce:**
dying here teleports you to graveyard in the barrens (blood elf horde tried so far)

**How it should work:**
you should be teleported to closest graveyard not one in the barrens :)

**Database links:**

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
