### ISSUE TITLE
[Paladin] Light's Grace not applying while casting holy lights

### ISSUE THREAD

**Issue by oomshroom** [gamefreedomgit/Frostmourne#233]
Sometimes while chain casting holy lights, [Light's Grace](https://wotlk.evowow.com/?spell=31836) doesn't apply, presumably due to spell batching.
[https://www.youtube.com/watch?v=Sm59n6N885M](https://www.youtube.com/watch?v=Sm59n6N885M)
This video is from a raid, with 3/3 points in Lights Grace. You can see the cast time of Holy Light randomly going to 1.84 from 1.47 as Light's Grace fails to apply.

Likely just one symptom of a deeper issue...

**Comment by Afgann** [comment]
fixed
