### ISSUE TITLE
[TBC] [Quest] Protecting Our Own (A) – no Living Grove Defender spawn

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2331]
In quest [Protecting Our Own](https://www.wowhead.com/wotlk/quest=10457/protecting-our-own#comments), player needs to use [Rina's Bough](https://www.wowhead.com/wotlk/item=29952/rinas-bough) on [Grove Seedlings](https://www.wowhead.com/wotlk/object=184631/grove-seedling). This should spawn [Living Grove Defender](https://www.wowhead.com/wotlk/npc=21072/living-grove-defender#comments), however it does not. Credit for quest is awarded.

https://www.wowhead.com/wotlk/npc=21072/living-grove-defender#comments:id=110889
https://www.wowhead.com/wotlk/quest=10457/protecting-our-own#comments:id=132103

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
