### ISSUE TITLE
[TBC] [Quest] Gorgrom the Dragon-Eater A – Alli version spawns Misha

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2335]
When the Alliance player do the quest [Gorgrom the Dragon-Eater](https://www.wowhead.com/wotlk/quest=10802/gorgrom-the-dragon-eater#comments), using [Sablemane's Trap](https://www.wowhead.com/wotlk/item=31827/sablemanes-trap) summons hostile [Misha](https://www.wowhead.com/wotlk/npc=10204/misha). 
Misha should be spawned only during the Horde version fo the quest.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
