### ISSUE TITLE
[Quest] Amongst the Ruins - respawn rate

### ISSUE THREAD

**Issue by Furiianda** [gamefreedomgit/Frostmourne#2336]
**Description:**
The quest item Fathom Core for the BFD quest Amongst the Ruins does not respawn, meaning only one player in the dungeon group can complete the quest.

**How to reproduce:**
Loot the stone (found underwater near the end of the dungeon), it disappears and does not come back.

**How it should work:**
The quest item should have a short respawn timer(<20 sec), and the elite mob Baron Aquanis should only spawn for the first player in the dungeon to loot the stone.

**Database links:**
https://www.wowhead.com/wotlk/quest=6921/amongst-the-ruins

**Comment by Riztazz** [comment]
Fixed, will close once it's live
