### ISSUE TITLE
[TBC] [Quest] Showdown (A) – missing event

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2338]
During the quest [Showdown](https://www.wowhead.com/wotlk/quest=10806/showdown), [Sablemane](https://www.wowhead.com/wotlk/npc=22473/baron-sablemane) yells one of his replicas in orcish:
Baron Sablemane yells: Let us begin.
Other problem is that when [Goc](https://www.wowhead.com/wotlk/npc=20555/goc) reaches 15% HP, ther should be another event where Sablemane turns into dragon [Sabellian](https://www.wowhead.com/wotlk/npc=22496/sabellian#comments). This part of the event does not happen at all. I have fought Goc very slowly and carefully to check this.

Baron Sablemane yells: We will speak again, but away from here. + the teleport away occur normally.
https://wowpedia.fandom.com/wiki/Showdown_(quest)
https://www.youtube.com/watch?v=Lli07104ypo&ab_channel=Bue

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
