### ISSUE TITLE
[TBC] [Quest] Into the Soulgrinder – Missing post-completion event; Speak with Mog'dorg – inavailable

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2339]
ISSUE 1
After handing in the quest [Into the Soulgrinder](https://www.wowhead.com/wotlk/quest=11000/into-the-soulgrinder), [Mog'dorg the Wizened](https://www.wowhead.com/wotlk/npc=22941/mogdorg-the-wizened) says: All hail, <name>, the new <king/queen> of the ogres!!! // And that is it.

The line should be yelled, lots of ogres should spawn hailing the player and all ogres in Blade's Edge should turn neutral forever for the player.

https://wowpedia.fandom.com/wiki/Into_the_Soulgrinder#Completion
https://www.wowhead.com/wotlk/quest=11000/into-the-soulgrinder#comments:id=209914
https://www.wowhead.com/wotlk/quest=11000/into-the-soulgrinder#comments:id=193236
https://www.youtube.com/watch?v=4at-UTC_wio&ab_channel=WoWQuests
Could not find any other video, everyone cuts it right after hand-in.

ISSUE 2
Quest [Speak with Mog'dorg](https://www.wowhead.com/wotlk/quest=11022/speak-with-mogdorg) is inavailable since the quest  giver [Bladespire Supplicant](https://www.wowhead.com/wotlk/npc=23053/bladespire-supplicant) doesn't spawn (due to ISSUE 1). 
This quest is optional and its follow-up is normally available.
https://www.youtube.com/watch?v=54lfg6sJZ7w&ab_channel=TomSanGames

**Comment by Piootrek** [comment]
Do you know if those ogres should stay visible there for the player or just despawn after some time?

**Comment by Greywolf59** [comment]
From other server I think I remember they eventually do despawn, maybe on logout.
