### ISSUE TITLE
[Quest] Blueleaf Tubers

### ISSUE THREAD

**Issue by Furiianda** [gamefreedomgit/Frostmourne#2340]
**Description:**
The quest cannot be progressed as, while the gophers can be summoned, the Snufflenose Command Stick item has no effect at multiple points in the Razorfen Kraul dungeon. This might be an issue with a lack of tubers in the dungeon. 

**How to reproduce:**
Attempt to complete the quest as normal, and the command stick item won't have any effect.

**How it should work:**
When using the Snufflenose Command Stick with summoned Snufflenose Gophers, the gophers should search the nearby area for the Tuber items and return lootable objects to the player's location.

**Database links:**
https://www.wowhead.com/wotlk/quest=1221/blueleaf-tubers

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
