### ISSUE TITLE
[Emote] Cower does not loop

### ISSUE THREAD

**Issue by Furiianda** [gamefreedomgit/Frostmourne#2341]
**Description:**
When using the /cower emote, it only lasts about 2 seconds, rather than looping indefinitely, like the /dance emote.

**How to reproduce:**
Type /cower.

**How it should work:**
Cower should loop indefinitely until the player moves or performs an action (just like /dance).

**Database links:**
N/A

**Comment by Piootrek** [comment]
Do you have any proof that Cower should loop?

**Comment by Furiianda** [comment]
Sure, how about this video from 2009?: https://www.youtube.com/watch?v=yBIB3bQvrnw  (patch 3.0.8)

Looping Cower also seems to be working in newer versions of the game, from Cata here on Whitemane, to retail, with no changelogs noted for the emote from official sources (checked via the usual community wiki sites). 

some comments I found during my search noted that during the Wrath beta (or prepatch from the end of TBC?), /cower did not loop either. There are some earlier videos showing that, but during Wrath's final patch it definitely looped, to my recollection.
Additionally found claims from the era that the variant /scared was a short non-looping version while /cower or /fear are the looping one (I do not have proof for that one in video however, sorry!) in case that info is useful to you.
Thanks for looking into it ^_^

**Comment by scrublama** [comment]
extremely minor, but when you /cower then mount and dismount its still looping, /dance breaks the loop when you do this. Not sure which one is correct but should be same behaviour ig @Piootrek

**Comment by Furiianda** [comment]
> extremely minor, but when you /cower then mount and dismount its still looping, /dance breaks the loop when you do this. Not sure which one is correct but should be same behaviour ig @Piootrek

Mount should break both for sure. However this is hilarious 👍

**Comment by Piootrek** [comment]
> extremely minor, but when you /cower then mount and dismount its still looping, /dance breaks the loop when you do this. Not sure which one is correct but should be same behaviour ig @Piootrek

Fixed
