### ISSUE TITLE
[TBC] [NPC] Skyguard Khatie – says Gossip in Emote

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2342]
[Skyguard Khatie](https://www.wowhead.com/tbc/npc=23335/skyguard-khatie) instead of saying any of the quotes listed, says her whole gossip text upon player's arrival. In my case since I am revered, she said the whole revered gossip.

https://www.wowhead.com/tbc/npc=23335/skyguard-khatie
https://wowpedia.fandom.com/wiki/Skyguard_Khatie#Quotes

https://www.wowhead.com/tbc/npc=23335/skyguard-khatie#comments:id=214464
https://www.wowhead.com/tbc/npc=23335/skyguard-khatie#comments:id=231039

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
