### ISSUE TITLE
Flame Leviathan bonus loot is not working

### ISSUE THREAD

**Issue by roblox-oof-dot-mp3** [gamefreedomgit/Frostmourne#2344]
**Description:**
Flame leviathan is currently only giving bonus loot in the form of a hardmode piece when all 4 towers are left up. It should have additional bonuses that trigger when 2+ and 3+ towers are left up. 2 towers should guarantee an additional runed orb, while 3 towers should guarantee a pattern. 

I've included images from the wiki describing this behavior for 10 and 25, as well as snippets of random hardmode kills I found on youtube where you can see there's always a pattern in the loot.

**How to reproduce:**
Kill Flame Leviathan and loot it

**How it should work:**
Taken from the WoWpedia wiki:
![image](https://github.com/user-attachments/assets/1b2500a4-6e72-484c-8365-95289ef71d9c)
![image](https://github.com/user-attachments/assets/c829857c-f9e6-4664-b288-667749a032ec)

https://youtu.be/MQ3vPoX8DWw?si=qbe5J7K-2W4BnUl-&t=288
https://youtu.be/aCuWMlboPK8?si=KKPPegiPbIz7SJM7
https://youtu.be/7nKivv2tiuU?si=Jz0_rAOIZn5dyYza&t=1237
https://www.youtube.com/live/ltWkCBdd-xk?si=uBLkjlonph13OQkd

**Database links:**

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
