### ISSUE TITLE
Thaddius not engaging bug

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#235]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
After killing feugen and stalagg we jumped down towards thaddius and the boss didn't activate

https://youtu.be/hA5kQhYIxY8

**Comment by UltraNix** [comment]
Fixed.
