### ISSUE TITLE
Skadi -  Utgarde Pinnacle

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#2351]
Skadi is not working properly. 
1) His flight route is incorrect. He moves only through the tunnel, through which the players run to the harpoons. Must fly out of it making a circle.
2) The interval for the boss to use breaths is too long. This is because it hangs in the air for a long time. On our server, you can run to the harpoons, then go back to where the boss started, and only at this time the boss uses his breath. From the moment the event starts, the first breath must be used after 32 seconds and all subsequent ones too.
3) When he uses the whirlwind, he should pick a target from the group including the tank and chase him in the whirlwind. The tank should constantly use taunt to keep the boss on him. As soon as the taunt end, he should change the target to the player being chased. This does not work on our server. He always hangs around the tank.

https://youtu.be/qrXzIqhugZ4?t=688

https://www.wowhead.com/wotlk/npc=26893/grauf
https://www.wowhead.com/npc=26693/skadi-the-ruthless

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
