### ISSUE TITLE
Tier set not applying with Transmog applied 

### ISSUE THREAD

**Issue by Lanarrin** [gamefreedomgit/Frostmourne#2352]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
My 4 piece T8 set bonus was not applying with a transmog applied to my helm

**How to reproduce:**
I was wearing Conq Seigebreaker chest, Great helm, and valorous siegebreakers hands and pauldrons. with my helm transmoged to the horsemans horrific helm. and it would not recognize the helmet as part of the set. only after removing the tmog did the 4p bonus show properly. Since there is no viewable buff from the 4p set bonus i was unable to tell if the bonus was applied or not. 

**How it should work:**
The set bonus should apply regardless of tmog. 

**Database links:**
https://www.wowhead.com/wotlk/item-set=-80/conquerors-siegebreaker-plate 
https://www.wowhead.com/wotlk/item=49126/the-horsemans-horrific-helm

**Comment by Piootrek** [comment]
It's just visual bug, bonus set is correctly applied.
