### ISSUE TITLE
[TBC] [Quest] Wrangle Some Aether Rays + daily – Rays don't follow

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2354]
During [this quest](https://www.wowhead.com/wotlk/quest=11065/wrangle-some-aether-rays) and the daily, player is supposed to wrangle Aether Rays.
[Wrangled Aether Rays](https://www.wowhead.com/wotlk/npc=23343/wrangled-aether-ray) should follow the player until the quest is handed in.

https://www.wowhead.com/wotlk/quest=11065/wrangle-some-aether-rays#comments:id=88253
https://wowpedia.fandom.com/wiki/Wrangle_More_Aether_Rays!#Notes

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
