### ISSUE TITLE
[TBC] [Quest] Harbingers of Shadowmoon – Harbingers missing whispers

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2358]
During the quest [Harbingers of Shadowmoon](https://www.wowhead.com/wotlk/quest=10643/harbingers-of-shadowmoon) player needs to kill [Shadowmoon Harbingers](https://www.wowhead.com/wotlk/npc=21795/shadowmoon-harbinger#comments). They should whisper to player about Gorefiend upon their death, which is reflected in quest completion text.
The mobs do not whisper.

https://www.wowhead.com/wotlk/npc=21795/shadowmoon-harbinger#comments:id=328354
https://wowpedia.fandom.com/wiki/Shadowmoon_Harbinger

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
