### ISSUE TITLE
Quest : Test of Lore

### ISSUE THREAD

**Issue by KryndorX** [gamefreedomgit/Frostmourne#2359]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The quest asks you to go in scarlet monatery liberary dungeon and loot the item "Beginnings of the Undead Threat" , the item is not clickable it just shines.

**How to reproduce:**
Take the quest and try to click the book.

**How it should work:**
Book should be clickable.

**Database links:**
Item : https://www.wowhead.com/wotlk/item=5861/beginnings-of-the-undead-threat
Quest : https://www.wowhead.com/wotlk/quest=1160/test-of-lore

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
