### ISSUE TITLE
Warlock portal still stuck sometimes after fixes

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#236]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
After restart applying last fixes warlock portal worked perfectly for a while spawning instantly. However, after a while it started being stuck again and being placed after 2 minutes of casting it. Then it worked again. So its very random now but it does still bug sometimes. The fixes were good it probably just need a last bit of touch-up.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
@BalanCV Can you record that bug?

**Comment by WhitemaneIsa** [comment]
No further info/complaints, closing.
