### ISSUE TITLE
[TBC] [Quest] Divination: Gorefiend's Truncheon – Missing prerequisite

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2362]
Quest [Divination: Gorefiend's Truncheon](https://www.wowhead.com/wotlk/quest=10636/divination-gorefiends-truncheon) is avaialble before player hands in [Teron Gorefiend - Lore and Legend](https://www.wowhead.com/wotlk/quest=10644/teron-gorefiend-lore-and-legend), which should be prerequisite for this quest.
https://www.wowhead.com/wotlk/quest=10636/divination-gorefiends-truncheon#comments:id=46300
https://wowpedia.fandom.com/wiki/Divination:_Gorefiend%27s_Truncheon?so=search#Progression

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
