### ISSUE TITLE
[TBC] [Quest] Demonic Crystals Prison – Only ghost spawns

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2363]
After completing [Demonic Crystal Prisons](https://www.wowhead.com/wotlk/quest=10528/demonic-crystal-prisons), ghost of Ar'tok spawns, however his body stays afloat bounded by the crystal. The crystals should stop binding the body and his body finally properly die.

https://www.youtube.com/watch?v=LMJXclYv1U0&ab_channel=Bue
https://www.youtube.com/watch?v=CJxvH2iaxhY&ab_channel=GitGudGuides

**Comment by Riztazz** [comment]
fixed, will close once it's live
