### ISSUE TITLE
[TBC] [Quest] Of Thistleheads and Eggs... – Missing post-completion event

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2364]
After handing in the [Of Thistleheads and Eggs..](https://www.wowhead.com/wotlk/quest=10547/of-thistleheads-and-eggs), small event should play out. This event is missing.

https://wowpedia.fandom.com/wiki/Of_Thistleheads_and_Eggs...?so=search#On_completion
13y old video: https://www.youtube.com/watch?v=SaSf1u8FRvo&ab_channel=Moronordon
1:56 https://www.youtube.com/watch?v=oD2u7R3aiKI&ab_channel=Bue
1:15 https://www.youtube.com/watch?v=GZz6CyM0mU4&ab_channel=PhoenixGaming

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
