### ISSUE TITLE
[MOUNT] Dark phoenix not shared between characters from different factions on the same account.

### ISSUE THREAD

**Issue by eni9m-a** [gamefreedomgit/Frostmourne#2365]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Dark Phoenix mount isn't shared between characters from different factions on the same account.

**How to reproduce:**

Log on a character that has the mount and the riding skill necessary to use it from X faction.
Log on a character that hasn't the mount and the riding skill necessary to use it from Y faction.

**How it should work:**

Both characters should be able to use the mount.

**Database links:**

**Comment by Piootrek** [comment]
It works correctly for me. Are you sure your other character has enough riding skill to use this mount?

**Comment by eni9m-a** [comment]
Hello,

Yes it has the correct riding skill and did not worked somehow.

Now it is working
