### ISSUE TITLE
[ToC25] Anub pursue is completely broken

### ISSUE THREAD

**Issue by broizter** [gamefreedomgit/Frostmourne#2367]
https://github.com/user-attachments/assets/8e378a69-4002-4203-b636-10171c184dc6

**Comment by broizter** [comment]
After Anub picks a target for pursue it gets instantly cancelled, and he picks a new one, causing spikes to never move and a combat log spam.

**Comment by oneadanut** [comment]
It happened in Toc10 heroic as well.

**Comment by Piootrek** [comment]
It was already fixed, but PTR wasn't updated. Can you recheck it now?

**Comment by broizter** [comment]
https://github.com/user-attachments/assets/e8a5c16c-0ef4-455e-bcf2-569c864b6afc

It's now working as expected. While I have you here I wanna ask if there's a better .tele command than trial? That one puts you in front of the 5man dungeon. I can't find the .tele command to be put in front of the raid entrance.

**Comment by Piootrek** [comment]
> It's now working as expected. While I have you here I wanna ask if there's a better .tele command than trial? That one puts you in front of the 5man dungeon. I can't find the .tele command to be put in front of the raid entrance.
There's only .tele trial

**Comment by broizter** [comment]
> > It's now working as expected. While I have you here I wanna ask if there's a better .tele command than trial? That one puts you in front of the 5man dungeon. I can't find the .tele command to be put in front of the raid entrance.
> > There's only .tele trial

Alright thanks. Well its not a big deal. Just a minor annoyance.
