### ISSUE TITLE
[ToC25] Slime pool on beasts is not generating a combat log event

### ISSUE THREAD

**Issue by broizter** [gamefreedomgit/Frostmourne#2368]
This ability should generate a SPELL_CAST_SUCCESS with spellid 66883, as shown in DBM from WotLK classic. It's the same in the DBM version made for 3.3.5.

![screenshot](https://github.com/user-attachments/assets/77c8ac68-0cc8-4b84-9948-17a12ada19c2)

**Comment by Riztazz** [comment]
fixed
