### ISSUE TITLE
[TBC] [Quest] [Dungeon] Imprisoned in the Citadel – quest giver missing

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2369]
The quest [Imprisoned in the Citadel](https://www.wowhead.com/wotlk/quest=9524/imprisoned-in-the-citadel#comments) in Hellfire Citadel – Shattered Halls Heroic is not obtainable. On heroic there should be quest giver NPC. This NPC is missing.
Alliance: [Randy Whizzlesprocket](https://www.wowhead.com/wotlk/npc=17288/randy-whizzlesprocket)
Horde: [Drisella](https://www.wowhead.com/wotlk/npc=17294/drisella)

**Comment by Riztazz** [comment]
fixed, will close once it's live

**Comment by Greywolf59** [comment]
I was not awarded credit for completion of this quest after killing the Executioner. Quest undoable.

**Comment by Riztazz** [comment]
New issue please, unrelated to main issue though it might seem like that
