### ISSUE TITLE
Mobs inside OS 3D portal Unknown

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#237]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
https://imgur.com/a/JRSrMTD
The mobs inside are named Unknown instead of Shade of Vesperon/Shadron? Since we need to kill a specific one this needs to be clarified.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
