### ISSUE TITLE
[TBC] [Item] Some TBC items missing sell price

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2371]
Random world drop, [Crystalforged War Axe](https://www.wowhead.com/wotlk/item=31291/crystalforged-war-axe) is missing vendor sell price.

This is not the first item I have encounter with this issue from TBC. Most of the items before were drops from dungeon bosses, however I did not monitor it, since I thought it normal.

I decided to go through AtlasLoot and check all items without selling price on PTR. Here is a list of dungeon drops missing vendor price:
PART 1, AUCHINDOUN
[Oculus of the Hidden Eye](https://www.wowhead.com/wotlk/item=26055/oculus-of-the-hidden-eye)
[Maladaar's Blessed Chaplet](https://www.wowhead.com/wotlk/item=27871/maladaars-blessed-chaplet)
[Slippers of Serenity](https://www.wowhead.com/wotlk/item=27411/slippers-of-serenity)
[Darkguard Face Mask](https://www.wowhead.com/wotlk/item=27415/darkguard-face-mask)
[Mok'Nathal Beast-Mask](https://www.wowhead.com/wotlk/item=27414/moknathal-beast-mask)
[Fetish of the Fallen](https://www.wowhead.com/wotlk/item=27416/fetish-of-the-fallen)
[Draenic Wildstaff](https://www.wowhead.com/wotlk/item=27877/draenic-wildstaff)
[Shield of the Void](https://www.wowhead.com/wotlk/item=28166/shield-of-the-void)
[Boots of the Colossus](https://www.wowhead.com/wotlk/item=27813/boots-of-the-colossus)
[Totem of the Astral Winds](https://www.wowhead.com/wotlk/item=27815/totem-of-the-astral-winds)
[Shaarde the Greater](https://www.wowhead.com/wotlk/item=25944/shaarde-the-greater)
[Mask of the Howling Storm](https://www.wowhead.com/wotlk/item=25955/mask-of-the-howling-storm)
[Lucid Dream Bracers](https://www.wowhead.com/wotlk/item=27827/lucid-dream-bracers)
[Stillwater Girdle](https://www.wowhead.com/wotlk/item=27835/stillwater-girdle)
[Sky-Hunter Swift Boots](https://www.wowhead.com/wotlk/item=27915/sky-hunter-swift-boots)
[Libram of the Eternal Rest](https://www.wowhead.com/wotlk/item=27917/libram-of-the-eternal-rest)
[The Boomstick](https://www.wowhead.com/wotlk/item=32780/the-boomstick)
[Ravenclaw Band](https://www.wowhead.com/wotlk/item=27925/ravenclaw-band)
[Terokk's Nightmace](https://www.wowhead.com/wotlk/item=27980/terokks-nightmace)
[Crow Wing Reaper](https://www.wowhead.com/wotlk/item=27986/crow-wing-reaper)
[Jaedenfire Gloves of Annihilation](https://www.wowhead.com/wotlk/item=27889/jaedenfire-gloves-of-annihilation)
[Soul-Wand of the Aldor](https://www.wowhead.com/wotlk/item=27885/soul-wand-of-the-aldor)
[Cloak of the Inciter](https://www.wowhead.com/wotlk/item=27892/cloak-of-the-inciter)
[Ornate Leggings of the Venerated](https://www.wowhead.com/wotlk/item=27893/ornate-leggings-of-the-venerated)
[Harness of the Deep Currents](https://www.wowhead.com/wotlk/item=27912/harness-of-the-deep-currents)
[Whispering Blade of Slaying](https://www.wowhead.com/wotlk/item=27913/whispering-blade-of-slaying)
[Shoulderguards of the Bold](https://www.wowhead.com/wotlk/item=27803/shoulderguards-of-the-bold)

PART 2, COILFANG
[Vest of Living Lightning](https://www.wowhead.com/wotlk/item=24357/vest-of-living-lightning)
[Wastewalker Shiv](https://www.wowhead.com/wotlk/item=24356/wastewalker-shiv)
[Totem of Spontaneous Regrowth](https://www.wowhead.com/wotlk/item=27544/totem-of-spontaneous-regrowth)
[Starlight Dagger](https://www.wowhead.com/wotlk/item=27543/starlight-dagger)
[Runed Fungalcap](https://www.wowhead.com/wotlk/item=24376/runed-fungalcap)
[Ironscale War Cloak](https://www.wowhead.com/wotlk/item=27550/ironscale-war-cloak)
[Liar's Cord](https://www.wowhead.com/wotlk/item=28124/liars-cord)
[Wavefury Boots](https://www.wowhead.com/wotlk/item=27549/wavefury-boots)
[Girdle of the Immovable](https://www.wowhead.com/wotlk/item=27672/girdle-of-the-immovable)
[Deft Handguards](https://www.wowhead.com/wotlk/item=24365/deft-handguards)
[Moonrage Girdle](https://www.wowhead.com/wotlk/item=27783/moonrage-girdle)
[Serpentcrest Life-Staff](https://www.wowhead.com/wotlk/item=27791/serpentcrest-life-staff)
[Gauntlets of the Bold](https://www.wowhead.com/wotlk/item=27475/gauntlets-of-the-bold)
[Sash of Serpentra](https://www.wowhead.com/wotlk/item=27795/sash-of-serpentra)
[Needle Shrike](https://www.wowhead.com/wotlk/item=27631/needle-shrike)
[Hungarhide Gauntlets](https://www.wowhead.com/wotlk/item=27745/hungarhide-gauntlets)
[Girdle of Living Flame](https://www.wowhead.com/wotlk/item=27743/girdle-of-living-flame)
[Ring of the Shadow Deeps](https://www.wowhead.com/wotlk/item=27761/ring-of-the-shadow-deeps)
[Greaves of the Iron Guardian](https://www.wowhead.com/wotlk/item=24456/greaves-of-the-iron-guardian)
[Skulldugger's Leggings](https://www.wowhead.com/wotlk/item=24466/skullduggers-leggings)
[Bone Chain Necklace](https://www.wowhead.com/wotlk/item=27779/bone-chain-necklace)

**Comment by Greywolf59** [comment]
PART 3, HF CITADEL
[Silent-Strider Kneeboots](https://www.wowhead.com/wotlk/item=27467/silent-strider-kneeboots)
[Girdle of the Blasted Reaches](https://www.wowhead.com/wotlk/item=27478/girdle-of-the-blasted-reaches)
[Light Scribe Bands](https://www.wowhead.com/wotlk/item=27452/light-scribe-bands)
[Volcanic Pauldrons](https://www.wowhead.com/wotlk/item=27454/volcanic-pauldrons)
[Oceansong Kilt](https://www.wowhead.com/wotlk/item=27458/oceansong-kilt)
[Vambraces of Daring](https://www.wowhead.com/wotlk/item=27459/vambraces-of-daring)
[Reavers' Ring](https://www.wowhead.com/wotlk/item=27460/reavers-ring)
[Libram of Avengement](https://www.wowhead.com/wotlk/item=27484/libram-of-avengement)
[Auslese's Light Channeler](https://www.wowhead.com/wotlk/item=24390/ausleses-light-channeler)
[Moonchild Leggings](https://www.wowhead.com/wotlk/item=27492/moonchild-leggings)
[Virtue Bearer's Vambraces](https://www.wowhead.com/wotlk/item=27489/virtue-bearers-vambraces)
[Signet of Repose](https://www.wowhead.com/wotlk/item=27491/signet-of-repose)
[Doomplate Gauntlets](https://www.wowhead.com/wotlk/item=27497/doomplate-gauntlets)
[Bloodsworn Warboots](https://www.wowhead.com/wotlk/item=27788/bloodsworn-warboots)
[Raiments of Divine Authority](https://www.wowhead.com/wotlk/item=24397/raiments-of-divine-authority)
[Pantaloons of Flaming Wrath](https://www.wowhead.com/wotlk/item=30709/pantaloons-of-flaming-wrath)
[Greaves of the Shatterer](https://www.wowhead.com/wotlk/item=27527/greaves-of-the-shatterer)
[Figurine of the Colossus](https://www.wowhead.com/wotlk/item=27529/figurine-of-the-colossus)
[Lightsworn Hammer](https://www.wowhead.com/wotlk/item=27538/lightsworn-hammer)

PART 4, TEMPEST KEEP
[Rubium War-Girdle](https://www.wowhead.com/wotlk/item=28375/rubium-war-girdle)
[Nether Core's Control Rod](https://www.wowhead.com/wotlk/item=28386/nether-cores-control-rod)
[Doomplate Chestguard](https://www.wowhead.com/wotlk/item=28403/doomplate-chestguard)
[Breastplate of the Bold](https://www.wowhead.com/wotlk/item=28205/breastplate-of-the-bold)
[Elementium Band of the Sentry](https://www.wowhead.com/wotlk/item=28407/elementium-band-of-the-sentry)
[Shiffar's Nexus-Horn](https://www.wowhead.com/wotlk/item=28418/shiffars-nexus-horn)
[Libram of the Lightbringer](https://www.wowhead.com/wotlk/item=28296/libram-of-the-lightbringer)
[Spaulders of the Righteous](https://www.wowhead.com/wotlk/item=27739/spaulders-of-the-righteous)
[Netherfury Cape](https://www.wowhead.com/wotlk/item=28371/netherfury-cape)
[Boots of the Glade-Keeper](https://www.wowhead.com/wotlk/item=28251/boots-of-the-glade-keeper)
[Totem of the Void](https://www.wowhead.com/wotlk/item=28248/totem-of-the-void)
[Cosmic Lifeband](https://www.wowhead.com/wotlk/item=28259/cosmic-lifeband)
[Dath'Remar's Ring of Defense](https://www.wowhead.com/wotlk/item=28265/dathremars-ring-of-defense)

PART 5, CAVERNS OF TIME
[Uther's Ceremonial Warboots](https://www.wowhead.com/wotlk/item=27420/uthers-ceremonial-warboots)
[Grips of the Lunar Eclipse](https://www.wowhead.com/wotlk/item=28214/grips-of-the-lunar-eclipse)
[Pauldrons of Sufferance](https://www.wowhead.com/wotlk/item=27433/pauldrons-of-sufferance)
[Wyrmfury Pauldrons](https://www.wowhead.com/wotlk/item=28344/wyrmfury-pauldrons)
[Sparking Arcanite Ring](https://www.wowhead.com/wotlk/item=28227/sparking-arcanite-ring)
[Hauberk of Desolation](https://www.wowhead.com/wotlk/item=28401/hauberk-of-desolation)
[Sun-Gilded Shouldercaps](https://www.wowhead.com/wotlk/item=27995/sun-gilded-shouldercaps)
[Hourglass of the Unraveller](https://www.wowhead.com/wotlk/item=28034/hourglass-of-the-unraveller)
[Primal Surge Bracers](https://www.wowhead.com/wotlk/item=28194/primal-surge-bracers)
[Pauldrons of the Crimson Flight](https://www.wowhead.com/wotlk/item=28207/pauldrons-of-the-crimson-flight)
[Scarab of the Infinite Cycle](https://www.wowhead.com/wotlk/item=28190/scarab-of-the-infinite-cycle)

**Comment by Greywolf59** [comment]
Found one more, random world drop: [The Oathkeeper](https://www.wowhead.com/wotlk/item=31299/the-oathkeeper)

**Comment by Riztazz** [comment]
In the future please open new issues as it's hard for me to track issues that are already closed.
I'll update those two
