### ISSUE TITLE
[TBC] [Quest] Potential for Brain Damage = High – not enough Relay spawns

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2376]
In the quest [Potential for Brain Damage = High](https://www.wowhead.com/wotlk/quest=10385/potential-for-brain-damage-high), player needs to drink [Ethereum Essence](https://www.wowhead.com/wotlk/item=29482/ethereum-essence) to be able to see [Ethereum Relays](https://www.wowhead.com/wotlk/npc=20619/ethereum-relay).
Player needs 15 drops from these guys. There is only 9 or 10 of them altogether. No wowhead comment mentions this issue, one comment mentions doing this quest in time of three drinks/buffs when drop was poor (here it is pretty much 100% I believe), which logically means there is either a lot more of them or the respawn is insane.

https://www.wowhead.com/wotlk/quest=10385/potential-for-brain-damage-high#comments:id=224043

**Comment by Riztazz** [comment]
Fixed, will close once it's live
