### ISSUE TITLE
[TBC] [Quest] The Flesh Lies... – Not enough spawns

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2377]
During the quest [The Flesh Lies...](https://www.wowhead.com/wotlk/quest=10345/the-flesh-lies), player needs to burn 12 [Withered Corpses](https://www.wowhead.com/wotlk/npc=20561/withered-corpses-burned). It seems there is only 10 in total and with decently long respawn timer (mobs respawn quicker).

UPDATE: The respawn of the first burned body took about 20-30 minutes.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
