### ISSUE TITLE
[TBC] [NPC] Adyen the Lightwarden – attacks Scryer players

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2379]
[Adyen the Lightwarden](https://www.wowhead.com/wotlk/npc=18537/adyen-the-lightwarden) is NPC standing right next to the other side of the portal used in the quest [Turning Point](https://www.wowhead.com/wotlk/quest=10507/turning-point). He attacks the player if the player chose the Scryer faction. He is unattackable and hits around 800 on lvl 80 plate.

[Deathblow to the Legion](https://www.wowhead.com/wotlk/quest=10409/deathblow-to-the-legion) event should be also checked, since I seen some random spawns of Aldor side of the quest while doing this as Scryer.
https://wowpedia.fandom.com/wiki/Deathblow_to_the_Legion#Notes

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
