### ISSUE TITLE
Pets are still not resetting sated

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#238]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Pets still keep their sated after cds reset. its not consistent but its still there.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
@Manpower99 What boss and what pet?

**Comment by Manpower99** [comment]
> @Manpower99 What boss and what pet?

Unholy DK Pet, bosses we killed and wiped on still kept sated

**Comment by UltraNix** [comment]
@Manpower99 Exactly - what boss?

**Comment by UltraNix** [comment]
Fixed.
