### ISSUE TITLE
[TBC] [Dungeon] The Mechanar HC: Mechano-Lord Capacitus – Missing abilities

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2380]
[Mechano-Lord Capacitus](https://www.wowhead.com/wotlk/npc=19219/mechano-lord-capacitus) is missing some of his abilities. He did use [Head Crack](https://www.wowhead.com/wotlk/spell=35161/head-crack) and summoned Nether Charges.
He did not use [Reflective Magic Shield](https://www.wowhead.com/wotlk/spell=35158/reflective-magic-shield) and [Reflective Damage Shield](https://www.wowhead.com/wotlk/spell=35159/reflective-damage-shield) and neither [Polarity Shift](https://www.wowhead.com/wotlk/spell=39096/polarity-shift).
Observed on Heroic Difficulty, Normal difficulty wasn't checked.

https://www.wowhead.com/wotlk/npc=19219/mechano-lord-capacitus#abilities;mode:normal
https://wowpedia.fandom.com/wiki/Mechano-Lord_Capacitus#Abilities

**Comment by Riztazz** [comment]
Reflective shield is a mechanic from normal

**Comment by Riztazz** [comment]
fixed the rest, will close once it's live. you were hit, just missed
