### ISSUE TITLE
[TBC] [Dungeon] The Mechanar: Nethermancer Sepethrea – Adds dont despawn upon wipe

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2381]
[Nethermancer Sepethrea](https://www.wowhead.com/wotlk/npc=19221/nethermancer-sepethrea) summons two/three (N/HC) [Raging Flames](https://www.wowhead.com/wotlk/npc=20481/raging-flames). These do not despawn if the party wipes. On next pull she adds another three, making it six elementals to deal with on second pull.
Observed on Heroic Difficulty, Normal wasn't checked.

https://www.wowhead.com/wotlk/npc=19221/nethermancer-sepethrea#drops;mode:normal
https://wowpedia.fandom.com/wiki/Nethermancer_Sepethrea#Strategy

**Comment by Riztazz** [comment]
fixed, will close once it's live
