### ISSUE TITLE
[TBC] [Dungeon] The Botanica – Commander Sarannis – Missing abilities

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2382]
It seems that [Commander Sarannis](https://www.wowhead.com/wotlk/npc=17976/commander-sarannis) is missing her abilities. She does summon the adds, however I haven't noticed any debuffs on me and all damage taken from her was pure melee. Also haven't noticed any special move when she yelled "Band'or shorel'aran!". Although it is possible her special attacks miss or were parried/dodged.
Observed on Heroic Difficulty, Normal wasn't checked.

https://wowpedia.fandom.com/wiki/Commander_Sarannis?so=search#Strategy
https://www.wowhead.com/wotlk/npc=17976/commander-sarannis

**Comment by Riztazz** [comment]
She is using her abilities correctly
