### ISSUE TITLE
[WOTLK][RAID] Bought an item from the Echo's Vendor by accident. After selling back after few minutes didn't get refund.

### ISSUE THREAD

**Issue by Aysta453** [gamefreedomgit/Frostmourne#2385]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Hello!

I bought an item from Echo's Vendor by mistake - In Ulduar Instance. 

![image](https://github.com/user-attachments/assets/a973a55d-75dc-48ee-9282-547a92612d3d)

Item - Pharos Gloves - for 12 Echo's.
Character: Mage Human - Aysta.

I tried to return this item to vendor to receive back Echo's emblems. But after selling this item I received nothing. 

**How to reproduce:**
Sell item.

**How it should work:**
User should receive Echo's emblems back. 

**Database links:**

**Comment by KryndorX** [comment]
Every item you buy for echo of the titans and you try to sell it back will not give you anything in return , the vendor just takes the item from you for free and asks you to pay gold if you want to buy it back.

**Comment by Aysta453** [comment]
That's correct.

But when you buy any item from other emblems vendors(valors, heroism and etc) this item is refundable for 2 hours. -Exception is if you put some enchant on this item or you put a gem( if item has socket). 


It shouldn't be like that also here?

**Comment by Aysta453** [comment]
![image](https://github.com/user-attachments/assets/e95dc7a3-caef-48d9-b16b-7c80b616e782)
Like here. I didn't manipulate an item in any possible way.

**Comment by Aysta453** [comment]
Okay. Thank you!
Should I call GM again to reset my situation (refund an item) or it will be handled automatically?
