### ISSUE TITLE
Debuff again stack

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#2386]
The problem is that the effects of reducing the attack speed by 20%+20% stack up, and the base attack speed 2.0 becomes 2.88. Please make a global correction so as not to create a report on the same topic every time, take into account all similar effects of both pets and classes.

https://www.wowhead.com/wotlk/spell=12287/improved-thunder-clap
https://www.wowhead.com/wotlk/spell=6343/thunder-clap
https://www.wowhead.com/wotlk/spell=27012/hurricane

![image](https://github.com/user-attachments/assets/c5833259-8f28-4993-81f3-8b7a09525b76)

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
