### ISSUE TITLE
Armor Kit error

### ISSUE THREAD

**Issue by Consealer** [gamefreedomgit/Frostmourne#2388]
Thick Armor Kit errors "Target too low level." when I applied to Dreamsinger Legguards.
Should work on items with item level 25+.
This happens to many more items.

In case you confuse "Requires Level" with "Item Level": They are not the same thing.

Thick Armor Kit
https://www.wowhead.com/wotlk/spell=10487/thick-armor-kit
Dreamsinger Legguards
https://www.wowhead.com/wotlk/item=13010/dreamsinger-legguards

**Comment by Piootrek** [comment]
It's not the bug. "Only usable on items level 25 and above" refers to required level, not item level and client blocks this action.

**Comment by Consealer** [comment]
> "Only usable on items level 25 and above" refers to required level, not item level
Nope... "Item level" refers to "item level" not "player level requited to use item".
But ok. Make me a favor and tell me "required level" of ... Chausses of Westfall. Which would be the highest Armor Kit I can use on them?

**Comment by Greywolf59** [comment]
Are you level 30, or is the user of the item enchanted level 30? there is hidden Player level requirement added to the ilvl requirement.
Combine table from here: https://wowpedia.fandom.com/wiki/Armor_kits?oldid=1734101 with https://www.wowhead.com/wotlk/spell=10487/thick-armor-kit#comments
Result: item needs to be at least level 25, player needs to be at least level 30.

**Comment by Consealer** [comment]
Character is 30+. Item level of Dreamsinger Legguards is 26, so 25+. Doesn't work, gives error "Target too low level.".
Devs confuse item level with character level required to use the item.

**Comment by Greywolf59** [comment]
In that case yes, I am inclined to believe this is a bug.

**Comment by Aeradel** [comment]
Tested, and this indeed is as Pio says.

The item cannot be used on level 24 items or less (tested).
The item can be used on level 25 items or higher (tested). 

It is very rare that items - especially as niche as this - are modified in early content. This would very likely be native.

**Comment by Consealer** [comment]
I have already provided reliable information.
Heavy Armor Kit
Required Level 30
Item level 25 and above.
Used by level 35 character on item of item level 26 errors: Target too low level. BUG.

**Comment by Aeradel** [comment]
[Only usable on items level 25 and above.](https://www.wowhead.com/wotlk/spell=10344/armor-32) is not the same as Only usable on item level 25 and above.

**Comment by Consealer** [comment]
Your notion doesn't prove i's not a bug.
You interpret the tooltip wrong. I trully believe it. I can't force you to see it. Or admit that you see it. I just want people to tell what they think. [Greywolf59](https://github.com/Greywolf59) supported my opinion. I hope more users will and in time developers will change theirs'.
