### ISSUE TITLE
Trash mimiron - Mines

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#2389]
The problem is that mines on the way to mimiron very little damage (10k). Mines have to kill.

https://www.wowhead.com/wotlk/spell=64873/sapper-explosion
https://www.wowhead.com/wotlk/npc=34193/clockwork-sapper
![image](https://github.com/user-attachments/assets/f48084c5-2f35-48c6-aeea-1674a41c26db)
https://youtu.be/YkcQ6-G7C9o?t=93

**Comment by Piootrek** [comment]
It does correct damage 
![image](https://github.com/user-attachments/assets/0134a30d-d020-4eaf-89f7-b8fc021b2f89)
