### ISSUE TITLE
Pets repositioning

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#239]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Pets in wow should try to and attempt to hit behind target if applicable whenever you queue the attack (auto attack) function.
currently in whitemane they keep infront of the target and often cause unecessary parries not to mention lowering of dps.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Manpower99** [comment]
> @Manpower99 What target and what pet?

Sapphiron, in the raid with in Harmony on PTR it happened an everytime i queued an attack it stayed in front of the boss

**Comment by UltraNix** [comment]
Hunter? Warlock? Or what class?

**Comment by Manpower99** [comment]
> Hunter? Warlock? Or what class?

unholy ghoul from me personally. but other pets are also likely

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/3152f72a-20c4-483a-a575-28ce505fde5b)
You can see my pet is behind the boss.

**Comment by Manpower99** [comment]
I will timestamp a recorded video as soon as i can

**Comment by Manpower99** [comment]
https://www.youtube.com/watch?v=U1asOBM7-vM
2:17:16 after a flight phase my pet i issued a Attack command which would normally reposition it to be behind the boss but it didn't. you can see other pets too having the same issue

**Comment by UltraNix** [comment]
Let me know if it's fixed.
