### ISSUE TITLE
[PTR] TOGC ascended 25m, champions demon hunter eye blast laser should have grace period and reduced damage

### ISSUE THREAD

**Issue by gforghieri** [gamefreedomgit/Frostmourne#2394]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

[PTR] TOGC ascended 25m, champions demon hunter eye blast laser should have grace period and reduced damage

Right now its dealing 20-25k every 1s, without grace period, one shotting most players. There is pretty much no way to avoid the first tick in the current implementation.

Frosthold tuning is significantly weaker.

Proof from frosthold: https://youtube.com/clip/Ugkx6tNHQ5Zk5QqnKSTOfpH1lH18r8Jiv3X-?si=a26VgOVEVKFVgHzb

**Comment by NickZedd** [comment]
There doesn't seem to be a grace period there. He takes damage after one second just like on whitemane.

Also I'd suggest that a better balancing is to put the damage to a number where any class can survive 2 hits, but not 3. So about 10k. It looks like you didn't even have to run from the beam on frosthold with how low the damage was.

**Comment by NickZedd** [comment]
On second thought I think about 13k is more reasonable, seeing as Divine sacrifice reduces the damage.

**Comment by crabcakeowo** [comment]
Eye blast laser is not doing ticks every 0.5s, it's doing ticks every 1s which looks to be the same as on frosthold. Damage is way higher here compared to frosthold. However from old videos eye blasts lasts for 8 seconds and does 8 ticks of damage, on whitemane it current only lasts for 7 seconds and does 7 ticks of damage. If damage is reduced to frosthold numbers, the mechanic is essentially non-existent, would be nice to have a good rebalancing in this case. 

Currently it does approximately 168k (24k ticks) (without damage reduction) damage over 7 seconds.

I would say rebalancing the damage to be reduced by at least 30% which is 112k (16k ticks) over 7 seconds or alternatively leave the damage untouched and let it be affected by shadow resistance. (which will mitigate almost the same amount when used with shadow aura mastery)

**Comment by gforghieri** [comment]
True its dealing damage every 1s, but there is no grace period, so it insta kills with 20-25k ticks.

This needs to be adjusted. There should be a grace period before it starts dealing damage and the damage should be lowered. I dont mind if its more than frosthold, but current state is just broken.

![image](https://github.com/user-attachments/assets/7a63fd2d-9cbb-4dbe-9cdd-2866cae36c76)
![image](https://github.com/user-attachments/assets/8fa2a696-6c2b-41f8-b7fe-22ea8c871dcf)
![image](https://github.com/user-attachments/assets/079ca565-6eab-4a99-9417-b299df892d79)
