### ISSUE TITLE
[PALADIN] Sacred Shield 50 % Crit Interaction with FoL

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#2395]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** sacred shield's proc should give 50 % crit chance to flash of light. Currently on my char I have 76 % crit with sacred proc yet somehow I manage 5-6 flash of lights not critting in succession. Not sure it's bugged, it's theoretically possible, but the probability of it happening 5 times in a row is: 0.24^5 = 0.0007962624. basically 0.

I couldn't even pinpoint to art of war proc or anything else, happened both with self cast, and on other friendly targets, with both instant AoW cast ones and normally 1.5 sec cast ones.

Maybe it's worth checking if the crit increase aura is applied in all cases?

**How to reproduce:** No idea

**How it should work:** the + 50 % crit chance should always be taken into account

**Database links:** https://www.wowhead.com/wotlk/spell=58597/sacred-shield

**Comment by NickZedd** [comment]
I don't quite know how how it's supposed to work or how you tested it, but are you sure the crit bonus is supposed to stay after the 500 damage has been absorbed? They seem to be tied to the same buff and the text reads "up to 6 seconds".

**Comment by Piootrek** [comment]
I've checked the code and 50% crit chance is correctly applied.
