### ISSUE TITLE
Gormok-the-impaler - impale - PTR

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#2396]
The "impale" ability does not work correctly.  In our case, the periodic damage of this ability is reduced due to armor and the tank receives very little damage (10 stack = 27k damage) periodic damage should ignore armor. Screenshot from the official server 2 stack =11k damage.

Whitemane
![image](https://github.com/user-attachments/assets/ac5dc565-d185-4ef4-9d54-4e58803762fd)
Official
![image](https://github.com/user-attachments/assets/6f6c158e-5cc3-406a-93b8-87a30a16540c)

https://www.wowhead.com/wotlk/npc=34796/gormok-the-impaler
https://www.wowhead.com/wotlk/spell=66331/impale

**Comment by Piootrek** [comment]
Fixed
