### ISSUE TITLE
ToGC - Gormok the Impaler - Snobold Vassal PTR

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#2397]
1)After killing a Magnataur, when the snobolds jump off its back, they become inactive even if damage is inflicted on them.
https://www.wowhead.com/wotlk/npc=34800/snobold-vassal
![image](https://github.com/user-attachments/assets/80a9a645-696b-47d3-bf27-daf40cf5c7be)

2) Snobold Vassal should be immune to any kind of control.
Snobold Vassal should be immune to AoE mechanics, but there are exception mechanics (Cleave, Improved Revenge)
Snobold Vassal should be immune to taunt (Only hard mode)
This doesn't work for us.

After the boss dies, I use different Aoe abilities including shouts and check the stun mechanics.
As for the rest of the control type of control, the information is 99%, at least I have never seen them applied to snobolds. Fear, by the way, also does not work, but I tested this in another video.
https://youtu.be/tanVV5lV63E?si=HUDz_0lIdp_CjbST

**Comment by Piootrek** [comment]
1. Fixed
2. Snobolds are already immune to CC spells. 

> Snobold Vassal should be immune to AoE mechanics, but there are exception mechanics (Cleave, Improved Revenge)

Do you have any proof for this?

**Comment by wowclassic1234** [comment]
Proof of spells that fall into the exception category?

**Comment by wowclassic1234** [comment]
> 1. Исправлено
> 2. Сноболды уже невосприимчивы к заклинаниям CC.
> 
> > Сноболд Вассал должен быть невосприимчив к механике AoE, но есть исключения (Рассечение, Улучшенная месть)
> 
> У вас есть какие-либо доказательства этого?

What part of the message do you need evidence for?

**Comment by wowclassic1234** [comment]
Here you can clearly see how I use cleave and the snobold takes 7918 damage. Under the category of spells of exceptions, if I understand correctly, should fall abilities that require the presence of a target through which the ability is used. Spells like Whirlwind, which are used without a target, should not cause damage to the snobold.


![image](https://github.com/user-attachments/assets/e2077bf4-4124-477c-8141-5661caf00e14)

**Comment by wowclassic1234** [comment]
> 1. Исправлено
> 2. Сноболды уже невосприимчивы к заклинаниям CC.
> 
> > Сноболд Вассал должен быть невосприимчив к механике AoE, но есть исключения (Рассечение, Улучшенная месть)
> 
> У вас есть какие-либо доказательства этого?

Do you still need proof or is there enough information to correct?

**Comment by NickZedd** [comment]
Never heard of snobolds being immune to aoe. Where can I find this information?

**Comment by wowclassic1234** [comment]
> Никогда не слышал, чтобы сноболды были невосприимчивы к АОЕ. Где я могу найти эту информацию?

You can find this in any video from 2009. It's literally 1-2 minutes of searching.

**Comment by wowclassic1234** [comment]
https://youtu.be/zFHYXj3xhhw?t=82

**Comment by wowclassic1234** [comment]
In ideally, it is better for the developer to watch the video from wotlk classic on behalf of different classes in order to understand which mechanics should cause damage to the snobold and which should not. Because from my memory,  DK from the guild said that Pestilence does not update diseases on a snobold if it was applied through a boss. And if Pestilence was used through snobold, then the diseases were updated on Snobold and the boss.

**Comment by Riztazz** [comment]
fixed, will close once it's live
