### ISSUE TITLE
Gormok the Impaler attack speed TOGC PTR

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#2399]
The Gormok the Impaler boss has an incorrect attack speed. Our server has a modifier 2.0 installed, the attack speed should be 1.5 seconds under the action of a 1.8 debuff

![image](https://github.com/user-attachments/assets/5a0fef0d-84c8-43b2-9d36-ca03e8c55672)

**Comment by oomshroom** [comment]
Do you have any proof of this? In classic logs his attack speed is 1.8 with debuff
![image](https://github.com/user-attachments/assets/3313a11d-7560-4530-92b2-af443fa3df72)
frost fever uptime
![image](https://github.com/user-attachments/assets/fbe7cead-df94-4459-bc61-3591b808d145)
