### ISSUE TITLE
Runic Power out of Combat Decay

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#240]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Since it should decay at same rate as rage then rage should be looked at also.
but to summarize the runic power decay on frostmourne ptr rn is too fast.
While not in combat, rage is lost at an average rate of 1 rage per second (2 or 3 each 2.5sec tick
Runic Power is generated when using abilities that require runes, does not decay in combat and decays at the same rate rage does out of combat. Jul 22, 2008

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
