### ISSUE TITLE
[Quest] Ursal the Mauler – Enslaved Druids don't wake up

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2400]
When player kills [Usal the Mauler](https://www.wowhead.com/wotlk/npc=2039/ursal-the-mauler), usually during [the quest](https://www.wowhead.com/wotlk/quest=486/ursal-the-mauler), the [Enslaved Druids of the Talon](https://www.wowhead.com/wotlk/npc=2852/enslaved-druid-of-the-talon) should wake up, one of them do /say and they should transform into flight form and fly away.

https://www.wowhead.com/wotlk/npc=2852/enslaved-druid-of-the-talon#comments:id=2806789
https://www.wowhead.com/wotlk/npc=2852/enslaved-druid-of-the-talon#comments:id=152934
https://wotlk.evowow.com/?npc=2852

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
