### ISSUE TITLE
[Quest] Isle of Quel dailies – double dailies

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2402]
Some quests have two versions of them available every day. Same targets, just different name and ID. One version fo the quest is specific for building presence of Shattered Sun Offensive on the Isle during one of the patches. Second version is usual daily/daily that replaces the first version once the first version is completed once.
First one should be avialable, and when compelted,the second version should replace it, making first version inavailable.

[Discovering Your Roots](https://www.wowhead.com/wotlk/quest=11520/discovering-your-roots) + [Rediscovering Your Roots](https://www.wowhead.com/wotlk/quest=11521/rediscovering-your-roots)
[A Charitable Donation](https://www.wowhead.com/wotlk/quest=11545/a-charitable-donation) + [Your Continued Support](https://www.wowhead.com/wotlk/quest=11548/your-continued-support)
[Making Ready](https://www.wowhead.com/wotlk/quest=11535/making-ready) + [Don't Stop Now....](https://www.wowhead.com/wotlk/quest=11536/dont-stop-now)
[Intercept the Reinforcements](https://www.wowhead.com/wotlk/quest=11542/intercept-the-reinforcements) + [Keeping the Enemy at Bay](https://www.wowhead.com/wotlk/quest=11543/keeping-the-enemy-at-bay)
[Taking the Harbor](https://www.wowhead.com/wotlk/quest=11539/taking-the-harbor) + [Crush the Dawnblade](https://www.wowhead.com/wotlk/quest=11540/crush-the-dawnblade)
[Distraction at the Dead Scar](https://www.wowhead.com/wotlk/quest=11532/distraction-at-the-dead-scar) + [The Air Strikes Must Continue](https://www.wowhead.com/wotlk/quest=11533/the-air-strikes-must-continue)
[The Battle for the Sun's Reach Armory](https://www.wowhead.com/wotlk/quest=11538/the-battle-for-the-suns-reach-armory) + [The Battle Must Go On](https://www.wowhead.com/wotlk/quest=11537/the-battle-must-go-on)

https://www.wowhead.com/wotlk/quest=11539/taking-the-harbor#comments:id=260499
https://www.wowhead.com/forums/topic/2-4-daily-shattered-sun-offensive-quest-guide-17960#p155565
I have done all the quets available both on Isle and in Shattrath. Also the two in Hellfire, still all the quests are available.

UPDATE: I have found one quest that Carbonite does not show me as completed, however Carbonite might be wrong. The quest is [Erratic Behavior](https://www.wowhead.com/wotlk/quest=11524/erratic-behavior). It is possible that instead of this quest I am getting directly the second version, [Further Conversions](https://www.wowhead.com/wotlk/quest=11525/further-conversions), which might interfere with the daily system. But I really have no idea. Either the problem is this one quest not being done or it is general issue, after all, all the NPCs are spawned, all buildings taken, the patch is not "live" so I am inclined it is general issue and it simply problem of second versions not overwriting first versions, but joining up on them instead.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
