### ISSUE TITLE
Armor Kit error #2

### ISSUE THREAD

**Issue by Consealer** [gamefreedomgit/Frostmourne#2405]
Example 1
When I try to use Heavy Amor Kit on Light Leather Pants by 35 level character it errors: Target too low level. This is a bug.
Heavy Armor Kit
https://www.wowhead.com/wotlk/item=4265/heavy-armor-kit
Requires Level 20
Usable on items level 15+

Light Leather Pants
https://www.wowhead.com/wotlk/item=7282/light-leather-pants
Item Level 19
Requires Level 14

Example 2
When I try to use Thick Amor Kit on Dreamsinger Legguards by 35 level character it errors: Target too low level. This is a bug.
Thick Amor Kit
https://www.wowhead.com/wotlk/spell=10487/thick-armor-kit
Requires Level 30
Usable on items level 25+

Dreamsinger Legguards
https://www.wowhead.com/wotlk/item=13010/dreamsinger-legguards
Item Level 26
Requires Level 21

How it should work:
Armor kits should be able to be used by players of level stated by "Requires Level" on items with minimum item level stated by "usable on items level".
The player level requred for the reinforced item to be equipped is irrelevant in this matter.

On Whitemane Cataclysm realm Maelstrom this works fine. On every WotlK server I have ever played it worked fine. Only here is this bug.
This is screen from my 24 twink on Whitemane Maelstrom Realm:
![Heavy](https://github.com/user-attachments/assets/c45d4bc9-66b3-464a-bc9b-2bba4f15c51f)

I am opening this issue by advise of GM Trombone. He told me to find a classic WotlK twink player stream and use it as an argument.
Video from the relevant moment: https://youtu.be/OBGVExogqUA?t=440
![Armor](https://github.com/user-attachments/assets/901d28fb-0343-4e3a-a528-bea51a4be254)
Darkweave Breeches are reinforced with +24 Heavy Armor Kit.

Darkweave Breeches
https://www.wowhead.com/wotlk/item=12987/darkweave-breeches
Item Level 22
Requires Level 17

The twink is level 19. So he did not reinforce the legs himself. Some higher(20+) character did it and traded them since they are BoE.
The legs' item level is 22, which is higher than minimum 15 that the kit requires

You might say "Darkweave Breeches Item level is 22 (20+) and Light Leather Pants is only 19 so heavy Armor Kit (Requires Level 20) shouldn't work on them."
Then I will say "Required Level reffers to required character level of kit's user, not reinforced item's Item Level. This is why twinks 19 have to trade it from higher levels on BoE items and have to use Medium Armor Kit on BoP items."
Then you will ignore it, give no argument and deny this issue again. Or finally you will understand and admit it's a bug.

**Comment by Riztazz** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/2388#issuecomment-2483115829

Like Piootrek already mentioned, this is not a server bug but a client bug in wotlk client.
When you use the kit on an item, a spell is casted normally, this is not happening here. Client displays an error and that's it, does not send any information to a server.
That means client itself is completely contradicting what you're saying and in this case we trust the client.
It works on cata because it's a different client from WOTLK, who knows what has been changed in between

**Comment by Riztazz** [comment]
On top of that, we have no way to fix bugs like that for vanilla client, maybe the whitemane client could be fixed in the future, talk to radeghost about that :)

**Comment by Consealer** [comment]
Ok. I understand. Client is bad. I will try to contact radeghost about it.
Thank you for your time. Sorry for problems.
