### ISSUE TITLE
Stachel of exotic mysteries

### ISSUE THREAD

**Issue by Amine-x-x** [gamefreedomgit/Frostmourne#2406]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
If you open rdf frame and the reward is there, then you queue and finish the run you get it no problem.
But , if someone of your group decide to leave in middle of run or you kick him and requeue, you may get a new queue of continuation that doesn't give you the reward.
**How to reproduce:**
Join RDF with a promised reward, kick someone /ask to leave and queue again to fill the same run , and you may not receive reward.

**How it should work:**
Promised reward must be received and not cancelled due to unexpected leavers and updating your queue of fill to a non-rewarding one.

**Database links:**

**Comment by Piootrek** [comment]
I've checked and tested the code, and it's not the case. Reward isn't overridden after player rejoins the queue.
