### ISSUE TITLE
[HUNTER] Deterrence Deflecting AoE Hits

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#2409]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Deterrence currently deflects AoE hits like Consecration

**How to reproduce:** Walk into consecrated area with deterrence active

**How it should work:** AoE spells should not be affected by deterrence

**Database links:** https://www.wowhead.com/wotlk/spell=19263/deterrence#comments

![image](https://github.com/user-attachments/assets/593513b2-0a0d-49b0-8df6-ba373d8b45fe)

**Comment by oneadanut** [comment]
@Piootrek this fix affected the Vortex ability from Twin Valkyrs in TOC, deterrence should deflect Vortex.

![image](https://github.com/user-attachments/assets/9025d14c-7157-4fc6-9053-73b2898be2f8)
