### ISSUE TITLE
Pets move too slowly

### ISSUE THREAD

**Issue by Savageferret** [gamefreedomgit/Frostmourne#241]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Hunter pets move too slow while in combat. It's very noticeable when comparing /petfollow (decent speed) & /petattack (slow) on a mob

**Comment by Inukk** [comment]
feels normal to me, did you check if you have cower on autocast?

**Comment by Savageferret** [comment]
No cower, but I can't reproduce the slowness. I swear I've had it be x2 slower on /petattack, but maybe it was cower that one time
