### ISSUE TITLE
[ToGC] 25m compiled bugs for first 3 bosses

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#2410]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

Bugs found during our PTR raid on Sunday the 17th. Tested and confirmed some more thoroughly after the raid as well.

### General

Boss frames are not working on any encounter.

10 minute+ cooldowns are not resetting after wipes

### Beasts

Players with snobolds on them can’t be targeted by most spells.
Some examples: Most heals seem to work, but lay on hands does not. Cooldowns such as paladin hands don’t work, and probably many more that I didn’t test. Tricks of the trade does work for some reason, but misdirection does not. Also, even battle shout cannot affect a target who has a snobold on them. This probably applies to more buffs as well.

Icehowl’s Ice Breath is always cast on the tank. It should be cast on a random raid member. 

Hunter Tranquilizing Shot should dispel Icehowl’s enrage. Unsure if this is intended for Asc.

### Jarraxus

Nether Portal does not trigger hunter explosive trap.

### Faction Champions

Enemy champions don’t switch targets often enough. They should reset their threat and pick a new target every few seconds. Based on classic videos, it seems that everyone usually has over a million threat on the champions, and the champion’s target gets much more while they are being followed.
https://youtu.be/XfU5pRzkm9Y?t=50

Hunter champ’s Bestial Wrath doesn’t make his pet immune to CCs.

Enemy pets should be tauntable as per guide. https://www.icy-veins.com/wotlk-classic/faction-champions-raid-guide mentions pets being tauntable.

If intended to work like pvp encounters, Hand of Reckoning should be dealing dmg despite not aggroing. 

Warrior champion’s Bladestorm does very little dmg (1k per hit). All other AoE spells I’ve seen do about 5k per tick.

**Comment by Riztazz** [comment]
Faction champions issue fixed by @Piootrek

**Comment by Riztazz** [comment]
Fixed beasts issues, they're on PTR already

**Comment by Riztazz** [comment]
I'm checking vids and blizzard never sent any boss frames in TOTC

**Comment by Riztazz** [comment]
Pets are taunt immune on ascended mode only
