### ISSUE TITLE
Shamans do not auto learn 2h weapon skills

### ISSUE THREAD

**Issue by Vaxsysl** [gamefreedomgit/Frostmourne#2411]
**Description:**
You have made it possible for players to auto learn their class spells as they level up. You also made players to have their weapon skills maxed out for most of the time. And you also made it possible for our characters to auto learn how to use all weapons.

Shamans at, are not learning all weapon skills. I am missing both of my two-handed weapon skills that are available to Shaman class, axes and maces. 
![WoWScrnShot_112224_024307](https://github.com/user-attachments/assets/abdcf716-4377-468e-a323-542dc30205be)
![WoWScrnShot_112224_025633](https://github.com/user-attachments/assets/ebb96832-90e9-45ac-971e-f44e266c2b04)

**How to reproduce:**
Login and see.

**How it should work:**
We should auto learn this per your custom content.

**Database links:**
https://www.wowhead.com/wotlk/skill=160/two-handed-maces
https://www.wowhead.com/wotlk/spell=197/two-handed-axes

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
