### ISSUE TITLE
[Toc] Unable to zone while encounter in progress

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#2413]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

Tested on PTR, happens consistently. Seems this is happening when leader talks to npc to start the encounter but does not pull boss.
If players are outside they will receive "Unable to zone while encounter in progress" only when everyone goes outside does this error get fixed and players can run in.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
