### ISSUE TITLE
[TOC] Floor bug

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#2414]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

The breakable floor part of the TOC arena is pretty bugged, which I assume is causing the following issues:
-Mages can't blink
-Army of the dead doesnt spawn while casting it pre fight (maybe they fall through floor?)
-Snobolds falling under the floor
-Summoning stone can't be used on the breakable floor, just at the very entrance

Observed on mimiron playground live(25nm), some players mentioned this was different on ptr

**Comment by broizter** [comment]
It also breaks hunter traps. They fall through the floor

**Comment by Riztazz** [comment]
Is this still happening?

**Comment by broizter** [comment]
> Is this still happening?

No, you can close this.
