### ISSUE TITLE
[ToGC] anub arak stuck on wrong difficulty

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#2418]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
After logging out and reusing the same 25m HC ID, Anub is on regular heroic even though it was originally set to ascended difficulty and the NPC to change it is not reachable.

Also, the difficulty of Anub can't be changed after you select it the first time so it's probably a good idea to add an NPC below.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
