### ISSUE TITLE
Dupe -  Death Knight Understudy in Naxx 

### ISSUE THREAD

**Issue by Xonder2** [gamefreedomgit/Frostmourne#242]
![Screenshot 2024-03-02 122824](https://github.com/gamefreedomgit/Frostmourne/assets/38938345/283dc72f-4915-4d45-8149-e4fb58b13aaa)

**Description:**
Naxx 25 - Instructor Razuvious  
after the pool and eveid, the mobs become duble.

**Comment by Afgann** [comment]
fixed
