### ISSUE TITLE
[Quest] [12630] [kickin' Nass and takin' Manes]

### ISSUE THREAD

**Issue by GM-Nightmare** [gamefreedomgit/Frostmourne#2420]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Nass after killing a target and kicking him is running away and is not retrievable unless you abandon and take quest again

**How to reproduce:**

**How it should work:**
nas should stay with you after gathering from a dead npc

**Database links:**
https://www.wowhead.com/wotlk/quest=12630/kickin-nass-and-takin-manes

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
