### ISSUE TITLE
Quest : the storm king's vengeance

### ISSUE THREAD

**Issue by Amine-x-x** [gamefreedomgit/Frostmourne#2421]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The quest asks you to ride Gymer and kill the scourage army minions, and the npc you ride has ability called "Gymer grab", which grabs one of the minions "vargul" and then you use "gymer throw " to throw him and he explode doing massive AOE damage, 
well , the "Gymer grab" doesn't work , it doesn't even grab a signle add, and since the grab doesn't work , the throw won't work too since they are linked together.
Also using Gymer's rage which knocks back the enemies around you far away , will cause them to reset and evade , specially if you using it against one of the required elite bosses like "algar the chosen", he get knocked far away and reset/evade.
**How to reproduce:**
get the quest and ride gymer then try to use "Gymer grab" at a "vargul" it won't grab any of them , even if you have only x1 near you it won't grab him.

**How it should work:**
Should grab the add then you use "Gymer throw" which will throw the add and explode it on the minnions around you.

**Database links:**
https://www.wowhead.com/wotlk/quest=12919/the-storm-kings-vengeance

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
