### ISSUE TITLE
Swapping a 1hand + X with a 2hand weapon when inventory is full deletes X

### ISSUE THREAD

**Issue by Wosser** [gamefreedomgit/Frostmourne#2422]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When you have a 1hand wepon and an offhand equipped, your inventory is full and you try to equip a 2hand weapon, the 1hand wepon gets the inventory place of the 2hand wepon and the offhand is deleted.

**How to reproduce:**
^

**How it should work:**
Trying to equip a 2hand wepon in such case should just trigger an "inventory is full" error and no gear should be swapped.

**Database links:**

**Comment by Riztazz** [comment]
That's exactly what is happening when i try to do as you describe.
"These items can't be swapped" to be precise
