### ISSUE TITLE
Chickenmount

### ISSUE THREAD

**Issue by MINIGOODWIN** [gamefreedomgit/Frostmourne#2423]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I bought a chicken mount through your webpage. It says its account wide, but I cant see it on my other characters, but the one I bought it to.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Piootrek** [comment]
It works for me. Are you sure you have enough riding skill for this mount on the other characters?

**Comment by MINIGOODWIN** [comment]
No, I cant. Why?

**Comment by Piootrek** [comment]
Because it works for me and I cannot reproduce.

**Comment by MINIGOODWIN** [comment]
But it doesnt work for me, so we have to find a solution. 

I dont know what you mean by reproduce?

**Comment by Furiianda** [comment]
> But it doesnt work for me, so we have to find a solution.
> 
> I dont know what you mean by reproduce?

"Reproduce" means the developer needs to be able to find the same issue you're experiencing, and experience it themselves in order to narrow down the cause of the issue. 
You can use free software OBS Studio to record videos.

**Comment by MINIGOODWIN** [comment]
Thank you  for explaining.

In my opinion, there’s no reason to film and do all this stuff. I go to my mount option, and see 6 dinosaurs and 2 pets from AQ40. There’s no chicken mount. No need to waste time on unnecessary filming again in my opinion.

it doesn’t work, and it needs to be fixed.

**Comment by MINIGOODWIN** [comment]
Take a video of what? Me pressing my mouse 4 times to prove, that what I’m saying is correct?

Long story short, I bought an accountbound mount through the webpage for an amount of coins, and the mount is not showing on other characters than my lvl 80, even though, I have learned at the skill artisan riding on the other character.

It’s the same fraction, the only thing different is, my lvl 80 is a priest and my other is mage.
