### ISSUE TITLE
Dungeon - Utgard Pinnacle - Cannot rez after death on skadi

### ISSUE THREAD

**Issue by bigchipbag** [gamefreedomgit/Frostmourne#2424]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

![image](https://github.com/user-attachments/assets/78cb7c19-aeb3-431e-af68-9665e68137cf)

**Description:**
Cannot resurrect anyone at Eagle's Eye after skadi the ruthless boss fight. Says "Target cannot be resurrected"
Happens on Ascended and Regular Heroic

**How to reproduce:**
Try to resurrect someone dead after boss

**How it should work:**
You should be able to resurrect

**Database links:**
??? it just doesn't work

**Comment by bigchipbag** [comment]
Same issue as: https://github.com/gamefreedomgit/Frostmourne/issues/2343

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
