### ISSUE TITLE
[Trial of the Crusader] Bugs in TOGC10 Ascended

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2425]
**Description:**
**1. Icehowl** 
- Icehowl is doing his charge too fast, he basically charges instantly after massive crash and the stun gets removed after few sec. The stun should run out when he is jumping back to get momentum for his charge as you can see in this video:
https://youtu.be/dInHQ0ZZPx8?si=pTA__s8k4LEOi0y5&t=267
- Arctic Breath should stun the affected people. I was able to dps on my rogue while having the breath debuff.

**2. Jarraxus**
- Portal and Volcano health in TOGC10 Ascended have the same value as in TOGC10, which is too low in my opinion.
- Volcano doesn't spawn any adds in TOGC10 Ascended. It should spawn instantly 1 Infernal and then others at ~3 seconds deelay.

**3. Faction Champions**
- All champions don't change targets at all, they choose a target and follow them until killed or if player dies/uses immunity spells or threat dump spells. They should change target every ~5 seconds.
- None of the champions can be gripped, they should be.
- The Feral druid is not resetting his position after wipe, it seems he remains on the spot where he was last time before wipe, stealthed. Basically when we talked with npc to start the fight, Feral druid attacked us and of course pulling the other champions.
- Warrior's Bladestorm doesn't get removed when disarmed.
- Demon hunter's laser is doing 23k damage, basically oneshots the target. I don't know how Shadow Prison should work, but in my opinion, you shouldn't get any damage while stunned in this ability since it's not dispellable and champions shouldn't attack the Shadow Prisoned player.

**4. Anub'arak**
- We could get the boss in phase 2 (40%) without submerge even without bloodlust in TOGC10 Ascended. Health is too low?
- Ice spheres are hard to target, seems like they don't have nameplates and also can't be gripped.

_We couldn't start TOGC10 on normal even after we did TOC10 normal.
We shouldn't get durability loss in Mimiron's Playground._

**Comment by NickZedd** [comment]
The icehowl charge being fast is a frosthold thing. If works the same as in 25m it's the correct behaviour and it's still completely reliable to dodge it. It could be that some of these other things, like the bladestorm not being disarmable, are also from frosthold? Since that same thing is a custom buff that was applied to 2 mobs in ulduar.

**Comment by oneadanut** [comment]
The icehowl charge is happening also in Toc10 normal and it doesn't look custom, it looks bugged.

**Comment by oneadanut** [comment]
Also, Icehowl is changing his direction when taunted while stunned after charge.

**Comment by Piootrek** [comment]
> Icehowl is doing his charge too fast, he basically charges instantly after massive crash and the stun gets removed after few sec. The stun should run out when he is jumping back to get momentum for his charge as you can see in this video:

Fixed

> Arctic Breath should stun the affected people. I was able to dps on my rogue while having the breath debuff.

Stun works correctly for me

> Volcano doesn't spawn any adds in TOGC10 Ascended. It should spawn instantly 1 Infernal and then others at ~3 seconds delay.

Related to another issue, will be fixed soon.

> All champions don't change targets at all, they choose a target and follow them until killed or if player dies/uses immunity spells or threat dump spells. They should change target every ~5 seconds.

I've changed a bit threat recalculation function. Please recheck after update

> The Feral druid is not resetting his position after wipe, it seems he remains on the spot where he was last time before wipe, stealthed. Basically when we talked with npc to start the fight, Feral druid attacked us and of course pulling the other champions.

It's intended, he spawns in one of the predefined locations. Can't be body pulled

> Warrior's Bladestorm doesn't get removed when disarmed.

Fixed

> Demon hunter's laser is doing 23k damage, basically oneshots the target. I don't know how Shadow Prison should work, but in my opinion, you shouldn't get any damage while stunned in this ability since it's not dispellable and champions shouldn't attack the Shadow Prisoned player.

Champions won't target shadow prisoned player

> Ice spheres are hard to target, seems like they don't have nameplates and also can't be gripped.

It's blizzlike that they don't have nameplate

> Also, Icehowl is changing his direction when taunted while stunned after charge.

Works correctly for me. Probably was fixed by @Riztazz with his recent fixes.


All health issues need game design decision @RadeghostWM . Grip issues are related to another issue and will be fixed soon.

**Comment by oneadanut** [comment]
You are saying Feral druid can't be body pulled, but he body pull us. We didn't do anything after talking with npc and Feral druid attacked us, starting the encounter.

**Comment by Piootrek** [comment]
> You are saying Feral druid can't be body pulled, but he body pull us. We didn't do anything after talking with npc and Feral druid attacked us, starting the encounter.

https://github.com/user-attachments/assets/69d21217-8cbf-4e5e-968d-aa931ee19e36
