### ISSUE TITLE
[Trial of the crusader][anub] Hand of freedom on an Icepatch should give u immunity to slow

### ISSUE THREAD

**Issue by scrublama** [gamefreedomgit/Frostmourne#2426]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Hand of freedom on icepatch should give u immunity to slow from the ice slow effect

**How to reproduce:**
Shoot down an icepatch and stand on it and cast hand of freedom, watch it only gives immunity to slow for a second

**How it should work:**
Slow immunity the entire hand of freedom duration
https://youtu.be/lmub2VELsQg?si=HPryX9fQb2WQwaey&t=116
https://wowpedia.fandom.com/wiki/Anub%27arak_(Trial_of_the_Crusader_tactics)#:~:text=Hand%20of%20Freedom%20can%20be%20used%20to%20negate%20the%20slowing%20effect%20of%20the%20permafrost%20on%20the%20tank%20and%20allow%20easier%20positioning

**Database links:**

**Comment by Piootrek** [comment]
Can you make a video of this bug? Works correctly for me.

**Comment by scrublama** [comment]
> Can you make a video of this bug? Works correctly for me.

on 25m heroic it seems to work fine
Permafrost has different IDs for 10, 10hc, 25, 25hc

I found this happen in 10m heroic, with this spellId
https://wotlk.evowow.com/?spell=67856

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
