### ISSUE TITLE
.tele and commands bug

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#243]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
.tele was added in the changelog and applied but the command is not working

If you only type .tele it tells incorrect syntax
If you type for example .tele orgrimmar it tells "there is no such subcommand"
This implies there is access to .tele command but either the syntax is changed and not documented on this server or we don't have access to some part of the subcommand that makes the .tele basically useless

Speaking of documentation on commands.
Currently players don't have access to .commands and .help only lists a hardcoded and nonupdated text.
Therefore players don't even know what commands they have access to.
For example .spellqueue command was added and not reflected in .help, neither did .port which sends you to gm island.

Since .help is just a hardcoded text instead of the original command you can't even use .help (command name) to instruct you how to use the command and its subcommands.
On a regular server you could use .help tele to see if we have access to whatever subcommand its referring to.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
