### ISSUE TITLE
Consumables on Mimiron's playground

### ISSUE THREAD

**Issue by Tahtoh88** [gamefreedomgit/Frostmourne#2431]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Haven't tested it yet this week but, i remember having non wrath consumables especially flame caps get consumed while testing on Mimiron's Playground. I haven't found any posts from issue search that addressed this situation so im issuing it

**How to reproduce:**
Use a flame cap inside a mimiron's playground instance

**How it should work:**
Like the rest of the relevant consumables, flame caps shouldn't be consumed

**Database links:**
https://www.wowhead.com/wotlk/item=22788/flame-cap

**Comment by oneadanut** [comment]
Indeed, flame caps should not get consumed, while **leg enchants should get consumed.**

**Comment by Tahtoh88** [comment]
I've also noticed Saronite and Sappers get consumed

**Comment by Riztazz** [comment]
fixed, will close once it's live
