### ISSUE TITLE
[Togc] [Anub'arak] [expuse weakness stacks are going through regardless if hit or not]

### ISSUE THREAD

**Issue by GM-Nightmare** [gamefreedomgit/Frostmourne#2432]
Anub'arak` Nerubian Burrowers

Description:

Melee hits from Anub Adds should not give you the Stacks if they dont hit you for any reason, meanwhile over here even if you dodge, parry / Miss or block, you are geting the stacks up

How to reproduce:
 
Pull Anub > Wait for Adds to Spawn > Check it out

How it should work:

When the adds does not land a melee hit on the tank for any reason, they should not give you the stacks, cuz it doesnt count it as a Hit.

![image](https://github.com/user-attachments/assets/bd4f64e1-be79-4eb1-a30c-c1055e9a8d07)
https://www.youtube.com/watch?v=qosIcX6Jgus 
3:17 - 3:23

**Comment by scrublama** [comment]
who told you this? 
im not getting stacks in 10m hc when i dodge parry miss or fully block

**Comment by Piootrek** [comment]
I've checked and it works correctly. Stacks are not applied when damage is fully mitigated.

**Comment by scrublama** [comment]
> > s are not applied when damage is fully mitigated.
> 
> If the damage is completely absorbed or completely blocked, then the tank does not receive a stack? Did I understand you correctly, is this how it works on our server?

There was a game design decision before the launch that’s now live and this debuff now applies regardless of mitigation
