### ISSUE TITLE
Summoned Guardians inside TOGC

### ISSUE THREAD

**Issue by Tahtoh88** [gamefreedomgit/Frostmourne#2436]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Still haven't figured out how the bug occurs, but there were times where my summoned elementals as a shaman don't spawn when placing their totems, a dk couldn't summon any army ghoul when he was channeling, and warlock couldnt conjure healthstone altar and summoning stone. It got fixed after a wipe, then stopped working after another wipe.
This happened on the wooden platform during the first 3 bosses of TOGC

**How to reproduce:**
summon guardian npcs inside TOGC

**How it should work:**
for the guardians to be properly present

**Database links:**
https://www.wowhead.com/wotlk/spell=42650/army-of-the-dead
https://www.wowhead.com/wotlk/spell=2894/fire-elemental-totem
https://www.wowhead.com/wotlk/zone=4722/trial-of-the-crusader

**Comment by broizter** [comment]
There is a bug with the floor that is already being tracked at https://github.com/gamefreedomgit/Frostmourne/issues/2414
