### ISSUE TITLE
[Dungeon] [Quest] Improve Culling of Stratholme Skip

### ISSUE THREAD

**Issue by bigchipbag** [gamefreedomgit/Frostmourne#2439]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The skip for the CoS dungeon from Chromie should allow people to skip it regardless of dungeon status (complete or quest complete)

**How to reproduce:**
Join a random dungeon and try to skip

**How it should work:**
The skip should be available for anyone who completed the quest or for anyone who has completed the dungeon, or just available at all times. It's such a headache to wait over five minutes when trying to complete the random dungeon, and so many people just drop group when they get CoS anyways. 

Improving the skip will help server morale

**Database links:**

**Comment by Piootrek** [comment]
Fixed, I will close this once the fix comes live.

**Comment by bigchipbag** [comment]
> Fixed, I will close this once the fix comes live.

Unfortunately this needs to be looked at again. The skip is not functional in some cases, in fact there's no dialog options with Chromie at all:
![image](https://github.com/user-attachments/assets/b1178df5-bd8d-4677-81fd-01202780b699)

**Comment by Piootrek** [comment]
At what stage of the instance you were exactly?

**Comment by bigchipbag** [comment]
> At what stage of the instance you were exactly?

We just walked in and there was no option to skip. I was the first person to interact with Chromie. It happened twice.

**Comment by Piootrek** [comment]
Do you have maybe Dispelling Illusions quest in the quest log?

**Comment by bigchipbag** [comment]
Negative I have completed the quests months ago. Others in the party reported the same issue.
