### ISSUE TITLE
Emblem of Ascension Vendor

### ISSUE THREAD

**Issue by Tripalowksi** [gamefreedomgit/Frostmourne#2441]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Vendor in Dalaran just sells item back without getting Emblem of Ascension back. It worked just fine on 1st item but not on the 2nd one

**How to reproduce:**

**How it should work:**
Vendor should refund emblems back everytime

**Database links:**
![WoWScrnShot_112724_062720](https://github.com/user-attachments/assets/7bea111e-9e19-4a4e-9f97-7e073988c11c)
![WoWScrnShot_112724_062811](https://github.com/user-attachments/assets/31b4cbcb-dd76-46c0-8d5d-970fbb889661)
![WoWScrnShot_112724_062826](https://github.com/user-attachments/assets/c10891ac-ff70-436b-adae-c1b5c5172021)

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
