### ISSUE TITLE
Undercity Portals all bugged - intermittent

### ISSUE THREAD

**Issue by bigchipbag** [gamefreedomgit/Frostmourne#2445]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Taking a portal to undercity takes you to the dalaran inn. Happened to me and another guildmate with both Dalaran portal and Mage Portal

**How to reproduce:**
Take an undercity portal

**How it should work:**
Take you to undercity lmfao

**Database links:**

**Comment by bigchipbag** [comment]
![image](https://github.com/user-attachments/assets/af2bc211-a0bc-4a75-87e3-1de8ad5497f2)

**Comment by UltraNix** [comment]
#2455
