### ISSUE TITLE
The argent tournament grounds spirit healer missing.

### ISSUE THREAD

**Issue by KryndorX** [gamefreedomgit/Frostmourne#2446]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
This photo shows that there must be a spirit healer in the argent tounament grounds, which it doesn't exist there.
![image](https://github.com/user-attachments/assets/539f9376-92b8-4932-ad84-ddeba54e958d)

**How to reproduce:**
Spirit healer is not there, you can easily go to that location and check as a GM access user or a dead player.

**How it should work:**

**Database links:**
Click icecrown to confirm. : https://www.wowhead.com/wotlk/npc=6491/spirit-healer#map

**Comment by Riztazz** [comment]
fixed, will close once it's live
