### ISSUE TITLE
VOA - Koralon-the-flame-watcher + flame-warder

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#2447]
The koralon-the-flame-watcher boss and flamewarder is not working correctly.

Meteor fists ability damage should be dealt every time the boss swings, but the boss should not deal damage from an automatic attack. That is, the automatic attack should be replaced by meteor fists. 

On our meteor fists server are linked to an automatic attack, and if the boss does not hit, the meteor fists do not work.
Official server 
![image](https://github.com/user-attachments/assets/17b7610f-2bfe-4133-ad03-2dc87ec56ba8)

Boss
https://www.wowhead.com/wotlk/npc=35013/koralon-the-flame-watcher
https://www.wowhead.com/wotlk/spell=66725/meteor-fists
https://www.wowhead.com/wotlk/spell=66765/meteor-fists

Trash
https://www.wowhead.com/wotlk/npc=35143/flame-warder
https://www.wowhead.com/wotlk/spell=66808/meteor-fists
https://www.wowhead.com/wotlk/spell=66809/meteor-fists

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by oneadanut** [comment]
Also, he should do the fire patches on a random player, not only on tank.

**Comment by Piootrek** [comment]
> Also, he should do the fire patches (flaming cinder) on a random player, not only on tank.

Fixed too.

**Comment by Piootrek** [comment]
I pushed a possible fix for this issue, please let me know if it still happens after the server update.
Flame Warders fixed.
