### ISSUE TITLE
Undercity Elevator

### ISSUE THREAD

**Issue by Vaxsysl** [gamefreedomgit/Frostmourne#2451]
**Description:**
I cannot leave Undercity via any elevator. I get teleported back down. This is very recent, so this morning's patch probably glitched it.

https://youtu.be/qf5mHvOqZww

**How to reproduce:**
Hop on.

**How it should work:**
https://en.wikipedia.org/wiki/Elevator :)

**Comment by UltraNix** [comment]
#2455
