### ISSUE TITLE
alga key gives emblem of triump x5

### ISSUE THREAD

**Issue by scrublama** [gamefreedomgit/Frostmourne#2452]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
alga key gives emblem of triump x5

**How to reproduce:**
alga key quest gives emblem of triump x5

**How it should work:**
give coqnuest

**Database links:**

**Comment by Riztazz** [comment]
@RadeghostWM Should i restore conquests or leave triumphs?

**Comment by RadeghostWM** [comment]
Leave Triumph right now, that's the better way as we merged ToC/ToGC IDs.
