### ISSUE TITLE
TOGC 25M Ascended Mimiron's Playground floor bugged bosses/totems/pets/summoning stone falling under ground, no blink/no grip

### ISSUE THREAD

**Issue by gforghieri** [gamefreedomgit/Frostmourne#2453]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

pets undergournd
totems underground
summoning stone falling underground
champions not grippable
no blink
champions under ground, demon hunter flying very low, he starts his path from underground
traps falling underground
bosses fall underground

**Comment by NickZedd** [comment]
Gonna add some stuff I think is related but that's up to the devs to figure out:
Icehowl getting stuck mid-air after charging
Jaraxxus volcano shoots it's projectile straight up in the air and spawns no adds

**Comment by Piootrek** [comment]
> pets undergournd totems underground summoning stone falling underground champions not grippable no blink champions under ground, demon hunter flying very low, he starts his path from underground traps falling underground bosses fall underground

Did you test it on live server or ptr?

**Comment by crabcakeowo** [comment]
Most of the ground issues occured during live server on playground, ptr seemed to work fine for the most part regarding this issue.

**Comment by Piootrek** [comment]
When did you test it last time?

**Comment by gforghieri** [comment]
Can be closed, it was fixed.
