### ISSUE TITLE
[TBC] [Quest] [Dungeon] Imprisoned in the Citadel – credit not awarded

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2456]
The new issue with the quest [Imprisoned in the Citadel](https://www.wowhead.com/wotlk/quest=9524/imprisoned-in-the-citadel#comments) is that I was not awarded credit for completion of this quest after killing the Executioner. Quest undoable (Alliance).

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
