### ISSUE TITLE
[Dungeon] Culling of Stratholme Arthas pathing

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#246]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
After activating arthas during the undead gauntlet by the end of the dungeon, he kept resetting back to the beginning constantly. We managed to get him to the end of the dungeon by having all 5 players close to him.

https://youtu.be/9xiiOkcZRaI

**Comment by UltraNix** [comment]
Fixed.
