### ISSUE TITLE
Daily dungeon quest gives Emblem of Conquest

### ISSUE THREAD

**Issue by Gajoel14** [gamefreedomgit/Frostmourne#2463]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The daily dungeon quest still gives 1 conquest emblem rather than 1 triumph.

**How to reproduce:**
Take the quest and turn it in. 

**How it should work:**
Should give one Emblem of Triumph. 

**Database links:**

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by oneadanut** [comment]
He talks about Timear Forsees quests, not Proof of Demise

**Comment by Piootrek** [comment]
> He talks about Timear Forsees quests, not Proof of Demise

Fixed too
