### ISSUE TITLE
Kil Jaeden orbs doesn't work

### ISSUE THREAD

**Issue by Avian139** [gamefreedomgit/Frostmourne#2467]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
During the Kil Jaeden fight the first orb activated correctly but the second orb did not activate at all. This happened several times and each time in a wipe because the orb was inactive (instance ID: 4642)

**How it should work:**
Before the boss casts Darkness of a Thousand Souls, one orb should become active so the player can grab a blue drake and use a shield.

**Additionally** 
We spent a few hours on this raid. After several attempts when we were sure that there was a bug, we wrote a ticket and GM Darsha came. He watched our fight with KJ twice. He told us to wait, so we spent another hour waiting for an answer. In the end, no one helped us and we did not receive the loot. Many people needed ONLY quest items for legendary weapons. Please send us at least quest items. It was not our fault that we wasted a lot of time, lost ID and received nothing.

**Comment by Piootrek** [comment]
Same as here https://github.com/gamefreedomgit/Frostmourne/issues/1622 
It works correctly, your damage was just too low.
