### ISSUE TITLE
Can't enter Stormwind; teleported to hearth location

### ISSUE THREAD

**Issue by Furiianda** [gamefreedomgit/Frostmourne#2468]
**Description:**
Same as the recent bugs with Tirisfal and Icecrown, but this time it's Stormwind. As soon as you enter the city, either via portal or front gate, you get teleported away to wherever you set your hearth.

**How to reproduce:**
Go to Stormwind via portal or front gate entry.

**How it should work:**
Stormwind city should be enterable normally.

**Database links:**
N/A

**Comment by Furiianda** [comment]
This issue seemed to have resolved itself while I was writing the report! Very strange. However many other people reported the issue in WorldChat so it was not on my end. Very strange.

**Comment by UltraNix** [comment]
#2455
