### ISSUE TITLE
[NPC] Boneguard Commander – Huge follow length, missing abilities, combat bug

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2469]
[Boneguard Commanders](https://www.wowhead.com/wotlk/npc=34127/boneguard-commander#comments) follow their aggro target for a very long time. Followed me all the way back to Corp'Rethar where it killed me. I have dismouinted the steed since I thought ir is a combat bug, as all argent tournament mounts tend to stay in combat indefinitely. It also seems the Commander is not usign his abilities, I did not see him charge me or throw a lance on me even once.
1: Huge/Indefinity aggro follow area of Commander
2: Commander probably missing abilities
3: General issue with Tournament vehicles staying in combat (especially with practice targets/dummies)

**Comment by Greywolf59** [comment]
UPDATE: They do use Charge, no Shield-Breaker so far. They will stop following the player if the player stays on argent mount. So it seems player dismounting the vehicle while in combat with them might be the issue.

**Comment by Piootrek** [comment]
1. His aggro range is same as every other creature in open world. 
2. Fixed
3. Fixed

Changes will be live after server update.
