### ISSUE TITLE
[Quest] Weapons of Choice

### ISSUE THREAD

**Issue by Savageferret** [gamefreedomgit/Frostmourne#247]
https://www.wowhead.com/wotlk/quest=893/weapons-of-choice

The quest items Backstabber and Wand drop from the correct mobs, but the Razormane War Shield doesn't drop at all from Razormane Warfrenzy

**Comment by qqdbpp** [comment]
how long did you test this exactly? 
![image](https://github.com/gamefreedomgit/Frostmourne/assets/159703358/7bda2752-5f3c-4aa1-8a28-9745fce20daf)

**Comment by Savageferret** [comment]
Not at all, just guessed it was bugged

**Comment by Savageferret** [comment]
But really I killed 5 Warfrenzys without it dropping before I moved on. It should have a 100% drop rate like the rest of the mobs / every other quest in the game pre-northrend

**Comment by qqdbpp** [comment]
probably because its not a quest item per se, you can still get them as drops without being on the quest

**Comment by Savageferret** [comment]
Oh that'll do it
