### ISSUE TITLE
[Live toc] Anub orbs

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#2473]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Anub orbs are still damaged by sapper charge or bombs

**How to reproduce:**
Press sapper on anub

**How it should work:**
Anub orbs should not be damaged by super sapper charge, bombs, ground aoes

**Database links:**

**Comment by Riztazz** [comment]
fixed, will close once it's live

**Comment by scrublama** [comment]
> fixed, will close once it's live

This is still not fixed on togc10

**Comment by Riztazz** [comment]
Fix has been reverted, caused some issues. Ill fix this again on monday

**Comment by Riztazz** [comment]
fixed, will close once it's live
