### ISSUE TITLE
TOC 5 asc

### ISSUE THREAD

**Issue by KryndorX** [gamefreedomgit/Frostmourne#2474]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Once you clear the event (mount fight) , the bosses will disapear upon their dismount , instead of going to their position and you won't be able to do anything , not even respawn them or speak with npc.
If by any chance bosses goes into the next fight, they won't drop chest and you can't even progress , can't speak to the NPC "arelas brighstar"
**How to reproduce:**
Finish the mounts battle.

**How it should work:**
Bosses goes to their positions after the first trash clear so you fight them with no mounts.

**Database links:**

**Comment by WhitemaneChronus** [comment]
Seems to be a common issue, bosses disappear right away and cannot find them or reset it.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
