### ISSUE TITLE
[Live toc] Anub burrower

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#2475]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Sometimes when nerubian burrowers go underground, they can emerge before the proper time - they are untargettable but can kill people. When proper time to reemerge happens they become targettable again
![WoWScrnShot_112924_232014](https://github.com/user-attachments/assets/4aa13974-1d61-4782-8e22-55de1664442d)

**How to reproduce:**
Unknown, this is the first time this happened

**How it should work:**
Nerubian burrowers should stay submerged until it is time for them to re-emerge, at which time they should be targettable.

**Database links:**

**Comment by Riztazz** [comment]
Pushed possible fix as i couldn't reproduce this locally
