### ISSUE TITLE
Onyxia25 bugs

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#2476]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
1. Onyxia 25 drops conquest emblems, it should drop triumph

2. Two onyxia lair guards are spawning, it should only be 1, proof vid below
https://youtu.be/Tay9I_RHPHg?si=53zoR1bdqoFs7f-J&t=135

Note: some onyxia wiki links claims spell summon guardian to be 2 on 25man, the video above from classic wotlk turns out to be 1, guess its up to management which route to go

**Comment by Riztazz** [comment]
Emblems fixed by @Afgann 
@RadeghostWM chose 1, so we will go with 1

**Comment by Riztazz** [comment]
fixed, will close once it's live
