### ISSUE TITLE
TOGC - Anub'arak

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#2477]
1) Damage from the leeching ability-swarm should ignore any talents and damage reduction abilities. Damage should only be reduced by resistance. On our server, damage is reduced from all % modifiers.
18640+4660=23300(30% HP)
![image](https://github.com/user-attachments/assets/139ecb0d-29ef-4020-b4ed-3c5f70ef1cc5)

2) Debuff Acid-drenched-mandibles should be applied to players with each attack, regardless of whether it was successful or not. The debuff overlay Should ignore dodge, parry, miss, block, absorb. On our server, the overlay occurs only when the player takes damage. 

Промах(miss)
![image](https://github.com/user-attachments/assets/7b21672e-903f-4394-9bb5-ad2fdff0dc45)

3) Swarm-scarab should be immune to the taunt effect, only in heroic mode.

![image](https://github.com/user-attachments/assets/5eeeda09-232d-46b4-94e2-6683910902ef)

https://www.wowhead.com/wotlk/npc=34605/swarm-scarab
https://www.wowhead.com/wotlk/npc=34564/anubarak
https://www.wowhead.com/wotlk/spell=66118/leeching-swarm
https://www.wowhead.com/wotlk/spell=65775/acid-drenched-mandibles

**Comment by wowclassic1234** [comment]
4) The boss has an attack speed of 2.0 set on our server, it should be 1.5 seconds
![image](https://github.com/user-attachments/assets/6fe207d1-7e3f-43d8-8b8b-570078682419)
![image](https://github.com/user-attachments/assets/0aab2629-6c78-4c6b-8166-662c60ebd477)

**Comment by Gescht** [comment]
> 1. Damage from the leeching ability-swarm should ignore any talents and damage reduction abilities. Damage should only be reduced by resistance. On our server, damage is reduced from all % modifiers.
>        18640+4660=23300(30% HP)
>        ![image](https://private-user-images.githubusercontent.com/173220680/391194567-139ecb0d-29ef-4020-b4ed-3c5f70ef1cc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNjI4OTgsIm5iZiI6MTczMzA2MjU5OCwicGF0aCI6Ii8xNzMyMjA2ODAvMzkxMTk0NTY3LTEzOWVjYjBkLTI5ZWYtNDAyMC1iNGVkLTNjNWY3MGVmMWNjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxNDE2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMWVhOGY1OTgzNTA2Y2NkYzQ1ZjQ4MzZkOTNjZjI4ODJlNzZlNWU0NDY0MjJhMDMxODE0NWY2NDYyMWE1OTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bhi9nLfweDd67gpx5meiDRsOaEdDW-J6X5gD-vjQoS4)

Can you share proof for this?

**Comment by NickZedd** [comment]
Though I think all of these changes would be good, the evidence you've posted is pretty confusing and leaves some room for interpretation. For example, I can't see what the proof is supposed to be for the scarabs being untauntable.

I can't find any mention of them being untauntable, but I also can't find any video of someone trying to taunt them (perhaps because they can't?), so I'm not sure so far.

**Comment by NickZedd** [comment]
Never mind it was just me not knowing what невосприимчивость means I guess. It all seems to check out at first glance, but I would still check videos and warcraftlogs before making big changes.

**Comment by Wowclassic2390** [comment]
> > 1. Damage from the leeching ability-swarm should ignore any talents and damage reduction abilities. Damage should only be reduced by resistance. On our server, damage is reduced from all % modifiers.
> >    18640+4660=23300(30% HP)
> >    ![image](https://private-user-images.githubusercontent.com/173220680/391194567-139ecb0d-29ef-4020-b4ed-3c5f70ef1cc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNjI4OTgsIm5iZiI6MTczMzA2MjU5OCwicGF0aCI6Ii8xNzMyMjA2ODAvMzkxMTk0NTY3LTEzOWVjYjBkLTI5ZWYtNDAyMC1iNGVkLTNjNWY3MGVmMWNjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxNDE2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMWVhOGY1OTgzNTA2Y2NkYzQ1ZjQ4MzZkOTNjZjI4ODJlNzZlNWU0NDY0MjJhMDMxODE0NWY2NDYyMWE1OTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bhi9nLfweDd67gpx5meiDRsOaEdDW-J6X5gD-vjQoS4)
> 
> Can you share proof for this?

the evidence in the photo, the tank takes full damage equal to 30% of its hp from the maximum health reserve, the boss's ability ignores the warrior defensive stance -10%, the talent improved defensive stance -6% and -3% buff dc priest/ppal

**Comment by Wowclassic2390** [comment]
> Never mind it was just me not knowing what невосприимчивость means I guess. It all seems to check out at first glance, but I would still check videos and warcraftlogs before making big changes.

There is no need for this, all the screenshots are from the official wotlk classic server, I have the entire gameplay completely recorded on video and all the evidence is reliable. on each screenshot, everything is clearly visible, if you have problems understanding the language that the addons display, use the translator.

**Comment by Wowclassic2390** [comment]
> > 3. Swarm-scarab should be immune to the taunt effect, only in heroic mode.
> > 
> > ![image](https://private-user-images.githubusercontent.com/173220680/391195297-5eeeda09-232d-46b4-94e2-6683910902ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwOTYwNTAsIm5iZiI6MTczMzA5NTc1MCwicGF0aCI6Ii8xNzMyMjA2ODAvMzkxMTk1Mjk3LTVlZWVkYTA5LTIzMmQtNDZiNC05NGUyLTY2ODM5MTA5MDJlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQyMzI5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YWYxNjBkYzA3ZGZiYjQxZWFjNzEyYTc5NDYwYmJhOTc5ZTZkNmYyM2Q0ZDllNmIzMmU2ZTI2YzI2MjRlZmY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wxplCaSrORhaMkgQlqDpwHua74Q4z7WH-eMfqqn4VHs)
> 
> On this screenshot the scarab is immune when it is enraged. It could be linked to the enrage and not linked to the heroic difficulty based of the ressources provided.

2:06 imun
https://youtu.be/nlSgocbsA8w?si=KHwvrtx3B1JOdvqx

**Comment by crabcakeowo** [comment]
Well the real question is what is the general design philosophy of the bosses for this server? Is it supposed to be like wotlk classic blizzlike or is it supposed to be like Frosthold? At some point, some of the bug reports don't make any more sense to me because it's now just a mixture of the two.

**Comment by wowclassic1234** [comment]
> Well the real question is what is the general design philosophy of the bosses for this server? Is it supposed to be like wotlk classic blizzlike or is it supposed to be like Frosthold? At some point, some of the bug reports don't make any more sense to me because it's now just a mixture of the two.

And who said that it looks like wotlk classic?  do you think that all the errors described here differ from the original wotlk 2009? Show at least counter evidence that this should not be the case.

**Comment by wowclassic1234** [comment]
> > 3. Swarm-scarab should be immune to the taunt effect, only in heroic mode.
> > 
> > ![image](https://private-user-images.githubusercontent.com/173220680/391195297-5eeeda09-232d-46b4-94e2-6683910902ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwOTYwNTAsIm5iZiI6MTczMzA5NTc1MCwicGF0aCI6Ii8xNzMyMjA2ODAvMzkxMTk1Mjk3LTVlZWVkYTA5LTIzMmQtNDZiNC05NGUyLTY2ODM5MTA5MDJlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQyMzI5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YWYxNjBkYzA3ZGZiYjQxZWFjNzEyYTc5NDYwYmJhOTc5ZTZkNmYyM2Q0ZDllNmIzMmU2ZTI2YzI2MjRlZmY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wxplCaSrORhaMkgQlqDpwHua74Q4z7WH-eMfqqn4VHs)
> 
> On this screenshot the scarab is immune when it is enraged. It could be linked to the enrage and not linked to the heroic difficulty based of the ressources provided.

2009
2:15
https://youtu.be/UdWQEea_lCk?t=135

**Comment by wowclassic1234** [comment]
> All reported issues are fixed. I will close this issue once the fix comes live.

Please look at this topic, it has an average priority assigned to it but the problem is of a critical  using a bug.
https://github.com/gamefreedomgit/Frostmourne/issues/2513
