### ISSUE TITLE
Onyxia's head

### ISSUE THREAD

**Issue by KryndorX** [gamefreedomgit/Frostmourne#2478]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
If the leader is the oposite faction (Horde for exemple) and the winner of the head is oposite faction (Alliance for exemple) , he can take the head and the quest but it asks him to go orgrimmar , but since he alliance, he can't return it.

**How to reproduce:**

**How it should work:**
Head quest should be usable to both factions since it is cross faction realm.

**Database links:**

**Comment by MichaelV114** [comment]
Same issue, got alliance one while being undead

**Comment by Riztazz** [comment]
fixed, will close once it's live

**Comment by malamrcha** [comment]
still not work

**Comment by Riztazz** [comment]
"will close once it's live"

**Comment by malamrcha** [comment]
when the fix will be online ?

**Comment by Riztazz** [comment]
You should be converted by now, if not, drop the quest and relog and it should convert
