### ISSUE TITLE
Spellsteal is causing a spell_cast_success event both for casting the spell and receiving the stolen buff - breaking DBM

### ISSUE THREAD

**Issue by broizter** [gamefreedomgit/Frostmourne#2479]
There is a bug (I think) that whenever a mage spellsteals a buff it creates two spell_cast_success events. One for the spellsteal cast, and one for receiving the stolen buff.

```lua
11/30 00:05:05.204  SPELL_CAST_SUCCESS,0x0000000000008E29,"Zinxd",0x511,0xF1300087DC1F7FC7,"Lord Jaraxxus",0x10a48,30449,"Spellsteal",0x40
11/30 00:05:05.204  SPELL_CAST_SUCCESS,0x0000000000008E29,"Zinxd",0x511,0x0000000000000000,nil,0x80000000,67106,"Nether Power",0x20
```

It's causing these lines in DBM to constantly trigger whenever mages start spellstealing the Nether Power buff on Lord Jaraxxus.
```lua
elseif args:IsSpellID(66228, 67107, 67106, 67108) then	-- Nether Power
		timerNetherPowerCD:Start()
                specWarnNetherPower:Show(args.sourceName)
		specWarnNetherPower:Play("dispelboss")
```

The reason I say that this is a bug is because this is how all DBM's (including classic and "retail") handles this ability. Its also exact same code I used on Sindragosa a few years back, where it worked fine. It would cause the timer to restart and alerts to trigger constantly on all of them if spellstealing caused a spell_cast_success event with the Nether Power spellid. It should only trigger when Lord Jaraxxus buffs himself with Nether Power.

Here's a link to the official DBM for "proof": https://github.com/DeadlyBossMods/DBM-WotLK/blob/a7d96602140bff22ce692e04cb5987b5cf8b622d/DBM-Raids-WoTLK/Coliseum/Jaraxxus.lua#L86

I can't think of any other way to prove that its currently not working as intended. It's not something that's very easy to look up

**Comment by broizter** [comment]
I have implemented a workaround in my DBM but might be worth looking into anyway.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
