### ISSUE TITLE
Naxx10 Ascended Tier Tokens loot table

### ISSUE THREAD

**Issue by wotlkenjoyer** [gamefreedomgit/Frostmourne#248]
We did naxx10 ascended multiple times,  but we have never seen any 213 ilvl  gear token, it only drops 10man tokens. 

So basically we still doomed to do 25mans in guild since 25man tier gear is not obtainable in 10man ascended.

Idk if its intended

**Comment by NNassib336** [comment]
Not sure if things changed, but our group got 1 token on our run a week and a half ago. Seems to be a low drop rate

**Comment by NNassib336** [comment]
We got 2 or 3 tokens in our 10m run today, so it's definitely part of the loot table

**Comment by wotlkenjoyer** [comment]
> We got 2 or 3 tokens in our 10m run today, so it's definitely part of the loot table

thank you so much,  so we just super unlucky
