### ISSUE TITLE
[Onyxia] Couple of bugs

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2485]
**Description:**
1. Boss shouldn't be immune to taunt.
2. Boss shouldn't instantly fly away in phase 2 when he reaches the entrance. He should have few seconds until he takes off.
3. Breath side radius damage is larger than visual.
4. Boss should reset when dragged out of the room.

**Comment by oneadanut** [comment]
Today I was in a pug for Onyxia25 and boss entered in phase 3 at 45%. It should go in phase 3 at 40%.

**Comment by Piootrek** [comment]
> Breath side radius damage is larger than visual.

Raidus looks good for me. Other bugs are fixed, will be live after server update.
