### ISSUE TITLE
Quest : Scavenging Deathknell

### ISSUE THREAD

**Issue by KryndorX** [gamefreedomgit/Frostmourne#2487]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The quest asks you to loot some boxes, but here is the problem if you have the event buff "PX-238 Winter Wondervolt" and you try to loot the boxes, it will say "you can't do that while you are immune"
__Edit : that buff makes you unable to loot any item not only quest items , even if you try to loot a chest , you won't be able__

**How to reproduce:**
Walk in the device located in durotar near "wonderform operator" that turns you into gnome and you will gain a buff called "PX-238 Winter Wondervolt"

**How it should work:**
that buff only turns you into a gnome with winter clothing its not suppose to have anything related to disable any quests.

**Database links:**

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
