### ISSUE TITLE
mobs freeze and do not attack 

### ISSUE THREAD

**Issue by Djuni1993** [gamefreedomgit/Frostmourne#249]
Mobs and "Pets" freeze and do not attack.
They start attacking and then they freeze again and fail my Quest =  [Escape from the Catacombs]

![image](https://github.com/gamefreedomgit/Frostmourne/assets/93435062/cce58d5a-a97f-4445-931b-f0ebd3463b03)

**Comment by Djuni1993** [comment]
https://github.com/TrinityCore/TrinityCore/commit/274dede3dc89fa72ec1687d5ff454feba9849e47 - Check please

**Comment by Djuni1993** [comment]
The change affects an update operation in a targeted movement generator class. This portion of the code determines a new position if the target moves or when the target is reached but the owning object is not close enough to it.

The change made is as follows:

```
else
{
    if (_speedChanged)
        SetTargetLocation(owner, false);
    else if (_targetReached && !owner->IsWithinMeleeRange(TargetedMovementGeneratorBase::GetTarget()))
        SetTargetLocation(owner, true);
}
```

This alteration impacts the behavior of the targeted movement generator class. Now, if the target has moved or if the target has been reached but the owning object is not close enough to it (checked by the IsWithinMeleeRange() function), a new target location will be determined. This change enhances the behavior of the previous code by providing a more accurate determination of the target.

**Comment by Afgann** [comment]
fixed
