### ISSUE TITLE
Onyxia 10 Adds

### ISSUE THREAD

**Issue by query-wow** [gamefreedomgit/Frostmourne#2491]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Onyxia 10 hatchling are spawning all at the same time, which means you'll get 40 adds at once instead of spaced out
**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Riztazz** [comment]
Fixed, will close once it's live

**Comment by oneadanut** [comment]
@Riztazz i think this fix made Onyxia to spawn less whelps than intended in both 10 and 25. In 25man I've seen like only 10 whelps and in 10man, around 5 whelps. This made the raid a joke.
