### ISSUE TITLE
zul farrak dustwraith rare has no loot table

### ISSUE THREAD

**Issue by xpeka95** [gamefreedomgit/Frostmourne#2492]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Dustwraith spawn is now fixed, i managed to find him 2 times in like 30 ids. But each time i got him, he dropped only silver coins no other loot.

**How to reproduce:**

**How it should work:**
He should be dropping various greens and greys as well as the blue item Desertwalker Cane ( https://www.wowhead.com/item=12471/desertwalker-cane ) which should have drop rate of 68% according to wow head. That item is the only off hand that ,, goes on your back ,, when you mog it. Thats why that mob is so important :)

**Database links:**
https://www.wowhead.com/npc=10081/dustwraith

**Comment by xpeka95** [comment]
Killed him 3 more times still the same, only silver coins drop.

**Comment by xpeka95** [comment]
got him again still no loot here is the pic:
https://imgur.com/QgafpGw

**Comment by xpeka95** [comment]
same again:
![WoWScrnShot_120924_213034](https://github.com/user-attachments/assets/4be6f8ad-4982-47a8-8cc6-98785731e152)

**Comment by Piootrek** [comment]
He has loot tables, just chances are really low. Increased them a bit.
