### ISSUE TITLE
[Dungeon] Novos the Summoner – Adds stay up on the stairs

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2493]
In Ascended II I have observed that the adds that spawn at the top of the stairs at [Novos the Summoner](https://www.wowhead.com/wotlk/npc=26631/novos-the-summoner) fight stay upstairs, they do not go down. Haven't had a chance to check it in other difficulties.

A side note: Spiders in room before this boss still spawn Spiderlings. If they get slowed while going to their den, the spiderlings simply spawn before they reach it. Spiderling spawn seems timed for certain amount of time since big spider starts to flee and it is not actually connected to spider reaching the den.

**Comment by Piootrek** [comment]
Should be fixed now.
