### ISSUE TITLE
[Ascended dungeon] [Trial of champion first boss]

### ISSUE THREAD

**Issue by GM-Nightmare** [gamefreedomgit/Frostmourne#2494]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
First boss is disappearing for no reason after people clearing the mount phase 

**How to reproduce:**
kill the mount phase and wait like a minute or two and they will either disappear or you wont be able to him them (unable to attack that)
tried everything and it just gave up , no way to restart the event or retrieve the boss back.

**How it should work:**

**Database links:**

**Comment by scrublama** [comment]
As far as i know theres no ascended version of trial of the champion.
If you queue ascended and get toc5 its the original toc5 hc

perhaps remove it from the ascended dungeon rotation if possible?

**Comment by UltraNix** [comment]
#2474
