### ISSUE TITLE
Achievment Fa-la-la-la-Ogri'la

### ISSUE THREAD

**Issue by lopesmane08** [gamefreedomgit/Frostmourne#2496]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Complete the Bomb Them Again! quest while mounted on a flying reindeer during the Feast of Winter Veil

**How to reproduce:** You have to turn in the quest while mounted on a flying mount and using the preserved holly item exclusive to the Feast of Winter Veil event.

**How it should work:** After turning in the quest while on the flying reindeer the achievment should proc

**Database links:**

**Comment by Piootrek** [comment]
Can you record a video of doing this quest? It works correctly for me.
