### ISSUE TITLE
[ToGC] Enraged swarm scarabs can be stunned and rooted

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#2498]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Hammer of justice and frost nova work on enraged swarm scarabs. Presumably all other stuns and roots also work.

Other types of CC seem to work as intended.

**How it should work:**
While affected by Determination, scarabs should be immune to stuns and roots.

**Database links:**
https://www.wowhead.com/wotlk/spell=66092/determination
![image](https://github.com/user-attachments/assets/edff3ee2-b3c4-45d7-8281-cfa70faa30e5)
![Wow_uvqxzInB46](https://github.com/user-attachments/assets/1914971f-47ae-4ceb-aed5-f00b35db1638)
![Wow_4BvWIv0ya2](https://github.com/user-attachments/assets/add48da4-df87-41f7-bf98-49fadce6df23)

**Comment by Piootrek** [comment]
Fixed, I will close this once the fix comes live.
