### ISSUE TITLE
 [quest] [11723] [Deploy the Shake-n-Quake!]

### ISSUE THREAD

**Issue by GM-Nightmare** [gamefreedomgit/Frostmourne#2502]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
using quest item near the webs should give you credit , its not giving any credit no matter where you use it

**How to reproduce:**
it should give credit after using item near the webs.

**How it should work:**

**Database links:**

**Comment by emirie1** [comment]
On my HC character Richelle, I'm able to get credit for deploying the Shake-n-Quake but Lord Kryxix never spawns after using the item.
