### ISSUE TITLE
Quest : Deploy the shake N'Quake

### ISSUE THREAD

**Issue by KryndorX** [gamefreedomgit/Frostmourne#2505]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The quest asks you to use the quest item in purpose to summon an npc and slay him , but the item doesn't deploy and  npc doesn't show up upon the use.

**How to reproduce:**
do the quest

**How it should work:**
Must count and progress , deploying doesn't count and NPC doesn't show up

**Database links:**
https://www.wowhead.com/wotlk/quest=11723/deploy-the-shake-n-quake

**Comment by UltraNix** [comment]
#2502
