### ISSUE TITLE
[Quest] [TBC] The Seer's Relic

### ISSUE THREAD

**Issue by Furiianda** [gamefreedomgit/Frostmourne#2507]
**Description:**
Quest cannot be turned in as the vision "freezes" and does not complete or grant credit.

**How to reproduce:**
Attempt to activate the item at the designated place/object, the cutscene starts, then freezes on the included screenshot frame. 
![WoWScrnShot_120224_172624](https://github.com/user-attachments/assets/a3a0fa07-049e-49b8-8ffc-8cf71bd44005)

**How it should work:**
The vindicator Sedai should fight the orcs and show him dying, but short of fixing the entire event, the item use at the correct location should also grant quest credit completion. :) 

**Database links:**
https://www.wowhead.com/wotlk/quest=9545/the-seers-relic

**Comment by Piootrek** [comment]
Fixed, I will close this once the fix comes live.
