### ISSUE TITLE
[Quest] Coward Delivery... Under 30 Minutes or it's Free

### ISSUE THREAD

**Issue by Furiianda** [gamefreedomgit/Frostmourne#2508]
**Description:**
When activating the Flare gun for delivering the escort NPC, it summons the Alliance unit Valiance Keep Officer to take the deserter, but the officer just stands there without taking the NPC from you, so the quest cannot be completed.

**How to reproduce:**
Fire flare gun with escort NPC at the designated location in the quest. (Video available via DB link)

**How it should work:**
When summoning the Valiance Keep Officer, the unit should activate a short dialogue "RP" scene where they take the prisoner from you and complete the quest.

**Database links:**
https://www.wowhead.com/wotlk/quest=11711/coward-delivery-under-30-minutes-or-its-free

**Comment by Piootrek** [comment]
Fixed, I will close this once the fix comes live.
