### ISSUE TITLE
Herbalism, experience not gained.

### ISSUE THREAD

**Issue by Chillzone93** [gamefreedomgit/Frostmourne#2509]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
(https://www.wowhead.com/wotlk/object=189973/goldclover)
(https://www.wowhead.com/wotlk/item=36907/talandras-rose)
(https://www.wowhead.com/wotlk/object=190173/frozen-herb)

**Description:**
When harvesting Goldclover and Talandra's Rose and Frozen Herb you do not gain experience even with the skill herbalism gaining levels.

**UPDATE:  This is an issue for all northrend herbs not just the ones i've listed above.**
**How to reproduce:**
use herbalism on Goldclover or Talandra's Rose or Frozen Herb.

**How it should work:**
harvesting herbs at the appropriate level of skill should grant some experience upon completion.

**Database links:**

**Comment by Chillzone93** [comment]
Update, this is an issue for all northrend herbs, not a single one of them gives experience no matter the herbalism level. yet i go back to any pre-wotlk area and it gives experience for every herb just fine.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by lordtunderrin** [comment]
nightmare vine and terrocone are not giving experience when harvested now.

**Comment by Piootrek** [comment]
That's another issue, fixed too. Will be live after server update.
