### ISSUE TITLE
aoe looting broken

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#251]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Currently you can dupe items by looting a mob, killing something on top of its corpse and looting again, this works with quest items, boss drops, etc

https://youtu.be/4A-d2ar0S_M

**Comment by qqdbpp** [comment]
holy shit

**Comment by Godmatik** [comment]
Lol

**Comment by Inukk** [comment]
I haven't checked if this also works with containers but I'm guessing you can still do it, so things like four horsemen's chest, freya's loot cache, etc

**Comment by Godmatik** [comment]
You can aoe loot quest objects on ground as well next to a corpse you looting

**Comment by Afgann** [comment]
fixed
