### ISSUE TITLE
[The Culling of Stratholme] Arthas

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2510]
**Description:**
When you talk with Arthas to face last boss, he basically teleports there and in a few seconds he starts the encounter. If you are not fast enough, the door get closed.

**How to reproduce:**
Talk with Arthas for last boss.

**How it should work:**
He shouldn't teleport there, he should run along with party members.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
