### ISSUE TITLE
[Utgarde Pinnacle] Skadi

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2511]
**Description:**
Skadi is doing his breath too fast in phase 1 after returning, he shoud stay in air 2-3 more seconds to allow throwing harpoons.

Also, his whirlwind in phase 2 seems to be undodgable. It should be dodgable/parriable and I think all mobs/bosses on this server have this bug.

**Comment by Greywolf59** [comment]
I do agree at least one second period should be added to this. It is not a problem for most classes, but for some without either speed boosts or quick defensive cds it is.
Also there is something invisible meleeing down on hunter and arlock pets. I think it start in the room after Svala.
And the Vrykuls spawning at Skadi sometimes do fall throught texture on spawn (always oen of the two), which is I think a result of no immediate threat (no hots going on, etc) becuase it happened when only me and tank survived so we were a bit further away from the entrance, still close enough, and we had no heals and spells going when they spawned.

**Comment by Piootrek** [comment]
Skadi will stay longer in a harpoons range.

> Also, his whirlwind in phase 2 seems to be undodgable. It should be dodgable/parriable and I think all mobs/bosses on this server have this bug.

Do you have any proof for this?

> Also there is something invisible meleeing down on hunter and arlock pets. I think it start in the room after Svala.
And the Vrykuls spawning at Skadi sometimes do fall throught texture on spawn (always oen of the two), which is I think a result of no immediate threat (no hots going on, etc) becuase it happened when only me and tank survived so we were a bit further away from the entrance, still close enough, and we had no heals and spells going when they spawned.

I couldn't reproduce any of those bugs. Please make a video if you encounter those issues again and make a new report.

**Comment by Greywolf59** [comment]
I will try to make a video but gyazo I am using has max 8s or something. When reproducing, have you skipped Svala? Because that is what everyone is doing these days.

**Comment by Piootrek** [comment]
> I will try to make a video but gyazo I am using has max 8s or something. When reproducing, have you skipped Svala? Because that is what everyone is doing these days.

I ran through whole dungeon with pet out and killed all bosses.

**Comment by Greywolf59** [comment]
Might be Svala issue then, thoguh the hits are really really small and nothing is visible. I will keep an eye out.

**Comment by oneadanut** [comment]
I thought whirlwind should act the same as bladestorm from warrior which can be dodged, but maybe I'm wrong.
