### ISSUE TITLE
[Trial of the Champion] Couple of bugs

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2512]
1. First boss:
- Mounts of first encounter have too much speed, you should be able to outrun them and kite.
- They should ignore unmounted players if there are mounted players alive.
- They shouldn't change targets every time they charge to the charged player.
- The bosses shouldn't start encounter by themselves after killing their mounts.
- The npc should have voice presenting the bosses.
- There should be an option on the npc to skip introducing the bosses, after you did toc5 on a previous run.

2. Priestess:
- Holy fire dot shouldn't do damage while in confess stun.

**The cooldowns don't reset after killing any of the bosses in Trial of the Champion.**

**I joined Toc5 via random dungeon finder and I didn't get the Emblem of Triumph, I had to do another random dungeon.**

**Comment by Piootrek** [comment]
Please provide proof that should work as you say.

**Comment by oneadanut** [comment]
I'm done reporting.
