### ISSUE TITLE
TOGC - Anubarak - Nerubian Burrower - Expose Weakness

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#2513]
Expose Weakness should be applied to the tank even if the damage has been completely absorbed or completely blocked. The Debuff overlay should not occur only if the nerubian burrower missed the tank or the tank dodged/parried.
On our server, stacks on a tank occurs only when taking damage, and this is a bug.
https://www.wowhead.com/blue-tracker/topic/us/anub-hc-nerubian-burrower-incorrect-interaction-with-block-1582516
![image](https://github.com/user-attachments/assets/6ab4f975-9a1d-4829-8378-b81a65d2dea4)

https://www.wowhead.com/spell=67721/expose-weakness
https://www.wowhead.com/cata/npc=34607/nerubian-burrower

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by yeagerca** [comment]
I think this blue post is being misconstrued and the change being made is incorrect.
```
Author: Piootrek 
Message: DB/Spell: Nerubian Burrowers should apply Expose Weakness debuff to a target even when initial damage was fully mitigated (Anub'arak encounter)
https://github.com/gamefreedomgit/Frostmourne/issues/2513
```
The blue post does not address whether or not a stack of Expose Weakness should be applied to a fully blocked attack, only how the damage calculation works _after stacks are already present_. With sufficient block value (extremely min-maxed), a you should be able to avoid getting stacks in the first place.

A block that fully mitigates a swing fire a MISSED combat log event similar to a parry, dodge, and miss which do not apply stacks.
These combat log entries were collected on Frostmourne today in TOC10 Normal.
Full block: `12/3 14:16:33.509  SWING_MISSED,0xF13000872F277385,"Nerubian Burrower",0xa48,0x0000000000003753,"Lithdora",0x100511,BLOCK,2628`
Parry: `12/3 14:17:17.195  SWING_MISSED,0xF13000872F2773DC,"Nerubian Burrower",0xa48,0x0000000000003753,"Lithdora",0x100511,PARRY`
Partial block: `12/3 14:17:11.744  SWING_DAMAGE,0xF13000872F277385,"Nerubian Burrower",0xa48,0x0000000000003753,"Lithdora",0x100511,150,0,1,0,3447,0,nil,nil,nil`

[WoWCombatLog - 10nm blocking stacks (unedited).txt](https://github.com/user-attachments/files/17999357/WoWCombatLog.-.10nm.blocking.stacks.unedited.txt)

**Comment by NickZedd** [comment]
Agreed. The blue post is talking about a completely different thing. It does not say how those stacks got on the tank in the first place, and that could easily have happened because the tank did not have block value cap, meaning he would constantly take small hits but because the block happens before the % damage increase, the damage remains quite low. @Piootrek

**Comment by Piootrek** [comment]
https://youtu.be/-EWFz94HQWI?t=31
All hits got blocked and tank still gets stacks.
