### ISSUE TITLE
Quest: The Seer's Relic

### ISSUE THREAD

**Issue by Amine-x-x** [gamefreedomgit/Frostmourne#2516]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When you use the quest item , nothing happen even if it cast it , yet no count the progress.

**How to reproduce:**

**How it should work:**
Progress must count

**Database links:**
https://www.wowhead.com/quest=9545/the-seers-relic

**Comment by Furiianda** [comment]
This has been reported and fixed!
https://github.com/gamefreedomgit/Frostmourne/issues/2507
