### ISSUE TITLE
Opposite Faction T9 piece can't be traded back to vendor

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2517]
I am Human Warrior. I have bought [Hellscream's Gauntlets of Conquest](https://www.wowhead.com/wotlk/item=48387/hellscreams-gauntlets-of-conquest). I did not notice it is Horde version and I did not plan to keep them in the first place. However immediately after transaction, I can't give them back to the vendor for refund.
![t9](https://github.com/user-attachments/assets/c3ff21e1-82f6-4c74-83ac-0946d4ba370c)

**Comment by Greywolf59** [comment]
By this report I would also liek ot ask for refund or solving the issue on my account if possible. As you can see ingame name is Lykfar. Other toons for verification: Chava, Baelgar, Geshoia, Imperfect, Zarthos.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
