### ISSUE TITLE
[Quest] Treats for Great-Father Winter

### ISSUE THREAD

**Issue by Furiianda** [gamefreedomgit/Frostmourne#2518]
**Description:**
The horde side version of this quest is repeatable, when it should be a one-time turn-in only.

**How to reproduce:**
Turn the quest in... then turn the quest in... then turn the quest in... (etc.) 

**How it should work:**
The quest can be turned in once only, or perhaps once per year/event.

**Database links:**
https://www.wowhead.com/wotlk/quest=6962/treats-for-great-father-winter

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
