### ISSUE TITLE
Azjol Nerub - Anub'ar Prime Guard - Drain Power

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#2519]
The problem is that when Anub'ar Prime Guard uses Drain Power, it imposes a debuff on the players, but it does not receive a buff that increases its damage from each imposed debuff.

This is how it should look like, 20 stack 1 stack From each player.
![image](https://github.com/user-attachments/assets/4023bfe4-0e45-4821-8c3c-c006f0ae0937)

https://www.wowhead.com/spell=59354/drain-power
https://www.wowhead.com/npc=29128/anubar-prime-guard

**Comment by wowclassic1234** [comment]
> Fixed, I will close this issue once the fix comes live.

The correction was done incorrectly. Currently, an NPC receive only 1 buff stack with 5 participating players in the battle.

It must be so. If 5 players are involved in the battle, then the NPC should receive 5 stacks for one use.

The screenshot shows that the guards have 20 stacks, and I have 8 stacks, the rest of the bets were received from other players.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by wowclassic1234** [comment]
> > Fixed, I will close this issue once the fix comes live.
> 
> These guards deal 4-5 times less damage than on the Official server, 2.7k hit at 23 stacks. On the official server, hit 11k. The proof is higher.
> 
> ![image](https://private-user-images.githubusercontent.com/173220680/398573966-6ebfc5df-ccd4-4d33-9bea-aa9a265a4549.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMzE4MjEsIm5iZiI6MTczNTEzMTUyMSwicGF0aCI6Ii8xNzMyMjA2ODAvMzk4NTczOTY2LTZlYmZjNWRmLWNjZDQtNGQzMy05YmVhLWFhOWEyNjVhNDU0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQxMjU4NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDVjOWY2NzZkNWQxMWE0MjJjMzczNjVhNDY3MWExNzU5NjlhNDgwYTdmNDZmOGU4MmJmNDNiMWIwMTc3YzdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DH46-3UzvM5W3oPgfCpKAdFQuOotUZATiUaSJdLgCMc)

Two options. Either the stacks don't work, or the NPC's initial damage is too low.
