### ISSUE TITLE
[Dungeon] Gundrak Drakkari Battle Rider

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#252]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
When pulling the rhinos at the end of Gundrak, the riders stand still on the ground instead of mounting the rhinos

![ApplicationFrameHost_QIVIW0IToA](https://github.com/gamefreedomgit/Frostmourne/assets/101921457/d8ce3400-c692-49e5-a11a-e1cebd67d43a)

**Comment by UltraNix** [comment]
@Inukk You wiped there? 
These riders dismount rhino on its death and then stay there for a while.

**Comment by Inukk** [comment]
we didn't wipe. I know the riders dismount when you kill the rhino, what I'm saying is that they're not mounting the rhinos at all even before pulling them, I'll attach a clip of the run as further proof

https://github.com/gamefreedomgit/Frostmourne/assets/101921457/344b7208-0887-460d-9c2d-2f662df60706

**Comment by UltraNix** [comment]
@Inukk It happens every time you are there? 
I'm not able to reproduce it though :/
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/6ee82d07-0dcf-41f8-9009-17857f6dd0dd)

**Comment by Inukk** [comment]
We haven't done gundrak since I made the bug report, but we did the entire dungeon twice on heroic and both times the battle riders didn't move

**Comment by WhitemaneIsa** [comment]
No further info in 3 months, seems to be okay now.
