### ISSUE TITLE
TO(G)C Faction Champions are Bugged and abusable - Range attack/Deathgrip

### ISSUE THREAD

**Issue by Tetrahydrx** [gamefreedomgit/Frostmourne#2520]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)

If Faction Champions get pulled by a range attack/deathgrip, and no player is close to them, they just stand on their spot and dont move at all.

[//]: # (https://www.wowhead.com/wotlk)
https://streamable.com/tv5w9y Video with Proof of it happening

**Description:**

**How to reproduce:**
Pull Faction with any Range spell, or try Death Gripping adds out (Without sending pets in), and ull see how they act

**How it should work:**
Whenever you pull Faction, all of them needs to start moving together

**Database links:**

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
