### ISSUE TITLE
[Dungeon] [Achievment] ToC 5 HC Champions kill credit not awarded

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2521]
Killing Horde champions in ToC 5 HC does not provide kill credit for the achievment [Heroic: Trial of the Champion](https://wotlk-twinhead.twinstar.cz/?achievement=4298). I actually did get kill credit for Mokra the Skullcrusher but it might have been from Ascended dungeon when he actually died, I don't remember.
![toc](https://github.com/user-attachments/assets/3a135544-15ba-403d-98fb-2a0287370467)

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
