### ISSUE TITLE
TOGC - icehowl

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#2522]
On our server, the Icehowl boss has an attack speed of 2.0. It should be 1.7, influenced by debuff 2.04

![image](https://github.com/user-attachments/assets/e73c2fe2-9e20-4302-ac33-b8ce9d520ab3)

https://www.wowhead.com/npc=34797/icehowl

**Comment by wowclassic1234** [comment]
On our server, the Valkyrie sisters have an attack speed of 2.0, the speed should be 1.5, under the influence of debuff 1.8

![image](https://github.com/user-attachments/assets/dd875c57-c20f-47bf-87d5-a4410a446155)

https://www.wowhead.com/npc=34497/fjola-lightbane
https://www.wowhead.com/npc=34496/eydis-darkbane

**Comment by wowclassic1234** [comment]
Mistress of pain has the wrong attack speed. We have a speed of 2.0 installed on the server, the speed should be 1.5 seconds.

She must also deal damage with two hands. We have her hitting with one hand.


![image](https://github.com/user-attachments/assets/57791b8c-f0e9-4e7d-a2f7-e01e53ecabeb)
https://www.wowhead.com/wotlk/npc=34826/mistress-of-pain

**Comment by crabcakeowo** [comment]
I believe changing valk attack speed will make it almost impossible to do, especially when there's already a stacking buff on it during abilities that increase their attack speed by 5% per stack every attack.

**Comment by wowclassic1234** [comment]
> I believe changing valk attack speed will make it almost impossible to do, especially when there's already a stacking buff on it during abilities that increase their attack speed by 5% per stack every attack.

There is no need to exaggerate, tanks and other raid participants have protective cooldowns that help them survive particularly dangerous boss abilities.

**Comment by wowclassic1234** [comment]
> This is not an exaggeration, not sure if you've done valks on ptr, but the moment raid reaches 20 stacks and ability comes, tanks die through dprot + bubble hsac, notice that I don't mention anything about any other boss except valks.

Use def cd and you won't have any problems. This is a normal situation when a buff appears on the bosses and the valkyrie starts beating faster.

**Comment by wowclassic1234** [comment]
> This is not an exaggeration, not sure if you've done valks on ptr, but the moment raid reaches 20 stacks and ability comes, tanks die through dprot + bubble hsac, notice that I don't mention anything about any other boss except valks.

Algalon has an attack speed of 1.0, he hits with two hands, in addition, he also uses two abilities that deal damage + black holes explode. And no one complains about him.

**Comment by crabcakeowo** [comment]
Do you even raid on this server or you just randomly reporting nonsense? The stacks I was talking about is a custom buff that gives the boss 5% damage every 10 orbs are soaked. Tanks were getting hit for 20-30k through defensives and getting hit for 40k twin spikes. If you have no clue what you are saying, I would rather you not make random reports that is going to break the encounter completely and ruin everyone's experience of the server.

**Comment by crabcakeowo** [comment]
you are reporting something without taking into account what repercussions it has on the current tuning, if you're not here to make the server better than don't bother reporting?

**Comment by wowclassic1234** [comment]
> you are reporting something without taking into account what repercussions it has on the current tuning, if you're not here to make the server better than don't bother reporting?
> 
> If you're going to be reporting things regarding tuning, at least show that you are an active raider in this server, else whatever you say holds no grounds on this server because TOGC is custom buffed not like CLASSIC.

I am an active raider on this server, I have two characters and I participate in all guild raid set the highest difficulty. I close all the content. There is no need to manipulate what you don't know about. I'll repeat it again for you. If you think the boss's damage is too high, create a separate topic about damage. No need to get into the subject of the boss's attack speed. You initially started the conversation in the wrong topic, so please leave it and create your own.

**Comment by crabcakeowo** [comment]
Yes but damage is supposed to be like that, tuning was like that because attack speed was set at 2.0 because damage is ridiculously high. You are reporting something to change this which means tuning for damage has to be changed as well, or we just don't touch something that is not broken? Simple as that.

**Comment by wowclassic1234** [comment]
> Yes but damage is supposed to be like that, tuning was like that because attack speed was set at 2.0 because damage is ridiculously high. You are reporting something to change this which means tuning for damage has to be changed as well, or we just don't touch something that is not broken? Simple as that.
> 
> Also, if you say you've done all content set at highest difficulty, show us logs of val'kyrs TOGC on PTR or live.
> 
> If you can't provide any of this, there's no grounds for you saying this, because you're just intentionally gatekeeping 95% of the server from doing this boss if you try to implement this change.

What kind of nonsense are you writing, you say that tanks received 20-30 k damage and 40k damage, using def cooldowns, and at the same time you claim that this is how it should be, which is complete nonsense and accuse me of putting their attack speed in order.  I have never seen such schizophrenia as yours.

**Comment by crabcakeowo** [comment]
Have you seen any videos of frosthold buffs or are you just talking without having a clue on whats happening here? Valks have a soft enrage on this server due to stacks building up gradually over the course of the fight. This change will just ruin the tuning of the encounter, considering during ability speedup the bosses are already hitting for 30k. You must be out of your mind of changing it.
![image](https://github.com/user-attachments/assets/d4797dd5-16d2-47ec-9708-259a9e3a043b)

**Comment by wowclassic1234** [comment]
> Have you seen any videos of frosthold buffs or are you just talking without having a clue on whats happening here? Valks have a soft enrage on this server due to stacks building up gradually over the course of the fight. This change will just ruin the tuning of the encounter, considering during ability speedup the bosses are already hitting for 30k. You must be out of your mind of changing it.
> 
> So yeah, if you've raided TOGC this reset, let me know how it went. I'm waiting to see if you can even down Northrend beasts.

For the mentally retarded, I repeat once again, if you think that valkyries cause too much damage, then create a separate topic and report this problem there, no need to spray saliva in my topic about the boss's attack speed. For idiots, I'll explain how the settings are set, first the boss is corrected by setting up blizzlike, and then the boss gets damage boosts 
 or damage reduction depending on the developer's vision. If you do not understand, then go outside and get some fresh air, I do not know how to help anymore.

**Comment by crabcakeowo** [comment]
Nobody is asking for your help regarding this issue, when the server is running togc on FROSTHOLD TUNING not BLIZZARD TUNING, how do you not understand this? You are trying to mix the two up which is going to be a problem, I'm not sure if I'm being clear enough for you, CURRENT BOSSESS MECHANICS WERE MADE WITH THIS BASE ATTACK SPEED IN MIND NOT BLIZZARD TUNING.

**Comment by crabcakeowo** [comment]
Which like I said, if devs are deciding to go with BLIZZARD TUNING instead of FROSTHOLD TUNING, they have to speak up and let us know what are they planning for this TOGC. If not, just don't touch stuff like this just because you have an idea of what is right when you clearly don't.

**Comment by wowclassic1234** [comment]
> Which like I said, if devs are deciding to go with BLIZZARD TUNING instead of FROSTHOLD TUNING, they have to speak up and let us know what are they planning for this TOGC. If not, just don't touch stuff like this just because you have sort of an idea of what its like on classic when the server is not like classic.

What you call the FROSTHOLD TUNING is the usual increase in damage and health of the boss. All pirate servers increase the complexity according to this scheme, the developers take the rest of the parameters from the basic settings of Blizzard. There is no need to talk about FROSTHOLD TUNING as something fantastic, where every mechanic is changed and carefully thought out. You're exaggerating again.

**Comment by crabcakeowo** [comment]
I'm not exaggerating, go check how many guilds killed val'kyrs on 25hc, you don't have logs of your own personal testing, you don't have evidence of anything and you're just making reports based on classic when this server is clearly NOT classic. This is not the same as fixing things such as abilities being targeted wherever they are not supposed to.

**Comment by Aitirn** [comment]
Let me be clear here, @wowclassic1234 i smell you havent stepped inside TOGC on either Frosthold or here, Valkyrs as first of all, are having 57 Milions HP, as second, Valkyrs are having Stacking DMG Buff, so increasing their attack speed, with 150% bonus DMG, with additional 200% haste from abilities, no CD saves your tank, once u reach 20 stacks on bosses, tanks are geting clearly one shot with any CD Active on them, incase their attack speed is 1.5 sec, it means your limit of stacks will be reduced even more, i can see your name, you are  addicted to wowclassic, sending fake screenshots and videos of Russian server (As the gems report), but you cant compare classic with something thats boosted Heroic.

**Comment by wowclassic1234** [comment]
> Позвольте мне внести ясность, @wowclassic1234 я чувствую, что вы не заходили в TOGC ни в Frosthold, ни здесь, у валькирий, во-первых, 57 миллионов HP, во-вторых, у валькирий есть усиление на накопление DMG, поэтому они увеличивают скорость атаки, получая 150% бонусных DMG и дополнительные 200% скорости от способностей, ни один CD не спасает ваш танк, как только вы достигаете 20 стеков на боссов, танки получают четко один выстрел с любым CD, активным на них, если их скорость атаки составляет 1,5 секунды, это означает, что ваш лимит стеки сократятся еще больше, я вижу ваше имя, вы зависимы от wowclassic, отправляете поддельные скриншоты и видео с российского частного сервера (как сообщают gems), но вы не можете сравнивать classic с чем-то, что усиливает Heroic.

Thank you, the quote about the Russian private server made my day.

**Comment by oomshroom** [comment]
> What you call the FROSTHOLD TUNING is the usual increase in damage and health of the boss. All pirate servers increase the complexity according to this scheme, the developers take the rest of the parameters from the basic settings of Blizzard. There is no need to talk about FROSTHOLD TUNING as something fantastic, where every mechanic is changed and carefully thought out. You're exaggerating again.

I would mostly agree with you for any other raid, but in the context of Frosthold's ToGC it really makes one wonder if you've even stepped foot in the raid, on either PTR or Live, or just analyzed boss attack speed from someone else's logfile.

**Comment by RadeghostWM** [comment]
Hey. The decision is not to buff bosses any further. While it may be not ultra-difficult for super hardcore guilds, we also want less hardcore players to have a shot.
