### ISSUE TITLE
TOGC - Anubarak - penetratingcold

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#2523]
In 25 HC mode (I don't know about the other modes), the penetrating cold ability should be applied every 26 seconds when there is a boss fight, and every 20 seconds when the boss burrows underground.

https://youtu.be/ba4tkrLmdfk?t=1782

https://www.wowhead.com/wotlk/spell=66013/penetrating-cold
https://www.wowhead.com/wotlk/npc=34564/anubarak

**Comment by crabcakeowo** [comment]
This is not a legitimate bug report. It's supposed to be every 20 seconds based on frosthold buffs, if we are moving away from that then devs will have to speak up, because currently I'm looking at the bug tracker and right now some of the bosses are having a mixture of frosthold buffs and classic tuning.

**Comment by wowclassic1234** [comment]
> This is not a legitimate bug report. It's supposed to be every 20 seconds based on frosthold buffs, if we are moving away from that then devs will have to speak up, because currently I'm looking at the bug tracker and right now some of the bosses are having a mixture of frosthold buffs and classic tuning.

I even like your version better.

**Comment by NickZedd** [comment]
The video you linked to is private

**Comment by wowclassic1234** [comment]
> The video you linked to is private

This is my gameplay from the official wotlk Classic

**Comment by Riztazz** [comment]
That's not what he meant.
"Video is unavailable, because it is private" when we try to access it.

**Comment by Riztazz** [comment]
> This is not a legitimate bug report. It's supposed to be every 20 seconds based on frosthold buffs, if we are moving away from that then devs will have to speak up, because currently I'm looking at the bug tracker and right now some of the bosses are having a mixture of frosthold buffs and classic tuning.

Also this, so closing
