### ISSUE TITLE
[ToGC] Anub'arak's Freezing Slash should reset his melee swing timer

### ISSUE THREAD

**Issue by oomshroom** [gamefreedomgit/Frostmourne#2524]
Currently Freezing Slash does not interact with his swing timer at all.
From this image (classic WCL) you can see how it should work: It is cast regardless of swing timer, but when it is cast the swing timer is reset (to 1.8, his attack speed with a 20% debuff).
![image](https://github.com/user-attachments/assets/b2c5bba8-97bd-4f7d-b8c8-42de00fdc179)

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
