### ISSUE TITLE
Quest : Kaw the mammoth destroyer

### ISSUE THREAD

**Issue by KryndorX** [gamefreedomgit/Frostmourne#2526]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Cannot mount any mammoth around him even if some of them let you , you get instant dismount. 
**How to reproduce:**
Do the quest normally trying to mount a mammoth around the Quest npc

**How it should work:**
Must be able to mount the mammoths around.

**Database links:**
https://www.wowhead.com/wotlk/quest=11879/kaw-the-mammoth-destroyer

**Comment by Nimbux** [comment]
All quests that require you to mount or use a vehicle are currently bugged.
For referance : https://github.com/gamefreedomgit/Frostmourne/issues/2527

**Comment by Piootrek** [comment]
I've made some changes, please let me know if it happens again after the server update.

**Comment by Vaxsysl** [comment]
@Piootrek It got bugged again. This time we can mount the woolies, but Kaw gets "stuck".
He's invulnerable and standing still until the game recognises us on wooly nearby or when we attack Moira. But we can only attack Moira, we cannot damage Kaw. Once we kill Moira he dismounts and runs to his place.

**Comment by Vaxsysl** [comment]
Hmm, I attempted it again today and it worked. Kaw did not reset. Idk now...
