### ISSUE TITLE
Vehicle Bug

### ISSUE THREAD

**Issue by Nimbux** [gamefreedomgit/Frostmourne#2527]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)
https://www.wowhead.com/wotlk/quest=11652/the-plains-of-nasam

**Description:**
Cannot complete quests that require you to use a vehicle or use/mount a NPC because you get instantly kicked out of the vehicle or you get dismounted

**How to reproduce:**
For referance : Accept the quest Plains of Nasam in Borean Tundra , try to use the tanks near the NPCs, you'll get instant kicked out of them

**How it should work:**
You should be able to use vehicles normally

**Database links:**
https://www.wowhead.com/wotlk/quest=11652/the-plains-of-nasam

**Comment by Piootrek** [comment]
I've made some changes, please let me know if it happens again after the server update.
