### ISSUE TITLE
[Quest][Alliance] Borean Tundra - Last Rites

### ISSUE THREAD

**Issue by emirie1** [gamefreedomgit/Frostmourne#2528]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
After talking to Thassarian at the top of the necropolis in Borean Tundra, he walks forward and the NPCs spawn to begin the scene. However, they do not walk into the center and just stand at the sides where they spawn in at. After about 5 minutes the NPCs despawned and Thassarian remained standing at the top of the ramp he first walks up. Another 5 minutes after that he started his dialogue and walked to the center of the platform. I submitted a GM ticket and Trombone came and reset Thassarian, but the event bugged out again. He was able to complete the quest for us by using his GM powers to kill Prince Valanar which triggered the objective to complete.

**How to reproduce:**
Accept the Alliance quest "Last Rites" from Thassarian in Borean Tundra, then go to the top of the necropolis and speak to him to start the event. Thassarian will walk up the ramp and Counselor Talbot and the Image of the Lich King will appear on opposite sides of the platform and just stand there.

**How it should work:**
Accept the Alliance quest "Last Rites" from Thassarian in Borean Tundra, then go to the top of the necropolis and speak to him to start the event. Thassarian will walk up the ramp and Counselor Talbot and the Image of the Lich King will appear on opposite sides of the platform and walk to the center of the platform where dialogue plays out, 2 more NPCs spawn, Thassarian reacts, and then Valanar becomes hostile and begins to attack Thassarian.

**Database links:**
https://www.wowhead.com/wotlk/quest=12019/last-rites

**Comment by Piootrek** [comment]
Should be fixed now.
