### ISSUE TITLE
[Quest] [13809] [Threat From Above]

### ISSUE THREAD

**Issue by Pupkos** [gamefreedomgit/Frostmourne#2529]
https://streamable.com/nev9st Video proof of me not being able to use Crusader Strike

Description:
Melee abilities such as Crusader Strike/Heroic Strike/Bloodthirst etc. cannot be used due to Chillmaw flying high in the air even after moving to higher places. The mob just positions itself far from player no matter the player movement.

How to reproduce:

How it should work:
Chillmaw should come close enough to the player so that he/she can use his/her melee spells.

Database links:
https://www.wowhead.com/wotlk/quest=13809/threat-from-above

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
