### ISSUE TITLE
[Quest] A Little Help From My Friends

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#253]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
During the escort, Ringo will afk beside you instead of attacking mobs that are aggroed

https://youtu.be/cL6Mf0EMQ6I

**Comment by Godmatik** [comment]
Same occurs with Tooga escort in Tanaris

**Comment by Afgann** [comment]
fixed

**Comment by GM-Nightmaree** [comment]
18/6/2024 , Little help from friends broke again 
![image](https://github.com/gamefreedomgit/Frostmourne/assets/157993777/c5aece50-daae-48fb-9326-18842256c8e5)
