### ISSUE TITLE
[Quest] Deciphering the Book – post-completion event missing

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2532]
Quest [Deciphering the Book](https://www.wowhead.com/wotlk/quest=9557/deciphering-the-book) is missing its post-completion event, the says of [Anchorite Paetheus](https://www.wowhead.com/wotlk/npc=17424/anchorite-paetheus).

https://wowpedia.fandom.com/wiki/Deciphering_the_Book#Cut_scene_upon_completion
https://www.wowhead.com/wotlk/quest=9557/deciphering-the-book#comments:id=852815

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
