### ISSUE TITLE
[ToGC] Anub'arak's Nerubian Burrowers should cast Submerge with a cast time, even when they are on an ice patch

### ISSUE THREAD

**Issue by oomshroom** [gamefreedomgit/Frostmourne#2533]
- Nerubian Burrowers should cast Submerge (to no effect) even when on an ice patch
- The Submerge ability should have a cast time (it currently does not)

[https://youtu.be/qosIcX6Jgus?t=36](https://youtu.be/qosIcX6Jgus?t=36)
[https://wotlk.evowow.com/?spell=67322](https://wotlk.evowow.com/?spell=67322)

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
