### ISSUE TITLE
Epic gems 

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#2536]
Single-colored stones sold for Pvp currency should cost 20k honor. On our server they cost 10k of any color.

![image](https://github.com/user-attachments/assets/da60b128-1702-4fd2-941f-a5db169aa220)

**Comment by crabcakeowo** [comment]
![image](https://github.com/user-attachments/assets/4d0becf5-6455-489e-98d4-7fcb4ebcd7ea)
from trinity core database

I'd suggest not making random bug reports such as this.

**Comment by crabcakeowo** [comment]
I'd leave it as is as it incentivises players to do random bg daily/wintergrasp as well.

**Comment by wowclassic1234** [comment]
> ![image](https://private-user-images.githubusercontent.com/176484749/392480290-4d0becf5-6455-489e-98d4-7fcb4ebcd7ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMzIxMzgsIm5iZiI6MTczMzMzMTgzOCwicGF0aCI6Ii8xNzY0ODQ3NDkvMzkyNDgwMjkwLTRkMGJlY2Y1LTY0NTUtNDg5ZS05OGQ0LTdmY2I0ZWJjZDdlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxNzAzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMWRiMWVkYTNlMTVlMmJkN2VhM2U4MjcyOGI2MDE5YTQ1ZjcwMmQyODI1NjAxOGMxYmVhYTgzODY4MWJjMzkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WR9kqPR81R9X97h_2yK8U8BHJiCAP71ICnE-fAwxmos) from trinity core database
> 
> I'd suggest not making random bug reports such as this.
> 
> Also, have confirmed with some classic players that it was actually 10k as well.

This is a screenshot from the official wotlk classic

**Comment by roblox-oof-dot-mp3** [comment]
> > ![image](https://private-user-images.githubusercontent.com/176484749/392480290-4d0becf5-6455-489e-98d4-7fcb4ebcd7ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMzIxMzgsIm5iZiI6MTczMzMzMTgzOCwicGF0aCI6Ii8xNzY0ODQ3NDkvMzkyNDgwMjkwLTRkMGJlY2Y1LTY0NTUtNDg5ZS05OGQ0LTdmY2I0ZWJjZDdlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxNzAzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMWRiMWVkYTNlMTVlMmJkN2VhM2U4MjcyOGI2MDE5YTQ1ZjcwMmQyODI1NjAxOGMxYmVhYTgzODY4MWJjMzkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WR9kqPR81R9X97h_2yK8U8BHJiCAP71ICnE-fAwxmos) from trinity core database
> > I'd suggest not making random bug reports such as this.
> > Also, have confirmed with some classic players that it was actually 10k as well.
> 
> This is a screenshot from the official wotlk classic https://www.wowhead.com/wotlk/item=36922/kings-amber#sold-by ![image](https://private-user-images.githubusercontent.com/173220680/392499525-76370334-2613-4e6e-9534-4303cf0213fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMzY0NDAsIm5iZiI6MTczMzMzNjE0MCwicGF0aCI6Ii8xNzMyMjA2ODAvMzkyNDk5NTI1LTc2MzcwMzM0LTI2MTMtNGU2ZS05NTM0LTQzMDNjZjAyMTNmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxODE1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjUxOWJjN2FlNWYyN2IzNTBjMTY1YmQ4MjExMmU2OGVlNjI2Zjc3MmEwYjg5MDRkMTQzZWM5YTgyNzRmMTk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6Bs7HryG7eNnlW4-804ph0nF5zbOyW5CkVrcLENtUTI)

Here's a blog from the original patch adding them describing prices. I've never seen nor heard of gems being 20k honor each, that looks like a change specific to the re-release.

http://www.bananashoulders.com/2009/06/26/epic-gems-and-jewelcrafting-in-3-2/
![image](https://github.com/user-attachments/assets/f94a6141-6971-4287-b327-b9a8eaa56396)

**Comment by oomshroom** [comment]
wowhead comments from og wotlk:
https://www.wowhead.com/wotlk/item=36919/cardinal-ruby#comments
https://www.wowhead.com/wotlk/item=36925/majestic-zircon#comments
![image](https://github.com/user-attachments/assets/2d309c90-efe7-4997-9772-5eeefd187720)
![image](https://github.com/user-attachments/assets/9cf98686-6ec9-4ce5-883b-e53ef3ba98ef)
![image](https://github.com/user-attachments/assets/411aa35a-2a9a-472f-9815-a9d8d2d78f33)
![image](https://github.com/user-attachments/assets/be41aed3-0869-456c-b579-e69154c8d764)

the only comment to mention a price of 20k is from classic wotlk:
https://www.wowhead.com/wotlk/item=36922/kings-amber#comments
![image](https://github.com/user-attachments/assets/f9988b82-931d-46d2-b5dd-fe05553ebbbe)

**Comment by Riztazz** [comment]
We will keep it at 10k
