### ISSUE TITLE
Cannot refund Tier 9 (plate) 

### ISSUE THREAD

**Issue by Leonhart29** [gamefreedomgit/Frostmourne#2537]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I bought the tier 9 paladin tank hands instead of the dps ones by mistake and i cannot refund it. When i try to sell it back it just grays out (and nothing else happens) and i can't move it anywhere else in the bag

Edit: i found out that i bought them from the alliance vendor (turalyon handguards of conquest), instead of the horde one which sells the liadrin's set. The hands automatically converted to the horde ones.

**How to reproduce:**
Idk how that happened. I also tried with the shoulders and it worked, but not with the hands (tank)

**How it should work:**
It should be possible to refund the item in the span of 2 or 3 hrs

**Database links:**
https://www.wowhead.com/wotlk/item=48653/liadrins-handguards-of-conquest

**Comment by Piootrek** [comment]
Should be already fixed.
