### ISSUE TITLE
[Quest][Argent Tournament]Missing dailies

### ISSUE THREAD

**Issue by emirie1** [gamefreedomgit/Frostmourne#2538]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The daily quest giving NPCs for the Silver Covenant and the Sunreavers are missing from their respective places, thus leaving the following set of dailies at the Argent Tournament unable to be obtained:
![image](https://github.com/user-attachments/assets/26854167-8309-4a7a-8a0f-2d0407bd1b5d)

As my main is an alliance character, the Silver Covenant NPCs should be at this location with the Sunreavers NPCs mirrored in the Horde's tent:
![image](https://github.com/user-attachments/assets/e8b11fc7-88b8-4cf0-8e7a-be5de2ed88be)

Proof that I am exalted with the Silver Covenant and thus not just missing these dailies because I am not exalted:
![image](https://github.com/user-attachments/assets/50565c3f-c157-450f-b44c-f99bb02f20dd)
![image](https://github.com/user-attachments/assets/fb54dcdc-3cf9-40bc-bee9-94658266cea1)

**Database links:**
https://www.wowhead.com/wotlk/guide/argent-tournament/quests-dailies#champion

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
