### ISSUE TITLE
[Mob] Voidwalker Minion

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#254]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
The voidwalkers summoned by Wastewander Shadow Mages in Tanaris are passive and don't attack the player even if aggroed

https://youtu.be/KCWIQS4lhqE

**Comment by UltraNix** [comment]
Fixed.
