### ISSUE TITLE
[Onyxia] Onyxian Warder has incorrect skinning table

### ISSUE THREAD

**Issue by roblox-oof-dot-mp3** [gamefreedomgit/Frostmourne#2541]
**Description:**
During our Onyxia run last week, the trash on the way looked like it may have the incorrect loot table. Every single skin was giving 1-2 rugged leather when they're supposed to give up to 19. I can't connect to the PTR to confirm, but it seemed like they have the table of a normal 50-60 mob.

**How to reproduce:**
Skin Onyxian Warder's

**How it should work:**
Follows the loot table on WoWHead

**Database links:**
https://www.wowhead.com/wotlk/npc=12129/onyxian-warder#skinning;mode:n10

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
