### ISSUE TITLE
Argent Tournament Quartermaster is missing

### ISSUE THREAD

**Issue by roblox-oof-dot-mp3** [gamefreedomgit/Frostmourne#2543]
**Description:**
Hiren Loresong, Quartermaster for the Silver Covenant, is missing currently. Not sure about Horde counterpart.

**How to reproduce:**
Go inside their tent in the tournament grounds. Observe his lack of presence.

**How it should work:**
Corporeal

**Database links:**
https://www.wowhead.com/wotlk/npc=34881/hiren-loresong#comments

**Comment by Riztazz** [comment]
Fixed in another commit by @Piootrek
