### ISSUE TITLE
[Trial of the Champion] Faction Champion's are meleeing while mounted

### ISSUE THREAD

**Issue by roblox-oof-dot-mp3** [gamefreedomgit/Frostmourne#2544]
**Description:**
Currently the faction champions are able to use melee attacks while on their mounts. This is making the first half of the event nearly impossible since they're able to do more than twice the damage they're supposed to do.
![image](https://github.com/user-attachments/assets/459df807-3ec6-4861-bcb4-32688c61b3bf)

Additionally, it appears as if they have no cooldown on their abilities. They are able to charge and refresh their armor repeatedly.

**How it should work:**
Faction champions can't melee while using a vehicle, the same as the player.

**Database links:**

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
