### ISSUE TITLE
Emblem of Ascension II vendor won't refund

### ISSUE THREAD

**Issue by Furiianda** [gamefreedomgit/Frostmourne#2545]
**Description:**
Items purchased from the Ascension 2 vendor cannot be refunded.

**How to reproduce:**
Buy an item, sell it back

**How it should work:**
Items should be eligible for refund within the 2-hour Emblem refund timeframe.

**Database links:**
N/A

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
