### ISSUE TITLE
ToC10 normal loot drops 25m patterns

### ISSUE THREAD

**Issue by Furiianda** [gamefreedomgit/Frostmourne#2546]
**Description:**
Trial of the Crusader on 10 normal mode drops patterns from 25man.

**How to reproduce:**
Kill lots of bosses :)

**How it should work:**
This is up to you, I'm not sure if it's intended or not.

**Database links:**
https://www.wowhead.com/wotlk/zone=4722/trial-of-the-crusader#drops;mode:n10

**Comment by Piootrek** [comment]
Do you have any screenshot that recipe dropped for 10man? I don't see any patterns in the loot tables.
