### ISSUE TITLE
[togc25] invisible slime pool not removed after wipe on 1st boss

### ISSUE THREAD

**Issue by scrublama** [gamefreedomgit/Frostmourne#2548]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
https://www.twitch.tv/dysbanded/clip/EvilSeductiveKangarooDxCat-AR2Bgm37SxAs-lY8

**How to reproduce:**
wipe on 1st boss worms with slime pools, enter after wipe and take dmg from slime pool thats also invisible

**How it should work:**
remove slime pool after wipe

**Database links:**

**Comment by Riztazz** [comment]
Fixed, will close once it's live

**Comment by oneadanut** [comment]
@Riztazz still not fixed.
