### ISSUE TITLE
Explosive Decoy damages players in Dalaran

### ISSUE THREAD

**Issue by Furiianda** [gamefreedomgit/Frostmourne#2549]
**Description:**
The Explosive Decoy damages opposite faction members in a sanctuary area of Dalaran (witnessed at south-side/alliance-side bank).

**How to reproduce:**
Place explosive decoy next to low level character to one shot them :) 

**How it should work:**
Player AoE spells or items shouldn't damage other players in a sanctuary area

**Database links:**
https://www.wowhead.com/wotlk/item=40536/explosive-decoy
![explosive_dummy](https://github.com/user-attachments/assets/6ea67445-4617-49b9-bad7-c167f2907faa)

**Comment by Riztazz** [comment]
fixed, will close once it's live
