### ISSUE TITLE
Ignite Munching

### ISSUE THREAD

**Issue by Enhatest** [gamefreedomgit/Frostmourne#255]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Dot munching is a bug that was present in original woltk that happened when two fire mage spells critted at the same time resulting in the ignite from the crit only being from one of them loosing them dps.
This was later fixed in classic and aparently on warmane but couldn't find a source on that.
https://www.wowhead.com/blue-tracker/topic/eu/wrath-classic-patch-3-4-2-update-notes-may-11-446339

**How to reproduce:**
Cast a fireball followed by an instat pyroblast and get them to both hit at the same time and crit it will results in lower ignite damage than expected.
Example: Here I crit for 5856 on my fireball and 6616 on my pyroblast both hit at the same time the expected Ignite damage should be (5856x0.4)+(6616x0.4) = 4988 intead the ignite damage is 2646 meaning it only took the pyroblast 6616 crit into account for the ignite damage
![image](https://github.com/gamefreedomgit/Frostmourne/assets/158791547/95c37803-b9cd-459a-b84d-db0a12d2c2f9)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/158791547/dbce392b-bae4-4f32-9104-4d385730aff1)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/158791547/fc82d829-5ca6-4b6d-b52f-9fa286a34137)

**How it should work:**
Each crit should add damage to the ignite

**Database links:**
https://www.wowhead.com/blue-tracker/topic/eu/wrath-classic-patch-3-4-2-update-notes-may-11-446339 (woltk classic fix)

**Comment by UltraNix** [comment]
If it was a bug on original wotlk, then we stay with that.
