### ISSUE TITLE
Multiple valanyr users absorbs not stacking

### ISSUE THREAD

**Issue by Joskanso** [gamefreedomgit/Frostmourne#2550]
**Description:**
When multiple healers with valanyr heal a target with the weapon procced at the same time only one of the healers heals is adding to the absorb on the target.

**How to reproduce:**
Get 2 healers with valanyr to proc weapon, both heal a target. Only the the healer who triggered the absorb first can stack it. Any additional heals from any other healer does not stack the absorb.

**How it should work:**
If healer one does 30k healing and healer two does 20k healing, that should add to 7,500 absorb.
What happens is only the first healers heals are counted, so the 30k, making the absorb 4,500.

Tested it and did 75k healing and other healer did 50k healing, Healing meter states only 11k absorb but should have been 18k. Absorb was fully utilised and tested multiple times. Always same outcome.

[Blue post stating multiple healers heals should stack absorb](https://www.bluetracker.gg/wow/topic/us-en/16903512910-valrsquoanyr-hammer-of-the-ancient-kings/)

**Comment by Riztazz** [comment]
I did some testing and i cannot reproduce this.
![image](https://github.com/user-attachments/assets/151471d0-cae2-4358-a66f-815d9441fe60)
Bubble is properly bumped as long as the other healer user also has the hammer. Someone who doesn't have a hammer won't bump the shield

**Comment by broizter** [comment]
> It was mostly an issue regarding addons such as details and skada, from our testings at least, valanyr's shield proc portion gets credited to the first healer that has the shield buff on the target. But afaik the proc is working as intended.

there is no api in 3.3.5 that addons can use to reliably tell who's absorb got used, so addons like skada and details do their own priority to "guess" what absorb got used.
