### ISSUE TITLE
Burning Bile ticks evade after bosses die

### ISSUE THREAD

**Issue by yeagerca** [gamefreedomgit/Frostmourne#2551]
**Description:**
After Dreadscale dies any existing Burning Bile debuffs cause "evade" damage. This means you cannot use it to clear Paralytic Toxin from allies. Both bosses were dead when I experienced this bug.

**How to reproduce:**
Obtain the burning bile debuff from Dreadscale, Kill Dreadscale, then stand near an ally.

**How it should work:**
Burning bile should continue to successfully do damage to nearby allies and clear paralytic toxin off of them.

**Database links:**
https://www.wowhead.com/wotlk/npc=34799/dreadscale
https://www.wowhead.com/wotlk/spell=66869/burning-bile
https://www.wowhead.com/wotlk/spell=66823/paralytic-toxin

**Comment by Riztazz** [comment]
fixed, will close once it's live
