### ISSUE TITLE
Jaraxus TOGC10 HC/Ascended

### ISSUE THREAD

**Issue by wotlkenjoyer** [gamefreedomgit/Frostmourne#2553]
![image](https://github.com/user-attachments/assets/0db76718-2db5-4b21-ac1b-e38275eb6e4f)

You can see on the screenshot , the same person in 2 seconds  got Touch of Jaraxus (new debuff) which does 35k damage undispellable
Legion flames that does damage by itself even if you very good at kiting it.
And what killed him  mistress grabbed him and threw to the ground (in to legion flames  fire)  it can't be showed in logs tho. 

But simply  every attempt we were loosing 1-2 people because of this bad rng debuff stacking.
Even if you do everything perfectly, at some point someone getting Legion flames + Touch of jaraxus, and this is already around 50k damage taken undispellable,  and even then  he still can be targeted by misstress which should not be happening, legion flames targets never been a target for misstress hug.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
