### ISSUE TITLE
TOGC: Icehowl Massive Crash

### ISSUE THREAD

**Issue by Aitirn** [gamefreedomgit/Frostmourne#2554]
**Description:**

Massive Crash on Icehowl is sometimes being delayed instead of casting on time, which at the end causes you to have a random amount of Crashes before the boss enrages, as it is supposed to be (Boosted Version of Frosthold). You should be having 3 charges, and the boss enrages once the third charge hits the wall and gets stunned. Over here, it's randomly every pull; sometimes you get 2 charges, sometimes you get 3 charges, all about if the massive crash is being delayed or not.

**How to reproduce:**

Pull the Boss, wait for the Enrage and count the Charges you had, try it few times and you will see.

**How it should work:**

Massive Crash should be always casting on exact time, so you can have 3 Charges before Enrage always.

Proof:

https://www.twitch.tv/videos/2318518445 You can Scroll around and Check, Pull at 26:00 - 2 charges Enrage, Pull at 47:00 3 charges (third Crash hit) > Enrage

**Comment by broizter** [comment]
This is also why its impossible to make accurate DBM timers for Icehowl. Would be great if fixed.
