### ISSUE TITLE
Horde item not "transforming" to alliance's equivalent.

### ISSUE THREAD

**Issue by LePeniche** [gamefreedomgit/Frostmourne#2558]
Hello, today I purchased an item in the AH, it's a blacksmithing item "Titanium Spikeguards", and i'm an Human. The item says that it is indeed horde only, but I read online that it should transform to the alliance's equivalent if it's in my inventory. Print annexed.

![image](https://github.com/user-attachments/assets/0e32716c-b86e-4cd0-b486-8bba7b10a376)

When I try to equip the item it says this:

![image](https://github.com/user-attachments/assets/b768cad7-d572-4be1-ae12-b3ade3309255)

here's a link to the item in wowhead : https://www.wowhead.com/wotlk/item=47573/titanium-spikeguards
"This item will be converted to [Titanium Spikeguards](https://www.wowhead.com/wotlk/item=47572/titanium-spikeguards) if you transfer to Alliance." 

thanks in advance! :)

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live. Now the item should be changed after you relog.
