### ISSUE TITLE
ToC 5man dungeon Ascended Difficulty two problems in one report

### ISSUE THREAD

**Issue by Darkej** [gamefreedomgit/Frostmourne#2561]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
ToC does not drop any ulduar items, only HC item drops, 
Last boss "The Black Knight" have Ascended buff only when in DK form, when in skeleton and ghost form he does not have the buff.
**How to reproduce:**
i joined andom ascended dungeon and got ToC, no clue if it need to be random

**How it should work:**
From what i understand all Ascended dungeons drop bonus ulduar item 10 man tier while last boss drops 25 man tier. There was no ulduar items. Last boss did not drop Emblem of Holy Ascension, but i did get the 3 tokens reward for daily dungeon.
Second part: Last boss did not have Ascended buff while his zombies had it.

**Database links:**

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
