### ISSUE TITLE
TOGC 10: Faction Champions

### ISSUE THREAD

**Issue by Aitirn** [gamefreedomgit/Frostmourne#2563]
**Description:**

Faction Champions on 10 man Heroic (New Spec Bosses and Boosted abilities like, Death and Decay, Consecration, and so on) are doing pretty much the same Damage as on 25 man Heroic, which in every way possible is wrong.

**How to reproduce:**

Pull both of them, check the damage of the bosses with New Spec / new abilities

**How it should work:**

Well, Pretty much sure the damage on 10HC and 25HC shouldnt be the same?

**Database links:**
Example:
25 Man Heroic BM Hunter:

![image](https://github.com/user-attachments/assets/21895817-f37d-4384-9e1a-50d29c5a853b)

10 Man Heroic BM Hunter:

![image1](https://github.com/user-attachments/assets/dec258d1-7814-4350-b62f-7cefaa836e5c)

**Comment by Piootrek** [comment]
Fixed by Afgann.
