### ISSUE TITLE
TOC5 normal bugged and wont start

### ISSUE THREAD

**Issue by Gajoel14** [gamefreedomgit/Frostmourne#2564]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Event wont start so cant do the dungeon. The doors open but the mobs dont come out. 

**How to reproduce:**
Start the event

**How it should work:**
Mobs should come out

**Database links:**

**Comment by KryndorX** [comment]
i want to add that even if you reset the npc using a GM respawn , yes you will be able to speak to the NPC but the first option will spawn the adds behind the gate and they won't engage, only the 2nd skip option will spawn them.

**Comment by Gajoel14** [comment]
When is the next server update?
