### ISSUE TITLE
TOc+TOGC25 Anub bugs

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#2566]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
1. Sometimes when taking a freezing slash, tank cannot move his character permanently until relog

2. Frost patches don't break both on heroic 25 and heroic 10man, did not test normals

3. On 25nm anub phases at 40% hp(should be 30 on nm) like on ascended custom difficulty, meaning the custom stuff leaked into normal, meaning there's probably more stuff like this on other bosses as well

**Comment by crabcakeowo** [comment]
Might have to do with switching difficulty, for anub phasing hp because it was perfectly fine during a full 25nm raid, boss phased at 30%.

**Comment by Aitirn** [comment]
only if you switch from HC to Normal Anub start on 40%, it was same with Faction HC, if you switch to normal u still get HC champs, Frost Spheres are fixed already

**Comment by sputnikk** [comment]
yep you guys are probably right since we did swap from HC to NM. Probably what is causing 3.

**Comment by Piootrek** [comment]
1. I cannot reproduce it, do you have any video of this issue?
2. Already fixed
3. Fixed
