### ISSUE TITLE
[Quest item] Head of onyxia not repeatable quest

### ISSUE THREAD

**Issue by scrublama** [gamefreedomgit/Frostmourne#2567]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I turned in head of onyxia and got dps neck, now 2nd one I need avoidance trinket but already on that quest it says.

**How to reproduce:**

**How it should work:**
make it repeatable

**Database links:**

**Comment by scrublama** [comment]
@RadeghostWM approve

**Comment by RadeghostWM** [comment]
Nope, that's how it's supposed to be.

**Comment by scrublama** [comment]
Well then there are still ways to get 2 of the items from horde and ally with faction change that’s blizzlike. Is that how you like us to play? @RadeghostWM
