### ISSUE TITLE
The Glaive Set Buffs "Shallow/Moderate/Deep Insight" which Increase Damage by 3/6/10% do not increase Rupture damage.

### ISSUE THREAD

**Issue by Tetrahydrx** [gamefreedomgit/Frostmourne#2568]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The Glaive Set Buffs "Shallow/Moderate/Deep Insight" which Increase Damage by 3/6/10% do not increase Rupture damage. 

**How to reproduce:**
Do a five combo point Rupture on a Target (Mage sure no Attackpower procs are pending) without the Glaive buff, and repeat with the "Deep Insight(10% dmg)" Buff - the value of the Rupture ticks stay the same.

**How it should work:**
Rupture should be snapshottable, the tricks buff for example does increase Rupture damage.

**Database links:**

**Comment by Piootrek** [comment]
Fixed by Afgann
