### ISSUE TITLE
[TOGC 25] Nether Power refreshing on spellsteal

### ISSUE THREAD

**Issue by crabcakeowo** [gamefreedomgit/Frostmourne#2569]
**Description:**
Nether Power is currently refreshing its duration when a mage spellsteals it, allowing for degenerate gameplay of having mage stacking up to 10 stacks granting a 200% bonus damage buff with almost no repercussions throughout the entire encounter.

**How to reproduce:**
Get a mage, use spellsteal on Jaraxxus's nether power at the start of the mechanic and wait for buff to nearly wear off before spellstealing again. 

**How it should work:**
Spellstealing the buff should grant https://www.wowhead.com/wotlk/spell=66228/nether-power and not refresh its duration on subsequent stacks.

**Database links:**
https://www.youtube.com/watch?v=7SJijuhsbbs - Timestamp 0:28 - 0:35
https://www.wowhead.com/wotlk/spell=66228/nether-power
https://www.wowhead.com/wotlk/spell=67009/nether-power

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
