### ISSUE TITLE
[Obsidian Sanctum] Pyrobuffet hitting players on boss platform and inside portals

### ISSUE THREAD

**Issue by oomshroom** [gamefreedomgit/Frostmourne#257]
**Description:**
Sartharion casts his Pyrobuffet spell on targets he shouldn't cast it on:
ALWAYS casts it on players inside portals
SOMETIMES casts it on players outside -- I've been Pyrobuffeted while standing in the middle of the platform and not doing anything funny, but it is not common (few bad casts per fight).

**How to reproduce:**

**How it should work:**
Pyrobuffet should only be cast on targets outside the boss platform, and not players inside portals.

**Database links:**

**Comment by Afgann** [comment]
fixed
