### ISSUE TITLE
Quest : On Ruby Wings

### ISSUE THREAD

**Issue by Amine-x-x** [gamefreedomgit/Frostmourne#2571]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
After you kill the Giant(thaiassi the lightning bringer) the NPC (Grand Necrolord Antiok) doesn't instantly remove his immunity shield sometimes he doesn't remove it at all
**How to reproduce:**

**How it should work:**
Shield must be removed instantly , and the chance of it not being removed must be fixed

**Database links:**
https://www.wowhead.com/wotlk/quest=12498/on-ruby-wings

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
