### ISSUE TITLE
Leather Armor Mearchant - Dalaran - Refund Not Working on some items

### ISSUE THREAD

**Issue by Estez5010** [gamefreedomgit/Frostmourne#2572]
**Description:**

Some of the items purchased from the vendor " Rafael Langrom " the Leather Armor merchant in dalaran - are not refundable.

I purchased Runetotem's Spaulders of Conquest and refunded them , while Runetotem's Handguards of conquest cannot be refunded

**How to reproduce:**
But an item / refund an item

**How it should work:**
Items should be eligible for refund within the 2-hour Emblem refund timeframe.

**Database links:**
N/A

**Comment by Piootrek** [comment]
This item already has refundable flag.
