### ISSUE TITLE
[NPC]Xabraxxis – Missing emote on spawn

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2573]
[Xabraxxis](https://www.wowhead.com/wotlk/npc=10373/) should yell when he is spawned by the player.

Xabraxxis yells: What the... nobody cleanses a furbolg in MY camp! Face the wrath of Xabraxxis!

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
