### ISSUE TITLE
[Quest] Escape Through Stealth – no stealth, long walk

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2574]
After player completes [A Lost Master](https://www.wowhead.com/wotlk/quest=993/a-lost-master), he can choose to etiher [Escape Through Force](https://www.wowhead.com/wotlk/quest=994/escape-through-force) or to [Escape Through Stealth](https://www.wowhead.com/wotlk/quest=995/escape-through-stealth).

Escape Through Stealth is absolutely the same as through Force.
[Volcor](https://www.wowhead.com/wotlk/npc=3692/volcor) should go into stealth-cat and quest completion should be awarded few steps out of the cave. However Volcor normally walks through middle of the camp unstealthed, same as he would do in Escape Through Force.

https://www.youtube.com/watch?v=ZQV9tBrnvfE&t=39s&ab_channel=scarything
https://www.wowhead.com/wotlk/quest=995/escape-through-stealth#comments:id=2786231
https://www.wowhead.com/wotlk/quest=995/escape-through-stealth#comments:id=5375549

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
