### ISSUE TITLE
[Quest] Trek to Ashenvale – not offered

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2575]
Quest [Trek to Ashenvale](https://www.wowhead.com/wotlk/quest=990/trek-to-ashenvale) should be offered by [Sentinel Selarin](https://www.wowhead.com/wotlk/npc=3694/sentinel-selarin), an NPC tha spawns after player hands in either [Escape Through Force](https://www.wowhead.com/wotlk/quest=994/escape-through-force) or the [Escape Through Stealth](https://www.wowhead.com/wotlk/quest=995/escape-through-stealth).

NPC does not offer this quest, however this bug was well known also in Vanilla and came back on Classic too. Also she runs away in like 30 seconds after she finishes her interaction with Terenthis. She should stay a bit longer, at least two minutes.
https://www.wowhead.com/wotlk/quest=990/trek-to-ashenvale#comments:id=3153766

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
