### ISSUE TITLE
[Quest] Orendil's Cure – Missing post-completion event

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2577]
Quest [Orendil's Cure](https://www.wowhead.com/wotlk/quest=1020/orendils-cure) is missing its post-completion event, [Pelturas Whitemoon](https://www.wowhead.com/wotlk/npc=3894/pelturas-whitemoon) just bows and that is it.

4:20 https://www.youtube.com/watch?v=yrdvhgswI8E&ab_channel=ClassicRetroGaming
2009 (3.1.3) comment https://www.wowhead.com/wotlk/quest=1020/orendils-cure#comments:id=773874
notes for cata version: https://wowpedia.fandom.com/wiki/Orendil%27s_Cure_(quest)#Notes
According to comment on wowhead, the pre-cata version had the same event, however it was not registered in pre-cata version of the quest on wowpedia.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
