### ISSUE TITLE
[Paladin] Lay on Hands

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#258]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Lay on Hands' cooldown is not being reset after every boss kill/wipe

**How to reproduce:**
Use LoH, kill a dungeon boss, cooldown won't reset

**Comment by Afgann** [comment]
fixed
