### ISSUE TITLE
Trial of the Crusader. Cobolts

### ISSUE THREAD

**Issue by Darkej** [gamefreedomgit/Frostmourne#2582]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Trial of the Crusader, Encounter "The Beasts of Northrend", Boss "Gormok the Implater", add "Snobold Vassal" 
The add does get hit by Fury Warrior ability Whirlwind, Cleave works fine.

**How to reproduce:**
Play warrior, use Whirlwind near cobold 

**How it should work:**
Cobold should take damage from whirlind

**Database links:**

**Comment by scrublama** [comment]
In classic atleast it worked the same way, if you wanna cleave you gotta target the kobolds then cleave/whirlwind/blade flurry etc

**Comment by Godmatik** [comment]
It's intended, most AoEs don't work on the kobolds

**Comment by Riztazz** [comment]
Intended and recently fixed to said behavior
