### ISSUE TITLE
ToC Faction Champions 25m Heroic - The enemy comp can be changed by swapping difficulty

### ISSUE THREAD

**Issue by broizter** [gamefreedomgit/Frostmourne#2585]
![bild](https://github.com/user-attachments/assets/e6d6e612-2881-43c4-80c9-fbd34f68faf7)
The comp for faction champions should be set and rotated weekly, but currently you can force a new comp by swapping difficulty to normal and then back to heroic.

First heroic comp:
![bild](https://github.com/user-attachments/assets/a019b42a-c969-4174-a17a-63054ab836ca)

Second comp after swapping to normal and back to heroic:
![bild](https://github.com/user-attachments/assets/048e8879-82a9-4ea7-87e2-84ab5d58591c)

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
