### ISSUE TITLE
ToC Lord Jaraxxus 25m Heroic - Portal and volcano spawn are not on a set timer

### ISSUE THREAD

**Issue by broizter** [gamefreedomgit/Frostmourne#2586]
"IN-FER-NO!" is the yell he does when he spawns a volcano, so here are examples from two different pulls, once where he used it 90 seconds after pull, and another time when he used it 95 seconds after pull. Same thing can be observed with the portal spawn. 

From what I can tell every time he uses Nether Power he will delay the next portal and volcano by 5 seconds, so depending on how many times he uses that ability the timer can end up being different.

![bild](https://github.com/user-attachments/assets/e3ecf5ac-e517-4072-9d9f-a3f6f43ce180)
![bild](https://github.com/user-attachments/assets/9ca7582a-3c55-4ea5-8c74-e28b392ef598)

How it "should work":
![bild](https://github.com/user-attachments/assets/9434a75f-82ea-4448-abe7-9d70f4e2574b)
![bild](https://github.com/user-attachments/assets/18d3f95b-d7ce-4a98-987a-3bd101f5ee9d)

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by broizter** [comment]
> Fixed, I will close this issue once the fix comes live.

I was planning to release a new version of DBM today, but the test realm is closed so I can't test these changes. Would you mind sharing the new portal and volcano timers? Currently portal happens 20 second and volcano 90 seconds after pull, and then both abilities have a 140 second cooldown (give or take 5-10 seconds because of the randomness that existed before).

**Comment by Piootrek** [comment]
Should be same as from wowiki screenshot. 
Nether Portal - 20s after pull and every 2 minutes after that
Volcano - 80s after pull and every 2 minutes after that
Also removed 5s delay from Nether Power

**Comment by broizter** [comment]
> Should be same as from wowiki screenshot. Nether Portal - 20s after pull and every 2 minutes after that Volcano - 80s after pull and every 2 minutes after that Also removed 5s delay from Nether Power

Great, thank you!
