### ISSUE TITLE
scarab lord

### ISSUE THREAD

**Issue by lordtunderrin** [gamefreedomgit/Frostmourne#2587]
Description:
Upon completing the Scarab Lord questline, I acquired the Scepter of the Shifting Sands. However, when attempting to interact with the gong in Silithus to bang it, there was no cogwheel cursor, and the gong was not interactable. This appears to be a bug related to the server's progression state. According to Wrath of the Lich King mechanics on private servers, the Scarab Lord questline should only be completable and the gong interactable once the Trial of the Crusader phase is released with Onyxia's Lair, as Onyxia is required to obtain Draconic for Dummies - Chapter VI, which is essential to progress in the questline.

How to reproduce:

1. Progress through and complete the Scarab Lord questline after the released patch of Onyxia's Lair (Phase 3).
2. Obtain the Scepter of the Shifting Sands.
3. Go to Silithus and attempt to interact with the gong.
4. Notice that the gong is not interactable, and no cogwheel cursor appears.

How it should work:

The gong should only be interactable after the server enters Phase 3 (Onyxia's Lair release) because that is when Onyxia is available to drop Draconic for Dummies - Chapter VI. This phase unlocks the remaining steps of the Scarab Lord questline, allowing the player to bang the gong and complete the event.

Database links:

Scepter of the Shifting Sands questline: https://www.wowhead.com/classic/guide/scepter-of-the-shifting-sands-scarab-lord-legendary-mount
Draconic for Dummies - Chapter VI: https://www.wowhead.com/wotlk/item=21108/draconic-for-dummies
Onyxia's loot table during WotLK: https://www.wowhead.com/wotlk/npc=10184/onyxia

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
