### ISSUE TITLE
[Feature request] ToC Encounter Frame on bosses

### ISSUE THREAD

**Issue by query-wow** [gamefreedomgit/Frostmourne#2589]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
In TOC none of the bosses have encounter frames. I've tried to find videos to find if it was a bug  because i'm so used to there being a frame but it doesn't seem like it so, I'm making it a feature request.
It's especially annoying for classes that multi dot or that want to target adds and want to get back on the boss quickly
Can the game designers consider adding the encounter frame to the bosses? This obviously won't really work for faction champions due to the fact that there are more than 2 bosses. 

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Piootrek** [comment]
@RadeghostWM

**Comment by RadeghostWM** [comment]
Let's add it @Piootrek

**Comment by Piootrek** [comment]
Done, I will close this issue once the fix comes live.
