### ISSUE TITLE
[Death Knight] Dk's gargoyle shouldnt have gcd for casts.

### ISSUE THREAD

**Issue by jmaguero94** [gamefreedomgit/Frostmourne#259]
Description: This bug have 0 proofs: https://github.com/gamefreedomgit/Frostmourne/issues/119

How to reproduce: Just use the pre-raid items on dual wield UH dk and repeat the rotation they do in raids.

How it should work: Gargoyle shouldnt have a GCD of 1 second per cast.

Database links: https://wotlk.evowow.com/?spell=49206

**Comment by jmaguero94** [comment]
Proofs:
![image](https://github.com/gamefreedomgit/Frostmourne/assets/42656617/567b99e8-50b1-4c5a-960f-a549f4cb8687)

**Comment by RadeghostWM** [comment]
3.3.5a is different than wotlkC

**Comment by Manpower99** [comment]
> 3.3.5a is different than wotlkC

Yes and there is enough proof that a gcd shouldn't exist in 3.3.5a
