### ISSUE TITLE
Arctic fur

### ISSUE THREAD

**Issue by Amine-x-x** [gamefreedomgit/Frostmourne#2590]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The npc in dalaran (Braeg Stoutbeard <Fur & Leather Trader>) doesn't sell arctic fur.

**How to reproduce:**

**How it should work:**
must sell arctic fur for x10 heavy borean leather.

**Database links:**
Everything he sell : https://www.wowhead.com/wotlk/npc=32515/braeg-stoutbeard

**Comment by Aitirn** [comment]
It is coming out on next patch, that's with ICC.
