### ISSUE TITLE
[Quest] Bodyguard for Hire - always fails mid-way 

### ISSUE THREAD

**Issue by Iconostasis** [gamefreedomgit/Frostmourne#2591]
**Description:** The quest is operational in terms of start point, NPC movement, fight spawns and end point. The problem is that the quest fails on its own while at the middle of the escort route. Check the next section for details.

**How to reproduce:**
> Start 00:00
>> First fight starts around 00:45 into the escort
>>> First fight ends around 01:15 into the escort (in my case)
>>>> Second fight starts around 02:05 into the escort (in my case)
>>>>> Second fight ends around 02:47 into the escort (in my case)
>>>>>> Third fight starts around 03:46 into the escort (in my case)
>>>>>>> Third fight ends around 04:26 into the escort (in my case)
>>>>>>>> Leader of the caravan ([Cork Gizelton](https://www.wowhead.com/wotlk/npc=11625/cork-gizelton)) keeps walking and at around 04:50 all the other NPCs ([Rigger Gizelton](https://www.wowhead.com/wotlk/npc=11626/rigger-gizelton) and 2 x [Gizelton Caravan Kodo](https://www.wowhead.com/wotlk/npc=11564/gizelton-caravan-kodo)) just either teleport to or respawn at the leader's location, at Cork's location. Might as well be a summon. I don't know what script is used for that, but it's something to prevent the rest of the caravan from falling too far behind and causing a quest failure. The problem is - when they teleport/respawn/summon it doesn't prevent failure - it causes it.

**How it should work:** The caravan participants (anyone other than Cork) should run to the leader to catch up. Quest failure should only be caused by failing to stay close to the leader (not sure what the range is, probably 45 or 60 yards). When all the fights are over the quest should complete and the caravan can continue on their way to the end point. The character can safely leave and hand in at [Smeed Scrabblescrew](https://www.wowhead.com/wotlk/npc=11596/smeed-scrabblescrew).

**Proposed solution:** (1) Keep the script, just modify the complete condition. It's probably down as fail instead of complete now. (2) Remove the script, make a new script for the NPCs to run to leader & modify complete conditions. It's probably down as fail instead of complete now. (3) Auto-complete on accept to save everyone trouble.

**Database links:**

https://www.wowhead.com/wotlk/quest=5821/bodyguard-for-hire

P.S. The quest that goes in the other direction of the escort route fails in the same way - script for catch up > fail. Here it is:

https://www.wowhead.com/wotlk/quest=5943/gizelton-caravan

Something has previously been done to these two quests in - https://github.com/gamefreedomgit/Frostmourne/issues/2261 - on Nov 7 2024.

**Comment by Iconostasis** [comment]
Sorry for spamming, got to thinking about it and I'm guessing a super easy fix would be to script the completion of the quest to happen before the other script pulls the NPCs to the leader, because that other script that pulls them could be intended to respawn them after the quest has failed/completed, so they can continue on their march to the end of the route. That is supposed to be finalized without the help of the character.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by Iconostasis** [comment]
@Piootrek , sorry to trouble you - the other escort quest from the same caravan is still bugged:

https://www.wowhead.com/wotlk/quest=5943/gizelton-caravan

**Comment by Piootrek** [comment]
> @Piootrek , sorry to trouble you - the other escort quest from the same caravan is still bugged:
> 
> https://www.wowhead.com/wotlk/quest=5943/gizelton-caravan
> 
> Just tested the Bodyguard escort and that one works like a charm.

What's wrong with this quest? Works correctly for me

**Comment by Iconostasis** [comment]
I've done both quests after the hotfix went into production and the server was restarted.

[Bodyguard for Hire](https://www.wowhead.com/wotlk/quest=5821/bodyguard-for-hire) completed fine, you've done a great job with it.
[Gizelton Caravan](https://www.wowhead.com/wotlk/quest=5943/gizelton-caravan), on the other hand, had the same issue as before the hotfix and failed after the fights ended.

I've had help from a GM to complete the quest for me so I can no longer test.
