### ISSUE TITLE
[DB/Gameobject] Ooze Covered Veins and Deposits XP

### ISSUE THREAD

**Issue by Iconostasis** [gamefreedomgit/Frostmourne#2592]
**Description:** There are some mine veins and deposits in the Classic section of the game that do not award XP when mined. Check database links.

**How to reproduce:** Simply mine the linked objects at any appropriate for the vein/deposit XP level.

**How it should work:** XP should be gained.

**Database links:**
[Ooze Covered Silver Vein](https://www.wowhead.com/wotlk/object=73940/ooze-covered-silver-vein)
[Ooze Covered Gold Vein](https://www.wowhead.com/wotlk/object=73941/ooze-covered-gold-vein)
[Ooze Covered Mithril Deposit](https://www.wowhead.com/wotlk/object=123310/ooze-covered-mithril-deposit)
[Ooze Covered Truesilver Deposit](https://www.wowhead.com/wotlk/object=123309/ooze-covered-truesilver-deposit)
[Ooze Covered Thorium Vein](https://www.wowhead.com/wotlk/object=123848/ooze-covered-thorium-vein)
[Ooze Covered Rich Thorium Vein](https://www.wowhead.com/wotlk/object=177388/ooze-covered-rich-thorium-vein)

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
