### ISSUE TITLE
Stinky's Escape

### ISSUE THREAD

**Issue by Vaxsysl** [gamefreedomgit/Frostmourne#2594]
**Description:**
The escort mob does not fight. It doesn't matter if he gets into range of enemies or gets attacked, he makes "attacking" sound and does nothing, keeps on going. Gets combat bugged stuck and if we heal him, we get combat bug too. Dangerous for HC chars.

**How to reproduce:**
Start quest and see.

**How it should work:**
He should fight back if provoked...shouldn't he?

**Database links:**
https://www.wowhead.com/wotlk/quest=1270/stinkys-escape
https://www.wowhead.com/wotlk/npc=4880/stinky-ignatz

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
