### ISSUE TITLE
[Quest] Jack Me Some Lumber + A Chip Off the Ulduar Block – should not be available at all

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2596]
I have ignored these quests because I have thought there is enough talk and knowledge about it already. But today I have seen in discord that the issue was resolved wrongly, by adding phased out spawns needed for the quest.

However [Jack Me Some Lumber](https://www.wowhead.com/wotlk/quest=13627/jack-me-some-lumber) should not be available at all. And same goes for [A Chip Off the Ulduar Block](https://www.wowhead.com/wotlk/quest=13681/a-chip-off-the-ulduar-block) They should have been available while we were on Ulduar patch, back then also the trees were visible (not everything from the tournament area should have bee phased out, there are lots of other things that should have been available most likely). However with patch 3.2 and tournament building finished, these quests should not be obtainable anymore (that is also why the trees and stones phased out). 

https://www.wowhead.com/wotlk/quest=13627/jack-me-some-lumber#comments:id=798576
https://wowpedia.fandom.com/wiki/Jack_Me_Some_Lumber
https://www.wowhead.com/wotlk/quest=13681/a-chip-off-the-ulduar-block#comments:id=798577
https://wowpedia.fandom.com/wiki/A_Chip_Off_the_Ulduar_Block

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
