### ISSUE TITLE
[Achievment] Ascended: Second Coming – not awarded

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2597]
Meta achievment for completing all the dungeons on Ascended II was not awarded. I have done them all, only thing I would be missing is some of the champions on ToC, however after gaining achievment for Heroic ToC, there is no achievment listed for killing all bosses on Ascended I or Ascended II so I can only assume ToC Ascended is not part of the meta. Meta achievment itself does not provide list of dungeons/partial achievments needed to complete the meta.

If ToC A2 is needed for Meta, it should have its own achievment. I would be opposed to adding ToC into Meta since players can't que specifically for any ascended dungeons and if they get into ToC there is a chance they will fight their own faction, which does not provide kills for achievment, or if they get the right faction champions, it would still take several runs to kill all the randomly chosen champions.

If ToC A2 is not needed for the meta, then there is some problem and I think that might be tied to this: https://github.com/gamefreedomgit/Frostmourne/issues/2495

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
