### ISSUE TITLE
TOC Recipes still re-ocked for factions

### ISSUE THREAD

**Issue by oXnOi** [gamefreedomgit/Frostmourne#2598]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I have made this post before. about recipes from TOC being faction locked. it got fixed, but now they are faction locked again. 
doing the raid from my main "Allience" trading to my LW-alt "horde", doesnt work. 

**How it should work:**
Should be unlocked for all factions. 
![LW recipes facntion locked 11th december](https://github.com/user-attachments/assets/f1737bee-d914-454e-91ea-ec8f0ac76bf4)

Best regards
- Maffiaff

**Comment by Piootrek** [comment]
It is working correctly for me. Did you try to relog with this item?

**Comment by oXnOi** [comment]
i did that day yes, but it seems to be working now :).
