### ISSUE TITLE
[Ascended Raids] Loot Lockout

### ISSUE THREAD

**Issue by RadeghostWM** [gamefreedomgit/Frostmourne#26]
Killing a boss that drops 25-Man gear, should make your character ineligible for any loot of another version of this boss that also drops 25-Man gear.

Example 1: I have killed Patchwerk on 25-Man. I get invited to a 10-Man Ascended. Patchwerk dies. When it's Group Loot, I cannot roll on item, because the system excludes me. If it's Master Looter, when he tries to give me an item, he would see an error that I am ineligible for this loot (the same thing when they kill a boss, and someone that wasn't present at boss' death comes into raid: he's ineligible for loot).

Example 2: I have killed all bosses on Naxx Ascended, but I killed Kel'Thuzad at Normal (because you can switch Ascended on and off, like you can switch Normal/Heroic on Icecrown Citadel). I go with my guild to Naxxramas 25 and I cannot participate in any loot distribution, because I already am locked to all of these bosses as I have killed them on Ascended; when we kill Kel'Thuzad, I can roll on items like usual, because I have killed him on 10-Normal, not Ascended.

Example 3: Your guild cleared Construct Quarter on 25-Man then raid ended, because one of healers left.
10 people from that raid made Ascended raid because they were butthurt. They cleared Construct Quarter on normal, because if it was Ascended, they couldn't get any gear. Then they cleared Plague Quarter on Ascended. Then guild leader called and you get back to 25-Man. The 10 of you cannot loot any bosses from Plague Quarter and you are butthurt because of this, because you wasted lockout on 10 Ascended and you got worse items. Then you proceed to clear rest of Naxxramas, but raid disbands on Kel'thuzad. Then you and your 10 mates go back to Naxxramas 10, clear everything on Normal, because otherwise you wouldn't get Ascended loot (as you cleared it on 25-Man), and kill Kel'thuzad on Ascended. Then your guild leader calls again and you tell him to go make love to himself, because you are fed up, and locked to Kel'thuzad, and Turning Tide didn't drop.

I'm sorry Afgann. xD

**Comment by Afgann** [comment]
fixed
