### ISSUE TITLE
[Quest] The Thane of Voldrune

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#260]
**Description:**
The dragon vehicule "walks" in the air instead of using a flying animation
The dragon's abilities work properly however

**How to reproduce:**
Mount the dragon vehicule for this quest

**How it should work:**
Dragon fly with flying anim

**Database links:**
https://www.wowhead.com/wotlk/quest=12255/the-thane-of-voldrune

**Comment by Afgann** [comment]
fixed
