### ISSUE TITLE
[Quest] Forsaken Diseases – Missing post-completion event

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#2602]
Quest [Forsaken Diseases](https://www.wowhead.com/wotlk/quest=1011/forsaken-diseases) is missing its post-completion event.

5:30 https://www.youtube.com/watch?v=gRXS6IgtE9Y&ab_channel=Bue

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
