### ISSUE TITLE
Fa-la-la-la-Ogri'la achievement not working,

### ISSUE THREAD

**Issue by Hirosee** [gamefreedomgit/Frostmourne#2603]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Achivement should be done during Winter Veil event that complete Bomb them again daily quest in Blade-edge mountain while on holiday mount reindeer effect, but its not working at the moment

**How to reproduce:**
when complete bomb them again while on holiday reindeer effect, should complete

**How it should work:**
when complete bomb them again while on holiday reindeer effect, should complete

**Database links:**
https://www.wowhead.com/achievement=1282/fa-la-la-la-ogrila

**Comment by Piootrek** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/2496
