### ISSUE TITLE
Mobs in the Nexus are immune to mind control

### ISSUE THREAD

**Issue by roblox-oof-dot-mp3** [gamefreedomgit/Frostmourne#2604]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Older threads indicate berserkers should not be immune to mind control, implying others probably shouldn’t be as well.

https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/311780-spellsteal-mind-control-meta-thread.html

**How it should work:**
Humanoids on all difficulties should be mind controllable and allow use of their abilities.

**Database links:**
List of NPC’s in the nexus: https://www.wowhead.com/zone=4265/the-nexus#npcs

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
