### ISSUE TITLE
Mobs in Trial of the Champion missing abilities when mind controlled 

### ISSUE THREAD

**Issue by roblox-oof-dot-mp3** [gamefreedomgit/Frostmourne#2605]
**Description:**
The mobs spawned before the 2nd boss all have none of their abilities when mind controlled. 

**How to reproduce:**
Mind control mobs before eadric/paletress

**How it should work:**
Mobs have their abilities while MC’d

**Database links:**

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
