### ISSUE TITLE
Savage Combat is stacking with Blood Frenzy when it shouldn't

### ISSUE THREAD

**Issue by crabcakeowo** [gamefreedomgit/Frostmourne#2606]
**Description:**
Savage combat from rogue combat talent tree applies a 4% increase physical damage taken debuff and Blood Frenzy from arms warrior talent tree stacks.

**How to reproduce:**
Have a combat rogue apply poison on a target and an arms warrior applying rend to get both debuffs. Use a 1-2 damage weapon and you will see a noticeable difference in damage.

**How it should work:**
![image](https://github.com/user-attachments/assets/952ac892-73a5-4150-a477-fe6a91e50920)

**Database links:**
https://www.wowhead.com/wotlk/spell=58413/savage-combat#comments

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
