### ISSUE TITLE
T9: Hunter 4 Set

### ISSUE THREAD

**Issue by Aitirn** [gamefreedomgit/Frostmourne#2609]
**Description:** Hunters 4 Set Tier 9 doesn't proc at all, it should have a chance to give 600 attack power on any ranged attack, but it never procs

**How to reproduce:** Go to PTR / Live Realm, get 4 set of Hunter and check it out

**How it should work:** Ranged Attacks should have a chance to give u 600 Attack Power.

**Database links:**

**Comment by crabcakeowo** [comment]
![image](https://github.com/user-attachments/assets/c8826cfd-a8dc-43fa-b22d-09504dd1d833)

**Comment by crabcakeowo** [comment]
don't think the hunter is supposed to get 600 AP because it even says in the set itself that it only grants AP to pets.
![image](https://github.com/user-attachments/assets/1239cfb9-d5ad-40f4-b261-332f9f7fac96)

**Comment by Piootrek** [comment]
It works as the tooltip says, only pet should get attack power.
