### ISSUE TITLE
Culling of Stratholme quest (A Royal Escort)

### ISSUE THREAD

**Issue by Furiianda** [gamefreedomgit/Frostmourne#2611]
**Description:**
Quest progress is paused or fails if not completing the quest in a single run of the dungeon.
According to reports, the quest cannot be restarted (abandoned/retaken) to fix this either.

**How to reproduce:**
Partially complete the quest on one run, then attempt to complete follow-up on a different visit to the dungeon.

**How it should work:**
You should be able to complete this quest even if it's not your first time in the dungeon or you completed Dispelling Illusions(prereq quest) on another run.

**Database links:**
https://www.wowhead.com/wotlk/quest=13151/a-royal-escort

**Comment by Piootrek** [comment]
Fixed, players will be able to start the bridge event after taking this quest.
