### ISSUE TITLE
(TOGC) Lord Jaraxxus: Fel Lightning Syncs Immediately with Empower Stacks in Trial of the Crusader

### ISSUE THREAD

**Issue by nkabrunobarros** [gamefreedomgit/Frostmourne#2612]
**Description:**  
In Trial of the Crusader Heroic (TOGC), during the Lord Jaraxxus encounter, the Fel Lightning ability is incorrectly "syncing" with Empower stacks. Fel Lightning is being cast within 1 second of Lord Jaraxxus gaining stacks, making it almost unavoidable and causing unintentional player damage spikes.

**How to reproduce:**  
1. Engage Lord Jaraxxus in Trial of the Crusader.  
2. Observe the timing between when Lord Jaraxxus gains Empower stacks and when he casts Fel Lightning.  
3. Note that Fel Lightning occurs almost immediately after stacks are applied.  

**How it should work:**  
There should be a noticeable delay between Lord Jaraxxus gaining Empower stacks and casting Fel Lightning, allowing players to react and avoid unnecessary damage.  

**Database links:**  
- [Lord Jaraxxus](https://www.wowhead.com/wotlk/npc=34780/lord-jaraxxus)  
- [Fel Lightning](https://www.wowhead.com/wotlk/spell=66528/fel-lightning)  

**Proof:**  
You can observe the issue in the following Twitch clip:  
https://www.twitch.tv/briunes/clip/TallFairSmoothieDancingBaby-0tzzyrUZKJ1DB-iR
Also Vod's of how it should happen
https://www.youtube.com/watch?v=1p5w_yJiviA&t=61s
https://www.youtube.com/watch?v=fnSq5AqqhKI

**Comment by Riztazz** [comment]
Fixed, will close once it's live

**Comment by wowclassic1234** [comment]
> Fixed, will close once it's live

Is it possible to make this correction take effect today? We have a raid in the guild today and because of this mistake, we will die again at this moment. Because of this, it is essentially impossible to kill the boss. With each attempt, 3 death at once, because of this, there is not enough dps or heal

**Comment by nkabrunobarros** [comment]
> > Fixed, will close once it's live
> 
> Is it possible for this fix to take effect today? Today we will have a raid in the guild, and 3 people will die again because of this mistake. Because of this, it is essentially impossible to kill the boss. With each attempt, 3 deaths occur at once, because of this there is not enough dps or healing

IF WE SUFFURED 2HOURS OF LORD J, U SHALL SUFFER ASWELL!!!
JK :D
pls do fix this

**Comment by wowclassic1234** [comment]
> > > Fixed, will close once it's live
> > 
> > 
> > Is it possible for this fix to take effect today? Today we will have a raid in the guild, and 3 people will die again because of this mistake. Because of this, it is essentially impossible to kill the boss. With each attempt, 3 deaths occur at once, because of this there is not enough dps or healing
> 
> IF WE SUFFURED 2HOURS OF LORD J, U SHALL SUFFER ASWELL!!! JK :D pls do fix this

YES, it would be easy if every class had a BR. It's hard to kill boss like that without battle res.

**Comment by wowclassic1234** [comment]
> Fixed, will close once it's live

please do a reboot server now if this fix has been completed

**Comment by Riztazz** [comment]
I'm not in charge of updating the realm;p
