### ISSUE TITLE
[Dungeon] Trial of the Crusader Ascended 1 - Did not drop two pieces of gear first boss, loot from wrong dungeon

### ISSUE THREAD

**Issue by bigchipbag** [gamefreedomgit/Frostmourne#2613]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Didn't get a screenshot, but we only had a 2H axe (one item) drop from killing the first boss. It was also the 2H axe from Halls of Lightning heroic (which I believe should not be in the loot table )

**How to reproduce:**
Kill first boss and loot

**How it should work:**
It should include ToC heroic items, not HoL heroic, and should drop the ToC gear plus whatever loot table you have for asc1 in ToC

**Database links:**

**Comment by Piootrek** [comment]
Trial of the Champion shouldn't be available on Ascended I difficulty. Removed it from the Dungeon Finder queue.
