### ISSUE TITLE
Fix mob respawn times in low level zones

### ISSUE THREAD

**Issue by Seren79** [gamefreedomgit/Frostmourne#2615]
Per the title, mob spawn times are just plain broken, especially in low level zones. There is no longer any reason for them to be respawning so quickly - the server is pretty much dead and there are very few new players. I pretty much never see other players questing alongside me (which is a shame), so hyper-spawns are just not necessary.

For example: I was just attempting to complete the quest The Night Watch in Duskwood where you kill 20 Plague Spreaders in the cemetery. Every mob in this area, including the green spiders and other ghouls, respawned **less than a minute** after I killed them. There is no time to even restore your health and mana before multiple mobs respawn on top of you. You're in the middle of killing a mob and three of them respawn on top of you. And then when you die, you can't complete the corpse run before every single mob has respawned, meaning you can't safely ress. Similar issues in Redridge with the gnolls, Westfall with Defias but tbh it's every zone and every mob. This is making the game borderline unplayable for me at this point. It's definitely something that has got worse with time, when it should have been sorted months ago.

**How to reproduce:**
Go to any low level zone and start killing mobs. Then go and make a cup of tea. You'll have been killed by the time you get back to your laptop cos all the mobs will have respawned in your brief absence.

**How it should work:**
Mobs should stay dead for a reasonable length of time and not respawn within seconds. You should be able to die and return to your corpse without all the mobs respawning during your 30 second corpse run. You should be able to pause to eat and drink without every single mob you just killed respawning before you finish your bottle of sweet nectar.

**Comment by Seren79** [comment]
Just updating this to say I am experiencing the same issue in Northrend too. Was playing my level 70 toon over the weekend and the mob respawn rate in Borean Tundra is ridiculous. For example: doing the Fizzcrank Airstrip quests around the Scalding Pools is a nightmare because the mobs respawn within seconds. I did not have time to replenish my health or mana before the mobs I had literally just killed began to respawn around me. The mobs are also densely packed and it seems like there are more of them than there should be - in some zones (e.g. Coldarra) there are mobs literally standing on top of each other. It makes questing stressful and not enjoyable. You seem to have programmed this for a player base of thousands and thousands but I'm sorry to say that the population is not currently high enough to justify this - in fact, I am considering going back to Warmane because this is frustrating and not fun (even though I think you guys are generally better). Please be realistic and adjust the mob timer to suit the actual server population.

**Comment by Riztazz** [comment]
fixed
