### ISSUE TITLE
Mobs aggro through floor

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#262]
**Description:**
Mobs social aggro through different floor. Happens on both lower on upper floor from player

**How to reproduce:**
Go to a boat with mobs, aggro a mob on one floor and see mobs from other floors aggroing

**How it should work:**
Shouldn't have such large aggro range on z-axis

**Database links:**

**Comment by Godmatik** [comment]
They aggro through walls as well, like when you are in a house in an open world zone, iirc from classic that should not be possible.

**Comment by Afgann** [comment]
fixed
