### ISSUE TITLE
Zabra's pants of triumph

### ISSUE THREAD

**Issue by KryndorX** [gamefreedomgit/Frostmourne#2620]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The item is a drop from voa and it is for horde

**How to reproduce:**

**How it should work:**
item must swap to alliance's item (velen's pants of triumph) if an alliance receive it

**Database links:**

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
