### ISSUE TITLE
[DB/Spells] Rot of Contagion - Duplicate spell cast

### ISSUE THREAD

**Issue by Iconostasis** [gamefreedomgit/Frostmourne#2622]
**Description:** [Rot of Contagion](https://www.wowhead.com/wotlk/spell=7102/contagion-of-rot) (7102) is supposed to be cast by:

>[Forsaken Herbalist](https://www.wowhead.com/wotlk/npc=3733/forsaken-herbalist)
>[Fetid Corpse](https://www.wowhead.com/wotlk/npc=1270/fetid-corpse)
>[Woodpaw Mongrel](https://www.wowhead.com/wotlk/npc=5249/woodpaw-mongrel)
>[Zanzil Zombie](https://www.wowhead.com/wotlk/npc=1488/zanzil-zombie)
>[Zekkis](https://www.wowhead.com/wotlk/npc=5400/zekkis)
>[Rotting Ghoul](https://www.wowhead.com/wotlk/npc=1793/rotting-ghoul)

Recently a player from Deathwalkers shared that he got affected by both [Rot of Contagion](https://www.wowhead.com/wotlk/spell=7102/contagion-of-rot) (7102) and [Rot of Contagion](https://www.wowhead.com/wotlk/spell=7103/contagion-of-rot) (7103) while fighting a [Zanzil Zombie](https://www.wowhead.com/wotlk/npc=1488/zanzil-zombie) in Stranglethorn Vale, which can be commonly found at the Ruins of Jubuwal at coordinates 35.51 and the Ruins of Aboraz at coordinates 39.58

**How to reproduce:** Let the [Zanzil Zombie](https://www.wowhead.com/wotlk/npc=1488/zanzil-zombie) attack you for a while and you will see it apply both effects to you.

**How it should work:** The mentioned NPCs in the open world should only cast 7102, the other 7103 spell is... well, I'm not sure what it is exactly but its only intended use is inside instances and raids if I have to trust WoWhead.
7103 should not be cast in the open world.

Wowhead comments also say it was used for tests during PTR and it somehow got woven into the official database via the wowhead data collection client while it was running on PTR.

**Database links:** Everything is hyperlinked.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
