### ISSUE TITLE
Vampiric lasts 12 seconds instead of 15 (and 18 instead of 21 with T9 Shadow Priest set bonus)

### ISSUE THREAD

**Issue by gabankhems** [gamefreedomgit/Frostmourne#2624]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

Description:
Vampiric touch is supposed to last 15 seconds after using it on a target, but it only works for 12 (and 18 with the T9 s-priest set bonus)

How to reproduce:
Just use Vampiric touch on any target from level 1 to level 83 with Max rank Spell, and it will display my values.

How it should work:
+3 second on each situation

Database Links:
https://www.wowhead.com/wotlk/spell=48160/vampiric-touch
or
https://wotlk.evowow.com/?spell=34914

1st link is WOTLK Classic
2nd link is WOTLK 3.3.5 (server version)

**Comment by NickZedd** [comment]
It ticks faster with haste. Do you have about 25% haste?

**Comment by Piootrek** [comment]
It works correctly.
