### ISSUE TITLE
Rich Adamantite Deposit does not grant EXP when gathered

### ISSUE THREAD

**Issue by Furiianda** [gamefreedomgit/Frostmourne#2625]
**Description:**
Most mining nodes grant a small EXP bonus, but Rich Adamantite in particular has been reported to not grant any EXP.

**How to reproduce:**
Gather/mine from a Rich Adamantite Deposit

**How it should work:**
Up to you, custom feature :)

**Database links:**
https://www.wowhead.com/wotlk/object=181569/rich-adamantite-deposit
https://www.wowhead.com/wotlk/object=181570/rich-adamantite-deposit

**Comment by Riztazz** [comment]
fixed, will close once it's live
