### ISSUE TITLE
Val'anyr, Hammer of Ancient Kings and Chain Heal interaction

### ISSUE THREAD

**Issue by Tahtoh88** [gamefreedomgit/Frostmourne#2626]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Chain heal isn't spreading valanyr shields on targets with full hp which isn't correct

**How to reproduce:**
use chain heal on a group of full hp people with valanyr proc on 

**How it should work:**
valanyr proc should allow chain heal to jump to targets regardless of their hp ignoring the smart heal factor

**Database links:**
https://www.wowhead.com/wotlk/item=46017/valanyr-hammer-of-ancient-kings
https://www.wowhead.com/wotlk/spell=1064/chain-heal

**Comment by broizter** [comment]
I have noticed that the Valanyr proc is doing pretty low % healing on my resto shaman, but can you include a direct link that shows that its supposed to jump even when targets are full hp with Valanyr?

**Comment by Tahtoh88** [comment]
after further research, i ended up being wrong, there is no mention about chain heal jumping to targets on bluetrackers mmochampion and wowhead. turned out i had the wrong impression

**Comment by Tahtoh88** [comment]
but if this is an occasion to revisit valanyr %healing on resto shaman let it be the case

**Comment by broizter** [comment]
> but if this is an occasion to revisit valanyr %healing on resto shaman let it be the case

I just quickly looked through some classic logs and it seems like it's correct that the % healing for resto shamans is low. Top paladin on Northrend Beasts had twice the amount of Valanyr healing compared to a shaman.
