### ISSUE TITLE
 [Warglaive of Azzinoth]

### ISSUE THREAD

**Issue by Roxface** [gamefreedomgit/Frostmourne#2627]
[Warglaive of Azzinoth]   / [Warglaive of Azzinoth]

**Description:**
 [Warglaive of Azzinoth]  it is bugged
**How to reproduce:**
your Sinister Strike has a 100% but he dont drop the buff 100 % need to do 5 ST for got the buff is that the bug 
**How it should work:**
your Sinister Strike has a 100% chance to grant you and evolving insight damage to that target by up to 10% Opponents can adapt over time negating opponent will begin the cycle anew
**Database links:**

**Comment by Piootrek** [comment]
It works as intended. You get a new buff level every 4th attack.

**Comment by Roxface** [comment]
you want me to record for u to see ?
