### ISSUE TITLE
Anub - extra scarab per burrow phase

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#2628]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Anub scarabs keep spawning after he emerges (1-2 extra add spawns after anub already up)
Observed on 25hc, probably same problem in all difficulties due to how the spell works.

**How to reproduce:**
https://youtube.com/clip/Ugkxs3OgFg9GCQlp0666SN1ZiIOJmQ3D5V4U?si=UDTMEA7qNPtLIdhM
In this clip you can observe a scarab appearing in the back right of the room after anub already emerged from his burrow phase.

**How it should work:**
https://youtu.be/-EWFz94HQWI?si=Vn5zMSgtBDwfuFLI&t=156
as you can see in this video the moment he emerges not a single scarab can spawn anymore

**Database links:**
![sumscarab](https://github.com/user-attachments/assets/cb6233a4-6453-4bb0-905c-023dfd27f590)

This probably happens due to burrow phase lasting 65 second while this spell ticks in the background every 4 seconds. Even if the main spell is cancelled on emerge, the child spell that is being called will still tick after 4 seconds, spawning extra scarab.
The fix is probably just cancelling the main spell 66339 5 seconds before the burrow phase ends to allign the spawn and burrow phases.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.

**Comment by oneadanut** [comment]
In ToGC25, 2 scarabs are still spawning exactly before boss emerges. If you check any video from classic/og, the boss stops spawning scarabs like 5 seconds before emerge. @Piootrek
