### ISSUE TITLE
Trinket : soul preserver

### ISSUE THREAD

**Issue by KryndorX** [gamefreedomgit/Frostmourne#2629]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The trinket doesn't procs for druids at all unless they cast while the trinket suppose to be triggered even from the HOTS.

**How to reproduce:**
druid and spam instant heal of time spells (Reju/Lifebloom/wild growth)

**How it should work:**
the trinket suppose to procs even from hots, the trinket description didn't specify that it has to procs from "cast" beside few comments in the DB link mention that it procs for Heal of time spells.

**Database links:**
https://www.wowhead.com/wotlk/item=37111/soul-preserver

**Comment by Piootrek** [comment]
I didn't find any proofs that should proc off hots. This spell has blizzard attribute to proc from direct spells only.
