### ISSUE TITLE
[Eye of Eternity] Malygos skips Static field casts

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#263]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Malygos sometimes skips casts of Static field in phase 3. 

Tested in 10 man only.
From logs you can see that he casts it approximately at intervals that are multiples of 14, the first cast of 11.47s being an outlier:
"Static Field-57430-npc:28859-774663 = pull:306.12/Stage 3/11.47, 15.40, 42.18, 42.31, 14.08, 28.27, 14.13, 14.12, 14.08", -- [9]

**How to reproduce:**

**How it should work:**
In several videos from retail it seems to be relatively consistent at around 15-22 seconds or so, but most commonly 20+.

**Database links:**
https://www.youtube.com/watch?v=V5K09z05-_4
https://www.wowhead.com/wotlk/spell=57430/static-field#used-by-npc

**Comment by NNassib336** [comment]
He can also cast it right as phase 3 starts. I believe there should be at least a bit of delay, but I have no proof. We may have just gotten unlucky

**Comment by Afgann** [comment]
fixed
