### ISSUE TITLE
Frozo the Renowned Not in Dalaran

### ISSUE THREAD

**Issue by dropjackwow** [gamefreedomgit/Frostmourne#2632]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Frozo the Renowned is supposed to be in Dalaran for the TOC patch, but is not present.

**How to reproduce:**
Walk over to the area of Dalaran where the profession trainers are and you wont see him

**How it should work:**
Walk over to the area of Dalaran where the profession trainers are and you see him

**Database links:**
https://www.bluetracker.gg/wow/topic/eu-en/12680047996-frozen-orbs-in-patch-333/

**Comment by Piootrek** [comment]
The first sentence from your link says "In the upcoming patch 3.3.3". 3.3.3 patch is ICC content.
