### ISSUE TITLE
Dueling in dalaran sewers doesnt reset cds anymore

### ISSUE THREAD

**Issue by scrublama** [gamefreedomgit/Frostmourne#2633]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
some zones used to reset your cds when dueling, as they're common duel zones and duelling vs someone without cds is unfair and waiting 5 minutes to duel is just not what we look for in 2024

**How to reproduce:**
Go dala sewers with a cd active and duel someone and watch it not reset

**How it should work:**
Reset cd on duel start, perhaps check if cd reset on bg enter too while at it

**Database links:**

**Comment by scrublama** [comment]
#2391

**Comment by Piootrek** [comment]
Fixed.
