### ISSUE TITLE
[DB/NPCs] Grey enemies grant XP

### ISSUE THREAD

**Issue by Iconostasis** [gamefreedomgit/Frostmourne#2638]
**Description:** We've had a player from Deathwalkers bring up this issue. A level 17 player fighting a level 11 cat type monster showing as grey has granted them XP for the kill. Then we started playing around with this and most of us tried grey mobs just on the verge of the green/grey label and we all gained XP from the grey mobs. I'm suspecting the NPC coloring might be using a different expansion's color system.

**How to reproduce:** Check [this table](https://wowpedia.fandom.com/wiki/Mob_difficulty_colors) for the level borders for each color and try to fight something that's just the first grey level that shows up compared to yours. I'm not sure how accurate this is, but it's the only reference I could find. Sorry for failing with providing accurate references this time 🙏 

**How it should work:** Grey NPCs should not grant XP upon kill. They should just grant quest completion progress and reputation.

**P.S.** Grey quests should grant a small amount of XP, but full reputation.

**Comment by Piootrek** [comment]
Can you add a screenshot with visible experience for a gray mob? I cannot reproduce this.

**Comment by Iconostasis** [comment]
I can't reproduce it at my current level for a screenshot. At level 60 (my level) XP starts from 52 level enemies, which appears to be working correctly.

Yesterday the thing that made us check was a level 17 Orc Warrior fighting a level 11 [Savannah Huntress](https://www.wowhead.com/wotlk/npc=3415/savannah-huntress) in The Barrens and gaining experience from it.

The Savannah Huntress has a possible spawn level of 11 or 12 and I'm wondering if such spawns grant experience due to the possibility of the spawn level being higher and eligible? Some way the system recognizes the NPC ID and granting XP for it as if it were higher level due to the variation in spawn level. 12 would have been green.

**Comment by Iconostasis** [comment]
Nope, I can't reproduce this no matter what I do. Please excuse me for opening this on someone else's behalf. I'll test personally next time before I start dealing with a bug report.
Let's close it.
