### ISSUE TITLE
DK Scourge Strike(Shadow) Double Diping

### ISSUE THREAD

**Issue by Nylco** [gamefreedomgit/Frostmourne#2646]
[https://www.wowhead.com/wotlk/spell=55090/scourge-strike#modified-by](https://www.wowhead.com/wotlk/spell=55090/scourge-strike#modified-by)

Found some evidences that the Shadow damage portion of this ability should benefit from certain effects (mainly +damage mods)
Certain because while originally after the 3.3.3 redesign it double dipped everything (including crits, as it could separately crit), blizz has fixed/limited the double dips afterwards to prevent the spell being OP. We're still left with a few double dips that were in effect on 3.3.5 and should add to the damage of the ability, which is currently too weak.

In order to reproduce it, simply make uh on test realm and go to the dummies to check the portion of current shadow damage which is often around 40ish% of physical damage which is too low especially in raid enviroment. Almost every Unholy is running DW so the fix of SS to the blizzlike version not classic one could bring 2h build its fromer glory.

Confirmed double dipping effects:

Blood Presence (15%)
Rage of Rivendare (10%)
Desolation (5%)
Two handed specialization (4%)
Bone Shield (2%)
Raidwide 3% damage boost (sanctified retribution/arcane empowerment/ferocious inspiration)

These damage mods will increase the physical damage portion of SS , which indirectly increases the shadow portion and then boost the shadow portion itself, for a doubled effect.
There are also boosts that don't apply to the physical effect but should increase the Shadow damage portion:
Black Ice (10%)
13% magic debuff (ebon plague/curse of elements/earth and moon)

SS will not double dip into effects that will reduce it's damage.

Link to whole double dip mechanic explanation back from 2010:
[https://www.mmopro.org/talent-specs/3333-unholy-dps-pve-3-3-3-a.html](https://www.mmopro.org/talent-specs/3333-unholy-dps-pve-3-3-3-a.html)

Cool and all, but does that explain why the shadow portion of Scourge Strike deals more than the stated 75% of the physical portion?
Yes, it does. Double-dipping is the culprit. After you factor in all of the previously mentioned buffs and talents, you’ll find that the shadow portion will ultimately deal 107.3 % of the physical portion (less partial resists), hence making them near identical, and explaining the almost total lack of gap between the two parts you’ll notice in parses.

Another source that speaks of double dips: 
[https://www.wowhead.com/forums&topic=141587](https://www.wowhead.com/forums&topic=141587)
"Scourge Strike double dips into many talents and buffs/debuffs there is. Many people might wonder why a Blood subspec is superior to Black Ice which buffs the shadow portion of SS by 10%. So let's take a look at what we get by speccing into Blood, that's a total of 14% crit for SS (5% crit on everyting), 2h spec which gives us another 4% (double dips into SS), the static AP from Bladed Armor and some RP through Butchery. "

I`d love to include og warcraftlogs from methods icc back in 2010 but since site is down and im having hard time accesing the info my proof for now is the vid all the way back from March 2010 uh dk on dummy where you can cleary see dude is hiting 2 times with scourge strike with equal some times even bigger 2nd hit(shadow) damage than the physical one without full raid buffs.
[https://www.youtube.com/watch?v=ea3oVeFPWRA](https://www.youtube.com/watch?v=ea3oVeFPWRA)

**Comment by Piootrek** [comment]
I've tested it and it works correctly. First physical damage is increased, shadow damage is calculated based on that damage and on top of that shadow damage is increased by buffs.
