### ISSUE TITLE
[Eye of Eternity] Conc AM interaction with Vortex

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#265]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
When Malygos casts vortex, using aura mastery with concentration aura does not allow you to keep casting, seemingly because characters are being physically moved around the boss, and the camera follows your character.

**How to reproduce:**

**How it should work:**
On retail, and also on Warmane, using conc AM during vortex allows the whole raid to keep casting. An archived 2009 version of the Malygos page on Wowwiki reads: _"Paladins can use [Concentration Aura] together with [Aura Mastery] to continue normal casting while in the air. Of course any casters under the affect of the paladin's aura can also keep on casting non-instant spells as they will not be interrupted."_ Also, the camera remains stationary as the characters are moved, as can be seen in the video.

**Database links:**
https://www.wowhead.com/wotlk/spell=56105/vortex
https://www.wowhead.com/wotlk/spell=19746/concentration-aura
https://youtu.be/V5K09z05-_4?t=122
https://wowwiki-archive.fandom.com/wiki/Malygos_(tactics)?oldid=1870411

**Comment by UltraNix** [comment]
Fixed.
