### ISSUE TITLE
 [[70] Divination: Gorefiend's Armor (10634)]

### ISSUE THREAD

**Issue by MINIGOODWIN** [gamefreedomgit/Frostmourne#2668]
[[70] Divination: Gorefiend's Armor (10634)]

I am trying to do this quest, but the dragon wont show. I have tried everything, and a staff member have too, so now I need some more help.

**Comment by Piootrek** [comment]
You need to equip Spectrectles to see the dragon.

**Comment by MINIGOODWIN** [comment]
I know that, and it still doesn’t work!De bedste hilsnerElea GoodwinOn 27 Dec 2024, at 13.24, Piootrek ***@***.***> wrote:﻿
You need to equip Spectrectles to see the dragon.
