### ISSUE TITLE
**Gamebreaking** Blood of the North talent not converting runes

### ISSUE THREAD

**Issue by Tellatw** [gamefreedomgit/Frostmourne#267]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:** 

DK Frost talent "Blood of the north" doesn't convert blood runes to death runes on use-

**How to reproduce:**

Get blood of the north talent, use blood strike.

**How it should work:**

Blood rune should transform into death rune.

**Database links:**

https://www.wowhead.com/wotlk/spell=54637/blood-of-the-north

**Comment by Afgann** [comment]
fixed
