### ISSUE TITLE
Potential issue with debuffs from BT not clearing properly

### ISSUE THREAD

**Issue by whitemane-lae** [gamefreedomgit/Frostmourne#2675]
I have two 2.6 speed weapons as Enhancement Shaman, [The Grinder](https://www.wowhead.com/wotlk/item=47816/the-grinder) and [Vulmir](https://www.wowhead.com/wotlk/item=45463/vulmir-the-northern-tempest), both enchanted with [Berserking](https://www.wowhead.com/wotlk/spell=59621/enchant-weapon-berserking).

My attack speed is 4.41 on both hands, 666 haste rating and 26.4% haste

<img width="253" alt="image" src="https://github.com/user-attachments/assets/cb66916d-7218-4508-9e94-bf294a5f48ed" />

No GM has been able to explain it but there are three people who were in my BT raid from melee group who had the same debuff.  Neither death, nor logout clears the debuff, and it is not visible on any bar.

Any thoughts or anything else I can provide for investigation?  We think it could be something that Gurtogg or Teron Gorefiend is doing which is causing it?

If I can get screenshots from anyone else in guild who experienced it (it affected at least 3 of us tonight and one previously) I will update this ticket.

EDIT: The debuff has cleared, so here is an updated screenshot in combat.

<img width="255" alt="Screenshot 2024-12-28 211950" src="https://github.com/user-attachments/assets/ab8b6ec5-d499-4f86-acea-5ba34b483c82" />

**Comment by whitemane-lae** [comment]
Could be these, how long does this effect last?

https://www.wowhead.com/tbc/guide/trash-mobs-black-temple-strategy-burning-crusade-classic
<img width="255" alt="image" src="https://github.com/user-attachments/assets/e68962a5-ccb7-418a-bd0c-1d8219b4dbb7" />

**Comment by whitemane-lae** [comment]
Could be these :
![image](https://github.com/user-attachments/assets/121a73a1-34f1-4d5a-995d-29e815531355)


https://www.wowhead.com/tbc/guide/trash-mobs-black-temple-strategy-burning-crusade-classic

How long does this last and should it last through death?

**Comment by Piootrek** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/2471
It's the same issue and it's already fixed, but server wasn't updated with the fix yet.
