### ISSUE TITLE
Heigan dance bug

### ISSUE THREAD

**Issue by NNassib336** [gamefreedomgit/Frostmourne#268]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Heigan is fixed on wipe, so that's great! however, the dance is now bugged in 2 ways:

 - In phase 1 the eruption happens much too frequently (I think? Difficult to tell because of the 2nd bug, but it seems to be using phase 2's frequency)
 - If anyone gets hit by the eruption, the eruptions stop completely until a phase swap. This happens often, since the eruptions seem to happen too frequently in phase 1. Again, difficult to test since the eruptions stop once someone gets hit. It's also possible that the eruptions are just bugged and randomly stop, not sure.

**How to reproduce:**
Dance with Heigan

**How it should work:**
In phase 1, the eruptions should be slower, and they shouldn't stop until the fight ends.

**Database links:**

**Comment by Afgann** [comment]
fixed
