### ISSUE TITLE
Eye of Eternity minor bug

### ISSUE THREAD

**Issue by NNassib336** [gamefreedomgit/Frostmourne#269]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
After activating the orb, combat starts but Malygos doesn't immediately approach the platform. He finishes whatever he's doing with the rift he's at before heading over to start the fight.

**How to reproduce:**
Start the fight with Malygos.

**How it should work:**
Once the orb is activated, Malygos should drop what he's doing and head straight to the platform. 

**Database links:**

**Comment by Godmatik** [comment]
Confirmed, if he is doing an animation on one of the rifts - he should immediately cancel that and approach then land on the platform once the orb is clicked

**Comment by Afgann** [comment]
fixed
