### ISSUE TITLE
[Ascended Raids] Loot Adjustments

### ISSUE THREAD

**Issue by RadeghostWM** [gamefreedomgit/Frostmourne#27]
10-Man Ascended should drop different loot:

1x Emblem of Heroism
2x Emblem of Valor [ONLY FROM THADDIUS, MAEXXNA, LOATHEB, FOUR HORSEMEN, KEL'THUZAD, SARTHARION 3D, MALYGOS]
1x Emblem of Valor [ONLY FROM SARTHARION 0D, SARTHARION 1D, SARTHARION 2D]
1x 10-Man Item [from killed boss] + additional 10-Man item for THADDIUS, MAEXXNA, LOATHEB, FOUR HORSEMEN, KEL'THUZAD]
1x 25-Man Item [from killed boss' 25-Man version, that could include 25-Man Tier token]

SPECIAL BOSSES
Sapphiron should drop 1x 10-Man, 1x25-Man, Key to the Focusing Iris (10-Man item version), 50% chance for Heroic Key to the Focusing Iris (25man item version) [so Sapph follows the pattern, but has 100% chance to drop 10man Key and 50% chance to additionally drop 25man key)
Kel'Thuzad should drop: 1x25-Man, 2x10-Man

EXAMPLES

Sapphiron:
1x Emblem of Heroism
1x 213 iLvl from Sapphiron (25-Man)
1x 200 iLvl from Sapphiron (10-Man)
1x Key to the Focusing Iris
33% chance for Heroic Key to the Focusing Iris

Thaddius:
1x Emblem of Heroism
2x Emblem of Valor
1x 213 iLvl from Thaddius (25-Man)
2x 200 iLvl from Thaddius (10-Man)

Kel'Thuzad:
1x Emblem of Heroism
2x Emblem of Valor
1x 226 iLvl from Kel'Thuzad (25-Man)
2x 213 iLvl from Kel'Thuzad (10-Man)

Patchwerk:
1x Emblem of Heroism
1x 213 iLvl from Patchwerk (25-Man)
1x 200 iLvl from Patchwerk (10-Man)

Gothik
1x Emblem of Heroism
1x 213 iLvl from Gothik (25-Man)
1x 200 iLvl from Gothik (10-Man)

Loatheb
1x Emblem of Heroism
2x Emblem of Valor
1x 213 iLvl from Loatheb (25-Man)
2x 200 iLvl from Loatheb (10-Man)

**OBSIDIAN SANCTUM**
Sartharion 0D: 2x Tier 7 Hands token (200 iLvl) 1x 10-Man item (200 iLvl), 1x10-Man item (200 iLvl), Dragon Hide Bag, Satchel of Spoils [no changes between normal and ascended]
Sartharion 1D: Additional item from Sartharion (200 iLvl) [no changes between normal and ascended]
Sartharion 2D: Additional item from Sartharion (213 iLvl) [no changes between normal and ascended]
Sartharion 3D: Additional item from Sartharion (50% for 213 iLvl, 50% for 226 iLvl) and Reins of the Black Drake [change: +1x226 item from Sarth 25-Man 3D]

Examples:

 Sartharion 0D drops:
- 1x Emblem of Heroism
- 1x Emblem of Valor
- 2x T7 Hand Token (200 iLvl)
- Item (200 iLvl)
- Satchel of Spoils
- Dragon Hide Bag

Sartharion 1D drops:
- 1x Emblem of Heroism
- 1x Emblem of Valor
- 2x T7 Hand Token (200 iLvl)
- Item (200 iLvl)
- Item (200 iLvl) [NEW]
- Satchel of Spoils
- Dragon Hide Bag

Sartharion 2D drops:
- 1x Emblem of Heroism
- 1x Emblem of Valor
- 2x T7 Hand Token (200 iLvl)
- Item (200 iLvl)
- Item (200 iLvl)
- Item (213 iLvl) [NEW]
- Satchel of Spoils
- Dragon Hide Bag

Sartharion 3D  drops:
- 1x Emblem of Heroism
- 1x Emblem of Valor
- 2x T7 Hand Token (200 iLvl)
- Item (200 iLvl)
- Item (200 iLvl)
- Item (213 iLvl) 
- Item (50% for 213 iLvl, 50% for 226 iLvl)[NEW]
- Satchel of Spoils
- Dragon Hide Bag
- Reins of the Black Drake [NEW]

Eye of Eternity
Malygos: 
- Item (213 iLvl)
- Item (50% for 213 iLvl, 50% for 226 iLvl)

I'm so, so sorry, Afgann xD

**Comment by Afgann** [comment]
fixed
