### ISSUE TITLE
Eye of Eternity loot (10m ascended)

### ISSUE THREAD

**Issue by NNassib336** [gamefreedomgit/Frostmourne#270]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
My guild ran EoE 10 ascended earlier - Malygos dropped 2 10m pieces and no 25m pieces. Not sure if this is intended, or if it's just not working properly

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/966
