### ISSUE TITLE
[HUNTER][SPELL] Lock and Load interaction with Frost Trap on targets with permanent snare immunity

### ISSUE THREAD

**Issue by Nuy** [gamefreedomgit/Frostmourne#271]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:** Lock and Load gets proced by Frost Trap even when target is immune to snares what shouldn't be the case.

**How to reproduce:** Have Lock and Load talent and use Frost Trap on any boss.

**How it should work:** Lock and Load shouldn't proc from Frost Trap if target is permanently immune to snares. 

**Database links:** https://www.wowhead.com/wotlk/spell=56344/lock-and-load - "As of 3.2, Lock and Load will now have a 22-second internal cooldown, and cannot be obtained on targets immune to snare effects when Frost Trap is used. :("

https://wowwiki-archive.fandom.com/wiki/Lock_and_Load - "[Patch 3.2.0](https://wowwiki-archive.fandom.com/wiki/Patch_3.2.0) (04-Aug-2009): Now has a 22 second cooldown. The Lock and Load effect cannot be obtained on targets immune to snare effects when Frost Trap is used. The tooltip for this talent has been updated to indicate that it also works with Explosive Trap."

**Comment by Afgann** [comment]
On which boss did it proc? Seems to work fine on patchwerk and grobbulus.

**Comment by Nuy** [comment]
> On which boss did it proc? Seems to work fine on patchwerk and grobbulus.

I used it on boss dummy and it shouldn't proc there too.

**Comment by Afgann** [comment]
fixed
