### ISSUE TITLE
[Quest] Kickin' Nass and Takin' Manes

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#273]
**Description:**
Nass doesn't despawn after turning in the quest, he continues to follow/assist in combat until he dies

**How to reproduce:**
Turn in quest with Nass still alive, check whether it despawns

**How it should work:**
Nash should despawn after turning in the quest, example in https://www.youtube.com/watch?v=tdZ9RzxZXgg

**Database links:**
https://www.wowhead.com/wotlk/quest=12630/kickin-nass-and-takin-manes

**Comment by Afgann** [comment]
fixed
