### ISSUE TITLE
[Quest] Infiltrating Voltarus

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#274]
**Description:**
When you accept the quest mounted, you get an error "You are mounted."
The quest doesn't trigger any action which is blocked by the player being mounted

**How to reproduce:**
Accept the quest while on a mount

**How it should work:**
Being mounted shouldn't generate an error on this quest

Video of accepting quest while mounted
https://www.youtube.com/watch?v=nCFD_1zIs_M

**Database links:**
https://www.wowhead.com/wotlk/quest=12661/infiltrating-voltaru

**Comment by Afgann** [comment]
fixed
