### ISSUE TITLE
[Quest] So far so Bad

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#275]
**Description:**
Alarmed Blightguard that spawn during the quest are stuck in the cauldrons, evading

**How to reproduce:**
Go to reliquary of pain (31,42) and find cauldrons. There are Alarmed Blightguard stuck in the object in pair

**How it should work:**
They should be pathing around. I believe they spawn from the cauldron when using the item, as per wowhead comment

**Database links:**
https://www.wowhead.com/wotlk/quest=12669/so-far-so-bad#comments
https://www.wowhead.com/wotlk/npc=28745/alarmed-blightguard#comments

**Comment by Afgann** [comment]
fixed
