### ISSUE TITLE
Oculus [Ley Guardian Eregos]

### ISSUE THREAD

**Issue by wotlkenjoyer** [gamefreedomgit/Frostmourne#277]
Last boss in oculus keep chasing "tank" drake   and keep auto attacking,  does insane amount of  damage. 

Melee hits+ Abilities

There should not be any melee/chasing mechanic, normally  Eregos stays at minimal range cast of his ability Arcane barrage and keep spamming it, and using other abilities from time to time, but he basically stays in same place, you can see on video, he never goes melee

*Database links:*
https://youtu.be/N7-nnh7oubM 
https://wowpedia.fandom.com/wiki/Ley-Guardian_Eregos
https://www.icy-veins.com/wotlk-classic/the-oculus-dungeon-guide

**Comment by Afgann** [comment]
fixed
