### ISSUE TITLE
[Quest] The Storm King's Vengeance

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#278]
**Description:**
A couple of issues;
- Algar the Chosen isn't flying
- mobs have small aggro range and resets. They should aggro you from very far while on Gymer
- Storm clouds aren't working/healing, the Grab ability just grabs the cloud and you can thrown it like a normal mob and it will explode

**How to reproduce:**
Ride Gymer to quest area

**How it should work:**
https://www.youtube.com/watch?v=nxwliC-Dn84
https://www.youtube.com/watch?v=09Tv2NAnizE

**Database links:**
https://www.wowhead.com/wotlk/quest=12919/the-storm-kings-vengeance

**Comment by arooks1** [comment]
Just tried doing the quest, and can confirm this is still an issue.

**Comment by ChronoWM** [comment]
Tried the quest and it seems to be working fine if player talks to NPC [Gymer](https://www.wowhead.com/wotlk/npc=29647/gymer) in his initial spot (in the cage)

**Comment by Godmatik** [comment]
It works and is completable, but as stated in the original post, there are some issues outstanding
