### ISSUE TITLE
[Zul'Drak] The Argent Stand

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#279]
**Description:**
The area in front of Argent Stand is currently a little bugged

- Sky Terror mobs should fly down and grab Argent Crusader and drop them to their death if they don't have a parachute
- There are no Rotting Abominations mobs spawning https://www.wowhead.com/wotlk/npc=28023/rotting-abomination
- Sometimes there will be a mob and npc just standing next to each other. NPC will only aggro the mobs if player aggro the mobs (this isn't specific to this quest, I have seen this issue elsewhere)

**How to reproduce:**

**How it should work:**
https://www.youtube.com/watch?v=Jy9_hTXk6F8

**Database links:**
https://www.wowhead.com/wotlk/quest=12740/parachutes-for-the-argent-crusade

**Comment by UltraNix** [comment]
Fixed.
