### ISSUE TITLE
Mobs and NPC fighting each other sometimes bugs

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#280]
**Description:**
There are areas where NPCs will attack mobs that spawn within their area
Sometimes, they will just stand idle next to each other. The NPC will aggro the mob only once the mob aggros the player.

**How to reproduce:**
It probably happens everywhere where you have NPC fighting respawning mobs.
I have found occurrences of this bug in the following areas:
- The Argent Stand
- Altar of Sseratus
- north of Snowdrift Plains (area with the mole machines and iron dwarves)
- Terrace of the makers

**How it should work:**
NPC should automatically aggro the mobs that spawn around them

**Database links:**

**Comment by Afgann** [comment]
fixed
