### ISSUE TITLE
[Mob] Trapdoor Crawler

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#282]
**Description:**
Trapdoor Crawler should be burrowing in the ground. None is burrowing in Heb'valok

**How to reproduce:**
Go to Heb'Valok in Zul'Drak

**How it should work:**
They should burrow into the ground sometimes. I'm not sure what's the CD on the burrow nor how long they stay burrowed.
https://www.youtube.com/watch?v=ytkKpJTSXbs

**Database links:**
https://www.wowhead.com/cata/npc=28221/trapdoor-crawler?fromWrath#comments
https://www.wowhead.com/cata/quest=12609/stocking-the-shelves

**Comment by Afgann** [comment]
fixed
