### ISSUE TITLE
[Quest] Throwing Down

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#284]
**Description:**
- The craters don't despawn after exploding, so you can't visually tell whether the objects are "tapped" and won't give credit
- There should be unattackable Burning Skimmer spawning on fire then dying after exploding the craters
- There's Burning Skimmer just hanging out and not respawning

**How to reproduce:**
do quest

**How it should work:**
https://www.youtube.com/watch?v=k3EQwcFLXYo

**Database links:**
https://www.wowhead.com/wotlk/quest=12598/throwing-down#comments

**Comment by UltraNix** [comment]
Fixed.
