### ISSUE TITLE
[Quest] Leave No One Behind

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#285]
**Description:**
The NPCs will fly to reach player if you're flying
Likely this behavior affects other NPCs following, not just on this quest

**How to reproduce:**
![WoWScrnShot_031424_104341](https://github.com/gamefreedomgit/Frostmourne/assets/45928535/c930c11e-bd34-4917-a705-88831996a8f3)

**How it should work:**
NPC should follow player on the floor even if player is flying

**Database links:**
https://www.wowhead.com/wotlk/quest=12512/leave-no-one-behind

**Comment by Afgann** [comment]
fixed
