### ISSUE TITLE
[Quest] I Sense a Disturbance

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#287]
**Description:**
Quest is completable and pathing is fine, for some reason however your character and the cat mount become almost fully hidden

**How to reproduce:**
Talk to quest giver to start the path

**How it should work:**
Char and mount alpha should stay 100%
https://www.youtube.com/watch?v=5WXh6gjIT2o
https://www.youtube.com/watch?v=jltUkyVZLFE

**Database links:**
https://www.wowhead.com/wotlk/quest=12665/i-sense-a-disturbance

**Comment by Afgann** [comment]
fixed

**Comment by Vaxsysl** [comment]
This quest got bugged recently. Talking to Har'koa summons her pup and we mount it up... but that's it. We can move with it and enemies won't attack us, but we are not in the spirit world and we are unable to finish the quest. This makes us sit at 81/100 quests for the zone (at least achievement wise, there's more than that obv) and we are effectively locked out of the remainder of the zone. Hurts hardcore kinda.
