### ISSUE TITLE
[Quest] Hell Hath a Fury

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#288]
**Description:**
High Priest Hawinni doesn't die after getting the frozen hex debuffs, he just resumes attacking and stay at 1% and cannot die.
You still get credit though so quest still completeable

**How to reproduce:**
Use hexx item on High Priest Hawinni

**How it should work:**
https://www.youtube.com/watch?v=XrUj7yib0cU

**Database links:**
https://www.wowhead.com/wotlk/quest=12674/hell-hath-a-fury

**Comment by Afgann** [comment]
fixed
