### ISSUE TITLE
[PvP/Duel]  Bloodworms

### ISSUE THREAD

**Issue by wotlkenjoyer** [gamefreedomgit/Frostmourne#289]
Same as Army of the Dead ghouls before fix, they arent spawning if i attacking in PvP/Duel  

if i force spawn though attacking Target Dummy , they ignoring my duel target.

https://www.wowhead.com/wotlk/spell=49543/bloodworms

AI of bloodworms should be rewoeked same way as it was done with Army of the ghoul, you did it perfectly guys. Army are nice rn!!

**Comment by Afgann** [comment]
fixed
