### ISSUE TITLE
[Quest] Wooly Justice

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#290]
**Description:**
The vehicule ability "Rushing Charge" can only be used once, after that you can't use it saying you're in combat, even though you are not in combat. You have to get off and on the vehicule for the ability to be usable again

**How to reproduce:**
Mount mammoth, use charge on quest mob and kill it, then see how the ability stays stuck "in combat"

**How it should work:**
Ability should detect when player leave combat
https://www.youtube.com/watch?v=dAxrfz8E_iI

**Database links:**
https://www.wowhead.com/wotlk/quest=12707/wooly-justice

**Comment by Afgann** [comment]
fixed
