### ISSUE TITLE
[Dungeon][Utgarde Pinnacle]

### ISSUE THREAD

**Issue by Nenze** [gamefreedomgit/Frostmourne#292]
You can jump on invisible wall on the stairs which might give a players chance to cheese the adds around the area 
![image](https://github.com/gamefreedomgit/Frostmourne/assets/122581454/87045aed-e2ae-4830-9c93-343b2f32145c)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/122581454/9275b69a-a7aa-4fba-aadb-63ca120f4ebf)

**Comment by UltraNix** [comment]
It's just a texture- nothing serverside.
