### ISSUE TITLE
Mobs don't move correctly when LOS'ed

### ISSUE THREAD

**Issue by Akaimba** [gamefreedomgit/Frostmourne#294]
**Description:**

https://medal.tv/games/world-of-warcraft/clips/20WEzjtXaQw0yF/d1337P0sIw78?invite=cr-MSwxdVAsNTM0Nzk0NDEs

**How to reproduce:**
line of sight any caster

**How it should work:**
they should run to you in a straight line

**Comment by Afgann** [comment]
fixed
