### ISSUE TITLE
Heroic Dungeon Bugs

### ISSUE THREAD

**Issue by Davud-P** [gamefreedomgit/Frostmourne#297]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
# __Heroic Bugs:__

__Violet Hold:__
- Crystals to wipe a wave are non-interactive.
Damages could be toned up by ~10%, they can barely break a Regrowth + Rejuv on a pPal, when you fix the rDruid gear.
- UD DK popping Army of the Dead before Erekem, reset the Army of the Dead cd when the boss died. (So did Lavanthor and final boss.)

__Utgarde Pinnacle:__
- Grauf's breath hits for initial damage, and at least 3x the ice tick damage, immediately. (One shots 22k HP with FR gear). (Also, for anyone else reading, don't use FR. It's just for testing, and is garbage).
Same can happen with first proc of Bane on King Ymiron

__Drak'Tharon Keep:__
- Dredd resets CD's partway through the fight.

__Occulus:__
- Occulus drake item being removed when you die in dungeon
- 3rd spell is bound to your 6th key, rather than 3rd
- Eregos is using melee attacks (not sure if actually a bug, but never seen it). The melee goes through red drake dodge though
- Amber drakes can stun allies mounting on their drakes, if cast during the leap
- Emerald drake can't heal hostile-tagged drakes (which occurs cross faction sometimes. It swapped around who was hostile and who wasn't between dungeon entries)
- Eregos won't spawn whelps, especially if stunned as he phases
- No Occulus bag after clear
- Unsure if intended, but Eregos's arcane balls during immunity phase are too fast to be dodgeable/kiteable.

__Culling of Strath:__
- Salramm also not showing on the map
- Arthas doesn't appear at the tavern entrance after Salramm is killed (His running is delayed?)

__Azjol-Nerub:__
- Hadronox resets periodically, regardless of if you kill crushers or not. Especially if you try to cheese the crusher initially, and drag the first one down the tunnel with you.
- Hadronox achievement did not fire when you kill her before she webs the doors. (We killed her halfway up the ramp). No web message was displayed, and mobs were spawning throughout the fight

__Gundrak:__
- Eck doesn't enrage, is that a mechanic that's supposed to happen normally?
- Gal'darah puncturing more often than he should (can put you at 4 punctures in a phase, making the achievement difficult to obtain without rebirth/HoP cheesing)
- His impale targets also aren't quite right, but could be random

__Heroic LFG Cross Faction:__ 
- Gives leader to 2 party members, if both factions are present, and it won't let you LFG again with the group without reforming.

__More general:__
- Timers for loot are infinite (could just be a PTR thing tho)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
