### ISSUE TITLE
tailor cloak enchants icd

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#298]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
currently they are incorrect as tested on whitemane ptr

**How to reproduce:**
enchant them and check proc chance and icd

**How it should work:**
Swordguard Embroidery : should be 20% proc chance on hit and 55sec icd
Lightweave Embroidery : should be 35% chance on cast (can proc from other procs ) and 1min icd
Darkglow Embroidery : 35% chance per cast and 45sec icd

**Database links:**
https://www.wowhead.com/wotlk/spell=55640/lightweave-embroidery
https://www.wowhead.com/wotlk/spell=55776/swordguard-embroidery
https://www.wowhead.com/wotlk/spell=55768/darkglow-embroidery

**Comment by Afgann** [comment]
fixed

**Comment by Manpower99** [comment]
@Afgann this seems to be broken again or not applied im not sure
