### ISSUE TITLE
[RHC] Satchel of Exotic Mysteries

### ISSUE THREAD

**Issue by wotlkenjoyer** [gamefreedomgit/Frostmourne#299]
When you queue as unpopular role  (usually tank/healer) you get satchel of exotic mysteries, but there is zero loot

![Capture](https://github.com/gamefreedomgit/Frostmourne/assets/158612010/c2943a47-b4f3-4164-ab30-c48a2f5a0802)
![Capture2](https://github.com/gamefreedomgit/Frostmourne/assets/158612010/f680babb-219f-4f3a-a58b-47848bb19fff)

**Comment by UltraNix** [comment]
Fixed.

**Comment by ChronoWM** [comment]
There are still ongoing issues with empty satchels for tanks in solo queue.

**Comment by bandini9** [comment]
> There are still ongoing issues with empty satchels for tanks in solo queue.

 I also got empty satchel 12 days ago, I posted it on discord but no one took it serious xd (This was after it was 'fixed')

**Comment by UltraNix** [comment]
Fixed.
