### ISSUE TITLE
Glyph of Life Tap doesnt work

### ISSUE THREAD

**Issue by SBOcodes** [gamefreedomgit/Frostmourne#30]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Human Warlock Glyph "Glyph of Life Tap" doesnt give spellpower buff

**How to reproduce:**
equip glyphe and lifetap :)
**How it should work:**
should give spellpower buff based on our spirit for 40s

**Database links:**

**Comment by SBOcodes** [comment]
No it doesnt.

**Comment by scrublama** [comment]
try relogging if you used the template @SBOcodes
