### ISSUE TITLE
Improved Drain soul dosnt give mana when mob dies

### ISSUE THREAD

**Issue by hamajaxd** [gamefreedomgit/Frostmourne#301]
Improved drain soul should give 14% mana if mob dies while u have drain soul on him it seems like on this server it only gives mana if u kill it with ur tick of drain soul which it shouldnt happen like this

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/ff273374-721c-4ce6-ba2e-9ba0d9c8fb72)
Looks okay to me.

**Comment by Godmatik** [comment]
You need to get the killing blow on it with drain soul. If your pet gets it, it won't proc

**Comment by hamajaxd** [comment]
@UltraNix @Godmatik yes u are correct in the server u need to get the killing blow but it shouldnt work like that as long as u have drain soul on target and he dies wether from u or pet or even another player u should get the mana back

**Comment by Godmatik** [comment]
It definitely does work like that and is blizzlike, you need to get the killing blow, not your pet.

Go try it on classic.
