### ISSUE TITLE
Offhand Swings timers

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#302]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
https://www.youtube.com/watch?v=In78lWEWyH8
as explained in this video
skip over to after 2:40
**How to reproduce:**
take warrior with same speed weapons an trigger attack, both swings will trigger same time
attempt to desync through macro or by swapping targets and same result

**How it should work:**
On wow whenever you trigger an attack on a new target the mainhand should be triggered immidiately based on the current swing timer, however the offhand should always lag behind everytime unless the attack has been charged (by triggering the attack from far away range for long enough)
this is important for desyncing and syncing similar speed weapons for classes such as warrior and enhancement shamans who benefit differently from having synced and desynced weapon speeds.
Regular Enha shamans want to sync their hits
and Fury warriors want to desync to prevent deep wounds munching and so that heroic strike feature benefits the offhand

an interaction with a macro that intentionally desyncs them is also something to be considered : 
/cleartarget
/targetlasttarget
/startattack

**Database links:**

**Comment by Manpower99** [comment]
I will provide additional info on this issue later since this is quite important imo.

**Comment by UltraNix** [comment]
Fixed.
