### ISSUE TITLE
Alchemist's Stone buff does not work in Trinket Slot #2

### ISSUE THREAD

**Issue by Furiianda** [gamefreedomgit/Frostmourne#303]
**Description:**
Alchemist Stone buff (40% increased effect from healing & mana potions) does not function when equipped in Trinket Slot #2.
The buff appears when the trinket is equipped in either slot, but the additional restorative effect only occurs when it is equipped in the 1st slot.

**How to reproduce:**
Equip one of the Alchemist Stone trinkets to the second trinket slot and chug a potion. 
Alchemist Stone bonuses appear in combat log/text after the potion as an additional restoration effect called "Alchemist's Stone".

**How it should work:**
The trinket should function the same when equipped in either trinket slot.

**Database links:**
https://www.wowhead.com/wotlk/item=44322/mercurial-alchemist-stone
https://www.wowhead.com/wotlk/item=44324/mighty-alchemists-stone
I was unable to test the Tank trinket "Indestructible Alchemist Stone" as materials to create it are not available from the vendor.

**Comment by UltraNix** [comment]
1. slot:
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/4fb6d9bd-c11b-48ba-af67-6757fbb37bd5)

2. slot:
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/ccef9de3-4059-4695-9b19-8627ae2c9fa3)

Works okay to me.

**Comment by Furiianda** [comment]
Weird- works for me today too. I guess it just doesn't work on 22nd March every year (: . Thanks for fixing it by viewing it (lol
