### ISSUE TITLE
mass looting

### ISSUE THREAD

**Issue by hamajaxd** [gamefreedomgit/Frostmourne#304]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

when in a group and u kill a group of mobs the aoe loot mess up for example if u kill 8 mobs that each drop 1 quest item u will only get 2-3 quest items from the mobs and no the drop chance is not low its just messed up at least make an option to turn off mass looting

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
@hamajaxd Can you give us examples of such mobs or q items?

**Comment by hamajaxd** [comment]
for example the wanted quest in tanaris the caliph dude when we killed 5 mobs , only 1 of us could get the head via mass loot ( we were 3 ) the other 2 didnt get to loot it , and many encounters we faced the same issue when we mass pull like 7-10 mobs and we kill them all only one of us get 7-10 quest items the rest get 3-5 quest items it shouldnt be like this @UltraNix

**Comment by Iramtempus** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/391

Dual ticket - Mine includes video. @UltraNix

**Comment by UltraNix** [comment]
Fixed.
