### ISSUE TITLE
[Night Elf] Shadowmeld Racial is BUGGED

### ISSUE THREAD

**Issue by Naturlish** [gamefreedomgit/Frostmourne#305]
**Description:**
Night Elf Shadowmeld Racial is bugged whenever you are trying to escape from mobs. The mobs keep attacking you after activation, and without any dot on your character of course.

**How to reproduce:**
Simply use Shadowmeld to vanish and get out of combat.

**How it should work:**
Whenever you activate Shadowmeld, you are supposed to leave the combat.

**Database links:**
https://wotlk.evowow.com/?spell=58984

**Comment by Afgann** [comment]
fixed
