### ISSUE TITLE
[Naxxramas] Heigan the Unclean

### ISSUE THREAD

**Issue by wotlkenjoyer** [gamefreedomgit/Frostmourne#306]
We did Heigan the Unclean today, 10man  ascended. 

First phase seems okay untill dance phase starts. In dance phase  poison explosion happens once,   on first  left position.
After that he just stand in middle of the platform  and does nothing. No explosions, nothing, just stay and dps, untill "dance" ends.

Then again phase 1,  untill this broken dance  repeats

**Comment by Davud-P** [comment]
I believe I was in this group. +1 to this issue.

Heigan dance explosions do not work after the first phase. When he teleports to the platform, the first zone fires off really quickly, and then he does nothing for the rest of the duration of the dance.

**Comment by Afgann** [comment]
fixed
