### ISSUE TITLE
A BOAT in Ironforge's Deeprun Tram

### ISSUE THREAD

**Issue by Naturlish** [gamefreedomgit/Frostmourne#307]
**Description:**
I was travelling from Stormwind to Ironforge with the tram and noticed this bug:
![image](https://github.com/gamefreedomgit/Frostmourne/assets/54108446/c8ddd661-5586-4f4e-970d-7f6225b8351e)

**Comment by WhitemaneIsa** [comment]
Seems like there is no longer a boat there :D
