### ISSUE TITLE
Naxx 10mn Ascended Bugs - Military Wing

### ISSUE THREAD

**Issue by Davud-P** [gamefreedomgit/Frostmourne#308]
**Description:**

**Instructor Razuvious:** 
1. His 2 small minions run towards the crystals when you initially MC them. This is not expected behavior, as they shouldn't start sprinting at the players before the tanks can turn them around.
2. Instructor also hits for way too little on the minions without bone shield. This should be amped way way up. At least x2 the damage, if not more. Seems like a weird interaction since he should be doing tank-lethal damage, thus forcing us to use the crystals. Not sure if there's an underlying interaction missing or not.

**Gothik the Harvester:** 
1. Moves when he can't LoS the main target. He probably should not move. On other servers, he just would wait until someone else took threat from tank. I don't think that's a terribly good design, but he probably shouldn't just run down the tank if Gothik can't see him. 

**4 Horsies:** 
1. They do basically no damage on 10mn Ascended. We killed them rather quickly, but even then they did not slap even at 3 marks. With current damages, we could safely get to 5 stacks without any deaths. I'm not sure if the stacks timing is off, or if their damage values just weren't set to an Ascended value.

**Comment by Afgann** [comment]
fixed
