### ISSUE TITLE
Return to angrathar

### ISSUE THREAD

**Issue by hamajaxd** [gamefreedomgit/Frostmourne#309]
https://www.wowhead.com/wotlk/quest=12499/return-to-angrathar#comments 
the questline above should trigger an event and a cinematic and open a follow up quest called " reborn from the ashes " but it dosnt

nothing happens after u turn in the return to Angrather 

https://www.wowhead.com/wotlk/quest=13347/reborn-from-the-ashes

**Comment by UltraNix** [comment]
Not this patch.
