### ISSUE TITLE
Drain Soul ticks are refreshing Corruption dot duration bug

### ISSUE THREAD

**Issue by Robosterone** [gamefreedomgit/Frostmourne#31]
**Description:**
Drain Soul ticks are refreshing Corruption dot duration which shouldn't happen and it is a bug.

**How it should work:**
Only CHANNEL_START event should refresh Corruption duration via Everlasting Affliction.

**How to reproduce:**
Put Corruption on target and cast Drain Soul.

**Database links:**
https://wowpedia.fandom.com/wiki/Everlasting_Affliction

**Comment by Robosterone** [comment]
I've found out only first Drain Soul tick is refreshing Corruption duration, others do not.

**Comment by Robosterone** [comment]
https://www.youtube.com/watch?v=gGwccF0WLTs little comparison how is it supposed to work/how it works rn

**Comment by Afgann** [comment]
fixed
