### ISSUE TITLE
Fast object respawns missing

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#310]
In a previous server version, you updated quest objects to respawn at a pretty fast rate.

https://github.com/gamefreedomgit/Frostmourne/issues/176

One of the recent updates broke it, and it's back to 5 minute respawns again.

**Comment by UltraNix** [comment]
@Godmatik For example, what objects?

**Comment by Godmatik** [comment]
Will retest this weekend, maybe its resolved now with your recent core updates
