### ISSUE TITLE
Resto Shaman Riptide Arrival Bug

### ISSUE THREAD

**Issue by Davud-P** [gamefreedomgit/Frostmourne#312]
**Description:**
rShamans can instant-consume their Riptide casts by casting chain heal first, and spamming riptide to instant-cast after chain heal completes. This allows you to apply the riptide on the target before the chain heal arrives, giving you a free instant empowered chain heal on the target.

**How to reproduce:**
Cast chain heal, and as it finishes cast Riptide. Riptide arrives before Chain heal, and is consumed.

**How it should work:**
Chain Heal should be applied first, and then the Riptide buff should be applied without being consumed, as Chain Heal was cast first and should arrive at the target before Riptide does.

**Comment by Afgann** [comment]
fixed
