### ISSUE TITLE
Mob pathing issue

### ISSUE THREAD

**Issue by dizzydead** [gamefreedomgit/Frostmourne#313]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
I often can't cast spells through doorways and enemies warp up over the door frame to get through. This can be a big problem in keeps where there are door ways right under the elite quest mob chamber. Mobs teleport up to aggro every enemy in the room. Additionally pets like the void walker follow the mob up into the doorframe and stay up there were you cannot target it.

**How to reproduce:**
Fight near a door frame.

**How it should work:**
Spells should go through doorways. Mobs should walk through doorways on the ground not in the ceiling.

**Database links:**
??? I don't know how it's made. I just play the game.

**Comment by dizzydead** [comment]
![Uploading Screenshot (456).png…]()

**Comment by dizzydead** [comment]
![Uploading Screenshot (457).png…]()

**Comment by UltraNix** [comment]
Fixed.
