### ISSUE TITLE
Minor visual bug in death knight starting zone

### ISSUE THREAD

**Issue by dizzydead** [gamefreedomgit/Frostmourne#314]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Noth the Plaguebringer's cauldron is already there before you do the quest to make it.

**How to reproduce:**
Play the death knight starting zone up until the quest.

**How it should work:**
The cauldron should not be there until you do the quest which involves stealing the items needed to craft it from the scarlet crusade.

**Database links:**
lol idk the database.

**Comment by dizzydead** [comment]
![Uploading Screenshot (474).png…]()

**Comment by UltraNix** [comment]
Link is dead.
