### ISSUE TITLE
Death Knght Battle for Light's Hope Bugged but doable

### ISSUE THREAD

**Issue by dizzydead** [gamefreedomgit/Frostmourne#315]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
In the death knight starting questline in eastern plaguelands you get a quest like "the battle for light's hope" where you fight tirion fordring and his paladins. Darion Mograine the guy you're fighting alongside is supposed to give you a buff which is supposed to make you strong enough to fight there but it doesn't. They one shot you. When you come back to respawn Mograine doesn't give you the buff and you get one shot again. The only way to win is to wait in the graveyard until its over or stay far from the fight for 10+mins.

Additionally when the battle finishes Tirion is supposed to cleanse the Ashbringer (Darion Mograine's sword) of it's corruption but he doesn't. That isn't very important gameplay wise but it does put a hole in the story since he uses the uncorrupted Ashbringer to shatter the Lich King's sword later at the top of ice crown.

**How to reproduce:**
To reproduce the bug just do the quest you would normally. I did the quest twice and it was bugged both times.

**How it should work:**
The buff Darion Mograine gives you is supposed to boost your defenses and damage so that you're strong enough to fight the paladins in light's hope. Tirion fordring is supposed to cleanse the Ashbringer of corruption when he acquires it. To do achieve this visual effect just make Tirion unequip https://www.wowhead.com/classic/item=22691/corrupted-ashbringer this ashbringer and have him equip https://www.wowhead.com/item=120978/ashbringer that one.

**Database links:**

**Comment by PanJanuszek** [comment]
#1405
