### ISSUE TITLE
Quest Name: Coward Delivery... Under 30 Minutes or it's Free - Alliance Deserter not following character.

### ISSUE THREAD

**Issue by dizzydead** [gamefreedomgit/Frostmourne#316]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
In Warsong Hold in the Borean Tundra there is a quest called Coward Delivery... Under 30 Minutes or it's Free which is part of a chain. I haven't done this quest before but I think it's bugged. In the video online there's an alliance guy who's supposed to follow you as an escort mission but he isn't showing up for me.

**How to reproduce:**
Accept the quest. In my experience the Alliance Deserter doesn't follow me each time. I have abandoned the quest and tried again but no luck.

**How it should work:**
Alliance Deserter should follow your character to the crossroad area where you will supposedly complete the escort. May want to check this one yourself though. I'm unfamiliar with wrath of the lich king areas.

**Database links:**
aaaaa

**Comment by Afgann** [comment]
fixed
