### ISSUE TITLE
Minor bug: Levitating dragon who isn't flapping it's wings.

### ISSUE THREAD

**Issue by dizzydead** [gamefreedomgit/Frostmourne#317]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Location: Icecrown. Argent Vanguard. There is a levitating dragon named Glory who is standing still but is a few meters in the air. Looks silly.

**How to reproduce:**
Bug is apparent to all who pass through the zone.

**How it should work:**
The dragon should either be flapping it's wings or be on the ground.

**Database links:**

**Comment by Afgann** [comment]
fixed
