### ISSUE TITLE
Racials are gone!

### ISSUE THREAD

**Issue by Naturlish** [gamefreedomgit/Frostmourne#318]
I just logged on any characters, any races, Horde or Alliance, on Frostmourne PTR.

All the racials have gone.

![image](https://github.com/gamefreedomgit/Frostmourne/assets/54108446/d37659a3-7311-4de9-804b-0b75d8fb5ecf)

![image](https://github.com/gamefreedomgit/Frostmourne/assets/54108446/299636f8-aa12-4a0f-906f-a8c2ea99122b)

**Comment by Afgann** [comment]
fixed
