### ISSUE TITLE
[Quest] Diabolical Plans

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#319]
Plans never drop - either insanely low drop rate or does not exist.

Result is this quest + follow-up can not be completed.

https://www.wowhead.com/tbc/item=23798/diabolical-plans#provided-for
https://www.wowhead.com/tbc/quest=9535/diabolical-plans

**Comment by Godmatik** [comment]
Also my character is Horde if that matters, 

Maybe only the Alliance version exists.

**Comment by Afgann** [comment]
fixed
