### ISSUE TITLE
Searing Gorges - Suntara Stones [BUGGED]

### ISSUE THREAD

**Issue by Naturlish** [gamefreedomgit/Frostmourne#320]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Dorius respawn is bugged which makes impossible to launch the quest.

**How it should work:**
When Dorius appears you can launch the escort quest.

**Database links:**
https://wotlk.evowow.com/?quest=3367

**Comment by Naturlish** [comment]
I found out you can make Dorius respawn again if you check for the Dark Iron Marksman first. He must disappear so Dorius could respawn again.

**Comment by UltraNix** [comment]
Jus tested and works okay.
