### ISSUE TITLE
Night Elf Hunter Quest - Taming the Beast part 2

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#322]
[](https://www.wowhead.com/wotlk/quest=6103/training-the-beast)
Tame a night stalker

**Description:**
This is step 2 in a 3 part chain which allows hunters to learn pet abilities of feed, dismiss etc. It is only after  you complete stage 3 of the chain that you get https://www.wowhead.com/wotlk/quest=6103/training-the-beast which rewards the hunter abilites.

 Upon taming a night stalker, it becomes a fully function pet and you learn the other hunter pet abilites right away. The quest cant be completed. I found only one that can be tamed as per quest requirement which doesnt become a pet

**How to reproduce:**
go tame a night stalker

**How it should work:**
Any night stalker cat should be tamed and not become a functional pet. You should only get the hunter pet abilites after stage 5 
[](https://www.wowhead.com/wotlk/quest=6103/training-the-beast)

**Database links:**

**Comment by UltraNix** [comment]
He's not your pet, but only your charm. You can dismiss it whenever you like.
The quest can be completed.
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/e4028ffd-1a89-43ee-8f6d-3835ad356f09)

**Comment by WhitemaneIsa** [comment]
This issue occured again today on the troll version, the player finished the pre-quest https://www.wowhead.com/wotlk/quest=6062/taming-the-beast and is now unable to tame the Crab https://www.wowhead.com/wotlk/quest=6083/taming-the-beast, because they are stuck with the not existing boar from before, it doesn't show in auras or anywhere.

**Comment by UltraNix** [comment]
@WhitemaneIsa Relog does not help? What error player sees?

**Comment by WhitemaneIsa** [comment]
> @WhitemaneIsa Relog does not help? What error player sees?

Didn’t test relog, there is no error message, the channel of the taming rod either finishes with no result or doesn’t happen at all
