### ISSUE TITLE
Blood Elf Racial Abilities And Passives Bug

### ISSUE THREAD

**Issue by Neroix** [gamefreedomgit/Frostmourne#323]
Description: When you start the game as blood elf at level (2) you I'd have an access to an NPC (Arcanist Helion) on the starting zone. Which gives you a quest called Thirst Unending (https://www.wowhead.com/quest=37439/thirst-unending), whenever you get the quest you wouldn't be able to find the racial ability Arcane Torrent In your general ability slot. My theory was it may be because of auto accept addon's but even after I disabled them all it still wouldn't allow me to obtain nor complete the quest.

Also whenever you'd start the game you'll get this massege that say's: Arcane torrent unlearned:

![Caxpture](https://github.com/gamefreedomgit/Frostmourne/assets/109008518/b56abd65-bba0-40bc-809d-09db125048e3)

So my best assumption might be is because of the force removal of racial abilities that lead into this issue.

How to reproduce: Start a character as blood elf then try to reach level (2) and speak with the NPC called (Arcanist Helion)

How it should work: at first you wouldn't have the ability on your general slot on your blood elf character until you've accepted the quest on level (2) from an NPC (Arcanist Helion). Then you'd have to cast it for the first time so that you'd have it permanently.

Database links: https://www.wowhead.com/npc=15297/arcanist-helion, https://wotlk-twinhead.twinstar.cz/?spell=50613

**Comment by UltraNix** [comment]
@Neroix What class? Also - have you swap your racials with something else?

**Comment by WhitemaneIsa** [comment]
> @Neroix What class? Also - have you swap your racials with something else?

From what I heard this happens when they swap their racial before they do the quest for their racial.

**Comment by WhitemaneIsa** [comment]
Haven't heard further complaints since. Closing.
