### ISSUE TITLE
Mob Pathing, STV Kurzen's Compound

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#326]
Description: For the Quest Bookie Herald 
 You need to go to the 2nd floor of the Building. The mobs near near the door tend to go through the roof to the 2nd floor and agro the upstairs mobs IF you LOS em or the run away. I think this could be a pathing issue in 2 similar story buildings cos l noticed this mob behavior in The 2 story building in The Rotting Orchard in Duskwood

**How to reproduce:**
Stand outside and pull one and  then run away to pull em out.

**How it should work:**
run outside through the door

**Database links:**
 [](https://www.wowhead.com/wotlk/quest=200/bookie-herod)

**Comment by UltraNix** [comment]
Fixed.
