### ISSUE TITLE
Skinning Bonus  - Master Of Anatomy Rank 1 did not apply

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#327]
I didn't get rank 1 of  Master of Anatomy when  l hit level 75 skinning nor did l get it when l learned  75 to 150 bracket. But l did get rank 2 when l hit 150 skinning. I still haven't learned level 3 150 to 225? yet

UPDATE. The Rank 1 spell didnt appear after hitting 75 skinng,  Rank 2 and 3 appeared BUT they do not increase the crit rating of the player. They only appear in the spell book

**Comment by jack40melb** [comment]
The Crit Bonus per rank do not apply to player at all

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/a30503a4-847e-4e31-83cb-75aa14d6e5b0)
With 74 skill in skinning.

![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/e2beb0a2-a651-4537-b2cb-d7854b1204f6)
With 75 skill in skinning.

![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/b90300f6-455e-4014-84ac-5805620676be)
With 150 skill.

I see no bug here.
