### ISSUE TITLE
Darkshore Quest   - Tharnariun's Hope

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#328]
**Description:**
The  Den mother has 3 cubs,  The den mother isnt linked to the 3 cubs so you can kill the den mother without being attacked by the cubs.

**How to reproduce:**
Go attack den mother

**How it should work:**
 Attack one and they all should attack.   Method should be pull the low level cub out one at a time and then  the den mother.

**Database links:**
[](https://www.wowhead.com/classic/npc=6288/jayla)

**Comment by Afgann** [comment]
fixed
