### ISSUE TITLE
Hunter Revive Pet - Pet revives at corpse and not at hunter's location.

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#329]
**Description:**
 When a pet dies and  and player cast revive pet,. The pet revives at its corspe and runs back to hunter through all mobs. they do not agro though

**How to reproduce:**
attack a mob with pet, let it die, move far away from pets corpse and cast revive pet

**How it should work:**
Should revive at current hunter's location

**Comment by UltraNix** [comment]
Fixed.
