### ISSUE TITLE
Conflagrate is consuming immolate DoT even with the glyph

### ISSUE THREAD

**Issue by Needashield** [gamefreedomgit/Frostmourne#33]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Conflagrate Should not consume the immolate/shadowflame debuff when you have Glyph of conflagrate

**How to reproduce:**
With the glyph on. cast immolate then conflagrate and the immolate/shadowflame debuff is gone

**How it should work:**
the debuff should remain on the target after you cast conflagrate

**Database links:**
https://www.wowhead.com/wotlk/spell=57258/glyph-of-conflagrate#comments

**Comment by scrublama** [comment]
glyphs doesnt seem to work until you relog if you used the template
