### ISSUE TITLE
DarkShore - Onu NPC still has ? after completing quest

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#331]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Darkshore - Onu NPC gives the Quest  - Onu is meditating. Once you complete it he still has the ? over his head

**How to reproduce:**

**How it should work:**
After completing the quest The Master's Glaive, and progress to next quest  The Twilight Camp his ? should be grey till you complete it. But after accepting the next one, its still gold, even when you complete the chain.

**Database links:**
[https://www.wowhead.com/wotlk/npc=3616/onu](url)

**Comment by UltraNix** [comment]
Fixed.
