### ISSUE TITLE
Battle Chickens

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#332]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Battle Chicken as confirmed with classic does stack with each application of Squawks.
https://www.reddit.com/r/classicwow/comments/lg9q2r/we_have_4_total_battle_chickens_in_our_raid_and/
Cannot provide warcraft logs as vanilla had a buff limit, tbc and wotlk warcraftlogs banned it by invalidating your logs if you used it.
but it does still work.
https://www.youtube.com/watch?v=Z-57ushw_SA&t=244s
this video explains the ban.

**How to reproduce:**
have two people in party with chickens
only one buff will be active if they proc and override the other

**How it should work:**
each buff should bd seperate and stack
the Level of the chicken itself should be engi skill/5. 
should only be melee attack speed https://www.wowhead.com/classic/spell=23060/battle-squawk

**Database links:**

**Comment by Godmatik** [comment]
You should consider limiting it to one buff stack.

Most private servers put restrictions on battle chickens because they are abused and broken - having a vanilla item provide stackable 5% melee haste.

**Comment by RadeghostWM** [comment]
each buff should bd seperate but it should NOT stack

the Level of the chicken itself should be engi skill/5.

should only be melee attack speed https://www.wowhead.com/classic/spell=23060/battle-squawk

This is how it should work to not abuse it and not require battle chicken stacking

**Comment by RadeghostWM** [comment]
Yes, limit to 1 stack.
