### ISSUE TITLE
Ashenvale quest " A shameful waste"

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#333]
**Description:**
 The larger lumber piles only count as one 

**How to reproduce:**

**How it should work:**
when they should count as 2 , " There are larger and smaller piles, from larger ones u will loot 2 Warsong Lumbers"  - from comment section

[https://www.wowhead.com/wotlk/quest=9517/a-shameful-waste](url)

**Comment by Afgann** [comment]
fixed
