### ISSUE TITLE
Ashenvale - Overseer Gorthak Pathing issue

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#334]
**Description:**
When attacked by pet, the Overseer Gorthak will run through and up to the roof of the building he is in. Also the  Warsong Shaman who is under him

**How to reproduce:**
attack either with a pet hunter, lock, mage

**How it should work:**
They should stay on their level or run along the path to the ground,

**Database links:**
[https://www.wowhead.com/wotlk/npc=17304/overseer-gorthak](url)

**Comment by UltraNix** [comment]
Fixed.
