### ISSUE TITLE
Hunter Pet - Bear - When it  attacks, it can suddenly start returning to hunter  before continuing attack

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#336]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When attacking a target using dash, it will run to mob, attack it and then turn around and walk back part way before turning around again and staying on target.

**How to reproduce:**
Have dash on auto cast,  Pet on defensive, attack a mob.

**How it should work:**
It should stay on the target

**Database links:**

**Comment by Afgann** [comment]
fixed
