### ISSUE TITLE
Ashenvale - Shredder Operating Manual

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#337]
**Description:**
Alliance - Seems to be a low drop rate. Its a horde quest so lm assuming the drop rate is the same. I completed all the quests in Ashenvale for alliance and only looted 6pages. Compared to the all the pages (+ some) from the same amount of time in STV for the Green Hills of Stranglethorn

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
