### ISSUE TITLE
[Undead/Paladin] Seal of Corruption spell missing.

### ISSUE THREAD

**Issue by MarcioMatteucci** [gamefreedomgit/Frostmourne#34]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Seal of Corruption is missing from the paladin's spell list.

**How to reproduce:**
If you choose to be an undead paladin you will not have the seal.

**Database links:**
https://wotlk-twinhead.twinstar.cz/?spell=53736

**Comment by RadeghostWM** [comment]
It's available in "General" tab.
