### ISSUE TITLE
Blackfanthom Deeps - Lorgalis Manuscript drops of mobs 

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#340]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Lorgalis Manuscript dropped of a crab

**How to reproduce:**
 kill mobs in BFD

**How it should work:**
 Should only be lootable from a chest in the first cavern

**Database links:**
[https://www.wowhead.com/wotlk/quest=971/knowledge-in-the-deeps](url)
[https://www.wowhead.com/wotlk/item=5359/lorgalis-manuscript](url)

**Comment by Afgann** [comment]
fixed
