### ISSUE TITLE
Barrens - Lizzarik's Bodyguard  Jorb is does not follow Lazzarik

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#342]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Jord stays at Ratchet while Lizzarik goes to Crossroads and back

**How to reproduce:**

**How it should work:**
He should follow Lizzarik as he does the patrol from Xroads to Ratchet

**Database links:**
[https://www.wowhead.com/wotlk/npc=3658/lizzarik#comments](url)
[https://www.wowhead.com/wotlk/npc=3659/jorb](url)

**Comment by Godmatik** [comment]
Confirmed

**Comment by Afgann** [comment]
fixed
