### ISSUE TITLE
Barrens -  Mssing/Inconsistent  Savannah  Prowlers, Matriarchs & cub packs in shrubs and base of Trees near ratchet

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#343]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Some of the shrubs and tree above entrance to Ratchet. Both North and south side

**How to reproduce:**

**How it should work:**
There  should be packs of 3-4  in the dark green shurbs  and under trees scattered around the Above Ratchet , combination of all 3 Matriarchs has  2 cubs,  1 matriarch  with 2 cubs in one location. Not 2 or 3 close by

**Database links:**
[https://www.wowhead.com/wotlk/npc=3425/savannah-prowler](url)
[https://www.wowhead.com/wotlk/npc=3416/savannah-matriarch](url)

![image_2024-04-16_125337650](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/c6dc88a0-2310-4194-8a7b-36ed2a6eaea9)

![1](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/b37e8783-2c3c-4dcf-b2da-ef47ce68191c)

![2](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/4fa39ca4-59b4-4a23-9975-e8d3bb740354)

![3](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/cb9d4597-96c5-417e-80a4-cd3cc63b0cf0)

![4](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/80a0c6f7-c000-4eb8-aff6-782d579c93c8)

![5](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/e00cfd5d-be89-49ae-9ada-b71b023dd6db)

**Comment by UltraNix** [comment]
Fixed.
