### ISSUE TITLE
[Feature] Event Skip - Halls of Stone

### ISSUE THREAD

**Issue by RadeghostWM** [gamefreedomgit/Frostmourne#345]
Make it possible to skip HoS event. That makes Bran open the door after the "boss" event, so players skip the whole event and don't get loot for that.

Let Bran have a new dialogue option when talking to him there for the first time:

**English (enGB/enUS):**
- I don't have time for that. (Skip event)

**German (deDE):**
Ich habe keine Zeit dafür. (Ereignis überspringen)

**Spanish (esES/esMX):**
No tengo tiempo para eso. (Omitir evento)

**French (frFR):**
Je n'ai pas le temps pour ça. (Passer l'événement)

**Russian (ruRU):**
У меня нет времени на это. (Пропустить событие)

**Chinese (zhCN, zhTW):**
我沒有時間做這個。 (跳過活動)

**Comment by UltraNix** [comment]
Fixed.
