### ISSUE TITLE
Savage Gladiator's Gavel missing mp5/sp stats

### ISSUE THREAD

**Issue by kinpie** [gamefreedomgit/Frostmourne#347]
[//]: # https://www.wowhead.com/wotlk/item=42344/savage-gladiators-gavel

**Description:**

Savage Gladiator's Gavel is missing mp5/sp stats.

**How to reproduce:**

type ".additem 42344" on the PTR and it will pop into your bags so you can see for yourself.

![image](https://github.com/gamefreedomgit/Frostmourne/assets/36087298/42ea02d5-060e-4800-82e7-417057301010)

**How it should work:**

![image](https://github.com/gamefreedomgit/Frostmourne/assets/36087298/4c0a502b-9dce-4536-927c-2e604565fe41)

**Database links:**

https://www.wowhead.com/wotlk/item=42344/savage-gladiators-gavel

**Comment by Acurtis03** [comment]
lol yeah... a mace with no spell power is definitely not correct. 
and as you can see from the hateful gavel 

https://www.wowhead.com/wotlk/item=42351/hateful-gladiators-gavel 

the spell power and other stats would be correct and on point if they matched the image linked by the OP.

**Comment by UltraNix** [comment]
Fixed.
