### ISSUE TITLE
Shaman Feral Spirit defaults to passive.

### ISSUE THREAD

**Issue by s71n63r** [gamefreedomgit/Frostmourne#348]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Shaman Feral Spirit defaults to passive, setting change is not remembered.

**How to reproduce:**
Roll Shaman.
Cast Feral Spirit
Observe default setting is "Passive"
Change setting to Defensive or Aggressive
Cast Feral Spirit again and note setting is set back to "Passive"

**How it should work:**
Should default to Defensive or Aggressive.
Or should remember last setting.

**Database links:**
https://www.wowhead.com/wotlk/spell=51533/feral-spirit

**Comment by Afgann** [comment]
fixed
