### ISSUE TITLE
Fleeting Plainstrider inside Wailing caves entrance.

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#349]
**Description:**
Does not belong here, should be only raptors and slimes, In the tunnel just past the npc Mad Magglish

![image_2024-04-14_120355744](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/e57b6ce3-c61f-4fea-807f-b66f1725da0f)

@

**Comment by Afgann** [comment]
fixed
