### ISSUE TITLE
[PTR] Glyphs dont work until you relog after you used template

### ISSUE THREAD

**Issue by scrublama** [gamefreedomgit/Frostmourne#35]
**Description:**
Glyphs dont work until you relog after you used template

**How to reproduce:**
Pick Template at Sally Whitemane
Tried as warlock with conflagrate consuming immolate and life tap not giving buff

**How it should work:**
Should probably work or tell them to relog work it to work

**Database links:**

**Comment by Afgann** [comment]
fixed
