### ISSUE TITLE
Wailing Caves - Rare spawn Trigore the Lasher missing from entrance area

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#350]
**Description:**
Trigore the Lasher should be in either one of the 2 pools just before the Portal entrance to WC. I have hardly ever seen him on any  WOTLK servers yet.

[https://www.wowhead.com/wotlk/npc=3652/trigore-the-lasher#comments](url)

**Comment by UltraNix** [comment]
Fixed.
