### ISSUE TITLE
Hunter Volley animation continues after casting/combat finishes

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#351]
**Description:**
This one is a bit random. Location inside Wailing caves

**How to reproduce:**
Attack something and cast volley.   As you can see from the image, lm casting volley where l am and yet the animation is still going the far side where l last cast it. Dont know if its a location issue cos all other times its finished.

**How it should work:**
The visually animation should stop upon casting end 

**Database links:**

![image_2024-04-14_110536749](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/17d9309d-06c8-450e-9df2-089daa4e9e1d)

**Comment by Manpower99** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/178

**Comment by UltraNix** [comment]
@jack40melb That old Volley still do damage?

**Comment by Manpower99** [comment]
> @jack40melb That old Volley still do damage?

No it is a permanent visual bug ( works for almost every aoe in game including blizzard hurricane volley, aka targeted ground aoe visual ) i have noticed it in multiple raids something related to server desyncing the visual/actual spell and just doesnt despawn it.
doesnt usually despawn until server restarts but since it happens usually in instances it is barely noticed.

**Comment by UltraNix** [comment]
@Manpower99 Will you be able to record that bug? I mean - maybe you are casting something else at the same time as the ending of channeling the Volley?

**Comment by Manpower99** [comment]
> @Manpower99 Will you be able to record that bug? I mean - maybe you are casting something else at the same time as the ending of channeling the Volley?

Thats the issue, it happens very rarely but when it does its almost always those spells. next time it happens ill take multiple screenshots with ingame time to show it.

**Comment by WhitemaneIsa** [comment]
No further info/complaints, closing.
