### ISSUE TITLE
Wailing Caves End boss Event - Inconsistant spawn of waves

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#352]
**Description:**
When the Disciple of Naralex begins casting his spell to awaken the druid:

- The mobs only appear one at a time
- they attack after a small amount of time.
- after a few minutes the animation of him casting stops.

**How to reproduce:**

**How it should work:**
The mobs should appear in 2 waves. First 3x serpents then a lot slimes. 
they all should attack at once after a small set amount of time

**Database links:**

10m40s into the video is when the casting event starts
[https://www.youtube.com/watch?v=7oIJ8qoQ7Qs](url)

**Comment by UltraNix** [comment]
Fixed.
