### ISSUE TITLE
[Quest] What the Cold Wind Brings...

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#354]
The mob Ith'rix the Harvester and associated event do not appear to exist.

Thus this quest can not be started or completed.

This event should occur every 30 minutes near Warsong Hold.

https://www.youtube.com/watch?v=mGb7lHRbbV4
https://wowpedia.fandom.com/wiki/Ith%27rix%27s_Hardened_Carapace

**Comment by UltraNix** [comment]
Fixed.
