### ISSUE TITLE
The Deadmines, Mast Room - Gobin Woodcarver 

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#356]
**Description:**
Too many Goblin Woodcarvers

**How to reproduce:**

**How it should work:**
Ones that are marked.

**Database links:**
![image_2024-04-15_151620331](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/b378cda4-aa95-415c-94bb-0d2e9c6cbca4)

**Comment by Afgann** [comment]
fixed
