### ISSUE TITLE
The deadmins - Defias Cannon  event

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#357]
**Description:**
The mob that comes to check the door is missing 1x  Defias evoker and Overseer

**How to reproduce:**

**How it should work:**
Should be a group of 4 1x overseer, 1x evoker and 2 non elites

**Database links:**
![image_2024-04-15_152726763](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/0b89ee9c-a765-444a-8da2-9d8e1e6c1a3d)

**Comment by Afgann** [comment]
fixed
