### ISSUE TITLE
King Bangalash Patrol path too large

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#358]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
He patrols past his location.

**How to reproduce:**

**How it should work:**
He should only patrol the top of his hill and down to the base and back up  on all 3 sides

**Database links:**
![Screenshot 2024-04-15 181251](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/54d711ca-f1aa-4369-a842-4fd8187ef1ba)

[https://www.wowhead.com/classic/npc=731/king-bangalash](url)

**Comment by UltraNix** [comment]
Fixed.
