### ISSUE TITLE
Explosive shot not working properly.

### ISSUE THREAD

**Issue by Mixetaa** [gamefreedomgit/Frostmourne#36]
**Description:**The Problem: Back then, as on many other spells like flamestrike, you could stack different ranks of it getting the effect of each rank. This is not the case on Frostmourne(ptr), in which the application of explosive shot (rank 3) will overlap the DoT of explosive shot (rank 4) previously used during LnL proc.
This interaction is working properly on classic.

There's a link provided that has a source from back then stating how this works.
https://www.wowhead.com/wotlk/spell=56344/lock-and-load#comments

Worth to note that the DoT from each explosive shot rank do not share a spell ID (they are different spell ID's)

I'll add a video showing how it should work: https://www.youtube.com/watch?v=oapdS8BUCh0

**Comment by Tednugg** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/158357485/fb2a6973-589e-4b38-bd53-f7e1795b0d65)
This is the comment he's referring to in the wowhead link.

**Comment by Dalvae** [comment]
that's cheating

**Comment by Afgann** [comment]
fixed
