### ISSUE TITLE
Stonetalon Mountains - Missing Rogue Flame Spirits

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#360]
**Description:**
 Missing Smoldering Fire Spirits along northern entrance to The Scarred Vale - See image.

Only saw 3 in total.

**Database links:**

[https://www.wowhead.com/wotlk/npc=4036/rogue-flame-spirit#map](url)

![image_2024-04-16_123823639](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/fbfbfc1b-1baf-4b99-a403-85249184f5da)

**Comment by Afgann** [comment]
fixed
