### ISSUE TITLE
Stonetalon Mountians - Covert Ops - Alpha/Beta  works but event doesn't

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#361]
**Update 01.05.24** 

- Quest now appear in quest log, 
- can now be completed 
- but the event is still does not work as it should

The quest items both have the glitter on them and are lootable but you would have to fight your way to it to get it.

But the wagons you blow up, explosives and event does not work.

How it should work

It should be the same for both quests, Covert Ops Alpha, Cover Ops Beta

**How to reproduce:**

**How it should work:**
- go to the explosives wagons.
- place explosives on wagon - Blue at lumber mill. Red at mine
- use appropriate trigger  (blue for blue, red for red) to activate explosion
- all mobs near the quest item will run towards explosion
- player can go loot quest item.

**Database links:**
[3:15s into video shows the event as it should happen.](https://youtu.be/XohhDItp7Xs?t=198)

[https://www.wowhead.com/wotlk/quest=1080/covert-ops-beta](url)
[https://www.wowhead.com/wotlk/quest=1079/covert-ops-alpha](url)

Applying the explosives
![Screenshot 2024-04-30 222043](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/82222f38-711f-478c-a5ea-b59bc695e817)

Trigger does not work.
![Screenshot 2024-04-30 222130](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/62f33411-4b97-4a7e-8626-e465fa39692b)

**Comment by jack40melb** [comment]
Update 01.05.24  Quest can now be completed but the event is still does not work as it should

The quest items both have the glitter on them and are lootable but you would have to fight your way to it to get it.

But the wagon you blow up, explosives and event does not work.

How it should work

- go to the explosives wagons. 
- place explosives
- use approriate trigger to activate explosion
- all mobs near the quest item will run towards explosion
- player can go loot quest item.

[3:15s into video shows the event as it should happen.](https://youtu.be/XohhDItp7Xs?t=198)

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
