### ISSUE TITLE
Azshara - Bear's Head - Missing TImbermaw mobs near some camps

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#362]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

**How to reproduce:**

**How it should work:**
![image_2024-04-16_183553092](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/b47000a8-c68e-4df6-9c95-4bc900246abe)

![Screenshot 2024-04-16 183417](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/6cb8a875-e747-4e6a-a9cf-200697a1736d)

**Comment by Afgann** [comment]
fixed
