### ISSUE TITLE
Azuremyst Island  2x/3x population of creatures

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#363]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Should be one of each spaced out, heaps of All mobs/types  - creatures to humanoids over the island. 
**How to reproduce:**

**How it should work:**
It should be only like a combination of 3 types spaced out  to each other or like 2x of 1 with 1x of another within a 30yr radius in a triangle shape. Where they patrol into the center of the triangle. sometimes 1 or 2 meet up in the center.

**Database links:**

![Screenshot 2024-04-16 223942](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/1bb708a0-c52f-4982-966d-ea105277eebc)
![Screenshot 2024-04-16 223721](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/46377d6e-c632-4a31-9757-35798243bd9b)
![Screenshot 2024-04-16 223700](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/dad7bd3a-9b01-468f-b432-77755867a93a)

![image_2024-04-17_110504308](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/feb71d34-871b-491f-981b-6510b5df67fb)

![Screenshot 2024-04-17 110332](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/87ad2597-405e-4685-9695-7783260290f5)

**Comment by WhitemaneIsa** [comment]
Seems to be fine now.
