### ISSUE TITLE
Azuremyst Island - Blood Elf Bandit, Multiple spawns at each location

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#364]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
At each location, all possible spawn points has a Blood elf bandit, instead of one

**How to reproduce:**
Go to a location and see

**How it should work:**
Each location has multiple spawn points for the blood elf bandit.  There should only be 1 at any given time. When he is killed he will randomly spawn in any other location, at any one of those spawn points. Making the player hunt for him is how it should be.

**Database links:**
[https://www.wowhead.com/wotlk/npc=17591/blood-elf-bandit#comments](url)

![image_2024-04-17_101353924](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/166dd20c-fc04-4cfa-a4c0-548d99cb547f)

![Screenshot 2024-04-17 093838](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/a0be224e-eadc-46fa-ad2a-10006be0035a)
![Screenshot 2024-04-17 094236](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/59cccc93-a636-42ee-b347-6ec340b50568)

**Comment by UltraNix** [comment]
Fixed.
