### ISSUE TITLE
Professions window takes a while to show categories 

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#365]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When you open the professions tab LW, Tailoring anything, it shows all the recipes as one list and not subdivided by their relevant categories. After a few mines of it being closed, it will open showing these

**How to reproduce:**
log into your toon, open your profession tab and see.

**How it should work:**
It should open with the categories first time. (like 2nd image)

**Database links:**

![Screenshot 2024-04-17 102000](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/9886dbba-7885-441b-81d1-b88d34f22819)
![image_2024-04-17_103415263](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/0c7c9b6b-44ed-4913-a415-2bc9e16d8bf1)

![Screenshot 2024-04-17 103007](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/81bde8ab-55ba-4201-8375-95f6395a0f9a)

**Comment by UltraNix** [comment]
I think it's a clientside bug.
