### ISSUE TITLE
Azuremyst Island  - Murgurgula  quest drop item cannot be looted by all of party members If on FFA

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#366]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Can only be looted by one person, when loot is on FFA. On group loot everyone can loot it

**How to reproduce:**
Make  a party set to FFA, kill npc and see if everyone can loot

**How it should work:**
Everyone should be able to loot it

**Database links:**
[https://www.wowhead.com/wotlk/item=23850/gurfs-dignity#comments](url)

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/18bd4e86-a6e7-4b30-8471-a5e2759d8b82)
Works okay to me.
