### ISSUE TITLE
Bloodmyst island - Named npcs appearing as trapped victims for quest They'r Alive, Maybe

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#367]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Upon freeing webs for [https://www.wowhead.com/wotlk/quest=9670/theyre-alive-maybe](url) Named npcs appear

**How to reproduce:**
Picked up quest

**How it should work:**
The named Npcs should only be in their own locations, not as trapped npcs

**Database links:**
[https://www.wowhead.com/wotlk/npc=17359/telathion-the-impure](url)
[https://www.wowhead.com/wotlk/npc=17715/atoph-the-bloodcursed](url)

![Screenshot 2024-04-17 131851](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/03b82d80-2a2e-4f21-8d70-7fbd55e272fb)

![image_2024-04-17_132758724](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/517498f9-3ab5-4c69-8841-35e21a390433)

**Comment by Afgann** [comment]
fixed
