### ISSUE TITLE
Bugged Quest: They're Alive! Maybe - Victims do not appear after webs broken

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#368]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Cleared all the Webs  1 full circuit and a half, not one of the victims appeared . On some webs you get just loot and it seems on those you get the credit for freeing the victims. You can still compete it but the npcs do not appear on breaking the webs

**How to reproduce:**
Pick up quest, break webs

**How it should work:**
There should be a chance that the webs spawn  a random creature or a victim. Not sure what the chance rate is, But you should be able to get the quest done before you go up the ramp to the top. See image of how it should be

**Database links:**
[https://www.wowhead.com/wotlk/quest=9670/theyre-alive-maybe#comments](url)
![Screenshot 2024-04-17 135138](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/5dedfbe7-41dd-45f9-a6a9-acaaf54b8334)

**Comment by Afgann** [comment]
fixed
