### ISSUE TITLE
Golden ! for quest Intercepting the Message hidden by Blue ?

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#369]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
ok, this one is a bit hard. Not sure if its a bug or just the way it is.

 After completing Irradiated Crystal Shards - [https://www.wowhead.com/wotlk/quest=9641/irradiated-crystal-shards](url) the NPC  **Vindicator Boros** will have a **BLUE ?**  Even though the quest **Intercepting the messenger** is still available.  So a player can easily skip this quest, which starts the end chain for the Draenei' and their story line in  Bloodmyst Island. Low Level quest tracking won't show the quest. ONLY by opening a chat dialogue with **Vindicator Boros**

**How to reproduce:**
Hand in Irradiated Crystal Shards, stand back and see.

**How it should work:**
No idea. I spent like 30mins+ killing sunhawk missives and googling it. Even Wowhead States that **Vindicator Boros** gives the quest but since l didnt see the GOLD ! over his head l didnt bother to open a dialogue window with him. The only way l found what to do was by reading the comments.

**Database links:**
[https://www.wowhead.com/wotlk/quest=9779/intercepting-the-message](url)

**Comment by UltraNix** [comment]
The Blue "?" comes from quest https://www.wowhead.com/wotlk/quest=9642/more-irradiated-crystal-shards
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/5ec4944d-2a1d-4fc2-9fab-979b6f9f4725)
If this quest (https://www.wowhead.com/wotlk/quest=9779/intercepting-the-message) was low lvl to you, then the blue marker is above it.
