### ISSUE TITLE
[Suggestion Approved] Demonic pact change

### ISSUE THREAD

**Issue by Samskie** [gamefreedomgit/Frostmourne#370]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Hello! I am here to suggest a change to the internal cooldown of Demonic Pact. Currently it has a 20 ICD, forcing you to time your pet attacks and attempt to get a good snapshot. Blizzard changed this to a 5 second (and then later 1 second) ICD, and making it so only a better pact would reapply.

https://www.reddit.com/r/blue_tracker/comments/w421b8/wow_kaivax_in_wrath_classic_warlock_update/
"In today’s new beta build, we’ve completed an update to Warlocks that should address a situation that has persisted since original Wrath of the Lich King.

Demonic Pact will no longer overwrite an existing Demonic Pact buff, unless:
There are less than 10 seconds left on the buff (e.g. it has been up for 35 seconds or more).
The spell power bonus of the new buff are higher than or equal to the power of the existing buff.
Additionally,

The internal cooldown of Demonic Pact has been lowered to 5 seconds (was 20 seconds).
This compensates for the changes above and helps ensure that Demonic Pact is refreshing on your target before it expires with a similar consistency to before this adjustment."

This was later changed to a 1 second internal cooldown, however I was unable to find the classic patch they did that.

It was suggested to me to post this here (https://discord.com/channels/1040715551531618365/1230663895597711451) Please let me know if you need more information or anything else from me.

**Comment by yamiamk** [comment]
PLSSSSS

**Comment by UltraNix** [comment]
not a bug. Discord is the place for suggestions.

**Comment by UltraNix** [comment]
Fixed.

**Comment by RadeghostWM** [comment]
@UltraNix yeah let's do this:)

**Comment by UltraNix** [comment]
Fixed.
