### ISSUE TITLE
Tanaris, Zul Farrak Dungeon Pyramid Event - 3 Issues

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#371]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
After the event starts, Sgt. Bly and co wait on top of the pyramid . 

- Takes about 7mins before he decends. 
- More than 4-5 waves of mobs appear. Next wave will appear before previous is cleared.
-  Sandfury Ayclotes Can agro/target/shoot players on top of pyramid  from the base with with shadow bolt  Range too far.
- [Weegli Blastfuse](https://www.wowhead.com/wotlk/npc=7607/weegli-blastfuse#comments) has the fastest gun speed like half a second. should be slower 

**How to reproduce:**
Start the event, and Kill the first wave and see

**How it should work:**

1. After first wave is cleared they should start to descend  and attack 2nd wave on the way down. 2nd wave should only appear after 1st wave is cleared or after a set amount of time. Not as close as it is current
2. Sandfury Acolyte should only agro when within normal range.  Their shadow bolt range should be 40yrd
3. Weegli Blastfuse should be a bit slower than that.

**Database links:**

[https://www.wowhead.com/wotlk/npc=8876/sandfury-acolyte#abilities;mode:normal](url)
[https://www.youtube.com/watch?v=mtBuWdd2EHk](url)

**Comment by arooks1** [comment]
I also tested this today, and can add that the mobs run "through" the pyramid and can get stuck under it. When the NPCs start moving from the top, they aggro the mobs under the pyramid and get tuck or die there as well.

![image](https://github.com/gamefreedomgit/Frostmourne/assets/115400565/fdf2d82b-88e7-4387-8909-86eb4e3c417d)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/115400565/4ddca343-c485-4c74-aabd-0a1256c61f8d)

**Comment by WhitemaneIsa** [comment]
Has been fixed already as I'm aware
