### ISSUE TITLE
Wetlands, Dun Algaz  - Dragonmaw Grunt does not run to player when attacked, Pathing issues

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#373]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
the grunts do not run to player when agroed
Pathing issues when running away.

**How to reproduce:**

**How it should work:**
they should run to  player. Should not run up/through buildings

![image_2024-04-20_131402297](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/108ddaa7-3b4f-4e7b-93d7-a9069d0ef651)

![image_2024-04-20_131052482](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/a2ecd1fb-dc12-49d1-81c4-23eeaffc816b)

**Database links:**

**Comment by Afgann** [comment]
fixed
