### ISSUE TITLE
Loch Mordan, Various mobs  various issues

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#374]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Mobs standing still
Not attack players on agro/attack
All mobs, zome wide

1. Stonesplitter Trogs  all typesclass, 
2. Mountain Buzzards
3. Bears
4. boars
5. Mo'gosh orges
6. Spiders
7. crocodiles

**Comment by Afgann** [comment]
fixed
