### ISSUE TITLE
Loch Mordan, Mo'grosh Stonghold missing mobs

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#375]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

 Missing mobs inside stronghold like other cave locations

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
I see mobs there - nothing to be missing here.
