### ISSUE TITLE
Zul Drak - A Tangled Skein (The quest is missing)

### ISSUE THREAD

**Issue by Naturlish** [gamefreedomgit/Frostmourne#376]
**Description:**
The quest **A Tangled Skein** is missing from the server.

**How it should work:**
Complete the required quests : 
1. Skimmer Spinnerets
2. Crashed Sprayer

Then it will unlock the quest: A Tangled Skein.

**Database links:**
https://www.wowhead.com/wotlk/npc=28284/specialist-cogwheel

**Comment by Afgann** [comment]
fixed
