### ISSUE TITLE
Titanium ore can't be prospected

### ISSUE THREAD

**Issue by thmf00** [gamefreedomgit/Frostmourne#378]
![obrázok_2024-04-20_212655811](https://github.com/gamefreedomgit/Frostmourne/assets/167646242/fd4f3c08-79f9-453b-b3d0-3c41e9f10cf1)

**Description:**
Titanium ore can't be prospected with JWC profession. In bag stays that "Titanium ore is prospectable", but after using prospect cast on Titanium ore comes a error "There are no gems in this". JWCer can't get Titanium powder, rare gems and epic gems in late phase.

**How it should work:**
Titanium ore should be prospectable. Prospecting titanium requires jwc lvl 450. - 10 titanium dusts can be traded into 1 jwc token in Dalaran via a repeatable quest. - You may get 2 gems of the same quality from 1 prospect, including 2 epics.

**Database links:**
https://www.wowhead.com/wotlk/spell=31252/prospecting#sounds
https://www.wowhead.com/wotlk/item=36910/titanium-ore
https://www.wowhead.com/wotlk/item=46849/titanium-powder#comments
https://www.wowhead.com/wotlk/currency=61/dalaran-jewelcrafters-token

**Comment by Godmatik** [comment]
Can't prospect it until patch 3.2 iirc

**Comment by UltraNix** [comment]
As above - not a bug.
