### ISSUE TITLE
Transmog disable set bonus

### ISSUE THREAD

**Issue by bilrage** [gamefreedomgit/Frostmourne#379]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I transmog the chest tier and it doesnt show up as equip

**How to reproduce:**
Transmog a tier equipment

**How it should work:**
It should keep the set bonus enable
![image_2024-04-20_224905778](https://github.com/gamefreedomgit/Frostmourne/assets/50302079/cf4dd0e0-64a4-4b08-bef9-ffa115c3eebb)

**Database links:**

**Comment by Iramtempus** [comment]
This is easily checked with PVP sets, as their bonuses are straight stat increases.
I imagine this is the same bug as all TMOGs where it is grayed out but still in effect.

**Comment by Iramtempus** [comment]
Just checked, this issue can be closed. It is a simple error in visual, the stats are still active.
![Non-TMOG](https://github.com/gamefreedomgit/Frostmourne/assets/88618448/56ca056e-994c-4855-a8a3-47c4050cc821)
![TMOG](https://github.com/gamefreedomgit/Frostmourne/assets/88618448/786a5f46-6277-4d22-957d-7dc64b37fa41)
