### ISSUE TITLE
[NPC][Missing Items][Dalaran] Missing rare gems in vendor

### ISSUE THREAD

**Issue by scrublama** [gamefreedomgit/Frostmourne#38]
**Description:**
Magistrix Lambriesse <Emblem of Heroism Quartermaster> is currently not selling any rare northrend gems 
Same would apply to Harold Winston <Jewelry Vendor>

**How to reproduce:**

**How it should work:**
Not 100% sure but I recall this NPC to sell rare gems on launch before t7 rather than after release.
And epic gems to come around t9 release.

**Database links:**
https://wotlk.cavernoftime.com/npc=31582#sells:100+1

**Comment by Afgann** [comment]
fixed
