### ISSUE TITLE
lvl 38 Dwarf Shaman - Call of water Quest, not avaliable

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#380]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I can't find any npc that offers the quest.  Its usually offered by [[Tuluun](https://www.wowhead.com/wotlk/npc=17212/tuluun)](url) Or
[https://www.wowhead.com/wotlk/npc=17219/sulaa](url)

Neither one offers it nor the shaman trainer in IF

Call of Earth was offered by the shaman trainer in IF to go to Azuremyst island trainer. And when l completed it, l was offered Call of Fire from  Tuluun also in Azuremyst Island. 

ON the Draneeni shaman,  Tuluun started the chain  with [https://www.wowhead.com/wotlk/quest=9500/call-of-water](url)

**How to reproduce:**
Complete Call of Earth and Call of Fire

**How it should work:**
Upon reaching level level 20, trainer should offer the starter quest

**Database links:**
https://www.wowhead.com/wotlk/quest=9500/call-of-water

**Comment by UltraNix** [comment]
Fixed.
