### ISSUE TITLE
Arathi Highlands  - Apprentice Kryten does not offer An Apprentice's Enchantment

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#382]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
level 48 shaman - The quest An Apprentice's Enchantment is part of a chain. NPC does not offer the quest.

**How to reproduce:**

**How it should work:**
He should offer the quest if your at the level, 

**Database links:**
[https://www.wowhead.com/wotlk/npc=2788/apprentice-kryten#starts](url)
[https://www.wowhead.com/wotlk/quest=691/worth-its-weight-in-gold](url)

**Comment by Afgann** [comment]
fixed
