### ISSUE TITLE
Arathi Highlands - Death from Below quest. Naga pathing issue

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#384]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When the Naga Attack, they appear on the hill, run down a little and then walk in the air. Not on the ground

**How to reproduce:**
Start the quest Death from Below [https://www.wowhead.com/wotlk/quest=667/death-from-below](url)

**How it should work:**
They should follow the ground

**Database links:**
![Screenshot 2024-04-22 171635](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/112f3c16-3634-45c6-ae10-23aee8bc3a62)
![Screenshot 2024-04-22 171656](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/34c0c9cb-14a3-4666-9429-d230b5c006e2)

**Comment by UltraNix** [comment]
Should be okay now.
