### ISSUE TITLE
Wetlands - Apprentice Duties, incorrect map mob location

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#385]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The Giant Crocadiles are in the northern part of wetlands, not near Menthril Harbour as the map shows.

**How to reproduce:**
 Pick up the quest, look on map

**How it should work:**

**Database links:**
![Screenshot 2024-04-21 105210](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/6788938a-337b-4ca4-b5ed-4b61f58dd2d1)

Correct lotion should be where the dots are [https://www.wowhead.com/wotlk/quest=471/apprentices-duties](url)

**Comment by Afgann** [comment]
fixed
