### ISSUE TITLE
66 Shaman. 56 Hit Rating = 4.35% is this correct? - (delete had the numbers wrongs)

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#387]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
 I thought at 80 you needed 26 hit rating = 8%

Is this correct?

![image_2024-04-24_231549935](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/bbf7ab18-8d2a-4b50-8988-dd0db0815152)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Godmatik** [comment]
"I thought at 80 you needed 26 hit rating = 8%"

huh?

**Comment by jack40melb** [comment]
NVM, l had it wrong.

**Comment by Godmatik** [comment]
You can close the issue yourself
