### ISSUE TITLE
Blade's Edge Mountains,  New mob 

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#388]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
According to a comment on wow head  "These wasps were removed in 2.1 when the Blade's Edge Plateau was turned into a questing area."

![image_2024-04-25_090306344](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/6b019bd6-77a3-45a7-afc1-719fb832198d)

**How to reproduce:**

**How it should work:**

**Database links:**
[https://www.wowhead.com/wotlk/npc=22194/spire-needler#comments](url)

**Comment by UltraNix** [comment]
Fixed.
