### ISSUE TITLE
Outlands, Nagrand - Missing NPC - Bro'Gaz the Clanless

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#389]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Seems to be a common issue with WOTLK private servers that this Rare is missing. Seached in all locations both  on WowheadClassic and Evowow and other WOTLK databases.

**How to reproduce:**

**How it should work:**
According to wow head, he patrols along these routes.
![Screenshot 2024-04-26 132657](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/15922381-3c02-4c0f-a1fa-fa52dce1c14f)

According to Evowow , he spawns in these locations
![image_2024-04-26_132804503](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/9db0a06c-439e-403b-8659-c6e95d794ca5)

**Database links:**
Comments suggest he patrols in either of the 3  locations
[https://www.wowhead.com/wotlk/npc=18684/brogaz-the-clanless](url)

**Comment by UltraNix** [comment]
Fixed.
