### ISSUE TITLE
[NPC][Northrend][Wrong item] <Grand Master Jewelcrafting Trainer> sells epic gem +10 stats

### ISSUE THREAD

**Issue by scrublama** [gamefreedomgit/Frostmourne#39]
**Description:**
-Timothy Jones <Grand Master Jewelcrafting Trainer> and probably all northrend jc trainers are selling epic gem design +10stats which should not be available until around t9 release.

+The equivalent to this patch is +6stats and is sold by him as a normal Train me profession skill.

**How to reproduce:**

**How it should work:**
-Timothy Jones <Grand Master Jewelcrafting Trainer> + all northrend jc trainers should not have the "Browse epic gems tab" available at this patch.

**Database links:**
https://wotlk.cavernoftime.com/item=49112
https://wotlk.cavernoftime.com/npc=28701#sells:0+1
https://i.gyazo.com/eb3d54ee7c29c9bb066b5a8bd6046eaf.jpg
https://i.gyazo.com/017e3ddb2abbaa938c59d6a24de0a6cd.jpg
https://youtu.be/KcHb0G6WnSo?si=AJ2WwytaWIbJxhmh&t=270

**Comment by Afgann** [comment]
fixed
