### ISSUE TITLE
Minor Borean Tundra bugs – Alliance Report

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#390]
1. [The Hunt is On](https://www.wowhead.com/wotlk/quest=11794/the-hunt-is-on)
- [Oculus of the Exorcist](https://www.wowhead.com/wotlk/item=35125/oculus-of-the-exorcist) does add the  gossip option to the NPCs on use.  However the NPCs do not get the shadowy/purple aura around them.
- [Tom Hegger ](https://www.wowhead.com/wotlk/npc=25827/tom-hegger), [Guard Mitchells](https://www.wowhead.com/wotlk/npc=25828/guard-mitchells), ["Salty" John Thorpe](https://www.wowhead.com/wotlk/npc=25248/salty-john-thorpe)
- [comment mentioning the glow](https://www.wowhead.com/wotlk/npc=25248/salty-john-thorpe#comments:id=738948)
- video from classic: https://www.youtube.com/watch?v=AC9MAANypZY&t=73s&ab_channel=Bue
- The hue is there on another free servers (prior classic release)

2. [Kvaldir Raiders](https://www.wowhead.com/wotlk/npc=25760/kvaldir-raider) and [Kaskala Defenders](https://www.wowhead.com/wotlk/npc=25764/kaskala-defender) are not fighting each other.
- https://wowpedia.fandom.com/wiki/Kaskala_Defender + https://wowpedia.fandom.com/wiki/Kvaldir_Raider?so=search
- Classic video. 1:01 forward: https://www.youtube.com/watch?v=4aIql-R0-C8&t=82s&ab_channel=Bue

3. Wailing Ziggurat emotes/says
- [Lurid](https://www.wowhead.com/wotlk/npc=26185/lurid) and [High Deathpriest Isidorus](https://www.wowhead.com/wotlk/npc=26171/high-deathpriest-isidorus) should have some convo time to time.
- Quotes at: https://wowpedia.fandom.com/wiki/High_Deathpriest_Isidorus
- 0:05 at 3y old video https://www.youtube.com/watch?v=BKiuYwRmmRo&ab_channel=JackGames

4. [Fizzcrank Survivor](https://www.wowhead.com/wotlk/npc=25773/fizzcrank-survivo)
- Missing emotes after being "summoned", is aggressive (1 HP Damage hits) instead of immediately porting away
- [WH comment](https://www.wowhead.com/wotlk/quest=11712/re-cursive#comments:id=838853)
- https://www.youtube.com/watch?v=h6kQRHCzZDg&ab_channel=WarcrafterSnorri

5. [Drake Hunt](https://www.wowhead.com/wotlk/quest=11919/drake-hunt)
- [Nexus Drake Hatchling](https://www.wowhead.com/wotlk/npc=26127/nexus-drake-hatchling) starts to fly back to orginal location upon getting quest credit. It should stay there and get Fireballed down in piece.
- 1:20 onward https://www.youtube.com/watch?v=7Udj_NAc6xA&ab_channel=TomSanGames

6. [Drake Hunt daily](https://www.wowhead.com/wotlk/quest=11940/drake-hunt)
- Has wrong mark, golden mark instead of blue for daily, at least when tracking the low level quests.

7. [Mustering the Reds](https://www.wowhead.com/wotlk/quest=11967/mustering-the-reds)
- Post-completion event does not occur.
- https://wowpedia.fandom.com/wiki/Mustering_the_Reds?so=search#Notes
- (non-wotlk) https://www.youtube.com/watch?v=fF91i71CwZ8&ab_channel=TheChroniclesofAzeroth

8. [Leading the Ancestors Home](https://www.wowhead.com/wotlk/quest=11610/leading-the-ancestors-home)
- The three elder spirits are always visible in the area. They should be seen only after using [the item](https://www.wowhead.com/wotlk/item=34715/tuskarr-ritual-object) at appropriate spot.
- After using the item, players is awarded credit, however the spirits do not react in any way. They should appear and walk to their stones.
- [Elder Kesuk](https://www.wowhead.com/wotlk/npc=25397/elder-kesuk), [Elder Sagani](https://www.wowhead.com/wotlk/npc=25398/elder-sagani), [Elder Takret](https://www.wowhead.com/wotlk/npc=25399/elder-takret)
- cata video https://www.youtube.com/watch?v=p_yeAZ24L3w&ab_channel=TomSanGames

**Comment by UltraNix** [comment]
Fixed.
