### ISSUE TITLE
[Quest Loot bugged] - Master loot + Group loot 

### ISSUE THREAD

**Issue by Iramtempus** [gamefreedomgit/Frostmourne#391]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
If in a party and on a "loot quest", the loot that is shared will bug the amount of quest items dropped. 
This seems to be a bug between;
AOE Looting & Shared Quest drops.

**How to reproduce:**
See video below.

**How it should work:**
If working correctly, both players should get the quest item. If killing 3 wolves, you should in theory get "3 x (Player numbers)" pelts, 3 for each player)

**Database links:**

See video:
https://www.youtube.com/watch?v=g4VdXcQxNZ8

**Comment by Iramtempus** [comment]
Tested after the latest push. Seems to be working as intended now! 👍

**Comment by UltraNix** [comment]
Fixed.
