### ISSUE TITLE
Quest Gnogaine - Mobs outside instance wont allow you to collect radation.

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#393]
**Description:**

You should be able to fill the vial from the mobs outside the instance 

- Caverndeep  Pillager 
- Irradiated Invaders

I did an entire loop killing all but the quest item  - Empty Leaden Collection Phial  wouldnt work on any of them

**How to reproduce:**

**How it should work:**
Either mob outside allows you to complete the quest. Then you get the 2nd part to go inside the instance for the next item

**Database links:**
See comments  [https://www.wowhead.com/classic/quest=2926/gnogaine#comments](url)
[Empty Leaden Collection Phial](https://www.wowhead.com/classic/item=9283/empty-leaden-collection-phial)

**Comment by UltraNix** [comment]
It works okay.
Mobs must be alive.
Must be used on Irradiated Invader or Irradiated Pillager.
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/3faef13a-e966-42a1-a344-b4cec4f294f7)
