### ISSUE TITLE
Sunwell Timewalking - M'uru

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#396]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Dark Fiend(npc=25744) should completely disappear upon using any kind of dispel on them.
Currently they are completely broken. They show up on the dispel log ONLY when using mass dispel, however, it does not affect them at all. Single target dispels also show "Invalid Target". They explode regardless of what you do.

They are also un-killable, staying at 1 hp if attempting to do actual damage to them. This makes the boss killable only if you skip phases with extreme damage.

-> Dark fiends do not spawn in phase2. They should, one after every Darkness spell, in the exact puddle of the darkness.

**How to reproduce:**

**How it should work:**
Mass dispel AND single target dispels(dispel, purge, tranq shot) should work on them, causing them to completely disappear and not explode.

**Database links:**

**Comment by Afgann** [comment]
fixed
