### ISSUE TITLE
Caster/Ranged mobs LoS+Pathing issues

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#398]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Currently if you Line of Sight a mob with caster/ranged capabilities, it stands in place for a while and removes combat and goes back to its position shortly after.
This is quite bad, even abusable. For example, in dungeons/raids mobs have infinite leash range unless they are forced to evade is so called "safe spots". Currently you simply need to LoS a mob to remove combat with it.
This is bad even for legitimate situations. For example, a tank would usually LoS multiple mobs in order to stack them properly. On this server it will simply deaggro the mobs instead.

**How to reproduce:**

**How it should work:**
A ranged mob should do a check if it is able to cast/ranged attack, and if not, it should simply switch to melee and follow its target until its designated leash range.

**Database links:**

**Comment by Afgann** [comment]
fixed
