### ISSUE TITLE
Sunwell Timewalking - Teleporter NPC

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#399]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
https://www.wowhead.com/tbc/npc=25632/vindicator-moorba#comments
This is an NPC that offers a gossip option to teleport you to the most recent boss you've killed up until M'uru.
Currently, he does not offer this option, making every wipe an incredibly long walk.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
