### ISSUE TITLE
Racial shift reverting back 

### ISSUE THREAD

**Issue by Galatosaurio** [gamefreedomgit/Frostmourne#40]
**Description:**
I created an Undead paladin and swapped racial to Blood Elf. When I relogged after being offline for a while my racial was back to Undead with no way to changing it back

**How to reproduce:**
Create Undead paladin, swap racial, log off, log back on

**How it should work:**
Once you racial shift to another race it should remain as such

**Comment by Galatosaurio** [comment]
Just checked with my orc with troll racial and it also swapped back, so it seems to happen regardless of race or class

**Comment by Afgann** [comment]
fixed
