### ISSUE TITLE
Sunwell Timewalking - Complex combat issues

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#401]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I'll make this post as a collection of bugs that I feel might be related, but I cannot be sure, might even happen outside Sunwell instance for all I know.

1. Noticed during and after Brutallus+Felmyst what I'd call a "pseudo-combat bug". After Brutallus death, standard combat was exited, people could drink and buff, however, potion used during Brutallus was still on cooldown saying "potion cooldown will start after exiting combat" - this means there was some kind of combat trigger still active in the background? -> this could happen because of how Brutallus and Felmyst are currently linked combat-wise.
The green puddles and skeletons that remain after wipe also put players in combat from far away even if they didn't attack them - could also be the issue.
This bug also continued to happen throughout the whole raid. The only way to get rid of potion cooldown was to release spirit after wipe (not even death+healer ressurect removed the cooldown!)

2. Cooldowns+bloodlust not being reset upon boss kills/wipes(boss despawn). The wipe/boss reset might be because some bosses like kalecgos have a weird script to despawn if you fail to kill him in the proper way and it doesn't trigger the cd reset and bl debuff remove.

However, I think this is also connected to point 1. After Eredar Twins kill I noticed I still had bloodlust debuff. This might happen due to that pseudo combat trigger being active making the server think there is still some kind of combat active, therefore not firing the remove cds+bl script?

**Comment by Afgann** [comment]
fixed
