### ISSUE TITLE
[Sunwell Plateau Timewlaking] Eredar Twins Flame Touched

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#403]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
During the encounter Alythess' tank can sometimes go from 0 to 20 stacks of Flame Touched after a single cast of Blaze, even if the tank immediately moves out of the fire

**Comment by Afgann** [comment]
fixed
