### ISSUE TITLE
Durator  - Canaga Earthcaller keeps Gold ? after completing the Call of the Earth Quest chain for shamans

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#404]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
After completing the final [Call of the Earth](https://www.wowhead.com/wotlk/quest=1518/call-of-earth), Quest give Canaga Earthcaller still has the gold  Quest complete over its head. allowing you  to pick up a 2nd Earth Sapta

**How to reproduce:**
Complete the first stage, pick up the 2nd stage which gives the Earth Sapta for the 3rd Stage, then complete the 3rd stage.

**How it should work:**
The Earth Caller should only offer the Earth Sapta (or replace it again) till you complete the final quest only. After which it should dissappear

**Database links:**
[Call of the Earth Part 1](https://www.wowhead.com/wotlk/quest=1516/call-of-earth)
[Call of the Earth Part 2 - rewards Earth Septa](https://www.wowhead.com/wotlk/quest=1463/earth-sapta#comments)
[Call of the Earth Part 3 - Final](https://www.wowhead.com/wotlk/quest=1518/call-of-earth)

![image_2024-04-28_105127831](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/41e1f752-fecb-4080-8c0a-8b8e8ec8ca04)

**Comment by UltraNix** [comment]
Fixed.
