### ISSUE TITLE
Valanyr procs

### ISSUE THREAD

**Issue by SilversRayleigh98** [gamefreedomgit/Frostmourne#407]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Valanyr doesn't proc at all

**How to reproduce:** valanyr should proc shields

**How it should work:** valanyr should proc shield after a couple of casts but it doesn't at all

**Database links:**

**Comment by UltraNix** [comment]
@SilversRayleigh98 Please, provide some proofs for that.

**Comment by UltraNix** [comment]
https://www.wowhead.com/wotlk/item=46017/valanyr-hammer-of-ancient-kings#comments:id=708712
According to this, it's not a bug.
