### ISSUE TITLE
[NPC] Dalaran Apprentice - Not running away

### ISSUE THREAD

**Issue by Iramtempus** [gamefreedomgit/Frostmourne#408]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Not an important bug, but these caster mobs do not flee when they get low on HP, they just freeze in spot doing nothing.

**How to reproduce:**
Tag the mob, lower it until "Attempts to run away in fear!"

**How it should work:**
Any mob with the fleeing ability should attempt to run to a close friendly NPC if in range(?)

**Database links:**
https://wowwiki-archive.fandom.com/wiki/Dalaran_Apprentice

**Comment by UltraNix** [comment]
It works okay if there are nearby friendly creatures (range is 30 yards).

**Comment by UltraNix** [comment]
@Iramtempus Yep - that part is going to be fixed.

**Comment by Iramtempus** [comment]
@UltraNix You da man! <3

**Comment by UltraNix** [comment]
Fixed.
