### ISSUE TITLE
[NPC] Moonrage Elder - Too Much Healing

### ISSUE THREAD

**Issue by Iramtempus** [gamefreedomgit/Frostmourne#409]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The healing output combined with the insane mana regen of this mob it leads to near to impossible pulls even with just 1 additional mob. It seems to be healing way to much compared to what it should do. 

**How to reproduce:**
Tag it and check

**How it should work:**
Here I actually don't know, I was trying to find numbers but did not find any in the normal databases.
This might actually be working as intended but it seems too be too highly scaled for some reason.
The database doesn't even link a chain heal. (Yes I know its the classic database)

**Database links:**

https://www.wowhead.com/wotlk/npc=1896/moonrage-elder#abilities

**Comment by UltraNix** [comment]
Fixed.
