### ISSUE TITLE
Calendar and events is messed up

### ISSUE THREAD

**Issue by scrublama** [gamefreedomgit/Frostmourne#41]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Calendar and events is messed up, also missing darkmoonfaire every month

![image](https://github.com/gamefreedomgit/Frostmourne/assets/24984413/f60c8840-62d4-4c63-9b79-2a4496d34110)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
