### ISSUE TITLE
Burning Steppes - Drakes (large black dragons) pathing issues

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#410]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Region wide, all types of drakes tend to dip into the ground part way during their patrol paths.

- [Black Drakes](https://www.wowhead.com/wotlk/npc=7044/black-drake)
- [Searscale Drakes](https://www.wowhead.com/wotlk/npc=7046/searscale-drake)
- [Scalding Drakes](https://www.wowhead.com/wotlk/npc=7045/scalding-drake)
 
![Screenshot 2024-05-03 124139](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/22a20ab9-80c5-4025-aca5-31268dc946f4)
![Screenshot 2024-05-03 134629](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/cd04b34e-9909-4e20-94cc-a3dc8b35543a)

**Comment by Afgann** [comment]
fixed
