### ISSUE TITLE
Ebon Gargoyle's Snapshot doesn't works correctly

### ISSUE THREAD

**Issue by Vesfire** [gamefreedomgit/Frostmourne#412]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I was testing the snapshot with diverses combinations when realize something curious, the gargoyle always hits 29 ebon gargoyle, so takes my attention. When did the next snapshot, targeted the gargoyle to watch it casting bar and seems like Gargoyle Strike has GCD.

**How to reproduce:**
When gargoyle casts Gargoyle Strike, stays quiet for a miliseconds without casting, thats what happens when you reach the haste cap with casters, but not the case of gargoyle, due to gargoyle have not got GCD. Therefore, there are no reasons to choice troll instead orc, no reason to choice haste trinkets over Str or attack power, because a Bloodlust + Speed potion + Hyperspeed accelerator (engineering enchant) gives you an amount of 840 and your gargoyle cast 26 strikes, which meas a waste of racial hability, in other words a mediocre player can snapshot the gargoyle same as the better dk in the world because you have not to worry about the procs.

**How it should work:**
Gargoyle has unlimited amount of casts, because has no GCD, which means if you have 100 millions of haste, then the gargoyle gonna cast 100 millions Gargoyle strike. 
Here you got the comparison between:

**** a 65 haste build + Hyperspeed accelerator + Speed potion + Bloodlust (30% haste) + Icy talons (20% haste) + Unholy presence (15% haste). a total of 905 Haste + 65%      **(26 strikes)** 
![WoWScrnShot_050324_032936](https://github.com/gamefreedomgit/Frostmourne/assets/160279264/b0377939-31e3-49f6-8621-a2679ac922fd)

**** versus a 718 haste build + hyperspeed accelerator + speed potion + comets trail + mark of norgannon + some passives procs + Berseking (20% haste) + Bloodlust (30% haste) + Icy talons (20% haste) + Unholy presence (15% haste) with a total of  2790 haste + 85%        **-_____-   just 29 strikes**
![WoWScrnShot_050324_033102](https://github.com/gamefreedomgit/Frostmourne/assets/160279264/fba3753c-2ec6-43f7-81bc-ff6db2c83fa0)

                                                                 If you read the post thanks for you attention, and hope you fixe it =D, have a good day.
**Database links:**
https://www.wowhead.com/wotlk/spell=16997/gargoyle-strike
https://www.youtube.com/watch?v=cEvqZDQkPQo

**Comment by Iramtempus** [comment]
This subject has already been covered in a thread on the discord under Frostmourne Suggestions -> "Please remove the UH DK changes makes class less fun".
The current state is a middle point between dev teams and staff. I imagine this topic has been closed from the staff PoV.

**Comment by Manpower99** [comment]
Its not a gcd, its a delay after cast. it is the correct approach and the most blizzlike way of how gargoyle should work.
but i have to say that the current delay after each cast under alot of haste is extremely delayed.
if radeghost or any of the dev team are looking at this thread please consider lowering the randomized spell batching delay on gargoyle when it is super hasted to less than a 0.7 (700ms) max threshold. according to your post on discord i see the amount of MS delay after each cast and it would be nice if the thresholds get reduced abit. 300 to 500 would make more sense since the median would be close to 400 (0.4) which would be more consistent with the classic ai spellbatching

**Comment by RadeghostWM** [comment]
Working as intended.
