### ISSUE TITLE
[Dungeon] [Crash] Ormorok the Tree Shaper in Nexus – Crystal Spikes crash server

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#413]
[Ormorok the Tree-Shaper](https://www.wowhead.com/wotlk/npc=26794/ormorok-the-tree-shaper) crashes the server when he uses [Crystal Spikes](https://www.wowhead.com/wotlk/spell=57082/crystal-spikes) (or 57083).
Situation: Prot warrior, affli lock, rogue, arms warrior, resto shaman. Mixed A+H group. Heroic version through random dungeon finder.
Shaman said he did the boss a day earlier and it was fine.

**Comment by Afgann** [comment]
fixed
