### ISSUE TITLE
[Quest] [NPC] Mage-Lord Urom quest, Oculus – Image of Belgaristrasz does not spawn on Urom's corpse

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#414]
[Image of Belgaristrasz](https://www.wowhead.com/wotlk/npc=28012/image-of-belgaristrasz) should spawn on corpse of [Mage-Lord Urom](https://www.wowhead.com/wotlk/npc=27655/mage-lord-urom) so the player can hand in [the quest](https://www.wowhead.com/wotlk/quest=13127/mage-lord-urom) and take [the next one](https://www.wowhead.com/wotlk/quest=13128/a-wing-and-a-prayer).

Image did not spawn on Urom's corpse and stayed on the previous position, where [Varos Cloudstrider](https://www.wowhead.com/wotlk/npc=27447/varos-cloudstrider) was killed.

1:40 https://www.youtube.com/watch?v=mwn7Y0XTGtw&ab_channel=zanbeef

**Comment by UltraNix** [comment]
Fixed.
