### ISSUE TITLE
Dire Maul West Instance - Various issues

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#416]
**Court of the highborne** 

Few too many  [Eldreth Apparition](https://www.wowhead.com/wotlk/npc=11471/eldreth-apparition), [Eldreth spirit](https://www.wowhead.com/wotlk/npc=11472/eldreth-spirit#drops;mode:normal), [Eldreth Phantasm](https://www.wowhead.com/wotlk/npc=11475/eldreth-phantasm) in the packs. They should  be packs of 3 with  maybe a single 1 in between 

![Screenshot 2024-05-04 124334](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/9441ee5f-1e9d-4a4a-8cb5-0ad0ff8e65ac)

[It should be more like this. 5:50s into video](https://youtu.be/iPJfi3GIRBY?t=306) 

**Prison of Immol'thar** 

Door to Library is already open before end boss is dead. It should only open once Immol'thar is dead.
![Screenshot 2024-05-04 130213](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/5d9359c1-0cab-40ba-b368-f31c5f2f6197)

Missing mobs
I think  there should  be a few more stationary groups of  [1x Arcane Torrents](https://www.wowhead.com/wotlk/npc=14399/arcane-torrent) with  [4x Arcane Feedback](https://www.wowhead.com/wotlk/npc=14400/arcane-feedback) dotted along the ring of the room.

Missing a few  single  [Residual Monstrosity](https://www.wowhead.com/wotlk/npc=11484/residual-monstrosity) dotted in between the packs.  think some patrol the room (not 100%sure)

![Screenshot 2024-05-04 130310](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/dee6fd56-ce67-40d9-8608-306da567e9bd)

[9:15s into video](https://youtu.be/iPJfi3GIRBY?t=555)

**[Highbourne Summoner](https://www.wowhead.com/wotlk/npc=11466/highborne-summoner#comments)** - Do not attack Immol'Thar once the shield is taken down. They stand still
 
![Screenshot 2024-05-04 130720](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/f4a44115-e45d-4000-bc32-cc05dc5007cb)

They should attack like this 10:50s into video.  https://youtu.be/iPJfi3GIRBY?t=650

The Athenaeum
End boss loot chest should spawn under the stairs
![Screenshot 2024-05-04 131433](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/4430ebd2-d260-4918-906e-ea3af180f51c)

![image_2024-05-04_143905392](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/3665f242-3758-4640-aa49-bc64539e3f41)

**Comment by UltraNix** [comment]
```
Prison of Immol'thar
Door to Library is already open before end boss is dead. It should only open once Immol'thar is dead.
```
https://youtu.be/iPJfi3GIRBY?t=576
You can clearly see there is no door there.

**Comment by jack40melb** [comment]
RE Dire Maul West door to Library

The door is recessed inside the passageway.  you can see it in the video  you linked to me but you have to slow it down.

From ptr
![Screenshot 2024-05-09 105208](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/85ebf3b0-a3f6-461d-a902-d9e5ba470858)

[From 9:30 to 9:36 you can see the door in the video](https://youtu.be/iPJfi3GIRBY)

From video
![Screenshot 2024-05-09 105208](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/aabb82c1-69e4-4ec0-8894-15ea4479a982)

![Screenshot 2024-05-09 105759](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/dc8e661b-7eb9-439b-a73e-1bf50808603a)

![Screenshot 2024-05-09 105640](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/63e33dbd-722d-4b6c-8fbc-fea9f04b0ce1)


It should be here
![Screenshot 2024-05-09 105640](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/f8db8e55-1894-4917-a906-19c3b7dd75c7)

**Comment by UltraNix** [comment]
Fixed.
