### ISSUE TITLE
Dire Maul North Instance - various issues

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#417]
[Gaurd Mol'Dar](https://www.wowhead.com/wotlk/npc=14326/guard-moldar#comments)  is stationary. He should patrol the Upper side of the courtyard, down the ramp to the other side and then that side before returning.

As shown in the pink/yellow. Not sure if he goes up the green section. 
![Screenshot 2024-05-04 144830](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/f15ad114-4d4b-453c-af87-3587d8f3beb4)

[Guard Slip'kk](https://www.wowhead.com/wotlk/npc=14323/guard-slipkik) - pace seems too fast. l think he was faster than walking but slower than what he is now.

[Gordok warlock](https://www.wowhead.com/wotlk/npc=11448/gordok-warlock)  Does not face player when agroed. they stay facing the same direction they appear in.

![Screenshot 2024-05-04 150036](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/abb1d626-cf13-4715-aa80-f8e6ac2c0694)

Gordok Seat (end boss) 

Gordok Mastiffs dont belong there
 
![Screenshot 2024-05-04 150306](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/3b53e6e0-8227-49a0-9e38-96b3dcf7cb30)

**Comment by UltraNix** [comment]
Fixed.
