### ISSUE TITLE
Death Grip unusable due to path issues

### ISSUE THREAD

**Issue by AMInxs** [gamefreedomgit/Frostmourne#418]
[//]: # (REMEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Death Grip is unusable on mobs due to path issues in majority of areas.

**How to reproduce:**
Try to use it on any random mob in the world/dungeons.

**How it should work:**
You should able to grip stuff :)

**Database links:**
https://www.wowhead.com/wotlk/spell=49576/death-grip

**Comment by Afgann** [comment]
fixed
