### ISSUE TITLE
Auto Learn Bug - Berserker Stance warrior

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#419]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Currently autolearn is giving another hidden berserker stance aura that is giving the 3% crit ( possibly the negative aspect of berserker stance also ).

**How to reproduce:**
Make a Warrior be in battle stance and relog > Check your character stats you'll notice a 3% increase in crit > go berserker stance you'll notice another 3% increase in crit > go out of berseker stance and notice a 6% reduction in crit.

A similar autolearn bug existed in maelstrom cata server where every warrior was getting the berserker stance benefit 

**How it should work:**
At appropriately level30 should learn one berserker stance automatically that isnt automatically activated on relogging.

**Database links:**
https://www.wowhead.com/wotlk/spell=2458/berserker-stance#comments

**Comment by Afgann** [comment]
fixed
