### ISSUE TITLE
[Event] {Darkmoon}

### ISSUE THREAD

**Issue by GM-Nightmaree** [gamefreedomgit/Frostmourne#420]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
darkmoon event is not active or even appears in calendar 

**How to reproduce:**
.event activelist doesnt even show darkmoon
**How it should work:**
The Darkmoon Faire arrives on the first Sunday of each month and leaves at the end of the day the following Saturday. It rotates among three static locations in Elwynn Forest, Mulgore, and Terokkar Forest.

**Database links:**
https://www.wowhead.com/wotlk/event=374/darkmoon-faire
![image](https://github.com/gamefreedomgit/Frostmourne/assets/157993777/b21f37ab-e4e4-4bce-970e-ce024870b6e9)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/157993777/bb86e11a-986b-4507-97ac-94082267546d)

**Comment by UltraNix** [comment]
Fixed.

**Comment by WhitemaneChronus** [comment]
Similar issue happened today, even though according to the calendar darkmoon should end on Saturday 13th, the event was not active.
Event is currently reenabled by GM Isa, I'm reporting this in case for future. 

![Screenshot 2024-07-12 103721](https://github.com/user-attachments/assets/f072b2e6-3f04-4032-b243-231f684a44e9)
![image](https://github.com/user-attachments/assets/3820acca-b10a-45cf-b7db-ce4ca95ba589)

**Comment by WhitemaneIsa** [comment]
I manually disabled it now after manually enabling it.

**Comment by UltraNix** [comment]
Fixed.
