### ISSUE TITLE
Mobs not moving

### ISSUE THREAD

**Issue by arooks1** [gamefreedomgit/Frostmourne#422]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Mobs seem to be bugged today, they are not moving. Tried out various dungeons in Outland and in Org. If you walk up to them they do attack as normal, but they do not move. UPDATE, tried out in the world, also seem to be bugged now.

**How to reproduce:**

**How it should work:**

**Database links:**
![image](https://github.com/gamefreedomgit/Frostmourne/assets/115400565/5b09388e-3a95-4960-850c-fcc9781ee9bd)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/115400565/0dba74db-559f-48ee-80bc-83599d0c016b)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/115400565/cab36326-a699-4861-b469-bbe6af514a3e)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/115400565/0b11660b-36c8-473a-a516-4a30a402a557)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/115400565/a2e307e8-db18-497c-b879-e13a896ed2c9)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/115400565/787c6494-41f7-4ab1-8cff-29bb707582c2)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/115400565/5ed6f04a-aac6-4a04-90a1-63cb70390a03)

**Comment by UltraNix** [comment]
@arooks1 Can you test it again? Seems to be okay now

**Comment by arooks1** [comment]
> @arooks1 Can you test it again? Seems to be okay now

Yeah works fine today, great!
