### ISSUE TITLE
Severe pathing issue on multiple floor levels

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#423]
**Description:**
There is a really bad pathing issue affecting both mobs and NPCs, happening when pathing over multiple floors level, for example when there is a cave underneath. They either fall down or start bugging out

**How to reproduce:**
Pull mobs located on top of a cave, such as at fargodeep mine or the gnolls cave in ghostlands
Go to Undercity and check Kraxx and Harbringer Balthazad pathing. At some point of their pathing they start "fly hacking" through undercity ceiling before coming back down 10 sec later.

![WoWScrnShot_050724_200453](https://github.com/gamefreedomgit/Frostmourne/assets/45928535/637dc6b6-fd17-4a01-afa0-8a703ebe5b0d)

**Comment by Iramtempus** [comment]
Haha yeah, Undercity have multiple patroling NPCs who tend to fly.

**Comment by UltraNix** [comment]
Fixed.
