### ISSUE TITLE
Ardent Defender not procing

### ISSUE THREAD

**Issue by Retyun** [gamefreedomgit/Frostmourne#424]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Ardent defender sint working properly. The cheat death doesn't happen

**How to reproduce:**Play prot pally spec 3/3 into Ardent Defender. Get attack until 0

**How it should work:**Once you hit 0. You should have a debuff with an image of ardent defender procing. Your health set back at 30% of max life.

**Database links:**https://www.wowhead.com/wotlk/spell=31852/ardent-defender

**Comment by UltraNix** [comment]
Fixed.
