### ISSUE TITLE
Crossfaction and Mind Controls

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#425]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Similar issue that happened in early T11 Maelstrom
Crossfaction currently bugs ALOT OF SPELLS.
but for this report it is mind controls in bossfights
Example : Kel'thuzad mind controls are friendly and sometimes dont stop being agressive afterwards.
Unsure about player mind controls but possibly the same issue due to crossfaction?.

**How to reproduce:**
Fight Kelthuzad in a raid of multiple people of different factions ally/horde
Notice issues relating to MC's with them being friendly and thus unable to Crowd Control

**How it should work:**
Obviously should work properly, likely not a simple thing to fix due to how crossfaction is, as its not an intended thing in the actual wotlk game.

**Database links:**

**Comment by Afgann** [comment]
fixed
