### ISSUE TITLE
Utgarde Keep (normal) Mob pathing issue

### ISSUE THREAD

**Issue by jack40melb** [gamefreedomgit/Frostmourne#426]
**Description:**
On the Njorn Stairs (between 1st boss and 2nd)  there is a a single group of Dragonflayer Strategist + Savage Worg that has pathing issues **when they go back up the stairs**. At certain points on their path back up, they tend to go striaght up through the roof and down through the floor,

**How to reproduce:**
Go to location and watch them

**How it should work:**
should just walk up and down the stairs

**Database links:**

![Screenshot 2024-05-11 095230](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/1ba9b5c5-3fed-44e3-b2cf-2dc6edd506f5)
![Screenshot 2024-05-11 100505](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/bac82f05-0579-4989-948d-fc7b1c0fa978)
![Screenshot 2024-05-11 095206](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/239a6409-e564-4a68-895f-7aac6d8ebb83)
![Screenshot 2024-05-11 100936](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/dae918db-3417-4ed3-8af2-faca0f644280)
![Screenshot 2024-05-11 100854](https://github.com/gamefreedomgit/Frostmourne/assets/6733191/ee96c69d-b13d-4263-be9a-15b93ce6d836)

**Comment by UltraNix** [comment]
Fixed.
