### ISSUE TITLE
Many humanoids can not swim / do not follow you into water

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#428]
I noticed many humanoid enemy mobs simply instantly reset if you go into water.

They should be able to swim and go after you.

**Comment by UltraNix** [comment]
@Godmatik Give us some examples.

**Comment by Godmatik** [comment]
Kolkar mobs in Barrens

**Comment by UltraNix** [comment]
@UltraNix This one is missing proper inhabit type - we'll be fixed.
Do you have more of these?

**Comment by Godmatik** [comment]
Yes - venture Co drudgers. 

Will let you know if I come across any others.

**Comment by UltraNix** [comment]
Fixed.
