### ISSUE TITLE
NAXX25 grobbulus pathing through the air and walls

### ISSUE THREAD

**Issue by gforghieri** [gamefreedomgit/Frostmourne#429]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
NAXX25 grobbulus pathing through the air

**How to reproduce:**
Go into naxx, check grobbulus pathing, he is going through the air, through walls etc.

**How it should work:**
Self explanatory

**Database links:**
N/A

**Comment by UltraNix** [comment]
Fixed.
