### ISSUE TITLE
[Distance value] Creatures/game objects range is limited to 100 yards

### ISSUE THREAD

**Issue by scrublama** [gamefreedomgit/Frostmourne#43]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Seems like most, if not all, creatures/game objects range is limited to 100 yards
https://streamable.com/l0zwks

**How to reproduce:**

**How it should work:**
Sure npcs and players could be 100 yards to save CPU but some objects/bosses etc could have longer range

**Database links:**

**Comment by Afgann** [comment]
fixed
