### ISSUE TITLE
OS25 3d, no whelps spawning, no acolyte adds inside portal, reflect debuff unremovable

### ISSUE THREAD

**Issue by gforghieri** [gamefreedomgit/Frostmourne#430]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
OS25 3d, no whelps spawning, no acolyte adds inside portal, reflect debuff unremovable

**How to reproduce:**
Try encounter OS25 3d

**How it should work:**
Tenebron should spawn eggs in portal which eventually hatch if not killed, these whelps get outside of the portal automatically
Shadron spawns an acolyte in portal increasing fire damage taken with a debuff (https://www.wowhead.com/wotlk/spell=58766/gift-of-twilight) and making sarharion immune to damage until this add is killed, then debuff is removed.
Vesperon spawns acolyte in portal causing reflect damage with a debuff, https://www.wowhead.com/wotlk/spell=57935/twilight-torment ,https://www.wowhead.com/wotlk/spell=57988/twilight-torment. This debuff is removed when the add is killed.

**Database links:**
Complete explanation on how it should work:
https://raidy-raidy.com/wotlk/sartharion#sartharion

**Comment by gforghieri** [comment]
related https://github.com/gamefreedomgit/Frostmourne/issues/182

**Comment by UltraNix** [comment]
Fixed.
