### ISSUE TITLE
NPC - Bale'dun Foreman

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#431]
This NPC has no melee abilities scripted in, only spams torch toss. If you run out of range he does not even attempt to chase you, just resets.

He should use torch toss to put up the debuff one time and then do melees

**Comment by jack40melb** [comment]
[Video 1:13s ](https://youtu.be/hRCPytDblrs?t=73)

**Comment by Afgann** [comment]
fixed
