### ISSUE TITLE
Reputation flights paths need to be removed

### ISSUE THREAD

**Issue by Iramtempus** [gamefreedomgit/Frostmourne#432]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
If all Flight paths will be open on launch and after for that matter the following 3 flight paths need to be removed as you don't get them until you phase those parts of the zone.

**How to reproduce:**

**How it should work:**

**Database links:**

![WoWScrnShot_051224_220506](https://github.com/gamefreedomgit/Frostmourne/assets/88618448/5c994bb6-4180-46c0-a6bc-affa1c0684dd)
![WoWScrnShot_051224_220517](https://github.com/gamefreedomgit/Frostmourne/assets/88618448/54f658d6-ba53-4381-86e9-711adb6c6b0f)
![WoWScrnShot_051224_220522](https://github.com/gamefreedomgit/Frostmourne/assets/88618448/571f6912-5275-4f1b-8472-a149dbc3f5b9)

**Comment by UltraNix** [comment]
Fixed.
