### ISSUE TITLE
[NPC] Sarathstra wrong animation

### ISSUE THREAD

**Issue by Iramtempus** [gamefreedomgit/Frostmourne#433]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
This *Flying* dragon walks a lot.
In all seriousness though, it has a walking animation and should have a flying animation.

Sarathstra, Scourge of the North ID: 12097
**How to reproduce:**

**How it should work:**

**Database links:**
https://wowpedia.fandom.com/wiki/Sarathstra

**Comment by Afgann** [comment]
fixed
