### ISSUE TITLE
[Quest] Nature Materials - Metallic Fragments

### ISSUE THREAD

**Issue by Savageferret** [gamefreedomgit/Frostmourne#435]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

Metallic Fragments are not being dropped by sprite darters. Should be added or have their drop rate increased as all other vanilla quests

Quest: https://www.wowhead.com/wotlk/quest=3128/natural-materials
Quest Item: https://www.wowhead.com/wotlk/item=9592/metallic-fragments#dropped-by

Should be dropped by these mobs:
https://www.wowhead.com/wotlk/npc=5278/sprite-darter
https://www.wowhead.com/wotlk/npc=7997/captured-sprite-darter

**Comment by jack40melb** [comment]
I think its global. I found a few quests in  Northrend, Howling fjord also had low drop rates from mobs for quest items

**Comment by Afgann** [comment]
fixed
