### ISSUE TITLE
[Paladin] Fanaticism talent reduces threat with Righteous Fury active

### ISSUE THREAD

**Issue by oomshroom** [gamefreedomgit/Frostmourne#437]
The Fanaticism talent in Retribution tree currently reduces the paladin's threat even when Righteous Fury is active.

**Description:**

**How to reproduce:**

**How it should work:**
Fanaticism should not reduce threat while Righteous Fury is active, as per the tooltip.

**Database links:**

**Comment by oomshroom** [comment]
Still bugged after changelog fix has been applied. With Fanaticism and Righteous Fury, physical damage does 1.0 instead of 0.7 threat per damage, and healing threat gets messed up in a way I cannot understand, only doing ~0.26 threat per healing instead of 0.6435 (0.5*0.5*1.43*1.8).

**Comment by oomshroom** [comment]
Still bugged after changelog fix has been applied. With Fanaticism and Righteous Fury, physical damage does 1.0 instead of 1.43 threat per damage, and healing threat gets messed up in a way I cannot understand, only doing ~0.26 threat per healing instead of 0.6435 (0.5*0.5*1.43*1.8).

**Comment by Piootrek** [comment]
Fixed, I will close this once the fix comes live.
