### ISSUE TITLE
[DK starter zone] DK SKIP Puts you in a different layer/phase

### ISSUE THREAD

**Issue by scrublama** [gamefreedomgit/Frostmourne#44]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
The unique DK SKIP feature Puts you in a different phase zone leading to confusion and nowhere to go
https://streamable.com/3jupl8

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Tednugg** [comment]
What's wrong with this? You just death gate out of the DK zone and you straight to the real world.

**Comment by scrublama** [comment]
> What's wrong with this? You just death gate out of the DK zone and you straight to the real world.

being phased and not see any npcs does not seem wrong to you?

**Comment by Tednugg** [comment]
But if you had already skipped all the quests, and get on with outland leveling, why do you care if you see any npcs ?
