### ISSUE TITLE
Spell casts do not reset auto-attack timer

### ISSUE THREAD

**Issue by oomshroom** [gamefreedomgit/Frostmourne#440]
**Description:**
Currently, casting spells does not reset the player's auto-attack timer, making it possible to attack between spell casts.
Reviewing some footage, it seems like this worked fine early in the PTR and got broken at some point.

**How to reproduce:**

**How it should work:**
Casting a spell should reset auto-attack timer.

**Database links:**

**Comment by Godmatik** [comment]
Incorrect - spell GCD should not delay auto-attack timer

https://www.youtube.com/watch?v=ch3aXvhmADc&t=716s

**Comment by oomshroom** [comment]
> Incorrect - spell GCD should not delay auto-attack timer
> 
> https://www.youtube.com/watch?v=ch3aXvhmADc&t=716s

Currently even casted spells such as holy light do not reset autoattack, you just swing immediately after the spell is finished casting.

**Comment by Godmatik** [comment]
Ah ok, yeah misunderstood then.

Instant spells (moonfire, etc) should not reset melee swing timer
Casted spells should.

**Comment by oomshroom** [comment]
fixed

**Comment by scrublama** [comment]
elementals melee weaving still
