### ISSUE TITLE
Weapon Swapping in combat not working correctly

### ISSUE THREAD

**Issue by Mythhy** [gamefreedomgit/Frostmourne#441]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
While in combat, you can swap your weapons, however you cannot swap a main hand weapon and a wand at the same time/same GCD.

**How to reproduce:**
Make a character that uses wands, get in combat, try to swap main hand weapon and wand at the same time via macro or clicking.

**How it should work:**
You should be able to swap out all 3 weapon types (mainhand, offhand, wand) at the same time.

**Database links:**
Here is a video of it working in Classic with the timestamp.
https://youtu.be/22gu3aczWhU?t=548

**Comment by UltraNix** [comment]
Fixed.
