### ISSUE TITLE
you dont have the required proficiency for using that item

### ISSUE THREAD

**Issue by hamajaxd** [gamefreedomgit/Frostmourne#442]
while leveling yesterday from 1 to 67 we had a few issues one of them was after a few hours of each session we had a bug where we cant use certain things for example the bombs in hellfire we couldnt use the bomb everytime we click it or click any mana / health pot it says you dont have the required proficiency for using that item
https://www.wowhead.com/quest=10146/mission-the-murketh-and-shaadraz-gateways

after exiting the game and entering again it fixes the game if it only happened to one of us i would think it was pc related or some a personal problem but it might but a bug in the server 

the items we couldnt use : 
Mana pots 
health pots 
Bombs in the quest mentioned above 
Stormcrow amulet in the zangermash quest https://www.wowhead.com/tbc/quest=9718/as-the-crow-flies

all 3 of us had the same issues after certain amount of time it happens and we have to exist the game

**Comment by UltraNix** [comment]
@hamajaxd Still happens?
