### ISSUE TITLE
First Unholy Death Knight ghoul spawns with mana and limited energy

### ISSUE THREAD

**Issue by yeagerca** [gamefreedomgit/Frostmourne#444]
**Description:**
The first time an unholy death knight summons a permanent ghoul it will spawn with a mana bar instead of energy. It has 100 energy that is invisible but does not regenerate.
Dismissing and resummoning the ghoul will summon an energy ghoul that functions normally.
Screenshots: https://imgur.com/a/XUgGeE5

**How to reproduce:**
Create a death knight. Assign it the Unholy spec template. Cast Raise Dead.

**How it should work:**
All ghouls should use energy that regenerates.

**Database links:**
https://www.wowhead.com/wotlk/spell=46584/raise-dead

**Comment by Afgann** [comment]
fixed
