### ISSUE TITLE
Glyph of Divinity returns incorrect amount of mana to caster

### ISSUE THREAD

**Issue by yeagerca** [gamefreedomgit/Frostmourne#446]
**Description:**
1. The mana returned by Glyph of Divinity is dependent on the target's current mana before the cast.
When cast on a DK's ghoul that has 2186/2186 mana, it gave 2186 mana to the caster. (See: #444 )
When cast on a DK's ghoul that has 100 energy, it gave no mana to the caster.
When cast on a Warlock's Felhunter that has 5405/5405 mana, it gave 5405 mana to the caster.
When cast on a Warlock that has 93/14736 mana, it gave 93 mana to the caster.
When cast on a Warlock that has 6105/14736 mana, it gave 6105 mana to the caster.
When cast on a Paladin that has 23194/23194 mana, it gave 23194 mana to the caster (whom has a maximum of 22729 mana).

2. When casting Lay on Hands on yourself Glyph of Divinity does not activate. The character gains 3900 mana from Lay on Hands.

**How to reproduce:**
Equip the Glyph of Divinity and cast Lay on Hands on a various targets. Record the amount of mana each character gains.

**How it should work:**
- When Lay on Hands (Rank 5) is cast with Glyph of Divinity, both the target and caster should receive 3900 mana regardless of current or maximum mana.
- If the caster targets themself, they should receive 3900 mana from Lay on Hands and 3900 mana from Glyph of Divinity for a total of 7800 mana. (Citation: https://www.wowhead.com/wotlk/item=41108/glyph-of-divinity#comments:id=561084 )
- The caster should receive mana from Glyph of Divinity even if the target does not use mana as a resource.

**Database links:**
Spell: https://www.wowhead.com/wotlk/spell=48788/lay-on-hands
Glyph: https://www.wowhead.com/wotlk/item=41108/glyph-of-divinity
Use glyph: https://www.wowhead.com/wotlk/spell=55123/glyph-of-divinity
Glyph effect: https://www.wowhead.com/wotlk/spell=54939/glyph-of-divinity
Mana return spell: https://www.wowhead.com/wotlk/spell=54986/glyph-of-divinity

**Comment by Afgann** [comment]
fixed
