### ISSUE TITLE
leash/pursuit range still broken

### ISSUE THREAD

**Issue by qqdbpp** [gamefreedomgit/Frostmourne#447]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

this was marked fixed in the past but was and still is broken, mobs evade way before the 10-15s leash timer ends if you run out of their zone

**Description:**
![image](https://github.com/gamefreedomgit/Frostmourne/assets/159703358/4a36926a-ccc6-4e79-8d66-facc1ff7ebea)
https://github.com/azerothcore/azerothcore-wotlk/issues/5455

exact same problem on this server as this azerothcore discussion from 2021. mobs have a fixed reset range instead of starting a 12-15s timer upon exiting their leash range.

**Comment by UltraNix** [comment]
Fixed.
