### ISSUE TITLE
[HUNTER][ITEM][SPELL] Hunter's 2/5 T7 set bonus doesn't work

### ISSUE THREAD

**Issue by Nuy** [gamefreedomgit/Frostmourne#448]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Hunter's 2/5 T7 set bonus doesn't seem to work at all. When I replaced Heroes' Crypstalker 2/5 pieces to some off-set 200 ilevel items my pet dealt more or less same damage or even more than with set bonus sometimes. Attack power and crit chance numbers were similar in both cases.

**How to reproduce:** Test pet's damage on dummy with 2/5 set, then without and compare results. 

**How it should work:** This set bonus should increase ALL of pet's damage by 5%. Without this set bonus working hunter's T7 is worthless. 

**Database links:** https://www.wowhead.com/wotlk/spell=60143/kill-command-pet-boost - the name suggests it should only increase Kill Command damage but it's actually ALL of pet's damage.

**Comment by Afgann** [comment]
fixed
