### ISSUE TITLE
Quest Objects - no longer have fast respawn timers

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#449]
Several weeks ago it was changed so that quest objects you loot off the ground have faster respawn timers.

Now this no longer appears to be the case - they are set at the standard 5 minute respawn timer.

Example: Witchbane in Dustwallow Marsh

**Comment by UltraNix** [comment]
Dynamic respawn timer depends on how many players are in that area.

**Comment by Godmatik** [comment]
This impacts quest objects too? imo this should only apply to mobs. But regardless this is fair as long as they repop fast enough for busy quest areas. People forming a line waiting for things to respawn is the most boring bottleneck of any leveling experience.

**Comment by UltraNix** [comment]
Yes - it affects gameobjects.
