### ISSUE TITLE
Braziers in ironforge have bigger damage radius then they should

### ISSUE THREAD

**Issue by lorxlocked** [gamefreedomgit/Frostmourne#45]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
braziers in irongforge have issue where they damage you as you walk past them without touching them

**How to reproduce:**
walk close past braziers

**How it should work:**
shouldnt damage you unless you jump on the brazier

**Database links:**

**Comment by scrublama** [comment]
maybe its your hitbox thats giganormous

**Comment by Afgann** [comment]
fixed
