### ISSUE TITLE
NPC's continue to cast spells as they flee

### ISSUE THREAD

**Issue by Akaimba** [gamefreedomgit/Frostmourne#451]
**Description:**
NPC's continue to cast spells as they flee.
https://medal.tv/games/world-of-warcraft/clips/2e74KjCrOb_IjW/d1337H4rdTKf?invite=cr-MSxURFgsNTM0Nzk0NDEs

**How to reproduce:**
find any mob that flees on low life, and is also a caster.

**How it should work:**
They finish their cast and flee, or interupt their cast and flee - i do not recall

i can see chromie craft had a similar issue
https://github.com/azerothcore/azerothcore-wotlk/issues/8843

**Comment by UltraNix** [comment]
Fixed.
