### ISSUE TITLE
Unable to cast spells in Moonkin Form unless spells are on the exact same keybinds in non-shapeshift form.

### ISSUE THREAD

**Issue by Calior1919** [gamefreedomgit/Frostmourne#452]
**Description:**
Unless the same spell is on the same keybind in Moonkin and non-shapeshift form, the spell cannot be cast. No reticle for things like Hurricane or Force of Nature and normal casted spells like Wrath and Starfire do not function.

**How to reproduce:**
Put spells on different keybinds in shapeshift and non-shapeshift forms and try to cast them.

**How it should work:**
There should be no issue having a spell on different keybinds in different forms.

**Comment by UltraNix** [comment]
@Calior1919 Could you show us these keybinds?

**Comment by Calior1919** [comment]
It doesnt matter which keybinds you use. It isnt recognizing that the button is being pressed unless the spell is on the exact same action bar slot with the exact same keybind.

**Comment by UltraNix** [comment]
As I can't reproduce it - please just show it.

**Comment by Iramtempus** [comment]
Will test once I get back from work on a default client/default keyboard layout, and report if I can reproduce it.
