### ISSUE TITLE
[Dungeon Finder] Cooldown timer/info missing

### ISSUE THREAD

**Issue by Nuy** [gamefreedomgit/Frostmourne#453]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** After a player receives Dungeon Finder CD there should be animated timer in his Dungeon Finder UI telling him how much time left befor he can queue again. Currently it's missing. 

**How to reproduce:** Receive Dungeon Finder CD and open your Dungeon Finder UI.

**How it should work:** After a player receives Dungeon Finder CD there should be animated timer in his Dungeon Finder UI telling him how much time left befor he can queue again

**Database links:** https://www.reddit.com/media?url=https%3A%2F%2Fexternal-preview.redd.it%2F3lPFGIOZVjZulmqkqbnybOYhl7IOiRgbYu-Llw8dDD8.png%3Fauto%3Dwebp%26s%3D783f75514a240af99d6e9cf7d08ebf4abada9dbd

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/27204751-fe63-4876-a5f5-718880b503d1)
Just tested - works okay.

**Comment by Nuy** [comment]
We kicked 2 members and remade the group so maybe that's why it got bugged.
