### ISSUE TITLE
Leeway still not working properly

### ISSUE THREAD

**Issue by Nihaobeachez** [gamefreedomgit/Frostmourne#454]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Testing Leveling on PTR recently and i noticed that leeway isnt working properly. If targets are moving youre supposed to have some extra range, accounting for lag etc. After checking Github ive found that it was already reported in march and fixed, i dont know if later fixes broke it again or if it was never fixed properly

**How to reproduce:**

**How it should work:**
v posting Link to old Github report

**Database links:** https://github.com/gamefreedomgit/Frostmourne/issues/121

**Comment by Nuy** [comment]
Don't make it too big like it exists on Stormforge cause it's absolute cancer there with warriors hitting through pillars and stuff.

**Comment by UltraNix** [comment]
@Nihaobeachez What do you mean not working? GIve us some exact examples - what mobs/spells are not working here?

**Comment by Nihaobeachez** [comment]
@UltraNix i only tested melee abilities on low and high level mobs (tirisfal, ghostlands, silverpine forest, icecrown, stormpeak). and what do you mean by examples for mobs? its the same no matter what mobs i attack. leeway works to some content, but not how its supposed to work. 

https://youtu.be/g-1A-JD2UMQ?si=WogexfIeGU2pjWKl&t=144

i dont know if npcs/players have different leeways or if its just 1 complete thing, but i also had a lot of scenarios where the mob attacked me because of leeway, but i was out of range to attack him. i also tested backpaddling, same issue. many of times where the mob is out of reach, even tho he should be in a leeway range.

if you would ask me just as player, i would say leeway is missing roughly 1 yard, maybe a little below that

**Comment by UltraNix** [comment]
Leeway for melee attacks is 2.6 yards. It's the same for players and mobs.

**Comment by UltraNix** [comment]
Fixed.
