### ISSUE TITLE
[Warlock] - Succubus -> Lesser Invisibility (Still bugging)

### ISSUE THREAD

**Issue by Naturlish** [gamefreedomgit/Frostmourne#456]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/54108446/282dd6f3-bf3f-4493-b4dd-757cc07de475)

This is from the previous ticket (#261), the problem is still persisting.

Evidence:

https://github.com/gamefreedomgit/Frostmourne/assets/54108446/ec186ce5-3060-4ca8-b7bd-047a346584d1

**Comment by Afgann** [comment]
fixed

**Comment by Naturlish** [comment]
@Afgann sorry to be annoying, but now the the spell doesn't refresh automatically when we are out of combat.. We have to click it.


https://github.com/gamefreedomgit/Frostmourne/assets/54108446/3e19aaab-3010-4e2d-b341-1e326c3088dd
