### ISSUE TITLE
Bloodpetal Poison

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#458]
https://www.wowhead.com/classic/item=22435/gorishi-sting

Drop rate should be 100% for this quest item, same as all other vanilla quest items.

But currently is not.

**Comment by UltraNix** [comment]
The chance depends on mobs.
15% from https://www.wowhead.com/npc=6551/gorishi-wasp, https://www.wowhead.com/npc=6552/gorishi-worker, https://www.wowhead.com/npc=6553/gorishi-reaver, https://www.wowhead.com/npc=6554/gorishi-stinger and https://www.wowhead.com/npc=6555/gorishi-tunneler
30% from https://www.wowhead.com/classic/npc=10040/gorishi-hive-guard
100% from https://www.wowhead.com/classic/npc=10041/gorishi-hive-queen

https://www.wowhead.com/item=22435/gorishi-sting#comments:id=893174
This comment stays clearly it's not 100%.

**Comment by Godmatik** [comment]
@UltraNix 

Then remove the guaranteed 100% drop rates from all other vanilla and TBC quests?
