### ISSUE TITLE
Missing Quests in Zul' Drak

### ISSUE THREAD

**Issue by qwerty4444444444444444444444444** [gamefreedomgit/Frostmourne#459]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Bunch of quests missing in Zul'Drak specifically at the Argent Stand.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Like what quests? Give us some links or quest names.

**Comment by qwerty4444444444444444444444444** [comment]
Like go to Argent Stand camp and see what is missing. I made one ticket for Loch Modan with detailed info and it has low priority & not fixed for weeks.

**Comment by UltraNix** [comment]
It's so hard to give one example of missing quest? I could check if there are some requirements, etc...

**Comment by Godmatik** [comment]
Iirc you need to do a breadcrumb to open up the quests.

**Comment by Greywolf59** [comment]
To open quests in Argent Stand you need to hand in the quest [Taking a Stand](https://www.wowhead.com/wotlk/quest=12795/taking-a-stand).  At least that happened for me. It should also be opened by simply compelting quest [Parachutes for the Argent Crusade](https://www.wowhead.com/wotlk/quest=12740/parachutes-for-the-argent-crusade) which should not have any prerequisite

Completing Taking a Stand opens up: The Blessing of Zim'Abwa, Gluttonous Lurkers, The Drakkari Do Not Need Water Elementals!
Completing Defend the Stand and Parachutes for the Argent Crusade (probably, handed as 1st and did not open anything) opens up: New Orders for Seargeant Stackhammer, Pa'Troll, Trouble at the Altar of Sseratus.
Sorry for not linking all the quest, I am in a hurry.

How it should be according to comments:
https://www.wowhead.com/wotlk/quest=12740/parachutes-for-the-argent-crusade#comments:id=557532 So these three quest should require only the Paratuches quest, not also the Defend the Stand.

The Drakakri Do not Need Water Elementals ahve also prerequisite wrong according to: https://www.wowhead.com/wotlk/quest=12740/parachutes-for-the-argent-crusade#comments:id=557532

Gluttonous Lurkers: Should be available after handing in Elemental Fluids: https://wowpedia.fandom.com/wiki/Gluttonous_Lurkers#Progression

Logical result based on comments:
Not a single quest should be dependant on Taking a Stand and Defend the Stand.
New Orders for Seargeant Stackhammer, Pa'Troll, Trouble at the Altar of Sseratus should be avaialble after completing Parachutes for the Argent Crusade and nothing else should be needed.
The Drakakri Do not Need Water Elementals, Gluttonous Lurkers and msot likely The Blessing of Zim'abwa ahve their prerequisites wrong.

Someone should check it more thoroughly, but that is how I see it.

**Comment by WhitemaneIsa** [comment]
As there has been no further info/complaints, this will be closed for now.

**Comment by Greywolf59** [comment]
I think that in my comment there is decent chunk of info. But I can open a new issue, with proper links I suppose.

**Comment by WhitemaneIsa** [comment]
> I think that in my comment there is decent chunk of info. But I can open a new issue, with proper links I suppose.

Please do, but we do not know if this is what the OG post meant and the title here is misleading and a bit chaotic. <3
