### ISSUE TITLE
Southshore guards don't aggro shadowy assassins

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#464]
**Description:**
Southshore guards don't aggro shadowy assassins when they unstealth and attack you, even if you're standing right on top of guards

**How to reproduce:**
Find shadowy assassins in Southshore

**How it should work:**
https://www.wowhead.com/wotlk/npc=2434/shadowy-assassin#comments
As per comments, guards should aggro assassins

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
