### ISSUE TITLE
[HUNTER][SPELL] Flare travel time too slow

### ISSUE THREAD

**Issue by Nuy** [gamefreedomgit/Frostmourne#466]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Flare's travel time is too slow now and lands after few seconds if used far away and it should be instant even if far.

**How to reproduce:** Use Flare far away from yourself.

**How it should work:** It should land on the ground immediately even if used far away. - https://youtu.be/1Vo9vYF0-18?si=nyDePuzCfgZ2eDZe&t=565

**Database links:** https://www.wowhead.com/wotlk/spell=1543/flare

**Comment by Afgann** [comment]
fixed
