### ISSUE TITLE
Bloodpetal Poison - reopen

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#468]
#458 

I understand that it's blizzlike that it does not have a 100% drop rate.

However, whether by mistake or custom feature, currently every vanilla and TBC quest on the PTR has a 100% drop rate on all quest related drops. Even the bloodcaps for this quest currently are 100% drop rate (but should not be).

So my point is that this quest drop's rate should match every other quest. If not, we should remove the 100% guaranteed drops on all other Vanilla/TBC quests (not something I think should be done for a 5x server).

**Comment by Afgann** [comment]
fixed
