### ISSUE TITLE
Wraith Scythe, Blade of the Unquenched Thirst, Ancient Hakkari Manslayer Chance on Hit bugged.

### ISSUE THREAD

**Issue by PendingtonFlex** [gamefreedomgit/Frostmourne#469]
**Description:**
Currently all items that are "Chance on hit: Steals x life from target enemy." don't properly scale off of spell power.

**How to reproduce:**
Use any one handed item with the chance on hit I referred too, Blade of Unquenched Thirst, Wraith Scythe, and Ancient Hakkari Manslayer, they only deal base damage.

**How it should work:**
scales with spell power.

**Added Note**
Only one handed weapons of this nature are affected by spell power, any two handers or similar effects do not scale with spell power, for example. Neretzek, The Blood Drinker, Skullforge Reaver.

**Database links:**
https://www.wowhead.com/classic/item=11920/wraith-scythe#comments
https://www.wowhead.com/item=11920/wraith-scythe#comments
https://www.wowhead.com/wotlk/item=19852/ancient-hakkari-manslayer#comments
https://www.wowhead.com/wotlk/item=21856/neretzek-the-blood-drinker#comments

**Comment by Afgann** [comment]
fixed
