### ISSUE TITLE
The Battle of Undercity QuestLine

### ISSUE THREAD

**Issue by erazm** [gamefreedomgit/Frostmourne#47]
**Description:**
1 - The quest "Return to Angrathar" doesn't trigger the cinematic when completed as it should.
2 - After completing the quest "A Royal Coup" and taking the quest "The Killing Time", Jaina is absent (Another phase, No Jaina, No Portal to Undercity). PS: Logging Off and Relogging made the portal pop (But Jaina isn't there).
3 - I don't know if it is due to short respawn times, but during "The Battle of Undercity", at some points of the map, mobs respawn so fast, that Varian and Jaina are stuck between two packs (Or maybe the spawn of the worm boss is a little bit to long).

**How to reproduce:**
1 - Complete the quest to Angrathar, and the cinematic won't launch as it should. 
2 - Take the quest "The Killing Time" after completing the quest "Royal Coup" 
3- Just take the quest "The Battle of Undercity" and run it normally.

**How it should work:**
1 - Completing the quest to Angrathar must trigger a cinematic and a certain phase.
2 - Jaina should be there and pop a portal to the frontiers of undercity.
3 - "The Battle of Undercity" should be a linear experience.

**Database links:**
https://www.wowhead.com/wotlk/quest=12500/return-to-angrathar#comments (To check all the quests of the chain).
https://www.wowhead.com/wotlk/quest=13370/a-royal-coup
https://www.wowhead.com/wotlk/quest=13371/the-killing-time
https://www.wowhead.com/wotlk/quest=12500/return-to-angrathar
https://www.wowhead.com/wotlk/quest=13267/the-battle-for-the-undercity

**Comment by radeghostmademedoit** [comment]
this should be a higher prio to be honest. it sucks that such an epic quest line is bugged

**Comment by radeghostmademedoit** [comment]
last part bugged out completely for me. doing alliance quest. everybody just disappeared and I have to restart

**Comment by PanJanuszek** [comment]
1. Required new client v3 with cinematic included.
2. fixed
3. fixed, found that spot, before big worm appeared. We had 30 waves of big abo required to move on. On retail I see that only 10 are required. So switched to 30->10.
