### ISSUE TITLE
[PET][NPC][MOVEMENT] Pets sometimes make mobs run to Africa

### ISSUE THREAD

**Issue by Nuy** [gamefreedomgit/Frostmourne#472]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Currently when you send your pet to attack any mob it can sometimes make it to spazz out and run away from it. I think it has something to do with mob repositioning/backpedalling when its attacker steps inside of it. Here you can see what I mean - https://www.twitch.tv/videos/2154829979

**How to reproduce:** Send your pet to attack any mob and sometimes it will cause the mob to spazz out and run away from it.

**How it should work:** Mobs shouldn't run to Africa when your pet is attacking them.

**Database links:** -

**Comment by UltraNix** [comment]
Fixed.
