### ISSUE TITLE
[NPC][LOOT] Skeletal Warrior's and Insane Ghoul's loot tables

### ISSUE THREAD

**Issue by Nuy** [gamefreedomgit/Frostmourne#473]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** These mobs drop way too many Green Linen Shirt even tho it shouldn't be in his loot table at all. Loot tables could be broken in general and should be thoroughly checked.

**How to reproduce:** Kill few of these mobs and check the drops.

**How it should work:** Green Linen Shirt shouldn't drop from any mob.

**Database links:** 
https://www.wowhead.com/wotlk/npc=48/skeletal-warrior
https://www.wowhead.com/wotlk/npc=511/insane-ghoul
https://www.wowhead.com/wotlk/item=2579/green-linen-shirt

**Comment by Afgann** [comment]
fixed
