### ISSUE TITLE
Melees and Pets repositioning + Parry interaction

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#474]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Kelthuzad seems to be one of many bosses that seem to be parrying from the sides and even behind sometimes.
Considering this is a bossfight that you would split melee groups into three and it does have parry haste enabled this is a big issue.
This happened on gluth aswell which led me to believe this might be related to server not updating something when ever bosses are moved? i cannot confirm this yet but this might be the reason why pets are not relocating behind target on gluth/sapphiron/kt/four horsemen (could be other bosses aswell)
This happened in the PTR raid yesterday
Pets are stuck ( armies ghouls felguards etc) consistently when used on baron rivendare's corner side of the Four Horsemen encounter. noticable primarily due to bosses being moved to avoid the custom mechanic you'll notice army and ghoul are stuck in same position.
Pets in wow should always relocate to behind target ( except in specific cases such as Kologarn )
older vod but still relevant : https://www.youtube.com/live/U1asOBM7-vM?si=klhmzoVWDXRoAzxt&t=8137
It is timesamped at the start of the fight the pets are positioned correctly
after flight phase starts the pets are in the front to relocate to the boss being moved : https://www.youtube.com/live/U1asOBM7-vM?si=ZA6WTb0njDakF0Fw&t=8176
now for the rest of the bossfight the pets will remain to the frontal side of the boss.
issue  on gluth : https://www.youtube.com/live/U1asOBM7-vM?si=GII4lMeX5aXlT1DE&t=1565
in this one the pets are parrying (you can see in chat who and who's pet is parrying getting spammed despite pets and melees all being behing the target.
Malygos has same two issues.

If not fixed by launch there will be more streams to use info from that i will link here.

**How to reproduce:**

**How it should work:**
Parries should not happen unless enemy is within the frontal melee cone.
Pets should relocate to behind target
Pets and Guardians keep getting stuck in specific positions

**Database links:**

**Comment by Manpower99** [comment]
Seems to be of similar nature (perhaps?) to https://github.com/gamefreedomgit/Maelstrom/issues/2425
Something that was plaguing Maelstrom for a long time at launch

**Comment by Manpower99** [comment]
Rogue in PTR Run yesterday says after repositioning he could no longer use Backstab behind the target also. sadly the raid was not recorded or logged.

**Comment by Manpower99** [comment]
It is likely a disjointing of the Hitbox/Model and a desync between client and server? I cannot fully conclude this but it is of very similar nature to what happened on start of maelstrom
In this timestamped stream the two mobs normally cleave to the front, but after they charge their furthest target their hitbox/frontal cone is desynced and they are cleaving in opposite directly
https://www.youtube.com/live/1P9zAlIWEzw?si=MLGeOTaJn-agLOj-&t=338
While this issue has been fixed a while ago on Maelstrom it is likely the exact same issue on Frostmourne.

**Comment by scrublama** [comment]
assign it to @Afgann , he fixed it 2020
https://github.com/SunwellTracker/issues/issues/2635

**Comment by UltraNix** [comment]
Let me know if it's fixed.

**Comment by Manpower99** [comment]
> Let me know if it's fixed.

Will provide u with a video **soon** of our PTR testing algalon so you can see pet behavior there.

**Comment by Manpower99** [comment]
> Let me know if it's fixed.

 @UltraNix 

Okay in past few IDs since fix, there has been a noticable improvement in pet repositioning behavior, this is very good with a small issue that is noticable in specific situations such as this : 
on whitemane atm (26/07/24) If multiple dks call their army then each ghoul will be periodically taunting as it is intended, the issue however is that ghouls are attempting to hit from behind so due to the target being rotated nonstop they will constantly be rotating aswell.
https://www.youtube.com/watch?v=7OJDDGU0hYU you can see here on a classic vod the add on anubrekhan being taunted nonstop but the ghouls position is not changing, likely because the repositioning works in checks/ticks, every lets say 100MS it would check if it is hitting from the target's back or not and would act accordingly depending on the situation.
in addition to this it seems that while the pets are repositioning/fanning on whitemane they are not attacking but just moving, they should be able to do both at the same time, in the same manner a player would be able to both swing attacks + move at the same time.
https://youtu.be/AYuj8kNU1qY?si=29P1Hb4uvo6nSrej&t=1036 can be observed here

**Comment by UltraNix** [comment]
`in addition to this it seems that while the pets are repositioning/fanning on whitemane they are not attacking but just moving, they should be able to do both at the same time, in the same manner a player would be able to both swing attacks + move at the same time.`
Tested and works okay.

**Comment by Manpower99** [comment]
> `in addition to this it seems that while the pets are repositioning/fanning on whitemane they are not attacking but just moving, they should be able to do both at the same time, in the same manner a player would be able to both swing attacks + move at the same time.` Tested and works okay.

Hmm it wasnt working while we were attempting algalon on ptr, but perhaps it was just a visual issue or i might be mistaken, will report back if i can confirm it.

The First issue though is 100% confirmed you can see it on any target that gets periodically taunted by multiple aotd ghouls.

**Comment by UltraNix** [comment]
Yep - will be fixed.

**Comment by UltraNix** [comment]
Fixed.
