### ISSUE TITLE
Sword Spec/Hack and Slash Follow up

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#475]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
https://github.com/gamefreedomgit/Frostmourne/issues/122
Something i reported a while ago seems to be incorrect, i apologize.
While the proof i linked is not incorrect it seems the patch notes do not reveal that this is something that got reverted not long after.
Proof : https://youtu.be/MyS20Rr8V1M?t=19
At 04:07 in this OG Wrath video showing that the hits from Sword spec and Hack and Slash are indeed white hits thus subject to missing and glancing.
This seems to be the same for Wotlk Classic and also Warmane and so i ask for it to be reverted.

**How to reproduce:**
**How it should work:**
**Database links:**

**Comment by Afgann** [comment]
fixed
