### ISSUE TITLE
Parry Haste and Players

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#476]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Parry Haste is a Mechanic that exists in WotLK for very few specific bosses also it is mainly removed from specific bosses in Vanilla and TBC that simply hit too hard and would be a painfully annoying to tank, after Cataclysm it was removed from PvE entirely but it is still kept for Players and no mention of it being removed even in retail.
in the version of WotLK we play they dont exist on every single boss but it is noticable from weakauras that track boss swing timers.
How it works :
"After a successful parry, the defender's "swing timer" is reduced by 40% of your weapon speed (or even reset), unless this would result in a reduction to less than 20% of your swing time remaining. This results in an average of .24 extra swings per parry; thus parry favors slower, higher damage weapons. Note that with a slow weapon and fast incoming attacks, it is possible to gain multiple speed reductions. While tanks like to profit from this effect, melee damage dealers should attack from behind whenever possible, both to increase their own damage and to avoid causing unneeded damage to the tank through the enemy's parries."
Currently the issue on Frostmourne is that Parry Haste does not work with Players, only Specific Bosses ( which is fine ) but this is an important mechanic that allows for Tanks through their avoidance to gain extra damage and threat. not to mention the effect it has on PvP

**How to reproduce:**
Parry an npc or player attack as a player and notice your current swing timer does not get reduced.

**How it should work:**
There is alot of proof to support that players should be able to parry haste
https://vanilla-wow-archive.fandom.com/wiki/Parry
https://www.mmo-champion.com/threads/693001-Parry-Haste
https://www.reddit.com/r/classicwow/comments/bvkkwi/parry_haste/
https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/46829798

**Database links:**

**Comment by UltraNix** [comment]
Just tested and works okay.
There is a limit - 60% of your base attack time. So you can reduce up to 40% of your base attack time.

**Comment by Manpower99** [comment]
> Just tested and works okay. There is a limit - 60% of your base attack time. So you can reduce up to 40% of your base attack time.
> 
> https://wowpedia.fandom.com/wiki/Parry?oldid=2145899 `When you parry an attack, the remaining time on your current swing is reduced by 40% of your weapon speed, unless this would result in a reduction to less than 20% of your swing time remaining`

You are right, my tests on ptr seems to not be the same on live.
