### ISSUE TITLE
[Hunter][Pet] Bad Attitude

### ISSUE THREAD

**Issue by Savageferret** [gamefreedomgit/Frostmourne#477]
The ability "Bad Attitude", used by the hunter pet Crocolisk, is missing its attack power modifier.

I tested with a fully geared hunter (2800 attack power) and a naked hunter. Both resulted in the same Bad Attitude damage

https://www.wowhead.com/wotlk/spell=52399/bad-attitude shows a 0.07 attack power modifier for all ranks

**Comment by Afgann** [comment]
fixed
