### ISSUE TITLE
[Enhancement] Flurry No Internal Cooldown

### ISSUE THREAD

**Issue by Dova14** [gamefreedomgit/Frostmourne#48]
**Description:**
Auto attacks consumes two flurry charges even when both weapons are sync'd or swinging within 0,5 seconds of each other

**How to reproduce:**
Start auto attacking a training dummy and have flurry proc via a crit, your next auto attack that doesnt have either swing crit will consume 2 flurry charges 

**How it should work:**
Flurry should have an internal cooldown of 0.5 seconds preventing two autos within 0.49 or less seconds of each other from consuming more than one charge of flurry

**Database links:**
https://wotlk-twinhead.twinstar.cz/?spell=16280

**Comment by Afgann** [comment]
fixed
