### ISSUE TITLE
Underbog Hungarfen

### ISSUE THREAD

**Issue by Akaimba** [gamefreedomgit/Frostmourne#480]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[[//]: # (https://www.wowhead.com/wotlk)](https://www.wowhead.com/tbc/npc=17770/hungarfen)

**Description:**
First boss in underbog spawns mushrooms - they are supposed to spawn randomly on the platform and slowly grow - after a few seconds they explode and deal nature dmg.
on PTR they all spawn under the same player and instantly deal dmg very quickly- even tank dies in 0.7 seconds.

[Underbog Mushrooms](https://www.wowhead.com/tbc/npc=17990): Spawn at random locations on the platform and immediately begin to grow in size. After a few seconds they explode and release a [ Spore Cloud](https://www.wowhead.com/tbc/spell=38653/spore-cloud) that lasts 20 seconds. The cloud inflicts 360 nature damage every 2 second. This can stack up to 5 times.

**How to reproduce:**
pull the boss

**How it should work:**
[Underbog Mushrooms](https://www.wowhead.com/tbc/npc=17990): Spawn at random locations on the platform and immediately begin to grow in size. After a few seconds they explode and release a [ Spore Cloud](https://www.wowhead.com/tbc/spell=38653/spore-cloud) that lasts 20 seconds. The cloud inflicts 360 nature damage every 2 second. This can stack up to 5 times.

**Comment by Piootrek** [comment]
Looks like it's fixed https://github.com/gamefreedomgit/Frostmourne/issues/546
Closing
