### ISSUE TITLE
Using random dungeon finder after you completed a dungeon

### ISSUE THREAD

**Issue by Akaimba** [gamefreedomgit/Frostmourne#481]
**Description:**
If you technically get the same dungeon, you are not teleport into a new instance - you stay in the same one.
Even if you manually teleport out and back in, it is the same instance of the dungeon.

This means you have to either kick each other for 15 min dungeon deserter og leave and get 30 minute dungeon deserter.

**How to reproduce:**
it is difficult - you have to complete a RDF dungeon, and queue up for another and hit the same dungeon.

**How it should work:**
it should teleport you to a new instance of the same dungeon.

**Comment by keelash123** [comment]
Yep if you dont regroup after completing a dugeon this wil happen basicly you wil join same instance with cleared trash and not able co complete it cause boss is dead :D in the past it was whatever because dungeon cooldown was removed cause it caused too many complications with dungeonfinder.

**Comment by UltraNix** [comment]
Fixed.
