### ISSUE TITLE
TBC End of dungeon Exp reward

### ISSUE THREAD

**Issue by Akaimba** [gamefreedomgit/Frostmourne#483]
**Description:**
You get fewer end of dungeon exp from completing a TBC dungeon, than a vanilla dungeon

**How to reproduce:**
completed Slavepens - it gave 56k exp
https://github.com/gamefreedomgit/Frostmourne/assets/163650784/6f52e33f-793d-43e6-80b2-98148b01b510)

Dire maul east gave 58,7k exp
Same did scholomance
![image](https://github.com/gamefreedomgit/Frostmourne/assets/163650784/010f16b6-844e-4f99-aa0d-ca24407e4f71)

**How it should work:**
end of dungeon Exp should scale with character level if i remember correctly

**Comment by UltraNix** [comment]
Yes - it depends on your level. 
I see the calculations are quite good in the core.

**Comment by WhitemaneIsa** [comment]
As there has been no further info/complaints, this will be closed for now.
