### ISSUE TITLE
[Spell] Hunter - Explosive Trap not working

### ISSUE THREAD

**Issue by Iramtempus** [gamefreedomgit/Frostmourne#484]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The trap does not trigger when mob walks near it, it just despawns.

**How to reproduce:**
See video
https://www.youtube.com/watch?v=qxGsKaVpXPs
**How it should work:**

**Database links:**

**Comment by Nuy** [comment]
It's already reported.

**Comment by Iramtempus** [comment]
@Nuy Did not see, closing as other already has dev assigned.

**Comment by Iramtempus** [comment]
Duplicate ticket
