### ISSUE TITLE
The Oculus - Ley-Guardian Eregos loot drop

### ISSUE THREAD

**Issue by AMInxs** [gamefreedomgit/Frostmourne#485]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
We did a RDF HC on the PTR and the last boss Ley-Guardian Eregos from Oculus didn't dropped Cache of the Ley-Guardian when killed.

**How to reproduce:**
Join the dungeon via RDF HC and kill the boss.

**How it should work:**
The boss should drop the bag when killed in a RDF HC queue group.

**Database links:**
https://www.wowhead.com/wotlk/item=52676/cache-of-the-ley-guardian#contained-in-object
https://www.wowhead.com/wotlk/object=193603/cache-of-eregos
https://www.wowhead.com/wotlk/npc=27656/ley-guardian-eregos

**Comment by Nihaobeachez** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/415

didnt exist in naxx patch.
