### ISSUE TITLE
[ASCENDED] Lockout

### ISSUE THREAD

**Issue by RadeghostWM** [gamefreedomgit/Frostmourne#486]
Make 10 Ascended lock to 25 man only, instead of 25+10. So if you do ascended, you can run 10man later.

**Comment by RadeghostWM** [comment]
Like if you for example killed all bosses except Kelthuzad on ascended (and killed KT on normal), when you go in on Normal difficulty, you can ill all bosses in 10-man except Kelthuzad (because you killed him on 10n already)

**Comment by Iramtempus** [comment]
Would also need to work the other way around I imagine? Being able to clear it on 10man normal then going in and attempting ascended?
As I suggested on discord I think simply making it a full lock instead of toggleable might help the implementation?

**Comment by Afgann** [comment]
fixed
