### ISSUE TITLE
Game lag after using engi gloves

### ISSUE THREAD

**Issue by Covidisreal** [gamefreedomgit/Frostmourne#489]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Experiencing in-game stutter after using engineering gloves. Happens only with engineering gloves regardless of having addons enabled / disabled. Stutter persists even after freshly reloaded ui ( /reload ui ) with and without addons enabled.
Some friends and players on GM island reported same issue.

**How to reproduce:**
Use engi gloves

**How it should work:**
Shouldn't lag 

**Database links:**
https://www.wowhead.com/wotlk/spell=54999/hyperspeed-accelerators

**Comment by Covidisreal** [comment]
UPD: Reinstalled latest game client from Whitemane website. Completely fresh, no addons, no settings ported from another WoW clients - problem persisted.

**Comment by Tahtoh88** [comment]
with the fix being implemented hyperspeed accelerators now puts on use trinkets on icd and vice versa

**Comment by UltraNix** [comment]
@Tahtoh88 Will be fixed withing the next patch.

**Comment by UltraNix** [comment]
Fixed.

**Comment by Tahtoh88** [comment]
as of right now the gloves are not usable with on use trinket again
