### ISSUE TITLE
[Enhancement] Lightning Weaving Resets Auto Attacks

### ISSUE THREAD

**Issue by Dova14** [gamefreedomgit/Frostmourne#49]
**Description:**
When weaving (Casting lightning bolt with maelstrom stacks between auto attacks) with any maelstrom stacks below 5, it will reset your auto attack.

**How to reproduce:**
Auto attack a training dummy and cast lightning bolt with 2 - 4 maelstrom stacks and have the cast finish before your auto attacks do

**How it should work:**
Maelstrom has a trigger that prevents spells that finish before your swing timer from resetting your auto attacks, so you should be able to cast a lightning bolt with at least 1 maelstrom stack and if it finishes before your auto swings the auto attacks should go through

**Database links:**
https://wotlk-twinhead.twinstar.cz/?spell=51532

**Comment by gmforghieri** [comment]
Adding some further proof that the functionality should indeed behave as Dova14 mentioned as it was the case even in original retail WotLK not just WotLK classic. Please check the below warmane bugreport and comments.

https://www.warmane.com/bugtracker/report/114709

**Comment by Dova14** [comment]
This is still bugged @Afgann 

As it works right now your auto attacks are still reset when you successfully weave (So casting lightning bolt before your auto attacks swing) if the swing has 0.5 or more seconds left till you swing. Instead now you do not lose your auto attacks if your cast finishes AFTER your auto attack does or if you finish casting 0.5~ or less before you swing (As Xeel reported in the discord and ive tested)

**Comment by Afgann** [comment]
fixed
