### ISSUE TITLE
ARMS WAR : [Sudden Death] proc 2 stacks with t10  (only one can be used) !!

### ISSUE THREAD

**Issue by Alim-ben** [gamefreedomgit/Frostmourne#490]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
for Arms warrior Spec  after  [Sudden Death] proc 2 stacks with t10 set bonus after using one 1/2 charges  the 2sd charge doesn't stay for arms spec (meaning we should be using 2 charge of Execute not just one after proc accure)

**How to reproduce:**
equip Tier 10 on arms spec & try to proc 2 charges of Execute & try using them ! (only one can be used)

**How it should work:**
We should be able to use 2 Executes after sundden Death proc 2 charges for arms spec (warrior)

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
