### ISSUE TITLE
[Quest] The Perfect Dissemblance - Doesn't Complete / A Fall From Grace

### ISSUE THREAD

**Issue by Iramtempus** [gamefreedomgit/Frostmourne#491]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Currently not working, you can use the mirror to grab the illusion but it doesnt trigger it in the quest log.
Leaving you in disguise but with an uncompleted quest.

**How to reproduce:**
Walk up to a Raven Priest, use quest item and cry.

**How it should work:**
https://www.youtube.com/watch?v=_-CoX8_wdEQ

**Database links:**

**Comment by Iramtempus** [comment]
Seems to be working now, not sure what fixed it but closing.

**Comment by PanJanuszek** [comment]
![image](https://github.com/user-attachments/assets/01ea0381-3929-4462-bdbd-33d28ba44563)


![image](https://github.com/user-attachments/assets/2d0718ba-9909-49cf-a8a5-4c9cdab77faf)

" I could ring the bell but Abbot wont appear next to you in the entrance. Please check both quests to avoid issues."
Check this: https://www.wowhead.com/quest=12274/a-fall-from-grace#videos:id=77691

![image](https://github.com/user-attachments/assets/9dcb1a9c-0eb0-41ec-a88f-da68a1c6d59a)

Closing as working
