### ISSUE TITLE
[Quest] Fresh Remounts - Agro seems bugged

### ISSUE THREAD

**Issue by Iramtempus** [gamefreedomgit/Frostmourne#492]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Was doing the quest and it is doable but the threat to the horse looks really bugged.
Once you use your riding crop and start riding towards venomspite, most mobs you agro will follow you all the way to venomspite.
If you are playing a class with no threat remove spells (Feign death, Vanish) this will kill you.

**How to reproduce:**
https://www.youtube.com/watch?v=BA3xIERKqk8

**How it should work:**

**Database links:**
https://www.wowhead.com/wotlk/quest=12214/fresh-remounts

**Comment by UltraNix** [comment]
Fixed.
