### ISSUE TITLE
Dungeon Cooldown not removed after completing specific dungeon

### ISSUE THREAD

**Issue by keelash123** [gamefreedomgit/Frostmourne#493]
After completing specific dungeon throu dungeon finder, i was stil marked with dungeon cooldown and it wasnt even showing in dungeon finder window.

After completing dungeon throu dungeon finder either random or specific dungeon cooldown should be removed and player should be able to join another dungeon.

similar dungeon finder bugs that we also encountered that are already reported:
https://github.com/gamefreedomgit/Frostmourne/issues/481
https://github.com/gamefreedomgit/Frostmourne/issues/453

This can be fixed easily by simply removing dungeon cooldown like on previous whitemane wotlk realms, it also can cause another problems because players can votekick someone instantly after they get teleported into a dungeon and that player wil get dungeon cooldown by simply playing wrong class that someone doesnt like and he wil be unable to join another dungeon for 15m whitout doing anithing wrong. Removing dungeon cooldown will have no negative impact on server it wil also fix uplinked issues 481, 453.

**Comment by Iramtempus** [comment]
Removing it will enable the abuse of RDF for leveling - I am not saying this is a reason to not do it but something to keep in mind.
Queue, get wailing cavers -> Kick -> Requeue, repeat untill you get a better dungeon. The best example being prison spamming in the 50 levels.

**Comment by keelash123** [comment]
> Removing it will enable the abuse of RDF for leveling - I am not saying this is a reason to not do it but something to keep in mind. Queue, get wailing cavers -> Kick -> Requeue, repeat untill you get a better dungeon. The best example being prison spamming in the 50 levels.

Yes but thats positive not negative, on last whitemane it was no dungeon cooldown and pple liked it, it alow them to avoid dungeon that they hate thats more like win / win situation, and it fits whitemane Qol, + it fix couple problems, and avoid negative experience after beint not able to reque dungeon finderafter after being votekicked for no reason or if dungeon finder bugs and rejoin u into same instance that is cleared you can simply vk each other, so i think geting rid of dungone cooldown is net Positive. Also i dont understand why we should have it now active when in past wotlk realms it was removed together with too many instances and it was fine and pple liked it.

**Comment by Nihaobeachez** [comment]
If it cant be fixed 100% till launch, the right call would be to just remove the RDF cooldown like keelash mentioned. a lot of player will do RDF spam on launch and if its scuffed in any way, the backlash will be huge.

can always reenable it, once the bugs for rdf are fixed

**Comment by Afgann** [comment]
fixed
