### ISSUE TITLE
Warlock Pet attacking unintentionally

### ISSUE THREAD

**Issue by brooman04** [gamefreedomgit/Frostmourne#495]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
warlock pet is automatically attacking mobs you right click but have not tagged yet or have been hit from in defensive mode.

**How to reproduce:**
in defensive mode. right click any mob, and the pet will auto attack.

**How it should work:**
pet should not attack if you right click a mob, only when caster is hit by mob or caster hits mob in defensive mode. 

**Database links:**

**Comment by Afgann** [comment]
fixed
