### ISSUE TITLE
[NPC][CHASE RANGE] Some mobs chase FOREVER after last update

### ISSUE THREAD

**Issue by Nuy** [gamefreedomgit/Frostmourne#497]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Some mobs chase FOREVER after last update and won't stop unless you die or use something like Feign Death. Seems to happen to only some mobs.

**How to reproduce:** Aggro mob like Kurzen Medicine Man and try to run away from him without attacking. He will chase forever despite you not touching him.

**How it should work:** After like 20-30 of chase mob should stop chasing if it wasn't attacked.

**Database links:** https://www.wowhead.com/wotlk/npc=940/kurzen-medicine-man

**Comment by Godmatik** [comment]
Also you can not exit combat simply by outranging mobs but you should be able to.

For example cast entangling roots on a mob, and run away like 200+ yards, you will never drop combat until those roots break.

**Comment by UltraNix** [comment]
`For example cast entangling roots on a mob, and run away like 200+ yards, you will never drop combat until those roots break.`
It's becasue they are doing still damage?

**Comment by UltraNix** [comment]
@Nuy Just tested that mob and see nothin wrong. I was chasing away from him (not doin any damage) and it evades after some 15 secs.

**Comment by UltraNix** [comment]
@Godmatik It's because you are still doing some damage (DoT in that case).
https://classicwow.live/guides/793/leash-behavior?g=classic says about any hostile action towards to your enemy.

**Comment by Nuy** [comment]
> @Nuy Just tested that mob and see nothin wrong. I was chasing away from him (not doin any damage) and it evades after some 15 secs.

Doesn't happen to every mob it seems (that's why I mentioned Kurzen Medicine Man specifically) and chase range on some of them seems way too big.

**Comment by Nuy** [comment]
> @Nuy Just tested that mob and see nothin wrong. I was chasing away from him (not doin any damage) and it evades after some 15 secs.

Weird, I could swear 1 or 2 of them chased my all the way back to the camp.

**Comment by UltraNix** [comment]
If you stop running and mob melee attacks you , then the leash timer is reset.

**Comment by Godmatik** [comment]
a mob attacking you should not extend the leash

**Comment by Nuy** [comment]
I'm pretty sure I was moving the entire time tho and he didn't hit me for like 7 second at least.

**Comment by UltraNix** [comment]
Fixed.
