### ISSUE TITLE
[ITEM][DROP RATE] Very low drop rate on Engine-Core Crystal

### ISSUE THREAD

**Issue by Nuy** [gamefreedomgit/Frostmourne#498]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Engine-Core Crystal's drop rate is pretty bad. 

**How to reproduce:** Kill Festering Ghouls while having the quest. 

**How it should work:** Considering every other quest item's drop rate is pretty much 100% on this server (feature) I think this should also drop way better instead of being forced to kill dozens of ghouls to get the drop. 

**Database links:** 
https://www.wowhead.com/wotlk/quest=11699/im-stuck-in-this-damned-cage-but-not-for-long
https://www.wowhead.com/wotlk/item=34957/engine-core-crystal
https://www.wowhead.com/wotlk/npc=25660/festering-ghoul

**Comment by Afgann** [comment]
fixed
