### ISSUE TITLE
[Paladin] Improved Lay on Hands doesn't always give the buff

### ISSUE THREAD

**Issue by oomshroom** [gamefreedomgit/Frostmourne#499]
Using Lay on Hands with 2/2 Improved Lay on Hands on a player other than self fails to give the damage reduction buff. Using it on self seems to work fine.

EDIT: seems to work sometimes but not always, difficult to test due to the long cooldown
~~EDIT2: might have something to do with targeting someone else and using a mouseover macro, not sure~~

**Comment by yeagerca** [comment]
Starting a duel will reset the cooldown of Lay on Hands. It can be helpful for testing.

**Comment by Afgann** [comment]
fixed
