### ISSUE TITLE
[Enhancement] Feral Spirits and Fire Elemental do not inherit your Melee Hit as their hit/expertise

### ISSUE THREAD

**Issue by Dova14** [gamefreedomgit/Frostmourne#50]
**Description:**
Feral Spirits currently miss and dodge on the heroic training dummy even while the shaman has well over hit cap (im at 376 Hit)
**How to reproduce:**
Grab an enhance with over hit cap and put wolves on a dummy, they will miss and dodge.

**How it should work:**
Feral Spirit should inherit your hit for their hit and expertise 

**Database links:**
https://wotlk-twinhead.twinstar.cz/?spell=51533
![Screenshot_6](https://github.com/gamefreedomgit/Frostmourne/assets/93952514/093ec445-e975-4475-84c8-d8113d158d6c)
![Screenshot_5](https://github.com/gamefreedomgit/Frostmourne/assets/93952514/e0029d75-7e4b-4a92-a440-17344d939fb2)

**Comment by Dova14** [comment]
After more testing, it seems they may be tied to your spell hit, as once i hit 17% spell hit on gear they stop missing completely.  It should be tied to your melee hit not spell hit cap

**Comment by Afgann** [comment]
fixed
