### ISSUE TITLE
Grace not applying to non-self targets

### ISSUE THREAD

**Issue by yeagerca** [gamefreedomgit/Frostmourne#502]
**Description:**
The Discipline Priest talent "Grace" is not applying to targets other than the caster.

**How to reproduce:**
Talent into Grace. Cast Flash Heal, Greater Heal, or Penance (heal) on a target other than the caster.

**How it should work:**
The listed spells should apply one stack of Grace per cast or tick, accumulating up to three stacks. Overhealing should also apply stacks. When Grace is applied to a new target, the old target loses all stacks of Grace.

**Database links:**
Grace Talent 2/2: https://www.wowhead.com/wotlk/spell=47517/grace
Grace Talent 1/2: https://www.wowhead.com/wotlk/spell=47516/grace
Grace Buff: https://www.wowhead.com/wotlk/spell=47930/grace

**Comment by Afgann** [comment]
fixed
