### ISSUE TITLE
Adjustments for Atiesh

### ISSUE THREAD

**Issue by RadeghostWM** [gamefreedomgit/Frostmourne#503]
**1. Item IDs were updated so need to swap it.**

OLD ID - NEW ID - COMMENT

22589 - 130023 - Atiesh (Mage) --quest reward
22630 - 130024 - Atiesh (Warlock) --quest reward
22631 - 130025 - Atiesh (Priest) --quest reward
22632 - 130026 - Atiesh (Druid) --quest reward
22726 - 130027 - Splinter of Atiesh -- drop
22727 - 130028 - Frame of Atiesh --drop 
22737 - 130029 - Atiesh (do questa w Stratholme chyba)

**2. Quest text and drop (8521)**

Change this paragraph:
"As for the base of the staff; the dwarf, Brann Bronzebeard, held it when he entered Ahn'Qiraj. He has left Ahn'Qiraj but the base of Atiesh remains."

To this:
"As for the base of the staff; the girl, Anveena Teague, held it when she entered the Sunwell Plateau. You should search there."

And the base should drop not from C'thun but Kil'jaeden in Timewalking SWP

**3. Anachronos: 15192 ID. He should be neutral to all players (shouldnt have Brood of Nozdormu faction)**

4. Atiesh boss: should be 80 level
5. Completing last quest should give achievement (it does) and title ID 193 (guardian of tirisfal) (it doesnt give title right now)

**Comment by UltraNix** [comment]
Fixed.
