### ISSUE TITLE
Localization issue

### ISSUE THREAD

**Issue by RRamz** [gamefreedomgit/Frostmourne#504]
![WoWScrnShot_053024_142104_cr](https://github.com/gamefreedomgit/Frostmourne/assets/128314906/f1153537-90bc-4fde-acaa-da4472ab14ca)

**How to reproduce:**
Approach the NPC in Dalaran.

Client: WotLK-Whitemane-Russian-v2
All addons are disabled.

**Comment by RRamz** [comment]
![111](https://github.com/gamefreedomgit/Frostmourne/assets/128314906/c688ebd0-2a20-405c-ae8f-6340830d4fa7)
Could you fix it?

**Comment by r0m1ntik** [comment]
Please fit it encoding in DB please :)

**Comment by r0m1ntik** [comment]
up

**Comment by Riztazz** [comment]
Fixed
