### ISSUE TITLE
[WARDEN][ADDON] Automatic quest turn-in AddOns sometimes causes disconnect

### ISSUE THREAD

**Issue by Nuy** [gamefreedomgit/Frostmourne#508]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Automatic quest turn-in AddOns like AutoQuest 2 sometimes causes disconnect. Automatic quest turn-in or pick-up is very useful and makes questing smoother so please fix it.

**How to reproduce:** Turn-in few quests with AutoQuest 2 AddOn.

**How it should work:** Auomatic quest turn-in shouldn't cause disconnect by anti-cheat.

**Database links:**

**Comment by Nuy** [comment]
I find it happens when your bags are full and you try to turn the quest with rewards. AddOn will spam turn unsuccessfully because bags are full and Warden detects it as flood I guess.

**Comment by Afgann** [comment]
fixed
