### ISSUE TITLE
Phoenix King Questline POIs

### ISSUE THREAD

**Issue by RadeghostWM** [gamefreedomgit/Frostmourne#509]
POI to turn; in quest 30000:
Map: 530 X: -1685 Y:7488 Z: 210 (Sig Nicious always has this POI when quest finishes at him)

POI 30001: .tele thunderstruck, turn in at sig nicious poi
POI 30002: .tele naxx, turn in at sig nicious poi
POI 30003: .tele sunwell, turn in at sig nicious poi
POI 30004: .tele obsidiansanctum, turn in at sig nicious poi
POI 30005: .tele eyeofeternity, turn in at sig nicious poi
POI 30006: Map 1 X:7984 Y:-2504 Z:487, tirn in at sig nicious poi
POI 30007: q is completed from the start, turn in at .tele blackrockdepths
POI 30008: no objective poi, turn in at .tele blackrockdepths
POI 30009: no objective poi, turn in at .tele blackrockdepths
POI 30010: completed from the beginning, turn in at sig niciouis

**Comment by UltraNix** [comment]
Fixed.
