### ISSUE TITLE
Auto-join WorldChat server and make the chat crossfaction

### ISSUE THREAD

**Issue by RadeghostWM** [gamefreedomgit/Frostmourne#510]
Auto join for all characters like in Cataclysm

**Comment by Godmatik** [comment]
hope you got a lot of GMs willing to monitor it

**Comment by nvrsbr** [comment]
Pretty sure this is not a place for suggestions.

**Comment by RadeghostWM** [comment]
> Pretty sure this is not a place for suggestions.

This is not a suggestion.
