### ISSUE TITLE
Traveler's Tundra Mammoth

### ISSUE THREAD

**Issue by RadeghostWM** [gamefreedomgit/Frostmourne#512]
Two vendor NPCs, when ejected, do not disappear. They just stand on the ground.

23642, 32641 ID of these NPCs.

**Comment by PanJanuszek** [comment]
![image](https://github.com/user-attachments/assets/ce0ac96b-55ee-41f5-9f99-446301824ad3)
![image](https://github.com/user-attachments/assets/1c12fe4c-828c-4e28-be1d-f31380b00c61)

cannot reproduce
