### ISSUE TITLE
Druid flight form gets canceled when herbing 

### ISSUE THREAD

**Issue by Flohinwow** [gamefreedomgit/Frostmourne#514]
**Description:**

Druid flight form gets canceled when herbing, when you try to herb the game gets rid of your flight form. 

**How to reproduce:**

Herb while in flight form.

**How it should work:**

It should let you herb while in flight form.

**Database links:**

Its a weird bug, On the 29 i could Herb while in flight form without getting dismounted but on the 30 is now canceling the form. Happened to another person as-well, no client changes from my part in between the two days, disable all add-ons to test.

![Screenshot 2024-05-30 at 20-06-58 Discord - Group Chat That’s All Fun   Games](https://github.com/gamefreedomgit/Frostmourne/assets/171302103/b67cbacb-f3a1-4cb2-9efd-41c0979aaadd)
![Screenshot 2024-05-30 at 20-03-55 Discord - Group Chat That’s All Fun   Games](https://github.com/gamefreedomgit/Frostmourne/assets/171302103/9206dc56-8042-4af5-a7be-488c7641d460)
![Screenshot 2024-05-30 at 20-03-48 Discord - Group Chat That’s All Fun   Games](https://github.com/gamefreedomgit/Frostmourne/assets/171302103/4f0c368b-9393-4ff4-9ce1-292cd24dc57f)

**Comment by UltraNix** [comment]
Fixed.
