### ISSUE TITLE
Nexus HC adds bugged

### ISSUE THREAD

**Issue by brooman04** [gamefreedomgit/Frostmourne#516]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
the dragon, and wraith adds near the 3rd boss constantly aggro from across the entire dungeon. Our group would get swarmed by adds while fighting the 2nd boss.

**How to reproduce:**
Walk near 2nd boss area. You will go into combat and mobs will show up a couple minutes later.

**How it should work:**
not this way.

**Database links:**

**Comment by Afgann** [comment]
fixed
