### ISSUE TITLE
[SWP] Gamebreaking  Kil'jaeden scripting issue

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#518]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
After phasing the boss, the timers for a dragon orb spawning and darkness of a thousand souls being cast should be 10 seconds apart, to give a player time to grab a dragon and shield the raid. This is the case when going into phase 3 and 4, but not when going into phase 5, the last phase. In the last phase, the dragon orb spawns after darkness has been cast. This is an issue since dragons only last for 120 seconds, and typically you can't use the dragon from phase 4 to save the raid in phase 5. As far as I can tell, the only way to kill the boss is to either have enough dps to trivialize the encounter and kill him early, or to use lust and dps cds in phase 4 to hopefully push him early enough to be able to use a 3rd shield with the previous dragon from phase 4.

**How to reproduce:**
Bring Kil'jaeden to 25% and observe the timings.

**How it should work:**
In phase 5, all of the dragon orbs should activate after 50 seconds, and darkness should start being cast after 60 seconds.

Side note: I would double check the timing during the phases, since there was one pull where I'm very sure the orb spawned at the same time as darkness started being cast in phase 2.

**Database links:**
https://www.wowhead.com/spell=46605/darkness-of-a-thousand-souls
Can't find a link to the dragon orb activation ability.

**Comment by Afgann** [comment]
fixed
