### ISSUE TITLE
[SWP] Gamebreaking Felmyst airphase "pathing" issue

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#519]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Felmyst flies in very unpredictable ways before doing her breath attack, making it essentially impossible to dodge and leads to near guaranteed wipes. Also, the boss flies towards the players a little and gets very close before picking a direction and almost immediately doing the breath, giving you even less time to react.. Currently there is a safe spot behind the big tree which can be used to easily kill the boss, but this safe spot should not be there.

Let me emphasize that you **cannot** remove the safe spot without fixing the boss movement before breaths as that would make it essentially impossible to kill reliably, and completely down to rng.

**How to reproduce:**
Wait for Felmyst to enter the air phase, and see how her movement doesn't really show you where she's going to breath early enough for it to be dodged.

**How it should work:**
The boss should clearly pick either the center or one of the sides a few seconds before the breath attack happens. It should also start from further away.

**Database links:**
https://www.wowhead.com/tbc/spell=45717/fog-of-corruption

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/931 https://github.com/gamefreedomgit/Frostmourne/issues/882 https://github.com/gamefreedomgit/Frostmourne/issues/973
