### ISSUE TITLE
Resurrection sickness

### ISSUE THREAD

**Issue by ravendale30** [gamefreedomgit/Frostmourne#52]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**

I tried dying and get the resurrection sickness and leave it and logout for an hour.  After i logged in an hour later, its still there
Is it intentional?

**How to reproduce:**

**How it should work:**
I think "normally" it will be removed even though the player is logged out.

**Database links:**

![image](https://github.com/gamefreedomgit/Frostmourne/assets/158454270/2bd39ecc-ef0f-4cce-b51f-15d4bdeb31d7)

**Comment by ravendale30** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/158454270/1b8ef36a-6503-4b4e-a272-9a861f9a8129)


![image](https://github.com/gamefreedomgit/Frostmourne/assets/158454270/c202258a-ebaa-4ac9-8f5c-1f10dc77f94b)


3 minutes apart

**Comment by Afgann** [comment]
https://www.wowhead.com/wotlk/spell=15007/resurrection-sickness#comments:id=396896

**Comment by Manpower99** [comment]
would be huge qol to actually let it tick while offline though
