### ISSUE TITLE
[SWP] Gamebreaking M'uru dark fiends bug

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#520]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The dark fiends that spawn from void zones in phase 2 of the M'uru encounter are not dispellable, and will run into players causing unhealable damage.

I assume this is the case for fiends that spawn in phase one as well, but we skipped those with enough dps.

**How to reproduce:**
Bring M'uru to phase 2, wait for him to spawn a void zone under you, run away from it, and try to use a magic dispel on the fiend that spawns from it.

**How it should work:**
The fiend should die when dispelled.

**Database links:**
https://www.wowhead.com/tbc/spell=46269/darkness
https://www.wowhead.com/tbc/npc=25744/dark-fiend

**Comment by Godmatik** [comment]
"I assume this is the case for fiends that spawn in phase one as well, but we skipped those with enough dps."

You should not be able to push Muru to P2 before one darkness even happens, wat? If this is the case, it's scaled very poorly

**Comment by Afgann** [comment]
fixed
