### ISSUE TITLE
Launch - mobs healing back to full randomly

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#521]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
As title says, this happens randomly. Might be related to hyperspawn? Or server update bug due to many connections?

**How to reproduce:**
Happens randomly when pulling mobs

**How it should work:**

**Database links:**

**Comment by itsemmastone** [comment]
This might be related to the high dynamic respawn rates we have for the launch phase. 

If this issue occurs again in a few days, please let me know in the comments below.
