### ISSUE TITLE
BGS - Flags/Caps don't award xp

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#522]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Under the assumption that xp award custom feature on this server is supposed to mimic cataclysm system, this is a bug.
Flag caps in WSG does not award XP, it should. Same with other bg caps.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
