### ISSUE TITLE
When in instance and loot drops, if you win item and inventory is full, item disappears from mob loot table

### ISSUE THREAD

**Issue by wmhina** [gamefreedomgit/Frostmourne#523]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When in instance and loot drops, if you win item and inventory is full, item disappears from mob loot table when u try to loot it

**How to reproduce:**
Be in instance. Have full bags. Win item. Get error message inventory full. Try to loot it. Get disapointed.

**How it should work:**
Item should still be on mob loot table

**Database links:**

**Comment by Manpower99** [comment]
have you checked your mailbox

**Comment by wmhina** [comment]
yes it was there sry im retard
