### ISSUE TITLE
Consumables not stacking properly

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#524]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
https://www.wowhead.com/wotlk/item=22779/scourgebane-draught#comments
https://www.wowhead.com/wotlk/item=22778/scourgebane-infusion

Should stack with flask and elixirs. Currently it replaces them. You can check the comments, these worked as an extra consumable on both OG wow and classic. It has been extensively used in classic as well so I'm sure there's plenty video proof for it.

**How to reproduce:**

**How it should work:**
It should not remove flask/elixirs and stack with everything else.

**Database links:**

**Comment by Afgann** [comment]
fixed
