### ISSUE TITLE
Rathilegore not giving item

### ISSUE THREAD

**Issue by tdaigo99** [gamefreedomgit/Frostmourne#525]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)https://discord.com/channels/1040715551531618365/1040715552227872809/1246244576583225455
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Hit Need after i killed rathilegore had 1 bag space open and didnt get the item, after going back to rathilegore the item wasnt in him

**How to reproduce:** hit need on rathilegore loot and items wont be in the inventory

**How it should work:** giving you the item in your inventory

**Database links:**
![WoWScrnShot_060124_022752](https://github.com/gamefreedomgit/Frostmourne/assets/171393017/c2138bdc-eadc-4669-8e88-a1c6f64ec28d)

**Comment by Afgann** [comment]
@tdaigo99 can you check if item is in your mailbox?

**Comment by tdaigo99** [comment]
I had checked A few times and after logging from my home it appeared in mailbox

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
