### ISSUE TITLE
Dungeon Complete rewards not granted

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#526]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Sometimes, killing the last boss and completing RDF does not grant rewards (XP & satchel)

**How to reproduce:**
No clue what causes it

**How it should work:**

**Database links:**

**Comment by Chubbychump** [comment]
It's a bit sad for low-level player like me to get to Satchel.

**Comment by UltraNix** [comment]
@BalanCV Specific bosses/difficulties or just random?

**Comment by WhitemaneIsa** [comment]
As there has been no further info/complaints, this will be closed for now.
