### ISSUE TITLE
Items from Postmaster with Random Enchantment

### ISSUE THREAD

**Issue by yeagerca** [gamefreedomgit/Frostmourne#527]
**Description:**
Items do not retain their random enchantment when mailed from the Postmaster. They have no enchantment at all. This bug occurred with the Duskwoven Amice.

**How to reproduce:**
While you have a full inventory, win a roll on an item that has a random enchantment. Check the mailbox message from the Postmaster returning the lost item to you.

**How it should work:**
Items with random enchantments should save their selected enchantment when being sent to the Postmaster.

**Database links:**
https://www.wowhead.com/wotlk/item=10063/duskwoven-amice

**Comment by Afgann** [comment]
fixed
