### ISSUE TITLE
Everlasting affliction bug (warlock)

### ISSUE THREAD

**Issue by Covidisreal** [gamefreedomgit/Frostmourne#528]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Drain life doesn't refresh corruption with "Everlasting Affliction" talent 

**How to reproduce:**
Drain life with corruption on target while having "everlasting affliction" talent in affliction tree

**How it should work:**
Should refresh 

**Database links:**
https://www.wowhead.com/wotlk/spell=47205/everlasting-affliction

**Comment by UltraNix** [comment]
Fixed.
