### ISSUE TITLE
[Important Quest] The Drakkensryd

### ISSUE THREAD

**Issue by Iramtempus** [gamefreedomgit/Frostmourne#529]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Range/Melee range needs to be reworked.
As a hunter I cannot melee the one I am sharing drake with, the ones in the distance change so much I cant kill them with range.
Needs to be fixed as its part of the Sons Of Hodir Quest Chain

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Iramtempus** [comment]
![Uploading image_2024-06-01_125515696.png…]()

**Comment by Iramtempus** [comment]
![WoWScrnShot_060124_125510](https://github.com/gamefreedomgit/Frostmourne/assets/88618448/eef6f3ca-1d06-43ee-8867-552f7db824c1)

**Comment by WhitemaneIsa** [comment]
Quest seems to be fine now, haven't heard any complaints since latest fix.

**Comment by Afgann** [comment]
fixed
