### ISSUE TITLE
[Demonology] Felguard not inheriting the owner's Hit Rating

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#53]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Felguard Melee hit and Cleave will occasionally miss while attacking a heroic training dummy, even if the warlock is above hit cap.

Testing was done on a warlock with 390 Hit Rating and 3/3 Suppression.

**How to reproduce:**
Attack a heroic training dummy with a Felguard while being over 17% spell hit, it will miss roughly 4.5% of its attacks.

**How it should work:**
Felguard hit% and expertise are inherited from the owner and therefore should not miss if the owner is above hit cap.

**Database links:**
https://wotlk-twinhead.twinstar.cz/?spell=30146
![wow_CBrYvZwuG5](https://github.com/gamefreedomgit/Frostmourne/assets/101921457/341fbde9-5d06-44c3-b850-b527050dda38)
![wow_9RBRq9KF1X](https://github.com/gamefreedomgit/Frostmourne/assets/101921457/14b7de9e-7966-4b50-bc09-63b598ac4930)
![wow_nHsRWwHy6Y](https://github.com/gamefreedomgit/Frostmourne/assets/101921457/43f32356-4425-435b-881b-fd1ea08370ad)
![wow_BVRwT1mXZa](https://github.com/gamefreedomgit/Frostmourne/assets/101921457/938d10e8-e610-42ae-b219-62165ac40237)

**Comment by Inukk** [comment]
After further testing I've noticed that all warlock pets require 17% spell hit in order to not miss any of their attacks (melee hits included) instead of the normal 8% melee hit for physical attacks and 17% spell hit for spells. Furthermore, the talent Suppression does not seem to increase the spell hit percentage of the warlock's pets.

**Comment by Afgann** [comment]
fixed
