### ISSUE TITLE
Stunned/CCd npc orientation

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#531]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The way stunned mobs face is not indicative of their actual facing/orientation. As such, it makes it difficult to find out where the mob's back is for backstab abilities. (May apply to players as well, which would make it pretty high prio for pvp, but have not tested, might be only npcs)

**How to reproduce:**
HoJ an NPC and it will face in a direction different from what he was before stun.

**How it should work:**

**Database links:**

**Comment by Manpower99** [comment]
Noticable

**Comment by Afgann** [comment]
fixed
