### ISSUE TITLE
[Profession fishing] Achievement not registering

### ISSUE THREAD

**Issue by GM-Nightmaree** [gamefreedomgit/Frostmourne#532]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
the coins arent getting counted after collecting them 

**How to reproduce:**
get fishing > fish coins in dalaran 

**How it should work:**
the coins should count in achievement 

**Database links:**
https://wowpedia.fandom.com/wiki/There%27s_Gold_In_That_There_Fountain

screenshots from a player 
https://cdn.discordapp.com/attachments/1246485068692848691/1246485165522288670/image.png?ex=665c8f46&is=665b3dc6&hm=9b0e5de23f8f6fe97a4f8dc4fe02b5934b04b5e3628124fad28a40620e2279cf&

https://cdn.discordapp.com/attachments/1246485068692848691/1246485139362681012/image.png?ex=665c8f3f&is=665b3dbf&hm=077647c352365a132887808b35a7c12441357e49f6ca5c3f16f3edf9236be7ba&

**Comment by emirie1** [comment]
Can confirm that this achievement is not working properly. The copper and silver coin achievements work and track fished up coins correctly. Only the gold coin achievement doesn't work.

**Comment by UltraNix** [comment]
Fixed.
