### ISSUE TITLE
[chainquest] The ring of blood 

### ISSUE THREAD

**Issue by GM-Nightmaree** [gamefreedomgit/Frostmourne#533]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
groups can stack bosses if its possible to create a "queue" so only 1 group could be active to do the quest 

**How to reproduce:**
players can take as much quests and npcs will stack making it impossible to do the bosses

**How it should work:**
make a queue system only 1 group to be able to take the quest 

**Database links:**
![image](https://github.com/gamefreedomgit/Frostmourne/assets/157993777/a7a2b207-3742-4f53-bf60-a8bb199d1ef1)
https://www.wowhead.com/tbc/quest=9962/the-ring-of-blood-brokentoe
https://www.wowhead.com/tbc/quest=9970/the-ring-of-blood-rokdar-the-sundered-lord
https://www.wowhead.com/tbc/quest=9972/the-ring-of-blood-skragath
https://www.wowhead.com/tbc/quest=9967/the-ring-of-blood-the-blue-brothers
https://www.wowhead.com/tbc/quest=9973/the-ring-of-blood-the-warmaul-champion
https://www.wowhead.com/tbc/quest=9977/the-ring-of-blood-the-final-challenge

**Comment by UltraNix** [comment]
Fixed.
