### ISSUE TITLE
[QUEST] The Drakkensryd

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#538]
Two big issues with this quest

1. The respawn rate of the mobs you need to kill on the drakes is incredibly low, nearly all the drakes are empty always
2. Very often when jumping on a drake with a mob on it, you will receive errors about not being able to melee/attack it because it is not in front of you.

**Comment by ChronoWM** [comment]
Quest: https://www.wowhead.com/wotlk/quest=12886/the-drakkensryd

Once you jump to a drake, _most of the times_ you cannot target the riders directly. Forcing players to use AOE abilities only.
Additionally players lose the disguise during the encounter.

**Comment by Afgann** [comment]
fixed
