### ISSUE TITLE
Sholazar Basin blatant incorrect mob placement

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#540]
East of Frenzyheart Hill

![frenzies](https://github.com/gamefreedomgit/Frostmourne/assets/37913400/1befa516-83d2-4318-8974-803d726987c0)

South of Frenzyheart Hill

![frenzies2](https://github.com/gamefreedomgit/Frostmourne/assets/37913400/0042f075-fc4d-4d22-a5a1-8b749b44b4d4)

**Comment by UltraNix** [comment]
Fixed.
