### ISSUE TITLE
Unable to defeat Hyldsmeet Drakeriders

### ISSUE THREAD

**Issue by jamesonhp1995** [gamefreedomgit/Frostmourne#544]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When harpooning the Hyldsmeet Proto-Drake during the quest "The Drakkensryd", upon killing the Hyldsmeet Drakeriders they do not count towards the quest. Sometimes when targeting the drake riders, you are unable to cast spells.

**How to reproduce:**
Harpoon to a Hyldsmeet Proto-Drake.
Defeat the Hyldsmeet Drakerider.
Note that you didn't receive credit for the kill

**How it should work:**
Harpoon to a Hyldsmeet Proto-Drake.
Defeat the Hyldsmeet Drakerider.
Note that you received credit for the kill

**Database links:**
https://wowpedia.fandom.com/wiki/Hyldsmeet_Proto-Drake
https://wowpedia.fandom.com/wiki/The_Drakkensryd
https://wowpedia.fandom.com/wiki/Hyldsmeet_Drakerider

**Comment by Greyedge8** [comment]
This should be marked with a high priority. This is part of the quest chain to unlock 'Sons of Hodir' rep.

**Comment by WhitemaneIsa** [comment]
Seems to be fixed since latest fix, haven't heard further complaints.
