### ISSUE TITLE
pet wont move when given any command

### ISSUE THREAD

**Issue by Valafar77** [gamefreedomgit/Frostmourne#545]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
my pet will not move at all outside of following me once combat is over. It will not attack anything not next to it and is completely stuck.

**How to reproduce:**
if you abandon the pet and get a new one, it works like normal for a bit then will bug eventually. the issue happens reguardless of addons or macros, and even occurs using /petattack. You can see the pet try to engage, but it cannot move. 

**How it should work:**
pet should follow or attack when given command or on aggro/def, not stand still

**Database links:**

**Comment by UltraNix** [comment]
#571
