### ISSUE TITLE
Hungarfen from Underbog instant kill 

### ISSUE THREAD

**Issue by Heigan1** [gamefreedomgit/Frostmourne#546]
**Description:**
Boss Hungarfen from The Underbog kills players instantly with Mushroom ability. Mushrooms are also not visible when spawned.

**How to reproduce:**
Attack first boss from The Underbog, he will cast Mushroom ability taking much more hp than it should.

**How it should work:**
Hungarfen will spawn mushrooms which should grow in size and then explode into Spore Cloud. Spore Cloud should inflict some damage and stacks to 5 times. 

**Database links:**

**Comment by Afgann** [comment]
fixed
