### ISSUE TITLE
Zul'farak event

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#548]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The goblin does not open the door to the final boss after the event is over.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by WhitemaneIsa** [comment]
Caused by players staying in combat with the goblin (NPC ID 7607 https://www.wowhead.com/npc=7607/weegli-blastfuse) itself after the combat event ended. 

![grafik](https://github.com/gamefreedomgit/Frostmourne/assets/164479303/c0506b7f-813e-44b8-85af-e6fc13daa780)

**Comment by Afgann** [comment]
fixed
