### ISSUE TITLE
[Death Knight] 3/3 Reaping does not trigger death rune convert with blood strike

### ISSUE THREAD

**Issue by wotlkenjoyer** [gamefreedomgit/Frostmourne#549]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/158612010/8125542d-ae6a-49c0-b417-c10e2ad03d00)

It should proc from blood strike and pestilence, currently procs only with pestilence, even if you take 3/3

https://www.wowhead.com/wotlk/spell=56835/reaping

**Comment by Afgann** [comment]
fixed
