### ISSUE TITLE
AH sold items not shown

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#554]
**Description:**
When you sell an item on AH, the only way to tell is that it doesn't show anymore in your auction list, money comes in mail an hour later
I'm not sure what's meant to be implemented here, but it should be one of the following:
- Show in your auction list but as sold with an hour cooldown
- get mail saying item sold (worst)
- get gold instantly (best)

**Comment by UltraNix** [comment]
Nothing bugged here.
When you sell item, there is an info on your chat:
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/9220835a-503b-4440-8a3b-de752b587241)
