### ISSUE TITLE
[ROGUE] Cheap shot stun delay

### ISSUE THREAD

**Issue by radeghostmademedoit** [gamefreedomgit/Frostmourne#557]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
If you cheap shot an NPC they still have about 0.2 seconds to cast or attack. Maybe it's also with other stuns

**How to reproduce:**
Cheap shot any npc

**How it should work:**
NPC should not be able to attack when cheap shotted

**Database links:**

**Comment by Godmatik** [comment]
confirmed for all stuns

**Comment by UltraNix** [comment]
Fixed.
