### ISSUE TITLE
[The Culling Stratholme] Arthas bugs out

### ISSUE THREAD

**Issue by radeghostmademedoit** [gamefreedomgit/Frostmourne#558]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Arthas can bug out and you can't continue the dungeon.

**How to reproduce:**
Go in the dungeon and do the first waves. When he arrives one can not talk to him.

**How it should work:**
Arthas should never bug out

**Database links:**

**Comment by UltraNix** [comment]
@radeghostmademedoit What phase of the instance? You mean before 2nd boss? Or maybe before the gauntlet?

**Comment by UltraNix** [comment]
Fixed.
