### ISSUE TITLE
[Halls of Lightning] Mobs from the gauntlet after second boss aggro through the door

### ISSUE THREAD

**Issue by radeghostmademedoit** [gamefreedomgit/Frostmourne#559]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
At least one of the mobs from the gauntlet after second boss is already hostile and aggroes through the door.

**How to reproduce:**
Go there.

**How it should work:**
Mobs should not aggro before the gauntlet

**Database links:**

**Comment by wotlkenjoyer** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/91

**Comment by wotlkenjoyer** [comment]
was reported  long time ago and even have fixed  status, but i  saw the same  again today, there are screenshots in post i gave above

**Comment by Afgann** [comment]
fixed
