### ISSUE TITLE
[ROGUE] Killing spree sometimes puts you on the ground floor in a dungeon

### ISSUE THREAD

**Issue by radeghostmademedoit** [gamefreedomgit/Frostmourne#560]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Sometimes when you do Killing Spree in a Dungeon you end up on the ground floor of the map, outside off the intended way. you need to port out and in again.

**How to reproduce:**
Happened in Utgarde and Hellfire ramparts, randomly.

**How it should work:**
You should not bug through the floor when using Killing Spree

**Database links:**

**Comment by Afgann** [comment]
fixed
