### ISSUE TITLE
[The Nexus] Lots of Mana Wraiths missing

### ISSUE THREAD

**Issue by radeghostmademedoit** [gamefreedomgit/Frostmourne#561]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
There should be a lot more Mana Wraiths. They usually accompany the arcane walkers or what they are called.

**How to reproduce:**
Go look and see there are none there.

**How it should work:**
There should be more mana wraiths.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
