### ISSUE TITLE
Grizzly Hills Quest Issues

### ISSUE THREAD

**Issue by Greyedge8** [gamefreedomgit/Frostmourne#564]
**Description:**
Issue with 'Filling the Cages' quest. Unable to complete.

**How to reproduce:**
Accept quest, attempt to recruit Budd to sap a troll.

**How it should work:**
A pet bar should appear, allowing the ability to control Budd to sap a troll. The pet bar never appears, not allowing control of Budd and preventing quest completion.

**Database links:**
Wowhead link: https://www.wowhead.com/wotlk/quest=11984/filling-the-cages

**Comment by UltraNix** [comment]
Fixed.
