### ISSUE TITLE
[Tailoring? / looting] Some loot from mobs doesn't get looted

### ISSUE THREAD

**Issue by Covidisreal** [gamefreedomgit/Frostmourne#565]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Some loot (mostly frostweave cloth) is unlootable when killing big packs of mobs. Not only it doesn't get looted, u also can't loot it separately.

P.S It feels like "Northrend cloth scavenging" bonus isn't getting looted at all, although it doesn't explain why some other items weren't looted either (maybe because that same mob contained some cloth from the proc 

**How to reproduce:**
Farm humanoids in northrend (was farming onslaught harbor, but seen same issue with others too)

**How it should work:**
Should collect all the loot?

**Database links:**
https://www.wowhead.com/wotlk/item=43876/a-guide-to-northern-cloth-scavenging 
*DB from classic

**Comment by UltraNix** [comment]
Fixed.
