### ISSUE TITLE
All heals are delayed

### ISSUE THREAD

**Issue by Askanis** [gamefreedomgit/Frostmourne#568]
There's a significant delay between healing someone and the party/raid frame updating the health bar. Never experienced this on any other WotLK server and I will most likely not continue playing a healing spec unless fixed. It feels pretty bad. If it stems from spell batching, well then spell batching needs to be tuned better.

**Comment by Afgann** [comment]
Its spell batching, we reduced it today by a little bit, you can check again to see if its fine.

**Comment by Askanis** [comment]
After a couple more days of farming heroics I can say it's still on a level where it affects the healing game play very negatively. It's difficult to make split second decisions on this server when everything is delayed. It needs to be more or less instant.

**Comment by sorath-gr** [comment]
I experience the same issue as resto druid, especially with Nourish. Most of the times, it lands with delay, instead of being instant. It feels like it's waiting for the HoT to tick in order to land together. The weird thing is that this happens only with Nourish spell. Every other healing spell works fine.

I really can't play like this. I try to save the tank when he take huge damage, and I see my spell not landing on him, causing much confusion!

**Comment by Askanis** [comment]
> I experience the same issue as resto druid, especially with Nourish. Most of the times, it lands with delay, instead of being instant. It feels like it's waiting for the HoT to tick in order to land together. The weird thing is that this happens only with Nourish spell. Every other healing spell works fine.
> 
> I really can't play like this. I try to save the tank when he take huge damage, and I see my spell not landing on him, causing much confusion!

Yeah it's a pretty awful experience.

**Comment by sorath-gr** [comment]
@Afgann Any update on this? Is anyone looking at it?

**Comment by sorath-gr** [comment]
OK, just to add that this happens with all direct heals from all classes. For example, it has the same effect on my resto shaman.

I believe that spell batching, should be removed from PvE (instances & raids).

**Comment by Riztazz** [comment]
fixed, will close once it's live
