### ISSUE TITLE
Culling of Strat - Trash waves

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#569]
The 8 trash waves for Culling of Strat dungeon always spawn in same spots - they should be random. Same as first two boss spawns.

Also the mobs and boss do not patrol upon spawning as they should.

Finally on wave 5 and wave 10 (boss waves), the flag does not appear on minimap for them

P.S. The zombies are giving 2 rep each and should not.

**Comment by UltraNix** [comment]
Fixed.
