### ISSUE TITLE
[Dungeon Finder] Missing Loot Rules under Need Before Greed

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Frostmourne#57]
**Description:**
Players loot rules under Need Before Greed for Dungeon finder

**How to reproduce:**
Players class - equipment rules are not fully set properly, players can roll for items that doesnt belong to their Spec

**How it should work:**
It should follow proper loot rules to prevent ninja looting
[loot rules.xlsx](https://github.com/gamefreedomgit/Frostmourne/files/14131755/loot.rules.xlsx)

**Comment by MrTide** [comment]
URL updated
Shaman > mail/leather roll requirement
Hunter > mail/Leather roll requirement

**Comment by Afgann** [comment]
fixed
