### ISSUE TITLE
Riding skill on Warlocks 

### ISSUE THREAD

**Issue by Ronove123** [gamefreedomgit/Frostmourne#579]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Im playing a Warlock, got the 2 first mounts for free, but when i try to buy the flying, i need to buy the first 2 riding skills i should already have cause i've been using the horse for days :P, heard from a friend he had the same issue on his paladin.

**How to reproduce:**

**How it should work:**
I guess it shouldnt ask me to buy a skill i already have.

**Database links:**

**Comment by Godmatik** [comment]
Same occurs with druid flying form.

Learning it should give 225 riding for free, but currently does not. We have to train it to get cold weather flying.

**Comment by RadeghostWM** [comment]
It works as it's supposed to. Having learned 100% mount is already an advantage, not so say anything about 150% flying on Druid.

**Comment by Godmatik** [comment]
@RadeghostWM 

Incorrect - it is not currently working correctly. Please reopen.

![225riding](https://github.com/gamefreedomgit/Frostmourne/assets/37913400/e3b5b3bc-3b22-4864-9aa1-f149b0c68ee3)

**Comment by eruiluvatar93** [comment]
I think Radeghost didn't understand what OP was saying. Everyone gets Journeyman riding for free so why when I want to learn Expert I still have to pay for Journeyman. I play as paladin I got both riding skills for free tho Expert didn't showed up in my skill tab. I don't mind paying for expert but I shouldn't be paying for Journeyman. It's not working as it supposed to and they closed few issues here without resolving them.
