### ISSUE TITLE
[Dungeon Hall of stones] Brann bronzebeard 

### ISSUE THREAD

**Issue by GM-Nightmaree** [gamefreedomgit/Frostmourne#581]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Brann bronzebeard doesnt reset if the group wipes 

**How to reproduce:**
Wipe during the tribunal of ages encounter and Brann bronzebeard wont reset it will just lay down dead

**How it should work:**
brann bronzebeard should reset after wiping

**Database links:**
https://www.wowhead.com/wotlk/npc=28070/brann-bronzebeard
https://www.wowhead.com/wotlk/quest=13207/halls-of-stone

**Comment by UltraNix** [comment]
#572
