### ISSUE TITLE
A Lesson in Fear quest

### ISSUE THREAD

**Issue by SapoQLxd** [gamefreedomgit/Frostmourne#582]
When impaling the vrykuls with the banner, the quest doesn't update to 1/1 for each.

Kill any of the surrounding enemies to spawn the named enemies, kill them then use the banner on their corpse.

It should update to 1/1 a couple of seconds after you plant the banner on any of the named mobs.

https://www.wowhead.com/wotlk/quest=11282/a-lesson-in-fear

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/c29eba58-659b-42ef-b98e-7e4431faf877)
Were you in raid group maybe?

**Comment by UltraNix** [comment]
Nvm - I've found the cause.

**Comment by devnatetanner** [comment]
> Nvm - I've found the cause.

What was the cause for those running into the same issue?
