### ISSUE TITLE
Novos gauntlet

### ISSUE THREAD

**Issue by roperoperope** [gamefreedomgit/Frostmourne#584]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I used thunderstorm to knock back an add that comes from the entrance and it got knocked underground. We had to reset by running out of the room.

**How to reproduce:**
Let the add come, try to knock it back to the stairs

**How it should work:**
Should not be knocked underground.

**Database links:**

**Comment by Afgann** [comment]
fixed
