### ISSUE TITLE
Azjol-Nerub Watcher Gashra aggros Krik'thir the Gatewatcher

### ISSUE THREAD

**Issue by yeagerca** [gamefreedomgit/Frostmourne#585]
**Description:**
When Watcher Gashra is aggroed during the first boss encounter of Azjol-Nerub it automatically aggros Krik'thir the Gatewatcher.
Bug occurred on Heroic difficulty.

**How to reproduce:**
Do the Krik'thir encounter in Azjol-Nerub.

**How it should work:**
Krik'thir should not aggro until attacked or until all three watchers have died.

**Database links:**
https://www.wowhead.com/wotlk/npc=28684/krikthir-the-gatewatcher
https://www.wowhead.com/wotlk/spell=52343/krikthir-subboss-aggro-trigger

**Comment by radeghostmademedoit** [comment]
and it can also aggro the boss as well

**Comment by Afgann** [comment]
fixed
