### ISSUE TITLE
"Shoot 'Em Up" quest cannons not working

### ISSUE THREAD

**Issue by StaticHispanic** [gamefreedomgit/Frostmourne#586]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Shots from the harpoon cannon aren't damaging the targeted drakes.

https://github.com/gamefreedomgit/Frostmourne/assets/142506452/d3aa417b-7b05-494d-8710-df2fb7955282

**How to reproduce:**

**How it should work:**
https://www.youtube.com/watch?v=hLel9QpTuwE

**Database links:**

**Comment by Godmatik** [comment]
Confirmed

Some of the drakes dont take damage.

Also if a drake dies near the cannon, the body covers it up, so u cant shoot from it anymore cause it blocks you

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
