### ISSUE TITLE
Azjol-Nerub Hadronox can drop players through the floor

### ISSUE THREAD

**Issue by yeagerca** [gamefreedomgit/Frostmourne#587]
**Description:**
Hadronox can pull players through the floor with Web Grab. This happens most often when Hadronox is standing on a slope at a lower elevation than the player.

**How to reproduce:**
Place Hadronox on a slope and stand higher than it. Wait for Web Grab to pull you through the floor.

**How it should work:**
Players should not be pulled to a location below the floor.

**Database links:**
https://www.wowhead.com/wotlk/npc=28921/hadronox
https://www.wowhead.com/wotlk/spell=59420/web-grab
https://www.wowhead.com/wotlk/spell=59421/web-grab

**Comment by yeagerca** [comment]
I was going to make a separate report, but I realized it was the same problem.

Description:
Anub'ar Necromancer or other mobs are being pulled beneath the bottom webs where they remain in combat but cannot be harmed by Hadronox. These Necromancers continuously spawn Animated Bones, causing intense FPS lag for everyone rendering them on their screen.
https://imgur.com/a/7TSa9vU

How to reproduce:
Kill a single Anub'ar Crusher so that Hadronox moves 1/3 of the way up the tunnel. At this position Hadronox is above a slanted web where the mobs surrounding it can be pulled below the floor.

How it should work:
NPCs should not be pulled to a location below the floor.

Database links:
 https://www.wowhead.com/wotlk/npc=28921/hadronox
 https://www.wowhead.com/wotlk/spell=59420/web-grab
 https://www.wowhead.com/wotlk/spell=59421/web-grab

https://www.wowhead.com/wotlk/npc=28922/anubar-crusher

https://www.wowhead.com/wotlk/npc=28925/anubar-necromancer
https://www.wowhead.com/wotlk/npc=29064/anubar-necromancer
https://www.wowhead.com/wotlk/npc=29098/anubar-necromancer
https://www.wowhead.com/wotlk/npc=29119/anubar-necromancer
https://www.wowhead.com/wotlk/spell=53334/animate-bones

**Comment by UltraNix** [comment]
Fixed.
