### ISSUE TITLE
Heirloom stats are not counted at level ups

### ISSUE THREAD

**Issue by RubyOnWhitemane** [gamefreedomgit/Frostmourne#588]
**Description:** If you level up while having Heirlooms equipped, your post-level up health & mana will ignore the bonus stats you receive from the Heirloom items, meaning that you get hurt and lose mana if they were higher than that before leveling up:

https://streamable.com/uzqxvf

**How to reproduce:** Equip Heirlooms and gain a level up

**How it should work:** Your health and mana should be set to full when you level up, just like it does on normal, non-Heirloom gear.
Proof: https://youtu.be/0ZJsqTPtfCY?t=567 (You can see the player has cloth heirlooms equipped, levels up and has full health and mana)

**Database links:** https://www.wowhead.com/wotlk/guide/heirlooms-overview#heirlooms-with-emblems-of-heroism

**Comment by RubyOnWhitemane** [comment]
I can confirm it is fixed.

**Comment by UltraNix** [comment]
Fixed.
