### ISSUE TITLE
Rogue

### ISSUE THREAD

**Issue by Betelgaza** [gamefreedomgit/Frostmourne#589]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

The Rogue is bugged. During the Shadowstep attack, he lands inside the enemy, which drains my HP and prevents me from attacking from behind. Additionally, during Stunlocks with Cheap Shot and Kidney Shot, the monster turns around, and sometimes it visually appears to be facing one way but is actually facing the other.

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
@Betelgaza Give us some examples of mobs where you land inside them.

**Comment by radeghostmademedoit** [comment]
Killing spree is also in the mob and not behind him. pls fix

**Comment by Betelgaza** [comment]
> @Betelgaza Give us some examples of mobs where you land inside them.

All monsters. Just yesterday, everything was fine with shadowstep, but now this problem has appeared. It is related to the incorrect placement of the monster when an attack is made. Similar to stuns (cheap shot, kidney shot), the monster suddenly changes its facing direction. For example, I attack it with kidney shot from the front, and the monster suddenly turns its back to me. The same thing happens when using shadowstep: I use shadowstep and I don't appear behind the mob but inside it, which causes it to detect and attack me

**Comment by GraveofBears** [comment]
https://www.youtube.com/watch?v=R5X2prRSVr0

I noticed that in discord they said the problem was fixed, but I still seem to have this same issue with feral cat.

**Comment by UltraNix** [comment]
Should be fixed.
