### ISSUE TITLE
[Raid Loot]  Naxxramas  Bosses not dropping loot after killing them.

### ISSUE THREAD

**Issue by GM-Nightmaree** [gamefreedomgit/Frostmourne#59]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Bosses in Naxxramas not dropping loot

**How to reproduce:**
Killing Gluth , Loaltheb and Thaddius under group loot dropped 0 items

**How it should work:**
Bosses should drop items when killed.

**Database links:**
https://www.wowhead.com/npc=15932/gluth
https://www.wowhead.com/classic/npc=16011/loatheb
https://www.wowhead.com/classic/npc=15928/thaddius

If any information is needed i'd happily provide more !

**Comment by GM-Nightmaree** [comment]
Update 
the four house men also

**Comment by GM-Nightmaree** [comment]
Kel'Thuzad as well dropped one item !
![Uploading Kel'Thuzad.png…]()

**Comment by Afgann** [comment]
fixed
