### ISSUE TITLE
Ressurection Sickness Whitemane+

### ISSUE THREAD

**Issue by Auranin** [gamefreedomgit/Frostmourne#590]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Healthy Ressurrection does not work when resurrected. Had this in Un'Goro at level 54.

**How to reproduce:**
See above

**How it should work:**
No ress sickness anywhere

**Database links:**

**Comment by Auranin** [comment]
Hi mate, yes. It has been for a while!

**Comment by UltraNix** [comment]
Hmm, I cannot reproduce it.
I die, then click on Release Spirit, talk to spirit healer, talk to him and then got resurrected without any sickness.
What's your char name?

**Comment by WhitemaneIsa** [comment]
This was/is likely related to Whitemane+ not loading in properly sometimes.

**Comment by WhitemaneChronus** [comment]
Here's a similar issue that shows Whitemane plus is active but player is still getting the debuff.
![Screenshot 2024-06-30 124050](https://github.com/gamefreedomgit/Frostmourne/assets/170808156/d57ea892-cab0-4091-bd91-c82039146fdf)

**Comment by WhitemaneIsa** [comment]
@UltraNix

**Comment by WhitemaneIsa** [comment]
Haven't heard any further issues since. Closing.
