### ISSUE TITLE
Druid Flight Form - 225 skill not learned automatically

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#591]
When learning flight form at level 60, you should also get 225 riding automatically.

Currently you do not, so you are required to pay 250g for it in order to learn cold weather flying + 300 riding later.

![225riding](https://github.com/gamefreedomgit/Frostmourne/assets/37913400/3af6c8ce-dc53-445f-b81e-ce7c1defb342)

**Comment by yeagerca** [comment]
Paladins also did not automatically learn fast ground riding when auto-learning their fast ground mount. Not sure if they're supposed to or not though.

**Comment by Godmatik** [comment]
They are

**Comment by sorath-gr** [comment]
I confirm, that we (druids) miss the skill while we have flying form. It should be there, without the need to go pay and learn it.

**Comment by Manpower99** [comment]
So can this be fixed so Paladins and Druids get their mount skill?

**Comment by UltraNix** [comment]
Flight Form is learnt from our autolearn feature, but not the riding skill - you still must pay for it - like other classes.
