### ISSUE TITLE
elixir of renown not giving 100% reputation

### ISSUE THREAD

**Issue by switchykins** [gamefreedomgit/Frostmourne#592]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
used elixir of renown to boost reputation gain with 100%, quest "mending fences" for sons of hodir still only gave 22.000 reputation which is the standard amount.

**How to reproduce:**
use item "elixir of renown" and complete quest "mending fences"

**How it should work:**
should give 100% reputation

**Database links:**

https://www.wowhead.com/wotlk/quest=12915/mending-fences

**Comment by UltraNix** [comment]
This quest is not affecting by this potion.
