### ISSUE TITLE
No flight path to Honor Hold from The Dark portal

### ISSUE THREAD

**Issue by bl2x14** [gamefreedomgit/Frostmourne#593]
Amish Wildhammer doesn't offer a flight path to Honor Hold from The Stair of Destiny in Outland

https://imgur.com/a/aDangrS

**How it should work:**
There should be a flight path available from this NPC to known Flight Masters

**Comment by UltraNix** [comment]
You need to comple and reward https://www.wowhead.com/quest=10140/journey-to-honor-hold.

**Comment by bl2x14** [comment]
> You need to comple and reward https://www.wowhead.com/quest=10140/journey-to-honor-hold.

There is no quest there.
