### ISSUE TITLE
Baron Aquantis - Wrong damage values

### ISSUE THREAD

**Issue by Missix12** [gamefreedomgit/Frostmourne#594]
So I was going to solo Baron Aquantis in Blackfathom Deeps at lvl 28 hc rogue. Damage values of this mini boss are broken (200 non crit, 500 crit), so much that i was unable to do anything about this. I put links to 2 videos from classic wow 2019 that both shows this mini boss dmg values. Not many players fought this guy because you need a quest to summon him. I would like to ressurect my rogue because i died to poor values and not my fault. 

![WoWScrnShot_060324_164122](https://github.com/gamefreedomgit/Frostmourne/assets/95503509/df587dd0-4d1b-4677-bec0-7e331f286713)
![WoWScrnShot_060324_164127](https://github.com/gamefreedomgit/Frostmourne/assets/95503509/8aface4c-a6a8-499f-b948-169fa16f2a0f)
![WoWScrnShot_060324_164131](https://github.com/gamefreedomgit/Frostmourne/assets/95503509/6e9d5022-d545-4a42-a590-9bf80c3de7ab)

https://www.youtube.com/watch?v=NBW5NoRHuQQ
https://www.youtube.com/watch?v=ehXV0stmDrM

**Comment by Afgann** [comment]
fixed
