### ISSUE TITLE
Ample inspiration

### ISSUE THREAD

**Issue by Laxor1** [gamefreedomgit/Frostmourne#595]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
ample inspiration quest in stormpeaks 
**How to reproduce:**
there should be mammoth so i can use bomb to get meat
**How it should work:**
when u get the quest there should be mammoths to see and kill them 
**Database links:**
https://wow.zamimg.com/uploads/screenshots/normal/110770-ample-inspiration.jpg
https://www.wowhead.com/quest=12828/ample-inspiration

**Comment by ChronoWM** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/226#issuecomment-2145477574
Can confirm the issue.
Player and NPCs are on the same phase, already checked.

**Comment by UltraNix** [comment]
Fixed.
