### ISSUE TITLE
Jumping off elevators early gives full fall dmg

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#596]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
As title says, doesn't matter how close elevator is to ground if you go off before it completely lands you take full fall dmg and die

**How to reproduce:**
jump or walk off elevator before it completely lands

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
