### ISSUE TITLE
Slows are not being applied to mage talents

### ISSUE THREAD

**Issue by Shahadath45** [gamefreedomgit/Frostmourne#597]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

MAGE aoe Talents - Improved Blizzard and Frostbite in the FROST TREE are not applying their improved slow to mobs. Mobs are still moving at their normal speed. 

**How to reproduce:**

When using blizzard with Frostbite, all mobs affected should move very slowly, which gives you more time to use another blizzard or kite. Mobs are walking through the blizzard at their regular speed, hitting the caster even before the first blizzard is over. 

https://www.youtube.com/watch?v=68Ux9I23b1c   

see vid at 4:30 

i am exactly in the same area trying the same thing and im being chased at normal speed. Mobs are not being slowed.

**Comment by Afgann** [comment]
fixed
