### ISSUE TITLE
Azjol-Nerub Heroic 

### ISSUE THREAD

**Issue by For3v3** [gamefreedomgit/Frostmourne#598]
Description: Heroic Dungeon Issue Azjol-Nerub

How to reproduce: 1st Boss. After pulling first 2 pack of mobs, last third pack coming with Boss

How it should work: 1st pack after this coming 2nd pack, 3-rd pack, and finally boss. (not together)

**Comment by Afgann** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/585
