### ISSUE TITLE
Northrend Quests not giving any gold

### ISSUE THREAD

**Issue by Voormas2** [gamefreedomgit/Frostmourne#599]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I've recently arrived in Warsong Hold as Voormas, a level 68 Death Knight. I quickly noticed all the quests only give experience, and NO gold. I've done a good handful by now, everything in Warsong Hold, Warsong Farms and Garrosh's Landing, and have received 0 gold for completing them. Everything else seems to be normal. Please help, and if possible, refund my damn gold. 

**How to reproduce:**

**How it should work:**
I should be rewarded gold from completing quests. 

**Database links:**

**Comment by Godmatik** [comment]
Some give gold, and some do not. It depends on the quest, they are all working just fine for me.

**Comment by UltraNix** [comment]
@Voormas2 Give us some examples of such quests.

**Comment by WhitemaneIsa** [comment]
As there has been no further info/complaints, this will be closed for now.
