### ISSUE TITLE
PvE Tuning + Time logs

### ISSUE THREAD

**Issue by RadeghostWM** [gamefreedomgit/Frostmourne#6]
**10-Man Raids**
All 10-Man versions should be left without any buffs, however, there should be an NPC at the start of the raid that enables **hard mode**; it can be enabled by Raid Leader and cannot be disabled until raid resets on Wednesday. Hard Mode will buff the raid bosses (using some boost that we have from previous server, we need to pick the most difficult one and buff it even more), and make them drop the same emblems as 25-Man, and drop 25-Man loot (but item number should be kept - so 2 items each boss).

**25-Man Raids**
We should use Frosthold version.

**Time logs**
Log times of boss kills so it's stored somewhere.

**Comment by Afgann** [comment]
fixed
