### ISSUE TITLE
[ROGUE] Tricks of the Trade gives the rogue aggro

### ISSUE THREAD

**Issue by radeghostmademedoit** [gamefreedomgit/Frostmourne#600]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
If you tricks of the trade the tank and he runs in to mobs you get aggro as a rogue, even though you shouldn't and the spell isn't active.

**How to reproduce:**
Cast Tricks of the Trade on someone who runs in to a mob

**How it should work:**
You should not get aggro from casting Tricks of the Trade on someone. 

**Database links:**

**Comment by bandini9** [comment]
I am unsure but even eating when facepull generates aggro, probably ToT shouldnt generate though

**Comment by UltraNix** [comment]
Fixed.
