### ISSUE TITLE
Crystals in Violet Hold dungeon not working

### ISSUE THREAD

**Issue by Xennpai** [gamefreedomgit/Frostmourne#601]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Crystals in Violet Hold dungeons are not working

**How to reproduce:**
Just go in the dungeon and they don't work at all

**How it should work:**
It should be clickable and killing all packs

**Database links:**

**Comment by Godmatik** [comment]
worked fine for us earlier

**Comment by Godmatik** [comment]
Well this was yesterday, maybe it broke since then, let me re-test in a bit, we just got it in queue

**Comment by Godmatik** [comment]
Works but only if you use them against the pack of 3 or 4 trash mobs that spawn

**Comment by Xennpai** [comment]
The crystal itself is not clickable for me at all

**Comment by Afgann** [comment]
Did it happen on normal or heroic?

**Comment by Xennpai** [comment]
On Heroic

**Comment by Xennpai** [comment]
So we entered the dungeon (thro RDF) and wiped on first boss (didn't use any crystals at all) after the wipe we get the pack of 3 mobs from portal and when I went to click the crystal it was unclickable.

**Comment by Afgann** [comment]
fixed
