### ISSUE TITLE
Azjol Nerub

### ISSUE THREAD

**Issue by radeghostmademedoit** [gamefreedomgit/Frostmourne#603]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
That whole dungeon is fucked. come on

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/587
https://github.com/gamefreedomgit/Frostmourne/issues/585
