### ISSUE TITLE
Mob leashing & aggro

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#606]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
-NPC initial leash is too high. They follow you forever without attacking them. Initial leash should be around 60% of what it is right now and can be extended further when hits are applied.
-Also NPC aggro range when same level as player is too high, should be slightly reduced.

**How to reproduce:**
Aggro mobs in open world

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
