### ISSUE TITLE
Paladin journeyman riding

### ISSUE THREAD

**Issue by adam4523** [gamefreedomgit/Frostmourne#608]
[//]: # (REMEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Paladins get their fast mount at level 40 with journeyman riding but in-game it still requires you to pay for it before learning flying.

**How to reproduce:**
Get a paladin to level 60 go to riding trainer and try to learn flying.

**How it should work:**
You should already have journeyman riding learned

**Database links:**

**Comment by Godmatik** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/591

related
