### ISSUE TITLE
Cant extend Heroic Lockouts

### ISSUE THREAD

**Issue by Nihaobeachez** [gamefreedomgit/Frostmourne#609]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** You are currently unable to extend the lockouts of heroic dungeons. Youll see the Green Text "extended" for a split second but it resets to default straight away ... might not work for raids either perhaps 

very easy to reproduce 

Go to the according list of ids,  press extend and see that it doesnt work 
Prio high pls
![image](https://github.com/gamefreedomgit/Frostmourne/assets/96308500/b41b3882-e09a-412f-9f07-898c0801b7cc)

**How to reproduce:** Finish Dungeon

**How it should work:** Heroic Dungeons should be extentable

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
