### ISSUE TITLE
Dungeon Finder reward incorrect

### ISSUE THREAD

**Issue by ammenvale** [gamefreedomgit/Frostmourne#61]
**Description:**
Currently on PTR the Dungeon Finder rewards the following:
Random Lick King Dungeon: 4 Emblem of Conquest
Random Lich King Heroic: 6 Emblem of Conquest

**How to reproduce:**
Open LFG tool on PTR

**How it should work:**
Set the right reward for T7 content:
Random Lick King Dungeon: 2 Emblem of Heroism (once daily, then gold)
Random Lich King Heroic: 2 Emblem of Valor (once daily, then 2 Emblem of Heroism)

**Database links:**
https://www.bluetracker.gg/wow/topic/eu-en/11824414332-the-dungeon-finder-what-to-know/

**Comment by Afgann** [comment]
fixed
