### ISSUE TITLE
Stefan Vadu aggroing Flying fiend when use Stefan's horn

### ISSUE THREAD

**Issue by lilazngrlx3** [gamefreedomgit/Frostmourne#610]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Stefan Vadu aggroing Flying fiends when use Stefan's horn 

**How to reproduce:**
Use stefan horn by the reliquary of pain if flying fiend in air above you he will aggro them and its really slow for him to take down/he can die

**How it should work:**
he should just fly down so you can take/hand in quest

**Database links:**
https://www.wowhead.com/wotlk/item=41390/stefans-horn

**Comment by UltraNix** [comment]
Fixed.
