### ISSUE TITLE
Fuel for the fire

### ISSUE THREAD

**Issue by lilazngrlx3** [gamefreedomgit/Frostmourne#612]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Bloated abomination casts flatulence without casting it and stops moving when its used

**How to reproduce:**
mind contrl the abom to move to trolls with attack button and when it attacks will cast it on cooldown even though no auto-cast making it hard to move to group a lot of trolls together

**How it should work:**
should only cast flatulent when owner casts it.

**Database links:**
https://www.wowhead.com/wotlk/quest=12690/fuel-for-the-fire

**Comment by UltraNix** [comment]
Fixed.
