### ISSUE TITLE
Sons of Hodir reputation

### ISSUE THREAD

**Issue by roperoperope** [gamefreedomgit/Frostmourne#614]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I did all the quests for sons of hodir reputation I could find, Thorim does not give me quests anymore and im stuck at hated 22520/36000. I am using the old whitemane client with the new patch. Now I did pick the sons of hodir rep incrase from the daily even tho I didnt unlock them completely, could that have bugged it out, im not sure.

**How to reproduce:** Do all the quests u see, have it bug out idk

**How it should work:** That I am not completely sure since I've only played on Warmane and it gave us exalted after finishing the questline.

**Database links:**

**Comment by Godmatik** [comment]
https://www.wowhead.com/wotlk/item=41556/slag-covered-metal


Check if you have this time, it is often overlooked

**Comment by roperoperope** [comment]
did it while i was doing the fjorn quest

**Comment by Godmatik** [comment]
You should open GM ticket then so they can tell you what part of chain you on. It's not bug since everyone I know has done this np and I see lots of people doing the dailies around me.

**Comment by roperoperope** [comment]
i opened it bro, one gm responded to me " i cant help u with this, gotta wait till head gm logs on" or something like that, so im just stuck waiting here now

**Comment by Godmatik** [comment]
Sounds like you need wait for head GM then

**Comment by WhitemaneIsa** [comment]
"Mending Fences" giving -22k instead of +22k, already known to dev team - fixed manually for rope & all other players

**Comment by WhitemaneIsa** [comment]
Lord bless the heavens (devs) this seems to be fixed, I haven't heard further reports.
