### ISSUE TITLE
exhausted vrykul

### ISSUE THREAD

**Issue by lilazngrlx3** [gamefreedomgit/Frostmourne#615]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
really long respawn timers on these mobs for hodir questline

**How to reproduce:**
quest Discipline

**How it should work:**
should be plenty of exhausted vrykul but when a lot of people doing quest really long respawn timer on these

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
