### ISSUE TITLE
quest: the last of her kind

### ISSUE THREAD

**Issue by lilazngrlx3** [gamefreedomgit/Frostmourne#617]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Issue when leaving brunhildr village to valley of ancient winters to do the quest the last of her kind you dont get disguise anymore. When riding bear back to village for quest you aggro the guards as the disguise doesnt come back on until you're up the path in brunhildr

**How to reproduce:**

**How it should work:**
Disguise should be up before you approach the guards to brunhildr village

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
