### ISSUE TITLE
Salram and Meathook RDF HC CoS

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#618]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
After they spawn they do not patrol forward and backward and simply sit still where they are.

**How to reproduce:**

**How it should work:**
they should move forward

**Database links:**

**Comment by Godmatik** [comment]
It's not just that.

None of the trash patrols as it should.

Also wave 5 + 10 do not show flag on minimap.

Also the trash wave spawns should be random

**Comment by Manpower99** [comment]
Yup, the trash waves seem to be in fixed locations and the bosses too, there is enough proof through videos that they shouldnt be.
Priority imo should be to allow patrols to happen and fix the minimap flags as those can be quite frustrating and a time consumption to race against the drake despawning.
Would highly appreciate if arthas pathing (moving through walls) and ai against zombies is improved.

**Comment by UltraNix** [comment]
Fixed.
