### ISSUE TITLE
Last Line of Defense Icecrown Argent Crusade Quest

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#619]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
after finishing last line of defense character is stuck until relog
which only happens by alt f4ing
even dying by ganks i cant release spirit

**How to reproduce:**

finish q and u are stuck
**How it should work:**
shouldnt be stuck

**Database links:**

**Comment by yeagerca** [comment]
Happened to me earlier today. I used Divine Intervention on someone to try to get out then could not release because I was falling. Needed to relog to fix it.

**Comment by UltraNix** [comment]
I just finished that quest and no stuck happened.
Maybe something specific happened with your characters?

**Comment by yeagerca** [comment]
If I recall correctly, after turning in the quest I was teleported to a position just in front of the little shed the quest giver is in, except I was slightly in the air stuck in a falling animation.
The issue could be related to the quest phasing, quests leading up to it, or maybe an interaction with RDF teleports during the quest chain. I've only heard from a few people that this happened and most of them I know were RDFing.

**Comment by WhitemaneIsa** [comment]
> I just finished that quest and no stuck happened. Maybe something specific happened with your characters?

Whatever is leading to it definitely happens to a lot of people, you also sometimes get stuck with them when you .appear on them. Some get stuck inside the stand itself, some get stuck a little further away from it. There is no other fix than relogging, summoning, killing, unaura all do not work.

**Comment by UltraNix** [comment]
Fixed.
