### ISSUE TITLE
[Quest] Slaying the Beast

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#62]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Taragaman the Hungerer is only dropping the quest item for 1 person.

**How to reproduce:**
Kill Taragaman while in a group, only 1 person will get the quest item.

**How it should work:**
The quest item should drop for everyone that has the quest.

**Database links:**
https://www.wowhead.com/classic/quest=5761/slaying-the-beast

**Comment by Afgann** [comment]
fixed
