### ISSUE TITLE
Krystallus Shatter 

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#620]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
while everything works as intended it is unlikely that this damage is scaled properly based on distance.
wotlk dungeons are intended to be easy and farmable and due to rdf you can easily be matched with 3 melees in greens which is in 90% of the cases going to kill atleast one even if they are standing pretty far away primarily due to the limited area we work with.
Please Re Evaluate the damage done by Shatter.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Firalus** [comment]
The damage and and damage scaling is fine. If you're standing alone you're looking to receive survivable damage.

There is another issue though, which is the fact that all pets, guardians and other entities such as shaman totems are targets for the mechanic, while I'm 99.9% sure anything that's not a player should be ignored - it's a carbon copy of the Gruul mech after all, which I'm completely positive only affected players in retail TBC.

**Comment by PanJanuszek** [comment]
Shatter does not make damage to pet if you stand nearby. Yes, as a player you see that pet is Stoned aka petrified. However there is no damage for pet owner when standing nearby.

Unless, you have some video?

**Comment by Manpower99** [comment]
> Shatter does not make damage to pet if you stand nearby. Yes, as a player you see that pet is Stoned aka petrified. However there is no damage for pet owner when standing nearby.
> 
> Unless, you have some video?

this was fixed months ago, boss is fine now
