### ISSUE TITLE
A lesson in Fear

### ISSUE THREAD

**Issue by Thurne** [gamefreedomgit/Frostmourne#621]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The quest "A Lesson in Fear" in Howling Fjord is not working correctly. You can kill the Vrykul, but it doesn't register you planting the Banner in the corpse.

**How to reproduce:**

**How it should work:**
Banner should be registered once planted in the corpse

**Database links:**
https://www.wowhead.com/wotlk/quest=11282/a-lesson-in-fear

**Comment by PanJanuszek** [comment]
Cannot reproduce

![image](https://github.com/user-attachments/assets/5535dd85-eaf5-4117-bfe4-465f58e59677)
![image](https://github.com/user-attachments/assets/0ddef458-ae64-440c-931e-a1ca0d8364b3)
![image](https://github.com/user-attachments/assets/64b17efb-c37a-4f2b-89e2-9d35f6484297)
