### ISSUE TITLE
(Warlock) Drain Life not refreshing corruption with 5/5 Everlasting Affliction

### ISSUE THREAD

**Issue by blahxd** [gamefreedomgit/Frostmourne#622]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Drain Life not refreshing corruption with 5/5 Everlasting Affliction

**How to reproduce:**

**How it should work:**
It should reset Corruption to its maximum duration after every application. Haunt, Shadow Bolt and Drain Soul work as intended

**Database links:**

**Comment by Godmatik** [comment]
Was already reported, server is restarting soon to fix so try after
