### ISSUE TITLE
NPC stealth detection too high

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#624]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Hostile npcs (even those of lower level than me) can detect me in stealth before i even have time to cheap shot them.

**How to reproduce:**
Approach same level(or -1/2) hostile npc from the front and he will react and attack too quickly, taking you out of stealth.

**How it should work:**
Cone detection seems to be working as approaching them from the back usually leads to successful cheap shot, while the front is more prone to detection(as intended). However, either stealth detection or mob reaction is too high since you should be able to land a stealth spell even when approaching from the front on mobs of the same level or lower (which does not happen currently)

**Database links:**

**Comment by GraveofBears** [comment]
I run into this with Druid and Cat Stealth, even with points in imp stealth, the detection is a bit off.

Using "Cat Feral Charge in Stealth" the enemy often detects us if you charge from the front, if charging from the side/back it doesn't. The spell is intended to place the player behind the target undetected, but when passing through the target you're often attacked and knocked out of stealth.

I also have a hard time when opening on a target from behind, that I am not actually behind the target, I assume this might be the same with using Backstab after opening with Stun:
https://www.youtube.com/watch?v=R5X2prRSVr0

**Comment by UltraNix** [comment]
Fixed.
