### ISSUE TITLE
Satchel of Exotic Mysteries

### ISSUE THREAD

**Issue by enaeroe** [gamefreedomgit/Frostmourne#626]
**Description:**
Doesn't receive Satchel of Exotic Mysteries while in a premade group for Random Heroic Dungeon.

**How to reproduce:**
Do Random Heroic Dungeon in a premade.

**How it should work:**
Give the reward regardless of it being a premade or random group.

**Database links:**

**Comment by UltraNix** [comment]
Already fixed.
