### ISSUE TITLE
Sunwell plateau lv70 is closed

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#627]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Because of the timewalking change you can't enter the lv70 version of sunwell. People usually run those for pre-bis items on fresh and for transmog later on. Now that is impossible.
On other servers they made it such that changing to 25hc would put you in the timewalk version and 25nm would be the lv70 as usual.
On previous sunwell servers there was an npc inside the dungeon that the leader could talk to to enable the modified version of dungeons.
Perhaps something like this could be enabled here?

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by WhitemaneIsa** [comment]
This is not a bug but already under investigation.

**Comment by Afgann** [comment]
fixed
