### ISSUE TITLE
Don't work quest on Icecrown arena

### ISSUE THREAD

**Issue by Apakalipsis1992** [gamefreedomgit/Frostmourne#628]
**Description:** On Icecrown arena don't work third quest in line. The boss flies in on a dragon, stands there for a while and disappears.

**How to reproduce:** Just take third quest on Icecrown arena.

**How it should work:** Quest should work. Fight with boss.

**Database links:** https://wotlk.cavernoftime.com/quest=13216

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/698
