### ISSUE TITLE
Turgid the Vile

### ISSUE THREAD

**Issue by roperoperope** [gamefreedomgit/Frostmourne#629]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** I just knocked Turgid thru the walls where he stands with thunderstorm.

**How to reproduce:** Weaken him, let him grab u with his ability, knock him the opposite direction where he was originally looking.

**How it should work:** Shouldnt be able to knock him thru the wall, i guess.

**Database links:**

**Comment by PanJanuszek** [comment]
I was not able to reproduce using Thunderstorm, Typhon. Tested 10x. If you can reproduce it and film, then pls open the ticket with movie and angle.
