### ISSUE TITLE
[Raid Loot] Malygos not dropping loot after defeating him.

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#63]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Alexstrasza's Gift is empty after defeating Malygos.

**How to reproduce:**
Looting Alexstrasza's Gift with group loot dropped 0 items .

**How it should work:**
Alexstrasza's Gift should drop items.

**Database links:**
https://www.wowhead.com/wotlk/npc=28859/malygos
https://www.wowhead.com/wotlk/object=193905/alexstraszas-gift

**Comment by Afgann** [comment]
fixed
