### ISSUE TITLE
Scatter Shot

### ISSUE THREAD

**Issue by sacredarrow99** [gamefreedomgit/Frostmourne#630]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Movement is too spastic and unpredictable, the target can either keep going in 1 way and then make a sharp turn for no reason, or move fast like a maniac left, right, forward backward, making it virtually impossible for a hunter to trap afterwards, the target just moves away from the trap.

**How to reproduce:**

**How it should work:** The target should be moving slightly, slower, and in a much more confined area, not walk away 5 feet like when you get feared by a Priest

**Database links:**

**Comment by slicplaya** [comment]
PLease fix. omg I will love you.

**Comment by UltraNix** [comment]
Fixed.

**Comment by slicplaya** [comment]
<3
