### ISSUE TITLE
Hunter pet pathing

### ISSUE THREAD

**Issue by sacredarrow99** [gamefreedomgit/Frostmourne#631]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**  Strange hunter pet pathing, doesn't go on command every time or stops mid way. When it comes to macros (focus macro pet stun) it doesn't go to the focused target to stun it, only when I manually click on the target and send him.

**How to reproduce:**

**How it should work:** Well, the complete opposite

**Database links:**

**Comment by UltraNix** [comment]
@sacredarrow99 Happened on open world or bg? Pet was away from you?
Also, show this focus macro.

**Comment by sacredarrow99** [comment]
> @sacredarrow99 Happened on open world or bg? Pet was away from you? Also, show this focus macro.

mostly bg where I actually needed the focus macro applied, but I did notice inconsistent pet behavior (starts dashing towards mob and starts mid way or does a few strikes, mob moves away and the pet doesn't follow it despite being actively sent to attack it)

Focus pet stun macro is tested and works perfectly fine on multiple servers I've played, including previous projects of Whitemane/Sunwell crew. Had no issue on Synergie with literally the same macro

#showtooltip Ravage(Rank 5)
/cast [target=focus] Ravage(Rank 5)


(and yes, I do change the rank of the spell accordingly to pet's level)

**Comment by slicplaya** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/639 I can 100% confirm the skill Ravage as well as pet pathing is screwed up atm.

**Comment by slicplaya** [comment]
The pet doesn't path at all once the skill Ravage is Queued. It literally stands there and does nothing.
