### ISSUE TITLE
[Rogue] Killingspree now ports you 10 meters behind the target sometimes

### ISSUE THREAD

**Issue by radeghostmademedoit** [gamefreedomgit/Frostmourne#633]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
After the last fix to the rogue abilities Killing spree and Shadowstep, now it ports you sometimes like 10m behind the target.

**How to reproduce:**
Use kIlling spree

**How it should work:**
One should stay just behind but not in the target

**Database links:**

**Comment by radeghostmademedoit** [comment]
I guess the problems are Critters around that instantly die. After they die Killing spree doesn't know where to jump again probably

**Comment by radeghostmademedoit** [comment]
happens all the time in Halls of the Stones

**Comment by radeghostmademedoit** [comment]
also happens in Halls of Lightning a lot. didn't see any critters around though

**Comment by UltraNix** [comment]
@radeghostmademedoit Still valid?

**Comment by WhitemaneIsa** [comment]
As there has been no further info/complaints, this will be closed for now.
