### ISSUE TITLE
Delete This Issue

### ISSUE THREAD

**Issue by Xennpai** [gamefreedomgit/Frostmourne#635]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Comment by Xennpai** [comment]
This issue is reported by a friend of mine, not me directly so he has all information

**Comment by Rosenaries** [comment]
can confirm this issue exist, noticed it too in sunwell at twins, sacrolash hits only with main hand. looks like global issue with NPCs that have dual wield weapons.

**Comment by Apakalipsis1992** [comment]
I also noticed this problem. It applies to all mobs and bosses who have 2 weapons in their hands

**Comment by wowclassic1234** [comment]
![image (26)](https://github.com/gamefreedomgit/Frostmourne/assets/173220680/ffc82e85-0395-473a-93e5-ef7153d168a7)

If errors that directly affect the damage per second of the boss receive the Low Priority status, then is it worth reporting problems of the same kind? About the incorrect speed of automatic attacks from raid bosses? Or will they also receive a low priority and be postponed indefinitely?

**Comment by wowclassic1234** [comment]
Up

**Comment by Xennpai** [comment]
up

**Comment by wowclassic1234** [comment]
Make a global edit for mobs that own two weapons, please. The dungeons are already too simple, all NPCs lack immunity to different types of control (low, mute, stan, interrupt) Besides, some NPC don't hit with two hands either. The next patch Ulduar will be released, you will strengthen the dungeons, but what's the point of that? If Npc still don't have immunity and don't hit with two hands?

**Comment by wowclassic1234** [comment]
I had a desire to write a topic about the missing types of NPC immunities, and other flaws with bosses in 5 ppl dungeons, but looking at this unclosed topic, I lost the desire to do this because I understand that all subsequent types of errors of this type are also ignored.

**Comment by RadeghostWM** [comment]
> I had a desire to write a topic about the missing types of NPC immunities, and other flaws with bosses in 5 ppl dungeons, but looking at this unclosed topic, I lost the desire to do this because I understand that all subsequent types of errors of this type are also ignored.

They are not ignored. See our changelog. 

This will get fixed before 3.1 hits.

**Comment by wowclassic1234** [comment]
UP
