### ISSUE TITLE
Fears and Hexes and possibly other CCs have no DR

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#636]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Multiple dungeons such as sunken temple/zulfarrak and draktheron keep etc have mob packs that cast hexes and fears which are not DRing at all. if unlucky you could be permanently feared.
I have not tested player polymorph/hexes/saps/fears yet but i will as soon as i can and comment on this or do a seperate report . it is super bugged and can catch many players by surprise.
**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
