### ISSUE TITLE
Paladin Mounts

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#638]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Paladin learns 40 mount on autolearn without journeyman riding, you can use it but if you wanna progress further you have to purchase journeyman to purchase Flying, would be nice if its fixed and we dont have to spend that extra gold

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
#608
