### ISSUE TITLE
Hunter pet Ravager skill Ravage not working correctly

### ISSUE THREAD

**Issue by slicplaya** [gamefreedomgit/Frostmourne#639]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** The skill "Ravage" by a ravager doesn't work properly. If the pet isn't in range and at hunter's feet, upon using the skill, it'll bug out and stand still making the attack sound. If i petpassive and send pet to attack, and halfway to the target cast ravage, it stops dead in it's tracks, makes the attack animation sound and will not move. The only time ravage works is if the pet is already on the target, and it will stay still afterwards again not attacking or moving. This is game breaking especially for PvP.

**How to reproduce:**
Tame a ravager, do said above circumstances, and watch the ravager not move.

**How it should work:**
When casting/using the skill "Ravage" from a ravager in any position the pet is in, the pet should attempt to move to the target turn on petattack, and use the skill upon reaching the proper melee distance range.

**Database links:**

https://wowpedia.fandom.com/wiki/Ravage_(pet_ability)?so=search

**Comment by UltraNix** [comment]
Fixed.
