### ISSUE TITLE
[Quest] Hellscream's Vigil

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#64]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Currently you can grab this quest twice for the turn in XP.

**How to reproduce:**
Talk to the questgiver, you'll see the quest available twice

**How it should work:**
Should only be able to grab the quest once.

**Database links:**
https://www.wowhead.com/wotlk/quest=11586/hellscreams-vigil

**Comment by Afgann** [comment]
fixed
