### ISSUE TITLE
It Goes To 11

### ISSUE THREAD

**Issue by Raulfin** [gamefreedomgit/Frostmourne#640]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Quest: 'It Goes To 11' (11421) 
The 'Harpoon Control Mechanism' (34032) doesn't work unless you are right on top of the Vrykul Harpoon Gun (27993).
Dragonflayer Defenders (24533) 'Harpoon Toss' (44188) has a near 0 cast time.
Dragonflayer Defenders spawn on a short timer.
Dragonflayer Defenders don't despawn/phase when your harpoon dies or you exit vehicle.
As is players get overwhelmed vary fast and cannot escape the defenders, leading to a few deaths and the nearest GY is in Valgarde so it takes a bit to run back each time.

**How to reproduce:**
hop in the harpoon.

**How it should work:**
Control Mechanism should have a larger radius to put you in the harpoon, it is listed as 5yd on the effect page (50331).
3-4 Dragonflayer Defender should spawn when you destroy a building, not every few seconds.
Harpoon toss should have a 1.5 cast time.
Despite Harpoon toss having 0cd the mobs should only use it every 3-5secs, not instantly when not on cd.

**Database links:**
https://www.wowhead.com/wotlk/quest=11421/it-goes-to-11

**Comment by ChronoWM** [comment]
Confirmed issue and mobs are not spawning - quest is not doable

**Comment by UltraNix** [comment]
Fixed.
