### ISSUE TITLE
[Dungeon] Drakkari Elemental – Surge through the wall

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#641]
[Drakkari Elemental](https://www.wowhead.com/wotlk/npc=29573/drakkari-elemental) does go out of arena and through the wall when he uses [Surge](https://www.wowhead.com/wotlk/spell=54801/surge) ability. Then he proceeds to return normally through the corridor.
Observed on Normal Difficulty, wasn't able to go heroic yet.

**Comment by Godmatik** [comment]
Confirmed seen it on heroic.

He should not be able to go through the walls

**Comment by Greywolf59** [comment]
Closing this since it was resolved in another issue
