### ISSUE TITLE
Hira Snowdawn not associated to Kirin Tor

### ISSUE THREAD

**Issue by Calior1919** [gamefreedomgit/Frostmourne#645]
Hira Snowdawn, the flight trainer in Dalaran is not associated to the Kirin Tor faction so reputation with Kirin Tor does not reduce the cost of training. The NPC should be associated with the Kirin Tor.

https://www.wowhead.com/npc=31238/hira-snowdawn

**Comment by Godmatik** [comment]
Intended - not a bug

She did not become associated with Kirin Tor until Cataclysm expansion



![403](https://github.com/gamefreedomgit/Frostmourne/assets/37913400/61fe9d38-2dc2-4458-85c5-e8467f68c604)
