### ISSUE TITLE
Riding Turtle - Store Mount - Not account shared

### ISSUE THREAD

**Issue by WhitemaneIsa** [gamefreedomgit/Frostmourne#646]
**Description:**
Riding Turtle - Store Mount - Not account shared
23720

**How to reproduce:**
Use it on a char, check your other char, won't show up

**How it should work:**
All mounts except class mounts should be shared

**Database links:**
https://www.wowhead.com/item=23720/riding-turtle

**Comment by GM-Nightmaree** [comment]
https://www.wowhead.com/wotlk/item=49290/magic-rooster-egg
as well
magic rooster isnt account shared :/

**Comment by GM-Nightmaree** [comment]
https://www.wowhead.com/item=32458/ashes-of-alar
as well 
not account shared

**Comment by UltraNix** [comment]
Fixed.
