### ISSUE TITLE
"High Priest Talet-Kha" required for quest "Words of Power" untargeteable

### ISSUE THREAD

**Issue by MK192s** [gamefreedomgit/Frostmourne#647]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
![image](https://github.com/gamefreedomgit/Frostmourne/assets/170763049/41e2aed5-2706-47c9-a250-cb7eac63bec6)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by WhitemaneIsa** [comment]
Works as intended, you need to kill the two "Mystical Webbing" in order to make her targetable/interrupt her meditation.
