### ISSUE TITLE
Hunter traps not procing on a target dummy

### ISSUE THREAD

**Issue by Mixetaa** [gamefreedomgit/Frostmourne#65]
Since the latest changelog on wotlk ptr, target dummy in GM island can't proc any of my hunter traps.
![WoWScrnShot_020224_133255](https://github.com/gamefreedomgit/Frostmourne/assets/158359423/c73ce15b-6e3f-4c05-ba1a-8fafd38199aa)
But I can say that they work normaly on any other mobs:
![WoWScrnShot_020224_133605](https://github.com/gamefreedomgit/Frostmourne/assets/158359423/2165db1e-f51d-4e21-9c44-e85fcdbf75f0)

**Comment by Mixetaa** [comment]
I wanna add that I just found out that you "can" trap target dummies in GM Island, but only if you are in a duel. Outside of a duel you can't.

**Comment by Afgann** [comment]
fixed
