### ISSUE TITLE
Crossfaction BG Que

### ISSUE THREAD

**Issue by roperoperope** [gamefreedomgit/Frostmourne#650]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** My friend and I are not able to que for BG's together since we r opposite faction.

**How to reproduce:** Try to que with opposite faction.

**How it should work:** Should be able to since its a whitemane qol.

**Database links:**

**Comment by Afgann** [comment]
fixed
