### ISSUE TITLE
Army of the Dead

### ISSUE THREAD

**Issue by roperoperope** [gamefreedomgit/Frostmourne#651]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Army of the Dead is currently interruptable.

**How to reproduce:** Cast Army of the Dead , have a mage interrupt u or some other class.

**How it should work:** Should not be interruptable unless by a spell that moves ur character, thunderstorm, death grip etc..

**Database links:**

**Comment by UltraNix** [comment]
https://www.wowhead.com/spell=42650/army-of-the-dead#comments:id=442998
Not a bug.
