### ISSUE TITLE
[Achievement] The Keymaster

### ISSUE THREAD

**Issue by emirie1** [gamefreedomgit/Frostmourne#652]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The general achievement "The Keymaster" is not properly registering the collection of keys associated with the achievement.
![WoWScrnShot_060424_193739](https://github.com/gamefreedomgit/Frostmourne/assets/130517865/3b0d403b-fc90-47d2-8459-5c9dd4d8fc69)

**How to reproduce:**
Track the achievement and then collect any key associated with it. It will not update.

**How it should work:**
Collecting an associated key should mark it as completed in the achievement list.

**Database links:**
https://www.wowhead.com/wotlk/achievement=1187/the-keymaster

**Comment by UltraNix** [comment]
Should be fixed already.
