### ISSUE TITLE
[Enchanting] Item cannot be disenchanted

### ISSUE THREAD

**Issue by erikpowa** [gamefreedomgit/Frostmourne#653]
**Description:**
Items can not be disenchanted:
[The Sharp Cookie](https://www.wowhead.com/wotlk/item=30568/the-sharp-cookie#disenchanting)
[Arkadian Claymore](https://www.wowhead.com/wotlk/item=30570/arkadian-claymore#disenchanting)
[Helm of the Burning Soul](https://www.wowhead.com/wotlk/item=37746/helm-of-the-burning-soul)

**How to reproduce:**
Have Enchanting. Try to disenchant the items listed above. You get error "Item cannot be disenchanted".

**How it should work:**
Should be disenchantable

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
