### ISSUE TITLE
Shaman totems

### ISSUE THREAD

**Issue by Firalus** [gamefreedomgit/Frostmourne#654]
**Description:**
Shaman totems are being targeted by damage reflecting/chaining abilities, as well as random target abilities.

**How to reproduce:**
Use a damaging totem vs. a mob with some form of damage reflection (such as Lightning Shield) or a mob that uses Chain Lightning (haven't confirmed for Cleave), or a boss using a random aggro spell (notable example - Jormungar Worm in Gortok the Palehoof encounter in UP).

**How it should work:**
Totems shouldn't receive AoE/chain/reflection/random damage.

**Comment by UltraNix** [comment]
Tested Chain Lightning - cannot jump to totems.

**Comment by UltraNix** [comment]
I see no random spells used by Jormungar Worm. When activated, it selects random player from map. But if your totem do damage and therefore make more threat, it becomes the 1st target.

**Comment by WhitemaneIsa** [comment]
No further info/complaints, closing.
