### ISSUE TITLE
Ley Guardian Elegos whelplings

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#655]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Watched every video i could on youtube, not a single kill do the whelps wipe the dungeon after elegos is dead.
on frostmourne currently if you kill elegos the whelps continue fighting you instead of despawning.

**How to reproduce:**

**How it should work:**
Despawns whelps that were brought to the fight after defeating him

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
