### ISSUE TITLE
Sjonnir the Ironshaper

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#656]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Couple of issues ever since today's HC Bosses damage increase have risenin multiple dungeons.
Sjonn's damage while enraged is ridiculous for the leveling of gear intended for random heroics ( ilevel average barrier of entry being 160 atm tanks are melting instantly )
When Sjonnir the Ironshaper reaches 20% health remaining, he goes into a frenzy. Frenzy increases attack speed by 50% and Physical damage done by 100%. coupled with the increase of dmg already this is getting too much to handle with randoms.
His adds are not despawning upon his death.

https://www.youtube.com/watch?v=3_OP-63rnlM
https://www.youtube.com/watch?v=geR-riuv-o0
**How to reproduce:**

**How it should work:**
Properly tune Bosses damage instead of just give a percentage increase to everything so his enrage is challenging and not just downright impossible with randoms.
despawn his adds upon defeat.

**Database links:**

**Comment by Afgann** [comment]
fixed
