### ISSUE TITLE
Unrelenting Construct HOS

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#657]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Unrelenting Construct in HoS have a couple of issues
Their AoE lightning damage explosion should be a cast that you can outdamage before they fully cast it. if it succeeds it will kill them as it happens and  should deal an average of 8k nature damage.
on frostmourne it happens instantly and does often too much damage.
https://www.youtube.com/watch?v=zf3Y8YZEw40

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.

**Comment by Manpower99** [comment]
@UltraNix the cast time is working now but it does not kill the caster aka the Unrelenting Construct if the cast goes successfully.

**Comment by UltraNix** [comment]
Fixed.
