### ISSUE TITLE
Skarvald the Constructor abilities

### ISSUE THREAD

**Issue by Oxynium** [gamefreedomgit/Frostmourne#658]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Skarvald the Constructor (2nd boss Utgarde Keep) resets threat every time he uses charge ability.

Additionally, he doesn't seem to ever use Stone Strike ability 

Stone Strike:
Inflicts 100% of normal weapon damage and knocks back the enemy.
(https://www.wowhead.com/wotlk/spell=48583/stone-strike) 

**How to reproduce:**
Tested on normal difficulty, pull the boss and watch threat table whenever he uses charge. 

**How it should work:**
Charge should stun the target but threat table should stay as it was.

**Database links:**
https://www.wowhead.com/wotlk/npc=24200/skarvald-the-constructor

**Comment by UltraNix** [comment]
Fixed.
