### ISSUE TITLE
Skadi the Ruthless - Aggro Table Issue

### ISSUE THREAD

**Issue by Greyedge8** [gamefreedomgit/Frostmourne#659]
**Description:**
Seems like the aggro table for Skadi isn't functioning correctly. The first hint that something was wrong, was when I was shielding the tank for the first pack of mobs as I ran passed Skadi. He hit me once and took almost all of my life while he was mounting the drake. Then, many times in one lockout, Skadi would immediately head towards the healer (me) when he would land after being harpooned. The hunter attempted to MD, but it only put the healer and the tank at the same level on the aggro table.

**How to reproduce:**
Fight Skadi. The healer will get targetted when he comes down off of his mount.

**How it should work:**
Skadi's aggro table should start when he lands. Any attentive tank should be able to taunt immediately and grab aggro before Skadi goes to the healer.

**Database links:**
https://www.wowhead.com/wotlk/guide/utgarde-pinnacle-overview

**Comment by Jelloprime** [comment]
Just happened to my group also today. Instantly, 1-shot the healer on landing. 6 consecutive attempt. Hand of Salvation didn't help. Hand of Protection didn't help either. One shot.

**Comment by Manpower99** [comment]
Can confirm that the aggro on skadi starts before he falls down.
should only start the moment he goes on the ground without his drake with half a second of the Boss being Idle to ensure peoples delays for taunts building up aggro without healers getting oneshotted, this issue happens consistently in every rdf group.

**Comment by UltraNix** [comment]
Should be fixed.
