### ISSUE TITLE
Higher respawn rates The Plains of Nasam mobs

### ISSUE THREAD

**Issue by arooks1** [gamefreedomgit/Frostmourne#66]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
The Plains of Nasam. The quest works fine, but the mobs need much higher respawn rates.

**How to reproduce:**
Kill the 100 required mobs at the Plains of Nasam

**How it should work:**
Mobs should be respawning much faster. Risk of creating huge bottleneck.

**Database links:**
https://www.wowhead.com/wotlk/quest=11652/the-plains-of-nasam

**Comment by Afgann** [comment]
fixed
