### ISSUE TITLE
Ruby Dragonshire Hyperspawns

### ISSUE THREAD

**Issue by Skrundead** [gamefreedomgit/Frostmourne#661]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
In Ruby Dragonshire the hyperspawns of the mobs outpaces the damage of the NPCs so the mobs end up overlapping about 100 times instantly killing the NPCs that try to attack them, on top of this if you have nameplates on and look at these groupings of mobs your game will immediately freeze and isnt fixable without force quitting and turning off nameplates

**How to reproduce:**
Just be in ruby dragonshire where the ghouls and geists spawn

**How it should work:**

**Database links:**

**Comment by WhitemaneIsa** [comment]
Can you confirm this still happens as of now? We readjusted spawn times a lot since this post was made.

**Comment by WhitemaneIsa** [comment]
As there has been no further info/complaints, this will be closed for now.
