### ISSUE TITLE
Random teleport in Shattrath with Scryers/Aldors

### ISSUE THREAD

**Issue by KajuKureno** [gamefreedomgit/Frostmourne#663]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Flew above Aldor in Shattrath city (I'm Scryers) to go farm at Elemental Plateau. 15-20min later i'm kicked out of the city, teleported out with the usual debuff. I didnt move from the spot. I just happened while farming.

**How to reproduce:**
Fly above Aldor or Scryers while being hated and see if it does that again

**How it should work:**
You should either get caught by the guards on foot and slightly aggroed while flying and immediatly get teleported out of the city.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
