### ISSUE TITLE
Oculus 3 and 4th bosses

### ISSUE THREAD

**Issue by trovi123** [gamefreedomgit/Frostmourne#664]
3d boss pulled insta after last puck was dead. So we could not fly to center. Boss runned to us. Agro had heal, looks like he saving agro when we killed his adds.
![image](https://github.com/gamefreedomgit/Frostmourne/assets/136437891/8b774e75-db9f-4dcf-9fe0-f0635a5ae06b)

last boss dont have 2nd phase with sparks at all

**Comment by UltraNix** [comment]
Fixed.
