### ISSUE TITLE
DrakTharonKeep King Dred

### ISSUE THREAD

**Issue by vkralj1997** [gamefreedomgit/Frostmourne#665]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Everything is working fine only King Dred Fear mechanic when it fears you it basicly no clip you in wall and you are stuck in wall until you tp out tp in

**How to reproduce:**
Remove that spell has ability to make you NOCLIP in it

**How it should work:**
It works well just not to move you in wall :)

**Database links:**
https://www.wowhead.com/wotlk/npc=27483/king-dred
https://www.wowhead.com/wotlk/spell=22686/bellowing-roar

**Comment by Afgann** [comment]
fixed
