### ISSUE TITLE
Halls of stone - Krystallus shatter

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#666]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The spell doesn't work properly, currently seems to instakill one person every shatter regardless of distance between players.

**How to reproduce:**

**How it should work:**
If players are more than ~20 yrds apart should take no damage.

**Database links:**

**Comment by Nihaobeachez** [comment]
Seems to work fine for me, its literally the shatter of Gruul. Im doing HoS everyday since Launch as Melee and nobody has died of this mechanic yet

**Comment by Afgann** [comment]
fixed
