### ISSUE TITLE
A Delicate Touch

### ISSUE THREAD

**Issue by magamis** [gamefreedomgit/Frostmourne#667]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Storm Peaks quest where you kill Garn Invaders with mines.

**How to reproduce:**
Currently the Garn Invaders are flying half way across the map the opposite end where the mobs are suppose to be.

**How it should work:**
Should be within Garn's Bane.

**Database links:**

**Comment by ChronoWM** [comment]
Confirmed issue, mobs spawn but they are either in wrong spots or under the map.

**Comment by UltraNix** [comment]
I belive it's fixed.
