### ISSUE TITLE
[Dungeon] Ahn'kahet kingdom

### ISSUE THREAD

**Issue by Rippinz** [gamefreedomgit/Frostmourne#670]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Taldaram boss is bugged. Flame sphere's are doing WAY more ticks then it should be doing. Basically one shotting the whole group.

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/wotlk/guide/ahnkahet-boss-strategies 
(Taldaram only)

**Comment by bl2x14** [comment]
Can confirm, onehits entire party, no matter the def cooldowns or overhealing.

**Comment by Godmatik** [comment]
@UltraNix this was already fixed

**Comment by UltraNix** [comment]
Fixed.
