### ISSUE TITLE
[Dungeon] The Oculus

### ISSUE THREAD

**Issue by Rippinz** [gamefreedomgit/Frostmourne#671]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Last boss sparks (Phase 2) are moving too fast making it impossible to dodge.

**How to reproduce:**

**How it should work:**
They should be way slower than intended.

**Database links:**

**Comment by Afgann** [comment]
fixed
