### ISSUE TITLE
Blending In - Borean Tundra Quest

### ISSUE THREAD

**Issue by jamesonhp1995** [gamefreedomgit/Frostmourne#672]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Unable to complete Blending in quest.
The Spire of blood isn't registering as scouted when entering the spire.

**How to reproduce:**
Walk into spire and run around entire spire, the quest doesn't update.

**How it should work:**
Walk into the spire and the Spire of Blood should register as scouted.

**Database links:**
https://www.wowhead.com/wotlk/quest=11633/blending-in

**Comment by PanJanuszek** [comment]
![image](https://github.com/user-attachments/assets/cc3ae664-f350-49ed-915a-41b8889c041c)

kill credit is on 1st floor.

Closing as not a issue
