### ISSUE TITLE
Mob facing after update

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#673]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Some mobs do not update their facing even when the tank moves position. They end up cleaving behind tank. They are stuck in this position for a while. Their facing is accurate to the cleave but they are not facing the tank or current highest threat.
 I don't know if its every cleaving mob or just this particular one ( Ghoul Tormentor - Drak'tharon keep)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
@BalanCV Can you record it?

**Comment by Manpower99** [comment]
Happens to moorabi in Gundrak, does not update position until like 10 seconds after a bossfight while he looks at other players despite him targeting the tank.
i cannot determine if dpsers behind him would be considered hitting from front ( visually ) or back cuz possibly hitbox is accurate but model isnt.

**Comment by UltraNix** [comment]
@Manpower99 Any stuns applied on boss during the fight?

**Comment by Manpower99** [comment]
> @Manpower99 Any stuns applied on boss during the fight?

Not that i remember, moorabi and most bosses is/should be immune to CCs and most importantly Stuns also that kinda rules it out

**Comment by UltraNix** [comment]
@Manpower99 As I can't reproduce it - could you record that bug for me?

**Comment by BalanCV** [comment]
@UltraNix https://vimeo.com/954599976?share=copy
choppy vid due to some encoding issues, but you can see the tank is on the right and the mob facing forward until he casts a spell, then he re-adjusts.
Will record drak tharon too when i get it.

**Comment by UltraNix** [comment]
@Manpower99 @BalanCV Can you give me some feedback on this when you have time? Should be fine now.

**Comment by Manpower99** [comment]
> @Manpower99 @BalanCV Can you give me some feedback on this when you have time? Should be fine now.

On moorabi i did not encounter this issue since yesterday, i will comment further after testing on more NPCs

**Comment by UltraNix** [comment]
I assume it's fixed?

**Comment by WhitemaneIsa** [comment]
As there has been no further info/complaints, this will be closed for now.
