### ISSUE TITLE
Drak'tharon keep - Prophet Tharon'ja

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#674]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When the boss stuns party to turn them into skeletons, he will target a random player (or 2nd highest threat after tank?)
He will autoattack this target a milisecond after the stun happens, oneshotting non platers (16k on leather) with no reaction time.
He should either target the tank first during beam or have around 1-3 second pacify after the spell so that people have time to cast shield on themselves.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Manpower99** [comment]
damage is incredibly overtuned though, without shield and through downtime of shield you are essentially one shottable

**Comment by Afgann** [comment]
fixed
