### ISSUE TITLE
[Dungeon] Halls of Stone

### ISSUE THREAD

**Issue by Rippinz** [gamefreedomgit/Frostmourne#675]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Boss Krystallus when he does the shatter mechanic, it is hitting everyone with a pet, including army of the dead.

**How to reproduce:**

**How it should work:**
It should only hit players and ignore pets for the mechanic.

**Database links:**

**Comment by Afgann** [comment]
fixed
