### ISSUE TITLE
LoS/Map calculation issues on slight ledges

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#679]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When there is a small bump/ledge/terrain difference between caster and mob, the spell will cast and mana will be spent but the actual spell will not fire.

**How to reproduce:**
https://vimeo.com/954041144?share=copy
choppy vid quality but can be seen in the first few seconds

**How it should work:**
Small terrain height difference should not be counted towards los calculations. (even though in this case LoS error message doesnt even appear)

**Database links:**

**Comment by Afgann** [comment]
fixed
