### ISSUE TITLE
Quest NPC not spawning when accepting quest in Boean Tundra

### ISSUE THREAD

**Issue by arooks1** [gamefreedomgit/Frostmourne#68]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
When accepting the quest "Coward Delivery...Under 30 Minutes or it's Free", an NPC should spawn that you must escort as part of the quest. This NPC does not spawn, and you cannot complete the quest.

**How to reproduce:**
Accept the quest from the quest giver outside Warsong Hold - part of a longer quest chain.

**How it should work:**
NPC must spawn that you then escort to a specified location, there you use the quest item provided.

**Database links:**
https://www.wowhead.com/wotlk/quest=11711/coward-delivery-under-30-minutes-or-its-free
![WoWScrnShot_020224_152205](https://github.com/gamefreedomgit/Frostmourne/assets/115400565/d11ebe62-cca7-41e2-b1f6-7ca3b8ec4ea7)

**Comment by Inukk** [comment]
I completed this quest, you need to talk to the orc npc and click the dialogue to get the prisoner npc

**Comment by arooks1** [comment]
You are correct, thanks!
