### ISSUE TITLE
Elemental Mastery CD visual BUG

### ISSUE THREAD

**Issue by Meaninglessx** [gamefreedomgit/Frostmourne#680]
(https://www.wowhead.com/wotlk/spell=16166/elemental-mastery)

**Description:** 
The Elemental Mastery spell seems bugged it shows off cd when its clearly on cooldown.

**How to reproduce:** 
after few tests i noticed that this bug occur when u spam the spell too fast the spell triggers but the cooldown animation dosent show .

**How it should work:**
the spell goes on cooldown whenever its used means u use the elemental mastery and press any casted spell to be instant then the cooldown starts counting

**Comment by UltraNix** [comment]
@Meaninglessx You you have any talent that could increase/descresae the cooldown on that spell?

**Comment by Meaninglessx** [comment]
There's no talent that increase or decrease cooldown on Wotlk for Elemental Mastery but i noticed also that this bug occur on Nature's Swiftness aswell so every non gcd spell that causes the next spell to be instant

**Comment by UltraNix** [comment]
@Meaninglessx Let me know if it's fixed or still bugged.

**Comment by Meaninglessx** [comment]
Seems working fine now, good job!
