### ISSUE TITLE
[Enchanting] Items can't be disenchanted

### ISSUE THREAD

**Issue by Ottawia** [gamefreedomgit/Frostmourne#684]
**Description:**
Several items can not be disenchanted:
[Winterfall's Frozen Necklace](https://www.wowhead.com/wotlk/item=37748/winterfalls-frozen-necklace#dropped-by)
[The Dreamer's Shoulderpads](https://www.wowhead.com/tbc/item=31190/the-dreamers-shoulderpads)
[Chestguard of Illumination](https://www.wowhead.com/tbc/item=31152/chestguard-of-illumination)
[Blade Dancer's Wristguards](https://www.wowhead.com/tbc/item=31175/blade-dancers-wristguards)

**How to reproduce:**
Make an enchanter and skill enchanting up to 225/325 skill

**How it should work:**
Items should be disenchantable

**Database links:**

**Comment by erikpowa** [comment]
also #653 , since this one got assign and the other isn't.

**Comment by Afgann** [comment]
fixed
