### ISSUE TITLE
Ironwool mammoth

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#685]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
In the area to the front of K3 there should be couple of Mammoth packs with their groups patrolling. i have waited for over an hour and they are not there/not respawning. Needed for the quest Ample Inspiration

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
#595
