### ISSUE TITLE
Leeway improvements

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#686]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Currently leeway works at around 8 yards for melee white hits which is great.
it does not work for melee yellow abilities however, multiple spells not benefitting still such as Arcane Torrent from Blood elf racial.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Manpower99** [comment]
does not seem to affect pestillence either, moving while jumping and using it would usually increase the aoe radius of spreading diseases by almost 2 yards

**Comment by UltraNix** [comment]
Leeway works for white melee attacks. Just tested with warrior's Bloodthirst. Same for e.g. Heroic Strike.
Also tested with Arcane Torment - looks okay.
Remember - both targets must moving, but not walking.

I see no bug here.
