### ISSUE TITLE
CD reset in dungeons

### ISSUE THREAD

**Issue by roperoperope** [gamefreedomgit/Frostmourne#689]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**CD's did not reset on these bosses in these dungeons.
Utgarde Pinnacle
1st boss
2nd boss
3rd boss
4th boss
----------
Culling
last boss
----------
Utgarde Keep
1st boss
2nd boss
3rd boss
----------
Oculus
2nd boss
3rd boss
----------
Halls of Stone
1st boss
2nd boss
3rd boss
4th boss
----------
Halls of Lightning
1st boss
2nd boss
3rd boss
4th boss

**How to reproduce:** Pop lust n cds, watch them not reset after the fight.

**How it should work:** Since its a Whitemane QoL, it should reset after every boss fight.

**Database links:**

**Comment by UltraNix** [comment]
I think it should only inside raids?

**Comment by Manpower99** [comment]
> I think it should work only in raids?

Yes but if that was the case, it wouldnt reset for the rest of the dungeon bosses?
Either way this is an incredibly amazing quality of life that reduces downtime and would be great if applied to all the dungeon boss encounters.

**Comment by UltraNix** [comment]
What dungeon bosses reset these cooldowns?

**Comment by roperoperope** [comment]
Every other boss not listed here resets. Lemme find u a dungeon list, should help u out.

**Comment by roperoperope** [comment]
Utgarde Keep - Every boss in this dungeon **does not** reset CD's.
Nexus - Every boss in this dungeon _does_ reset CD's.
Ajzol-Nerub - Every boss in this dungeon _does_ reset CD's.
Ahn’kahet: The Old Kingdom - Every boss in this dungeon _does_ reset CD's.
Drak’Tharon Keep - Every boss in this dungeon _does_ reset CD's.
Violet Hold - Every boss in this dungeon _does_ reset CD's.
Gundrak - Every boss in this dungeon _does_ reset CD's.
Halls of Stone - Every boss in this dungeon **does not** reset CD's.
Halls of Lightning - Every boss in this dungeon **does not** reset CD's.
The Culling of Stratholme - **Only last boss** in this dungeon **does not** reset CD's, _the rest do_.
The Oculus - **Only 2nd and 3rd boss **do not**** reset CD's, but first one _does_ reset CD's.
Utgarde Pinnacle - Every boss in this dungeon _does_ reset CD's.
This seems better, lmk if it doesn't make sense.

**Comment by Manpower99** [comment]
@UltraNix this might be related to a hidden thing that makes them appear as bosses and other bosses don't?
for example i have tested army of the dead on some of the dungeon bosses and many of those bosses do not get taunted, almost as if being treated like a raid boss.
Regardless it would be highly appreciated if all of the dungeon bosses give cooldown resets

**Comment by UltraNix** [comment]
Only raid bosses should reset CDs and it's going to be fixed to that state.

**Comment by roperoperope** [comment]
Is this a wotlk only thing or its gonna be applied to cata realms aswell?

**Comment by UltraNix** [comment]
I belie on cata we have the same restrictions.

**Comment by UltraNix** [comment]
Wotlk.

**Comment by UltraNix** [comment]
After thinking it over once again, we're gonna apply this to all wotlk dungeons as well.

**Comment by roperoperope** [comment]
Thank you.

**Comment by BalanCV** [comment]
Yep having cd reset in dungeons actually makes it fun. Considering the QoL inclinement of this server I think this is a good way to go, for the future as well.

**Comment by UltraNix** [comment]
Fixed.
