### ISSUE TITLE
Cant get poisons as a rogue if dispelled

### ISSUE THREAD

**Issue by Jonken90** [gamefreedomgit/Frostmourne#690]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
https://www.wowhead.com/classic/quest=2480/hinotts-assistance#comments

I got dispelled while having the curse, could still finish quest, but as i could not use the reward to dispel myself I never got poisons.

**How to reproduce:**
Get the curse from finishing the prior quest, get dispelled by a druid. Get no progress when handing in the quest in hillsbrad.

**How it should work:**
Rogue should get poisons on completing last quest of the chain

**Database links:**

**Comment by Nihaobeachez** [comment]
Its wotlk brother, just buy them from the vendor

**Comment by UltraNix** [comment]
As above - it's not auto rewarded.
