### ISSUE TITLE
Divine Plea 

### ISSUE THREAD

**Issue by Aeradel** [gamefreedomgit/Frostmourne#691]
Divine plea consistently refreshing itself. It almost seems like player is manually refreshing as I witnessed it later going past 10 seconds and then reapplying. Purely speculative but I believe the player has manual control over how often it is refreshed as this aura is not refreshed when the player has reached a sufficient amount of mana, but is consistently refreshed at any other point - albeit with a slight varying delay (not shown in well shown in the video unfortunately). 

Unsure on replication - don't have a paladin myself nor have I witnessed on another paladin. Could be a unique bug or something happening with multiple players.

Divine plea should only provide the divine plea aura once and then go on cooldown. 

https://www.wowhead.com/wotlk/spell=54428/divine-plea
https://www.youtube.com/watch?v=yqJQiFreMMk

**Comment by BalanCV** [comment]
https://www.wowhead.com/wotlk/spell=53585/guarded-by-the-light
did you take this into consideration?

**Comment by Aeradel** [comment]
> https://www.wowhead.com/wotlk/spell=53585/guarded-by-the-light did you take this into consideration?

i did not. noob mistake. thank you <3
