### ISSUE TITLE
Taunting Player pets

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#692]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Taunts currently do not affect player pets aka enforced attack for the duration of the debuff

**How to reproduce:**

**How it should work:**
It should work against player pets

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
