### ISSUE TITLE
Cluck not rewading with pet chicken

### ISSUE THREAD

**Issue by jerrdale** [gamefreedomgit/Frostmourne#694]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The quest Cluck! in Westfall

**How to reproduce:**
/cluck at a targeted chicken repeatedly until it turns green.
accept the quest.
buy chicken feed from the farmer.
/cheer the chicken and he turns green again.
complete the quest

**How it should work:**
It should reward a pet chicken

**Database links:**
https://www.wowhead.com/quest=3861/cluck

**Comment by WhitemaneIsa** [comment]
Works as intended, turning the quest in at the chicken spawns a chicken egg that needs to be looted for the pet.

![grafik](https://github.com/gamefreedomgit/Frostmourne/assets/164479303/a71c6dcc-c22a-49b6-904b-bfd90d44c260)
