### ISSUE TITLE
Pickpocket loottables

### ISSUE THREAD

**Issue by bandini9** [gamefreedomgit/Frostmourne#695]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Pickpocketting mobs shouldn't drop health pot but you should get health pot from Pickpocketed Reinforced Junkboxes 

**How to reproduce:**
Pickpocket a mob

You see you will get health potion

**How it should work:**

You should get health potion from junkbox

**Database links:**
https://wotlk.evowow.com/?item=43575#contains
https://www.wowhead.com/wotlk/item=43575/reinforced-junkbox

**Comment by radeghostmademedoit** [comment]
they should drop health pots
for example you see it here: https://www.youtube.com/watch?v=ay1_lzZVGYs

**Comment by bandini9** [comment]
> they should drop health pots for example you see it here: https://www.youtube.com/watch?v=ay1_lzZVGYs

Oh well then! Maybe It's a classic thing because OG wotlk didnt have that as far as i remember
