### ISSUE TITLE
Thalassian and Darnassian

### ISSUE THREAD

**Issue by bandini9** [gamefreedomgit/Frostmourne#696]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Belf and Nelf local language Thalassian and Darnassian not working

**How to reproduce:**
Click on a chat bubble on your chat box
Click Language
Click Thalassian as Belf / Click Darnassian as Nelf
Chat
It's still common language visible normally by others

**How it should work:**
You should be able speak Thalassian or Darnassian

**Database links:**

**Comment by UltraNix** [comment]
It's a crossfaction feature - so everybody can understand everybody on all chats.

**Comment by bandini9** [comment]
It's a RP feature that should be in game, even when there's a crossfaction chat or not. What you say doesnt makes sense because It exists even without crossfaction

**Comment by UltraNix** [comment]
Fixed.
