### ISSUE TITLE
Unanimated Mobs

### ISSUE THREAD

**Issue by bandini9** [gamefreedomgit/Frostmourne#697]
![WoWScrnShot_060624_025646](https://github.com/gamefreedomgit/Frostmourne/assets/40371383/1f6dbf96-28d8-4184-99f4-5d79a8ae91e0)
![WoWScrnShot_060624_025646](https://github.com/gamefreedomgit/Frostmourne/assets/40371383/1f6dbf96-28d8-4184-99f4-5d79a8ae91e0)
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
There are stable objects, mobs but not targettable also they dont attack

![WoWScrnShot_060624_025825](https://github.com/gamefreedomgit/Frostmourne/assets/40371383/4254b2aa-12ca-4397-a4e0-424a14d7afd8)
![WoWScrnShot_060624_025825](https://github.com/gamefreedomgit/Frostmourne/assets/40371383/4254b2aa-12ca-4397-a4e0-424a14d7afd8)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
