### ISSUE TITLE
Battle of Valhalas, the return of sigrid  iceborn

### ISSUE THREAD

**Issue by TaintlessElk** [gamefreedomgit/Frostmourne#698]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Ice crown arena boss doesn't engage when spawned, just despawns

**How to reproduce:**
Start quest, she comes out, lands, then disappears

**How it should work:**
She should fight

**Database links:**

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/649
