### ISSUE TITLE
Sap animation and sound happening way late

### ISSUE THREAD

**Issue by bandini9** [gamefreedomgit/Frostmourne#699]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Rogue skill Sap animation and sound working very late

**How to reproduce:**

**How it should work:**

It should be instant animation and sfx

**Database links:**

**Comment by WhitemaneIsa** [comment]
Could you provide a video of this?

**Comment by WhitemaneIsa** [comment]
As there has been no further info/complaints, this will be closed for now.
