### ISSUE TITLE
Killing Machine and Offhand

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#70]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Well known among the DK community somewhat undocumented change in Retail Ulduar 3.1 is Killing Machine no longer proccing on white hits from offhand as a nerf to the original way of playing Dual Wield Unholy (previously called shadowfrost spec).
On Whitemane it currently procs from both MH and OH.

**How to reproduce:**
Talent Killing Machine, equip only offhand and hit dummy.

**How it should work:**
Should be 1 PPM per Talent Point so 5PPM at 5/5 Killing Machine talented and should only proc from Mainhand white Hits and ofcourse as with every PPM it has improvements with haste since it procs from white hits only.
http://web.archive.org/web/20090201103330/http://elitistjerks.com/f72/t41658-dw_unholy_dps_discussion/ is an elitist jerks archive back when Shadowfrost spec was being discussed and it documents a nerf on how killing machine works and to cite it :
 **Killing Machine: This is now a PPM that only triggers on white main hand attacks. The base number is 5 and improves with Haste.**
please note that during cata this change was reverted as only frost dks could dual wield effectively in that patch and the revert was to improve Frost Dks 
https://wowpedia.fandom.com/wiki/Killing_Machine
to cite :  **Patch 4.2.0(2011-06-28): Can now properly be triggered from off-hand attacks as well as main-hand attacks.**
Classic also works exactly as intended with people from Blight Club ( DK class discord ) testing it and confirming it only procs from main hand white hits and im willing to provide screenshots of people's findings if need be.

**Database links:**
https://wotlk-twinhead.twinstar.cz/?spell=51124

**Comment by Afgann** [comment]
fixed
