### ISSUE TITLE
Moonkin Form and Mana from Crits

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#700]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The chance seems to be incredibly low, a druid party member with close to 20k Mana went oom after full rotation while being conservative with mana by not applying dots and still only got 4.5k mana returns.
The chance to get 2% of your total mana has to be increased.

Either there is a hidden icd (but shouldnt) or the chance is abysmally low. Based on logs from classic and bug reports on warmane it is concluded that the Mana return should be close to 100%

i have checked every log from T10 front page US/EU and the proc chance is very high on crits.
Here are Patchwerk logs from t7 since thats closest patch as current content
https://classic.warcraftlogs.com/reports/t418WmQ3qKTjCH9b#type=resources&spell=100&source=57&fight=36
https://classic.warcraftlogs.com/reports/2xvJLnX41bArgzN3#type=resources&spell=100&source=47&fight=2
It is crippling Boomkins completely to have this low mana regen and lowering their value of crit.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Yep - it's a TBC leftover.
```
Patch 3.0.2 (2008-10-14): No longer increases your attack power or causes you to regenerate mana off melee attacks, but now has a chance to cause you to instantly regenerate 2% of your total mana every time you critically hit with a spell.
```
Will be fixed.

**Comment by Manpower99** [comment]
awesome, appreciate it ultranix!

**Comment by UltraNix** [comment]
Fixed.

**Comment by Manpower99** [comment]
> Fixed.

asked two boomkins in guild who claimed they're actually getting less mana than before. if i may ask what is the current chance on each crit to get 2% of total mana back?
