### ISSUE TITLE
Army of the Dead and Taunts

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#701]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Army of the Dead is inconsistent in Dungeons, it can either ignore bosses or Taunt them depending on who it is.
important to fix as they are possibly used in raid and dungeon strategies for various reasons including mass taunting or as a defensive.

**How to reproduce:**
Use it on multiple dungeon bosses and notice the inconsistent behavior.

**How it should work:**
Armies should constantly attempt to taunt regular non skull targets.
Should never taunt Skull Level Bosses(RAID), dungeon bosses are not Skull Level so all of them should be tauntable unless specifically immune to taunts.

some vod from classic
https://www.youtube.com/watch?v=JVPa6zTAwFc

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
