### ISSUE TITLE
Battle for undercity

### ISSUE THREAD

**Issue by icnatsplel** [gamefreedomgit/Frostmourne#702]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**The battle for undercity quest from the alliance side wasn't completable.

**How to reproduce:**Do the whole scenario and at the end the scripting doesn't  work 

**How it should work:**after you kill putrice and you escort Varian to the throne room he  charges thrall and then thrall sylvanas and and the guards just disappear instead of jaina coming and freezing everybody to teleport you out, then varian has only 2 options either tp to start or restart the attack 

**Database links:**

**Comment by emirie1** [comment]
Can confirm that this occurs. Just attempted this quest on June 7th and at the very end, Varian charges Thrall and everyone but Varian disappears. The dialogue with Jaina freezing everyone and teleporting the Alliance out does not work, thus rendering this quest unable to be completed.

**Comment by PanJanuszek** [comment]
i have made some changes last week, if problem ll occur again, please re-open

**Comment by WhitemaneChronus** [comment]
Last part where Varian engages with the orcs is not working.
Varian stands still and the event does not continue.
