### ISSUE TITLE
Cannot prospect titanium ore

### ISSUE THREAD

**Issue by jakemsnyder** [gamefreedomgit/Frostmourne#703]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I am unable to prospect titanium steel. I have 450 jewelcrafting and it says that the ore is prospectable, but when I go to do it, I get an error that says "There are no gems in this".

**How to reproduce:**
Try to prospect titanium ore.

**How it should work:**
Should be prospectable.

**Comment by UltraNix** [comment]
It's a 3.3.2 feature.
```
[Patch 3.2.0]Titanium Ore can be prospected. Prospecting titanium yields 3 Titanium Powder]]
```
