### ISSUE TITLE
(Warrior Deep Wounds) Melee Critical strike chance and Spell Critical strike chance are not normalized like they should be

### ISSUE THREAD

**Issue by mariobrose2** [gamefreedomgit/Frostmourne#704]

**Comment by mariobrose2** [comment]
bump

**Comment by yeagerca** [comment]
bump
I recently retested these and they still use spell crit.
Adding [Fiery Retributer](https://www.wowhead.com/wotlk/item=19968/fiery-retributer) to the list.
