### ISSUE TITLE
Faction change gives incorrect legendary achi pop

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#708]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Unsure if it is related ONLY to the free faction transfer or not, as this bug has happened couple of days ago when it wasnt free.
but it is consistently happening

**How to reproduce:**
faction transfer for free on shop > get sulfuras and sun flute achi pop in system chat

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
