### ISSUE TITLE
Naxx 10 Ascended (loot issues) 

### ISSUE THREAD

**Issue by Khalthous** [gamefreedomgit/Frostmourne#71]
We just cleared Naxx 10 Ascended to try it out, pretty nice long fights mana issues, but overall fun.

So the issues we faced are: 

Construction wing: the slimes going into Patchwerk are fast, but can be slowed, although the slimes at patchwerk if a pet touched them the player dies :D, so that's a bugg.

Loot problems: 
4 horseman - There was no treasure box and the boss only had gold on it - no loot overall.
Loatheb - No loot not even gold.
KT - No loot not even gold.

**Comment by Afgann** [comment]
fixed
