### ISSUE TITLE
Vehicle death UI bug

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#710]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
If the vehicle dies while you are inside it, the UI gets stuck as the vehicle UI but trying to fit your own action bar spells in it. You can still cast but can only see vehicle UI until /reload.

**How to reproduce:**
Have your drake in occulus die, but you are still alive after.

**How it should work:**
Should reset to player UI without needing /reload.

**Database links:**

**Comment by UltraNix** [comment]
@BalanCV Are you able to reproduce it?

**Comment by WhitemaneIsa** [comment]
No further info/complaints, closing.
