### ISSUE TITLE
old hillsbrad foothills cannot be completed - caverns of time are impossible to make

### ISSUE THREAD

**Issue by Serniksernik** [gamefreedomgit/Frostmourne#711]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)
https://www.youtube.com/watch?v=tLBrHZwZBF8
https://www.wowhead.com/tbc/quest=10283/tarethas-diversion

**Description:**
Caverns of time - old hillsbrad foothills
Thrall prison has no interaction doors- thrall stand too far away, making interaction with him impossible.
This cause old stratholme to be not possible to finish.

Why it is important?
Not finishing old hillsbrad foothills will cause Caverns of Time not being able to open other instances, like swamps..
- This will cause many profession masteries to be blocked (I cannot complete Flask Mastery for Alchemy, because I need to finish old hillsbrad foothills to access Swamps in caverns of time to get 10 Essence of Infinity)

**How to reproduce:**
set ablaze 5 houses according to quest Taretha's Diversion
Try talking to Thrall (he stands too far away)

**How it should work:**
You should be able to talk to him - maybe he should be closer to the door, or make door interactable, so after talking with him he can get out of the prison and equip armor (and finish old stratholme

**Database links:**
None
Tested on "MiningTailor" character Death knight draenei 68 lvl with party.

**Comment by PanJanuszek** [comment]
**cannot reproduce he is in range in normal/heroic**
![image](https://github.com/user-attachments/assets/113b4b13-dee3-47b8-9161-eb408b9fb7b8)
