### ISSUE TITLE
Oil of immolation causing permanent pot CD

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#712]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Several bugs with this one that can affect your other consumables when using it in combination.
First of all the buff does not even appear on your buff bar when consumed. It does get applied fine though.

Second, it works like a potion and you can only drink one while in combat, but this should not be the case since it is not a potion and sort of unique consumable(more like classified as an elixir since it shares cooldown with them). It should only have 3 second cooldown before you can use another one, not affected by combat.
https://wowwiki-archive.fandom.com/wiki/Oil_of_Immolation

Third, because of second point it messes up your actual potion during combat if you use it or macro it in a burst macro you will not be able to use your pot.
Sometimes it gets bugged even when combat ends you cannot use your potions anymore.

**How to reproduce:**
use oil of immolation in combat with a dummy then try and use it again, will not work
- Make a macro like this and play around on dummy
/use Potion of Speed
/cast blood fury
/use flame cap
/use Oil of Immolation

At some point you speed pot (and all pots) will bug out so bad that it will say in cooldown even when outside combat ( will stay bugged even on death until relog)

**How it should work:**
Oil of immolation should not have potion combat cd.
Does not share cooldown with other potions and can be chugged in combat as often as every 3 seconds.

Looks like blizzard was tackling similar issue once 
https://us.forums.blizzard.com/en/wow/t/oil-of-immolation-cooldown/375138/6
"The issue is Oil of Immolation triggering an unending CD after using it."

**Database links:**
https://imgur.com/W124vsR
you can see in this photo all my potions being in cooldown even outside combat

**Comment by UltraNix** [comment]
Fixed.
