### ISSUE TITLE
Custom client repair tooltip

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#713]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
While using the custom Client (did not test hd) mousing over repair in a repair vendor does not show the amount of gold required to repair.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/944
