### ISSUE TITLE
[Unholy Gargoyle] Spell seems bugged

### ISSUE THREAD

**Issue by Rippinz** [gamefreedomgit/Frostmourne#714]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The gargoyle summoned by the Unholy Death Knight seems not working correctly. I made a ticket about this so im reporting here.

Firstly, i asked about if there was any haste cap on the gargoyle and it was told that it was working like original classic, so i investigated a bit and it should work like it did on Naxx patch on the true wrath classic 2 years ago. 

I made several tests with the gargoyle to see how many casts it would do according to the current haste i had before summoning it. Having 90% haste with trinket procs, gear, potion of speed and bloodlust it ONLY did 27 casts which is really low.
On classic wrath, with more than 100% haste it was going beyond the GCD having around 0.3 seconds cast, being able to get 70+ casts.

It feels like the gargoyle has some type of GCD while casting. Is it possible to investigate about this?

**How to reproduce:**

**How it should work:**
Should scale with the caster DK's spell haste rating and spell haste buffs (such as Bloodlust) snapshot in the moment of cast.
Example:
Calculation with 6,65% spellhaste (218 rating) on the DK:
2 / 1,0665 = 1,87 sec cast time on Gargoyle Strike.
Calculation with 30% spellhaste (bloodlust) on the DK:
2/1,3 = 1,53sec cast time on Gargoyle Strike.
**Database links:**

**Comment by BalanCV** [comment]
This has been addressed before server release intensively. Gargoyle now is working as OG wrath having a randomized delay between casts not gcd thats why its not machinegunning like classic, because it stops a bit after every cast regardless of speed of cast itself.

The only thing you can change right now would be if the haste scaling is incorrect. If you can find comparison proof that x amount of haste reduces it by more or less on this server.

**Comment by Rippinz** [comment]
From the tests i did, it did add more casts for the duration but i havent found the actual cap where it doesn't add more. Do you want actual proof of it?

**Comment by Manpower99** [comment]
So far seems to work fine, as 3.3.5a standards with actual improvements.
it is affected by delay after each cast which allows it to be more in line with the original way gargoyle worked.
if you are going to refer to how classic worked, t7 gargoyle was extremely op cuz they refused to add delay to it
and t8 onwards had dynamic haste scaling which is not appropriate to 3.3.5a.
if you have proof that there is a cap on how many casts it can do then report it but so far i managed to reach 31 casts in a raid in PTR.

**Comment by WhitemaneIsa** [comment]
As there has been no further info/complaints, this will be closed for now.
