### ISSUE TITLE
Smelt gone

### ISSUE THREAD

**Issue by tomqtx** [gamefreedomgit/Frostmourne#715]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Hi team, using HD WoW Client - the Mining skill Smelt has disappeared, I've now only got the option for Mining under the Professions tab, see screenshot

This issue only started today, Smelt was there before, screenshot here - https://imgur.com/a/9uQHHok

**Comment by tomqtx** [comment]
Still bugged

**Comment by WhitemaneIsa** [comment]
You should still be able to use /use smelting or /cast smelting for the time being, or simply use the non-HD Client
