### ISSUE TITLE
Bring 'Em Back Alive 

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#716]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Quest: https://www.wowhead.com/wotlk/quest=11690/bring-em-back-alive
Unable to do the quest.
Player is supposed to mount infected kodo (https://www.wowhead.com/wotlk/npc=25596/infected-kodo-beast) and deliver them
however they keep falling from the Kodo and it does not proceed.

**How to reproduce:**
Take the quest from NPC https://www.wowhead.com/wotlk/npc=25607/farmer-torp
Use the item (https://www.wowhead.com/wotlk/item=34954/torps-kodo-snaffle) to mount the Kodos. 

**How it should work:**
https://www.youtube.com/watch?v=ksuiVO5Zvz4

**Database links:**

Quest: https://www.wowhead.com/wotlk/quest=11690/bring-em-back-alive
https://www.wowhead.com/wotlk/npc=25607/farmer-torp
https://www.wowhead.com/wotlk/npc=25596/infected-kodo-beast
https://www.wowhead.com/wotlk/item=34954/torps-kodo-snaffle

**Comment by UltraNix** [comment]
@WhitemaneChronus Just tested and see no problems.
Happens in specific spot/area/mob?

**Comment by WhitemaneChronus** [comment]
It used to be the entire area, all the mobs. 
Just tested the quest now and its working properly; we haven't received a report of it recently as well.

**Comment by WhitemaneChronus** [comment]
Sorry we faced this issue again, the quest is working fine on ptr but we have it "again" on live server. i'm attaching a short video.
Respawning kodos didnt help as well. 
when you click the Kodo npc it mounts/demounts afterwards.

I tried with different npcs that could be found in that area, none seem to work and we are receiving reports from players again. 

https://youtu.be/gQNdHPg-TTE

**Comment by PanJanuszek** [comment]
Still reproductable @WhitemaneChronus ???

Which client do you use??
Can you disable gm off and gm visible on ??

**Comment by WhitemaneChronus** [comment]
Eu client
No addons
no aura such as invis
no other quests 
Completed [Damned Filthy Swine](https://www.wowhead.com/wotlk/quest=11688/damned-filthy-swine) as well

I lose control of the NPC as soon as i click the item or right click the Kodo. 
unable to complete.

**Comment by WhitemaneChronus** [comment]
As of now its fixed.
