### ISSUE TITLE
Steamtank Surprise

### ISSUE THREAD

**Issue by Adrenark** [gamefreedomgit/Frostmourne#718]
Steamtank Surprise, quest in Dragonblight next to Wintergrade Keep.

[//]: # [(https://www.wowhead.com/wotlk)](https://www.wowhead.com/wotlk/quest=12326/steamtank-surprise)]

**Description:**
Every time i want to get into siege tank i get kicked out after 0,5 sec. When i manage to get tank near the Plague Wagon to sabotage it, by spaming right click on it and nonstop moving, it doesn't count the progress. On top of that, if 7th Legion marksman aggro on near undead creature, after defeat the whole siege goes back to it's original spot, next to quest giver.

**Comment by ChronoWM** [comment]
Quest https://www.wowhead.com/wotlk/quest=12326/steamtank-surprise
Alliance steam tank: https://www.wowhead.com/wotlk/npc=27587/alliance-steam-tank

Player is unable to ride the vehicle

**Comment by UltraNix** [comment]
Cannot reproduce it.
It happens in specific spot/area?

**Comment by Adrenark** [comment]
It's been long time ago and it's fixed. Few days after report I was able to complete that quest.
