### ISSUE TITLE
Quest: A Dip in the Moonwell

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#719]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Player is supposed to bring back Thalanaar moonwell water using the provided robot. After navigating the robot to the moonwell and casting "gather water" action item should be obtaineded in your inventory, however that's not the case.
Gather water does not provide you with any samples.

**How to reproduce:**
Use the Robotron Control while standing near the Concealed Command Console hidden in a small cluster of bushes on the rim of the needle closest to Thalanaar to take command of a Robotron 3000. Pilot the robot to the western edge of [Thousand Needles](https://www.wowhead.com/wotlk/zone=400/thousand-needles) where the Alliance outpost of Thalanaar is located. Use the robot to collect a sample of the moonwell's water by casting gather water on action bars.

**How it should work:**
https://www.youtube.com/watch?v=ASXehLsmCOE

**Database links:**
Quest: https://www.wowhead.com/wotlk/quest=9433/a-dip-in-the-moonwell
[Robotron Control Unit](https://www.wowhead.com/wotlk/item=23675/robotron-control-unit) (Provided)
[Thalanaar Moonwell Water](https://www.wowhead.com/wotlk/item=23670/thalanaar-moonwell-water)

**Comment by PanJanuszek** [comment]
![image](https://github.com/user-attachments/assets/1c14bba5-0516-443b-b0d5-42ac02a87bfb)
![image](https://github.com/user-attachments/assets/029d2c23-07fe-400b-b796-42ae99f1d18e)

**Comment by WhitemaneChronus** [comment]
Quest is fixed now and is working as intended, thanks.
