### ISSUE TITLE
Oculus Emerald drake healing spell

### ISSUE THREAD

**Issue by wotlkenjoyer** [gamefreedomgit/Frostmourne#72]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
[Dream Funnel](https://www.wowhead.com/wotlk/spell=50344/dream-funnel)

Emerald drake ability does not transfer caster HP to the target, funnel does not appear, only  drake becomes green but nothing else happens, tested in different ways, tried to be super close to the target, etc.

**Comment by Afgann** [comment]
fixed
