### ISSUE TITLE
Culling of Stratholme

### ISSUE THREAD

**Issue by Raulfin** [gamefreedomgit/Frostmourne#720]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
We were just going CoS Hc daily and Meathook didn't spawn on wave 5, it passed to wave 6 after a moment, and then he spwned in the same place with wave 7. Trash spawned normally on waves 6 and 7, so had to fight meathook+ wave 7.

When the timer for Infinite Corruptor ran out he despawned immediatly mid combat.

**How to reproduce:**

**How it should work:**
Meathook shouldn't spawn on a trash wave.
When the timer runs out Infinite Corruptor should turn and run to the captured drake, kill it, and enter a portal and can still be killed during this time.

**Database links:**
https://www.wowhead.com/wotlk/npc=26529/meathook
https://www.wowhead.com/wotlk/npc=32273/infinite-corruptor

**Comment by UltraNix** [comment]
Fixed.
