### ISSUE TITLE
[Dungeon] Azjol-Nerub

### ISSUE THREAD

**Issue by Rippinz** [gamefreedomgit/Frostmourne#721]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Last 2 adds ( Anub'ar Prime Guard) before the last boss are doing insane and fast damage ticks. Spell is named "Mark of Darkness".

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
