### ISSUE TITLE
Mage-Lord Urom - Frostbomb

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#722]
Frostbomb should tick more and more the longer you stay in it in heroic, but currently does not.

![frostbomb](https://github.com/gamefreedomgit/Frostmourne/assets/37913400/d7c3ed75-0566-4092-a056-8984ec534aca)

**Comment by roperoperope** [comment]
this matik guy killing all the fun i heard, watch him find out that grounding totem works on it aswell kek

**Comment by Godmatik** [comment]
> this matik guy killing all the fun i heard, watch him find out that grounding totem works on it aswell kek



> this matik guy killing all the fun i heard, watch him find out that grounding totem works on it aswell kek

Sorry, are you upset that I am reporting bugs in a bugtracker? 

Your comment is entirely pointless

**Comment by roperoperope** [comment]
no no keep it up, its good
no need to be salty

**Comment by UltraNix** [comment]
Fixed.
