### ISSUE TITLE
Ley Guardian Eregos - Time Stop

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#723]
Diminishing returns still not being applied to the stun from Time Stop ability

**Comment by UltraNix** [comment]
Not sure if bosses should be affected by diminishing returns.

**Comment by Godmatik** [comment]
> Not sure if bosses should be affected by diminishing returns.

For this encounter, yes the stun done by Amber Drake should affected by diminishing returns.

Video showing this:
https://www.youtube.com/watch?v=OXMaIW2rFLs

**Comment by UltraNix** [comment]
Fixed.

**Comment by MadeinNoxus** [comment]
It is broken again, when you apply the effect to many times, it just does not work and says he is inmune
