### ISSUE TITLE
CoS H

### ISSUE THREAD

**Issue by Gwynn1** [gamefreedomgit/Frostmourne#725]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**meathook and wave 4 spawn together at the same point. impossible with current gear to heal and tank thru

**How to reproduce:**

**How it should work:**
wave 4 spawns. we kill then meathook spawns as wave 5

**Database links:**

**Comment by Raulfin** [comment]
same as #720

**Comment by UltraNix** [comment]
Fixed.
