### ISSUE TITLE
[QUEST BUG] - [THE PLAINS OF NASAM]

### ISSUE THREAD

**Issue by sicknot1** [gamefreedomgit/Frostmourne#726]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Unable to enter the demos - it says "you are in the wrong zone"

**How to reproduce:**
get the quest and jump into it

**How it should work:**
You should be able to get into them near the quest giver

**Database links:**

![image](https://github.com/gamefreedomgit/Frostmourne/assets/35937937/9e873f78-db6c-4b7c-a696-d32e720091e5)

**Comment by PanJanuszek** [comment]
![image](https://github.com/user-attachments/assets/e9593db6-219a-4ce0-b424-7db397034c02)

What client do you use?? enUS, RU?
Can you provide your exe?

**Comment by WhitemaneChronus** [comment]
It is fixed now and is working properly
