### ISSUE TITLE
steamtank surprise quest bugged 

### ISSUE THREAD

**Issue by doomknights** [gamefreedomgit/Frostmourne#729]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
the quest is currently bugged the moment you try to raid the tank it throws you off and its undoable currently 

**How to reproduce:**

**How it should work:**

you should be able to mount the tank without it auto dismounting you instally
**Database links:**

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/718
