### ISSUE TITLE
Warrior and Stances

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#73]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Classes with stances such as Warrior and DKs should never be without a stance

**How to reproduce:**
make a warrior or get mind controlled

**How it should work:**
when making a new DK or Warrior u should always be in the default stance (1) which is blood presence or battle stance unless you are already in one.
getting pushed into a shapeshift like in theronja last boss of draktheron keep always pushes you out of stances completely also.
how it should work : https://www.youtube.com/watch?v=XVJE9VS5Dt8
Time stamp is after 10:30 where they fight the boss and the warrior tank is still in defensive stance after. On Whitemane it currently pushes you out of warrior stances. and with how each stance has its own seperate ability bars, the stance 0 has completely seperate 

**Database links:**

**Comment by Afgann** [comment]
fixed
