### ISSUE TITLE
[Quest] [Phasing] Destroying the Altars – phased mobs, too fast respawn

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#730]
During quest [Destroying the Altars](https://www.wowhead.com/wotlk/quest=13119/destroying-the-altars), there are two huge issues.
A: Mobs respawn way too fast considering how many is there.
B: There are [Corpulent Horrors](https://www.wowhead.com/wotlk/npc=30696/corpulent-horror#comments) present. They should not be there. They belong in later phase, after player finishes [Killing Two Scourge With One Skeleton](https://www.wowhead.com/wotlk/quest=13144/killing-two-scourge-with-one-skeleton), they are requried for next quest after this, [He's Gone to Pieces](https://www.wowhead.com/wotlk/quest=13212/hes-gone-to-pieces).

https://wowpedia.fandom.com/wiki/Corpulent_Horror?so=search

EDIT: The aboms are wrongly phased in whole of Fleshwerks. Their presence near the altars, together with respawn makes that quest pretty much undoable solo.

**Comment by PanJanuszek** [comment]
fixed with #820
