### ISSUE TITLE
Healing Effects Not Applied on Ramps

### ISSUE THREAD

**Issue by pwrbttm** [gamefreedomgit/Frostmourne#732]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When healing, if you or your target is on a ramp, and you are in line of sight, the healing spell will cast, take your mana, but not apply to your target. It happens with instant cast and casted spells.

**How to reproduce:**
Have the healer stand on a ramp and their target on the platform above while in LoS and cast a heal on the target.

**How it should work:**
Either the heal should apply to your target or you should get an error message that the target is not in line of sight depending on where on the ramp you or your target are.

**Database links:**
Example video of the bug:
https://imgur.com/a/k6Z4x8u

**Comment by Godmatik** [comment]
Confirmed, it's annoying as hell

**Comment by ammenvale** [comment]
+1 can confirm

**Comment by Davud-P** [comment]
+1 confirmed. Also happens with Rogue Sweeping Strikes and I've seen Warrior have their Bladestorm do 0 damage.

**Comment by TheGreatTesla** [comment]
Very confirmed, happens with both aoe dps spells and healing

**Comment by Afgann** [comment]
fixed
