### ISSUE TITLE
Holy Paladin's Divine Favor

### ISSUE THREAD

**Issue by eruiluvatar93** [gamefreedomgit/Frostmourne#733]
**Description:**
Basically the bug goes like this: I will use Divine Favor then I'll cast a spell so Divine Favor goes on 2 minutes cooldown and then when I want to use it again sometimes it works sometimes it doesn't it's random. I haven't seen anyone else reporting this bug here so I don't know if it happens to other Holy Paladins. I thought it was my ElvUI but I checked with other UIs or without and it's still the same. Maybe it has longer cooldown than it shows I don't know.

**Comment by UltraNix** [comment]
@eruiluvatar93 Still happens?

**Comment by WhitemaneIsa** [comment]
No further info/input/report, closing.
