### ISSUE TITLE
Halls of Stone Heroic - Sjonnir the Ironshaper Lightning Shield 

### ISSUE THREAD

**Issue by Nihaobeachez** [gamefreedomgit/Frostmourne#737]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Sjonnir's Lightning Shield has no ICD currently. If you're a fast attacking dualwield class u get multiple Lightning Shield Proccs at once, which basically instakills you

**How to reproduce:** Attack Sjonnir while Lightning Shield Buff is up

**How it should work:** Lightning Shield should have a 50% proccrate with a internal cooldown of 2 seconds between each Stack consumption

**Database links:**
![image](https://github.com/gamefreedomgit/Frostmourne/assets/96308500/9e5d0cf1-139b-4652-af89-a13b099a3bcf)

**Comment by Afgann** [comment]
fixed
