### ISSUE TITLE
Getting Revered/Exalted With Kirin Tor Doesn't Drop Flying Prices

### ISSUE THREAD

**Issue by BorisVolk** [gamefreedomgit/Frostmourne#738]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When we get revered/exalted learning cold weather and artisan stays same pice

**How to reproduce:**
It just happens

**How it should work:**
It should discount the prices according to the rep level with a %

**Database links:**

**Comment by Godmatik** [comment]
Not a bug.

The cold weather flying NPC was not made associated with Kirin Tor until Cataclysm.
