### ISSUE TITLE
GBOS not being learned automatically

### ISSUE THREAD

**Issue by Fibo-droid** [gamefreedomgit/Frostmourne#74]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Greater Blessing of Sanctuary is not being auto-learned, it requires heading to a trainer and manually learn it.

**How to reproduce:**
Create a fresh paladin and level it to level 60+ under Protection spec.
https://imgur.com/a/oCD8oDD

**How it should work:**
Given the spell auto-learn feature, it should be automatically added to the character at level 60.

**Comment by Afgann** [comment]
fixed
