### ISSUE TITLE
The Sum is Greater than the Parts

### ISSUE THREAD

**Issue by Frostlock2** [gamefreedomgit/Frostmourne#740]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
 [The Sum is Greater than the Parts]
this quest Not working properly

**How to reproduce:**
https://www.youtube.com/watch?v=N5IaFforrpg

**How it should work:**
https://www.youtube.com/watch?v=N5IaFforrpg

**Database links:**
https://www.youtube.com/watch?v=N5IaFforrpg

**Comment by GM-Nightmaree** [comment]
kindly edit the title to [Quest 13043] , The quest is working **BUT** the respawn timer is very low

**Comment by Frostlock2** [comment]
i wait more than 20 min and the mobs dont spown.
btw on video no need to wait 10-15 min to complete the quest.

**Comment by slicplaya** [comment]
The adds do not seem to spawn unless I exit the vehicle move halfway into the room and quickly jump back into the vehicle in the corner. I cannot seem to get the next set of adds to spawn. It's definitely not working correctly.

**Comment by Exorcista** [comment]
not working as for today

**Comment by davmag91** [comment]
> The adds do not seem to spawn unless I exit the vehicle move halfway into the room and quickly jump back into the vehicle in the corner. I cannot seem to get the next set of adds to spawn. It's definitely not working correctly.

I was able to complete this in weird way, basically I ran around the room multiple times, untill eventually Dr. Terrible spawned, used nitro boots + demon portal and got inside the vehicle and killed him lulz

**Comment by turbosnek** [comment]
Now I can't mount Nergeld NPC
