### ISSUE TITLE
Improved Blizzard still reported not working

### ISSUE THREAD

**Issue by Aeradel** [gamefreedomgit/Frostmourne#741]
Still having several reports of Improved Blizzard's slowing effect not working as intended.

**Comment by Nihaobeachez** [comment]
Devs wont search for old reports, if something is still broken it doesnt take much to refer to the old report, so they know what they working with. 

https://github.com/gamefreedomgit/Frostmourne/issues/623

**Comment by Afgann** [comment]
fixed
