### ISSUE TITLE
Culling of Stratholme normal - no chest

### ISSUE THREAD

**Issue by wowstunt** [gamefreedomgit/Frostmourne#742]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The chest did not spawn after defeating Mal'Ganis.

**How to reproduce:**
Defeat Mal'Ganis on normal difficulty.

**How it should work:**
Dark Runed Chest should spawn after defeating Mal'Ganis.

**Database links:**
https://www.wowhead.com/wotlk/object=190663/dark-runed-chest
https://imgur.com/a/cvqdzSr

**Comment by UltraNix** [comment]
Fixed.
