### ISSUE TITLE
[Quest] A Rough Ride, not completing

### ISSUE THREAD

**Issue by fjederholdt** [gamefreedomgit/Frostmourne#745]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Not completing A Rough Ride when entering the mistwhisper refuge, even with or without riding the crocodile

**How to reproduce:**
took the quest, flew to mistwhisper refuge, summed zepik the gorloc hunter, 
also tried taking the croc to the refuge with no luck. 

**How it should work:**
Should be completed upon entering the refuge area on the croc

**Database links:**

**Comment by ChronoWM** [comment]
Confirmed the quest does not complete as you reach the destination.

**Comment by UltraNix** [comment]
Fixed.
