### ISSUE TITLE
Multiple TBC Items non disentchantable / no vendor price

### ISSUE THREAD

**Issue by fxn7** [gamefreedomgit/Frostmourne#746]
**Description:**
Many blue/rare items from TBC do not have a Vendor price and therefore cannot be disentchanted, even though they should be sellable and disentchantable. List of Items i found so far:

Cloak of the Inciter (Link 1)
Soul-Wand of the Aldor (Link 2)
Harness of the Deep Currents (Link 3)
Bands of Syth (Link 4)
Shoulderguards of the Bold (Link 5)
The Dreamer's Shoulderpads (Link 6)

**How to reproduce:**
Get the item, try to sell or disentchant

**How it should work:**
should be sellable to vendor and should be disentchantable

**Database links:**
1. https://www.wowhead.com/wotlk/item=27892/cloak-of-the-inciter#disenchanting
2. https://www.wowhead.com/wotlk/item=27885/soul-wand-of-the-aldor#disenchanting
3. https://www.wowhead.com/wotlk/item=27912/harness-of-the-deep-currents#disenchanting
4. https://www.wowhead.com/wotlk/item=27918/bands-of-syth#disenchanting
5. https://www.wowhead.com/wotlk/item=27803/shoulderguards-of-the-bold#disenchanting
6. https://www.wowhead.com/wotlk/item=31190/the-dreamers-shoulderpads#disenchanting

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
