### ISSUE TITLE
Holy Priest Serendipity Talent 

### ISSUE THREAD

**Issue by Matrwa** [gamefreedomgit/Frostmourne#747]
Description: sometimes when you get stacks of serendipity they are not consumed by Greater Heal or Prayer of Healing on the first cast. Most likely i seen it was on Surge of Light procs(almost sure that is when you get proc on casting spell with stacks)

How to reproduce: get serendipity stacks on holy priest with surge of light proc then cast greater heal or prayer of healing
then check if stacks are consumed

How it should work: anytime you cast greater heal or prayer of healing with serendipity stacks should be consumed after 1 cast of those spells

Database links: https://www.wowhead.com/wotlk/spell=63733/serendipity

**Comment by Afgann** [comment]
fixed
