### ISSUE TITLE
[Quest] Triage quest complete but First Aid max level not increased to 300

### ISSUE THREAD

**Issue by sk6868** [gamefreedomgit/Frostmourne#748]
**Description:**
Triage quest was completed yet the FIrst Aid max level has not increased to 300

**How to reproduce:**
reach 225 First Aid, go to Arathi Highlands and do the Triage quest.

**How it should work:**
First Aid max level should increase to 300 after the completion of the Triage quest

**Comment by sk6868** [comment]
Any updates on this?  I put a GM ticket and it referred me here so if you are not gonna fix it in an appropriate time, what's the point of opening a GM ticket.

**Comment by WhitemaneIsa** [comment]
![grafik](https://github.com/gamefreedomgit/Frostmourne/assets/164479303/1f54bfa3-72c2-4dd3-b9a6-88056f81fd44)
![grafik](https://github.com/gamefreedomgit/Frostmourne/assets/164479303/2ab8e341-b0fb-48d4-9b32-f96f3bd00017)
![grafik](https://github.com/gamefreedomgit/Frostmourne/assets/164479303/cc67b0b1-bda0-4742-81cd-4cff683c75fe)
![grafik](https://github.com/gamefreedomgit/Frostmourne/assets/164479303/74fbae24-d969-4a53-aa53-cf9d18d88e4d)

https://www.wowhead.com/wotlk/quest=6624/triage
https://www.wowhead.com/wotlk/quest=6622/triage

----
@sk6868 Open another ticket directed at me (Isa) please, if you still require your skill to be manually set (given that you have completed the quest) and I can fix it for you until the devs get to it.

**Comment by UltraNix** [comment]
On wotlk (3.3.5, not classic) these quests do not give you First Aid at 300 lvl.
https://wowpedia.fandom.com/wiki/Triage
![asd](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/7cf2210e-f712-49a1-a1b0-a20f611a2f17)
