### ISSUE TITLE
Dungeon Deserter applied to you, when you leave dungeon after final boss is cleared and new RDF queue ready check is initiated. 

### ISSUE THREAD

**Issue by HasieEST** [gamefreedomgit/Frostmourne#749]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Dungeon Deserter debuff is applied to your character, after you defeat final boss of the dungeon and leave the group. May possibly be applied due to leaving the group when there is an prompt to queue for new dungeon. Leaving 2 screen shots, one which shows Leather-Braced Chain Leggings from Loken (HoL normal) being distributed to player and 2nd screen shot showing me leave the group right after new rdf queue ready check has been called for.

**How to reproduce:**
- Queue RDF
- Complete Dungeon
- Initiate a new RDF queue prompt for your party (have few ppl accepting that they are ready to queue up)
- Leave midway of the new queue prompt (without accepting or denying the prompt)

**How it should work:**
A player shouldn't be receiving a deserter debuff when leaving the dungeon group after completing it and queue for new RDF queue is initiated. 

**Database links:**

![image](https://github.com/gamefreedomgit/Frostmourne/assets/25981761/265f9733-ab58-486d-bce9-cabf2eb2cf68)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/25981761/1e038846-a57d-423f-9e0b-b8b334b9aa59)

**Comment by UltraNix** [comment]
Fixed.
