### ISSUE TITLE
Mobs aggro range 

### ISSUE THREAD

**Issue by grom98** [gamefreedomgit/Frostmourne#75]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:** I believe all mobs aggro range is incorrectly high. For example gray levels mobs are pulling from range that green level mob should be. And green level mobs seem to have range of yellow level mob. I dont think that it should work that way.

**How to reproduce:**  Go ahead and take a note of which range the mobs of different levels are pulling aggro

**How it should work:** mobs should have less aggro range than right now.

**Database links:**

**Comment by RadeghostWM** [comment]
maybe...?

https://github.com/azerothcore/azerothcore-wotlk/issues/5455
https://github.com/azerothcore/azerothcore-wotlk/pull/6214

@Afgann

**Comment by qqdbpp** [comment]
if you are working on aggro/leash range maybe also look at range mob behavior. currently they will only prefer using ranged attacks and will never melee attack/ always run out of range to use range attacks ( not blizzlike ) on classic they will try to melee you until you are in range distance ( and will even follow you around if you keep them close )

**Comment by danniellos94** [comment]
https://prnt.sc/Dt8rHK6vhUn7
This is screen from wotlk classic shows how close the tank can be near halion (lvl 83 boss) and it doesn't pull him.
