### ISSUE TITLE
AH Cut is too high

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#751]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
this server is using Neutral AH between factions due to Xfaction the Cut they take is 15% instead of the usual 5% from non Neutral AH.

**How to reproduce:**

**How it should work:**
Lower it to 5% this is greatly affecting unsuspecting players at a great cost

**Database links:**

**Comment by Manpower99** [comment]
Still not fixed, people are hoarding items to massive degree in their personal guild banks instead of selling..

**Comment by Manpower99** [comment]
@Afgann

**Comment by Manpower99** [comment]
It also seems that the deposit fee is way too high also.

**Comment by Macilious** [comment]
yes , it's way too much , it's ridiculous , someone get on that asap please , it's really more than 15% to be honest , it's way higher
