### ISSUE TITLE
Prince Taldaram Fire Orbs

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#753]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The way they function currently is undoable unless you go to a corner to LoS 2 orbs and get hit by 1 orb which is still enough damage taken to kill the entire party if not healed through with cooldowns or boss is moved a tiny bit to the front.
this is of course less of an issue by gear but a fresh group with pre dungeon gear is going to suffer trumendously if done in the correct way.

https://www.youtube.com/watch?v=s-E2jkXCrbo
https://www.youtube.com/watch?v=m00J3Dzq0xc
https://www.youtube.com/watch?v=F3xeNj7wlKU
https://youtu.be/vrtkbpSGm0w?si=Q1dM5S3cfR2CkMGZ&t=523
Multiple videos from OG Wotlk and Classic proving the currently way it works is inaccurate

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
