### ISSUE TITLE
Halls of Stone Multiple bugs encountered

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#754]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

**Unralenting Construct** : 
https://www.youtube.com/watch?v=Z6PuIDTktdM
Should at 10% HP start casting https://www.wowhead.com/wotlk/spell=61513/short-circuit a normally uninterruptable cast that kills the mob and does the tooltip damage in average to everyone within 10 yards.
Intended to be Displaced/Stunned or to kill the mob before casting it to prevent the massive amount of damage or if group's damage is insufficient is to focus one at a time. Currently the mob simply does the damage at 10% hp with no cast and does not self destruct.

**Maiden of Grief** :
https://www.youtube.com/watch?v=6992PW7KckM
https://www.youtube.com/watch?v=7TBP_mxofXo

Constantly spams her emotes whenever she's at certain thresholds instead of how it works in the videos.

As observed in the videos by the time she casts her Void Zones the previous one despawns about a second later.
https://www.wowhead.com/wotlk/spell=50752/storm-of-grief the void zones tick every second however on Frostmourne the damage every tick seems way higher than intended
the radius is also bigger than the visual

Something broken in general in this server is all NPCs tendency to break their own CCs, this occurs in other mobs and dungeon bosses which i will report _in full_ another time.

as observed in these videos she will prioritize targets who are not hit by Shock of Sorrow 
Meaning if tank gets hit, after half a second she will put put him as a "Non Threat" but keeps his aggro and prioritize other Threatening targets who are not hit By Shock of Sorrow, this is part of the mechanic where the tank has to pre position himself in the Void zone to break the CC she put on him and no have the other Party members killed.
However if everyone gets hit by Shock of Sorrow and it is not cleared within half a second she will have no choice but to prioritize the normally highest threat target aka the Tank and break her own CC on him by doing so.

These issues are also written in wowpedia https://wowpedia.fandom.com/wiki/Maiden_of_Grief
to cite : **However, if someone clears Shock of Sorrow and the tank doesn't she will attack that person as an NPC's tendancy is to not break CC. If all members are incapacitated she will attack the person with the highest threat.**

**Krystallus** multiple bugs have already been reported so i will refrain from repeating them.

**Sjonnir the Ironshaper**
Lightning Shield icd has already been reported, small issue seems to be related to a different bug report https://github.com/gamefreedomgit/Frostmourne/issues/673 happens to him aswell whenever the fight starts

**Brann Event :** we encountered an issue a couple of days ago when we wiped on the event Brann permanently despawned which didnt allow us to redo it.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
