### ISSUE TITLE
[Quest] "Second Chances" 

### ISSUE THREAD

**Issue by Zeehra** [gamefreedomgit/Frostmourne#755]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
After seeing someone else kill Archbishop Landgren, I used "Arete's Gate" on the corpse, but then realised I needed to kill him too. I got a group and killed him, but after that I wasn't able to use the Gate on the corpse, and was thus not able to complete the quest (even though it said "Return to Lord-Commander Arete at Death's Rise"). Nightmare finished the quest for me, but I was not able to get the follow-up quest either. Went back to Death's Rise, but the version of Lord-Commander Arete there didn't have the follow up either.

**How to reproduce:**
Repeat my stupid steps I guess.

**How it should work:**
Should be able to use the portal thing on the bishop's corpse, as it states.

**Database links:**
https://www.wowhead.com/wotlk/quest=12847/second-chances#comments
https://www.wowhead.com/wotlk/npc=29560/lord-commander-arete
https://www.wowhead.com/wotlk/item=40730/aretes-gate

https://imgur.com/a/0fHDtpV

**Comment by PanJanuszek** [comment]
Ok, so here is the thing:

You bugged yourself :)

What happend:
1. When Bishop dies, he creates 1min time window to use gate. When someone is using gate, (f.e in group), he starts event with corpse
2. When Lord Commander Arete will take soul from bishop, then you are not capable to use item.
3. You have to wait for next respawn.
