### ISSUE TITLE
NPCs and multiple bosses break their own CCs

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#756]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
in all of wow's expansions even vanilla and classic and several other private servers mobs and multiple bosses have a tendency to not break crowd control (CC) effects. This is because NPCs are programmed to follow specific behaviors and rules, which include respecting CC effects applied this affects aggro in multiple ways where if a target is not attackable due to the npc not wanting to break the CC it will instead attack the subsequent highest threat target that wouldnt break cc, however if everyone is cc'd then instead of reseting aggro completely and thus the fight itself it will be forced to attack the highest threat target regardless the players being CC'd or not.

This is also because a CC'd target is considered "Non Threatening" for the duration as they cannot do anything. it does not dump their aggro just puts them in a position where their threat is paused and phased.

Examples :
 **Maiden of Grief** : directly from wowpedia
She also casts Shock of Sorrow, which deals 1750 to 2250 shadow damage, incapacitates all group members for 10 seconds. This ability has a 4 second cast time. If the healer is positioned near a void zone they can jump into it to avoid being incapacitated for the full duration. In the event this happens too quickly, PvP trinkets are able to clear the incapacitate. This is NOT an [aggro](https://wowpedia.fandom.com/wiki/Aggro) dump. **However, if someone clears Shock of Sorrow and the tank doesn't she will attack that person as an NPC's tendancy is to not break CC. If all members are incapacitated she will attack the person with the highest threat.**
https://github.com/gamefreedomgit/Frostmourne/issues/754 i expressed in this bug report the same issue

however this is a universal issue to every npc/boss in the game to breakable CCs that the NPC will prefer not to break or CCs that make you invulnerable for the duration, rendering you a "Non Threatening Target but still on the Threat Table".

this an interaction that functions correctly on warmane and could provide proof from multiple recorded bosses there, i will continue digging for videos that showcase this mechanic from blizzard servers as well.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Just tested with Maiden of Grief's Shock of Sorrow - dps cleared that debuf and the boss switched to that target (tank was still under that effect).
@Manpower99 Provide some screenshots or maybe video of this bug on our server.

**Comment by WhitemaneIsa** [comment]
No further info/complaints, closing.
