### ISSUE TITLE
[Approved Suggestion] 24hr Timer to Poisons, Spell/firestonees, and Shaman Enhancements

### ISSUE THREAD

**Issue by Dova14** [gamefreedomgit/Frostmourne#758]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/93952514/10055013-e869-4224-869a-baa562f4d7be)

**Comment by RadeghostWM** [comment]
Approved! Let's do this :)

**Comment by WhitemaneIsa** [comment]
> Approved! Let's do this :)

How do you plan on handling Heirlooms regarding this as there is no void storage in wotlk?

**Comment by Dova14** [comment]
> > Approved! Let's do this :)
> 
> How do you plan on handling Heirlooms regarding this as there is no void storage in wotlk?

Right click the buff off on your buff bar

**Comment by WhitemaneIsa** [comment]
> > > Approved! Let's do this :)
> > 
> > 
> > How do you plan on handling Heirlooms regarding this as there is no void storage in wotlk?
> 
> Right click the buff off on your buff bar

That does not work if the player forgot to do that and the heirloom got unequippesd due to the max level of them being reahed ans the item being sent to them instead :/

**Comment by RadeghostWM** [comment]
> > > > Approved! Let's do this :)
> > > 
> > > 
> > > How do you plan on handling Heirlooms regarding this as there is no void storage in wotlk?
> > 
> > 
> > Right click the buff off on your buff bar
> 
> That does not work if the player forgot to do that and the heirloom got unequippesd due to the max level of them being reahed ans the item being sent to them instead :/

Death Knight can runforge his heirloom weapon and send it -- enchant is either stripped or just don't work, so that's the same case here.

**Comment by WhitemaneIsa** [comment]
> > > > > Approved! Let's do this :)
> > > > 
> > > > 
> > > > How do you plan on handling Heirlooms regarding this as there is no void storage in wotlk?
> > > 
> > > 
> > > Right click the buff off on your buff bar
> > 
> > 
> > That does not work if the player forgot to do that and the heirloom got unequippesd due to the max level of them being reahed ans the item being sent to them instead :/
> 
> Death Knight can runforge his heirloom weapon and send it -- enchant is either stripped or just don't work, so that's the same case here.

For the DKs the enchant won't work, for all others it simply doesn't send the weapon, at least on Cataclysm. Definitely will have to pay attention to that.

**Comment by Afgann** [comment]
fixed
