### ISSUE TITLE
Macros with modifier not working

### ISSUE THREAD

**Issue by jerrdale** [gamefreedomgit/Frostmourne#759]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Any macro I make with modifier only works on the spell that is unmodified. Mouseover macros work fine.
I have also used paging on action bar and put the other spell into the same button as the primary spell. So if I hold shift, action bar one pages to two and the spell bound to button will not work. I have to click the button on this method or the modified macro method.

**How to reproduce:**
#showtooltip
/stopcasting
/cast [mod:shift] Arcane Explosion; [mod:ctrl] Fire Blast; Cone of Cold

**How it should work:**
If Shift is held and the keybind is pressed, Arcane Explosion should occur. If CTRL is held and keybind is pressed, Fire Blast should happen. With NO modifier, Cone of Cold will happen.

This worked on client 3.3.5a, which is on Warmane's server.

**Database links:**

**Comment by Riztazz** [comment]
Is this original 3.3.5a client or 3.5 client?
It works on my client as expected
