### ISSUE TITLE
Rogue Mutilate

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#76]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Currently on this server, Mutilate has only one chance to proc the poison from main hand. It should have two chances to proc poison from main hand only and one chance from offhand.
This is one of the things that classic has that isn't custom but was part of original wrath.
This was recognized by frostmourne as well and added in season3 making assa rogues part of the meta again.

This is one of those hard to find concrete evidence of but known to exist. We can extrapolate from this patch note:
[Patch 3.0.8](https://wowwiki-archive.fandom.com/wiki/Patch_3.0.8) (2009-01-20): This ability will no longer give poisons on the off-hand weapon two chances to be triggered.

This proves that off-hand used to have 2 chances to trigger as well but removed. Patch notes never mention main hand double chance being removed. Using this logic we can somewhat link to evidence of this mechanic.

**How to reproduce:**
Use mutilate on dummy at max melee range so only mutilate hits and with poison on mh only

**How it should work:**
By simonize:
"There are two main factors that decide how you place those weapons: physical damage and poison damage. Regardless which hand you put which weapon in, Deadly Poison will always go on Webbed Death and Instant Poison will always go on Sinister Revenge. If you used SR in the MH and WD in the OH, you would deal a little more physical damage with each cast of Mutilate and a little more physical damage with auto attacks. Using WD in the mainhand instead results in more poison damage - this is because the chance per hit to trigger Deadly Poison is higher than the chance per hit to trigger Instant Poison. **Your Mutilate ability gives two chances to trigger the MH poison and one chance to trigger the OH poison, and your Envenom gives one chance to trigger your MH poison, zero chances to trigger OH poison per cast.** Putting Webbed Death + Deadly Poison in the mainhand results in more poison triggers from your abilities which is generally more significant than the slightly lower physical damage compared to the SR MH / WD OH setup. That all being said, we're talking about a less than 1% difference in estimated damage output here - its not THAT big of a deal to swap which hand which weapon goes in, but I do think WD MH / SR OH is better.
"

**Database links:**
https://wowwiki-archive.fandom.com/wiki/Mutilate#:~:text=Mutilate%20is%20a%20rogue%20ability,and%20awards%20two%20combo%20points.

https://www.icy-veins.com/forums/topic/68502-assassination-rogue/#:~:text=Your%20Mutilate%20ability%20gives%20two,trigger%20OH%20poison%20per%20cast.

**Comment by Manpower99** [comment]
After multiple hours in target dummy testing I can say that mutilate is indeed not having twice the chance to proc main hands poison. This is a blizzlike thing that remained from tbc and of wrath and existed in tbc classic and wotlk classic also with every rogue in classic knowing of its existence and using it.

**Comment by Afgann** [comment]
fixed
