### ISSUE TITLE
Quest "It rolls downhill" ID: 12673

### ISSUE THREAD

**Issue by Ner0-x** [gamefreedomgit/Frostmourne#760]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The Quest doesnt work. U can use quest item on pet and get control of him, but when u use spell to harvest crystals, the pet just goes to crystal but dont collect it.

**How it should work:**
The pet, after using spell, should go to nearest crystal, harvest it and then goes to platform.

**Database links:**
https://www.wowhead.com/wotlk/quest=12673/it-rolls-downhill

**Comment by Aeradel** [comment]
Confirmed to not be working as intended

**Comment by Exorcista** [comment]
still not working, blocking a key major chain :s

**Comment by UltraNix** [comment]
Fixed.
