### ISSUE TITLE
Whispering blocking GM chat - "You can only whisper...."

### ISSUE THREAD

**Issue by Iramtempus** [gamefreedomgit/Frostmourne#761]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
See screenshot, friend tried contacting GM.
When approached he was unable to reply as he got the blocked messages text in regards to fresh accounts.
This needs to be fixed.
I can add on to this that this message is bugged in multiple ways. Leveling my 2nd 80 I kept getting that same error while being on an account WITH an 80. I think the entire system has a major flaw in it so maybe needs a larger bug fix.

**How to reproduce:**
![image_2024-06-08_002039015](https://github.com/gamefreedomgit/Frostmourne/assets/88618448/0bf9db91-2794-4dd0-bfa0-fc1d15456f4e)

**How it should work:**

**Database links:**

**Comment by Riztazz** [comment]
This should be fixed already
