### ISSUE TITLE
Alliance is unable to purchase gems with heroism

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#762]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Checked both my horde and alliance characters, alliance character is unable to purchase gems in the emblem of heroism vendor

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by HolyRatgamer** [comment]
Very annyoing for alliance yeah. Needs to be fixed ASAP.

**Comment by iskense** [comment]
they are sold at jewelcrafter vendor in dalaran for alliance. but not a heroism vendor.

**Comment by UltraNix** [comment]
Fixed.
