### ISSUE TITLE
[QUEST] Daily HC quest - Proof of Demise: Sjonnir the Ironshaper

### ISSUE THREAD

**Issue by WhitemaneIsa** [gamefreedomgit/Frostmourne#764]
**Description:**
Quest Item The Curse of Flesh Disc doesn't always drop from the boss for players.

**How to reproduce:**
No clue, had it happen to 5 players so far, works fine for myself on every occasion I tested. 
Aeradel said it can happen when there is someone in the group that does not have the quest.

**How it should work:**
Should 100% give anyone on the quest that kills the boss the quest item.

**Database links:**
https://www.wowhead.com/wotlk/item=43699/the-curse-of-flesh-disc
https://www.wowhead.com/wotlk/npc=27978/sjonnir-the-ironshaper
https://www.wowhead.com/wotlk/quest=13252/proof-of-demise-sjonnir-the-ironshaper

**Comment by Aeradel** [comment]
This is not working as intended. Also having issues with the other Proof of Demise quests not dropping the required loot as well.

**Comment by UltraNix** [comment]
Maybe bags were full?

**Comment by Aeradel** [comment]
> Maybe bags were full?

Surprisingly, I haven't had issues with this in a week or so. It was pretty consistent when it was happening and got to the point where even full groups weren't getting the drop, but it's not an issue anymore - at least from what I've noticed.
