### ISSUE TITLE
Innervate generating crazy amounts of threat

### ISSUE THREAD

**Issue by robertonno** [gamefreedomgit/Frostmourne#766]
https://www.wowhead.com/classic/guide/threat-overview-classic-wow
"Mana generates threat at a 1-to-0.5 ratio (100 mana gained = 50 threat generated), Rage generates threat at a 5-to-1 ratio (50 rage = 250 threat), and Energy generates threat at a 5-to-1 ratio as well. The threat generated by these resources is distributed equally to all of the mobs that are actively engaged by the party/raid. In addition, these threat values are static and cannot be altered by threat modifiers (talents, abilities, etc)."
https://wowwiki-archive.fandom.com/wiki/Threat
"Power Gain (Mana) | Base threat is 0.5x Mana gained (only certain effects)"

**Description:**
Currently innervate uses the Power Gain (Rage) threat modifier of 5 points of threat per mana gained.
This is 10 times higher than the intended 0.5 threat for each point of mana that is the normal modifier for all Mana type of power gains.

Couldnt find info on this on wotlk wowhead but its in classic wowhead which should be the same principal of 0.5 threat per mana gain

**How to reproduce:**
Create a druid .char level 80
Burn your mana with healing touch until below 10%.
Engage a mob, cast innervate, watch threat meter > each tick of 800 mana gained generates like 4k threat.

**How it should work:**
Innervate should be generating 0.5 threat per mana gain and not 5

**Database links:**
https://snipboard.io/VivJhN.jpg

Did a test in game, a single innervate generated 27k threat

**Comment by robertonno** [comment]
An extra video from TBC but should be the same principal and confirms the 0.5 threat per point of mana
https://www.youtube.com/watch?v=XOvSIL7y0fI

**Comment by Afgann** [comment]
fixed
