### ISSUE TITLE
Can't learn Arcane concentration Talent as Mage

### ISSUE THREAD

**Issue by Kitsunaka** [gamefreedomgit/Frostmourne#767]
**Description:**
I'm trying to learn  Arcane concentration at level 17 and even with the previous tier be already filled 

**How to reproduce:**
Have a mage at least 15

**How it should work:**
Be able to learn after spending 5 points into the arcane tree

**Database links:**

![image](https://github.com/gamefreedomgit/Frostmourne/assets/171727766/2f0fcf4d-c25d-477d-8a41-a6175bdc1518)

**Comment by Godmatik** [comment]
Disable zygor addon

**Comment by WhitemaneIsa** [comment]
Addon related issue, not a server bug
