### ISSUE TITLE
Hardcore players cannot be removed from friend list.

### ISSUE THREAD

**Issue by Mfy92** [gamefreedomgit/Frostmourne#769]
**Description:**
As the title says, Hardcore players cannot be removed from friend list, only normal ones

**How to reproduce:**
-

**How it should work:**

Should be able to remove them
**Database links:**
![WoWScrnShot_060824_041313](https://github.com/gamefreedomgit/Frostmourne/assets/172094754/7c453176-8659-422f-862a-a79847338264)

**Comment by RadeghostWM** [comment]
That's due to this -HC thing. write /removefriend <name> (without -HC)
