### ISSUE TITLE
Quest Anatoly Will Talk broken

### ISSUE THREAD

**Issue by LezChap** [gamefreedomgit/Frostmourne#770]
**Description:**
Couldn't complete quest.  I find Tatjana on her horse up in the camp.  I hit her with the tranq shot that I'm given for the quest, and her horse turns friendly.  I jump on the horse and it becomes a controllable pet/vehicle.

According to the comments on WoWhead, the horse should run back to Anatoly and Sasha to complete the quest script.  It doesn't.  Running it back manually also doesn't trigger the rest of the quest script and quest complete.

A few other things that I noticed that may be related:  1) When I first arrived at Sasha, there was a friendly horse with Tatjana at the location, left by a previous player who failed to complete the quest because of this bug.  2) There are multiple Tatjana's around the area sleeping on the ground.  This happens if the horse is killed.  They do not appear to ever despawn.  In any case, these extra Tatjanas should probably not exist.  Tatjana and her horse won't respawn until you have an NPC aggro and kill the horse, leaving Tatjana on the ground sleeping.  I'm assuming the never-despawning Tatjanas may be getting the quest stuck, and the quest scripting is not recognizing the newly spawned one?

https://www.wowhead.com/wotlk/quest=12330/anatoly-will-talk
https://www.youtube.com/watch?v=j1BPszXlRBY

**Comment by Aeradel** [comment]
Confirmed to not be working as intended.

**Comment by Wosser** [comment]
Tried to do the quest today and now neither Tatjana nor the horse spawn at all.

**Comment by AgentMalice** [comment]
It is not fixed and still broken in the same way today.

**Comment by PanJanuszek** [comment]
I think there was no update yet.
