### ISSUE TITLE
Feign death bug

### ISSUE THREAD

**Issue by hunturd69** [gamefreedomgit/Frostmourne#771]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**Feign death sometimes not showing cooldown on the spell after using it 

**How to reproduce:**

**How it should work:**Shows cooldown after using it 

**Database links:**

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/984
