### ISSUE TITLE
Quest "It Rolls Downhill"

### ISSUE THREAD

**Issue by Adrenark** [gamefreedomgit/Frostmourne#773]
It Rolls Downhill
https://www.wowhead.com/wotlk/quest=12673/it-rolls-downhill

**Description:**
Geist I control by using "Scepter of Suggestion" doesn't pick up gems, they just stand next to them.

**How it should work:**
Controlled geists should be able to pick up gems and taken to the teleporter in the middle of Voltarus should count the quest progression.

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/760
