### ISSUE TITLE
Quest "A Rough Ride"

### ISSUE THREAD

**Issue by Adrenark** [gamefreedomgit/Frostmourne#774]
A Rough Ride
https://www.wowhead.com/wotlk/quest=12536/a-rough-ride

**Description:**
Crocolisk you get on doesn't take you to Mistwhisper Refuge, you can just ride it like a mount and donesn't make you complete quest when you get to the destination on him like that. 

**How it should work:**
You talk with crocolisk and he should take you on his back to Mistwhisper Refuge, where it completes the quest without being able to control his movement.

**Comment by UltraNix** [comment]
#745
