### ISSUE TITLE
Quest "A Rough Ride" not working

### ISSUE THREAD

**Issue by Mylasea** [gamefreedomgit/Frostmourne#775]
**Description:**
Quest is not working properly: crocolisk does not go to destinated location, summoned mob does not see quest as complited after I fly to proper location by myself.

**How to reproduce:**
Night elf, druid, 80 lvl - I tried all possibilites: with summoned Zepik, without, in elf form, in flight form, even moonkin form, crocolisk does not go by itself. I went to destination by myself to see if I can turn the quest - not working. After retaking the quest (multiple times) it still didn't work.

**How it should work:**
Crocolisk should automatically move towards quest location by itself (when a player mounts it), after a ride, player is supposed to turn the quest at summoned NPC, Zepik

**Database links:**
https://www.wowhead.com/wotlk/quest=12536/a-rough-ride

**Comment by UltraNix** [comment]
#745
