### ISSUE TITLE
Problem with Backstab/ambush (mobs)

### ISSUE THREAD

**Issue by For3v3** [gamefreedomgit/Frostmourne#776]
Description: Cant use backstab or ambush if mob pulled 

How to reproduce: U cant use ambush or backstab if mob pulled. U can use all skills but after using kidney shot or cheap shot (shadow dance) u cant use back or ambush, its looking like mobs rotating with u in stunlock.

**Comment by Manpower99** [comment]
There is an issue with NPCs in general when it comes to how they position themselves after being pulled where they look backwards etc. similarly in PTR we have a feral that couldnt Shred Maexxna unless he was at her frontal cone.

**Comment by Roswald1334** [comment]
Stunning a pulled mob makes the mob do a 180, so that visually it looks like its back is facing you, but when you try to do backstab or ambush it errors saying you need to be behind your target. yes this is very confusing

**Comment by UltraNix** [comment]
@Roswald1334 Can you record that?

**Comment by Roswald1334** [comment]
yeah i can, but are you from the team that is going to look into it, or not? @UltraNix

**Comment by For3v3** [comment]
Uploading output(compress-video-online.com) (2).mp4…

**Comment by UltraNix** [comment]
Yes.

**Comment by For3v3** [comment]
I can sent u in discord

**Comment by For3v3** [comment]
@UltraNix  https://www.youtube.com/watch?v=ddu5RdTNgZo
