### ISSUE TITLE
'Kindness' Shadowmoon Valley TBC quest

### ISSUE THREAD

**Issue by salkion** [gamefreedomgit/Frostmourne#777]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When I place the item for the quest the drakes don't come to get it.

**How to reproduce:**
-

**How it should work:**
When you place the item for the quest they should come get the food and then fly away.

**Database links:**
I don't have any

**Comment by PanJanuszek** [comment]
Cannot reproduce:
![image](https://github.com/user-attachments/assets/a3822926-f679-4ff3-9602-49102cf75e9d)
![image](https://github.com/user-attachments/assets/0a510f27-a105-45ba-96d3-075a82d30ef1)
