### ISSUE TITLE
Chaos Theory Achievement bugged

### ISSUE THREAD

**Issue by magamis** [gamefreedomgit/Frostmourne#778]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Chaos Theory isn't received after not killing a portal.

**How to reproduce:**

**How it should work:**
Achievement received after killing boss without killing a portal.

**Database links:**

**Comment by roperoperope** [comment]
u need to leave every portal alive, evne the ones before boss

**Comment by magamis** [comment]
> u need to leave every portal alive, evne the ones before boss

This is not true. Played in wrath and it should only count the portals the boss summons.

**Comment by roperoperope** [comment]
im saying how it works on here

**Comment by roperoperope** [comment]
cuz i got it already

**Comment by magamis** [comment]
Well it should be fixed. Even if that's how it works on here.

**Comment by Afgann** [comment]
fixed
