### ISSUE TITLE
Sunwell 70 Version

### ISSUE THREAD

**Issue by roperoperope** [gamefreedomgit/Frostmourne#779]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
We are not able to zone in Sunwell 70 version at this moment.

**How to reproduce:** Try to zone in Sunwell.

**How it should work:**
Sunwell 70 version should still be open and up for gear grab even in wotlk version of the game.
I understand its meant for timewalking but there's prebis gear in there for almost every class.

**Database links:**

**Comment by magamis** [comment]
there is no prebis here

**Comment by roperoperope** [comment]
check ur lists again ^^

**Comment by Manpower99** [comment]
> there is no prebis here

Incorrect, but irrelevant nonetheless, Timewalking imo should follow warmane's approach of requiring ur raid to set specific difficulty to enter them on Timewalking version
Example :
Sunwell Plateau if left on 25 man normal would enter the 70 version
if the raid sets 25 man heroic difficulty it would enter 80 version made by whitemane team.

similarly should be the case for every future timewalking as they provide Gear, Achievements,Mounts,Transmog etc.
Sunwell Plateau is specifically important at this point due to the upcoming tier 7 race as it contains Pre raid bis items for multiple classes and especially rogues.

**Comment by Manpower99** [comment]
Seems to be working now!

**Comment by magamis** [comment]
> > there is no prebis here
> 
> Incorrect, but nonetheless Timewalking System in Whitemane imo should follow warmane's approach of requiring ur raid to set specific difficulty to enter them on Timewalking version Example : Sunwell Plateau if left on 25 man normal would enter the 70 version if the raid sets 25 man heroic difficulty it would enter 80 version made by whitemane team.
> 
> similarly should be the case for every future timewalking as they provide Gear, Achievements,Mounts,Transmog etc. Sunwell Plateau is specifically important at this point due to the upcoming tier 7 race as it contains Pre raid bis items for multiple classes and especially rogues.

there is no prebis here. at all

**Comment by Manpower99** [comment]
> > > there is no prebis here
> > 
> > 
> > Incorrect, but nonetheless Timewalking System in Whitemane imo should follow warmane's approach of requiring ur raid to set specific difficulty to enter them on Timewalking version Example : Sunwell Plateau if left on 25 man normal would enter the 70 version if the raid sets 25 man heroic difficulty it would enter 80 version made by whitemane team.
> > similarly should be the case for every future timewalking as they provide Gear, Achievements,Mounts,Transmog etc. Sunwell Plateau is specifically important at this point due to the upcoming tier 7 race as it contains Pre raid bis items for multiple classes and especially rogues.
> 
> there is no prebis here. at all

I wont argue in a github, feel free to believe what you wish despite all of this being irrelevant as sunwell 70 has been cleared yesterday by multiple guilds who are attempting to race for the realm first.

**Comment by RadeghostWM** [comment]
There will be Chromie inside that switches versions. :)

**Comment by Manpower99** [comment]
> There will be Chromie inside that switches versions. :)

Awesome thank you for your work!
