### ISSUE TITLE
Trinket + ENgineering hands enchant

### ISSUE THREAD

**Issue by kevolc** [gamefreedomgit/Frostmourne#782]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)
https://www.wowhead.com/wotlk/item=37723/incisor-fragment
https://www.wowhead.com/wotlk/spell=54758/hyperspeed-acceleration

**Description:**
can't use both at same time 

**How to reproduce:**
try use both at same time

**How it should work:**
you wrote you remove this CD but CD stay 

**Database links:**
https://www.wowhead.com/wotlk/item=37723/incisor-fragment
https://www.wowhead.com/wotlk/spell=54758/hyperspeed-acceleration

**Comment by Dova14** [comment]
This still doesn't work, you are unable to use both engi hands and any on use trinket at the same time. 
As Stated This SHOULD BE WORKING, as it was inplemented back in ptr and only recently broke

Using on use trinket: Puts my gloves on 20 second cd
![image](https://github.com/gamefreedomgit/Frostmourne/assets/93952514/9a7bde1d-3147-4a17-9c27-2c24e62cc7a2)

Using Gloves: puts my trinket on 10 second CD
![image](https://github.com/gamefreedomgit/Frostmourne/assets/93952514/7677bb0e-63a9-4427-8804-d081923525e3)

**Comment by Melh232323** [comment]
The same happens with the pyro rocket gloves and the mark of war prisoner (trinket for vh)
https://www.wowhead.com/wotlk/item=37873/mark-of-the-war-prisoner
https://www.wowhead.com/wotlk/spell=54998/hand-mounted-pyro-rocket

**Comment by slicplaya** [comment]
It's working as intended. The duration of trinkets or gloves is the cd for the other. You cannot use both at the same time. This is why things like darkmoonfaire: Death are epic and powerful, they don't share cd with pyro rocket and can proc at the same time.

**Comment by Dova14** [comment]
> It's working as intended. The duration of trinkets or gloves is the cd for the other. You cannot use both at the same time. This is why things like darkmoonfaire: Death are epic and powerful, they don't share cd with pyro rocket and can proc at the same time.

Refer to the previous bug reports, this was something the devs added back in the ptr and confirmed to work like this.  You can find the changelog and previous bug reports.

**Comment by Melh232323** [comment]
> It's working as intended. The duration of trinkets or gloves is the cd for the other. You cannot use both at the same time. This is why things like darkmoonfaire: Death are epic and powerful, they don't share cd with pyro rocket and can proc at the same time.

Its not working as devs intended, since like Dova said devs state that they both could be used on same time like in classic Rn.

**Comment by Melh232323** [comment]
Fix please

**Comment by MichalPasierb** [comment]
> It's working as intended. The duration of trinkets or gloves is the cd for the other. You cannot use both at the same time. This is why things like darkmoonfaire: Death are epic and powerful, they don't share cd with pyro rocket and can proc at the same time.

That part is actually true, confirmed, on gloves equip, trinkets get 10sec GCD:
https://us.forums.blizzard.com/en/wow/t/hyperspeed-accelerators/1358083/5

**Comment by PanJanuszek** [comment]
> It's working as intended. The duration of trinkets or gloves is the cd for the other. You cannot use both at the same time. This is why things like darkmoonfaire: Death are epic and powerful, they don't share cd with pyro rocket and can proc at the same time.

That part is actually true, confirmed, on gloves equip, trinkets get 10sec GCD:
https://us.forums.blizzard.com/en/wow/t/hyperspeed-accelerators/1358083/5

**Comment by RadeghostWM** [comment]
This will be done when new patch hits.

**Comment by RadeghostWM** [comment]
Fixed.
