### ISSUE TITLE
Teleport: Thunder Bluff

### ISSUE THREAD

**Issue by Vaxsysl** [gamefreedomgit/Frostmourne#783]
**Description:**
Whitemane gives us automatic spell learning. However, not all spells are learned. In Mage's case, for the Horde side, we do not learn "Teleport: Thunder Bluff". And we don't learn "Teleport: Stonard".

**How to reproduce:**
Hit 20 and see that other teleports are learned and that these two are not.

**How it should work:**
...train all teleports for the faction? :)

**Database links:**
https://www.wowhead.com/wotlk/spell=3566/teleport-thunder-bluff
https://www.wowhead.com/wotlk/spell=49358/teleport-stonard

**Comment by UltraNix** [comment]
Teleport Thunder Bluff is learnt at 30 lvl.
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/19f728eb-e102-4830-8fac-3d5eaad36c3f)

Teleport Stonard is learnt at 35 lvl.
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/23fec936-6425-4fc7-b4da-2819e6dcb98e)

**Comment by Vaxsysl** [comment]
You might have set them to be learned at those levels, but I could go to trainers at level 20 to learn teleports. Did someone typo 30 instead of 20?

**Comment by UltraNix** [comment]
No - it should be learnt at 30/35 lvl.
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/d00abb9d-7bed-4101-a3b8-2463d48fff70)
I don;t see these at 20 lvl.

**Comment by Vaxsysl** [comment]
You are in Orgrimmar UltraNix :)
Go to Thunder Bluff and Stonard (tele)portal trainers and you'll see them available. All teleports are learnable at level 20. Portals are generally level 40 for racial capitals.

**Comment by UltraNix** [comment]
Yep - it should be at 30 lvl.
Will be fixed.

**Comment by UltraNix** [comment]
Fixed.
