### ISSUE TITLE
warsong gulch "trees" not tree ing

### ISSUE THREAD

**Issue by Murglr** [gamefreedomgit/Frostmourne#784]
**Description:**
Warsong gulch trees are not working as they should.

![wsg](https://github.com/gamefreedomgit/Frostmourne/assets/95224437/50dbd27c-5017-4794-be80-28ac42b8c342)

They have a physical body but do not disrupt line of sight so it is possible to cast / shoot / heal through them.

**How to reproduce:**
Anyhow, anywhen, anywhere on map

**How it should work:**
The tree trunks should break line of sight.

**Comment by Godmatik** [comment]
Not a bug, this is how it was on classic as well.

**Comment by UltraNix** [comment]
It's not a bug.

**Comment by zebostplay** [comment]
> It's not a bug. These trees should not block LoS.

Not true.

**Comment by zebostplay** [comment]
> Not a bug, this is how it was on classic as well.

Not true.

**Comment by Godmatik** [comment]
Actually true. There are multiple videos of this and you can go on classic today and see the same.

The trees blocking LoS is a warmane bug
