### ISSUE TITLE
Low lvl mobs can still daze you - Wrong daze-immunity scaling

### ISSUE THREAD

**Issue by Massie323** [gamefreedomgit/Frostmourne#785]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Right now, low lvl mobs (tested vs lvl 55 as lvl 80) are able to daze you when they shouldn't be.
The odds of getting dazed are reduced by your Defense Rating, which simply by outleveling a mob, should be enough to completely eliminate the chance of being dazed.

Proof: https://web.archive.org/web/20090826065452/http://forums.worldofwarcraft.com/thread.html?topicId=1602585932
This old blue-post talks about how they thought about **removing** this interaction with Defense rating in patch 2.2 but left it in instead.

https://youtu.be/WDOeqM-wGcI - This video showcases how defense rating was used back in vanilla (classic) to become daze-immune

![image](https://github.com/gamefreedomgit/Frostmourne/assets/57675820/32fb91e9-b1af-473f-a530-7ee4ee0bd090)

A lvl 80 char would be at 400 Defense by default, meaning they would vastly surpass the Daze-immunity threshold of a lvl 55 mob.

**How to reproduce:**
Pull low lvl mobs as lvl 80 (i.e. in Stratholme) and get dazed anyway

**How it should work:**
Scaling that formula would mean:
Daze-immunity @lvl60 = 400 Defense
Daze-immunity @lvl70 = 450 Defense
Daze-immunity @lvl80 = 500 Defense

Keep in mind, that is the point where you are COMPLETELY immune to Daze. Every point of Defense higher than the weapon skill of the enemy mob will decrease the odds of a daze (from a base 20% chance per hit).

**Comment by Manpower99** [comment]
Hopefully gets adressed, this is of major importance for tanks

**Comment by UltraNix** [comment]
Just tested 55 lvl mob against 80 lvl player - the chance is 2.15%.

**Comment by WhitemaneIsa** [comment]
No further info/complaints, closing.
