### ISSUE TITLE
Orc Racial lvl 1 at lvl 80

### ISSUE THREAD

**Issue by Zeckcell** [gamefreedomgit/Frostmourne#789]
![WoWScrnShot_060924_043815](https://github.com/gamefreedomgit/Frostmourne/assets/172161340/ac6daf14-f2f0-4cc9-b870-4197c9e395d8)

**Description:**

Seems like my racial have not changed over the levels, i think its a bug cuz my main race is blood elf and at lvl 1 i switched the racial to the orc one.

**How to reproduce:**

Create a character lvl 1 and switch a racial that can lvl up to increase the ammount of stat given.

**How it should work:**

Im not sure how much spell power i should get from  the orc racial skill: Blood Fury, at lvl 80, but im pretty sure is not 5 spell power.

**Database links:**

https://www.wowhead.com/wotlk/spell=20572/blood-fury

The first english comment on wowhead says that at lvl 70 it should give 282 AP/RAP, so at lvl 80 should be even more. And mine is 5.

I will add here a link to a picture about it. https://imgur.com/uyAwK8D

**Comment by GM-Nightmaree** [comment]
Can confirm it , its not scaling with level 
tested it manually

**Comment by UltraNix** [comment]
It's just a tooltip.
Gives 163 SP at 80 lvl.
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/cde90bd4-6ff8-411d-9fa0-46f306193537)
