### ISSUE TITLE
[Quest] A Hero's Burden

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#79]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Moodle is present at the lich fight during the quest and can't be dismissed if you choose to side with the frenzyheart. Relogging makes him disappear.

**How to reproduce:**
Follow through the questline as intended, side with the frenzyheart during the lich fight.

**How it should work:**
Moodle should be automatically dismissed prior to the lich fight, his quest item should also be removed from your inventory.

"While securing the aid of friends is highly recommended, [Moodle](https://www.wowhead.com/wotlk/npc=28122/moodle) will not be able to accompany you on this task."

**Database links:**
https://www.wowhead.com/wotlk/quest=12581/a-heros-burden

**Comment by UltraNix** [comment]
Fixed.
