### ISSUE TITLE
Riding for Paladins

### ISSUE THREAD

**Issue by eruiluvatar93** [gamefreedomgit/Frostmourne#790]
**Description:**
I got Journeyman riding at lvl 20 for free like everyone then I got Expert riding for free at lvl 40 which is already a bug then in order to get flying at level 60 I would have to pay for Journeyman and Expert riding. That is a bug I only would have to pay for Expert riding and then for flying. Few reports like this have been closed here without resolving.
![Screenshot 2024-06-09 020123](https://github.com/gamefreedomgit/Frostmourne/assets/169212371/65c773c2-00bc-4eb3-9786-a18e812ed9d2)
![Screenshot 2024-06-09 020208](https://github.com/gamefreedomgit/Frostmourne/assets/169212371/5b5830b4-36f1-4f42-9140-ce852f998cb7)

As you can see on the first screenshot I have to learn journeyman riding to get expert and flying on the second screenshot you can see my riding is 100% speed which is expert but in skill tab is still journeyman this is wrong it's a bug please fix that.

**Comment by Manpower99** [comment]
Yeah its been reported multiple times no fix as of yet
