### ISSUE TITLE
Infernal Stones Stack to 20 

### ISSUE THREAD

**Issue by Spacemuffin007** [gamefreedomgit/Frostmourne#791]
**Description:**
Infernal Stones to Stack to 20

**Screenshot of Radeghost's approval**
https://i.imgur.com/CgwIXiM.png

**Link to Discord Suggestion**
https://discord.com/channels/1040715551531618365/1247814957761040384

**Database links:**
https://www.wowhead.com/classic/item=5565/infernal-stone

**Comment by RadeghostWM** [comment]
Approved! Let's do this

**Comment by RadeghostWM** [comment]
also Symbols of Divinity - 20 stack as well.

**Comment by RadeghostWM** [comment]
also Symbol of Kings - 20 stack as well if they dont already

**Comment by Afgann** [comment]
fixed
