### ISSUE TITLE
[Professions] Can't swtich specialization at Narain Soothfancy

### ISSUE THREAD

**Issue by radeghostmademedoit** [gamefreedomgit/Frostmourne#792]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I'm at Narain Soothfancy and want to switch from gnome spec to goblin spec. I should be able to talk to him and then click the book on the table to swtich the spec for 150g. Currently nothing happens if I click the book.

**How to reproduce:**
Get Engi and choose a spec, go to Tanaris and try to change it.

**How it should work:**
You should be able to change the spec

**Database links:**
![image](https://github.com/gamefreedomgit/Frostmourne/assets/171498225/0fad5328-bc2e-4310-9e2f-766d91e4f07e)

![image](https://github.com/gamefreedomgit/Frostmourne/assets/171498225/570ab5fb-49d0-4a3e-b4d7-fa9c1e753edb)

**Comment by UltraNix** [comment]
@radeghostmademedoit You are sure you have one of the specialization?
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/a1c83a07-3d15-496b-a5e2-306af29633d8)
