### ISSUE TITLE
Transmute: King's Amber doesnt work

### ISSUE THREAD

**Issue by Lampasak** [gamefreedomgit/Frostmourne#793]
Cant use Transmute: King's Amber. When i try it tells me "The spell is not available to you"
I already did two transmutes so i dont know why i cant do another,when its not on CD

![image](https://github.com/gamefreedomgit/Frostmourne/assets/97378901/055e4528-1d93-45f9-9c00-30a5bfbf86d5)

**Comment by Manpower99** [comment]
Because Epic Gems arenot available at this patch

**Comment by UltraNix** [comment]
Not this patch.
