### ISSUE TITLE
Flame caps are not farmable correctly

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#794]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Whenever you gather Ragveil, when it should respawn in the same node there should be a good chance it will respawn as a flamecap.
currently this interaction does not work making flame caps incredibly scarce.
https://www.wowhead.com/forums/topic/how-to-farm-flame-caps-113595
https://www.mmo-champion.com/threads/666776-What-is-the-best-way-to-gather-flamecaps

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
#143
