### ISSUE TITLE
Arcane Concentration - Mage Talent

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#795]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
the talent works, its a 2% chance per talent point for a cap of 10% chance to proc clearcasting.
however there is a small quirk that should exist to prevent it from proccing too often

Example : it should only have a slightly reduced chance on each Missile of **Arcane Missiles**
should only have a 10% chance from the cast of **Blizzard** and not each tick
only 10% chance from the cast of **cone of cold** and **arcane explosion** and **flamestrike**.
the casts ofcourse would need to hit.

This is exactly how it worked in OG, and Classic and warmane with multiple bug reports proof. this was intended by Blizzard to prevent mages from having infinite mana on aoe.

Essentially this means that blizzard and their tooltips are as usual _misleading_, what this talent means is **when you cast a spell that causes damage** you have a chance depending on your talent points invested to proc it.
the only change that happened at the end of wotlk was to arcane missiles as a slight boost to arcane mages.

**How to reproduce:**
Cast blizzard on 10+ mobs and notice it proccing in middle of the cast which essentially gives mages infinite mana.

**How it should work:**
Patch 3.3.0 [Arcane Concentration]: The interaction of this talent with [Arcane Missiles] has been restructured. Instead of an Arcane Missiles cast triggering the talent, each missile has an independent (but reduced) chance to trigger this talent. In addition, the talent will no longer sometimes be triggered from misses by Arcane Missiles, [Arcane Blast], and Blizzard.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.

**Comment by Manpower99** [comment]
> Fixed.

Don't think it has, still procs from middle ticks from blizzard. should only be the first hit to have a 10% chance ( and should not amplified by the amount of targets either).
