### ISSUE TITLE
Penance

### ISSUE THREAD

**Issue by Albedopriest** [gamefreedomgit/Frostmourne#796]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Sometimes misses 3rd shot of penance. it depends on hast or talent https://www.wowhead.com/wotlk/ru/spell=59891 when it active there 2 casts 2 bullets instead of 3

**How to reproduce:** use https://www.wowhead.com/wotlk/ru/spell=48066 to activate talent https://www.wowhead.com/wotlk/ru/spell=59891 and then cast https://www.wowhead.com/wotlk/ru/spell=47540

**How it should work:** 3 bullets allways - pew pew and pew ! ^^

**Database links:** https://www.wowhead.com/wotlk/ru/spell=47540

**Comment by Murglr** [comment]
no 3rd tick of penance while power infused :(

**Comment by UltraNix** [comment]
#836
