### ISSUE TITLE
RDF prevents requeueing if you are solo

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#797]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
If everyone leaves in the middle of an RDF instance wether heroic or not it kicks u out of the instanced group and teleports you to graveyard.
should keep your within the instanced ID and RDF Group incase everyone else leaves in the middle of RDF to allow players to finish the ID and not be griefed.

Example : everyone could leave after saving themselves to first boss of a specific dungeon and then leave. if one person stays because he needs to clear the dungeon he can no longer queue to finish the ID instead he will be teleported to graveyard

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Just tested and see no bug here - if you stay inside the dungeon without the group, you can queue the RDF. Also, you have 1 min to join another group before teleporting to graveyard - there is no bug here.

**Comment by Manpower99** [comment]
> Just tested and see no bug here - if you stay inside the dungeon without the group, you can queue the RDF. Also, you have 1 min to join another group before teleporting to graveyard - there is no bug here. You cannot continue dungeon without the group. You may invite some to you party and then queue as a party, but you can no longer continue this ID - RDF dungeons are bound to LFG groups.

Except they shouldn't be, but a seperate bug report has been made to adress this issue in a blizzlike manner which is the that RDF shouldn't respect your lockouts, which technically alleviates this issue even though it did happen to my party after a wipe.
