### ISSUE TITLE
STV contest doesn't spawn School of Tastyfish

### ISSUE THREAD

**Issue by michalpajaczkowski** [gamefreedomgit/Frostmourne#798]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
As in title, no Schools of Tastyfishes

**How to reproduce:**
try to win STV contest

**How it should work:**
Pools should be spawned

**Database links:**
https://www.wowhead.com/wotlk/object=180248/school-of-tastyfish#comments

**Comment by michalpajaczkowski** [comment]
NPC [Riggle Bassbait](https://wowclassicdb.com/wotlk/npc/15077) didn't spawn in BB

**Comment by UltraNix** [comment]
Fixed.
