### ISSUE TITLE
[Logs] Implement logs for PvE Raid Bosses

### ISSUE THREAD

**Issue by RadeghostWM** [gamefreedomgit/Frostmourne#8]
Like Maelstrom has. For now, it should be all Naxxramas bosses, Malygos, Sartharion, and all Sunwell Plateau bosses (timewalking only).

Also that needs info about raid difficulty/setup of course, and in case of Sartharion, an indicator of how many drakes were alive.

**Comment by Afgann** [comment]
fixed
