### ISSUE TITLE
Using Spirit Healer in Wintergrasp as an attacker spawns you inside the fortress

### ISSUE THREAD

**Issue by Askanis** [gamefreedomgit/Frostmourne#803]
As an attacker you can talk to the spirit healer to instantly get ressed inside the fortress. With Whitemane+ there is no penelty since you don't get ress sickness.

**Comment by UltraNix** [comment]
@Askanis Talk to what spirit healer?

**Comment by broizter** [comment]
> @Askanis Talk to what spirit healer?
> 
> ![image](https://private-user-images.githubusercontent.com/80540499/338270360-972022b1-6f0e-47de-a388-853b23d414cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMzg1MzEsIm5iZiI6MTcxODAzODIzMSwicGF0aCI6Ii84MDU0MDQ5OS8zMzgyNzAzNjAtOTcyMDIyYjEtNmYwZS00N2RlLWEzODgtODUzYjIzZDQxNGNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDE2NTAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyYTVjMDgxM2VlMmIwZWRmZjA5ZmNlN2M1ODMzZDNkYzhkNTY4MDFkY2FlYTMzYjYwZDBkZDBjNDBiNmQxZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D9UL_Z7uF4-eHXqWBchSMDThr2jcxMfrXTIt74ttYxk)
> 
> I see no such option.

The spirit healer (angel) behind the NPC you're interacting with in the picture.

**Comment by UltraNix** [comment]
@broizter The angel just ress you in that spot - nothing more.

**Comment by broizter** [comment]
> @broizter The angel just ress you in that spot - nothing more.

I haven't tested it today but yesterday she would send you to the graveyard inside the fortress up on the hill. Where defenders spawn.

**Comment by broizter** [comment]
IIRC it was at the graveyard at Westspark Workshop. The reason I discovered the bug was that I accidentally cancelled the countdown to ress and talked to the spirit healer instead. I got killed quickly obviously since I spawned at the enemies graveyard. I was able to repeat this process about 5 times before I got tired of it.

**Comment by broizter** [comment]
Related bug, you don't have to wait for the ress timer in Wintergrasp if you got Whitemane+ because you can use the spirit healer with no penalty.
