### ISSUE TITLE
Trinket doesnt proc, can u fix it? 

### ISSUE THREAD

**Issue by frostblasts** [gamefreedomgit/Frostmourne#804]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

hello, i bought a trinket with EoH and it doesnt proc like other ones?

Mirror Of Truth

**How it should work:**
it should proc?
**Database links:**
https://imgur.com/a/L3AXXmX

**Comment by nimbl3x** [comment]
The proc is really low.

**Comment by UltraNix** [comment]
It's 10% chance on critical strike (comes from Blizzard files).
45 sec ICD (comes from 3.2 patch notes).
I see no bug here.
