### ISSUE TITLE
Charge of the Dragonflights  Scepter Quest

### ISSUE THREAD

**Issue by eaglebloo** [gamefreedomgit/Frostmourne#805]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Im trying to go for the Dirge's recipe but once you complete the quest 'The Charge of the Dragonflights' Anarchonos doesn't offer the next 3 quests that follow this.

**How to reproduce:**

Complete Charge of the dragonflights
**How it should work:**

Complete the quest and recieve the next 3 quests to starts the color shard quests
**Database links:**

https://www.wowhead.com/classic/quest=8555/the-charge-of-the-dragonflights

**Comment by PanJanuszek** [comment]
![image](https://github.com/user-attachments/assets/43d65fa3-3f40-48db-9b68-f7bf5038e36c)
 please remember to be at least Neutral with Brood of Nozdormu
