### ISSUE TITLE
[NPC] Theridran <Druid Trainer>

### ISSUE THREAD

**Issue by Enteroox** [gamefreedomgit/Frostmourne#806]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The Druid Trainer in Stormwind - [Theridran](https://www.wowhead.com/wotlk/npc=5505/theridran) does not offer options to purchase Dual Talents, nor reset the learned talents.

**How to reproduce:**
Visit the NPC [Theridran](https://www.wowhead.com/wotlk/npc=5505/theridran) and check the provided options - the only one existing is "Please teach me." which offers skills to purchase.

**How it should work:**
There should be two more options available together with the "Please teach me." one.

**Database links:**
[Theridran](https://www.wowhead.com/wotlk/npc=5505/theridran)

**Comment by Enteroox** [comment]
After checking the Darnassus druid trainer, I noticed He offers these options, so the issue is not in my character.

**Comment by UltraNix** [comment]
Fixed.
