### ISSUE TITLE
Malygos Platform and pet pathing

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#807]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Pets are pathing quite awkward in Malygos' platform as tested today on PTR.
noticable as they are not doing anything due to constant falling and attempting to use spells that affect pets such as mendpet/ghoul frenzy/health funnel shows them as grayed out spells due to out of range or line of sight
**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
