### ISSUE TITLE
Patchwerk room mobs + frogger event

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#808]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Similar to many mobs that do CCs, the abominations before Patchwerk in Naxxramas are constantly stunning with 0 DR.

Frogger event ( green slimes after patchwerk ) is also weird on the hitbox and seems to be affecting pets but should not.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
fixed
