### ISSUE TITLE
Felhunter spell lock autocast

### ISSUE THREAD

**Issue by Covidisreal** [gamefreedomgit/Frostmourne#809]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Felhunter (warlock pet) spams spell lock off CD without attempting to actually interrupt any spell

**How to reproduce:**
Attack anything with felhunter while spell lock autocast is enabled

**How it should work:**
Shouldn't cast spell lock unless something in spell range is casting?

**Database links:**

**Comment by WhitemaneIsa** [comment]
As there has been no further info/complaints, this will be closed for now.
