### ISSUE TITLE
Typhoon has no kockback on enemies

### ISSUE THREAD

**Issue by Juhl1994** [gamefreedomgit/Frostmourne#81]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
When balance druid typhoon is used on enemies, there is no knockback

**How to reproduce:**
use typhoon on enemies

**How it should work:**
it should have a knockback effect

**Database links:**

**Comment by RadeghostWM** [comment]
You got https://www.wowhead.com/wotlk/item=44922/glyph-of-typhoon ?
