### ISSUE TITLE
Oculus Last boss vehicles/drakes

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#811]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Randomly during the encounter, the vehicles are moving camera position/field of view. this is a recent issue that happened since yesterday previously never occured.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
@Manpower99 Can you record it to be sure I know what are we talking about here?

**Comment by Manpower99** [comment]
> @Manpower99 Can you record it to be sure I know what are we talking about here? Or explain it somehow else :P

Yeah it is quite hard to explain perhaps lmao it's simply that while i was on amber drake the camera kept getting rotated randomly, will be recorded today.

**Comment by bandini9** [comment]
I can say this happens, It didnt bother me though but yeah, drakes are making a turn like they are distracted with rogue skill when passing through vortexes

**Comment by Manpower99** [comment]
Yeah it still happens, essentially right after using the 4th ability ( the siphon ) of bronze drake, the camera fixation is shifty and rotates which can cause players to rotate into a sphere during his phases and die

**Comment by UltraNix** [comment]
@Manpower99 What about that video?

**Comment by Manpower99** [comment]
> @Manpower99 What about that video?

Sadly i just keep forgetting about it as iam mostly focusing on other things atm like Army/Fire Ele/Infernal scaling which are all very off atm. i apologize for the delay and will try to remember next time im in oculus, but the bug is still happening.

**Comment by UltraNix** [comment]
Okay - no need to know, I think I know what we are talking about.

**Comment by UltraNix** [comment]
Fixed.
