### ISSUE TITLE
Distract, Shadow step, And pets following a stealthed target. Gotta be fixed before Arena season starts

### ISSUE THREAD

**Issue by Roswald1334** [gamefreedomgit/Frostmourne#812]
I have found 3 things that does not work properly, and it need to be adressed before arena season starts because it will definetly be game changeing. 

Shadow step
If you shadowstep someone in water you get teleported to the seabed, but the enemy you shadowstep is at the surface, mighty annoying

Distract
Rogue abillity distract is not working properly. It rarly changes the persons direction if the person is walking. i have countless times tried to distract enemys that are passing bridges and edges, to make them fall over. but they switch direction for 0.1 sec then instantly goes back the way they are already traveling. that is not how its intended to work. 

Dk ghouls (maybe even priest shadowfiend, gargoyle, hunter pet, havent tried yet)
if i have a dk ghoul attacking me and i vanish and run away, they ghoul will chase me down wherever i go and take me out of stealth. this is insanely broken, and makes it impossible to do any kind of play vs a dk in pvp. and needs to be fixed before arena season cuz its game changing

**Comment by UltraNix** [comment]
`
Dk ghouls (maybe even priest shadowfiend, gargoyle, hunter pet, havent tried yet)
if i have a dk ghoul attacking me and i vanish and run away, they ghoul will chase me down wherever i go and take me out of stealth. this is insanely broken, and makes it impossible to do any kind of play vs a dk in pvp. and needs to be fixed before arena season cuz its game changing
`
This one also need some clip.

**Comment by Roswald1334** [comment]
https://github.com/gamefreedomgit/Frostmourne/assets/172214691/642ba80f-2d38-4764-bbd2-d30d90ac0779

shadowstep in water.

**Comment by UltraNix** [comment]
Fixed.
