### ISSUE TITLE
Escape from Silverbrook

### ISSUE THREAD

**Issue by Schanks15** [gamefreedomgit/Frostmourne#813]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)
Hello,

The quest Escape from Silverbrook isn't working properly. The player is supposed to mount the horse and kill the worgens that attack him while the horse rides to Amberpine Lodge. I've been stuck on it for the past hour on my character Srchargesalot. woud appreciate any help
**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/wotlk/quest=12308/escape-from-silverbrook

**Comment by Aeradel** [comment]
verified as not working properly - player has manual control over horse when they should not

**Comment by Torises** [comment]
Due to player control, quest is still bug while you can mount limitless unable to complete it.

**Comment by PanJanuszek** [comment]
Can you record movie? I have tested it today, postec screenshots, and there is no more manual control. Pics from my side

**Comment by PanJanuszek** [comment]
Update is on, should work
