### ISSUE TITLE
Unlimited looting quest object "Attack on Tower" 

### ISSUE THREAD

**Issue by Consealer** [gamefreedomgit/Frostmourne#814]
Quest:
https://www.wowhead.com/wotlk/quest=696/attack-on-the-tower
When I loot chests with quest items, then remove quest items, I can loot the chests again. The spawning mobs dont attack at higher level. The chests contain materials, lockboxes, gear. They respawn immediately.

I think the only thing lootable from the chests should be the quest item.

**Comment by UltraNix** [comment]
Fixed.
