### ISSUE TITLE
[Death Knight] Incorrect Dk's rune grace period

### ISSUE THREAD

**Issue by Apakalipsis1992** [gamefreedomgit/Frostmourne#82]
https://www.youtube.com/watch?v=OT6bgWH-KBk

**Description:** The death knight's grace period does not work correctly. In the video above, you can see that it starts at about 7.8-8 seconds. In fact, the grace period should remain 2.5 seconds. That is, runes in the grace period should have a CD of 7.5 seconds.

**How to reproduce:** Repeat the steps I performed in the video (Spend all runes for the first time. Wait until they all recover and then at least another 2.5 seconds. And start spending it again).

**How it should work:** 7.5 seconds CD instead of 7.8-8 (how does it work now)

**Database links:** https://www.wowhead.com/wotlk/guide/classes/death-knight/frost/dps-overview-pve

https://dropmefiles.com/jWPub

**Comment by Manpower99** [comment]
Very noticable, played for multiple hours yesterday and today on target dummy, rune grace period does not go below 8.
should be 7.5

**Comment by RadeghostWM** [comment]
@Afgann put on prio pls
