### ISSUE TITLE
[Quest] [Minor] The Flesh Giant Champion – Margrave Dhakar no jump, no sword

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#821]
During the quest [The Flesh Giant Champion](https://www.wowhead.com/quest=13235/the-flesh-giant-champion#comments), [Margrave Dhakar](https://www.wowhead.com/npc=31306/margrave-dhakar) should jump on Morbius and attack his head. Currently he does not jump there and he does not use his sword either. He just fistfights the giant which looks hilarious.

https://www.wowhead.com/npc=31306/margrave-dhakar#comments:id=1322945
https://www.youtube.com/watch?v=dXufjnQumj8&ab_channel=etwaa

**Comment by WhitemaneIsa** [comment]
@PanJanuszek not the same issue but the same quest, the guy now won't be able to talk to unless we kill and respawn him. Not sure if it just happens after some time passed or if it's triggered by someone else completing the quest there.

**Comment by PanJanuszek** [comment]
@WhitemaneIsa You mean, [Margrave Dhakar] is not able to talk?

**Comment by PanJanuszek** [comment]
should be ok now
