### ISSUE TITLE
Wintergrasp kicking you out even when you're active.

### ISSUE THREAD

**Issue by streamson1** [gamefreedomgit/Frostmourne#824]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Wintergrasp kicking players out when they're active. Example: I was MID cast on a player and it booted me out. Making me miss out on my honor and my wintergrasp tokens.
**How to reproduce:**

**How it should work:**

Not kicking you out when you're MID fight. ONLY when you're afk.
**Database links:**

**Comment by UltraNix** [comment]
@streamson1 Just to clarify: you've been teleported out the Wintergrasp or kicked out of the server?

**Comment by UltraNix** [comment]
If you stand afk then yes - you will be kicked out.

**Comment by WhitemaneIsa** [comment]
As there has been no further info/complaints, this will be closed for now.
