### ISSUE TITLE
Cursor macros

### ISSUE THREAD

**Issue by brooman04** [gamefreedomgit/Frostmourne#825]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
@cursor macros are not working. trying to setup my saronite bombs macro and it does not cast

**How to reproduce:**

/use [@cursor] Saronite bombs
**How it should work:**

should cast bombs at your cursor
**Database links:**
i know this worked on classic wotlk

**Comment by UltraNix** [comment]
https://wowpedia.fandom.com/wiki/Macro_conditionals
```
[Patch 7.1.0]@cursor added.
```
