### ISSUE TITLE
Molten Core Magmadar Enrage cannot be removed by Tranquilizing Shot

### ISSUE THREAD

**Issue by yeagerca** [gamefreedomgit/Frostmourne#826]
**Description:**
Magmadar's Enrage ability is being applied as a debuff instead of a buff, resulting in Tranquilizing Shot being unable to dispell it.

**How to reproduce:**
Bring a hunter (Tranquilizing Shot) or rogue (Anesthetic Poison) to the Magmadar encounter to try dispelling Enrage.

**How it should work:**
Enrage should be an Enrage-type buff on Magmadar that is dispellable.

**Database links:**
https://www.wowhead.com/wotlk/npc=11982/magmadar
https://www.wowhead.com/wotlk/spell=19451/enrage

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
