### ISSUE TITLE
Molten Core Majordomo encounter does not end part 2

### ISSUE THREAD

**Issue by yeagerca** [gamefreedomgit/Frostmourne#827]
**Description:**
Continuation of report #463
Majordomo can now be defeated and spawns the loot chest, however the "encounter" never ends and Majordomo does not teleport to Ragnaros's room to spawn Ragnaros.
Leaving, regrouping, and attempting to enter the instance results in a "Unable to zone in while an encounter is in progress" error.

**How to reproduce:**
Defeat the Majordomo encounter in Molten Core.

**How it should work:**
When Majordomo's allies are defeated and he spawns the loot chest, the encounter should end, and the friendly version of Majordomo should spawn in Ragnaros's Lair to optionally start the Ragnaros encounter.

**Comment by yeagerca** [comment]
Did it again today, the loot chest didn't spawn this time.

**Comment by Piootrek** [comment]
Pushed possible fix, please let me know if the issue persists.
