### ISSUE TITLE
[Dungeon] CoT Arthas mob ignore

### ISSUE THREAD

**Issue by Covidisreal** [gamefreedomgit/Frostmourne#828]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Arthas is ignoring Tomb Stalkers and runs past them (valley after 3rd boss, before final boss)

**How to reproduce:**
Start the valley clearing event, clear some packs, leave nothing but a tomb stalker - watch him run past it 

**How it should work:**
Should hit them

ty for startholme fix tho, everything else is pretty much working perfect <3

**Database links:**

**Comment by Manpower99** [comment]
Arthas seems to be ignoring mobs often, its ideal he ignores normal mobes aka zombies but elites he should fight as otherwise this could lead to problems withtin the gauntlet before Mal'ganis

**Comment by UltraNix** [comment]
Fixed.
