### ISSUE TITLE
[Dungeon] Azjol-Nerub guardian pathing bug?

### ISSUE THREAD

**Issue by Covidisreal** [gamefreedomgit/Frostmourne#829]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
My fire elemental disappeared on Anub'arak encounter. Totem was these, but elemental itself went to narnia. Fire elemental himself did only 1 hit on boss according to skada. He also didn't come back after first burrow.

**How to reproduce:**
Summon fire elemental on the second half of the arena (the furthest one from the entrance), but close to the boss

**How it should work:**
-

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
