### ISSUE TITLE
[NPC][Spawns] Quest - A Bump in the Road - No Saltstone Basilisks in Crater

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Frostmourne#83]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
No Saltstone Basalisks are in the crater at 78,59

**How to reproduce:**
.questadd 1175
.tele TheShimmeringFlats
Go to 78,59
Note how there are no NPC 4147 in the crater

**How it should work:**
There should be mobs in the crater
https://www.youtube.com/watch?v=ZbIihlilyyU&t=550s

**Database links:**
https://www.wowhead.com/classic/npc=4147/saltstone-basilisk

**Comment by Afgann** [comment]
fixed
