### ISSUE TITLE
Arcane talent doesn't work - Arcane shielding bug*

### ISSUE THREAD

**Issue by Markus909** [gamefreedomgit/Frostmourne#830]
https://www.wowhead.com/wotlk/spell=11252/arcane-shielding#see-also-ability

**Description:** arcane shielding should reduce mana loss per damage you get,and these part work fine*
after that it should give + 50% on Mage armor resistance.
i tryed like four times learning and unlearning that talent but my Mage armor resistance doens't change.

**How to reproduce:** learn the talent and check the resistance. try to learn and reset talent to check if something change.

**How it should work:** it should give more resistance simply by learning that talent.

**Database links:**
https://wotlk.evowow.com/?spell=12605#modifies
https://wotlk.evowow.com/?spell=6117

**Comment by UltraNix** [comment]
Resistance given by Mage Armor without talent.
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/326973de-81d3-4fd3-a9ce-21ecf3e17d43)

Resistance given by Mage Armor with 1/2/ talent:
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/1ecad972-8797-4076-ade3-3b5b42a1bc04)

Resistance given by Mage Armor with 2/2/ talent:
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/3b53094a-b1b5-425b-9dd4-e4265bce7f9b)

All good.
Remember to unapply and apply Mage Armor everytime you change that talent.
