### ISSUE TITLE
Captain Malin's Letter drops for Horde

### ISSUE THREAD

**Issue by LezChap** [gamefreedomgit/Frostmourne#831]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Captin Malin's Letter drops for Horde.  It shouldn't, as it's an alliance-only quest starting item.

(https://www.wowhead.com/wotlk/item=36756/captain-malins-letter#starts)

**Comment by Afgann** [comment]
fixed
