### ISSUE TITLE
the blood hunger

### ISSUE THREAD

**Issue by muerto12** [gamefreedomgit/Frostmourne#832]
**Description:**
The problem comes in my pj which does not increase the 3% more damage that the glyph grants to ### the blood hunger skill that gives 5%, it should give me 8% but we see in the following images that it does not, I already spoke with a gm of the problem and said to come here to fix it

**How to reproduce:**

When cast it should deal 8% more damage. 

**How it should work:**
 the glyph must give that 3% for the blood hunger skill to be 8% in total

**Database links:**

https://www.wowhead.com/wotlk/es/spell=60177/hambre-de-sangre
https://www.wowhead.com/wotlk/es/spell=64284/glifo-de-hambre-de-sangre 

![WoWScrnShot_061024_042246](https://github.com/gamefreedomgit/Frostmourne/assets/165277671/738b8d72-556d-4465-b837-cc9c3713fb11)

![WoWScrnShot_061024_042255](https://github.com/gamefreedomgit/Frostmourne/assets/165277671/93be8e4a-71ac-462b-843c-51f4d4eca835)

![WoWScrnShot_061024_042936](https://github.com/gamefreedomgit/Frostmourne/assets/165277671/3056054f-40b3-4149-95c0-112730b88f9a)

**Comment by Manpower99** [comment]
tested it on ptr, the spell and the glyph work as intended.

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/6ad7ea6a-2afc-4585-9568-39cdc63accb5)
You can clearly see it's 8%.
Tooltip is misleading - blame Blizzard.
