### ISSUE TITLE
A Rough Ride quest bugged

### ISSUE THREAD

**Issue by abderrahmen2001** [gamefreedomgit/Frostmourne#833]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
a quest named "A Rough Ride" is riding a crocodile and he will leads u to a place without moving him but when I ride him I can move, even I go to the place the quest doesn't complete.

**How to reproduce:**

**How it should work:**

when I ride the crocodile he will lead me to a place without moving him and then when he gets there the quest is finished
**Database links:**
this is the link of the quest in "www.wowhead.com" as u said
https://www.wowhead.com/wotlk/quest=12536/a-rough-ride

**Comment by UltraNix** [comment]
745
