### ISSUE TITLE
[Quest] Reconnaissance Flight

### ISSUE THREAD

**Issue by erikpowa** [gamefreedomgit/Frostmourne#834]
Unable to use ability Land Flying Machine at crash site on Vic's Flying Machine

https://www.wowhead.com/wotlk/quest=12671/reconnaissance-flight
https://www.wowhead.com/wotlk/spell=52226/land-flying-machine

**Comment by ChronoWM** [comment]
There are issues with the vehicle however, relog fixes the issue usually.
