### ISSUE TITLE
[Quest] Rifle the Bodies - Cannot loot quest start item

### ISSUE THREAD

**Issue by ProfessorLagg** [gamefreedomgit/Frostmourne#835]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I cannot loot loot `Mage Hunter Personal Effects` from `Dead Mage Hunter` in `Moonrest Gardens` just outside `Star's Rest`

**How to reproduce:**
Go and try to loot a  `Dead Mage Hunter`

**How it should work:**
You right click the `Dead Mage Hunter`, and loot a `Mage Hunter Personal Effects` from it.
This `Mage Hunter Personal Effects` should be able to contain the item `Moonrest Gardens Plans`, which starts the quest `Rifle the Bodies`

**Database links:**
https://www.wowhead.com/wotlk/quest=12000/rifle-the-bodies
https://www.wowhead.com/wotlk/item=35792/mage-hunter-personal-effects
https://www.wowhead.com/wotlk/npc=26477/dead-mage-hunter
https://www.wowhead.com/wotlk/item=35783/moonrest-gardens-plans

**Comment by Godmatik** [comment]
Did it just fine on two different alts, try disable addons?

**Comment by WhitemaneIsa** [comment]
As there has been no further info/complaints, this will be closed for now.
