### ISSUE TITLE
Penance - 2 ticks instead of 3

### ISSUE THREAD

**Issue by DanielSekulaJAVA** [gamefreedomgit/Frostmourne#836]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Discipline priest, Penance. 25% of the time it heals 2 times instead of 3. 

**How to reproduce:**
It happens during dungeon, didn't tested it outside. You need to be discipline priest, with talent Penance

**How it should work:**
It should heal 3 times, when not interrupted or hit.

**Database links:**
https://www.wowhead.com/wotlk/spell=47540/penance

**Comment by UltraNix** [comment]
Fixed.

**Comment by Skrundead** [comment]
Still happening @UltraNix

**Comment by UltraNix** [comment]
@Skrundead Please - record it.

**Comment by Murglr** [comment]
still happening indeed

**Comment by UltraNix** [comment]
@Murglr What talents? What's your haste? Also - need video.

**Comment by Murglr** [comment]
Borrowed time though im pretty sure ive seen 3rd tick not proc even without it, 150 haste and im sorry but i dont have recording softwares

**Comment by Murglr** [comment]
penance on ennemy target, borrowed time on, no power infusion or pushback, only 2 ticks

**Comment by Skrundead** [comment]
https://imgur.com/a/8n7n81H
@UltraNix Hope these clips help out!

**Comment by UltraNix** [comment]
Fixed.

**Comment by DanielSekulaJAVA** [comment]
Penance still ticks 2 times instead of 3. Tested on RHC, SWP and VOA 10

**Comment by buza-me** [comment]
So the same with the Mind Flay. https://www.wowhead.com/wotlk/spell=48156/mind-flay @UltraNix it works fine out of combat but does two ticks instead of 3 in combat.
I can make a separate issue for Mind Flay if you want.

**Comment by UltraNix** [comment]
@DanielSekulaJAVA @buza-me As I can't reproduce it after last restart, please provide combat log (or a video) with timestamps where I can see Penance ticks.

**Comment by buza-me** [comment]
@UltraNix [video](https://www.youtube.com/watch?v=x6H8VAn3FKc) first and last penance casts.

**Comment by buza-me** [comment]
I have now added timestamps to the video, my bad.

**Comment by UltraNix** [comment]
@buza-me Combat log with timestamps would be more helpful.

**Comment by buza-me** [comment]
@UltraNix I cba don't fix it just tell the priests to reroll

**Comment by UltraNix** [comment]
Fixed.
