### ISSUE TITLE
CoS skip arthas roleplay

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#837]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
it was already working before the new addition but now it is different.
would be nice to make it if someone finishes the quest they can teleport after roleplay with jaina/uther
if everyone in party did the quest before then should be able to skip arthas rp with jaina/uther

currently no matter what you have to do the roleplay at the start of every dungeon

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/876e9265-7c83-4e47-9f8a-9f7e43ab7409)

It looks okay to me.
Quest rewarded or completed achievements - these are conditions.
**All players** must met these conditions to skip the event.
