### ISSUE TITLE
Fiery Warhorse flying isn't working

### ISSUE THREAD

**Issue by Hasan-Smajlovic** [gamefreedomgit/Frostmourne#838]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: #(https://wowpedia.fandom.com/wiki/Fiery_Warhorse%27s_Reins)

**Description:*I needed Cold Flying for this mount to be learned and I learned it and it can't fly. My gryphon works fine, but with this mount I cant fly (I needed cold weather flying to learn it): *

**How to reproduce:* *

**How it should work:* I think I should be able to fly with this mount. I think so because it asked me for cold weather flying.*

**Database links:**

**Comment by radeghostmademedoit** [comment]
it's a ground mount https://www.wowhead.com/item=30480/fiery-warhorses-reins#comments

but weird that it asked you for cold flying

**Comment by UltraNix** [comment]
Yes - it;s a ground mount.
I cannot reproduce the bug with Cold Winter Flying. You can use that mount e.g. in Stormwind without that spell.

**Comment by Hasan-Smajlovic** [comment]
Eeeh rip 1k gold but its okay. :D

**Comment by UltraNix** [comment]
@Hasan-Smajlovic Poke me on Discord.
