### ISSUE TITLE
Gundrak - Drakkari Colossus 

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#839]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
His Elemental form while Surging seems to be able go through the serpent boss side of the wall.
seems to be throwing the pools seem to be spawning too frequent and do way more damage than intended

**How to reproduce:**

**How it should work:**
https://www.youtube.com/watch?v=77GupblGvaM
using this as reference

**Database links:**

**Comment by UltraNix** [comment]
I don't understand a word from this report :)
`His Elemental form while Surging seems to be able go through the serpent boss side of the wall.`
What wall?

`do way more damage than intended`
What does too much damage?

**Comment by Manpower99** [comment]
> I don't understand a word from this report :) `His Elemental form while Surging seems to be able go through the serpent boss side of the wall.` What wall?
> 
> `do way more damage than intended` What does too much damage?

Exactly what i said though xd

Pool of mojos are being thrown too frequently and way too much damage.
Whenever the elemental form is surging to the red marked area on this screenshot it is going to the wall and rotating all the way back towards the players

https://imgur.com/zRnBcNV

**Comment by Afgann** [comment]
fixed
