### ISSUE TITLE
DK talent - Butchery

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#840]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Seems to be not scaling with talent points
2 Talent Points invested still generates only 1 runic per 5 seconds.

**How to reproduce:**

**How it should work:**
2/2 should generate 2 runic power per 5 seconds in combat.

**Database links:**

**Comment by UltraNix** [comment]
With 1/2, youe have 1,2 Runic Power every 6 seconds (so it's 1 per 5 seconds).
With 2/2 you have 1,6 Runic Power every 2 seconds (so it's 2 per 5 seconds).
Since runic pwoers updates every 2 seconds, thus we have no bug here.
