### ISSUE TITLE
Skadi the Ruthless issues

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#842]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
skadi's waves seem to be incorrect in numbers as observed in this [video ](https://www.youtube.com/watch?v=4i55CARvzAM)

Threat to skadi seems to count from the Gauntlet phase, this is leading to premature healer deaths.
Skadi's threat should only start from the second of landing on the ground, with him prioritizing the closest target unleass taunted or damaged.
this is causing pre mature healing deaths due to how healers generate aggro while he's flying.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
