### ISSUE TITLE
Spikeked titan steel helm craft made boots

### ISSUE THREAD

**Issue by Tombstoned-pissed** [gamefreedomgit/Frostmourne#843]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
when i crafted spike titan steel helm it made the spiked titan steel boots.
craft bar read "spiked titansteel helmet" 
Blacksmithing showed the helm as selected aswell
i belive its a graphic issue

**How to reproduce:**
hearth to dal and try to craft it

**How it should work:**
it should craft the correct item, or at least show you you are crafting somthing else 

**Database links:**

**Comment by Godmatik** [comment]
Sounds like you goofed, never once had this happen to me. Try deleting cache folder

**Comment by Manpower99** [comment]
Cache folder doesnt exist under this current whitemane client, so if he's using it then its either a goof or an actual bug.

**Comment by RadeghostWM** [comment]
It's not a bug, rather user error.
