### ISSUE TITLE
Culling of Statholme (COS), only first player talking to chromie can teleport

### ISSUE THREAD

**Issue by gforghieri** [gamefreedomgit/Frostmourne#844]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

Issue:

Culling of Statholme (COS), only first player talking to chromie can teleport, everyone in the group should be able to, as long as they completed the prequest.

**Comment by UltraNix** [comment]
Fixed.
