### ISSUE TITLE
Random Heroic Dungeon Finder gives ID lockout but it should not

### ISSUE THREAD

**Issue by bgb** [gamefreedomgit/Frostmourne#845]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** When you queue through random heroic dungeon finder and run assigned dungeon, it saves you like it normally would do when joining specific dungeon choosed by yourself.

**How to reproduce:** Queue Heroic rdf, join and run it, get saved. If you keep repeating it, you will eventually run out of dungeons and will not be able to que RHDF at all untill next day (happened to me).

**How it should work:** Two possibilies: 
1) Random Heroic shouldnt be giving ID lockout at all. It worked like this on Wotlk Classic. 
2) But I also checked if it was like this back in original Wrath and i found this old topic from 2010 which says that random heroic finder was giving ID so you couldnt run same dungeon manually after you completed it with HRDF but you still could get it randomly: https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/52885729

Either way it should let you que randomly without limitation, you shouldnt run out of heroic dungeons.

**Database links:**

**Comment by Godmatik** [comment]
Dunno about classic, but literally every server I have been a part of that has dungeon findser has you locked to a dungeon when you complete it. 

Doesn't matter if it's specific queue or random. Otherwise you could run that dungeon multiple times in one day when it's intended to be only once per 24h

**Comment by bgb** [comment]
> Dunno about classic, but literally every server I have been a part of that has dungeon findser has you locked to a dungeon when you complete it.

By every server you mean every private server? Well, I dont know about it since I didnt play privs since couple years but I think it doesnt mean they got it correctly, we should be rather looking at blizzard here right?


> Doesn't matter if it's specific queue or random. 

Why you say it doesnt matter if its specific or random when I gave you proof how it worked on original Wotlk and also on Classic: https://www.reddit.com/r/wotlk/comments/16upmu8/rdf_and_dungeon_lockouts/

> Otherwise you could run that dungeon multiple times in one day when it's intended to be only once per 24h

But you could and should be able to do that! I had many times done multiple times a day Forge of Souls on Wotlk Classic through Random Heroic. This is intended, not running out of dungeons and not be able to que.

**Comment by Manpower99** [comment]
Makes sense since random queue was to allow crossrealm dungeons as a feature to assist low population ones,
by these findings, rdf heroic does get you saved to instances, but the random queue ignores it and still allows you to queue into it
specific queue and manually entering does not.

**Comment by NNassib336** [comment]
This is stupid. You should only be able to run each heroic dungeon once.

**Comment by Godmatik** [comment]
Yeah honestly this sounds like some sort of classic bug. Why would it make sense for you to run a heroic dungeon that has a 24 hour lockout and not get locked to it? Very odd...

**Comment by Manpower99** [comment]
> Yeah honestly this sounds like some sort of classic bug. Why would it make sense for you to run a heroic dungeon that has a 24 hour lockout and not get locked to it? Very odd...

https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/52885729
this is a post from 14 years ago, it is not wotlk classic.

**Comment by Nihaobeachez** [comment]
@UltraNix @bgb RDF was added with ICC, both in original wrath and wotlk classic. Thats why there were no lockouts for heroics if you queue randomly, which made sense since its the end of the expansion.

having rdf activated on launch is a custom feature (which is needed and desired ofc), but adding no lockouts now is a really bad idea

**Comment by bgb** [comment]
> @UltraNix @bgb RDF was added with ICC, both in original wrath and wotlk classic. Thats why there were no lockouts for heroics if you queue randomly, which made sense since its the end of the expansion.

Do you have any source for this or it is just your opinion? Because going by this logic blizzard should change how RDF worked with the begining of the next expansion (Cata). Did that happen?

> having rdf activated on launch is a custom feature (which is needed and desired ofc), but adding no lockouts now is a really bad idea. 
 Why exactly is it bad idea? Arent we on a server with progress speeded up anyway? Why you think limiting people who want to run dungeons all the day if they want is bad?

> if you want to have it blizzlike, remove RDF till ICC. the guy who opened this "bug" did no research at all, neither did the dev and just blindly trusted the information and changing it. (i still admire ur hard work UltraNix, just a big L this time)
Facts are: rdf didnt work like on blizzard so when I spotted a bug and reported it, but I guess some ppl consider bugs as a feature...

**Comment by UltraNix** [comment]
Just to clarify this:
random heroic dungeon **still does lock you out** this dungeon, so you cannot enter the same heroic dungeon e.g. entering the portal.
But RDF ignores this lockout so you can do the same heroic dungeon infinite times. But that works only via RDF.

RDF was added on ICC patch, but we have it since the very start - so this change will be apply as well.

**Comment by Manpower99** [comment]
> Just to clarify this: random heroic dungeon **still does lock you out** this dungeon, so you cannot enter the same heroic dungeon e.g. entering the portal. But RDF ignores this lockout so you can do the same heroic dungeon infinite times. But that works only via RDF.
> 
> RDF was added on ICC patch, but we have it since the very start - so this change will be apply as well.

Beautiful, thanks for the clarification!
