### ISSUE TITLE
[NPC][Spawns] Quest - Load Lightening - Not enough Salt Flats Scavanger

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Frostmourne#85]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Missing Spawns of Salt Flats Scavangers (https://www.wowhead.com/classic/npc=4154/salt-flats-scavenger)

**How to reproduce:**
.questadd 4154
.tele TheShimmeringFlats
Go to 86,65
Note the vultures do not surround the bones as intended. Spawns seem to be missing.

**How it should work:**
https://www.youtube.com/watch?v=eoIr9imzZEs&t=35s

Notice how in the video the vultures surround the bones. On Frostmourne only half of them are spawned.

**Database links:**
https://www.wowhead.com/classic/quest=1176/load-lightening
https://www.wowhead.com/classic/npc=4154/salt-flats-scavenger

**Comment by Godmatik** [comment]
Confirmed, its a problem on all stock servers where that spot only has ~3 spawns

**Comment by Afgann** [comment]
fixed
