### ISSUE TITLE
Dispersion bag

### ISSUE THREAD

**Issue by irinasvarichevskaya** [gamefreedomgit/Frostmourne#850]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When I fall from a great height in dispersion, I die. But it shouldn't.

**How to reproduce:**
Fly higher, use Dispersion 

**How it should work:**
I have to survive. 90% of damage should be absorbed

**Database links:**
https://www.wowhead.com/spell=79811/dispersion

**Comment by UltraNix** [comment]
https://wowpedia.fandom.com/wiki/Dispersion
`Dispersion does not reduce fall damage`
