### ISSUE TITLE
[DEATH KNIGHT] Raise Dead doesn't summon the pet

### ISSUE THREAD

**Issue by dopalone** [gamefreedomgit/Frostmourne#851]
**Description:**
Raise Dead sometimes goes unusable after trying to summon a pet which doesn't summon anything rendering it unable to try to resummon again until relog.

**How to reproduce:**
Happens randomly after pet/player dies and the ghoul has to be resummoned.

**How it should work:**
It should just summon it.

**Database links:**
https://www.wowhead.com/wotlk/spell=46584/raise-dead

**Comment by dopalone** [comment]
https://streamable.com/eanl08

**Comment by Manpower99** [comment]
Can confirm it, happens randomly with no figured cause.
only fix to it is a relog.

**Comment by UltraNix** [comment]
@dopalone Video unavailable.

**Comment by WhitemaneIsa** [comment]
No further info/complaints, closing.
