### ISSUE TITLE
[Icecrown] Webbed Crusader

### ISSUE THREAD

**Issue by davmag91** [gamefreedomgit/Frostmourne#853]
The "Webbed Crusader" npc should stand still and not attack.

What happens?

It moves and attacks. :)

**Comment by WhitemaneIsa** [comment]
I checked every single spawn location and cannot confirm this - can you provide a video or be more specific about the location?

**Comment by WhitemaneIsa** [comment]
As there has been no further info/complaints, this will be closed for now.
