### ISSUE TITLE
Chilled Meat and Shoveltusk Flank drop rates too low

### ISSUE THREAD

**Issue by KeNoMeDeja** [gamefreedomgit/Frostmourne#854]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Chilled Meat drop rates from northrend beasts are extremly low, also Shoveltusk Flank from Howling Fjord Shoveltusk beast have an extremly low drop rate.

**How to reproduce:**

Killing beasts

**How it should work:**

They should drop at rate between 30 and 60% as for Chilled Meat on some beasts, Shoveltusk Flank should be around 50% and it feels below 20%. It is a paint to farm them for the Great Feast.

**Database links:**

https://www.wowhead.com/wotlk/item=43013/chilled-meat
https://www.wowhead.com/wotlk/item=43009/shoveltusk-flank

**Comment by PanJanuszek** [comment]
(1) https://www.wowhead.com/wotlk/item=43013/chilled-meat
between 26.9 %- 61.4% it's ok
(2)https://www.wowhead.com/wotlk/item=43009/shoveltusk-flank
you are right it's decreased by almost 25% per NPC's --> fixing
