### ISSUE TITLE
Cooking awards not rewarded

### ISSUE THREAD

**Issue by Paschnfuzz** [gamefreedomgit/Frostmourne#855]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**Not receiving Cooking award from completing cooking daily.

**How to reproduce:**
Complete cooking daily, notice no award is received.  

**How it should work:**
Upon completing the daily, you should receive the cooking award

**Database links:**
https://www.wowhead.com/wotlk/item=43016/dalaran-cooking-award
https://www.wowhead.com/wotlk/item=43007/northern-spices

**Comment by Paschnfuzz** [comment]
No it's not.  I got 2 today from the daily, but did not receive it yesterday for the daily, so I should have 3 and not 2.

**Comment by WhitemaneIsa** [comment]
This unfortunately seems to have been a one time only occurence. To compensate you can open a ticket ingame directed at me (Isa) and I can give you a cooking award.
The report will be closed for now.
