### ISSUE TITLE
Egg of Mortal Essence not procing with Fel Synergy

### ISSUE THREAD

**Issue by jamesonhp1995** [gamefreedomgit/Frostmourne#857]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The trinket Egg of Mortal Essence does not proc off of Fel Synergy from the warlock demonology talents.

**How to reproduce:**
Equip Egg of Mortal Essence and get the Fel Synergy talent and cast shadowbolt at a target dummy.
The trinket will never proc.

**How it should work:**
The trinket should proc from all damage done by the warlock that heals the pet.

**Database links:**
https://www.wowhead.com/wotlk/item=40685/the-egg-of-mortal-essence
https://www.wowhead.com/wotlk/spell=47231/fel-synergy

**Comment by Manpower99** [comment]
on wotlk classic warlock discord, it was confirmed that this trinket can only proc from direct heals by warlock to the pet using health funnel.

**Comment by UltraNix** [comment]
Need some retail sources.

**Comment by Manpower99** [comment]
https://www.mmo-champion.com/threads/658602-The-Egg-of-Mortal-Essence
https://wowwiki.fandom.com/wiki/The_Egg_of_Mortal_Essence

2009-07-26, 12:32 AM
"not a special post on the subject but for the purpose of any warlock that wants to search about this trinket, i did a small test and found:
*does not work on Fel Armor heal ticks
*does not work from Siphon Life heals
*does not work from Haunt heal
*although didn't test enough for Drain Life it did not proc
only procced from using Life Tap, it took about 7 casts to make it proc on occasions, even giving time of 1 minute for cooldown to go."

Patch 3.3.0 (08-Dec-2009): This item can no longer be triggered by Life Tap.

It seems to have worked in the past patches but 3.3 fixes all of them, which is in line with how classic works.
only way to proc it is through directly healing your pet through health funnel which might be a broken interaction in frostmourne

**Comment by UltraNix** [comment]
So according to this info - this is not a bug.

**Comment by erikpowa** [comment]
@UltraNix  Can you check it again? 

None of the above "info" mentioning Fel Synergy being bugged and the topic is about **[Fel Synergy](https://www.wowhead.com/wotlk/spell=47231/fel-synergy)**, but can be **any direct heal that isn't over-healing** should trigger the trinket. (talent like **[Fel Synergy](https://www.wowhead.com/wotlk/spell=47231/fel-synergy)**, items like **[Bauble of True Blood](https://www.wowhead.com/wotlk/item=50354/bauble-of-true-blood)**).
It looks like this trinket is _specifically_ disabled for warlocks here.

Here is a similar item, but this one works just fine: [Scarab of the Infinite Cycle ](https://www.wowhead.com/wotlk/item=28190/scarab-of-the-infinite-cycle)

**Comment by UltraNix** [comment]
Fel Synergy is not a direct heal (it's triggered by talent).
Scarab of the Infinite Cycle might be bugged in these terms - should be reported as well.
