### ISSUE TITLE
Cannot disenchant some items

### ISSUE THREAD

**Issue by Nibbalamp** [gamefreedomgit/Frostmourne#859]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Cannot be disenchanted 
https://www.wowhead.com/wotlk/item=31291/crystalforged-war-axe#dropped-by
https://www.wowhead.com/wotlk/item=37745/greenhealers-garb
https://www.wowhead.com/item=34698/bracers-of-the-forest-stalker
**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by ChronoWM** [comment]
similar issue for
https://www.wowhead.com/wotlk/item=31303/valanos-longbow
https://www.wowhead.com/wotlk/item=31299/the-oathkeeper

**Comment by UltraNix** [comment]
Fixed.
