### ISSUE TITLE
Oculus  server crash

### ISSUE THREAD

**Issue by wotlkenjoyer** [gamefreedomgit/Frostmourne#86]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
If someone (or all members) dies on the drake during the last boss fight and dismounting,  it cause server crash

**How to reproduce:**
pull the boss and let him kill you, When ALL members being dismounted coz they lost drake HP , server crashes. tested 3 times in a row

**Comment by Afgann** [comment]
fixed
