### ISSUE TITLE
Sartharion 3 drake Bugs - PTR

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#862]
1 - Fire walls literally don't work, you don't get hit by them even if you run into them point blank range
2 - Void zones should one shot people, but do not
3 - When you pull Sartharion with 3 drakes alive, he should immediately have 3 buffs on him, but instead he only had 1 (25% health buff). 
4 - The damage overall is insanely low with all 3 drakes alive - this will be an instant one shot for any semi-competent raid group. Something is clearly not currently working properly, but can't quite tell what it is really. Perhaps the buffs + debuffs are not all being applied or something like that (see below post). 
5. The fire breath that Sartharion himself does is incredibly low.
6. Melee damage of boss + drakes are incredibly low (see my Naxxramas report where the same issue is present)

**Comment by Godmatik** [comment]
https://www.youtube.com/watch?v=VZdodseKXJU

See how all 3 buffs/debuffs are up as soon as you pull the boss.
Right now this is not happening

**Comment by RadeghostWM** [comment]
@Afgann

**Comment by Godmatik** [comment]
This is pretty critical bugs, can it be reviewed before the RF race tomorrow please?

Thanks!

**Comment by Afgann** [comment]
> ![dsfljd](https://private-user-images.githubusercontent.com/37913400/338978425-6b3875ce-45ee-40cc-ad04-9a5e91691d36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyOTE0OTAsIm5iZiI6MTcxODI5MTE5MCwicGF0aCI6Ii8zNzkxMzQwMC8zMzg5Nzg0MjUtNmIzODc1Y2UtNDVlZS00MGNjLWFkMDQtOWE1ZTkxNjkxZDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE1MDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0OGE5MmZiZjY0ZjI5NWMzMDQ2YTZlMDE2YTBmMzNhOTg3ODk5NjNjNGU0Yzk4MGRmNzVkNWZhZTJlNWZlN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NuHvsARK3XoXdwlsN4VQ6FkTVTzcw22aKtb2rXSsJsU)
> 
> I do not know who reported this as a bug, but it's not correct.
> 
> See this classic video: https://www.youtube.com/watch?v=VZdodseKXJU
> 
> Notice how all 3 player debuffs from the drakes are up as soon as you pull the boss. They should only be removed when you kill a drake. Also each time you kill a drake it should add a buff to Sartharion.
> 
> Right now this is not happening.

It literally fixes what you've meant in point 2, maybe i just worded it wrong.

**Comment by Godmatik** [comment]
> > ![dsfljd](https://private-user-images.githubusercontent.com/37913400/338978425-6b3875ce-45ee-40cc-ad04-9a5e91691d36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyOTE0OTAsIm5iZiI6MTcxODI5MTE5MCwicGF0aCI6Ii8zNzkxMzQwMC8zMzg5Nzg0MjUtNmIzODc1Y2UtNDVlZS00MGNjLWFkMDQtOWE1ZTkxNjkxZDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE1MDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0OGE5MmZiZjY0ZjI5NWMzMDQ2YTZlMDE2YTBmMzNhOTg3ODk5NjNjNGU0Yzk4MGRmNzVkNWZhZTJlNWZlN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NuHvsARK3XoXdwlsN4VQ6FkTVTzcw22aKtb2rXSsJsU)
> > I do not know who reported this as a bug, but it's not correct.
> > See this classic video: https://www.youtube.com/watch?v=VZdodseKXJU
> > Notice how all 3 player debuffs from the drakes are up as soon as you pull the boss. They should only be removed when you kill a drake. Also each time you kill a drake it should add a buff to Sartharion.
> > Right now this is not happening.
> 
> It literally fixes what you've meant in point 3, maybe i just worded it wrong.

My bad, I was referring to the debuffs on players

All 3 should be active immediately when boss pulls, and only removed when you kill a drake.

**Comment by Afgann** [comment]
Thats how it works currently on PTR, i just had to fix this a few days ago because another change broke it.

**Comment by Godmatik** [comment]
Ok, if it works fine on live then very well.

However we noticed fire walls were completely broken, they did not damage and didn't knock you back.

**Comment by Godmatik** [comment]
Understood

IMO it should one shot same as last sunwell servers, but that is discussion to be had with Radeghost I guess. Thanks for clarification

**Comment by Afgann** [comment]
On which version did you test (10/25)? Can't seem to replicate issue with fire wall.

**Comment by Godmatik** [comment]
We tested it on Tuesday. I am not sure which version it was at that time.

**Comment by RadeghostWM** [comment]
But did you test it with 10 ppl or 25 ppl?

**Comment by Godmatik** [comment]
25 people
