### ISSUE TITLE
Hunter's Mark

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#863]
You can stuck multiple Hunter's Marks from multiple Hunters on one target

**Comment by Manpower99** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/100

The benefit is not applying twice it is merely a visual thing to allow the strongest hunter's mark to apply and not be overriden by weaker ones unless it has been broken recently.
https://www.wowhead.com/wotlk/spell=19423/improved-hunters-mark#comments

**Comment by UltraNix** [comment]
Fixed.
