### ISSUE TITLE
Warlock 2pc set not showing bonus

### ISSUE THREAD

**Issue by Paschnfuzz** [gamefreedomgit/Frostmourne#864]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Wearing warlock 2pc set, but not showing that I have the bonus.  Tried re-logging, un-equipping etc.

**How to reproduce:**
Equip chest and gloves, notice there is no bonus when you hover over either piece

**How it should work:**
2pc set should be highlighted
![6efa0864935db1d40e03b581a9175599](https://github.com/gamefreedomgit/Frostmourne/assets/143338046/8f2ca485-88d8-4a7a-8380-327a21f82a5d)
![b4020baab9d537e3ba85773808dc06f3](https://github.com/gamefreedomgit/Frostmourne/assets/143338046/075a74eb-734d-42fc-961a-081967f50a32)
![9d3c2d24891b3cde2d507f9df39ad0ca](https://github.com/gamefreedomgit/Frostmourne/assets/143338046/731468da-ca8d-4c95-ab8a-82100f208169)

**Database links:**

**Comment by UltraNix** [comment]
I'm not sure what these pics should show us as you still have one piece of bonus equipped.

![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/3fade0cc-4ef0-4172-b141-830424c2987e)
You can clearly see on my char that the bonus is active (even visible in list auras and confirming that the bonus works)

**Comment by Paschnfuzz** [comment]
Just tried clearing cache, disabling addons etc, still same issue

**Comment by UltraNix** [comment]
Hmm, do you have maybe transmogs?

**Comment by Paschnfuzz** [comment]
so weird...just removed transmog and it's working now.  thanks for your help!
