### ISSUE TITLE
Normal Culling of Stratholme Loot Bug

### ISSUE THREAD

**Issue by vicewm** [gamefreedomgit/Frostmourne#865]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Malganis, the last boss in Culling of Stratholme, is not dropping 2 items sometimes. I have run this dungeon on this difficulty 5 times now and twice I have only seen one item. This is very frustrating as a holy paladin attempting to farm a bis item for the rest of the expansion, and the dungeon takes long enough as it is to only get half the loot. 

**How to reproduce:**
Kill Mal'ganis on normal difficulty. 

**How it should work:**
Malganis should drop 2 rare 187 items on normal difficulty. https://www.wowhead.com/wotlk/object=190663/dark-runed-chest is the chest the loot is contained in, and you can see from the drop chances and overall loot table 2 items are intended. 

**Database links:**
https://www.wowhead.com/wotlk/npc=26533/malganis
https://www.wowhead.com/wotlk/object=190663/dark-runed-chest

**Comment by UltraNix** [comment]
Fixed.
