### ISSUE TITLE
Naxxramas 25m Bugs - PTR

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#866]
**ALL bosses** - they deal VERY low melee damage to tanks. I'm seeing 1k-2k hits at most or so, they deal less damage than a 5 man heroic boss. These all need their damage increased significantly (just like you did with heroic bosses). Faerlina when enraged does 8k autos to a pre-bis tank as an example, you can just heal through that but IMO should not be able to.

In addition - you recently reduced health of all bosses by 30%. I feel this was a mistake - most of them die way too quick and you skip mechanics as a result. This combined with their very low melee damage they deal makes several bosses in here feel undertuned. At least compromise and do a 15 or 20% increase.

**Anub'Rekhan** - Almost never used his impale ability (only saw him use it on tank once? and it was after locust swarm ended, he should use frequently and target a non-tank member) - Insect Swarm was cast 2 mins after pull - which is way too late, he should use it much earlier. Otherwise you can kill him before it even happens.

**Grand Widow Faerlina** - The charge ability from Naxxramas Followers is being spammed too often, and the knockback AoE range of it feels much bigger than it should be as well. 

**Maexnna** - The Four Web wraps always spawn in the same spots. The positions of them should be somewhat random. In addition, the web wraps timer is off, it feels like it is independent of the other abilities but should not be. There should always follow a pattern: Web wraps --> Spiderlings --> Raid wide stun --> Repeat. The spiderlings and raid wide stun timers seem fine.

**Gothik** - While he is on the balcony, you can damage him. He should be immune in phase 1. His shadow bolt in P2 hits for nearly no damage.

**Four Horsemen** The raid wide AOE damage one of the horseman deals when alone (not tanked) is very low (3k aoes only). It can be healed through. You can nuke one of the melee horseman with lust before a single mark goes out because of the low health. The void zones hit for only 2k per tick and are not threatening at all.

**Patchwerk Trash** - The big group of little slimes in the grate room (after the abominations) should fast respawn after killing them, but they do not. 

**Gluth** -  Zombie melee damage is a bit on the low side

**Thaddius** - Somehow trash pulled from previous room when we pulled boss. Also when fight begins, Thaddius is already monitoring threat and will snipe a healer as soon as he is active. His threat table should not be active until he becomes active at start of Phase 2. His chain lightning in Phase 2 ability hits for almost nothing and could use a buff.
Also - Polarity Shift is not working properly -  It should always be an even amount on each side when charges are sent out (for example if you have 25 people, it should be 12 positive/13 negative or 13 negative/12 positive each time). Right now it is not doing this and is completely random, you could have 20+ of the same charges up at one point.

You can pull the Heigan trash beyond the locked gate in the Noth room with a pet,

**Noth** - Noth's first teleport happens too late into the fight - you can kill him before he goes up to the balcony

**Heigan** - The eruption slime hits for almost no damage, there's no risk at all of dying if you mess up the dance.

**Loatheb** - The spores movement speed is too fast. Melee damage could use a slight bump (but not as much as melee damage buff the other bosses need)

**Comment by Godmatik** [comment]
Sapphiron seems fine.

We did not have time to test Kel'thuzad - hoping some other guild can do so and provide feedback.

**Comment by Manpower99** [comment]
**Thaddius** does indeed have an issue similar to the recently fixed skadi threat issue where threat seems to count from before he is targetable, the + and - are also indeed too uneven and should be looked at.

**Gothik** should be invulnerable prior to Phase 2, this currently does not change much this his health seems to reset to full at Phase2 but it is padding to potential armory dps logs.

**Loatheb** spores move too fast as observed in this [video ](https://www.youtube.com/watch?v=GC25zMz9Lhw)they are supposed to be slower, it also seems to have a _huge radius?_ to give Fungal Creep, should be about 10 yards and should not apply to random players within 10 yards but whicever 5 players are closer.
the [debuff ](https://www.warcrafttavern.com/wotlk/news/wotlk-classic-hotfixes-november-8th-fungal-creep-nerfed-on-trash/)should also dissappear upon encounter with loatheb being over.

**Heigan's** Eruptions could use a 30% damage increase in attempts to make it more difficult as a bossfight.

@Afgann

**Comment by RadeghostWM** [comment]
What gear did you test it with? Prebis? T10?

**Comment by Godmatik** [comment]
> What gear did you test it with? Prebis? T10?

Only pre-bis - we made sure to enforce this.

**Comment by Godmatik** [comment]
@RadeghostWM thoughts on the tuning suggestions?
