### ISSUE TITLE
Fiery Plate Gauntlets - unfired plate gauntlet not lootable

### ISSUE THREAD

**Issue by Karsenity** [gamefreedomgit/Frostmourne#867]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** quest "Fiery Plate Gauntlets" bugged, cannot loot the unfired plate gauntlets. Item despawns without yielding them

**How to reproduce:** Attempt to loot the fiery plate gauntlets

**How it should work:** Should be able to pickup the unfired plate gauntlets quest item to finish the quest

**Database links:** https://www.wowhead.com/wotlk/item=12812/unfired-plate-gauntlets#contained-in-object

**Comment by Aeradel** [comment]
confirmed - i wasn't able to loot them. empty loot window.

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/12a0426d-798f-420d-9867-b9fb1f42389f)
Cannot reproduce it - maybe there was more warriors/paladins in your party with this quest?

**Comment by Karsenity** [comment]
I was the only blacksmith in our group, so only one with the quest.

One thing I should specify is I first tried to grab it without the quest, then I grabbed the quest from the corpse beside them, and then tried again. Just incase there's some flag after you attempt once.

**Comment by UltraNix** [comment]
Fixed.
