### ISSUE TITLE
Some TBC Boss drops aren't disenchantable

### ISSUE THREAD

**Issue by StaticHispanic** [gamefreedomgit/Frostmourne#868]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
In the Shattered Halls N, the Greaves of the Shatterer and Lightsworn Hammer aren't able to be disenchanted.
When you try to DE it from the rolling menu, it says "You do not have an enchanter of skill 275 in your group" and when you try to DE it from your bags, it just says "Item cannot be disenchanted"

![image](https://github.com/gamefreedomgit/Frostmourne/assets/142506452/bcfdd7bc-a615-424b-aefa-14b0cc24a62e)

**How to reproduce:**

**How it should work:**
They're supposed to be disenchanted into Large Prismatic Shards
![image](https://github.com/gamefreedomgit/Frostmourne/assets/142506452/cf76169f-8582-446f-877f-49af403d8aad)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/142506452/45b61523-586c-46d4-b9ba-979d23943fec)

**Database links:**

**Comment by Manpower99** [comment]
some TBC items seem to also not have a vendor value whatsoever and many not disenchantable.
https://www.wowhead.com/wotlk/item=31303/valanos-longbow
looted it yesterday and it had no vendor value.

**Comment by Afgann** [comment]
fixed
