### ISSUE TITLE
Spells that cost no mana and mana rule

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#869]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
spells that cost no mana such as Lightning Shield and spells whose mana cost is reduced to 0 due to Clearcasting other similar buffs or talents should allow you to continue to regen your mana as if you hadn't cast anything.
currently tested as spellhance and a arcane mage and a Hunter with 3/3 hunter's mark talent on ptr the spells are affecting the 5 second rule.

https://wowpedia.fandom.com/wiki/Five_second_rule
to cite: Because the activation of the five second rule was dependent on mana expenditure, mana regeneration would continue if a character cast a "free" spell by the means of [clearcasting](https://wowpedia.fandom.com/wiki/Clearcasting). The same applied to any spell (i.e. Spell nature ravenform [[Nature's Swiftness]](https://wowpedia.fandom.com/wiki/Nature%27s_Swiftness)) which cost 0 mana. This could be useful when trying to regenerate mana, but still being able cast one free spell without interrupting mana regeneration (for instance in case of an emergency.) 

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
