### ISSUE TITLE
Reputation Exalted aren't doubled on alts

### ISSUE THREAD

**Issue by ffroehly** [gamefreedomgit/Frostmourne#871]
**Description:**
When there's a character that is exalted in a faction, the reputation on alts is supposed to doubled.
However, I'm getting +15% more on bosses instead of +100%.

**How to reproduce:**
Get a 80 character that is exalted in Kirin'Tor, then get an alts 80 on a dungeon and kill a boss. You'll see that the reputation gained is 373ish.

**How it should work:**
On bosses, reputation is 325 basic. And it should be 650 once doubled.

**Database links:**
/

**Comment by Manpower99** [comment]
it worked fine for me on alt with sons of hodir, i cannot confirm for other reputations

**Comment by UltraNix** [comment]
Fixed.
