### ISSUE TITLE
DK start zone – Prince Valanar's says are in Common

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Frostmourne#873]
Playing the Troll DK, my troll did not understood [Valanar](https://www.wowhead.com/wotlk/npc=28377/prince-valanar)'s says in Common.

https://wowpedia.fandom.com/wiki/Prince_Valanar#Quotes

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
