### ISSUE TITLE
Visual Bug - Improved Icy Talons

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#874]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The talent seems to work as intended it is not stacking however multiple instances of the buff do exist on the buff bar but shouldn't.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Piootrek** [comment]
Fixed, I will close this once the fix comes live.
