### ISSUE TITLE
No ICD on some npc spells in dungeons.

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#876]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
https://wotlk.evowow.com/?npc=30179 Twilight apostle - Ahn'kahet dungeon, has lightning shield with no icd on its damage effect. Fast attack classes easily kill themselves attacking this mob.
Proc chance also looks like it might be 100% on the shield dmg.
From wowhead https://www.wowhead.com/wotlk/spell=61570/lightning-shield (should have Proc chance: 50%, 2s cooldown)

https://wotlk.evowow.com/?npc=27281 Ritual channeler - Utgarde pinnacle (mobs spawned by Svala) give you a debuff whenever you attack them with no icd once again. Fast attack classes get 20 stacks in less than a second which is instadeath unless cloaked/ams.
The spell itself: https://www.wowhead.com/wotlk/spell=59407/shadows-in-the-dark
Should have 800ms cooldown.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by yeagerca** [comment]
The Drakkari Lancer in Gundrak also does this with Retaliation.
https://www.wowhead.com/wotlk/npc=29819/drakkari-lancer
https://www.wowhead.com/wotlk/spell=40546/retaliation

**Comment by Manpower99** [comment]
> The Drakkari Lancer in Gundrak also does this with Retaliation. https://www.wowhead.com/wotlk/npc=29819/drakkari-lancer https://www.wowhead.com/wotlk/spell=40546/retaliation

Relatiation by the Drakkari Lancer is completely bugged, he can counterattack from behind while it is also proccing too much where a rogue under massive attack speed could insta kill himself. it should only counterattack one attack per 0.5 seconds and intended to be a thing against tanks not dpsers

**Comment by Afgann** [comment]
fixed
