### ISSUE TITLE
Attacking vehicles - perma combat

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#877]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Attacking vehicles in wintergrasp gives the player permanent combat until the vehicle is destroyed.

**How to reproduce:**
Attack a catapult in wintergrasp and have it run away. Combat will remain until either vehicle is destroyed or player dies.

**How it should work:**
Standard leave combat timer.

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
