### ISSUE TITLE
Pestilence range bugged

### ISSUE THREAD

**Issue by Sylanha** [gamefreedomgit/Frostmourne#878]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Pestilence on DK's is not how it's supposed to work. On Warmane and Classic Wotlk it has a bigger range and is supposed to spread when moving into the direction, like an extension.

**How to reproduce:**
I will provide video evidence on how it is supposed to work on Warmane(/Classic Wotlk) and can be easily reproduced in Acherus/DK City on the training dummies. Apply diseases on the middle one and spread it on the outer dummies while moving towards them.

**How it should work:**
It should be possible to spread diseases while moving towards the target, extending the range. Also the range of Pestilence is bigger in general, so a range buff should be applied on top of that.

**Database links:**
I will provide Video evidence from myself, recorded on Warmane (Buubabomber) and on Whitemane (Buubabomber/Zyncrow).
https://youtu.be/10GcrBpnGyI

In addition I will link a Video from Warmane from another DK player proving that pestilence should work like I mentioned above.
Starting at 15:01 https://youtu.be/_4dWcyc4xF0?si=3zv-fD8NnBfvYe3-&t=901

**Comment by Manpower99** [comment]
It is indeed not benefitting from leeway at all i already reported this but this is a much better explained report!

**Comment by Sylanha** [comment]
Also there was a mechanic where when you jump, your AoE has a wider range. But I would very much prefer the above to get fixed.

**Comment by Sylanha** [comment]
Yeah just mentioned it, since that the case when jmuping while pressing Bloodboil. It should have a bigger range

**Comment by UltraNix** [comment]
Fixed.
