### ISSUE TITLE
[SHAMAN - ENHANCEMENT] Fire elemental + feral spirits AoE damage reduction missing

### ISSUE THREAD

**Issue by gmforghieri** [gamefreedomgit/Frostmourne#88]
**Description: **
Feral spirits and fire elementals should have the Avoidance ability which reduces AoE damage taken by 90%, just like hunter or warlock pets have it.  Without these the feral spirits or fire ele just dies in case of any AoE like Sartharion fire wall for instance.

https://wotlk.evowow.com/?spell=65220
https://wotlk.evowow.com/?spell=32233

**How to reproduce: **
For example, summon wolves and fire elemental on Sartharion and observe the fire wall kill them.

**How it should work: **
Spirit wolves and Fire elemental should have 90% AoE dmg reduction just like warlock and hunter pets.

https://www.youtube.com/watch?v=1dvOuKtxCyg
https://www.youtube.com/watch?v=bfoL8V2Ycq8
https://www.youtube.com/watch?v=2gOL9-d5MBc

**Comment by UltraNix** [comment]
Feral Spirits:
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/5080182a-43f9-409f-a209-7126d194a0c2)

Fire Elemental:
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/9adcc2eb-4eac-495f-b82b-01d91cc0965d)

Spell 32233 provides 90% of AoE damage reduction.
Tested on Sartharion:
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/0c406e23-d5b9-4529-9771-b72cd0cac59f)

As you can see, his Cleave damage is reduced.
