### ISSUE TITLE
NPC not dropping any loot

### ISSUE THREAD

**Issue by Obudin** [gamefreedomgit/Frostmourne#881]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Add called Kutube'sa (in Zul'drak 56, 63) 

**How to reproduce:**

**How it should work:**
It should give some loot, according to Wowhead.

**Database links:**
https://www.wowhead.com/wotlk/npc=28494/kutubesa

**Comment by WhitemaneIsa** [comment]
It gave me loot regularly. You might have just been unlucky.
