### ISSUE TITLE
Sunwell Timewalk - Felmyst Critical Bug

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#882]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
On phase 2 - flight phase, Felmyst's position in the air does not reflect properly which lane she will use Fog of corruption on. This makes it entirely RNG whether the raid wipes or not. Critical bug that needs to be fixed prior to sunwell timewalk release or people will go nuts as usual.

She mostly hovers over the middle or fire zones but where she casts the breath is random. Sometimes this aligns with her position which makes it look like its working properly, but other times she flies far into fire zone and casts breath on tree lane wiping the raid.

https://www.youtube.com/live/e-Zi9uUWEPY?si=3obNSr8qb9iQmbQr&t=15440
This video is from a few days ago level70 version. I assume scripts are the same for the timewalk, if I am mistaken please tell I will close the issue.
You can see at the exact time on the video, Felmyst shifts from far left to middle(her actual air position), yet she still casts breath far left.(ground spell cast position)
If you explore the video around that time previous pull she did the same thing staying fire side but she cast breath on the tree and we wiped.

**How to reproduce:**
Reach femyst flight phase and observe boss flight+cast patterns.

**How it should work:**
The way she moves in the air should be indicative of which zone on the ground the wipe spell will be cast on.

**Database links:**

**Comment by RadeghostWM** [comment]
@Afgann

**Comment by Afgann** [comment]
fixed
