### ISSUE TITLE
Darkclaw Lobster not being fished up

### ISSUE THREAD

**Issue by Karsenity** [gamefreedomgit/Frostmourne#883]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Darkclaw lobster's are supposed to be the common fish obtainable in the Bay of Storms in Azshara. However it looks like due to changes in how often you obtain rare fish, they're either extremely rare or unobtainable.  With 3 people fishing here at different times, none of us obtained a single lobster.

**How to reproduce:** Fish in the Bay of Storms

**How it should work:** Darkclaw Lobster should be obtainable (normal rate is over 50% of casts)

**Database links:** https://www.wowhead.com/wotlk/item=13888/darkclaw-lobster#comments

**Comment by Afgann** [comment]
fixed
