### ISSUE TITLE
[NPC] Mottled Screecher

### ISSUE THREAD

**Issue by Enteroox** [gamefreedomgit/Frostmourne#884]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The [Mottled Screecher](https://www.wowhead.com/wotlk/npc=1021/mottled-screecher) is a raptor beast in the Wetlands with the ability to call other raptors to aid him, however, this does not seem to function.

Note: I am unsure if my character being 15 levels above the raptors could nullify the "help" part.

**How to reproduce:**
Visit the raptors in Wetlands, not too far from the Alliance fort, try hunting them and you'll notice that the [Mottled Screechers](https://www.wowhead.com/wotlk/npc=1021/mottled-screecher) do screech to gain help, however, the other raptors in the area do not respond.

**How it should work:**
Other raptors should join to assist them.

**Database links:**
[Mottled Screecher](https://www.wowhead.com/wotlk/npc=1021/mottled-screecher)

**Comment by Afgann** [comment]
fixed
