### ISSUE TITLE
Human Illusion being aplied to Human players in Culling of Stratholme

### ISSUE THREAD

**Issue by AMInxs** [gamefreedomgit/Frostmourne#885]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Human players are being affected by the Human Illusion buff from the dungeon.

**How to reproduce:**
Join the dungeon via RDF when a horde player is the leader.

**How it should work:**
Shouldn't transform ally races know to Arthas.

**Database links:**
https://www.wowhead.com/wotlk/spell=35483/human-illusion

**Comment by Manpower99** [comment]
Two instances of the Human illusion is applying to players confirmed, seems to be always turning players into Human Male instead of respecting character's gender being female/male.
my character being orc female got transformed into human male instead of female human.

**Comment by UltraNix** [comment]
Fixed.
