### ISSUE TITLE
Switching talents keep the previous glyphs that are already active.

### ISSUE THREAD

**Issue by Bigdeepsx** [gamefreedomgit/Frostmourne#887]
**Description:**
For example: as a mage, I can put on molten armor, switch talents and use different glyph and the molten armor glyph would still give me extra crit.
or I can summon elemental using the eternal water glyph and keep the elemental even if I switch to talents without the eternal water glyph.

**How to reproduce:**
Use glyph of molten armor, use the spell molten armor, switch talents, you will see the crit bonus is still there, now use molten armor again with the new talents without the glyph, bonus will disappear as it should.
For the elemental you can just have 2 frost talents and have 1 with the glyph and the other without, switch areas (queue bg or dungeon or whatever) and the elemental will appear and last forever without the glyph.

We can abuse this bug to have 5 glyphs or more active at a time.
Example of eternal elemental being active on other talents will be added to this threat (You can tell its eternal water since the spell "freeze" isn't available anymore) 

![WoWScrnShot_061324_022902](https://github.com/gamefreedomgit/Frostmourne/assets/172526848/decea91b-69b1-47dc-9402-8675ad048846)
![WoWScrnShot_061324_022904](https://github.com/gamefreedomgit/Frostmourne/assets/172526848/9494d3ad-d620-41f7-86cf-76ba8e4a88f3)
![WoWScrnShot_061324_022903](https://github.com/gamefreedomgit/Frostmourne/assets/172526848/a3f0fa9e-97a6-4560-a583-2bb64a2327b4)

**Comment by Bigdeepsx** [comment]
Most likely this bug is abusable on every class with glyphs that are similar to these.

**Comment by Manpower99** [comment]
I thought this got fixed since beta but i guess not then.
hopefully gets fixed before 14th

**Comment by UltraNix** [comment]
@Bigdeepsx Explain once again the elemental case, because I cannot reproduce it.
Have frost talents with glyph.
Summon water elemental
Change talents (elemental is despawned)
Now I have talents without glyph
Join bg
Summon water elemental

Is that right?

**Comment by Bigdeepsx** [comment]
You gotta have one frost talents with the glyph, and one without, both has to be frost with the talent water elemental.
The elemental will keep randomly appearing without freeze and permanent, even on the talents without the glyph.
Basically im trynna play pvp without my elemental "freeze" spell which is ANNOYING.
and the bug doesnt stop there, it can be abusable with molten armor as I said before

**Comment by UltraNix** [comment]
Fixed.
