### ISSUE TITLE
Writhing Choker in Zul'Drak

### ISSUE THREAD

**Issue by alemae96** [gamefreedomgit/Frostmourne#889]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I looted the quest and it says "You do not meet the requirements for this quest".

**How to reproduce:**
I have restarted game and pc and still same issue.

**How it should work:**
It should allow me to accept the quest when looted and right clicked.

**Database links:**

**Comment by LezChap** [comment]
When I looked this up, I believe there's two versions of the Choker.  One is supposed to drop before you've completed the Cleansing Drak questline, and one is supposed to drop after, and each one starts a leader quest to the same mob/questline but has different text depending on where you are in the "story" of the questline.

 However, the one that's supposed to drop after you've done the Drak dungeon quest appears to be dropping even if you haven't completed the Dungeon questline yet.  When I completed the Drak quest, the choker (I still had in my inventory) worked.

Just looked it up from Wowhead:
To be more clear about this item:
[Writhing Choker](https://www.wowhead.com/wotlk/item=38673) and [Unliving Choker](https://www.wowhead.com/wotlk/item=38660) will start different quests but lead to the same objective. So:

[Unliving Choker](https://www.wowhead.com/wotlk/item=38660#starts):
Starts: [An Invitation, of Sorts...](https://www.wowhead.com/wotlk/quest=12631)
Chains:
2nd: [Near Miss](https://www.wowhead.com/wotlk/quest=12637)
3rd: [You Can Run, But You Can't Hide](https://www.wowhead.com/wotlk/quest=12629)
4th: [Dressing Down](https://www.wowhead.com/wotlk/quest=12648)
5th: [Infiltrating Voltarus](https://www.wowhead.com/wotlk/quest=12661)
...
[Writhing Choker](https://www.wowhead.com/wotlk/item=38673#starts):
Starts: [Darkness Calling](https://www.wowhead.com/wotlk/quest=12633)
Chains:
2nd: [Close Call](https://www.wowhead.com/wotlk/quest=12638)
3rd: [Silver Lining](https://www.wowhead.com/wotlk/quest=12643)
4th: [Suit Up!](https://www.wowhead.com/wotlk/quest=12643)
5th: [Infiltrating Voltarus](https://www.wowhead.com/wotlk/quest=12661)
...
As you can see the quest names are different but have all the same objectives and by the 5th chain they have converged into one only.
Conclusion: Do not waste your time trying to get the other choker once you've gotten your first.

**Comment by alemae96** [comment]
I'm doing Loremaster. So I've completed every other quest in ZD including dungeon quests, and this is the last set of chain to complete the zone. So I'm not sure what else there is to do tbh.

**Comment by LezChap** [comment]
For loremaster it's still possible...each daily quest counts once, and there's several options there with the Troll Patrol dailies.
