### ISSUE TITLE
Brann is Attackable by Horde Members in Halls of Stone

### ISSUE THREAD

**Issue by Radju988** [gamefreedomgit/Frostmourne#89]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**Tittle says it all :D

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by ammenvale** [comment]
Did HoS as alliance and he was attackable to me, looks like it's when the other faction talk to Brann

**Comment by Afgann** [comment]
fixed
