### ISSUE TITLE
[Quest] Stormhoof's spear doesn't drop

### ISSUE THREAD

**Issue by Lastfallen99** [gamefreedomgit/Frostmourne#890]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When doing the quest The Hero's Arms Stormhoof's spear doesn't drop, it has a 8% of drop chance from Scion of storm but it only drops the item quest Stormhoof's mail that also has a 8% drop chance.

**How to reproduce:**
Take the quest "The Hero's Arms"
Go to Thunderfall in northeastern Storm Peaks
Kill groups of Scion of storm

**How it should work:**
It should drop Stormhoof's spear alongside with the other loot that the Elemental should drop

**Database links:**
https://www.wowhead.com/wotlk/item=42782/stormhoofs-spear
https://www.wowhead.com/wotlk/quest=13049/the-heros-arms
https://www.wowhead.com/wotlk/npc=30184/scion-of-storm#drops
https://www.wowhead.com/wotlk/item=42783/stormhoofs-mail

**Comment by Afgann** [comment]
fixed
