### ISSUE TITLE
Disenchantable items which can’t be disenchantable

### ISSUE THREAD

**Issue by Ricox2003** [gamefreedomgit/Frostmourne#891]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

The pieces of gear that say DE can’t be DE. Those are girdle of divine blessing and Draenei honor guard shield
**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
