### ISSUE TITLE
Quest - Fervor of the Frostborn - The Iron Watcher Incorrect Behaviour

### ISSUE THREAD

**Issue by Cyclohexanewow** [gamefreedomgit/Frostmourne#893]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
After correctly charging to the edge of the platform when below ~40% health, The Iron Watcher teleports back to its starting position and evades before you are able to get to the edge of the platform to use the Battered Storm Hammer one more time to push him off the edge of the platform to complete the quest objective.

**How to reproduce:**
Attempt to complete the quest objective in the normal way.

**How it should work:**
The Iron Watcher should stay at the edge of the platform until the player is able to run in to the correct range to use the Battered Storm Hammer

**Database links:**
See first comment in https://www.wowhead.com/wotlk/quest=12874/fervor-of-the-frostborn for the intended completion method

**Comment by Ner0-x** [comment]
Confirmed, doesnt work!

**Comment by Afgann** [comment]
fixed
