### ISSUE TITLE
Return to Angrathar - No cutscene

### ISSUE THREAD

**Issue by T0rturous** [gamefreedomgit/Frostmourne#894]
[//]: # (https://www.wowhead.com/wotlk/quest=12500/return-to-angrathar)

**Description: I completed the quest but the cutscene didn't play and the scenery didn't change.**

**How to reproduce: Go through it yourself i guess.**

**How it should work: You get the cutscene and the scenery changes.**

**Database links:**

**Comment by UltraNix** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/465#issuecomment-2127887950
Check if you have that file.

**Comment by RadeghostWM** [comment]
The client might not have the video attached.
