### ISSUE TITLE
Green drakes not leeching (Oculus)

### ISSUE THREAD

**Issue by Galatoa** [gamefreedomgit/Frostmourne#897]
[[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)
](https://wowpedia.fandom.com/wiki/Oculus#Flying_combat)

**Description:**
Green drakes during Ley-Guardian Eregos fight (last boss in Oculus) don't leech correctly the poison damage they deal with their Leeching Poison spell. Sometimes they work fine and sometimes they randomly stop leeching health making it impossible to use their 2nd and 3rd spells cause they consume health.

**How to reproduce:**
So far every time I've done the fight it has happened, leeching works only sometimes and whenever it stops working for a while it goes back to healing as it should also randomly. I haven't been able to identify any particular trigger for this bug.
It consistently happens every fight (usually multiple times per fight) but it doesn't happen in a predictable pattern (e.g. stops working at the beginning of the fight or after Phase Shift...).
**How it should work:**
As the wiki states: [Leeching Poison] Poisons the enemy dragon, leeching 1300 to the caster every 2 sec. for 12 sec. Stacks up to 3 times. Instant.
So as long as you have stacks of poison on Eregos you should be healing every 2 seconds not sometimes healing every 10-20 sec on random intervals.
In fact as long as you keep up the 3 stacks you should be healing 3900 hp every 2 sec which should be enough to keep up with the 30% max hp cost of Touch of Nightmare and the 5% max hp transfer of health of Dream Funnel.

**Database links:**
(https://wowpedia.fandom.com/wiki/Oculus#Flying_combat)
(https://www.wowhead.com/?spell=50328)

**Comment by bandini9** [comment]
Happened to me once at the start of fight and I GUESS It started working after I healed someone once

**Comment by Riztazz** [comment]
fixed, will close once it's live
