### ISSUE TITLE
World Vendor Item Respawn Timers

### ISSUE THREAD

**Issue by 4rt-Net** [gamefreedomgit/Frostmourne#898]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Rare items and recipes in vendors (specifically from hardcore perspective)

Issue 1:
There is no indicator or timer showcasing when the item will be available.
Example:
![image](https://github.com/gamefreedomgit/Frostmourne/assets/53600019/33224858-95db-4039-a67d-7faef2a33e42)

Issue 2: 
The respawn time is off, I personally waited approximately 01:30:00 for the item to respawn and kept refreshing the vendor by talking to her again, item still did not refresh. 
On wotlk classic retail this timer was around 15-30 minutes. 

Issue 3: 
There is a separate AH for softcore/hardcore which is great, however, world vendors may be camped by softcore players which makes it extremely difficult if not impossible to get items as hardcore, this is worsened by the fact that AH is separated. 
(especially profession recipes for example tangy clams in tanaris)

**How to reproduce:**
Sit infront of Kris Legace for 2 hours to buy "Stalking Pants" -_-

**How it should work:**
Respawn eventually

**Database links:**

**Comment by UltraNix** [comment]
For these items and this vendor - respawn timer is 12h.

**Comment by UltraNix** [comment]
Fixed.

**Comment by 4rt-Net** [comment]
> Fixed.

Thanks a mil UltraNix - saw the fix ingame. Much appreciated 🙏😎
