### ISSUE TITLE
Need some GM to erase 3 totems of my bag

### ISSUE THREAD

**Issue by Dokka90** [gamefreedomgit/Frostmourne#900]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I did 3 of the 4 totem quest (Alliance) and now I can´t remove the totems from my bag. It says its forbidden to do that.
![Imagen-1](https://github.com/gamefreedomgit/Frostmourne/assets/142290067/37505019-3b3c-4462-bf06-6be23644262f)
![Imagen-2](https://github.com/gamefreedomgit/Frostmourne/assets/142290067/fc04d047-1b91-491f-b468-060ec98f93d9)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Dokka90** [comment]
Hi Elsa, I did that. I open the ticket ingame and they sent me here to report the problem.

**Comment by WhitemaneIsa** [comment]
> Hi Elsa, I did that. I open the ticket ingame and they sent me here to report the problem.

Put in your ticket that I told you to put it and they should assign it to me.
