### ISSUE TITLE
Heroic RDF: Healer should also get [Satchel of Exotic Mysteries] <3

### ISSUE THREAD

**Issue by pierlucj** [gamefreedomgit/Frostmourne#901]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by RadeghostWM** [comment]
He does when there’s not enough healers.
