### ISSUE TITLE
Slad'ran - Gundrak - LoS Bug

### ISSUE THREAD

**Issue by Skrundead** [gamefreedomgit/Frostmourne#902]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
https://imgur.com/a/orhjKvw

**How to reproduce:**

**How it should work:**
Could have been a latency thing but Im worried that the LoS doesnt work in some cases or the cast goes off earlier than intended

**Database links:**

**Comment by WhitemaneIsa** [comment]
[Slad'ran](https://www.wowhead.com/wotlk/npc=29304/sladran)

**Comment by Afgann** [comment]
fixed
