### ISSUE TITLE
RDF HC lockouts inconsistent when queuing with full party

### ISSUE THREAD

**Issue by yeagerca** [gamefreedomgit/Frostmourne#903]
**Description:**
Refer to issue #845 about RDF HC allowing players to randomly queue into dungeons they are already locked to.

When queuing RDF HC, players are sometimes being placed in their old lockout where bosses were already dead.
- This occurred when queuing into RDF HC as a full party of five.
- This issue occurred in Gundrak. Once where Eck was still alive from the previous clear, and once where all bosses were dead.
- It did not occur in Violet Hold. The instance was fully reset except for the portal counter UI element, which reset from 7/18 to 1/18 upon the first portal spawning.

**How to reproduce:**
Queue into RDF HC with a full party where one of more members are saved to different lockouts.

**How it should work:**
RDF HC should always place the party in a fresh instance.

**Comment by yeagerca** [comment]
#872 may be the same issue.

**Comment by Manpower99** [comment]
yesterday we got a druid who was locked and thus different id than us, as we queued he was inside the dungeon but different cleared instance.
