### ISSUE TITLE
Players automatically removed from group when they log off (relog), group automatically disbands

### ISSUE THREAD

**Issue by gforghieri** [gamefreedomgit/Frostmourne#904]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Players automatically removed from group when they log off (relog), group automatically disbands

**How to reproduce:**
Be in a group of 2 players, have a player logout to relog for example, party automatically disbands

**How it should work:**
Players should not automatically leave the group when they logout.

**Comment by Afgann** [comment]
fixed
