### ISSUE TITLE
 [Symbol of Kings]

### ISSUE THREAD

**Issue by lovemaja** [gamefreedomgit/Frostmourne#905]
** [Symbol of Kings]**

 Symbol of Kings do dont stack with a 100 in stack now after the respawn before restart a stack can have 100 in it now it is 20...

**Comment by toolshmool** [comment]
![Screenshot 2024-06-14 154043](https://github.com/gamefreedomgit/Frostmourne/assets/60327939/31eaca0e-f6a4-4ba6-8a6d-9f2c0c1b2d89)

Make them stack as 100 like b4

**Comment by WhitemaneIsa** [comment]
Working again.
