### ISSUE TITLE
Anomalus Achievement not working

### ISSUE THREAD

**Issue by Paunimogo** [gamefreedomgit/Frostmourne#907]
[//]: # https://www.wowhead.com/wotlk/achievement=2037/chaos-theory https://www.wowhead.com/wotlk/npc=26763/anomalus#drops;mode:heroic # 

**Description:**
When trying to do the Anomalus Achievement Chaos Theory, Anomalus will get to 50% in the battle, then it will spawn chaos rifts, to complete the achievement you have to end the battle without killing the rifts, we did just that, with 1 rift alive as it didn't spawned any 

**How to reproduce:**
Get it to 50%, then wait aprox 40 to 50 seconds without killing the rift, then kill the boss, the achv won't pop

**How it should work:**
When killing it without killing the rift, the achv should pop

**Database links:**
https://www.wowhead.com/wotlk/achievement=2037/chaos-theory 
https://www.wowhead.com/wotlk/npc=26763/anomalus#drops;mode:heroic

**Comment by Afgann** [comment]
fixed
