### ISSUE TITLE
target=focus macro bug

### ISSUE THREAD

**Issue by johnsmith534** [gamefreedomgit/Frostmourne#908]
I have two macros `#showtooltip Corruption 
/stopcasting
/cast [target=focus,exists] Corruption` and `#showtooltip Shadow Bolt
/cast [target=focus,exists] Shadow Bolt(Rank 1)` the macro to cast Corruption on my focus target works but if I try to use the Shadow Bolt macro it tells me I have no target and only works when I have something targetted. It is also not properly downranking the spell.

**Comment by UltraNix** [comment]
Both macros work okay to me.
@johnsmith534 Could you re-test it?

**Comment by johnsmith534** [comment]
Seems it is a bug with ElvUI
