### ISSUE TITLE
Item - Symbol of Kings not stacking properly

### ISSUE THREAD

**Issue by ffroehly** [gamefreedomgit/Frostmourne#909]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Syombols of Kings are only stacked by 20 intead of by 100. This has been modified since release of 13/06 or 14/06, not sure.

**How to reproduce:**
Try to stack the item "Symbol of kings". Get 200 of them, you'll see 10 stacks of 20

**How it should work:**
It shoudl be 2 stacks of 100

**Database links:**
![2024-06-14 17_34_11-World of Warcraft](https://github.com/gamefreedomgit/Frostmourne/assets/86048865/bdf2d978-b04d-4233-983d-bc6ed412dbae)

**Comment by Afgann** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/905
