### ISSUE TITLE
Halls of Lightning ( Fearing mobs pull through the closed door)

### ISSUE THREAD

**Issue by wotlkenjoyer** [gamefreedomgit/Frostmourne#91]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

In front  of Volkhan on left side the door is closed, if Volkhan is alive. 

If you fight 3 elementals at  the door, fearing mobs from hallway  being pulled somehow and coming through.

**Comment by Afgann** [comment]
fixed

**Comment by wotlkenjoyer** [comment]
![WoWScrnShot_031924_012654](https://github.com/gamefreedomgit/Frostmourne/assets/158612010/cab75ece-f937-4dbb-bf3d-a46b765aa9b2)
![WoWScrnShot_031924_012701](https://github.com/gamefreedomgit/Frostmourne/assets/158612010/bb219029-5d6e-498e-824d-0f9bbf7ab70f)

**Comment by wotlkenjoyer** [comment]
@Afgann @UltraNix    

Hello, we did it today again, without trying to bug it on purpose, it happened again, they just coming through , fear everyone, and you most likely wipe because elementals destroying healer

On the screenshot you can see, Volkhan is alive,  doors closed, but mobs are here
