### ISSUE TITLE
GetRepairAllCost() API function works incorrectly

### ISSUE THREAD

**Issue by RRamz** [gamefreedomgit/Frostmourne#911]
GetRepairAllCost() function works incorrectly

**How to reproduce:**
/run repairAllCost, canRepair = GetRepairAllCost();print(repairAllCost, canRepair);
repairAllCost is always equal to 0

**How it should work:**
repairAllCost should be to the repair cost in copper

**Comment by Godmatik** [comment]
Confirmed, if you highlight over the 'repair all' icon at a vendor, it doesn't show much gold it is to repair

**Comment by UltraNix** [comment]
![Uploading image.png…]()
Works like this for me.

**Comment by WhitemaneIsa** [comment]
> ![image](https://private-user-images.githubusercontent.com/80540499/340411642-32625553-3cbb-4fea-b65e-0ad3f89c5878.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NTEwNDgsIm5iZiI6MTcxODY1MDc0OCwicGF0aCI6Ii84MDU0MDQ5OS8zNDA0MTE2NDItMzI2MjU1NTMtM2NiYi00ZmVhLWI2NWUtMGFkM2Y4OWM1ODc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE4NTkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZDViYWI2NmRmY2Q3YjNiNjU1NmRjYWY3ZDBjYjk4ZDE3NDAwMzNiNzUxYjdkY2UzMDdjNmRiNTgxNzdkNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q9Sd3Z9Qv0iGq4VPx8yRbR3ZkdQEG5lvmif4oLmp6Nk) Works like this for me.

Try it again while being in a guild maybe. I can definitely reproduce it.

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/944
