### ISSUE TITLE
A Hero's Burden bug select rep from oracles or wolvar

### ISSUE THREAD

**Issue by Drancelot** [gamefreedomgit/Frostmourne#912]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When I finish the missions A Hero's Burden they do not give me the choice of the mission to select the reputation of the oracles or the wolvars

**How to reproduce:**

When you kill one of the npcs that are next to Artruis the Heartless, the npc that he has frozen next to him become aggressive and it is assumed that when you kill one of them, the other one should give you a mission to choose the other's reputation.

**How it should work:**

**Database links:**

**Comment by WhitemaneIsa** [comment]
They remain hostile and only Jaloot unfreezes after some time, Zepik remains frozen and unattackable.

https://www.wowhead.com/wotlk/quest=12581

https://www.wowhead.com/wotlk/npc=28668/zepik-the-gorloc-hunter
https://www.wowhead.com/wotlk/npc=28667/jaloot

**Comment by Drancelot** [comment]
The problem is that I have already completed and delivered the previous
mission A Hero's Burden and neither Jaloot nor Zepik were able to take the
mission for their reputation by killing one, the other was still aggressive
and now I can't continue with any of them. the two reputations El problema
es que la misión anterior A Hero's Burden ya la tengo completada y
entregada y tanto jaloot como zepik ninguno se puso como para poder coger
la mision para su reputacion al matar a uno el otro seguía en agresivo y
ahora no puedo continuar con ninguna de las dos reputaciones

**Comment by UltraNix** [comment]
Fixed.
