### ISSUE TITLE
Sell back to vendor doesnt work.

### ISSUE THREAD

**Issue by Beardedrasta** [gamefreedomgit/Frostmourne#915]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When you buy an item for emblems you have 2 hours to sell it back to vendor for emblem value, it currently doesnt let you sell it back.

**How to reproduce:**
Buy item from emblem vendor and then try to sell back.

**How it should work:**
It should return the purchase amount back to player.

**Database links:**

**Comment by RadeghostWM** [comment]
Please give name of the item(s) you tried to refund but couldn't.

**Comment by WhitemaneIsa** [comment]
As there has been no further info/complaints, this will be closed for now.
