### ISSUE TITLE
Reinforced Junkbox - Loot Drop

### ISSUE THREAD

**Issue by Sunkween** [gamefreedomgit/Frostmourne#917]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk/item=43575/reinforced-junkbox)

**Description:**
Rogues can Pick Pocket certain mobs to acquire the box. After opening it, you have a chance to get some good loot. I opened over 700 Boxes and no decent loot came. Only Potions, Poisons and some scraps. At least one epic should drop by now.

**How to reproduce:**
Loot a box and open it.

**How it should work:**
 Although it should take a bigger number of boxes, around 100-200 you should see at least one good item (even if not epic) And with 700+ one epic should have dropped already.

**Database links:**
https://www.wowhead.com/wotlk/item=43575/reinforced-junkbox#contains

**Comment by Afgann** [comment]
fixed
