### ISSUE TITLE
Kel'thuzad 25m - Guardian of Icecrown

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#919]
1 - Their default movement speed is very slow. You can kite them, they should be immune to slows as well.
2 - They deal insane amount of damage if you do not kite them, 1-2 shotting a tank (?)

A bit confused about the number 2 issue, it makes it seem like that kiting is required?

Forgive me if this is some type of custom buff that I am not aware of. On Classic and other servers, you tanked them as normal and they got a stacking damage buff the longer they lived.

**Comment by RadeghostWM** [comment]
This is working as intended, they should oneshot you, so they should be kited :P
