### ISSUE TITLE
Grobbulus poison doesnt dispell with Cloak of Shadows

### ISSUE THREAD

**Issue by bandini9** [gamefreedomgit/Frostmourne#920]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Grobbulus poison doesnt dispell with Cloak of Shadows

**How to reproduce:**
Start grob, get debuff, use CoS

**How it should work:**
Should be dispelled, doesnt get dispell

**Database links:**

**Comment by roperoperope** [comment]
its a 90% chance to dispell, not a 100% could've been just unlucky, try it once more

**Comment by Manpower99** [comment]
> its a 90% chance to dispell, not a 100% could've been just unlucky, try it once more

No, its a 90% chance to resist, the dispell is (or should be cuz bugged) guaranteed if you cast it after you use cloak of shadow

**Comment by WhitemaneIsa** [comment]
https://www.wowhead.com/wotlk/npc=15931/grobbulus#comments:id=495829
https://www.wowhead.com/wotlk/spell=28240/poison-cloud

**Comment by bandini9** [comment]
> https://www.wowhead.com/wotlk/npc=15931/grobbulus#comments:id=495829
> 
> It should be this one I assume? https://www.wowhead.com/wotlk/spell=28158/poison
> 
> This one gets properly removed: https://www.wowhead.com/wotlk/spell=28137/slime-stream

https://www.wowhead.com/wotlk/spell=28169/mutating-injection this is it

**Comment by UltraNix** [comment]
Fixed.
