### ISSUE TITLE
Rogue Talent Cheat Death

### ISSUE THREAD

**Issue by Stylesxz** [gamefreedomgit/Frostmourne#921]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The rogue talent Cheat Death doesn't work as intended. When the talent procs you're supposed to take 90% reduced damage for 3 seconds(its a buff), instead when it proc'd I got killed with the next attack which was an engineering pyro rocket which hit me for 1.9k taking the full damage from it and that shouldn't hit me for 1.9 cuz of the 90% dmg reduction provided from the buff.

**How to reproduce:**

**How it should work:**
You have a 100% chance that an attack which would otherwise kill you will instead reduce you to 10% of your maximum health. In addition, all damage taken will be reduced by up to 90% for 3 sec (modified by resilience). This effect cannot occur more than once per minute.

**Database links:**
https://www.wowhead.com/wotlk/spell=31230/cheat-death

**Comment by UltraNix** [comment]
@Stylesxz Do you have any screenshots when this happened?

**Comment by Stylesxz** [comment]
545 resil and no I don't have screenshots but it clearly doesn't work u can
just test it on the PTR

На пн, 17.06.2024 г. в 21:08 UltraNix ***@***.***> написа:

**Comment by WhitemaneIsa** [comment]
No further info/complaints, closing.
