### ISSUE TITLE
Sun-Lute Head Not dropping

### ISSUE THREAD

**Issue by JerichoCreed** [gamefreedomgit/Frostmourne#922]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Killed Kel'Thuzad and the Sun-Lute Head quest item did not drop, upon speaking to a GM they have told me that it should drop on all difficulties but it did not drop at all.
![Capture](https://github.com/gamefreedomgit/Frostmourne/assets/172870389/20991f22-83c4-4824-8dfb-75b758b23418)
these are the only items that dropped

**How to reproduce:**
killing the boss

**How it should work:**
Item Should drop from boss

**Database links:**

**Comment by RadeghostWM** [comment]
What difficulty that was? Did you have the quest?

**Comment by JerichoCreed** [comment]
This was 10 normal 
Yes i am on the quest
one of the GMs told me to make a bug report as it should drop from all difficulties

**Comment by JerichoCreed** [comment]
The quest description and the YouTube video don't specify it should be on a specific difficulty

**Comment by yeagerca** [comment]
Just killed Kel'Thuzad on 10 normal while on the quest "Headstock Heist" and it did not drop the quest item "Sun-Lute Head".
Character: Tomayto

**Comment by Vitezica** [comment]
Same issue. It was not specified which difficultly drops the quest item. And it did not drop in 10 man normal. Please either specify the difficulty or add it as loot table for 10 man.

**Comment by GM-Nightmaree** [comment]
it doesnt drop on 10 man normal , it only drops on 25 normal and ascended mode

**Comment by JerichoCreed** [comment]
> it doesnt drop on 10 man normal , it only drops on 25 normal and ascended mode

thank you for getting back to me on this issue there was no clarification on the quest or the video about the drop

is the drop rate 100%?

**Comment by WhitemaneIsa** [comment]
The drop rate is 100% on 10m Ascended and 25m, yes.
