### ISSUE TITLE
Multi-target spells delays

### ISSUE THREAD

**Issue by Tahtoh88** [gamefreedomgit/Frostmourne#923]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
There is a slight delay in multi target healing or damage. I've noticed this with blood boil and chain heal, i don't have such delay when playing in different wotlk private servers (chromie warmane). Confirmed it with other people and i've had this issue before nax launch.

The cast and the animations are properly working, but the healthbar and the battle text values are slightly delayed

**How to reproduce:**
Cast a multi target spell against enemies or to injured party members

**How it should work:**
There shouldn't be a delay in healing or spell value registration.

**Database links:**
https://www.wowhead.com/wotlk/spell=55459/chain-heal
https://www.wowhead.com/wotlk/spell=49941/blood-boil

**Comment by UltraNix** [comment]
It's called spell batching.

**Comment by Tahtoh88** [comment]
Spell batching is when you queue a spell while mid-cast of another spell, but this was different
funny enough i was going through dungeons to record it for better context but so far i can't seem to reproduce it anymore
