### ISSUE TITLE
Respawn timers during Bonus Weekend

### ISSUE THREAD

**Issue by Trixsss** [gamefreedomgit/Frostmourne#924]
Hello,

It seems that, in weekends, at the same time when the 50% experience is increased, the respawn timers from mobs, at least from the north-west area of Blasted lands, are increased by like 5x times. comparing to the weekdays. Tested and it happens every weekend.

Thank you.

**Comment by WhitemaneIsa** [comment]
@itsemmastone can you look at this?

**Comment by Godmatik** [comment]
Hyperspawns are often happening in low population areas. It is not related specifically to bonus weekend.

**Comment by Trixsss** [comment]
It is happening EXACTLY when weekend experience bonus occurs. I repeat, the
respawn timers are greatly increased while the weekend bonus is on, while
in weekdays, the respawn timers is fast and alright, as it was previously
implemented. Would you just please test it or is it somehing that you are
already aware of and only wish to try deny something clear and obvious?
Thank ou.

**Comment by WhitemaneIsa** [comment]
> Hyperspawns are often happening in low population areas. It is not related specifically to bonus weekend.

That is true, which is why I asked Gaga to check if it could potentially be related.

**Comment by UltraNix** [comment]
Weekend Bonus has nothing do to with respawn timers.
