### ISSUE TITLE
arena points disappeared

### ISSUE THREAD

**Issue by Dieman94** [gamefreedomgit/Frostmourne#926]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)
the day before yesterday I had 325 arena points, yesterday they disappeared, there were 25 left, I wrote to the moderators they said they knew about the problem and it was being solved, but today it also didn't work out and I sent ticks to in-game support again, I farmed them every day for 25, it's very insulting and unfair, please return the arena points

frostmorn player's nickname; Glad

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by RadeghostWM** [comment]
AP is always wiped when season starts
