### ISSUE TITLE
[Gjalerbron Attack Plans] - Quest starter item bug

### ISSUE THREAD

**Issue by johnatgh** [gamefreedomgit/Frostmourne#927]
**Description:**
The item [Gjalerbron Attack Plans] starts the quest "Gjalerbron Attack Plans". (horde side)
The problem with it is that it doesn't allow to start the quest giving an error: "You don't meet the requirements for that quest".
I've checked wowhead and there is no info about having to complete other quests before being able to start this one.

**How to reproduce:**
Acquire the item and try to use it.

**How it should work:**
It should start the quest "Gjalerbron Attack Plans".

**Database links:**
https://www.wowhead.com/wotlk/item=33347/gjalerbron-attack-plans
https://www.wowhead.com/wotlk/quest=11266/gjalerbron-attack-plans

**Comment by UltraNix** [comment]
https://www.wowhead.com/wotlk/quest=11261/the-conqueror-of-skorn is required.
