### ISSUE TITLE
Joining SOLOQ as prot paladin isnt possible

### ISSUE THREAD

**Issue by Frigex** [gamefreedomgit/Frostmourne#928]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Joining SOLOQ as a prot pala isn't working. Some people are spending hours of farming honor. Please find a solution.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by RadeghostWM** [comment]
Intended.

**Comment by UltraNix** [comment]
It's intended.
