### ISSUE TITLE
Culling of Strat - some lingering issues

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#929]
1. When zombies respawn, they do the level up sound but should not. It gets really loud when a lot of them respawn around same time.
2. Meathook and Salramm bosses should patrol around when they spawn, similar to the trash waves
3. None of the undead or dragonkin mobs in this dungeon drop money (silver) but they should
4. Mal'ganis uses his abilities far less often than before. He also always used carrion swarm on the tank rather than a random target.

**Comment by Piootrek** [comment]
1. Fixed
2. They already have a correct patrol paths
3. Fixed
4. Timers look good for me, Carrion Swarm fixed.
I will close this issue after the fix comes live.
