### ISSUE TITLE
[WARRIOR] Ravager proc crits aren't applying deep wounds

### ISSUE THREAD

**Issue by FedeMontanari** [gamefreedomgit/Frostmourne#93]
**Description:**
Ravager on-hit proc critical strikes are not applying Deep Wounds

This is **NOT** due to munching. Tested on a dummy that had no deep wounds debuff active

**How to reproduce:**
Get a crit from the axe on any target

**How it should work:**
Crits from the axe should apply deepwounds debuff since they are melee swings

**Database Links**
[Deep Wounds](https://www.wowhead.com/wotlk/spell=12867/deep-wounds)
[Ravager](https://www.wowhead.com/wotlk/item=7717/ravager)

**Comment by Karsenity** [comment]
I was able to recreate this bug as well

**Comment by Afgann** [comment]
fixed
