### ISSUE TITLE
[Broken] Maexxna - 10man Ascended - Web Wrapping too many

### ISSUE THREAD

**Issue by Iramtempus** [gamefreedomgit/Frostmourne#930]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Boss is webbing 4 people, should be 1 (10man) or at max 2 (25man)

**How to reproduce:**
Fight the boss

**How it should work:**

**Database links:**

**Comment by Godmatik** [comment]
25m amount is correct - 4 webs

**Comment by Iramtempus** [comment]
But this is in a 10man, should not grab 4.

**Comment by Godmatik** [comment]
I know but you said max at 25m is 2 webbed. Just making sure they don't change to that.

**Comment by Iramtempus** [comment]
> I know but you said max at 25m is 2 webbed. Just making sure they don't change to that.

Oh my bad, yeah sure.
