### ISSUE TITLE
Sunwell timewalk - felmyst

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#931]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
1.  Fog of corruption aoe is way bigger than it looks and should be. People are getting mind controlled while very much outside the visual effect on the ground. (ex: hugging tree while middle breath happened) - honestly this applies to pretty much every damaging aoe i've seen so far so probably make separate report for it as a general rule.

2. Demonic Vapor currently spawns skeletons constantly even when people are not stepping in the fog left behind from the laser. It keeps spawning into next phase sometimes.
It should spawn an initial wave of adds and only spawn more if people stand in the gas left behind.

3. If you stand near the tree side, raid aoe or something can pull the mobs from the gauntlet after felmyst while you are fighting it unintentionally (probably starfalls?) potentially wiping the raid.

**How to reproduce:**

**How it should work:**
https://www.wowhead.com/wotlk/npc=25038/felmyst#abilities;mode:n25
Demonic Vapor "Cast when airborne. Similar to nightbanebreath; deals nature damage and summons skeletons. Also leaves behind a trail that if stepped in applies a nature damage debuff and summons more skeletons."

**Database links:**

**Comment by Zipica** [comment]
@WhitemaneIsa I was told that its not tauntuble also and it should be becouse of tank swaping

**Comment by Afgann** [comment]
fixed
