### ISSUE TITLE
General ground aoe bug

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#934]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
There are multiple examples of ground aoe (perhaps all of them) that are doing damage/negative effect way outside of their visual zone of effect.

Some obvious examples I've encountered are: Felmyst mind control cloud, Naxxramas pipe before gluth ticks damage on people outside the pipe, Maiden of grief dark circle doing damage way outside the circle.

https://vimeo.com/959167387?share=copy
Sadly i had a tauren in this video(bigger hitbox), you can still observe the effect even like this; however, I've done this on live with female orc(one of the smaller hitboxes) and the issue is even more apparent.

This is pure speculation on my part, but I feel like fixes applied to player aoe leeway #133 are also applying to everything in a weird way and extending ranges? (non-player aoe, npc aoe spells, event generated aoe). Perhaps this might be the cause.

**How to reproduce:**
sit outside the dark circle on maiden of grief, still take damage
sit outside the breath of felmyst, still get mid controlled
sit outside the gluth pipe, still ticks damage

**How it should work:**
Npc/Non-player casted aoe should match their visual que.

**Database links:**

**Comment by RadeghostWM** [comment]
Prio. @UltraNix

**Comment by UltraNix** [comment]
These there spells described here are all different in terms of selecting targets - so it's not a generic problem and there is no generic solution. Must be fixed one by one.

**Comment by UltraNix** [comment]
Fixed.
