### ISSUE TITLE
Sunwell lockout

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#935]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I currently have IDs for every raid in this tier 10man and 25man. They all reset Wednesday 5:59am, except for Sunwell(timewalk) which resets Friday 6:05am.
I do not know if this is intentional, but I assume not since every raid in the tier should reset on the same day.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Manpower99** [comment]
This is probably related to that sunwell t6 was reset since its same ID as Timewalking sunwell on friday.
So whileit is likely intentional it should be changed back to resetting on Wednesday now.

**Comment by WhitemaneIsa** [comment]
This has already been changed. Of course all raids will reset at the same time on Wednesday.
