### ISSUE TITLE
titanium cannot be prospected

### ISSUE THREAD

**Issue by tekilamx** [gamefreedomgit/Frostmourne#937]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I already downloaded the game again, closed it and logged in again, I even relogged, even though it doesn't work, I deleted all my addoms. 
however maximum reach in jewelry my nickname is Vanevancleef

**How to reproduce:**

**How it should work:**

**Database links:** https://ibb.co/Y74PJ9T

**Comment by Godmatik** [comment]
Intended. 

You could not prospect it until patch 3.2
