### ISSUE TITLE
Savage Gladiator's Item No Stats - Reimport

### ISSUE THREAD

**Issue by RadeghostWM** [gamefreedomgit/Frostmourne#938]
Has no spell attached.

![image](https://github.com/gamefreedomgit/Frostmourne/assets/106831024/543056c8-2569-4a07-8150-1aff5c802432)

Should be https://www.wowhead.com/wotlk/item=42612/savage-gladiators-libram-of-justice

**Comment by RadeghostWM** [comment]
https://www.wowhead.com/wotlk/item=42296/savage-gladiators-pike

Missing AP on Whitemane 
![image](https://github.com/gamefreedomgit/Frostmourne/assets/106831024/7ce4d7ea-64b1-40a0-9696-5f0c1bd89294)

**Comment by RadeghostWM** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/106831024/a6de7171-cec2-4b24-bc85-bfa0b772e920)
Missing AP on Whitemane https://www.wowhead.com/wotlk/item=42445/savage-gladiators-longbow

**Comment by RadeghostWM** [comment]
https://www.wowhead.com/wotlk/item=42295/savage-gladiators-bonegrinder this is also missing AP.

Hm, maybe re-import Savage Glad from somewhere?

**Comment by RadeghostWM** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/106831024/ed4e8511-6064-44ab-b232-3d9af6026a11)
yeah importing savage gladiator's items is necessary :P

**Comment by Afgann** [comment]
fixed
