### ISSUE TITLE
Client crash loading into OS10 Heroic after client restart

### ISSUE THREAD

**Issue by yeagerca** [gamefreedomgit/Frostmourne#939]
**Description:**
Logging out inside of Obsidian Sanctum 10 Heroic then logging back in from a fully restarted WoW client causes the client to crash with the critical error seen below. The error is consistent across multiple characters, clients (Whitemane and other), and computers with and without addons, character equipment, and character auras. Notably however, if a character alone in the instance is removed from the group then logs back in before the one minute timer that removes them from the instance expires, they can load into the instance without an issue; an "instance is full" error from other characters attempting to enter indicates that they have loaded into the same instance ID.

The error type, exception code, and memory addresses were consistent for all crash replications.
Instruction "0x00524868" refers to the GetMapDifficultyInfoByMapIdAndDifficulty function. Source: https://wowdev.wiki/Client_Error_Analysis#0x00524868_read_0x00000008

Error message screenshot:
![OS10HC Critical Error](https://github.com/gamefreedomgit/Frostmourne/assets/93017663/6a58526b-c4e2-48f8-a4df-fbf2d5e90acd)
Error message transcription:
```
This application has encountered a critical error:
ERROR #132 (0x85100084) Fatal Exception
Program: C:\WoW 3.3.5a Whitemane Frostmourne\Wow.exe
Exception: 0xC0000005 (ACCESS_VIOLATION) at 0023:00524868
The instruction at "0x00524868" referenced memory at "0x00000018".
The memory could not be "read".
Press OK to terminate the application.
```

**How to reproduce:**
Enter Obsidian Sanctum with difficulty set to 10 Heroic. Close the WoW client and log back in to the same character. The client will crash when the loading bar is full.
Remove the character from the group remotely to be safely teleported to the entrance.

**How it should work:**
Fix the function that handles non-existent heroic difficulties that is being used to create the ascended difficulty lockouts.

**Comment by Afgann** [comment]
fixed
