### ISSUE TITLE
Paladin Auras working but different logic than they should

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#94]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Currently all Paladin auras work, however the issue is in the logic which they apply/get occupied, an example would be
Pala 1 : Conc Aura
Pala 2 : Devo Aura
if Pala 2 would need to swap to conc aura to aura mastery or any othe reason he would need to wait for Pala 1 to drop the aura first but thats incorrect. each Paladin should be allowed any aura even if its already applied by someone else with ofcourse the one being popped by Aura Mastery being prioritized if two+ auras are applied by different Paladins with of course proximity/phasing/aura mastery being the factor on which one gets applied

**How to reproduce:**
Have two Paladins in the same party/raid group and try to use the same aura and it will look like its occupied.

**How it should work:**
Should instead work blizzlike where the Auras are personal and then apply to other people based on proximity/phasing and then aura mastery.
 proof from both og wrath and wrath classic and even tbc and cata since aura logic didnt change till much later into the expansions
wotlk classic : https://www.youtube.com/watch?v=KnIhO_ImJuw 
notice here how multiple people are holding shadow aura at 03:39
og tbc: https://www.youtube.com/watch?v=PXpjYHkW4gc
notice how in hobbs' video he has both retri and devo aura but on his bars only devo is occupied? because its personal and he applied it to himself and people around him.
og wrath :https://youtu.be/WFSM8sSXmwA?si=wpIY72lc3hyhjGu_
notice the fire/devo/retri but only devo being occupied on his aura bar?
og cata : https://youtu.be/P6-WKncXEYI?si=LcEodsevoi_okIUh
and last one from og wrath : https://youtu.be/SGYVHEUgLfo?si=axyZuZFxShpl86VP&t=296
if need be can provide more videos from both wotlk classic or original wrath.
**Database links:**
https://wotlk-twinhead.twinstar.cz/?spell=48942

**Comment by Manpower99** [comment]
Since this seems to remain under the radar despite being a very important fix for paladins. its exactly how paladin auras worked originally and blizzlike both in Original game and classic. Paladin Auras stack logic is based on personal aura as the videos provided prove with the buff obtained by others working as stronger is applied based on proximity/phasing for who gets what and while two people have the same aura the one with Aura Mastery should have the priority.

From wow-pedia:
"Auras do not stack. If two paladins in a party are using the same aura, only the greater of the two will be in effect, the other is effectively wasted."

**Simple Explanation of the issue currently on your realm :**
1) Player-A is paladin with fire resistance in the raid.
2) Player-B is random player near Player-A and is receiving fire resistance buff from Player-A.
3) Player-C is paladin with fire resistance outside of raid -> gets summoned into raid -> nobody in raid receives his fire resistance as the value is equal with Player-A.
4) Player-C uses Aura Mastery, only he is receiving the x2 effect on fire resistance, everybody else like Player-B still have the default value from Player-A. Since Player-C's value went up, everybody should be receiving Player-C's double value.

The "Fix" is to make Paladin Auras personal on your stance/aura bar and the benefit of nearby players would be based of a priority system like this : Strongest Aura is applied ( talents and aura mastery ) > proximity and phasing ( positioning based ) 

Considering this is a boosted realm and the importance of such a raid cooldown like Aura Mastery it would be great if this is fixed before launch as it will impact every raiding guild significantly.
this affects speed and execution + any errors in pugs or miscommuncation can cause more than 11% more damage taken by raid wide damage or effects such as infest, ignis knockup and more.

If the videos in the report are not enough proof of this, i will grab video evidence from wow classic to prove how it should work. it was fixed to work like this on warmane during frostmourne's 3 TOGC time and can also provide proof from there.

**Comment by UltraNix** [comment]
Fixed.
