### ISSUE TITLE
[Suggestion] Items to add to PoW vendors

### ISSUE THREAD

**Issue by Murglr** [gamefreedomgit/Frostmourne#941]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Items that could be added to path of war starter vendors (below 200 ilvl)

**Database links:**
https://www.wowhead.com/wotlk/item=37111/soul-preserver
https://www.wowhead.com/wotlk/item=43836/thorny-rose-brooch
https://www.wowhead.com/wotlk/item=44014/fezziks-pocketwatch
https://www.wowhead.com/wotlk/item=37064/vestige-of-haldor

**Comment by Melh232323** [comment]
https://www.wowhead.com/wotlk/item=37873/mark-of-the-war-prisoner
https://www.wowhead.com/wotlk/item=38361/venture-co-lightning-rod

**Comment by WhitemaneIsa** [comment]
Please post suggestions in the suggestion area, not on the bugtracker. 

https://ptb.discord.com/channels/1040715551531618365/1163874902617620612
