### ISSUE TITLE
Obsidian Sanctum 25 no Currency (All bosses)

### ISSUE THREAD

**Issue by Daroey** [gamefreedomgit/Frostmourne#942]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
All bosses didn't drop any emblem of valor and they should do

**How to reproduce:**

**How it should work:**
The 3 small drake should drop at least 1 emblem, Sartharion should drop 2 emblem of valor

**Database links:**
https://www.wowhead.com/wotlk/item=40753/emblem-of-valor

**Comment by WhitemaneIsa** [comment]
https://www.wowhead.com/wotlk/npc=30451/shadron#drop-currency;mode:n10
https://www.wowhead.com/wotlk/npc=30452/tenebron#drop-currency;mode:n10
https://www.wowhead.com/wotlk/npc=30449/vesperon#drop-currency;mode:n10

**Comment by Daroey** [comment]
Yes, It's one per drake in normal mode (3 drake down) not the 3D

**Comment by WhitemaneIsa** [comment]
> Yes, It's one per drake in normal mode (3 drake down) not the 3D version.

Don't mind my commentary, I'm just adding links etc. to make it a little quicker for our Devs to look into :)

**Comment by Daroey** [comment]
Ah xD yep my bad ! thx !

**Comment by Afgann** [comment]
fixed
