### ISSUE TITLE
CB on arena (rogue)

### ISSUE THREAD

**Issue by For3v3** [gamefreedomgit/Frostmourne#943]
Description: issue with CB  (cold blood)

How to reproduce: I cant use CB on arena i pressure the button 10-15 time, and mb 1 time they will activated. But nah, seems not usable.

**Comment by UltraNix** [comment]
@For3v3 Let me know if it's fixed or still bugged.

**Comment by For3v3** [comment]
@UltraNix  still bugged

**Comment by UltraNix** [comment]
@For3v3 I will need some record of this bug.

**Comment by For3v3** [comment]
@UltraNix now its work, left only visual bug

**Comment by UltraNix** [comment]
@For3v3 That's what I want to be recorded.

**Comment by For3v3** [comment]
Oki 5 min

**Comment by For3v3** [comment]
https://youtu.be/wu8igaRl1-w Sorry for the delay

**Comment by UltraNix** [comment]
@For3v3 It's a macro there?

**Comment by UltraNix** [comment]
Fixed.
