### ISSUE TITLE
Flight path

### ISSUE THREAD

**Issue by Xennpai** [gamefreedomgit/Frostmourne#945]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I am unable to chose a flight path to The Shadow Vault & Dun Niffelem
And yes I have completed the quest chains to become Friendly with the factions (Knights of The Ebon Blade & Sons of Hodir)
**How to reproduce:**
Go to a flightpath in Northrend and see that it's unable to be selected (non-existent)

**How it should work:**
Should be a clickable flightpath after you finish the quest chains to become Neutral/Friendly

**Database links:**

**Comment by Xennpai** [comment]
I saw some people are having it available, I'm just wondering how do I fix it for myself?

**Comment by UltraNix** [comment]
@Xennpai Are you able to fly there (e.g. to The Shadow Vault) and see if the flight master is visible to you?

**Comment by Xennpai** [comment]
It is visible

**Comment by UltraNix** [comment]
So - you can fly from there to e.g. Dalaran.
But you cannot fly there e.g. from Dalaran, right?
