### ISSUE TITLE
Oculus Issues

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#946]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
**Vehicle Drake**'s itemlevel scaling seem to be either nonexistant or very weak.
they are missing an [ability ](https://wowclassicdb.com/wotlk/spell/53389)that helps newer players with the dungeon as it can be a very confusing with the vehicles.

**Varos Cloudstrider's Beam** :
Currently seems to be moving very fast in comparison to how it should be based on this [video](https://www.youtube.com/watch?v=yPjb_PQ_sfk)
Beam should dissappear a second after boss dies.

**Mage-Lord Urom** Should not be Damagable/Killable while casting [Empowered Arcane Explosion](https://www.wowhead.com/wotlk/spell=51110/empowered-arcane-explosion#used-by-npc)
_Damage seems inaccurately low?_
Normal Version should cast it for 8seconds and damage taken should be 9000 
and on Heroic Version should be 13500 and cast time should be 6seconds

**Planar Anomaly** Nameplates are not visible but should be, as it helps with their visibility.

[Conjurer's](https://wowpedia.fandom.com/wiki/Ring-Lord_Conjurer)
did not ever summon [snowflake](https://www.wowhead.com/wotlk/npc=28153/snowflake#comments;mode:heroic)
over 10+ clears since server launch did not see this being summoned once even with low dps groups.

**Centrifuge Constructs** are not working at all. [They](https://www.wowhead.com/wotlk/npc=27641/centrifuge-construct) are missing some abilities that normally would require stuns/slows or kiting them unless you are overgeared.
On each Hit on [Normal ](https://www.wowhead.com/wotlk/spell=50045/empowering-blows)Difficulty should increase damage by 400 and [Heroic ](https://www.wowhead.com/wotlk/spell=59214/empowering-blows)Difficulty by 800, both hidden buffs should stack up to a max of 25.
In Addition to that, each Construct should buff other nearby Constructs by 50% more damage with this [passive visible aura](https://www.wowhead.com/wotlk/spell=50088/energy-link). You can see the buff in this [WotLK Classic Video ](https://youtu.be/PBQ0e1mLcoA?si=PP0DmpbuKmgDjUUN&t=561)
Their movement speed should also be slow as they could be kited as part of the difficulty which is noticable in the same video on multiple occasions of fighting the same NPCs.

Consider adding [Cache ](https://wowpedia.fandom.com/wiki/Cache_of_the_Ley-Guardian)at the end of the RDF HC.
Reasoning it was added because players have avoided the dungeon for all of wrath, og and classic and private servers. it is simply not a very well liked instance and an awkward vehicle combat dungeon that tends to be annoying and unrewarding. 
A possibility of a mount and some gems/emblems will atleast add the reward to actually finishing it.
Releasing it only at 3.3 while it drops obsolete rare gems nullifies the reason of its existance, as it shouldn't be a problem since it can only be obtained through RDF which cannot be sniped anymore due to ignoring of ID and adds a reason not to instantly leave.
updating it with the catch up 2 emblems every new tier would be a great step Like this :
3.0 Heroism
3.1 Valor
3.2 Conquest
3.3 Triumph

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by yeagerca** [comment]
Mage-Lord Urom's encounters have an additional bug:
Damage over time effects placed on Urom while he is summoning mobs can carry over to the next platform, causing him to start the next event before players are in position.
- If this is done where the next part is another summoning, the summoned adds will reset and players can continue after combat resets.
- If this is done where the next part of the encounter is the boss fight, it will start the boss fight but when it resets all three summoning events are reset must be completed again.

**Comment by Manpower99** [comment]
> Mage-Lord Urom's encounters have an additional bug: Damage over time effects placed on Urom while he is summoning mobs can carry over to the next platform, causing him to start the next event before players are in position.
> 
> * If this is done where the next part is another summoning, the summoned adds will reset and players can continue after combat resets.
> * If this is done where the next part of the encounter is the boss fight, it will start the boss fight but when it resets all three summoning events are reset must be completed again.

I did not encounter this but i will intentionally put debuffs next time im there to test this.

**Comment by UltraNix** [comment]
```
Vehicle Drake's itemlevel scaling seem to be either nonexistant or very weak.
```
About this one - it's 1 point above 170 ilvl. So eg. if you are 200 ivl, then drake's hp and damage is increased by 30%.

**Comment by UltraNix** [comment]
Fixed.

**Comment by Manpower99** [comment]
Centrifuge Constructs still have few issues
they constantly activate/deactivate their energy link, and energy link is capped at 1 on each construct
Each construct alive should buff the other two by 1 instance of energy link
So if all 3 are alive then every construct would be buffed by the other 2. currently only one buff is visible
their movement speed seems to be fast still in comparison to video footage.
unsure if empowering blows is stacking or not but it should.
