### ISSUE TITLE
Fear spell on Arena and PvP (Spellname - Psychic Scream|| Class-priest)

### ISSUE THREAD

**Issue by Worstfmever** [gamefreedomgit/Frostmourne#947]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)
Spellname - Psychic Scream|| Class-priest
https://www.wowhead.com/wotlk/ru/spell=27610/%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9-%D0%BA%D1%80%D0%B8%D0%BA

**Description:**
When my partner (Priest) presses the ability "Psychic Scream"
The enemy takes flight, but can use any ability, be it Dispel/Mortal Strike, Fear, Blink, etc.
This is not how it should work! When using fear, the enemy should flee and be unable to use any of their abilities.

Here is an example of this bug, I was playing arena and streaming, DC/HUNT came up against me.  At 27:36 my priest uses Psychic Scream on the enemy priest, but he stands and casts Massdispel.
The second moment, at 33:24, my partner presses the Psychic Scream ability on the enemy priest, and he, having a fear debuff, casts Vampiric Touch. and This is just a small number of proofs that I have, if you watch the entire stream, there will be a lot of them.

Links for Stream:
https://www.twitch.tv/videos/2173646001

**How to reproduce:**
Use abillity Psychic Scream (Priest)

**How it should work:**
During a Psychic Scream ability or loss of character control, the player should not be able to use their abilities.

**Database links:**
https://www.wowhead.com/wotlk/ru/spell=27610/%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9-%D0%BA%D1%80%D0%B8%D0%BA

**Comment by slicplaya** [comment]
I mean, there's a crap ton of batching issues here, but that Mass Dispel with a full 3 sec left on fear is just over the top. Casts mass dispel to remove fear. xD

**Comment by UltraNix** [comment]
It's not related to spell batching.

**Comment by Worstfmever** [comment]
UPD: 
The error only occurs if my priest uses fear on an enemy that is in a sheep

**Comment by UltraNix** [comment]
Fixed.
