### ISSUE TITLE
Tricks of the Trade not activating with Range weapons

### ISSUE THREAD

**Issue by bandini9** [gamefreedomgit/Frostmourne#948]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Tricks of the Trade should activate with any damage as it says on the tooltip "The current party or raid member becomes the target of your Tricks of the Trade. The threat caused by your next damaging attack and all actions taken for 6 sec afterwards will be transferred to the target" but it doesnt proc from range weapon attack. I am speaking about Shoot/Throw

**How to reproduce:**
Tricks party/raid member, use Shoot/Throw

**How it should work:**
Tricks should activate and transfer threat/boost dmg of the target

**Database links:**
https://www.wowhead.com/wotlk/spell=2764/throw
https://www.wowhead.com/wotlk/spell=3018/shoot
https://www.wowhead.com/wotlk/spell=57934/tricks-of-the-trade

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/164e38c6-b760-485a-8866-b768c2a79515)
As you can see, I used throw and the Tricks of the Trade procced on my party member. Alsob, you can see my current threat which is 0 (despit using throw).

**Comment by bandini9** [comment]
![WoWScrnShot_061724_180216](https://github.com/gamefreedomgit/Frostmourne/assets/40371383/ee606484-33fa-4ba7-a9fe-57e91dc66fda)
![WoWScrnShot_061724_180249](https://github.com/gamefreedomgit/Frostmourne/assets/40371383/c071c165-788a-422c-8642-31d10584368b)
Okay as you can see, I used shoot and the Tricks of the Trade didn't procced on my party member.

**Comment by UltraNix** [comment]
Yep - it does proc from throw, does not from shoot.

**Comment by UltraNix** [comment]
Fixed.
