### ISSUE TITLE
CDs doesnt reset (only as Rogue maybe?) after a duel at Dalaran sewers

### ISSUE THREAD

**Issue by bandini9** [gamefreedomgit/Frostmourne#949]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Cold Blood, CoS, Evasion doesn't reset after a duell at Dalaran sewers

**How to reproduce:**
Duel then Burn CDs end duel before your CDs comes up

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
CDs are reset at the beggining of duel.
