### ISSUE TITLE
Teleport Shatrath

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#95]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
it is currently placed in general tab of spellbook instead of arcane
might even be different spell id? twinstar database claims different spell id than the one given ingame.
ingame spell id:33690
i believe it's an auto learn bug
**How to reproduce:**

**How it should work:**

**Database links:**
https://wotlk-twinhead.twinstar.cz/?spell=35715

**Comment by Afgann** [comment]
fixed
