### ISSUE TITLE
Brutallus' Corpse Duration

### ISSUE THREAD

**Issue by Aeradel** [gamefreedomgit/Frostmourne#950]
The corpse stays for too long and either needs to shrink, move, or despawn within a few minutes when dead.

**Comment by Manpower99** [comment]
Please do not forget waiting for it to be looted and then despawning it, perhaps 5 minutes after being looted.
better solution to prevent these issues is to shrink the corpse by about 60% so it is there just not massive enough to visually block mechanics from visiblity.

**Comment by Afgann** [comment]
fixed
