### ISSUE TITLE
Ulduar - CD resets

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#951]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Currently cooldown resets on boss kill/wipe are not applied to Ulduar bosses. Tested on the 10man version.

**Comment by Afgann** [comment]
fixed

**Comment by Afgann** [comment]
fixed
