### ISSUE TITLE
Ulduar - Algalon pets falling through floor

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#952]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
In Algalon room, pets are falling down through the translucent floor. They might come back after a while, but they shouldn't fall in the first place.

**Comment by RadeghostWM** [comment]
hahaha @Afgann you need to make gob pathfinding before ToC i guess xD

**Comment by BalanCV** [comment]
Some people said summoning stone also falls through ground on the arena :)

**Comment by Manpower99** [comment]
> Some people said summoning stone also falls through ground on the arena :)

Yes the summoning stone fell down under the platform lmao.

**Comment by Afgann** [comment]
fixed
