### ISSUE TITLE
Ulduar - XT Deconstructor adds

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#954]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
The small adds that are spawned from the piles on the corners of the room are stuck in place. 
https://wowpedia.fandom.com/wiki/XS-013_Scrapbot

**How to reproduce:**
Start XT encounter normally, wait until add spawn phase

**How it should work:**
They should move along the bomb bot towards the boss. The bomb bot is moving properly.

**Database links:**

**Comment by Afgann** [comment]
fixed

**Comment by Afgann** [comment]
fixed
