### ISSUE TITLE
Ulduar - Flame Leviathan & Related

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#955]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
1. Vehicles start with 0 energy resources - it should start with full.

2. Too low amount of pyrite in air AND it takes too long to respawn after being blown down to the ground.

3. Demolishes vehicle ability does not knock back.

4. Going out of bounds/wiping makes flame leviathan slowly go back to his position instead of phasing out and reappearing after a minute in his initial position.

**Comment by Afgann** [comment]
fixed
