### ISSUE TITLE
[RESTO SHAMAN] Tidal Waves partially bugged

### ISSUE THREAD

**Issue by piti2137** [gamefreedomgit/Frostmourne#956]
**Description:** Tidal Waves talent isn't working properly when procced by Chain Heal.
While casting CH you already smash next button - Healing Wave or Lesser Healing Wave - the buff seems to be "late" and isn't applied when you instantly queue HW, you still get regular cast time HW.
LHW will be surely the same, but its way easier to notice lack of 30% reduced cast time than doing **2137** casts to test for lack of crit chance buff on LHW.
The stack isn't consumed, but the buff isn't applied either, as i said Tidal Waves buff "seems to be late".
If you wait like 0.1s or so for "server to refresh" - then TW buff is working as intended.

**How to reproduce:** Have Tidal Waves talent, start casting Chain Heal, then already spam Healing Wave as next button, you will see regular cast time of HW and the stack of TW won't be consumed.

**How it should work:** When you cast Chain Heal and then instantly (spam next button) Healing Wave, HW cast time should be reduced by the value 30% (rank 5), same applies to Lesser Healing Wave and its crit strike chance.

**Database links:** https://www.wowhead.com/wotlk/spell=51566/tidal-waves

**Comment by UltraNix** [comment]
The thing here is spell batching - you have delayed proc and spell mod from talent applied.

**Comment by holyshryt** [comment]
If you read the comments to the link you posted with your bug report, you’ll see it was also an “issue” back in 2008. You’re casting your next heal before buff is even active, so it will not consume the tidal waves. I tested it another server just to see and got the same results.
