### ISSUE TITLE
drawf shaman cant speak launguage name somethingnew

### ISSUE THREAD

**Issue by hashimo08** [gamefreedomgit/Frostmourne#959]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
wont let me speak says cannot speak this launguage.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/0c988652-5e21-4887-ac4b-2160fef2e8e0)
What chat was that? Maybe you were in crossfactioned dungeon/party/battleground? Any error on your screen?

**Comment by WhitemaneIsa** [comment]
As there has been no further info/complaints, this will be closed for now.
