### ISSUE TITLE
Retribution Talent Sanctified Retribution 

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#96]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Talent for Retribution Paladin Sanctified Retribution applies to allies but not yourself.

**How to reproduce:**
Talent it, notice it does not give 3% edamage to yourself as the BM/Arcane Talent does, but it still applies to allies

**How it should work:**
Should be to yourself as well as your allies.

**Database links:**
https://wotlk-twinhead.twinstar.cz/?spell=31869

**Comment by UltraNix** [comment]
With no Retri Aura:
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/22ea13d8-5661-4491-8377-02f0990ada0f)

With Retri Aura:
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/9d50cbca-c0a5-48cc-a555-347a90d6b2f9)

Works okay.
