### ISSUE TITLE
Bugged mobs in storm peaks

### ISSUE THREAD

**Issue by Chrumchie** [gamefreedomgit/Frostmourne#960]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Infesting Jormungar in the cave at 38 50 are bugged, you cant click them namepalte isnt visible and when you aggro them by walking next to them they wander around and dont have an attack animation

**How to reproduce:**
walk next to them

**How it should work:**
Like normal aggressive mobs

**Database links:**
https://www.wowhead.com/wotlk/npc=30148/infesting-jormungar

**Comment by WhitemaneIsa** [comment]
this only affects Jormungar's that are currently burrowed

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
