### ISSUE TITLE
Sarth Breath

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#961]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Sartharion seeems to still snapshot first location to breathe on, making it still dodgable.

**How to reproduce:**
reported before but seems to still be bugged

**How it should work:**
Should follow the main target so breath is not dodgable.

**Database links:**

**Comment by Afgann** [comment]
fixed
