### ISSUE TITLE
Thaddius + Skadi

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#962]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Upon Becoming targetable these 2 bosses should reset threat, reported it before and are labeled as fixed but they still seem to prioritize healers as soon as they're in.
Skadi the Ruthless
Thaddius

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
@Manpower99 Still happens?

**Comment by Godmatik** [comment]
Still happens for Thaddius. Not sure about Skadi

**Comment by UltraNix** [comment]
The aggro should be reset already - can be tested with e.g. Omen addon.
After that - it's should be just random attack from the boss.

**Comment by UltraNix** [comment]
@Godmatik Please - restest it.

**Comment by Godmatik** [comment]
Thaddius is fixed now
