### ISSUE TITLE
Shadowfang Keep - Guy not opening door

### ISSUE THREAD

**Issue by Xarlillos** [gamefreedomgit/Frostmourne#963]
When done with the first part, asked the guy who opens the door, he does the animation, goes to the door and casts the spell, but the door wont open. Please fix, thanks:)

**Comment by Xarlillos** [comment]
PD: happened 2 times already, not sure but may be only with alliance npc.

**Comment by Afgann** [comment]
fixed

**Comment by WhitemaneChronus** [comment]
We have another issue in SFK recently, the door after [Fenrus the Devourer](https://www.wowhead.com/wotlk/npc=4274/fenrus-the-devourer) doesnt open after defeating the boss. 

While i could not replicate this issue myself (even when i skipped all previous bosses, killing this one opened the door) we are receiving a lot of tickets in this regard.
