### ISSUE TITLE
Improved Tracking

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#964]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
While tracking humanoid the damage bonus seems to not affect beasts which leads me to believe this is working incorrectly, while the tooltip can be misunderstood the way it should work is exactly how it works on classic/warmane.
https://www.wowhead.com/wotlk/spell=52788/improved-tracking#comments
2nd comment.
**How to reproduce:**

**How it should work:**
There should be no need for specific tracking mode: Unlike in previous versions, you don’t need to switch to a specific tracking mode to receive the bonus. Simply having one of your tracking abilities active will grant the 5% damage increase to all of the specified types.

**Database links:**

**Comment by UltraNix** [comment]
Fast test against beasts.
Without tracking:
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/35c2db9a-2760-444f-81f4-c454fb8c5f05)
50 normal hits * 54 avg = 2700

With humanoids tracking:
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/6ef58b4a-407b-45bd-a58a-2cda8bb8b486)
50 normal hits * 57 avg = 2850
2850 / 2700 = 1,05
No bug here.

**Comment by Manpower99** [comment]
The bug report is about that the talent should work if you are tracking Anything it should work against anything regardless if you are specifically tracking that type or not though, the talent seems to work when specifically Tracking beasts and damaging beasts, but if you are tracking humanoids and damaging beasts the damage is not increased but it should, because the talent tooltip can be misleading/misunderstood. i'll conduct more tests on my own as soon as i can.

**Comment by UltraNix** [comment]
I just did what you said.
Tracking humanoids and damaging beasts - you can clearly see increased damage.

**Comment by Manpower99** [comment]
> I just did what you said. Tracking humanoids and damaging beasts - you can clearly see increased damage. And yes - you must have activated tracking aura (Improved Tracking talents is just spellmod that affects tracking auras).
> 
> I see nothing misleading in tooltip.
> 
> ```
> While tracking Beasts, Demons, Dragonkin, Elementals, Giants, Humanoids and Undead
> ```
> 
> If you want increased damage, you must have tracking aura on you. But damage is increased regardless your tracking type. You are tracking humanoids - you have increased damage against beasts which you can see on my screenshots.

You're right then, my tests were done on wolves below dalaran which were inconsistent perhaps. thank you for the confirmation!
