### ISSUE TITLE
Reputation bonus from Ancestral Wisdom

### ISSUE THREAD

**Issue by Acurtis03** [gamefreedomgit/Frostmourne#968]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
On the website it states that ancestral wisdom increases your reputation gains by 15% per each level 80 character on your account. It seems its not accurately calculating the reputation gains currently. 
I Currently have 7 level 80 characters, so now leveling my 8th char i have turned in a quest which at a base level is supposed to reward 250 reputation, well 15% of 250 is 37.5, if you increase it by 15% of the base gain 7 times for each character i have...
( 7 x 37.5 = 262.5 )....... 250 + 262.5 = 512.5 reputation is what this quest should have gave me on a weekday, but when it only rewarded me 468.5 rep... even more so is that this actually happened during the 50% increase rep gains, so if we do ( 512.5 x .50 = 256.25 )......
so we have the extra 50%... 256.25 + 512.5 = 768.75....... so it would be 768/769 REP as a reward for that quest if we are rounding. 

468 rep for the quest vs 768 rep for the quest is a big difference, perhaps i'm doing the calculations wrong? Would appreciate input / resposne.

**How to reproduce:**
get a few level 80's for ancestral wisdom, then on a fresh character turn in some quests and check the reputation you recieve vs what you should recieve via the calculation of +15% rep per each lvl 80 char you have.

**How it should work:**
all reputation gains should be properly increased by 15% per each lvl 80 character as stated on the realm website.

**Database links:**

here's the quest i turned in, for reference.
https://www.wowhead.com/wotlk/quest=9280/replenishing-the-healing-crystals

**Comment by Acurtis03** [comment]
side note, ancestral wisdom exp modifier had to be fixed and adjusted on the PTR a couple months back because the multipliers were not accurate, i believe something similar is happening here with reputation where the gains are not being calculated correctly..

**Comment by UltraNix** [comment]
Fixed.

**Comment by UltraNix** [comment]
Fixed.
