### ISSUE TITLE
Pendant of the Agate & Shape Shifting

### ISSUE THREAD

**Issue by 4rt-Net** [gamefreedomgit/Frostmourne#969]
**Description:**
The Pendant of the Agate Shield (jewelcrafting amulet)'s buff drops off when entering a different form. 
The item: https://www.wowhead.com/wotlk/item=20970/design-pendant-of-the-agate-shield

When the buff is activated using the item's active ability it works as intended, however entering something like cat form it will auto remove the buff. 

**How to reproduce:**
Video Example of the issue: 
https://youtu.be/eGS-UgIxqXg

Have not tested with alternative forms and/or character changing effects, however, appears as if the active ability is not taken into account when the default form is lost.

**Comment by UltraNix** [comment]
Fixed.
