### ISSUE TITLE
Blood Frenzy Arms Warrior

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#97]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Currently if you crit and apply deep wounds before applying rend you apply blood frenzy which is fine, however after deep wounds fades while rend is still up you lose blood frenzy even though rend should also be one of the dots that apply the debuff.
https://imgur.com/bVPgvCx
**How to reproduce:**
talent blood frenzy>
crit to apply deep wounds>
apply rend>
stop critting so deep wounds fall off while rend is still up and blood frenzy will be removed
**How it should work:**
Aslong as either debuffs are up on the target Blood Frenzy should not be removed

**Database links:**
https://wotlk-twinhead.twinstar.cz/?spell=29859

**Comment by Manpower99** [comment]
to note this issue is not consistent. it happens more often than it doesn't but iam uncertain of the full reason behind it. but after more than 20 tries on target dummies the issue still happens.

**Comment by Afgann** [comment]
fixed
