### ISSUE TITLE
RHC popping for players with ID

### ISSUE THREAD

**Issue by bandini9** [gamefreedomgit/Frostmourne#970]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
I q'd for RHC and I got The Oculus but our tank did it before, which is a Whitemane feature, there's no RHC lockout but our Tank already had ID and we were not able to see each other therefore kicked each other to leave dungeon at the end

**How to reproduce:**
No idea? That never happened before

**How it should work:**
Eventhough players have ID from earlier in the day, they should be in the same ID as this is whitemane feature

![WoWScrnShot_061724_175220](https://github.com/gamefreedomgit/Frostmourne/assets/40371383/222798ea-e657-4ca8-8016-cfed01c3a89f)
![WoWScrnShot_061724_175232](https://github.com/gamefreedomgit/Frostmourne/assets/40371383/cf9bee5c-cb33-4a42-81ba-fce62546ac51)

**Database links:**

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/903

**Comment by WhitemaneIsa** [comment]
@UltraNix restart hasn't happened yet so I don't know if your fix is applied yet, It just happened again on a Culling of Stratholme group.

**Comment by UltraNix** [comment]
@WhitemaneIsa Should be applied now.

**Comment by WhitemaneIsa** [comment]
Haven't heard any new reports about it since, I'll close. <3
