### ISSUE TITLE
Whitemane+ instant flight paths not always working

### ISSUE THREAD

**Issue by lorxlocked** [gamefreedomgit/Frostmourne#972]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Sometimes the whitemane plus perks arent working and the instant flightpaths dont work and the no repair on gear doesnt function either

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by WhitemaneIsa** [comment]
This is caused by the general Whitemane+ perks not being active. Please type .premium in chat to see if your perks are still active and update us if this also occurs while they are showing as active.

To fix them not loading properly sometimes, you can simply restart your game.

**Comment by WhitemaneIsa** [comment]
As there has been no further info/complaints, this will be closed for now.
