### ISSUE TITLE
[Quest: 13043] The Sum Is Greater than the Parts

### ISSUE THREAD

**Issue by davmag91** [gamefreedomgit/Frostmourne#974]
**Description:**
When you mount Nergeld you should start an gauntlet with multiple waves until Dr.Terrible shows up. Currently we mount up Nergeld and nothing happens.

**How to reproduce:**
Accept quest, go to the npc to start the gauntlent and verify nothing happens.

**How it should work:**
When you mount Nergeld you should start an gauntlet with multiple waves until Dr.Terrible shows up.

**Database links:**
https://www.wowhead.com/wotlk/quest=13043/the-sum-is-greater-than-the-parts

**Comment by WhitemaneIsa** [comment]
https://github.com/gamefreedomgit/Frostmourne/issues/740
