### ISSUE TITLE
[Achievement] Dehydration

### ISSUE THREAD

**Issue by davmag91** [gamefreedomgit/Frostmourne#976]
Ichoron adds run too fast to the boss making this achievement almost impossible.

**Comment by Godmatik** [comment]
The issue also is that they should briefly pause when they are formed before they start moving

**Comment by bandini9** [comment]
You just need to time crystals in VH, could be too fast but it shouldn't cause issue

**Comment by disruption01** [comment]
> You just need to time crystals in VH, could be too fast but it shouldn't cause issue

they're too fast, even if you click on crystals you don't have time. on wotlk classic they were way slower.

**Comment by roperoperope** [comment]
i think they also spawn too close

**Comment by Afgann** [comment]
fixed
