### ISSUE TITLE
Orc's passive racial [Axe Specialization] doesnt work

### ISSUE THREAD

**Issue by Ljepoja** [gamefreedomgit/Frostmourne#977]
https://www.wowhead.com/wotlk/spell=20574/axe-specialization

Playing orc warrior, discovered this bug when i equiped mace that should've gave me a minor expetise boost, but gave me a lot of expertise. Expertise is showing same numbers with an axe and without anything equiped. Have'nt tested if this is only a visual bug or if it actually doesnt give expertise. Could be only for this axe, but dont have a spare one to test it.

![WoWScrnShot_061824_010707](https://github.com/gamefreedomgit/Frostmourne/assets/74017238/ff86b90c-b2bb-4666-a6a0-22f76911a2f9)

![WoWScrnShot_061824_010715](https://github.com/gamefreedomgit/Frostmourne/assets/74017238/89d0741c-b46c-4950-9252-1cb381f8dc7b)
![WoWScrnShot_061824_010722](https://github.com/gamefreedomgit/Frostmourne/assets/74017238/8876d28d-41c7-46ea-9cb1-6bdbd3a97dee)
![WoWScrnShot_061824_011127](https://github.com/gamefreedomgit/Frostmourne/assets/74017238/dd0d7628-8a9b-4965-af1c-ec4a673b946d)

**Comment by Godmatik** [comment]
There is a difference between expertise and expertise rating.

It's giving 5 expertise, which is equal to 1.25% reduction in change to dodge and parry.

**Comment by Greywolf59** [comment]
I don't see a screenshot with your mace equipped. Or just buy some white mace from vendor without expertise to test it. Fist weapons are considered "unarmed" so that's why your unarmed expertise stays at 19 most likely.

**Comment by Ljepoja** [comment]
I think this might just be some visual bug, on 2nd picture expertise should be 19 which is correct, but on 3rd picture there is no axe equipped and expertise should be 14. When i equipped items that dont give expertise rating, that expertise is stuck on 19, but when i equipped [Inevitable Defeat] and unequipped it the expertise is 14 which is correct and should also be like that on 3rd picture. Screenshots when mace is equipped and unequipped: 
![WoWScrnShot_061924_094945](https://github.com/gamefreedomgit/Frostmourne/assets/74017238/7904af92-0407-4568-997c-f26ef6a00ea9)
![WoWScrnShot_061924_094950](https://github.com/gamefreedomgit/Frostmourne/assets/74017238/e11b7ae8-2e5b-44dd-bd99-bbac546c9dcd)
