### ISSUE TITLE
[COS] Mal'ganis/Arthas

### ISSUE THREAD

**Issue by disruption01** [gamefreedomgit/Frostmourne#978]
If we click on arthas to move on (into malganis room) , ignore him and go kill the other (timed) boss when we come back they are fighting endless and can't die (doors are locked so we can't even move in)

**Comment by Godmatik** [comment]
Arthas always heals himself to full on very low cooldown, not possible for him to ever die

**Comment by UltraNix** [comment]
Fixed.
