### ISSUE TITLE
Amish Wildhammer

### ISSUE THREAD

**Issue by Aeradel** [gamefreedomgit/Frostmourne#981]
Amish Wildhammer has issues with not allowing flights (Hellfire Peninsula).

Tested on several different characters, addons disabled and enabled. 

I've had players use other flight paths and come back in case it's a lack of known flight paths, and it's not. It just doesn't provide the ability to fly - only dialog. Some can use and some can't.

https://github.com/TrinityCore/TrinityCore/issues/2596

**Comment by Afgann** [comment]
fixed
