### ISSUE TITLE
Hunter ability "Eyes of the Beast" despawns pet after ending

### ISSUE THREAD

**Issue by Karsenity** [gamefreedomgit/Frostmourne#982]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** After cancelling "Eyes of the Beast" using the "Leave Vehicle" button at the end of the actionbar, the hunter's pet dismisses immediately

**How to reproduce:** Use Eyes of the Beast and cancel it using the "Leave Vehicle" option on the actionbar

**How it should work:** The pet should remain summoned when the spell ends

**Database links:**

**Comment by Karsenity** [comment]
Some additional information: this is only happening when using an addon that replaces actionbars such as ElvUI. The default UI provides an ability with the same icon with the tooltip "Cancel", however when using an actionbar replacement it instead gives access to the ability "Leave Vehicle". 

![image](https://github.com/gamefreedomgit/Frostmourne/assets/48289014/0c231157-0121-4fd5-bdd3-7cad93e26b2b)

![image](https://github.com/gamefreedomgit/Frostmourne/assets/48289014/10539ec7-ed53-4a34-894f-35c2011f3a74)

**Comment by Karsenity** [comment]
I found the cause, the API command `PetDismiss()` is instantly dismissing pets. This can be replicated by typing `/run PetDismiss()` into the game, even without using eyes of the beast.

**Comment by Afgann** [comment]
fixed
