### ISSUE TITLE
Feign death visual bug

### ISSUE THREAD

**Issue by hunturd69** [gamefreedomgit/Frostmourne#984]
feign death sometimes having visual bug of not showing its cooldown after being used it will matter in pve situations when you are about to get aggro on boss/mob and whatever and it will most definetely WILL matter in pvp when you dont know whether its off cd or not when you are bout to have chaos bolt/lava burst getting casted on you

**Comment by WhitemaneIsa** [comment]
As there has been no further info/complaints, this will be closed for now.
