### ISSUE TITLE
Jabbey Restock

### ISSUE THREAD

**Issue by Zeckcell** [gamefreedomgit/Frostmourne#985]
**Description:** i lf a cooking guide and i found this one: https://www.wow-professions.com/wotlk/cooking-leveling-guide-wotlk-classic
I already ussed the guides here to lvl up other profesions and its really accurate. One of the recipes needed in this guide is: https://www.wowhead.com/wotlk/item=16767/recipe-undermine-clam-chowder#comments
This recipe should be sold by Jabbey on the East side of Tanaris, on the little harbor. Well, the comments on wowhead says that this recipe appears on the loot table of jabbey every 30 minutes. I spended more than an hour there clicking on him and w8ing, and the recipe, never appeared.

**How to reproduce:** Go to East side of Gadgetzan Tanaris, on the coast, talk to Jabbey and check item table.

**How it should work:** "As some ppl """"said"""" on wowhead comments", the recipe should appear once every 30 minutes. Its not an important recipe, its just for leveling up cooking, and can be skipped by cooking other things instead of this. Thats why i thought that it should appear quick.

**Database links:**

https://www.wowhead.com/wotlk/item=16767/recipe-undermine-clam-chowder#comments

**Comment by Afgann** [comment]
fixed
