### ISSUE TITLE
Low Fishing School Banks

### ISSUE THREAD

**Issue by Zeckcell** [gamefreedomgit/Frostmourne#986]
**Description:** I have cooking at 295 and i have 3 recipes to get to 300. I confirmed that 2 of them cannot be cooked to get to 300 cuz the fishes of the links i will post down there dosnt appear on the map as fishing school banks. I already spended 1h lf them on Azshara and Deathpass already. And i tryed to get them by fishing on the normal water or other fishing school banks and they didnt appeared. Also, i have fishing skill at 334 and im always using Bright Baubles: +75 fishing skill.

**How to reproduce:** Go to Azshara or Deathpass with "Find fish on minimap activated" and u will not find ANY school bank of Darkclaw Lobsters or either Raw Whitescale Salmon.

**How it should work:** You should find some (idk exactly which ammount of) fishingh school banks around the maps i mentioned. And u should be able to detect them on minimap with Find Fish.

**Database links:** 

https://www.wow-professions.com/wotlk/cooking-leveling-guide-wotlk-classic
https://www.wowhead.com/wotlk/item=13889/raw-whitescale-salmon#fished-in;0+9-8+1
https://www.wowhead.com/wotlk/item=13888/darkclaw-lobster

**Comment by disruption01** [comment]
use this database for reference not wowhead, evowow is private server database, some stuff was changed on wotlk classic so it wouldnt be a perfect match for a private server

open these links and check if you tried to find those schools in the areas below
https://wotlk.evowow.com/?item=13888
https://wotlk.evowow.com/?item=13889

**Comment by Zeckcell** [comment]
In that database the salmon seems not to be on deathpass, but the darkclaw should appear on bay of the storms in azshara, and i didnt saw any, and i swim around and a GM came to me and look for them and couldnt found any also.

**Comment by Aeradel** [comment]
I can confirm, the fishing pools are scarce, and even the pools that exist have extremely low drops rates on fishes required for cooking. I.e. the Darkclaw Lobster. Even with the proper fishing equipment and skill, the poster wasn't able to get a single one after an hour of fishing in pools.

**Comment by UltraNix** [comment]
Fixed.
