### ISSUE TITLE
Unholy DK pet Ghoul is not benefitting from Bloodlust/Heroism

### ISSUE THREAD

**Issue by Sylanha** [gamefreedomgit/Frostmourne#987]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Unholy DK pet Ghoul is not benefitting from Bloodlust/Heroism.

**How to reproduce:**
Create a DK with the Unholy Talent "Master of Ghouls" and have ONLY THE GHOUL  get the Bloodlust/Heroism Buff WITHOUT THE DK ( Master). Just have the sated debuff before summoning a new ghoul. You will see the Ghoul is getting the buff (visually) , but it is not benefitting from it.

**How it should work:**
As with other haste buffs, the ghoul should be double dipping aswell with Bloodlust/Heroism. I will showcase it with the windfury totem buff in a video provided by me. Here, the ghoul is getting 16% meelehaste itself without the Player/Master itself without the Player/Master in the effected totem area. The moment the Player/Master enters the effected totem area, the ghoul benefits again from the totem buff (double dipping) which isnt working with Bloodlust/Heroism.

**Database links:**
https://youtu.be/qbELknMJtBA

**Comment by Afgann** [comment]
fixed
