### ISSUE TITLE
Army haste scaling not working properly/capped

### ISSUE THREAD

**Issue by Sylanha** [gamefreedomgit/Frostmourne#988]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Army is not scaling properly with haste (Windfury or Bloodlust/Heroism). There seems to be a capped or weird haste scaling with Army of the Dead.

**How to reproduce:**
As a Deathknight, get into a group with a shaman and test it with:
1. 0 Haste gear
2. Normal Gear (270 Haste) + Windfury
3. Normal Gear (270 Haste) + Bloodlust
4. Normal Gear (270 Haste) + Bloodlust + Windfury

**How it should work:**
Army should scale with strength, stamina and haste converting into strength, stamina and attackspeed, respectively.
Army should be able to snapshot haste properly and not stop random at aprox. 300 meelehits. The haste scaling should not be capped or acting weird.
I tested it myself in a video that I will provide below. I also tested it months ago with a ridiculous amount of haste (2000+ more haste than in the video below) and it did the same aka did not go beyond 300ish meelehits.

In addition:
The ghouls only take 10% damage (90% damage reduction) from area of effect spells, even without the Night of the Dead talent (that talent gives your personnal ghoul (pet given from Master of the Ghouls) the same area-of-effect damage reduction), meaning they'll be fine even by staying near any NPC using a nova-like spell.

**Database links:**
https://youtu.be/tB5VhgQLxjg

**Comment by Afgann** [comment]
fixed
