### ISSUE TITLE
Hunter Spell Explosive Shot and downranks overlapping

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#99]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Downranked explosive shots are overriding/overlapping the previously casted explosive shot.

**How to reproduce:**
Proc Lock n Load and try to cast different ranks right after each other. ( 4>3>4 )

**How it should work:**
Different ranks should have different spell ids and different debuffs and thus not overlap as they current do

https://www.wowhead.com/wotlk/spell=56344/lock-and-load#comments:id=993102

https://www.youtube.com/watch?v=oapdS8BUCh0&ab_channel=VeramosGaming

to cite :
Patch 3.3.2

Just tested this with recount. When LnL procs you can cast explosive shot(rank 4) explosive shot(rank 3) explosive shot(rank 4) and it will get all 9 ticks and it does more damage than an explosive shot(rank 4) spam. Very handy when you need that big burst of damage and every second counts.

**Database links:**
https://wotlk-twinhead.twinstar.cz/?spell=60053

**Comment by Afgann** [comment]
fixed
