### ISSUE TITLE
BG Flag Carrier Kicked

### ISSUE THREAD

**Issue by Aeradel** [gamefreedomgit/Frostmourne#991]
It's been a persistent issue I haven't been able to find the cause of.

Players hold the flag and then are removed from the battleground, being given deserter.

I've only witnessed it once, and the player had died and was instantly removed - although I'm not sure dying is the direct cause.

**Comment by UltraNix** [comment]
And not being afk?

**Comment by Aeradel** [comment]
> And not being afk?

Correct.

I have verified this in person. I watched a player carrying the flag - with no inactivity debuff as is typical of AFK kicks - running in the middle of the battleground to their side, die, and get immediately removed and penalized.

I can't speak for every occurrence, but there have been reports of this happening - although I have not solidified that dying is the root cause.

**Comment by UltraNix** [comment]
Fixed.

**Comment by WhitemaneIsa** [comment]
> Fixed.

U sure? it seems to still happen.

**Comment by UltraNix** [comment]
@WhitemaneIsa Need more info needed on this.

**Comment by WhitemaneIsa** [comment]
> @WhitemaneIsa More info needed on this. Flag carrier cannot be kicked from BG (via AutoKick system).

Not specifically flag carrier, in general randomly people complain to get removed after being gone for less than 2 minutes. Even if they were mass reported, they should not be removed this quickly.

**Comment by WhitemaneIsa** [comment]
No further info/complaints, closing.
