### ISSUE TITLE
Scripting issues with quests

### ISSUE THREAD

**Issue by Seren79** [gamefreedomgit/Frostmourne#994]
Hello, I've noticed scripting on several quests is missing e.g. if an NPC is meant to do/say something outside of the quest box. An example of this is the Alien Egg quest in Thousand Needles where the wind serpent does not appear once you complete the quest. No biggie, as most of us have played this game multiple times over, but wanted to flag that certain things are clearly not working as they usually should.

**Comment by WhitemaneIsa** [comment]
Please provide a proper bug report per quest you notice this on.
