### ISSUE TITLE
Permanent Aura Mastery Bonus

### ISSUE THREAD

**Issue by CpkWoW** [gamefreedomgit/Frostmourne#995]
**Description:**
Permanent Aura Mastery Bonus

**How to reproduce:**
As paladin use aura mastery, then a druid has to use cyclone on you if the AM expires before the cyclone you will see that you, and your group/raid, keep the bonus.

**How it should work:**
U should lose the bonus after AM expires

**Database links:**
https://www.wowhead.com/wotlk/spell=31821/aura-mastery
https://www.wowhead.com/wotlk/spell=33786/cyclone

**Comment by Dalvae** [comment]
https://www.mediafire.com/file/gyacclxbongm3at/2024-06-18_15-16-02.mkv/file

I can confirm. Here are the tests.

**Comment by Manpower99** [comment]
same issue occured on Maelstrom back when it was first released.
can confirm it on ptr and live server

**Comment by UltraNix** [comment]
Fixed.
