### ISSUE TITLE
Herald Volazj - Twisted Visage

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#996]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
On Insanity cast, the player copies sometimes do normal damage 500-1000 melee on plate.
Other times they melee hit 5-6k on plate and 7-8k on leather, killing people almost instantly.

**How to reproduce:**
Random on which insanity they get buffed for no reason.

**How it should work:**
As the first line of the report not like the second

**Database links:**

**Comment by sputnikk** [comment]
Some people have reported the twisted visages hitting even harder after the fix in the changelog today.

**Comment by Afgann** [comment]
fixed
