### ISSUE TITLE
Bug un Dk unholy scourge strike glyph and Epidemic talent

### ISSUE THREAD

**Issue by Thickskull** [gamefreedomgit/Frostmourne#998]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When playing Dk using  the scourge strike Glyph and Epidemic Talent together they cause the following bug; scourge strike glyph does not give the +3 seconds, puts a weird cap ignoring the epidemic talent and capping both of your dots at max duration(15 sec) ignoring the epidemic talent wich increases the max duration to 21, 

**How to reproduce:**
Create a Dk use Epidemic talent to increase by 6 seconds the duration of your dots, then use glyph of scourge strike with increases your dots duration by 3+ seconds everytime you use it, then you will see the bug

https://www.youtube.com/watch?v=UKExLnyZr0E

**How it should work:**
You use epidemic talent to increase the dots duration to 21 secs  and everytime you use scourge strike with the glyph it should increase the duration +3 seconds with a maximum of 9 aditional seconds granted by the glyph at the same time

**Database links:**
https://www.wowhead.com/wotlk/spell=58723/glyph-of-scourge-strike

**Comment by Afgann** [comment]
fixed
