### ISSUE TITLE
[item] Damaged Necklace

### ISSUE THREAD

**Issue by looniegg** [gamefreedomgit/Frostmourne#999]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Abandoning Damaged Necklace quest deletes it from inventory.

**How to reproduce:**
Start quest, abandon it.

**How it should work:**
It should remain in inventory.

**Database links:**
https://wotlk.evowow.com/?item=43297

**Comment by UltraNix** [comment]
https://www.wowhead.com/item=43297/damaged-necklace#comments:id=474422:reply=519011
Not a bug.
